### ISSUE TITLE
[Suggestion] Explicit Required Named Arguments

### ISSUE THREAD

**Issue by masters3d** [dotnet/csharplang#1005]
I'd like to require certain arguments to be called with a name argument label. 

Currently I can sort of fake this requirement by providing a dummy optional parameter as the first parameter when all the arguments are optional.

```C#
        // I want to force the caller to use a named paramerter label so please excuse the __paramLabelRequired__
        public void UpdateScreen(int __paramLabelsRequired__ = 0, bool showingTitle = true)
        {...}
```

This is how I must call this now. 
```C#
view.UpdateScreen(showingTitle: false);
```

The below will not work because of the dummy first optional argument and this is intentional.
```C#
view.UpdateScreen(false);
```

This would work though: 

```C#
view.UpdateScreen();
```

It would be awesome if I could require a name argument like this:

```C#
        public void UpdateScreen( bool @required showingTitle)
        {...}
```
or something like this. 

```C#
        public void UpdateScreen( bool showingTitle showingTitle)
        {...}
```
alternatively if could be added to the method. 

```C#
        @requiredNameArguments
        public void UpdateScreen( bool showingTitle)
        {...}
```

Currently I am not able to require it in non optional arguments which is where I would want this to work.

The advantage is that the named argument would be required at the call site thus giving more meaningful information to the caller on what the parameters do at a glance. 

This could work after this is implemented: https://github.com/dotnet/csharplang/issues/518

**Comment by svick** [comment]
This sounds like it could easily be accomplished by an analyzer. The parameter or the method would have an attribute, e.g.:

```c#
public void UpdateScreen([RequireNamedArguments] bool showingTitle)

// or

[RequireNamedArguments]
public void UpdateScreen(bool showingTitle)
```

The analyzer would then find all calls of methods with the attribute and produce a diagnostic if the call didn't use named arguments.
