### ISSUE TITLE
get/set Expression bodied properties

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1007]
Allow to get and set with expression Bodied properties

```
public int X <=> point.X;
```
Equivalent to

```
public int X
{
    get => point.X;
    set => point.X = value;
}
```

Could be used for indexers too.

```
public int this[int index] <=> _source[index]; 
```

Equivalent to 

```
public int this[int index]
{
    get => _source[index];
    set => _source[index] = value;
}
```

----

Notes to consider 

 - expression must be a valid l-value **and** r-value (as suggested by @benaadams)

**Comment by Logerfo** [comment]
>`int Foo <=> bar = baz = qux; // sets all values.`

and returns...?

**Comment by DavidArno** [comment]
I initially upvoted this as a simple idea for mapping read/write properties to some value other than the default backing field. But I've removed that upvote as your "*Notes to consider*" addendum just muddy the proposal.

Keep it simple:
1. For property, `x <=> item`, `item` can be a (non-readonly) field or a read/write property,
2. For indexer, `this[int index] <=> item`, `item` must be another indexer.

**Comment by benaadams** [comment]
@DavidArno More explicit on the indexer?
```
this[int index] <=> item[index];
this[int index] <=> item[_offset + index];
```

**Comment by MkazemAkhgary** [comment]
@Logerfo returns what `=> x = y = z;` returns. 

@DavidArno indeed, i tried to expand usage in conjunction with get only properties. Chained assignments could be prevented. Its not something i do usually, in fact i never did it.

**Comment by MkazemAkhgary** [comment]
@benaadams i liked that but what if item is jagged array `int[][]`?

Then it has to be either explicit like what you suggest or implicit `item`.

I guess explicit version pays off more.

**Comment by Logerfo** [comment]
@MkazemAkhgary in C#, multiple assignments returns the rightmost value of the chain. In your examples, `qux` or `z`, but that can be really confusing. I see you already remove that from the notes, so we don't need to proceed with this discussion.

**Comment by benaadams** [comment]
>  i liked that but what if item is jagged array int[][]?

Defined via type, an array is still a single item
```csharp
private int[][] item;

public int[] this[int index] <=> item[index];
```
or the other type
```csharp
private int[,] item;

public int this[int i1, int i2] <=> item[i1, i2];
```

**Comment by benaadams** [comment]
I think it just needs to be

"expression must be a valid l-value and r-value"

i.e. valid on both sides of an equals

For example it could happily be a `ref` returning function so for example given
```csharp
private int[] items;

private ref int FindEntry(int index)
{
    // ...
}
```
This
```csharp
public int X
{
    get => FindEntry(0);
    set => FindEntry(0) = value;
}

public int this[int index]
{
    get => FindEntry(index);
    set => FindEntry(index) = value;
}
```
Could be converted to
```csharp
public int X <=> FindEntry(0);

public int this[int index] <=> FindEntry(index);
```

**Comment by Logerfo** [comment]
Another possibility is to use just the `=>` syntax and change its behavior to act like you propose, now allowing the `readonly` modifier on properties to behave the way the operator does today. That would change existing properties, but I don't know how big deal that would be.

**Comment by benaadams** [comment]
> That would change existing properties, but I don't know how big deal that would be.

Would be a significant breaking change as all current simple readonly properties would suddenly become read/write e.g.

```csharp
private int _x;

public int X => _x; // now read/write, was readonly before
```

**Comment by Logerfo** [comment]
@benaadams Since the assignment is not possible today, that change would not actually break anything, as it's more kind of a relaxation. It can break analyzers, but anything can. I think it would only break reflection/cecil for properties like `IsWriteable` or `IsReadonly`, which would have different values due to this change.

**Comment by MkazemAkhgary** [comment]
@Logerfo for properties that have complex expressions, they becomes get only properties. so whether property will be readonly or not would become vague.

 `=> 1 + 2` is impossible to be writable.

**Comment by benaadams** [comment]
@Logerfo hmm true; but it would also mean everyone who had written an readonly property would then have to change/audit their code to keep the properties readonly

**Comment by MkazemAkhgary** [comment]
@benaadams very good explanation. that is more general, updated.

**Comment by MohammadHamdyGhanem** [comment]
I suggest this instead of `<=>`:
```C#
public int this[int index] using _source[index]; 
```

#2291

**Comment by Happypig375** [comment]
That syntax deviates too much from `=>`. It looks too different from `=>`.
