### ISSUE TITLE
[Proposal] Non returning method return type

### ISSUE THREAD

**Issue by vcsjones** [dotnet/csharplang#1011]
A common thing in many projects are methods that do nothing but `throw` as a helper. Either so they can get a localized string,.  Consider this poorly made search method:

```csharp
public int NaiveFindIndex(string find)
{
    for (var i = 0; i < collection.Count; i++)
    {
        if (collection[i] == find)
            return i;
    }
    ThrowHelperItemNotFound();
    return default;
}

private static void ThrowHelperItemNotFound()
{
    var message = GetLocalizedMessage("ITEM_NOT_FOUND");
    throw new LocalizedException(message);
}
```

The `return default` is necessary because the compiler is not aware that `ThrowHelperItemNotFound` throws an exception. If I were inline the method, then the `return default` is not necessary.

Another issue besides return is definite assignment analysis:

```csharp
public int SillyPermissions(string permissionName)
{
    PermissionEnum permission;
    switch (permissionName)
    {
        case "read":
            permission = PermissionEnum.Read;
            break;
        case "write":
            permission = PermissionEnum.ReadWrite;
            break;
        default:
            ThrowHelperInvalidPermission();
            break;
    }
    DoSomethingWithPermission(permission);
}
```

This example will not compile because the `default` case is not known to assign to `permission`. If the `default` case were to throw an exception directly, the `break` would not be needed, and `permission` would be definitely assigned when called at `DoSomethingWithPermission`.

# Proposal

I propose introducing a new return type or indicator that declares the method as non-returning. Something like:

```csharp
private static void! ThrowHelperItemNotFound()
{
    var message = GetLocalizedMessage("ITEM_NOT_FOUND");
    throw new LocalizedException(message);
}
```

Because a compiler could now be made aware that the method definitely doesn't return, the `return default` in the above example could be eliminated. A compiler implementation should verify that the method does, in fact, never "return".

# Implementation Suggestion

I would propose that the method actually be `void` with an attribute annotation:

```csharp
[NonReturningMethod]
private static void ThrowHelperItemNotFound()
```

A compiler that is consuming one of these methods would also throw an `UnreachableException` after the consumption to keep the method IL verifiable. So the call will be lowered to something like:

```
ThrowHelperItemNotFound();
throw new UnreachableException();
```

# Compatibility

If a compiler is unaware of one of the `[NonReturningMethod]` attribute, then it will see it as a `void` method exactly as it does today.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/538

**Comment by vcsjones** [comment]
[sigh] I'm really bad at finding existing proposals. Thanks @ufcpp

**Comment by HaloFour** [comment]
@vcsjones 

Don't sweat it.  There are a bunch of them and unless you know the exact terminology of the previous proposals it can be hard to find them.  Even when I recall that something has already been proposed or perhaps discussed in the comments of another proposal it can be a real bear to actually find that to cite it.
