### ISSUE TITLE
Local functions extension method

### ISSUE THREAD

**Issue by jcouv** [dotnet/csharplang#1024]
@UnoSD commented on [Sun Feb 05 2017](https://github.com/dotnet/roslyn/issues/16959)

Will local functions support being used as extension methods?

It could be useful to make code more readable and not clutter the type.

---

@svick commented on [Sun Feb 05 2017](https://github.com/dotnet/roslyn/issues/16959#issuecomment-277521910)

[It seems they currently can't.](http://tryroslyn.azurewebsites.net/#b:master/f:r/M4FwhiCWDGAE0BszGLAwgKAN4dn2oEMsAbgPaQAmsAsgBQCUu+O+bpF1AonSABaRUZAEYArAKbQQsMg1hYAvszxKFQA=) This code:

```c#
static class C
{
    static void M()
    {
        void E(this object o) {}
    }
}
```

Produces this not quite clear error message:

> error CS1106: Extension method must be defined in a non-generic static class

Though maybe this can be reconsidered as part of https://github.com/dotnet/roslyn/issues/16271.

---

@jcouv commented on [Sat Oct 21 2017](https://github.com/dotnet/roslyn/issues/16959#issuecomment-338449053)

I'll move this discussion to csharplang, as it is not currently actionable as a compiler bug (current behavior is by design).

**Comment by MkazemAkhgary** [comment]
what is the benefit of having local extension methods?

extension methods are already cluttered, be it local or global, it does not matter. its implementation is separate from type.

**Comment by Logerfo** [comment]
Dupe of https://github.com/dotnet/csharplang/issues/850?

**Comment by jcouv** [comment]
Indeed dupe of #850. Closing.
Thanks
