### ISSUE TITLE
GUI Issue with Object Initializer

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#1038]
Not sure where to put this so I'm putting it here.

````
       //Put this class
        public class OnlyGets {
            public string[] First { get; } = new[] { ""};
            public long[] Second { get; } = new[] { 0L };
        }

            var C = new OnlyGets() {
              //When you create one like this, First and Second both show up as suggested autocompletes but you can't do anything with them.  Shouldn't they not be listed at all?
            };

````

**Comment by HaloFour** [comment]
@TonyValenti 

Belongs on Roslyn, that's where questions/bugs regarding the implementation of the compiler and the tooling goes.

Readonly properties can participate in object initialization via collection initializers.  Arrays can't normally participate in those without an extension method (that wouldn't make much sense but would be syntactically legal).  I assume Intellisense isn't doing the work to figure out if the target type wouldn't support a collection initializer before making the suggestion, though.

**Comment by svick** [comment]
The fixed issue https://github.com/dotnet/roslyn/issues/13158 is almost the inverse of this one. Its fix (https://github.com/dotnet/roslyn/pull/20726) seems to check whether the type or *an interface it implements* has an `Add` method. And array does have that, `T[]` implements `IList<T>`, which has `Add(T)`. But array implements it implicitly, so `new OnlyGets() { First = "" }` doesn't actually compile. I think that check should be modified to account for implicit interface implementations.

**Comment by svick** [comment]
@TonyValenti Since you created https://github.com/dotnet/roslyn/issues/22816, do you want to close this issue?
