### ISSUE TITLE
allow fixed and stackalloc expressions to be used with conditional assignment.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1040]
What I want to do is really impossible without duplicating code for each branch. ideally here is what I want to do.

    Range* ranges; // pointer to a temporary array.

    // if array length is small allocate it on stack
    if (length < 50000)
    {
        var alloc = stackalloc Range[length];
        ranges = alloc;
    }
    else // possibly cant fit on stack, use pointer to fixed array.
    {
        // really really wrong, because nothing is fixed after this line.
        fixed (Range* x = &(new Range[length])[0]) ranges = x;
    }

I'm not sure what features are required for this. how ever following is not possible.

    Range* ranges;
    ranges = stackalloc Range[length]; // some syntax error.

It seems `stackalloc` is very special syntax. but why should it be not allowed to be used as part of expression? 

The other feature I need is this. having `fixed` as expression

      {
          Range* ranges = fixed(&(new Range[length])[0]); 
          //...
      }

and managed object should remain fixed until end of current block is reached. 

Then with these features, I will be able to do following.

     Range* ranges = length < 50000 ? stackalloc Range[length] : fixed(&(new Range[length])[0]);

and happily use ranges which is conditionally stack allocated or not.

**What can be fixed easily**

I don't see why `stackalloc` cant be used inside expression (and has to be really whole declaration and assignment statement). I doubt this will be hard for c# team to solve this.

**What may be a challenge**

having `fixed` expression that will fix managed object for rest of current block. 

**How can I solve this**

write exact duplicate code for each branch.

**Comment by svick** [comment]
The work being done on `Span<T>` and safe `stackalloc` for C# 7.2 might make this easier to implement.

With C# 7.1, the code you want to write (`Range* ranges; ranges = stackalloc Range[length];`) indeed  produces some syntax errors:

> error CS1525: Invalid expression term 'stackalloc'
> error CS1002: ; expected
> error CS1513: } expected

But on C# 7.2 (nightly build from MyGet), the error is different:

> error CS8346: Conversion of a stackalloc expression of type 'Range' to type 'Range*' is not possible.

---

In fact, safe `stackallloc` might actually be the solution here. This code works for me in C# 7.2 nightly:

```c#
Span<Range> ranges;

if (length < 50000)
{
	ranges = stackalloc Range[length];
}
else
{
	ranges = new Range[length];
}

// use Span<Range> directly or convert to a pointer:
fixed (Range* ptr = &ranges.DangerousGetPinnableReference())
{
}
```

**Comment by alrz** [comment]
You could also use ternary for that
```cs
var ranges = length < 50000 ? stackalloc Range[length] : (Span<Range>)new Range[length];
```

**Comment by MkazemAkhgary** [comment]
@alrz @svick interesting, I have to update VS to get 7.2, currently I have 7.1 max. problem solved. I guess this thread can be closed then.
