### ISSUE TITLE
Should silent language version upgrade be desirable?

### ISSUE THREAD

**Issue by gulshan** [dotnet/csharplang#1043]
From C# 7, we hope that the .csproj file format is not going to change much. It does not contain the tools version and the language version by default. The default language version is also `default` which means the last "major" version of the language. So, when C# 8.0 will be published, projects with this default language version will be compiled against C# 7.0 or C# 8.0 (which includes all the minor 7.x versions) based on the tools installed in the machine it is being compiled. I know that the language version upgrade will not a breaking change. But should it not be explicit? If 7+ features are to be used in a project with default langversion, I think the best strategy will be to make the langversion explicit in the csproj. Then all devs and CI admins will know they have to upgrade the tools instantly. Else one dev with upgraded tools can break the code for others. This will be more of a problem in open source projects in my opinion.

And the complier always supports the previous versions of the language, independent of the current tools version. So, supporting langversion 7(or lower) will not be a problem with later compiler tools.

**Comment by yaakov-h** [comment]
Two things: 

1. This is probably the wrong place for this discussion - dotnet/sdk is probably more appropriate.

2. I don't really see an issue with the current defaults. If you have good CI practices, you'll notice the build failing with a C#7 compiler and C#8 code and fix it before it gets checked in to `master` or `trunk` or whatever your mainline branch is.

    If you know there's a big upgrade coming to your company, you can lock `<LangVersion>` to `7.0` ahead of time, then remove it after the upgrade - or keep it around as `8.0`.

    If one developer with newer tools "can break the code for others", that means that a developer with current tools can also do this. If so, you have bigger organisational issues than a single XML tag in a project file.

**Comment by gulshan** [comment]
Not that it's unmanageable. But may become inconvenient. In all previous C# version upgrades, csproj files also got upgraded, at least in the tools version. Most probably it will not be the case for the first time in C# 8.

**Comment by jnm2** [comment]
Being limited by tools to the lowest common denominator is as understandable as any other dependency chain, like having to support net40. What I think is an antipattern is tying the source or project files to a particular tool or version of that tool. They shouldn't constantly reflect the version of the latest tool you used with it. Reflecting just the practical LCD is better. (Which LangVersion does well.)

**Comment by gulshan** [comment]
Ok, the default LangVersion has been changed- https://devblogs.microsoft.com/dotnet/an-update-to-c-versions-and-c-tooling/
>When no LangVersion is specified, the default meaning is now determined by the target framework of your project. When you target a preview framework that also has a corresponding preview C# version, that preview version is the default. If you do not target a preview framework, then **Latest** is chosen.
