### ISSUE TITLE
Proposal: Allow iteration variables to be `ref` in `for` and `foreach` loops

### ISSUE THREAD

**Issue by agocke** [dotnet/csharplang#1046]
Currently, the iteration variable of a `foreach` is not allowed to be a `ref` variable, and it's not allowed to declare a `ref` variable in the initialization section of a `for` loop. It's proposed that ref variable declaration in these places be allowed.

* [X] Proposal added
* [ ] Discussed in LDM
* [ ] Decision in LDM
* [ ] Finalized (done, rejected, inactive)
* [ ] Spec'ed

**Comment by cpplearner** [comment]
#461, #924

**Comment by yaakov-h** [comment]
BTW, I don't think this Issue counts for "Proposal added" - you need an [actual proposal document](https://github.com/dotnet/csharplang/tree/master/proposals) for that.

**Comment by scalablecory** [comment]
I think this is a bit more complex than it seems on the surface level, because `IEnumerable` is read-only. It would need new pattern matching rules and probably some sort of `IMutableEnumerable` interface.

**Comment by HaloFour** [comment]
@scalablecory 

> I think this is a bit more complex than it seems on the surface, because `IEnumerable` is read-only. It would need new pattern matching rules and probably some sort of `IMutableEnumerable` interface.

The compiler could support it today when using `foreach` over arrays or over a type that follows the enumerable convention where `Current` does return a `ref`.  Beyond that it would need another pair of interfaces where `Current` could be defined as `ref`.

**Comment by HaloFour** [comment]
Actually looks like the compiler already handles the enumerable convention when the `Current` property is declared to return a `ref`.  The compiler consumes the reference fine and ensures that it's only dereferenced once, but prevents it from being mutated directly, assigned to a `ref` local or passed to a `ref`/`out` parameter.  If the iterator variable could be declared as `ref` the compiler could relax those restrictions and allow direct mutation.

**Comment by gafter** [comment]
This proposal is being treated as part of #933

**Comment by jcouv** [comment]
Closing this, since subsumed by https://github.com/dotnet/csharplang/issues/933

Btw, @agocke the [speclet](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/ref-local-reassignment.md) for ref re-assignment doesn't mention `ref` in `for` and `foreach`. Can you update?
