### ISSUE TITLE
Feature Request: LINQ .foreach method for Enumerable not only for lists

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/csharplang#1053]
Currently, the` .foreach` method ([see this for further Information](https://msdn.microsoft.com/en-us/library/bwabdf9z(v=vs.110).aspx)) is only for `List<T>`, but it would make sense to make it for `Enumerable<T>` like other similar LINQ Expressions ([as example](https://msdn.microsoft.com/en-us/library/bwabdf9z(v=vs.110).aspx)).

**Comment by HaloFour** [comment]
Requests to add new methods to the base class library are better proposed on the [CoreFX repository](https://github.com/dotnet/corefx/issues) as it doesn't involve changes to the C# language itself.

**Comment by scalablecory** [comment]
This already exists in the System.Interactive nuget package.

**Comment by Joe4evr** [comment]
[You really shouldn't be using the `ForEach()` method anyway.](https://blogs.msdn.microsoft.com/ericlippert/2009/05/18/foreach-vs-foreach/)

**Comment by svick** [comment]
If you're like me and like *typing* `collection.foreach`, because it reflects well your thought process, you might consider using ReSharper's `.foreach` [postfix template](https://www.jetbrains.com/help/resharper/Postfix_Templates.html). It means you can type `collection.foreach`, but then it creates a normal `foreach` loop.

**Comment by gafter** [comment]
Closing as this is not related to any C# language issue.

**Comment by TheMinefighter** [comment]
,You might be right that this feature is already in a nuget package, or they there are alternatives. I KNOW. On the one hand you can remove the feature, or you could make it work with Enumerable<T> like all other LinQ Expressions, but the current status makes (at least in my eyes) no sense.

**Comment by svick** [comment]
@TheMinefighter You can't remove the feature, that would be a breaking change.
