### ISSUE TITLE
Properties, backing field: another story

### ISSUE THREAD

**Issue by rndfax** [dotnet/csharplang#1059]
Hello!

Properties... backing fields... want to access backing field from property implementations...

I've seen proposals which propose using explicit names for property backing field (like `field` variable or declaring var inside Prop scope or `$field`) but all of them do not solve problems, instead, sometimes, introducing new ones:
1) still need to declare variable to hold the value. It's hard to devise new variable name, when you already named your Property!
```c#
int Prop
{
   int _prop;
// or
// int prop;
// or
// int PropField;
}
```
Stick to your code style you say. But then every property will have `PropertynameField` variable. In all your project. And this will be default for all properties. And programmer must write Property, and then introduce PropertyField variable to work with. Why? This introduction of property-scoped-variable will not have any meaning at all, generally speaking.

2) introduce breaking change with `field` variable. Well, no comments. Breaking is bad.

3) introduce foreign to c# syntax with dollar signed variables (`$field`). No comments either.

It's better to extend things by using previously forbidden syntax.

```c#
int Prop
{
    get
    {
        return; // Call default property implementation which returns value of the hidden backing field
// Now it's: error CS0126: An object of a type convertible to 'int' is required
    }
    set
    {
        set; // Call default property implementation which will set `value` to the hidden backing field
// Now it's: error CS0103: The name 'set' does not exist in the current context
// If we have variable `set` it still generates error:
// error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement
    }
}
```

On IL level nothing will be changed (from layout point of view), it still will be using these guys to implement "call default property implemetation":
```
  .field private int32 '<Prop>k__BackingField'
...
    IL_0002:  stfld      int32 prop.Program::'<Prop>k__BackingField'
...
    IL_0001:  ldfld      int32 prop.Program::'<Prop>k__BackingField'
...
```

Some example of proposal:
```c#
int Prop
{
    get
    {
        Console.Write("DEBUG: Prop.get method called\n");
        return;
    }
    set
    {
        Console.Write("DEBUG: Prop.set method called\n");
        set;
        if (Prop == value) // dummy check :)
            Console.Write($"Prop has been set to {value}\n");
    }
}
```

#### Why `set;` and `return;` syntax is possible and logical in properties

Properties already have special syntax and special reserved `value` variable with special meaning. So it's okay to endow `set;` and `return;` with special meaning in property scope.
Empty `return;` (like just regular `return;` from the method with void) for `get` part of property is not strange because "we do not have void properties, and returning nothing is not possible by design". So you have two choices: `return expr;` and `return;`. The latter returns "the value of the Property itself" - the value stored in hidden backing field.
The `set;` of `set` part of property is not strange because it logically implies that you intend to "set (assign) value to the Property itself" - store the value to the hidden baking field.

PS. Instead of `set;` can be used better command like `storeValue;` which does what it says into baking field of the property. Or `latch;`...

**Comment by jnm2** [comment]
Sorry @rndfax, you have a good idea, it's just that #140 (`field keyword) is the gold standard as far as I'm concerned. It handles all the examples I've thrown at it with the most elegance.

**Comment by bondsbw** [comment]
Under this proposal, accessing the backing field requires evaluating the `get`:

> ```c#
> if (Prop == value) // dummy check :)
> ```

This causes extra code to run, which is the case in your example.  The output of setting the value of `Prop` will contain:

```
DEBUG: Prop.set method called
DEBUG: Prop.get method called
```

**Comment by bondsbw** [comment]
This example is confusing however, because the equality check is _after_ `set;` and therefore is always `true`.

**Comment by svick** [comment]
How can the getter return a value different than the backing field? And how can the setter set the backing field to a value other then `value`?

Consider something like (yes having both accessors handle `null` doesn't make much sense):

```c#
private string prop;
public string Prop
{
    get => prop ?? string.Empty;
    set => prop = value ?? string.Empty;
}
```

If similar properties can't use this proposal, then I think that makes it much less valuable.

**Comment by bondsbw** [comment]
Now for my opinions...

I prefer #140 (semi-auto properties) over this proposal.

And this proposal does a very poor job arguing against property-scoped fields (#133) based on how difficult it is to name the field.   _Even the provided example_ (`_prop`) shows how easy it is.

**Comment by rndfax** [comment]
@bondsbw

> Under this proposal, accessing the backing field requires evaluating the get:

Hm, indeed. If you have complex logic in getter and want to read value from property in setter, then it will run extra code.

> This often causes extra code to run, which is the case in your example. The output of setting the value of Prop will contain:

Yes, that was expected, it was the intent of the example.

> This example is confusing however, because the equality check is after set; and therefore is always true.

Yes, it's not just says in comment about 'dummy check'...

**Comment by rndfax** [comment]
@svick

Good catch.

**Comment by rndfax** [comment]
@bondsbw

> difficult it is to name the field. Even the provided example (_prop) shows how easy it is.

It's not just devising the name is a difficult task. Eventually you find yourself in situation where every custom property has identical scoped variable:
```c#
int Prop1
{
int _prop1;
...
string Prop2
{
string _prop2;
...
int Prop3
{
int _prop3;
...
```
.. and so on million times.
Why in the first place this is needed? From this point of view the `field` proposal from #140 seems more elegant, although it's breaks compatibility. That's what I was trying to highlight in disadvantages for property-scoped variables.

**Comment by rndfax** [comment]
Conclusion. This proposal doesn't account cases where it's needed to access raw value of the backing field.

**Comment by Joe4evr** [comment]
> the `field` proposal from #140 seems more elegant, although it's breaks compatibility

How? Contextual keywords are not a new thing to C#. You can use `var` and if there happens to be a type named `var` in scope, it will bind to that type; if not, it binds to whatever type will be inferred from the right-hand side. What makes you think `field` can't follow suit?

**Comment by rndfax** [comment]
@Joe4evr 

May be I'm missing something (or misunderstood you), but I'm relying on this behaviour:
```c#
int Prop
{   
    set 
    {   
        var value = 3;
    }   
}   
```
Generates `error CS0136: A local or parameter named 'value' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter`.
So if some code already declared `field` variable and there will be introduced the new `field` contextual keyword then it won't compile with similar error. Or not?

**Comment by Joe4evr** [comment]
If someone had an identifier named `field` in scope, then it would still bind to that as it would otherwise break back-compat. If *no such* identifier exists, it will gain the behavior of referring ot the auto-generated backing field.

You can try the exact same behavior out *today* using something like this:
```cs
void Foo(Dictionary<int, string> data, int key)
{
    string _; //comment out this line, and look how 'out var _' changes behavior
    if (data.TryGetValue(key, out var _))
        Console.WriteLine("Key existed");
}
```

**Comment by rndfax** [comment]
@Joe4evr I understood your point and yes, I agree with you, that `field` can be worked-around like this to not break anything. But in #140 someone mentioned that it won't compile with plain `field` and they told why, and proposed additional solutions to specify initialization in order to not brake existing code and make the `field` to work as backing field (https://github.com/dotnet/csharplang/issues/140#issuecomment-309876442).

**Comment by bondsbw** [comment]
@rndfax >.. and so on million times.
>Why in the first place this is needed? From this point of view the `field` proposal from #140 seems more elegant

I agree, for those examples.

Named fields in #133 is useful for certain cases where you want to encapsulate data that doesn't fit the type of the property.  E.g. a nullable version of the same type, an initialization tracker (`bool _isInitialized`), a usage counter, a logger, etc.

**Comment by rndfax** [comment]
@bondsbw 

>  Named fields in #133 is useful for certain cases where you want to encapsulate data that doesn't fit the type of the property. E.g. a nullable version of the same type, an initialization tracker (bool _isInitialized), a usage counter, a logger, etc.

Ah, I see now, that the whole #133 is a bit different, it's more general proposal, which _could_ be used to emulate backing fields.

**Comment by bondsbw** [comment]
@rndfax Exactly.
