### ISSUE TITLE
Implicitly hoist scope of variables declared in try-catch blocks (similar to how out variables were improved)

### ISSUE THREAD

**Issue by IanKemp** [dotnet/csharplang#1066]
A common pattern when writing try-catch blocks is the following:

```csharp
string[] foo = null;

try
{
    foo = GetFooInAWayThatMayThrow();
}
catch (Exception ex)
{
    Log(ex);

    return;
}

// can only get here if the try succeeds
DoSomethingWith(foo);
```

`foo` will only ever be populated and used if the `try` block succeeds, otherwise it is untouched. The above (current) syntax is rather verbose and redundant, as `foo` has to be initialized even if we know it'll never be touched due to hitting the `catch` block. (Yes, technically you can access it from the `catch` or a `finally`, but if you need to do that the current syntax is fine.)

A nicer way of writing this would be the following:

```csharp
try
{
    // inferred from return type
    var foo = GetFooInAWayThatMayThrow();
}
catch (Exception ex)
{
    Log(ex);

    return;
}

DoSomethingWith(foo);
```

which would ([similarly to inline out variables](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#out-variables)) result in the following code being generated:

```csharp
string[] foo = default(string[]);

try
{
    foo = GetFooInAWayThatMayThrow();
}
catch (Exception ex)
{
    Log(ex);

    return;
}

DoSomethingWith(foo);
```

**Comment by MkazemAkhgary** [comment]
this is a breaking change
```
try
{
    var foo = GetFooInAWayThatMayThrow();
}
catch (Exception ex)
{
    Log(ex);
    return;
}
var foo = something_else;
```

Also blocks play very important rule for lifetime of variable hence how the program behaves. so nothing should be implicit about variable declarations and blocks.

Apart from that, this proposal is just saving one line. there are other proposals that pack whole thing into one line but still refused by community due to some concerns.

#1015, #980, #616, etc

**Comment by IanKemp** [comment]
> this is a breaking change

Correct - I didn't consider your (admittedly simple) case, probably because I see the use of the same-named variable in different scopes as a code smell and thus would never do something like that.

However there is no reason why the compiler cannot implement simple heuristics to detect cases like this and only apply my hoisting suggestion if the same-named variable doesn't already exist in the parent scope.

> so nothing should be implicit about variable declarations and blocks.
> Apart from that, this proposal is just saving one line.

The implicit out variable feature does the same thing, yet makes so much difference.

> there are other proposals that pack whole thing into one line

Those appear to be quite complex changes with large ramifications, this one would be (relatively speaking) far simpler.

**Comment by MkazemAkhgary** [comment]
>The implicit out variable feature does the same thing, yet makes so much difference.

That's not correct. let me show you.

```
if(dic.TryGetValue(key, out var x)) // this is outside {}
{
     // x is not declared in this block.
}
```

As you can see `x` is explicitly and clearly declared outside `{}`. your proposal how ever:

```
{
    var x ...;
}
```

which translates to

```
var x...;
{
}
```

is misleading.

**Comment by IanKemp** [comment]
Ah, I understand you now. Yes, you are correct. I suppose we could go with something like:

```csharp
try (var foo)
{
    foo = GetFooInAWayThatMayThrow();
}
catch (Exception ex)
{
    Log(ex);

    return;
}

DoSomethingWith(foo);
```

but at that point all you're really doing is making the ```try``` more complex and fragile for little benefit.

**Comment by svick** [comment]
> `foo` has to be initialized even if we know it'll never be touched due to hitting the `catch` block

That's not true, you can leave it uninitialized:

```c#
string[] foo;

try
{
    foo = GetFooInAWayThatMayThrow();
}
catch (Exception ex)
{
    Log(ex);

    return;
}

// can only get here if the try succeeds
DoSomethingWith(foo);
```

**Comment by WillNess** [comment]
@IanKemp check out question one hundred sixty thousand and nine, on that site where we recently were in contact. You'll see I was in similar position as yours (even worse, I think). I don't put links (and don't even name names) here and especially there as I don't want the admins to realize it's still visible; they think they deleted it. Since THAT happened, I have zero expectations off that site and their pack of cheerleaders. :) When there's no hope, there's no disappointment.
