### ISSUE TITLE
Proposal: #pragma warning disable once

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/csharplang#1070]
Currently when we need to disable a warning for a given statement, we have to enclose it between `#pragma warning disable` and `#pragma warning restore` directives:

```
#pragma warning disable FOO123
var x = Foo("bar");
#pragma warning restore FOO123
```

This is quite verbose and impedes code readability.

Proposal: introduce `#pragma warning disable once` directive that disables a warning for the following statement only:

```
#pragma warning disable once FOO123
var x = Foo("bar");
```

The idea is borrowed from ReSharper's warning suppression comments:

```
// ReSharper disable once InconsistentNaming
```

**Comment by sharwell** [comment]
Conceptually I'm not against the idea of simplifying this case. However, the proposed syntax leaves a lot of questions for me (i.e. it might not be intuitive and/or there could be a better way to approach this):

1. What happens if there are more than one instance of the specified ID(s) on the following line?
1. What happens if there are no instances of the specified ID(s) on the following line?
1. What happens if the warning isn't on the immediately following line, but appears later?
    * Special case: #295 
    * Special case: multi-line tokens such as verbatim string literals
    * Special case: multiple `disable once` directives on consecutive lines

**Comment by HaloFour** [comment]
Ya know, I don't think I've ever used `#pragma warning disable`.  Out of curiosity what are the common scenarios where you'd want to disable a warning rather than address it?

**Comment by sharwell** [comment]
@HaloFour Three most common cases:

1. Bug in the analyzer which caused it
2. During multi-targeting, one target results in the warning while others do not, and suppressing is easier than conditional compilation
3. The change would be a breaking change according to the versioning policy of the product

Also one project I worked on looked at the "most recently changed date" for methods and applied different testing requirements, so changes to old code could result in unexpected developer overhead to address secondary policies (in this case, a global suppressions file was used to target the warning locations).

**Comment by HaloFour** [comment]
@sharwell 

Ah, I see, so something that's more commonly triggered via analyzers where you might be applying stricter and more pedantic rule sets that you might want to shut-up on an individual basic, just like Resharper.  That does make sense.

When dealing with vanilla C# compiler warnings I don't think I've ever encountered a situation where the compiler couldn't be satiated with what is often better/shorter code anyway.  95% of the time it seems to be the result of the fact that other developers don't seem to realize that you can omit the variable name in a `catch` statement.

**Comment by thomaslevesque** [comment]
> What happens if there are more than one instance of the specified ID(s) on the following line?

If that line has a single statement, all instances are suppressed; the directive applies to the whole statement.

> What happens if there are no instances of the specified ID(s) on the following line?

Nothing. The directive applies to the next statement, not to the next occurrence of the warning.

> What happens if the warning isn't on the immediately following line, but appears later?

Blank lines would have no effect. Only statements should be considered. The directive would apply to the first statement following it.

>     Special case: #295

That's a tricky one... I'm not sure what it should do in this case.

>     Special case: multi-line tokens such as verbatim string literals, where the warning is reported after the first line of the token

As I said, lines don't matter, only statements do.

>     Special case: multiple disable once directives on consecutive lines

They would all apply to the next statement.

**Comment by thomaslevesque** [comment]
> Ya know, I don't think I've ever used #pragma warning disable. Out of curiosity what are the common scenarios where you'd want to disable a warning rather than address it?

In addition to the scenarios mentioned by @sharwell:

- [CS0169](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0169) on a field that is actually used by reflection.
- Code Analysis or FxCop naming rules when there's a good reason to violate the rule.
- [CA1006](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1006-do-not-nest-generic-types-in-member-signatures) when there's no way around it (e.g. `Expression<Func<T>>`)

**Comment by jnm2** [comment]
Not to mention the three or four I typically put in for pinvoke structs.

**Comment by gautelo** [comment]
Another use case is when the framework or a library will call certain optional methods through reflection. One example is the mstest ClassInitialize method which require a TestContext argument. When you don't use that argument you get IDE0060. I expect there might be similar cases for asp.net global asax things and/or console host args etc. I guess interfaces for these things would remove this problem, but as it stands this pops up.

**Comment by goblinfactory** [comment]
Isn't the problems described above already resolved for C++ using #pragma warning supress? What I mean, is that they've already worked through all the edge cases, and this was their final conclusion, and most likely well reasoned and battle tested.

We should adopt the same pattern for C# for the same reasons they did. imho. Below are examples of how it works in C++, and I see no practical reason we shouldn't follow the same convention? It's very readable, and the concept of push and pop solves problems of really bad bugs creeping in by having a piece of code inadvertently creating a coupling (changing behavior) of other code using pragmas. 
 
***example of supress warning 1234 in C++***

```C++
#pragma warning (disable : 4507 34; once : 4385; error : 164; supress : 1234 )
```
C++ supress docs here
https://docs.microsoft.com/en-us/cpp/preprocessor/warning?view=vs-2019

**important point is this text**
```
suppress | Pushes the current state of the pragma on the stack, disables the specified 
warning for the next line, and then pops the warning stack
 so that the pragma state is reset.
```

**Comment by goblinfactory** [comment]
if we are going to deviate from the C++ convention, then I'd propose that 
when the `#pragma warning disable` appears before any namespace declaration, that the suppression applies only for that file, and only for that namespace. This will allow us to move the pragma warning to the top of the file, and it will be invisible to anyone scanning the code. these are pre-processor commands to compilers that humans do not need to concern when reading code to understand it's intent.
