### ISSUE TITLE
a method question about the start of a 'Try'

### ISSUE THREAD

**Issue by YinHaoDev** [dotnet/csharplang#1072]
if (DateTime.TryParse(StartDateTime, out var beginDateTime)) {}
if (DateTime.TryParse(EndDateTime, out var endDateTime)) {}
no problem. but
if (DateTime.TryParse(StartDateTime, out var beginDateTime) || DateTime.TryParse(EndDateTime, out var endDateTime))
{}

will prompt 'EndDateTime' CS0165 C# use to unassigned local variable

if (beginDateTime > endDateTime) {}
I'm using CSharp 7.1.
Is it a bug ? 
or am I using the wrong way?

**Comment by HaloFour** [comment]
The `||` operator short-circuits which means that if the first call to `TryParse` succeeds the second one isn't even attempted thus the compiler can't guarantee that `endDateTime` has been assigned a value.  Try using the `|` operator instead.

**Comment by YinHaoDev** [comment]
ok .
