### ISSUE TITLE
static generic deconstructs should be warning

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1076]
static generic deconstructs without any constraints should be treated as warning. while we can use analyzer but I think this should be added to Microsoft rule set.

this was something that already [mentioned by @sharwell](https://github.com/dotnet/csharplang/issues/987#issuecomment-335462158)

if you have such deconstruct

    public static void Deconstruct<T>(this T value, out T a, out T b) => (a, b) = (value, value);

you can assign one to many

    var (x, y) = 1;

but assume you have following deconstruct somewhere else

    public void Deconstruct(out int a, out int b) ...;

if you decide to remove this (assume you used this deconstruct in multiple places in your code), you wont get any error because static generic deconstruct becomes successor of it. it is likely that behavior of program will be changed (and introduces bugs) without letting you know.

same thing happens if deconstruct cant be called due to its accessibility or wrong signature.

therefor, I think it should be warning in general, because such deconstruct can swallow programmer errors and turn them into bugs.

**Comment by HaloFour** [comment]
I don't see why this situation is any different from any other situation where removal or modification of a method may result in different method resolution, whether that be a different overload or an extension method.  If you decided to have a pathological all-catching deconstruct method in your project that's a risk you willfully accept.

**Comment by MkazemAkhgary** [comment]
@HaloFour but this one is tricky, normally when you decide to remove a method or change its signature, you get errors due to change. you may not get any errors if you use overloads, but that's different. 

you cant really find which deconstruct is being called. for methods you can right click and select "go to implementation" but I don't see way for deconstructs.

another thing, when you change a method, very specific part of your project changes. so you expect and you probably know what part of code is affected.

but this deconstruct is a virus, it affects your whole project. so changes could be all over the place.

by the way that's what I wanted to share and help others not to get in this trap, its lesson I learned in hard way.

**Comment by HaloFour** [comment]
I'd say that your situation is fairly unique.  But it is probably a good idea to have a simple eay to navigate to the Deconstruct method from a deconstruction assignment.

**Comment by svick** [comment]
@MkazemAkhgary Consider having an extension method like:

```c#
public static int CompareTo<T>(this T x, T y) => 0;
```

You also have a type `Foo` that implements `IComparable<Foo>` (and thus also has `public int CompareTo(Foo)`).

If you then change `Foo` to remove the `IComparable<Foo>` interface (and the `CompareTo()` method), code that previously called `Foo.CompareTo()` will still compile, thanks to the extension method.

This situation is fairly similar to the one with `Deconstruct()`. Do you think the extension `CompareTo()` should also produce a warning?

> for methods you can right click and select "go to implementation" but I don't see way for deconstructs.

It seems to work for me with ReSharper enabled if you right click on the closing deconstruction parenthesis. Including that behavior in Roslyn itself sounds like a reasonable request to me.

**Comment by MkazemAkhgary** [comment]
fair enough, an easy way to know which deconstruct is being resolved will be a good addition.

**Comment by svick** [comment]
@MkazemAkhgary You should probably create a separate issue about that in the Roslyn repo.

**Comment by MkazemAkhgary** [comment]
oh ok

**Comment by CyrusNajmabadi** [comment]
@jcouv had added (or is adding) easy ways to see which Deconstructs are being used from the IDE.  I believe you'll be able to get this information by hovering over the = sign in a deconstruct assignment.
