### ISSUE TITLE
Composite enums

### ISSUE THREAD

**Issue by drozdekl** [dotnet/csharplang#1079]
It would be great to have a composite enums. What do you think about this idea?

```CSharp
enum Color {
    Blue {
        CadetBlue,
        SkyBlue,
        Turquoise
    },
    Red,
    Green
}
```

It would be great to just write (with intellisense): `var x = Color.Blue.SkyBlue`

Currently I often use enums like BlueCadet, BlueSky, BlueTurquoise because I am lazy and want Visual Studio to quickly offer exactly what I do want. 

edit: I program automata with many states which I like to be compile constants. That's reason why I have enums with a lot of values and very similar names. It is nearly impossible to distinguish them and something like "folders" would help. I want to recycle some names and composite enums would be an option.

edit: I would also like to write something like: `case Blue` in `switch`. That could be just copying of the code from `Blue` case into `Blue.CadetBlue`, etc. 

edit: It would be also possible to do nothing with enums and introduce something like groups. It could look like:
```CSharp
group Blue from Color {
    CadetBlue,
    SkyBlue,
    Turquoise
}
```

It would be possible to access for example `Blue.SkyBlue` like an equivalent of `Color.SkyBlue`. Also it would be possible to write:
```CSharp
Color a = ...
switch(a) {
    case Blue:
    ...
}
```

**Comment by MkazemAkhgary** [comment]
I like your query style syntax for enums, that's something to think about in wider use cases...

**Comment by RsWorkProgrammingGroup** [comment]
Good idea!
I love it!😃😃😃

**Comment by Joe4evr** [comment]
And how do you propose this is represented under the covers? How will the compiler know which enum values have sub-values and which don't to provide accurate IntelliSense? What kind of code will the compiler spit out for your case of `case Blue` matching all the sub-values of `Blue`?

These are questions you need to provide an answer for.

**Comment by aluanhaddad** [comment]
I like the idea of nested enums.

**Comment by lillo42** [comment]
I like the idea too

**Comment by bondsbw** [comment]
Not the same but related: #587
