### ISSUE TITLE
Namespaces topic has a todo item to add an example

### ISSUE THREAD

**Issue by mairaw** [dotnet/csharplang#1086]
Topic: https://github.com/dotnet/csharplang/blob/master/spec/namespaces.md

We got a comment on our docs to remind us of that: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces#comments-container

**Comment by scottdorman** [comment]
Can this be closed? The referenced page in docs no longer seems to have that comment (or any comments for that matter).

**Comment by mairaw** [comment]
But the TODO is still on the spec:
![image](https://user-images.githubusercontent.com/12971179/56158040-d58b4f80-5f75-11e9-9223-3b0718855a99.png)

The comment is probably gone since we switched feedback systems since then.

**Comment by scottdorman** [comment]
@mairaw Thanks for the clarification. I didn't see the TODO in the spec when I first looked at it (skimmed it too quickly rather than just searching for it).

**Comment by BillWagner** [comment]
Examples are added in dotnet/csharpstandard#9 which is currently in review by the committee.

I'll close this (Yes, I could move it to the csharpstandard repo, but that doesn't seem as useful.)
