### ISSUE TITLE
Let File.Move and File.Copy overwrite files

### ISSUE THREAD

**Issue by jmeberlein** [dotnet/csharplang#1091]
I get if you want to add protection, so developers can't accidentally overwrite files. But when I see Move and Copy methods, I expect something similar to `mv` or `cp` on the command line, which will overwrite the file if they have the right permissions.

**Comment by HaloFour** [comment]
This belongs on the [CoreFX](github.com/dotnet/corefx/issues) repository which manages the actual framework.

**Comment by aluanhaddad** [comment]
@jmeberlein @HaloFour is correct.

However, you should note, that the `System.IO.File.Copy` method is overloaded, both static and instance-wise, such that you can write
```C#
System.IO.File.Copy("source", "dest", overwrite: true);
```

**Comment by gafter** [comment]
This issue is not a language issue. Closing.
