### ISSUE TITLE
Discussion / Proposal: Generic Operators

### ISSUE THREAD

**Issue by HellGate94** [dotnet/csharplang#1093]
this change can clean a lot up a lot of code split across many places and also remove a lot of redundant code.

Example:
```
public static byte Max(byte val1, byte val2);
public static short Max(short val1, short val2);
public static ushort Max(ushort val1, ushort val2);
...
```

This requires an overload for each datatype and if you create custom datatypes you need to add it to the definition or another helper class.

This is where Generic Operators could come in very very handy. instead of implementing it for every datatype using a generic function to handle them all (and override special cases by hand that don't apply to the generic case).
Now i know there are several problems with this but i'm sure they can be solved.
To name a few:
 - required type definition on call (`Math.Max<int>(1,10)`)
 - adding attributes for such methods
 - generics are mostly run time instead of compile time

Ignoring this cases for now and looking at how Generic Operators could be implemented

Proposal:
```
public static T Max<T>(T val1, T val2) where T : IOperator(<) { // need a better syntax to define the operators needed
    if (val1 < val2) {
        return val2;
    }
    return val1;
}
```

Another Example:
```
public static T Avg<T>(T val1, T val2) where T : struct, IOperator(+), IOperator<double>(*) { // T requires to have a T + T and T * double operator defined
    return (val1 + val2) * 0.5;
}
```

**Comment by eyalsk** [comment]
@HellGate94 #164 would solve it and many other issues.
