### ISSUE TITLE
Drawbacks  Why should we not do this?

### ISSUE THREAD

**Issue by GordonHarley** [dotnet/csharplang#1094]
Lack of ability to quickly parse code unless you're a regular programmer in functional languages, for one thing...   but I don't disagree with adding it since some people will get use out of that.  I can take a quick glance at a normal line of C++ or C# and tell you exactly what it does.   This, not so much.

**Comment by Joe4evr** [comment]
![](http://i.imgur.com/nHv3ZC3.png)

**Comment by DavidArno** [comment]
Um, am I missing something? What is this issue about? 😕 

And what is that picture supposed to be, @Joe4evr? 😕 😕

**Comment by MkazemAkhgary** [comment]
ok, a little humor is not bad, but seriously

>Why should we not do this?

what exactly?

> but I don't disagree with adding it

adding what?

> since some people will get use out of that

out of what?

> and tell you exactly what it does

which does what?

 > This, not so much.

what? 😅

**Comment by jnm2** [comment]
I keep seeing the weirdest mistake posts around GitHub and scratching my head trying to figure out how they happened.

**Comment by MgSam** [comment]
I agree. It's total bullshit. Let's never even think about doing this again.

**Comment by alrz** [comment]
This is probably ambiguous.

**Comment by scalablecory** [comment]
I for one would like to do this, but I think we need to better understand the ramifications it will have on Java programs.

**Comment by stepanbenes** [comment]
They don't disagree neither.

**Comment by DarthVella** [comment]
> I can take a quick glance at a normal line of C++ or C# and tell you exactly what it does. This, not so much.

I wholeheartedly agree.

**Comment by Logerfo** [comment]
Dupe of [#6969](1094)

**Comment by dsaf** [comment]
I have found it perfectly understandable. Perhaps I can simplify this for you guys:

> Drawbacks Why should we not do this?

Drawbacks of current C# vision

> Lack of ability to quickly parse code unless you're a regular programmer in functional languages, for one thing...

New functional programming features are more friendly towards developers with that affinity but might make code harder to read for imperative-first developers.

>...but I don't disagree with adding it since some people will get use out of that.

Nevertheless there is a value in adding functional features since there is an obvious interest from vocal members of the community.

> I can take a quick glance at a normal line of C++ or C# and tell you exactly what it does.

It is much easier for me personally to understand a line of C++ 98 or C# 2.0.

> This, not so much.

Which is not the case with C# 7.0+.
