### ISSUE TITLE
Delegated properties, like in Kotlin

### ISSUE THREAD

**Issue by AsafMah** [dotnet/csharplang#1096]
When using frameworks it seems that there is a lot of boilerplate surrounding Properties.
Here are some examples:

### INotifyPropertyChanged
It is used in both wpf and windows universal, which make a hefty percentage of the desktop GUI apps developed today, and it makes writing binded classes very annoying, and makes them less readable.

Someone already suggested special syntax just for this interface for how annoying it is: 
https://github.com/dotnet/csharplang/issues/

I don't think we need new language features just for this interface, but the problem doesn't stop here.

### ReactiveUI
This framework defines two types of special properties. 
Both require a backing field and boilerplate:
```c#
    string _SearchTerm;
    public string SearchTerm
    {
        get { return _SearchTerm; }
        set { this.RaiseAndSetIfChanged(ref _SearchTerm, value); }
    }

    ObservableAsPropertyHelper<Visibility> _SpinnerVisibility;
    public Visibility SpinnerVisibility => _SpinnerVisibility.Value;
```

## The solution (In kotlin)

Kotlin has a very nice feature called "Delegated Properties".
You can read about it here: https://kotlinlang.org/docs/reference/delegated-properties.html
It looks like this:
```kotlin
class Example {
    var p: String by Delegate()
}
```
p is an auto property (all kotlin properties are), but it is delegated to the delegate class.
The delegate class looks like this:
```kotlin
class Delegate {
    operator fun getValue(thisRef: Any?, property: KProperty<*>): String {
        return "$thisRef, thank you for delegating '${property.name}' to me!"
    }
 
    operator fun setValue(thisRef: Any?, property: KProperty<*>, value: String) {
        println("$value has been assigned to '${property.name} in $thisRef.'")
    }
}
```

Basically, every time p is accessed, the corresponding method to the access type in Delegate would be called.

It lets you abstract over writing getters and setters, you only need to write the delegate class once, and now every property can use its functionality in one line.

## The solution

What I propose is to add a mechanism similar to this in c#. 

First, we would need to define a class.
It should have the methods GetValue and SetValue with the right signatures like this:
```c#
class NotifyHelper<T> {
    private T _val;
    public NotifyHelpe(T val) => _val = val

    T GetValue(object this, PropertyInfo property): {
                 return _val;
    }
 
    void SetValue(object this, PropertyInfo property, T value) {
             if (value == _val) {
                    return;
             }
            _val = value;
            ((INotifyPropertyChanged) this)?.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property.Name));
    }
}
```
And that's it, now you have a re-useable way to have your classes support the interface.

the syntax for using the class could look like this (it's not final at all, of course):
```c#
class Example {
String p using NotifyHelper.Create("Initial") //Create method is to avoid specifing the generic type, its definition is omitted here
int i using NotifyHelper.Create(5) 
MyCustomObject c using NotifyHelper.Create(new MyCustomObject(3)) 
}

```

As you can see it's pretty readable, convenient and extendable.

# Other uses
The kotlin page lists other uses for this feature, notably their own version of Lazy<T> - in kotlin, if you have a lazy property you can just define it to be your type T, instead of c#'s Lazy<T>.
The delegated property will make sure that it is initialized late and only once, but when you use it you can treat it the same as any other string.

**Comment by eyalsk** [comment]
@AsafMah This is probably yet another use-case for #107. Check other use-cases here #341.

**Comment by aluanhaddad** [comment]
I like the idea of delegation here. It seems like some pretty powerful patterns could emerge, but I dislike the proposed syntax.  I feel like it's a missed opportunity to express a relationship between a type and a property on that type by enhancing generic constraints. The example code is opaque.

**Comment by rikimaru0345** [comment]
Eyalsk: that's the first thing that came to my mind as well! 

I would love to be able to do what is suggested here, but I think it could be solved in a better, more generic way. 

If we get some additional syntax to delegate properties, then it won't take long for "extended" suggestions to pop up (like maybe also proxying methods).

That would bring us back to generators aka "replace original" again.

**Comment by eyalsk** [comment]
@rikimaru0345 

> I would love to be able to do what is suggested here, but I think it could be solved in a better, more generic way.

That generic way you speak of is through a source generation.

Adding a specific syntax to the language just for that means you specialize not generalize and can't see why it warrant a new syntax.

**Comment by asarazan** [comment]
Just to further reinforce the point: This remains the most useful feature of Kotlin, and the one I absolutely miss the most now that I work in C#. Just having a wrapper delegate over Unity's PlayerPrefs interface would make me so happy-- especially since C#'s initialization order makes `Lazy` nearly useless in practice.

**Comment by georgiuk** [comment]
I have proposed something similar here #1095 . I hope more people find it useful and request for it.

**Comment by orthoxerox** [comment]
https://github.com/dotnet/vblang/issues/282
