### ISSUE TITLE
local delegates

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1097]
sometimes when it comes to simplifying to semi-equivalent methods, you end up using functions and pass that function to a method with common logic.

while `Func` and `Action` delegates are very useful, but it some cases you cant use them. for example when argument should be passed by `ref`. in that case I end up writing my own delegate.

In my scenario I was using local methods, but a delegate has to be declared outside method. it would be nice if I could declare a delegate inside method.

```
private delegate TRet Del<TRet>(ref int? x); // if only I could declare that inside :)
public void Foo()
{
    bool GetResult(Del<T> find, ...)
    {
        // common logic
    }

    bool MoveNextStrategy(...some parameters...)
    {
       return GetResult(source.NextHigherItem, ...); // NextHigherItem is method group
    }
    bool MoveBackStrategy(...some parameters...)
    {
         return GetResult(source.NextLowerItem, ...); // NextLowerItem is method group
    }
    //...

```

---

a delegate could be declared inside a method like this.

```
public void Foo()
{
    delegate TRet Del<TRet>(ref int? x);
    // use delegate.
}
```

**Comment by Joe4evr** [comment]
Why would you *not* want to use a local function over a delegate in this scenario?

**Comment by MkazemAkhgary** [comment]
never mind, I had a design problem somewhere, better to fix that instead.

also this proposal brings in mind, use of local struct or classes as well! but I don't find that a good design.

**Comment by benaadams** [comment]
https://github.com/dotnet/csharplang/issues/1060
