### ISSUE TITLE
set a method group to method implementation

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1098]
some methods act as a delegate. for example 

    public void Dispose() => _resource.Dispose();

allow to set method groups to method implementation like this.

    public void Dispose() = _resource.Dispose;

now for this example, it didn't save to much 🤓 , but if there are parameters it becomes smaller.

    public void DoSomething(int x, int y, int z) => _foo.DoSomething(x, y, z);

becomes

    public void DoSomething(int x, int y, int z) = _foo.DoSomething;

**Comment by Mafii** [comment]
I don't think this adds a lot to the language, compared to the effort required to make such a thing work.

This would blur the line between methods and func<T> objects so much, that it could be confusing to newcomers.

**Comment by MkazemAkhgary** [comment]
I dont think this needs too much effort. This syntax is not conflicting with any existing syntax. Im not sure how it blurs the line between delegates and methods, could you please elaborate more? @Mafii

**Comment by lillo42** [comment]
When another method have less/more parameter or  parameter in different position like:

```
private void DoPrivateSomething(int a, int b) { ... }
private int c = 0;
public  void DoSomething(int a) => DoPrivateSomething
// public  void DoSomething(int a,  int b) => DoPrivateSomething(a,c)
```

or 

```
private void DoPrivateSomething(int a) { ... }
public  void DoSomething(int a,  int b) => DoPrivateSomething
// public  void DoSomething(int a,  int b) => DoPrivateSomething(a)
```

or 


```
private void DoPrivateSomething(int b, int a) { ... }
public  void DoSomething(int a,  int b) => DoPrivate
// public  void DoSomething(int a,  int b) => DoPrivate(b,a)
```

What should happen in these cases?

**Comment by MkazemAkhgary** [comment]
@lillo42 Your examples are irrelevant. first two examples are impossible with method groups. what happens is compiler error.

 its like saying call a parameter-less method with argument, what should happen? obviously compiler error. 

for the last example, again. this is using method group syntax. you don't expect more than that. a method group maps parameters one by one. your argument still applies when casting method group into a delegate. story is not different here.

**Comment by DavidArno** [comment]
@Mafii,

I think it adds a lot to the language for those that use the delegation pattern. All that boilerplate copying of the parameters would just disappear.

Having said that, I'm not convinced by the syntax as `=` and `=>` are easily confused. But the idea has merit.

**Comment by HaloFour** [comment]
While it does make delegation patterns slightly less verbose I think that the amount of benefit isn't great enough to warrant a language change.  In the absence of source generators I'd much rather a language feature for delegation that would eliminate having to specify all of the methods to begin with.

IIRC in IntelliJ the autocomplete will detect when you're going to call a method where all of the parameter types/names match a signature and it will offer to complete the entire list of arguments.  Something like that would at least eliminate the need for typing these arguments individually.

**Comment by eyalsk** [comment]
@HaloFour 

> While it does make delegation patterns slightly less verbose I think that the amount of benefit isn't great enough to warrant a language change. In the absence of source generators I'd much rather a language feature for delegation that would eliminate having to specify all of the methods to begin with.

You mean something like the following? where signatures need to match exactly? or I'm misinterpreting you? :)

```
public void Dispose() => _resource
```

**Comment by MkazemAkhgary** [comment]
@eyalsk that wouldn't be complete. What if method names are different?

I think we could omit return type as well.

    public Dispose() => _resource.Dispose;

But now im kind of 😐

**Comment by benaadams** [comment]
```csharp
public void DoSomething(int x, int y, int z) = _foo.DoSomething;
```
Could always be implemented as syntactic sugar for:
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public void DoSomething(int x, int y, int z) => _foo.DoSomething(x, y, z);
```

**Comment by HaloFour** [comment]
@eyalsk 

I don't have IntelliJ at hand to provide a screenshot, but more like when you have the following:

```java
public class C {
    public int Foo(int x, String y, Object z) {
        return 0;
    }

    public int Bar(int x, String y, Object z) {
        return Foo$
    }
}
```

With the caret at the `$` when you type `(` the IDE would automatically detect that `Foo` (or an overload of `Foo`) accepts arguments matching the types and signatures of a subset of the parameters in scope, so autocomplete would offer up `(x, y, z)` as the first option.

**Comment by MkazemAkhgary** [comment]
Here are my other thoughts

---

    public delegate Add => _source;

this creates public Add delegate with all accessible overloads available for `_source`. 

---

    public delegate Add(T item) => _source;

this creates `Add(T)` delegate to `_source`. 

---

    public delegate Add(T item) => _source(string t, string t2);
    {
           var str = item.ToString();           
           var str2 = item.ToString();
           return (str, str2);
    }

this creates a delegate with extra logic in between. tuple like return is used which will be mapped to target method signature of `_source`.

---

@HaloFour This proposal is not about how intellisense could help with writing, I think a syntax would be better, this would be very helpful for writing fast collection wrappers, decorators, enumerators, nested objects, mappers, views etc.

**Comment by Pzixel** [comment]
What do you want is called `partial application` or `alias` in case if your `partial application` fix exactly 0 arguments. It's not possible in C# and I think it's a bit uncommon to have it here. However, it's quite natural in languages like F#

```fsharp
let add (x:int, y:int) = x + y;
let delegatedAdd = add;
delegatedAdd(1,2)
```

**Comment by MkazemAkhgary** [comment]
@Pzixel thanks for the comment. I think we could have something similar in c#. just needs work like how they are working on concepts.
