### ISSUE TITLE
Add Pattern match methods for Linq library.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1102]
a combination of Where and Select in single query like Match that is capable of pattern matching and selecting matches.

**Comment by svick** [comment]
If you want to propose adding a method to the base class library, then the correct place to do that is [the corefx repo](https://github.com/dotnet/corefx). And you should follow [their API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md), if you want your proposal to be seriously considered.

**Comment by stepanbenes** [comment]
If I may speak for author of the issue, he may be refering to the language proposal such as this:
```cs
var yCoordinates = from obj in objects
                   match Point { X: 4, Y: var y }
                   select y;
```
It is quite interesting idea but I suppose difficult to implement.

This could be rewritten to:

```cs
var yCoordinates = from obj in objects
                   where obj is Point { X: 4, Y: var y }
                   select y;
```
which also requires language change - allow expression variables in linq clauses with the same scope as range variable.

**Comment by stepanbenes** [comment]
If I may speak for the author of the issue, he may be refering to a language proposal such as this:
```cs
var yCoordinates = from obj in objects
                   match obj with Point { X: 4, Y: var y }
                   select y;
```

I think new `match` clause is not necessary, it could be rewritten to:

```cs
var yCoordinates = from obj in objects
                   where obj is Point { X: 4, Y: var y }
                   select y;
```
It is quite interesting idea but I suppose difficult to implement. It requires language change - allow expression variables in linq clauses with the same scope as range variable.

**Comment by svick** [comment]
@stepanbenes 

> allow expression variables in linq clauses with the same scope as range variable.

That's https://github.com/dotnet/csharplang/issues/159.

**Comment by MkazemAkhgary** [comment]
@stepanbenes no, thats query expression, i asked for extension method where you are forced to do

    var yCoordinates = objects.Where(obj => obj is Point).Select(obj => (Point)obj);

**Comment by CyrusNajmabadi** [comment]
> ```var yCoordinates = objects.Where(obj => obj is Point).Select(obj => (Point)obj);```

Isn't that just: ```var yCoordinates = objects.OfType<Point>();```?

**Comment by MkazemAkhgary** [comment]
No, sorry for bad example, actually its

    var yCoordinates = objects.Where(obj => obj.prop is Point).Select(obj => (Point)obj);

Lets just go ahead

    var yCoordinates = objects.Match<Point>(obj => obj.prop);

Maybe with additional logic with property matching but im not sure what good way for it would be. Have to think for a while

**Comment by CyrusNajmabadi** [comment]
> var yCoordinates = objects.Match<Point>(obj => obj.prop);

How would this work?  Can you provide an implementation for this?

**Comment by MkazemAkhgary** [comment]
I think this works, im too sleepy now sorry. 😰😴

    static IEnumerable<TOut> Match<Tin, TOut>(this IEnumerable<TIn> source, Func<Tin, TOut> resultSelector)
    {
        foreach(var item in source) if(item is TIn t) yield return t;
    }

And with property matching logic

    static IEnumerable<TOut> Match<Tin, TOut>(this IEnumerable<TIn> source, Func<Tin, TOut> resultSelector, Predicate<TOut> match)
    {
        foreach(var item in source) if(item is TIn t && match(t)) yield return t;
    }

So you can call it like

    objects.Match<Point>(obj => obj.prop, p => p.IsZero());

**Comment by CyrusNajmabadi** [comment]
```c#
static IEnumerable<TOut> Match<Tin, TOut>(this IEnumerable<TIn> source, Func<Tin, TOut> resultSelector)
{
    foreach(var item in source) if(item is TIn t) yield return t;
}
```

1. This doesn't use resultSelector
2. ```item is TIn t``` will always be true.

**Comment by MkazemAkhgary** [comment]
Oh! I need some coffee...

```
static IEnumerable<TOut> Match<TIn, TIntermediate, TOut>(this IEnumerable<TIn> source, Func<TIn, TIntermediate> resultSelector)
{
    foreach(var item in source) if(resultSelector(item) is TOut t) yield return t;
}
```

Since TOut is not used we have problems with compiler infer return type.

We could use object instead of Intermediate generic type to reduce number of generic parameters, but that cause boxing of value types.

**Comment by CyrusNajmabadi** [comment]
Right.  So i don't see how your proposal would actually work.  Also, as mentioned above.  If you want to propose API additions, this is not the right repo for it.  Finally, i would personally prefer that simple API changes (i.e. ones that can be trivially built just by combining existing APIs) just be offered through nuget packages through the community. I don't feel like we need to take every bit of functionality and jam it into the core Fx.  That's what nuget is for :)

**Comment by huoyaoyuan** [comment]
For all of the cases above, OfType just works, doesn't it?
Linq is designed for concatenating, so we need primitive ones, not plenty of combined.
