### ISSUE TITLE
Proposal: allow 'stackalloc' followed by initialization

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#1112]
For example:
```C#
Span<int> prime = stackalloc int[10] {2, 3, 5, 7, 11, 13, 17, 19, 23, 29}; // this should be allowed
```

**Comment by jcouv** [comment]
Tagging @VSadov @OmarTawfik

**Comment by alrz** [comment]
I think Span is similar to [`initializer_list<T>`](http://en.cppreference.com/w/cpp/utility/initializer_list) in C++. so we can default to Span when no type is specified.
```cs
var span = {1, 2, 3};
```

**Comment by orthoxerox** [comment]
@alrz What would be the backing store of `{1, 2, 3}`, an array?

**Comment by alrz** [comment]
@orthoxerox It could be a shorthand for `Span<int> span = stackalloc int[3] {1, 2, 3};`

**Comment by orthoxerox** [comment]
@alrz I think this might be too confusing. Nothing indicates that you cannot return this value from your method, but you can't.

**Comment by VSadov** [comment]
The question of array initializers for stackalloc comes up very often nowdays. 

It is fairly uncontroversial and a relatively small feature. It has been discussed before with near universal agreement that it should be done at some point

I have posted a proposal here https://github.com/dotnet/csharplang/pull/1122  - to make sure it does not fall off the list.
