### ISSUE TITLE
Language-Version-History.md C# 2 (Co- and Contra-variance for delegates and interfaces)

### ISSUE THREAD

**Issue by Exocomp** [dotnet/csharplang#1114]
In [Language-Version-History.md](https://github.com/dotnet/csharplang/blob/master/Language-Version-History.md) it states in C# 2 that "Co- and Contra-variance for delegates and interfaces" was implemented however I can't find any information Co- and Contra-variance for Interfaces being released in C# 2.

**Comment by gafter** [comment]
Right; variance was introduced in C# 4, as stated later in that document.

**Comment by gafter** [comment]
Fixed.
