### ISSUE TITLE
Declare variables in e.g. if statements

### ISSUE THREAD

**Issue by dozer75** [dotnet/csharplang#1115]
For a long time a clear (? in my opinion anyway) rule has been in C# that variable declarations should be explicit outside statements like `if`'s. From what I think I remember back at the announcement of C# in the beginning of 2000 was that this was regarded an abomination in C that should never be a part of C# due to the level of complexity it caused.

However already back then, iteration statements like `for` and later on `foreach` introduced the possibility to have localized iteration variables defined. And now in C#7 out variables was introduced which again can be used in if statements to check for the condition and create a local variable like this:

```
if(int.TryParse("1", out var val))
{
}
```
Since I think that this obfuscate the standard already I have a hard time argumenting for why local variables in e.g. if statements shouldn't be possible, if it would function the same way as an out variable.

So, since out variables was introduced, I think that it would be only logical to support a statement like this:

```
if((var result = someFunction()) == 1)
{
    //do something
}
```

should be valid. I think that the scope of the variable defined in the if statement should be scoped the same way as out variables.

Of course, there are also other statements than `if` that should be handled the same way.

As for developers this could be faked by doing something a generic like this (very simplified):

```
private static bool GetVariable<T>(Func<T, bool> conditionFunc, out T result)
{
    result = default(T);
    return conditionFunc(result);
}
```

which can be used like this to achieve the same result as a variable declaration:
```
if (GetVariable<int>(i => i == 1, out var result))
{
    //use result here
}

//or here
```

**Comment by jnm2** [comment]
Already being tracked- see https://github.com/dotnet/csharplang/issues/973.

**Comment by gafter** [comment]
Please take discussion to #595 and #973
