### ISSUE TITLE
object composition

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1119]
just very basic idea for making programmers life easier. please help us to flesh this out. give your thoughts and feedbacks.

---

support for alias type like this. (keyword is contextual)

```
public alias IntList : List<int>;
```

alias type can contain generic type itself

```
public alias GL<T> : List<T>;
```

alias can be composed, example composition of alias.

```
public alias IntList : List<int>
{
    public void Product()
    {
         long p = 1;
         foreach(var i in this) p *= i;
         return p;
    }
}
```

this is a class, exact doppelganger of list with additional method.

alias can change method implementations. or accessibility of members. they can also change return type of methods.

```
public alias IntList : List<int>
{
    internal int Add(int item) // new implementation and new accessibility with return type
    {
         // voodoo
    }
}
```

alias can hide method implementations (by only changing accessibility).

```
public alias IntList : List<int>
{
    private void Add(int item); // does not change implementation
}
```

alias can call members in original type like this.

```
public alias IntList : List<int>
{
    public void Add(int item)
    {
         alias.Add(item);
    }
}
```

alias can not inherit. but it can implement from interfaces for additional implementations.

```
public alias IntList : List<int>, IFoo, IBar
{
     // implementations
}
```

alias can be composed from other aliases too.

alias type can be composed from delegates or structs. (in case they are delegates they can not be composed)

```
public alias Activator<T> : Func<T, T>;
```

note that alias can not access private members of target type. (or internal members of type in other assembly)

alias type and original type is not assignable to each other unless implicit cast is defined. for aliases that have no composition compiler can generate implicit cast for them.

---

incremental and decremental modifiers: alias can be marked as incremental or decremental. if its incremental then nothing is visible and you have to write methods you want to make public. (visible)

```
public incremental alias IntList : List<int>
{
    public void Add(int item); // Add becomes visible.

    public void Foo() // some other method with implementation
    {
    }
}
```

if alias is marked as decremental, all accessible methods of target type is visible and you have to write methods you want to make private. (hide)

```
public incremental alias IntList : List<int>
{
    private void Add(int item); // Add becomes hidden.

    public void Foo() // some other method with implementation
    {
    }
}
```

**Why alias?**

In my humble opinion this will make composition over inheritance a lot easier. so writing collection wrappers become easier too. without needing to type too much. also makes them a little faster because there is no delegate method, and no extra reference.

this does not require CLR support. compiler can auto generate code and be it in out side assembly or not, alias is always seen as actual target type. for example if target type is class, in intellisense alias will be shown just like its a class.

**Comment by HaloFour** [comment]
We already have `using` for aliases.  I don't see what this proposal has to do with partial application at all.

As for the "composition" bit, I don't see why that's remotely necessary.  Inheritance is a very different relationship from composition and generally the wrong solution.  By inheriting from a specific implementation of a collection class, as you are in your examples, you are leaking internal implementation details.  And even if that is what you intend to do it's already simple enough to accomplish in the language by simply using the existing inheritance syntax.

**Comment by DarthVella** [comment]
I don't see much difference between this and simple inheritance. Outside the ability to hide members (public -> private), all of the functionality proposed is already possible. Unless aliasing is possible over sealed classes, I suppose, but that's an entirely difference can of worms.

**Comment by theunrepentantgeek** [comment]
This is the sort of thing that could easily be achieved with a partial class, a code generator and a whiff of convention; no need for language support.

> also makes them a little faster because there is no delegate method, and no extra reference.

Avoiding the need to implement a wrapper by hand by having the compiler generate the wrapper doesn't remove the need for method implementations to delegate to the wrapped instance; the two will have exactly identical performance.

**Comment by MkazemAkhgary** [comment]
I think you didn't understand it correctly. let me give a simple example. here is the class

```
public class Foo
{
    public void Method1() {}
    public void Method2() {}
    public void Method3() {}
}
```

now here is alias.

```
public alias Bar : Foo
{
    public void Method4() {}
}
```

this compiles to

```
public class Bar
{
    public void Method1() {}
    public void Method2() {}
    public void Method3() {}
    public void Method4() {}
}
```

@DarthVella this is not inheritance, its [composition. ](https://en.wikipedia.org/wiki/Object_composition)

@theunrepentantgeek here Bar and Foo are not same thing, so partial class is not same. and as you can see Bar should be faster to code and run. `Bar` methods do not call `Foo`, they are duplicated by compiler.

@HaloFour this is some thing at first I thought, i.e making `using` alias public so its not per `.cs` file but its visible to entire namespace. for example `public using Foo = Bar<T1, T2...>` this should be declared like a type inside a namespace. so in that namespace you don't have to redefine `Foo` in every cs file.

I think you misunderstood. I'm not inheriting from class. here `Bar` is not inheriting `Foo`. it became exact copy with additional modifications.

**Comment by MkazemAkhgary** [comment]
by the way I was thinking that making exact copy may lead to leaking private members of target type. for example aliasing a list you may have access to backing array. in order to prevent that we can change compilation of Bar to following. in this case  @theunrepentantgeek is right, there is no performance improvement but it will be much faster to code.

```
public class Bar
{
    private readonly Foo foo; // accessed by alias keyword
    public void Method4() {}
}
```

here is how to write appropriate constructor (should be written by hand)

```
public class Bar
{
    public Bar(Foo foo)
    {
        alias = foo;
    }
}
```

**Comment by DarthVella** [comment]
Oh, my apologies. I have some reading to do then.

**Comment by HaloFour** [comment]
@MkazemAkhgary 

So you want delegation.  There are other proposals for that already.  And that still has nothing to do with aliases or partial application.

**Comment by DavidArno** [comment]
@theunrepentantgeek,
> This is the sort of thing that could easily be achieved with a partial class, a code generator and a whiff of convention; no need for language support.

Except that I really don't want to have to start marking classes as `partial` to have a code generator manipulate them and the code generator idea has turned into a thing of near mythical status that seems unachievable without a significant rethink and rewrite.

@MkazemAkhgary,
I second @HaloFour's observation. Partial application is a completely different thing to this delegation pattern proposal. You should consider changing its title.

**Comment by MkazemAkhgary** [comment]
@DavidArno my proposal is now twisted. when you use alias without body its really an alias just like `using ...` but with access modifiers so its not limited to a `cs` file and can be declared like a type. I may give it another proposal `public using Foo = Bar`

@HaloFour  alias keyword is misleading. apart from that this pattern can be used for either object composition or object aggregation depending on how you use that object. hmm its not clear how associated object should be created and destroyed. closing...
