### ISSUE TITLE
Value Tuples and args

### ISSUE THREAD

**Issue by drozdekl** [dotnet/csharplang#1124]
Let's define
```CSharp
void Func1(int arg1, int arg2) { ... }
void Func2((int arg1, int arg2) arg) { ... }
void Func3(int arg1, int arg2, int arg3) { ... }
void Func4((int arg1, string arg2) arg) { ... }
```

It is currently perfecly possible to write code
```CSharp
Func1(1, 5);
Func2((1, 5));
Func3(1, 3, 5);
Func4((4, "abc"));
```

I think that there there could be some kind of implicit composition and decomposition from and into args list. The function which would be finally applied would be the most specific one. It means that currently valid expressions behave absolutely the same but it is also possible to write code 
```CSharp
Func3((1, 3, 5));
Func4(7, "abc");
```

It is possible that there are some drawbacks I can't see and that's why I pick topic to discussion. The rules above are most useful especially when we have functions returning value tuples which matches to args list of some other methods.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/search?q=splatting&type=Issues&utf8=%E2%9C%93
