### ISSUE TITLE
Proposal: Allow the name of an out variable to be omitted if it is not used

### ISSUE THREAD

**Issue by jmairboeck** [dotnet/csharplang#1125]
It should be allowed to omit the variable name of a variable declared in an out expression, if the variable is not going to be used (similar to the catch clause for example), like this:

```c#
string str = ...
var isValidInt = int.TryParse(str, out int); // or out var
// the actual value is not needed here
```

Currently, when just saying `out int`, it is considered an "invalid expression". In the `out var` case, it is reported as "identifier var not found" (because var is a contextual keyword).

**Comment by CyrusNajmabadi** [comment]
```c#
string str = ...
var isValidInt = int.TryParse(str, out _);
```
