### ISSUE TITLE
default is not permitted as constant pattern with nullable types

### ISSUE THREAD

**Issue by jcouv** [dotnet/csharplang#1135]
@alrz commented on [Mon Jun 05 2017](https://github.com/dotnet/roslyn/issues/20015)

**Version Used**: master

**Steps to Reproduce**:

```cs
bool a = default(int?) is default(int?);  // error CS0150: A constant value is expected
bool b = default(int?) is default;        // error CS0150: A constant value is expected
```

**Expected Behavior**: No error

**Actual Behavior**: A constant value is expected

---

@jcouv commented on [Tue Jun 06 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-306686863)

FYI @gafter for triage

---

@gafter commented on [Mon Sep 11 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-328695577)

The expression on the right-hand-side of the `is` operator is not "target typed", and therefore must be an expression that has a type. This behavior is by design.

---

@alrz commented on [Mon Sep 11 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-328720443)

Two things: 

This is an error even with a typed `default(int?)`
`default` works for anything non-nullable: `obj is default`

---

@gafter commented on [Wed Sep 13 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-329238330)

Hmmm. Will investigate more.

---

@gafter commented on [Fri Sep 15 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-329856805)

According to the language specification, a value of type `int?` is not a constant.

---

@gafter commented on [Wed Nov 22 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-346437803)

I expect it is likely we will want to forbid patterns of the form `default`, to reduce confusion when we introduce the switch expression in the future. As such, I think it would be counterproductive to fix this.

---

@alrz commented on [Wed Nov 22 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-346440091)

Nothing about `is default` is confusing, this is just to make it consistent with itself (this is the only case that is not permitted). switch statement already produce a warning for the direct use (but not `(default)`, for instance). I think switch expression could follow the same rule, to be not confused with the "default" case.

---

@sharwell commented on [Wed Nov 22 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-346440828)

💭 I would expect both of the cases in the original example to behave like this:

```csharp
bool c = default(int?) is null;
```

---

@jcouv commented on [Wed Nov 22 2017](https://github.com/dotnet/roslyn/issues/20015#issuecomment-346441927)

I'll move to csharplang, since currently by design.

**Comment by alrz** [comment]
Another point,

>According to the language specification, a value of type int? is not a constant.

That is correct, but we do allow `default` in parameter default values, in which produce `null`. I think it's reasanble to do it for patterns as well.

**Comment by jcouv** [comment]
Notes from LDM as FYI https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-11-06.md

**Comment by jcouv** [comment]
`default` has since been disallowed in a pattern:
`bool b = default(int?) is default; // error CS8363: A default literal 'default' is not valid as a pattern. Use another literal (e.g. '0' or 'null') as appropriate. To match everything, use a discard pattern 'var _'.`

I'll go ahead and close this issue. Thanks
