### ISSUE TITLE
Proposal: Restrict class/interface scope to namespace

### ISSUE THREAD

**Issue by NickT1977** [dotnet/csharplang#1138]
Limit the scope of a class or interface to namespace level.
e.g.
`internal namespace class MyClass`
or 
`internal namespace interface MyInterface`
These would only be accessible to classes within the same namespace.

Thanks
Nick

**Comment by erik-kallen** [comment]
I guess that with

> These would only be accessible to classes within the same namespace.

you mean

> These would only be accessible to classes within the same namespace in the same assembly.

I think this is an excellent idea (I have thought about it myself). For many application the project is not the optimal granularity for determining visibility

**Comment by jnm2** [comment]
There's no way to express this in IL, so even if C# annotated it specially and played along, other languages would still see everything as `internal`.

**Comment by erik-kallen** [comment]
@jnm2 That's where the "in the same assembly" condition would come in. No annotations would even be required, it would only need to be marked as internal in IL. I wouldn't mind if `InternalsVisibleTo` exposed these types as well, it is (probably) mainly used for testing and these types could do with tests, too

**Comment by CyrusNajmabadi** [comment]
Why not just compile this into its own assembly?  Then internal will mean just what you want.

**Comment by NickT1977** [comment]
@CyrusNajmabadi  I could get the same behaviour by using different assemblies and the internal scope but it is very common that in a namespace I will have a set of related a few classes that has just one class with the entry points that I want to expose to the rest of the project (the other classes are just implementation detail).  Using assembly's seems like a bit overkill for the amount of times that  this occurs and I would prefer not to have potential many assembly's with only a handful of classes in each.

**Comment by DavidArno** [comment]
> ... it is very common that in a namespace I will have a set of related a few classes that has just one class with the entry points that I want to expose to the rest of the project ...

Why not make those "implementation details" classes, private nested classes of the entry point class?

**Comment by bondsbw** [comment]
Here is a related issue I never ported over here: https://github.com/dotnet/roslyn/issues/8391

To sum it up: separate the logical concept of  _component_ from the physical concept of _assembly_.  You can have multiple components in an assembly (components would likely be different namespaces).  The `internal` keyword then follows the logical component.

One major difference with just using assemblies is performance during the build process. Many tiny projects take much longer to build than a large monolithic project.

**Comment by Pzixel** [comment]
@bondsbw in my previous company we had an analyzer for very this purpose that wouldn't allow you to use the type from external namespace.

**Comment by MkazemAkhgary** [comment]
as long as its internal you shouldn't really care. with correct use of namespaces you can eliminate need of this feature.

with a proper naming and grouping of types in namespaces you will no longer pollute namespaces, please don't get obsessed as long as these types are internal and it wont affect users experience, neither yours.
 
don't worry to write namespaces with only internal types. when you reference a compiled dll of your class library those namespaces will not show up in intellisense.

https://stackoverflow.com/questions/720647/hiding-namespaces-containing-only-internal-types-in-a-class-library

**Comment by bondsbw** [comment]
@MkazemAkhgary 
>as long as its internal you shouldn't really care

One of the goals of the other proposal is dependency management.  Today you can use assemblies to enforce decoupling (no cyclic dependencies) and encapsulation (`internal`); in that proposal, you could use components to do the same, without the need for separate projects/assemblies.

**Comment by bondsbw** [comment]
To be clear, I don't split my code into 1000 projects.  I don't think many developers do.  The build time isn't worth it, even if you get better decoupling and encapsulation.

But I do segment large projects into many namespaces.  Turning those into components would be a huge help for dependency management.

**Comment by Pzixel** [comment]
@bondsbw I already have given you an answer: write code analyzer, 30 minutes of coding and you're done.

**Comment by bondsbw** [comment]
@Pzixel I understood that.  Obviously an analyzer would work.  The other proposal was even based on an NDepend "analyzer" that did this years before Roslyn existed.

Including this mechanism within the shipping product standardizes it.

**Comment by Pzixel** [comment]
@bondsbw then you could just create a nuget package with this analyzer and share it whenever you want :)

Seriously, I don't think we need this feature to be built in the language itself.

**Comment by CyrusNajmabadi** [comment]
> To sum it up: separate the logical concept of component from the physical concept of assembly

The issue i have is this:  That's a fine idea, but i don't know why it is tied to a namespace.  For example, i may still have a logical component that is spread over a few namespaces.  I may do this for my own organizational reasons, or because it makes sense for my public API.  Common things may go in my root namespace, with much more specialized stuff in my child namespaces.  

It sounds like you'd actually want something totally unrelated to accomplish this.  Something like:

```
component X {
  namespace Y {
    component class Z { } // only visible to others in my same component
  }
}
```

That said, i think this sort of thing always breaks down.  Eventually you have strange venn diagrams of things you want to be visible (i.e. Component A and B should see each other, and B and C shoudl as well, but not A and C).  So i think it's sorta worthless in the end.

Today, we have an actual solution throughout the toolchain:  Use assemblies, and use InternalsVisibleTo to indicate when components do share between them.  You can then merge those assemblies at the end of the day if you don't want to actually ship that way.  

This, to me, seems like a good enough solution without having to go spend an enormous effort to yet against try to come up with a componentization model.

**Comment by bondsbw** [comment]
@CyrusNajmabadi 
> (i.e. Component A and B should see each other, and B and C shoudl as well, but not A and C)

In the component proposal, this wouldn't be the case.  Just like assembly-based components, they must be acyclic.

>You can then merge those assemblies at the end of the day if you don't want to actually ship that way.

Shipping isn't the issue.  Build time is.

**Comment by CyrusNajmabadi** [comment]
> Shipping isn't the issue. Build time is.

Breaking into separate assemblies would help build time.  msbuild can easily parallelize those guys :)

**Comment by bondsbw** [comment]
I'm talking about hundreds of components.  Just how many cores do you have?  :laughing:

**Comment by erik-kallen** [comment]
@CyrusNajmabadi We don't need to solve all scenarios that could possibly be thought of, but I think it would be nice to have accessibility determined on something between the class and assembly level, and namespace seems to me like it would be a nice fit.

**Comment by alrz** [comment]
@CyrusNajmabadi your `component` idea is very similar to https://github.com/dotnet/roslyn/issues/8302. It doesn't suffer from "ven diagram" situation that you described, because every dependency must be explicitly specified via `requires` directives.

**Comment by CyrusNajmabadi** [comment]
> I'm talking about hundreds of components

That would be even better for parallelization.  Lots of opportunity there :)

**Comment by Pzixel** [comment]
@ChristopherHaws this is how it works today, isn't it? 😉

**Comment by ChristopherHaws** [comment]
@Pzixel No. Currently you can't have private or protected classes directly in namespaces, only in classes.

**Comment by MkazemAkhgary** [comment]
What you want is "internal". Can you please elaborate more on whats the use of private/protected class in namespace level? @ChristopherHaws

**Comment by Joe4evr** [comment]
@ChristopherHaws There's no way to express that in the IL: top-level types are either `public` or `private` (exposed as `ìnternal` in C#).

**Comment by Logerfo** [comment]
@Joe4evr Does this really need to be featured in IL? I mean, if this was just a c# language feature (making namespace level private in IL) that would be enough for me.

**Comment by DavidArno** [comment]
@Logerfo,

It is possible to mix languages in a single assembly (though VS doesn't currently support this directly). So you'd have the situation where eg a web project containing C# and VB.Net code would have different accessibility rules depending on the language used. Sounds messy.

**Comment by Logerfo** [comment]
@DavidArno I don't think that types declared with the `namespace` access modifier should be accessible from other assemblies, even with the same namespace. That being true, your concern is not an issue.

**Comment by DavidArno** [comment]
@Logerfo,

That's not what I said. You can mix languages **in the same assembly**, so that C# code would be unable to access types that the VB.Net code, in the same assembly, would be able to access.

**Comment by Logerfo** [comment]
@DavidArno how's that possible? and if so, why does both csproj and vbproj exist?

**Comment by Pzixel** [comment]
@Logerfo http://msdn.microsoft.com/en-us/library/ms366714.aspx

**Comment by jnm2** [comment]
Plus, everyone is familiar with ILMerge, right?

**Comment by honza77** [comment]
Did anybody considered something like Haskell or  ML modules? Am not sure how they differ from VB.Net modules.

**Comment by Chad077** [comment]
The suggested **namespace** modifier would fill the gap between the current **protected** and **internal** modifiers. There is no clean easy workaround for the lack of safe encapsulation at namespace branch (subsystem) level. I don't care for cross-assembly so what equates to "**internal namespace**" is fine and would be greatly appreciated.
