### ISSUE TITLE
Any updates on yield returning enumerables?

### ISSUE THREAD

**Issue by Mafii** [dotnet/csharplang#1143]
I couldn't find any newer answer to this statement that they won't consider it right now (2008):

https://connect.microsoft.com/VisualStudio/feedback/details/256934/yield-return-to-also-yield-collections

If it has been mostly forgotten, I would like to bring it up as a suggestion again!

Benefits and cost should be clear to the team, as they (including mads) have discussed it ~~half~~ a decade ago.

Wes' original article proposing the `yield foreach` syntax that I would prefer: https://blogs.msdn.microsoft.com/wesdyer/2007/03/23/all-about-iterators/

One of Wes' code examples

```
static IEnumerable<int> FromTo(int b, int e)
{
  if (b > e)
    yield break;
  yield return b;
  yield foreach FromTo(b + 1, e);
}
```

**Comment by Joe4evr** [comment]
Tentatively 👍 on this.

Best thing to do is make this a [full proposal](https://github.com/dotnet/csharplang/blob/master/proposals/proposal-template.md) instead of only linking to an old discussion.

**Comment by svick** [comment]
I believe this is a duplicate of https://github.com/dotnet/csharplang/issues/378.

**Comment by Mafii** [comment]
It is @svick . closing this.
