### ISSUE TITLE
tuple items can be variant?

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1156]
for example 

```
ISparse<out T> : IEnumerable<(IReadOnlyList<T> list, int index)>
{
}
```

I don't see how this could break contracts on covariance. I know though its the fact that tuple is struct and not variant but this can be special cased and be treated some how?

for sake of completeness here is contravariant example. 

```
IConsumer<in T>
{
    void Consume((T item, int count) t);
}
```

**Comment by ufcpp** [comment]
C#'s tuple is the `ValueTuple` struct. So, this is the same issue as your recent request https://github.com/dotnet/csharplang/issues/1152

**Comment by MkazemAkhgary** [comment]
@ufcpp yes but not entirely, ValueTuple is mutable. but as long as tuple is passed by value its items can be variant. (maybe this statement can also hold for other structs as well)

**Comment by ufcpp** [comment]
@MkazemAkhgary 

> maybe this statement can also hold for other structs as well

Yes. And thus, the answer is the same as https://github.com/dotnet/csharplang/issues/1152#issuecomment-347524076

> This would be a large undertaking including required CLR support, for marginal gain in language expressiveness. We don't think this is where we want to invest.

**Comment by ufcpp** [comment]
FYI, IMO, a struct could be covariant if all of its fields are covariant.
https://github.com/dotnet/csharplang/issues/317#issuecomment-325193165

**Comment by MkazemAkhgary** [comment]
@ufcpp  glad I'm not alone at this one. so its already some thing methodical.

as I develop experience in programming, I some times feel need for it. data redundancy is something that I prefer to avoid. subtyping (as you linked that wiki page) helps to achieve this. 

now with usage of tuples in c# I think its time to consider this variant struct/record fields in wider scales.

**Comment by CyrusNajmabadi** [comment]
> now with usage of tuples in c# I think its time to consider this variant struct/record fields in wider scales.

It will be considered if it a widespread problem that is actually hampering development in a significant way.  I'm not seeing anything to demonstrate that that's the case.

Indeed, i'm not even seeing any examples here that i find compelling as to why this would be needed...

**Comment by MkazemAkhgary** [comment]
@CyrusNajmabadi  I understand. the thing is c# 7 is new, not every one is overwhelmed with it. it takes time until noticeable amount of developers encounter similar problems. 

there could be many examples and usages, obviously if I think and mention a few, you would say it doesn't worth the cost it takes. that's true until significant amount of developers have encountered similar problems and it becomes substantial.

the fact that I cant use tuples with covariant feature can be easily solved. with additional overhead in my program of course. (instead of using tuple I have to make custom type that supports covariant) so not a big deal 😸

**Comment by CyrusNajmabadi** [comment]
> it takes time until noticeable amount of developers encounter similar problems.

How about we fix things then, instead of proactively trying to address this that may actually not be problems? :)

> there could be many examples and usages

I would love to see some.  It's hard to state if there's an actual issue if we can see real world use cases that are truly impacted by this.

**Comment by CyrusNajmabadi** [comment]
Note: iirc, i asked you (but maybe it was someone else) to try to put more detail in language suggestions that helped demonstrate why the feature was worth the cost, and why it was somethign that would substantively benefit a large set of users.  That critique still applies.  

Put it this way:

I can't tell if this is a real proposal that addresses a really improtant use case.  Or if it's just something you ran into as a one-off when developing your own app that you wish made your life better.  I can't even tell what your app does or if you've designed it well.  And, as such, maybe this an anti feature to deal with problems in your own app.  Trying to make a language change without clearer understanding of the situation is not likely to happen :-/

**Comment by MkazemAkhgary** [comment]
>i asked you (but maybe it was someone else) to try to put more detail in language suggestions 

Yes It was you :) . How ever i think i made this general enough to make it seem worthy. Billieve me or not, I have iterated many times over different solutions in my project before i start to propose here.

So i thought it _can_ benefit many users. Tuple usage is good excuse for me! i think people will see limitation there and want some free imagination :)

>I can't tell if this is a real proposal that addresses a really improtant use case. Or if it's just something you ran into as a one-off when developing your own app that you wish made your life better

while it was something i faced during developement, it is unlikely that will not be experienced by others as well. Im not saying this is some thing that every one uses though.

Bilieve me or not, im discarding lot of proposals in my head already with same reason as you explained, these are a few that pop out here ;)

Enough of babbling. Here is some usage. 

1-in case tuples are used as generic argument of some type you can have tuple as accumulator for multiple variables in covariant way.

In my case it was sparse array. So array could be enumerable of value and index so you easily know position of enunerator without much pain. Be it covariance you can manupulate multiple sparse arrays of variant types easier. (Since im designing an API i want that to work best in different situations. So more features less limitation hehe)

Hey, you use tuple usually as generic argument or as return of some method or function. These are all places that can potentially benefit from this feature. 

2-Making return type of Tasks covariant. Either ValueTask or Task can be covariant. If im not mistaken, they dont take any input once they are initialized. (Im not sure if this is real deal though)

3-Value Enumerables here #974 could benefit from covariance without being boxed.

4- anything else that comes to mind of reader. Im not super human or genius or anything! Otherwise i wouldnt be here :)

---

How is that supposed to work for mutable structs that are passed by value

It requires CLR change. for mutable structs new instance of struct with new generic arguments can be cloned.

For covariance classes and immutable structs see #1152 

----

Ok thats all i could do to defend this proposal. If it wasnt enough then its eligilable for closing :[

**Comment by aluanhaddad** [comment]
I ran into this recently. It would be nice if tuples implemented a covariant read-only interface. Obviously some performance overhead but the flexibility would be much appreciated.

**Comment by MkazemAkhgary** [comment]
I don't think interface helps here. since it causes boxing. if its one item being boxed its not problem. but for `IEnumerable` that can have any number of items in it, its not ideal solution.

`ValueType` is mutable. we need something like `ImmutableValueType`, there has to be a way of noting this via good syntax.

I think now its better to propose a way to declare immutable classes. a way to strictly define immutable classes or structs, those are inherently covariant compatible and have other cool stuff properties. so it does provide much more benefit than just this proposal. 

so no change in CLR but just extra feature for CLR making c# and other languages better.
