### ISSUE TITLE
Static interfaces

### ISSUE THREAD

**Issue by drozdekl** [dotnet/csharplang#1164]
Please add better support for interfaces on static members. It is currently possible and useful but  it also uses a lot of generic contraints which are just code boilerplate. I am not sure about the syntax and really don't care about it, probably it would be just syntactic sugar as for example yield return is. The only thing I would really like is to have some better way of writing code equivalent to*:

```C#
using System;

interface Interface<T, StaticT>
    where T : Interface<T, StaticT>
    where StaticT : Static<T, StaticT>
{
    void NormalMethod();
}

interface Static<T, StaticT>
    where T : Interface<T, StaticT>
    where StaticT : Static<T, StaticT>
{
    void StaticFunction();
}

class Static<T> : Static<T, Static<T>>
    where T : Interface<T, Static<T>>
{
    public void StaticFunction() =>
        Console.WriteLine("I am static!");

    public void NormalMethod(T @this) =>
        @this.NormalMethod();
}

class Abc : Interface<Abc, Static<Abc>>
{
    public void NormalMethod() =>
        Console.WriteLine("I am regular method!");
}

static class Program
{
    static void Main()
    {
        Abc x = new Abc();
        Static<Abc> y = new Static<Abc>();

        y.StaticFunction();
        y.NormalMethod(x);
    }
}
```

* I know that `StaticFunction` is not in fact static because it is called on y which is of type `Static<Abc>`. I would like y to be hidden because there should be exactly one instance of `Static<Abc>`. It would be nice if some syntactic sugar auto generated all methods with `@this`. 

Maybe this is antipatern which only I am using but I think that if there would not be so much contraints then static contracts would be used more.

**Comment by HaloFour** [comment]
#164 would enable this.  Normal interfaces can't apply to static members as they can't be invoked virtually as you can't have a vtable without an instance.

**Comment by drozdekl** [comment]
@HaloFour I know that static interfaces don't have this pointer thus you can't use them in interfaces. In my applications I use `Static<T>` instead of `static` because it leads to existence of this pointer which leads to possibility of using `Static<T>` in interfaces. The thing I am complaining about is that there is so much boilerplate code to make this work... 

Adding of method `void f(int a, int b)` to `Abc` leads to adding
```C#
void f(T @this, int a, int b) => @this.f(a, b);
```
to `Static<T>` to make it work. It is annoying.

**Comment by drozdekl** [comment]
I have read #164 and that completely covers the whole problem about static interfaces. In fact there were interesting part about the implementation of the whole thing so I will maybe optimize the pattern I wrote above. 

Because shapes completely solve the problem I am closing the issue now.
