### ISSUE TITLE
Expressions like 10 < x < 20

### ISSUE THREAD

**Issue by luetm** [dotnet/csharplang#1175]
It's a small thing, but I think it would make a lot of .Where() clauses much more readable. Just convert it to 10 < x && x < 20 internally.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/1128
https://github.com/dotnet/csharplang/issues/217
https://github.com/dotnet/csharplang/issues/847
https://github.com/dotnet/csharplang/issues/420

**Comment by luetm** [comment]
Ok thank you. Feel free to close ;)

**Comment by DavidArno** [comment]
@luetm,

You need to close it, please.
