### ISSUE TITLE
Allow type inference for "is" operator

### ISSUE THREAD

**Issue by Makeloft** [dotnet/csharplang#1183]
Look at following sample

```
private static object CreateInstance(Type type, Map snapshot, ReplicationProfile replicationProfile) =>
    type.IsArray && type.GetElementType() is Type elementType
        ? (snapshot.TryGetValue(replicationProfile.SetDimensionKey, out var dimensions)
            ? Array.CreateInstance(elementType, ((Set) dimensions).Cast<int>().ToArray())
            : Array.CreateInstance(elementType, ((Set) snapshot[replicationProfile.SetKey]).Count))
        : Activator.CreateInstance(type);
```
Statement
`type.GetElementType() is Type elementType `
may be simplified to
`type.GetElementType() is elementType `
because method return value of type 'Type'

Another possible case
```
var value = new AnyType();
...
if (value is AnyType && value.GetType() is Type valueType) { ... }

if (value is && value.GetType() is valueType) { ... }
```
It is nice to have more short statement
`value is`
instead
`value is AnyType`
which equivalent
`value != null`

Extension methods
```
    public static class CastExtensions
    {
        public static T Of<T>(this object o) => (T) o;
        public static bool Is<T>(this T o) => o != null;
        public static bool Is<T>(this object o) => o is T;
        public static T As<T>(this object o) where T : class => o as T;
    }
```
        public static bool Is<T>(this T o) => o != null; /* equals to 'o is T'; 
Type inference for generic method cause simplification of use: 
`string str = ...`
call 
`str.Is<string>() `
may converted into 
`str.Is()`

Seems that this logical beauty may be expanded to "is" operator too.

P.S. Sometimes method 'Of' is very useful to avoid crazy brackets
`((Type1) ((Type0) item).Property0).Property1 = value;`

`item.Of<Type0>().Property0.Of<Type1>().Property1 = value;`

Possible, nice to have something like operator "of"
`item of Type0.Property0 of Type1.Property1 = value;`

**Comment by yaakov-h** [comment]
Do `type.GetElementType() is var elementType` and `value is {}` solve your problem for inferred typing and null checks respectively?

The latter is earmarked for C# 7.3, I think.

**Comment by Makeloft** [comment]
Thanks! Seems that it is what I want. Only `value is {}` looks strange. What about `value is` ?

**Comment by Joe4evr** [comment]
`value is {}` is a property matching pattern: it's to be used like `if (value is { Foo = "Hello", Bar = 42 })`. This translates roughly to `if (value != null && value.Foo == "Hello" && value.Bar == 42)` (though potentially with slightly better code-gen). An empty property pattern is then equal to just doing a null-check.

**Comment by Makeloft** [comment]
Interesting feature!
What about to made property matching pattern `{ }` optional like both `new Class()` and `new Class { }` ?

**Comment by stepanbenes** [comment]
@Makeloft It looks like you did not finish the

**Comment by yaakov-h** [comment]
There was another proposal for `if (?value)` to be a thing, but considering the pattern matching expression above, it would add to the language a _third_ way to do the same thing, and I reckon it won't make any headway.

**Comment by Makeloft** [comment]
@yaakov-h I think that cases `value is` and `value is { }` is the one feature with fully complete generalization of usage like `new Class(x, y)` and `new Class(x, y) { }`.
But `?value` really is new syntax feature and your argument is not very suitable into our current case.

**Comment by yaakov-h** [comment]
@Makeloft 

`new Class (x, y) { Foo = Bar };` calls the constructor and then has a property initialiser with a single property.

`new Class(x, y) { };` calls the constructor and then has an empty property initialiser.

`new Class(x, y);` calls the constructor;

In all cases, there's a constructor call. On the other hand,

`value is { X = 5 }` is a pattern matching expression with an implicit null check.

`value is { }` is an empty pattern-matching expression with an implicit null check.

`value is` is nonsensical. There's nothing.

You can't fairly compare the two.

**Comment by Makeloft** [comment]
From my point of view
`value is` is implicit null check like `new Class(x, y)` calls the constructor

**Comment by Makeloft** [comment]
Not actual. May continued into #1054
