### ISSUE TITLE
Types parametrized by const expression

### ISSUE THREAD

**Issue by drozdekl** [dotnet/csharplang#1185]
I am not sure whether this feature is promoted or not, in fact I couldn't find any similar proposal. I am also not sure if there are deep reasons why this feature is not suitable for C# language. In that case I will close the issue.

The thing I would use pretty much could look like (I don't care about syntax. Maybe there are better options and maybe this whole feature is not usable at all because my usage of C# is specific):

```C#
interface IMagicBlock<const int dim>
	where dim > 1
{
	bool IsSubBlockOf<n>(Block<n> block)
		where n >= dim;
}

class Block<const int Dimension> :
	IMagicBlock<Dimension>
	where Dimension > 1
{
	bool IsSubBlockOf<n>(Block<n> block)
		where n >= Dimension
	{
		...
	}
}

Block<3> a = ...
Block<5> b = ...
var c = a.IsSubBlockOf(b);
var d = b.IsSubBlockOf(a); // COMPILE TIME ERROR: 3 >= 5
```

That's it. Developers could parametrize class or interface by const expression which could be even constrained by const predicate.  In the above the type of`Block<3>` is another type than `Block<5>` which is the same as type of `Block<4+1>`. Every usage of `Block<n>` generates new class which fulfills the template of Block. 

The `Dimension` can currently be property of `Block` but this solution throws away the compile time check. Currently I sometimes simulate this feature where the const expression is enum (there is a finite set of values and every single one I simulate by interface). This proposal does not solve any currently unsolvable problem, it just brings stronger type checking into the language. With these proposal there could even be fixed arrays which could look like `Array<T, const int Length> where Length > 0 { ... }`. I think that it is the thing which is expected - assigning value of fixed array of length 5 into fixed array with length 3 should be compile time error and there is many other similar cases where this feature would be useful. Anyway I understand if there are consequencies or reasons why this just don't fit into language.

I am not sure about the syntax and don't care about it much. I have just wanted to share my idea. I work a lot with multidimensional math objects and this kind of templating is the thing I would use in many cases because of strong type checking. It is even possible to generate these class by hand or auxiliary script but it is annoying.

**Comment by MkazemAkhgary** [comment]
you can already have such behavior by passing parameters to constructor and control those parameters inside constructor (either throw or coerce value).

 yes, it will not be checked at compile time, but how could it be checked at compile time any way?

**Comment by Joe4evr** [comment]
This looks like a Code Contract. And yes, using a constructor would be a good solution.
> how could it be checked at compile time any way?

Analyzers.

**Comment by drozdekl** [comment]
@Joe4evr 

Using constructor is fine but it is not possible to write something like:
```
class Dim5Structure : Block<3>
{
   ...
}

class Dim7CompletelyDifferentStructure : Block<7>
{
    ...
}
```

I currently can generate something like `Block_3` and `Block_7` as two classes which inherit from Block that has readonly property `Dimension` which is set by constructor. But it is annoying so I resignate to that kind of type check which is a little pity. 

The types could be parametrized only by const expression which is the thing that imo allows compiler to check all contracts. The suggested solution with readonly property set by constructor is unnecessary general because it allows you to write:

```
for(int i = 0; i < 10; i++)
{
    Block b = new Block(i);
}
```

which should not be allowed. If I'm not mistaken that all const expressions are evaluated at compile time so there should not be problem to check contracts.

**Comment by drozdekl** [comment]
The constracts in fact aren't the main feature. I have written these examples to show that with this feature it would even be possible to make contracts a bit easier to implement. It would be sufficient to just allow unconstrained const expressions like:

```C#
enum ListType {
    Empty, DefaultBehaviour, CustomBehaviour, SpecialBehaviour_1, ..., SpecialBehaviour_n
}

class MyList<const ListType Type>
{
    ...
}

class ExtendedList : MyList<ListType.CustomBehaviour>
{

}
...
MyList<ListType.DefaultBehaviour> a  = new();
ExtendedList b = new();
...
```

I think that this feature wouldn't break anything in the language but maybe I am wrong. In that case I will close the issue.

**Comment by CyrusNajmabadi** [comment]
> @Joe4evr

> Using constructor is fine but it is not possible to write something like:

```c#
class Dim5Structure : Block<5>
{
   ...
}
```

Sure there is.  You'd write it as:

```c#
class Dim5Structure : Block
{
    public Dim5Structure() : base(5) { }
}
```

And you've have your analyzer do the verification.

**Comment by CyrusNajmabadi** [comment]
> The suggested solution with readonly property set by constructor is unnecessary general because it allows you to write:

```c#
for(int i = 0; i < 10; i++)
{
    Block b = new Block(i);
}
```

> which should not be allowed

Then your analyzer would check for that and report an error :)

**Comment by drozdekl** [comment]
@CyrusNajmabadi  Thanks :) I am definitely going to try programming an analyser but currently it seems to me difficult similarly like programming sw for a nuclear plant. It seems that I should close the issue now.

**Comment by CyrusNajmabadi** [comment]
> I am definitely going to try programming an analyser but currently it seems to me difficult similarly like programming sw for a nuclear plant.

It really isn't :)

The majority of IDE refactorings/code-fixes are driven by analyzers.  You can also see many examples of them here: https://github.com/dotnet/roslyn-analyzers

There's a learning curve to understand and effectively utilize the Roslyn API.  That's going to be the case no matter what as the API has to completely provide access to the entirety of the C# and VB languages.  However, once you start experimenting and writing these, you'll find yourself becoming quite proficient.  Several community members have done this and have contributed several analyzers/fixers/refactorings to the roslyn codebase and the VS ide itself :)

Good luck!  Also, i recommend https://gitter.im/dotnet/roslyn if/when you run into issues/questions.

**Comment by ufcpp** [comment]
usecases:

- finite field tyeps: https://gist.github.com/ufcpp/290132dc8b7420937807c68cbd48648e
- bit types: https://github.com/ufcpp/BitFields

```cs
public interface IConstant<T> { T Value { get; } }

public static class ConstantInt
{
    // these structs are psudo-constant shapes.
    // (https://github.com/dotnet/csharplang/issues/164)
    public struct _0 : IConstant<int> { public int Value => 0; }
    public struct _1 : IConstant<int> { public int Value => 1; }
    public struct _2 : IConstant<int> { public int Value => 2; }
    // ...
}

public unsafe struct Bits<N>
    where N : IConstant<int>
{
    // N is pseudo-constant but not actually constant.
    // I want the following "fixed size buffer".
    private fixed byte bytes[default(N).Value / 8];
}
```

**Comment by drozdekl** [comment]
I can think of many usecases where this feature could applied. It would be possible for example extend definition of constants. Struct can be considered constant if it has no fields. We could write:

```C#
const struct Pair<int Fst, int Snd> { }
// It would not be typical struct which certainly can't be constant even if there are no fields
// const structs should be new basic type. All Pair's differ only by their `typeof(...)`. 
```

And compiler should allow this definition if I understand the concept of compile time constants properly. There are no fields, the only thing we expect is that all parameters are passed as constexpr. The usage could be:

```C#
class ImportantDates
{
    const Pair<24, 12> Christmas;
    const Pair<29, 2> FathersBirthday;
    ...
}
```

I can think of many applications and will investigate more how to simulate these concepts similarly as ufcpp (thanks for your code samples).

I would also use something like:
```C#
struct Number<byte Bits> 
{
    bool ConcatOverflows(Number<Bits2> other) => ~(Bits & Bits2) > (Bits | Bits2);
    void Concat(Number<Bits2> other) => ... // and + shift + and
}
```

And many other similar structures which I can't describe well because they are a bit complicated. I will definitely try to find way to better type checking at compile time because there is too many cases which could go bad at run time.
