### ISSUE TITLE
`in` parameter and anonymous method

### ISSUE THREAD

**Issue by chrisdunelm** [dotnet/csharplang#1187]
Is it possible to define an anonymous method with an `in` parameter?

I have a delegate: `delegate TResult InFunc<T1, TResult>(in T1 arg1)`

Is it possible to assign an anonymous method to an instance of this delegate?

I've tried:
`InFunc<int, bool> fn = in x => x > 0;`
`InFunc<int, bool> fn = (in x) => x > 0;`
`InFunc<int, bool> fn = (in x => x > 0);`

But none work, all give compile-time errors.

Is this supported? Thanks

**Comment by HaloFour** [comment]
Try:

```cs
InFunc<int, bool> fn = (in int x) => x > 0;
```

IIRC it's the same rules that the compiler enforces with `ref` or `out` parameters in a lambda.  You always have to also specify the parameter type.

**Comment by chrisdunelm** [comment]
That works :) Thanks for your help
