### ISSUE TITLE
Allow assignment in if clause and check for nullability

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#1197]
Alternative for #1192 #792 #306

I think instead of using pattern matching clause we could reuse the syntax from other language. Just the plain old assignment operation

```C#
if(var x = someObj.SomeField.SomeProperty.SomeMethod())
{
    // x here if it not null
}
```

We could avoid the ambiguous as of C and JS by only allow declaration of variable in `if` and not allow assignment to exist variable

Like so

```C#
object a = null;

// OK, normal
if(a == null)
{
}

// OK, new variable assigned
if(var b = someObj.SomeField.SomeProperty.SomeMethod())
{
    // b here if it not null
}

// ERROR, cannot assign existing variable in if clause
if(a = someObj.SomeField.SomeProperty.SomeMethod())
{
}

// ERROR, unassigned variable cannot use equal operator
if(var c == someObj.SomeField.SomeProperty.SomeMethod())
{
}
```

Concern : Should this also work with nullable struct? How about custom nullable (such as #889) in the future

**Comment by Makeloft** [comment]
I like it. But this is very closely to the pattern matching
```
if (item.SomeMethod() is AnyType b)
{
}
```
And if 'is var' will be fixed into C# 8
```
if (item.SomeMethod() is var b)
{
}
```

**Comment by svick** [comment]
Assignment to an existing variable in `if` is already valid. For example, the following is valid code (and doesn't even produce a warning):

```c#
void M(bool b1, bool b2)
{
    if (b1 = b2)
    {
    }
}
```

Also, I would find it very confusing if the code `if (var x = y)` performed a `null` check: Nowhere else in C# does `var` mean "not `null`" and `if` never performs a `null` check by itself, so I think the combination of `if` and `var` shouldn't do it either.

**Comment by yaakov-h** [comment]
#973

**Comment by theunrepentantgeek** [comment]
> We could avoid the ambiguous as of C and JS by only allow declaration of variable in if and not allow assignment to exist variable

This would be a breaking change that would a lot of people.
