### ISSUE TITLE
Records Primary Deconstructor?

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1204]
in csharplang/proposals/records.md 
will the record have a Primary Deconstructor (a default Destruct method with the same field order?)
Also: I suggest to add a method named ToTuple to convert the record to a tuple. It will be nice also to create a record based on a tuple.

**Comment by DavidArno** [comment]
That's probably a question for @gafter, who is likely to reply "maybe" to the first question. As far as I know, the design for records is still very much "up in the air" still.

**Comment by gafter** [comment]
@MohammadHamdyGhanem When the records proposal is revised, the `operator is` part will be replaced by a similar thing based on `Deconstruct`. The name has changed, but the behavior will be similar.

I'm not sure I understand the value in the proposed record-tuple conversion. Please open a new issue with your proposal, with an explanation of the benefits.
