### ISSUE TITLE
Add "matches" keyword

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1206]
I suggest to add a keyword to be used in string pattern matching in if statements like this:
```
string x ="string";
If (x matches "Pattern")
{
}
```
this can be the compact form of this code:
```
string x ="string";
Regex s = new Regex("Pattern");
if (s.Match(x).Success)
{
}
```
Regex Class can do more complex tasks of course, but checking the pattern of short strings is a more common task.

**Comment by HaloFour** [comment]
This is already very easily a one-liner:

```cs
if (Regex.IsMatch(value, pattern)) { }
```

**Comment by stakx** [comment]
Do we really need a language feature for everything that's in the BCL, these days? 😒 

Just use `Regex.IsMatch(input, pattern)`.

**Comment by HaloFour** [comment]
I would like to see some kind of support for regex in pattern matching, though:

```cs
if (person is Student { Course is { Name is matches("Advanced") } course } student)
{
    Console.WriteLine($"{student.Name} is taking the advanced course \"{course.Name}\".");
}
```

Or a generalized way to create helper patterns like this.

**Comment by DavidArno** [comment]
@HaloFour,
If I understand you correctly, I believe that's exactly the sort of scenario that active patterns would solve.

**Comment by Richiban** [comment]
Actually, using regexes is beautiful with pattern matching:

```fsharp
module Regex =
    open System.Text.RegularExpressions
    
    let (|RegexMatch|_|) regex s =
        if Regex.IsMatch(s, regex) then Some () else None
        
    let (|RegexMatches|) regex s =
        Regex.Matches(s, regex)
        |> Seq.cast<Match>
        |> Seq.toList
        
open Regex

match "hello heap hat at" with
| RegexMatches "x" [] ->
    printfn "This regex doesn't match"
| RegexMatches "h\w+" (x::y::_ as m) ->
    printfn "There are at least two matches for this pattern: %A" m
| RegexMatches "hello" [m] ->
    printfn "There is exactly one match for this pattern: %A" m
| _ -> 
    failwith "Fell through"
```

Note: This makes use of active patterns, recursive patterns, list patterns.

**Comment by CyrusNajmabadi** [comment]
> Regex Class can do more complex tasks of course, but checking the pattern of short strings is a more common task.

Here's the problem: when you start adding these sorts of things to the language then all those 'complex' things that were left out (that you think aren't important enough) are the things that lots of other people  complain about and what in the language.  For example, people will want ways to say "i want thsi regex to be compiled" or "i want this to be a case insensitive regex" or "i want whitespace ignored in this regex".

We do not like adding language features that make one scenario only *slightly* better.  We like adding language features that compose and can broadly improve a whole host of scenarios.

**Comment by AustinBryan** [comment]
You can use an extension method using the code from HaloFour, so it looks like:

```csharp

if (str.Matches("pattern"); {}
```

**Comment by MohammadHamdyGhanem** [comment]
@AustinBryan 
I've created Verex: https://github.com/MohammadHamdyGhanem/Verex .
Now, I can do this:
```
            if ((AnyWordChar[2, 6] + AssertNextIs("s" + NonWordEdge)).IsMatch("this is a test"))
                Console.WriteLine("text contains words that end with 's'.");
```
