### ISSUE TITLE
XML code comments and 'in' parameters

### ISSUE THREAD

**Issue by andi6** [dotnet/csharplang#1209]
I don't find a way to reference a method with an 'in' parameter in xml code comments. Also VisualStudio (15.5.2) seems to be unable to do it.

If I take a sample method:

`public void MethodWithInPar(in double dummy) { }`

VisualStudio suggests

```
		/// <summary>
		/// This is the summary for <see cref="MethodWithInPar(double)"/>.
		/// </summary>
```

with xml comment generation enabled in project settings (classic .NET framework project) I get CS1574.

**Comment by andi6** [comment]
@HaloFour 

I've tried this also: CS1574

**Comment by andi6** [comment]
Sorry, wrong button

**Comment by gafter** [comment]
Issue moved to [dotnet/roslyn #23957](https://github.com/dotnet/roslyn/issues/23957) via [**ZenHub**](https://www.zenhub.com/)
