### ISSUE TITLE
Allow => everywhere

### ISSUE THREAD

**Issue by banjouuid** [dotnet/csharplang#1210]
It could be nice to have: 

`      try => FilePicker.Open(file); 
       catch=> Debug.WriteLine("error");`

Rather than:

` try
            {
                FilePicker.Open(file);
            }
            catch
            {
                Debug.WriteLine("error");
            }`

 Let me know what you think.

**Comment by eyalsk** [comment]
Well, it's almost everywhere but maybe bringing it to try/catch/finally block make sense at this point.

**Comment by Vlad-Stryapko** [comment]
I'm a huge fan of` =>` but it doesn't really look good in this particular case. It makes me think `try` and `catch` are semantically disconnected from one another.

**Comment by eyalsk** [comment]
@Vlad-Stryapko  It should probably be something like this:

```
try => FilePicker.Open(file) catch => Debug.WriteLine("error");
```
But honestly, the following looks much better:
```
try FilePicker.Open(file) catch Debug.WriteLine("error");
```
I can't see the benefit of having the arrow there.

**Comment by HaloFour** [comment]
What about `catch` blocks that handle specific exceptions?  What about multiple `catch` blocks?  I don't see how the `=>` syntax deals with the issue of ambiguity of correlating `catch` blocks with nested `try` blocks:

```cs
try =>
try => DoSomething()
catch (FooException e) => HandleFooException(e)
catch (BarException e) => HandleBarException(e) // where do I belong?
catch (BazException e) => HandleBazException(e) // where do I belong?
finally => CleanUp() // where do I belong?
```

Also, your proposal title is "Allow => everywhere" but you only touch on `try`/`catch` blocks.  `=>` isn't allowed in most control statements.

**Comment by eyalsk** [comment]
@HaloFour Well, in my opinion nested exceptions shouldn't be allowed.

**Comment by banjouuid** [comment]
The point in here it's make code more readable, if we can make it from {} to => and from => to not having anything at all as  `try FilePicker.Open(file) catch Debug.WriteLine("error");` would be brilliant too

**Comment by alrz** [comment]
```
try =>
try =>
```
try is not an expression, I suppose the grammar is `try => expression`

**Comment by CyrusNajmabadi** [comment]
The problem with this is that => means one of two things depending on context.  It either means ```{ expr; }``` or it means ```{ return expr; }```.  That's why it can be easily used with lambdas, methods, constructors, etc.  it's known from context which of those forms is meant.  

With statement forms, it isn't clear.  if i have:

```c#
int Foo()
{
    try => Bar();
    catch => Baz();
    return Quux();
}
```

Does that mean:

```c#
int Foo()
{
    try { return Bar(); }
    catch { return Baz(); }
    return Quux();
}
```

or

```c#
int Foo()
{
    try { Bar(); }
    catch { Baz(); }
    return Quux();
}
```

?

**Comment by MkazemAkhgary** [comment]
Well at the end of the day it saved only two characters.

**Comment by yaakov-h** [comment]
One.

**Comment by eyalsk** [comment]
The only proposal that I really want that yes, saves on characters and nesting is the namespace one but most of these _niche_ proposals just don't cut it for me and probably for many of us.

**Comment by magol** [comment]
I suggest following pattern

 Foo() catch (IOException) Debug.WriteLine("error");

This pattern is restricted to only one catch.

**Comment by yaakov-h** [comment]
I'm not so sure that swallowing exceptions should be made easier...
