### ISSUE TITLE
Dictionary strong key names

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1216]
I suggest to add this form to the dictionary initializer:
```
var Cities = new Dictionary<string, int>()
       {NewYork = 10, London = 5, Cairo = 12};
```
Note that no quotations around key names, not only for simplicity, but also to force us to choose valid names to be used as members. The complier can use this syntax to define strong key names seen only in the dictionary scope so they don't affect other variable names. These keys can be used as follows:
```
Console.WriteLine(Cities.Cairo);
Cities.London = 3;
```
Or by the traditional ways:
```
Console.WriteLine(Cities[Cairo]); 
Cities[London] = 3;
```
This will prevent key names mistyping bugs, and give us intillisense auto completion.
To do this, the compiler can generate a new class that inherits the Dictionary class, and add properties to it with the key names from the initializer!

**Comment by HaloFour** [comment]
I don't see why any syntax changes are necessary to enable auto-completion in Intellisense for dictionary types.  That can be done through normal metadata, which this proposal would still have to find a way to furnish otherwise those names would be immediately lost at every boundary.  How do you propose to solve that problem?

This syntax also collides a great deal with existing syntax.  I don't see any value in trying to turn arbitrary types that happen to have a `string` indexer into some kind of quasi-dynamic type.  

For previous discussion into similar ideas look at https://github.com/dotnet/roslyn/issues/3555.

**Comment by HaloFour** [comment]
Also:  [C# Language Design Notes for Apr 21, 2014](https://roslyn.codeplex.com/discussions/543875)

**Comment by MohammadHamdyGhanem** [comment]
First of all, I find the syntax 
`{NewYork = 10, London = 5, Cairo = 12};`
easier, shorter and ore readable than:
`{ {"NewYork" , 10 }, {"London" , 5 }, {"Cairo", 12} }; `
How Can it be done?
The compiler can create an instance of the dictionary, initialize it, and use the dictionary keys to validate the syntax and push them into intillisense list.
The ".key" notation is a new feature. I don't know how hard can it be for the compiler. If we achieve strong key names, I think it will be more convenient to use the ".key" syntax.

**Comment by MohammadHamdyGhanem** [comment]
>  If this causes an outcry, well that’s different feedback, and we can then act on that.
let's outcry!

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

You can use the following syntax:

```cs
var Cities = new Dictionary<string, int>()
       {["NewYork"] = 10, ["London"] = 5, ["Cairo"] = 12};
```

There's no need for more syntax to do the same thing.

> let's outcry!

Why?  The reason nobody cared before is that this syntax adds virtually nothing to the language.  At *best* it shaves a tiny number of characters from indexer operations, but only when those indexers are identifier-compatible strings.  The syntax itself would do nothing to improve the Intellisense story, and whatever metadata provider could would be better applied to indexers in general without requiring any modifications to the language.

**Comment by MohammadHamdyGhanem** [comment]
In fact I had another solution, but I thought it may be big and has a little effect except on dictionaries, so, I changed it.
This solution involves defining const string nominations like this:
`public nomin cityNames{ NewYork, London , Cairo};`
This is a shorthand for:
```
public nomin cityNames{ 
     NewYork = "NewYork", 
     London = "London", 
     Cairo = "Cairo"
};
```
of course you can use different values than the names:
```
public nomin cityNames{ 
    NewYork = "New York City", 
    London = "London City", 
    Cairo = "Cairo City"
};
```
So, you can use these string constants like this 
`Citis[cityNames.London] = 10;`
This way we can group string constants by thier function, and this is better than using strings through project resources.
so, in 2nd stage, the compiler can define a nominator for the dictionary initializer whatever it's synatax.

**Comment by HaloFour** [comment]
```cs
public static class CityNames
{
    public static readonly string NewYork = "New York City";
    // etc.
}
```

**Comment by MohammadHamdyGhanem** [comment]
That's right, but the nomin syntax is a more compact, and compiler can use it to produce this full class.
And, the initialization can be:
```
var Cities = new Dictionary<string, int>()
      nomin of {NewYork = 10, London = 5, Cairo = 12};
```

**Comment by HaloFour** [comment]
> but the nomin syntax is more compact

It would make substantially more sense to argue for `enum` to be expanded to support `string` as well as integral types.  Then you wouldn't need this weird "nomin" construct, and you could use these things in a more type-safe manner.

> And, the initialization can be:

Which is even weirder looking, more verbose, and buys you nothing over the existing syntax.  At least with proper enums you can reference type-safe members directly.

**Comment by MohammadHamdyGhanem** [comment]
Enum is a numeric type that can be casted to int and other numeric types, so, I do not thik C# can allow this not to breake existing code. There's a need for new string const container.
The last syntax tells compiler to create a new nomin, and justifies writing key names as if they are variabes not letirals.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> Enum is a numeric type that can be casted to int and other numeric types, so, I do not thik C# can allow this not to breake existing code.

Enums can also be `char`.  This wouldn't be a breaking change as there are no existing enums of this type.  Nor is there an expectation that you can always cast an `enum` to some arbitrary integral type, as they can be any integral type, which can already result in an overflow exception.

> The last syntax tells compiler to create a new nomin, and justifies writing key names as if they are variabes not letirals.

What's the point of doing that?  That couldn't possibly be public, and since the key still remains a typeless string that provides zero benefit to any consumer of that dictionary.

**Comment by MohammadHamdyGhanem** [comment]
Can I propose the string nomin as separite issue? or should I modify this isuue to include it?

**Comment by MohammadHamdyGhanem** [comment]
Or should you propose the string enum?

**Comment by MohammadHamdyGhanem** [comment]
> What's the point of doing that? That couldn't possibly be public, and since the key still remains a typeless string that provides zero benefit to any consumer of that dictionary.

Why can't they be public?
The compiler can produce the static class that the nomin generates as a public class. This way it can be used even from another project.
There of course will be a naming convention the compiler uses to bind the nomin to the dictionary, such as: Cities , ___CitiesDictinaryNomin.

**Comment by MohammadHamdyGhanem** [comment]
Or, the Dictionay class can contain a field that holds the generated nomin class name, so it can be used if the dictionary is passed as a parameter.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

Just to note that indexer/dictionary initializers have nothing to do with `Dictionary<TKey, TValue>`.  It applies to literally any type that implements `IEnumerable` that happens to have an indexer, including any custom type.

Also, even if `Dictionary<TKey, TValue>` was modified to include a new field to carry a class name, how would that help given that the value of that field could only be read at runtime?  That wouldn't give the compiler any useful information to go on and it wouldn't provide any form of type safety that a proper enum could.

**Comment by MohammadHamdyGhanem** [comment]
Another approach:
The compiler can generate a new  class that inherits the Dictionary class, and add properties to it with the key names from the initializer!
I think this is the optimum solution.
But I'm still a fan of the syntax:
```
var Cities = new Dictionary<string, int>()
       {NewYork = 10, London = 5, Cairo = 12};
```

**Comment by HaloFour** [comment]
> But I'm still a fan of the syntax:

That's already legal object initializer syntax.  That would create an ambiguity in the language, as object initializers and collection/indexer initializers cannot be mixed.

**Comment by svick** [comment]
I don't understand the point of this proposal. What is it that you're actually trying to achieve? What makes you think others want to achieve the same thing often enough to warrant changing the language?

If you need a dictionary from a small set of values, you can create a normal `enum` and use that for the key type. Why is that approach not sufficient for your needs?

If you really want something that behaves both as a dictionary and an object with properties, you can write that type. It won't be a single line (at least not without some kind of code generation), but why should it be? I'm not convinced how useful that is: having either an object with properties OR a dictionary tends to be enough, you usually don't need both. If you do, can you explain why?

**Comment by MohammadHamdyGhanem** [comment]
> If you need a dictionary from a small set of values, you can create a normal enum and use that for the key type. Why is that approach not sufficient for your needs?

This works only with numeric values, but you can save any thing in a dictionary not just numbers. Besides, dictionaries can expand in runtime. The hard coded keys only regards the initial values, which C# already allows us to write them without asking: why don'y you declare an enum instead?

**Comment by MohammadHamdyGhanem** [comment]
>  If you do, can you explain why?
Try thisL
```
            var Cities = new Dictionary<string, int>() { {"NewYork" , 10 }, {"London" , 5 }, {"Cairo", 12} };
            Cities["New York"] = 12;
```
There is a bjg that won't be caught an desighn time, nor runtime!
The line:
Cities["New York"] = 12;
will add the new key "New York" to the dectionary becuase it is not the smq key as "NewYork".
This kind of misspelling of key names lead to undesired result that can be hard to discover in large projects. Declaring each key as a constant or a static read only field in a static class is time consuming (so, I suggested to add a nomin type).

**Comment by MkazemAkhgary** [comment]
@MohammadHamdyGhanem thats were you use constant values. 

    public const NewYork = "1321242345234534647";

As long as you always use constant literal NewYork, no matter what string you use, you will never misspell it.

usage 

     var Cities = new Dictionary<string, int>() {{NewYork, 10}};
    Cities[NewYork] = 12;
 
put these constant literals in a suitable class with good name. you are good to go.

**Comment by yaakov-h** [comment]
#576 looks like a decent solution before it got derailed into something closer resembling #274.

**Comment by MohammadHamdyGhanem** [comment]
@MkazemAkhgary 
Please read all the discussion.

@yaakov-h 
Nice.

**Comment by MohammadHamdyGhanem** [comment]
I have a new solution. I can work with a Tuple to write a clean code, then convert the tuple to a dictionary, whenever I need keys to be added in runtime or I want to pass a dictionary to some legacy method.
So, there are two ways:
1- Add a ToDictionary<string, T> method to tuples. 
2- Add a constructor to Dictionary classes that accepts a ValueTuple.
Dictionary can also have the method ToTuple.
Same rules can applied to upcoming Records. Records will solve the problems involved with Tuple elemnt names..

**Comment by svick** [comment]
@MohammadHamdyGhanem 

> This works only with numeric values, but you can save any thing in a dictionary not just numbers. Besides, dictionaries can expand in runtime.

Most of the time, I consider the fact that `enum`s have an underlying integral value to be an implantation detail, they're just a set of values. Why is the underlying value important for you?

And you didn't mention expanding the dictionary before, which is why I didn't consider it. And also because I think it would be inconsistent to have a set of values that can be accessed in a special way, while others can't.

That's why I asked for the motivation behind the this. Without that, it's really hard to evaluate what makes this feature useful or to offer good alternatives.

**Comment by svick** [comment]
@MohammadHamdyGhanem 

> convert the tuple to a dictionary

That wouldn't work, because a generic converting method wouldn't have access to the names of the values. Though it would work if you used anonymous type instead of tuple (and were okay with some reflection).

**Comment by yaakov-h** [comment]
It kinda works...

```cs
using System;
using System.Linq;

public static class Program
{
    public static void Main()
    {
        var placesThatNeverCloseDown = new[]
        {
         	(city: "New York", num: 1),
         	(city: "Rio", num: 2),
         	(city: "Old London Town", num: 3)
        };

        var dict = placesThatNeverCloseDown.ToDictionary(t => t.city, t => t.num);
        
        foreach (var item in dict)
            Console.WriteLine(item);
    }
}
```

**Comment by MohammadHamdyGhanem** [comment]
@svick 
This is why I said:

> Records will solve the problems involved with Tuple elemnt names.

So, if this is a useful feature, can we suggest it to be added to Records?
A method to convert a Record to a Dictionary?

**Comment by Joe4evr** [comment]
A Record will just look like any other type, so you can declare a method on it to do that conversion.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
What about this solution. C# Can add this new syntax:
Dictionary CityTemperaturesDic: Dictionary<String, int>
{
     NewYourk = 12,
     London = 10,
     Cairo = 15
}

The compiler can use this to create a calss CityTemperaturesDic like this:
 
Dictionary CityTemperaturesDic: Dictionary<String, int>
{
     NewYourk = 12,
     London = 10,
     Cairo = 15
}


    class CityTemperaturesDic : Dictionary<String, int>
    {
        public CityTemperaturesDic()
        {
            this["NewYourk"] = 12;
            this["London"] = 10;
            this["Cairo"] = 15;
        }

        public int NewYourk
        {
            get => this["NewYourk"];
            set => this["NewYourk"] = value;
        }

        public int London
        {
            get => this["London"];
            set => this["London"] = value;
        }

        public int Cairo
        {
            get => this["Cairo"];
            set => this["Cairo"] = value;
        }
    }

Now you can use this Typed Dictiinary anywhere in you project or even expose it outside the project:
var Cities = new CityTemperaturesDic( );
Cities.NewYork = 6;
if (Cities.Cairo < 10)
   Consol.WriteLine("Too Cold");

**Comment by MohammadHamdyGhanem** [comment]
I added it as a new proposal #1226

**Comment by AustinBryan** [comment]
You're literally thinking of an `enum`.

```csharp
enum City { NewYork, London, Cairo };

var Cities = new Dictionary<City, int>()
       { {NewYork, 10}, {London = 5}, {Cairo = 12} };
```

It has everything you're looking for and well prevent you from using `"foo"` as a city name.
