### ISSUE TITLE
Language extensions

### ISSUE THREAD

**Issue by Makeloft** [dotnet/csharplang#1224]
There are two main opposite points
1. Pattern Matching is completely new C# 7 feature and may change meaning of `var` keyword
2. Some elements of PM already has been present before C# 7 release and may be safely extended without changing of `var` meaning into classical C# 6 context

For example
`new Person { FirstName = "abc" };`
operators `var`, `is`, `as`; type casting `(T) o`

_* You may consider suggested syntax independently from PM too, even without null propagation extensions. Then try to answer, can PM replace `to` operator? And opposite, can suggested feature replace PM? [updated]_

Consider following valid code
```c#
new AnyModel { AnyProp0 = "abc" }.AttachModel();
new AnyModel() { AnyProp0 = "abc" }.AttachModel();
```
But nice to have too
```c#
GetModel() { AnyProp0 = "abc" }.AttachModel();
/* possible even following variation */
GetModel { AnyProp0 = "abc" }.AttachModel();
```
Moreover nice to have
```c#
/* field, property, local variable */
string activeValue = default(string);
...
GetModel() { AnyProp0 to activeValue }.AttachModel();

GetModel() { AnyProp0 to var newLocalValue }.AttachModel();
```
By the same logic two valid expressions
```c#
GetModel() to var m { AnyProp0 = GetValueFor(m) }.AttachModel();

GetModel() { AnyProp0 to var newLocalValue } to var m.AttachModel();

GetModel() { AnyProp0 to var newLocalValue } to AnyModel m.AttachModel();
```
Also helps to avoid crazy braces
```c#
((AnyModel) ((Button) sender).DataContext).UpdateModel();
sender to Button _.DataContext to AnyModel _.UpdateModel();
```

**Summary**
What really nice to have at C#
- right side assignment operator `to` which has logic similar to extension method 
        `public static T To<T>(this T o, out T x) => x = o;`
- two way property matching pattern `{ }` with clear meaning (without non null checks)

Valid variations of syntax
```c#
public string AnyField = "aaa";
public string AnyProperty { get; set; } = "bbb";

var anyLocalVariable = "ccc";

GetModel() to m /* define new variable 'm' [optional] */
{
    AnyProp0 = "abc", /* set value "abc" to the property */
    AnyProp1 to var p1, /* define new variable 'p1' with value from 'AnyProp1'  */
    AnyProp2 = "xyz" to var p2, /* define new variable 'p2' with value "xyz" and  set the value to the property AnyProp2 */
    AnyProp3 to AnyField, /* update 'AnyField' by value from 'AnyProp3' */
    AnyProp4 to AnyProperty, /* update 'AnyProperty' by value from 'AnyProp5' */
    AnyProp5 to anyLocalVariable, /* update 'anyLocalVariable' by value from 'AnyProp5' */
}.RedrawModel();

new AnyModel to m /* define new variable 'm' [optional] */
{
    AnyProp0 = "abc", /* set value "abc" to the property */
    AnyProp1 to var p1, /* define new variable 'p1' with DEFAULT value from 'AnyProp1'  */
    AnyProp2 = "xyz" to var p2, /* define new variable 'p2' with value "xyz" and  set the value to the property AnyProp2 */
}.AttachModel();
```
According sample with `swith`
```c#
switch(GetShape() to var s { Color to var color, Texture to var texture })
{
	case Circle c { Radius to var r, Color = color = "Red" }: /* override Color value ! */
	    WriteLine($"Circle with Radius={r}, Color={color}, Texture={texture}"); 
	    break;
	case Rectangle r { Width to var w, Heigth to var h } where w > h: /* additional validation */
	    WriteLine($"Rectangle with Width={w}, Heigth={h}, Color={color}, Texture={texture}"); 
	    break;
	case Heart h:
	    WriteLine($"Heart with Color={color}, Texture={texture}");
	    break;
	default:
	    WriteLine($"Unrecognized or invalid shape {s}");
	    break;
}
```
**Tuples**
We may use following syntax
```c#
GetTuple() { to var x0, to var x1, to AnyModel m }
```

**Problems**
Which problems may occurs

Consider code
```c#
//new AnyModel() to var m
GetModel() to var m
{ 
    AnyProp0 = "abc",
    AnyProp1 to anyVariable,
    AnyProp2 to AnyProperty,
    AnyProp3 to var newLocalVariable
};
```
and the coincident unwrapping
```c#
AnyType newLocalVariable;
newLocalVariable = default(AnyType); /* see below: to avoid [CS0165] Use of unassigned local variable */

//var tmp = new AnyModel();
var tmp = GetModel();
var m = tmp;
tmp.AnyProp0 = "abc";
anyVariable = tmp.AnyProp1;
AnyProperty = tmp.AnyProp2;
newLocalVariable = tmp.AnyProp3;
```

Obviously that we can get `NullReferenceException` for nullable types. How can we avoid this?

Currently we have following valid variations of syntax
```c#
new AnyModel { }?.AttachModel(); /* redundant but valid */
GetModel()?.AttachModel();
```
with C# 8 will be able too
```c#
new AnyModel? { }.AttachModel();
new AnyModel?() { }.AttachModel();
```
What about this
```c#
GetModel() { AnyProp = 123 }?.AttachModel(); /* may occur NRE during unwrapping */
GetModel?() { AnyProp = 123 }.AttachModel(); /* safe from NRE during unwrapping */
GetModel? { AnyProp = 123 }.AttachModel(); /* safe from NRE during unwrapping */
/* or */
GetModel()? { AnyProp = 123 }.AttachModel(); /* safe from NRE during unwrapping */
```

Consider the following simple sample with extension methods
```c#
switch(GetPoint().To(var p)?.Unwrap(out var x, out var y))
{
	case Point _:
	    WriteLine($"X={x}; Y={y}; Name={p.Name}"); 
	    break;
	case null:
	    WriteLine($"It is null"); 
	    break;
}
```
It is safe from NRE but compiler says that 
```
[CS0165] Use of unassigned local variable 'x'
[CS0165] Use of unassigned local variable 'y'
```
Try to understand why. Expression `out var x` equals to simple variable declaration like `int? x;` without initialization. Compiler can not be sure that `x` and `y` will be initialized every time and show compile error to avoid possible reading of unassigned variable.

But we describe before that operator `to` may initialize new local variables by default values! This step allows to avoid this error and process similar cases even with recursive patterns
```c#
GetModel() { Point? { X to var x, Y to var Y } }
GetModel() { Point? to var p { X to var x, Y to var Y } }
```
If necessary programmer should check variable `p` for `null` to understand that `x`, `y` has been initialized by default values or read directly from `Point`.

P.S. Closely related with https://github.com/dotnet/csharplang/issues/1196

**Comment by Makeloft** [comment]
@yaakov-h do you may provide objective arguments [exclude broken change] why you dislike suggested syntax ?

**Comment by yaakov-h** [comment]
I'm tired and it's late so this may be incomprehensible, but:

- This seems internally inconsistent.
- You're introducing `x to var y` when we already have `x is var y`.
- You're introducing `x to Type y` when we already have `x is var y`.
- You appear to be introducing `to` for deconstruction, when you could just already use deconstruction.
- None of this appears to be related to pattern matching, and is completely disjointed from C#'s pattern matching roadmap.
- None of your proposals show a problem that you're trying to solve, rather it appears to be new syntax for the sake of it.
- Most of your "today" syntax is invalid.
- Many of your proposal can already be implemented with extension methods, which removes the need for new syntax.
- Most of your C#8 syntax is also invalid. For example, `new AnyModel? { }.AttachModel();` isn't likely to be legal - what on earth does the `?` after the type mean in a constructor?
- You seem to be largely ignoring proposed features in favour of your own which make little to no sense by comparison. For example, your switch statement could potentially use actual pattern matching like so:

```cs
switch(GetPoint())
{
	case Point { X is var x, Y is var y } p:
	    WriteLine($"X={x}; Y={y}; Name={p.Name}"); 
	    break;
	case null:
	    WriteLine($"It is null"); 
	    break;
}
```

Hey look, no `to`s in sight, because they are completely unnecessary, and no potentially unassigned variables.

**Comment by yaakov-h** [comment]
Also, call me old fashioned, but that sort of code could also just be an if statement.

**Comment by DavidArno** [comment]
I am completely confused as to what this proposal is trying to achieve.

It seems to start off with the idea of using initialiser style syntax to modify properties of an existing value within a method chain:
```cs
GetModel() { AnyProp0 = "abc" }.AttachModel();
```
But then you then use that same syntax, but introduce the `to` keyword, to read a property and assign it to an existing variable within a method chain:
```cs
GetModel() { AnyProp0 to activeValue }.AttachModel();
```
Then `to var` gets used to assign to a new variable, pretty much anywhere in an expression:
```cs
GetModel() { AnyProp0 to var newLocalValue } to var m.AttachModel();
```
And to finally leave me completely confused, you claim this creates "two way property matching pattern", without ever having shown a pattern.

Even the title ("Language Extensions") is a bit of a give away that there is no clear proposal. I think you need to take a step back and think about what exactly is it that you are trying to achieve here and put a few more words, and a few less randomly generated pieces of scatter code, into describing it.

**Comment by Makeloft** [comment]
@yaakov-h @DavidArno @Pzixel
Ok, you may consider this feature independently from PM too.
I really want to have
```
GetModel() { AnyProp0 = GetValueFor(m) }.AttachModel();
GetModel() { AnyProp0 to anyVariableOrProperty } .AttachModel(); 
GetModel() { AnyProp0 to var newLocalVariable } .AttachModel(); 
```
Moreover I am ready to get NRE without null propagation extensions. What about this ?
Can PM replace 'to' operator ?

**Comment by orthoxerox** [comment]
@Makeloft why do you want to get an NRE? The whole idea behind many of the new language constructs is to avoid getting new NREs or other exceptions.

Nullable reference types will warn you about possible NREs, patterns return a success value so you know the match failed and do not access the deconstruction variables etc.

**Comment by Makeloft** [comment]
@orthoxerox 
I want to simplify syntax, I don't want to get NRE ! :)
Look
```c#
GetModel() { AnyProp0 = GetValue(), AnyProp1 to _anyField }.AttachModel();

var tmp = GetModel();
tmp.AnyProp0 = GetValue();
_anyField = tmp.AnyProp1;
tmp.AttachModel();
```
It is just a syntax sugar!

**Comment by HaloFour** [comment]
Looks like an over-convoluted "with" block, something else that the language doesn't need.  Your translation more than suffices to accomplish that logic.

**Comment by Makeloft** [comment]
@HaloFour what about this? This released feature is not needed too?
```c#
new AnyModel() { AnyProp0 = GetValue() }.AttachModel();

var tmp = GetModel();
tmp.AnyProp0 = GetValue();
tmp.AttachModel();
```

**Comment by HaloFour** [comment]
@Makeloft 

Needed?  No.  But they are shorter, stricter and have a very specific purpose.

**Comment by Makeloft** [comment]
@HaloFour suggested syntax are shorter, stricter and have a very specific purpose too.

**Comment by HaloFour** [comment]
@Makeloft 

That's your opinion and you're welcome to it.  [Factory initializers have been proposed already.](https://github.com/dotnet/csharplang/issues/803)  Reading properties using initializer syntax seems entirely out of place.

**Comment by Makeloft** [comment]
@HaloFour thanks! But this proposal doesn't contains 'to' operator.

**Comment by HaloFour** [comment]
@Makeloft 

That it doesn't, and I prefer it that way.  I don't believe reading properties has any place in an initializer.

**Comment by bondsbw** [comment]
I like the idea of factory initializers as it brings more parity between constructor and factory syntax.  `with` has been mentioned in multiple proposals and matches the direction taken by other languages.

Setting an external value from a member goes beyond parity and should probably be a separate proposal.  I would not support that proposal because it increases the amount of syntax for programmers to learn which is not justified by the number of situations it would improve.

**Comment by Makeloft** [comment]
@bondsbw thank for opinion!
Yes, it is a new syntax. But for my point of view this syntax is intuitive and brings elegant solutions for wide range of problems from 'factory initializers' to 'pattern-matching improving'.

**Comment by HaloFour** [comment]
> 'pattern-matching improving'.

You continue to demonstrate that you don't understand the concept of pattern matching.  This proposal is completely unrelated to anything to do with pattern matching, nor does it remotely fit with the syntax or philosophy behind it.  Syntax aside, recursive property patterns have a completely different behavior and have nothing to do with initializers.  The concept of trying to mutate the target expression with a match makes even less sense than trying to read properties from an initializer.

**Comment by DavidArno** [comment]
@Makeloft,

As for your `to` operator, please see:

#973
#595 
#402
#377

**Comment by Makeloft** [comment]
@HaloFour possible that I don't understand pattern matching. But also possible that you don't see something more global than PM.

One of main reason why I want to have this syntax that because it helps me to avoid constantly true 'o is var t' and 'var' meaning expansion.

@DavidArno thank for links!

**Comment by HaloFour** [comment]
@Makeloft 

> One of main reason why I want to have this syntax that because it helps me to avoid constantly true 'o is var t' and 'var' meaning expansion.

Your misunderstanding of the language and its constructs are a very poor justification for any language proposal.

**Comment by DavidArno** [comment]
> One of main reason why I want to have this syntax that because it helps me to avoid constantly true 'o is var t' and 'var' meaning expansion.

If you don't like `o is var t`, then don't use it. Endlessly proposing odd syntax changes, that generally have very little connection to pattern matching, will never make it go away. So just ignore it's existence and more on.

**Comment by gafter** [comment]
> One of main reason why I want to have this syntax that because it helps me to avoid constantly true 'o is var t' and 'var' meaning expansion.

How does your proposal "help you avoid" it? What are you doing that requires this construct so that you have been forced to use it in your code and therefore require an alternative? In what body of code have you seen `is var t` used extensively?

**Comment by Makeloft** [comment]
@gafter 
It is very simple. Instead not intuitive for me expression `is var` I can use obvious `to var` like described with `switch` sample and save type infer meaning for `var` into my code.

Even possible NRE is not big problem for me, because C# 8 compiler or analyzer may show warnings to suspicious places and I can check it. Moreover it will be provokes me to use non nullable types.

```c#
switch(GetShape() to var s { Color to var color, Texture to var texture })
{
	case Circle c { Radius to var r, Color = color = "Red" }: /* override Color value ! */
	    WriteLine($"Circle with Radius={r}, Color={color}, Texture={texture}"); 
	    break;
	case Rectangle r { Width to var w, Heigth to var h } where w > h: /* additional validation */
	    WriteLine($"Rectangle with Width={w}, Heigth={h}, Color={color}, Texture={texture}"); 
	    break;
	case Heart h:
	    WriteLine($"Heart with Color={color}, Texture={texture}");
	    break;
	default:
	    WriteLine($"Unrecognized or invalid shape {s}");
	    break;
} 
```

**Comment by Makeloft** [comment]
There is another very interesting thing about deconstruction.
It is possible to rewrite method Unwrap like extension and apply to `null` result.

Following sample compiles and works nice.
```c#
    public class Point
    {
        public int? X { get; set; }
        public int? Y { get; set; }
    }
    
    public static class PointExtensions
    {
        public static Point Unwrap(this Point p, out int? x, out int? y)
        {
            x = default(int?);
            y = default(int?);
            if (p == null) return null;
            x = p.X;
            y = p.Y;
            return p;
        } 
    }

            switch (GetPoint().Of(out var p).Unwrap(out var x, out var y))
            {
                case Point _ when x.Is() && y.Is():
                    Console.WriteLine($"X={x}; Y={y}; Name={p.Name}");
                    break;
                case Point _ when x.IsNull() && y.Is():
                    Console.WriteLine($"X not seted; Y={y}; Name={p.Name}");
                    break;
                case Point _ when x.Is() && y.IsNull():
                    Console.WriteLine($"X={x}; Y not seted; Name={p.Name}");
                    break;
                case Point _ when x.IsNull() && y.IsNull():
                    Console.WriteLine($"X not seted; Y not seted; Name={p.Name}");
                    break;
                case null:
                    Console.WriteLine("No Point" + x);
                    break;
                default:
                    Console.WriteLine("No Point");
                    break;
            }
```

**Comment by gafter** [comment]
@Makeloft it sounds like you don’t need any new features to “help you avoid” constructs you don’t like. You have so far been avoiding them without your proposed new features.

**Comment by Makeloft** [comment]
@gafter yes, correct, now I found the all ways to save `var` meaning into my code.
But it will be nice to have general syntax sugar for deconstruction pattern and something like
```c#
//new AnyModel() to var m
GetModel() to var m
{ 
    AnyProp0 = "abc",
    AnyProp1 to anyVariable,
    AnyProp2 to AnyProperty,
    AnyProp3 to var newLocalVariable
};
```

**Comment by Makeloft** [comment]
@gafter the previous sample with switch shows how may work this sugar with `null` values.
We may just ignore block, avoid NRE and initialize new variables by default values.

**Comment by DavidArno** [comment]
@Makeloft,

We already have deconstructors:
```cs
(anyVariable, AnyProperty, var newLocalVariable) = GetMpodel();
```
We don't need another way of doing deconstruction.

**Comment by DavidArno** [comment]
@Makeloft,

Then write your own language that does what you prefer. Basically, put up or shut up. 

Endlessly whining that at the language team to add near-duplicate features just because you don't like the way the existing feature works achieves nothing and wastes everyone's time.

**Comment by Makeloft** [comment]
@DavidArno no-no-no. I don't suggest duplicate features, just want to show that there are general features which may cover another features and solves wide range of language problems by elegant way.

**Comment by Makeloft** [comment]
@gafter 
Some magic and night inspiration... Just candy.

```c#
   public class Point
    {
        public int? X { get; set; }
        public int? Y { get; set; }
    }
    
    public static class LanguageExtensions
    {
        public static T To<T, TResult>(this T o, Func<T, TResult> decomposer, out TResult result)
        {
            result = o == null ? default(TResult) : decomposer(o);
            return o;
        }
    }

            switch (GetPoint().Of(out var p).To(o => o.X, out var x).To(o => o.Y, out var y))
            {
                case Point _ when x.Is() && y.Is():
                    Console.WriteLine($"X={x}; Y={y}; Name={p.Name}");
                    break;
                case Point _ when x.IsNull() && y.Is():
                    Console.WriteLine($"X not seted; Y={y}; Name={p.Name}");
                    break;
                case Point _ when x.Is() && y.IsNull():
                    Console.WriteLine($"X={x}; Y not seted; Name={p.Name}");
                    break;
                case Point _ when x.IsNull() && y.IsNull():
                    Console.WriteLine($"X not seted; Y not seted; Name={p.Name}");
                    break;
                case null:
                    Console.WriteLine("No Point" + x);
                    break;
                default:
                    Console.WriteLine("No Point");
                    break;
            }
```

**Comment by Joe4evr** [comment]
@Makeloft What you sound like:
![](https://camo.githubusercontent.com/0a717b754785bf1424f3c89a4050e7a465191e7b/687474703a2f2f692e696d6775722e636f6d2f6a45506d4932382e706e67)

**Comment by gafter** [comment]
> I don't suggest duplicate features, just want to show that there are general features which may cover another features and solves wide range of language problems by elegant way.

I don’t see how your suggestions “cover” pattern-matching, though they seem to be able to express a subset of the uses for patterns in a less elegant way.

**Comment by Makeloft** [comment]
@gafter 
Suggestion don't cover PM at all, but perfectly cover for me situations when you use constantly 'is var' and expansions of 'var' meaning. I can write fully clear code for me.

Moreover it contains syntax sugar for another scenarios behind PM.

**Comment by Makeloft** [comment]
@Joe4evr I very like C# 7 and respect creators!!!!
But I really dislike constantly true 'is var' and 'var' meaning expansion.

**Comment by Joe4evr** [comment]
Cyrus has explained to you multiple times that the meaning of `var` has not expanded, but that *your interpretation* of the meaning of `var` has been too narrow.

If you can't see past your own confirmation bias, then you'll never be able to make a proposal that satisfies Microsoft's language design team nor the community.

**Comment by gafter** [comment]
Please move discussion to https://github.com/dotnet/csharplang/issues/1196

**Comment by Makeloft** [comment]
@gafter 
Actually if it were been used another keyword [`let`, `any`, `null or var` etc.] instead playing with `var` and `is`, good, I fully agree to have your PM interpretation. But it was dirty decision and now `o is { } t` looks for me like hack to revert lost meaning of `o is var t`. Now we play with meaning of `{ }`.

Current proposal is just a syntax sugar [no breaking changes!!!] but also allows compensate some effects of previous strange decision.

**Comment by Makeloft** [comment]
No one word about pattern matching into https://github.com/dotnet/csharplang/issues/1228.
