### ISSUE TITLE
Pattern Matching on Generic Type Parameters

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#1225]
I'd like to be able to write code like this:
````
var Samples = new object[] {
  new List<String>(), 32, null, new List<Int>(), new List<Person>(), "", 
};

foreach(var item in Samples){
  if(item is List<out var OfType>){
    Console.WriteLine($@"Item is a list of {OfType}");
  }
}
````

Basically I'd like to be able to easily detect and extract type parameters.

**Comment by HaloFour** [comment]
What are the use cases for wanting to do this?  I can't think of any that don't involve reflection of some type.

I've proposed [additional APIs](https://github.com/dotnet/corefx/issues/644) to the BCL team to help reason about generic types.  This scenario could pretty easily be covered by one of those APIs:

```cs
var Samples = new object[] {
  new List<String>(), 32, null, new List<Int>(), new List<Person>(), "", 
};

foreach(var item in Samples){
  if(item != null && item.GetType().Is(typeof(List<>), out Type elementType)) {
    Console.WriteLine($@"Item is a list of {elementType}");
  }
}
```

**Comment by alrz** [comment]
With recursive patterns it would get a lot less verbose

```cs
if (item is (typeof(List<>), {var elementType})) {
   Console.WriteLine($"item is a list of {elementType}");
}
```
which is equivalent to:

```cs
item.Deconstruct(out var type, out var args);
if (type == typeof(List<>) && args.Length == 1) {
  var elementType = args[0]
  Console.WriteLine($"item is a list of {typeArgument}");
}
```
using a Deconstruct method:
```cs
static void Deconstruct(this object obj, out Type openType, out Type[] typeArguments) {
    var t = obj.GetType();
    type = t.GetGenericTypeDefinition();
    typeArguments = t.GenericTypeArguments;
}
```

**Comment by bondsbw** [comment]
Just brainstorming, is this suggesting that the following somehow work, effectively extending the concept of generic type parameters to local variables?
```c#
public void AddIfCompatible(object list, object obj)
{
    if (list is List<out var T> listT && objToInsert is T objT)
    {
        listT.Add(objT);
    }
}
```
And if that works then would type constraints be allowed?
```c#
if (list is List<out var T> listT where T : int)
{ ... }
```

I'm having a hard time justifying this over simply adding a generic type parameter to the method.  Keeping the API backwards compatible without introducing an overload (e.g. the method also works on non-generic lists).

**Comment by TonyValenti** [comment]
@HaloFour -
I really like your APIs but there are a few issues that I foresee:
1.  They're not refactoring-safe.  If I move an generic type parameter around, I just broke a lot of code.
2.  For classes that accept multiple generic type parameters, I'd like to be able to both specify certain ones and extract others.  For example:
````
if(Source is Dictionary<int, out var ValueType>){
  //Only work if the dictionary has Keys of Int.  Who cares about the values.
}
````

**Comment by HaloFour** [comment]
@TonyValenti 

Matching specific parameters is certainly possible with my API:

```cs
if(item != null && item.GetType().Is(typeof(Dictionary<,>), out Type keyType, out Type valueType) && keyType.Equals(typeof(int)) { ... }
```

That was a fairly common use case in my project.

You frequently move generic type parameters around?

Even so, I can't imagine that there are enough use cases to justify a special syntax for pattern matching generic type arguments.  Given that whatever this pattern would be used for likely involves reflection odds are that would still break during said refactoring anyway.  Between recursive patterns (and hopefully parameterized active patterns) you should be able to mix type matching in with pattern matching anyway, and hopefully with fairly decent syntax.

**Comment by gafter** [comment]
@TonyValenti How would this work? For example, how do you imagine this would be translated into existing C#? Or if that's not possible, into IL? Or if that's not possible, how would it be translated into machine language?
