### ISSUE TITLE
Typed Dictionary

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1226]
I hope C# can add this new syntax:
```
Dictionary CityTemperaturesDic<String, int>
{
     NewYork = 12,
     London = 10,
     Cairo = 15
}
```

The compiler can use this to create a calss CityTemperaturesDic like this:
```

    public class CityTemperaturesDic : Dictionary<String, int>
    {
        public CityTemperaturesDic()
        {
            this["NewYork"] = 12;
            this["London"] = 10;
            this["Cairo"] = 15;
        }

        public int NewYork
        {
            get => this["NewYork"];
            set => this["NewYork"] = value;
        }

        public int London
        {
            get => this["London"];
            set => this["London"] = value;
        }

        public int Cairo
        {
            get => this["Cairo"];
            set => this["Cairo"] = value;
        }

        void Deconstruct(out int NewYork, out int London, out int Cairo)
        {
            NewYork = this.NewYork;
            London = this.London;
            Cairo = this.Cairo;
        }

        (int NewYork, int London, int Cairo) ToTuple()
               => (this.NewYork, this.London, this.Cairo);

        System.Dynamic.ExpandoObject ToExpandableObject()
        {
            dynamic x = new System.Dynamic.ExpandoObject();
            x.NewYork = this.NewYork;
            x.London = this.London;
            x.Cairo = this.Cairo;
            return x;
        }
    }
```
if one clicks "Go to definition" over "CityTemperaturesDic", C# opens a code page that displays the generated code. This way any one that konws basic C# syntax will understand such new blocks. So, you can conseder this as a new form of code generation: a Generated code with a shorthand syntax.

Now you can use this Typed Dictionary anywhere in you project or even expose it outside the project:
```
var Cities = new CityTemperaturesDic( );
Cities.NewYork = 6;
if (Cities.Cairo < 10)
   Console.WriteLine("Too Cold");
```

This will prevent misspelled key names, which lead to unexpected results. For example, if you use this code:
```
Cities["Cair"] = 5;
if (Cities["Cairo"] < 10)
     Console.WriteLine("Too Cold"); 

```
In design time, C# can't detect the misspelled Key "Cair", and in runtime, the "Cair" key will be added to the Dictionary with value 5 without raising any exception, so the condition will always be false, because it deals with another key! This Can't happen in Typed dictionary, because a syntax error will happen in then line:
`Cities.Cair = 5;`
And Intellisense with prevent that sort of mistakes.

Note:
we can make this part

`Dictionary CityTemperaturesDic<String, int>`

shorter, if we agreed that the keys will always be strings. I suggest:

`Dictionary CityTemperaturesDic<int>`

I would also prefer to add these methods to the generated dictionary:

The typed dictionary can be converted to a tuple, or to a dynamic ExpandoObject, and can be deconstructed.

**Comment by svick** [comment]
C# generally does not have very specific patterns like this one built-in. It doesn't even consider `Dictionary<K, V>` to be a special type.

What makes this one pattern so compelling that it should be added to the language? Do you have any evidence that the misspellings that you're trying to defend against are common?

**Comment by MohammadHamdyGhanem** [comment]
> What makes this one pattern so compelling that it should be added to the language? Do you have any evidence that the misspellings that you're trying to defend against are common?

You can do a Survey. I don't think it's my job. This is something that annoys me, so I suggested a solution.
This typed dictionary (when used to store objects) can be compared to ExpandoObject and Tuples.
ExpandoObject doesn't have intellisense support, and Tuples looase thies names in reflection.

**Comment by yaakov-h** [comment]
If your class is just a subclass of Dictionary, how can the compiler or runtime prevent you from inserting other keys that weren’t defined at the constructor callsite?

This seems to completely fall apart under polymorphism.

**Comment by Joe4evr** [comment]
@MohammadHamdyGhanem You also sound like this:
![](https://camo.githubusercontent.com/0a717b754785bf1424f3c89a4050e7a465191e7b/687474703a2f2f692e696d6775722e636f6d2f6a45506d4932382e706e67)

**Comment by MohammadHamdyGhanem** [comment]
@yaakov-h 
I don't want to prevent that. This solution is to give us design time hard typing, while still have the full dictionay functionslity at runtime.
By the way, the generated properties can have more code to verify that kry exists, and add it if it was removed.
This typed dictionary can be consederd as a record, with the ability to enumerat its contents, and expand them in run time. With hard coded keys, you can pass environment variables in an easy to write, easy to use way. I thlnk saving these typed dictionaries as resources will help better organization of resources. 
I think there is more to discover about this feature if you give it some thought.

**Comment by yaakov-h** [comment]
> There is more to discover about this feature if you give it some thought.

You’re the one proposing it, so you’re the one who has to sell it.

You’re currently at -100 points. How are you going to get this feature up to 100 points?

So far I see zero use for this as a language feature, and a way that this could already be solved with a Roslyn Analyzer...

**Comment by MohammadHamdyGhanem** [comment]
@Joe4evr 
I don't think they are dummies!.. I think they are lazy. My point of view is that nowadays projects became huge and complicated. The compiler should generate every repeated long codes and give us new compacted forms of syntax that replace large blocks. This would achieve two purposes:
1- Save programmer's time while writing code.
2- Shrinking code size helps new programmers to easily read, understand, and reuse it.

So, C# folks already gave us the basic building blocks, but we now need a more bigger blocks to fasten building things.
By the way: Why there is not any predefined famous patterns added to the Regex Class? Should we search for the e-mail pattern every time we need it?
This is an example where programmer laziness stands against C# folks laziness!
Saving a minute from a C# programmer's time,  could save millions of minutes regarding all C# programmers. This is tons of money and electricity and pollution!
Please C# folks, see it that way, at least for our mother green earth!

**Comment by MohammadHamdyGhanem** [comment]
@yaakov-h 
Where can I see these points?

It's not necessary to sell it immediately. It's a way of thinking came out of a previous dissection. Ideas are procreative and can be modified or built on.

**Comment by yaakov-h** [comment]
@MohammadHamdyGhanem https://github.com/dotnet/csharplang/issues/936#issuecomment-331871526 paragraph 4 explains it well.

In this case, you appear to be trying to define a new construct which mixes strongly-typed objects with stringly-typed objects.

If you want to make sure that your strings are correct, this is a great place for an Analyzer to step in and check them for you.

**Comment by svick** [comment]
@MohammadHamdyGhanem 

> The compiler should generate every repeated long codes and give us new compacted forms of syntax that replace large blocks.

If you did that, you would end up with a huge, bloated language, full of obscure ways to write code that nobody knows. C# is already a fairly large language, so every new feature has to be really worth it.

You are right that making patterns that repeat in code shorter is a good thing, but I don't think adding a new special syntax for each pattern to the language is the right way to do it. My preferred solution is a good support for code generators (https://github.com/dotnet/csharplang/issues/107).

> Shrinking code size helps new programmers to easily read, understand, and reuse it.

I don't think that would be the end result of this approach to language design. You would end up with lots of special syntaxes and new programmers would be lost trying to learn them all.

> Why there is not any predefined famous patterns added to the Regex Class? Should we search for the e-mail pattern every time we need it?

If you think there should be, that would require adding a new API to .Net, not adding new feature to the C# language, so the right place to discuss that would be [the corefx repo](https://github.com/dotnet/corefx/).

It certainly doesn't have anything to do with the programmers on the C# team or their "laziness".

> Saving a minute from a C# programmer's time, could save millions of minutes regarding all C# programmers.

Adding a new feature to C# (or a new API to .Net) does not take a minute, but it's still the easy part. The hard part is convincing the language design meeting (or the API review group) that it's a good addition. And that's how it should be, exactly because millions of programmers will have to live with those decisions for at least a decade and every mistake causes real pain to those millions of programmers.

**Comment by jnm2** [comment]
@Joe4evr 

> @Makeloft What you sound like:
> <img src="https://camo.githubusercontent.com/0a717b754785bf1424f3c89a4050e7a465191e7b/687474703a2f2f692e696d6775722e636f6d2f6a45506d4932382e706e67" width="10%" />

> @MohammadHamdyGhanem You also sound like this:
> <img src="https://camo.githubusercontent.com/0a717b754785bf1424f3c89a4050e7a465191e7b/687474703a2f2f692e696d6775722e636f6d2f6a45506d4932382e706e67" width="10%" />

What's that thing again about having a hammer and every problem looking like a nail? 😜

**Comment by MohammadHamdyGhanem** [comment]
I would also prefer to add these methods to the generated dictionary:
```
        void Deconstruct(out int NewYork, out int London, out int Cairo)
        {
            NewYork = this.NewYork;
            London = this.London;
            Cairo = this.Cairo;
        }

        (int NewYork, int London, int Cairo) ToTuple()
               => (this.NewYork, this.London, this.Cairo);

        System.Dynamic.ExpandoObject ToExpandableObject()
        {
            dynamic x = new System.Dynamic.ExpandoObject();
            x.NewYork = this.NewYork;
            x.London = this.London;
            x.Cairo = this.Cairo;
            return x;
        }
```

So, typed dictionary can be converted to a tuple, or to a dynamic ExpandoObject, and can be deconstructed.

**Comment by MohammadHamdyGhanem** [comment]
@svick 

> You would end up with lots of special syntaxes and new programmers would be lost trying to learn them all.

There is an easy solution. the
Dictionary CityTemperaturesDic<String, int>
synatx is self explainig, but I suugest if one clicks "Go to definition" over "CityTemperaturesDic", C# opens a code page that displays the generated code. This way any one that konws basic C# syntax will understand such new blocks. So, you can conseder this as a new form of code generation: a Generated code with a shorthand syntax. 
I may suggest to allow us to add programmer-defined blocks syntax saved in defintion files, that can be imported to the project and destributed with it. Anyone sees these new syntaxes can understand them by the "go to definition" command. The definition Fileof cource will have some comments and explaination.
So, is it possible to make the compiler allow us to define our syntax and its generated code? The compiler task is easy: parse the block, and use the parametrs to generate the code.
If anyone ok with this idea, we can add a new proposal and see how can we define the defintions rules ot templates.

**Comment by HaloFour** [comment]
> So, is it possible to make the compiler allow us to define our syntax and its generated code?

In short, no.  It's simply not a good idea.  It would make it completely impossible to ever know what the syntax of the language does, and it would completely prevent any future evolution of the language as if anything could be potentially compilable language then any new features could inadvertently collide with it.  This has been requested before and it has been quickly and rightly shut down.

If you want your own language then feel free to fork Roslyn and have at it.  But this constant throwing of random spaghetti at the wall to solve completely esoteric "problems" with no actual use cases just because you'd prefer new grammar to accomplish everything will most likely get no results.  C# is a mature language with a massive audience of developers so the team is exceptionally conservative about language changes.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
I notice you prefer to reject ideas too soon, before explore deferent alternatives.
For example, user defined syntax can start with @ or #. This way it can,t be mistaken with other normal code or new updates. Any new feature in C# tends to preserve existing code, so it wouldn't break the generated code.
So, can you please give me a good reason to refuse this idea?

**Comment by jnm2** [comment]
> I notice you prefer to reject ideas too soon, before explore deferent alternatives.

I think the difference between you and him is perspective, to be honest.

**Comment by MohammadHamdyGhanem** [comment]
I don't mind his attitude. A good argument help ideas grow. You can see that I started with a simple idea, and @HaloFour pushed it so far. I realy enjoyed the discussion,  and had many benefits. I am now starting to read about code generation in VS.NET, to see its capabilities and limits, and hope I can find something to build a good proposal on.

**Comment by MohammadHamdyGhanem** [comment]
Allowing user defined syntax for some blocks has these benefits:
1. Encourage more programmers to test their ideas without disturbing C# team. 
3. Templates can be published on githup and shared with VS.NET projects. It will be easy to measure the popularity of them.
2. Fast growth of the language, because C# team can adopt famous syntaxes.

**Comment by jnm2** [comment]
@MohammadHamdyGhanem You might be interested in this conversation: https://github.com/dotnet/csharplang/issues/371#issuecomment-353856178

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

Most of these conversations have already happened.  The concept of inlining alternative syntax, or amending the C# parser proper, has come up here and on the Roslyn repo and has already been argued.  It's not a tenable proposition and doesn't solve any real problem.  But it makes the compiler insanely more complex and makes the language completely non-deterministic.

There is already a path for developers who want to play with extending the compiler to support new grammar and features.  It's called forking Roslyn.  The team encourages it.

**Comment by MohammadHamdyGhanem** [comment]
> There is already a path for developers who want to play with extending the compiler to support new grammar and features. It's called forking Roslyn. The team encourages it.

This requires understanding existing compiler code first to be able to modify it, which is a time consuming task for experienced programmers, and has no future, becuase it can isolate the new fork from new features added to the original Compiler, or demand more effor to catch up. 

I have explained how can any new syntax be easy to understand, by showing the generated code which of course will has some comments and explaination.
So, without good reasons, I don't care if an idea has been dismissed before. Time changes, C# evolves, and refused ideas could be revisited and accepted.

@jnm2 
I think my idea is easier, becuase it doesn't involve IL nor C# compiler itself! It's merely a C# code generator that parses a block and converts is to C# code that is treated as usual. I think that the changes required are minimal, and most the effort is to define the standered template formulas and rules. We even can write the parser and generate the code! All I want from C# compiler is to pay attention to the blocks starting with @ or # or whatever notation we agree with to apply the parser on them, and every thing will continu as normal from there.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> This requires understanding existing compiler code first to be able to modify it, which is a time consuming task for experienced programmers, and has no future, becuase it can isolate the new fork from new features added to the original Compiler, or demand more effor to catch up.

Indeed, it's not a permanent solution.  But if you want to prototype something out to demonstrate it's value that is the path that you take.  Otherwise you're waiting on the team to do that work for you, and that's not terribly likely to happen.

> I have explained how can any new syntax be easy to understand, by showing the generated code which of course will has some comments and explaination.
> So, without good reasons, I don't care if an idea has been dismissed before. Time changes, C# evolves, and refused ideas could be revisited and accepted.

You've already been linked to a very recent conversation (as in days ago) about support for inline languages where a member of the team clearly lays out why it's not a reasonable task for the compiler.  Even basic source generators have proven exceptionally difficult due to the tooling requirements and they have an exceptionally limited impact on the language itself.  Supporting arbitrary inline languages, or worse, custom C# grammar, would be infinitely harder.  And ultimately there's no point to it.  It doesn't solve any problems except to scratch the itch of those who seem desperate to invent new syntax to accomplish otherwise very easily solvable problems.

**Comment by yaakov-h** [comment]
If you really really want, you could use a Text Template to write out your custom whatever and transform that into C# code. This is Visual Studio functionality that is already available today.

We use this a lot at my workplace to generate classes from XML, CSDL and other file types.

**Comment by TKharaishvili** [comment]
@MohammadHamdyGhanem your problem sounds like something I'd use a design time code generation tool for. T4 for example.

Have you tried that?

**Comment by MohammadHamdyGhanem** [comment]
@TKharaishvili 
A code generstor is not a solution. If you used 10 different dictionaries, the code generator will add10 claases to the solution. Using special syntax hide these classes and is faster than using a code generator.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem

> A code generator is not a solution. If you used 10 different dictionaries, the code generator will add10 claases to the solution. Using special syntax hides these classes and is faster than using a code generator. 

Which is exactly the same thing that your proposal suggests:

> The compiler can use this to create a calss CityTemperaturesDic like this:

> if one clicks "Go to definition" over "CityTemperaturesDic", C# opens a code page that displays the generated code.

**Comment by MohammadHamdyGhanem** [comment]
Yes, but it's hidden classes not added to the solution. You only see the compact definition unless you wan't to see the compleate one. There something like that ( a generated code that only appears when you click goto definition) but I can't remember it now.

**Comment by yaakov-h** [comment]
>  If you used 10 different dictionaries, the code generator will add10 claases to the solution.

Technically with #107 the classes would be added to the compilation, not to the solution.

**Comment by Hosch250** [comment]
I don't see how this would be any different than doing something like:

```
var dictionary = new Dictionary<string, int>
{
     ["NewYork"] = 12,
     ["London"] = 10,
     ["Cairo"] = 15
}
```

and using it like a normal dictionary. And FWIW, you could also do:

```
public enum CityTemperatures
{
    NewYork = 12,
    London = 10,
    Cairo = 15 
}
```

**Comment by edin** [comment]
While ago i have added suggestion for implementing "mapped properties" , i think this is more general feature that could also solve this problem.

https://github.com/dotnet/vblang/issues/61#issuecomment-296363652
