### ISSUE TITLE
Auto-Implemented Property With Identified Backing Field 

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1227]
While I'm writing this property:

```
public int NewYork
{
   get => this["NewYork"];
   set => this["NewYork"] = value;
}

```
I asked myself: Why can't it be auto-implemented?

So, could it be like this:

`public int NewYork(this["NewYork"]) { get; set; }`

Or like this:

`public int NewYork { this["NewYork"] : get; set; }`

This is not only for dictionary keys. It's general for any property that uses an existing object instead of a backing filed 

`public int Prop1(Storage) { get; set; }`

Or:

`public int Prop1 {Storage: get; set; }`

I hope to hear other syntax suggestions.

**Comment by bondsbw** [comment]
If the goal is to reduce the amount of typing, I don't see how adding such as property definition:
```c#
public int NewYork(this["NewYork"]) { get; set; }
...
var city = myobj.NewYork;    
```
makes sense compared with simple indexing:
```c#
var city = myobj["New York"];
```
&nbsp;

And you can already do this:
```c#
public ref int NewYork => ref this["New York"];
```
even better if you can live with read-only:
```c#
public int NewYork => this["NewYork"];
```

**Comment by orthoxerox** [comment]
Someone has proposed `public int NewYork <=> this["NewYork"];` elsewhere, I'll see if I can find the issue.

**Comment by MohammadHamdyGhanem** [comment]
@orthoxerox 
<=> came to my mind from beginning,  so I,m ok with it.

**Comment by MohammadHamdyGhanem** [comment]
@bondsbw 

>  I don't see how adding such as property definition
 
#1226

**Comment by bondsbw** [comment]
@MohammadHamdyGhanem Proposals need to stand on their own, so add your reasons here.

Provide real scenarios this would help,  e.g. why would you need to implement the indexer in the first place instead of simply implementing the properties?  And why not use my suggestions that are already part of the language?

**Comment by MohammadHamdyGhanem** [comment]
This is not about indexer. It is just an example. I have already said it is valid for any other backing field.
Ref return works with read only properties, but how can you define auto implemented read-write property with ref return?
Fields can't replace properties in many scenarios such as data binding.

**Comment by bondsbw** [comment]
@MohammadHamdyGhanem I think `<=>` would be sufficient.

**Comment by MkazemAkhgary** [comment]
#1007 which was refined by Ben Adams

**Comment by MohammadHamdyGhanem** [comment]
I found another solution:
```C#
public int NewYork {get; set; } using this["NewYork"]
```

This also allows:
```C#
   public int Age {get; set; } using _age = 10
```

Which is a shortcut for:
```
int _age = 10;
public int Age
{
   get => _age;
   set => _age = value;
}
```

**Comment by HaloFour** [comment]
```cs
public int Age { get; set; } = 10;
```

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
Please read carefuly:
```C#
   public int Age {get; set; } using _age = 10;
```

is a shortcut for:
```C#
int _age = 10;
public int Age
{
   get => _age;
   set => _age = value;
}
```

**Comment by MohammadHamdyGhanem** [comment]
The purpose is not to just initialize the property, put to map it to a variable, afield or a an indexer... etc.

**Comment by MohammadHamdyGhanem** [comment]
```public int NewYork {get; set; } using this["NewYork"];```
is a shortcut for:
```C#
public int NewYork
{
   get => this["NewYork"];
   set => this["NewYork"] = value;
}
```

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

Your `Age` example doesn't demonstrate that at all, given you indicate it as "shorthand" for also declaring and assigning the field.

Why do you feel the need to post this suggestion a dozen times to other different proposals?
