### ISSUE TITLE
Proposal: Property with backing field scoped to property

### ISSUE THREAD

**Issue by Confuset** [dotnet/csharplang#1240]
It always bugged me that you basically have two options when writing propertys.

Auto-Property
```
public int Something { get; set; }
```
Property with backing field
```
private int _something
public int Something
{
    get{ return _something; }
    set{ _something = value; }
}
```
In simple cases this is not a problem, but as soon as you start to do something inside the setter, things can break, when somebody does not use the properties setter.
This is especially annyoing when you are implementing INotifyPropertyChange, Validation etc. and things start to get buggy…

So my proposal would be to have some sort of keyword that is scoped to getter and setter, like the 'value'-keyword.

```
public int Something
{
   get { return field; }
   set { value = field; }
}
```

This way no one could accidently access that field directly and break things.

**Complications:**
This could break old code that used the keyword, but i think this is not a big issue as, the compiler could find these and issue an error.

**Alternate design:**
To mitigate the complications with already used keywords we could use:
```
public int Something
{
   field _something;
   get { return _something; }
   set { value = _something; }
}
```
or
```
public int Something
{
   field long _something;
   get { return _something; }
   set { value = _something; }
}
```
This would allow to return different types than internally used.

What you think?

**Comment by GeirGrusom** [comment]
Duplicates:

#133 
#140
#318

**Comment by Confuset** [comment]
mh. looks like we need a findable name for this :-)
Sorry for the duplicate…

**Comment by Joe4evr** [comment]
Please close the issue then.

**Comment by Confuset** [comment]
Thanks

**Comment by Confuset** [comment]
Thanks

**Comment by Confuset** [comment]
Thanks

**Comment by Unknown6656** [comment]
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
