### ISSUE TITLE
Immutable keyword

### ISSUE THREAD

**Issue by saleyn** [dotnet/csharplang#1249]
Currently we have a couple of ways to initialize a property/field to ensure that it's "read only", where in the second case it's initialized in the class's constructor:
```C#
public readonly Dictionary<string, int> CustomDict = new Dictionary<string, int>();
public Dictionary<string, int> CustomDict { get; private set; }
```
Often, however, there is a need to ensure delayed initialization of an immutable property/field, where the initialization happens after construction.  The second case with the private setter doesn't really make the property/field immutable from the perspective of the current class - its members can still modify it.

Hence, it would be advantageous to introduce the "immutable" keyword that would allow to set an object to a value if and only if it's null:
```C#
public class Example {
  public immutable Dictionary<string, int> CustomDict { get; private set; }

  public void Initialize() {
    CustomDict = new Dictionary<string, int>(); // This will throw if Initialize() is called more than once
  }
}

public static class Program {
  public static immutable Hash<string, SomeType> Cache;

  public static void Main(string[] args) {
    CheckArgs(args);
    Cache = InitCache();
    ...
  }
}
```

**Comment by MkazemAkhgary** [comment]
You are probably looking for this.

    public Lazy<Dictionary<string, int>> CustomDict { get; } = new Lazy<Dictionary<string, int>(() => new Dictionary<string, int>());

As soon as you access dictionary via `CustomDict.Value`, dictionary it will get initialized. This is called lazy initialization. Subsequent calls to `Value` will use previously initialized instance.

**Comment by saleyn** [comment]
My proposal is similar to the lazy initialization, yet, gives more control to the developer at when the initialization actually happens.  With lazy initialization, the initialization happens as soon as `Value` is called, however, real-world use cases may require some prior checks, ensuring availability of data, etc., before the initialization is allowed to occur.
It also converts the paradigm to the first-class element of the language.

**Comment by VisualMelon** [comment]
Whilst I'm not wholly opposed to the feature (though I can't personally see much value, and I'd prefer this sort of thing was kept 'in code', leaving keywords for high-impact stuff like static-analysis, but without property-private fields it would fill a very particular niche for write-once properties), I do object to the keyword choice: this value is only immutable in some situations, and presumably can be written many times so long as you keep writing null. My instinct would that be that `immutable` provides stronger guarantees than `readonly`. All that said, I can't think of a better name, but I would need convincing that there is no better option!

**Comment by saleyn** [comment]
@VisualMelon: I agree with your comments. This thread is merely to outline a need for "write-once" properties that is different from the current "readonly" designation.

**Comment by Neme12** [comment]
How would that even be possible without runtime checks?

**Comment by VisualMelon** [comment]
It wouldn't be possible without retime checks; I don't think the OP is claiming otherwise.

To work properly with multiple threads, it would also require Compare and Exchange to ensure the value replaced was `null`.

**Comment by HaloFour** [comment]
This would be something fairly easily accomplished through a generic type wrapper.  Like `Lazy<T>`, but with obviously different semantics:

```cs
public class WriteOnce<T> {
    private const int NOTSET = 0;
    private const int SET = 1;

    private T value;
    private int flag = NOTSET;

    public T Value {
        get => return (flag == SET) ? value : throw new InvalidOperationException("Value not yet set.");
        set {
            if (Interlocked.Exchange(ref flag, SET) == NOTSET) {
                this.value = value;
            }
            else {
                throw new InvalidOperationException("Value is already set.");
            }
        }
    }
}
```

**Comment by VisualMelon** [comment]
@HaloFour that isn't quite the behaviour described in the OP (which specifically refers to only allowing writes if the field is `null`), but is probably more applicable to the real world.

**Comment by Neme12** [comment]
I don't think we should introduce a keyword that insert runtime checks for you that you can do easily yourself. And you will probably do that anyway to give people a more meaningfull error message when Initialize is called more than once. And if you just use Initialize, you probably only need one check, not a separate one for each variable. Also, this doesn't really have that much to do with `immutable`.

**Comment by HaloFour** [comment]
@VisualMelon 

Fine:

```cs
public class WriteOnce<T> where T : class {
    private T value;

    public T Value {
        get => value;
        set {
            if (Interlocked.CompareExchange<T>(ref this.value, value, null) != null) {
                throw new InvalidOperationException("Value is already set.");
            }
        }
    }
}
```

There's probably a dozen ways to write this depending exactly on how you want it to behave, and that kind of policy is best left to libraries.

**Comment by Logerfo** [comment]
I agree with @HaloFour here. The only drawback to this approach is regarding pattern matching, as described in #1248. I see no reason for a new keyword.
