### ISSUE TITLE
Discussion: foreach distict 

### ISSUE THREAD

**Issue by avatarsystems** [dotnet/csharplang#1251]
I would like to see a foreach distict looping mechanism that skips duplicates automatically. For example:

foreach distict (ForeignKey fk in myTable.ForeignKeysOnTable)
{
   ...
}

**Comment by eyalsk** [comment]
@avatarsystems How about using LINQ? `myTable.ForeignKeysOnTable.Distinct()`?

**Comment by avatarsystems** [comment]
That works.  Just thought it neat feature for the core language without having on Linq.

**Comment by Unknown6656** [comment]
Nothing of semantic value to add, but I just wanted to say, that the English word is _disti**n**ct_ (with an `n`) - _distict_ sounds a bit odd....

**Comment by CyrusNajmabadi** [comment]
```c#
foreach (var fk in myTable.ForeignKeysOnTable.Distinct())
{
...
}
```

**Comment by jnm2** [comment]
> That works. Just thought it neat feature for the core language without having on Linq.

`foreach` works by looking for GetEnumerator, MoveNext, etc through duck-typing or interface casting. Are you proposing that it would be worthwhile for `foreach distinct` to look for a duck-typed `Distinct()` method before calling `GetEnumerator()`?
If we were to be consistent, how many other methods should we start hard-coding into `foreach`?

**Comment by avatarsystems** [comment]
>If we were to be consistent, how many other methods should we start hard-coding into foreach?
Just thinking.  Maybe:  1) reverse, 2)  excluding  (very often you walk your list in your loop manually doing a continue command)  .    Since everyone seems focused on functionality workarounds,  reverse can potentially using Linq's OrderBy() or Reverse()),  excluding is possible with Linq's Except().  Other workarounds not mentioned so far are the list object's ForEach method or writing an extension method.

**Comment by MattDillard** [comment]
I wouldn't consider LINQ a workaround, but rather the right way of doing things. It keeps the foreach primitive focused and clear, while permitting immense flexibility by filtering, reversing or otherwise transforming the collection over which we iterate.

**Comment by bondsbw** [comment]
#101 is a championed proposal for extending LINQ query syntax with `do` blocks, and is a continuation of the discussion at https://github.com/dotnet/roslyn/issues/100 which includes discussion of `distinct` as a keyword.

Plus LINQ query syntax directly handles filtering, projection, grouping, joins, and could eventually include other popular suggestions like `skip`/`take`, `aggregate`, `any`/`all`, and others (see #116).

`foreach` isn't going away but I doubt it ever gets much in the way of new features.  Just my opinion.
