### ISSUE TITLE
[Question] Method Group Casting?

### ISSUE THREAD

**Issue by khionu** [dotnet/csharplang#1257]
So, I'm a bit baffled by this. If someone could help me understand why this is, and why it has to be, if it must, I would greatly appreciate it.

If you have two methods, say Alpha and Beta, with identical signatures, an implicit cast can't be determined between them.
![Example](https://i.imgur.com/JguixFB.png)

Yet, if I add an explicit cast to either, it works just fine. I understand that things that seem obvious to a developer may not be to the compiler, but that doesn't feel like it cuts it for this scenario.

**Comment by HaloFour** [comment]
@khionu 

The ternary conditional operator requires that at least one of the potential expressions is explicitly typed and that the other expression can be implicitly cast to that type.  With a method group there is no known type as a method could be cast to any infinite number of potential delegate types which would be incompatible with one another even if they have the same signature.

**Comment by bondsbw** [comment]
Eric Lippert [explains here](https://stackoverflow.com/questions/17214380/why-are-all-delegate-types-incompatible-with-each-other) why this is the case:

> The reasoning behind the decision as I understand it . . . is that the expectation was that there would be delegate types with _semantics_.  You want this to be a type error:
>```c#
> AnyFunction<int, int> af = x=> { Console.WriteLine(x); return x + y; };
> PureFunction<int, int> pf = af;
> ```
> A "pure" function is a function which produces and consumes no side effects, consumes no information outside of its arguments, and returns a consistent value when given the same arguments. Clearly `af` fails at least two of those, and so should not be assignable to `pf` as an implicit conversion.
> But semantics-laden delegate types never happened, so it's a bit of a misfeature now.

I am curious why this consideration didn't extend to interfaces, which are also aligned with the concept of a contract.  Or perhaps it was considered and rejected because of many reasons, then why didn't that decision influence the design of delegates.

**Comment by jnm2** [comment]
> > But semantics-laden delegate types never happened, so it's a bit of a misfeature now.

Maybe partly because it's still so easy to do things like `PureFunction<int, int> pf = af.Invoke;`– and most of the time you're implicitly casting a method group via target typing anyway?

**Comment by bondsbw** [comment]
@jnm2  Yep.  If #877 is implemented, it should handle the case in the proposal.

**Comment by khionu** [comment]
Thank you all for your responses and information.
