### ISSUE TITLE
Proposal: Allow us to create a singleton more nicely

### ISSUE THREAD

**Issue by adrianknight89** [dotnet/csharplang#1259]
How about we introduce `singleton` so that creating singleton classes is much easier?

```
public singleton class MyClass
{
	private MyClass()
	{
	}

	public static int PropertyA { get; set; }

	public static void MethodX()
	{
	}
}
```

The following rules are set:

- If a `singleton` class is created, public constructors will issue a compiler error.
- It is by default `sealed` to prevent sub-classing.
- There is no need for explicit `_instance` field and/or `Instance` property.
- All properties and methods are static. (This would enforce that non-static members are not allowed since they can't be used by static members unless somehow an `Instance` property is injected at compile time that is not shown to devs by intellisense.)
- I'm not sure about thread-safety and using locks, but this is something that needs to be thought of.
- This class must be lazy loaded (i.e. instantiate only upon first access).

Usage would be:
`MyClass.PropertyA = 5;` or `MyClass.MethodX();`

So here, the goal is to bypass `Instance` so code statements can be shorter.

Does anybody think `singleton` makes sense and is doable?

**Comment by eyalsk** [comment]
@adrianknight89 This fits more to #341. See the proposal [here](https://github.com/dotnet/roslyn/blob/master/docs/features/generators.md).

So it would be something like this:
```
[Singleton]
public class MyClass
{
}
```

**Comment by stakx** [comment]
@adrianknight89 - much of what you are proposing can already be achieved using a regular `static class`. Am I missing something?

**Comment by yaakov-h** [comment]
Duplicate of #490.

**Comment by stakx** [comment]
@adrianknight89: What you are proposing sounds a lot like a regular `static class` to me. What am I missing?

(One notable difference between singleton classes and static classes is that the former can implement interfaces, but this proposal here makes that impossible.)

**Comment by eyalsk** [comment]
@stakx Singleton means there's a single instance of the object, static classes don't imply this, they imply that there's a single instance of the type.

**Comment by theunrepentantgeek** [comment]
Enforcing a singleton through the language seems overkill - there are already very good ways to enforce this without building it into the language.

(And that's assuming it's a good idea to rigidly enforce the single-instance nature of a class in the first place. I've found this to be a mistake - for one, it makes worthwhile unit testing of much of the entire system impossible because otherwise independent things get strongly coupled together. Configuring a singleton by *Policy* is a much better approach. That said, I suspect I'm in minority here.)

**Comment by stakx** [comment]
@eyalsk: I am aware of that difference in semantics, but where would it actually matter in the given proposal?

**Comment by eyalsk** [comment]
@stakx Singleton involves adding some boilerplate to create and then accessing the instance whereas by having language support it can eliminate all this.

**Comment by adrianknight89** [comment]
@stakx Sorry, I did not think about interfaces. Correct me if I'm wrong. If all members are forced to be static, then that eliminates interface support. However, I also mentioned baking `Instance` into the class implicitly.

Also note that I mentioned lazy loading the object. With a static class, all members are loaded unless they are defined as Lazy<T>, correct? Here, we just need to lazy load the implicit `Instance` object.

What I was trying to suggest is not to get rid of `Instance` but hide it from the user.

**Comment by stakx** [comment]
@eyalsk: Again, if all methods and properties must be `static`, then obviously a static `Instance` field or property field becomes automatically useless. You can just invoke the static members directly. What boilerplate would there be left to write?

**Comment by eyalsk** [comment]
@adrianknight89 
> What I was trying to suggest is not to get rid of Instance but hide it from the user.

So you in fact, get rid of this.

@stakx Again, whether it's a static class or not you need to expose the instance and this is what this proposal is all about, hiding it to make it look like a regular object.

**Comment by adrianknight89** [comment]
I'm going to close this discussion since the proposal has a lot of similarities to #490. Thank you all for your input.

**Comment by stakx** [comment]
@eyalsk:

> you need to expose the instance and this is what this proposal is all about

If that assessment is correct, then my above posts are perhaps largely irrelevant, as are many of the rules that have been laid out. I'd suggest to @adrianknight89 to present his proposal in a way that focuses much more on that one aspect.
