### ISSUE TITLE
[Question] Discard identifier in "is" pattern matching expected?

### ISSUE THREAD

**Issue by markdchurchill** [dotnet/csharplang#1260]
As `(foo is Bar _)` is equivalent to `(foo is Bar)` when creation of an identifier is not intended:
Should I expect a CS0103 when using this pattern for (admittedly questionable) readability improvement in `if(foo is Bar _) return _;`?

I also see the proposal recommending removal of _ as a valid non-discard identifier, so this may be a moot point in the long run.

**Comment by MkazemAkhgary** [comment]
As long as underscore has two meanings your code works. But now you know it, its not wise to keep doing wrong thing.

If you are concerned with breaking changes, dont worry there will be warnings about that. This has been already discussed. Although AFIK removal of underscore as identifier is not yet confirmed.

**Comment by Joe4evr** [comment]
@MkazemAkhgary #1064 is about as much confirmation as you can get.

**Comment by MkazemAkhgary** [comment]
@Joe4evr [this was last comment by gafter](https://github.com/dotnet/csharplang/issues/1064#issuecomment-341978577)

>To be clear, I do not believe we have to deprecate _. I just think it is worth considering. The LDM has not triaged this suggestion yet.

but yes, discussion is there. so this post is pretty much duplicate you can close It and move discussion to #1064

**Comment by DavidArno** [comment]
> Should I expect a CS0103 when using this pattern for (admittedly questionable) readability improvement in `if(foo is Bar _) return _;`?

Yes, you should. If a variable `_` is in scope, then in the following too cases, `_` is still treated as a discard and not a reference to that former variable: `x is T _` and `out T _`:
```cs
var _ = new Bar();
var foo = new Foo();
if(foo is Foo _) Console.WriteLine($"Foo({_})"); // writes "Foo(Bar)"
        
if (int.TryParse("1", out var _))
{
    Console.WriteLine($"int({_})"); // Writes "int(Bar)" 
}
```
[Code can be experimented with, here](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMBuAWAChjUAmTAIQEMwBvAX1IoDEB7NzEK2zR45pgDCmYnWKZJ2HADZsAFmkAOABQBKUUSl8J2qQDdeAfUwBeTFACmAdx5h1hLXsmGwmAGYczFm5nZsHXWcAS3cVT05ggGc/LyMNXABOFQASACJ/FTojBjU0tUdnSSC9UMwVYKhgADoAFTAATwAFWijLFTScNJhMNghgTFdMeLUS7XEnIqkk1LTK4CycvILNKaZJzHWGIA===)

So `_` in `if(foo is Bar _)` is always a discard and so you'll get a CS0103 if you try and reference it as a variable.

**Comment by gafter** [comment]
Closing, as the question has been answered.
