### ISSUE TITLE
Proposal: lock statement syntax

### ISSUE THREAD

**Issue by BaZzz01010101** [dotnet/csharplang#1262]
what about this syntax of lock statement:
```
lock (var obj = manager.getUnsafeObj(id)) 
{
    obj.doSomething();
}
```
similar to:
```
using (var obj = manager.createDisposableObj())
{
    obj.doSomething();
}
```

**Comment by DavidArno** [comment]
Rather than needing a specific change to the `lock` syntax, this could be covered by [declaration expressions](https://github.com/dotnet/csharplang/issues/973#issuecomment-358393898):
```cs
lock (var obj = manager.getUnsafeObj(id); obj) 
{
    obj.doSomething();
}
```
It's slightly more long-winded than your suggestion, but uses a generic (proposed) feature.

**Comment by alrz** [comment]
Declaration expression results in the exact same synnax

> ```cs
> lock (var obj = manager.createDisposableObj())
> {
>     obj.doSomething();
> }
> ```
A declaration expression returns the expression itself.

**Comment by DavidArno** [comment]
@alrz,

Ah, I didn't realise that. Problem solved then. 👍

**Comment by BaZzz01010101** [comment]
Yes, problem solved 👍 Thanks guys
