### ISSUE TITLE
[Feature] Add multi-parameter overloads for Math.Max and Math.Min

### ISSUE THREAD

**Issue by m93a** [dotnet/csharplang#1263]
It would be logical if `Math.Max` and `Math.Min` had overloads for three, four and more parameters. I don't see why don't we have them already. They would be very easy to implement and backwards compatible.

## Example usage
When you need a method to take three non-negative `int`s you have to do one of the following:
* something like `Math.Min(Math.Min(a,b),c) < 0`, which is really ugly and unreadable
* take `uint`s and cast them (which often results in double-casting because you have an `int`, you cast it to `uint` to pass it to the method and it casts it back to `int` again)
* check for every parameter separately, which is not very elegant
* define your own `Min` method – this is the best solution but because you can't extend static classes, you'll end up with something awkward like `MathExtensions.Min(a,b,c)`
But if we had the overloads, we could simply do `Math.Min(a,b,c)`

## Example implementation
```c#
public static class Math
{
    public number Max(number a, number b, number c)
        => Max( Max(a, b), c);
    
    public number Max(number a, number b, number c, number d)
        => Max( Max(a, b, c), d);
    
    public number Max(params number[] list)
    {
        number m = list[0];
        for(int i = 1; i < list.Length; i++)
        {
            m = Max(m, list[i]);
        }
    }
}
```

(substitute `number` for any primitive type)

**Comment by tannergooding** [comment]
This should be moved to the CoreFX repository, as it has to do with the framework API, rather than with the C# language.

NOTE: CoreFX expects API proposals to be in a specific format (https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md#steps); otherwise, it is generally treated as a discussion rather than a proposal.

**Comment by Logerfo** [comment]
Problem is that there is no `number` keyword in C#. There is no way to represent a value that could be both integer or float, for example. So, in order to achieve the requested feature, the language would need to be updated before. And IIRC, in order to achieve the language update, the CLR would need to be changed as well.

**Comment by m93a** [comment]
@Logerfo Nope, that's not what I meant! That was only a shorthand for explicitly writing all this for `int`, `long`, `float`, `double`, ...

**Comment by kingmotley** [comment]
Since INumber<T> was added in .NET 7, can we do something like the following?

    public static T Max<T>(params T[] values) where T : INumber<T>
    {
        if (values == null || values.Length == 0)
            throw new ArgumentException("At least one value must be provided.", nameof(values));

        T max = values[0];
        foreach (var value in values)
        {
            if (value > max)
            {
                max = value;
            }
        }
        return max;
    }

**Comment by bernd5** [comment]
Of course, see: [Sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoA5VMAU2SgGMBnAbmOIDcJk5MOQC85ALIQAHgAoA2gHY4ADjj5ScACxLyeOOQDMmgLoBKbiTwBOGWHM9LNybJz6ArPryn7RAMoAHCBgAHmAATwRGAD5ydlFyOT1DfQVjCyonaRl2bwtiKgA2cgAVCWlg4qiZQOQIMDiAoIqY/gAbVEYc8gB3AAtmRhLyEHIASXowYGZm4gBvYnJF8igAM3IZNo64kTEYVFbW8gwMck3O6gAZRhgAcwRe0TFSUwWlt/vkAHtu8hhGH4AgsgbgxrggAKJSViMfwIKCfGAyABEAIQ5FajAg7DRCMGZyEqGx5Cm5H8X14UAAJoxKdQkfoYHVGJ8VhsIO1OrkHG9SpApPEzuw5KQ0q9FitPshMawHmzBPjYKd2VsXkQ3vM1W8lqt1viYnzVVqlhqjUa+QLlYwLKbyABfMV2h1YBRCaQWe1EYhAA==)

But to make it part of the [runtime](https://github.com/dotnet/runtime)- it should be issued there
