### ISSUE TITLE
Proposal: Declare variables inside if conditions

### ISSUE THREAD

**Issue by TheUnlocked** [dotnet/csharplang#1265]
The proposal would be to allow this:
```cs
if (Foo f = a.Bar() == b){
    // ...
}
```
as syntactic sugar for:
```cs
Foo f = a.Bar();
if (f == b){
    // ...
}
```
In that particular case, the sugar would seem mostly useless and more confusing than anything. However, this would save a lot of text in long else-if chains:
```cs
if (A a = word.GetA() != null)
    a.Foo();
else if (B b = word.GetB() != null)
    b.Bar();
else if (C c = word.GetC() != null)
    c.Baz();
// ...
```
versus
```cs
A a = word.GetA();
B b = word.GetB();
C c = word.GetC();
// ...
if (a != null)
    a.Foo();
else if (b != null)
    b.Bar();
else if (c != null)
    c.Baz();
// ...
```

This might be possible with a switch-case, but only if A, B, and C all extend whatever `word` is, which they may not.

The main problem I see with this is that it might be unclear what exactly you're setting the variable to. For example:
```cs
if (bool b = GetBool() && GetOtherBool())
```
Would have an ambiguous meaning. An alternative to fix this could be to require that the declaration be in parentheses:
```cs
if ((bool b = GetBool()) && GetOtherBool())
```

Another potential flaw is that it might cause confusion and inconsistencies across the language. For example, would this change imply that the following is also legal?
```cs
// Assuming Baz extends Bar which extends Foo
Foo a = (Bar b = (Baz c = new Baz()));
```

An alternative syntax could be to just drop the `=`:
```cs
if (Foo f a.Bar() == b)
// or
if ((Foo f a.Bar()) == b)
```

**Comment by CyrusNajmabadi** [comment]
```c#
if (Foo f = a.Bar() == b){
    // ...
}

// as syntactic sugar for:

Foo f = a.Bar();
if (f == b){
    // ...
}
```

This precedence would be extremely strange give how C# already works.  If you write:

```Foo f = a.Bar() == b```, that's the equivalent of ```Foo f = (a.Bar() == b)``` not ```(Foo f = a.Bar()) == b```

**Comment by yaakov-h** [comment]
This sounds a lot like #595 / #973. Duplicate?

**Comment by TheUnlocked** [comment]
This was specifically for if statements, but as #973 is a champion of a more generalized form which would include this, I'll close this issue and defer to that one.
