### ISSUE TITLE
allow to change ref local reference.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1272]
for example

    ref var selected = ref A;

here `selected` becomes an alias for `A`. any assignment to `selected` will also change `A` because they are literally same.

How ever this is not possible

    if(meets_some_condition) selected = ref B;

I wish it was possible, so that `selected` is no more an alias to `A` but its an alias to `B`. 

Is there technical reason why it is not allowed? is this hard to achieve? or simply not considered feasible to be implemented?

---

PS. following will not compile either, because it complains `selected` is used like a type. btw I think this syntax would be better to describe changing of a reference.

    if(meets_some_condition)  ref selected = ref B;

**Comment by benaadams** [comment]
Ternary is currently possible in C#7.2
```csharp
ref var selected = ref (meets_some_condition) ? ref b : ref a;
```
[Ref Local Reassignment](https://github.com/dotnet/csharplang/blob/master/proposals/ref-local-reassignment.md) was cut from C#7.2 though 😢

**Comment by MkazemAkhgary** [comment]
@benaadams  Thanks, but I need a ref change after declaration.

I have a BST, I want to get minimum of right node, but I also need to have the reference of minimum so I can set it to null or assign something else to it later.

    ref var minNode = ref node.Right;
    while (minNode.Left != null) minNode = ref minNode.Left; // change ref

later null or right sub tree of `minNode` is assigned to `minNode` . this is part of `Delete` implementation of BST. I guess I should change it a little bit.

**Comment by MkazemAkhgary** [comment]
@HaloFour Yep, closing as duplicate.
