### ISSUE TITLE
Proposal: modifier (perhaps "static") for local functions, to explicitly disallow captured state semantics

### ISSUE THREAD

**Issue by mgravell** [dotnet/csharplang#1277]
A recurring problem I've seen a *lot* since the addition of local methods - and *in particular* in `async` optimizations (and [not just me](https://blogs.msdn.microsoft.com/seteplia/2018/01/25/the-performance-characteristics-of-async-methods/)) is that it is very easy to accidentally introduce shared state into a local function when you *really didn't want to*. For example:

    void Foo(int a) {
        void Bar(int val) {
             Blah(a); // <== error; this was meant to be val
        }
        // ...
        Bar(a);
    }

This is a common intent when using local functions to *enclose* a method, without actually intending to allow shared capture state.

Currently, the only "fix" here is to move the method out:

    static void Bar(int val) {
         Blah(val); // <== fixed, because the compiler told us about it
    }
    void Foo(int a) {    
        // ...
        Bar(a);
    }

This *works*, but it pollutes the space and loses code locality and expressiveness. I actually find myself routinely copy/pasting local methods out and back in again to check that they still compile - to see if I've leaked state.

---

Proposal: allow the `static` modifier on local functions, to express the intent to divorce all state. I'm not 100% sure that `static` is the right word, but it seems close. The effect would be simply to enforce that variables (parameters and locals) declared *outside* the `static` local method are **not** in scope inside the local method, essentially as though the local method had been declared *outside* the method. The "local method", then, is simply here for code cleanliness reasons.

This has the effect of avoiding unintended captured state machinery.

Example:

    void Foo(int a) {
        static void Bar(int val) {
             Blah(val); // <== fixed, because the compiler told us about it
        }
        // ...
        Bar(a);
    }

There is an outstanding question of whether it is acceptable to share the `this` instance but nothing else; this ambiguity is perhaps the biggest thing *against* the `static` keyword.

Additional possibility: because of the lack of state, it allows re-use of the most obvious/correct variable names. I've seen lots of examples essentially like:

    void Foo(int a) {
        void Bar(int innerA) {
             Blah(innerA); // <== note awkward naming
        }
        // ...
        Bar(a);
    }

but this proposal allows the "obvious" names to be used consistently:

    void Foo(int a) {
        static void Bar(int a) {
             Blah(a);
        }
        // ...
        Bar(a);
    }

**Comment by Drawaes** [comment]
This was brought up during a PR review by @stephentoub 

https://github.com/dotnet/corefx/pull/25187#discussion_r150392470

It is way to easy to make that mistake.

**Comment by mgravell** [comment]
side thought: should the same modifier also be allowed for anonymous methods and lambdas, in the same way that `async` can be used as a modifier? for example:

    Action<string> someCallback = static s => { ... };

which would again mean that no implicit state capture is permitted inside the lambda expression or expression body.

**Comment by Joe4evr** [comment]
See also: dotnet/roslyn#23970

**Comment by eyalsk** [comment]
@mgravell This can also be solved using attributes and analyzers with #794, however, we still can't apply attributes in the context of anonymous methods and lambdas but with [this](https://github.com/dotnet/roslyn/issues/6671) it's going to be possible.

Alternatively, if a language feature is introduced to support this I'd love it to be extended further and have C++ style capture list due to the flexibility it provides as described here #117.

**Comment by eyalsk** [comment]
> There is an outstanding question of whether it is acceptable to share the this

In my opinion it shouldn't, this approach should be all or nothing for two reasons:

1. Consistency.

2. Control - It can always be passed explicitly.

**Comment by mgravell** [comment]
@eyalsk interesting related ideas, thanks; the "capture list" approach looks nice, but is complicated; IMO C# is already bloating fast enough, and an "all or nothing" is probably a very pragmatic reasonable approach - especially since "all" is already the implicit default. In particular, the "capture list" approach is complicated by the fact that capture closures are already scoped and nested by declaration location. It may be nearly impossible to implement such that you're *not* capturing something extra by accident (where A captures x+y and B captures y+z - either A may also be silently capturing z, or B may be silently capturing x - in terms of fields on the state machine and lifetime)

**Comment by DavidArno** [comment]
Related issue: #275. Though the scope of this proposal is far narrower, and likely far easier to implement than that other one.

**Comment by Joe4evr** [comment]
> the "capture list" approach looks nice, but is complicated

Capture lists were suggested before and the team has rejected it.

**Comment by eyalsk** [comment]
@Joe4evr Doesn't mean it can't be reevaluated but again I understand the likelihood of it to be rejected again.

**Comment by TheUnlocked** [comment]
The use of `static` for this works surprisingly well with #832, as the function could be considered to be cached, and because of that, it couldn't possibly access something outside of _its_ scope.

**Comment by MkazemAkhgary** [comment]
Can static local function access instance members of current instance? or it will be static context?

my suggest is that local function (whether static or not) in instance method can access instance members. but local function in static method cant access instance members (pretty obvious)

```
int field;

void Foo()
{
    static void local()
    { 
        field = 0;
    }
}
```

**Comment by Drawaes** [comment]
The main problem is with avoiding accidental capture of a variable in the parent method thus causing allocations. I am not sure the above helps with that. 

Being able to make a local or annon method static means in the annon case the delegate can be single instance and cached. That the compilier can detect the capturing of variables and you can save a register as you don't need to pass a ref to "this".

It seems like the solution that adds no keywords, uses preexieting language semantics that are well known (static methods) and covers 90% of the situations. Also will allow for a better perf profile... Seems like a win, win, win

**Comment by yaakov-h** [comment]
I _really_ don't like the idea of a local function having the `static` keyword but retaining the ability to access instance fields, properties and methods.

**Comment by Drawaes** [comment]
Static local methods wouldn't have the ability to access instance fields or properties and methods would they? If they did then they would need the "this" ref passed in and I agree that would be nasty.

**Comment by HaloFour** [comment]
@Drawaes 

> The main problem is with avoiding accidental capture of a variable in the parent method thus causing allocations. 

Local functions don't incur the same penalty for capture as delegates do.  They don't cause any allocations, the enclosed variables are lifted to a struct and the function itself passed that struct with a `ref` parameter:

```cs
public int M(int x, int y) {
    int add() => x + y;
    return add();
}

//  translated into:
private struct DisplayClass {
    public int x;
    public int y;
}

private static int add(ref DisplayClass ptr) {
    return ptr.x + ptr.y;
}

public int M(int x, int y) {
    DisplayClass ptr = default;
    ptr.x = x;
    ptr.y = y;
    return add(ref ptr);
}
```

**Comment by benaadams** [comment]
> Local functions don't incur the same penalty for capture as delegates do. They don't cause any allocations, 

They do if they are async, even the presence of an async local function causes an allocation even if its not called; if it does any capturing https://github.com/dotnet/roslyn/issues/18946

**Comment by Drawaes** [comment]
Sorry my fault I should have specified that async was my major use case for them.

**Comment by Neme12** [comment]
> but this proposal allows the "obvious" names to be used consistently:
> 
> ```c#
> void Foo(int a) {
>     static void Bar(int a) {
>          Blah(a);
>     }
>     // ...
>     Bar(a);
> }
> ```

Why would you pass the same exact value instead of capturing it though? Isn't this what the compiler already does for you? You can be consistent and use the "obvious" name without declaring it twice.

**Comment by Drawaes** [comment]
Because it causes allocations.

**Comment by HaloFour** [comment]
@benaadams 

I see.  Yeah, there are several scenarios that cause local functions to use the delegate-style capturing rather than a struct, presumably because they all involve the potential lifting of that state into a value that must be able to persist beyond the lifetime of that method invocation.

Another example is when a method happens to also create a delegate that encloses over part of the method state, even if that enclosed state doesn't overlap with the state of the local function.

**Comment by sharwell** [comment]
I am currently investigating ways to leverage the ClrAllocationAnalyzer for practical performance purposes. For example, an analyzer that recognized [`PerformanceSensitiveAttribute.AllowCaptures`](https://github.com/dotnet/roslyn/blob/67f2d4338d3889d89c642ae4effebd49751d49d7/src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs#L49-L56) could report a warning if the constraint was violated, e.g. by a local function.

**Comment by Drawaes** [comment]
I get that an analyzer is nice but why not just stop it happening at all with the static word? It seems a little like the new get out of jail free card is "add an analyzer".

I tend to agree that sometimes that makes sense to stop language bloat but in this case a well known and understood concept like "static" is really not an addition to the library. Infact I would go so far as to say without static it's odd, any other method can be static (getters/setters, constructors, methods) so why not these two types of methods?

**Comment by HaloFour** [comment]
@Drawaes 

I think the idea there is that an analyzer can be done today whereas any language feature proposal has to endure the LDM process which is infinitely more protracted.  It also fits pretty well in this case since the expected behavior of the language feature is a warning/error if you try to capture in one of these local functions.

Regarding `static`, I agree that it's probably the best existing keyword for the job, but I personally don't think that it does so without some kind of expansion on its current definition.  Is the idea that the "method" has it's own "instance" which represents the locals and other state?

**Comment by Drawaes** [comment]
The definition would surely be as is today... There is no ref to this passed in and the method has access to it's stack as per any static?

**Comment by HaloFour** [comment]
@Drawaes 

> The definition would surely be as is today... There is no ref to this passed in and the method has access to it's stack as per any static?

That doesn't imply anything about the locals, though.  Static methods can freely capture their own locals and that doesn't involve any `this` pointer.

**Comment by benaadams** [comment]
Method is just like a regular static method; its just scoped to the parent method; so only has access to static variables and its own parameters.

**Comment by HaloFour** [comment]
@benaadams   Agreed, I just don't think that the current definition per the spec implies that relationship.

**Comment by Neme12** [comment]
> in this case a well known and understood concept like "static"

but this is not the well known meaning of the word static
1) it implies that the method is actually static and `this` doesn't get passed either - and it very well could be, but what if you wanted a method that doesn't capture but isn't static?
2) `static` could also be understood to mean that the function is static (no `this`) but does capture locals - if you told me about static local functions, this is what I would probably think they might mean

`static` never meant "doesn't capture" - I think we're mixing up 2 different meanings because you could very well imagine both A without B and B without A

**Comment by Joe4evr** [comment]
I agree that `static` might not be the best choice of keyword. I pointed out in the proposal for "static variables" (as linked earlier) that I'm not a fan of using the keyword `static` in that particular context, because it could still be lowered into an instance field.

**Comment by MkazemAkhgary** [comment]
what about `private`? still not accurate but maybe not as confusing as `static`

**Comment by eyalsk** [comment]
In what case it's going to be lowered into instance methods where the rules applied to it should match the exact same rules that apply to static methods today, additionally, it wouldn't share any state with the parent method.

**Comment by eyalsk** [comment]
@Name12

> it implies that the method is actually static and this doesn't get passed either - and it very well could be, but what if you wanted a method that doesn't capture but isn't static? that would be just as efficient

I really, honestly don't get what you're saying, if you don't use any external state and efficiency isn't an issue what's the point of making this statement? just mark it as static and enforce what you implicitly do without it!

> static could also be understood to mean that the function is static (no this) but does capture locals - if you told me about static local functions, this is what I would probably think that might mean

This is purely a design decision and to be honest I don't know why would you intuitively think that it would capture locals, I'd think the exact opposite simply because `var x = this`, now, `x` is available in the context of the local function so what's the point of disallowing it?

**Comment by eyalsk** [comment]
@MkazemAkhgary 

> what about private? still not accurate but maybe not as confusing as static

Apparently for some people "saying nothing" is less confusing than "saying something".

The private modifier doesn't add any information and the function is private by virtue so I really don't understand how can it be less confusing.

**Comment by MkazemAkhgary** [comment]
@eyalsk neither `static` nor `private` is confusing for me.

**Comment by Drawaes** [comment]
So I think this got off track. What I believe the original proposal was for was to be able to add the static modifier.

This was not to make the method "non capturing" as this concept doesn't exist today but instead to actually make the method behave exactly like a static does today just scoped. 

Now a side benefit from that is if you code all your local methods you can be marked static and you will get a compile warning for trying to capture a local because that wouldn't work in a static. Also you should save register space due to no "this" ref. 

But it would work like any other static method infact if you pulled it out into the surrounding class it would work the same.

**Comment by HaloFour** [comment]
@Drawaes 

> Now a side benefit from that is if you code all your local methods you can be marked static and you will get a compile warning for trying to capture a local because that wouldn't work in a static.

Why wouldn't that work in a `static`?

**Comment by Drawaes** [comment]
Why would it?

**Comment by HaloFour** [comment]
@Drawaes 

> Why would it?

Because capturing a local has nothing to do with being an instance method.  A local function written in a static method will produce another static method, while still capturing local state.

**Comment by MkazemAkhgary** [comment]
`static` is not accurate (some say its confusing) because meaning of static interferes with `this` instance. proposal is only about to prevent conflicting _local_ variable names and NOT to prevent accessing instance members. 

`this` should be shared so that fields, properties, methods can be still accessed via local function so its more useful than just what static method offers. 

---

I think `new` keyword is better keyword to intend the hiding of enclosing scope. it does not interfere with `this` instance either.

```
Baz Property { get; set; }

void Foo(int a) {
    new void Bar(int val) {
         // can not use "a" but can happily use Property
    }
    // ...
    Bar(a);
}
```

**Comment by TheUnlocked** [comment]
If you want to use `this` or other non-static members, pass `this` in as an argument. I think that's a much more sensible way of handling things over using `new` or `private` in contexts that make very little sense.

**Comment by MkazemAkhgary** [comment]
that's not nice. local function is about to help with readability. now you are saying to pass this by hand? add extra parameter and access every instance member by referring to name of that parameter? 

No Thanks! I prefer to use good old approach and write instance private method.

How come` static` makes more sense anyway? `static` only prevent accessing `this`. I don't see how it suggests to _hide_ enclosing scope?

**Comment by benaadams** [comment]
> How come `static` makes more sense anyway? `static` only prevent accessing `this`. I don't see how it suggests to hide enclosing scope?

A `static` method in a class hides its enclosing scope; you can't access and of its instance data or call any of its instance methods - only call static functions and access static data.

Likewise a static local function shouldn't have access the the parent functions local state or the classes instance state, much like a regular static function.

The static local function is providing scoping so as not to pollute the class with a static function which is only called in a single method.

**Comment by MkazemAkhgary** [comment]
@benaadams  Makes sense. but that's what OP was concerned about. the meaning of static... I think he proposed this (and picked up `static`) solely to avoid naming problems not to prevent accessing `this` instance. 

but why do I bother anyway! I'm being careful man here. I'm not going to make these little mistakes....
hopefully 😀

**Comment by HaloFour** [comment]
@benaadams 

I'm totally game with `static` being defined to mean that in the C# specification in order to facilitate this request (and the similar request for delegates).  I only brought it up as there seems to be an argument here that the definition of `static` seems to already imply this, and that by somehow eliminating an imposed limitation of applying `static` to local functions would somehow prevent enclosing locals.  Nothing that I see in the C# verbiage would seem to make that happen.

**Comment by stakx** [comment]
I agree with the proposal (didallowing capture) but I am also one of those unhappy about the choice of keyword (`static`). This will just make the meaning of "static" unnecessarily ambiguous.

Why does this require a specific language construct at all? IMHO this problem couöd be easily solved with an analzer IF it were possible to place custom attributes on local methods:

```csharp
void Outer(int arg)
{
    [ShouldNotCapture]
    int Inner()
    {
        return arg; // analyzer complains about captured `arg`
    }
}
```

IIRC custom attributes on local methods has already been proposed elsewhere, so if that feature made it in all that's required is an additional analyzer (maybe as part of the new warning wave thingy that's also being planned).

**Comment by Drawaes** [comment]
Attributes are an ugly coding construct for something that I would consider to be very common place. And especially smack bang in the middle of a function that you are nested in.

**Comment by stakx** [comment]
@Drawaes: Imagine the attribute were called `[Static]`. (Horrible idea, but for argument's sake only.) The *visual* "ugliness" would consist of an additional set of angle brackets and a letter being in upper-case. But perhaps you didn't mean the visual aspect at all, rather the *conceptual* ugliness, i.e. that custom attributes (being a "meta" feature) shouldn't be used for a core feature. In that regard, I tend to agree. But overloading the meaning of `static` is equally (conceptually) ugly. The only good thing about it would be its visual familiarity. In that case I'd much rather see explicit (possibly empty) capture lists.

**Comment by Drawaes** [comment]
So .. yes the conceptual as well as the extra line an attribute usually has is ugly. I tend to agree that maybe static isn't the correct term and to be honest an inner function should be able to say access a class level member variable.

**Comment by stakx** [comment]
@jnm2:

> A static local function would be static in exactly the same sense as a static method, right?

Perhaps I am slow to understand, but no, I read the proposal differently. It suggests that `static` on local methods "divorces all state" (i.e. it would supposedly disallow variable capture from the enclosing method and possibly further).

So for example:

```csharp
static int staticField;

static void Outer()
{
    var local = 7;
    staticField = 42;

    Inner();

    static void Inner()
    {
        local = 8; // disallowed?
        staticField = 43; // disallowed?
    }
}
```

My understanding of present-day `static` is "belongs to the type, not to an instance of that type". If `static` had this meaning in all circumstances (including when placed on local methods), then both `local = 8` should be allowed (because we're talking local variables here, which have nothing to do with static/instance members) as should be `staticField = 43` (because both the field and the method are static).

However, according to the proposal, at least one if not both assignments become illegal because they access outer state.

**Comment by HaloFour** [comment]
@stakx 

```cs
public class C {
    static int staticField;
    int instanceField;

    public void Outer() {
        int local = 0;

        static void Inner() {
            local = 123; // fail, can't capture locals
            instanceField = 456; // fail, can't capture this
            staticField = 789; // fine, doesn't require capturing anything
        }
    }
}
```

**Comment by jnm2** [comment]
@stakx Then it sounds like you'd be happy with `static` being used the way they are planning in #1565 (as in HaloFour's example)?

**Comment by Drawaes** [comment]
I am not convinced you shouldn't be able to capture this. As that isn't a "capture" in the normal sense of the word and very unlikely to be the perf hit most worry about and is driving the feature? I could also be wrong ;)

**Comment by TheUnlocked** [comment]
To add to the above, there is a case to be made that static in this context would mean static to the enclosing function but not to the instance. However, I'm not going to be the one making that case. ;)

**Comment by stakx** [comment]
@Halo: I'd actually be fine with that if that were the end result. BUT please note that this doesn't require a redefinition of what `static` means. The fact that you'd no longer be able to catch locals and instance fields would be a useful side effect, and `static` would keep the meaning it's always had. But that's not what this proposal wants:

> Proposal: modifier (perhaps "static") for local functions, to explicitly disallow captured state semantics

The meaning of the modifier (`static`) would be to disallow capture. This is *not* what present-day `static` is for, and neither should it assume that new, additional meaning. (Even though the end result would be that it *would* in effect disallow capture of all but static fields.)

> Proposal: allow the static modifier on local functions, to express the intent to divorce all state. 

Again, `static` doesn't mean "divorce all state" and neither should it assume that new meaning.

By all means, go ahead with the proposal, but please don't specify this new feature in a way that gives `static` a new meaning. Make it clear that `static` simply has a beneficial side effect in this particular situation.

**Comment by jnm2** [comment]
@stakx 

> But that's not what this proposal wants:
> > Proposal: modifier (perhaps "static") for local functions, to explicitly disallow captured state semantics

By disallowing captured state, you disallow capture of `this` and thereby, access to instance fields, but no capture is necessary to access static fields and therefore you aren't enforcing purity. I didn't see anyone ask for disallowing access to static state, though maybe I missed it.

**Comment by stakx** [comment]
@jnm2: I agree with what you're saying. What I am objecting against are alternate definitions such as "divorce all state" (which would include static state btw.) or "disallow capture" being affixed to `static` because that'd simply make `static` have at least two meanings.

**Comment by jnm2** [comment]
I follow though, I'm not sure if you're right. To get to the point: how *would* you define the current meaning of `static`?

**Comment by stakx** [comment]
@jnm2: As above. I don't have the spec at hand but basically, `static` should mean "this member does not belong to an instance of this type, but to the type itself".

**Comment by jnm2** [comment]
@stakx You could expand that definition to, "this member does not capture instance or local state." Then `static` wouldn't have two meanings; it would have a single meaning, clarified to apply in more contexts.

Like variables being added in Newtonian physics that had been negligible in previous contexts, and so were not talked about until relativity came around.

**Comment by stakx** [comment]
@jnm2: In my eyes, that wouldn't be an expansion of the existing definition, but a replacement, because I simply don't perceive `static` as having anything to do with capture.

Sure, I can get used to a new, different, but also more general meaning for `static` -- I just can't say that I like the idea of it very much, especially if such a radical redefinition could potentially be avoided.

I guess I've made my argument sufficiently clear, so I won't raise any further objections. :)

**Comment by benaadams** [comment]
>  because I simply don't perceive `static` as having anything to do with capture.

Adding that it "doesn't capture instance or local state"; means it still doesn't have anything to do with capture :)

**Comment by stakx** [comment]
@benaadams: No. But you've now associated it with that term, with previously was an altogether separate thing. If I added to the definition of `static`, "but it isn't orange" then you'd probably wonder too why that definition needs to mention colour at all. (A definition for X would ideally say what X is, not what it isn't.)

**Comment by stakx** [comment]
@jnm2: +1. Tiny nitpick: "other static members defined in the same scope, or in an enclosing scope". (Otherwise a local method defined in method A could access a local method defined in method B.)

**Comment by jnm2** [comment]
@stakx Is that necessary though? Local functions aren't considered members, are they?
Item 2 could be "accessible static type members."

**Comment by jnm2** [comment]
@stakx Is that necessary though? Local functions aren't considered members, are they?
Item 2 could be "accessible static type members."

There's a bit more to it than this aspect, anyway 😁 https://github.com/dotnet/csharplang/blob/master/spec/classes.md#static-and-instance-members

**Comment by eyalsk** [comment]
It's not like we don't have keywords that are used in different contexts in the language, e.g., `using` so why this is any different? I mean `static` isn't clear enough? or I'm missing something? but really context is important so I can't see what's the issue with "redefinition" when it's applied to a different context. 

Just my 2c. 😄

**Comment by jnm2** [comment]
@eyalsk My gut feeling is that it's not necessarily a good thing when that happens, if that's happening. But you could be right.

**Comment by CyrusNajmabadi** [comment]
Honestly... the more i use c++ the more i just like capture lists.  I think it's good that C# defaulted to 'allow capture'.  But i think it would be fine to be able to just say ```(a, b, c)[] => ...``` (no capture for you!).  It's incredibly brief and simple and gives exactly the behavior you want.  And, it easily extends to being able ot say "actually... i do want to be able to capture something, but specify what it is".  

The fact that it's only two chars to prevent any capturing at all is really nice for me...

**Comment by gafter** [comment]
See https://github.com/dotnet/csharplang/issues/1565

**Comment by mgravell** [comment]
Woohoo, this appears to be in the 8.0 beta in VS 16 preview 2, and it works *great*.

**Comment by jcouv** [comment]
I'll go ahead this issue since it is a duplicate (and already implemented too ;-) ).
https://github.com/dotnet/csharplang/issues/1565
