### ISSUE TITLE
Allow inline variable declaration for in and ref parameter types

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#1289]
@Kentalot commented on [Mon Jan 29 2018](https://github.com/dotnet/roslyn/issues/24525)

**Version Used**: 
I'm using C# 7.2 and version 15.5.3 of VS 2017 Enterprise.

**Steps to Reproduce**:

``` C#
private static void GetValue(out string input)
{
    input = null;
}
private static void DoNothing(ref string input)
{
}

private static void DoNothingIn(in string input)
{
}

private static void Call()
{
    GetValue(out var x);
    DoNothing(ref var y = x);
    DoNothingIn(in var z = null);
}
```

**Expected Behavior**: Compiles and y is usable after calling DoNothing and z is usable after calling DoNothingIn and all of x, y, and z are basically null;

**Actual Behavior**:
Does not compile since you can't inline declare variables for ref or in keywords.  I hope that's clear.  Thanks!

---

@HaloFour commented on [Mon Jan 29 2018](https://github.com/dotnet/roslyn/issues/24525#issuecomment-361463569)

Proposals to change the behavior of the language are taken at the [C# Language](https://github.com/dotnet/csharplang/) repository.

**Comment by MkazemAkhgary** [comment]
Also #1077.

**Comment by Kentalot** [comment]
Thanks guys.  Sorry for posting in the wrong repo.  #1077 is similar for the ref part, but I guess mine is new-ish that it's requesting a similar thing for the in keyword (I know they're related).  But anyway, thanks for considering my request!

**Comment by reinspi** [comment]
Probably it is may sense to allow symmetry assignment for `out` operator too. It is useful with null propagation operator and conditional expressions to avoid a compile error
`[CS0165] Use of unassigned local variable`

Consider this sample
```c#
var name = "John";
if (GetPerson()?.Name.To(out name) != null)
    Console.WriteLine($"Person name is {name}");
else Console.WriteLine($"Default name is {name}");
```
Currently we have the compile error for code
```c#
// var name = "John";
if (GetPerson()?.Name.To(out var name) != null)
    Console.WriteLine($"Person name is {name}"); /* Use of unassigned local variable 'name' */
else Console.WriteLine($"Default name is {name}");
```
But it may be solved
```c#
if (GetPerson()?.Name.To(out var name = "John") != null)
    Console.WriteLine($"Person name is {name}");
else Console.WriteLine($"Default name is {name}");
```

Of course similar logic may be applied for pattern matching too if needed.
```c#
if (GetPerson()?.Name is string name = "John")
    Console.WriteLine($"Person name is {name}");
else Console.WriteLine($"Default name is {name}");
```

**Comment by reinspi** [comment]
[A more simple code example](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMBuAWAChUBmbHANmwCYKB2TAb2Mze3N2tQBYKAOABQBKZq3YTcWAMYQAzsAD2AWwDKwMAEsoAc0wBeTACJSNHEbyYA9FcwBxAKbAAwvKVqN2nSMJEJEgCNFRQAbTA0ATwBVOQdXBRUANQBDEIgHA3DIB0sbeycAFTBo2Pj3FLSHH2IASBrxf0wAN2SwTE1MnBpSX0a2TQAzTEFImLi3JNT0zAAyGfaoYAA6IoiABVbYwVkEjy1dGExFCGB24WEGvrZcAE5BABIjMpVmqYymTQBfI2FevocQrEKHdHgARBwDZIQEKnFqVZhfH5/NifYifIA===) for my previous comment
```c#
string customString = "321"; // GetCustomString();
bool tryUseCustomValue = true; // GetTryUseCustomValue();
		
var i = 123;
if (tryUseCustomValue && int.TryParse(customString, out i))
    Console.WriteLine($"Custom value {i}");
else Console.WriteLine($"Default value {i}");
```
Nice to have
```c#
//var i = 123;
if (tryUseCustomValue && int.TryParse(customString, out var i = 123))
    Console.WriteLine($"Custom value {i}");
else Console.WriteLine($"Default value {i}");

//if (tryUseCustomValue && int.TryParse(customString, out var i))
//    Console.WriteLine($"Custom value {i}");
//else Console.WriteLine($"Default value {i}"); /* Cause 'Use of unassigned local variable 'i' */
```
Hope it is clear.

**Comment by MkazemAkhgary** [comment]
@ghost symmetry for `out` would be post assignment.

        public bool Foo<T>(out T x)
        {
            return Bar(x = out var y);
        }

pre assignment is not possible, because methods with `out` parameter are always forced to initialize out parameter which leads to overwriting your argument. its completely unexpected behavior.
