### ISSUE TITLE
Proposal: per-property scope syntactic sugar

### ISSUE THREAD

**Issue by DoktorDemento** [dotnet/csharplang#1290]
# Proposal

This pattern is extremely common:
```c#
private int _backingField = 5;

public int PropertyWithBackingField
{
    get
    {
        return _backingField;
    }
    set
    {
        _backingField = value;
        update();
    }
}
```
What if the property body was its own scope?
```c#
public int PropertyWithBackingField
{
    int _backingField = 5;
    
    get
    {
        return _backingField;
    }
    set
    {
        _backingField = value;
        update();
    }
}
```

This would also be useful for cached properties. Single-use calculation methods could be kept inside the property which uses them:
```c#
private readonly ConcurrentDictionary<string, double> _cache
    = new ConcurrentDictionary<string, double>();

public double CachedProperty
{
    get
    {
        return _cache.GetOrAdd("KeyString", calculateValue);
    }
    
    double calculateValue()
    {
        return Math.Sqrt(5);
    }
}

```

The main benefit of this proposal is that it would allow proper encapsulation of backing members, by preventing access by any means other than their associated property.
# Notes
* Members inside a property would be scoped to the property only, as they won't be needed elsewhere. Therefore they don't need access modifiers.
* This would probably be best done as syntactic sugar, where property members would actually be private members of their containing class (with a prefix to avoid collisions).

**Comment by DoktorDemento** [comment]
Opening in error - saw https://stackoverflow.com/questions/12098745/property-backing-value-scope while looking for previous suggestions. Add my vote to those asking for this, anyway :)

**Comment by HaloFour** [comment]
#133

**Comment by Unknown6656** [comment]
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md

**Comment by jnm2** [comment]
@Unknown6656 #140 (use backing field without naming it) was discussed in that meeting, but this one is a duplicate of #133 (declare normal fields with property scope) which is not a direct duplicate.
