### ISSUE TITLE
functions without heap allocation

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1297]
it would be nice to have an special struct function like this

```
public ref struct ValueFunc<TIn, TOut>
{ //...
}
```

Plus it should be only passed by reference. compiler must enforce this rule.

Since whole function resides inside stack (ref struct) and function is always passed by reference (special treatment from compiler), heap allocations could be avoided while capturing local variables.

this also works nicely with `in` parameters. because method would only take `in ValueFunc<>` with no change in caller. so something like this

```
AddOrUpdate(key, () => value, x => {});
```

does not allocate anything on heap.

**Comment by yaakov-h** [comment]
#302?

**Comment by MkazemAkhgary** [comment]
@yaakov-h Oh I see, thanks. cool! I was totally ready to get comments like why you want to do this. its not reasonable. its nonsense. bla bla! ... haha. 

closing as duplicate ;)
