### ISSUE TITLE
Feature Request: .ToDictionary method for IEnumerable<KeyValuePair<IKey,IValue>> returning Dictionary<IKey,IValue>

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/csharplang#1299]
Often it would be useful to be able to create a Dictionary<IKey, IValue>from an IEnumerable<KeyValuePair<IKey, IValue>>. With that, it would be easier to initialize Dictionaries from LINQ Expressions. Furthermore, it would make the code for initializing Dictionaries far more readable. The Method would be defined as below:
```
public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(
     this IEnumerable<KeyValuePair<TKey, TValue>> src)
{
     return src.ToDictionary(keyValuePair => keyValuePair.Key, keyValuePair => keyValuePair.Value);
}
```

**Comment by CyrusNajmabadi** [comment]
This should be moved to https://github.com/dotnet/corefx.  That's where API design goes for the base class libraries.  Thanks!

**Comment by TheMinefighter** [comment]
Moved
