### ISSUE TITLE
expression precedence table in introduction missing nameof(x)

### ISSUE THREAD

**Issue by bbarry** [dotnet/csharplang#13]
https://github.com/dotnet/csharplang/blob/master/spec/introduction.md#expressions

    |                                  | `default(T)`      | Obtain default value of type `T` |
    |                                  | `delegate {...}`  | Anonymous function (anonymous method) |

should be 

    |                                  | `default(T)`      | Obtain default value of type `T` |
    |                                  | `nameof(x)`       | Obtain the name of `x` as a constant string |
    |                                  | `delegate {...}`  | Anonymous function (anonymous method) |

**Comment by MadsTorgersen** [comment]
Thanks, good catch!

Since this isn't yet authoritative source, I'll keep these spec defects around for later application.

**Comment by gafter** [comment]
Not sure how much it is needed. Syntactically, a nameof expression is treated as an invocation expression.

**Comment by bbarry** [comment]
The elvis operators are also missing (I'm not entirely sure how to even bring that up; are they unary in this table based on [this](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#unary-operators)?). I suppose it comes down to whether the table here is an authoritative source vs a high level summary of the language's expressions. 

Syntactically to the rest of the spec nameof doesn't seem much different than `checked(x)`, `unchecked(x)` or `default(T)` which are all in the table except for the quirk where it might not be a keyword and then becomes an invocation expression.

**Comment by BillWagner** [comment]
I'm closing this.  This entire clause has been removed from the C# standard in V5. The new expressions are added in the expressions chapter in the correct location.
