### ISSUE TITLE
Declare lambda with deconstructed value tuple argument

### ISSUE THREAD

**Issue by steevcoco** [dotnet/csharplang#1302]
Perhaps not an issue, but a request ... Don't know where to post such a thing.

Can't declare a lambda with a deconstructed value tuple parameter:

Declaring `Func<(bool aBool, int aInt), bool>` as a lambda must not have the deconstructed form:

    ((bool aBool, int aInt)) => aBool

Must be:

    ((bool aBool, int aInt) tuple) => tuple.aBool

**Comment by MkazemAkhgary** [comment]
you can omit data types in lambda. they are inferred automatically. so you can write

    tuple => tuple.aBool

which is even shorter than what are were looking for.

**Comment by MkazemAkhgary** [comment]
but I think there is similar problem is in method signatures. you can see why it doesn't make sense for a method to have a deconstructed parameter, because that's literally two separate parameters not a tuple.

    public void Method((bool aBool, int aInt)) // doesn't work. there is no tuple, whats the point of deconstruction here?
    public void Method(bool aBool, int aInt) // works.

I think that the same goes for lambdas here.

**Comment by steevcoco** [comment]
Yes; I see. Gee I'm dumb! Sorry: you are actually completely right.

In my first example, I included the explicit Func declaration as an example. In code, you would have some interface to call that can capture the type; like:

    interface IInvoke<TIn, TOut>
    {
        void Invoke(Func<TIn, TOut> func);
    }

And then you want to invoke it with a tuple lambda. I completely wrongly tried to capture in the deconstructed syntax:

    IInvoke<(bool b, int i)> my;
    my.Invoke(((bool b, int i)) => i);

I just wrote a 'half-deconstructed' tuple! I wanted the compiler to infer the tuple type, and I just stupidly wrote the whole tuple instead of just a name ... Obviously, you can capture it like you said with just a simple parameter name ... and I see the compiler will even pick out the tuple field names too!

    IInvoke<(bool b, int i), int> my = default;
    my.Invoke(t => t.i);

Sorry! A bunch of new capturing came out, and I just got clarified!
