### ISSUE TITLE
why implicit cast for tuples doesnt work?

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1305]
Is there any specific reason why this cast is not allowed to be implicit. even if I define implicit operator.

    public static implicit operator Foo((A , B) t)
    {
        return new Foo(t.Item1, t.Item2);
    }

this works but only with explicit cast, but I think it should be implicit because I said so. is this trying to be idiot-proof or something?

**Comment by svick** [comment]
[It works for me.](https://sharplab.io/#v2:D4AQTABAYg9jCwAoA3ki6IgIwDZMBZMsAOACgEo0NVEM7o4IAPCAXglPzABoJ8BmcgG4q6AL6iISAJAh+RPAEsAtgAcANooDGigC4QYqgKYAnAIa6YJhjFKlFAO129Hu8hDcya0uiADsEA5GAO42pLoAdACSukbKWLyRMXFgwjISiNIycmGuEIouThAAVu7IGWJAA===)

Could you share a complete example program that doesn't work the way you expect it to work?

**Comment by MkazemAkhgary** [comment]
I see. It doesn't work for generics though. what is the reason? hmm

    public class Program
    {
        public static void Main()
        {
            var t = (1, 5);
            Test(t);
        }

        public static void Test<T>(Foo<T> foo)
        {
        }
    }

    public struct Foo<T>
    {
        int x;
        T y;

        public Foo(int x, T y)
        {
            this.x = x;
            this.y = y;
        }

        public static implicit operator Foo<T>((int x, T y) t) => new Foo<T>(t.x, t.y);
    }

It seems overload resolution cant infer types inside tuple.

**Comment by svick** [comment]
That's not related to tuples, I think type inference doesn't work with implicit casts. This code [produces the same error](https://sharplab.io/#v2:D4AQTABCCMDsCwAoA3ki6rQGxQCyYA4AKASjQ1UQ2ogEsA7AFwmYF4JoBucmiAFQCmAZ0ZFGJblQwBfJDygBmTDhD5BIgDx8AfEQBiAewNbtEAGZGSEZBFmI7SEQCcArgGNmh4zqSVqIJRgcWgBbAAcAG1o3WmYDMIEnAENGAycILxMiPggATytWUwATATMklwjGSWkgA===):

```c#
class Program
{
    static void Main()
    {
        int t = 1;
        Test(t);
    }

    public static void Test<T>(Foo<T> foo) { }
}

struct Foo<T>
{
    public static implicit operator Foo<T>(T y) => default;
}
```

And both examples work if you specify the type argument explicitly, i.e. `Test<int>(t)`.

**Comment by MkazemAkhgary** [comment]
I see. I think type inference doesnt work for user-defined implicit casts.
