### ISSUE TITLE
multiple exception types with the same handler

### ISSUE THREAD

**Issue by chmely** [dotnet/csharplang#1312]
It would be nice to be able to specify one catch clause for multiple exception types, e.g.

try {...}
catch (InvalidCastException [ex1], FormatException [ex2])
{
  // common handler for both
}
catch (Exception ex)
{
  // generic handler
}

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/164

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/399

or 

```cs
try {...}
catch (Exception ex) when (ex is InvalidCastException || ex is FormatException)
{
    // common handler for both
}
catch (Exception ex)
{
    // generic handler
}
```

**Comment by jnm2** [comment]
This is also an exact duplicate of https://github.com/dotnet/csharplang/issues/519 and is similar to https://github.com/dotnet/csharplang/issues/235.

**Comment by YairHalberstadt** [comment]
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/519
