### ISSUE TITLE
static extension methods

### ISSUE THREAD

**Issue by chmely** [dotnet/csharplang#1313]
For code cleanness I'd love to be able to do something like this:

public static int ParseOrDefault(class int T, string s, int defautValue)
{
    return T.TryParse(s, out int result) ? result : defaultValue;
}

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/164

**Comment by DavidArno** [comment]
@ufcpp,

Have you created some sort of database of topics vs issue numbers, or are you simply very good at remembering and searching? 😀

**Comment by ufcpp** [comment]
I'm simply remembering.

**Comment by jnm2** [comment]
@DavidArno I almost jumped on these but figured someone else would do it and save me the trouble.

@chmely This issue is an exact duplicate of https://github.com/dotnet/csharplang/issues/1010 and is covered by https://github.com/dotnet/csharplang/issues/192.

**Comment by MkazemAkhgary** [comment]
@DavidArno he got the dictionary in his head. I probably have linked list :(

**Comment by YairHalberstadt** [comment]
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/1010
