### ISSUE TITLE
Allow different types in declaration statement

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1319]
sometimes It helps to reduce lines. I know its somewhat an edge case scenario, but it also takes near zero effort to allow this. (minor change in syntax analyzer will do)

    Foo foo, Bar bar; // allow this

Is there strong reason why it should be disallowed?

**Comment by MkazemAkhgary** [comment]
I will pull the trigger if you suggest 

    Foo foo; Bar bar;

**Comment by stakx** [comment]
What are C#'s current rules regarding pointer types (in an `unsafe` context)? Is something like `T * a, b` currently allowed? If not, I could imagine that what you're proposing was disallowed to prevent such variable declarations that can easily be misunderstood by human readers (e.g., is `b` a `T` or a `T*`?).

**Comment by quinmars** [comment]
What about:

```csharp
Foo foo, Bar bar, foobar;
```
What type will have `foobar`? And may I ask what is wrong about the semicolon?

```csharp
Foo foo; Bar bar;
```

**Comment by MkazemAkhgary** [comment]
editors tend to add line break after semicolons. that is annoying to me. 

but for that case it could be

    Foo foo1, foo2, foo3, Bar bar1, bar2;

or even

    Foo foo1 = f1, foo2, foo3, Bar bar1, bar2 = b2;

**Comment by yaakov-h** [comment]
Editors can be changed a lot easier than the language.

**Comment by quinmars** [comment]
@MkazemAkhgary IMHO, your examples would be more readable with an semicolon.

BTW: Your proposed syntax is a special case of the _C comma operator_. I pray that the _comma operator_ will never make it into C#.  Fortunately, this is very unlikely, because it conflicts with tuples in many places since C#7.

**Comment by HaloFour** [comment]
> sometimes It helps to reduce lines.

You can reduce lines by not introducing lines.  There's nothing wrong with putting two declarations on a single line separated by a semicolon.  Neither the compiler nor Visual Studio will force you to separate them.

**Comment by MkazemAkhgary** [comment]
fair enough

**Comment by CyrusNajmabadi** [comment]
> Foo foo, Bar bar;

What about:

```Foo foo; Bar bar;```

Why is comma valuable here as there's already an existing language construct to do the separation that has been legal since C# 1.0 and which is exactly the same length and complexity as what you have up there?

**Comment by CyrusNajmabadi** [comment]
> editors tend to add line break after semicolons.

Fixing an editor is roughly 100-1000x cheaper than making a language feature (that's a serious estimate btw, not a joke).

**Comment by CyrusNajmabadi** [comment]
> What are C#'s current rules regarding pointer types (in an unsafe context)? Is something like T * a, b currently allowed? 

It's definitely allowed.  Unlike C, the pointer belongs to the type, not the variable.  So in C# that's the declaration of two variables ('a' and 'b') both of type ```T*```.
