### ISSUE TITLE
multi dimentional enumerator

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1322]
Since covariance is not possible for tuples 

    public interface IX<out T1, out T2> : IEnumerable<(T1, T2)>

I came across this idea.

    public interface IEnumerator<out T1, out T2> : IDisposable
    {
        T1 Current1 { get; }
        T2 Current2 { get; }

        bool MoveNext();
    }

    public interface IEnumerable<out T1, out T2>
    {
        IEnumerator<T1, T2> GetEnumerator();
    }

It would be very nice to have foreach directly support this. given that c# has become friend with tuples. 

     foreach(var (x, y) in source)
     {
     }

so `Current` or `Current1` to `CurrentN` is first parameter or parameter 1 to N. currently I can use extension methods. but I thought maybe its good to propose it here.

        public static IEnumerable<(T1, T2)> AsEnumerable<T1, T2>(IEnumerable<T1, T2> source)
        {
            var enumerator = source.GetEnumerator();

            while (enumerator.MoveNext())
            {
                yield return (enumerator.Current1, enumerator.Current2);
            }

            enumerator.Dispose();
        }

**Comment by CyrusNajmabadi** [comment]
Sorry, the problem statement is far too abstract.  What practical problem are you trying to solve? Can you give the actual concrete situation?

**Comment by MkazemAkhgary** [comment]
Its a simple key value enumeration over B+tree. 

It could be useful for dictionary and other indexed collections as well.

**Comment by CyrusNajmabadi** [comment]
> Its a simple key value enumeration over B+tree.

Why are the existing ```IEnumerable<>/IEnumerator<>``` solutions not good enough for that purpose?  I've written B+ tree code (and lots of other collections), and i can't recall a situation where I would need an interface like yours.

**Comment by MkazemAkhgary** [comment]
I want to have key and value at same time.

Another approach using linq would be to iterate on

    src.Keys.Zip(src.Values, (k, v) => (k, v));

Key is part of data i.e choosen as key. But they are stored seperately. Another approach would be to store keys as duplicate in data but it should be immutable. Changing the key becomes a little complicated.

I guess my problem is not common.

**Comment by CyrusNajmabadi** [comment]
> I want to have key and value at same time.

Dictionaries already give you this.  

```c#
var d = new Dictionary<int, string>();
d.Select(kvp => /* do whatever you want with kvp.Key and kvp.Value */);
```

**Comment by CyrusNajmabadi** [comment]
> I guess my problem is not common.

You still haven't explained what your problem is :)    All you've said is "I want to have key and value at same time."  I don't know why that's an issue, or why there's any difficulty using that today with the existing corefx and language features.

In the future, can you fully describe the problem you're having and why the existing system isn't sufficient?

**Comment by MkazemAkhgary** [comment]
Well i want things to be kept in order. Thats why i choosed B+tree. I also want covariance so linq operations like concat will be simpler (no verbous casts and generic arguments). I have to map linq operations to this new enumerable though.

**Comment by MkazemAkhgary** [comment]
Imho .net is missing greatness of B+tree. Im writing an API for this. And i want everything to look solid.

**Comment by CyrusNajmabadi** [comment]
So what is the problem you're facing?  You still haven't explained it :)

**Comment by MkazemAkhgary** [comment]
I guess my problem is solved now! I closed the issue

**Comment by CyrusNajmabadi** [comment]
Ok... great.  :)   In the future keep in mind what i mentioned about 'X' and 'Y'.  Please include far richer information with your feature requests to help give readers an idea about what issue you're trying to solve.  Thanks!

**Comment by MkazemAkhgary** [comment]
I see. I really have to practice on that. Thanks for noting that. I also realized it was XY problem. Just now! hehe

**Comment by jnm2** [comment]
Have you tried @sharwell's https://github.com/tunnelvisionlabs/dotnet-trees?
