### ISSUE TITLE
Can we have C# able to infer complex generic

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#1324]
I don't know if this is duplicate but the keyword of this was so hard to find

The problem is C# cannot infer complex generic

```C#
public void DoSomething<E,T>(E items) where E : IEnumerable<T>
{
}

int[] numbers;
DoSomething(numbers);
```

Will cause an error that generic method cannot infer from usage

Is it possible to let it could? Also I wish that these kind of method could allow mapping with extension method too

**Comment by MkazemAkhgary** [comment]
#1103, #1018, #997, non of my tries worked!

[more links on this comment](https://github.com/dotnet/csharplang/issues/997#issuecomment-336421033)

**Comment by gafter** [comment]
@agocke is investigating extending type inference to take constraints into account.
