### ISSUE TITLE
[Proposal] Ambient parameter values to simplify passing of common parameters

### ISSUE THREAD

**Issue by theunrepentantgeek** [dotnet/csharplang#1332]
# Proposal

A new block scoped construct that allows uniquely typed parameter values to be omitted from the point of call if they are the last parameter.

## Syntax

```csharp
ambient (expression)
{
    // code
}
```

# Motivation

Sometimes you find a block of code that is passing the same parameter value in a large number of places, cluttering the code. 

Common examples include loggers, transactions, caches, request contexts, cultural information, and async cancellation tokens. Seeing these passed into every method call doesn't improve the readability of the code, it just clutters things up.

## Example 1

Recently I saw some parsing code where a separate lambda expression had to be specified for serialization and deserialization of each value. The various `ToString()` and `Parse()` methods all need an `IFormatProvider` so that the conversion to/from a string is done in the correct manner. This resulted in code that repeated the same `CultureInfo` value over and over, something like this recreation:

``` csharp
var parser = new Parser<ConnectionStatistics>();
parser.AddProperty(
    nameof(ConnectionStatistics.TargetRate),
    rate => rate.TargetRate.ToString(CultureInfo.InvariantCulture),
    (stats, rate) => stats.TargetRate = int.Parse(rate, CultureInfo.InvariantCulture));
parser.AddProperty(
    nameof(ConnectionStatistics.AverageRate),
    rate => rate.AverageRate.ToString(CultureInfo.InvariantCulture),
    (stats, rate) => stats.AverageRate = double.Parse(rate, CultureInfo.InvariantCulture));
parser.AddProperty(
    nameof(ConnectionStatistics.PeakRate),
    rate => rate.PeakRate.ToString(CultureInfo.InvariantCulture),
    (stats, rate) => stats.PeakRate = double.Parse(rate, CultureInfo.InvariantCulture));
parser.AddProperty(
    nameof(ConnectionStatistics.Start),
    timestamp => timestamp.Start.ToString(CultureInfo.InvariantCulture),
    (stats, timestamp) => stats.Start = DateTimeOffset.Parse(timestamp, CultureInfo.InvariantCulture));
parser.AddProperty(
    nameof(ConnectionStatistics.Finish),
    timestamp => timestamp.Finish.ToString(CultureInfo.InvariantCulture),
    (stats, timestamp) => stats.Finish = DateTimeOffset.Parse(timestamp, CultureInfo.InvariantCulture));
```

The repetition of `CultureInfo.InvariantCulture` is necessary to the correct operation of the code: skipping the parameter would lead to some very odd results if the information saved by one user with particular cultural settings was reloaded by another user with different settings.

But, the readability of the code suffers. 

Introducing a block context to provide the common value would simplify the code, making significantly easier to read:

``` csharp
ambient(CultureInfo.InvariantCulture)
{
    var parser = new Parser<ConnectionStatistics>();
    parser.AddProperty(
        nameof(ConnectionStatistics.TargetRate),
        rate => rate.TargetRate.ToString(),
        (stats, rate) => stats.TargetRate = int.Parse(rate));
    parser.AddProperty(
        nameof(ConnectionStatistics.AverageRate),
        rate => rate.AverageRate.ToString(),
        (stats, rate) => stats.AverageRate = double.Parse(rate));
    parser.AddProperty(
        nameof(ConnectionStatistics.PeakRate),
        rate => rate.PeakRate.ToString(),
        (stats, rate) => stats.PeakRate = double.Parse(rate));
    parser.AddProperty(
        nameof(ConnectionStatistics.Start),
        timestamp => timestamp.Start.ToString(),
        (stats, timestamp) => stats.Start = DateTimeOffset.Parse(timestamp);
    parser.AddProperty(
        nameof(ConnectionStatistics.Finish),
        timestamp => timestamp.Finish.ToString(),
        (stats, timestamp) => stats.Finish = DateTimeOffset.Parse(timestamp));
}
```

I suggest that this second block of code is significantly easier to read and understand - the reduction in clutter makes a non-trivial difference.

## Example 2

Passing around cancellation tokens is a necessary part of writing async code, but the ubiquitous parameters are just a form of visual clutter. I took some sample code from a [gist](https://gist.github.com/nfriedly/0240e862901474a9447a600e5795d500) on GitHub and refactored it to use an `ambient` block:

``` csharp
static void Transcribe()
{
    ambient (CancellationToken.None) 
    {
        var ws = new ClientWebSocket();
        ws.Options.Credentials = new NetworkCredential(username, password);
        ws.ConnectAsync(url).Wait();
        Task.WaitAll(ws.SendAsync(openingMessage, WebSocketMessageType.Text, true), HandleResults(ws));
        Task.WaitAll(SendAudio(ws), HandleResults(ws)); 
        ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "Close").Wait();
    }
}

static async Task SendAudio(ClientWebSocket ws)
{
    ambient (CancellationToken.None) 
    {    
        using (FileStream fs = File.OpenRead(file))
        {
            byte[] b = new byte[1024];
            while (fs.Read(b, 0, b.Length) > 0)
            {
                await ws.SendAsync(new ArraySegment<byte>(b), WebSocketMessageType.Binary, true);
            }
            await ws.SendAsync(closingMessage, WebSocketMessageType.Text, true);
        }
    }
}
```
I hope that it's clear that the all of the **async** method calls are using the same cancellation token. (But, see *Problem: Visibility*, below.)

We also gain in maintainability - if/when a future developer changes to use a different CancellationToken, the change only needs to happen in one place.  

# Implementation: How would it work?

The expression contained in the `ambient` block would be stored into a new local variable. This variable would be inserted into all eligible method calls within the scope.

Within an `ambient` block, compiler method resolution would prefer to call methods that used the available ambient value as the last parameter of the method.

In this example, we'd want the compiler to select the method `Equals(string, StringComparison)`  and not the simpler `Equals(string)`.

``` csharp
public string Name { get; }

public bool HasName(string name)
{
    ambient (StringComparison.OrdinalIgnoreCase)
    {
        return Name.Equals(name);
    }
}
```

The compiler would rewrite this code as follows:

``` csharp
public string Name { get; }

public bool HasName(string name)
{
    var comparison = StringComparison.OrdinalIgnoreCase;
    return Name.Equals(name, comparison);
}
```

Effectively, this is nothing more than syntactic sugar provided by the compiler. There are no required changes to libraries or the runtime.

## Question: Why only the last parameter?

In almost all of the sample scenarios I've explored, the common parameter that's shared across multiple methods is the last one. 

Applying this restriction gives (almost) all of the value of the feature while making it easier for a developer to understand and simplifying the implementation.

If an ambient value can be consumed by *any* of the parameters of method calls, the search for an appropriate method overload would become significantly harder, and potentially slower. It would also be much harder for a reader to discern which overload was going to be invoked.

Lifting the restriction in a later version of C# would be a breaking change as it would change which overload of a method was selected.

## Benefit: Avoiding static members

Currently, many projects choose to provide ambient information via static classes instead of passing the values as parameters. Classic examples of this include logging and transactions.

This is done to try and improve the readability of code by eliminating clutter but does so at the expense of tight coupling to the static members involved. 

The `ambient` block provides a way to avoid the tight coupling of static members while avoiding the clutter of explicitly passing the value into every method.

Problem: Potential for misuse

An `ambient()` could result in some very hard to read code if combined with common or widely used types such as `string` or `int`. For example,

``` csharp
ambient("foo bar baz")
{
    Console.WriteLine();
}
```

We could mitigate that by requiring the ambient type to have a particular attribute (say `[Ambient]`) or to implement a specific interface (`IAmbient`), but this would dramatically limit the usefulness of the feature. 

## Problem: Visibility

We're used to seeing method calls that contain all of the parameters being passed to the method - this change breaks that convention and this may be confusing to some developers. (Reducing the potential for surprise is one reason for the limitation of only providing the last parameter.)

The expression at the top of the `ambient` block makes it clear what value is provided, but it's not clear which methods consume the value. For this reason, the target scenarios are those where a common value (such as a transaction, logger or cancellation token) needed across multiple calls.

# Comparison with Scala

While discussing these ideas with colleagues and friends, I was introduced to Scala's [implicit parameters](https://docs.scala-lang.org/tour/implicit-parameters.html). There are a lot of parallels between these two features, but some key differences as well.

Both allow an ambient value from the context of the caller to be consumed by the method. 

However, Scala defines this as a part of the signature of the method, producing a *spooky action at a distance* that can catch developers by surprise. From what I've found online, this is particularly common when a method signature is revised to add an implicit parameter after the method is already widely consumed. 

The `ambient` block suggested here works in the opposite way - instead of the method *pulling* in implicit parameters all over the codebase, the ambient value is *pushed* into candidate methods specifically within a defined scope. This puts control into the hands of the developer and almost entirely eliminates the surprise factor.

**Comment by CyrusNajmabadi** [comment]
> I hope that it's clear that the all of the async method calls are using the same cancellation token. (But, see Problem: Visibility, below.)

I have an issue with this because it can make people *feel* like the right hting is happening, when in fact, it's absolutely not.  Take your example of cancellation tokens.  THere are many examples where the cancellation token is not last in the list.  i.e. 

```c#
        public Task<TResult> StartNew<TResult>(Func<TResult> function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler);
```

Someone could leave out the cancellation token, completely expecting it to be ambiently picked up.  Indeed, if this was in a group of other method calls, all of which did not have the cancellation token passed, it would be super easy to just assume this was doing the right thing, when in fact it was not.

**Comment by CyrusNajmabadi** [comment]
> The expression contained in the ambient block would be stored into a new local variable. This variable would be inserted into all eligible method calls within the scope.

This seems like a not great idea.  imagine now any call to string.format will always end up having these extra ambient values passed in.  After all, those ambient values will be accepted as a new valid 'last' parameter for those calls.

Similarly, this ambient value could change overload resolution in ways i definitely do not want.  For eample, if i had:

```c#
void Foo(int i) {}
void Foo(int i, object failureEvent) {}
```

Now, because of ambients in scope, the latter will be picked even if that wasn't my intent at all.

**Comment by CyrusNajmabadi** [comment]
> Lifting the restriction in a later version of C# would be a breaking change as it would change which overload of a method was selected.

Note: this proposal also leads to breaking changes when a 3rd party developer adds an overload to their API.  

For example, say i have:

```c#
ambient(someVal);
ThirdPartyApi.DoSomething(x, y, z);
```

in v1 of the ThirdPartApi that calls a method that jsut takes 3 parameters.  But in v2 that third party adds a new overload that takes 4 parameters.  Now, my code silently will call that new API, even though i never wanted that.

**Comment by DavidArno** [comment]
> I hope that it's clear that the all of the async method calls are using the same cancellation token

Unfortunately, I don't find it clear. I don't often use async calls, so I'm left looking at your code example wondering which of those constructors and methods actually use the ambient value.

When I look at your examples, what shouts out at me is the pointless use of `CultureInfo` in the `CultureInfo.InvariantCulture` example and `CancellationToken` in `CancellationToken.None`. Add a `static using` in both cases and they just become `InvariantCulture` and `None` respectively.

**Comment by ghord** [comment]
Note that you can already achieve something similar with `CallContext` in .NET

**Comment by bondsbw** [comment]
At best I would want _some_ indication that the ambient is intended, e.g.

```c#
ambient(CultureInfo.InvariantCulture)
{
    var parser = new Parser<ConnectionStatistics>();
    parser.AddProperty(
        nameof(ConnectionStatistics.TargetRate),
        rate => rate.TargetRate.ToString(**),
        (stats, rate) => stats.TargetRate = int.Parse(rate, **));

    ...
}
```

If you did it this way, it wouldn't even have to be the last parameter.

**Comment by vladd** [comment]
@bondsbw Perhaps `_` could be reused instead of `**`? It aligns quite well with meaning of "I don't care".

**Comment by svick** [comment]
@bondsbw At that point, how is that better than just using a local variable?

```c#
var ci = CultureInfo.InvariantCulture;

var parser = new Parser<ConnectionStatistics>();
parser.AddProperty(
    nameof(ConnectionStatistics.TargetRate),
    rate => rate.TargetRate.ToString(ci),
    (stats, rate) => stats.TargetRate = int.Parse(rate, ci));

...
```

If you're okay with using `**`, then you're presumably also okay with using a short name like `ci`.

**Comment by bondsbw** [comment]
@svick It isn't really, maybe marginally more  visible.

**Comment by theunrepentantgeek** [comment]
> There are many examples where the cancellation token is not last in the list

@CyrusNajmabadi I'm torn over whether ambient parameters should be restricted to the last parameter or injected wherever there is a type match. 

Allowing injection for any parameter value would cleanly handle this situation but at the cost of a greatly increased probability of surprise around which overload was selected by the compiler. There would also be costly in compilation time as overload selection would be much more complex.

> imagine now any call to string.format will always end up having these extra ambient values passed in

I hadn't considered **params** declarations, but it seems to me that ambient parameters shouldn't be pushed into methods like `string.Format()`.

> this proposal also leads to breaking changes when a 3rd party developer adds an overload to their API.

This is true - but we already have that risk when more specific overloads are added. For example when `void Foo(params string[] args)` exists and `void Foo(string)` is added.

**Comment by CyrusNajmabadi** [comment]
> This is true - but we already have that risk when more specific overloads are added. 

I disagree.  In the current world, when overloads are added, you're likely to preserve semantics.  i.e. "void Foo(string)" should behave the same as the original "Foo" with a singple parameter.  Now you're telling users, *any time you add a parameter at the end, someone may end up calling it implicitly, even if they didn't intend to".

**Comment by CyrusNajmabadi** [comment]
> Allowing injection for any parameter value would cleanly handle this situation but at the cost of a greatly increased probability of surprise around which overload was selected by the compiler. 

Indeed.  The only way i would support this would be with some syntactic denotation.  i.e. 

```c#
parser.AddProperty(
    nameof(ConnectionStatistics.TargetRate),
    rate => rate.TargetRate.ToString($$),
    (stats, rate) => stats.TargetRate = int.Parse(rate, $$));
```

Because now you're being clear of what's happening.

Of course, if you're going to do this, you might as well just say:

```c$
var $$ = CultureInfo.Invariant;
...
```

SO i don't see why this would buy anything.

**Comment by HaloFour** [comment]
In Scala a function must explicitly opt-in to implicit parameters and it must be applied across every parameter in the parameter list.  The only way to mix explicit parameters with implicit parameters is through function currying, itself just syntax candy for defining a function that returns another function, each being invoked separately.  This is what helps to avoid the mess of overload resolution, although it remains a mess of actually discerning what the heck is going on especially since implicits can be imported.

I'm far from an expert in Scala but my opinion is that implicits, despite their occasional benefit of brevity, only serve to make it impossible to reason anything about the code as you read it.  I also don't believe that they make any sense in C# in isolation from the various other features in Scala with which they must be used.

**Comment by bondsbw** [comment]
I'm with @HaloFour.  I'm also not a Scala expert but I went through a fairly advanced book utilizing Scala as the language of choice for its HKT support.

I typed in every single code example, understood all the concepts through the entire book, but for the life of me I still don't understand where those `implicit` parameters actually came from.
