### ISSUE TITLE
Proposal: Allow "this" as the constructor name

### ISSUE THREAD

**Issue by MV10** [dotnet/csharplang#1335]
Some languages use the `this` keyword as the name of the constructor. It seems sensible to me so I thought I'd float the suggestion. I suppose it also implies `~this` for finalizers.

```
public class Foo
{
    public this(string bar) { ... }
}
```

While building and maintaining DI-aware libraries, I often find myself cutting-and-pasting constructors and this change would save a (small) step having to rename the constructor to match the new class.

**Comment by HaloFour** [comment]
A `this` member already means something different in C#, defining an indexer.  I think it would be confusing to reuse it to also mean a constructor.

**Comment by MV10** [comment]
Ah, great point. Closing.

**Comment by jnm2** [comment]
> I often find myself cutting-and-pasting constructors and this change would save a (small) step having to rename the constructor to match the new class.

💡 What about copying and pasting only the constructor parameter list, and then using a code action to generate fields from the parameter list?

**Comment by TruePluto** [comment]
may be using ctor instead of this

```
public class Foo
{
        public ctor(string bar){....}
        public ctor(string bar, string bar2) :this(bar){...}
        public ctor():base(){...}
}

```

**Comment by CyrusNajmabadi** [comment]
Note: there is nothing actually syntactically wrong with allowing 'this' as the constructor name.  yes, it shares a prefix with indexers.  but they have very different code after the 'this' keyword.  'this' works well for me in both situations.  One explains how to construct a new 'this', and one explains how you could index as instance of 'this'.

**Comment by MV10** [comment]
@TruePluto I've had the same thought ... but they try to avoid adding new keywords. (That was explained to me once when I asked about the weird way that `using` has two wildly different meanings.)

@CyrusNajmabadi That's a good point. Indexers have a return-type, so without a type it could indicate the constructor.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi That's a good point. Indexers have a return-type, so without a type it could indicate the constructor.

Which is exactly the same grammatical difference between constructors and methods today :)   So it makes a bunch of sense.

**Comment by GeirGrusom** [comment]
`new`
