### ISSUE TITLE
Proposal: `is not` syntactic sugar

### ISSUE THREAD

**Issue by TheUnlocked** [dotnet/csharplang#1338]
I get that this is somewhat frivolous, but I think that
```cs
if (foo is not Bar){
     // Do something
}
```
is cleaner than
```cs
if (!(foo is Bar)){
     // Do something
}
```

I can't really think of any downsides to doing this, other than that it would take any amount development time for a relatively inconsequential syntax change. There are upsides however:
1. It's more English-like.
2. It doesn't require surrounding anything in parentheses, slightly reducing the amount of time you need to put into negating an `is` expression.
3. In larger boolean expressions, it may decrease parenthesis clutter.

An alternative to `is not` could be `is!` or `!is`, though those could be somewhat confusing.

**Comment by HaloFour** [comment]
Related to #882 and #568.  This particular syntax has been suggested in some comments.  However, I think that it would have to somehow work alongside pattern matching in order to fit with the `is` operator.

**Comment by MkazemAkhgary** [comment]
```c#
public class not {}

if(obj is not not)
```

>I can't really think of any downsides to doing this

 1- obj is not of type `not`

 2- obj is of type `not` and variable `not` is declared with pattern matching

**Comment by Unknown6656** [comment]
@MkazemAkhgary : In this case one would have to provide either an alias or the parent namespace name, e.g.:
```csharp
namespace kek
{
    public class not {}
    

    public static class Program
    {
        public static int main(string[] argv)
        {
            ...
            if(obj is not kek.not)
            ...
        }
    }
}
```

**Comment by lachbaer** [comment]
This came up already so often, but somehow I got the feeling that is the word __`not`__ that hinders the construct to make progress in its career :wink: . I'll throw in leaving the C-ish `!` char for the meaning of _not_:

```C#
if (foo is ! Bar) { ... }
```
(this acutally looks a bit spanish `¡s!` :grin: )

**Comment by Neme12** [comment]
I'd be for this if `not` is actually a pattern, so it would be possible to use `case not Bar` for example.

**Comment by MkazemAkhgary** [comment]
I don't think `not` is really helping here. it just gives vague meaning. `case not` is definitely vague, if there are 2 `case not` then which one should be chosen if given argument is neither of two cases? 

you cant have more than one `case not` and there is already `default` case for this purpose. 

english language is not a programming language.

**Comment by gafter** [comment]
Order is significant in a switch statement. The first matching case is taken. If none match then a default label, if present, is taken.

**Comment by Richiban** [comment]
Having `not` as a way of inverting a pattern could prove to be incredibly useful, especially in recursive situations. E.g. 

```csharp
switch(point)
{
    case Point2D(not 0, not 0): ...
    case not Point3D(_, _, _): ...
    default: ...
}
```

**Comment by Neme12** [comment]
@Richiban yes it would be useful especially in recursive patterns... but this of course begs the question: what if you want to match if the value is > 0? or any other comparison?

**Comment by Neme12** [comment]
but of course inverting a pattern is a much more general concept than inequality...

i'm just a little worried that in this particular case (of `Point(not 0, not 0)` it might not be so much useful after all/ it would have a very narrow use case because:
a) it would only work if you want inequality
b) you can't extract the value this way

that said, i would still prefer this as a general pattern rather than some syntactic sugar around `is` (in fact i don't think i want such a feature at all, this doesn't feel right to me to make another version of `is` just to have a nice word in there and make it read well in 1 specific case)

**Comment by deniszykov** [comment]
There is syntax for this:
```cs
if (foo is Bar == false) {
     // Do something
}
```

**Comment by Neme12** [comment]
:D how about 'foo is Bar is false'

**Comment by MkazemAkhgary** [comment]
how about

    dear computer, see if foo is bar, then do this.

yes, a little exaggeration, just to show you my feelings about `1-It's more English-like.`

**Comment by yaakov-h** [comment]
This is csharplang, not applescriptlang 😄

**Comment by TruePluto** [comment]
@MkazemAkhgary  How about using "isnot" instead of "is not"

```
public class not {}

if(obj isnot not)
```

**Comment by jnm2** [comment]
I like `is not`, not as much `isnot`, and I still like the informality of `isnt`. The potential standalone `not` pattern seems the most interesting though.

**Comment by gafter** [comment]
Added #1350 to champion this idea as a pattern form, along with some previous suggestions from @alrz.

**Comment by CyrusNajmabadi** [comment]
If it starts with i, it's an interface, and thus should be written ```ISnot```.  I.e. the set of functionality in things that are snot-like.

**Comment by gafter** [comment]
@CyrusNajmabadi Since @jnm2 likes informality, I think we should go with `aint`.

**Comment by jnm2** [comment]
@CyrusNajmabadi If my nose was running money...

**Comment by sharwell** [comment]
Duplicate of #27

**Comment by gafter** [comment]
Already championed as part of #1350

**Comment by AustinBryan** [comment]
Personally, I think this is much cleaner: 
```csharp
if (foo aint bar)
{

}
```

😜

**Comment by TheUnlocked** [comment]
Closing because this was championed a while ago.
