### ISSUE TITLE
Introduce exponentiation operator

### ISSUE THREAD

**Issue by adampooler** [dotnet/csharplang#1339]
Calculating exponents is ugly in c#:
`double y = Math.Pow(Math.Pow(2 * 2, 11), 27 / 9);`

Compare the same expression in Python:
`y = ((2 * 2)**11)**(27 / 9)`

As it's such a common operation what are your thoughts on supporting the same syntax in c#?

**Comment by ufcpp** [comment]
https://github.com/dotnet/roslyn/issues/4594
https://github.com/dotnet/csharplang/issues/175

**Comment by adampooler** [comment]
Apologies for the duplicate request
