### ISSUE TITLE
local function overload

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1352]
it would be nice to have local functions support overloading. eg:

```c#
double Sigmoid(double x) => 1d / (1d + Math.Pow(Math.E, -x));
double[] Sigmoid(double[] array) => array.Select(Sigmoid).ToArray();
```

---

edit: ambiguity exists but such scenarios would be similar to when using normal method overloads.

**Comment by bondsbw** [comment]
The usefulness doesn't seem to be worth the headaches of overload resolution it would cause.

**Comment by MkazemAkhgary** [comment]
right, I could definitely name the second one `Sigmoids`. I just thought it wouldn't be a big deal to add this feature, apparently it is. @bondsbw

**Comment by bondsbw** [comment]
FWIW I might even be ok with going back in time to remove method overloading.  Clarity of code is worth so much and overloading can lead to hard-to-find bugs.

**Comment by CyrusNajmabadi** [comment]
> FWIW I might even be ok with going back in time to remove method overloading. Clarity of code is worth so much and overloading can lead to hard-to-find bugs.

There's a reasonable argument to be made that the *majority* of complexity in the language *and* compiler is solely due to overloading.   I know if i worked on a new language, i would likely prohibit this as a feature just to free up oodles more time to work on other issues.

I've been using 'go' for several months and not only has the lack of overloads *not* been a problem, i actually think having the overloads be named so specifically has helped readability. 

Obviously, this can't change for C#/VB/.net.  But i'm def on the side of feeling like overloading is simply too much cost for what it brings you.

**Comment by orthoxerox** [comment]
@CyrusNajmabadi hear, hear! Every time I have to go to [this folder](https://github.com/dotnet/roslyn/tree/master/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution) to make one of my prototypes work I die a little inside. Conversions, overrides, visibility, params, optional arguments, it's such a mess.

**Comment by GSPP** [comment]
I found overloading to be a missing feature multiple times now. The most recent case is something like this:

```
string FormatTable(Table t) => string.Join("", t.Rows.Select(tr => FormatTableRow(tr)));
string FormatTableRow(TableRow tr) => ...
string FormatTableCell(TableCell tc) => ...
//... more ...
```

The code would be better and easier to write if the functions could all just be called `Format`. The idea is to simply write `Format(x)` and it just formats whatever it is you pass to it.

I have seen some discussion on why overloading was not allowed:

https://github.com/dotnet/roslyn/issues/2930:
> Scoping Rules
> Exactly same as for local variables (therefore no overloading)
> They may be declared only directly within a block

But that's not a discussion of the merits from a language users standpoint. I would certainly like to see overloading for local functions to make it into the language.

**Comment by jnm2** [comment]
With the union types proposal, a (less efficient) mitigation would be:

```cs
string Format(Table | TableRow | TableCell obj)
{
    switch (obj)
    {
        case Table t:
            return string.Join("", t.Rows.Select(tr => FormatTableRow(tr)));
        case TableRow tr:
            // ...
        case TableCell tc:
            // ...
    }
}
```
