### ISSUE TITLE
Allow implicit project references

### ISSUE THREAD

**Issue by yugabe** [dotnet/csharplang#1354]
I'm working on a DDD-like architecture and would like to wire up my application in an ASP.NET Core (2.1 Preview 1) project. In clean architecture it should be possible to abstract away implementation details ("Infrastructure" code). The ASP.NET Core project initiates the DI wireup in Startup.ConfigureServices(). There is an [official ASP.NET Architecture Guide e-book](https://www.microsoft.com/net/download/thank-you/aspnet-ebook) on the Microsoft site, which goes into more detail:
> Note: To wire up dependency injection in ConfigureServices in the Startup.cs file of the UI project, the project may need to reference the Infrastructure project. This dependency can be eliminated, most easily by using a custom DI container. For the purposes of this sample, the simplest approach is to allow the UI project to reference the Infrastructure project.

There is a [great post](https://ardalis.com/avoid-referencing-infrastructure-in-visual-studio-solutions) referenced by the book by Ardalis, who uses [StructureMap](http://structuremap.github.io/) to solve this issue. Unfortunately, using StructureMap still requires one to somehow move the appropriate assemblies to the entry point's /bin/ folder (which there could be more than one of, like test projects).

I've tried a few things with more or less success:
- If I add a direct reference to the Infrastructure project, all the types within are visible to the UI layer, which is unwanted (it's against clear SoC).
- If I add an additional project that references Core and Infrastructure (e.g. Infrastructure.Abstractions) and that initiates the concrete wireup of Infrastructure, even though there is no direct reference from the UI to Infrastructure, the concrete types are still visible in the UI (there is a transitive reference). I'm pretty sure this wasn't always the case, see [this SO post](https://stackoverflow.com/questions/42428571/transitive-references-in-net-core-1-1) for details.
- I tried loading the implementation assembly by hand using reflection and invoke the wireup indirectly this way, but this produced some unwanted side effects and feels very _hacky_. I needed to add a pre-build event that uses MSBuild to build the Infrastructure project and move the assembly output to be in the UI project's bin folder. This works, but it's very fragile. If as a post-build event in Infrastructure I copy the output over, the assembly obviously won't be copied because the Infrastructure project is not in the dependency tree for the UI project and it won't even build (unless I explicitly build it).
- The current workaround that works is if I add a custom MSBuild task to the relevant .csproj files (and use manual assembly loading and reflection to invoke the relevant wireup): 
``` XML
  <Target BeforeTargets="Build" Name="BuildInfrastructure">
    <MSBuild RebaseOutputs="true" Projects="../Infrastructure/Infrastructure.csproj" Targets="Build" Properties="OutputPath=../$(ProjectName)/$(OutputPath)" />
  </Target>
```

What I'd like to see is having an "implicit" project or assembly reference available. This would mean that I could add such a reference, but the types in that assembly would not be visible to the compiler unless explicitly stated.

For the above reasons, I propose the reuse of the _"using"_ keyword to let the compiler know that implicit referenced assembly types can be used in the context. This means that:
- A flag should be available to referenced assemblies and projects in the Properties window that allows one to hide the types declared in those assemblies unless explicitly stated in code. **Edit**: I realized this property already exists and is called _Reference Output Assembly_, but it [does not work](https://github.com/dotnet/project-system/issues/95). When set to false, the types declared will not be visible. Combined with Copy Local it seems the assembly would be copied to the right folder, but manual assembly loading would still be required, which is fragile.
- In C#, there should be a block that resolves the implicit reference types. Proposal below:

``` CSharp
public class Startup
{
    // Code omitted for brevity.

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        // To use the given implicitly referenced assembly, 
        // it's required to explicitly declare it in a using block. 
        // There should be IntelliSense inside the parentheses 
        // that list only the implicit references.
        using reference(InfrastructureAssembly)
        {
            // The Infrastructure.ConcreteService1 type in not visible 
            // outside an appropriate using reference() block.
            services.AddScoped<Core.IInfrastructureService1, Infrastructure.ConcreteService1>();
        }

        services.AddMvc();
    }
}
```

**Comment by Richiban** [comment]
@yugabe 

> If I add a direct reference to the Infrastructure project, all the types within are visible to the UI layer, which is unwanted (it's against clear SoC).

If it helps, my solution for this problem has been to make all types in the infrastructure layer internal. You must still add the explicit reference, but at least the incorrect layer doesn't get access to any types that it shouldn't. Your particular DI container should still be able to wire those types up (you might need to add an `InternalsVisibleTo` call to achieve this).

**Comment by yugabe** [comment]
@Richiban Thanks for the tip! I've tried that already, but couldn't get it to work with .NET Core's included container. The exception message was quite clear that I needed to provide a public constructor, and I'd rather stick with the out-of-the-box solution than a third party one. I haven't used ```InternalsVisibleTo``` yet, but it seems like a valid workaround, but a little fragile, I think (the dependent assembly should know of the assembly depending on it, and publish this knowledge).
In fact, I'm trying to achieve a little more than just "plain" clean architecture with an Infrastructure layer, but I think the scenario above is what should be the most common.

**Comment by bondsbw** [comment]
> If I add an additional project that references Core and Infrastructure (e.g. Infrastructure.Abstractions) and that initiates the concrete wireup of Infrastructure, even though there is no direct reference from the UI to Infrastructure, the concrete types are still visible in the UI (there is a transitive reference).

This doesn't seem right, transitive references means `A -> B -> C` implies `A -> C`, not `R <- Q -> S` implies `R -> S`.  (Right?)

**Comment by bondsbw** [comment]
BTW I am assuming you mean that Core == UI... if not then maybe I'm misinterpreting what you are trying to do.

**Comment by yugabe** [comment]
Maybe I wasn't clear above, but the structure is a classical Clean architecture or Onion architecture, where there are (in the simplest case) 3 projects:
- UI: the Web project that creates HTML and wraps them in HTTP responses
- Infrastructure: this contains specific business logic
- Core: this mainly contains the database entities, and database-independent business logic
In this DDD (Domain Driven Development) architecture dependency is inverted. Anything can (and usually should) reference the Core layer directly. This means that the UI (Web) layer references the Core, and Infrastructure also references core, but UI doesn't have a reference to Infrastructure.
So to answer your question: yes, ```UI -> Infrastructure -> Core``` does imply that UI sees the types defined in Core, even though there is no direct reference from UI to Core.

**Comment by bondsbw** [comment]
Ok, I understand now.  I might suggest this approach:

- `Infrastructure.Abstractions` contains shared interfaces, referenced by:
  - `Infrastructure` (implementations)
  - `UI`
- A new `Bootstrapper` layer references `Infrastructure` and `UI`
  - `Bootstrapper` loads `Infrastructure` classes into the DI container
  - `Bootstrapper` passes the container to `UI`

`Bootstrapper` is the entry point and has the responsibility of wiring everything up.  That responsibility is removed from `UI`.

**Comment by bondsbw** [comment]
Also, `Infrastructure.Abstractions` may just be part of `Core`... that's up to you.

**Comment by yugabe** [comment]
Yes, thank you for the suggestion, this seems the right approach, but this way the problem remains, as I either have to: 
- Reference the `Bootstrapper` library from the `UI` (ASP.NET Core applications have their own structured entry point, can't really remove that) and make visible all transiently referenced types, or
- Use magical assembly copying, loading and reflection (this is my current working workaround). The one you suggest seems better than what I was doing, because this way I'd only need to _magic-reference_ one assembly instead of one for every feature and business logic assembly.

I think the language and the compiler should be able to restrict usage of a certain assembly as I've shown above with something like `using reference(AssemblyName) { /**/ }`, because it provides type safety and robustness as cyclical dependencies still wouldn't be allowed, but the build and compilation would be safe as it is now, instead of relying on manually loading assemblies dynamically from user code.

The problem is a little more complicated than I outlined, but this seemed like the most general approach most users take when using dependency inversion to construct complex solutions. 

The current build and compilation pipeline doesn't seem to support dependency inversion along with separation of concerns (and the open/closed principle) because of this.

**Comment by bondsbw** [comment]
I don't know a whole lot about ASP.NET Core, but you would need to move `Main()` into the `Bootstrapper` assembly and ensure that is your entry point/startup assembly.

Your `Startup` class could still live in `UI`.  But the container would be setup in `Main()` instead of in `Startup.ConfigureServices()` as [shown here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup#convenience-methods).

**Comment by yugabe** [comment]
@bondsbw Thanks, at first glance, this seems to work like a charm! It seems so trivial now that the wireup should happen **above** the UI layer, not _in_ it. I'm going to close the issue now unless I run into any trouble regarding this. Also, my findings will be published in a blog post in the coming weeks, and if I don't forget, I'll add a link here for anyone interested.

If anyone from the team stumbles upon this, I still see added value in a language and compiler extension which allows using types in a given assembly in a managed scope as I demonstrated in the opening post, as that makes SoC cleaner and dependency inversion possible out-of-the-box. Obviously, assemblies are not a first class citizen (yet) in C#, so this might be a tough cookie to crack, but the current solution seems to work good enough for me.
