### ISSUE TITLE
Proposal: A simple for loop

### ISSUE THREAD

**Issue by gulshan** [dotnet/csharplang#1356]
This is a tiny feature request and does not actually solve any specific problem. When encountered `for` loops in C, I did not get that much resemblance between the name `for` and the looping mechanism it provides. In my mind, to bear the resemblance, for would look something simpler, like this-
```c
for(n)
{
    // This loop will run "for" "n" times
    // n can be short/int/long
}
```
So, hereby, I am requesting this feature in C#.

**Comment by orthoxerox** [comment]
How often do you need a loop that will run n times with no way to determine the current iteration?

**Comment by magol** [comment]
I agree that current C-inspired for-loop is not the best. It's clumsy to write and unnecessarily verbose. The reason it looks like it does is for flexibility. But in C#,  we can not take advantage of all the flexibility that C offers.

When you use for-loops, it is common to increase by 1. So in most cases,  it is unnecessary to write i++. 

I agree that there should be a shorter notation for counted loops, but the index variable must be included. We maybe can get inspection from other languages.

**Comment by Unknown6656** [comment]
@magol: With slices #185 one should be able to write this code here soon:
```csharp
foreach (var _ in 0..10)
{
    // ...
}
```
It is not super-compact, but I think that is OK. I do not think, that there is a real need for more optimization/compaction

**Comment by gulshan** [comment]
I already said, this does not solve any specific problem. May be new comers will be more comfortable to start with this simple for loop. That's all.

**Comment by magol** [comment]
@Unknown6656 ah, I had forgotten about that. Thanks for the reminder about slices/ranges :-)
It is not super compact, but it is easier to read and write then the for-syntax.

**Comment by bondsbw** [comment]
@Unknown6656 Honestly though that isn't strictly _better_ than

```c#
foreach (0..10)
{
    // ...
}
```

It might not hit the +100 point mark but I think it's worth considering.

**Comment by Unknown6656** [comment]
other thought -- relying on _"extension operators"_(#515) and copying C's implicit `int` to `bool` conversion:
```csharp
int count = 10;

while (--count)
{
    // ....
}
```
with the following operator somewhere defined in the background:
```csharp
internal static implicit operator bool (int v) => v != 0;
```

**Comment by bondsbw** [comment]
That makes me sad.

**Comment by Unknown6656** [comment]
@bondsbw I know ....... me too ......
But it is a brutal world out there ....
_I've heard there are even languages out there, where you do not define a variable's type, as it could be anything at runtime...... Or even worse: change it's type at runtime............_


--------
If you see signs of Javascript, Python or PHP - it is not yet too late.
We are here to help you.
#notice_the_signs

**Comment by mburbea** [comment]
I've personally always been a fan of this looping construct::
```cs
int count = 10;
while(count --> 0){
  // ...
}
```
The `-->` or goes to operator makes it so explicit.

**Comment by jnm2** [comment]
Why not scope the iteration variable?

```cs
for (var count = 10; count --> 0;)
{
  // ...
}
```

**Comment by lachbaer** [comment]
```C#
for (var i = 1 to 10 step 2) { ... }
```
just kidding... 🤣

**Comment by MkazemAkhgary** [comment]
This is my preferred one.

```c#
for (object boxedCounter = Activator.CreateInstance(Type.GetType("System.Decimal"), Activator.CreateInstance(Type.GetType("System.Int32")));
        (Type.GetType("System.Int32").GetRuntimeMethods().Where(m => m.Name.SequenceEqual("Equals")).ToArray()[0].Invoke(Type.GetType("System.Decimal").GetRuntimeMethods().Where(m => m.Name.SequenceEqual("CompareTo")).ToArray()[0].Invoke((decimal)boxedCounter,
        new object[] { Activator.CreateInstance(Type.GetType("System.Decimal"), Type.GetType("System.Int32").GetRuntimeMethods().Where(m => m.Name.SequenceEqual("Parse")).ToArray()[0].Invoke(null, new object[] { "10" })) }), new object[] {
            Type.GetType("System.Int32").GetRuntimeMethods().Where(m => m.Name.SequenceEqual("Parse")).ToArray()[0].Invoke(null, new object[] { "-1" })})).ToString().Cast<object>().SequenceEqual(new object[] { 'T', 'r', 'u', 'e'});
        boxedCounter = Type.GetType("System.Decimal").GetMethod("op_Addition").Invoke(null, new object[] { (decimal)boxedCounter, Activator.CreateInstance(Type.GetType("System.Decimal"), Type.GetType("System.Int32").GetRuntimeMethods().Where(m => m.Name.SequenceEqual("Parse")).ToArray()[0].Invoke(null, new object[] { "1" })) }))
{
    var i = (int)(decimal)boxedCounter;
}
```

**Comment by Nukepayload2** [comment]
What about this?
```c#
#pragma language using VB
For i = 0 To 10
#pragma language restore
    Console.WriteLine(i);
}
```

**Comment by AustinBryan** [comment]
```csharp
namespace MyNamespace
{
    public static void For<T>(int length, Func<T> body)
    {
        for (int i = 0; i < length; i++)
             body();
    }
}

...

using static MyNamespace.For;

public static Main() => For(10, () => 
{
    Console.WriteLine();
});
```
