### ISSUE TITLE
Proposal: Mandatory assigning property value when creating instance

### ISSUE THREAD

**Issue by stevenxi** [dotnet/csharplang#1362]
- When we have a class with multiple properties need to be assigned value when creating the instance, there're several ways.

1. Make properties a public set-able. But in this way, you don't get compile error or even warning if there's property that forgotten to be set.

```
    public class MyObject
    {
        public string PropertyA { get; set; }
        public string PropertyB { get; set; }
        public string PropertyC { get; set; }
        public string PropertyD { get; set; }
        public string PropertyE { get; set; }
    }

    var obj = new MyObject
            {
                PropertyA = "a",
                PropertyB = "b",
                PropertyC = "c",
                PropertyD = "d",
                PropertyE = "e"
            };
```
2. Assign values from constructor. This way is bit messy if there're too many property need to be initialized. Also, if properties' types are same, wrong order of parameters will cause compile error. 
```

    public class MyObject
    {
        public MyObject(string propertyA, string propertyB, string propertyC, string propertyD, string propertyE)
        {
            PropertyA = propertyA;
            PropertyB = propertyB;
            PropertyC = propertyC;
            PropertyD = propertyD;
            PropertyE = propertyE;
        }

        public string PropertyA { get; }
        public string PropertyB { get; }
        public string PropertyC { get; }
        public string PropertyD { get; }
        public string PropertyE { get; }
    }
            var obj = new MyObject("a", "b", "c", "d", "e");
```

Although you can do this
`var obj = new MyObject(propertyA: "a", propertyB: "b", propertyC: "c", propertyD: "d", propertyE: "e");`
But it's an optional, there's no way to force user to do so.

3. Or, use builder/factory pattern etc, is bit over complicated.

**- So it will be nice to combine the pos of first 2 options together.**

When the property defined as below, it allows to be set inside constructor or when creating the instance. 
Compiler should raise error if value not been set by neither places.

```
    public class MyObject
    {
        public string PropertyA { get; init set; }
        public string PropertyB { get; init set; }
        public string PropertyC { get; init set; }
        public string PropertyD { get; init set; }
        public string PropertyE { get; init set; }
    }

    var obj = new MyObject
            {
                PropertyA = "a",
                PropertyB = "b",
                PropertyC = "c",
                PropertyD = "d",
                PropertyE = "e"
            };

    var obj = new MyObject //Fail compiling as PropertyE isn't set.
            {
                PropertyA = "a",
                PropertyB = "b",
                PropertyC = "c",
                PropertyD = "d"
            };
```
Further, if allow combine the 'init' keyword with modifier, we can even have a public set-able property that must be assigned initial value when creating instance.

**Comment by HaloFour** [comment]
There's no facility in the CLR to require that any member is invoked after a class is instantiated.  There'd be no way to enforce this from any other language, or even from older C# languages.

If you want to require this behavior you can always write an analyzer and use attributes to denote what properties are "required".

**Comment by stevenxi** [comment]
I don't think it should be part of CLR, and I understand no any other language does this. 
But why can't we have it while no one else does it? :)

**Comment by svick** [comment]
@stevenxi You might want to read up on [Roslyn analyzers](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers). In short, they give you a way to produce custom compile time errors or warnings. And producing an error when your API is used incorrectly is one of their main use cases.

**Comment by Joe4evr** [comment]
It should be noted that the analyzers that are going to come with [Nullable Reference Types](https://github.com/dotnet/csharplang/issues/36) will warn you when a non-nullable field/property is not initialized on construction.

**Comment by Richiban** [comment]
@HaloFour 

> There's no facility in the CLR to require that any member is invoked after a class is instantiated

Sure, but it's easy to fake. The behaviour that we want is a constructor but it would be long and ugly to use. Why not have some way of having mandatory properties that actually just lowers to a constructor? Would be really damn nice for records as well:

```csharp
var x = new MyType 
{
    PropA = "a",
    PropB = "b",
    PropC = "c"
}
```

Which, if decompiled to an earlier version of C#, would come out as:

```csharp
var x = new MyType(PropA: "a", PropB: "b", PropC: "c");
```

**Comment by zippec** [comment]
Looks like records #39

**Comment by dsaf** [comment]
Dupe (IMHO): https://github.com/dotnet/csharplang/issues/322

**Comment by YairHalberstadt** [comment]
Closing as 'duplicate' of championed issue https://github.com/dotnet/csharplang/issues/3630
