### ISSUE TITLE
Proposal: LinQ to Regex

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1364]
# proposal:
Regular expressions are very powerful, but complex, so that I need to review its syntax every time I need to use them, besides it is hard to understand complex expression that appears in others codes.
So, I propose to use a LinQ-Like syntax with the keywork match to define Regex.

# Details:
At first, there should be some base class that all expression types derive from.  
This will allow us to define expressions outside the LinQ, so that they can be reusable.
Something like that:
```
var str1 = "…….";
RgxExpression Exp1 = Letter.Repeat(1, Lazy := true);  // \w+?
var results = match m in str1
                      let c = Digit.Repeat( )   // \d*
                      where m = Exp1 || c.Letter.c
                      select m;
```
Notes :
1- we can use
   `replace m with exp2`                    
instead of select m

2- || is an alternative to Or(exp) method. Also ! is an alternative to Not(Exp). 
3- The Repeat() Method has some overloads to represent +, * and {n, m}, with optional param. for laziness.
4- RgxExpression  calass should have some construcors to allow create an instance based on a regex string, or another RgxExpression instance or expression. This will help define repeated expression, and maje use ofregex language. RgxExpression.ToString() will return the regex string.  
5. Repeat, Letter, Not, Or, .... etc are extension methods to the RgxExpression Class. Each of them append ther expression to the caller expression and return a new expression.

In the same way, we can use LookAhead() and Lookbehond():
```
var results = match m in str1
                      let u = !Constant("u") 
                      where m = Constant("q").LookAhead(u)
                      select m

```
And Conditions:
```
var results = match m in str1
            let x = Constant("_") 
            where m = (Boundary || LookBehind(_))? Constant("A") : Constant("a")                          
            select m

```
Same for Atomic(Exp1) …. etc
I think every item of the regex language can be represented in similar way.
This is how I represent email regex for example:
```
var smalls = Range("a", "z");
var caps = Range("A","Z")
var L = Any(smalls, cap, Digit, ".", "_", "-")
var W1 = L.Repeat(1);
var W2 = L.Repeat(2, 4);
var email = Boundary.W1.Constant("@").W1.Constant(".").W2.Boundary;
string rgx = email.ToString();

```

# Benefits:
1-	readable understandable expressions.
2-	easy to use other local variables and other linQ and lambdas to do whatever programmer wants.
3-	Strongly typed with intelligence auto-complete means zero syntax errors.

I hope you like the idea and participate to complete mapping other regex parts.

**Comment by CyrusNajmabadi** [comment]
```c#
var smalls = Range("a", "z");
var caps = Range("A","Z")
var L = Any(smalls, cap, Digit, ".", "_", "-")
var W1 = L.Repeat(1);
var W2 = L.Repeat(2, 4);
var email = Boundary.W1.Constant("@").W1.Constant(".").W2.Boundary;
string rgx = email.ToString();
```

I don't see what the C# language has to do with this.  You're just describing a way to expose an API for doing regular expression matching.  That can be done today already with the language as-is.

**Comment by MohammadHamdyGhanem** [comment]
Hope it is clear now. The RgxExpression can be like this:
```
class RgxExpression 
{
   public string Expression {get; set;}
      
}
```

The extenstion methods should be like this:

```
RgxExpression Foo (this RgxExpression exp)
{
  RgxExpression exp1 = ........;
    return Merge(exp.Expression, exp1);
}

```

**Comment by khellang** [comment]
The proposal *looks* a lot like https://github.com/sprache/Sprache, but sounds a lot like https://github.com/VerbalExpressions/CSharpVerbalExpressions. Anyway, it's already implemented with the current language features.

**Comment by MohammadHamdyGhanem** [comment]
@khellang

> The proposal looks a lot like https://github.com/sprache/Sprache, but sounds a lot like https://github.com/VerbalExpressions/CSharpVerbalExpressions. Anyway, it's already implemented with the current language features.

Thanks. yes they are similar, but without the Linq part.

**Comment by CyrusNajmabadi** [comment]
> The problem is that there is more than 100,000 NuGets 

That's a good thing.  :)  

> and it's nearly imposible to explore them all!  .Net should imprace such goode Nugts as a part of the language,

You haven't specified what actual language changes you want here.  Pretty much everything you've discussed is unrelated to the C# language.

> or at least refere to important Nugets related to .NET tpoics in its Docs.

This is feedback for the .net teams :)  Not for csharplang :)   csharplang is the repo dedicated to just hte C# language (i.e. the actual language specification).  It is where proposals to *change* the language are made, and where the C# team works on new language features.  

If you have a request for a new API, then that should go to something like CoreFx.  But you will need to follow their rules for proposals.

**Comment by CyrusNajmabadi** [comment]
> I should psot this priposal as well in the CoreFx.

Can you explain what actual change to the C# language you are proposing? What change are you looking for *actual specification* for C#?  Thanks! :)

**Comment by CyrusNajmabadi** [comment]
> You say I can do it myself. I can't build LinQ Expression now,

Why not?

> and suppose I did how can this be a part of the languae?

What do you mean "part of the language"?

Linq-to-sql was done, and it needed no language changes once Linq was originally added.  Same with "linq to xml" or "linq to objects" or "linq to twitter" or "linq to excel" or "linq to ..."

So why does "linq to regex" require any language changes?  And if it doesn't require any language changes, then why do you need this issue opened here? :)

**Comment by MohammadHamdyGhanem** [comment]
Can't use from. The regular expression will be constructed and passed to Regex class. This is differnet than working with Inumerable collections. If I use From, then how should I know the difference?

**Comment by CyrusNajmabadi** [comment]
>If I use From, then how should I know the difference?

The same way that linq-to-sql knows the difference, as does linq-to-xml and the rest :)   

> This is differnet than working with Inumerable collections.

linq has no concept of "ienumerable collections".  What you are describing is "linq to objects" which is a library that C# has no special knowledge of.  Linq to objects operates over collections.  Your own linq library can operate on whatever it wants (like linq-to-sql operates over tables and the like).  

I recommend you go read up on how to create your own linq provider :)

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem This may be informative:   [Walkthrough: Creating an IQueryable LINQ Provider](https://msdn.microsoft.com/en-us/library/bb546158.aspx)

**Comment by theunrepentantgeek** [comment]
@MohammadHamdyGhanem Here's an excellent presentation from TechEd New Zealand 2010 where Ivan Towlson shows how LINQ really works - there really is no magic, just a whole lot of really clever design.

https://channel9.msdn.com/Events/TechEd/NewZealand/2010/DEV401

Unfortunately, the resolution of the video is just a touch low, so some of the code is a *little* difficult to read.

Disclaimer: Ivan is a friend and a colleague.

**Comment by MgSam** [comment]
Regular expressions have been around in some form or another for almost [70 years](https://en.wikipedia.org/wiki/Regular_expression). If you find them confusing, I suggest spending more time practicing with them, rather than trying to reinvent the wheel. They are one of the few constructs where the syntax and semantics are closely shared among most major programming languages and learning them well will help you, no matter what language you write.

**Comment by khellang** [comment]
> This project has been forked 96 times!

I don't think the number of forks means what you think it means.

It's standard practice to fork a project, just to commit some changes and send a pull request upstream, then just forget about the fork.
For instance, I have 159 forked repositories under my profile. I have no intention, whatsoever, to maintain any of those forks on a permanent basis 😝 

If you want to get an indication of which forks have the most recent changes, you can take a look at https://github.com/VerbalExpressions/CSharpVerbalExpressions/network.

**Comment by MohammadHamdyGhanem** [comment]
@khellang 
I see, but the repository is idle for years, and there are some issues and pull requests with no resopnse. Some forks have been reforked. It's hard to imagin that some basic operrations are still missing after 5 years despite all these forks! I am afraid to miss some good work and start over in a new fork.

**Comment by MohammadHamdyGhanem** [comment]
I sent some notes and suggestions and hope to hear from them. Maybe some features are there but I am not aware of, accordingly I can decide what to do next.

**Comment by CyrusNajmabadi** [comment]
Can you close this out in the meantime? It sounds like tehre's a workable solution for you.  A library that gets you at lest most of the way there.  And you can fill in any gaps if you want.

Regardless, this isn't a csharplang issue.  There is no actual change to the language necessary here.

**Comment by MohammadHamdyGhanem** [comment]
@khellang @HaloFour @theunrepentantgeek 
Here is Verex (my verbal regex builder):
https://github.com/MohammadHamdyGhanem/Verex
Thanks

**Comment by scalablecory** [comment]
You may want to take a look at [Xpressive](https://www.boost.org/doc/libs/1_67_0/doc/html/xpressive.html) and [Spirit](https://www.boost.org/doc/libs/1_67_0/libs/spirit/doc/html/index.html) for inspiration.

**Comment by MohammadHamdyGhanem** [comment]
@scalablecory 
Thanks, but I like using verbal API because it is easy to write and read, even it is longer.
