### ISSUE TITLE
Generalize ? operator on struct

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#1365]
In the same manner of other keyword like `foreach` that does not work on specific type but instead being a syntactic sugar on member directly. I think we could relax the `?` operator to work on any struct that contains `HasValue` and `Value` member

```C#
public struct Rational
{
    public int Number,Fract;
    public float Value => Number / (float)Fract;
    public bool HasValue => Number != 0 && Fract != 0;
}

var r = new Rational(0,0);
var x = r?.ToString(); // r? act like float? and return null when NaN or infinity

```

```C#
public struct LazyInit<T> where T : class
{
    public bool HasValue => true; // Lazy will always try to create value
    public T Value 
    {
        if(value == null)
           value = getter();

        return value;
    }

    T value;
    readonly Func<T> getter;
    public LazyInit(Func<T> func) => getter = func;
}

var lazyList = new LazyInit<List<int>>(() => new List<int>());
lazyList?.Add(3); // lazyList? let we access member of List directly
lazyList?.Add(4);
lazyList?.Add(5);
var product = lazyList?.Aggregate((seed,item) => seed * item); // Also extension method
```

**Comment by Thaina** [comment]
@ufcpp Thanks, This feature is too old, I forgot about it and forgot the keyword to find it

**Comment by jnm2** [comment]
I'm amused that your rational type does not consider zero to be a value. Technically the only time your struct does not have a rational value is when the denominator is zero.

**Comment by Thaina** [comment]
@jnm2 Just little wrong logic man

**Comment by HaloFour** [comment]
> Just little wrong logic man

Little Wrong Logic Man is the worst superhero.

**Comment by jnm2** [comment]
Lol, it only sticks if it's true. 😜

@Thaina https://en.wikipedia.org/wiki/Rational_number
