### ISSUE TITLE
Yet another params proposal: params IReadOnlyList<T>

### ISSUE THREAD

**Issue by alfredmyers** [dotnet/csharplang#1366]
There are several proposals for allowing params to be used with types other than T[]: #178, #179, etc.

This proposal is specifically for `IReadOnlyList<T>` since [T[] implicitly implements both `IList<T>` and `    IReadOnlyList<T>`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs#L26)

So given a method

```
public int Sum(params IReadOnlyList<int> values) {
   return values.Sum();
}
```

Both the following call sites would be valid:

```
var sum1 = Sum(1, 2, 3);
var sum2 = Sum(GetIntArrayOrListOfIntFromElseWhere());
```

**Comment by alrz** [comment]
the full list of generic array interfaces is as follow,
```
IList<T>
ICollection<T>
IEnumerable<T>
IReadOnlyList<T>
IReadOnlyCollection<T>
```
I think we should support all these as part of https://github.com/dotnet/csharplang/issues/179

we could also add `params Span<T>` (https://github.com/dotnet/csharplang/issues/535). The only question is that how the overload resolution should behave, e.g.
```cs
void M(params int[] p)
void M(params IList<int> p)
void M(params ICollection<int> p)
void M(params IEnumerable<int> p)
void M(params IReadOnlyList<int> p)
void M(params IReadOnlyCollection<int> p)
void M(params Span<int> p)

M(1); // which method should be called?
```

**Comment by alfredmyers** [comment]
Other interfaces already are subject of other proposals.
I'm trying to focus this proposal on `IReadOnlyList<T>` (and maybe `IList<T>`?) as both .NET Core and .NET Framework already make T[] implement them.

**Comment by jnm2** [comment]
@alfredmyers Unless you are proposing that we do something contrary to what #179 proposes, what's the point of starting a new discussion?

**Comment by portal-chan** [comment]
```csharp
void M(params int[] p)
void M(params IList<int> p)
void M(params ICollection<int> p)
void M(params IEnumerable<int> p)
void M(params IReadOnlyList<int> p)
void M(params IReadOnlyCollection<int> p)
void M(params Span<int> p)

M(1); // which method should be called?
```

If all these `params` types we're added, I'd say that only one of all the `int` collection overloads should be allowed to be specified as `params`.

**Comment by jnm2** [comment]
> If all these params types we're added, I'd say that only one of all the int collection overloads should be allowed to be specified as params.

I like it, except that removing `params int[]`  would be a breaking API change and prevent C#7 and lower compilers from being able to use any params overload. So as long as people care about compatibility or `params` working on older compilers, that would effectively keep people from using `params` on anything but arrays.

**Comment by bondsbw** [comment]
@portal-chan Then we have to figure out how this is handled:
```c#
interface IA
{
    void M(params ICollection<int> p);
}
interface IB
{
    void M(params IReadOnlyCollection<int> p);
}
class C : IA, IB
{
    // Must implement both
    public void M(params ICollection<int> p) {}
    public void M(params IReadOnlyCollection<int> p) {}
}
```

**Comment by svick** [comment]
@bondsbw I don't think that particular case would be an issue. While you can specify `params` on an interface method, that doesn't mean the implementation has to be `params` too. For example, the following code [compiles fine today](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4wHbGnAhgYwgAgEkBBAWACgBvC/W/AAQBZ8BZACgAcsosBbAZ3xpgAbQC6+DgEoA3BQC+FegCZ8AYXwgiZKjTr0AzA2bth4yVPyVF5eUA==):

```c#
interface IA
{
    void M(params int[] p);
}
class C : IA
{
    public void M(int[] p) {}
}
```

**Comment by bondsbw** [comment]
@svick TIL

**Comment by jnm2** [comment]
Default values don't have to match, either.

**Comment by alrz** [comment]
I think we can permit such overloads as long as we have a preference. 

For example, we could resolve `M(42)` to the second method to enable overloading a params parameter with a params Span<int> without breaking existing code:
```cs
void M(params int[] p)
void M(params Span<int> p)
```
and choose the first one below for `M(42)` based on the most specific type i.e. `int`:
```cs

void M(params IEnumerable<int> p)
void M(params IReadOnlyList<long> p)
```

But give declaration-site errors for these:
```cs
void M(params int[] p)
void M(params IEnumerable<int> p)
```
