### ISSUE TITLE
Inferred member name issue

### ISSUE THREAD

**Issue by dogo-sefacan** [dotnet/csharplang#1367]
Hi team,

![2018-03-09_13h33_37](https://user-images.githubusercontent.com/37143156/37203361-77b48a0c-239e-11e8-9c11-656d3f9210c0.png)

I need to fix it, but it will not be a legible code. Because the other member names remain different.

![2018-03-09_13h41_28](https://user-images.githubusercontent.com/37143156/37203679-90ae1c02-239f-11e8-8dc3-63ef9c3ec7b5.png)

**Comment by CyrusNajmabadi** [comment]
@dogo-sefacan The appropriate repo for this issue is: https://github.com/dotnet/csharplang

You can disable this analyzer if you want by changing this setting:

![image](https://user-images.githubusercontent.com/4564579/37204294-2d2515f0-2345-11e8-82d5-b76444b6d87f.png)

**Comment by Logerfo** [comment]
@CyrusNajmabadi this is dotnet/csharplang

**Comment by Unknown6656** [comment]
@CyrusNajmabadi : I think you have to sleep more :wink:

**Comment by jnm2** [comment]
![image](https://user-images.githubusercontent.com/8040367/37212806-1d38ddb4-237e-11e8-9d3a-7b32026dc59b.png)

Wat

**Comment by jnm2** [comment]
Yay https://github.com/dotnet/roslyn/issues/24805

**Comment by CyrusNajmabadi** [comment]
> I think you have to sleep more

Yeah. i should not have been commenting at 3am for me.  :)   Regardless, please move this to dotnet/roslyn

**Comment by alrz** [comment]
I don't see how this isn't legal. inferred and explicit names are permitted in a single init.

**Comment by CyrusNajmabadi** [comment]
I think he's saying it's not *legible*  (not that it's not "legal").  I think the complaint is that it's unpleasant for him to have the analyzer create code that mixes/matches these styles.

**Comment by dogo-sefacan** [comment]
@CyrusNajmabadi I definitely wanted to say that.
