### ISSUE TITLE
Proposal: Allow optional property initialization with fallback to the default value

### ISSUE THREAD

**Issue by nrhoffmann** [dotnet/csharplang#1369]
### Proposal
Can we get this syntax `[Property Name] ?= [Some Value]`, when using the object initializer, to only override a property's default value if `[Some Value]` is not `null` or `default`?

### Example / Explanation
Currently, you can do this...
```c#
public class Connection
{
  public string Name { get; set; }
  public string Server { get; set; } = "127.0.0.1";
  public int Port { get; set; } = 80;
}
```

This is really nice, because it allows you to initialize a property with a default value. For example...
```c#

 var localhost = new Connection
 {
   Name = "localhost"   
 };

connections[localhost.Name] = localhost;
```

Suppose, that while refactoring my code I notice that I frequently make connections and add them to some dictionary that maps their name to themselves. To clean things up a bit I might do the following...
```c#
public Connection MapNewConnection(string name, string server = default, int port = default)
{
  var connection = new Connection
  {
    Name = name,
    Server = server,
    Port = port 
  };
  connections[connection.Name] = connection;
  return connection;
}
```

However, now I've lost the defaults set in `Connection`...
```c#
Console.WriteLine(MapNewConnection("localhost"));
// Connection { Name = localhost, Server = null, Port = 0 }
Console.WriteLine(MapNewConnection("google", "172.217.10.46"));
// Connection { Name = localhost, Server = "172.217.10.46", Port = 0 }
```

I am proposing the using the following syntax to solve this issue...
```c#
public Connection MapNewConnection(string name, string server = default, int port = default)
{
  var connection = new Connection
  {
    Name = name,
    Server ?= server,
    Port ?= port 
  };
  connections[connection.Name] = connection;
  return connection;
}
```

**Comment by vladd** [comment]
Why not just use `Server = server ?? default`?

**Comment by jnm2** [comment]
I like `??=` because it follows the existing patterns we have for converting an operator to an assignment shorthand operator, but `??` has always been about `null` and not `default`. Both of these things have been covered in previous issues.

**Comment by nrhoffmann** [comment]
@jnm2
Are they planning on making #34 work in object initializers?

**Comment by ghost-abc** [comment]
@nrhoffmann hi!

Currently you may try to use extended `with`-pattern.

[Compiled online sample for your code](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGMD2BbADgSwBsIEAaGEBOAOwB8ABABgAJ6BGAbgFgAoJ1tgBZuPXvQDMAgGysATMwAyAUV4BvXs02tJ7GQBVmezAB49APgAUMABb5kh5plKO4MBwA8AlMwC8Z5u6+jiJa2tIOAOr4NqaWNnYOTsy4UAhQ2PaYwABWEOgwANoAusmwMCTU3n7BvAC+vGI68gDCzOo8oRLh9IICABwWnhpa7aGdbACcFgCyULgAchAA7s2Y1NR5MPhrFgBEhJjoUITWmMgwu56eIWOa7FOzC8ur65vb1HsA5piYn8S7zl2bAA7LIAHSyEFgtiMMGCKSXa7DW73GZzRYrNYbfLvL4/P4QAHMIGgiFQmFwhHONiyPpXG6aeodLTIsL0FpYt5rVmjW5smHMebpCBtZifCAwDjMZASqVMvn8lgAZRIADcSKLxZLpbLmLUgkDZMCwbDYWxdgyxl18NQ3AAFTAINyqMW6mXa/U+Zh9RgiVmdSSYdUIBD4AAmIvYLCMSpgoeon0Gvn8ABJdqohdgIPrVCqEMHaiBVA6nbULaz5SzmXc2DIACL4HFrVIAT2MUecL2xWzW/iwryb1HsXo2S2YDcHrfbMM7nMHliR1eYrK6umYXa51GYjwxG8HbAsUeY1GFziPMvzGq9EbAUDghBgzhtblwjrc14gt/vMCGS95t1Hdc5x7D5PDBIwLEwVxmFVVJmHQMCohsCx/T5dAwUzEUR1PVDbnQvNgyCC9CIAfhI+CwQIkhSFwsZ0JLd9kjfXwPy/B9mHI+jmJAJinWXJdQkXBV+27d5kAKdDMJKL10EtTpgXgy1K00FcdFrICBxA7d0WeYDcSPE8szPAViKvZgbzvB8n1tXjGIs78qjMWiRM3cTDIgaTj2WDTRJ2MCIKgtxYIQeDEOiawUIEtCMOFIJ3JoqK8MotUzNMkKyIoqiyFo0IuL4r1X3y1jLLcTiwQY5geMKtxaMXWogA==)
```c#
    public Connection MapNewConnection(string name, string server = default, int port = default)
    {
        new Connection().To(out var c).With(
            c.Name = name,
            c.Server = server ?? c.Server,
            c.Port = port == default ? c.Port : port 
        );
        connections[c.Name] = c;
        return c;
    }
```
Moreover your method may be rewritten as bodied like
```c#
public Connection MapNewConnection(string name, string server = default, int port = default) =>
    connections[name] = new Connection().To(out var c).With(
        c.Name = name,
        c.Server = server ?? c.Server,
        c.Port = port == default ? c.Port : port 
    );
```
A base implementation of this pattern
```c#
    public static T To<T>(this T o, out T x) => x = o;
    public static T With<T>(this T o, params object[] pattern) => o;
```
[Detailed and an optimized implementation here](https://github.com/Makeloft/Ace/issues/2)

**Comment by jnm2** [comment]
This time he's gone to the trouble of deleting his account for you, so all that's left is deleting the spam.

**Comment by YairHalberstadt** [comment]
`??=` has now shipped, but is not supported in object initializers. If this still interests you, I would suggest opening a new issue allowing it in object initializers.
