### ISSUE TITLE
Dynamic Generic Types as Method<T...>

### ISSUE THREAD

**Issue by sgf** [dotnet/csharplang#1372]
how about add this new Feature(syntax) like:

```
public List<T..> ExeSql<T..>(string sql,params object[] objs)
{
var len=length(T..);
typeof(T..[0])
typeof(T..[1])
typeof(T..[2])
...
..
..
//or maybe use foreach
foreach(typeof(T) t in T..)
{
      t....
}


}
```
to instead of 
```
public List<T1> ExeSql <T1> (string sql,params object[] objs)
public List<T1,T2> ExeSql<T1,T2>(string sql,params object[] objs)
public List<T1,T2,T3> ExeSql<T1,T2,T3>(string sql,params object[] objs)
<T1,T2,T3,T4>...
<T1,T2,T3,T4,T5>...
T6...
...
...
..
```

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/5058, which was closed with this message:

> I am not moving this particular issue [from dotnet/roslyn to dotnet/csharplang] because I don't have confidence that the LDM would likely consider doing this as proposed. I think we might consider doing something along these lines along with higher-kinded types if we do that; see dotnet/csharplang#339.

**Comment by bondsbw** [comment]
What is `List<T1,T2>` and `List<T1,T2,T3>`?

Where would this be useful?

**Comment by svick** [comment]
@bondsbw I think it's effectively `List<(T1, T2, T3)>`. So, if you want to return a table with a person's name and age, you would have something like `ExeSql<string, int>("select name, age from people")`.

**Comment by bondsbw** [comment]
```c#
var items = ExeSql<(string, int)>("select name, age from people");
(string name, int age) = items[0];
```

Since that is legal today, I'm not seeing anything very useful in this proposal.

**Comment by sgf** [comment]
where if u want to design a API to return multi Result Types
such call like:

 List<Account,User,UserInfo,UserSetting,.....{or more types result}> ExeSql<Account,User,UserInfo,UserSetting,.....{or more types result}>(.....)

u should be define lots of **overload** Methods.
but if we can just define once times.thats will be Write less code,yes,we just need write once in One Method.

**Comment by sgf** [comment]
@bondsbw
sorry my project is very old if we can define like ur submit(use new Tuple syntax ),i will close this issues

**Comment by sgf** [comment]
@bondsbw
these codes could be Compiled 
```

        public class TestClass {

        }

        public List<T> TestMethod<T>(){


            return new List<T>();
        } 

            Test<(string, int, TestClass)>();
```
but how can i get the Types from T with argument of Tuple in TestMethod ?

**Comment by sgf** [comment]
i found it GetGenericArguments. @bondsbw thank u,and thanks to all.

       ```
public class TestClass
        {

        }
        public static List<T> Test<T>()
        {
            var types = typeof(T).GetGenericArguments().ToList();
            types.ForEach(t => Console.WriteLine(t.Name));
            return new List<T>();
        }
        static void Main(string[] args)
        {
            Test<(string, int, TestClass)>();
            Console.ReadKey();
        }
```
