### ISSUE TITLE
when clould be C# support direct get  multi returns from Method Calling?

### ISSUE THREAD

**Issue by sgf** [dotnet/csharplang#1377]
In fact, go language and lua are supported.

Now used by tuple:
```
var xyz=funTest(a,b,c);
if(xyz.Item1==0)
{
   //do some thing
}
```

hope :
```
if(var x,y,z=funTest(a,b,c);x==0) {
   //do some thing
}


//or if do not need y,z

if(var x=funTest(a,b,c);x==0) {
   //do some thing
}
```

**Comment by HaloFour** [comment]
#973

**Comment by gafter** [comment]
You can do this today:

`if (((x, y, z) = funcTest(a, b, c)).x == 0) {`

if you predeclare `x` `y` and `z`.

#973 would permit you to write

`if ((var (x, y, z) = funcTest(a, b, c)).x == 0) {`

**Comment by gafter** [comment]
If you don't mind being a bit hacky, you will be able to use pattern-matching in C# 8 to write

`if (funcTest(a, b, c) is var (x, y, z) && x == 0) {`

**Comment by gafter** [comment]
Or even

`if (funcTest(a, b, c) is (0, var y, var z)) {`

**Comment by sgf** [comment]
@gafter 
im use
```
      if (((x, y) = funcTest()).x == 0)
            {

            }
```
but i get errors:
Error	CS0103	The name 'x' does not exist in the current context	ConsoleApp1	
Error	CS0103	The name 'y' does not exist in the current context	ConsoleApp1

**Comment by sgf** [comment]
@gafter 
ok,i got ur msg:

> if you predeclare x y and z.
i haven't predeclare.
but i hope do not predeclare ,than i can use more easyly style.

**Comment by sgf** [comment]
> if ((var (x, y, z) = funcTest(a, b, c)).x == 0) {

if could be remove the more "(" ")",thats will better.

like:

if(var x,y,z= funcTest(a, b, c);z==0){


because this line couold be split two part:
```
var x,y,z=funcTest(a, b, c);
//and
if(z==0){
```

the context is more clean

**Comment by ghost-acb** [comment]
@sgf hi!

> var xyz=funTest(a,b,c);
> if(xyz.Item1==0)
> {
>    //do some thing
> }

Also currently there is a little unusual alternative way
```c#
if (funTest(a,b,c).To(out var t).Item1 == 0)
{
    Console.WriteLine(t.Item2);
   //do some thing
}
```
See [a following online sample](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMBuAWAChiB6AKkwBkBDKAcwhvoFNMWAPYFqAZwEsA9n0zlSxXADZsAJmoBRYgG9imNdgDM2HNIAqmAOr9gACwA8ugHwAKU/16Z9gmJgAONMDQC2DwQCMAKxYAY2AAbQBdNxpgbjAoAEpMAF5LTEFCInVNbT1HQQsbOwcnF0EIYEdMDiTU6pT0vGziAF9iCTkAYWVVdSlHCFcAGxYzfihgF3HJzGm0gDNoXRZeYGtpzBopicw/bcrg2ste7LVdQZGAOk6wFhiWay3dl0PMk9zsABZtAA5rBPeKiypzU/HmmGsiygy1W1nQLhkLg0CUuukE1nKlQAbh5MMAUQBJbheHApZKYdAA4EgoEgkG4ACctkuRJYXhkCUydNOjOZrK8yK53PU725wEuRlM1lFwrU4v5OFR6MxmBxYGqCRgMtl8uJMiVGIqqtxAE9Ndrhbq2RoDSq1ZgAF5U2VqTkW5rU4W8gAkACIABrJJQcFqYACaQZNoYAWkGHS1fW7Pdk2p7U6nskA=)
```c#
using System;

/* Language extensions */
static class LE
{
    public static T With<T>(this T o, params object[] pattern) => o;
    public static T To<T>(this T o, out T x) => x = o;    
}

class C
{
    static Tuple<int, int, int> funTest(int a, int b, int c) =>
        Tuple.Create(a, b, c);

    static void Main()
    {
        if (funTest(0, 2, 3).To(out var t).Item1 == 0)
        {
            Console.WriteLine(t.Item2);
            Console.WriteLine(t.Item3);
            
            t.With(
                t.Item1.To(out var x),
                t.Item2.To(out var y),
                t.Item3.To(out var z)
            );
            
            Console.WriteLine($"X={x} Y={y} Z={z}");
        }
    }
}
```
More details and optimized implementation [here](https://github.com/Makeloft/Ace/issues/2).

**Comment by yaakov-h** [comment]
@terrajobst *sigh*

**Comment by CyrusNajmabadi** [comment]
@terrajobst Can you contact github about this?  The continued creation and deletion of accounts just to behave in this manner has to be a violation of some of their terms.

**Comment by jaredpar** [comment]
@CyrusNajmabadi we've contacted github about this several times. The result is what you see here.

**Comment by ghost-aab** [comment]
Guys, are you really think that my comments are spam and `to-with` pattern is useless thing or bad practice?

Of course, I understand that the most of you already know about it, but my comments shows fresh scenarios of usage or addressed for new people who ask related questions. 

You may just ignore new posts or even dislike, but you constantly try to lock me. It looks very-very strange, no technical details, only emotional reactions.

I don't force someone to use this, but give alternatively choice, because I know that there are another people from community who like it and already have use in practice. Yes, it is true.


If you want to critic technical details welcome to [this thread](https://github.com/Makeloft/Ace/issues/2).

To avoid off topic emotions feel free to express them [here too](https://github.com/Makeloft/Ace/issues/5).

**Comment by sgf** [comment]
@CyrusNajmabadi 
ppl create issues,Not because of emotion or complaining.
Like this question, I am not sure that anyone has ever created some issues like it.
if i know,i wont create it.
in fact,we are not like u soak in GitHub every day and be clear about the details of a project.


But a good programming language, should not let go of every one to make it's grammar become Straightforward details.

Since Gafter raised a similar question, I think I can close the issues.

**Comment by CyrusNajmabadi** [comment]
@sgf My post was not in response to you, but to the continued poor behavior by:

![image](https://user-images.githubusercontent.com/4564579/37439812-1b21319c-27b7-11e8-964f-9752f5b41cf3.png)

Your issue is great, and i hope you continue participating here! :)

**Comment by sgf** [comment]
@CyrusNajmabadi 
aha,its' ok 😂.
I'm sorry to have misunderstood you,m8.
