### ISSUE TITLE
Allow destructuring tuples in pattern matching?

### ISSUE THREAD

**Issue by q42jaap** [dotnet/csharplang#1379]
I've read https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md and didn't see something along the following lines in there:
```
var t = ("str", 42)
switch (t) {
  case (_, var nr) when nr > 42: ...
  case ("str", 41): ...
  case ("str", _): ...
}
```
I was wondering whether this type of pattern matching is also being considered.

I know this from other languages like scala:
https://www.safaribooksonline.com/library/view/programming-scala-2nd/9781491950135/ch04.html#MatchingOnTuples

**Comment by svick** [comment]
According to the document you linked to, the tuple patterns in your example would be parsed as [positional patterns](https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md#positional-pattern) without  the `type` component. So, such patterns are being considered.

**Comment by q42jaap** [comment]
Thanks
