### ISSUE TITLE
match_expression syntax

### ISSUE THREAD

**Issue by q42jaap** [dotnet/csharplang#1380]
I find the `:` a bit confusing in:
```
let area = primitive switch (
    case Line l: 0,
    case Rectangle r: r.Width * r.Height,
    case Circle c: Math.PI * c.Radius * c.Radius,
    case _: throw new ApplicationException()
);
```
Even though `let` is there and `switch` isn't accompanied by the usual `{}` I misread this as expressions that don't have any effect (i.e. not assigned).
With `=>` being in the language for expression-bodied members, especially for properties, I would think the syntax might be better off with:
```
let area = primitive switch (
    case Line l => 0,
    case Rectangle r => r.Width * r.Height,
    case Circle c => Math.PI * c.Radius * c.Radius,
    case _ => throw new ApplicationException()
);
```
I'm saying this because `=>` makes it feel like the `switch` is "returning" for the cases there.

*Edit:*
What made me think of `=>` is because that always has an expression behind it (in contrast to a block statement). It's true for lambdas and for expression-bodied members.

**Comment by ghost-ccc** [comment]
@q42jaap hello!

Very closely syntax may be implemented by extension methods.

See the online compiled sample for details https://dotnetfiddle.net/4QIZsd

```c#
using System;
					
public static class Program
{
	
	public static void Main()
	{
		Console.WriteLine(new Line { }.CalculateSquare());	
		Console.WriteLine(new Circle { Radius = 7 }.CalculateSquare());		
		Console.WriteLine(new Rectangle { Width = 4, Heigth = 2 }.CalculateSquare());
		
		Console.WriteLine(new Triangle { }.CalculateSquare());	
	}
	
	private static double CalculateSquare(this Shape shape) => shape.Switch(
		
		(Line l) => 0d,
		(Circle c) => 2 * Math.PI * c.Radius * c.Radius,
		(Rectangle r) => r.Width * r.Heigth,
		
		(Shape _) => throw new Exception("Unrecognized shape")
	);
	
	public class Shape {}
	
	public class Line: Shape {}

	public class Circle : Shape
	{
		public double Radius { get; set; }
	}

	public class Rectangle : Shape
	{
		public double Width { get; set; }
		public double Heigth { get; set; }
	}
	
	public class Triangle: Shape {}
}

/* Language Extensions */
public static class LE
{
	public static TR Switch<T, TR, T0>(this T o,
		Func<T0, TR> c0) =>
		o.Switch(c0, (Func<object, TR>) null);
		
	public static TR Switch<T, TR, T0, T1>(this T o,
		Func<T0, TR> c0, Func<T1, TR> c1) =>
		o.Switch(c0, c1, (Func<object, TR>) null);
		
	public static TR Switch<T, TR, T0, T1, T2>(this T o,
		Func<T0, TR> c0, Func<T1, TR> c1, Func<T2, TR> c2) =>
		o.Switch(c0, c1, c2, (Func<object, TR>) null);
		
	public static TR Switch<T, TR, T0, T1, T2, T3>(this T o,
		Func<T0, TR> c0, Func<T1, TR> c1, Func<T2, TR> c2, Func<T3, TR> c3) =>
		o.Switch(c0, c1, c2, c3, (Func<object, TR>) null);
		
	public static TR Switch<T, TR, T0, T1, T2, T3, T4>(this T o,
		Func<T0, TR> c0, Func<T1, TR> c1, Func<T2, TR> c2, Func<T3, TR> c3,
		Func<T4, TR> c4) =>
		o.Switch(c0, c1, c2, c3, c4, (Func<object, TR>) null);

	public static TR Switch<T, TR, T0, T1, T2, T3, T4, T5>(this T o,
		Func<T0, TR> c0, Func<T1, TR> c1, Func<T2, TR> c2, Func<T3, TR> c3,
		Func<T4, TR> c4, Func<T5, TR> c5) =>
		o.Switch(c0, c1, c2, c3, c4, c5, (Func<object, TR>) null);
		
	public static TR Switch<T, TR, T0, T1, T2, T3, T4, T5, T6>(this T o,
		Func<T0, TR> c0, Func<T1, TR> c1, Func<T2, TR> c2, Func<T3, TR> c3,
		Func<T4, TR> c4, Func<T5, TR> c5, Func<T6, TR> c6) =>
		o.Switch(c0, c1, c2, c3, c4, c5, c6, (Func<object, TR>) null);
		
	public static TR Switch<T, TR, T0, T1, T2, T3,T4, T5, T6, T7>(this T o,
		Func<T0, TR> c0, Func<T1, TR> c1, Func<T2, TR> c2, Func<T3, TR> c3,
		Func<T4, TR> c4, Func<T5, TR> c5, Func<T6, TR> c6, Func<T7, TR> c7)
	{
		switch ((object)o)
		{
			case T0 o0: return c0.Invoke(o0);
			case T1 o1: return c1.Invoke(o1);
			case T2 o2: return c2.Invoke(o2);
			case T3 o3: return c3.Invoke(o3);
			case T4 o4: return c4.Invoke(o4);
			case T5 o5: return c5.Invoke(o5);
			case T6 o6: return c6.Invoke(o6);
			case T7 o7: return c7.Invoke(o7);
		}

		return default(TR);
	}
}
```
Thanks for inspiration!

**Comment by ghost-cca** [comment]
P.S. Only 
```c#
(Circle c) => 2 * Math.PI * c.Radius * c.Radius
```
should be corrected to
```c#
(Circle c) => Math.PI * c.Radius * c.Radius
```
Right code https://dotnetfiddle.net/1YyKDg :)

**Comment by Unknown6656** [comment]
I like the syntax of `=>` more than `:`, as it gives -- as @q42jaap said -- a more _executive_ feeling than a _declarative_ one.

----------

Unrelated to this proposal:
What the f*** is this _"ghost"_-user doing here?
If I recall it correctly, @CyrusNajmabadi was planning on contacting GitHub a few days ago about banning him/it from spamming the repository.
Why is this user/bot(/alien [?]) still posting? Why can it post, even though it is connected to a deleted account? What's the story behind it?

**Comment by HaloFour** [comment]
@Unknown6656 

He is continually creating new accounts, commenting and then immediately deleting them.

**Comment by Unknown6656** [comment]
@HaloFour Oh thank you - that explains it ......
Jesus Christ, that is annoying ...
Incidentally - do you know, whether dotnet members have the permissions to delete single posts in issues? It could be worth using a bot connected with one of the dotnet members in order to filter and delete these spam posts ....

**Comment by DavidArno** [comment]
@Unknown6656,

The problem is, the Github folk never planned for someone creating an account, posting, then deleting the account. As a result, those comments by "ghost" can't be deleted. Which is why they are hanging around even once MS folk are informed. @terrajobst is talking to Github to see if a solution can be found. Until then, the best we can all do is just ignore them.

**Comment by Unknown6656** [comment]
@DavidArno ,
Ah of course, I understand. That is hardly something one does plan when developing such a big service as GitHub itself.....
Thank you very much for clearing that up ^^

**Comment by q42jaap** [comment]
@DavidArno FYI: https://help.github.com/articles/limiting-interactions-with-your-repository/

**Comment by gafter** [comment]
@q42jaap Those options for limiting interactions with your repository only last 24 hours.

**Comment by q42jaap** [comment]
FYI: this is discussed by Mads and Dustin: https://www.youtube.com/watch?v=QZ0rWLaMZeI
Closing this issue since the "published" direction this is going in feels right.
