### ISSUE TITLE
Proposal: Access modifier blocks

### ISSUE THREAD

**Issue by Mundairson** [dotnet/csharplang#1391]
Forgive me if this idea has previously been floated and/or rejected :-)

## Background

Access modifiers inside classes and structs are currently either explicitly stated on members, or implicitly determined from language defaults. For example, properties, methods and fields without access modifiers inside classes are by default private but can be explicitly declared to a scope such as public, internal, private and so on.

This proposal is to allow the access modifiers to be used as syntactic sugar around multiple members at once. This has several advantages.

- Allows the grouping of identically accessible members into spatially similar parts of the code. (Yes, this is similar to how C++ sections object members.) This can help to "clean" code files into mentally manageable blocks, which some people currently do by using #region blocks.
- It reduces the amount of repetitive keystrokes. No need to type "public" each time, for example, to change POCO members from the language default.
- It enables groups of related members to have explicitly stated accessibility levels, which is good for self-documentation.

It would operate as compile time syntactic sugar, so all members inside the block would have the same accessibility as if the modifier were explicitly defined on that member. All rules currently in the language concerning accessibility modifiers would therefore still apply. It would not flow into class or struct definitions, thus giving them isolation; it is only to be used within them and to a single level. The order of the blocks is not important, so _public_ does not have to come first, for example. Modifier blocks cannot be nested.

## Examples

``` C#
namespace mycompany.something
{
    // Could not be used here. The convention of one object definition per file would
    // cause it not to make sense out here anyway.
    public class Address
    {
        // Starts a block of public members. Everything in here is public.
        // Accessibility cannot be stated or overridden.
        public 
        {
            // These autoproperties are public but the backing fields are still
            // private as they're not explicitly visible. Sugar on top of sugar.
            string City {get; set;}
            string Postcode {get;}

            string SayHello(string name) => $"Hello, {name}";

            // Not allowed as a modifier cannot explicitly be used inside a modifier block.
            // If you want to use the private modifier, the autoproperty definition should be
            // moved outside of the public{} block.
            bool IsMainAddress {get; private set;}

            // Nested classes would normally be private, but here it is public as it's
            // inside the public{} block.
            class SomeOtherAddressThing
            {
                ...

                // Not affected by the public{} block above as we're now inside another
                // object definition. The modifier block does not cascade in here, but as
                // we're now in a new "context" we could start a new one.
                private
                {
                    string _city;
                    string _postcode;
                }

                public 
                {
                    string City => _city;
                    string Postcode => _postcode;
                }
            }

            // The static modifier itself could be moved into the block definition.
            // See the extension methods example, below.
            static Address WorkAddressFactory() => new WorkAddress();
        }

        private
        {
            // These would be private anyway but are now spatially grouped with less "noise".
            int myAge;
            string firstName;
            string familyName;

            // Would normally be private anyway, but here it is made explicit.
            class WorkAddress : Address 
            {
                ...
            }
        }

        // This modifier is OK because we're not inside a modifier block.
        internal string SomeOtherValue()
        {
            ...
        }
    }

    // This class has the default accessibility. This is a good example of how where
    // you define an object already changes the default accessibility. Here it is
    // internal but for the nested class, above, it would have defaulted to private.
    // With the new syntax, the accessibility is defined by the containing
    // accessibility modifier block if present or the language default if omitted.
    class SecondHomeAddress 
    {
        ...
    }
}
```

## Extension methods with static also moved

This is a possible way to frame other modifiers, but is not the main focus of the proposal.

``` C#
public static MyAddressExtensions
{
    public static 
    {
        Address DoSomethingWithAddress(this Address address)
        {
            // do something
            return address;
        }

        Address MaybeDoSomethingWithAddress(this Address address)
        {
            // do something
            return address;
        }
    }
}
```

**Comment by jnm2** [comment]
I think this has been suggested here: https://github.com/dotnet/csharplang/issues/818

**Comment by Mundairson** [comment]
@jnm2 I thought it might have. My apologies, I'll close this.
