### ISSUE TITLE
delete from c++

### ISSUE THREAD

**Issue by dpeter99** [dotnet/csharplang#1392]
A way to delete a object and set all of the references to it ``null``

Sintax:
```
Object a = new Object();

delete a;
```
``a=null``

(I'm new to language suggestions so this might be stupid or already possible)

**Comment by tannergooding** [comment]
> I'm new to language suggestions so this might be stupid or already possible

All reference types in C# are handled by garbage collection. They will get deleted sometime after the go out of scope.

The exception to this is unmanaged resources (generally created through some kind of P/Invoke), which need to be deleted manually (generally via another P/Invoke call).

**Comment by dpeter99** [comment]
yeah i know that part @tannergooding 
i thought it would be nice to have a way to:
1. make sure the instance is removed
2. in more complex programs make sure there are no loose references to things that are no longer in use
A example:
In a game we could delete a entity and be certain that all of the references are removed

**Comment by HaloFour** [comment]
@dpeter99 

What good would that do?  The GC allocates from the managed heap in order.  Any "holes" you could create from "deleting" an instance would just remain empty until the next collection anyway.

**Comment by dpeter99** [comment]
Well i thought it would just remove all references to that object and than GC would collect it when it does.
Basically schedule it for GC, make sure GC will collect it

**Comment by HaloFour** [comment]
@dpeter99 

That's exactly what's going to happen when you let that reference go out of scope.  It's not like you can somehow sever ties to any other reference that might be hanging out there so the GC is still going to have to walk the root references.

**Comment by dpeter99** [comment]
Well my idea was for cases where some higher manager wants to delete a Entity than it can makes sure all of the references are removed. Like in a large project (especially ones witch can be extended by the user) where it would be hard to remove all the references to a object to make it collected by GC

As I said i might be looking over some obvious things.

**Comment by kameko** [comment]
This is easily accomplished through proper encapsulation via putting a reference in a private field and only allowing access to it indirectly through properties/methods. If you can't keep track of your own objects then you shouldn't be trying to mass-delete them in the first place where something else could be using it only to have the program crash.

**Comment by HaloFour** [comment]
@dpeter99 

> Well my idea was for cases where some higher manager wants to delete a Entity than it can makes sure all of the references are removed.

I'm not sure what you mean by that.  Do you mean that you can `delete` an instance and any other variables referencing that instance would become invalid?

**Comment by dpeter99** [comment]
Yes @HaloFour that was my idea

I see your point @kameko  and I agree.

**Comment by HaloFour** [comment]
@dpeter99 

I'd say that runs pretty contrary to the design of the CLR and of the GC.  It's expected that if you're holding a strong reference to an instance of a managed type that the reference will always be valid.  Allowing an operation that would render any such references instantly invalid would resurrect an entire class of bugs that managed languages like C# were designed to avoid.  In either case, the GC doesn't offer any such capability and without that there's nothing that the language can really do.  You'd have to convince the [CLR](https://github.com/dotnet/coreclr/) team to consider exposing that kind of functionality and in my opinion that would be a pretty tough sell.

**Comment by dpeter99** [comment]
Well if the experts say so...
Yeah i guess i would need much more knowledge of the GC to talk about it...
