### ISSUE TITLE
Proposal: Multi-expression switch statement

### ISSUE THREAD

**Issue by SmartK8** [dotnet/csharplang#1395]
This feature should give a cleaner, more readable and more maintainable solution for the `switch` statement, when two or more independent variables (even of different type) decide branching of the program.

### Plain switch
`enum Mode { Mode1, Mode2, Mode3 }`
`enum Flag { FlagA, FlagB }`

The input values in the example below are `Mode value1` and `Flag value2`. There can of course be more of the input expressions (value3, value4, etc.).

```
switch (value1, value2) // value3, etc.
{
  // equivalent of (value1 == Mode.Mode1 && value2 == Flag.FlagA) || (value1 == Mode.Mode3 && value2 == Flag.FlagB)
  case Mode.Mode1, Flag.FlagA: 
  case Mode.Mode3, Flag.FlagB:
    break;

  // equivalent of (value1 == Mode.Mode1 && value2 == Flag.FlagB)
  case Mode.Mode1, Flag.FlagB: 
    break;

  // equivalent of (value1 == Mode.Mode2 && value2 == Flag.FlagB)
  case Mode.Mode2, Flag.FlagB: 
    break;

  // applies only to: value1 == Mode.Mode3 cases unresolved above (value2 != Flag.FlagB)
  default Mode.Mode3, any: 
    break;

  // applies only to: value2 == Flag.FlagA cases unresolved above (value1 != Mode1 && value1 != Mode3)
  default any, Flag.FlagA:
    break;

  default:
    // remains the same for all the unresolved cases
    break;
}
```

### Switch with pattern matching

This proposal can be combined with the existing `case` capabilities like pattern matching and `when` condition. The example below shows how controls (both parent and child of type `UIElement` for example) can be processed.

```
switch (parent, child)
{
  case Grid grid, Button button:
    break;

  case ToolBar _, Button button when button.IsEnabled:
    break;

  case any, Button button:
    break;

  // do nothing in all other cases
}
```

### Backward compatibility

This solution should of course still be 100% backward compatible and allow for just one value to be passed to `switch` statement.

```
switch (value1)
{
  case Mode.Mode1:
    break;

  default: // equivalent to (and shorthand for) default any:
    break;
}
```
## Motivation and alternatives:

It is motivated by the years of experience and also by the answers that are usually given on various sites (StackOverflow,  CodeProject, etc.) as a workaround (usually involving alternatives like **c**, **d** or **e** at best). These alternatives are:

**a)** Use many subsequent `if`-`else` statements. 

_Drawback:_ These can get quite messy in larger quantities, harder to read and therefore mantain in larger quantities, but it is a viable alternative option.

**b)** Use nested `switch` statements.

_Drawback:_ It can created entangled web that is even more hard to read than **a)**. But again it is a viable option.

**c)** Use bitwise operation on values.

_Drawback:_ Only applies to certain controlled conditions. You have to have values under your control and tweak them to give unique combined results; which is usually not the case.

**d)** Join the values into one and have one switch statement. 

_Drawback:_ These unfortunately mostly end up being a string compared to a merged string. This solution is unreasonably hard to maintain and prone to errors, when values are changed.

**e)** Use `tuples`.

_Drawback:_ Basically even a bit more convoluted than **a**). Can decrease code readability and can be tough to maintain when changes occur.

**f)** Create some kind of rule engine.

_Drawback:_ This requires a scenario to be above a certain complexity, for a rule engine creation to be justified; also it is usually slower and more error prone; unless well-thought and optimized. It's not a suitable alternative for these - more casual - situations.

**Comment by HaloFour** [comment]
Recursive patterns with C# 8.0 will already enable this scenario via tuples, so I consider it fairly unlikely that a second syntax just for this would be considered as well:

```cs
switch ((parent, child))
{
  case (Grid grid, Button button):
    break;

  case (ToolBar _, Button button) when button.IsEnabled:
    break;

  case (_, Button button):
    break;

  // do nothing in all other cases
}
```

**Comment by SmartK8** [comment]
Can you, please, point me to some reference link? I did not find this use case in the Language Feature Status on Roslyn and even here in the proposals. I would still prefer real types without Tuple magic behind it, that can possible be not as fast/efficient (compiler wise), but Tuples would still be a better option than nothing.

**Comment by HaloFour** [comment]
@SmartK8 

It's not as plainly spelled out as it could be but it is covered under [positional patterns](https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md#positional-pattern).  As with many other cases involving tuples I would expect that the compiler would optimize away the use of `System.ValueTuple<...>`.

**Comment by bondsbw** [comment]
I would like to remove the duplicate parentheses for tuples.

(Maybe just remove the requirement for parentheses surrounding the `switch` expression altogether?)

**Comment by SmartK8** [comment]
I read the 'positional patterns' and I'm not sure tuples work for the switch like that. Especially this case seems very unrealistic:

```
case (_, Button button):
    break;
```

I also agree that if it was the case and it was supported, the double parentheses are weird. Even though I understand that parser probably needs that.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/1379#issuecomment-373225917 ?

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/579 ?

**Comment by SmartK8** [comment]
Thanks, I saw that, but skipped over that, because I saw `|` symbol and thought it was just calculated value and therefore standard switch.

**Comment by DavidArno** [comment]
@SmartK8,

> ... I still think it would be better to do it right, instead of everything being solved by a tuple ...

That of course depends on your definition of "right". To my mind, inventing new syntax just to avoid using a tuple would be the wrong thing to do. Supporting switching on tuples via positional patterns would be the right thing to do, therefore in my view.

**Comment by alrz** [comment]
>I would like to remove the duplicate parentheses 

https://github.com/dotnet/csharplang/issues/1090

**Comment by SmartK8** [comment]
As I've said, I'm for any solution that would allow for a cleaner code in this context. I regard this proposal more as an extension to existing switch syntax rather than a new one. It just seems to me, that Tuple solution is being horseshoed as cure-all everywhere, when a clean solution (admitting that switch can have multiple values) would be more, well, clean. Switch syntax wasn't the main design purpose for Tuple, it was only an after-thought, same with removal of parentheses, that seems like a patch on how to make it work with Tuples. Why not just design it for the purpose it should serve from the get-go? I can imagine parser just allowing for comma separated "more of the same" expression in switch/case. While compiler takes it into account and can leave the same optimizations for one value as is and create a branch of optimizations for multi-value separately. Tuple needs first a recognition as a tuple, then recognition of context in which it is used and then making some compiler magic to make it work. I've design it (including contextual word any) to be the least intrusive from the point of parser and compiler, to look like C# and to look clean. In my code I always prefer real solution rather than adopting some existing concept that can be bent to be reused. It might require more work, but I'm always willing to pay with more work to get more clean. Well, that's my opinion at least.

**Comment by HaloFour** [comment]
@SmartK8 

The extension to pattern matching already happened in C# 7.0.  The addition of recursive patterns, as a general purpose feature, is going to happen in C# 8.0, and it solves significantly more use cases than your proposals single-use feature.  The syntax is nearly identical, only trivially more verbose.

As for `any`, the C# language already has a wildcard/discard syntax which was added for pattern matching and that is `_`, which was adopted from any of the many functional languages that have the same feature.

You may think it's more clear, but recursive pattern matching, including positional pattern matching and deconstruction, is definitely being added to the language.  It's been in the works for years.  This use case will certainly be met as a result.

**Comment by SmartK8** [comment]
I repeated this almost in every comment: If it will be using tuples and without parentheses, it'll better than nothing and I'm OK with it. There's no need to reiterate it for me further. But so far I don't see it in the pattern matching proposal. All I see are scattered comments on how to possible do it, but no use in switch in proposal/feature itself.  Maybe this should be added then; to avoid confusion. Specifically this use:

`(_, Button button)`

At best I see: `(ToolBar _, Button button)` which would match positional pattern matching. But that is not the same as the code above. I'm not sure it is considered for C# 8.0 seriously. The evidence amounts to few concerned comments here and there at best. Thus my concern as well. Can I take your word for it that it will be included in the form proposed? I don't care about `any` or `_`. It was just an attempt to make it easier by not reusing the existing meaning of that symbol in pattern matching and out parameters.

**Comment by svick** [comment]
@SmartK8 As far as I know, when it comes to C# 8.0, nothing is set in stone yet. And the people discussing here are not Microsoft employees. So I don't think anyone is going to give you absolute guarantees about what's going to be in it.

That being said, there is currently a prototype of recursive patterns in the branch [features/recursive-patterns](https://github.com/dotnet/roslyn/tree/features/recursive-patterns), which you can easily try out using [SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwgEI5gCeAPgAIAMABOwIwBuALAAodgGZeAJm4BhbgG9R3Fb0nsALNwCyACgCUi5aoC+ok0A=).

For example, the [following code compiles on that branch](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwgEI5gCeAPgAIAMABOwIwBuALAAoUewBM3AMKiA3qO5LeAFm4BZABQBVAJIBRADYQAthAoxuJJBerc9R0+csYAFjkMATAJSLlCkWUg7mQAdxwYN25NTWtnOzcPH19A4KUAtLSMKGQIaIBxRk9uAHMiuwAhOBgYAHsKbmBquopvED9MzOAkKABrYVTOpWzc6IB9Sub6xqnW9sHuAEhl7uh+juCAXw3tkV3xKSqa6ZB7A2MzC245bn2RSW5CnGLThwvna9vRA7PHS8sbpsgA==):

```c#
void M(UIElement parent, UIElement child)
{
    switch ((parent, child))
    {
        case (Grid grid, Button button):
            break;
        case (_, Button button):
            break;
    }
}
```

**Comment by DavidArno** [comment]
@svick,

Nice! Last time I tried that branch, @gafter had not had a chance to get any of the new syntax working. I shall have to have a play.

**Comment by HaloFour** [comment]
@SmartK8 

The "discard" pattern is the third pattern listed in this proposal and can be used recursively in other patterns:  https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md#patterns

I will state that the proposal as its written is both a bit stale and a bit obtuse.  It doesn't really explain the story between tuples and pattern matching beyond mentioning that positional patterns are supported for types that implement `ITuple`, which isn't very clear.  For those of us that have been following this conversation since it started almost four years ago on CodePlex it seems second nature since we often toss about examples using tuples.

/cc @gafter  Might be worth explicitly calling out tuples in the pattern matching proposal for positional patterns?  This is the [second issue](https://github.com/dotnet/csharplang/issues/1379) in less than a week to raise the question.

**Comment by SmartK8** [comment]
I'm aware that not is set in stone, that's a given here :) I will check/try it out. Thanks.

**Comment by SmartK8** [comment]
@HaloFour: Thanks, I can see it now. 
@svick: It compiles as expected, won't run at the moment, but I guess it's too experimental at this point.

I've tried this [sample](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwhTIwA+AAgAwAELAjANwCwAKCEUoAWxQkMEDgBUUMDkIDeQjlwDMXAExduAdjUdVg9epZaWugIJH1Js2YscAQgHs3AG2gUOANRxcYG9jDgBzCBheDmRI6IBfOw5E4VMnS10XJIdHTQ4ASQoYDV0AYTc4ItCIqJi45KSU3KU080tuADYuABY5BQBZSIALNwATAAprDjwoTzgIbmpXadn57QBKbKT1ZAB3HBgMIY5x8Zm5haXztfXN1rMc5owGGUmOKCWXDmB1jl2hiC+KAAOgCQRCADIId9geVKooAHwcNggba5HgATnGACIpnhAjhgjIoBRRssiG5cDB8BBsesBPdmsAkFAANYM5rNNHqZ6xE4AfU+31+/0BMLhVQAPMjUYz0dwsdivhQIGFYDS6RzOepmdB2dzOQbRhAwFA4J46AbzAqcQBlNwSGBDHAUMIcCCeWKaq3fFn6uVNMzxFpc+7OHhdFi9HgADnGd0cj1yUygHAAvBwVbsOFNlP4CUT0xwYAh5sktc0vsAi1nlnmJYoMwBWcsGg3yRiDJ1jcYfYUV5KOIwpFJAA) for anyone interested

**Comment by bondsbw** [comment]
@alrz Thanks, unfortunately the discussion in #1090 mostly overlooks the `switch` use case.  The issues surrounding `if`  really don't apply to many of the others.

**Comment by gafter** [comment]
I did a demo on Friday that included the following example

``` c#
using System;

public class Door
{
    public DoorState State;

    public enum DoorState { Opened, Closed, Locked }

    public enum Action { Open, Close, Lock, Unlock }

    public void Act(Action action, bool haveKey = false)
    {
        Console.Write($"{State} {action}{(haveKey ? " withKey" : null)}");
        switch ((State, action))
        {
            case (DoorState.Opened, Action.Close):
                State = DoorState.Closed;
                break;
            case (DoorState.Closed, Action.Open):
                State = DoorState.Opened;
                break;
            case (DoorState.Closed, Action.Lock) when haveKey:
                State = DoorState.Locked;
                break;
            case (DoorState.Locked, Action.Unlock) when haveKey:
                State = DoorState.Closed;
                break;
            case var (oldState, _):
                State = oldState;
                break;
        }
        Console.WriteLine($" -> {State}");
    }
}

class Program
{
    static void Main(string[] args)
    {
        var door = new Door();
        door.Act(Door.Action.Close);
        door.Act(Door.Action.Lock);
        door.Act(Door.Action.Lock, true);
        door.Act(Door.Action.Open);
        door.Act(Door.Action.Unlock);
        door.Act(Door.Action.Unlock, true);
        door.Act(Door.Action.Open);
    }
}
```

Its output is

``` none
Opened Close -> Closed
Closed Lock -> Closed
Closed Lock withKey -> Locked
Locked Open -> Locked
Locked Unlock -> Locked
Locked Unlock withKey -> Closed
Closed Open -> Opened
```

When *switch expressions* are ready, the switch statement can be replaced by

``` c#
State = (State, action) switch 
 {
     (DoorState.Opened, Action.Close) => DoorState.Closed,
     (DoorState.Closed, Action.Open) => DoorState.Opened,
     (DoorState.Closed, Action.Lock) when hasKey => DoorState.Locked,
     (DoorState.Locked, Action.Unlock) when hasKey => DoorState.Closed,
     var (oldState, _) => oldState
 };
```

**Comment by gafter** [comment]
Added the following to #1054 

### switching on a tuple literal

In order to switch on a tuple literal, you have to write what appear to be redundant parens

``` c#
switch ((a, b))
{
```

It has been proposed that we permit

``` c#
switch (a, b)
{
```

**Comment by gafter** [comment]
The removal of redundant parens was approved by the LDM today. I just finished making the compiler produce great code when switching on a tuple (i.e. not construct a tuple object unless needed), and I'll fix the redundant paren issue tomorrow. Both changes will appear in my next pattern-matching PR.

**Comment by gafter** [comment]
This is fixed in https://github.com/dotnet/roslyn/pull/25963; the following test has been added to demonstrate the way it works and the quality of the generated code:

``` c#

        [Fact]
        [WorkItem(20641, "https://github.com/dotnet/roslyn/issues/20641")]
        [WorkItem(1395, "https://github.com/dotnet/csharplang/issues/1395")]
        public void TupleSwitch01()
        {
            var source = @"using System;

public class Door
{
    public DoorState State;

    public enum DoorState { Opened, Closed, Locked }

    public enum Action { Open, Close, Lock, Unlock }

    public void Act0(Action action, bool haveKey = false)
    {
        Console.Write($""{State} {action}{(haveKey ? "" withKey"" : null)}"");
        State = ChangeState0(State, action, haveKey);
        Console.WriteLine($"" -> {State}"");
    }

    public void Act1(Action action, bool haveKey = false)
    {
        Console.Write($""{State} {action}{(haveKey ? "" withKey"" : null)}"");
        State = ChangeState1(State, action, haveKey);
        Console.WriteLine($"" -> {State}"");
    }

    public static DoorState ChangeState0(DoorState state, Action action, bool haveKey = false)
    {
        switch (state, action)
        {
            case (DoorState.Opened, Action.Close):
                return DoorState.Closed;
            case (DoorState.Closed, Action.Open):
                return DoorState.Opened;
            case (DoorState.Closed, Action.Lock) when haveKey:
                return DoorState.Locked;
            case (DoorState.Locked, Action.Unlock) when haveKey:
                return DoorState.Closed;
            case var (oldState, _):
                return oldState;
        }
    }

    public static DoorState ChangeState1(DoorState state, Action action, bool haveKey = false) =>
        (state, action) switch {
            (DoorState.Opened, Action.Close) => DoorState.Closed,
            (DoorState.Closed, Action.Open) => DoorState.Opened,
            (DoorState.Closed, Action.Lock) when haveKey => DoorState.Locked,
            (DoorState.Locked, Action.Unlock) when haveKey => DoorState.Closed,
            _ => state };
}

class Program
{
    static void Main(string[] args)
    {
        var door = new Door();
        door.Act0(Door.Action.Close);
        door.Act0(Door.Action.Lock);
        door.Act0(Door.Action.Lock, true);
        door.Act0(Door.Action.Open);
        door.Act0(Door.Action.Unlock);
        door.Act0(Door.Action.Unlock, true);
        door.Act0(Door.Action.Open);
        Console.WriteLine();

        door = new Door();
        door.Act1(Door.Action.Close);
        door.Act1(Door.Action.Lock);
        door.Act1(Door.Action.Lock, true);
        door.Act1(Door.Action.Open);
        door.Act1(Door.Action.Unlock);
        door.Act1(Door.Action.Unlock, true);
        door.Act1(Door.Action.Open);
    }
}";
            var expectedOutput =
@"Opened Close -> Closed
Closed Lock -> Closed
Closed Lock withKey -> Locked
Locked Open -> Locked
Locked Unlock -> Locked
Locked Unlock withKey -> Closed
Closed Open -> Opened

Opened Close -> Closed
Closed Lock -> Closed
Closed Lock withKey -> Locked
Locked Open -> Locked
Locked Unlock -> Locked
Locked Unlock withKey -> Closed
Closed Open -> Opened
";
            var compilation = CreateCompilation(source, options: TestOptions.ReleaseExe, parseOptions: TestOptions.Regular.WithRecursivePatterns());
            compilation.VerifyDiagnostics();
            var compVerifier = CompileAndVerify(compilation, expectedOutput: expectedOutput);
            compVerifier.VerifyIL("Door.ChangeState0",
@"{
  // Code size       59 (0x3b)
  .maxstack  2
  .locals init (Door.DoorState V_0) //oldState
  IL_0000:  ldarg.0
  IL_0001:  stloc.0
  IL_0002:  ldloc.0
  IL_0003:  switch    (
        IL_0016,
        IL_001c,
        IL_0025)
  IL_0014:  br.s       IL_0039
  IL_0016:  ldc.i4.1
  IL_0017:  ldarg.1
  IL_0018:  beq.s      IL_002b
  IL_001a:  br.s       IL_0039
  IL_001c:  ldarg.1
  IL_001d:  brfalse.s  IL_002d
  IL_001f:  ldarg.1
  IL_0020:  ldc.i4.2
  IL_0021:  beq.s      IL_002f
  IL_0023:  br.s       IL_0039
  IL_0025:  ldc.i4.3
  IL_0026:  ldarg.1
  IL_0027:  beq.s      IL_0034
  IL_0029:  br.s       IL_0039
  IL_002b:  ldc.i4.1
  IL_002c:  ret
  IL_002d:  ldc.i4.0
  IL_002e:  ret
  IL_002f:  ldarg.2
  IL_0030:  brfalse.s  IL_0039
  IL_0032:  ldc.i4.2
  IL_0033:  ret
  IL_0034:  ldarg.2
  IL_0035:  brfalse.s  IL_0039
  IL_0037:  ldc.i4.1
  IL_0038:  ret
  IL_0039:  ldloc.0
  IL_003a:  ret
}");
            compVerifier.VerifyIL("Door.ChangeState1",
@"{
  // Code size       67 (0x43)
  .maxstack  2
  .locals init (Door.DoorState V_0)
  IL_0000:  ldarg.0
  IL_0001:  switch    (
        IL_0014,
        IL_001a,
        IL_0023)
  IL_0012:  br.s       IL_003f
  IL_0014:  ldc.i4.1
  IL_0015:  ldarg.1
  IL_0016:  beq.s      IL_0029
  IL_0018:  br.s       IL_003f
  IL_001a:  ldarg.1
  IL_001b:  brfalse.s  IL_002d
  IL_001d:  ldarg.1
  IL_001e:  ldc.i4.2
  IL_001f:  beq.s      IL_0031
  IL_0021:  br.s       IL_003f
  IL_0023:  ldc.i4.3
  IL_0024:  ldarg.1
  IL_0025:  beq.s      IL_0038
  IL_0027:  br.s       IL_003f
  IL_0029:  ldc.i4.1
  IL_002a:  stloc.0
  IL_002b:  br.s       IL_0041
  IL_002d:  ldc.i4.0
  IL_002e:  stloc.0
  IL_002f:  br.s       IL_0041
  IL_0031:  ldarg.2
  IL_0032:  brfalse.s  IL_003f
  IL_0034:  ldc.i4.2
  IL_0035:  stloc.0
  IL_0036:  br.s       IL_0041
  IL_0038:  ldarg.2
  IL_0039:  brfalse.s  IL_003f
  IL_003b:  ldc.i4.1
  IL_003c:  stloc.0
  IL_003d:  br.s       IL_0041
  IL_003f:  ldarg.0
  IL_0040:  stloc.0
  IL_0041:  ldloc.0
  IL_0042:  ret
}");
        }
```

I think this demonstrates that your hypothetical disadvantages do not exist.

**Comment by gafter** [comment]
This request is now satisfied by the pattern-matching feature in development for C# 8.
