### ISSUE TITLE
Proposal: New operator %% for power-of-two integer Modulus operations

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/csharplang#1406]
Hello, recently I have discovered an extremely efficient method of taking the modulus of an integer, but only when the divisor is a power of two. While I have implemented this as a method in my program, I think it would be useful and convenient to have this as an operator in the C# language itself.

    public static int ModPow2(int a, int b)
    {
        return (a & (b-1));
    }

This function is only valid for integers and powers of two (b = 2, 4, 8, 16, etc) due to the bitwise nature, but in my testing I have found that it is orders of magnitude faster than the standard modulus operation. In many situations, it is therefore far preferable to use this function instead of `%`.

My proposal is to add to C# a new operator called `%%` which would work similarly to this function (so that `a %% b` has the same output as `ModPow2(a, b)`)

You may ask "why not just write `a & (b-1)` instead?" and the answer is readability and ease of use. 

* The `%%` symbol would make it obvious that the purpose of this bitwise operation is to take the modulus of a number, and show that the intended input for `b` is a power of two. 

* It would also be easier to discover. Not every programmer would realize that `a & (b-1)` can work as a modulus function, but a programmer may try `%%`, or read about `%%` in an example and be able to easily know that it's a modulus function.

**Comment by CyrusNajmabadi** [comment]
> This function is only valid for integers and powers of two (b = 2, 4, 8, 16, etc) due to the bitwise nature, but in my testing I have found that it is orders of magnitude faster than the standard modulus operation. In many situations, it is therefore far preferable to use this function instead of %.

For something so niche and specialized, it's unclear ot me why a method isn't perfectly suitable for this purpose :)

Does any other language out there offer such an operator?

**Comment by quinmars** [comment]
There are some more restrictions to that function: `a` and `b` have to be positive else the result will be different to the normal modulo operation. Additionally the modulo operation throws an exception if b is zero.

So what's wrong to use a function for this very limited and specialized use case?

Btw. if the compiler has enough information that the above restrictions are fulfilled, it apparently will perform this optimization:

```csharp
public static class Program
{    
    public static uint Mod4(uint n)
    {
        return n % 16;
    }
}
```

Will [compile to](https://sharplab.io/#v2:C4LghgzgtgPgAgZgARwIwDYUCYWoOwCwAUAN5LlLEUrJqYCuAlgHbBICyA9gCYAsAFE1ZJmASioUSE6uTh4RSAKRIMAbmlIAvsU1A===):

```
; Desktop CLR v4.7.2563.00 (clr.dll) on x86.

Program.Mod4(UInt32)
    L0000: mov eax, ecx
    L0002: and eax, 0xf
    L0005: ret
```

**Comment by aaronfranke** [comment]
> `a` and `b` have to be positive else the result will be different to the normal modulo operation.

`%` is actually the Remainder operation, not the Modulus operation. I can't imagine many use cases for power-of-two Remainder operations, but the Modulus operation is very useful.

On a related note, a true Modulus operator would be nice to have. If you don't like this proposal, perhaps `%%` could be the true Modulus instead? I currently implement it like this:

    public static real_t Mod(real_t a, real_t b)
    {
        real_t c = a % b;
        if (c < 0) {
            c += b;
        }
        return c;
    }

**Comment by Unknown6656** [comment]
> Perhaps this proposal would make more sense as %&?

Nope - as `%&` is valid syntax (I think), e.g.:
```csharp
unsafe
{
	mytype x = new mytype(...);
	int y = 42;

	x = x %& y;
	// would be equivalent to:
	x = x % &y;
}


struct mytype
{
	// ...
	public static mytype operator%(mytype x, int* p) => ...;
}
```

**Comment by aaronfranke** [comment]
Well, maybe `&%` then?

Either way, I'll close this issue. It seems that this feature is not very popular. 

But I will open a new issue, for `%%` to act as a true modulus operator, and as @quinmars noted, the compiler already optimizes `%` to bitwise when passed `uint`, so if `%%` was a true modulus, `a %% b` where `b` is a power-of-two and they are both `int` could be optimized *by the compiler* to be bitwise.

**Comment by jnm2** [comment]
> so if %% was a true modulus, a %% b where b is a power-of-two and they are both int could be optimized by the compiler to be bitwise.

I don't like this. There would be two ways to do the same thing with equal performance.

**Comment by aaronfranke** [comment]
@jnm2 The current `%` operation does not have equal performance to Bitwise `&`.

**Comment by jnm2** [comment]
@aaronfranke It does when `b` is known to be a power of two, [as @quinmars showed](https://github.com/dotnet/csharplang/issues/1406#issuecomment-375085534).

**Comment by aaronfranke** [comment]
@jnm2 Not quite. That's only when it is passed a `uint` as Remainder and Modulus have different effects when it comes to negative numbers. `%%` could optimize for signed `int`.

**Comment by jnm2** [comment]
@aaronfranke What would the optimization be for signed ints? This looks [pretty optimized](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgZgARYCMAbAQEwGEDsAsAFADeeze9LB+RpAlgHYx4AsgHsAJgBYAFHwG8AlGxYNF7Zlip5eeAKR4SAbhV4AvvWNA===) to me.

**Comment by aaronfranke** [comment]
Based on @quinmars answer, something like this:

    L0000: mov eax, ecx
    L0002: and eax, 0xf
    L0005: ret

**Comment by jnm2** [comment]
`((uint)(-1)) % (uint)10` gives `5`, so something would have to happen besides masking.

**Comment by aaronfranke** [comment]
`(uint)(-1)` is `4294967295`. I am not saying cast to uint. I am not familiar with assembly code, all I do know is that the most optimal Modulus for powers of two is with logical AND `&`.
