### ISSUE TITLE
Dynamic operation bool&&dynamic does not evaluate right-hand-side when left is false

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#1414]
The compiler-generated code for a binary `&&` expression in which the left-hand-operand is `bool` and the right is `dynamic` does not evaluate the right-hand-side if the left is `false`, and it treats the result of the whole operation as `false`. This is not explained by the current specification, and the definite assignment rules should also recognize this fact; see https://github.com/dotnet/roslyn/issues/25718.

**Comment by BillWagner** [comment]
Moving to dotnet/csharpstandard
