### ISSUE TITLE
Proposal : auto conversion from anonymous object to tuples 

### ISSUE THREAD

**Issue by mariusmg** [dotnet/csharplang#1416]
It would be very nice if some autoconversion could be done from a anonymous object to tuples based on 
the fields/property names. So the following code would work :

public (string content, DateTime updateDate) Get(int id)
{
			return this.Find().Where(x => x.Id == id).Select(note => new {content = note.Content, updateDate = note.UpdateDate}).FirstOrDefault();
}

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv .  Definitely an interesting suggestion.  

Although, @mariusmg Can you explain your scenario more?  Your example is not compelling.  Why would you not just write:

```c#
public (string content, DateTime updateDate) Get(int id)
{
  return this.Find().Where(x => x.Id == id).Select(note => (content: note.Content, updateDate: note.UpdateDate)).FirstOrDefault();
}
```

?

**Comment by DavidArno** [comment]
I'm with @CyrusNajmabadi here. At first glance, this seems a nice idea, but upon reflection it's hard to think of a use-case that can't just be solved by using a tuple instead of an anonymous type, thus avoiding the need to convert.

**Comment by yaakov-h** [comment]
I would argue that you could have an `IQueryable` provider that does not understand `ValueTuple`, but you could always do `.Select(note => new { note.Content, note.UpdateDate }).ToArray().Select(n => (n.Content, n.UpdateDate))` as a workaround.

**Comment by mariusmg** [comment]
@CyrusNajmabadi 
Both your samples fail for me with  CS8143   "An expression tree may not contain a tuple literal". My compiler version is 2.7.0.62715 (db02128e)   (VS 15.6.4)

With which version of csc does that work for you ?!


@yaakov-h 
I get a predictable type conversion failure 
CS0029	Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<(string Content, System.DateTime UpdateDate)>' to '(string content, System.DateTime udapteDate)'	

Regarding my scenario,  i have a bunch of small methods which do EF queries and return anonymous objects now (becase they only select a few columns from the table). I want to replace the return types of those methods with tuples (personally i think the resulting code would be simpler and better ). It would be nice if the resulting tuple could be created directly from the query, instead of the workaround with a intermediary anonymous object which has the query result and creating the resulting tuple from that.

**Comment by yaakov-h** [comment]
How do you have a method that return an anonymous object? Dynamic?

**Comment by mariusmg** [comment]
The method returns the tuple itself (first post)

public (string content, DateTime updateDate) Get(int id)

**Comment by jnm2** [comment]
> I would argue that you could have an `IQueryable` provider that does not understand `ValueTuple`, but you could always do `.Select(note => new { note.Content, note.UpdateDate }).ToArray().Select(n => (n.Content, n.UpdateDate))` as a workaround.

You're right, but I am \*so tired\* of doing this.

**Comment by CyrusNajmabadi** [comment]
I'd rather just have expression trees support tuples versus adding an anonymous-type-to-tuple conversion.

**Comment by alrz** [comment]
>I'd rather just have expression trees support tuple

At this point, it seems to me that we're waiting for the syntax to somehow "stabilizes" se we can go ahead and add expression tree support for all that in one go. I hope it becomes something like IOperation so every language feature comes with its own expression tree support. However, since those types are considered as an external dependency, it may be a burden to gradually add expression tree support for each feature.

**Comment by mariusmg** [comment]
> I'd rather just have expression trees support tuples

Sounds great. Anything that helps tuples feel more like first class citizens :)

**Comment by CyrusNajmabadi** [comment]
@jcouv Would it be on you to have expression trees support tuples?

**Comment by jcouv** [comment]
I don't know. I think we will have this discussion in C# 8.0 context, but nothing concrete yet.
