### ISSUE TITLE
Syntactic sugar for yield returning each element of enumerable.

### ISSUE THREAD

**Issue by aquartulli** [dotnet/csharplang#1429]
Put simply it'd be nice to turn this:
`IEnumerable<string> GetFooStrings()
{
     yield return "Foo";
     foreach (var s in GetBarStrings())
     {
          yield return s;
     }
}`

into:
`IEnumerable<string> GetFooStrings()
{
     yield return "Foo";
     yield return each GetBarStrings();
}`

**Comment by scalablecory** [comment]
I can appreciate the desire, I think most of us have had to put some foreach bloat in our code. But, the gain here is not substantive enough to warrant additional syntax.

**Comment by Logerfo** [comment]
See https://github.com/dotnet/csharplang/issues/378

**Comment by aquartulli** [comment]
@Logerfo Didn't see this when looking for dups. Nice to know it has been on the radar at some point.
