### ISSUE TITLE
Proposal: [CallingMemberType] parameter attribute

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#1432]
Since .NET 4.5, System.Runtime.CompilerServices has attributes for the member name, file path and line number of the caller.

The idea is to add CallingMemberTypeAttribute so as to allow code like:

public void TraceMessage(string message,
        [CallerMemberType] string memberType = null,
'       [CallerMemberName] string memberName = "",
        [CallerFilePath] string sourceFilePath = "",
        [CallerLineNumber] int sourceLineNumber = 0)
{
   ...
}

This new attribute would spare us from writing reflection/stacktrace-frame code.

**Comment by svick** [comment]
This is a subset of https://github.com/dotnet/csharplang/issues/87.

**Comment by Ultrahead** [comment]
Ok
