### ISSUE TITLE
Proposal: Default-Type Declaration on Interfaces

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#1433]
For C# 8, a new feature is being considered for interfaces: declaring Default Operations. The idea here is to extend that to types like enums and delegates.

```
public interface IObjectState
{
  delegate void OnObjectStateChangedHandler(IObjectState sender, ObjectStates oldState, ObjectStates newState);  

  event OnObjectStateChangedHandler OnObjectStateChangedEvent; // This is valid already

  enum ObjectStates
  {
    Off,
    Created,
    Initialized,
    ...
  }

  ObjectStates CurrentState { get; }
  ...
}
```

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/13725. I'm not sure why that issue was never migrated to this repo, but that issue can probably be closed now as duplicate of this one.

**Comment by Ultrahead** [comment]
Good to know.

**Comment by Joe4evr** [comment]
Please close your issues when you find out they're already in the works.

**Comment by Ultrahead** [comment]
Closing ...
