### ISSUE TITLE
Proposal: setting/"initializing" properties of returned instances

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#1434]
Currently, when you instantiate a class, you can set its properties this way:

```
var myService = new MyService()
{
  Property1 = true,
  ...
};
```

The idea is to extend this feature for situations like:

```
var myService = Factory.GetService<MyService>()
{
  Property1 = true,
  ...
};
```

For nullable types, ? could be used: Factory.GetService<MyService>()? ...

**Comment by svick** [comment]
This is a duplicate of https://github.com/dotnet/csharplang/issues/803, except for the nullable part.

**Comment by Ultrahead** [comment]
I'm closing this thread given #803 and #1449.
