### ISSUE TITLE
Proposal: MainAsync can be an entry point

### ISSUE THREAD

**Issue by acid-chicken** [dotnet/csharplang#1438]
I propose to add a specification that the method which named "MainAsync" can become the entry point if the method which named "Main" does not exist.
It makes good for the naming conventions which specifies all of the asynchronous method names have to end with "Async".

example code:
```csharp
class Program
{
    static async Task MainAsync(string[] args)
    // This method is the entry point of this program
    // because the program has no method which named "Main".
    {
        await Task.Delay(int.TryParse(args.FirstOrDefault(), out int result) ? result : 0);
        Console.WriteLine("Hello, world!");
    }
}
```

**Comment by svick** [comment]
[The proposal which added `async Main` says:](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/async-main.md)

> ### Alternatives
> […]
> Using "MainAsync" instead of "Main" as the name. While the async suffix is recommended for Task-returning methods, that's primarily about library functionality, which Main is not, and supporting additional entrypoint names beyond "Main" is not worth it.

So it seems to me this option was considered and rejected.

**Comment by acid-chicken** [comment]
Thank you for your comments.
I understand this proposal was already rejected. So I'll close this issue.

Incidentally, how can I hide warning at "async Task Main" in a project that has the coding rule like below?

```ini
dotnet_naming_rule.async_method_names_ends_with_async.symbols = async_methods
dotnet_naming_rule.async_method_names_ends_with_async.style = ends_with_async
dotnet_naming_rule.async_method_names_ends_with_async.severity = warning

dotnet_naming_symbols.async_methods.applicable_kinds = method
dotnet_naming_symbols.async_methods.applicable_accessibilities = *
dotnet_naming_symbols.async_methods.required_modifiers = async

dotnet_naming_style.ends_with_async.required_suffix = Async
```

**Comment by jnm2** [comment]
^ @sharwell I don't see an issue for this in dotnet/roslyn. Should @acid-chicken open one?

**Comment by jnm2** [comment]
@acid-chicken In general, you hide warnings by placing the text cursor on the warning, pressing <kbd>Ctrl</kbd>+<kbd>.</kbd>, selecting "Suppress XXXXXXX", and selection an option.

For example, here you'd choose to suppress in source. It would insert:

```cs
#pragma warning disable IDE1006 // Naming Styles
```

**Comment by acid-chicken** [comment]
@jnm2 Thank you! I could resolve this problem by inserting the context you suggested.
