### ISSUE TITLE
Proposal: Non-static entry point

### ISSUE THREAD

**Issue by sylveon** [dotnet/csharplang#1440]
## Summary
[summary]: #summary

This suggestion aims to permit the use of a Main method without the `static` attribute, if the class in which the entry point resides has a parameter-less constructor.

## Motivation
[motivation]: #motivation

Currently, accessing non-static members of the class in which Main resides requires manually creating an instance of it. It's an error that many beginners I saw on a community-ran C# Discord make, and that I sometimes accidentally make myself. Adding this would prevent those kinds of mistakes, as well as remove the manual instance creation required to access these if for any reason they cannot be marked static.

One of the case I can think off my head is if the class inherits an abstract class from an external library or the program itself which has virtual methods (why would you do this to a entry point class is out of the scope of this proposal). Instead of having to do `new Program().VirtualMethod();`, `this.VirtualMethod();` would suffice.

## Detailed design
[design]: #detailed-design

Knowing the limitation of the CLR to have a static entry point, the solution would lean towards something like the recently introduced async main, which is just syntactic sugar for something similar to this:

```cs
public static int Main(string[] args) => MainAsync(args).GetAwaiter().GetResult();

public static async Task<int> MainAsync(string[] args)
{
    // Method body
}
```

Which means, if this proposal is implemented, this (currently invalid) code
```cs
class Program
{
    private readonly _rng = new Random();

    public int Main(string[] args)
    {
        return _rng.Next();
    }
}
```

would, when compiled, end up more akin to
```cs
class Program
{
    private readonly _rng = new Random();

    public int Main(string[] args)
    {
        return _rng.Next();
    }

    public static int Main(string[] args) => new Program().Main(args);
}
```

Evidently, we would be able to use the other variants of Main too without the static modifier (async, void return, parameter-less)

If the class has a custom-specified parameter-less constructor, it will be ran (maybe it would be good to show a warning here, specifying that the constructor will run before the non-static Main).

If the class does not have a parameter-less constructor (for example, it is marked abstract, or it has custom constructors), the compiler would error if a non-static Main is trying to be used.

If both a non-static Main and static Main exists, a CS0017 error will be emitted, and the user would need to remove one of them to continue, or use the `/main` compiler switch to select another class as entry point. (this was just quickly though of, as I am not aware of what happens currently if both a async and sync entry point are declared. Maybe it would be  better to use the same behavior here.)

---

I am open to suggestions and criticism.

**Comment by svick** [comment]
For the case of beginners starting with C#, I would like to see C# scripting made more widely available and better supported. With that, you don't have to worry if the `Program.Main` method or fields of the `Program` class are `static` or not, because there is not `Program` class in the first place.

**Comment by theunrepentantgeek** [comment]
This would break existing code - the `static Main()` method doesn't have to be on any particular class (i.e. it doesn't have to be a member of `static class Program`). The only restriction is that there can be only one (unless you forgo compiling in Visual Studio and use `/main` from the command-line).

While I don't know if it is a common pattern, I've seen a bunch of console apps where each of the *modes* of the application are implemented by a different class, each with an entry point called `Main()`.

To illustrate, here's how a program like **git** would be built if it were rewritten in C# following this approach:

``` csharp
public static class Program
{
    public static int Main(string[] args) { ... }
}

public class PullMode
{
    public int Main(string [] args) { ... }
}

public class FetchMode
{
    public int Main(string [] args) { ... }
}

public class CommitMode
{
    public int Main(string [] args) { ... }
}
```
and so on.

If non-static `Main()` methods were considered valid entry points, code like this would fail to compile on the new version of the compiler.

Since the team (rightly!) holds backward compatibility in very high regard, I suspect this suggestion won't progress as the benefit (if any) is minor.

**Comment by svick** [comment]
@theunrepentantgeek I think that problem is easily solvable the same way it was solved for [`async Main`](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/async-main.md#detailed-design), which also added new possible signatures for `Main`:

> To avoid compatibility risks, these new signatures will only be considered as valid entrypoints if no overloads of the previous set are present.

**Comment by sylveon** [comment]
@HaloFour After trying to come up with a reply, I noticed that everything this would support reeks of bad practice. Seeing how the general opinion is also negative towards this suggestion, there's no point in fighting for it except making another Makeloft out of myself. I'm going to close this issue.

@svick While I think C# scripting is a good idea (on the mentionned Discord server, we even have an [eval service](https://github.com/discord-csharp/CSDiscord) connected to a [bot](https://github.com/discord-csharp/MODiX) for quick scripting or demo inside the server itself), there's still a lot of work IMO for it to reach a level good enough for basic programs:
 - Impossible to debug. You can't set breakpoints on nor launch a .csx file from within VS. You have to rely on the C# interactive prompt, its `#load` directive and Console.WriteLine based debugging.
 - No template. Right now to create a .csx file, you need to manually go into the File Explorer, create it and then open it from VS. There's no prebuilt "C# Script" project.

Along with those issues, most beginners will probably still begin with a regular C# project until the C# script format gets more widespread, because a regular is what all the existing, trusted and recommended books and videos recommend.

While things like [AnyScriptCs](https://marketplace.visualstudio.com/items?itemName=IgalTabachnik.AnyScriptCS) exists, which fixes my first point, it doesn't uses the Roslyn engine and is unmaintained.
