### ISSUE TITLE
Proposal: close all remaining braces with )!;

### ISSUE THREAD

**Issue by feO2x** [dotnet/csharplang#1441]
Consider the following code:

``` csharp
private static Task<Document> SetDefaultXmlCommentForParameterName(Document contextDocument, SyntaxNode syntaxRoot, XmlElementSyntax xmlElementSyntax) =>
    Task.FromResult(
        contextDocument.WithSyntaxRoot(
            syntaxRoot.ReplaceNode(
                xmlElementSyntax,
                xmlElementSyntax.WithContent(
                    new SyntaxList<XmlNodeSyntax>(
                        SyntaxFactory.XmlText(ParameterNameDefaults.DefaultComment))))));
```

I'm a big fan of the declarative nature of these nested method calls - however, I don't like the closing brackets `))))));` at the end. It would greatly enhance readability if we could write something like **`)!;`** instead. The C# compiler would automatically fill in the missing braces during a build.

Some issues:

- Can we make this work for other brace types (curly braces, square brackets), too? Especially when they are mixed in the nested call chain?
- How hard is it to implement this feature? I have no idea.
- How hard is it to maintain this feature? I have no idea.

Nonetheless, I think this or something similar would be a fantastic piece of syntactic sugar, especially in contexts where hierarchical object graphs are manipulated with nested method calls.

**Comment by sharwell** [comment]
:memo: This is ambiguous with the `!` operator coming for nullable reference types.

**Comment by feO2x** [comment]
@sharwell That's correct - could we use some other character?

**Comment by Joe4evr** [comment]
Relevant XKCD:
![](https://imgs.xkcd.com/comics/lisp_cycles.png)

**Comment by Thaina** [comment]
If it's me I would rewrite everything into extension method then write it as

```C#
=> syntaxRoot.GetNode(xmlElementSyntax).ReplaceWith(xmlElementSyntax.WithContent(ParameterNameDefaults.DefaultComment.ToXmlText(SyntaxFactory).ToSyntaxList<XmlNodeSyntax>())).ApplySyntaxRoot(contextDocument).ToTask();
```

**Comment by eyalsk** [comment]
Piping is a much better solution.

**Comment by asyncawaitmvvm** [comment]
OP is using a bad coding pattern. If any of those nested calls throws an exception, they will all be included on the same line in the stack trace.

**Comment by feO2x** [comment]
Alright, it's not a good proposal. Never propose something out of a gut feeling.
