### ISSUE TITLE
Proposal: Interlocked.Exchange overload for ulong, uint

### ISSUE THREAD

**Issue by shravan2x** [dotnet/csharplang#1446]
As the title suggests, I propose adding overloads to atomically exchange ulongs and uints. I had a use case for them earlier today and couldn't understand why they didn't exist.

Can these be added or is there some technical issue?

**Comment by khellang** [comment]
Isn't this a request for corefx and/or coreclr and not a language request?

**Comment by shravan2x** [comment]
I was confused why it didn't already exist and thought there might be a reason why they decided not to add them. So I created this issue to discuss that reason.

I'll move it to corefx.
