### ISSUE TITLE
object??.field may return false instead of null

### ISSUE THREAD

**Issue by suadev** [dotnet/csharplang#1455]
As you know,  the '?' operator in "object?.field" returns null if the object is null. In the following if statement, i would like to use '?' for null check but, if the model is null, model?.item will be return also null, not false.

```cs
if (model.item != null && model.item.list!= null && model.item.list.Any())
{
//...
}
```
What about double '??' here. I mean;

<strike>
if (model??.item && model.item??.list && model.item.list??.Any())

</strike>

```cs
if (model??.item??.list??.Any())
{
//...
}
```

if model or item or list is null, the condition equals false.

**Comment by yaakov-h** [comment]
`if (model.item?.list?.Any() ?? false)`?

**Comment by suadev** [comment]
@yaakov-h nice job :D

**Comment by suadev** [comment]
@yaakov-h  what about that? 

```cs
if (model??.item??.list??.Any())
{
//...
}
```

**Comment by Neme12** [comment]
what about this:
```c#
if (model??.item!??.list?!!.Any!!!())
```

**Comment by Richiban** [comment]
@suadev 

Your example isn't consistent; I think what you actually want is:

```csharp
if (model?.item?.list??.Any())
{
//...
}
```

But, I don't think this looks so good. It's also not a good idea, as discussions in other issues have elucidated, to give a way in which the programmer can conflate `null` with `false` in the case of a `Nullable<bool>`.

**Comment by yaakov-h** [comment]
@suadev I've probably rewritten this post about 3 times now trying to understand your proposal and what on earth `model??.item??.list??.Any()` could even mean. I can't make heads nor tails of it.

What is the return type of `x??.ToString()`? Is it a `string`, or is it a `bool`? 

If `??.` as a new operator would only apply to boolean situations, it's of _extremely_ little utility.

**Comment by theunrepentantgeek** [comment]
The `??` operator already gives a very easy way for any developer to be quite clear what **null** should mean in that case.

If you don't like `??` then it can equally be expressed as

```
if (model.item?.list?.Any() == true) 
{
    // elided
}
```

**Comment by suadev** [comment]
I accept that I do not think too much about this idea (: 

@Richiban  if model is not null, model??.item  doesn't return true. It returns nothing, just keep going.
?? is only for the case that model is null.

@yaakov-h  you can use x?.ToString(), no need to use "??" here.

'??' is only for using in a if statement.

**Comment by yaakov-h** [comment]
Or even `?? someVariable`, `?? AFunctionCall()`, etc.

**Comment by suadev** [comment]
@jnm2 , you are right, "putting ?? true at the end" it was a good point 👍
