### ISSUE TITLE
Feature Request: Type Aliases for primitive arrays

### ISSUE THREAD

**Issue by CharlesTaylor7** [dotnet/csharplang#1460]
Currently, I can create a type alias by writing (inside my namespace) : `using IntList = List<int>;`
I would like to use this feature on primitive array types, something like: `using IntArray = int[]`.

My use case is that I'm writing performance critical code, and would rather not wrap my primitive array in a class just to provide a descriptive name.

**Comment by CharlesTaylor7** [comment]
@HaloFour My example was lazy. The actual scenario, I encountered today was working with polynomial coefficients and wanting to alias `float[]` as `Coefficients`.

**Comment by CyrusNajmabadi** [comment]
What about:

```c#
struct Coefficients {
   private float[] _data;

   // whatever ops you want
}
```

Now you won't accidentally pass a float[] intended for some other purpose to something that only expects to operate on Coefficients.

**Comment by CharlesTaylor7** [comment]
@HaloFour Do you have reference source describing this JIT optimization?

**Comment by CharlesTaylor7** [comment]
@HaloFour @CyrusNajmabadi Thanks for the pragmatic solution of wrapping in a struct. 
As for the actual feature request, h

**Comment by alrz** [comment]
This could be a part of https://github.com/dotnet/csharplang/issues/423

Currently, none of build-in types are permitted in using alias:

```cs
using SomeTuple = (int i, int j);
using SomeArray = int[];
using SomePrimitive = int;
```

**Comment by MkazemAkhgary** [comment]
Have you performed benchmarks to see how  well `float[]` performs compared to a wrapper type?

most of the time you realize it has almost to absolutely no effect.

**Comment by MkazemAkhgary** [comment]
>and would rather not wrap my primitive array in a class just to provide a descriptive name.

Is that all you want? Just to provide a descriptive name? Whats wrong about having variable like `float[] coefficient = ...`?

**Comment by CharlesTaylor7** [comment]
@MkazemAkhgary  I use `var` for local variables declarations. So your example is nothing close to my use case.
The benefit lies in being able to use `Coefficients` as the return type of a method/property. Or to annotate an method argument. I'm not a big fan of xml doc `<param>` tags. A well named type/alias can go a long way in explaining programmer intent.
This design technique might seem strange if you've never seen it before, but its more common in certain languages. In F# & Haskell type aliases are standard practice.

**Comment by theunrepentantgeek** [comment]
I'm a big fan of being able to name types in useful ways - I know the technique as _Semantic Types_ and I've both blogged and presented on the subject. 

But … type aliases are a kind of poor-man's semantic type, delivering the appearance of type safety without actually achieving it. 

@CyrusNajmabadi gave this example, above:

```
struct Coefficients {
   private float[] _data;

   // whatever ops you want
}
```
How does this fail to deliver the same benefits as you claim for type aliases?

**Comment by CyrusNajmabadi** [comment]
> The benefit lies in being able to use Coefficients as the return type of a method/property. 

Note: this is a very marginal benefit.  Information about aliases is completely erased when compiled.  So anyone actually looking at your API will see it as a ```float[]```.  If you want to signify that these are coeffecients, then defining a Coefficients type is valuable.  If you use a struct, it should be nearly free (though perhaps in some extremely perf sensitive cases it might not be).

**Comment by AustinBryan** [comment]
@alrz  I sort've feel like an alias for a tuple is getting very close to just being a `struct`.

**Comment by CharlesTaylor7** [comment]
@theunrepentantgeek I ended up using @CyrusNajmabadi's approach of wrapping in a struct. (Pretty similar to using a `newtype` wrapper in Haskell).
 My interest in array aliases has decreased, but I do find it to be a curious gap in the language semantics.

The feature requested would be more useful if we could also export type aliases a la F#.
