### ISSUE TITLE
Support single item tuples in C#

### ISSUE THREAD

**Issue by ymassad** [dotnet/csharplang#1464]
Please support single item "tuples" in C#. For example:

`Dictionary<(string address), (int count)> dictionary;`

The benefit of this is code readability.

As far as I know, the underlying ValueTuple already has a single item version.

Also, for performance reason, it could also be implemented in a way that does not use a ValueTuple. For example, the above code can be translated to the following:

`Dictionary<string,int> dictionary;`

Instead of:

`Dictionary<ValueTuple<string>,ValueTuple<int>> dictionary;`

**Comment by HaloFour** [comment]
#883
