### ISSUE TITLE
Allow suppression of definite assignment in a struct constructor with explicit layout.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/csharplang#1465]
NOTE: I believe this should be a compiler feature, rather than a language feature, in the same vein as `SkipLocalsInit` (https://github.com/dotnet/csharplang/pull/1223).

Today, the C# language has no built-in support for overlapping-fields. However, the C# compiler recognizes the `FieldOffset` and `StructLayout(LayoutKind.Explicit)` attributes which allow encoding this metadata at the IL level.

Additionally, in certain performance oriented and/or interop scenarios it may be important that the user be allowed to skip the rule that all fields of the struct must be assigned before the constructor exists.

As such, I propose support for a new attribute that will allow users to bypass the definite assignment rule  for structs marked with the `StructLayout(LayoutKind.Explicit)` attribute.

**Comment by tannergooding** [comment]
A possible workaround is to take the address of `this`:
```C#
fixed (MyStruct* pThis = &this)
{
    // This skips the C# definite assignment rule that all fields of the struct
    // must be assigned before the constructor exits.
}
```

However, this does not work with types using generic structs where `T` is not constrained to be `unmanaged`. Adding the `unmanaged` constraint is not always possible, even for a struct that meets the requirements, due to back-compat concerns.

**Comment by tannergooding** [comment]
FYI. @VSadov, @jaredpar

**Comment by jaredpar** [comment]
Why invest a language / compiler feature when customers have the following work around:

``` c#
this = default;
```

That should effectively silence definite assignment in all interesting cases.

**Comment by tannergooding** [comment]
@jaredpar, because `this = default` still causes the following IL to be generated:
```
ldarg.0
initobj MyStruct
```

This may cause poor performance in code where performance matters.

**Comment by tannergooding** [comment]
The point of this proposal is to expose a mechanism that prevents double-writes in performance oriented code (but it also becomes applicable to interop-code as well).

The only thing that definitely avoids this today is `fixed (MyStruct* pThis = &this) { }`. This still has the side-effect of emitting some unused pinning code, but the generated assembly ends up being much better in that case, because the JIT can potentially optimize the unused local away.

**Comment by VSadov** [comment]
Allowing use of formally uninitialized results in a nondeterministic behavior. 
This seems a lot to lose while the perf benefits would be observable in a very narrow set of scenarios like benchmarks that intentionally amplify the costs of struct field writes (basically do nothing else).

JIT can and does detect double-initialization and in many cases dead writes are elided. 
If there is a room for more optimizations, this should be done in the JIT. As I understand there are still some inefficiensies around initialization of structs. I think that should be the first place where improvements should be made 

Countering insufficient optimizations by language changes should be a very last resort measure. Codegen may be improved or significantly changed, but the language rules will have to stay even after that.

**Comment by qrli** [comment]
I'm not sure the solution is to suppress definitive assignment analysis, but it is indeed better if the redundant duplicated initialization can be removed. 

Ideally, I'd expect the compiler to recognize overlapping fields and treat them as assigned as long as all the bits are assigned, even by some other field name.

**Comment by EgorBo** [comment]
https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Decimal.cs#L134-L151 -- hm.. so the feature is already implemented? I see in this (and others) constructor some fields are not inited (with the same offsets).

**Comment by PathogenDavid** [comment]
@EgorBo That is strange. CS0171 is definitely alive and well for structs with explicit field offsets. ([See test here](https://sharplab.io/#v2:EYLgHgbALAPgAgBgARwIwDoBKBXAdgFwEsBbAU3QEkDSAnAewAcBlWgN0IGNSBnAbgFgAUEIDaTfDWwd8AGQCGATzrZ8ACnlKVAaUK4AJugCiYBgBtOhfAEoAukLgBmJNwlT8SACo98AYW4JUAHZUIQBvISRIpBEAMUJSUz0AeQAzFO5SNW5CAC9SOhTVFNM6OWskACokBFsIqMckGlI5PTpcUwUkYtL3AEFTBgALOQFBKOi4hOS0jKzc/MLusqtK6tqx+qcmlraOrpKypBG6yJOUJy8XPwDgooP3MCsz8I3xyLkkAF4kMFHxgF8hIDhIIgA))

It seems like the compiler is making some relaxation here. I poked around in Roslyn [where the error is handled](https://github.com/dotnet/roslyn/blob/55a846f6c29b5e8010e3a12d2854e8e924273984/src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs#L329) and nothing stood out to me that would make `System.Decimal` an exception to the rule. I didn't dig very far though.

**Comment by PathogenDavid** [comment]
Also since they haven't been mentioned yet, here's some old Roslyn issues which are relevant to this one:

* https://github.com/dotnet/roslyn/issues/7323
* https://github.com/dotnet/roslyn/issues/10319

https://github.com/dotnet/roslyn/issues/10378 also mentions both of the above issues.

Specifically, I would point out @gafter's comment on https://github.com/dotnet/roslyn/issues/7323:

> I am not confident that the LDM would be willing to act on this request, so I am not moving it to the new repo. I recommend you write your constructor this way:
>
> ```csharp
> public SingleOrUInt32(float value) : this()
> {
>     //UInt32 = 0;
>     Single = value;
> }
> ```

------

There was some discussion about whether the JIT will optimize away the "unnecessary" assignments, but it doesn't. I don't think it really safely can for thread safety reasons. You can see redundant assignments are emitted even in [simple cases](https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACBmABMuAJwFcBjOXAFQFMCAlagE2IDtHEW4BBZZASwDmLVNU4BYAFABvSbjm4cuQtUSMA9iwA2AT1x9OuRAG5Z803MU16TVu049+QkZwAU+imACU53DInyAw1wAXlwABkgoE39AuUQQ3DBogIBfSTSJSSA==).

**Comment by tannergooding** [comment]
Closing this as covered by the `Unsafe.SkipInit<T>(out T value)` API added in .NET 5
