### ISSUE TITLE
Allow 'in' [readonly 'ref'] based unconstrained extension methods

### ISSUE THREAD

**Issue by makeman-xyz** [dotnet/csharplang#1474]
Consider the code which has a purpose in creation of an extension method logically similar for both classes and structs but without copying of structs
```c#
using System;

public static class C {
    public static T To<T>(this ref T o) where T: struct => o;
    public static T To<T>(this T o) where T: class => o;
    
    /* nice to have */
    //public static T To<T>(this ref T o) => o;
    /* or */
    //public static T To<T>(this in T o) => o;
    
    public static void Main() {
        int i = 0;
        Console.WriteLine(To(ref i));
        Console.WriteLine(To(new Object()));
        
        Console.WriteLine(i.To());
        Console.WriteLine(new Object().To());
    }
}
```
[On the C# 7.2](https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLACgNQMwMQNgQCY4BhOAbwzhoVyUIBU5GB7AHkYD4AKAFwAWASwDOcAE4BTAGYs4rAJRwA7gMlSWIOCL7iArgGM+cALxd5adLTp4mLDt37CxzRSrUbGWqCTMXqtAE0APQAVHAAdkIGknB8rHACAIYAbrGhwUFwwcE4tnJsnLyCohIycm5+rJbWYfLicBlZOXkMBQ7FznBCERVKVTWBVrStBAgALHgAHDxKVMPWND3GQqZwMIOLeACcPGw8UrJCCgqbi0i7+xGSynAA8gBGAFaSRrMnZ9ZZ1hc8QgB0+w+2WCcHU4lYDVIAGUYIgiIgtIw1HADEkADbo7piJIAWweQgA5npWHoRN8Rohdtdbo8Xm8FIDWO9kCCweIIVDYfDESwUWjMdi4HiCcTSeSFnAAL4YKVAA==) there are compiler errors
```c#
        Console.WriteLine(i.To()); // error CS0121: The call is ambiguous
        Console.WriteLine(new Object().To()); // error CS0121: The call is ambiguous
```

[On the C# 7.3](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChLsBmQogNkICZ8BhfAb0v18LuJMAKviEB7ADxCAfAAoYACwCWUfAjgAzUfjEBKfAHcFiOKJD5YCAK4BjGPgC80neQp9+9YaMkz5y1SJ6hsbqZiyOzmKu7jx8APQAVPgAdko2pjBi+AoQAG6mCXGxvHFxtJ7a4lJyiipqmtpBTi7F+Ik6CPiFraXlgpU+Nf74SsmN+s1Rra19jIQALPQAHLL63G7ufKP2So74uNGbvMQAnLLisupaSrq6h0en52KyyXAG+ADywABWcHart3um1a7keSgAdBdAW04vhEAgxJ02ABlXBEZhEcxCYz4GwQAA2+JGqggYGASgA5lYxFYoCC+I9Xu8vr9/rpIc9oaU4QgEUjUejMaIcXjCcT8KTyVSaXSNrwAL6UeVAA=) this code works great according 
https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/improved-overload-candidates.md

In the current case much more convenient to have a single extension method without constraints
```c#
public static T To<T>(this ref T o) => o;
/* or */
public static T To<T>(this in T o) => o;
```

As I understand from https://github.com/dotnet/roslyn/issues/165 a restriction for `ref`-based extension methods has been added to avoiding of possible reassignment with reference types, for example like

```c#
public static T To<T>(this ref T o) => o = default(T);
```
But seems that `in` [read-only `ref`] keyword disallows reassignment and may be safely used for unconstrained extension methods.

What do you think? Maybe do I misunderstood something and `in`-based extension methods disabled by some objective reasons?

----
Posted by @Makeman-from-Makeloft
P.S. Guys, if you will continue useless banning policy I shall be forced to post information as @ghost

**Comment by sharwell** [comment]
> As I understand from dotnet/roslyn#165 a restriction for ref-based extension methods has been added to avoiding of possible reassignment with reference types ... But seems that `in` [read-only `ref`] keyword disallows reassignment and may be safely used for unconstrained extension methods.

It does seem that allowing unconstrained `in this` extension methods would adhere to the original design goal.

**Comment by makeman-xyz** [comment]
@ufcpp thank!

`in` modifier semantics is confusing for me.

According [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2)

> The in modifier on parameters, to specify that an argument is passed by reference but not modified by the called method.

I expected that
```c#
void Test(in AnyStructOrClass o)
```
is like
```c#
void Test(readonly ref AnyStructOrClass o)
```
But actually we have something like
```c#
void Test(readonly AnyStructOrClass o)
```

**Comment by Joe4evr** [comment]
```cs
public static void M<T>(in T x)
    where T : struct, IDisposable
{
    // x is always copied because T could be non-readonly.
    // This is why `in` extension methods are not allowed.
    x.Dispose();
}
```
This is also why `struct` Disposables are a Bad Thing™.
