### ISSUE TITLE
COM-interop and ref-modifier of parameters. Is it bug or feature?

### ISSUE THREAD

**Issue by antrv** [dotnet/csharplang#1476]
Hello!

The following code is not compiling. But if you uncomment the commented line with [ComImport] attribute, then the code will compile. 
Is it a compiler bug or a feature? Where this behavior is described?

Thank you,
Anton

```
    public struct MyStruct
    {
    }

    // [ComImport]
    [Guid("3D7E2C40-16C2-479C-A629-EA919898EE2C")]
    public interface IMyIntf
    {
        void A(ref MyStruct s);
    }

    static void Main()
    {
           MyStruct s = default;
           IMyIntf i = null;
           i.A(s);
    }
```

**Comment by HaloFour** [comment]
What compiler error are you getting?  It seems to compile fine on [SharpIO](https://sharplab.io).  IIRC `ref` parameters in COM interfaces is quite common.

**Comment by HaloFour** [comment]
@antrv 

You're always required to specify `ref` at the call-site when passing a `ref` argument.  The `ComImport` attribute has nothing to do with it.

**Comment by HaloFour** [comment]
@antrv 

Actually, let me take that back, seems the compiler does relax that requirement when the `ComImport` attribute is there.  I'm going to assume that this is because so many COM interfaces have `ref` parameters.  (Shows how long it's been since I've done COM interop in C#)

**Comment by svick** [comment]
This has already been discussed in https://github.com/dotnet/roslyn/issues/23828, which points to the article [*COM Interop in C# 4.0*](https://blogs.msdn.microsoft.com/samng/2009/06/16/com-interop-in-c-4-0/), which explains the reasoning for this feature:

> The first feature is really an acknowledgement that the APIs generated for COM interop are quite poor. For those of you who have worked in any amount of detail with the Office PIAs, you’ll quickly realize that for some reason, just about everything is passed around by ref.
>
> […]
>
> I have to struggle with the type system to make it happy, just to add a simple Word document!
>
> C# 4.0 makes this easier. The compiler will now determine that you’re working with a COM object by looking at the attributes of the type of that object, and checking to see if it has the [ComImport] attribute. Once it determines that you indeed are working with a COM object, it then gives you the ability to pass arguments to the method […] without giving them by ref.

**Comment by antrv** [comment]
Thank you for the explanation!
