### ISSUE TITLE
Proposal: compiler-populated `Members` on `NewExpression` for more than anonymous types

### ISSUE THREAD

**Issue by tuespetre** [dotnet/csharplang#1481]
Currently the compiler will only pass the `members` argument to the `NewExpression` constructor when the `NewExpression` is for an anonymous type. If this could be done for other types' constructors as well, it would give expression tree processors (such as LINQ providers) a chance to resolve bindings with more accuracy, especially when code authors want to work with non-anonymous immutable/record types. 

I feel that this will be an important feature to have **especially** with the coming proposed record types, given that they compile down to plain old classes and can be manually expanded as plain old classes in order to add to the type's definition, meaning they should be able to appear in expression trees.

What I am proposing consists of two parts:

1. A new attribute, say `System.Runtime.CompilerServices.NewExpressionMembersAttribute`, and the use of it to resolve members for `NewExpression`s. This attribute would be allowed to target constructors, and it would receive a string array of names of fields and/or properties applicable to the type being constructed. Those names would be exposed through a `MemberNames` property on the attribute, and the attribute would take them as a required constructor argument:

    ```
    namespace System.Runtime.CompilerServices
    {
        [AttributeUsage(AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
        public sealed class NewExpressionMembersAttribute : Attribute
        {
            public NewExpressionMembersAttribute(params string[] memberNames)
            {
                MemberNames = new ReadOnlyCollection<string>(memberNames ?? new string[0]);
            }

            public ReadOnlyCollection<string> MemberNames { get; }
        }
    }
    ```

    Example usage of the attribute would be:
    
    ```
    public class Order
    {
        [NewExpressionMembers(nameof(Id), nameof(OrderedAt), nameof(Total))]
        public Order(int id, DateTime orderedAt, decimal total)
        {
            Id = id;
            OrderedAt = orderedAt;
            Total = total;
        }
        
        public int Id { get; }
        
        public DateTime OrderedAt { get; }
        
        public decimal Total { get; }
    }
    ```
    
    Then whenever the compiler is going to emit the construction of a `NewExpression`, it would look for a `NewExpressionMembersAttribute` on the constructor. If found, it would attempt to resolve a list of members matching the given names according to the types of the constructor's parameters. If this resolution is successful, the `NewExpression` that is emitted will have its `Members` populated with the resolved members.
    
2. Automatic placement of a `NewExpressionMembersAttribute` based on code flow analysis. When compiling a constructor that

   - does not already have a `NewExpressionMembersAttribute` defined on it and
   - has parameters,
    
   the compiler should perform a code flow analysis to determine whether each of the parameters are taken for the value of exactly one public property or field, or else exactly one private property or field, of the constructed type. For instance, the `Order` class defined above could easily have the `NewExpressionMembersAttribute` generated by the compiler.
   
   In this example, one of the right-hand expressions of an assignment coalesces to throw an `ArgumentNullException`, but the compiler should be able to resolve it and add `[NewExpressionMembersAttribute(new[] { "Bar" })]`:
   
    ```
    public class Foo
    {
        public Foo(string bar)
        {
            Bar = bar ?? throw new ArgumentNullException(nameof(bar));
        }
        
        public string Bar { get; }
    }
    ```
    
   In this example, the parameter is assigned directly to a field, but that field is ultimately taken for the return value of a single property, so the compiler should resolve that property and add `[NewExpressionMembersAttribute(new[] { "Bar" })]`:
   
    ```
    public class Foo
    {
        private string bar;

        public Foo(string bar)
        {
            this.bar = bar ?? throw new ArgumentNullException(nameof(bar));
        }
        
        public string Bar
        {
            get => bar;
            set => bar = value ?? throw new ArgumentNullException(nameof(bar));
        }
    }
    ```
    
    If the general idea of this proposed feature is supported, there would of course need to be a more rigorous specification with more examples.

**Comment by Joe4evr** [comment]
I'm not sure what you're asking for, but from the title it sounds like it should be covered by Target-typed `new` #100, which also doesn't require any attributes to be added to existing codebases.

**Comment by tuespetre** [comment]
@Joe4evr this is to do with `System.Linq.Expressions.NewExpression`. 

When the compiler emits an expression tree for `from x in xs.AsQueryable() select new { x }`, the `new { x }` part becomes `Expression.New(anonymousTypeConstructor, new[] { parameterExpression_x }, new[] { anonymousTypeMember_x })` whereas when the compiler emits an expression tree for `from x in xs.AsQueryable() select new Foo(x)`, the `new Foo(x)` part becomes `Expression.New(fooConstructor, new[] { parameterExpression_x })`. This proposal would allow that to possibly become `Expression.New(fooConstructor, new[] { parameterExpression_x }, new[] { fooMember_X })`.

So then, when that query is composed upon, like `from foo in foos where foo.X == 12321 select foo`, and the query provider goes to interpret the expression tree, it could see the member access to `foo.X`, trace `foo` back to `new Foo(x)`, see that `X` corresponds to the `x` argument of the constructor, and trace `x` back to its source to obtain further metadata that would be useful for processing the query.

**Comment by HaloFour** [comment]
@tuespetre 

IIRC that's only possible with anonymous types because the compiler completely controls their shape and can make the correlation between the constructor arguments and the members.  For any other data type there is no such correlation.  That might be somewhat different with records as the compiler can control their shape as well, to a point, but only with the primary constructor.

**Comment by HaloFour** [comment]
@tuespetre 

Gotcha.  So, in the following case:

```cs
public class Foo {
    private readonly string bar;
    private readonly string baz;

    public Foo(string bar, string baz) {
        this.Bar = bar;
        this.Baz = baz;
    }

    public string Bar { get => this.bar; }
    public string Baz { get => this.baz; }
}
```

The compiler would recognize that:

1. The properties `Bar` and `Baz` only return the value contained in the fields `bar` and `baz` without modification.
1. The constructor assigns the fields `bar` and `baz` based on the constructor arguments `bar` and `baz` without modification.

Thus would automatically annotate the constructor parameters with the `NewExpressionMembersAttribute` attribute as follows:

```cs
public class Foo {
    private readonly string bar;
    private readonly string baz;

    [NewExpressionMembers("bar", "baz")]
    public Foo(string bar, string baz) {
        this.Bar = bar;
        this.Baz = baz;
    }

    public string Bar { get => this.bar; }
    public string Baz { get => this.baz; }
}
```

I'd be worried that such a thing would be quite fragile.  How flexible can the compiler be when determining the flow of these constructor arguments through to these properties?

**Comment by HaloFour** [comment]
@tuespetre 

>  The one thing I would change in your example is that the compiler should be able to resolve the public properties `Bar` and `Baz` rather than the private fields.

Oops, I meant to do that.

> it should be able to determine whether there is a unique assignment relationship between a parameter and a field.

Between a parameter and a field, and then from a field to the return value from a property.  But would that hold true if the field isn't `readonly` or if the property is writable?  What happens if that value is passed to any arbitrary method along the way?  What about multiple constructors that invoke each other and don't individually assign the fields?

**Comment by CyrusNajmabadi** [comment]
> Using the CSharpDataFlowAnalysis and related classes, it should be able to determine whether there is a unique assignment relationship between a parameter and a member.

This can only be done if you have the source for something.  The compiler has to run against symbols pulled in from metadata where it can make no such validation.

**Comment by tuespetre** [comment]
@CyrusNajmabadi that is correct. That determination or analysis to which I am referring happens while compiling the constructor itself from source. And say the compiler is compiling a constructor which invokes a `base` constructor for which only symbols are present -- if the `base` constructor has the attribute defined on it, that could be used, otherwise, no cigar.

**Comment by CyrusNajmabadi** [comment]
>  That determination or analysis to which I am referring happens while compiling the constructor itself from source.

That analysis would then have to happen in every compiler.  there is nothing stopping anyone from compiling in any language (including a previous version of C#) and creating this constructor with this attribute on it.

**Comment by tuespetre** [comment]
> That analysis would then have to happen in every compiler. 

Why? Either you compile with a supporting version of the compiler that performs the analysis and inserts the attributes automatically, manually add the attributes if you can't use a newer version but still want to give consumers the benefits, or do nothing and nobody will be out anything that they have already today. Isn't that kind of like we have going on with `ExtensionAttribute`?

> there is nothing stopping anyone from compiling in any language (including a previous version of C#) and creating this constructor with this attribute on it.

I'm not sure what you are saying here. Are you saying that if someone did that, it would be bad, or...?

**Comment by tuespetre** [comment]
I disown this proposal 😅
