### ISSUE TITLE
Discussion: implicit cast from dynamic to anonymous interface wrapper

### ISSUE THREAD

**Issue by GlassGrass** [dotnet/csharplang#1483]
In dynamic typing paradigm, the object which has signature-matched members behaves as equality to interface implementation even though without explicit declaration.
Therefore, I propose a mechanism which regards dynamic object as interface implementation in a specific case.

For example, following code:

```C#
using System;

public interface ISomeInterface
{
    string SomeMethod(int a, int b);
}

public class SomeClass
{
    public void Foo(dynamic dynamicArg)
    {
        Bar(dynamicArg);
    }
    
    public void Bar(ISomeInterface arg)
    {
    }
}
```

will be converted to:

```C#
using System;

public interface ISomeInterface
{
    string SomeMethod(int a, int b);
}

public class SomeClass
{
    public void Foo(dynamic dynamicArg)
    {
        Bar(dynamicArg as ISomeInterface
            ?? new __AnonymousSomeInterfaceWrapper(dynamicArg));
    }
    
    public void Bar(ISomeInterface arg)
    {
    }
}

public class __AnonymousSomeInterfaceWrapper : ISomeInterface
{
    private readonly dynamic _entity;
    
    internal __AnonymousSomeInterfaceWrapper(dynamic entity)
        => _entity = entity;
    
    public string SomeMethod(int a, int b)
        => _entity.SomeMethod(a, b);
}
```

This translation will be applied to only assignment between dynamic-typed and interface-typed variables.

**Comment by bondsbw** [comment]
This would change existing behavior.  Granted, it changes a `RuntimeBinderException` into working code and I doubt there are many who rely on that exception who would be negatively affected.

**Comment by HaloFour** [comment]
"Working" up until the point that trying to invoke a member on the interface throws because the member doesn't actually exist on the dynamic instance.  Granted you can do this today by writing your own wrapper, but I don't like the idea of dynamic types implicitly leaking back into what should be type-safe code.  It also means that every `dynamic` that exists automagickally "implement" all marker interfaces.

**Comment by bondsbw** [comment]
And the use cases are probably already covered by existing proposals:

- Shapes (#164)
- Constraints on dynamic (#284)
