### ISSUE TITLE
'var' instead of a method return type

### ISSUE THREAD

**Issue by antrv** [dotnet/csharplang#1484]
Allow this construction
```
public var GetDictionary()
{
      return new Dictionary<string, (int, int)>();
}

```
instead of this
```
public Dictionary<string, (int, int)> GetDictionary()
{
      return new Dictionary<string, (int, int)>();
}
```
The rules of type inference with the case of multiple return statements can be the same as for creating array for example.

**Comment by svick** [comment]
Related: *var return for local functions* https://github.com/dotnet/csharplang/issues/943.

**Comment by jnm2** [comment]
This would make it harder to notice when you introduce breaking changes to a public API since the public API would be determined by an implementation detail of the method (returning a more or less specific or implicitly convertible type). We need the practice of locking in the API spec in the signature.

If this was ever added, I hope it would ship with warnings or errors out of the box when used in public signatures.

**Comment by sharwell** [comment]
Currently it's possible to bind everything in a compilation unit using only the information in that compilation unit plus the _signatures_ of everything in other compilation units. Exposing an inferred type across compilation unit boundaries has the potential to tremendously degrade overall performance.

I lean against requests like this at least until we reach a point of high assurance that the developer experience will not be negatively impacted by attempting to provide the feature.

> This would make it harder to notice when you introduce breaking changes to a public API since the public API would be determined by an implementation detail of the method (returning a more or less specific or implicitly convertible type). We need the practice of locking in the API spec in the signature.

This is only a concern for a subset of development situations, and possibly even a minority. Providing a stable public API incurs a non-trivial cost to the developer, and this cost should be pay-to-play (i.e. developers not attempting to provide a stable API should not be forced to deal with that overhead).

**Comment by HaloFour** [comment]
I'm with @jnm2, the signature is the most important part of a method, so much more so than the actual implementation.  Depending on the logic the compiler would have to use in order to derive that return type you could accidentally shift the signature of an API thus breaking all consumers.

I think that target-typed `new` expressions would largely alleviate the concerns around verbosity as you don't have to repeat yourself in the signature and in the creation of the return value:

```cs
public Dictionary<string, (int, int)> GetDictionary()
{
      return new();
}
```

**Comment by jnm2** [comment]
@sharwell 

> This is only a concern for a subset of development situations, and possibly even a minority. Providing a stable public API incurs a non-trivial cost to the developer, and this cost should be pay-to-play (i.e. developers not attempting to provide a stable API should not be forced to deal with that overhead).

This is a really good point. But even within codebases which don't need to maintain a stable API: to the extent which it feels painful to put `Dictionary<string, (int, int)>` in a signature, it's a good thing that it feels painful. The pain pushes you toward a pit of success.

**Comment by theunrepentantgeek** [comment]
> This is only a concern for a subset of development situations, and possibly even a minority. 

I disagree. Every non-trivial application I've worked on has been segmented into multiple layers where each layer provides a *public API* consumed by the layer above. (I'm thinking of systems as small as 2 kloc and as large as 1000 kloc and everywhere in between.)

Even when the API is never consumed outside of one specific application, stability is important - having part of a persistence layer API spontaneously change from `List<TimeSeries>` to `IList<TimeSeries>` would be a serious breaking change.

**Comment by bondsbw** [comment]
Agreed with @jnm2 about the API risk and with @svick / @DavidArno that local functions make more sense.

I might also entertain `private var` methods.  (Performance issues aside.)

**Comment by gulshan** [comment]
I thin my proposal #265 was the narrowest in the scope in this regard of type inference.

**Comment by gafter** [comment]
For the reasons discussed here, and also due to possible difficulties inferring the type when there are mutually recursive methods, we are never going to do this.

**Comment by ymassad** [comment]
@gafter , is this feature never going to be implemented even for private methods? Or is this a different proposal?

If inferred return type is to be implemented for local functions, why not do it also for private methods? Is there any difference?

**Comment by gafter** [comment]
We have no plans to implement return type inference for local functions or private methods.
