### ISSUE TITLE
Specify query expression translations algorithmically

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/csharplang#1486]
I'm reading section **Query expression translation** of the C# language [specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#query-expressions), since I need to write such a translator - note that Roslyn doesn't perform this exact translation, it [binds certain symbols directly](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Binder_Query.cs) from the query expression (otherwise, I'd borrow its code). The approach of describing the **syntactical** translations on a *per example* basis is unsatisfactory, both because it requires unnecessary knowledge of the semantic of the queries and because it, by definition, isn't a thorough description. Please, consider providing the translation steps on **algorithmic basis** (ideally, in a functional style).

**Comment by CyrusNajmabadi** [comment]
> it requires unnecessary knowledge of the semantic of the queries 

It does not.  From the languages perspective there is zero knowledge of semantics necessary here.

> and because it, by definition, isn't a thorough description. 

How is it not thorough? Each query form gets a precise description of hte translation.  For example:

```
A query expression with a continuation

from ... into x ...

is translated into

from x in ( from ... ) ...
```

> Please, consider providing the translation steps on algorithmic basis (ideally, in a functional style).

Can you give an example of what you mean?    The above description states exactly what happens.  The spec already says that if you have a query with a continuation exactly how it should be translated.  The only potential point where there may need to be clarity is where the placeholders go.  i.e. it's inferred in the above that each specific ```...``` section goes into the respect forward ordered section in the result.  Technically that isn't totally clear, but it's very minor.

**Comment by CyrusNajmabadi** [comment]
> Note that Roslyn doesn't perform this exact translation, it binds certain symbols directly from the query expression (otherwise, I'd borrow its code).

Yes.  THe language simply specifies how the language works, the implementatoin is free to do whatever it wants to accomplish that as long as the language rules are met and thus no deviations can be observed by the user.  That's what is happening here.  The compiler is simply folding two steps into one.  It since it knows how to syntactically translate the code, and then it knows how to 'bind' that translation, it can just do both steps as one to save on cost.

**Comment by ltcmelo** [comment]
Hi @CyrusNajmabadi, I appreciate that you're always giving feedback on my tickets!

Let me try to clarify:

> From the languages perspective there is zero knowledge of semantics

Yes. Perhaps my sentence wasn't accurate and a bit abused (when I said "required"). I'm not saying semantics of the language, but the understanding of usual behavior of "queries". Let's say that you replaced the names `GroupBy`, `Select`, `from`, etc. from that description and, still, you'd like to document such a syntactic translation process through examples, as it mostly is right now. While it'd still be possible, for the *reader* it'd be harder to follow.


> The above description states exactly what happens

The fact that a description states what happens doesn't necessarily mean that such description is algorithmic. I can tell you that I have a function `sort` and that, after it's invoked with the items `{ 5, 9, 2 }`, the result will be `{ 2, 5, 9 }`. Yet, I told you nothing about the algorithm used for the actual sorting procedure.

A practical example: In certain parts of that specification you have something like below.

"**from x in e select v** *is translated into* **( e ) . Select ( x => v )**"

I can immediate create an algorithm for this translation and give it to you in a clear mathematical notation using [inference rules](https://en.wikipedia.org/wiki/Rule_of_inference).

```
from x in e select v    (v != x)
------------------------------
( e ) . Select ( x => v )
```

For this little part I could "buy it" that you description is algorithmic. But the translation is more complex than that. In particular, your description doesn't tell me how to take a big arbitrary query expression, apply a sequence of steps (e.g., like the one I mention above), and arrive at the final translation - you only have certain parts in between. Maybe, a person who's experience with C# can connect the dots easily, but that's implied by the specification.

While, one would still be able to write their own algorithm, at the least the language spec would provide a *reference* implementation.


> How is it not thorough? Each query form gets a precise description of hte translation

Not, it doesn't. *Each* query you *used* as an example gets a precise description.


>  The language simply specifies how the language works, the implementatoin is free to do whatever it wants

I'm fine with this. I only brought this up because I wanted to explain why I manually writing this translation, in case someone just appears and say something like "look at the way Roslyn does".
 
Back to my original post, I asked you to *consider* an algorithmic description. In my opinion, it'd make the language spec more elegant and readable.

**Comment by gafter** [comment]
@ltcmelo Can we close this issue?

**Comment by ltcmelo** [comment]
Sure.

Em sex, 27 de abr de 2018 19:55, Neal Gafter <notifications@github.com>
escreveu:
