### ISSUE TITLE
what difference between system level and application level exception ?

### ISSUE THREAD

**Issue by Newbe36524** [dotnet/csharplang#1488]
Exceptions in C# provide a structured, uniform, and type-safe way of handling both system level and application level error conditions. 

So, what difference between system level and application level exception ?

Can I make username-or-password-error into a exception like UsernameOrPasswordException ?

**Comment by stuartstein777** [comment]
You can create your own exception.

See https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions

**Comment by jnm2** [comment]
It sounds like the question is about https://msdn.microsoft.com/library/system.systemexception.aspx vs https://msdn.microsoft.com/library/system.applicationexception.aspx.

**Comment by yaakov-h** [comment]
FWIW, `ApplicationException` was removed completely in .NET Core 1.x and was added back in for .NET Standard 2.0... I assume for code portability or runtime compatibility? There's not much discussion on https://github.com/dotnet/corefx/issues/9854.

There's also a [fourth constructor](https://msdn.microsoft.com/en-us/library/tz6bzkbf(v=vs.110).aspx) that you should implement in Framework code in order for exceptions with custom data to correctly traverse Remoting/AppDomains, AFAIK.

**Comment by Newbe36524** [comment]
@stuartstein777 @jnm2 @theunrepentantgeek @yaakov-h 
Thank you for replay.

I noticed "Exceptions in C# provide a structured, uniform, and type-safe way of handling both system level and application level error conditions."  in https://github.com/dotnet/csharplang/blob/master/spec/exceptions.md.

So I have a question about what difference between system level and application level exception. And all about replays has explained it.

ApplicationException and SystemException are  just two kind of Exception built in Framework , I think now.

**My real question is : Using exception to change bussness flow can be a good practice and it is Exception design for ? (I think business error is application exception)**

---

For example,I have two bank account and I have to enter my password on ATM to transfer some money from my bank account to the other.

in C# ,I coded.

~~~csharp

public interface ITransfer
{
    /// <summary>
    /// transfer some money from account a to account b
    /// </summary>
    /// <param name="fromAccount"></param>
    /// <param name="toAccount"></param>
    /// <param name="amount"></param>
    /// <param name="password"></param>
    /// <returns>transfer success time</returns>
    /// <exception cref="PasswordErrorException"> password error </exception>
    /// <exception cref="AccountUnavailableException"> account navailable</exception>
    DateTimeOffset Transfer(string fromAccount, string toAccount, decimal amount, string password);

}

public class PasswordErrorException : BusinessException
{
}

public class AccountUnavailableException : BusinessException
{
}

public class BusinessException : Exception
{
}

~~~

However, My partner says:" Exception is not designed for changing bussness flow, and it is just designed for raising same unexcepted problem like OutofMemoryException".

My partner code this :

~~~csharp

public interface ITransfer
{
    /// <summary>
    ///
    /// </summary>
    /// <param name="fromAccount"></param>
    /// <param name="toAccount"></param>
    /// <param name="amount"></param>
    /// <param name="password"></param>
    /// <returns>transfer success time</returns>
    Result<DateTimeOffset> Transfer(string fromAccount, string toAccount, decimal amount, string password);

}

public struct Result<T>
{
    public T Value { get; set; }
    /// <summary>
    /// 001 for password Error
    /// 002 for account navailable
    /// </summary>
    public int Code { get; set; }
    public bool IsOk { get; set; }
    public string Message { get; set; }
}

~~~

---

**I think it should be explain in C# guidance, let`s dicuss it.**

**Comment by jnm2** [comment]
Exceptions are for exceptional situations such as detection of programming errors. They are not good for ordinary control flow.

**Comment by orthoxerox** [comment]
I have a feeling we're reading somebody's homework assignment.

**Comment by Newbe36524** [comment]
@jnm2 There will be many if-else to ensure each step is ok . is there any better practise?

--- 

@orthoxerox I`m looking for better choice to deal with busniness error. My partner using Result<T> to indicate operation result inspired by Golang, I perfer using Exception as Java.

We now working on some online shop project with orleans which implementing the Virtual Actor Model。

I am confused which one is better choice, or any other choice

**Comment by HaloFour** [comment]
Either way, this is not the venue for this question.  This repository is specific to questions regarding the C# language specification and its evolution.  I would suggest https://stackoverflow.com/ for general programming questions and best practices.

**Comment by yaakov-h** [comment]
IIRC, Exceptions are heaps cheaper in Java than in C#.

Personally, I’d have an authentication function that takes care of accounts and passwords, then a separate function for balance transfer that’s only available on an authenticated account object. 

We’re not here to mediate your own internal dispute, however:

* Exceptions should not be used for issues that are expected or can be a regular occurrence, such as invalid passwords.
* I personally don’t like much of that Result<> object, it looks like an abomination derived from Optional<> or Either<,>. In particular, that int error code looks like a type safety bug just waiting to happen.

**Comment by Newbe36524** [comment]
Thank you very much, and I closed this issue because the question has be solved witch I ask in title of this issue.

---

I Found a post about "Best practices for exceptions" post at https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#throw-exceptions-instead-of-returning-an-error-code.

I will go dotnet/docs repo to discuss my question.
