### ISSUE TITLE
Is this a bug in the specification of query translations?

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/csharplang#1490]
Is this a bug in the specification of the [query expressions' translation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#query-expressions)?

  - Rule A: `from T x in e` is translated into `from x in ( e ) . Cast < T > ( )`
  - Rule B: `from x in e where f ... ` is translated into `from x in ( e ) . Where ( x => f ) ...`
  - Rule C: `from x in e select x` is translated into `( e ) . Select ( x => x )`

Now, consider the input, available as an example: 
`from Customer c in customers where c.City == "London" select c`

How I'd *resolve* that expression.

  1) After applying rule A, for ranged types:
    `from c in customers.Cast<Customer>() where c.City == "London" select c`

  2) After applying rule B, for where clauses:
   `from c in customers.Cast<Customer>().Where(c => c.City == "London") select c`

  3) After applying rule C, the degenerate case: 
   `customers.Cast<Customer>().Where(c => c.City == "London").Select(c => c)`

However, the final translation as according to the spec is the one below - note that it doesn't contain the final `Select`:
`customers.Cast<Customer>().Where(c => c.City == "London")`

**Comment by ltcmelo** [comment]
> There's a separate rule for the degenerate case of selecting the query variable directly.

Which rule is this one?

**Comment by CyrusNajmabadi** [comment]
The degenerate cases is only for when the query starts out in that form.

**Comment by ltcmelo** [comment]
> The degenerate cases is only for when the query starts out in that form.

Are you that the degenerate case doesn't apply on queries resulting from transformations?

If so, I can't find such restriction in the spec. Am I missing it?

**Comment by ltcmelo** [comment]
OK, after your update on the post, I identify it. Thanks!

Would be worth to make that statement clearer, though...

**Comment by CyrusNajmabadi** [comment]
Glad this helped!
