### ISSUE TITLE
Infer the type of collection elements 

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1492]
C# can't infer the type of the elements of many collections, for example:

```
var rgx = new Regex("Some Regex");
foreach (var m in rgx.Matches("Some Text")
{

}
```

m will be an object, will Matches collection contains elements of type Match.
Can c# do anything about this, or these collections should be rewritten in CorFx as generic-type?
One thought: can these collections marked with some attribute (i.e. ElementTypeArribute) that shows its element type, so the compiler can correctly infer the type?

**Comment by CyrusNajmabadi** [comment]
```
var rgx = new Regex("Some Regex");
foreach (Match m in rgx.Matches("Some Text")
{

}
```

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
hhhh.
I know I can use a direct type instead of the var, but I got used to the var keyword, and I get frustrated evey time when I find no elements in the auto-complete list, and go back to write the exacy type!

> Sure. Please file such a suggestion in corefx.
It can break some existing code, that uses variables of type MatchCollection and such collections!
This is why I mentioned the ElementTypeArribute, not to break any code, but it will need the to be used by the compiler. So, is C# OK with ElementTypeArribute?

**Comment by CyrusNajmabadi** [comment]
> This is why I mentioned the ElementTypeArribute, not to break any code, but it will need the to be used by the compiler
If it's used by the compiler, why will code not be broken?

**Comment by MohammadHamdyGhanem** [comment]
Nothing will change in existing projects code, nor the .net classes. Only compilers will use the attribute to know the elements type.

**Comment by yaakov-h** [comment]
> m will be an object, will Matches collection contains elements of type Match.

`m` is a [`MatchCollection`](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.matchcollection(v=vs.110).aspx) object, which only implements `IEnumerable`, not `IEnumerable<Match>`.

Is there any reason that corefx could not simply add this interface to the class? I don't see how it would break existing code.

Or, if it would break existing code, could that become un-broken with #52 (DIM)?

**Comment by ufcpp** [comment]
@yaakov-h 
https://github.com/dotnet/corefx/pull/27532#issuecomment-369283194

**Comment by yaakov-h** [comment]
Oh I see, it's the primary `GetEnumerator()` method...

**Comment by DavidArno** [comment]
Surely that issue could be worked around with a simple nuget package that contained simple extension methods eg:
```cs
IEnumerable<Match> AsTypedEnumeration(this MatchCollection collection)
{
    foreach (Match item in collection)
    {
        yield item;
    }
}
```

then the following at least becomes possible:
```cs
foreach (var m in rgx.Matches("Some Text").AsTypedEnumeration())
{
    // m is a Match here, not object
```

I'd be surprised if such a package doesn't already exist. I'll have to write one if not.

**Comment by svick** [comment]
@DavidArno In .Net Core 2.0, `MatchCollection` implements `IEnumerable<Match>`, so the method you're talking about already exists: [`AsEnumerable()`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.asenumerable?view=netcore-2.0). Though calling it is still necessary, because `GetEnumerable()` still returns non-generic `IEnumerator` (presumably for backwards compatibility). And of course, your `AsTypedEnumeration()` would still be useful on other frameworks.

**Comment by MohammadHamdyGhanem** [comment]
@DavidArno 
Nice idea, but it make the code longer. var meant to make the code shorter and easier (write var and don't think of any returned type!)
I see that adding a ElementTypeArribute and mark each object collection with it will be the best solution,

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

That would subtly change the behavior of existing code.  These situations should be increasingly rare these days since it only really comes up when interacting with pre-.NET 2.0 types that return non-generic collections.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
Using an attribute to mark object collection with a specific element type will not change the behavior of existing code. If you disagree, please provide an example.

**Comment by MohammadHamdyGhanem** [comment]
@svick 
Who would use something like that?
You can expect that the existing code doesn't use var with object collections, but use the known type like Match.
I think the term "break existing code" means professional long running apps, not some beginners testing projects.

**Comment by DavidArno** [comment]
@MohammadHamdyGhanem,

"break existing code" refers to any theoretically possible existing code. The team take that statement seriously.

**Comment by svick** [comment]
@MohammadHamdyGhanem 

> I think the term "break existing code" means professional long running apps, not some beginners testing projects.

Keep in mind that there are millions of lines of professional code out there. Whatever coding pattern you can think of, someone somewhere probably used it.

Sure, my specific code doesn't make much sense, but that doesn't mean much. If you want to propose a breaking change (and you are doing that), you would need really good arguments why the break is worthwhile and that it won't actually break too many people. (And even that might not be enough.)

**Comment by MohammadHamdyGhanem** [comment]
Correct me here:
If this breaking change happened, the already running apps targets older frameworks and will not be affected by the change. 
But in VS.NET, if an old project upgraded to the newer version, some problems might happen. I think this can be solved easily in many cases (not just this proposal) by raising compiler warnings, or some options to let the user choose the desirable behavior. 
C# can check the code file creation date and if it is past the day of the new feature release, it treats it with as were in the past, with some options to change this behavior.> something like:
-	Apply [new feature] on projects created after [date]
-	Apply [new feature] on all projects.
-	Disable [new feature].
This can allow you to implement as new breaking features as you want, but isolate it from old projects! Otherwise, all the past mistakes will last forever!

**Comment by CyrusNajmabadi** [comment]
> C# can check the code file creation date and if it is past the day of the new feature release

I can't imagine this ever happening.  It would be completely bonkers for many people.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
please read carefully:

> this can be solved easily in many cases (not just this proposal)

**Comment by CyrusNajmabadi** [comment]
I don't see how that affects anything i said.

**Comment by MohammadHamdyGhanem** [comment]
I saw "this would be a breaking change" kill very good ideas countless times. 
In my opinion, a warring about the breaking change, is enough. I can choose to compile to older framework, or accept the breaking code and fix the compiler errors.
Otherwise, you can create two releases of each new version: a conservative one, and a breaking one :D, so we can use the new fashion in new projects, and keep old ones safe and sound!

**Comment by CyrusNajmabadi** [comment]
> In my opinion, a warring about the breaking change, is enough

The team disagrees.  

> . I can choose to compile to older framework, or accept the breaking code and fix the compiler errors.

What you can do is not relevant to the discussion.  Breaking changes impact the entire community.  An individual's acceptance of that problem for their own code isn't relevant.

> Otherwise, you can create two releases of each new version: a conservative one, and a breaking one

The team has stated many times it does not want the language forking or creating new dialects unless it is massively valuable to do so.

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem You are free to make these suggestions.  Just know that making suggestions that go against the intentions the team has stated countless times will not get you anywhere.  It's the github equivalent of tilting at windmills. 

If you want your suggestions taken seriously, please restate them within the boundaries of what the team feels are acceptable changes, otherwise they'll just get ignored/closed.

**Comment by CyrusNajmabadi** [comment]
> I saw "this would be a breaking change" kill very good ideas countless times.

By the teams definition they are not "good ideas" if their virtues cannot outweigh the awfulness of them breaking people.

Again, as i mentioned, there are ways to accomplish what you want without insisting that the rest of hte ecosystem be broken.  You can write your own analyzer that flags this and fixes it for you.  this would allow you the behavior where the language has effectively changed, but without forcing others into that change.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Is it "the entire community" or just "what the team feels are acceptable changes"?
How can the team know what the community wants in we don't say it individually?
Individual openions can add up at some point. I myself have a problem with writting code in two different fashions, and as I said before, little repeated things can be irritating, like the unexpected var meaning.
Thanks for your advise anyway.

**Comment by CyrusNajmabadi** [comment]
If you want, feel free to go to https://gitter.im/dotnet/roslyn and we can discuss things more.  I don't think there's any value in this discussion here.

**Comment by jnm2** [comment]
^ I've had these exact same thoughts.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

Not going to happen.  Breaking all existing apps that use these classes is not an option, period.

**Comment by MohammadHamdyGhanem** [comment]
It can be made as Nugets, so anyone wants to use the modern classes download them.

**Comment by CyrusNajmabadi** [comment]
And people who want to use modern classes and not be broken?

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem If you do feel passionate about this, it would be good if those efforts and energies could be funneled into https://github.com/dotnet/roslyn/issues/26655.

**Comment by MohammadHamdyGhanem** [comment]
> And people who want to use modern classes and not be broken?

Not sure I get your meaning here?
if it's old project, don't use the GenCollections Nuget. 
If it's new project, use the GenCollections Nuget.

Also, both can be mixed if the Nuget uses a new namespace. This is a brain storm and I can't tell big will this Nuget be.

**Comment by CyrusNajmabadi** [comment]
You're talking about a hard fork of all of these v1 types.  That's not likely to happen at all.

**Comment by Thaina** [comment]
```C#
foreach (var m in rgx.Matches("Some Text").OfType<Match>())
{
}
```

This will also filter null out

**Comment by jnm2** [comment]
@Thaina Does `Matches` ever yield a null element?

**Comment by Thaina** [comment]
@jnm2 I don't know I never use Regex. `OfType` just generally filter only object of that type

**Comment by Thaina** [comment]
@jnm2 In that case I think `rgx.Matches("Some Text").Cast<Match>()` might be yours preference

**Comment by jnm2** [comment]
@Thaina It is! Or using `Match` instead of `var` if it's in a foreach loop.
