### ISSUE TITLE
New keyword "singleton"

### ISSUE THREAD

**Issue by puppets2666** [dotnet/csharplang#1500]
Add a new keyword for easy implementation Singleton pattern. The method GetInstance is generated automatically.

singleton class S{ }
S s = S.GetInstance();

**Comment by svick** [comment]
Why is the singleton pattern something that should be promoted by the language? Especially considering that this is going to save you only a few lines of code, it doesn't seem worth it to me.

**Comment by puppets2666** [comment]
Because it used often, C# looks friendly to patterns with all his interfaces andevent, and almost all new features about saving a few lines.

**Comment by d-dizhevsky** [comment]
How do I choose whether it is going to be a thread-safe singleton or not? What if I need to add custom things to it? 
IMHO it won’t be any useful as a language-level feature
