### ISSUE TITLE
Discussion:  call instead of callvirt for structs with no calls to "base" operations

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#1503]
When working with structs the compiler generates either a "call" MSIL operation or "constrained + callvirt" MSIL operations. However, in same cases, the latter is then executed by the CLR as direct "call", instead. And in others, a hidden boxing occurs after dereferencing. Wouldn't be possible for callvirt that are executed as calls to be compile as such, so as to clearly state how they will be in fact executed by the CLR?

--------------------------------------------
First case:
--------------------------------------------
```
int i = 1;
var text = i.ToString();
```
In this case, Roslyn seems to know, exactly, the method to call, emits the following MSIL code:
```
...
call instance string [mscorlib]System.Int32::ToString()
```

Now, for custom structs things change ...

--------------------------------------------
Second case:
--------------------------------------------
```
public struct MyStructA{}
...
MyStructA a = default;
var text = a.ToString();
```
The resulting MSIL code is:
```
...
constrained. MyStructA
callvirt instance string [mscorlib]System.Object::ToString()
```
If I understand it correctly, here the CLR will produce a hidden boxing of the dereferenced type in order to call the method on the base type.  The boxing is not explicit in the code, but can be inferred from the behaviour of "constrained".

--------------------------------------------
Third case:
--------------------------------------------
```
public struct MyStructB
{
    public override string ToString() => return "Text: " + base.ToString();
}
...
MyStructB b = default;
var text = b.ToString(); 
```
The resulting MSIL code is:
```
constrained. MyStructB
callvirt instance string [mscorlib]System.Object::ToString()
```
Although ToString is declared as an overridden operation on MyStructB, since it calls the base method, the CLR behaves as in the second case, then boxing the type before the virtual call.

--------------------------------------------
Fourth case:
--------------------------------------------
```
public struct MyStructC
{
    public override string ToString() => return "My custom text";
}
... 
MyStructC c = default;
var text = c.ToString();
```
Contrary to what I was expecting, the resulting MSIL code is again:
```
constrained. MyStructC
callvirt instance string [mscorlib]System.Object::ToString()
```
However, the CLR here executes a direct call since not only does MyStructC override ToString but also it implements the method without calls to member of the "base" class.

--------------------------------------------
Fifth case:
--------------------------------------------
```
public interface IDoSomething
{
	void DoSomething(); 
}
...
public struct MyStructD : IDoSomething
{
    public void DoSomething(){}
}
...
MyStructD d1 = default;
d1.DoSomething();
```
Here the produced code is what I should have expected for the previous case:

```call instance void MyStructD::DoSomething()```

--------------------------------------------
Final case:
--------------------------------------------
```
public static void DoSomething<T>(T myStruct)
        where T: struct, IDoSomething
{
    	myStruct.DoSomething();
}
```
The MSIL code generated for this static operation is:
```
...
ldarga.s myStruct
constrained. !!T
callvirt instance void IDoSomething::DoSomething()
ret
...
```
Again, although the compiler generates "constrained + callvirt" MSIL operations, for the given example the CLR performs a direct "call", instead. But, there is no way to enforce a similar behavior to all value types that implement IDoSomething given that some of them might be calling "base" operations. 

--------------------------------------------

Thus, the discussion: 

a) for case 4, wouldn't be possible to generate a direct MSIL call instead of constrained + callvirt, instead?

b) for case 6, how about having a new generic constraint to help the compiler producing a direct call instead of a callvirt? Like, say, "sealed": `where T: sealed struct, IDoSomething`. This way, a compilation error would occur when a struct declares a method for DoSomething that produces a "hidden boxing" situation.

Thoughts welcome ...

**Comment by CyrusNajmabadi** [comment]
> a) for case 4, wouldn't be possible to generate a direct MSIL call instead of constrained + callvirt, instead?

Why would it matter?  All that's important is the end machine code the runtime actually generates here.  For any method call on a struct, it should be a a direct call (and will be inlined if the runtime deems it appropriate).

> b) for case 6, how about having a new generic constraint to help the compiler producing a direct call instead of a callvirt? Like, say, "sealed": where T: sealed struct, IDoSomething. This way, a compilation error would occur when a struct declares a method for DoSomething that produces a "hidden boxing" situation.

Same as above.  The relevant metric is what hte runtime produces here.  Fortunately, the runtime already generates specific code for struct instantiations of generics.  So, in these cases, when you actually call things it will actually transform this into a direct call (without "hidden boxing") for you, without needing any more info from the IL level.

**Comment by asyncawaitmvvm** [comment]
I completely agree with OP. I hate hidden boxing of structs for code that clearly should require no boxing.

**Comment by CyrusNajmabadi** [comment]
@asyncawaitmvvm can you give an example of hidden boxing in these cases?

**Comment by Ultrahead** [comment]
If the runtime produces direct calls, why not stating that on the MSIL and make it mandatory?

**Comment by CyrusNajmabadi** [comment]
"if it ain't broke"

**Comment by Ultrahead** [comment]
It ain't broke but it's not clear from the MSIL, and in my opinion it should. Leaving no room for "custom" behaviour to the runtime depending on the target system.

**Comment by CyrusNajmabadi** [comment]
it hasn't been a problem in the decade+ since generics were added, and since the dawn of the runtiem when we had structs/virt-calls.  I'm not sure there is any purpose redirecting resources to tackle something that has never been a problem :)

if it ain't broke.

**Comment by CyrusNajmabadi** [comment]
if you do think there's still an issue here, i would file it on the coreclr repo.  AFAICT, the roslyn compiler is behaving as per intentions with zero actual issues to be concerned about.  If CoreCLR believes this is an issue, they can decide if new IL patterns are needed and let Roslyn know.  The compilers can hten be updated accordingly.

**Comment by Ultrahead** [comment]
"If it ain't broke" does not seem to apply to other tasks that weren't issues in the first place for many, and yet, resources were assigned to tackle them. 

The issue here is that you have to infer the behaviour, say when analyzing perf issues, on a case-by-case basis since the result is not clear from MSIL.

**Comment by Ultrahead** [comment]
No, I believe this is a case for Roslyn and not CoreCLR.

**Comment by CyrusNajmabadi** [comment]
> The issue here is that you have to infer the behaviour

You'd have to infer it with a 'call' instruction anyways.  

> say when analyzing perf issues, on a case-by-case basis since the result is not clear from MSIL.

Why are you analyzing msil when doing anything perf related?  You could have a single IL instruction that could blow up to be incredibly slow, or you could have a ton of IL instructions that become no cost at all.  When measuring perf you should actually measure and direct your energies around what is actually costly for yoru scenarios.

> No, I believe this is a case for Roslyn and not CoreCLR.

The roslyn compiler is emitting code exactly as per what is expected.  It is following the rules of the language and emitting code that the runtime is 100% ok with.There is no need or want for Roslyn to do anything as long as the IL is defined as per the spec.  

If you want the language to actually change here, that's also not likely to change as that would be a language feature that involves a ton of energy to spec and implement which would have actually no effect on any programs and would simply be a more verbose way to say and accomplish what you already have gotten since C# 1.0.

**Comment by CyrusNajmabadi** [comment]
> b) for case 6, how about having a new generic constraint to help the compiler producing a direct call instead of a callvirt? Like, say, "sealed": where T: sealed struct, IDoSomething. This way, a compilation error would occur when a struct declares a method for DoSomething that produces a "hidden boxing" situation.

This is not correct, and is even called out by the docs:

> If thisType is a value type and thisType implements method then ptr is passed unmodified as the 'this' pointer to a **call  method instruction**, for the implementation of method by thisType.

There is no hidden boxing.  "constrained callvirt" on a value type which implements the method (which must be the case to satisfy the constraint and be verifiable), is spec'ed to behave exactly the same as a "call".

So there would be no benefit in the compiler making any sort of change here as the code it is already emitting has been required by teh spec to be the same as you want it to emit.

**Comment by CyrusNajmabadi** [comment]
> It ain't broke but it's not clear from the MSIL, and in my opinion it should

The spec makes it explicitly clear that these forms are equivalent and thus there would be no value in changing the C# language to change how things emitted when the existing emitting code is appropriate and gives you the equivalence you want.

**Comment by Ultrahead** [comment]
public struct TestStruct
{
   public void DoSomething() => this.ToString();
}

**Comment by CyrusNajmabadi** [comment]
?

**Comment by Ultrahead** [comment]
https://stackoverflow.com/questions/7995606/boxing-occurrence-in-c-sharp

**Comment by Ultrahead** [comment]
https://github.com/controlflow/resharper-heapview#resharper-heap-allocations-viewer-plugin

**Comment by CyrusNajmabadi** [comment]
I have addressed your points.  
The only suggestion i've seen to the c# language you provided was:

> b) for case 6, how about having a new generic constraint to help the compiler producing a direct call instead of a callvirt? Like, say, "sealed": where T: sealed struct, IDoSomething

I've explained why such a language change is not necessary given how the runtime is already spec'ed.

> a) for case 4, wouldn't be possible to generate a direct MSIL call instead of constrained + callvirt, instead?

This is not a language request.  There is nothing to change in the language here.  The language is unconcerned with MSIL.  it simply defines the semantics of the language and would require no change here.

**Comment by Ultrahead** [comment]
And I have provided an example of 6 where there is hidden boxing:

```
public struct TestStruct : IDoSomething
{
   public void DoSomething() => this.ToString();
}
```

**Comment by CyrusNajmabadi** [comment]
You have not proposed any language changes for that case.  What is it that you actually want changed in the language here?

**Comment by Ultrahead** [comment]
Yes, I have:

> b) for case 6, how about having a new generic constraint to help the compiler producing a direct call instead of a callvirt? Like, say, "sealed": where T: **sealed struct**, IDoSomething. This way, a compilation error would occur when a struct declares a method for DoSomething that produces a "hidden boxing" situation.

**Comment by CyrusNajmabadi** [comment]
That was for a *different* example.  One that had generics.  Your new code has no generics.  Where would you put that constraint in this code:

```c#
public struct TestStruct : IDoSomething
{
   public void DoSomething() => this.ToString();
}
```

?

**Comment by Ultrahead** [comment]
Use generics if you want, the CLR will perform a hidden boxing when dealing with TestStruct.

**Comment by CyrusNajmabadi** [comment]
> Use generics if you want, the CLR will perform a hidden boxing when dealing with TestStruct.

This is not true.  I already provided hte relevant details explaining that.

**Comment by Ultrahead** [comment]
And I have provided examples and links that it is.

**Comment by CyrusNajmabadi** [comment]
Please provide an example that demonstrates this.

**Comment by CyrusNajmabadi** [comment]
Again, Ultrahead, what is your actual langauge change suggestion.  You've only provided *one* suggestion (the "sealed" constraint).  I have explained why that is not necessary using the exact language of the CLR spec.  

You have asked about other cases (like just a normal struct) but have not actually specified what you want changed in the langauge about them.  So what is it you want?

**Comment by CyrusNajmabadi** [comment]
```c#
public struct TestStruct : IDoSomething
{
   public void DoSomething() => this.ToString();
}
```

This is not an actionable example.  You have not stated the problem here, and you have not given a suggestion on how you would like the language to change here.  

What change do you actually want in the language to address any perceived problems you feel exist in this example?  How would you *like* to write this?

**Comment by Ultrahead** [comment]
I already have provided examples (plus links with examples, including one from a well-known refactoring tool). Ditto for the lang change ("sealed"). If you want to disregard them and have the last word, be my guest.

**Comment by CyrusNajmabadi** [comment]
> I already have provided examples 

I'm asking: what do you want changed in the language wrt to *this* example:

```c#
public struct TestStruct : IDoSomething
{
   public void DoSomething() => this.ToString();
}
```

> If you want to disregard them and have the last word, be my guest.

This has nothing to do with getting in hte last word.  This has to do with getting clarity on what change you would actually like to see in the language that would change anything aobut this exact case yo have brought up.  As already demonstrated, and explained here (https://github.com/dotnet/csharplang/issues/1503#issuecomment-387278685), your suggested language change would have no effect on this case.

If your suggested language change would have no effect, i'm asking what *actual* language change you would have that would have an effect.

**Comment by CyrusNajmabadi** [comment]
> Ditto for the lang change ("sealed")

How would that have any effect?  As i already linked to, emitting a call would have no effect because the runtime has already stated *explicitly* that the constrained-callvirt in this scenario *is* just a ```call```.  Once again:   

> If thisType is a value type and thisType implements method then ptr is passed unmodified as the 'this' pointer to a call method instruction, for the implementation of method by thisType.

**Comment by ElTomato8** [comment]
> > b) for case 6, how about having a new generic constraint to help the compiler producing a direct call instead of a callvirt? Like, say, "sealed": where T: sealed struct, IDoSomething. This way, a compilation error would occur when a struct declares a method for DoSomething **that produces a "hidden boxing" situation.**
> 
> The bolded part is not correct, and is even called out by the docs:
> 
> > If thisType is a value type and thisType implements method then ptr is passed unmodified as the 'this' pointer to a **call  method instruction**, for the implementation of method by thisType.
> 
> There is no hidden boxing. "constrained callvirt" on a value type which implements the method (which must be the case to satisfy the constraint and be verifiable), is spec'ed to behave exactly the same as a "call".
> 
> So there would be no benefit in the compiler making any sort of change here as the code it is already emitting has been required by teh spec to be the same as you want it to emit.

Here is an example
https://mycodingplace.wordpress.com/2016/11/11/value-type-methods-call-callvirt-constrained-and-hidden-boxing/

>When a callvirt method instruction has been prefixed by constrained thisType, the instruction is executed as follows:

>If thisType is a value type and thisType implements method then ptr is passed unmodified as the ‘this’ pointer to a call method instruction, for the implementation of method by thisType.
If thisType is a value type and thisType does not implement method then ptr is dereferenced, boxed, and passed as the ‘this’ pointer to the callvirt method instruction. `

>then ptr is dereferenced, boxed `

Isnt it hidden boxing when constrained callvirt?

**Comment by 333fred** [comment]
I'm going to close this issue, as it is not relevant to the language and we cannot convert it to a discussion because of a GitHub bug (see all the closes and opens above). Feel free to open an issue on dotnet/roslyn if this is something you want to discuss further.
