### ISSUE TITLE
Proposal: "wrap" keyword for inheritance 

### ISSUE THREAD

**Issue by scneiashardevil** [dotnet/csharplang#1515]
A keyword that I think will help you build wraped classes:
Sample code:

```cs
// this class could be compile-time types instead (System.Array, System.String etc.)
// the sealed class or struct.
sealed class Foo // (or struct Foo)
{
    private int m_value; // not accessible

    public Foo(int value)
    {
        m_value = value;
    }

    public int Value { get => m_value; set => m_value = value; }

    public void Add(int newValue) => m_value += newValue;
}

// subclass to be developed (user code)
wrap class Bar // (or wrap struct Bar)
    : Foo
{
} 
```

or as follows:

```cs
// subclass to be developed  (user code)
class Bar // (or struct Bar) 
    wrap : Foo
{
}
```

The compiler can use this to create a calss "Bar" like this:

```cs
// compiled code
class Bar (or struct Bar)
{
    private Foo m_base; // it can be read-only, depending on the situation.
    public Bar()
    {
        m_base = default; // or  m_base = new Foo(default);
    }

    public Bar(int value)
    {
        m_base = new Foo(value);
    }

    public Bar(Foo value)
    {
        m_base = value;
    }

    public void Add(int newValue) => m_base.Add(newValue);

    public int BaseValue { get => m_base.Value; set => m_base.Value = value; }

    public static explicit (or implict) operator Foo(Bar bar)
    {
        return bar.m_base;
    }

    public static explicit (or implict) operator Bar(Foo foo)
    {
        return new Bar(foo);
    }
}
```

Another sample:

```cs
// user code
wrap class Bar // (or wrap struct Bar)
    : int // System.Int32
{
}

// compiled code
class Bar // (or struct Bar)
{
    private int m_value ; // it can be read-only, depending on the situation.

    public Bar(int value)
    {
        m_value = value;
    }

    public int Value { get => m_value ; set => m_value = value; }

    public static explicit (or implict) operator int(Bar bar)
    {
        return bar.Value;
    }

    public static explicit (or implict) operator Bar(int val)
    {
        return new Bar(val);
    }
}
```
Rules:

1. Access only public and protected property and functions.
2. It must be at least one public constructor (without parameter or as in sample code) of the wrapped class.

Of course, there may be problems with you. I did not think much about it just the draft.
These are what I think for now. Of course it is possible to add other features.
Is it possible and like or it reported?

**Comment by svick** [comment]
One thing that I think is missing from this proposal: *Why?* Why should the `wrap` keyword be added to the language? How does it make the code better?

As far as I can tell, it doesn't make the code much shorter (you pretty much only avoid the field declaration). And it makes the code less clear, because a type that seems to inherit from another type won't actually be its subtype. So what are the advantages?

**Comment by quinmars** [comment]
Related: #234

**Comment by scneiashardevil** [comment]
Hi @quinmars.
Yes it is similar. But I think not only interfaces, also for classes and structs.
Thanks for reply.

**Comment by scneiashardevil** [comment]
Hi @svick 
You're right, there is just code abbreviations purpose. So there is an aim to save time in coding. At least I think so.

I guess there are mistakes in the example i give. When a class inherits it inherits its public members as well. Rigth?

Ex:

```
class Foo
{
	public int Value { get; }
}

_// this is inheritance we know_
class Bar : Foo
{
	_// inheritance public members!_
}
```

Just like inheriting, but with a "wrap" keyword in the beginning.

```
_// The sealed class can not be inherited as is known._
sealed class Foo
{
	public int Value { get; }
}

wrap class Bar : Foo
{
	_// Think of it as inheriting the sealed class.
	// The distinctive feature will be the "wrap" keyword._
}
```

Public members will appear to be inherited, but in the compiled code it will still be as we know it.

```
_// compiled code!_
class Bar
{
    private int Foo m_base; _// it can be read-only, depending on the situation._
    public Bar(int value)
    {
        m_base = new Foo(value);
    }
    public void Add(int newValue) => m_base.Add(newValue);
    public int BaseValue { get => m_base.Value; set => m_base.Value = value; }
}
```

Think! Sometimes it is necessary to create a wrapper class instead of taking over. It's usually done in these sealed classrooms or in structures, is not it?
Writing code with this keyword it will be shorter, instead of writing one by one for all public members.
Also in order to understand is not it sufficient for the word "wrap" to arrive after the access qualifier? Like "sealed" or "abstract" etc.

Is it too much illogical?  :(

Thanks for reply.

**Comment by yaakov-h** [comment]
Obligatory "#107 will solve this" comment.

**Comment by scneiashardevil** [comment]
@yaakov-h, I did not understand! What should i do now or is there something i should do? What is the situation? This thread closing?

**Comment by MgSam** [comment]
@scneiashardevil @yaakov-h is just saying the if code generators were ever added to the language, you would be able to make one yourself that pretty much does what you're asking for here. 

However, the LDC has put that feature on hold and it's unlikely it'll be added to the language any time in the next few years, if ever.

**Comment by scneiashardevil** [comment]
@MgSam
I understand now 😃. It that case so closing this thread
thanks for reply.
