### ISSUE TITLE
Introduce support for unmanaged strings

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#1517]
I'd be interested in what others think of this suggestion.

The string type in .Net is a managed type and therefore one cannot embed strings inside structs if one want to take a pointer to that struct because pointers to structs which contain managed references is not possible.

However there are situations in which it is desirable to manipulate structs which do contain strings and if the string was embedded as a contiguous array (much like we can already do with fixed buffers) then taking a pointer to that struct becomes meaningful.

This would enable the creation of rich (struct) data types containing "strings" which are contiguous blocks of bytes and can be marshaled easily and quickly using just a pointer to the struct, the serialization of such types becomes straightforward too and rather quick.

Therefore we need a type which has string semantics and can inter-operate with the existing string type but is in fact implemented as a fixed buffer of Char (or Byte) with a maximum capacity and a current length.

The implementation could be a struct something like this (this is not legal C# of course but serves to illustrate)

```
public struct Text
{
   public Text (int Capacity)
   {
      this.Capacity = Capacity;
   }
   public int Length {get; private set;}
   public int Capacity {get; private set;}
   public fixed Char text [Capacity];
}
```

In addition to the above conversion operators to and from the .Net String type would be included as would some additional constructors (accepting say other Text or String instances).

However there is no way currently to declare a fixed buffer who's size is defined at runtime, the array length of fixed buffers must be a compile time constant.

The C# languages does not provide a means to limit a constructor argument to a compile time constant, if it did then we could begin to create such a `Text` type - in principle.

I have modeled this before (for both single byte and unicode strings) and the approach taken was to create a family of fixed length Text structs like `Text_32`, `Text_64`, `Text_128` and so on up to some reasonable limit like `Text_2048` or something. But this is unwieldy and restricts the possible max lengths to a few integer values, being able to create a Text with an arbitrary capacity would be much nicer.

If there was a way to restrict a constructor argument to a constant then one can envisage how this could all hang together.

```
private struct DataMessage
{
   public Text text = new Text(32);
   public int ErrorCode;
}
```

The above struct could - at compile time - have a fully determined size, all that has happened is that the constant value required to declare the fixed buffer has been supplied from the struct constructor that contains the fixed buffer.

So this ultimately leads to a new form of argument declaration - const.

```
public void SomeConstructor (const int Max)
{

} 
```

The intent is obvious - wherever this method is invoked the Max argument must be a compile time constant and would reasonably be available only for constructors (which are only (ordinarily) ever called once during the lifetime of a type).

This would require support for this:

```
public struct Text
{
   public Text (const int Capacity)
   {
      this.Capacity = Capacity;   
   }
   public int Length {get; private set;}
   public readonly int Capacity {get; private set;}
   public fixed Char text [Capacity];
}
```

The compiler would know how large to create the fixed buffer because it would know the value of Capacity because this would be a constant in the declaration of the Text instance. This would require that the compiler be able to execute the logic in the constructor at compile time and for this reason the logic in such a constructor could be restricted to simple field/property assignments like that shown.

The above are merely possible ways to do this, the key objective however is to support fixed length string-like members which can be contiguously contained within structs and thus allows pointers to such structs.

**Comment by svick** [comment]
Don't spans give you almost everything you're asking for?

Consider [this code](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEAMACFBGA3AWACh0tsA6AJQFcA7YGAWwjIEk7oB7ABwGVowYAYwgBnAoSK0RAQzgQMI4FCqDgGACLTg0gLKiZAcwhEA3kQwWsAZgyCONRRhh0MAFQgAPYABkINA8AAFhgAvBhWAEzilhjmlig2cDAeEAAmtoHSUG6ewADa7l6+/kEAutGWcRYJTi4AolBQHFAAwhypEOIAvkREKBEYLaZVGFKy8igALBg6ABSa2noihvIMAJQjZoQxMTxc0jQAPIKZUAB8GMC5ewehIzuWNBAA7hg3RydZZ7MMZIXAABoNFpdPppEY/rligFAmsKg97pYAPRIjDPZoAazRMCCCn2NAw0hEhIwUAgXAANtJhEwXHBmqRMIFoMZtg9YmyHgAjBBXABUGC4SlCGFmPP5awAZAx4TtERYUaMRPIhdlgBwMABHKhCDEUhAKaAwaQUmAAL3kQVWYKM8o57Le+MO4ogFyYy3BEHed05DpmEAYzQQOiyIkyFLIAEERAAhXmiWZPV7vQ4LUEeozfaVA7BrOF2u2KqjKjDulbe9VanWCPUGg7pGRyfWG2Am82W5mlm2smI9QhdIA===) (which already compiles):

```c#
unsafe struct DataMessage
{
    public const int TextLength = 32;
    
    public fixed char Text[TextLength];
    
    public int ErrorCode;
}

unsafe void M(DataMessage m)
{
    Span<char> textSpan = new Span<char>(m.Text, DataMessage.TextLength);

    // work with span as a replacement for string here

    byte* ptr = (byte*)&m;

    // use ptr to quickly serialize the message

    Span<byte> messageSpan = MemoryMarshal.AsBytes(new Span<DataMessage>(&m, 1));

    // use messageSpan to quickly and safely serialize the message
}
```

Here you have a type with constant-length embedded text. You can create `Span<char>` out of the text to use as a `string` (`Span<char>` can't do everything `string` can, but new `Span`-supporting methods are being added to .Net) and you can take a pointer (or `Span`) to the whole type for serialization.

**Comment by Korporal** [comment]
@svick - Hi,

I'll be honest - I haven't used Span at all, I read about it briefly recently but glossed over it. I did a huge amount of work though with unmanaged memory some years ago and also created a messaging API in which classes (derived from a base "Message") could contains "unmanaged strings" yet were a contiguous block of bytes and sending receiving such messages over a Socket was trivial and very

**Comment by ufcpp** [comment]
https://source.dot.net/#System.Private.CoreLib/shared/System/Number.NumberBuffer.cs,961cb25f24056f66

**Comment by Korporal** [comment]
I inadvertently closed this!

@svick - I admit I've not really looked at Span so will certainly explore this and you may be onto something.

I am exploring the "unmanaged" generic constraint and can tell you I used to almost dream of this a few years back when I was doing a great deal in this area.

I'm going to close this issue and open a related one that is very closely associated with this subject.
