### ISSUE TITLE
Instance and static overloads ambiguity

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1518]
I have 2 methods with the same name and same signature, but one is static and the other is instance. Whey doesn't C# accept them? One is called from the Class Name, and the other is called from an object of the class? Why does C# consider this ambiguous?

```
class Verex   
{
     public static Verex Const(string value, bool sanitize = true)
     {
        // C# say that Const( ) call is ambiguous in next line,.
        return (New Verex()).Const(value, sanitize);
     }

     public Verex Const(string value, bool sanitize = true)
     {
        // ………
     }
}

```

**Comment by CyrusNajmabadi** [comment]
```c#
class Verex
{
    void Foo()
    {
         Const(...); // What am i calling?
    }
}
```

**Comment by CyrusNajmabadi** [comment]
There is also the CLR:

> 1 . 8 . 6 . 1 . 5
Method Signatures
A method signature is composed of 

1. a calling convention,  
2. the number of generic parameters, if the method is generic,  
3. (info about the calling convention)
4. list of zero or more parameter signatures, one for each parameter of the method and, 
5. a type signature for the result value, if one is produced

**Comment by CyrusNajmabadi** [comment]
Also, i think you have the error wrong.  The error is not that it's ambiguous.  The error is that you can't even declare multiple members with teh same signature:

> Type 'Verex' already defines a member called 'Const' with the same parameter types	

I think you're getting confused by the fact that Roslyn doesn't just stop at the first error, it keeps on going and reports more, and it is indeed ambiguous which you are accessing *since* C# allows static access off of instances.

**Comment by svick** [comment]
@CyrusNajmabadi Isn't whether method is static or instance part of the calling convention (see [§II.15.3 Calling convention](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf#%5B%7B%22num%22%3A2181%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C87%2C521%2C0%5D))?

The following code ilasms and peverifies fine for me:

```il
.assembly extern mscorlib { }
.assembly app { }

.class private auto ansi beforefieldinit C
       extends [mscorlib]System.Object
{
  .method public hidebysig instance void M() cil managed
  {
    ret
  }

  .method public hidebysig static void  M() cil managed
  {
    ret
  }

  .method public hidebysig specialname rtspecialname instance void  .ctor() cil managed
  {
    ldarg.0
    call       instance void [mscorlib]System.Object::.ctor()
    ret
  }
}
```

**Comment by CyrusNajmabadi** [comment]
Ah, my mistake then.  I thought that was something else.  I retract that part and i'll leave this as just the answer specified as: https://github.com/dotnet/csharplang/issues/1518#issuecomment-388646959

The TLDR of it is: it's probably not a good idea to do this, and it will ultimately be ambiguous when you are doing lookup on an instance.  So it's just not allowed.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
I konw I can creat a new instance and call the instance method. I am working on VerbalExperisssions  and method names are long. sometimes I need to create a new expression, call a method to modify it and pass as a parameter. I thought creating static versions can shorten the synatax a bit, but it doesn't work. Now I'm using something like:
Verex.New.EnglishAlphabetOrUnderscore()
instead of the wrong idea:
Verex.EnglishAlphabetOrUnderscore()
I just wondered why static and instant methods are not distinct, or why can't they be?
Thanks.

**Comment by CyrusNajmabadi** [comment]
> I just wondered why static and instant methods are not distinct, or why can't they be?

I'm not sure what you're asking.  Could you clarify your question?

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Don't mind. You already answered :)
Thanks.
