### ISSUE TITLE
[Proposal]A operator may help to unwrap Task<Object>

### ISSUE THREAD

**Issue by TuoNiao** [dotnet/csharplang#1523]
We can make a new operator to auto unwrap the Task<Objcet> result
For example, We may use HttpClient like this

 var client = new HttpClient();
 var message = await client.GetAsync("");
 var content = message.Content;
 var result = await content.ReadAsStringAsync();

Or we can make it shorter:

 var client = new HttpClient();
 var result = client!.GetAsync()
                            .Content
                            !.ReadAsStringAsync();

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/1117

**Comment by YairHalberstadt** [comment]
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/1117
