### ISSUE TITLE
Spec bug: interpolated string may not contain newlines

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#1528]
A non-verbatim interpolated string may not contain newlines, even in the interpolations. That is what the compiler enforces, but the spec should say that. See also https://github.com/dotnet/roslyn/issues/26814

**Comment by CyrusNajmabadi** [comment]
Note: my reading of hte spec is that this is pretty effectively called out in the lexical grammar:

```
single_regular_balanced_text_character
    : '<Any character except / (U+002F), @ (U+0040), \" (U+0022), $ (U+0024), ( (U+0028), ) (U+0029), [ (U+005B), ] (U+005D), { (U+007B), } (U+007D) and new_line_character>'
```

The "and new_line_character" makes it pretty clear this isn't allowed.

**Comment by svick** [comment]
Isn't this a duplicate of https://github.com/dotnet/csharplang/issues/1513?

**Comment by svick** [comment]
@CyrusNajmabadi Except the `regular_balanced_text_part` rule has other options than just `single_regular_balanced_text_character`. If you go with some of the other rules (like `delimited_comment` or `string_literal`), what `single_regular_balanced_text_character` says doesn't apply, which means the grammar says newlines are allowed there.

**Comment by CyrusNajmabadi** [comment]
@svick Sorry, i don't know how to read things in the manner you're specifying.  Can you provide a specific chain of grammar rule that would allow a newline here in the interpolation gap whitespace itself?

**Comment by gafter** [comment]
I think @CyrusNajmabadi is right regarding https://github.com/dotnet/csharplang/blob/master/spec/lexical-structure.md#interpolated-string-literals possibly modulo an issue described in #1513

**Comment by svick** [comment]
@CyrusNajmabadi Not in the whitespace, but within a comment or a string literal, which is what #1513 is about. That issue also includes the chain of grammar rules.
