### ISSUE TITLE
Possible missing expression in Expression Table in language specification introduction.

### ISSUE THREAD

**Issue by enntwo** [dotnet/csharplang#1533]
In reference to the Expression Table in spec/introduction.md:
https://github.com/dotnet/csharplang/blob/master/spec/introduction.md#expressions

Implicitly-typed array definition expressions seem to be missing from from the summary chart here. 
`new[] {...};`

Seeing as the three variations of object initialization expressions are provided, including the anonymous object initializer, it seems consistent to include the implicitly-typed array definition after the Array creation expression.

**Assumptions**

My assumption is that is currently omitted because it is a form of the Array creation expression, rather than a separate expression (such as object creation vs. anonymous object creation):

> array_creation_expression
>     : 'new' non_array_type '[' expression_list ']' rank_specifier* array_initializer?
>     | 'new' array_type array_initializer
>     | 'new' rank_specifier array_initializer          // Implicitly-typed array definition
>     ;
> 
> object_creation_expression
>     : 'new' type '(' argument_list? ')' object_or_collection_initializer?
>     | 'new' type object_or_collection_initializer
>     ;
> 
> anonymous_object_creation_expression
>     : 'new' anonymous_object_initializer
>     ;

Though my counterpoint to this assumption is that both object creation and object creation with initializer are listed on separate lines even though they are both examples of the _object_creation_expression_ above.

It is also my assumption that the table is exhaustive, I do not know if are some expressions are omitted for brevity. I understand that not all forms of every expression is shown (in general a single form of each expression is shown) but this feels like a useful inclusion, much like object creation vs. object creation with initializer.

**Comment by svick** [comment]
> Seeing as the three variations of object initialization expressions are provided

There is actually one variant missing from the table: object initialization without parentheses: `new T{...}`.

**Comment by BillWagner** [comment]
Closing this as the ECMA committee removed this chapter from the spec as of C# 5.0 (It was largely informative, not normative, and was not complete, as noted in this and other issues).

I did examine the grammars for the expressions above, and the pertinent portions of the standard text are correct.
