### ISSUE TITLE
Deleted discussions

### ISSUE THREAD

**Issue by Pzixel** [dotnet/csharplang#1535]
I'm not sure if it's a right repo to ask or I have to ask support, but it seems that some of issues are hidden or deleted somehow.

I'm talking about https://github.com/dotnet/csharplang/issues/1196 and https://github.com/dotnet/csharplang/issues/1224 . They had tons of useful comments as well as it was a great example of impossible LDM tolerance and patience. However, they are not available (I get 404 when I'm trying to access them). 

What happened to these issues?

**Comment by gafter** [comment]
I don't have personal knowledge about what happened, but I hope they were deleted. We were trying to deal with a spammer and cleaning up after the fact can be hard.
