### ISSUE TITLE
[Proposal] Using statement with expression body operator

### ISSUE THREAD

**Issue by florinciubotariu** [dotnet/csharplang#1540]
The syntax in C# would look like:

`using (var memStream = new MemoryStream(bytes)) => variable.UploadFromStream(memStream);`

Instead of 
```
using (var memStream = new MemoryStream(bytes))
{
  variable.UploadFromStream(memStream);
}
```

**Comment by Pretasoc** [comment]
You can already omit the braces, if there is only one line inside them. In my opinion an expression body operator is more confusing than simply omitting the braces.
