### ISSUE TITLE
Suggestion: Strgroup type in C# and VB.NET

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1541]
# Situation:
I have this class:

```
    public static class RegexConst
    {
        public static readonly string LineFeed = @"\n";
        public static readonly string CarriageReturn = @"\r";
        public static readonly string NewLine = @"\r\n";
        public static readonly string Digit = @"\d";
        public static readonly string NotADigit = @"\D";
        public static readonly string WordChar = @"\w";
        public static readonly string NotAWordChar = @"\W";
        public static readonly string Bell = @"\a";
        public static readonly string Alarm = @"\a";
        public static readonly string StartOfText = @"\A";
        public static readonly string EndOfText = @"\z";
        public static readonly string EndOfLastNonEmptyLine = @"\Z";
        public static readonly string Backspace = @"\u0008";
        public static readonly string WordBoundary = @"\b";
        public static readonly string WordEdge = @"\b";
        public static readonly string NotAWordBoundary = @"\B";
        public static readonly string NotAWordEdge = @"\B";
        public static readonly string VerticalTab = @"\v";
        public static readonly string FormFeed = @"\f";
        public static readonly string WhiteSpace = @"\s";
        public static readonly string NotAWhiteSpace = @"\S";
        public static readonly string Escape = @"\e";
    }

```
I want to define a method parameter that only accepts values from RegexConst fields!
There is no string enum to use in this situation. Is there any solution?
The only solution in my mind, is to define a base class and then define 22 inhereted class to represent all those values. This is an over kill, and I don't think it is a practical solution!
I don't want to use  a string param and use validation code to check that its values belongs to all those values above. My aim is to make the the method self describing and force who uses it to use one of these predefined values.
Note that I can't use a char with these values. If I pass these  strings as a c# char, the generated string will contain non writeable chars. I want these string strings to appear as escaped chars. 
 
# Suggestion:
if there is no such solution, this brings back the need for some sort of string Enum. They have the same benefits of Enums.
I suggest to add this new type:

```
public Strgroup RegexConst
{
  LineFeed = @"\n",
  CarriageReturn = @"\r",
  NewLine = @"\r\n",
  Digit = @"\d",
  NotADigit = @"\D",
  WordChar = @"\w",
  NotAWordChar = @"\W",
  Bell = @"\a",
  Alarm = @"\a",
  StartOfText = @"\A",
  EndOfText = @"\z",
  EndOfLastNonEmptyLine = @"\Z",
  Backspace = @"\u0008",
  WordBoundary = @"\b",
  WordEdge = @"\b",
  NotAWordBoundary = @"\B",
  NotAWordEdge = @"\B",
  VerticalTab = @"\v",
  FormFeed = @"\f",
  WhiteSpace = @"\s",
  NotAWhiteSpace = @"\S",
  Escape = @"\e",
}

```
So we can use it in the same way we use enum:

```
void foo(RegexConst x)
{
      Console.WriteLine("This is " + x);
}

```
Of course Strgroup will be a general purpose for storing any set of string constants and strict input parameters to them. I just show my use case.

Also I want the same type uin VB.NET:
```
public Strgroup RegexConst
  LineFeed = "\n"
  CarriageReturn = "\r"
  NewLine = "\r\n"
  Digit = "\d"
  NotADigit = "\D"
  WordChar = "\w"
  NotAWordChar = "\W"
  Bell = "\a"
  Alarm = "\a"
  StartOfText = "\A"
  EndOfText = "\z"
  EndOfLastNonEmptyLine = "\Z"
  Backspace = "\u0008"
  WordBoundary = "\b"
  WordEdge = "\b"
  NotAWordBoundary = "\B"
  NotAWordEdge = "\B"
  VerticalTab = "\v"
  FormFeed = "\f"
  WhiteSpace = "\s"
  NotAWhiteSpace = "\S"
  Escape = "\e"
End Strgroup

```

# Implantation: 
C# will generate the static class RegexConst, change the RegexConst x param to string x and generate some validation code to throw exception if a code assigns any value to it other than those defined in the static class RegexConst. So, no need to make any changes to IL or CoreFx.

**Comment by CyrusNajmabadi** [comment]
> I want to define a method parameter that only accepts values from RegexConst fields!

```c#
public struct RegexConst
{
    public readonly string Value;
 
    public static readonly RegexConst LineFeed = new RegexConst(@"\n");
 
    private RegexConst(string value) => Value = value;
}
```

Now you can expose methods that only take a RegexConst, and people can only get RegexConsts with the static you expose.  No need for a language feature to do what can already be done.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Nice. I will add an implicit operator to convert to a string and it will do the job.
But a string enum strill a compact form, and other asked for. Why can't we have it?

**Comment by CyrusNajmabadi** [comment]
>Why can't we have it?

No one said you can't have it :)   I'm just pointing out there's a viable solution today.  

That said, i see very little benefit to this suggestion.  We already have a completely usable solution today.  So why spend time working on somethign that is a non-problem?  I'd much rather work be done on features that don't have trivial solutions :)

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Thanks, I already used your solution. I never wrote such form of code before.

> We already have a completely usable solution today
C# added many features that doesn't solve any problem but majes code shorter, easier to write and read, such as => instead of method bodies. By the way: why can'y we use the => form with operators?

This is the Full class, and you can compare it to the strgroup RegexConst:
```
    public struct RegexConst
    {
        public readonly string Value;
        private RegexConst(string value) => Value = value;
        public static implicit operator string(RegexConst r)
        {
            return r.Value;
        }

        public static readonly RegexConst LineFeed = new RegexConst(@"\n");
        public static readonly RegexConst CarriageReturn = new RegexConst(new RegexConst(@"\r";
        public static readonly RegexConst NewLine = new RegexConst(@"\r\n");
        public static readonly RegexConst Digit = new RegexConst(@"\d");
        public static readonly RegexConst NotADigit = new RegexConst(@"\D");
        public static readonly RegexConst WordChar = new RegexConst(@"\w");
        public static readonly RegexConst NotAWordChar = new RegexConst(@"\W");
        public static readonly RegexConst Bell = new RegexConst(@"\a");
        public static readonly RegexConst Alarm = new RegexConst(@"\a");
        public static readonly RegexConst StartOfText = new RegexConst(@"\A");
        public static readonly RegexConst EndOfText = new RegexConst(@"\z");
        public static readonly RegexConst EndOfLastNonEmptyLine = new RegexConst(@"\Z");
        public static readonly RegexConst Backspace = new RegexConst(@"\u0008");
        public static readonly RegexConst WordBoundary = new RegexConst(@"\b");
        public static readonly RegexConst WordEdge = new RegexConst(@"\b");
        public static readonly RegexConst NotAWordBoundary = new RegexConst(@"\B");
        public static readonly RegexConst NotAWordEdge = new RegexConst(@"\B");
        public static readonly RegexConst VerticalTab = new RegexConst(@"\v");
        public static readonly RegexConst FormFeed = new RegexConst(@"\f");
        public static readonly RegexConst WhiteSpace = new RegexConst(@"\s");
        public static readonly RegexConst NotAWhiteSpace = new RegexConst(@"\S");
        public static readonly RegexConst Escape = new RegexConst(@"\e");
    }

```

**Comment by CyrusNajmabadi** [comment]
> And with your solution, all that is needd is to use the

That's fine.  :)

You're welcome to add a +1 on proposals in this space (for example https://github.com/dotnet/csharplang/issues/576).  

I'm just pointing out that there would likely be very little interest in improving things here as there would be very little benefit to the ecosystem, but it woudl incur all the costs that come along with creating new language features.  THere are literally fixed resources with which to make any language change.  So anything that is picked necessarily means other things have to not be picked.  So the LDM tries to pick teh best bang/buck proposals.  This proposal is very low bang, and would have all the costs assocaited with defining and developing an entire new type into the type system.

**Comment by MohammadHamdyGhanem** [comment]
I may suggest to allow us to add programmer-defined blocks syntax saved in defintion files, that can be imported to the project and destributed with it. Anyone sees these new syntaxes can understand them by the "go to definition" command. The definition Fileof cource will have some comments and explaination.
 So, is it possible to make the compiler allow us to define our syntax and its generated code? The compiler task is easy: parse the block, and use the parametrs to generate the code.
 If anyone ok with this idea, we can add a new proposal and see how can we define the defintions rules ot templates.
Something like this:
```
public @strgroup RegexConst
{
  LineFeed = @"\n",
  CarriageReturn = @"\r",
  NewLine = @"\r\n",
  Digit = @"\d",
  NotADigit = @"\D",
  WordChar = @"\w",
  NotAWordChar = @"\W",
  Bell = @"\a",
  Alarm = @"\a",
  StartOfText = @"\A",
  EndOfText = @"\z",
  EndOfLastNonEmptyLine = @"\Z",
  Backspace = @"\u0008",
  WordBoundary = @"\b",
  WordEdge = @"\b",
  NotAWordBoundary = @"\B",
  NotAWordEdge = @"\B",
  VerticalTab = @"\v",
  FormFeed = @"\f",
  WhiteSpace = @"\s",
  NotAWhiteSpace = @"\S",
  Escape = @"\e",
}

```
The compiler can use this to create a calss CityTemperaturesDic like this:
 ```
public struct RegexConst
    {
        public readonly string Value;
        private RegexConst(string value) => Value = value;
        public static implicit operator string(RegexConst r)
        {
            return r.Value;
        }

        public static readonly RegexConst LineFeed = new RegexConst(@"\n");
        public static readonly RegexConst CarriageReturn = new RegexConst(new RegexConst(@"\r";
        public static readonly RegexConst NewLine = new RegexConst(@"\r\n");
        public static readonly RegexConst Digit = new RegexConst(@"\d");
        public static readonly RegexConst NotADigit = new RegexConst(@"\D");
        public static readonly RegexConst WordChar = new RegexConst(@"\w");
        public static readonly RegexConst NotAWordChar = new RegexConst(@"\W");
        public static readonly RegexConst Bell = new RegexConst(@"\a");
        public static readonly RegexConst Alarm = new RegexConst(@"\a");
        public static readonly RegexConst StartOfText = new RegexConst(@"\A");
        public static readonly RegexConst EndOfText = new RegexConst(@"\z");
        public static readonly RegexConst EndOfLastNonEmptyLine = new RegexConst(@"\Z");
        public static readonly RegexConst Backspace = new RegexConst(@"\u0008");
        public static readonly RegexConst WordBoundary = new RegexConst(@"\b");
        public static readonly RegexConst WordEdge = new RegexConst(@"\b");
        public static readonly RegexConst NotAWordBoundary = new RegexConst(@"\B");
        public static readonly RegexConst NotAWordEdge = new RegexConst(@"\B");
        public static readonly RegexConst VerticalTab = new RegexConst(@"\v");
        public static readonly RegexConst FormFeed = new RegexConst(@"\f");
        public static readonly RegexConst WhiteSpace = new RegexConst(@"\s");
        public static readonly RegexConst NotAWhiteSpace = new RegexConst(@"\S");
        public static readonly RegexConst Escape = new RegexConst(@"\e");
    }

```
Allowing user defined syntax for some blocks has these benefits:
1.Encourage more programmers to test their ideas without disturbing C# team.
2.Templates can be published on githup and shared with VS.NET projects. It will be easy to measure the popularity of them.
3.Fast growth of the language, because C# team can adopt famous syntaxes.

**Comment by CyrusNajmabadi** [comment]
> So, is it possible to make the compiler allow us to define our syntax and its generated code? 

No. :)

> The compiler task is easy: 

It isn't.  See the large threads on things like Source-Generators :)

> Allowing user defined syntax for some blocks has these benefits:
1.Encourage more programmers to test their ideas without disturbing C# team.
2.Templates can be published on githup and shared with VS.NET projects. It will be easy to measure the popularity of them.
3.Fast growth of the language, because C# team can adopt famous syntaxes.

I'd be happy to discuss this more with you on gitter.  I can give you some ideas on how you could create such a system.  Note that such a system will likely always be external to roslyn as hte complexities and downsides make it unlikely to be part of the core project itself.  However, if those limitations are acceptable to you, it would be something you could create and maintain for the benefit of hte ecosystem.


Or, alternatively, you could just use t4 or any of the many templating libraries out there.  If none of those are sufficient for you... well, then you'll have a better understanding of why this is not a simple or easy undertaking :)

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem If you want to continue the discussion, let's do it over on gitter.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi @srivatsn @migueldeicaza @tmat @jongalloway @HaloFour @svick 
Based on this workarround:
https://www.codeproject.com/Articles/11130/String-Enumerations-in-C
If we have this strgroup
```
public @strgroup RegexConst
{
  LineFeed = @"\n",
  CarriageReturn = @"\r",
  NewLine = @"\r\n"
}

```C# can convert it to this enum:
```
public enum RegexConst
{
    [StringValue("@"\n")] LineFeed,
    [StringValue("@"\r")] CarriageReturn,
    [StringValue("@"\r\n")] NewLine
}

```And 
`var x = RegexConst.IneFeed;
`converted to 
`var x = StringEnum.GetStringValue(RegexConst.IneFeed);`
