### ISSUE TITLE
C# regex syntax!

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1545]
I built a Verex class baised on VerbalExpressions repo, to build regex patterns in easier way. 
This Code:
```
var SequenceWithoutAngleBrakets = Verex.New.OutOfRange('<', '>').NoneOrMany();
var OpenAngle = Verex.New.CaptureGroup("Open", "<");
var CloseAngle = Verex.New.BalancingGroup("Close", "Open", ">");
var expr = Verex.New
    .StartOfLine
    .Next(SequenceWithoutAngleBrakets)
    .NoneOrMany(
         Verex.New
         .OnceAtleast(
             OpenAngle
             .Next(SequenceWithoutAngleBrakets)
          ).OnceAtleast(
             CloseAngle
             .Next(SequenceWithoutAngleBrakets)
       )
     )
     .IfThisIs("Open", Verex.New.IfNextIsNot(""))
     .EndOfLine;

```
generates this regex pattern:
`^[^<>]*(((?<Open><)[^<>]*)+((?<Close-Open>>)[^<>]*)+)*(?(<Open>)(?!))$`

So, I asked myself: couldn't regex just be a part of C#, and written as a direct code? For example the previous code can be like this:

```
var SequenceWithoutAngleBrakets = Verex
{
    OutOfRange('<', '>')
    NoneOrMany();
}
var OpenAngle = Verex {CaptureGroup("Open", "<")};
var CloseAngle = Verex {BalancingGroup("Close","Open", ">")};

var expr = Verex
{
     StartOfLine;
     SequenceWithoutAngleBrakets;
     NoneOrMany 
     {
          OnceAtleast
          {
             OpenAngle;
             SequenceWithoutAngleBrakets;
          }
          OnceAtleast
          {
             CloseAngle;
             SequenceWithoutAngleBrakets;
          }
      }
      If ("Open")
         IfNextIsNot("");
      
      EndOfLine;
}
```

I don't say this is the right syntax or the best verbal method names. This is just a basic idea to discuss, driven by the agony of anyone tries to understand what does this mean when it appears in code:
`^[^<>]*(((?<Open><)[^<>]*)+((?<Close-Open>>)[^<>]*)+)*(?(<Open>)(?!))$`
I can't stop thinking of a better way to write regex patterns!

**Comment by MohammadHamdyGhanem** [comment]
Another example:
```
var ValidFirstChar = Verex {EnglishAlphabetOrHyphen;}
var ValidChars = Verex { ValidFirstChar + Digit + '.' + '-' ;}

var email = Verex{
                WordEdge;
                ValidFirstChar;
                ValidChars(0, 20);
                "@";
                ValidFirstChar;
                ValidChars(2, 14);
                ".";
                ValidFirstChar;
                ValidChars(1, 9);
                WordEdge;
```

This should generate:
`\b[_a-zA-Z][_a-zA-Z0-9.\-]{0,20}@[_a-zA-Z][_a-zA-Z0-9.\-]{2,14}\.[_a-zA-Z][_a-zA-Z0-9.\-]{1,9}\b`

**Comment by Unknown6656** [comment]
Multiple points:

 1) What _exact_ syntax do you propose for language-intrinsic RegEx support?
 2) Yeah, RegEx may be hard to learn at the beginning, but I do not like the verbal explanation of RegEx expressions -- I think that the 'normal' notation is compact and precise.
 3) I would much rather  like something along the lines of JS, maybe with backticks instead of forward slashes:

```csharp
Match m = `(?<animal>dog|cat|horse)\s+is\s+(?<age>[0-9]+)\s+years?\s+old\.`.Match("dog is 5 years old.");

var animal = m.Groups["animal"]; // dog
var age = m.Groups["age"]; // 5
```

**Comment by svick** [comment]
I think you could get pretty close with existing syntax just by changing your API:

```c#
var SequenceWithoutAngleBrakets = Verex.OutOfRange('<', '>').NoneOrMany();
var OpenAngle = Verex.CaptureGroup("Open", "<");
var CloseAngle = Verex.BalancingGroup("Close", "Open", ">");

var expr = Verex.New(
     Verex.StartOfLine,
     SequenceWithoutAngleBrakets,
     Verex.NoneOrMany(
          Verex.OnceAtleast(
             OpenAngle,
             SequenceWithoutAngleBrakets),
          Verex.OnceAtleast(
             CloseAngle,
             SequenceWithoutAngleBrakets)),
      Verex.If("Open", IfNextIsNot("")),
      Verex.EndOfLine);
```

And if you wanted, you could simplify the above even more by `using static`.

**Comment by MohammadHamdyGhanem** [comment]
@Unknown6656 
Thanks. But I never liked regex syntax. It's powerfull but not human friendly, and hard to understand if you are not the one how wrote it.

@svick
This is a good idea, and I already tried to have 2 versions of each method: a static one and an instance one, but c# refuses the 2 overloads that only differ by the static keyword!.. The only solution is to add a different change to the name, or add the statics to a separite helper class.
using instance methods and dor syntax shorter in some cases. Statics are shorter in start of a sub pattern.
The param array is useful in adding patterns from Verex variables.
Seems all three ways have to coexist!

I have a new idea ablut creating a class for eacch entity in regex (strings, groups, char classes,... etc) , then compose the expr as an array of entities using {} initialization. The problem is there will be many new "entity"() in the array!

**Comment by CyrusNajmabadi** [comment]
you could just change your API to allow for this:

```c#
using static Verex;

var expr = new Verex
{
     StartOfLine,
     SequenceWithoutAngleBrakets,
     new NoneOrMany 
     {
          new OnceAtleast
          {
             OpenAngle,
             SequenceWithoutAngleBrakets,
          },
          new OnceAtleast
          {
             CloseAngle,
             SequenceWithoutAngleBrakets
          }
      },
      new If ("Open")
      {
         IfNextIsNot("")
      },      
      EndOfLine;
}
```

**Comment by CyrusNajmabadi** [comment]
>a static one and an instance one, but c# refuses the 2 overloads that only differ by the static keyword!

I don't understand the case where you'd have instance/static *and* have the same signature.

**Comment by CyrusNajmabadi** [comment]
> But I never liked regex syntax. It's powerfull but not human friendly, and hard to understand if you are not the one how wrote it.

I'm not sure the Verex syntax is any more human-friendly.  It's just names instead of symbols.  But once you know that ```+``` is ```OnceAtLeast``` then ```OnceAtLeast``` is simply incredibly excessive to say the same thing.

Note: when my regex work comes on line, it will make it much easier to understand regexes in VS.  And you can also do things like use multi-line regexes to comment you work, which is a *lot* better for understanding a regex versus having names for the symbols that people already know.  i.e. you should be writing:

```c#
new Regex(@"
^[^<>]*                       # Helpful comment.
(((?<Open><)[^<>]*)+          # More commenting.
....                          # etc. etc.
", IgnorePatternWhitespace);
```

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Thanks. I already refered to the idea of defining patttern classes in a my last reply, and you made lt clear it is a good one.
But I dont know kow can I wite StartOfLine unqualified. It is a property of Verex class not a variable. It could be static and written as Verex.StartOfLine.
The idea of multiline regex with comments is good and I thought about. It is alredy done by concating multiple strings
new Regex(@" ^[^<>]*"  +            // Helpful comment. 
"(((?<Open><)[^<>]*)+" +          // More commenting. 
....                         
, IgnorePatternWhitespace);
And I don,t know how your work would not break existing code, the new line in the regex is simllar to \n\r and maybe some thounsand programmers were inserting a true line in the pattern instead of \n\r witch will be treated differently with your modification.
Still, sympoles are hard to memorize. I alway return to docs to find out what some sympoles mean. At least we need intillisense support when we write the first parameter of the tegex class to offer names of patters and there equivalent regex. Or you can solvr the two issues by adding new sympole before the regex string,so we can have intillisense and syntax check inner lines can be illimenated such as 
var s = %".*";
s can be conseded a string, or if we agreed on the principal, the sympole % can be a mark to define a regex with this pattern and assign it to s. So % will give us three benefits.
Finally,  what is your work on regex? You replied in many of my regex issues but this is the fist time to mention it. Is there more work other than your given example?

**Comment by CyrusNajmabadi** [comment]
> It is a property of Verex class not a variable. It could be static and written as Verex.StartOfLine.

Right.  And then you can use static imports to make it available without qualification :)

Or you can do something like:

```c#
using V = Whatever.Verex;
//..
V.StartOfLine
```

**Comment by CyrusNajmabadi** [comment]
> And I don,t know how your work would not break existing code

This is something that is already supported in regexes.  :)

**Comment by CyrusNajmabadi** [comment]
>  Or you can solvr the two issues by adding new sympole before the regex string,so we can have intillisense and syntax check inner lines can be illimenated such as
var s = %".*";

Please see the PR i linked to: https://github.com/dotnet/roslyn/pull/23984

You don't need any special syntax for this.

> Finally, what is your work on regex? You replied in many of my regex issues but this is the fist time to mention it. Is there more work other than your given example?

I've linked to it :)   It basically adds IDE features to help you write a regex without needing any actual changes to the language.

**Comment by CyrusNajmabadi** [comment]
> Or you can solvr the two issues by adding new sympole before the regex string,so we can have intillisense 

Note: intellisense doesn't require any special symbols/syntax.  For example, we provide intellisense inside comments in places we think are appropriate.  A similar thing can be done inside a string (which is what my PR is).

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem Are there any actual language changes needed here?  The language already has several mechanism to help you build these sort of fluent/tree-construction APIs.  So it feels like it would be better if your API just embraced those instead of having the language have any knowledge about regexes at all...

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Ok, I'll try these new ideas and see. I was tied to the original implementaion of VerbalExpressions, except adding some Vexex params to allow sub-patterns, instead adding raw regex strings.
I'll also look into your PR. See you there.

**Comment by MohammadHamdyGhanem** [comment]
@Unknown6656 @migueldeicaza 
Here is Verex (my verbal regex builder):
https://github.com/MohammadHamdyGhanem/Verex
Thanks
