### ISSUE TITLE
Predefined ValueTuples

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1547]
I'm using this ValueTuple in one of my classes:
`(Char from, Char to)`
I found that using such tuple many times in code makes it longer and ugly such as:
`protected List<(Char from, Char to)> Ranges = new List<(Char from, Char to)>();`
Of cource this became a nightmare if  the tuple has more than two elements!
but it solves some problems such as this:
```
public CharClass(params (Char from, Char to)[] ranges){
}
```

Tuple param array is better that struct param array because it is self descrying and makes calling code shorter:
 
`var x = new CharClass(('a', 'z'), ('A', 'Z'), ('0', '9');`

This is better than:
`var x = new CharClass(new Range('a', 'z'), new Range('A', 'Z'), new Range ('0', '9');`

So, I ask: why can't we declare the ValueTuple as a Type, so we can reuse it anywhere?
Something like this:

```
ValueTuple CharRange
{
   Char from;
   Char to;
}
```

So we can write:
```
protected List <CharRange> Ranges = new List<CharRange>();
public CharClass(params CharRange[] ranges){
}
```

The param info tool tip should show the CharRange Tuple as (Char from, Char to) so the user knows what he should write. We pass the values to this tuple param  as usual:
`var x = new CharClass(('a', 'z'), ('A', 'Z'), ('0', '9');`

There is another benefit: the names of the elements will not be lost in reflection, because it's now stored in the type declaration.

Note: I think this may relate to Records. 
May be this problem can be solved in general be allowing record values to be passed as Tuple syntax (the reverse of the deconstruction).
I know there are plenty of suggestions out there may be similar, but I can't recall them right now.

**Comment by HaloFour** [comment]
I think they already added this feature in C# 1.0.  It's called a `struct`.

**Comment by svick** [comment]
So your `ValueTuple CharRange` is basically a more succinct syntax for the following code?

```
struct CharRange
{
    public Char From { get; }
    public Char To { get; }
    
    public CharRange(Char from, Char to)
    {
        From = from;
        To = to;
    }
    
    public static implicit operator CharRange((Char from, Char to) tuple)
        => new CharRange(tuple.from, tuple.to);
}
```

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour  @svick 

I alredy used this solution:

```
        protected struct Range<T>
        {
            public T Min;
            public T Max;

            public Range(T min, T max)
            {
                Min = min;
                Max = max;
            }

            public static implicit operator Range<T>((T from, T to) range)
            {
                return new Range<T>(range.from, range.to);
            }

            public static implicit operator (T from, T to) (Range<T> range)
            {
                return (range.Min, range.Max);
            }
        }

```Put as you can see, I have to make my struct generic type, becuase I need this tow value range of two differnt types. I also use type called CharOrEscape, but practically this makes some problems, espitially when passing an array ov valueTuple to a List<Range<CharOrEscape>> which needs more code fot casting!
This will be easier and shorter if I just have a predefined ValueTuple!
As I say always: I can workarround any problem, but why should we waste our time in such twisted ways every time, while we can have an esier solution?

**Comment by MohammadHamdyGhanem** [comment]
I replied in the https://github.com/dotnet/csharplang/issues/1546 issue because of the problem of adding an array of type1 to a list of type2, C# can't do the cast even type1 cav be csted to type2!

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

The language shouldn't be encouraging developers to tie the code into knots in the manner that you seem to.  If you need a named and reusable data structure then you don't need tuples.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
I'm working on verbal regex (Verex). I need to make the verbal syntax as clrear, as short and as readable as possible. Passing pairs of values as tuples achives that, but I found my self declaring the same tuples over and over!
Each situations imposes its syntax.
Using a struc will make the verbal longer (adding the new struct part a lot in long expression). Tuples are perfect params for me, but I need s smart sortcut for them!
I konw Tuples were found to give a quick return multiple value, but C# allowed them to be a full type (I made a suggestin before tuples to made a multiple retun value with a suntax similar to annonymous types: {int, string}, and never tought of using that as a parameter!). Tuples are used with collections, and pased as parameters, and appear anywere else! Something like that is powerfull and can get more.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> Each situations imposes its syntax.

You seem to like to invent your syntax as you go along and then propose that C# change to meet what you would like.  That's not how this works.  It also won't remotely happen on a timescale that makes it relevant to this project that you're working on.

C# is already getting range syntax.  Arguing that C# should add a way to name tuples as proper types so that you can use them as a hack of a range syntax is not likely to gain much in the way of traction.

C# already has aliases.  You can do `using CharRange = System.ValueTuple<char, char>;` right now.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
This is a sample:
```
            var x = Pattern.CharClass('a', 'b')
                .AddRanges(('0', '9'), ('j', 'r'))
                .Repeat(5, RepeatMode.Lazy);
```
This is the best syntax I came up with so far. The pattern will be
[ab0-9j-r]{5}?

**Comment by CyrusNajmabadi** [comment]
> I'm working on verbal regex (Verex). I need to make the verbal syntax as clrear, as short and as readable as possible. 

Don't we already have that?  It's a regex :)   I thought the point of verex was to not be as short as possible, but instead to encourage a more tree-construction-based approach so you could structurally build your regex programmatically instead of parsing it out of a string.

**Comment by CyrusNajmabadi** [comment]
> @HaloFour
>This is a sample:

```c#
            var x = Pattern.CharClass('a', 'b')
                .AddRanges(('0', '9'), ('j', 'r'))
                .Repeat(5, RepeatMode.Lazy);
```

There is nothing stopping you from taking a Tuple in as your arguments, but then converting it internally to an actual named type.  This is trivial to do, and i would not really be very beneficial for the language to provide a shorthand for something that can already be done so simply by you inside your API.

**Comment by CyrusNajmabadi** [comment]
> This will be easier and shorter if I just have a predefined ValueTuple!

But you have a predefined valuetuple.  It already exists and works well.  You just don't want to use it :)

> As I always say : I can work arround any problem, but why should we waste our time in such twisted ways every time, while we can have an esier solution?

I don't think the proposal makes things easier.  You can already do this:

```c#
public Pattern AddRanges(params (char, char)[] ranges)
    => AddRanges(ranges.Select(Range.From));

private Pattern AddRanges(IEnumerable<Range<char>> ranges)
{
    // Do whatever you want. with the parameter.
    return this;
}
```

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
I alredy did the internal conversion between Tuple and Range struct  b4 I post this. 
What I post here is not a question for a solution (I do this at Stackoverflow, or ask you at gitter :) ). What I post here is my thoughts about C# beeing easier and time saver. I share my thoughts about how the programming language shoud be from my poit of view. This doesn't mean you should agrree on that or share the same vision. These are issues to discuss, mabbe something good come out of one of these discussions somesay.
Note that this is the fifth or sixth definition block I ask for, and all this can be answered by one solution: Give us the ability to define our own code blocks! 
thanks.

**Comment by stakx** [comment]
> Give us the ability to define our own code blocks!

How about this:

```csharp
{
    // your code goes here
}
```

**Comment by BhaaLseN** [comment]
I thought I read this on another issue, but cannot seem to find it. But today, it isn't possible to define tuple aliases:
```c#
using System;
// not allowed:
using Person = (string firstName, string lastName);
// works, but has no names to Item1/Item2
using PersonVT = ValueTuple<string, string>;
```

There's been more than one occasion where I wished to have this to indicate more clearly that I actually mean the same tuple type; and not just one that looks the same.

...or I could just go and define a `struct` (or `class`) instead.

**Comment by svick** [comment]
@BhaaLseN I think you're talking about https://github.com/dotnet/csharplang/issues/423.

**Comment by AustinBryan** [comment]
Also, if [#100](https://github.com/dotnet/csharplang/issues/100) is added, the current calling code could be such:

```csharp
// Current:
var x = new CharClass(new Range('a', 'z'), new Range('A', 'Z'), new Range ('0', '9');
// C# 8.0
var x = new CharClass(new('a', 'z'), new('A', 'Z'), new('0', '9');
// Tuples
var x = new CharClass(('a', 'z'), ('A', 'Z'), ('0', '9');
```

Yes tuples are still the best, but not much better than with [#100](https://github.com/dotnet/csharplang/issues/100) to make any significant argument to add it.

**Comment by MohammadHamdyGhanem** [comment]
Another approach:
In general, can't we shorten the code by defining a name for reapeated parts like this:
`#define CharRange: (Char from, Char to)` ?
So, we can write:
```
protected List <CharRange> Ranges = new List<CharRange>();
public CharClass(params CharRange[] ranges)
```

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

`#define` is used for preprocessor directives, not aliases.  You'd use `using` for aliases, which has already been proposed here: #423

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
I thought of using. but feared you woll say it is for namespaces only, and using static is for static members only! But ofcource I'd prefer using over #def

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

You can use it for aliases today, it's just somewhat limited.  There are various proposals to make it less limited:

```cs
using StringDictionary = System.Collections.Generic.Dictionary<string, string>;
```
