### ISSUE TITLE
Provide searchable tag for finalised LDM notes

### ISSUE THREAD

**Issue by mungojam** [dotnet/csharplang#155]
Previously, I had a [URL](https://github.com/dotnet/roslyn/issues?utf8=✓&q=label%3A%22Design%20Notes%22) I could use to keep up to date with LDM notes. I could quickly look there and see if there were any new ones since I last looked (obviously notifications or an RSS feed would be nicer).

In the new setup, I haven't worked out a way to do this. The only options at present seem to be to either:

1. Keep looking at the [2017 folder](https://github.com/dotnet/csharplang/tree/master/meetings/2017) and look at the last changed dates there in order to ignore future ones

or 
 
2. Look through the "Meeting note issues" [here](https://github.com/dotnet/csharplang/issues?q=label%3A%22Meeting+notes%22+is%3Aclosed), ignoring any that aren't related to meeting notes.

I propose that a tag be added onto the design note discussion items once they have been completed. Perhaps this is due to happen anyway and it's just that there haven't been any new notes published since the migration to the new setup.

**Comment by MadsTorgersen** [comment]
Good idea to have a separate tag for this.

You are right that no design notes have been published since we moved. I was planning to put out an issue for each, as you propose, when they are done, but had not thought of a dedicated label. I'll do that.

Thanks!

Mads

**Comment by mungojam** [comment]
Thanks for implementing this. It works really well
