### ISSUE TITLE
C# unions?

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#1554]
This probably isn't something I'd ordinarily suggest for a language feature but it is possible to implement it now we have C# 7.3

Do others think there is any sense in seeking to make this more of an inherent C# feature though:

```
namespace NewConsole
{
    unsafe class Program
    {
        static void Main(string[] args)
        {
            Union union = new Union(null); // pass a real address here in practice!

            // layout1 and layout2 each refer to the same memory address.

            var layout1 = union.AccessAs<Layout_1>();
            var layout2 = union.AccessAs<Layout_2>();

            layout1.Counter = 23;
            layout2.Rate = 34.5;
        }
    }
    public unsafe class Union
    {
        public void* Address { get; private set; }
        public Union (void * Address)
        {
            this.Address = Address;
        }

        public ref T AccessAs<T>() where T : unmanaged
        {
            return ref (*(T*)Address);
        }
    }
    public struct Layout_1
    {
        public long Counter;
        public int Depth;
        public int Other;
    }
    public struct Layout_2
    {
        public byte Byte1;
        public byte Byte2;
        public byte Byte3;
        public byte Byte4;
        public double Rate;
    }
}
```

The alignmnet of each struct must of course be the same and a few other considerations...

**Comment by tannergooding** [comment]
See also: https://github.com/dotnet/csharplang/issues/687

As a workaround, you can already declare unions today using `[StructLayout(LayoutKind.Explicit)]` and `[FieldOffset(int)]`

**Comment by tannergooding** [comment]
```C#
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit)]
public unsafe class Union
{
    [FieldOffset(0)]
    public Layout_1 Layout_1;

    [FieldOffset(0)]
    public Layout_2 Layout_2;
}

public struct Layout_1
{
    public long Counter;
    public int Depth;
    public int Other;
}

public struct Layout_2
{
    public byte Byte1;
    public byte Byte2;
    public byte Byte3;
    public byte Byte4;
    public double Rate;
}
```

**Comment by tannergooding** [comment]
See also https://github.com/dotnet/csharplang/issues/399

**Comment by tannergooding** [comment]
and https://github.com/dotnet/csharplang/issues/113

**Comment by Korporal** [comment]
@tannergooding - Yep, you're right - I've never had ocassion to use a "union" in a .Net world (but there was a question about it on MSDN Forums earlier). The attributes are clearly better !

**Comment by Korporal** [comment]
This includes some alignment capabilities:

`using System;
using System.Runtime.InteropServices;

namespace NewConsole
{
    unsafe class Program
    {
        static void Main(string[] args)
        {
            Union union = new Union(null, 16);

            // layout1 and layout2 each refer to the same memory address.

            var layout1 = union.AccessAs<Layout_1>();
            var layout2 = union.AccessAs<Layout_2>();

            layout1.Counter = 23;
            layout2.Rate = 34.5;
        }
    }
    public unsafe class Union
    {
        public void* Address { get; private set; }
        public int Alignment { get; private set; }
        public Union (void * Address, int Alignment)
        {
            // sanity check Alignment...

            this.Alignment = Alignment;

            // sanity check the Address...

            if ((long)(Address) % Alignment != 0)
                throw new ArgumentException("The supplied address is not aligned as expected.");

            this.Address = Address;
        }

        public ref T AccessAs<T>() where T : unmanaged
        {
            // check that alignment of T matches the Alignment value...

            return ref (*(T*)Address);
        }
    }

    [StructLayout(LayoutKind.Explicit)]
    public struct Outer
    {
        [FieldOffset(0)]
        public Layout_1 L1;
        [FieldOffset(0)]
        public Layout_2 L2;
    }

    public struct Layout_1
    {
        public long Counter;
        public int Depth;
        public int Other;
    }
    public struct Layout_2
    {
        public byte Byte1;
        public byte Byte2;
        public byte Byte3;
        public byte Byte4;
        public double Rate;
    }
}`

**Comment by Korporal** [comment]
Actually this is what the main method _should_ look like:

```
        static void Main(string[] args)
        {
            Union union = new Union(null, 16);

            // layout1 and layout2 each refer to the same memory address.

            ref var layout1 = ref union.AccessAs<Layout_1>();
            ref var layout2 = ref union.AccessAs<Layout_2>();

            layout1.Counter = 23;
            layout2.Rate = 34.5;
        }

```

**Comment by huoyaoyuan** [comment]
Why don't you use common base class and pattern matching? For performence critical code, unsafe should be the right way.

**Comment by tannergooding** [comment]
@Korporal, what is the purpose of the wrapper `Union` class? Why not just do:
```C#
using System;
using System.Runtime.InteropServices;

class Program
{
    static void Main(string[] args)
    {
        Variant1();
        Console.WriteLine();
        Variant2();
    }

    static void Variant1()
    {
        var union = new Union();

        Console.WriteLine(union.layout1);   // Counter: 0; Depth: 0; Other: 0;
        Console.WriteLine(union.layout2);   // Byte1: 0; Byte2: 0; Byte3: 0; Byte4: 0; Rate: 0;

        union.layout1.Counter = 23;
        union.layout2.Rate = 34.5;

        Console.WriteLine(union.layout1);   // Counter: 23; Depth: 0; Other: 1078018048;
        Console.WriteLine(union.layout2);   // Byte1: 23; Byte2: 0; Byte3: 0; Byte4: 0; Rate: 34.5;
    }

    static void Variant2()
    {
        var union = new Union();

        ref var layout1 = ref union.layout1;
        ref var layout2 = ref union.layout2;

        Console.WriteLine(union.layout1);   // Counter: 0; Depth: 0; Other: 0;
        Console.WriteLine(union.layout2);   // Byte1: 0; Byte2: 0; Byte3: 0; Byte4: 0; Rate: 0;

        layout1.Counter = 23;
        layout2.Rate = 34.5;

        Console.WriteLine(union.layout1);   // Counter: 23; Depth: 0; Other: 1078018048;
        Console.WriteLine(union.layout2);   // Byte1: 23; Byte2: 0; Byte3: 0; Byte4: 0; Rate: 34.5;

    }
}

[StructLayout(LayoutKind.Explicit)]
public struct Union
{
    [FieldOffset(0)]
    public Layout_1 layout1;

    [FieldOffset(0)]
    public Layout_2 layout2;
}

public struct Layout_1
{
    public long Counter;
    public int Depth;
    public int Other;

    public override string ToString()
    {
        return $"Counter: {Counter}; Depth: {Depth}; Other: {Other};";
    }
}

public struct Layout_2
{
    public byte Byte1;
    public byte Byte2;
    public byte Byte3;
    public byte Byte4;
    public double Rate;

    public override string ToString()
    {
        return $"Byte1: {Byte1}; Byte2: {Byte2}; Byte3: {Byte3}; Byte4: {Byte4}; Rate: {Rate};";
    }
}
```

**Comment by Korporal** [comment]
@tannergooding - Nothing wrong with that code BUT the "Union" struct in this case is inherently specific to the two data structs. The "Union" wrapper class in my example is truly generic and requires no structs other that the actual data structs themselves.

**Comment by Korporal** [comment]
@tannergooding - If you're referring to [this code](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il) (which I've never seen and seems to be written in IL) then you may be correct. But it does not do any alignmnet checks (but these could be added in principle). That also seems to be "lets refer to struct A as struct B" so is inherently limited to seeing one struct in terms of another rather than "lets refer to the addres as struct A" or "lets refer to the address as struct B" and so on. But otherwise it seems very similar indeed!

**Comment by tannergooding** [comment]
> But it does not do any alignmnet checks (but these could be added in principle).

Yes, you can write your own wrapper to do the alignment checks. However, I'm not sure why alignment checks would be required. The generated IL should work, regardless of how the types are aligned (and in practice the JIT won't let you specify how you want types to be aligned anyways, you need a custom allocator for that).

> hat also seems to be "lets refer to struct A as struct B" so is inherently limited to seeing one struct in terms of another rather than "lets refer to the addres as struct A" or "lets refer to the address as struct B" and so on. But otherwise it seems very similar indeed!

A ref is just a type-safe (and GC-safe) way of saying this is the address of a given type. So the code is exactly saying "lets treat this reference (managed pointer) to struct A as a reference (managed pointer) to struct B".

**Comment by HaloFour** [comment]
Outside of specific interop/marshaling scenarios or for narrow performance use cases is there a lot of reason to try to map the multiple types within a union into the same memory space?

I'd rather that energy be put into type union/intersections and discriminated unions.  I think that those features would have significantly more reach, and neither should require trying to hack around with pointers and unsafe code.

**Comment by ufcpp** [comment]
See the last section of https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-05-14.md

> We could work with the runtime to allow us to overlay different types inside of a struct. For unions where each variant is small, structs would probably be highly preferable from a performance perspective.

It requires CLR changes.

**Comment by ufcpp** [comment]
see also https://github.com/dotnet/csharplang/issues/317

**Comment by tannergooding** [comment]
@ufcpp, it doesn't require CLR changes, it (and other languages already exposing support for discriminated unions) would just benefit from them.

**Comment by ufcpp** [comment]
@tannergooding 
Class unions (F#'s discriminated union) does not but struct unions requires it, especially generic struct unions.

```cs
using System;
using System.Runtime.InteropServices;

// OK
[StructLayout(LayoutKind.Explicit)]
readonly struct Union_Int_DateTime
{
    [FieldOffset(0)]
    public readonly int Discriminator;

    [FieldOffset(4)]
    public readonly int Item1;

    [FieldOffset(4)]
    public readonly DateTime Item2;

    public Union_Int_DateTime(int value) : this() => (Discriminator, Item1) = (0, value);
    public Union_Int_DateTime(DateTime value) : this() => (Discriminator, Item2) = (1, value);
}

// OK
[StructLayout(LayoutKind.Explicit)]
readonly struct Union_String_StringArray
{
    [FieldOffset(0)]
    public readonly int Discriminator;

    [FieldOffset(4)]
    public readonly string Item1;

    [FieldOffset(4)]
    public readonly string[] Item2;

    public Union_String_StringArray(string value) : this() => (Discriminator, Item1) = (0, value);
    public Union_String_StringArray(string[] value) : this() => (Discriminator, Item2) = (1, value);
}

// Compilable but runtime exception
[StructLayout(LayoutKind.Explicit)]
readonly struct Union_String_Int
{
    [FieldOffset(0)]
    public readonly int Discriminator;

    [FieldOffset(4)]
    public readonly string Item1;

    [FieldOffset(4)]
    public readonly int Item2;

    public Union_String_Int(string value) : this() => (Discriminator, Item1) = (0, value);
    public Union_String_Int(int value) : this() => (Discriminator, Item2) = (1, value);
}

// Compilable but runtime exception
[StructLayout(LayoutKind.Explicit)]
struct Union<T1, T2>
{
    [FieldOffset(0)]
    public readonly int Discriminator;

    [FieldOffset(4)]
    public readonly T1 Item1;

    [FieldOffset(4)]
    public readonly T2 Item2;

    public Union(T1 value) : this() => (Discriminator, Item1) = (0, value);
    public Union(T2 value) : this() => (Discriminator, Item2) = (1, value);
}
```
