### ISSUE TITLE
this code can't be compiled. It's look to me it's valid and it should compile.

### ISSUE THREAD

**Issue by anirugu** [dotnet/csharplang#1559]
``` c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestingConsole
{
    enum Test
    {
        A,
        B
    }


    class Program
    {
        static void Main(string[] args)
        {
            var x = Foo(Test.A);
        }


        static string Foo(Test test)
        {
            switch (test)
            {
                case Test.A:
                    return "a";
                case Test.B:
                    return "b";
            }
        }
    }
}
```

In this scenario, I have 2 value for enum, the code will only compile if I define default case in switch. Since there will be no third value for enum it must be not required for compile this code.

I define both case of enum so it should not  make error #cs0161. Please let me know if I am doing it wrong way or it's valid.

**Comment by HaloFour** [comment]
It's possible for an enum to be assigned an invalid value.  It's unfortunate, but it does result in a code path that does not return a value.  This is expected.

```cs
Test t = (Test)999;
Foo(t);
```

**Comment by gafter** [comment]
Your enum has an underlying type of `int`. As such it has 2^32 **valid** values, only two of which have names.

**Comment by anirugu** [comment]
hmm, it's ok then. Thanks for clarifying. It's now clear.
