### ISSUE TITLE
Proposal: if-else expression

### ISSUE THREAD

**Issue by gulshan** [dotnet/csharplang#156]
Chaining conditions to form an expression is already possible in C# with ternary `?:` operator-

```csharp
public CType getType() =>
    IsMethodOrPropertySymbol() ?
        this.AsMethodOrPropertySymbol().RetType
    : IsFieldSymbol() ?
        this.AsFieldSymbol().GetType()
    : IsEventSymbol() ?
        this.AsEventSymbol().type
    : null;
```

But this is not very readable. So, it's not common to see this type of chaining in C# code. Rather, it becomes chain of if-else statements-

```csharp
public CType getType()
{
    CType type = null;
    if (IsMethodOrPropertySymbol())
        type = this.AsMethodOrPropertySymbol().RetType;
    else if (IsFieldSymbol())
        type = this.AsFieldSymbol().GetType();
    else if (IsEventSymbol())
        type = this.AsEventSymbol().type;
    return type;
}
```

But if there were support of if-else expressions, the code will become both concise and readable-

```csharp
public CType getType() =>
    if (IsMethodOrPropertySymbol())
        this.AsMethodOrPropertySymbol().RetType
    else if (IsFieldSymbol())
        this.AsFieldSymbol().GetType()
    else if (IsEventSymbol())
        this.AsEventSymbol().type
    else null;
```

if-else expressions can even replace `?:` in some places for readability, without chaining-
```csharp
double sinc(double x) => x != 0.0 ? Math.Sin(x) / x : 1.0;
double sinc(double x) => if (x != 0.0) Math.Sin(x) / x else 1.0;
```
 Kotlin is already using this construct successfully.

**Comment by jnm2** [comment]
I'm not opposed to this, but I chain ternaries all the time and I usually find them very readable. I tend to put the condition and expression on the same line:

```c#
public CType getType() =>
    IsMethodOrPropertySymbol() ? AsMethodOrPropertySymbol().RetType
    : IsFieldSymbol() ? AsFieldSymbol().GetType()
    : IsEventSymbol() ? AsEventSymbol().type
    : null;
```

**Comment by DavidArno** [comment]
Yes please! ❤️

**Comment by YaakovDavis** [comment]
This will complicate the [default delegate types](https://github.com/dotnet/csharplang/issues/150) proposal.

Consider this code:
```
bool Foo()
{
   ...
}

bool Bar()
{
}

var d = () => if(condition) Foo() else Bar();
```

Currently, under that proposal, `d` in the snippet above resolves to `Action`. 
With if-else expressions, it's unclear whether the `if` is used a statement or an expression, and consequently, whether `d` should be `Action` or `Func<bool>`.

Also, an expression that reads `if (condition) value else anotherValue` is confusing IMO.
For the above 2 reasons, I propose adding the `then` keyword to the syntax:

```if (condition()) then value else anotherValue```

**Comment by HaloFour** [comment]
@jnm2 

Agreed, I don't find it onerous to use ternary operations in such a manner.  I'll also make the argument that fewer lines of code does not make your program faster.

I could see perhaps a expression-based `switch`/`match` supporting code like this, if it can evaluate against `true` (or does so by default given a lack of operand).

```cs
public CType getType() =>
    return match {
        case IsMethodOrPropertySymbol(): this.AsMethodOrPropertySymbol().RetType,
        case IsFieldSymbol(): this.AsFieldSymbol().GetType(),
        case IsEventSymbol(): this.AsEventSymbol().type,
        case _: null
    };
}
```

The provided use case also looks like it's tailor-made for discriminated unions.

**Comment by DavidArno** [comment]
@YaakovDavis,

Actually, the lambda:
````cs
var d = () => if(condition) Foo() else Bar();
````
would resolve to a `Func<bool>` under that proposal, the following would result in an `Action`:
````cs
var d = () => if(condition) Foo(); else Bar();
````
(note the addition of a single `;` after `Foo()`). 

However, you therefore still raise a good point that I hadn't thought of in my excitement: that minor difference has a huge effect on the code meaning and will likely leave developers scratching their heads over why their code doesn't work as planned, for it's such an easy thing to miss.

Your proposal of `then` is good, but then I read @HaloFour's code. I agree with him that the hopefully soon to delivered `match` pattern matching expression feature makes for even better code. I feel my enthusiasm for `if else` expressions waning therefore. The existing ternary expression covers simple either/or cases and `match` will cover everything else, more neatly than strung-together `if`, `else if` ... expressions.

**Comment by YaakovDavis** [comment]
> note the addition of a single ;

I actually meant to have it (it wouldn't compile otherwise, without if-else expressions).
In any case, I agree that `match` offers a potentially better story.

**Comment by gulshan** [comment]
@YaakovDavis @DavidArno `var d = () => if(condition) Foo(); else Bar();` will not be a valid code I guess. You have to enclose with braces- `var d = () => {if(condition) Foo(); else Bar();}`. If you compare now-

```csharp
var d = () => {if (condition) Foo(); else Bar();};
var d = () => if (condition) Foo() else Bar();
```
The difference is obvious IMHO.

**Comment by DavidArno** [comment]
@gulshan,

Ha, that'll teach me to not post code without checking it compiles first! You are of course correct: the `{}`'s are needed and that does make the difference between the action and func a lot more obvious.

**Comment by Thaina** [comment]
I will not oppose this but I think `?:` is already do it jobs well. And for me if there are nested I would use parentheses

**Comment by gulshan** [comment]
@HaloFour I admit that, there will be many situations covered by proposed `match` expression, but not all. Especially the example I used here is not a good fit for match expression IMHO. Because I am not matching an expression against other values/expressions/patterns. I am calling some bool-returning-methods and conditionally evaluating corresponding expressions.

BTW, I code I have used is real codetaken from [Roslyn](https://source.dot.net/#Microsoft.CSharp/Microsoft/CSharp/RuntimeBinder/Semantics/Symbols/Symbol.cs,03b019fb14196741). And what is the current proposal for match expression syntax?

**Comment by DavidArno** [comment]
@gulshan,

I suspect `match` won't (and probably shouldn't) work this way, but it *could* be used for your example:
````cs
public CType getType() =>
    true match (
        case * when IsMethodOrPropertySymbol() : AsMethodOrPropertySymbol().RetType,
        case * when IsFieldSymbol() : AsFieldSymbol().GetType(),
        case * when IsEventSymbol() : AsEventSymbol().type,
        case * : null);
````

(I apologise if the above leaves anyone with bleeding eyes 😁 )

**Comment by JamesFaix** [comment]
This proposal is replacing operators with keywords, which seems to be against the general trend in C#.  (Syntactic bittering, perhaps?)  I agree that chained ternary operator usage can get a little ugly, but the problem is easily solved with parenthesis and whitespace.

**Comment by gulshan** [comment]
@JamesFaix The main use-case of this proposal is readability. I don't see how parenthesis and whiespaces improve readability of the code. For contrast-

```csharp
public CType getType() =>
    IsMethodOrPropertySymbol() ? AsMethodOrPropertySymbol().RetType :
    ( IsFieldSymbol() ? AsFieldSymbol().GetType() :
    ( IsEventSymbol() ? AsEventSymbol().type :
    null ));

public CType getType() =>
    if (IsMethodOrPropertySymbol()) AsMethodOrPropertySymbol().RetType
    else if (IsFieldSymbol()) AsFieldSymbol().GetType()
    else if (IsEventSymbol()) AsEventSymbol().type
    else null;
```

Did you have some other type of formatting in mind?

**Comment by HaloFour** [comment]
This reads just fine to me.

```cs
public CType getType() => IsMethodOrPropertySymbol() ? AsMethodOrPropertySymbol.RetType
    : IsFieldSymbol() ? AsFieldSymbol().GetType()
    : IsEventSymbol() ? AsEventSymbol().type
    : null;
```

If you find that you're piling on too many conditional ops that you're having trouble reading it, maybe you're putting too much into a single expression.  It's not like it's going to run faster that way.

I find the following much more readable than any expression form:

```cs
public CType getType() {
    if (IsMethodOrPropertySymbol()) {
        return AsMethodOrPropertySymbol().RetType;
    }
    else if (IsFieldSymbol()) {
        return AsFieldSymbol().GetType();
    }
    else if (IsEventSymbol()) {
        return AsEventSymbol().type;
    }
    return null;
}
```

And I'm going to be reading it significantly more often than I'm going to be writing it.

**Comment by gulshan** [comment]
I'll just put another example. These are 3 versions of the same lambda-

```csharp
Func<int, int> discount1 = age => age <= 12 ? 10 : age > 70 ? 15 : 0;
Func<int, int> discount2 = age => if (age <= 12) 10 else if (age > 70) 15 else 0;
Func<int, int> discount3 = age => { var x = 0; if (age <= 12) x = 10; else if (age > 70) x = 15; return x; };
```

I'll argue that, the if-else expression version `discount2` is automatically concise and readable. And for other two versions, the programmer has to pay extra attention to keep them readable. This required extra attention may seem trivial, but that's subjective IMHO.

**Comment by Thaina** [comment]
@gulshan As for me the version 2 is not readable as much. And it more likely to make me feel dizzy. Operator is far more better because it will never confuse with variable

As for me

```C#
Func<int, int> discount1 = age => age <= 12 ? 10 : (age > 70 ? 15 : 0);
```

Is the best

**Comment by gulshan** [comment]
My examples using currently proposed switch expression-
```csharp
public CType getType() => switch        // Hoping to omit 'true' before 'switch'
{
    IsMethodOrPropertySymbol() => this.AsMethodOrPropertySymbol().RetType,
    IsFieldSymbol() => this.AsFieldSymbol().GetType(),
    IsEventSymbol() => this.AsEventSymbol().type,
    _ => null
}
```
But will that cover inequalities like proposed-
```csharp
Func<int, int> discount2 = age => if (age <= 12) 10 else if (age > 70) 15 else 0;
```
Or we have to do something like-
```csharp
Func<int, int> discount2 = age => switch { (age <= 12) => 10, (age > 70) => 15, _ => 0 }
```
