### ISSUE TITLE
Prtial inner classes

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1560]
I have a static class named Unicode which has more than 150 static properties. This class is defined inside another class named Pattern, so I put the Unicode class in a separate file like this: 
```
public abstract partial class Pattern
{
   public static class Unicode
   {
   }
}
```

I think it will add some sugar to code if  it's written just as: 
```
public static class Pattern.Unicode
{
}
```
 The Pattern.Unicode is an accepted syntax for namespaces, so it's not strange.
If we want to make Unicode class itself partial, this would be:

```
public static partial class Pattern.Unicode
{
}
```

which is equivalent to:
```
public abstract partial class Pattern
{
   public static partial class Unicode
   {
   }
}


```

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/711.

**Comment by MohammadHamdyGhanem** [comment]
@svick 
Indeed.. Seems all good ideas are already propsed ☺

**Comment by gafter** [comment]
Closing as duplicate.

**Comment by jnm2** [comment]
> Indeed.. Seems all good ideas are already propsed ☺

And with fewer typos. 😉
