### ISSUE TITLE
Should method defaults work like this?

### ISSUE THREAD

**Issue by JerryNixon** [dotnet/csharplang#1562]
Seems to me that returning `default` could easily be inferred.

````csharp
public async Task<(string Intent, double Score)> RecognizeAsync(string text)
{
    return default;
}
````

Why all this?

````csharp
public async Task<(string Intent, double Score)> RecognizeAsync(string text)
{
    return (default(string), default(double));
}
````

Isn't that a little overkill? Acceptable, I suppose, as the long-hand approach.

**Comment by CyrusNajmabadi** [comment]
I'm a little confused.  The first form is legal C# and will be accepted and compiled.  You will get a warning that you're not actually using 'await' in an async method.  But otherwise it's fine.

**Comment by mariocatch** [comment]
Maybe you don't have c# 7.1 or greater targeted, @JerryNixon

**Comment by DavidArno** [comment]
[Sharplab shows that your `default` version compiles just fine](https://sharplab.io/#v2:C4LgbgpgTglgZgTwDQBMQGoA+ABADAAmwEYBWAbgFgAoa7AJnwBUIBnYagb2vx8IGZCADkIA2ADwAKYgQCSAO2AQFSfCgD2AVwBGAGwj4AygGM1UCAEoAfPgBKEEwHM5MAF4QAgiwRyjUogUUAD2BzfABeaxQIOABDDR1gSioAX2ogA=). It does have the warning that @CyrusNajmabadi speaks of, but no errors.

**Comment by JerryNixon** [comment]
Yeah! Works!

**Comment by JerryNixon** [comment]
By the way I am using the ValueTuple package with .NET 4.6.1 in a Bot.

**Comment by JerryNixon** [comment]
I see now I need to target C# 5.1 to get it to work.
