### ISSUE TITLE
A base type as a placeholder for acutual child type!

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1566]
I face some situations in OOP where I want C# and VB.NET to do some of repeated none-creative work for me! 
One of these situations is having to re-define all the constructors of the base class in its children, and they just call the corresponding base class constructors without doing any thing else! I hope every child class do that implicitly, and if I need to do more in one constructor, I can write it explicitly.
But most important, I want to customize the return value of methods defined in the base class, so they return an instance of each child instead returning an instance of the base class.
Lets take an example. I have this base class:
```
public abstract partial class Pattern
{
    public Pattern Repeat(uint min, uint max, RepeatMode behavior = RepeatMode.Greedy)
    {
       // ………
    }

    public Pattern Repeat(uint times, RepeatMode behavior = RepeatMode.Greedy)
    {
       // ………
    }

    public Pattern RepeatAtLeast(uint times, RepeatMode behavior = RepeatMode.Greedy)
    {
   // ………
    }

    public Pattern OnceOrMore(RepeatMode behavior = RepeatMode.Greedy) => Repeat(1, 0, behavior);
    public Pattern NoneOrMany(RepeatMode behavior = RepeatMode.Greedy) => Repeat(0, 0, behavior);
    public Pattern NoneOrOnce(RepeatMode behavior = RepeatMode.Greedy) => Repeat(0, 1, behavior);
    public Pattern Maybe(RepeatMode behavior = RepeatMode.Greedy) => Repeat(0, 1, behavior);

}
```
I put the repeat methods in the base class, so all the children inherit them. I need to make each method return the type of the class, so I can compose regex verbal expressions as a chain of patterns. So, I used the  Pattern type as the return value of these methods.
By this design I wrote minimum code, and things work fine for all child classes except for a class named CharClass, which defines some operators like - and + and if I call one of the repeat methods from the base class, it returns a Pattern object and I can't use the + or - operators without doing a cast which makes the expressions longer and ugly!
So, I needed to add this code to the CharClass:

```
public new CharClass Repeat(uint min, uint max, RepeatMode behavior = RepeatMode.Greedy)
            => (CharClass)base.Repeat(min, max, behavior);

public new CharClass Repeat(uint times, RepeatMode behavior = RepeatMode.Greedy)
            => (CharClass)base.Repeat(times, behavior);

public new CharClass RepeatAtLeast(uint times, RepeatMode behavior = RepeatMode.Greedy)
            => (CharClass)base.RepeatAtLeast( times, behavior);

public new CharClass OnceOrMore(RepeatMode behavior = RepeatMode.Greedy) 
            => (CharClass)base.Repeat(1, 0, behavior);
public new CharClass NoneOrMany(RepeatMode behavior = RepeatMode.Greedy) 
            => (CharClass)base.Repeat(0, 0, behavior);
public new CharClass NoneOrOnce(RepeatMode behavior = RepeatMode.Greedy) 
            => (CharClass)base.Repeat(0, 1, behavior);
public new CharClass Maybe(RepeatMode behavior = RepeatMode.Greedy) 
            => (CharClass)base.Repeat(0, 1, behavior);

```
Obviously, all this long code do nothing but calling the base methods and cast their return values to the CharClass type!
So, I asked myself: why can't the base method return the actual type of the caller class?
Actually I faced a similar problem with the params of the overloaded operators. If I define The operator in the base class I can't use them with operands of the child types, and if I defined them in the children, I can't use them with operands of the base type!
So, I think these problems need someway to tell C# what the actual type we want to use instead of the base type, which can be done by marking  each method or operator by some attribute to say what behavior we expect from the return value and params in the children.
Of course it will be better if we can use a type list to allow a param or a return value to be one of the supplied list of types. We had this discussion before.
But now, I can think of an easy solution: enclose the base type by []  to tell C# to substitute it with the child that calls the method:

```
public [Pattern] Repeat(uint min, uint max, RepeatMode behavior = RepeatMode.Greedy)
{
       // ………
}

```
C# can generate the needed  wrapper in each child class to call the base method and cast it to the actual type, or the compiler can do this directly in run-time if this is possible.
 
I want to do things in my life other than "copy, paste and modify" without any actual added value!

**Comment by Joe4evr** [comment]
#169
#252

**Comment by MohammadHamdyGhanem** [comment]
@Joe4evr 
Seems a popular demand. Why didn't it hapen yet?

**Comment by MohammadHamdyGhanem** [comment]
@Joe4evr 
And waht about this part:
> One of these situations is having to re-define all the constructors of the base class in its children, and they just call the corresponding base class constructors without doing any thing else! I hope every child class do that implicitly, and if I need to do more in one constructor, I can write it explicitly.

**Comment by bondsbw** [comment]
I prefer the flavor where the return type is `this`.

**Comment by MohammadHamdyGhanem** [comment]
@bondsbw 
I wrote this b4 I know about other proposals, but after I read about this return type, I fall in love with it 😀.

**Comment by jnm2** [comment]
@MohammadHamdyGhanem So maybe close this one since the existing proposals cover what you want in a way that you like even better?

**Comment by MohammadHamdyGhanem** [comment]
@jnm2 
No, there still some other points in this issue, like repeted empty constructors.

**Comment by bondsbw** [comment]
@MohammadHamdyGhanem Inheriting constructors is covered in #806.

**Comment by MohammadHamdyGhanem** [comment]
@bondsbw 
The last thing: the overloaded operators should accept parameters of the base type or any of its children. This need no new keywords.

**Comment by bbarry** [comment]
As an aside, I think your mutable design is non-ideal. 

Instead of 

    public new CharClass Repeat(uint min, uint max, RepeatMode behavior = RepeatMode.Greedy)
            => (CharClass)base.Repeat(min, max, behavior);

you should have something like:

    public new CharClass Repeat(uint min, uint max, RepeatMode behavior = RepeatMode.Greedy)
            => new CharClass(this, new GeneralizedRepeatQuantifier(min, max, behavior));

Fluent apis that depend on mutating state are generally frustrating garbage because they wind up only working in the ways that the designer planned for.  A better api wouldn't make assumptions about how it is used and would simply declare what it is expressing.

**Comment by CyrusNajmabadi** [comment]
> Thanks for the hint, but I prefer my design. CharClass can not declare instances becuase it is abstract base class for positiveCharClass and NegativeCharClass classes.

Even if you're an abstract base class, you can have instances of it.  This is a core part of how .net and C# work.  Take a look at the Roslyn syntax model to see how this works.  You have abstract base types (like 'ExpressionSyntax'), which you can have instances of, with many concrete subclasses (and even some abstract derived types).  

The point was not baout abstract/concrete.  It was about immutable/mutable.  With the former being much better for a lot of scenarios.

Note: as i linked you to in a previous conversation, the Regex ssystem i created for roslyn is built off of creating immutable trees.  There are a lot of benefits to this approach that make the design simpler and avoid a lot of problematic scenarios :)

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
I use the imutable approach. Repeat methods make a memberwise clone of the current instance, apply the repeat to, and return it. I can't creat a new instance, since it will lose all the values. A clone is the solution.
This allows me to use Pattern variables more than once in the expression, without messing things up.
