### ISSUE TITLE
Proposal: auto-property for full get/set redirection

### ISSUE THREAD

**Issue by wiz0u** [dotnet/csharplang#1571]
I am thinking about being able to write this:

    public int Timeout <=> _session.Timeout;
as a syntactic sugar for:

    public int Timeout { get { return _session.Timeout; } set { _session.Timeout = value; } }

This seems like a natural extension of the existing expression-bodied syntax for getter-only property:

    public int Timeout => _session.Timeout;

**Comment by jnm2** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/1007.

**Comment by wiz0u** [comment]
Indeed
