### ISSUE TITLE
Add overload of StreamReader.ReadLine() to include line endings

### ISSUE THREAD

**Issue by dfoverdx** [dotnet/csharplang#1572]
I'm writing code that parses a file which has mixed line endings--`\n` and `\r\n`.  New lines within quoted strings use `\n`, while new lines out of strings use `\r\n`.  For simplicity, I would like to use `StreamReader.ReadLine()` rather than implementing my own method using a buffer, but I need to preserve the line endings from the file.  As far as I know, it is not currently possible to detect which line ending was used when using `StreamReader.ReadLine()`.

**Comment by stakx** [comment]
Hi @dfoverdx, your request does not target the C# language (which is what this repository is concerned with) but the Framework Class Library ([dotnet/corefx](https://github.com/dotnet/clr)).

**Comment by dfoverdx** [comment]
@stakx Thanks!  I Googled ".net framework feature request" and this was what came up.
