### ISSUE TITLE
Quickly adding items to Collections when Initializing/

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#1575]
This should work.  Notice I'm using += to add an item to the collection. 
````
public class Person {
  public string Name {get; set; }
  public List<Person> Children {get; private set;} = new List<Person>();
}

var TestPerson = new Person(){
  Name = "Bob Smith",
  Children += { 
    new Person(){
      Name = "Jessica Smith"
    }
  }
};
````

**Comment by HaloFour** [comment]
> This should work.  Notice I'm using += to add an item to the collection.

That's why it doesn't work.  Use `=` instead.

**Comment by TonyValenti** [comment]
@HaloFour Wow!  Didn't know you could do that!  I always wondered why the member was listed.  Thanks!
