### ISSUE TITLE
Unexpected behavior in overloaded indexers and methods

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1576]
I have This:
```
        public enum RepeatMode
        {
            Greedy = -1,
            Lazy = -2
        }

        public class Pattern
        {
            public string this[uint min, uint max, RepeatMode behavior = RepeatMode.Greedy] => "1";
            public string this[uint times, RepeatMode behavior = RepeatMode.Greedy] => "2";
        }

```
Now, when I execute this code:
`MessageBox.Show( new Pattern()[2, 0]);`

The message box show "2", while I expect "1"!
This means that ` [2, 0]` called 
`this[uint times, RepeatMode behavior = RepeatMode.Greedy]`
C# doesn't allow implicit conversion from int to Enum, and even there is no member of the enum that has a 0 value!
Why does this happen?

Note: 
The same happens with overloaded methods. Add this to the Pattern class:
```
            public string Foo(uint min, uint max, RepeatMode behavior = RepeatMode.Greedy) => "1";
            public string Foo(uint times, RepeatMode behavior = RepeatMode.Greedy) => "2";
```

And then test this code:
`MessageBox.Show(new Pattern().Foo(2, 0));`

The message also shows "2"!

**Comment by HaloFour** [comment]
Curious, it seems to only implicitly convert to the enum when the second argument is `0`.  If that argument is any positive integer it calls the expected overload.

**Comment by Neme12** [comment]
There is an implicit conversion from an integer literal whose value is 0 to any enum.

**Comment by Neme12** [comment]
Hm, that's interesting, the compiler actually allows it from any expression whose constant value is 0:
```c#
class C
{
    void M()
    {
        const int zero = 0;
        RepeatMode m = zero;
    }

    enum RepeatMode
    {
        A, B
    }
}
```

**Comment by HaloFour** [comment]
> C# doesn't allow implicit conversion from int to Enum

It does when the int is a literal of 0.

> and even there is no member of the enum that has a 0 value!

The compiler doesn't validate the members of the enum when converting.

It looks like you're stumbling on a somewhat unintuitive implicit conversion precedence rule.

**Comment by Neme12** [comment]
> C# doesn't allow implicit conversion from int to Enum

There is a different between conversion from a type and a conversion from an expression.
```c#
class C
{
    void M()
    {
        var x = 5; // 5 is of type int
        short i = 5; // compiles even though there's no implicit conversion from int to bool
    }
}
```

**Comment by svick** [comment]
This is the expected behavior. From [the spec, section *Implicit enumeration conversions*](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#implicit-enumeration-conversions):

> An implicit enumeration conversion permits the *decimal_integer_literal* `0` to be converted to any *enum_type* […]

Since the literal `0` has implicit conversions to both `RepeatMode` and `uint`, both overloads are applicable. I believe the `"2"` overload is considered better, because it does not use a default value for any parameter.

**Comment by eyalsk** [comment]
At first I really thought that the reason you get 2 should be obvious.

Anyway, the issue you're having aside, I really think that you better off with something like this:
```
public class Pattern
{
	public string GreedySomething(uint min, uint max) => "1";
	public string LazySomethin(uint times) => "2";
}
```
I think that using an enum in this case is counterintuitive.

**Comment by svick** [comment]
@Neme12

> Hm, that's interesting, the compiler actually allows it from any expression whose constant value is 0:

[That's actually an intentional spec violation:](https://github.com/dotnet/roslyn/blob/292e598/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs#L1062-L1066)

```c#
// SPEC: An implicit enumeration conversion permits the decimal-integer-literal 0 to be converted to any enum-type 
// SPEC: and to any nullable-type whose underlying type is an enum-type. 
//
// For historical reasons we actually allow a conversion from any *numeric constant
// zero* to be converted to any enum type, not just the literal integer zero.
```

**Comment by MohammadHamdyGhanem** [comment]
Thanks all.
I suggest that C# checks the enum value, and if it's not defined , then C# chooses another overload with a non enum param, if there is one. This will give us a way to solve such issues, by just giving the enum members non zero values.

**Comment by svick** [comment]
@MohammadHamdyGhanem That would be a breaking change. Considering that the compiler currently intentionally violates the spec just to avoid a breaking change for code that was previously compiled using the older, buggy native version of the compiler, I don't see a breaking change being introduced here.

**Comment by MohammadHamdyGhanem** [comment]
This is my workarroun to solve the issue:
```
            public string Foo(uint min, uint max, RepeatMode behavior = RepeatMode.Greedy) => "1";
            public string Foo(uint times, RepeatMode behavior = RepeatMode.Greedy)
            {
                if (behavior == 0)
                    return Foo(times, 0, RepeatMode.Greedy);

                return "2";
            }
        }
```

**Comment by jnm2** [comment]
That's what csc's `/features:strict` (`<Features>strict</Features>` in .csproj) is for.

**Comment by Neme12** [comment]
> This is my workarroun to solve the issue:

![image](https://user-images.githubusercontent.com/11444821/40685210-df4d46d8-6393-11e8-93a2-5593b3bf7173.png)

**Comment by MohammadHamdyGhanem** [comment]
@svick 
I think what I suggest will not break any thing. Who would write two overloads like this and send zero to choose to call the one with the enum not the int ?

@jnm2 
Please explain or give me a link.

@Neme12 
It works fine for me. I can't change my design because it is perfect for the job.

**Comment by MohammadHamdyGhanem** [comment]
This code will call the first overload:
            MessageBox.Show(new Pattern().Foo(2, (uint)0));
Seems that C# preferes to cast to enum over casting to uint!
As I said, I prefer the workqrround than using this cast, becusae I write verbal Expressions to generate regex, and I want them to be as short and readable as possible.
Thanks all

**Comment by tannergooding** [comment]
> Who would write two overloads like this and send zero to choose to call the one with the enum not the int ?

@MohammadHamdyGhanem, there are a number of scenarios, when using enums, where you might support values outside those strictly defined.

Some examples include:
* Values that exist for internal/debug usage
* Values which were removed (sometimes a source-breaking change is find, but a binary-breaking change is not)
* Serialization/Deserialization support
* Future-compat (sometimes you just pass the value through to another method, such as native code, and it understands the value where you do not)
* etc

**Comment by tannergooding** [comment]
Most of these scenarios exist and can be found within one or more enums in the greater dotnet codebase on GitHub.

**Comment by eyalsk** [comment]
> This is my workarroun to solve the issue:

Why don't you check whether the value is legal and if not throw an exception? I mean, what are you doing?

**Comment by MohammadHamdyGhanem** [comment]
@tannergooding 
I understand, so I have said nothing about previnting enum from dealing with other undefined values. What I am saing is about how c# resolves the overload resolution: If there is such confusion, C# should prefer to pass the zero to any integral param if exists, rather than passing it to an enum than doesn't define a zero value. I think this makes sense.

**Comment by eyalsk** [comment]
@MohammadHamdyGhanem 

> C# should prefer to pass the zero to any integral param if exists, rather than passing it to an enum than doesn't define a zero value. I think this makes sense.

But @svick already linked the spec to you and it can't be changed at this point because it's more than easy to assume that there's code in the wild that is dependent on this exact behaviour.

**Comment by MohammadHamdyGhanem** [comment]
@eyalsk
I use zero as an indication for infinity. (2, 0) should generate {2,} in regex. (0, 0) will generate *.
I don't expect user to do that directly, becuase I gave him alternatives, but I use this internally in my code. I used uint type to prevent passing negative values. May be we also need some positive non-zero natuarl types!
Any way, my code works fine now. 
Thanks.

**Comment by tannergooding** [comment]
> If there is such confusion, C# should prefer to pass the zero to any integral param if exists, rather than passing it to an enum than doesn't define a zero value.

Right. This might make more "sense", but as others are indicating it is a breaking change.

The current behavior (implicitly converting 0 to the enum) is behavior that has been around for a very long time (at the very least since C# 2.0, from my tests).

This means that there is at least 15 years of code that "could" be using this syntax (I haven't done any code searches to find if there is any code using it yet).

That isn't to say getting the breaking change is impossible, just that it would be much harder to do, since the functionality has been the current way for so long.

C#, as a language, takes back-compat fairly seriously and there needs to be very good reason for taking existing code and silently changing its behavior.

**Comment by MohammadHamdyGhanem** [comment]
@eyalsk 
I'm not asking to prevent this conversion. But C# in this issue has two possible conversions to make: 
1- Cast zero to uint.
2- Cast zero to RepeatMode.
There are two signs for c# that should make it prefer 1 over 2:
1- RepeatMode has no zero member.
2- There is another overload that fits, and if c# choeses it , then there will be already a defualt value for the RepeatMode, so it is not likely that the caller mean to pass a zero to RepeatMode, as he has other easer ways to do so! 
I'm not talking about changing any enum rules. I talk about how C# should chosse the most likely overlaod.
Thanks.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> I'm not talking about changing any enum rules. I talk about how C# should chosse the most likely overlaod.

That's still a change, and a potentially breaking one.  It's probably so narrow as to not actually affect any real code out there, but that potential still has to be weighed against the effort to make the change.

An easier alternative might be to accept `int` instead of `uint` as these parameters.  The C# compiler prefers `int` to `enum`.

**Comment by MohammadHamdyGhanem** [comment]
@tannergooding 
The break will happen in this conditions:
There are a method with two ot more overloads, one of them has an enum param, and another has an integral type,  and the designer passes zero to this method, with the intention to be passed to the enum param not to the integral param! Who on earth would do such a thing and why?
May be you need to do a survey about this specific case, to see if such a programmer has ever existed :)

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
> The C# compiler prefers int to enum.

This is another problem. Since Positive integer types appeard, it seems if it is still strange on the language. I asked once in CoreFx to change all properties that only accept positive values such as wisth and length.... to be of type uint instead of int. I know it is a massive breaking change, but why this doesn't happen in every new member added to the framework? Why should every thing be an int even if it doesn't accept negative values? Seems thst positive types are added and forgotten!

**Comment by tannergooding** [comment]
@MohammadHamdyGhanem, right, but still a breaking change. 

Ex:
```C#
public enum ClassStyle
{
	Caption,
	SysMenu,
	ThickFrame,
	MinimizeBox,
	MaximizeBox
	OverlappedWindow = Caption | SysMenu | ThickFrame | MinimizeBox | MaximizeBox
}

[DllImport("User32.dll", CharSet = CharSet.Unicode)]
private static extern IntPtr CreateWindowW(
	string className,
	string windowName,
	ClassStyle style,
	int x,
	int y,
	uint width,
	uint height,
	IntPtr parent,
	IntPtr menu,
	IntPtr instance
	IntPtr param
);

public static IntPtr CreateWindow(string title, uint size, ClassStyle style = ClassStyle.OverlappedWindow)
{
	return CreateWindowW("GeneratedClassName", title, style, int.MinValue, int.MinValue, size, size, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);
}

public static IntPtr CreateWindow(string title, ClassStyle style = ClassStyle.OverlappedWindow)
{
	return CreateWindowW(title, 0x80000000, style);
}
```

I haven't explicitly defined `0`, but it is still a valid value for `ClassStyle` and it is perfectly valid for the user to pass in.

Now, if we take the breaking change, my UI interop code silently breaks when I recompile.

**Comment by tannergooding** [comment]
>  I know it is a massive breaking change, but why this doesn't happen in every new member added to the framework?

Because you shouldn't have to add an `unchecked((int)value)` or vice versa (`unchecked((uint)value)`) anytime you need to move from an API that uses one to an API that uses the other. It just becomes a major pain.

Consistency ends up making the experience altogether better.

> Why should every thing be an int even if it doesn't accept negative values? Seems thst positive types are added and forgotten!

Plenty of reasons. Negative values allow you to differentiate between `default` and `invalid` (as an example). And yes, there are other ways to do that as well. However, .NET and C# started out nearly 20 years ago, before 64-bit computers were mainstream. Plenty of older code does whatever it can to save space (given that most uses didn't have 4GB of RAM, and even then an app only had access to 2GB, unless it explicitly compiled with access to 3GB).

**Comment by tannergooding** [comment]
At this point, it is mostly for consistency. There are hundreds of millions of lines of code written in C# and that use the .NET Framework, we don't want to break that existing code and we want to continue allowing new code to work with all the older code as well.

**Comment by MohammadHamdyGhanem** [comment]
@tannergooding 
From many issues like this, I think there is a need for a transition in CoreFx and Roslyn like that happened from EF 6 to EF core. I expect that the framework will stop at some point and CoreFx will dominate. Core Fx was an apportunity to get rid off all ,framework past, but it didn't happen!
I know this is not posiible now becuase you opened many doors at once and many work is not done yet, but this can be possible someday when things settles down.
Thanks.

**Comment by gafter** [comment]
Every enum has a "zero" member. It is the default value of that enum. That isn't going to change.
