### ISSUE TITLE
Need Multiline Tab in Visual Studio while working with many tabs

### ISSUE THREAD

**Issue by frozenprakash** [dotnet/csharplang#1580]
Need Multiline Tab in Visual Studio while working with many tabs.
This is a very important feature missing for a long time in visual studio.

![image](https://user-images.githubusercontent.com/16418079/40721930-88547716-6438-11e8-9ed1-aa224b46dd3f.png)

**Comment by ethanae** [comment]
@frozenprakash can you please provide an example of what you mean exactly?

**Comment by ethanae** [comment]
@frozenprakash this wouldn't be correct place for this as it doesn't concern the C# language. This is an IDE query. You should probably go to [Visual Studio UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide) or refer to [MSDN docs for feedback and bugs](https://msdn.microsoft.com/en-us/library/zzszcehe%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)

**Comment by frozenprakash** [comment]
Updated with an image in above comment, For these list of files we open in visual studio, only one line is visible, and then we need to press right arrow to see the hidden files.

To avoid this, we can have a Multiline tabs to see all the list of files open.

**Comment by zippec** [comment]
@stuartstein777 Only if you have "Environment -> Tabs and Windows -> Show pinnd tabs in a separate row" checked

**Comment by frozenprakash** [comment]
Yeap, sorry about it, will post this question in Visual Studio feedback.
And i'll remove this question soon from this repo.

**Comment by frozenprakash** [comment]
@stuartstein777  Yes thats the only way around, but still it's not perfect as to have multiline tabs.

**Comment by eyalsk** [comment]
@stuartstein777 Not sure whether you're aware but there's an extension for [it](https://marketplace.visualstudio.com/items?itemName=SergeyVlasov.TabsStudio-documenttabsmanagerforVisualStudioIDE) on market, not sure how much it costs though.

**Comment by robbelroot** [comment]
Allthough i hate to pick out this thread again.. I just want you to save installing and uninstalling because you wonder about pricing after it took like 8 minutes to install and like 10 minutes to uninstall (speedy pc..). Here you can see [the pricing](https://tabsstudio.com/order.html).

**Comment by CyrusNajmabadi** [comment]
Closing. This is not a language issue
