### ISSUE TITLE
Is it an undefined behavior to dereferencing `in` parameter in an unsafe block?

### ISSUE THREAD

**Issue by lxconan** [dotnet/csharplang#1586]
Consider the following code:

```csharp
static void TryModifyReadonlyRef(in int value)
{
  unsafe
  {
    fixed (int* ptr = &value)
    {
      *ptr = 2;
    }
  }
}

[Fact]
public void unsafely_modifies_the_in_parameter()
{
  int value = 5;
  TryModifyReadonlyRef(in value);
  Assert.Equal(2, value);
}
```

The test will pass. I searched the document and did not find description on dereferencing the pointer to a `ref` or `in` parameter (please correct me if I am wrong). So based on my understanding is should be an undefined behavior and should be discouraged. Is my understanding correct?

**Comment by jnm2** [comment]
Why did you close? Did you find the answer?

**Comment by gafter** [comment]
I think this is a reasonable request and we should definitely at least consider doing something about it.

**Comment by lxconan** [comment]
@gafter Thanks. I closed it because I am not sure if I should asking on gitter first -_-.

So according to the C# specification in an *unsafe* context, there is only one kind of pointer. (comparing with the pointers in C/C++, `T *`, `T const *`, `T * const`, `T const * const`.  So, once the address of a struct is assigned to a pointer, it can do anything according to the description to the pointer. 

So at least, I would like to see that the compiler can give us some hint on it to prevent the readonly reference be changed accidentally.
