### ISSUE TITLE
Add the () operator or allow operators with more than two params!

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1589]
I have a Pattern class and I can do and/or operation on patterns. If I need to enclos the resulted pattern expression I do this:
```Pattern p = (pattern1 & pattern2 & pattern3).Enclose() | pattern4;```
To get something like ```(?:pattern1pattern2pattern3)|pateern4```
I tried to use an operator to get rid of the ```.Enclose()``` part, put I faced two problems 
1. I use + and & for other operations. I can't use && because it is not overloadable. I used * but it is confusing.
2. Even if there is a suitable operator, it will enclose two patterns but if there is a third it will yield an expression like this: ```(?:(?:pattern1pattern2)pattern3)|pattern4```
So, I think what if there is a () operator that passes , as a param , the evaluated Pattern object between any optional (),  so I can operat on it as I want.
```public static Pattern operator () (Pattern p) => p.Enclose();```
The same also with [], {}, and <>.

Another solution is to allow us to define operators with more than two params, or an params array!
```
public static Pattern operator & (Pattern p1, Pattern p2, Pattern p3) 
    => (p1.Add(p2).Add(p3)).Enclose();
```

**Comment by MohammadHamdyGhanem** [comment]
Another solution is to allow us to define operators with more than two params, or an params array!
```
public static Pattern operator & (Pattern p1, Pattern p2, Pattern p3) 
    => (p1.Add(p2).Add(p3)).Enclose();
```

**Comment by DavidArno** [comment]
Sorry, @MohammadHamdyGhanem, but to my mind this proposal highlights why it's so important to not loosen the rules around operators. `&` is the bitwise and operator. Using it for a different purpose just obfuscates your code.

What's wrong with `Enclose()` anyway?

**Comment by svick** [comment]
I would find this very confusing. Enclosing an expression within parenthesis is there to change the order of operator evaluation or to make that order clearer, it should not call a function.

**Comment by MohammadHamdyGhanem** [comment]
@DavidArno  @svick 
> What's wrong with Enclose() anyway?

I'm writing a regex builder. The verbal expression written with this builder can be long, and it will be a bit shorter if I git rid of the .Enclose() method.. Example:
```
var xx = AssertNextIs(
    AssertNextIsNot("abc") 
    & (
            (AssertPreviousIsNot("a") & AssertNextIsNot("bc") ).Encolse()
        & (AssertPreviousIsNot("ab") & AssertNextIsNot("c")).Enclose()
        ),
    Group(AnyChar.OnceOrMore(RepeatMode.Lazy)),
    "abc"
    )
    & BackRef(1);
```
The Extra () tells C# how tha operands are orederd, but don't affect my generated regex, so I need to add the .Enclosed() call to do that! I would like to taje advantage of the extra () I wrote to do the two tasks together: Tell C# what to do, and tell my builder what to do! Writting expressions with the .Enclouse() function will be harder, and I expect thst the user will forget calling this method, depending only on the () he add as used to do as a programmer! I want to use WYSIWYG rule!
This issue and others make me think about the limitations of C# overloadable operators. I saw other issues asking for allowing defining any new operator, and I want that too. I consumed +, -, &, | but need more meaningful symbols for somemore operators! 

> & is the bitwise and operator
it's suiatable for any AND operation, so C# didn't force it to retun bool or integer oly. In VB.NET is it also a concatenation operator.

**Comment by CyrusNajmabadi** [comment]
> The Extra () tells C# how tha operands are orederd, but don't affect my generated regex, so I need to add the .Enclosed() call to do that!

You shouldn't need a method for that.  This should be clear from your regex builder what to do.  i.e. if you have:  ```(a & b & c) | d``` then your regex builder should be able to tell if you need ```()``` or not depending on the construct that is actually on the left/right of the operator.  Just store hte information you need in your pattern type, and use that appropriately when building your final string.

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem Can you link to your Pattern class?

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Thanks for the tips.

> Just store hte information you need in your pattern type, and use that appropriately when building your final string.

this will complicat things because I use immutable classes. But I have another solution. Evet pattern class accepts params array, to easily concat patterns. I will enclose concatenated patterns, and if a user don't want enclosing, he can use the & operator instead of the , separator. I did some work to enclose expressions that must be enclosed as ored pateerns and text patterns. I also get rid any unnecessary  () such as one letter string or 2 letter escaped symbol... etc. Using .Enclose() is still necessary in rare situations. This is the best I can do for now.
I will publish the project now (but with no documentation!.. I woll only give some samples) and give you the link. Any suggestions are welcomed.
Thanks.

**Comment by CyrusNajmabadi** [comment]
> this will complicat things because I use immutable classes

Can you explain why this will complicate anything?  I pointed you to my own regex stuff, and i use immutable data types without problem :)

> and if a user don't want enclosing, he can use the & operator instead of the , separator.

One of the good things about systems where you construct forms programmatically is that you generally do not have to be concerned about the final form.  Instead, you just generate the correct string based on the form tehy constructed.

For example, using the [SyntaxGenerator](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs) type, you can easily build syntactic forms using Roslyn.  I can do the following ```g.MultiplyExpression(2, g.AddExpression(3, 4))``` and this will generate ```2 * (3 + 4)```.  However, if you do  ```g.AddExpression(2, g.MultiplyExpression(3, 4))``` it will generate ```2 + 3 * 4```.  Note that the former has parens, and the latter does not.  This is because Roslyn knows when parens are necessary to produce the tree form that was supplied.

This all works, even though these are all immutable classes.

You can do the same with your system.  No need for any overloading of parens.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
I can enclose each pair of Patterns, but this will produce extra unnessecary parenthesis.
Any way, I finally puplished Verex, and you can take lokk at it and make any suitable changes:
https://github.com/MohammadHamdyGhanem/Verex
Hope @DavidArno @svick @srivatsn @migueldeicaza take a look too. 
Thanks.

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem You didn't address the actual points i was making :)

**Comment by MohammadHamdyGhanem** [comment]
I was busy finishing and puplishing Verex :)
So, now you can see the problem yourself :)

**Comment by CyrusNajmabadi** [comment]
I can see your code.  As i've mentioned, Roslyn demonstrates an appropriate solution to this sort of problem.  it doesn't require an overloadable ```()``` operator.  It seems like the regex system you've built would not need it either :)

**Comment by DavidArno** [comment]
@MohammadHamdyGhanem,

> I'm writing a regex builder. The verbal expression written with this builder can be long, and it will be a bit shorter if I git rid of the .Enclose() method...

I'm really struggling with this. It seems pure irony to me. You have taken the terse, symbol-based, syntax of regexes and created a more verbose, and thus arguably easier-to-read, syntax. But now you are asking for improved operator support to allow you to start using symbols to make that syntax more terse. 

It feels to me that you have lost sight of your own goal somewhere. 😊

**Comment by MohammadHamdyGhanem** [comment]
@DavidArno 
No. The () is more readable and meaningful to programers than ().Enclose(), so l follow the exact rples I started with. Being readable doesn't mean adding unnecessary verbals.
Besides, allowing multi param operators can be more efficient in some situations,  beause repeating passing the previous result as an operator can be a burden with large value types, and even arrays where you will reproccess the same elements over and over.
Thanks.

**Comment by MohammadHamdyGhanem** [comment]
@DavidArno @svick @CyrusNajmabadi @srivatsn @migueldeicaza 
I think of tuples as a solution:
I can define some overload operators to do:
```Pattern p = (pattern1, pattern2, pattern3) | pattern4;```
instead of:
```Pattern p = (pattern1 & pattern2 & pattern3).Enclose() | pattern4;```

But the problem is that I need to define so many overlods to deal with two element tuple to 5 element tuple or more! Is there a way to define a Tuple<pattern> that accepts any number of elemnts ot type Pattern?

**Comment by CyrusNajmabadi** [comment]
>  Is there a way to define a Tuple<pattern> that accepts any number of elements of
type Pattern?

No.

> I don't want to add any verbose syntax to my verbal expressions!

The solution to this is to just use Regex.  It's already non-verbose.  When you make a fluent API you're necessarily sacrificing succinctness for verbosity. :)

**Comment by CyrusNajmabadi** [comment]
> instead of:
Pattern p = (pattern1 & pattern2 & pattern3).Enclose() | pattern4;

You still haven't explained why ```.Enclose()``` is necessary.  I've already given multiple examples showing why you shouldn't need that.  So it seems like you're suggesting unnecessary language changes to solve a problem that shouldn't actually exist.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
You are working with a parser, while I am working with a builder. The logic is Different.
() in regex can change its meaning, and as I said, I don't want to add extra () arround every thing just for caution. In fact I'm using (?: ) to avoid unnessecary capture groups, and this makes regex looks complex and unreadable enough.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
>The solution to this is to just use Regex
No, thanks. I will not write any thing like this manually ever agian:
```\b(?:1?\d{1,2}|2(?:[0-4]\d|5[0-5]))(?:\.(?:1?\d{1,2}|2(?:[0-4]\d|5[0-5]))){3}\b```

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi
You are working with a parser, while I am working with a builder. The logic is different.

Please read my post again: https://github.com/dotnet/csharplang/issues/1589#issuecomment-394190714

It is specifically about working with immutable builder patterns and precisely about not needing this sort of parentheses operator even with such a system.

> In fact I'm using (?: ) to avoid unnessecary capture groups, and this makes regex looks complex and unreadable enough.

This is a decision on your part.  You control the entire output of your tree-to-text transformation.  There is no requirement you emit in that form.  You just need to emit in a form that respects the actual tree structure.  Again, i've pointed out how that can be done without needing a paren-operator.  :)

**Comment by CyrusNajmabadi** [comment]
> No, thanks. I will not write any thing like this manually ever agian:

You don't have to.  As mentioned in previous discussions there are ways to build these regexes up in a manner that makes them clearer.  Similarly, you can choose the form that allows you to annotate and document what is going on to make them clearer.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
After some testing, I discoverd I do n;t need the extra Enclose() :)
I thought I need it in expressions that use many look arrounds, but I found out that I can use nested look arrounds, and this solves the problem. This code generates an expression to seact for any thing but abc, ensuring not selectiong any part of the sequence abc:
```
            var x = AssertNextIsNot("abc") +
                         AssertNextIsNot(AssertPreviousIs("a") + AssertNextIs("bc")) +
                         AssertNextIsNot(AssertPreviousIs("ab") + AssertNextIs("c")) +
                         ('a'.Negate() | ("a" + AssertNextIsNot("bc"))).OnceOrMore() ;
```
This generates the regex: ```(?!abc)(?!(?<=a)(?=bc))(?!(?<=ab)(?=c))(?:(?:[^a]|a(?!bc))+)``` 
By the way, in this issue https://github.com/dotnet/corefx/issues/29937, I asked for a negative group expression to simplfy the above just to be ```(?^abc)```

**Comment by MohammadHamdyGhanem** [comment]
The Previous Verex can also rewritten as:
```
            var x = AssertNextIsNot("abc" |
                         (AssertPreviousIs("a") + AssertNextIs("bc")) |
                         (AssertPreviousIs("ab") + AssertNextIs("c"))) +
                         ('a'.Negate() | ("a" + AssertNextIsNot("bc"))).OnceOrMore() ;
```
In which I use the () only to encose the Or expressions, and it works fine!
This verex generates:
```(?!abc|(?<=a)(?=bc)|(?<=ab)(?=c))(?:(?:[^a]|a(?!bc))+)```
which is a bit copact that:
```(?!abc)(?!(?<=a)(?=bc))(?!(?<=ab)(?=c))(?:(?:[^a]|a(?!bc))+)```
and the exactly do the same job.
This particular sample, caused me trouples at first, so I thought I need  .Enclose() method, but now every thing works fine.
Thanks.

**Comment by MohammadHamdyGhanem** [comment]
But in general, arbitrary () can't be anticipated because I don't parse C# code directly,

**Comment by CyrusNajmabadi** [comment]
> After some testing, I discoverd I do n;t need the extra Enclose() :)

> so I thought I need .Enclose() method, but now every thing works fine.
Thanks.

Ok.  So can this request be closed?  If it's not actually needed to solve any real world problems, it's probably not something worthwhile to add to the language. :-)

**Comment by AustinBryan** [comment]
> No. The () is more readable and meaningful to programers than ().Enclose()

`()` is not an operator, at least not in the way you think it is. It's used either in function calls or grouping operations. Overriding it does not make any sense and it would confuse me if I saw it in use in any way other than how it's supposed to be. 

`Enclose()` is *much* more readable and meaningful as what it does is universally understood by it's name. If anyone could make `()` do what ever they want, how is that more readable?
