### ISSUE TITLE
Allow inner struct/class/enum names intersect with member variable names

### ISSUE THREAD

**Issue by rndfax** [dotnet/csharplang#1590]
C++ and Java (or Swift) allows this, but C# doesn't. Here is some C# example:
```c#
class A {
    public enum Mode {
        Read,
        Write,
    }

    public Mode Mode { get; private set; }

    void M(Mode mode) {
        if (mode == Mode.Read) {
            Mode = Mode.Write;
        }
    }
}

class B {
    A A = new A();

    void M2() {
        if (A.Mode == A.Mode.Read) {
            A.M(A.Mode.Write);
        }
    }
}
```
It gives error:
```
error CS0102: The type 'A' already contains a definition for 'Mode'
```

I must change either
* variable name or enum name and get special, kinda overkilled, naming in M2 method of B class (sometimes Mode is just a Mode, not m_mode, not GetMode, not ModeEnum, not ModeMode etc...),
* or I must take out enum definition out of the A class and increase namespace pollution (sometimes Mode is related only to the A class and nothing else)

in both cases this complicates things which could just work out of the box (like in C++ or Java or Swift), isnt'it?

+ https://github.com/dotnet/csharplang/issues/1590#issuecomment-393905303

**Comment by svick** [comment]
@DavidArno A variable of that enum type represents a single mode, so the type should be called `Mode`, not `Modes`.

**Comment by rndfax** [comment]
:) Please, do not try to fix this example! It's just an example. Instead of enum take inner struct or inner class and you will get the same problem.

**Comment by DavidArno** [comment]
@svick, unsurprisingly, I say you are wrong. The type should be plural; the variable should be singular. 

@rndfax,
The problem only occurs:
1. If one nests types (which to my mind at least should generally be avoided as classes are not namespaces and shouldn't be used as such),
2. One insists on poor naming conventions of having types and fields, variables and properties with the same name as a type.

I do not believe it would be good use of the team's time to spend it working around what I see as poor programming practices. Fix the code; not the language.

**Comment by rndfax** [comment]
Ok, here is another example - device emulator! Device has register block, each register have fields and reset values:
```c#
class SuperDevice {
    struct RegisterBlock {
        struct Status {
            public readonly static bool ResetValue = false;
            public bool RxDone;
        }
        struct Control {
            public readonly static u32 ResetValue = 0xdeadbeef;
            public u32 RxAddr;
        }

        Status Status;
        Control Control;
    }

    public RegisterBlock RegisterBlock;

    void M() {
        if (RegisterBlock.Status.RxDone) {
            RegisterBlock.Status.RxDone = false;
            RegisterBlock.Control.RxAddr = RegisterBlock.Control.ResetValue;
        }
    }
}
```

This SuperDevice class must be in one namespace - Emulator. In Emulator there are many-many devices. Each device has registers and fields and etc... So it's logical to have device specific register description inside device itself --- in question about why nesting is necessary sometimes.

To compile this I have to devise suffixes and prefixes to struct names or variable names or make another struct layouts to overcome this. And I've got complications on how to set ResetValue since it's static.

> Fix the code; not the language.

I clearly see C# limitation, if I fix the code I will have tons of struct with tons of names which negatively impacts code readability instead just have everything in one place with straight-forward naming.

**Comment by jnm2** [comment]
@DavidArno That doesn't jive with what I've seen, so I looked it up:

https://docs.microsoft.com/dotnet/standard/design-guidelines/enum:

> **✓ DO** name flag enums with plural nouns or noun phrases and simple enums with singular nouns or noun phrases. 

I don't think it's a great idea to go off on a tangent from the design of the BCL.

**Comment by DavidArno** [comment]
@jnm2,

The design guidelines cause problems as described here. I'm not even remotely interested in following guidelines that cause problems as well as offer poor semantic advice. 🙉

**Comment by jnm2** [comment]
@DavidArno I don't see any evidence for those two claims.

**Comment by masonwheeler** [comment]
The vast majority of the time, when confronted with a "this works in C++ and does not work in C#" issue, the appropriate response is "this is by design."  A lot of the differences in C# *specifically* come from learning from C++'s mistakes, and this is one of them.  Having the same identifier multiple places in the same scope is difficult to work with at the best of times (cf. method overloading) and we really don't want to encourage more of it..

**Comment by eyalsk** [comment]
@masonwheeler

> Having the same identifier multiple places in the same scope is difficult to work with

Why is it difficult? do you refer to parsing? tooling? what exactly?

**Comment by masonwheeler** [comment]
@eyalsk Disambiguation, aka "overload resolution," aka "the thing in the compiler which makes *everything* more difficult," to hear the Roslyn folks talk about it at least.

**Comment by eyalsk** [comment]
@masonwheeler hmm okay?

**Comment by theunrepentantgeek** [comment]
> If follow this statement then 99% of issues here can be closed with such resolution :)

Yes. *Yes.* **Yes!**

And we could concentrate on innovative language features that actually improve the expressiveness and the power of C# as a language instead of debating for the 27th time the merits of making semicolons optional.

**Comment by theunrepentantgeek** [comment]
> Having the same identifier multiple places in the same scope is difficult to work with

> Why is it difficult? do you refer to parsing? tooling? what exactly?

Much more fundamental than that - it causes difficulties for any *future developer* trying to read and understand the code.

Lifting this restriction might make things easier for the original developer, but at the cost of making things significantly harder for any future maintenance developer coming in cold later on.

**Comment by eyalsk** [comment]
> Much more fundamental than that - it causes difficulties for any future developer trying to read and understand the code.

Why?

> Lifting this restriction might make things easier for the original developer, but at the cost of making things significantly harder for any future maintenance developer coming in cold later on.

Why?

Dunno, maybe the following is better.
```
class A
{
	public Internals.Mode Mode { get; private set; }

	public void M(Internals.Mode mode)
	{
		Mode = Internals.Mode.Write;
	}

	public static class Internals
	{
		public enum Mode
		{
			Read,
			Write,
		}
	}
}
```
In general, I don't like to expose nested types at all and think they should be private but I do think that it should be up for the developer to decide and so if this restriction doesn't impose a problem then it should be lifted.

**Comment by theunrepentantgeek** [comment]
> Why?

Because you, as the original developer, know clearly that `Name`, `Name`, `Name`, `Name`, & `Name`,  are five different things and you keep them all separate in your head. You never get confused because you know the whole thing inside out and back to front - you know which one comes from the parent class, which ones come from the nested types.

But, as a maintenance developer coming along six months after you leave the company, I'm reading through all 12,962 lines of code in `Wonderfulstuff.cs` (not counting comments and whitespace) and I've got no idea that the same name has five different meanings until I've spent seven *days* getting my brain tied into a pretzel.

And if you think that no-one would ever create such a monstrosity, then you have a higher opinion of developers than I. 

Illustration: There was this one time when I was complaining to a colleague about a class that was just too big - the source file was over 3,500 lines of code. He was kind enough to point out that it was a `partial` class ... and the piece I was reading was just one (and one of the smaller) of almost two dozen source files for the same class.

**Comment by eyalsk** [comment]
@theunrepentantgeek 

> But, as a maintenance developer coming along six months after you leave the company, I'm reading through all 12,962 lines of code in Wonderfulstuff.cs (not counting comments and whitespace) and I've got no idea that the same name has five different meanings until I've spent seven days getting my brain tied into a pretzel.

So what are you saying? just because there are some poor developers out there that don't bother writing readable code the language should educate the rest about it? 

But just to make my point in the same file you could have the code below (which compile) and still end up with the same "problem" you describe which I don't really think is a problem but do you really think that having nested types and members share the same name will somehow decrease the readability of the code? in my mind, in my opinion, this is one of the things that should be the responsibility of the programmer and not the language.

Now, I really don't know exactly why do we even have this limitation in place but I don't think it has anything to do with readability so I disagree but I do respect your opinion.

```
public enum Mode
{
	Read,
	Write,
}

class A
{
	public Mode Mode { get; private set; }

	void M(Mode mode)
	{
		Mode = Mode.Write;
	}
}
```

**Comment by rndfax** [comment]
@masonwheeler 

> The vast majority of the time, when confronted with a "this works in C++ and does not work in C#" issue, ...

This issue is not about "this works in C++ and doesn't work in C#". I mentioned C++ as just an example to show all of you that it's not something strange I propose, that this is a typical practice in other languages.

> Having the same identifier multiple places in the same scope is difficult to work with at the best of times 

And how exactly it's difficult? Please, provide an example of difficulties. And, please, propose the solution for my real life example https://github.com/dotnet/csharplang/issues/1590#issuecomment-393905303, how should I organize all this.

**Comment by rndfax** [comment]
@theunrepentantgeek 

> Because you, as the original developer, know clearly that Name, Name, Name, Name, & Name, are five different things and you keep them all separate in your head. You never get confused because you know the whole thing inside out and back to front

What you describe is related to everything. Today you can have Name, Name, Name & Name in different namespaces, classes, structs and enums and all of them have different types and meanings. And only the original developer knows exactly what they are and what they for.

Please, consider this example https://github.com/dotnet/csharplang/issues/1590#issuecomment-393905303. What should I do with it?

> we should be writing code that's convenient for future maintenance developers - and that making things convenient for the original author should take a back seat to the longer view. 

Amen.

So, do you have examples in your mind where naming intersection would cause code maintenance inconvenients? Is it really would be inconvenient to understand `if (Mode == Mode.Read)` or `Mode = Mode.Write`?

**Comment by rndfax** [comment]
@eyalsk 

> In general, I don't like to expose nested types at all and think they should be private

Any advice on here https://github.com/dotnet/csharplang/issues/1590#issuecomment-393905303?

**Comment by eyalsk** [comment]
@rndfax Well, I don't know anything about the codebase so I don't think I can give you any useful advice but there are some weird issues with the code when it comes to accessibility, generally, I don't tend to nest public types and if it's private it's going to be private all the way and when I need to expose the data then I'd probably do it through a wrapper of some sort but anyway, without knowing too much and based on the example in your comment I'd go with something like this: 
```
public class SuperDevice
{
	public SuperDeviceRegisterBlock RegisterBlock;

	void M()
	{
		if (RegisterBlock.Status.RxDone)
		{
			RegisterBlock.Status.RxDone = false;
			RegisterBlock.Control.RxAddr = SuperDeviceControl.ResetValue;
		}
	}
}

public struct SuperDeviceRegisterBlock
{
	public SuperDeviceStatus Status;
	public SuperDeviceControl Control;
}

public struct SuperDeviceStatus
{
	public readonly static bool ResetValue = false;
	public bool RxDone;
}

public struct SuperDeviceControl
{
	public readonly static u32 ResetValue = 0xdeadbeef;
	public u32 RxAddr;
}
```
Yes, it's verbose but many times being pragmatic just saves a lot of headaches. 😄

**Comment by masonwheeler** [comment]
@mdfax

> This issue is not about "this works in C++ and doesn't work in C#". I mentioned C++ as just an example to show all of you that it's not something strange I propose, that this is a typical practice in other languages.

If it is "typical practice" in other *languages* (plural,) please provide examples.  All you've given us so far is what's possibly the most un-persuasive example you could possibly come up with.

> And how exactly it's difficult? Please, provide an example of difficulties.

Seriously?  You don't know that overload resolution is one of the most difficult tasks in the entire compiler, that adds complexity to everything it touches and makes *everything* more difficult?

Just try proposing practically any language change at all to the Roslyn guys, and watch.  Almost immediately, one of them is going to say "this will cause problems for overload resolution because [insert scenario here that sounds ridiculously contrived unless you've got enough experience with programming to know that someone, somewhere, had to have been dumb enough to do exactly that at some point] and this would cause the behavior in that scenario to change, breaking compatibility."  The last thing we want is to make that even worse.

**Comment by masonwheeler** [comment]
@rndfax 
>Is it really would be inconvenient to understand `if (Mode == Mode.Read)` or `Mode = Mode.Write`?

Yes!  That's *incredibly* difficult to understand, particularly from the perspective of the compiler!  At least with overload resolution, we have parens there so the compiler knows it's only looking at methods and nothing else.  With this, we're looking at *everything* now, and the identifiers are in the same scope so we can't apply precedence rules.  What if `Mode` (the field, not the type) were a Stream, which has members named `Read` and `Write`?  Which is the correct interpretation of the code?

You're in *way* over your head with a suggestion like this.  Please go and read everything Eric Lippert ever wrote on the design decisions that went into the C# language and the way things work under the hood.  Yes, all of it; I'm not kidding.  It will be a very enlightening experience.  Right now you don't seem to have the technical background to understand the enormous problems that your suggestion creates and why it would be completely infeasible.  This should rectify that.

**Comment by rndfax** [comment]
@masonwheeler 

> If it is "typical practice" in other languages (plural,) please provide examples

Funny, I've already provided two and asked you to provide your examples, but all what you could answer is to ask me again to provide you another example...

>> And how exactly it's difficult? Please, provide an example of difficulties.

> Seriously?

Absolutely.

>> Is it really would be inconvenient to understand if (Mode == Mode.Read) or Mode = Mode.Write?

> Yes! That's incredibly difficult to understand,

Then what about the code which is perfectly correct in today C# language:
```c#
enum Mode {
    Read,
    Write,
}
class A {
    Mode Mode;
    void M() {
        if (Mode == Mode.Read) {
            Mode = Mode.Write;
        }
    }
}
```
As you can see nothing will change if it will be allowed to define enum Mode inside class A.

> What if Mode (the field, not the type) were a Stream, which has members named Read and Write? Which is the correct interpretation of the code?

Please, provide an example already :) So what if it's a Stream? Where the difficulties?
```c#
class A {
    class Stream {
        void Read() { ... }
        void Write() { ... }
    }
    Stream Mode;
}
```
Can you please point where the things will start to break?

What more can I say is that you are missing a whole point here. C and C++ from the beginning of time were able to compile without any problem the following code:
```c
void M() {
    struct A { int a; };
    struct A a;
    a.a = 3;
}
```
And you are saying that these old 20th century languages could do this and now 21th century C# language can't, because it's suddenly becomes difficult?

**Comment by eyalsk** [comment]
@masonwheeler 

> If it is "typical practice" in other languages (plural,) please provide examples. All you've given us so far is what's possibly the most un-persuasive example you could possibly come up with.

Yes, like all of the proposals here are state of the art... 

> Seriously? You don't know that overload resolution is one of the most difficult tasks in the entire compiler, that adds complexity to everything it touches and makes everything more difficult?

Yes, it's complex but I doubt it has anything to do with this issue per se, please if I'm wrong educate me how this issue has anything to do with overload resolution.

> Just try proposing practically any language change at all to the Roslyn guys, and watch. Almost immediately, one of them is going to say "this will cause problems for overload resolution because [insert scenario here that sounds ridiculously contrived unless you've got enough experience with programming to know that someone, somewhere, had to have been dumb enough to do exactly that at some point] and this would cause the behavior in that scenario to change, breaking compatibility." The last thing we want is to make that even worse.

I've read plenty of issues and I doubt most of them had any impact on overload resolution.

> Yes! That's incredibly difficult to understand, particularly from the perspective of the compiler!

Tell us why,,, educate us with code examples, educate us about where in the spec this would impose the sort of difficulties you state. I'm all for learning.

> Right now you don't seem to have the technical background to understand the enormous problems that your suggestion creates and why it would be completely infeasible. 

You claim to have the technical background but provided zero facts for your statements so I'm asking you to do it.

**Comment by eyalsk** [comment]
@masonwheeler Just to add to the examples made by @rndfax:

This works too:
```
class B
{
	public enum Mode
	{
		Read,
		Write,
	}
}

class A : B
{
	public Mode Mode { get; private set; }

	void M(Mode mode)
	{
		Mode = Mode.Write;
	}
}
```

**Comment by rndfax** [comment]
@eyalsk You provided an excellent example: `a.Mode = B.Mode.Read;`. It clearly shows that code is difficult to read by definition --- there is no magic in the language which it's written on, which magically makes all code readable for everyone. One must investigate the code to understand it no matter what.

Another point this example shows is that the code readability is completely depends on the developer skills and nothing else. No matter how good language is, no matter what restrictions it imposes --- only and only the developer is responsible for code clearness --- as you've already said:

> should be the responsibility of the programmer and not the language.

When developer can't simply express logic in one language but can do this in other languages, this makes developer slightly sad :)

**Comment by eyalsk** [comment]
@rndfax 

>  It clearly shows that code is difficult to read by definition 

Typo? :)

**Comment by eyalsk** [comment]
@rndfax 

>  It clearly shows that code is difficult to read by definition

I actually don't think that code have to be difficult to read although it can be when people don't define standards, when people write code that makes sense only for the moment, when people don't treat their  source code as documentation, when people think that a language should be opinionated about how others should write their code.

**Comment by theunrepentantgeek** [comment]
> So what are you saying? just because there are some poor developers out there that don't bother writing readable code the language should educate the rest of us about it?

While I wouldn't phrase it exactly that way, you're pretty close to the mark - the language should *absolutely* constrain us in ways that prevent poor practices.

Here's a simple example:
```
int customer = ...
Customer customer = FindCustomer(customer);
string customer = customer.Name;
```

There are (popular, widely used) languages that permit redefinition of local variables in this way - but C# thankfully does not.

**Comment by eyalsk** [comment]
@theunrepentantgeek 

> While I wouldn't phrase it exactly that way, you're pretty close to the mark - the language should absolutely constrain us in ways that prevent poor practices.

Right and where in the guidelines of a language that permits it the designers wrote that programmers shouldn't name a property after the name of the type.

How did you get to the conclusion that in this particular instance it's a poor practice? how did you get to the conclusion that it hinders code readability.

How did you get to the conclusion that the designers of the C# language disallowed it for reason you state?

> There are (popular, widely used) languages that permit redefinition of local variables in this way - but C# thankfully does not.

Can you point them out? most statically typed languages that I know of do not permit it, not even TypeScript.

**Comment by eyalsk** [comment]
In addition to what I wrote above this issue can also be solved by something as simple as the following but I guess that this is what this proposal is all about.
```
class A
{
	private Mode _mode;
	
	public enum Mode
	{
		Read,
		Write,
	}
	
	public Mode GetMode() => _mode;

	void SetMode(Mode mode)
	{
		_mode = Mode.Write;
	}
}
```

**Comment by eyalsk** [comment]
@masonwheeler Instead of downvoting people provide proofs to your claims so far you've shown none and yet you tell people:

> Right now you don't seem to have the technical background to understand the enormous problems that your suggestion creates and why it would be completely infeasible. This should rectify that.3

Hilarious. 🙄

**Comment by jnm2** [comment]
@masonwheeler That comment made me feel like a bad person for agreeing with some of what you said because the tone is so off-putting.

**Comment by DavidArno** [comment]
At the risk of appearing the biggest hypocrite on the planet, please tone it down a bit @masonwheeler. I agree that overloading names like this is bad practice; it makes for hard to read code as the same label has multiple meanings. But personally attacking @rndfax over this really is uncalled for.

**Comment by eyalsk** [comment]
I'm really curious about this, I don't find any claims to overload resolution being an issue and I have a really hard time to believe this restriction was put due to readability.

I might be wrong, completely wrong even but so far I can't find anything about it and it's sad, it's probably written in the spec somewhere but I couldn't find it.

**Comment by eyalsk** [comment]
@DavidArno 

> I agree that overloading names like this is bad practice

There's no such a thing as overloading names and there IS NO issue with overload resolution here but let's go through few facts.

1. A property is not a method, it's implemented by a method but have unique name such as get_XXX and set_XXX which is just an implementation detail so it wouldn't make sense for the language to say something about properties in the overload resolution section but even then you can't really overload properties because their signature is fixed unlike indexers.

2. Overload resolution describes how the language would resolve two or more methods with different signatures in the same method group.

3. Two classes that has members with the same name can still inherit from one another where one of the members would be hidden and this is where the `new` keyword comes in.

4. A type name has nothing to do with the name of a property or the name of a method in overload resolution but it does when scoping rules are applied.

So the issue here might be related to scoping and not really to overload resolution.

**Comment by DavidArno** [comment]
@eyalsk,

The problem with natural language is that the same word can mean different things in different contexts. When I talk about "overloading names", I'm referring to the English definition of the word, "*to put too many things in or on something*". I'm not referring to "overload resolution" of methods.

I don't care about the compiler; I write code for other people to read first and foremost. The compiler doesn't care about clarity, but I do. When I see `Mode`, I don't want that term to be overloaded with possible meanings; I want it to have exactly one meaning.

This proposal is seeking the opposite. It's asking for it to be possible for arbitrary labels to be able to carry multiple means and for the compiler to resolve that overloading. This benefits the author of the code over those reading it. Therefore this is not a good proposal in my view.

**Comment by eyalsk** [comment]
@DavidArno 

> The problem with natural language is that the same word can mean different things in different contexts. When I talk about "overloading names", I'm referring to the English definition of the word, "to put too many things in or on something". I'm not referring to "overload resolution" of methods.

I see so you chose it deliberately to confuse me. j/k. 😉 

> I don't care about the compiler; I write code for other people to read first and foremost. The compiler doesn't care about clarity, but I do. When I see Mode, I don't want that term to be overloaded with possible meanings; I want it to have exactly one meaning.

Yes the compiler doesn't care about clarity but the designers seems to care for it. 😄 

> This proposal is seeking the opposite. It's asking for it to be possible for arbitrary labels to be able to carry multiple means and for the compiler to resolve that overloading. This benefits the author of the code over those reading it. Therefore this is not a good proposal in my view.

Understood.

**Comment by eyalsk** [comment]
I discussed this with @masonwheeler over Gitter and now I understand what he truly meant and I kinda agree with him and this is maybe the reason for the declaration rules to be the way they are.

To conclude what we discussed I'd just say that the compiler might have to do more work if something like this would fly and as far as I understand this is the concern he has.

**Comment by masonwheeler** [comment]
Just to clarify, for those without a background in compiler design, here's what I meant when I wrote above:

> What if `Mode` (the field, not the type) were a `Stream`, which has members named `Read` and `Write`? Which is the correct interpretation of the code?

To us it's obvious, because assigning a method reference to a field of type `Stream` is semantically invalid.  But that's not the way the compiler looks at it.

Most modern compilers have a multi-pass design, which means you declare a series of operations, some of which have dependencies on others, and perform all of the calculations for one operation before performing the calculations for later stages.  This example would snarl the dependency pipeline, because you need to firmly know what it is you're working with before you can decide whether operations on its members are semantically valid or not.  Changing the rules in this way, then, would most likely* require massive re-engineering of the compiler in order to support an extreme corner case that most developers don't even care about.  This is why I think it's a bad idea.

* Most likely: I don't actually know the specific details of how the pipeline is set up in Roslyn, and it's possible that I'm wrong here.  But it makes sense for it to be done this way.

**Comment by rndfax** [comment]
@DavidArno and @eyalsk (and @theunrepentantgeek ...) are only persons here who consider this proposal from the programmer point of view --- and that what everyone must do here, because csharplang repo is for C# ***language*** development. Everyone here must think from the programmer's view --- we "speak" on this language. And only Microsoft will decide what to implement in **their** language.

@masonwheeler 

> Just to clarify, for those without a background in compiler design

> Most modern compilers have a multi-pass design

> would most likely* require massive re-engineering of the compiler

So, the guy with a background in compiler design, what about C++, Java or Swift compilers which can handle all this? Or they are not modern enough? Your whole argument is based on "this proposal is bad because it's difficult to implement it in C# compiler". You will implement this in C# compiler? No. So why do you aggressively care about technical aspects of the implementation?

As you say:
> most developers don't even care about

then why are you here in the first place? If it will be in the language just don't use it and you will be fine. Why destroy other people dreams which will not affect you anyway?

> learning from C++'s mistakes, and this is one of them

C++, Java and Swift --- they all allow this. So all three of them have the same "mistake". Hmmm, interesting. It seems they just don't have a guy with a background in compiler design :)

Anyway, the following statements must not be in csharplang repo:

> I do not believe it would be good **use of the team's time to spend it working around** what I see as poor programming practices.

> That's incredibly difficult to understand, particularly **from the perspective of the compiler**!

> Changing the rules in this way, then, would most likely* require massive re-engineering of the compiler in order to support an extreme corner case that most developers don't even care about. This is why I think it's a bad idea.

Thank you guys, otherwise Microsoft would have spent all its time trying to support this proposal, but since it's difficult, C# would become slow and difficult and all C# programs would become not readable at all --- neither by humans nor by compilers. And the world would stop, everyone died, the end.

Only Microsoft decides, not you.

@theunrepentantgeek 

> the language should absolutely constrain us in ways that prevent poor practices.

Then design another language :) which does have constraint on this: https://github.com/dotnet/csharplang/issues/1590#issuecomment-394114876 --- which is almost literally the same as what this proposal is about. Or why C++, Java and Swift are still alive since they do not prevent such poor practices? Actually they allow much more, but they are still in top 10 and always be.

**Comment by masonwheeler** [comment]
@rndfax Please read [Minus 100 points,](https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/) as it does a far better job explaining why your argument is completely wrong than I could.

**Comment by rndfax** [comment]
@masonwheeler Neither you nor your link do not explain why in this proposal you concerned only about compiler difficulties and what's wrong with C++, Java and Swift. If this proposal is not supported by most programmers - it's okay, I don't mind really. But it's not okay to not say anything and just send others to read some links or books (and say something about others background if you don't know them very well). Please, do not go off-topic.

**Comment by eyalsk** [comment]
@rndfax I really think that it's great that we have many different kinds of developers with different opinions and I wouldn't dismiss their knowledge so easily, even though I disagree with some people here and their motives I do respect them, it's our job as developers to be open minded and listen despite our disagreements, I know it's hard but we shouldn't take things down to a personal level even when the discussion gets heated and we should definitely try and keep it professional.

**Comment by AustinBryan** [comment]
@rndfax There's loads of things wrong with C++. A pretty fair amount of differences from C++ to C# is features that were removed from C++ because they turned out to be horrible practices that should never be used, like global variables. Also, even if 500 programming languages had a feature, that doesn't make it a good idea or that it's the best idea. That's basically the logical fallacy called "Appeal to Popularity."

If a feature didn't make the transfer from C++ to C# or even Java to C#, odds are they had their reasons. 

As for the workaround, you can use a nested class, like @eyalsk used, but probably make it `private`.
As for why you *are* able to use types that have the same name provided they are in different outer classes, I'm pretty sure that's because they *are* in different outer classes and that makes it easier on the compiler. I don't know. I'm not a compiler expert, that's just my guess.

**Comment by mikedn** [comment]
It's funny how C++ gets given as an example where this works when in fact this is not exactly true:

```C++
struct A
{
    enum Mode
    {
        Read,
        Write,
    };

    Mode m_mode;

    Mode Mode() { return m_mode; }
    void Mode(Mode mode) { m_mode = mode; } // This fails to compile
};
```
Sure, there are ways to make it work. But to claim that this works in C++ is misleading. And in general, C++ has a rather different way of handling names in scopes so attempting to draw parallels between it and C# are kind of useless.

**Comment by eyalsk** [comment]
@mikedn The C# examples failed to compile too due to different accessibility levels which I pointed out.
