### ISSUE TITLE
One Element ValueTuple !

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1595]
A ValueTuple can have one element:
```ValueTuple<int> t;```
But C# doesn't allow to use the syntax 
```(int x) t;```
It accepts only a tuple with  at least two elemnts!
I use valueTuple params to prevent confusion betwen some overloads. For example:
```
void Foo(params string[] x) { }
void Foo(string y, params string[] x) { }
```
when we call:
```Foo("1", "2");```
it will call th overload:
```void Foo(string y, params string[] x) { }```
while it is also right to call the other overload!
This confusion can be solved easily if we have a one element tuple:
```
void Foo(params string[] x) { }
void Foo((string) y, params string[] x) { }
```
so, we can call the second overload like this:
```Foo(("1"), "2");```
This easy trick can allow us to make two overloads with exactly same param types, except one of them is enclosed in ()!
So please, allow us to have a single elemnt valuetuple.

**Comment by HaloFour** [comment]
The syntax `(expression)` is already legal C#, and it does not make a tuple:

```cs
var i = (1);
var s = ("1");
```

**Comment by HaloFour** [comment]
Also relevant is that single-element deconstruction is something that the team want to enable, but since parenthesized constant patterns are already legal C# syntax it will require some additional syntax to make valid:

https://github.com/dotnet/csharplang/issues/1054#issuecomment-393941465

**Comment by stakx** [comment]
I don't think the idea behind is, nor should it be, to help you pick the right method overload. Using C# 7.2 or 7.3, you could probably just disambiguate by including `y`'s name:

```csharp
Foo(y: "1", "2");
```

**Comment by MohammadHamdyGhanem** [comment]
@stakx
C# doesn't allow two overloads differes only by one param name.

@HaloFour 
We can use one element tuple as param only, so, any aditional () passed as argument can be a tuple only if the param is a tuple.

I also came up with another solution, where we use () arround a param as disambiguation not as a tuple:
void Foo(int x, int y) {}
void Foo((int avg), int y) {}
So we call
Foo(5, 3)
Foo((5), 3)
The compiler can convert this to two functions with different names in IL.

**Comment by stakx** [comment]
@MohammadHamdyGhanem:

> C# doesn't allow two overloads differes only by one param name.

And they don't. Look at your methods again: they differ by one parameter, not by a parameter's name.

But I misunderstood, nevertheless. You want overload logic to favour the single-parameter overload instead of the one having a `y` parameter. Specifying `y:` at the call site would then be enough to disambiguate, no one-tuple required for that.

However currently that same technique does not work to select the single-parameter overload, because one cannot qualify a `params` parameter with its name (`x:`). I personally think the current overload selection is just fine as it is.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> We can use one element tuple as param only, so, any aditional () passed as argument can be a tuple only if the param is a tuple.

Parameterized expressions are legal anywhere, including method arguments.

> ```cs
> Foo(5, 3)
> Foo((5), 3)
> ```

Those are both already legal, and they both already mean the same thing.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
> Those are both already legal, and they both already mean the same thing.
Yes, and I suggest to change that, and give (5) another meaning if the param is inclosed in (). This will not break any code, since there is currently no inclosed param, so any existing (5) will still treated as usual!

**Comment by Joe4evr** [comment]
> This will not break any code

How can you be certain of this? Have you seen all the trillions and trillions of lines of code that have been written in C#?

**Comment by svick** [comment]
@MohammadHamdyGhanem 

> This will not break any code, since there is currently no inclosed param, so any existing (5) will still treated as usual!

Currently there is pretty much no difference between `(T1, T2)` and `ValueTuple<T1, T2>`. Are you suggesting that `(T)` and `ValueTuple<T>` should be treated differently in overload resolution? I think that would be very confusing.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

The following is also already legal:

```cs
public string Foo(int i) => "Hello";
public string Foo(ValueTuple<int> t) => "World";

void M() {
    Console.WriteLine(Foo((5)); // prints Hello
}
```

Your proposal would break that.  It's a pretty radical departure from how parenthesized expressions work today, and given your only real use case is to abuse it for this DSL of yours I don't see how it would ever gain any traction.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
I alrady use 2 element tuple to git red of such confusion :
```
public static BalancingGroup BalancingGroup(string otherGroupName, params Pattern[] patterns) {}
public static BalancingGroup BalancingGroup((string thisGroupName, string otherGroupName) groups, params Pattern[] patterns) {}
```
So, I can call:
```
Assert.AreEqual(BalancingGroup("group1", "abc", Didit).Expression, 
       @"(?'-group1'abc\d)");
Assert.AreEqual(BalancingGroup(("group2", "group1"), "abc", Didit).Expression,
       @"(?'group2-group1'abc\d)");
'''
But I failed to do the same in similar situations that need a one element Tuple!

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
> Your proposal would break that.

No. My second proposal has nothing to do with Tuples!
I suggest to enclose the param with () no to define it as a tuple!
```
void Foo(int x, int y) {}
 void Foo((int avg), int y) {}
```
```(int avg)``` is not a tuple. It is just a param enclosed with (). a tuple must have a name like ```(int avg) z```. So, when we want to call this overload we enclose the argument with () too. This will not break any code, because there is no enclosed params out there yet!. If C# fount an encoused argument, if tries to pass it to an enclosed param. If there is not one, it passes it to a regular param!

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

Either way you're asking to have the compiler treat a parenthesized expression as something other the type of the expression.  Whether you think that should be called a tuple or a frob or a rubber duck is irrelevant (it's a womple) and doesn't change the fact that you're redefining what existing syntax means and in a way that breaks all existing expectations and makes zero sense.

The team has already weighed in on womple literals.  The team has already weighed in on unnamed tuple parameters.  This proposal depends on the team both reversing both of those decisions.

**Comment by mrgleba** [comment]
Maybe it should be allowed to create an one-element tuple that has a name assigned:
`(foo: 10)` creates a `Tuple<T1>` and `(10)` creates an `Int32` as usual. And analogously
`IEnumerable<(int z)>` creates creates a `Tuple<T1>` vaiant.
This should be unambiguous to the compiler.

We are trying to achieve an automatic parsing of a HTTP request XML body to a type in a method's parameter. We'd be wanting to be able to declare:
`public static Foo((int x, int y, IEnumerable<(int z)> item)`
so through reflection we'd know to get attributes `x` and `y` from the root element and attribute `z` from child elements named `item`.

Right now we can only do:
`public static Foo((int x, int y, IEnumerable<int> item)`
which doesn't provide us with any information about the attribute name in child elements.

**Comment by gafter** [comment]
@mrgleba Yes, we have discussed that and it is likely we would take that approach.  A zero-element tuple expression could be written `()`.

**Comment by mrgleba** [comment]
Wow! This is big.

Would empty tuple have a similar behavior as unit in F# (ie: method without an explicit return statement returns `()` by deafult and `()` serves as an empty return type/empty statement)?

**Comment by gafter** [comment]
@mrgleba No, there are no proposals to do anything like that.

**Comment by jnm2** [comment]
@mrgleba You might be interested in the discussion in these semi-related proposals: https://github.com/dotnet/csharplang/issues/1279, https://github.com/dotnet/csharplang/issues/1603, https://github.com/dotnet/csharplang/issues/1604

**Comment by jnm2** [comment]
This issue is similar to https://github.com/dotnet/csharplang/issues/575 (proposes the syntax `(1,)` and https://github.com/dotnet/csharplang/issues/883 (doesn't propose a syntax).

**Comment by ja72** [comment]
> The syntax `(expression)` is already legal C#, and it does not make a tuple:
> 
> ```cs
> var i = (1);
> var s = ("1");
> ```

Other languages deal with this by requiring a comma after the _one_ value

```cs
var idata = (1,);
var sdata = ("a",);
```

But sadly C# does not.

**Comment by Shadowblitz16** [comment]
I don't understand why can `(some variable or value)` be a single element tuple? there is no need to enclose something like that unless your doing logical expressions in any case the compiler can just check if the expression inside the `()` is compiled to a value.

for example..
```
var test = ((0==1) ? "ZeroEqualsOne" : "ZeroEqualsZero"); // tuple

var test = (0==1) ? "ZeroEqualsOne" : "ZeroEqualsZero"; // not a tuple

```

**Comment by CyrusNajmabadi** [comment]
> be a single element tuple? 

Because it already has meaning today.

```c#
var test = ((0==1) ? "ZeroEqualsOne" : "ZeroEqualsZero"); // tuple
```

Code like this absolutely exists today (including in projects like roslyn).  We cannot change the meaning of it as it would be far too big of a break.
