### ISSUE TITLE
[Proposal] Add comma delimited case values

### ISSUE THREAD

**Issue by rushfrisby** [dotnet/csharplang#1602]
1) A lot of developers don't know about fall through logic and this could give them some awareness and make it a little easier to type out.

```csharp
int value = 1;
switch(value)
{
	case 1, 2, 3:
		return DoSomething();

	case 4, 5, 6:
		return DoSomethingElse();

	default:
		return null;
}
```

Would essentially be the same as

```csharp
int value = 1;
switch(value)
{
	case 1:
	case 2:
	case 3:
		return DoSomething();

	case 4:
	case 5:
	case 6:
		return DoSomethingElse();

	default:
		return null;
}
```

2) Huge case statements create large vertical gaps in code that make it hard to read. This could tighten up those cases...

```csharp
int value = 1;
switch(value)
{
	case 1, 2, 3, 4, 5, 6, 7, 8, 9, 10:
	case 11, 12, 13, 14, 15, 16, 17, 18, 19, 20:
		return DoSomething();

	case 21, 22, 23, 24, 25, 26, 27, 28, 29, 30:
	case 31, 32, 33, 34, 35, 36, 37, 38, 39, 40:
		return DoSomethingElse();

	default:
		return null;
}
```

**Do you really want to see 40 cases on 40 lines here?**

I realize there are better patterns that can be used but let's not get ahead of ourselves. Unfortunately we all have seen huge case statements and refactoring them into a Strategy Pattern, for example, isn't always in the cards. Adding this type of syntax could help.

**Comment by HaloFour** [comment]
Check out #1350.  It's slightly more verbose but has more applicable scenarios.

**Comment by yaakov-h** [comment]
I think #185 is a bit more conducive to this sort of example. In particular, https://github.com/dotnet/csharplang/issues/185#issuecomment-389428479:

```csharp
switch (x)
{
    case in 1..10: ... ;
}
```

**Comment by Neme12** [comment]
I would prefer #1350 which is a much more general solution.

**Comment by Unknown6656** [comment]
I think that the best solution would be a combination of #185 and #1350:
```csharp
switch (x)
{
    case 3 or 7 or 9..22 or -88:
        // ...
        break;
}
```

**Comment by DavidArno** [comment]
Whilst a combination of #185 and #1350 would be nice, it's worth remembering that pattern matching in C# 7 already significantly solves what the OP is asking for. Those "40 cases on 40 lines" can be expressed as just two cases already:

```cs
switch(value)
{
    case var i when i.InRange(1, 20):
        return DoSomething();

    case var i when i.InRange(21, 40):
        return DoSomethingElse();

    default:
        return null;
}

...

public static bool InRange(this int value, int min, int max)
    =>  value >= min && value <= max;
```

**Comment by AustinBryan** [comment]
Just because it can already be done doesn't mean the shorter syntax isn't a plus. You could say the same thing about properties, that we can do the same thing with methods. It's just sugar.

```csharp
switch(value)
{
    case int i 1..20:   // would much rather type this
        return DoSomething();

    case var i when i.InRange(21, 40):   // than this
        return DoSomethingElse();

    default:
        return null;
}
```

Besides, that isn't the only thing the `..` operator would be able to do.

**Comment by DavidArno** [comment]
@AustinBryan, completely agree. I guess that wasn't clear from my comment.

**Comment by redknightlois** [comment]
@DavidArno Not really, it is not the same thing. With the C# 7.x notation the performance profile is an actual search over an array. With the proposed notation what it is emitted is a perfect hash value straight in code. For that to happen with C# 7.x notation would require static code evaluation a lá C++ templates.

**Comment by YairHalberstadt** [comment]
With C# 9 you can now do:

```csharp
int value = 1;
switch(value)
{
	case 1 or 2 or 3:
		return DoSomething();

	case 4 or 5 or 6:
		return DoSomethingElse();

	default:
		return null;
}
```

Which I think ticks all the boxes you're asking for, so I'm going to close this.

If you still want this considered, let me know and I'll move it to a discussion.
