### ISSUE TITLE
Required in properties 

### ISSUE THREAD

**Issue by cordasfilip** [dotnet/csharplang#1607]
This is an idea I had in another [thread](https://github.com/dotnet/csharplang/issues/1087) but I think it could be useful for other things as well .
Something I always liked are Object Initializers but they become unusable when working with immutable objects and there is no way to force the user of the class to set the property. We could indicate that the property must be used in Object Initializer with in parameter.So if we define a class like this.

```
public class Test
{
    public in string Prop1 { get; set; }

    private in string Prop2 { get; set; }

    public in string Prop3 { get; private set; }

    public in string Prop4 { get; }
}

static void Main(string[] args)
{
    var t1 = new Test(); // Compile time error
    var t2 = new Test
    {
        Prop1 = "",
        Prop2 = "",
        Prop3 = "",
        Prop4 = ""
    };// No error even if we have private fields

}
```
To me this solves two problems with one solution. Makes object initializers work for immutable classes and DI injection could easily fill only the in properties. We would get compile time errors if no property is set and the build will fail if someone change something. This doesn't need to be run-time error really and if someone dose something he was not suppose to let him handle it on his own risk. Since this are just properties everything will work as it dose now with inheritance and partial...
I also think this will be useful for null-able reference types since I don't know how properties will work if you don't have default values for properties, this way you could make a none null-able reference type as in and let the user of the class have to deal with it when creating a new object.

**Comment by stakx** [comment]
I understand where you're coming from, but this proposal doesn't feel quite right to me:

> that the property must be used in Object Initializer with in parameter

I don't like the word "must" here. I think there should be no difference between `var f = new Foo(...) { P = ... };` and `var f = new Foo(...); f.P = x;` and coders should be able to freely choose which form they prefer. The application of what you're proposing would effectively enforce the former syntax, that however may not be everyone's choice.

If a property *must* be set during object initialization, it should be set in the ctor (i.e. via a ctor parameter) because that's what ctors are there for.

> DI injection could easily fill only the in properties.

This sounds appealing, but it feels wrong to adjust the language just to suit the needs of one kind of library. And that need (property injection) isn't even a major, unsolved problem of DI containers. They've managed just fine without the proposed feature for the last x years.

**Comment by cordasfilip** [comment]
@stakx I get what you mean but people sometimes decide not to use immutable objects to avoid gigantic constructors that are just unreadable and take up too many lines of code for nothing. I don't think it's enforcing one syntax just makes it more usable since you can't use it with immutable classes. Your objections are valid but as I see it people can decide not to use it at all since it's just syntax sugar. I just think it will save me a lot of unnecessary lines of code and help me to deal with inheritance with DI.

**Comment by eyalsk** [comment]
> Makes object initializers work for immutable classes

They are looking at this, you can check the [LDM notes](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-10-09.md).

_It should not be strongly tied to the Dictionary<K, V> type, but be target typed
We should look at initializing immutable objects (also for object and collection initializers)_

> DI injection could easily fill only the in properties

You can do that today through an attribute.

> We would get compile time errors if no property is set and the build will fail if someone change something. 

You can perform static analysis to make sure they were initialized but it would probably be a lot cheaper to write an integration test for the container that would make sure that properties on certain types that has a certain attribute have their properties set and then add a build step for it.

**Comment by amis92** [comment]
I'll just link this here, then: https://github.com/amis92/RecordGenerator

*that's exactly what @DavidArno asks for, generation of builders (and ctors, and mutating methods) for immutable types*

**Comment by bondsbw** [comment]
Or the immutable version of `with`.

**Comment by eyalsk** [comment]
@DavidArno Agreed on everything but I do think that the language should provide better and easier ways to construct objects, especially when it comes to immutable objects and collections.

**Comment by cordasfilip** [comment]
As previously mentioned all valid arguments, this might not be the best solution and I think we all agree that there is a problem with this right now  because when working with immutable classes it requires too much boilerplate code. What I wanted with this is to have a shorter way to create immutable objects and have it readable as Object Initializers. Also this was an idea to deal with constructor hell where you have to copy paste a bunch of input fields from the base class. Still would like to see some better way to do this in the future.

**Comment by eyalsk** [comment]
@cordasfilip Just a small suggestion, it's better create a a new issue per proposal than to create a single issue with multiple ones and when you do make sure each proposal stand on its own.

**Comment by jnm2** [comment]
And isn't a duplicate.

**Comment by cordasfilip** [comment]
I am closing this one because it already getting implemented in a similar way.

**Comment by 333fred** [comment]
I just want to be clear @cordasfilip: this is not being implemented currently. We don't have a way of specifying required properties currently.

**Comment by cordasfilip** [comment]
> I just want to be clear @cordasfilip: this is not being implemented currently. We don't have a way of specifying required properties currently.

But this is just a Init-only properties? This was the first thing in Mads blog about c# 9 https://devblogs.microsoft.com/dotnet/welcome-to-c-9-0/
I like my syntax more but I mean it is matter of taste. If they are not required how will this work?

**Comment by 333fred** [comment]
`init` specified that a property _can_ be set with an object initializer. It says nothing about whether the property is _required_ to be set via the object initializer.

**Comment by cordasfilip** [comment]
@333fred O that sound a bit silly if you turn on nullable reference types. So I will still have to ignore the warning or  create an empty object or set everything to null. My thinking was it should be required by default. Will there be a green warning or something for this? For example if it is a nullable type and you don't init it with a value, this just doesn't make sense if you turn on nulls.

**Comment by 333fred** [comment]
No, and these are really orthogonal features. Remember that the nullability of a type doesn't imply anything about whether there is a valid default. A simple example would be this person definition:

```cs
public class Person
{
    public string FirstName { get; init; }
    public string MiddleName { get; init; } = "";
	public string LastName { get; init; }
}
```

All are non-nullable, but one of them has a default because not everyone has a middle name. The required properties would be `FirstName` and `LastName`, but we need a way to communicate this to consumers while also being explicit for the creator. If you forgot to provide a default value for `MiddleName`, it's your problem as the object creator. If a user forgot to supply a `LastName` as a consumer, it's their problem. We need a way for the creator to indicate _explicitly_ that there is no default value, and that consumers are expected to provide one, without breaking swaths of existing code that works fine today.

**Comment by cordasfilip** [comment]
@333fred But this will show a green warning `public string FirstName { get; init; }` so to me this would necessitate that you set the value during init because it's the only place you can do it. I think this can show a green warning on the init and no warning in the class. Because you not setting the default just doesn't make any sense. And if I need a constructor for this I can just add everything.

**Comment by spydacarnage** [comment]
I've seen a Mads talk from early April in which he mentioned consideration
of an after-initialisation block, which could be used similar to how you
get a warning on a constructor saying that a property hasn't been set.  Not
sure if there's any legs in that idea, though, or whether it has already
been dismissed.

**Comment by 333fred** [comment]
> But this will show a green warning `public string FirstName { get; init; }`

First, I'm not sure what you mean by green warning. Do you mean a regular warning, or an info diagnostic, or something else? Not everyone uses the same VS colorscheme so describing diagnostics by color isn't broadly applicable.

NRT would warn on the creator side, just as it would with `FirstName { get; set; }`. The only difference between these scenarios is that in one you can only set the property during object initialization. In both cases you, as the object creator, would like to require that users provide a value for `FirstName`. However, no information is exposed from the object as to whether a default value is provided. From a consumer side, there is _no_ public difference between `FirstName { get; init; }` and `FirstName { get; init; } = ""`. That's the part that we need to add in some fashion, so you can be explicit in API design. Changing that requirement is a breaking a change and should be deliberate on your part.

**Comment by 333fred** [comment]
> I've seen a Mads talk from early April in which he mentioned consideration
of an after-initialisation block, which could be used similar to how you
get a warning on a constructor saying that a property hasn't been set.  Not
sure if there's any legs in that idea, though, or whether it has already
been dismissed.

We considered for a while, but feedback from broader review found that this idea was confusing to consumers so we're reworking it. I don't believe it'll make C# 9, though I could be wrong.

**Comment by spydacarnage** [comment]
We considered for a while, but feedback from broader review found that this
idea was confusing to consumers so we're reworking it. I don't believe
it'll make C# 9, though I could be wrong.

Shame - I thought that might be the case, but I was hoping not.  It looked
like it could solve a lot of the "is the object complete" issues that have
been raised against init properties.

>

**Comment by 333fred** [comment]
> Shame - I thought that might be the case, but I was hoping not.  It looked
like it could solve a lot of the "is the object complete" issues that have
been raised against init properties.

Not really, unfortunately. It would potentially be able to get rid of warnings on the creator side, but wouldn't then enforce warnings on the consumption side, rather deferring them to runtime. We really need a hollistic solution here.
