### ISSUE TITLE
Proposal - Add new keyword fullnameof

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#1609]
There are cases where we might have numerous methods all with the same name but scattered across different classes (e.g. MVC Controllers). In these cases the existing `nameof `keyword gives only the lexical spelling of the simple name and does not include namespaces.

Having `fullnameof `would address this and it would (where applicable) generate the fully qualified name of the item (e.g. a method).

**Comment by yaakov-h** [comment]
Duplicate of #701.

**Comment by DavidArno** [comment]
@Korporal, would you mind closing this please, since it is a direct duplicate?
