### ISSUE TITLE
async doesn't work with Task

### ISSUE THREAD

**Issue by anirugu** [dotnet/csharplang#1622]
Please tell me if I am doing it some wrong way, I am trying it latest preview out there,

This is the code

 public static async Task<string> Test()
        {
            string val = "anirudha";
            return await Task.Run<string>(new Func<string>(() => { return val; }));
        }

and this is the code without Task

   public static async string Test()
        {
            string val = "anirudha";
            return await Task.Run<string>(new Func<string>(() => { return val; }));
        }

it doesn't compiled, I set the latest minor version (latest) and it's still on same track. I try this thing afer reading commit from Mads sir 
here https://github.com/dotnet/csharplang/commit/7b961e73f76c15be8a85c5d61f0db18cfdc72b9e

+Async methods no longer have to return `Task` and `Task<T>`, but can follow a pattern. We don't currently do a similar thing for iterators, but we should think about it, also for async iterators.

Thanks for checking this post.

**Comment by tpetrina** [comment]
This is not really a design issue, you have a bug in your code. use `Task<string>`.

```csharp
public static async Task<string> Test()
{
    string val = "anirudha";
    return await Task.Run(new Func(() => { return val; }));
}
```

**Comment by HaloFour** [comment]
@tpetrina @anirugu 

Actually the requirements for what an `async` method can *return* are quite different as they have to work with the compiler to manage the state machine.  Here's a good blog posting with examples:

https://blogs.msdn.microsoft.com/seteplia/2018/01/11/extending-the-async-methods-in-c/

But you're right in that you can't return "raw" objects, you have to return something that represents a "task", it just doesn't have to be `System.Threading.Tasks.Task` anymore.

**Comment by HaloFour** [comment]
Another doc on the subject:

https://github.com/dotnet/roslyn/blob/master/docs/features/task-types.md

**Comment by anirugu** [comment]
@tpetrina  @HaloFour  thanks for the help,

this means I can't use the async keyword on the raw object but it will work if something is async.

I tried to write some other code, like this, still not get it compiled (in latest preview)

  public static async string GetValues()
        {
            System.Net.Http.HttpClient client = new System.Net.Http.HttpClient();
           return await client.GetStringAsync("http://google.com");
        }

I am calling this async method which is async and it's wrapped by Task<string>. Please help me clarify how it's not compiling.

**Comment by tpetrina** [comment]
Because the return type must be awaitable. String is not.

**Comment by HaloFour** [comment]
@anirugu 

`string` doesn't represent a task.  You need to return a type that represents a "task".  You're out-of-the-box options are `System.Threading.Tasks.Task<string>` or `System.Threading.Tasks.ValueTask<string>`.  Or you can write your own if you follow the guidelines in the above documentation or blog posting.

The language change isn't to allow you to just return the value.  It's to support alternate task types, like `ValueTask<T>`, which is a `struct` and doesn't require additional allocation on the heap.
