### ISSUE TITLE
Add access modifiers to inheritance

### ISSUE THREAD

**Issue by scalablecory** [dotnet/csharplang#1627]
It would be great to add private/protected/internal inheritance, as well as interface implementation, with usage similar to C++. It would also need to be affected by `InternalsVisibleToAttribute`.

```
class Foo : private Bar
{
    public void Go()
    {
        Bar bar = this; // okay.
    }
}

Bar bar = new Foo(); // error.
```

This would allow performance-critical library implementations to reduce GC pressure in certain situations.

One such example is `TaskCompletionSource`: this class is a thin wrapper around a `Task`, and so requires two allocations. Using this example, we can demonstrate benefits:
* We can fold this into a single allocation by having `TaskCompletionSource` privately inherit `Task`, but still allowing a clean separation.
* mscorlib currently "cheats" this clean separation in a few places (e.g. `SemaphoreSlim`) to do exactly this optimization. We could clean up these parts of mscorlib while simultaneously enabling third-party libraries to make this optimization.

**Comment by HaloFour** [comment]
Sounds like this would require some fairly serious CLR changes.

**Comment by yaakov-h** [comment]
```
Bar bar = new Foo(); // error.
```

So how would I get a `Task` out of the `TaskCompletionSource` in your example? Or can only the class itself  perform that cast, but not external consumers?

**Comment by scalablecory** [comment]
@yaakov-h yes, only `TaskCompletionSource` would be able to perform the cast.

```
class TaskCompletionSource<T> : private Task<T>
{
    public Task<T> Task => this;
}
```

**Comment by Pretasoc** [comment]
Since c# doesn't support multiple inheritance, would the public type look like it derived directly from `object`?
