### ISSUE TITLE
Generic constraint enhancements for 'new'

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/csharplang#1633]
Didn't see anything similar to this except possibly the shapes proposal but I might not be searching diligently enough.

We already have support for 'where T : new()'.

That works well for unambiguous construction however if I want to ensure that an instance supports a certain type of constructor I feel I should be able to also constrain the call to such without requiring a specific type;

Example:

'where T : new(ref int)' as well as 'where T : new (T)' or any other valid syntax which may be found on a constructor rather than constraining to a specific type e.g. 'where T : RefCtorClass'.

Constraints may be combined in specific ways where necessary for the underlying code e.g. 'where T : new(), new(T)' thus requiring and allowing the use of both constructors.

This would help with factory patterns where such additional parameters are commonly passed by reference e.g. parsers, serialized types and such.

Currently such patterns are achieved by using type constraint to a class which is known to have such a constructor declared.

Compiler changes required would be minimal as we already perform similar verification for new, we would just modify such logic and ensure the defined syntax matches an available one.

CLR and Spec changes would also be required to accomadate this enhancement but probably not in a backward compatible manner.

Justification for the enhancements would be that we already support the 'new' constraint for almost no reason as the initial class constraint would also take care of the allocation semantics, this enhancement would complement the existing paradigms where the allocation semantics are useful to describe such as those constructors which have ref or out parameters which are useful to the underlying implementation but may also be useful outside of such implementation.

E.g. 'RefCtorClass(ref int pos, out int childrenAllocated)'

Or 

'UnsafeCtor(ref int* source, out int whatever)'

Rather than constraining for and requiring a reference to where 'RefCtorClass' or 'Unsafe Ctor' is defined I can now simply say the type must have this type of constructor...

This would in my opinion allow for generic design patterns which are much more decoupled than can be achieved today.

Would also like to see enhancements for constraints to allow the use of 'ref' and 'in' for constraints e.g. 'where T : ref struct' in addition to the enhancements specified at https://github.com/dotnet/csharplang/issues/1620

**Comment by Pretasoc** [comment]
Duplicate of #769, #1330, #1574.

**Comment by juliusfriedman** [comment]
Indeed, sorry for the added issue. I will close this as your comment serves as a link to those issues which can subsequently be referenced.

Thank you

**Comment by Joe4evr** [comment]
Also literally yesterday's #1626.

*Can everyone **please** learn to search before opening an issue?*
