### ISSUE TITLE
Official documentation/specification of C# "swap" syntax through tuples?

### ISSUE THREAD

**Issue by lassevk** [dotnet/csharplang#1656]
With C# 7 you can do this:

    (x, y) = (y, x);

to swap the contents of two variables. This gets compiled into this:

    ldarg.2 // these were parameters
    ldarg.1
    starg.s 2
    starg.s 1

However, it is nearly impossible finding any official documentation for whether this is just a random byproduct of something else or actually a feature of C# now. Is there any official documentation that mentions this support?

Note that the above code does in no way construct a tuple value, it's entirely syntactic sugar for swapping the contents of two variables, there's plenty of other patterns where a tuple instance isn't created, such as:

    var (a, b, c) = (1, 2, 3);

(sigh, I miss the C# specifications)

**Comment by lassevk** [comment]
I'm aware of this - [Deconstructing assignments](https://github.com/dotnet/csharplang/blob/0709623617764880198f972d66845e88a89fe149/meetings/2016/LDM-2016-04-12-22.md#deconstructing-assignments), but that's more of an open-ended question to me, and not a definitive "this is what we're going to do" type of documentation or specification.

**Comment by ufcpp** [comment]
https://github.com/dotnet/roslyn/blob/master/docs/features/deconstruction.md

> in the special case where the expression on the right-hand-side is a tuple (tuple expression or tuple type), then the elements of the tuple are assigned to the variables on the left-hand-side without calling Deconstruct.

**Comment by bbarry** [comment]
The gist was that wherever the act of tuple usage is not observable, a compiler is permitted to avoid doing so. The ValueTuple class of types are to be "well known" and specified in ways such that some operations involving them can be lowered/desugared into more basic operations.

The spec issue exists here: https://github.com/dotnet/csharplang/issues/59

**Comment by yaakov-h** [comment]
This question might be better suited for https://github.com/dotnet/docs.

There are quite a few things you can do in C# that have come about as unusual combinations of other features.

**Comment by jcouv** [comment]
The language spec posits that the constructor of `ValueTuple` types is free of side-effects. So the compiler can do this optimization.
This optimization was done [on purpose](https://github.com/dotnet/roslyn/pull/20295), and was agreed by LDM, but I don't think it will be called out in the spec.

Note that such a deconstruction can result in a `ValueTuple` being constructed, when the result of the deconstruction-assignment is used.
For instance: `var tuple = ((x, y) = (y, x));`.

**Comment by jcouv** [comment]
I'll go ahead and close this issue, since I think it is answered and I have a PR to update the deconstruction design doc.
