### ISSUE TITLE
IList<T> should implement IReadOnlyList<T> and also an IReadOnyList should exist

### ISSUE THREAD

**Issue by msedi** [dotnet/csharplang#1666]
Currently only List<T> implements the IReadOnlyList<T>, but IList<T> does not implement IReadOnlyList<T>. This is a problem in many cases where only IList<T> is visible on a class and not the actual list. In some situations I have an IList<T> as class properties, and some classes I have need to take a IReadOnlyList<T>. 

Since the IList<T> currently does not "derive" from IReadOnlyList<T> this is often causing problems with the assignment.

Also it would be helpful to have the analogon of a IReadOnlyList as this is the case with IList.
I had some severe problems by using an IReadOnlyList<object> where the contents of the List<T> have been readonly structs.

**Comment by MrJul** [comment]
This repository is for discussing the C# language itself, not the base class library.

Please see https://github.com/dotnet/corefx/issues/5489 for a similar issue.
This would be a breaking change, and as such would probably never happen.

**Comment by msedi** [comment]
You are right. I'm sorry. I will cose it and open it up again in corefx.
