### ISSUE TITLE
Hat operator is inconsistent with regular expression syntax

### ISSUE THREAD

**Issue by ckarras** [dotnet/csharplang#1672]
In regular expressions, the hat (^) symbol is used to mark the beginning of a string, and $ is used to mark the end of a string. 

According to https://neelbhatt.com/2018/05/26/c-8-0-expected-features-part-iv-something-new-for-indexes-and-ranges/, a new operator is planned using this symbol to represent an index relative to the end of the an array:

    var last = myCollection[^1];  // myCollection[Index.CreateFromEnd]

It would make more sense to follow the existing known convention from regular expressions when representing a relative index from the end of a string, instead of making a new convention that's the opposite of the existing one:

    var last = myCollection[1$];

**Comment by scalablecory** [comment]
This should be a comment on #185, not its own issue.

**Comment by ckarras** [comment]
Done, moved to comment on #185
