### ISSUE TITLE
There should be two more labels

### ISSUE THREAD

**Issue by eyalsk** [dotnet/csharplang#168]
Currently, everything is flagged as **Discussion** and I think that it can be improved, slightly.

**Legacy proposal** or **Roslyn proposal** - Proposals that are just a copy/paste from Roslyn.

**Featured proposal** - Proposals that are well formatted and/or follow the [template](https://github.com/dotnet/csharplang/blob/master/proposals/proposal-template.md) this is for the most part like a **Discussion** but I think that it will motivate people to think about their proposals a bit more.

**Comment by DavidArno** [comment]
I agree here. Absolutely everything seems to be a discussion, unless a championed feature. Being able to filter genuine discussions (eg this one) and language proposals from the community would be useful.

**Comment by mattwar** [comment]
I think the idea here is that there are not actual proposals until their are designated champions.  Everything is here just a discussion.  Actual proposals are documents in the repo.

**Comment by eyalsk** [comment]
@mattwar Okay, I just thought that if everything is painted with the same color people are less motivated to improve their proposals and it might be helpful to distinguish between a discussion about and other issues but if you feel that there's no point in it, I can close it. :)

**Comment by eyalsk** [comment]
@gafter Thank you. :)
