### ISSUE TITLE
Proposal: Syntax Hightlighting for Discard

### ISSUE THREAD

**Issue by Ccursed** [dotnet/csharplang#1681]
I propose to highlight the usage of underscore ( _ ), when used as discard character, to be treated like a keyword (this / default / await / etc.) by the syntax highlighting in Visual Studio. 

Example:

`SomeObject.SomeEvent += (value1, _) => { //Do Something with only value1 };`

Where the underscore would be marked in blue (Dark Visual Studio Theme, colors accordingly for theme).

I think it would improve code readability and would make it more clear that the specified parameter is not neccesary for the required operation.

Edit: My example is bad. 
Hopefully better:

`var (value1, _, _) = CreateTupleWith3Values();`

Where currently the discard underscores are not syntax hightlighted.

**Comment by jnm2** [comment]
Is this covered by https://github.com/dotnet/csharplang/issues/111?

**Comment by Ccursed** [comment]
@jnm2 As far as I can tell, no. 

It is not about existing or new ways of usage, but simply about syntax highlighting.

My current Visual Studio 17 (latest Updates) and running latest minor C# version does not highlight underscores used as discards.

**Comment by jnm2** [comment]
@Ccursed See https://github.com/dotnet/roslyn/issues/16667. This looks intentional.

**Comment by Ccursed** [comment]
@jnm2 Yes I see. Thanks.

**Comment by Joe4evr** [comment]
It's a shame, though. I loved seeing that discard highlighted differently.

**Comment by jnm2** [comment]
Me too! I thought it was cool. @jcouv, what are the possibilities if we were to move this issue to dotnet/roslyn?

**Comment by jcouv** [comment]
Issue moved to [dotnet/roslyn #28284](https://github.com/dotnet/roslyn/issues/28284) via [**ZenHub**](https://www.zenhub.com/)
