### ISSUE TITLE
Request: Use Levenshtein distance (or similar) to improve errors in the event of a misspelled ctor name

### ISSUE THREAD

**Issue by Phrohdoh** [dotnet/csharplang#1688]
Say I have a class:

```csharp
public class ClassA { }
```

I add a ctor but misspell it accidentally:

```csharp
public class ClassA
{
    public ClasA() { ... }
}
```

Instead of getting `error CS1520: Method must have a return type` it would be more helpful to get something similar to the following:

```
error <code>: Did you mean to make the method `ClasA` a constructor for `ClassA`?

hint: Method `ClasA` does not specify a return type and is similar in spelling to the containing type `ClassA`
```

I'm sure this could be expanded to other areas but I believe this would be immediately beneficial with the smallest surface area.

**Comment by HaloFour** [comment]
This seems like the job of an analyzer, not the compiler.  An analyzer could also offer a Fix.

**Comment by Phrohdoh** [comment]
Is there any reason this shouldn't be shipped as part of the compiler so everyone can benefit?

**Comment by CyrusNajmabadi** [comment]
Working on the IDE side for this.

**Comment by CyrusNajmabadi** [comment]
> Is there any reason this shouldn't be shipped as part of the compiler so everyone can benefit?

To keep the compiler surface small and extremely well defined.  The IDE layers are well suited to figuring out the likely cause of problems and suggesting suitalbe replacements.

Note: by IDE we do not mean 'Visual Studio'.  We're simply referring to the layers that are more intended to help people manipulate code.

**Comment by CyrusNajmabadi** [comment]
Note: CSharplang is the wrong repo for this.  This is not a suggestion on how to change the language.  This is a request for how the compiler (or IDE) layers would work.  The right repo for this is dotnet/roslyn.  Can you move there please?  Thanks!

**Comment by Phrohdoh** [comment]
I'll move it there, sorry about that!

**Comment by CyrusNajmabadi** [comment]
No worries :)
