### ISSUE TITLE
Proposal: Much like => can we have <=> for get and set?

### ISSUE THREAD

**Issue by ukwd** [dotnet/csharplang#1691]
So we have:

```
        public SomeType Property => _backingField;
```

Which replaces:
```
        public SomeType Property
        {
            get { return _backingField; }
        }
```

Would it be possible to replace:

```
        public SomeType Property
        {
            get { return _backingField; }
            set { _backingField = value; }
        }
```

With:
```
        public SomeType Property <=> _backingField;
```

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/1007

**Comment by yaakov-h** [comment]
If you feel that the other issue adequately captures what you were proposing, then please close this issue so that it doesn't linger around forever.

**Comment by Joe4evr** [comment]
Also, take a look at what a language design member said on this subject in #1278.
> If the syntax for a read-write property is shorter than the syntax for a read-only property, then we have failed, and the changes would not encourage programming with immutable data as we intended.
