### ISSUE TITLE
Add "and", "or", "not" keywords for the "&&", "||" and "!" operators.

### ISSUE THREAD

**Issue by Mirandatz** [dotnet/csharplang#1692]
[It looks like even C++ has a keyword for the "and" operator](https://en.cppreference.com/w/cpp/keyword/and)

I don't think there are many drawbacks to adding such keywords.
On the other hand, I think such keywords could improve the legibility of a lot of   ##expressions.

**Comment by HaloFour** [comment]
This would collide with #1350 which is looking to use those keywords to support patterns.  If those keywords were simply synonyms for the existing operators they would create ambiguities.

**Comment by AustinBryan** [comment]
Is this another "C++ has this feature so C# should have it to" issue? Those were only in C++ to accomedate people that didn't have `&` and `|` on their keyboards. That is clearly not an issue in today's world. Read more [here](https://stackoverflow.com/questions/14740864/any-downside-to-using-the-and-operator-vs-the-operator).

Besides them being unnecessary and unbeneficial and only moderately improving readability for people who have spent less than a month programming `&&` and `||`, it would give issues to the pattern matching which planned on using those keywords. 

And I think most people would much rather have more pattern matching features than having useless synonym keywords that would risk breaking existing code for virtually no gain.

**Comment by theunrepentantgeek** [comment]
> I don't think there are many drawbacks to adding such keywords.

* They would make the language ambiguous.
* They would prompt many developers (not just beginners) to waste time finding out whether they were synonyms for the existing operators or actually differed

Lack of drawbacks isn't sufficient. A proposal has to have substantial value to pass the bar.

[Eric Gunnerson's classic post](https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/) explains this well:

> One way to do that is through the concept of “minus 100 points”. Every feature starts out in the hole by 100 points, which means that it has to have a significant net positive effect on the overall package for it to make it into the language.

**Comment by svick** [comment]
@AustinBryan 

> Is this another "C++ has this feature so C# should have it to" issue? Those were only in C++ to accomedate people that didn't have `&` and `|` on their keyboards.

There's a C++ feature that C# doesn't have? We must correct that immediately! Next up: digraphs and trigraphs.

**Comment by saxus** [comment]
> Next up: digraphs and trigraphs.

Yeah, I know, this is an very old, bad legacy, but IMHO we should move over on this. We had a conversation in our company a few times around this two lines during code reviews:

```cs
if (false == TryGetSomething(...)) ...
if (!TryGetSomething(...)) ...
```

First one is simply looking too odd (but at least bullet-proof) the 2nd one is too easy to forgot or accidently move over on the negation. Half of the team hate the 1st one and obviously other half hate the 2nd one. A dedicated "not" keyword would be help much on this.

```cs
if (not TryGetSomething(...)) ...
```

Also when you have a few (), arithmetic operators, etc. you definitely don't wan't to se more hieroglyphs on your code. "and" and "or" keyword can help a lot for readability.

**Comment by YairHalberstadt** [comment]
@saxus
https://www.google.com/search?q=xkcd+standards&oq=xkcd+standards&aqs=chrome..69i57j0l3.3922j1j4&client=ms-android-xiaomi&sourceid=chrome-mobile&ie=UTF-8#imgrc=Nfm3n72u7u7QJM:

**Comment by HaloFour** [comment]
@saxus 

> Half of the team hate the 1st one and obviously other half hate the 2nd one.

Adding a third method only guarantees that 66% of them hate any of those options.

In my opinion if negating the expression makes the code difficult to read it's easier to first assign that expression to a variable and then have the condition negate that variable.  Or negate the expression before assigning it to the variable, ensuring that the variable name reflects that negation:

```cs
var exists = TryGetSomething(...);
if (!exists) { ... }
if (exists == false) { ... }

var doesntExist = !TryGetSomething(...);
if (doesntExist) { ... }
```
