### ISSUE TITLE
Proposal: using syntax expansion for multiple disposable objects

### ISSUE THREAD

**Issue by jakepnix** [dotnet/csharplang#1693]
This proposal is to improve syntax of 'using' keyword for multiple disposable objects.
When we use multiple disposable object with using keyword, then the code will be complex as below.

```
        using (WebResponse response = request.GetResponse())
        {
            using (Stream stream = response.GetResponseStream())
            {
                using (StreamReader reader = new StreamReader(stream))
                {
                       // implementation
                }
            }
        }
```
or
```
using (WebResponse response = request.GetResponse())
using (Stream stream = response.GetResponseStream())
using (StreamReader reader = new StreamReader(stream))
{
     // implementation
}
```

But, if C# supports following syntax then it will help readability and simple coding style.
(At the end of this scope, disposable method will be called.)
```
using WebResponse response = request.GetResponse();
using Stream stream = response.GetResponseStream();
using StreamReader reader = new StreamReader(stream);

// implementation

```
Additionally if we can combine with braces then we can use more sophisticated disposable objects.
```
   {
       using WebResponse response = request.GetResponse();
   }
   // response.Dispose() will be called like RAII in C++
```

**Comment by yaakov-h** [comment]
This appears to be a duplicate of #114, which is already being championed for C# 8.x (see #1174).

If you feel that this is the case, then please close this issue.

If you feel that the two issues are different, then can you please elaborate on how this is a different proposal to #114?

**Comment by theunrepentantgeek** [comment]
Duplicate of #114, and #1174.

**Comment by jakepnix** [comment]
Thanks yaakov-h,
As you mentioned, it is same case.
I will close this issue.
