### ISSUE TITLE
Feature Request: Create an operator that represents String.IsNullOrEmpty()

### ISSUE THREAD

**Issue by jnegron357** [dotnet/csharplang#170]
In the same way that we have the null coalescing operator, I'd like to see one that can include an implicit check for empty strings.

## Before
`string result = String.IsNullOrEmpty(var1) ? var2 : var1;`
`//using an extension method:`
`string result = var1.IsNullOrEmpty() ? var2 : var1`
## After
`string result = var1 ??! var2;`

This would be a great way to clean up code!

**Comment by jnm2** [comment]
I use `IsNullOrWhitespace` far more frequently.

**Comment by jnegron357** [comment]
I suppose `IsNullOrWhiteSpace` makes more sense since it has better coverage.

**Comment by alrz** [comment]
HasValue on Nullable could be convention-based so you could define an extension property for string with that effect.
```cs
extension string {
  public bool HasValue => string.IsNullOrEmpty(this);
}

var x = str ?? "empty";
```

**Comment by Thaina** [comment]
I write extension method in my own basis

```C#
public static StringExt
{
    public static bool IsNullOrEmpty(this string str) => string.IsNullOrEmpty(str);
}

"abc".IsNullOrEmpty();
string s = null;
s.IsNullOrEmpty();
```

**Comment by eyalsk** [comment]
I almost never use `string.IsNullOrEmpty` but `x == null` and/or `x.Length == 0`.

Just as an example:

```
if (text == null)
{
	throw new ArgumentNullException(nameof(text));
}

if (text.Length == 0)
{
	yield return new TextChar(default(char));
}
```

**Comment by MovGP0** [comment]
the operator should probably represent IsNullOrDefault to include non-class objects:

```csharp
T result = foo ??! bar;
```

maps to

```csharp
T result = foo == null || foo.Equals(default(T)) ? bar : foo;
```

Another way of doing this would be the ability to create custom operators like in F#.

**Comment by MovGP0** [comment]
Another way of doing this would be the ability to create custom operators: 

```csharp
public static class StringExtensions 
{
    public static string operator (??!) IsNullOrEmpty(this string left, string right) 
    {
        return string.IsNullOrEmpty(left) ? right : left;
    }
}
```

**Comment by JamesFaix** [comment]
I don't think this provides enough value to warrant language integration.  The extension method call in the example is only a few characters longer than an expression with the new operator would be.

**Comment by jamesqo** [comment]
If you use `IsNullOrEmpty` a lot in a file, adding a `using static System.String` at the top will help decrease verbosity. Better yet, you could  create an extension method and write `if (str.IsNullOrEmpty())`... I don't think 1 function warrants language integration.

There's another way to do this I just thought of, too: `if (str?.Length > 0)`

**Comment by jnegron357** [comment]
The arguments against this feature are understandable but I still believe having the specialized operator or the ability for the developer to create it would be very useful and in the end would help us be more productive. I'm sticking to my guns despite the down votes.
