### ISSUE TITLE
Proposal: Dynamic Tuples

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1700]
I suggest to allow functions to define dynamic tuple to receive any no of items. I suggest this syntax:
```() t = (1, 3.1, "abc");```
I think that all the required from C# is to allow any ValueTuple to be assigned to t. I exactly don't know how hard can this be, so lets hear from the experts.

dynamic tuple will allow us to define functions that can receive any no. of different type params, which is better than using object param aarray. Ex:
```
void Foo(() x)
{
    var T = (ITuple)x
    for (int i = 0; i< T.Length; i++)
          Console.WritleLine(T[i]);
}
```

The problem is that t[i] returns object and this indexer is readonly, so I suggested this solution #1699 to index the ValueTuple directly and it will be a read/write. So, it it happens, we can use x[i] in the above loop directly.
```
void Foo(params() x)
{
    for (int i = 0; i< ((ITuple)x).Length; i++)
          Console.WritleLine(x[i]);
}
```

It will be also nice if ValueTuples implement the ITuple.Length property normally not explicitly, so the code can be:
```
void Foo(params() x)
{
    for (int i = 0; i< x.Length; i++)
          Console.WritleLine(x[i]);
}
```

Now, we can call Foo like this:
```Foo((4, 5.5, "test"));```

This doesn't seem useful so far, but it will be in out params. suppose I have this function:
```
void ReadData(out ( ) data)
{
    for (int i = 0; i< x.Length; i++)
          Reader.Read(out data[i]);
}
```

Assuming we have a ```Reader.Read<T>(out T data)``` somewhere, to read the data from a file.

Now, I can write:
```ReadData(out (int, byte, string, single) x);```

Dynamic tuples can also used as a return value. Ex:

```
( ) Foo()
{
    retutn (1, 1.2, "Test");
}
```

```
( ) result = Foo( );
for (int i = 0; i< result.Length; i++)
      Console.WritleLine(result [i]);
```

I first thought of this to find a way to read multiple data of different types from a file in one line. I think it can be useful in other tasks.

**Comment by yaakov-h** [comment]
```csharp
void Foo(() x)
```

What would this look like in IL?

ValueTuples are structs, and ValueTuples of different arity are structs of different sizes. You can't currently have a variable that could refer to structs of different sizes without first boxing the struct, in which case you may as well just use `ITuple`.

**Comment by MohammadHamdyGhanem** [comment]
@yaakov-h 
You are right. But ITuple has some problems, firts of all its indexer is readonly, and second I don't know how to convert ITuple back to ValueTuple. If I get Values, Types, and no. of items, can I create the ValueTuple at runtime?

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> If I get Values, Types, and no. of items, can I create the ValueTuple at runtime?

You can use `ValueTuple.Create` via reflection, but you'll have to store that right back in either `object` or `ITuple` so I don't see the point.  Nor do I see any point to your proposal.  It seems to lack some fundamental understanding as to how static typing works.

**Comment by jnm2** [comment]
@MohammadHamdyGhanem You already have a tool that works even better: `object[]`.

**Comment by MohammadHamdyGhanem** [comment]
@jnm2 
I was tring to avoid boxing and casting. But seems it is a dead end.
I have a new suggestion here https://github.com/dotnet/csharplang/issues/1701
Thanks.
