### ISSUE TITLE
Shortest syntax for multiple method calls

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1701]
I have this code:
```
binaryWriter.Write(15); 
binaryWriter.Write("test");
binaryWriter.Write(false);
binaryWriter.Write(1.2);
binaryWriter.Write(byteArr, 1, 2);
```

I suggest to use this shortcut syntax instead:
```
binaryWriter.Write(15; "test"; false; 1.2; 
                                 byteArr, 1, 2);
```

This is better than using Tuples as I did here https://github.com/dotnet/corefx/issues/30826#issuecomment-403020954

**Comment by jnm2** [comment]
The difference between commas and semicolons is too easy to miss.

**Comment by MohammadHamdyGhanem** [comment]
@jnm2 
Yes, but we are used too in for loops. I didn't invent this convention.
Anyway, if the problem is in the delimiter, you can suggest a better one.
Thanks

**Comment by MohammadHamdyGhanem** [comment]
As an alternative:
```binaryWriter.Write(15 => "test" => false => 1.2=> byteArr, 1, 2);```

**Comment by jnm2** [comment]
@MohammadHamdyGhanem 

> Yes, but we are used to in for loops. I didn't invent this convention.
> Anyway, if the problem is in the delimiter, you can suggest a better one.

I'm not sure why you'd compare a for statement to a method call?
I don't see a need and I honestly guess that there wouldn't be a great option. That `=>`, for example, looks like you're declaring a lambda and would directly conflict with the syntax used to pass a lambda to a method call.

**Comment by jnm2** [comment]
Something related which would make me feel a lot better would be a way to assign a method group to a local variable and resolve it to a different method on each use:

```cs
var write = binaryWriter.Write;
write(15); 
write("test");
write(false);
write(1.2);
write(byteArr, 1, 2);
```

It's a thought I had while reading https://github.com/dotnet/csharplang/issues/1694.

**Comment by jnm2** [comment]
What you're trying to do reminds me of C++'s `cout << 15 << "test" << false << 1.2`.

**Comment by jnm2** [comment]
What you're trying to do reminds me of C++'s `cout << 15 << "test" << false << 1.2`.

In similar situations, I sometimes do the StringBuilder thing. Particularly when each call has generics to be inferred. You'd have to define your own type, but you can do this today:

```cs
binaryWriter.Fluent()
    .Write(15)
    .Write("test")
    .Write(false)
    .Write(1.2)
    .Write(byteArray, 1, 2);
```

**Comment by asyncawaitmvvm** [comment]
They added this cool keyword called **params**.

`binaryWriter.Write(15; "test"; false; 1.2; byteArr, 1, 2);`

can become
`
binaryWriter.Write(15, "test", false, 1.2, byteArr, 1.2);`

I recommend you should not be allowed to post here without a minimum of 10 years of actual coding experience.

**Comment by theunrepentantgeek** [comment]
I don't think this proposal is a good idea - introducing additional syntax makes things harder to understand than the original, and I don't believe reducing keystrokes is actually a useful goal for evolution of the C# language.

That said, @asyncawaitmvvm, I don't think there's a strong correlation between "years of experience" and "quality of proposal" - and I don't think your level of snark is justified.

**Comment by CyrusNajmabadi** [comment]
@asyncawaitmvvm Please abide by the .net code of conduct.  You can read more about it here: https://dotnetfoundation.org/code-of-conduct

**Comment by yaakov-h** [comment]
Snark aside, `params` doesn't even solve the problem in the OP.

You could use `params` to write an extension method that farms the objects out to the single-argument overload of `Write`, but the final call in the OP's example is a completely different overload.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
With simple format and coloring  from the editor there will be no confusion. 
Besides, this is very simple in comparison to some modern C# codes, I struggle to read. Look at this:
`public static void Sort<TKey1, TKey2, TValue> (TKey1[] keys, TValue[] items, int index, int length, Func<TKey1, TKey2> ValueToCompare) where TKey2 : IComparable => Array.Sort(keys, items, index, length, new TComparer<TKey1>((x, y) => ValueToCompare(x).CompareTo(ValueToCompare(y))));`

**Comment by MohammadHamdyGhanem** [comment]
@yaakov-h 
Even with  one parameter overloads, object params array will be a slightly slower than my suggested syntax, becuase boxing and unboxing. Note that I want to use this syntax with methods defined in. Net framework. If I wrote the method myself, I can optimize it as I want. I gave the example of writting data to files, becuase it is the most common situation where code can be long and better to be shortened.
Thanks.

**Comment by MohammadHamdyGhanem** [comment]
@asyncawaitmvvm 
I apologiz for my poor writings. I tend to write short issues, where I expect readers to know the missing details, and let some details to discussion. This is not the formal proposal you can expect, and it is my mistake if you miss any of my points.
Thanks

**Comment by theunrepentantgeek** [comment]
@MohammadHamdyGhanem Syntax highlighting is a choice for the code editor, not the language. This might be Visual Studio, Visual Studio Code, Visual Studio for Macintosh, Nodepad++, JetBrains Rider, or something else entirely.

The biggest problem with the example you gave is that the code formatting is atrocious; while the compiler doesn't care, good code layout is critical for the humans reading the code.

On my team, we'd format in this way:
```
public static void Sort<T1, T2>(
    this T1[] A, 
    Array items, 
    int index, 
    int length, 
    Func<T1, T2> ValueToCompare) 
    where T2 : IComparable 
=> Array.Sort<T1>(
    A, 
    index, 
    length, 
    new TComparer<T1>((x, y) => ValueToCompare(x).CompareTo(ValueToCompare(y))));
```

Even so, this would probably fail code review - the `items` parameter isn't used at all, and the comparer should be broken out as a separate local.

Optimizing code for *readability* and *maintainability* is good practice that lowers the cost of ownership over the lifetime of the code. Doing so doesn't require mutilation of the language.

**Comment by CyrusNajmabadi** [comment]
> With simple format and coloring from the editor there will be no confusion.

In general, we want the language to be readable and clear even in the absence of an editor like VS.

Furthermore, even if you had VS, it's not clear to me how you would make that readable.  Instead of asserting htat something will be true the onus is on you to *show* that it would be true.

**Comment by MohammadHamdyGhanem** [comment]
@theunrepentantgeek 
Yes, items should be sent as the second param.
The point is that not all valid codes arenecessarily readable or simple. One can choose to write a normal method body to make that code more readable. 
Thanks

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Lets break this issue into two points:
1- is the proposal useful?
2- how to make it readable.

If 1 is now, then no need for 2.
To be honest, calling the same method repeatedly with different params is not common unless in writting data to steams or images or so. If these are the only cases, then the issue belongs to corefx (and they happy with things as they are). If there are other common situations like this, then c# can do something.
If ; is confusing, we can think of other separators such as ;; or ->
`binaryWriter.Write(15 -> "test" -> false -> 1.2 -> byteArr, 1, 2);`

**Comment by mcosmin222** [comment]
What happens if that method call throws an exception? How will you know where the exception is actually thrown? How will the stack trace look like?

**Comment by CyrusNajmabadi** [comment]
I did a search in Roslyn itself, and found less than two dozen cases where this would actually come into effect.  

The idea that people will *commonly* have long chains of calls to *overloads* with different types, is just too tenuous to get behind.  It would basically be a feature to help someone out with at most a dozen lines of code in an entire project.  It's just not at all worth it.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Even if the Method has only one overload, this still helps avoiding to write an extension method to pass multiple arguments. These type of chain calls happens mostly when working with grids (tables, matrices, images… etc). So, you can extend the benefits some more.
The important matter is that the suggested syntax helps only with voids. I can suggest to use it with functions by collecting the return values in a Tuple if they are of different types, or a list<T> if the all overloads return T. This will need some work to do type inference.

**Comment by HaloFour** [comment]
Proposals like this serve to make the language slightly easier to write but at the sacrifice of making it much harder to read.  And that difficulty isn't limited to where you use this feature, either.  It would require that the developer squint carefully at literally every single method invocation they come across in their entire codebase as it would be exceptionally simple for a single glyph buried in the argument list to completely alter what the code means.  For that reason I don't think it's a good idea regardless of how frequently the situation might come up.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
I agree with all opinions against ; but I think that -> is unique and haed to miss or confuse. I should update the original issue, but it seems it had more disagreement than I ever saw in other topics 😊.
Thanks anyway.
