### ISSUE TITLE
Proposal: Generic Equality Constraints

### ISSUE THREAD

**Issue by CharlesTaylor7** [dotnet/csharplang#1706]
I attempted to write a class that looked like:
``` cs
class Foo<T1, T2> : IEquatable<T1>, IEquatable<T2>
{
   // Implementation
}
```
I got an unusual error message of: `'Foo<T1, T2>' cannot implement both 'IEquatable<T1>' and 'IEquatable<T2>' because they may unify for some type parameter substitutions`

My proposal is to allow generic constraints of the form `type1 == type2` & `type1 != type2`. This would allow the following:
``` cs
class Foo<T1, T2> : IEquatable<T1>, IEquatable<T2>
    where T1 != T2
{
   // Implementation
}
```

**Comment by CharlesTaylor7** [comment]
On further inspection, it appears that the following code is perfectly legal:
``` cs
class Foo<T1, T2> : IEquatable<List<T1>>, IEquatable<List<T2>>
{
    // Implementation
}
```
Does anyone know why the other declaration is not allowed when this code would also unify IEquatable instances whenever `T1 == T2` ?

**Comment by bondsbw** [comment]
@CharlesTaylor7 
> On further inspection, it appears that the following code is perfectly legal:
> ```c#
> class Foo<T1, T2> : IEquatable<List<T1>>, IEquatable<List<T2>>
> {
>     // Implementation
> }
> ```

I get an error:

`error CS0695: 'Foo<T1, T2>' cannot implement both 'IEquatable<List<T1>>' and 'IEquatable<List<T2>>' because they may unify for some type parameter substitutions`

**Comment by Logerfo** [comment]
I don't think checking for equity would be enough. What if T1 inherits T2 (or the opposite)? The unification could still happen, couldn't it? Maybe a constraint that enforces T1 and T2 to don't be related?

**Comment by HaloFour** [comment]
@Logerfo 

> What if T1 inherits T2 (or the opposite)? The unification could still happen, couldn't it?

No, that would just result in normal overloads.  The unification problem occurs when two members would have identical signatures.

**Comment by Logerfo** [comment]
@HaloFour I see. I guess what I'm thinking is another issue, then. Take a look at this code:
```c#
public class C<T1, T2>
{
    public void M(T1 t1) { }
    public void M(T2 t2) { }
    public static void Test() => new C<int, int>().M(2);
}
```
It gets the following compilation error:
> The call is ambiguous between the following methods or properties: 'C<T1, T2>.M(T1)' and 'C<T1, T2>.M(T2)

But with the following:
```c#
public class B { }
public class A : B { }
public static void TestA() => new C<A, B>().M(new A()); //t1 overload
public static void TestB() => new C<A, B>().M(new B()); //t2 overload
```
It compiles just fine.

The constraint the OP is asking would "solve" the first problem, by disallowing `C<int, int>` to happen. What I meant with a constraint which enforces T1 and T2 to don't be related would have the same effect, but would also disallow `C<A, B>` to happen, avoiding unintended overload resolutions. Those scenarios make me always write different method names, like this:
```c#
public void M1(T1 t2){ }
public void M2(T2 t2){ }
```

**Comment by YairHalberstadt** [comment]
One case where this would be useful is defining something like this:

```csharp
public class TwoWayDic<T1, T2> : IDictionary<T1, T2>, IDictionary<T2, T1>
{
}
```

Currently you get:
> error CS0695: 'TwoWayDic<T1, T2>' cannot implement both 'IDictionary<T1, T2>' and 'IDictionary<T2, T1>' because they may unify for some type parameter substitutions

It would be nice to be able to write:

```csharp
public class TwoWayDic<T1, T2> : IDictionary<T1, T2>, IDictionary<T2, T1> where T1 != T2
{
}
```

**Comment by theunrepentantgeek** [comment]
You'd still have a problem if there were implicit cast operations from `T1` to `T2` or back.
