### ISSUE TITLE
Scoping private variables within a class

### ISSUE THREAD

**Issue by stokara** [dotnet/csharplang#1712]
In my most common use case of property backing fields I would like to be able to be sure that the private field is not modified externally to the property setter. To visually indicate this I commonly declare the field above the property. It would be great to have this ensured by the compiler by having the variable scoped within the property perhaps like this:

public Type PropertyName {
  private Type field;
  get => field;
 set => setMethod(ref field, value);
}

**Comment by Joe4evr** [comment]
#1643, #140, #1497, etc.

**Comment by bondsbw** [comment]
#133

**Comment by AustinBryan** [comment]
A better name for this would be "property scoped variables." Also, please reformat your code

**Comment by Unknown6656** [comment]
Oh boy - here we go again with the duplicates:

See https://github.com/dotnet/csharplang/issues/1497#issuecomment-386837762
And ...
#1497
#1420
#1336 
#1290 
#1240
(#1059)
#626
#318
#140
#133
_[and there are probably even more]_

**Comment by stokara** [comment]
mea culpa - I did this without searching.

**Comment by Unknown6656** [comment]
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
