### ISSUE TITLE
Not-null guard via something like pattern matching

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/csharplang#1717]
It's possible to replace...

```c#
var name = e.Name;
if (name != null)
{
     // name is not null
}
```

...with...

```c#
if (e.Name is string name)
{
     // name is not null
}
```

This pattern doesn't work well with anything but short type names though.

```c#
if (e.Value is IReadOnlyDictionary<string,IReadOnlyList<string>> idsByName)
{
     // idsByName is not null
}
```

Something like this maybe:

```c#
if (e.Name not null name)
{
     // name is not null
}
```

I'm not so attached to the syntax. It should just be short and not have a [performance impact](dotnet/roslyn#13247).

---

Other usages for a negative pattern.

```c#
if (!(o is string)) { ... }
if (o not string) { ... }
```

I can't think of a case for declaring a var, other than the null test.

Is anything planned like this to support nullable reference types?

**Comment by theunrepentantgeek** [comment]
What's wrong with using **var** like this?

```
if (e.Value is var idsByName)
{
     // idsByName is not null
}
```

**Comment by HaloFour** [comment]
@theunrepentantgeek 

The `var` pattern matches `null`.

**Comment by gafter** [comment]
@drewnoakes I hope @CyrusNajmabadi 's answer satisfies you. If not please reopen.

**Comment by drewnoakes** [comment]
@CyrusNajmabadi I thought for a minute I'd posted on the TypeScript repo 😆 

I assume that's an empty [property pattern](https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md#property-pattern) list. While it might work, my goal was to be concise and clear, and I'm not sure how clear it would be to those unfamiliar with intricacies of pattern matching.

Would that work for nullable value types as well, or would you need a `Value` property in the list?

**Comment by HaloFour** [comment]
@drewnoakes 

> Would that work for nullable value types as well

It does work for nullable value types and you don't need to specify any properties:

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgD4ACADAAS0CMA3ALABQtAzMwCZGAYUYBvboynN+OCjEYBZABRyYAfkY4AlOMnSDOMI1Vbk4gL6MAHrolcDj6bQDsNzg6eML+p68b0HgY+XBZAA

**Comment by theunrepentantgeek** [comment]
> I'm not sure how clear it would be to those unfamiliar with intricacies of pattern matching.

@drewnoakes I remember similar arguments being made about *generics* when they were introduced - and much later about lambdas. *Unfamiliarity* only lasts while we move forward to the new version. Every piece of new syntax is odd at first.

**Comment by CyrusNajmabadi** [comment]
> I'm not sure how clear it would be to those unfamiliar with intricacies of pattern matching.

Woudln't hte same be true of ```is <expr> not null```?  Someone would have to become familiar with how that worked?

Note there is also this proposal: https://github.com/dotnet/csharplang/issues/1350

It actually will add a 'not' pattern.  so my expectatoin is that you *will* eventually be able to say ```if (<expr> is not null)``` as that will just be an ```is pattern``` with a nested ```not``` and ```(null) constant``` patterns.  @gafter can let me know if my reading of that is correct and that syntactic form would be supported :)

**Comment by CSharpLanguage** [comment]
IMHO
As we see from @theunrepentantgeek 's [comment](https://github.com/dotnet/csharplang/issues/1717#issuecomment-405394437) the construction `is var` has confusing implementation and broke intuitive expectations. It is very tempting to replace
```c#
if (GetDictionary() is Dictionary<string, object> d) ...
```
on
```c#
if (GetDictionary() is var d) ...
```
But this replacement breaks the logic of course and without an code analyzer or tests it is very hard to catch and understand.

`is {}` looks strange too because it is a totally new way of variable declarations into the language.
Currently we can use
```c#
// explicit type declarations
T x =...
is T x
case T x
(T x) => ...

// implicit type declarations with type infer
var x = ...
is var x
case var x
(x) => ...

let x = ... (only into a context of LINQ expressions)
```
Seems that `is {} x` is the new kind of a implicit declaration with type infer but the following forms have not sence
```c#
{} x = ...
({} x) =>
```
Sorry, but currently I can not found summery into this approach.

**Comment by CSharpLanguage** [comment]
@HaloFour the same valid for a explicit type declaration
```c#
string s = (string)null;
```

**Comment by HaloFour** [comment]
@CSharpLanguage 

Exactly, so stop comparing the two.  They are not the same thing and are not expected to behave like the same thing.

**Comment by CSharpLanguage** [comment]
@HaloFour 
Yes, absolutely agree that there are slightly different things. But there is a sort of special symmetry between them.
Now I am not seeing the same symmetry with `is {} x`.

**Comment by HaloFour** [comment]
@CSharpLanguage 

Property patterns are the inverse of object initializers.

**Comment by CSharpLanguage** [comment]
@HaloFour 
Object initializers are not variables declarations.
Looks that inverse of object initializers should not be variables declarations too.

**Comment by HaloFour** [comment]
@CSharpLanguage 

It's not a variable declaration.  It's a property pattern.  The variable pattern is after the pattern, `x`.

**Comment by CSharpLanguage** [comment]
@HaloFour 
Ok, in this case seems that the variable pattern should contain explicit type definition or keyword for type infer
```c#
is {} T x
is {} var x
```
For example if we avoid `var` like with lambdas `(T x) => ...` and `(x) => ...` the form `is {} T x` should be still valid.

**Comment by HaloFour** [comment]
@CSharpLanguage 

`is T {} x`

But the language will intentionally allow you to omit the type name when it is known.

The same will be true with positional patterns.

**Comment by CSharpLanguage** [comment]
@HaloFour 
Good. Only I am not sure that `var` should be avoided like with lambdas.

**Comment by CSharpLanguage** [comment]
@DavidArno 

> There is no solution that would be 100% consistent across all cases.

Seems that there is fully consistent solution.
Just try to add fallback value into `is`-like PM expressions...

Currently
```c#
if (y is T x)
{
   ...
}
// Console.WriteLine(x); // compile error: possible unassigned variable
```
equals to
```c#
T x;
if (y is T) 
{ 
   x = y;
  ...
}
// Console.WriteLine(x); // compile error: possible unassigned variable
```

How it may looks and works alternatively?
```c#
if (y is T x : optionalFallbackValue)
{
   ...
}
Console.WriteLine(x); // print 'optionalFallbackValue' if y is null or is not T
```
equals to
```c#
T x = optionalFallbackValue;
if (y is T) 
{ 
   x = y;
  ...
}
Console.WriteLine(x); // print 'optionalFallbackValue' if y is null or is not T
```
Instead `optionalFallbackValue` we may suppose `default(T)`.

Moreover this logic may sense for
```c#
if (y is var x : optionalFallbackValue)
{
   ...
}
Console.WriteLine(x); // print 'optionalFallbackValue' if y is null
```
equals to
```c#
var x = optionalFallbackValue;
if (y is object) // null check
{ 
   x = y;
  ...
}
Console.WriteLine(x); // print 'optionalFallbackValue' if y is null
```

What about switch?
```c#
switch(GetValue())
{
   case T1 x: ...
   case T2 x: ...
   case var x: ... // all cases except null
   default var x: ...  // all cases with null
}
```

We save meaning for all basic features via clear composition.
Out single suppose that `x` is `default(T)` if `y` is not `T`.

Why not? Do you see any contradictions?

**Comment by HaloFour** [comment]
@CSharpLanguage 

> Why not? 

Because breaking changes for the sake of making you feel better are not on the table.

**Comment by terrajobst** [comment]
@CSharpLanguage 

We had this exact conversation with the last user accounts of yours that we ended up blocking because you refused to take "we don't do breaking changes just because you don't like the design" as an answer. I've blocked this account as well.

**Comment by CSharpLanguage-Oh** [comment]
@terrajobst 
Sorry for my refusal and insistence of course.
But I don't suggest to bring breaking changes at all and accept current design as is.

I am worrying about a direction related with 
@HaloFour 

> Property patterns are the inverse of object initializers.

This is very unclear for me...
Because
1. object initializers look like particular case of `with` pattern
```c#
GetPoint()?.With
(
  .Name = "abc",
  .X = 12,
  .Y = 32
)
```
2. `with` pattern supports two directions (construction/deconstruction)
```c#
int a, b;
GetPoint()?.With
(
  .Name to var name,
  .X to a,
  b = .Y
)
```
3. property patterns looks as a new sort of `with` pattern
```c#
if (GetPoint() is Point p && p.Check
        (
                .Name.StartWith("ab"),
                .X > 52,
                .Y < .X,
        ).All(true) // All(false), Any(true), Count(true) == 2, ...
   ) ...
```
There are consistence and flexibility into classical concepts.

But I really want to feel symmetry between
```c#
is T { /* comparisons */ } x
var x = new T { /* assignments*/ }
```
and can't...

But you try to stop all my discussion related with this topic. Why?
Do you feel this symmetry for the last case exactly? Can you explain?
