### ISSUE TITLE
Proposal: Make FriendAccessAllowedAttribute public

### ISSUE THREAD

**Issue by lukdr** [dotnet/csharplang#1724]
Would it be possible to make the System.Runtime.CompilerServices.FriendAccessAllowedAttribute public, to be more explicit and clearly state intent of what exactly should be visible to a friend assembly? 

Additionally, it might be even better to have an AssemblyName property on that attribute so that the usage of InternalsVisibleToAttribute would not be needed.

**Comment by HaloFour** [comment]
This probably belongs on [CoreCLR](https://github.com/dotnet/coreclr/) as it affects the accessibility of a type in mscorlib and doesn't involve modifications to the C# language.

**Comment by yaakov-h** [comment]
Would it not affect the language in terms of what types are accessible to consuming code?

**Comment by lukdr** [comment]
@HaloFour true, it probably belongs in CoreCLR, but since the topic is here anyway, maybe a new access modifier should be considered, as the above attributes are clearly a workaround for something that language doesn't provide.

**Comment by YairHalberstadt** [comment]
Closing as this has been raised on CoreCLR at https://github.com/dotnet/runtime/issues/10707.

WRT this comment

> but since the topic is here anyway, maybe a new access modifier (visible to assemblies in solution) should be considered, as the above attributes are clearly a workaround for something that language doesn't provide.

I suggest you raise a new discussion focusing on this question if it is still important to you.
