### ISSUE TITLE
Allow specific type in generic

### ISSUE THREAD

**Issue by msedi** [dotnet/csharplang#1726]
I'm not sure if there's a better solution, so we can for sure discuss this suggestion.
In C++ ( and I really don't want to have the complexity of C++ in C#!) I have the possibility to define - in that case templates - something like this:

`template <typename T, int No> class MyClass;`

and then use the class as following

`MyClass<float,10> testClass;`

I had a lot of situations where this might be helpful to have this in C#. Some might say that you can solve this, by having a this in a constructor so that the C# class looks like this

```
public class MyClass<T>
{
  public readonly int No;
  public MyClass(int no) {No = no;}
}
```

But in some situation, especially for static classes this could maybe help. Example:

```
public class ArrayPool<T, int size)
{
  public static readonly Span<T> Instance = new T[size];
}
```

What do you think, is there some better solution?

**Comment by orthoxerox** [comment]
See also #357

**Comment by msedi** [comment]
@orthoxerox: Thanks for pointing out. It's always hard to find already existing issues.

**Comment by amis92** [comment]
@msedi I think a little oververbose workaround would be constraining the type to derive from some IAnyProvider interface *and* have parameterless constructor:

```csharp
interface IAnyProvider<T>
{
    T Value { get; }
}

class ArrayPool<T, TSize>
    where TSize : IAnyProvider<int>, new()
{
    public static readonly Span<T> Instance = new T[new TSize().Value];
}

struct Size10 : IAnyProvider<int>
{
    int IAnyProvider<int>.Value => 10;
}

// using size10
var array = ArrayPool<MyClass, Size10>.Instance;
```

**Comment by ufcpp** [comment]
@amis92 

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

interface IConstant<T> { T Value { get; } }

class A1<TSize>
    where TSize : IConstant<int>, new()
{
    public static int Get() => new TSize().Value; // this IS NOT devirtualized
}

class A2<TSize>
    where TSize : struct, IConstant<int>
{
    public static int Get() => default(TSize).Value; // this IS devirtualized
}

struct _5 : IConstant<int> { public int Value => 5; }

/*
 Method |      Mean |     Error |    StdDev |    Median |
------- |----------:|----------:|----------:|----------:|
     X1 | 55.840 ns | 1.1514 ns | 3.3221 ns | 54.943 ns | // not inlined
     X2 |  1.094 ns | 0.0591 ns | 0.1095 ns |  1.081 ns | // inlined
 */
public class X
{
    [Benchmark]
    public int X1() => A1<_5>.Get();

    [Benchmark]
    public int X2() => A2<_5>.Get();
}

class Program
{
    static void Main()
    {
        BenchmarkRunner.Run<X>();
    }
}
```
