### ISSUE TITLE
System.Runtime.Intrinsics

### ISSUE THREAD

**Issue by kgb7711** [dotnet/csharplang#1727]
Support  System.Runtime.Intrinsics that is available in .Net Core 2.1 or redesign System.Numerics!

**Comment by bbarry** [comment]
What sort of support would be necessary for the language?

Most of the intrinsics deal with packed vector data types; I am unclear as to what the language would do to make them more supported. Can you provide examples?

**Comment by AustinBryan** [comment]
You didn't even describe them how to redesign System.Numerics (which I bet won't be easy, if not, impossible and break everything). You would need an incredibly compelling argument for them to do so, you aren't convincing anyone by saying to just do it. How are they supposed to know which way to redesign it?

You should provide some examples of what you want to do. Maybe there is actually a way to do it already without any changes to the language.

**Comment by YairHalberstadt** [comment]
I'm closing this as it's not clear what the language proposal is. Feel free to open a new issue/discussion explaining what you would like in more detail.
