### ISSUE TITLE
[Proposal] if(;) and for(;)

### ISSUE THREAD

**Issue by sirius0xff** [dotnet/csharplang#1732]
`if(; )`:
many times we have to do:
```
var foo=bar();
if(foo!=null) {
     //..........
}
```
where the variable foo is not useful outside of the `if` scope.

An intuitive syntax for this is:
```
if(var foo=bar(); foo!=null) { // just like the famous for loop
     //..........
}

//same as, (not considering `continue`) :

for(var foo=bar(); foo!=null;) { 
     //..........
     break;
}
```
`/**********************************************************************************/`
`for(; )`:
From time to time we may face the pattern:
```
for(string line = stream.ReadLine(); line != null; line = stream.ReadLine()) { 
    //..........
}
```
Which can be shorten if with have the syntax `for(_statement_; _condition_) ` :
```
for(string line = stream.ReadLine(); line != null) { // line is a new var in each loop
    //..........
}
same as:

while(true) { 
    string line = stream.ReadLine();
    if(!( line != null))break;
    //..........
}
```

`/**********************************************************************************/`
Both are basically extended `for(;;)` loop, as a syntax sugar.

**Comment by svick** [comment]
Also, with C# 8.0 pattern matching, you will be able to write:

```c#
if (bar() is {} foo) {
     //...
}

while (stream.ReadLine() is {} line) {
    //...
}
```

The `is {}` syntax is a property pattern with no properties. This syntax is certainly confusing when you see it for the first time, but maybe it's good enough?

**Comment by BhaaLseN** [comment]
It _might_ work with C# 7 as well in your case if you're dealing with classes and non-`null` as condition:
```c#
if (bar() is var foo) { /* ... */ }

while (stream.ReadLine() is string line) { /* ... */ }
```
(except the fact that the declaration is _after_ the statement instead of _before_)

**Comment by HaloFour** [comment]
@BhaaLseN 

> It *might* work with C# 7 as well in your case if you're dealing with classes and non-`null` as condition:

Note that `var` patterns will match `null`.

**Comment by BhaaLseN** [comment]
Oh, right, it should probably be `if (bar() is ReturnTypeOfBar foo)` then, right?
💭 _and I should go review some code I wrote earlier that made it through without blowing up_

**Comment by jnm2** [comment]
@BhaaLseN Using the mnemonic that `var` means `declare local variable`, I haven't really had any trouble spilling into thinking that it means `<infer type>`.

**Comment by jnm2** [comment]
@BhaaLseN Using the mnemonic that `var` means `<declare local variable>`, I haven't really had any trouble slipping into thinking that it means `<infer type>`.

**Comment by BhaaLseN** [comment]
I've commonly used it as "infer the type here and declare a variable", so I might have to change my way of thinking a little. Thanks.

**Comment by Thaina** [comment]
@BhaaLseN Most people think like that. Is was a completely wrong decision of the design team

**Comment by jnm2** [comment]
@Thaina Whether or not you agree that the decisions in the design of C# 7.0 were good ones, they have been made. There's no point in stating your unhappiness because it isn't actionable for anyone.

**Comment by sirius0xff** [comment]
let me close it =D

**Comment by Thaina** [comment]
@jnm2 I just state that he is not the wrong one. It should not be like this. It counterintuitive from the start in every aspect. And if it really the point that majority of people using C# think it is a bug, not a design decision, then we should fix it now

**Comment by Thaina** [comment]
@jnm2 Actually because we try to say that it has been made. It has been done. It cannot fixed anymore. And so we left this bug as it is. Then there would be people create a subtle bug from non intuitiveness of this feature right now

**Comment by HaloFour** [comment]
@Thaina You not liking it doesn't make it a bug.  The language team and many C# devs both understand this decision and agree with it.  Sure, maybe it's a little unintuitive, the first time.  You learn how it works once.  This is true of most new language features.

**Comment by Thaina** [comment]
@HaloFour Right now I have more confident that it not just because I don't like it but it really not intuitive in general. Many C# dev agree with it *after* they have take part in the result. But if someone does not carefully read every aspect, like someone above, they would have misunderstand that aspect because it really a subtle bug, only when the value is `null`

It not intuitive because both `var` and `is` is not new syntax so we have some expectation over it, and the new feature just break this expectation

**Comment by CyrusNajmabadi** [comment]
Evidence for this claim: "Most people think like that" would be appreciated.

I, personally, don't think that way.  But i don't presume me personal beliefs necessarily apply to the majority of users wrt to this facet of the language :)
