### ISSUE TITLE
[Proposal] Short syntax of properties

### ISSUE THREAD

**Issue by puppets2666** [dotnet/csharplang#1735]
Sometimes properties have onle get and set without any logic:
`public new string Text
        {
            get
            {
                return mainTextLbl.Text;
            }
            set
            {
                mainTextLbl.Text = value;
            }
        }`
I suggest a shorter syntax:
`public new string Text { mainTextLbl.Text; }`
so in curve brackets you put a field which will be returned with get and modified with set

**Comment by ufcpp** [comment]
similar to https://github.com/dotnet/csharplang/issues/1007

**Comment by Joe4evr** [comment]
I will never stop linking [this comment](https://github.com/dotnet/csharplang/issues/1278#issuecomment-360619835) every time someone proposes this exact thing.

**Comment by MohammadHamdyGhanem** [comment]
I suggest to use `using` as in here #2291
