### ISSUE TITLE
Proposal: Add abstract constructors

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/csharplang#1740]
## What is the problem
The following is about non abstract classes:
Some classes have operations each instance has to perform by definition on Initialization (like adding a handle to an Eventhandler) and contracts they have to comply with, like a `NotNull` Attribute on a field. If such a field is supposed to be initialized in different ways, the question is how to initialize such a type.

## How it's solved today
This is currently often done by making a basic (private) constructor which is chained by others, which initialize such a field.
## Why that is no good way of solving the problem
The existence of an invokable constructor not fulfilling these contracts requirements (e.g. that for any instance of the object a string is not null) violates these contracts.
## How my proposal would change that
The idea is that if that base constructor was not invokable for itself, these contracts would not be violated. That is what the `abstract` modifier would do: Make a constructor only chainable, using `: this(Parameters)` or `: base(Parameters)`, but not  invokable for itself.
## Alternative solutions
As @Happypig375 pointed out, Java solves that problem by providing an [Instance initializer block](https://www.javatpoint.com/instance-initializer-block). I do not think that that would be a good solution for c#, because I can't imagine any good syntax for that in C#.
## Optional
Together with that I would suggest that constructors of abstract classes,
should be marked as abstract (because they already behave like the proposed abstract constructors).
To ensure compatibility a missing `abstract` modifier on a constructor of an abstract class would only give a compiler warning.
## Example
```C#
	public class Example {
		[NotNull] public readonly string SomeFilesystemContent;

		public readonly bool IsFolder;
			//Called external
		public static EventHandler DrivesChanged ;

		public abstract Example() {
			DrivesChanged+= DrivesChangedHandler;
		}

		public Example(string itemName): this() {
			SomeFilesystemContent = itemName;
			if (Directory.Exists(itemName)) {
				IsFolder = true;
			} else if (!File.Exists(itemName)) {
				throw new ArgumentException("That is no valid filesystem item", nameof(itemName));
			}
			
			
		}
		public Example(DirectoryInfo folder): this() {
			SomeFilesystemContent = folder.FullName;
			IsFolder = true;
		}
		public Example(FileInfo folder): this() {
			SomeFilesystemContent = folder.FullName;
		}

		private void DrivesChangedHandler(object sender, EventArgs e) {
			if (!Directory.Exists(SomeFilesystemContent)) {
				//Show some error or so
			}
		}
	}
```
## Notes: 

I know that even with such a change such contracts can still be violated, e.g. By reflection, but 

This proposal is not about adding such contracts, only about adding a more formal way of compliance in constructors

**Comment by HaloFour** [comment]
Constructors aren't inherited and don't participate in virtual dispatch.  Marking them as `abstract` doesn't make much sense.

> To ensure compatibility a missing `abstract` modifier on a constructor of an `abstract` class would only give a compiler warning. 

That would still be considered a breaking change.

**Comment by CyrusNajmabadi** [comment]
I've read the "why" section 5 times now and i actually can't figure out what it's trying to say.  Can you give an actual code example that demonstrates why you think such a language feature is necessary?  Thanks!

**Comment by TheMinefighter** [comment]
@HaloFour First is pretty much wrong because this proposal is not about virtual dispatch at all. It is about limiting the ability to invoke the constructor.
Secondary might be the case (for that I marked it as optional)

**Comment by jnm2** [comment]
@TheMinefighter 

> You could not call a method on the beginning of each constructor, because you can't set a readonly there.

Why not make a private constructor to which all the others delegate?

**Comment by TheMinefighter** [comment]
@jnm2 Because it is a contract violation, even if it is private.

**Comment by TheMinefighter** [comment]
@CyrusNajmabadi Clarified by moving the old 'Why' to 'Example' and adding a more understandable 'Why'.

**Comment by jnm2** [comment]
@TheMinefighter I'm sorry for being slow, but in what way is it a contract violation to delegate shared initialization code to a common private constructor?

**Comment by CyrusNajmabadi** [comment]
Sorry, when i said:

>  Can you give an actual code example that demonstrates why you think such a language feature is necessary? 

I meant: "actual code".  i.e. something like this:

```c#
class ExampleClass
{
    [NotNull]public string s;

    // Fill in the rest
}
```

I really can't understand your why/example parts right now because they're so cryptic.

**Comment by jnm2** [comment]
Also `: this(...)` and `: base(...)` syntax is not *inheriting* the referenced constructor but rather *calling* that constructor. Inheriting a constructor would mean that the base class's constructor would be usable directly through the derived class.

**Comment by CyrusNajmabadi** [comment]
I don't get this bit at all:

> If that base constructor was not invokable for itself (by beeing marked as abstract), these contracts would not be violated.

In an abstract class *none* of the constructors are invokable.  After all, the class is abstract.  You can't directly instantiate it *by definition*.

**Comment by TheMinefighter** [comment]
@jnm2 I know it is now technical inheritance, but even Microsoft calls it that: https://blogs.msdn.microsoft.com/tomholl/2008/11/18/constructors-and-inheritance-why-is-this-still-so-painful/

**Comment by TheMinefighter** [comment]
@CyrusNajmabadi this proposal is NOT about constructors in abstract classes it is about abstract constructors in non abstract classes.

**Comment by jnm2** [comment]
@TheMinefighter https://blogs.msdn.microsoft.com/tomholl/2008/11/18/constructors-and-inheritance-why-is-this-still-so-painful/ never refers to `: this(...)` itself or `: base(...)` itself as inheritance as you are doing.

**Comment by jnm2** [comment]
@TheMinefighter 

> this proposal is NOT about constructors in abstract classes it is about abstract constructors in non abstract classes.

You can't have an abstract member in a non-abstract class.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi this proposal is NOT about constructors in abstract classes, it is about abstract constructors in non abstract classes.

@TheMinefighter Could you please please please do this: https://github.com/dotnet/csharplang/issues/1740#issuecomment-408181296

It would help clear up a *lot* of confusion.  Thanks!

**Comment by TheMinefighter** [comment]
@jnm2 You know what I mean with constructor inheritance, give me a better term if you know one, and an (following this proposal) abstract constructors would be allowed in a non abstract class.

**Comment by jnm2** [comment]
@TheMinefighter It's called constructor chaining, or it's simply called a call like any other method call.

**Comment by TheMinefighter** [comment]
@jnm2 done

**Comment by TheMinefighter** [comment]
@CyrusNajmabadi added real code

**Comment by CyrusNajmabadi** [comment]
Why not just write:

```c#
public class Example
{
    [NotNull]
    public string SomeFolderName;

    public readonly bool InitalizedFromString;
    //Called external
    public static EventHandler DrivesChanged ;

    private Example()
    {
        DrivesChanged+= DrivesChangedHandler;
    }

    public Example(string folderName): this()
    {
        SomeFolderName = folderName;
        InitalizedFromString = true;
    }

    public Example(DirectoryInfo folder): this()
    {
        SomeFolderName = folder.FullName;
    }
}
```

?

**Comment by jnm2** [comment]
@TheMinefighter I see what you're asking now, but it's very distracting because `abstract` has a very particular polymorphic meaning which is not how you are using it. You're asking to be able to call an abstract member, like calling `base.AbstractMethod();` but with constructors.

**Comment by jnm2** [comment]
@CyrusNajmabadi They want to be able to inherit from `Example` and but disallow the inheriting class from doing `new Example()`, rather forcing them to call that constructor only via `: base()`.

**Comment by TheMinefighter** [comment]
@jnm2 other suggestions for the keyword?

**Comment by jnm2** [comment]
> if we want contracts which we can be 100% sure about (which should be something we want), the private modifier is a contract violation, e.g. if one of your co-workers uses that inside the class.

I disagree. I use private constructors a lot. You can always abuse private members from within the same class. That's not where the important boundaries lie (or else you need to refactor into multiple classes).

**Comment by TheMinefighter** [comment]
@jnm2 I get your point, but I think that such logical boundary would be better.

**Comment by HaloFour** [comment]
How exactly do you envision such a feature being enforced?  Bear in mind that the .NET ecosystem is comprised of dozens of languages.

**Comment by TheMinefighter** [comment]
I would not enforce it instead (as contracts are in general in .NET except for WCF and some others) I would see it as good coding practice

**Comment by Happypig375** [comment]
Is this literally instance initializer blocks in Java?
https://www.javatpoint.com/instance-initializer-block
```java
class Bike8{  
    int speed;  
      
    Bike8(){System.out.println("constructor is invoked");}  
   
    {System.out.println("instance initializer block invoked");}  
       
    public static void main(String args[]){  
    Bike8 b1=new Bike8();  
    Bike8 b2=new Bike8();  
    }      
}  
```
Output:
```
instance initializer block invoked
constructor is invoked
instance initializer block invoked
constructor is invoked
```

**Comment by eyalsk** [comment]
@TheMinefighter It seems like you're asking to add contracts into the language. 

As far as I can tell the whole point in your proposal is this `[NotNull] public readonly string SomeFilesystemContent;`, i.e, making sure the field is not null but one can easily set it to null through reflection, especially when the field is public and yet the whole discussion is about constructors but then it's in the title so I'd say you got what you asked for. 

Your proposal and example is unfortunately convoluted to say the least so if you really want to have a fruitful discussion you should provide enough information about the problem and only then propose solutions.

**Comment by TheMinefighter** [comment]
@Happypig375 Didn't knew that, but based on the example you are right.

**Comment by TheMinefighter** [comment]
@eyalsk Thanks for the constructive criticism, I think I have clarified the proposal, as it now states "This proposal is not about adding such contracts, only about adding a more formal way of compliance in constructors"

**Comment by eyalsk** [comment]
@TheMinefighter I'd really remove the word contract from this proposal as it can detracts people and instead focus on the initialization part so your example can be as simple as this:
```
public class Example {
	private readonly int _bar; 
	
	// All of the other constructors calls this implicitly 
	public abstract Example(int bar) {
		_bar = bar;
	}
	
	public Example(int bar, string foo) {
	}
	
	public Example(int bar, object foo) {
	}
}
```
As opposed to the following:
```
public class Example {
	private readonly int _bar; 

	public Example(int bar) {
		_bar = bar;
	}
	
	public Example(int bar, string foo) : this(bar) {
	}
	
	public Example(int bar, object foo) : this(bar) {
	}
}
```

**Comment by CyrusNajmabadi** [comment]
> @eyalsk Thanks for the constructive criticism, I think I have clarified the proposal, as it now states:
"This proposal is not about adding such contracts, only about adding a more formal way of compliance in constructors"

Note: you don't actually need any language changes for that.  You can just write an analyzer that checks code and validates that your constructors are abiding by these pseudo-contracts you would like enforced.  Would that not be a sufficient solutoin to this problem space for you?  If not, why not?  Thanks! :)

**Comment by CyrusNajmabadi** [comment]
@eyalsk Interesting idea.  My immediate concerns with any sort of implicit hookup like this is simply: what happens when i want to refactor and have two of these guys (potentially with one dependent on the other?).

**Comment by eyalsk** [comment]
@CyrusNajmabadi So say you want to refactor some of the initialization in ctor `C` and initialize it in `B` because you may have additional ctors that depends on it so I'd imagine this is how it would play out:
```
public class Example {
	private readonly int _bar; 
	
	// A
	public abstract Example(int bar) {
		_bar = bar;
	}

	// B
	public abstract Example(int bar, object foo) /* Implicitly calls A */ {
	}
	
	public Example(int bar, string foo) /* Implicitly calls A */ {
	}
	
	// C
	public Example(int bar, object foo) /* Implicitly calls B */  {
	}
}
```
I'm pretty sure there are challenges here but these example are just to really help people and myself understand what the OP was trying to convey.

**Comment by TheMinefighter** [comment]
@CyrusNajmabadi I am aware of the possibility to run such checks, any serious IDE has such a feature, but I think a solution on language level is far better, because it makes things more clear from a semantic point of view and also clearer for beginners.

**Comment by TheMinefighter** [comment]
Proposal id hereby closed for the following reasons:
 - Most people feel no need for adding a more formal way of compliance in constructors
 - Many people feel confused by the abstract keyword
 - People come rarely in situations where they would need abstract constructors.

Huge thanks to everybody here for participating in this discussion and providing constructive criticism!
