### ISSUE TITLE
[Proposal] _ as discard parameter for lambda unless  referenced

### ISSUE THREAD

**Issue by sirius0xff** [dotnet/csharplang#1745]
Which would allow both:

`SomeEvent += (_,_,_,_)=>foo();`
and
`SomeList.Select(_=>_.Foo).MoreLinq....`

And this would result in an error:
`SomeEvent += (_,_,_,_)=>_.bar();`

==========================================================
If nested, take the closest one in scope:
```
SomeEvent += (_,_,_,_)=>SomeList.Select(_=>_.Foo).MoreLinq....
//same as:
SomeEvent += (_,_,_,_)=>SomeList.Select(__=>__.Foo).MoreLinq....
```
or simply forbid it:
`SomeEvent += (_,_,_,_)=>SomeList.Select(_=>_.Foo).MoreLinq.... //error`

==========================================================
It may cause confusion, so it may be a bad idea.
Please feel free to vote.

**Comment by DavidArno** [comment]
Already "championed": #111. 😄

**Comment by sirius0xff** [comment]
Nice then I close this.
