### ISSUE TITLE
C# 7.3 Enum.TryParse<T> inside of  function with perhaps non-idelal Enum generic constraint

### ISSUE THREAD

**Issue by rychlym** [dotnet/csharplang#1746]
Hi, 
I have tried to write following code with C# 7.3
```
        public static T ParseOptionalEnum<T>(string input, T defaultVal) where T : Enum
        {
            if (input == null)
            {
                return defaultVal;
            }

            if (Enum.TryParse<T>(input, false, out var result))
            {
                return result;
            }

            return defaultVal;
        }
```

This end up with an error message, that TryParse assumes non-nullable argument. 
I tend to a opinion, that that new Enum generic constraint is not ideally designed here. What I assumed, was no error message. (I understand that the Enum.TryParse<T> uses historically struct generic constraint , and the Enum(,ValueType) is defined as a class) 
Have you considered such a case (as I wrote)  already - I believe so?  What about having there rather the enum keyword instead of the Enum in the future meaning just the non-nullable enum?

**Comment by HaloFour** [comment]
The CLR constraint `System.Enum` covers both actual enums as well as `System.Enum` itself, which is oddly not a value type.

You can combine `System.Enum` with `struct` in order to force that the generic type argument be a proper enum.  That should also take care of this nullability issue.

**Comment by rychlym** [comment]
I see,  thanks for the explanation! This looks as a nice trick for me :)
(The 2nd question might  be then moved to not so important : What about the "enum" shorcut as for the "struct, Enum" generic constraint? - I guess, the time will show it  ...)
