### ISSUE TITLE
ref fields

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1747]
Why can't I define a ref field like:
```
class Test<T>
{
   private T nullItem = default;
   private ref T X =  ref nullItem;

   public void Foo(T x) => ref this.X = ref x;
}
```

It's not allowed also to declare a read-write ref property.
Why?

In other words:  Is there any problem that prevents using public refs instead using only local refs?

**Comment by jnm2** [comment]
@MohammadHamdyGhanem It's `field` not `filed`.

You can only take a `ref` to something so long as the compiler can prove that the ref only exists on the stack. It's a runtime limitation, I think. IIRC, the alternative is very expensive GCs.

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem What does this line mean?

> ```private ref T X =  ref nullItem;``` ?

It looks like you're trying to make a ref method.  But you're not providing any parameters to it.  Did you mean:

```private ref T X() { return ref nullItem; }```

?

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem Can you fix your title to be something more appropriate?  Thanks

**Comment by tannergooding** [comment]
@MohammadHamdyGhanem, could you elaborate on:
> It's not allowed also to declare a read-write ref property

It sounds like you are trying to decare a set method as well:
```C#
public class C
{
    private int _field;
    
    public ref int Property
    {
        get
        {
            return ref _field;
        }
        
        set
        {
            _field = value;
        }
    }
}
```

However, for `ref returning properties`, you just need to declare the getter.
public class C
{
    private int _field;
    
    public ref int Property
    {
        get
        {
            return ref _field;
        }
    }
}
```

Since the property is returning a `ref`, it is impliciltly writeable and `Property = value` will compile as expected.

**Comment by MohammadHamdyGhanem** [comment]
@jnm2 
Sorry, I hace a strange keyboard typing mistake that makes me switch two adjacent letters like what happened wilth e and L 😊

@CyrusNajmabadi 
I was trying to implement linked list using ref variables, so I need to store the ref as a public field.

@tannergooding 
It is strange to allow readonly properties to be writable!

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> It is strange to allow readonly properties to be writable!

The property returns a reference, and references are, by definition, writable.

**Comment by jnm2** [comment]
@MohammadHamdyGhanem 

> Sorry, I hace

> like what happened wilth

Okay, I believe you. 😆
There is an edit button...

**Comment by CyrusNajmabadi** [comment]
> I was trying to implement linked list using ref variables, so I need to store the ref as a public field.

I don't know what this means.  Why would a linked list need ref-fields?  Why wouldn't is just have normal fields?

**Comment by CyrusNajmabadi** [comment]
> It is strange to allow readonly properties to be writable!

The property is not writable.  You are simply returning an l-value when you 'get' the property.  An l-value is assignable.  That's... sorta the point :)

**Comment by jnm2** [comment]
@MohammadHamdyGhanem The ref is an address. A normal property getter just returns a value, but a ref property getter returns a value location; i.e., it returns the _potential_ to read and write to a value.

**Comment by MohammadHamdyGhanem** [comment]
@jnm2 
No, this is a touch screen problem,  where my finger is four times the button 😂😂😂

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
I was excrementing with ref, to figure out its limits,  and see if I can use it instead of pointers and copying object references. Clearly it is not possible.
Thanks.

**Comment by jnm2** [comment]
> I was excrementing

Dude. You have to do _something_.

**Comment by CyrusNajmabadi** [comment]
> I was excrementing with

I certainly hope not.

> to figure out its limits, and see if I can use it instead of pointers and copying object references. Clearly it is not possible.

I have no idea what this means.  It concerns me to read this because it feels like you might have inaccurate view of how C# works *regardless* of the 'ref' feature.  A linked list is very trivial to provide in C#, and can be done without any need for 'refs' or 'copying object references'.  it's unclear to me what you could have been doing that would make you think C# was not suitable for this, or that 'ref's would be something you would need to use to address that problem.

I would *highly* recommend *in the future*, that before opening an issue asking "why can't i write this random piece of code" you simply go to gitter.im/dotnet/csharplang and just ask the people there how the feature works, why you would want them, and how it applies to your specific scenarios.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
I closed this becuase @jnm2 gave me the answer I asked for.
https://github.com/dotnet/csharplang/issues/1747#issuecomment-408914818
Thanks.
