### ISSUE TITLE
Feature Request : Make async events returning Task await correctly

### ISSUE THREAD

**Issue by Marshal313** [dotnet/csharplang#1748]
So, I've been drilling with a combination of async methods and events to see if I can find a way to track the raised async event and await it if needed. So I have my event handlers return Task (I know it's not standard and events should return void, But this case is an asynchronous event that needs to be tracked, so it can't be a fire-and-forget task)

I realized that if I await the raise of an async event, Then the control may return to the caller before all listeners' tasks are complete, And that's because when an Asynchronous event is raised, The last listener (which is the one whose value is returned !) may complete sooner than other listeners, therefore the caller awaits ONLY the last listener.
This is obviously not a bug, Because this is how events work. But it can really help if using the usual call parenthesis (TheEvent(sender, args)) calls the event in a way that all listeners are awaitable (Only for events that return an object of type Task) instead of only the last called listener.
There is an Easy way to achieve the expected behavior, Which is to await all listeners before returning to caller using an Extension method, But implementing this method depends on type of the event handler, And for each event handler this method needs to be implemented.  
A more dynamic approach (perhaps using a Generic method) can also be used to then cast the delegates to the given event handler type, But this method can and may introduce bugs later.

So the request is to make this mechanism part of the language. Whenever an event handler returns Task and the event which uses that kind of handler is raised, The the resulting task must be a task awaiting all tasks returned from all listeners of that event.
I have written an example so that you can see what I mean easier. It's just a single .cs file inside this zip file : [AsyncEventWaitExample.cs.zip](https://github.com/dotnet/csharplang/files/2241810/AsyncEventWaitExample.cs.zip)
If you run this example, using the key "1" you can raise the event as usual, and using the key "2" you can raise the event using the extension method I've written for that specific type of Event Handler (AsyncEventHandler<EventArgs>)
If you keep raising the event as usual (using "1" key), you see that some of the listeners' tasks are completed after the last delegate is awaited and "Event raised !" is printed !
But if you raise the event by the extension method (using "2" key), all listeners are awaited therefore the "Event raised !" string is never printed until all listeners complete.

So is it possible for this behavior to be a part of the language ? Of course, Not necessarily using the methods I explained above, But the resulting behavior (to await all listener tasks instead of only the last one) is the required feature !

**Comment by HaloFour** [comment]
Changing the behavior of multicast delegates would be a breaking change.  You can manually use `GetInvocationList` to "unwrap" the multicast delegate used to back the event and then `await` on all of the returned tasks.

**Comment by jnm2** [comment]
I really dislike the idea that it's the publisher's responsibility to handle the subscriber's errors. That's a coupling that doesn't make sense, since the publisher can't have the context it needs to do anything with the exception besides route it to a top-level exception handler.

**Comment by Marshal313** [comment]
How about a new type of event, called async event that would knowingly behave this way. Currently the async keyword is not valid for events, So we can use it to add this feature to the language.
What I have in mind is something like this :
`public async event SomeAsyncEventHandler TheAsyncEvent;`
This will result in a compiler error right now, But this can be a feature of the language. The async event handler can be forced to return an awaitable type.

I guess using this method to implement this feature, we should be able to define a new type of event in the language that is handled differently from usual synchronized events. This way there shouldn't be any need to change the events behaviors, we just define new behaviors !

Am I correct ?

**Comment by Marshal313** [comment]
Well, Then I guess that's it.
The issue is closed.
