### ISSUE TITLE
Proposal: Set namespace for file without indentation or braces

### ISSUE THREAD

**Issue by svarcoe** [dotnet/csharplang#1769]
It would be nice to reduce the level of indentation by being able to declare a namespace for the whole file.
```csharp
namespace is MyProject.Namespace;
using System;
public class MyClass
{
    // Fully qualified typename: MyProject.Namespace.MyClass
}
```

There might be some subtle differences with type searching that people aren't expecting because my example implies that the `using` statements are now inside of the namespace declaration. 

The compiler would have to enforce some rules like only one `namespace` declaration per file and it must be at the top of the file.

**Comment by HaloFour** [comment]
#137

**Comment by svarcoe** [comment]
Sorry....my github search didn't find that. Thanks!

**Comment by HaloFour** [comment]
No worries.  It's like trying to find a specific needle in a needle stack in here.

**Comment by Joe4evr** [comment]
Please close.
