### ISSUE TITLE
Proposal: Allow ref returns for collections with indexer access.

### ISSUE THREAD

**Issue by Neo-Ciber94** [dotnet/csharplang#1773]
Or at least some way for access by ref.

```csharp 
public class List<T>
{
        public ref T this[int index] {get;} 
        //or
        public ref T At(int index);
}
```

I think this will be pretty handy when working with highweight structs or just for performance.

**Comment by svick** [comment]
The language already allows this.

If you're asking for this to be added to the collections that are included in .Net, then the right place for that request is [the dotnet/corefx repo](https://github.com/dotnet/corefx), ideally following [the API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md). There was a related issue about this: https://github.com/dotnet/corefx/issues/25189, but I couldn't find a currently open issue for this request.

**Comment by ufcpp** [comment]
> but I couldn't find a currently open issue for this request.

https://github.com/dotnet/corefx/issues/31598

**Comment by HaloFour** [comment]
This can be done with new collection types, but because it requires exposing pointers directly into the storage mechanism of a class it very likely could not be applied to any existing collection classes and the potential use cases are probably very narrow.

**Comment by Joe4evr** [comment]
dotnet/corefx#25189

**Comment by YairHalberstadt** [comment]
Closing as the language already allows this, and there are existing issues for this feature in dotnet runtime: https://github.com/dotnet/runtime/issues/24110 and https://github.com/dotnet/runtime/issues/27062
