### ISSUE TITLE
type translate grammar

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/csharplang#1774]
if i has a Enum struct likes:
`enum TestEnum {
	Test1,
	Test2,
	Test3
}`
then i want translate string to enum value, i may write if...elseif...elseif...
or Dictionary，or List<Tuple<...>>
then i want a new grammar to easy translate type:
`string s = "Test1";`
`TestEnum e = case (s) { "Test1": TestEnum.Test1, "Test2": TestEnum.Test2, "Test3": TestEnum.Test3 };`
`// the variable e equal to TestEnum.Test1`
or the language has other grammar are easy translate type which i don't know?

**Comment by fawdlstty** [comment]
i know most easy grammar is:
`string s = "Test1";
TestEnum e = new Dictionary<string, TestEnum> { ["Test1"] = TestEnum.Test1, ["Test2"] = TestEnum.Test2, ["Test3"] = TestEnum.Test3 }[s];`
but it's not simple

**Comment by anadale** [comment]
`Enum.Parse`?

**Comment by jnm2** [comment]
This syntax is already coming to C# 8.0 ([live preview](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgD5y4UDmABAMoCeyZAtgNwCwAKEEQKcLkwAqKGAFFR4gN6TpARgA0yzgCYNUzgGYmAX0GCicYABscGJhktRkyJgGFBCwUy9NzVm0zwAexwAEyYAWQAKTgQcRiZkAEpPbyUU7289WXkmCCYAXgSEgHccGAwAC3SMpg8BGu8ASAAiLJVmgoA+TWyxADo2tWqGr1bpLQ787qy5fqydYZGxg0np6VmuAel9IfqRjIB9LqYYCoRA4qYKCEuAQQQGMRFZAA8MCCIYHECKSOaAVQomECDAoOAAXhAwngoJY4BBmhoKFAuBBAmBoolknsGkYePtqiYBEYgA)):

```cs
TestEnum e = s switch
{
    "Test1" => TestEnum.Test1,
    "Test2" => TestEnum.Test2,
    "Test3" => TestEnum.Test3,
    _ => throw new ArgumentException("Unrecognized value", nameof(s))
};   
```

**Comment by fawdlstty** [comment]
hi @anadale i think it's not easy to use because it can't discern example "test2", it restricted.

**Comment by fawdlstty** [comment]
thank you @jnm2, i just like it

**Comment by theunrepentantgeek** [comment]
A key problem here revolves around requirements. 

@fawdlstty, You clearly want a case-insensitive comparison; I've had situations where a case-sensitive comparison was the only acceptable solution. 

What should be the result of parsing `"Test1|Test2"`? What about parsing `0` or `34` or `0x10`? Whatever your preference, I assure you there are projects with other opinions (and if we were to discuss this over a few quiet drinks, I could tell you about several).

There are already several good ways to convert between strings and enumerations - `Enum.Parse()` and `Enum.TryParse()` have already been mentioned. Another is `EnumConverter` (accessible by calling `TypeDescriptor.GetConverter()`.

**Comment by jnm2** [comment]
@fawdlstty There's also `(TestEnum)Enum.Parse(typeof(TestEnum), s, ignoreCase: true)`.

**Comment by AustinBryan** [comment]
And if any of that syntax is too much, you could always write a simple extension method

**Comment by fawdlstty** [comment]
thank you all
