### ISSUE TITLE
[Proposal] optional break keyword in switch, break cases by default, except empty cases.

### ISSUE THREAD

**Issue by sirius0xff** [dotnet/csharplang#1776]
The time for C# to make C++ programmer feel comfortable is long gone.

Currently the break keyword in switch is mostly for annotation only.
Nonempty `case`s is already break-by-default in the sense that missing a break is invalid code.
Empty `case`s can be kept as is.
Hence making `break` optional is backward compatible with existing code.

Code would be less verbose without those redundant `break`s:

```
switch(foo){
case bar:
    some code...
    //break-by-default
case baz: //fallthrough-by-default, can break manually
case boz:
    some code...
    //break-by-default
}

```

**Comment by HaloFour** [comment]
> The time for C# to make C++ programmer feel comfortable is long gone.

What does this have to do with comfort?

C# requires the `break` statement specifically because C++ *doesn't* and this is a known vector for bugs.  Changing that back would do nothing except reintroduce those bug vectors.

**Comment by jnm2** [comment]
See https://github.com/dotnet/csharplang/issues/603 and https://github.com/dotnet/roslyn/issues/959.

**Comment by jnm2** [comment]
See https://github.com/dotnet/csharplang/issues/603 and https://github.com/dotnet/roslyn/issues/959, specifically [Neil's comment](https://github.com/dotnet/roslyn/issues/959#issuecomment-77043389):

> While the design of the `switch` statement may leave much to be desired, it is already in the C# language and familiar to many programmers. Falling through from one case to another is often error-prone, so we disallow it. However, we allow the simple case of fall-through where there are no statements between one case label and the next.
> 
> If we were to change the language to say that there is an implicit `break` after any statements following a case label, that would be a breaking change in the usual case that there is more than one case label in a row. Since we do not want to make breaking changes, we do not want to make the break statement implicit. It would be too subtle to have very different runtime behavior when there are no statements versus there being a single "empty" statement `;`.
> 
> Having said that, we are considering an alternative switch construct for use with the pattern-matching proposal. The main motivation would be to provide an expression form. Since it would be a distinct syntactic form, we are not constrained by the sensibilities (or otherwise) of the existing switch statement.
> 
> Thanks for the question. I hope we've answered it to your satisfaction.

**Comment by bondsbw** [comment]
```c#
// rm.cs

switch(arg)
{
    case "r":
        SetRecursive();
    case "v":
        SetVerbose();
    case "f":
        SetForce();
}
```
This is safe, it'll prompt me.
```sh
> rm -rv C:\
```
Hmm the verbose output is suddenly crashing, I'll just comment it out to test the rest...
```c#
// rm.cs

switch(arg)
{
    case "r":
        SetRecursive();
    case "v":
        //SetVerbose();
    case "f":
        SetForce();
}
```
```sh
> rm -rv C:\
```
Uh oh...

**Comment by sirius0xff** [comment]
Thanks to @jnm2 
Duplicate of dotnet/roslyn#959

**Comment by sirius0xff** [comment]
@HaloFour
clearly did not read the content
