### ISSUE TITLE
Permit a fixed field to be of blittable type

### ISSUE THREAD

**Issue by 4creators** [dotnet/csharplang#1794]
Expanding the range of type which could be used as fixed filed type provides additional flexibility in laying out data. This is of utmost importance in performance scenarios in particular those based on Hardware Intrinsics.

@gafter

**Comment by tannergooding** [comment]
Dupe of https://github.com/dotnet/csharplang/issues/78 ?

**Comment by tannergooding** [comment]
If so, this is already championed and tracked by https://github.com/dotnet/csharplang/issues/1314

Providing some additional details, like how is improves HWIntrinsic based code would also be useful.
The total size of a struct is somewhat limited in the JIT, so the HWIntrinsics scenarios that could use this type of data seems limited.

**Comment by 4creators** [comment]
@tannergooding  Yeah, its dupe. Closing
