### ISSUE TITLE
Document breaking change rule between empty and non-empty struct

### ISSUE THREAD

**Issue by jnm2** [dotnet/csharplang#1797]
I hit this for real. https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md does not mention this source-breaking change:

```cs
using System;

public struct S { }

public class C
{
    public void M()
    {
        S s;
        Console.WriteLine(s);
    }
}
```

###### [(sharplab)](https://sharplab.io/#v2:EYLgHgbALANALiAbgUwE4EsBmBPAPgVwGd0A7AcwAIBlbQuZAWwG4BYAKHYAd9gAbdAMYU6qfALjUKAbwoBfdlx78hA3gENChCgGF2U9hUMVufQRUQB7dABMKAWQAUASgNH9bI58mFWHr4e0LEkILXmQAOgB1DHoAGVJkB0InX095NnSgA==)

After adding a field:

```cs
using System;

public struct S
{
    private readonly int foo;
}

public class C
{
    public void M()
    {
        S s;
        Console.WriteLine(s); // error CS0165: Use of unassigned local variable 's'
    }
}
```

###### [(sharplab)](https://sharplab.io/#v2:EYLgHgbALANALiAbgUwE4EsBmBPAPgVwGd0A7AcwAIBlbQuZAWwG4BYAKHYAd9gAbdAMYU6qfALjV2Ab3YU5FThkQBDehVTJlAEwD2JXtgqkJmHTtZsAvuy49+Qgb2WFCFAMLTZ87n0EVEOuhaFACyABQAlF5yMmzy8dTCFgnybnqEOrzIAHQA6hj0ADKkyGGEEcny1lbsQA)

**Comment by svick** [comment]
If you're asking for corefx documentation to change, why is this issue in the csharplang repo?

**Comment by jnm2** [comment]
Thanks @svick, thought I was in corefx.

`https://github.com/dotnet/corefx/issues/31834`
