### ISSUE TITLE
Proposal: Conditional Assignment Operator (i.e. Null Conditional Operator on Left-Hand Side)

### ISSUE THREAD

**Issue by dhughes55** [dotnet/csharplang#1800]
Consider the following example:

```
var employee = employeeRepo.GetById(id);
if (employee != null)
{
    employee.User = user;
}
```

This is a very common null check situation.  Wouldn't it be nice and compact to allow a null conditional operator on the left-hand side of the assignment like so:

```
var employee = employeeRepo.GetById(id);
employee?.User = user;
```

The null conditional operator used here would be interpreted by the compiler to mean:

- If employee is not null, set its user property to the user variable on the right.
- If employee is null, short circuit the entire line of code and perform no assignment.

So essentially, the null conditional operator would act as a conditional assignment operator.

Thoughts?

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/34

**Comment by dhughes55** [comment]
I figured someone somewhere had already proposed this but I couldn't seem to find it anywhere.  Good deal.  Closing this issue.
