### ISSUE TITLE
a

### ISSUE THREAD

**Issue by foremptyonly** [dotnet/csharplang#1802]

**Comment by GSPP** [comment]
We should definitely implement this.

**Comment by DarthVella** [comment]
Most of this will fall under Shapes and Extensions, right?

**Comment by yaakov-h** [comment]
Either that, or Code Generators.

**Comment by jnm2** [comment]
@foremptyonly This looks like generic specialization. You might be interested in https://github.com/dotnet/csharplang/issues/1315.

**Comment by jnm2** [comment]
Wait a minute, the original text of this issue is identical to https://github.com/dotnet/csharplang/issues/1803 which is already pointed in the same direction.

What's up with this issue?
