### ISSUE TITLE
Async Main method in console application gives build error for "C# latest major version (default)"

### ISSUE THREAD

**Issue by NishantThakkar** [dotnet/csharplang#1804]
Async Main method in console application gives build error for default language version selection which is "C# latest major version (default)".

![image](https://user-images.githubusercontent.com/5793534/44384002-48077500-a538-11e8-94ea-f1b1a806cba4.png)

Code:
```
 static async Task Main(string[] args)
 {
      HttpClient _httpClient = new HttpClient();
      string json = "some json";
      await _httpClient.PostAsync("https://someurl.com", new StringContent(json, Encoding.UTF8, "application/json"));
      Console.ReadKey();
  }
```

Build error:

![image](https://user-images.githubusercontent.com/5793534/44383812-ac760480-a537-11e8-90c9-a87a1b811961.png)

Now if i change default selection to any C# version:

![image](https://user-images.githubusercontent.com/5793534/44384016-535aa080-a538-11e8-9753-3e4fb859775b.png)

Project build successfully:

![image](https://user-images.githubusercontent.com/5793534/44384066-7c7b3100-a538-11e8-8707-9b12b7c5eaea.png)

**Comment by theunrepentantgeek** [comment]
This is [as documented](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1) - specifying _latest major version_ means **v7.0** and `async Main()` was introduced in **v7.1**.

**Comment by NishantThakkar** [comment]
Got It. Thank you.
