### ISSUE TITLE
Set method without backing field

### ISSUE THREAD

**Issue by sd016808** [dotnet/csharplang#1805]
If we need a custom get/set method, we need a backing field like this:

```csharp
private decimal _valueDecimal;
public decimal ValueDecimal
{
    get => _valueDecimal;
    set
    {
        if (_valueDecimal == value)
            return;

        _valueDecimal = value;
        OnPropertyChanged();
    }
}
```

If I have a lot of custom properties, it's very tired to declare several backing fields.
Can we use some keyword like "backingField" instead of declaring a backing field? 
e,q,
```csharp
public decimal ValueDecimal
{
    get => _valueDecimal;
    set
    {
        if (backingField == value)
            return;

        backingField = value;
        OnPropertyChanged();
    }
}
```

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/140

**Comment by jnm2** [comment]
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
