### ISSUE TITLE
Discussion: Referring to implementing type in generics

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#1808]
## Problem
Consider an interface IGroup:

```
public interface IGroup
{
     IGroup Operation(IGroup operand);
     IGroup Identity {get;}
}

``` 
And consider a generic Reduce function on IGroup:

```
public T Reduce<T>(IEnumerable<T> items, T seed) where T : IGroup
{
    IGroup result = seed;
    foreach(var item in items)
        result = result.Operation(item);
    return (T) result;
}

```

Now there's quite a few problems here.

Firstly, anything that implements IGroup, must define Operation for an operand of any IGroup implementation. But since this is impossible, they must check to see if the operand is of the implementing type, and throw an exception of it is not, thus reducing type safety.

Secondly, the Reduce function has to do a runtime cast in order to return a T not an IGroup, again reducing type safety.

## Discussion

It would be useful if there were some way to refer to the implementing type in an interface. Perhaps a keyword like `impl`. Then IGroup would look like this:

```
public interface IGroup
{
     impl Operation(impl operand);
     impl Identity {get;}
}
```
An implementation might be `Integer`:

```
public class Integer : IGroup
{
    public int Value {get; set;}
    public Integer Operation(Integer operand) => new Integer{Value = Value+operand.Value};
    public Integer Identity => new Integer{Value = 0};
}
```

I don't know what the best way to implement this feature would be. It could be a compile time trick to cast everything from the implementing type to an IGroup and vice versa would be sufficient.

## Issues

1. Inheriting an implementation of IGroup

Consider our Reduce function as it would look now:

```
public T Reduce<T>(IEnumerable<T> items, T seed) where T : IGroup
{
    T result = seed;
    foreach(var item in items)
        result = result.Operation(item);
    return result;
}

```

Looks great? 
Afraid not. What if `SomeClass : Integer` and I call `Reduce<SomeClass>`? The SomeClass.Operation does not return SomeClass but an Integer.

So we would need to add another constraint `directly` meaning that a class directly implements an interface:

```
public T Reduce<T>(IEnumerable<T> items, T seed) where T : directly IGroup
{
    T result = seed;
    foreach(var item in items)
        result = result.Operation(item);
    return result;
}

```

Now it would be impossible to call `IReduce<SomeClass>` since it does not directly implement IGroup.

2. What about dealing with an the interface directly.

At first this doesn't seem like much of a problem. When I have a reference to an IGroup, and I call IGroup.Identity, I know it will return impl where impl:IGroup, so I can just implicitly cast the return type to an IGroup.

However things get more complicated when returning a generic type. Returning an `IReadOnlyList<impl>` would be fine, since it is contravariant, and so castable to `IReadOnlyList<IGroup>`. However if an interface method returned a `List<impl>` it would not be able to be called from a reference to the interface directly, and would only be able to be called via generics.

In order to make the implementation of this feature purely compile time with no runtime support, it would be easiest to say that any generic interface method return types must be contravariant in impl, and any generic interface method parameters must be covariant in impl.

**Comment by mcosmin222** [comment]
Why does a type implementing IGroup have to know about other implementations of IGroup for the Operation method? 

I implemented a dummy example of your code and I don't see any problem. Aside from the cast in the Reduce method, which I think shouldn't be there (the method should return IGroup, not a concrete implementation), but that bares no importance.

**Comment by mcosmin222** [comment]
In a few hours, when I get back home.

anyways, it is a dummy impl, some class implementing IGroup, operation returns a new instance of it, and Reduce is public static in a helper class.

**Comment by yaakov-h** [comment]
Related to #252, #902.

**Comment by ufcpp** [comment]
[Shapes](https://github.com/dotnet/csharplang/issues/164) is different approach but might solve this problem.

**Comment by ghostnguyen** [comment]
Does #1803 address your concern?

**Comment by YairHalberstadt** [comment]
@ghostnguyen I don't see how

**Comment by zippec** [comment]
@YairHalberstadt 
Maybe this design could get close to what you want?
```C#
public interface IGroup<TThis> where TThis : IGroup<TThis>
{
    TThis Operation(TThis operand);
    TThis Identity { get; }
}
public class Integer : IGroup<Integer>
{
    public int Value {get; set;}
    public Integer Operation(Integer operand) => new Integer{Value = Value+operand.Value};
    public Integer Identity => new Integer{Value = 0};
}
```

**Comment by YairHalberstadt** [comment]
@zippec 
Whilst that would partially work, it makes it impossible to accept a reference of `IGroup`, since you would need to know `TThis`.
For example, you couldn't create a `List<IGroup>`, only a `List<T> where T : IGroup<T>`

**Comment by CyrusNajmabadi** [comment]
> For example, you couldn't create a `List<IGroup>`, only a `List<T> where T : IGroup<T>`.

Why would that be a problem?  If you want to operate purely generically, without knowing this info, then you can define things like so:

```c#
public interface IGroup
{
    IGroup Operation(IGroup g);
    IGroup Identity { get; }
}

public interface IGroup<TThis> : IGroup where TThis : IGroup<TThis>
{
    TThis Operation(TThis operand);
    TThis Identity { get; }
}
```

Now, if you want a list where you're unburdened from knowing the inner type, you just refer to the ungeneric IGroup.  If you want the strong typing, and yo uwant to prevent problems like mixing/matching groups of the wrong type, you use the generic derived interface.

**Comment by yaakov-h** [comment]
Then you have to double-implement everything like IEnumerable<T> 😞

**Comment by CyrusNajmabadi** [comment]
>Then you have to double-implement everything like IEnumerable<T> 😞

DIM addresses that.  You just have your DIM do the following:

```c#
public interface IGroup<TThis> : IGroup where TThis : IGroup<TThis>
{
    TThis Operation(TThis operand);
    TThis Identity { get; }

    IGroup IGroup.Operation(IGroup operand) => this.Operand((TThis)operand);
    IGroup IGroup.Identity => this.Identity;
}
```

**Comment by jnm2** [comment]
Made me think of https://github.com/dotnet/csharplang/issues/1328.

**Comment by YairHalberstadt** [comment]
#2493 is related, and appears to have more support. Closing.
