### ISSUE TITLE
Implicit type infer for method groups

### ISSUE THREAD

**Issue by SymmetryKeeper-Y** [dotnet/csharplang#1810]
There is implicit type infer for lambdas, but there is not for method groups.
Why not? There are unobvious technical difficulties?

```c#
using System;

static class TestClass
{
    static void MethodOne() { }
    static void MethodTwo(object x) { }

    static void Test(Action a) { }
    static void Test<T>(Action<T> a) { }

    static void Test()
    {
        Test(() => { });
        Test(MethodOne);

        Test((object x) => { }); // type infer from a signature of a lambda
        Test(MethodTwo); // <= compile errors, no type infer from a signature of a method
    
        Test<object>(MethodTwo); // an implicit conversion to Action<object> without type infer
        Test((Action<Object>)MethodTwo); // an explicit conversion to Action<object> with type infer
    }
}
```
Can not compile a line `Test(MethodTwo);`
```c#
// error CS1503: Argument 1: cannot convert from 'method group' to 'Action'
// error CS0411: The type arguments for method 'TestClass.Test<T>(Action<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```
[[sharplab.io]](https://sharplab.io/#v2:D4Vwzglgdg5gBAZQJ5gC4FMC2BuAsAKALQENUIBjOcgG2LDDgBV00BhW+ggbwIEgSylAG4B7CABM4AWXSoAFiPEB5KOgAUASjhc4AXz4CKcUROmyF4xgHcRakQCMAVunKo4ADy079hfP1SkRiaSzGgAjGoAgq4QIlBwxF56BgGCxmIhLKgAPIwAfFExcbl5CUk+KYHCGUxZmnw8+HDNLc2hqBGacAC8pd4aeE2tLe0RMvKKKugDBATDI3V2Ti5unj19egNwAPTbcKhIAA7ocNAAZugATnBnlyKYCXCQMFCkIJcnImePtJj24sQ5vNamg1OMLNYRFtdnBst0qPdDhBqCcrndLmAADRwKAifZHE7nK43O4PYhPCAvN4fOBfR6YcyKPhA+btbIOZyuArgxSQ6F7YjxCCYQ7UCgQNzkOJCK6QOL7PHRMjFDkrPIs4btNSFZVQbJKZZcjQ8yw2fkJeLodyi8WS6Wy2LxVCKop61VcjU+XRAA=)

**Comment by jnm2** [comment]
I think this is a dupe of https://github.com/dotnet/csharplang/issues/129.

**Comment by SymmetryKeeper-Y** [comment]
@jnm2 
Yes, it is closely related.
