### ISSUE TITLE
Method(params ITuple args)

### ISSUE THREAD

**Issue by SymmetryKeeper-Y** [dotnet/csharplang#1811]
Currently supported
```c#
void M<T>(params T[] args) => ...

M(new [] { 1, 2, 3, 4 });
M(1, 2, 3, 4);
```
Nice to have
```c#
void M<T>(params T args) where T: ITuple => ...

M( (1, 2, 3, 4) );
M(1, 2, 3, 4);
```
- no array allocations
- no boxings during arguments passing

Examples of usage:
1. Generalizations and optimizations
```c#
 /* boxing free equals */
public static bool Equals<T>(T a, T b) => EqualityComparer<T>.Default.Equals(a, b);

public static bool Is<T>(this T o, T x) => Equals(o, x); /* Equals<T>(o, x); */
public static bool Is<T>(this object o, T x) => o is T && Equals((T) o, x);
public static bool Is(this object o, object x) => Equals(o, x);
public static bool Is<T>(this T o) => o != null;
```
```c#
x.Is(3) // x is 3
x.Is(a)
(x, y).Is((1, 5))
(x, y).Is((a, b))
```
Remarkable that currently compiler translate an expression `x is 3` as `object.Equals(3, x)` instead more effective form `EqualityComparer<int>.Default.Equals(3, x)`

Of course for tuples `(x, y).Is(1, 5)` looks more pretty which may be implemented via creating of a range of overloads

```c#
//public static bool Is<A, B>(this (A) x, A a, B b) => x.Is((a));
public static bool Is<A, B>(this (A, B) x, A a, B b) => x.Is((a, b));
public static bool Is<A, B, C>(this (A, B, C) x, A a, B b, C c) => x.Is((a, b, c));
public static bool Is<A, B, C, D>(this (A, B, C, D) x, A a, B b, C c, D d) => x.Is((a, b, c, d));
// etc...
```
or via a much more elegant feature

```c#
public static bool Is<T>(this T x, params T o) where T : ITuple => x.Is(o);
```

2. Abstract factory initializers and micro optimizations

```c#
IList scientists = new List<string>(5) // explicit 5 (calculated by a programmer)
{
  "Plank",
  "Bohr",
  "Schrodinger",
  "Einstein",
  "Feynman"
};

// abstract type specification, infer and merging
var scientist = New.IList // implicit 5 (calculated by a compiler)
(
  "Plank",
  "Bohr",
  "Schrodinger",
  "Einstein",
  "Feynman"
);

var scientist = GetScientist().Merge
(
  "Newton",
  "Maxwell"
);
```
```c#
GetModel().To(out var m).With
(
  m.Prop0 = value0,
  m.Prop1 = value1,
  m.ToString().To(out _currentModel)
)
```
```c#
public static T With<T, TTuple>(this T o, params TTuple x) where T : ITuple => o;
```

**Comment by svick** [comment]
My issue with this approach is that `ITuple` is not strongly-typed. This means that:

1. There is usually no compile-time checking that the right type is passed in, e.g. `GetScientist().Merge(42)` would still compile.
2. If the passed-in values are value types, they have to be boxed and unboxed to be accessed through `ITuple`.

Because of that I think that "params Span\<T>" https://github.com/dotnet/csharplang/issues/1757 is a much better solution.

**Comment by SymmetryKeeper-Y** [comment]
@svick 
Agree with you that for collection extensions `params Span<T>` looks better.
But seems that for some cases `params ITuple` have sense too.

**Comment by gafter** [comment]
This is not something we would consider.

**Comment by SymmetryKeeper-Y** [comment]
@gafter 
Objectively why? If you see obvious lacks of the proposal, can you explain?
