### ISSUE TITLE
A shorter syntax for cases with multiple values in switch 

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1822]
I ran into this switch case:
```
switch (var) {
        case ' ': 
        case '\n': 
        case '\r': 
        case '.': 
        case ',':
        case '،':
        case '?': 
        case '!':   
        case '(':  
        case ')':
            //Do Something
           break;
}
```

It will not be better if rewritten as:
```
switch (var) {
        case ' ': case '\n': case '\r': case '.': case ',': case '،': case '?': case '!':  case '(':  case ')':
            //Do Something
           break;
}
```

So, why can't C# allow this:
```
switch (var) {
        case ' ', '\n', '\r', '.', ',', '،', '?',  '!',   '(',  ')':
            //Do Something
           break;
}
```

And if it is somehow embarrassing to use VB.NET style, so I suggest this:

```case in {' ', '\n', '\r', '.', ',', '،', '?',  '!',   '(',  ')'}:```
This last syntax will allow us to use arrays directly.. Suppose we have an array named Arr:
```case in Arr:```

**Comment by HaloFour** [comment]
#1350 

```cs
switch (var) {
    case ' ' or '\n' or '\r' or '.' or ',' or '،' or '?' or '!' or '(',  ')':
        //Do Something
        break;
}
```

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
Good, but "or" will be strange in c#. It is not used in logical conditions elsewhere, besides ", " is more compact than " or ".
Also, ```in { }``` can be extended to use ranges:
```case in [1..9]```

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> Good, but "or" will be strange in c#.

Everything new is strange, until it isn't.

> besides ", " is more compact than " or ".

Compactness isn't particularly important, especially when the difference is one character.

What is more important is that `or` is proposed to have significantly more utility in that it can be used *anywhere* that patterns can be used, including within recursive patterns, where `,` both wouldn't make sense and would be ambiguous.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
Let me put it this way:
Why don't you use | instead of or?.. | is the C# symbol for or, and it will be confusing if you use botth I and or in different places. Use I in all places, or allow "or' to be used in conditions and bitwise operations!

**Comment by CyrusNajmabadi** [comment]
> Why don't you use | instead of or

Because it already has meaning.  For example, it already has meaning if you `|` together two characters.  C# cannot break that meaning.

> and it will be confusing if you use botth `I` and `or` in different places

Why?  C# already does this.  If you use linq, there's a `equals` keyword in a `join` clause.  We don't use .Equals, or `==`.

**Comment by alrz** [comment]
I think the team is considering `in (1, 2)` syntax for or patterns (and probably `all (I1 x, I2 y)` for and? I don't know if that's any better.

**Comment by dsaf** [comment]
It will be fun explaining to new users why LINQ does not have ```or```, ```and``` but a legacy branching logic construct does.

**Comment by HaloFour** [comment]
@alrz 

> I think the team is considering `in (1, 2)` syntax for or patterns

That's not a bad syntax.  It works well for constant patterns, but I think it might get muddied for other patterns?

```cs
switch (point) {
    case in ((0, _), (_, 0)):
        // Do Something
        break;
}
```

Kind of looks like a bug looking back at me.

It does solve any concerns regarding precedence, though.

**Comment by MohammadHamdyGhanem** [comment]
1.what is wrong with using only commas? It is familiar and easier.
2. What about 
case in [1, 5, 7]:
case in [i.. 15];
case in Arr
Case in valuetuple
This will make us able to check contents of collections and tuples and any enumersble type.
2.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

> case in [1, 5, 7]:

That would preclude future patterns to match against arrays/lists.

> This will make us able to check contents of collections and tuples and any enumersble type.

Patterns apply against constants, not other variables.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
Select case in vb matches any thing: constants, variables, or expressions. It doesn,t mach values in collections,  tuples, or ranges, so i hope itdo that, and hope c# swich case does all what vb's does.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

`switch` is not `Select Case` and it's been expressed multiple times that the C# team has no interest in achieving parity between the two.  The pattern matching proposal as it stands has no plans for patterns based on variables.

**Comment by gafter** [comment]
Closing as a dup of https://github.com/dotnet/csharplang/issues/1350
