### ISSUE TITLE
autoasync noawait

### ISSUE THREAD

**Issue by japm** [dotnet/csharplang#1823]
Please consider allowing to complement the await  programming model with two new keywords 

**autoasync**  and **noawait**

consider the following code

```
  class MyClass{
     Task<int> DoTask1(){ .........................}
     Task<int> DoTask2(){ .........................}
     Task<int >DoTask3(){ .........................}
     Task<int> DoTask4(){ .........................}

     public async Task CallTasks(){
             
             if ((await DoTask1()) < 0)
                 return;
             if ((await DoTask2()) < 0)
                 return;
             if ((await DoTask3()) < 0)
                 return;

             DoTask4();
             return ;
     }
}
```

could be written with the 2 new keywords the opposite way

```
  class MyClass{
     Task<int> DoTask1(){ .........................}
     Task<int> DoTask2(){ .........................}
     Task<int> DoTask3(){ .........................}
     Task<int> DoTask4(){ .........................}

     public autoasync Task CallTasks(){
             
             if (DoTask1() < 0)
                 return;
             if (DoTask2() < 0)
                 return;
             if (DoTask3() < 0)
                 return;

             
             noawait DoTask4();
             return ;
     }
}
```

autoasync would automatically await on all functions returning task 
(i think is at leas 90% true for async method), noawait allows for obtaining
the returning task and use it as you want.

This would ease the transition from sync to async and clean the method implementation
from excessive language keywords usage, avoiding repeating await in all your code

**Comment by japm** [comment]
Im explicitly doing a choice at programming time about the behavior of a function, is not hiding anything. If 99% of your async methods calls await on every task returning method, what is the purpose of obligatory having to call await in all calls ?
How this improves the understanding of the code ?

Async/Await is all about concurrency/paralellism/thread reuse, My programs logic has nothing to do with this, its all about business logic and i'd like it stay in this way.

**Comment by HaloFour** [comment]
@japm 

> If 99% of your async methods calls await on every task returning method, what is the purpose of obligatory having to add await in all calls ?

To explicitly acknowledge that you want that part of the function turned into a suspension point of the generated coroutine, which is expensive and changes the behavior of that expression.

Also note that `Task` and `Task<T>` are not the only types that are awaitable.  The `await` keyword recognizes a pattern that can be satisfied by literally any type as long as it matches the awaitable convention.  And as `await` can be used anywhere within an expression.  This would be asking the compiler to attempt to automatically generate a suspension point for every value in every expression.  You could end up with suspension points where you didn't expect them, and you could end up missing suspension points where you expected them if the expression didn't fit the awaitable convention, as the compiler would have to silently skip them.

**Comment by japm** [comment]
Ok, i understand your point of vew.

We are trying to move a large codebase to async pattern, and its almost impossible not to miss an 
await, and our logic ends up having tons of await and  ConfigureAwait(false). I think there should be a way to make this implicit by convencion, instead of manually inserted in the code by the programmer.

But its true my understanding of the whole problem can be narrow-minded, and i dont see all the edges of the problem.

**Comment by bondsbw** [comment]
I like the idea, just not in C#.  It probably works well for a language which was originally designed around this message passing model.

**Comment by japm** [comment]
No positive reviews on this, so closing this issue

Thanks for your feedback @HaloFour , @bondsbw
