### ISSUE TITLE
Proposal: allow trailing comma for `params` arguments

### ISSUE THREAD

**Issue by daniel-white** [dotnet/csharplang#1824]
Similar to #1246, but in a smaller scope.

Since `params` generates an array of the specified types from the remaining arguments, it is akin to a collection initializer. With no other arguments permitted after the `params` argument, this should be well defined as to which method is invoked. With logging or other format strings, this would be handy.

Given this signature:

```
 void Log(string format, params object[] args)
```

these should be treated the same

```
Log(
    format,
    a,
    b,
    c
);
```
and
```
Log(
    format,
    a,
    b,
    c,
);
```

**Comment by svick** [comment]
I don't think it makes sense to have special syntax just for `params`. And for the general case, there is already https://github.com/dotnet/csharplang/issues/391.
