### ISSUE TITLE
Expression Bodied Properties: [method: .... attribute target 

### ISSUE THREAD

**Issue by AlexanderMorou** [dotnet/csharplang#1827]
# Expression Bodied Properties: [method: .... attribute target
This was ported by request from [dotnet/roslyn Issue 29566](https://github.com/dotnet/roslyn/issues/29566).
## Summary
It is impossible to currently assign attributes to the get method of an expression bodied property.  It should be allowed.
## Proposal
The proposal is to allow `method:` target on such properties since they have only one possible method defined in their metadata.  There is no ambiguity on what the target is in this scenario.
```C#
[method: ForSomeMethod]
public bool MyProperty => SomeExpression;
```
The current equivalent non-expression bodied method is:
```C#
public bool MyProperty { [ForSomeMethod] get => SomeExpression; }
/* or */
public bool MyProperty { [ForSomeMethod] get { return SomeExpression; } }
```

**Comment by CyrusNajmabadi** [comment]
This:

```c#
[method: ForSomeMethod]
public bool MyProperty => SomeExpression;
```

Does not seem substantively better than:

```c#
public bool MyProperty { [ForSomeMethod] get => SomeExpression; }
```

Its the exact same amount of code, and the latter makes it clear which method is applies to.  The latter also would work for things like auto-props.

**Comment by AlexanderMorou** [comment]
It's not a matter of which is better.  It's a matter of one simply being **unable** to do what the other does.

**Comment by CyrusNajmabadi** [comment]
> It's not a matter of which is better. It's a matter of one simply being unable to do what the other does.

I get that.  I'm saying: i don't believe there's a need for the expression-body form to have this capability.  If you need this, just use the normal accessor-form, optionally using an expression-bodied accessor if you want.

Expression-bodied props are intended for the ultra common case of not needing all the powerful config possible with a full prop.  The goal is not to have expression-bodied props, but then have them allow for all that same power.  The goal is just to have something simple and easy for the common case.  When you have to do something uncommon, just pop back out and use the full form that allows for this.

**Comment by AlexanderMorou** [comment]
Fair point.
While nothing is usually as simple as it seems, it felt like this may not be terribly hard to accomplish.

Though, just because it's easy to do doesn't mean you should necessarily do it.
