### ISSUE TITLE
Spec does not mention type 'overloading' on number of type arguments

### ISSUE THREAD

**Issue by Septiple** [dotnet/csharplang#1829]
I believe that the spec currently disallows this code:

```
class A {}

interface A<T>{}

struct A<T, U>{}
```

[In Basic concepts, under Declarations](https://github.com/dotnet/csharplang/blob/master/spec/basic-concepts.md#declarations), it states:

> Except for overloaded members (Signatures and overloading), it is a compile-time error to have two or more declarations that introduce members with the same name in a declaration space. It is never possible for a declaration space to contain different kinds of members with the same name.

[In Classes, under Class declarations](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#class-declarations), it states:

> (...) followed by the keyword class and an identifier that names the class, (...)

The same wording is used in structs and interfaces. If I interpret the spec correctly, the code above declares three types named `A`, all of different type (class vs struct vs interface), which is illegal in two ways under the spec. I haven't found any other place in the spec that makes the above code legal, but of course I might have missed it.

Of course, [Namespace and type names](https://github.com/dotnet/csharplang/blob/master/spec/basic-concepts.md#namespace-and-type-names) goes out of its way to allow type 'overloading' on the number of parameters, and the above compiles and is perfectly sensible code, so I'd say this is an omission in the spec (or at least it would be good to clarify this in Basic concepts).

I'd say the spec should either state that a class declaration class `A<T>{}` declares a class with name `A<>`, or it should allow name overloading on the number of parameters.

**Comment by svick** [comment]
The [ECMA version of the C# 5.0 spec](https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf#%5B%7B%22num%22%3A927%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C55%2C411%2C0%5D) (released in Decmber 2017) does clarify this:

> It is a compile-time error to have two or more declarations that introduce members with the same name in a declaration space, except in the following cases:
> * […]
> * Two or more type declarations with the same name but distinct numbers of type parameters are 
allowed in the same declaration space (§8.8.2).

As far as I understand it, the ECMA version of the spec is supposed to form the basis of new versions of the spec going forward, so I think there isn't anything to do here but wait until the ECMA version of the spec is updated to be more current. It should get republished here then.

**Comment by Septiple** [comment]
Sounds good, thanks for the info!
