### ISSUE TITLE
Add support for copy constructors

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/csharplang#1842]
Like [copy constructor in C++](https://en.cppreference.com/w/cpp/language/copy_constructor).

The syntax could be something like this:

```csharp
public class Person
{
    public Person(Person original)
        : copy(original)
    {
    }

    public int Id { get; set; }
    public string Name { get; set; }
}
```
This would perform a shallow copy of all fields from the original to the current instance.

The `copy` keyword could also accept a base class of the current class, enabling scenarios like this:

```csharp
public class PersonWithAge : Person
{
    public PersonWithAge(Person original)
        : copy(original)
    {
    }

    public int Age { get; set; }
}
```

This would make it easy to make derived types with extra information:

```csharp
Person person = ...;
var withAge = new PersonWithAge(person) { Age = 42 };
```

**Comment by Joe4evr** [comment]
This is part of [the "With"-method syntax that's part of Record types](https://github.com/dotnet/csharplang/blob/master/proposals/records.md#caller-receiver-parameters). Despite its category, it'll be applicable to any type, not just Records.

**Comment by quinmars** [comment]
I guess the `.With(...)` method would generate an instance of `Person` not `PersonWithAge` and you would have to implement it on your own like you have to implement the (copy) constructor on your own today.

**Comment by thomaslevesque** [comment]
@Joe4evr this is related, but not really the same thing. For instance, it wouldn't help in my example with a derived class

**Comment by Joe4evr** [comment]
Yeah, I was drawing a conclusion too early there. Your problem is perfectly solvable with a normal constructor, though.
```cs
public class Person
{
    public int Id { get; }
    public string Name { get; }

    public Person(int id, string name)
        => (Id, Name) = (id, name);

    public PersonWithAge WithAge(int age)
        => new PersonWithAge(this, age);
}
public class PersonWithAge : Person
{
    public int Age { get; }

    public PersonWithAge(int id, string name, int age)
         : base(id, name)
         => Age = age;

    internal PersonWithAge(Person p, int age)
         : base(p.Id, p.Name)
         => Age = age;
}
```

**Comment by quinmars** [comment]
I also use frequently classes with "copy" constructor and I hate to implement the constructor, because it is error prone and boring work, hence I have sympathy for that proposal. But I see some problems, mainly with inheritance.
There is no way for the compiler to copy private fields of a base class, that includes the backing fields of auto properties. Alternatively the compiler could generate code that assigns all properties. For simple auto properties that's probably what you except, but it's not difficult to construct examples where this would lead to unexpected results. If you think for example on WPF dependency properties. Also, the assignment of derived properties could cause unexpected overhead. On the other hand if you restrict the feature to only direct descendants of `object` or to only copy the immediate fields of the class (ignoring the inherited ones), the feature would become very special.

**Comment by theunrepentantgeek** [comment]
> This would perform a shallow copy of all fields from the original to the current instance.

And immediately run into issues whenever one of those fields is a container of any kind - `List<T>`, `Dictionary<K,V>`, `HashSet<T>`  are very commonly used.

Essentially this proposal is running into the sames problems as `ICloneable`, where a shallow copy is only the "correct" solution for simple cases.

**Comment by AustinBryan** [comment]
@theunrepentantgeek And that would include arrays too, right?

**Comment by thomaslevesque** [comment]
@theunrepentantgeek I'm aware of this limitation. I'm not looking for a way to do a deep clone of an object.

**Comment by Joe4evr** [comment]
You're gonna have to write the specific per-object logic for that yourself.

**Comment by jnm2** [comment]
I really want this syntax:

```c#
var person = new Person(...);
var personWithChangedName = person with { Name = "New name" };
```

**Comment by thomaslevesque** [comment]
> Implementing a copy constructor by doing a shallow copy of members is only correct for a subset of types - the exact subset where writing the copy constructor is trivial.

Trivial, but annoying. And you have to change it every time you add a new member.

> As soon as the class includes any kind of container, whether a list, set, dictionary, or array

Or even any instance of a mutable reference type.

> things get more complicated - not least because it's not as simple as doing a deep clone of everything.

Yeah, I'm aware of that. But in many cases a shallow copy is enough.

Anyway, I realize this feature will probably never be added; it just doesn't provide enough value. I guess I just suggested it out of frustration at having to manually copy all properties.

**Comment by msedi** [comment]
At the beginning I was coming to the same conclusion as @thomaslevesque, but over time I saw that the concept of C++ does not really work with reference and value types. So I created by own static Copy methods where I can directly control how the object is cloned.

I had also colleagues did haven't much understood the concept of reference and values types and applied the copy by simply assigning the values from the source struct to the target struct. While there was no problem with the value types there were of course problems with strings and arrays. Which they didn't recognize.

This might happen to a shallow copy also and now one recognizes this, Nevertheless, if someone is not aware of reference and values types it will happen in either case.

I came to the conclusion the some sort of ICloneable with better support how to clone would be a better approach or some general concept to clone an object. I haven't found out yet what's the best concept, though.

**Comment by theunrepentantgeek** [comment]
> I just suggested it out of frustration at having to manually copy all properties.

@thomaslevesque FWIW, I completely agree with you, copy constructors can be frustrating to write and it's really easy to forget a new property.

The practice I've adopted to mitigate this is to write a [property based](https://github.com/fscheck/FsCheck) _unit test_ for the copy constructor that uses reflection to check that all the properties were copied across. It's not perfect, but such a test catches almost all updating errors.

**Comment by thomaslevesque** [comment]
@theunrepentantgeek thanks for the tip!

**Comment by erik-kallen** [comment]
@thomaslevesque you might also find `object.MemberwiseClone()` useful.

**Comment by thomaslevesque** [comment]
> @thomaslevesque you might also find `object.MemberwiseClone()` useful.

It returns a new instance of the same type, so it doesn't help if I want to do `new DerivedClass(instanceOfBaseClass)`. Also, it's protected, so I can't call it from outside.
