### ISSUE TITLE
Ternary switch

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1844]
I suggest this syntax for a ternary switch:

``` 
var Result = switch(I) { 
   case 0 => "Zero",
   case 1 => "One",
   case 10 => "Ten",
   case 100 => "Hundred",
   case 1000 => "Thouzand",
   default => "Any Other Number"
};
```

This is a short syntax for:
```
string Result;
switch(I) {
   case 0:
        Result = "Zero";
        break;
   case 1:
        Result = "One";
        break;
   case 10:
        Result = "Ten";
        break;
   case 100:
        Result = "Hundred";
        break;
   case 1000:
        Result = "Thouzand";
        break;
   default:
        Result = "Any Other Number";
}
```

**Comment by HaloFour** [comment]
Close, it's:

```cs
var result = i switch { 
    0 => "Zero",
    1 => "One",
    10 => "Ten",
    100 => "Hundred",
    1000 => "Thouzand",
    _ => "Any Other Number"
};
```

[SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwg4A2APgAIAMABCwIwDcAsACgWAZi4AmDgGEOAbyEdFXMT04BZABQ4KMDjgCUcoXigIOSZHAa6AvHo7IA7jhgYAFnI4KlnGwD4OACIALXIAe0Dqb0VuDn8ggHkKCEjojm5fAMCAFQgKVMEldLZMoIAJOAoAEyQqgqKMkris7LcwuAAvKGr6pQB9ZqCAQQoATw4EmDdyDgA5OABbYHJAoQBfAUKipRYAdnMUKxhNorX1oA===)

[Relevant Conversation](https://github.com/dotnet/csharplang/issues/1054#issuecomment-340559138)

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
Dropping "case" is nice, but I find "i switch" strange. So, I prefere:
Close, it's:

var result = switch(i) { 
    0 => "Zero",
    1 => "One",
    10 => "Ten",
    100 => "Hundred",
    1000 => "Thouzand",
    _ => "Any Other Number"
};

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
I see. You want use switch like the ? symbol.. So, why we don't use ? directrly?
```
var result = i? { 
    0 => "Zero",
    1 => "One",
    10 => "Ten",
    100 => "Hundred",
    1000 => "Thouzand",
    _ => "Any Other Number"
};
```

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

You can see from the conversations that I've linked that the team explored many permutations of the syntax.  The syntax that I demonstrated above is what they currently have prototyped in the pattern matching branch.  I'm not saying that it's set in stone, but the team is probably not doing to jump back into the syntax argument without a really good reason.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
What about a general expression form not only ternery swich?
In VB.NET I suggested to add lampda expression evaluator, something like this:
```
var number = int.parse(Console.ReadLine());
var result = (int i := number) =>
{
    return i switch { 
        0 => "Zero",
        1 => "One",
        10 => "Ten",
        100 => "Hundred",
        1000 => "Thouzand",
        _ => "Any Other Number"
    };
}
```
This is a lampda expression that is defined and called with number passed as an argument to th i param.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

I don't know what you're talking about.  The proposal I linked to is a general "expression" form of `switch` and can be used anywhere that an expression can be used, including within a lambda:

```cs
Func<int, string> f = i => i switch { 
    0 => "Zero",
    1 => "One",
    10 => "Ten",
    100 => "Hundred",
    1000 => "Thousand",
    _ => "Any Other Number"
};
```

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
I'm talking about general expression evaluation not only pattern matching. For examole:
In VB.NET I suggested to add lampda expression evaluator, something like this:
var number = int.parse(Console.ReadLine());
var result = (int i := number) =>
{
    if (i==0)
        return "Zero";
    if (i==1)
        return"One";
    // .......    
    return "Any Other Number"
    };
}
The idea is to write a lambda and call it in one place. Today we must cast the lamda to a Func delegate then add the argument after the end of the lamda, which is not nicely readable:
```
var result = ((Func<int, string>)((int i) =>
{
    if (i==0)
        return "Zero";
    if (i==1)
        return"One";
    // .......    
    return "Any Other Number"
    }))(number);
}
```

**Comment by MohammadHamdyGhanem** [comment]
it will also be nice if you allow to use => as a return keyword:
```
var result = (int i := number) =>
{
    if (i==0) => "Zero";
    if (i==1) => "One";
    // .......    
    return "Any Other Number"
    };
}
```

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

Such things would be entirely orthogonal to `switch` expressions.
