### ISSUE TITLE
[Proposal] Add keyword "not" for "is"

### ISSUE THREAD

**Issue by Dergard** [dotnet/csharplang#1850]
now:
```
...
if(!(someObject is SomeClasss someClassObject)) return;
//work with someClassObject
...
```

how want to work
```
...
if(someObject not is SomeClass someClassObject) return;
//work with someClassObject
...
```

**Comment by ufcpp** [comment]
[Negated-condition if statement](https://github.com/dotnet/csharplang/issues/882)
[not patterns](https://github.com/dotnet/csharplang/issues/1350)

**Comment by calielc** [comment]
I really like idea of ``if (foo is not Foo)`` and ``if (foo is not null)``

**Comment by DavidArno** [comment]
Would you mind closing this, please, as it's a duplicate?

**Comment by willard720** [comment]
I get that you're trying to keep it the same with how `!` works now (`if (!isActive)` reads as "if not is Active") but that can't be helped. This can. Why not just `if (someObject is not Foo)` and keep it much more readable, more inituitive and less confusing?

**Comment by ufcpp** [comment]
> 'if (someObject is not Foo)'

again, dup of https://github.com/dotnet/csharplang/issues/1350

**Comment by alrz** [comment]
Note that a pattern of the form `Foo` is normally resolved as a constant. while `is Foo` deliberately works (to retain backward-compatibility with prior versions of the language), you will need an underscore for a negated type check, e.g. `is not Foo _`

**Comment by jnm2** [comment]
> `is not Foo _`

I'm not liking this.

```c#
if (x is Foo && y is not Foo _)
```
