### ISSUE TITLE
Proposal: Add a way to extend existing classes

### ISSUE THREAD

**Issue by Reelix** [dotnet/csharplang#1852]
Say you have basic logging in your program, and in certain cases you want to write a console line as well. In this case, you have three viable options:

1.) Hook into the console, and log everything written to it
2.)
Console.WriteLine("Text Here");
Logger.Log("Text Here");

3.)
SomeFunc("Text Here");

void SomeFunc(string text)
{
Console.WriteLine(text);
Logger.Log(text);
}
- - - - - -
I propose a way to be able to extend the base classes, and in doing so allow the developer to add additional functionality without the need to add new classes, so you can eventually add a new class to your project, and go like:

Console.LogLine("Text Here");

This could possibly be done by creating a class of a new class type "extension" that requires an existing class type as a name, and in doing so allows you to add new methods onto those classes.

**Comment by HaloFour** [comment]
I believe this would fall under the discussion here: https://github.com/dotnet/csharplang/issues/164

**Comment by benaadams** [comment]
Extension Methods? https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods

**Comment by willard720** [comment]
C# 8 will have Extension Everything, where you can do extension static methods.
