### ISSUE TITLE
Proposal: a way of defining a class that is only derivable within an assembly

### ISSUE THREAD

**Issue by dsaf** [dotnet/csharplang#1854]
This would allow creating sealed hierarchies which is often useful for reusable libraries with a defined scope. In some cases it's beneficial to _not_ give the library user a false impression that a class is _meant_ to be inheritable because it _had_ to be made inheritable.

I am not too bothered about exhaustive type pattern matching on top of this. But if it's possible and does not require putting all classes in the same file and/or removing (polymorphic) behaviour than that's OK too. This is not about case/data/record classes, this is about normal OOP classes.

Example based on suggested ```public internal sealed``` phrase (to avoid new keywords):

```csharp
//First.dll
public internal sealed class SomeComponentBase
{
    public virtual void SomeBehaviour() {}
}

public sealed class OtherComponent : SomeComponentBase
{
    public override void SomeBehaviour() {}
}
```

```csharp
//Second.dll
#error Error CS9999 'YetAnotherComponent': cannot derive from externally sealed type 'SomeComponentBase'...
public sealed class YetAnotherComponent : SomeComponentBase
{
    public override void SomeBehaviour() {}
}
```

PS: introducing namespace scope in addition to assembly scope could be quite interesting too. Though this would not be limited to just this case.

**Comment by theunrepentantgeek** [comment]
Are you aware of the [**private protected**](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private-protected) visibility modifier? 

Declaring a constructor with **private protected** visibility gives a class that can only be inherited within the same assembly. Make all the leaf classed **sealed** and you have your sealed hierarchy.

Here's an example from a series on my blog:

``` csharp
public abstract class ValidationResult
{
    private protected ValidationResult()
    {
    }
}
```

Unless, I've misunderstood the intent of your proposal?

**Comment by dsaf** [comment]
I raised this proposal after having had just applied ```private protected``` and feeling that that is not enough. You made that class abstract and uninstantiable in it's own right. This is not always preferable.

**Comment by HaloFour** [comment]
You can use `internal` on the constructor and provide a `public static` factory method to instantiate the class publicly.

There's nothing that C# can do to implement a feature like this.  Without CLR support it would be exceptionally easy to avoid this limitation by using a downlevel version of the compiler, or any other language.

**Comment by bondsbw** [comment]
This proposal is a duplicate of #485, where it uses the `closed` keyword.

One interesting feature of `closed`:  you are not required to seal its subtypes.  This means that you can enforce that all derived types derive through one of the blessed subtypes you provide.

**Comment by dsaf** [comment]
@bondsbw fair enough.
