### ISSUE TITLE
Allow contravariance for C# out variables

### ISSUE THREAD

**Issue by TChristoph** [dotnet/csharplang#1855]
**Version Used**: 2.9.0.63208 (958f2354)

**Steps to Reproduce**:

Compile the following code:

```
class T { }
class U : T { }

class Programm
{
	U GetU() => new U();
	T GetT() => GetU();
	
	void TryGetU(out U u) => u = new U();
	void TryGetT(out T t) => TryGetU(out t);
}
```

**Expected Behavior**:

The code will compile.
`GetT()` will return an instance of `U`.
`TryGetT(out var t)` will assign an instance of `U` to `t`.

**Actual Behavior**:

The code does not compile:

> ```(14,39): error CS1503: Argument "1": Cannot convert from "out T" in "out U".```

As normal (`in`) parameters behave kind of covariantly - given a method signature `void x(T t)`, it would legal to call it with an instance of U, for example `x(new U());` -, it would be only logical in my understanding that `out` parameters should behave kind of contravariantly. In this example, given a method signature `void y(out U u)`, it should be also legal to invoke it on the following way:
```
T t;
y(out t);
```
As the first example above shows, from a semantic point of view, an out parameter does not differ from a return value. Since return values can be used in a contravariant context (we could do an implicit cast from a value of type `U` to `T`), I think the same should be possible for `out` arguments.

I cannot find or imagine any explanation why C# does not support this.

Respecting `ref` arguments, they should be kept invariant, as they allow assignments from both sides - caller and callee.

I am looking forward to your opinions and assessments.

**Comment by yaakov-h** [comment]
This appears to be a duplicate of #1760.

**Comment by TChristoph** [comment]
Yes, you're right.
