### ISSUE TITLE
[Proposal] Multiple catch with same handler

### ISSUE THREAD

**Issue by lukasportal** [dotnet/csharplang#1858]
Handle multiple exception blocks without having to write additional methods or ugly if(x is XException) to insert in the catch{} blocks when they are the same for different exception types
Today:
```
try
{
    DoSomething();
}
catch (FooException f)
{
   // can be ignored/ok
   Log();
   DoSomethingElse();
}
catch (BarException b)
{
   // can be ignored/ok
   Log();
   DoSomethingElse();
}
catch (Exception e)
{
    LogFatal();
}
```

A way to make it better today is by:
```
try
{
    DoSomething();
}
catch (Exception e)
{
    if (e is FooException || e is BarException)
    {
         // can be ignored/ok
         Log();
    }
    else
    {
        LogFatal();
    }
}
```

The proposal way to re-write that would be, sort of like nested using() statements:
```
try
{
    DoSomething();
}
catch (FooException f)
catch (BarException b)
{
    // can be ignored/ok
    DoSomethingElse();
}
catch (Exception e)
{
    LogFatal();
}
```

**Comment by DavidArno** [comment]
This is already possible with pattern matching on the catch:
```cs
try
{
    DoSomething();
}
catch (Exception e) when (e is FooException || e is BarException)
{
    // can be ignored/ok
    DoSomethingElse();
}
catch (Exception)
{
    LogFatal();
}
```

I'm not sure what benefit your proposal would add to this.

**Comment by lukasportal** [comment]
Sorry about that then, pattern matching looks already pretty enough
Thanks!

**Comment by jnm2** [comment]
I don't think there's any pattern matching going on there. That is a C# 6 exception filter with C# 1 type checks. :D

**Comment by YairHalberstadt** [comment]
I still think this is a valid request.

```csharp
catch (FooException f)
catch (BarException b)
```

feels like it should work, and looks much nicer than 
```csharp
catch (Exception e) when (e is FooException || e is BarException)
```

**Comment by yaakov-h** [comment]
@YairHalberstadt wouldn't you basically need #399 so that you could access members of the exception object then?

**Comment by YairHalberstadt** [comment]
@yaakov-h

I think having it just be of type Exception would be fine., but that is a valid point.

**Comment by HaloFour** [comment]
I prefer the Java approach:

```cs
try {
    // foo
}
catch (SomeException | SomeOtherException exception) {
    // can use properties of the common ancestor of the exception here
}
```

But I think that the addition of union types would make such a feature more powerful.

**Comment by DavidArno** [comment]
Maybe the or pattern will help here:
```cs
try
{
    DoSomething();
}
catch (Exception e) when (e is FooException or BarException)
{
    DoSomethingElse();
}
```

**Comment by YairHalberstadt** [comment]
@davidArno

A catch already looks a bit like a pattern match, so why not move it inside:

```csharp
catch(FooException or BarException e)
```
```

**Comment by DavidArno** [comment]
Yes, I like that.
