### ISSUE TITLE
Discussion: Should generic constraints be used to allow casting a contravariant/covariant Generic Type

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#1864]
Consider the following code
```
    public class Class<TBase, TDerived> where TDerived : TBase
    {
        public Class(TDerived derived, Func<TDerived> derivedFunc, Action<TBase> baseAction)
        {
            Base = derived; //compiles
            BaseFunc = derivedFunc; //does not compile
            derivedAction = baseAction; //does not compile
        }

        TBase Base { get; }
        Func<TBase> BaseFunc { get; }
        Action<TDerived> derivedAction { get; }
    }
```
Should we allow this code to compile, i.e. use the generic constraints to allow casting of covariant and contravariant generics?

#### Advantages

It makes sense, and may well be useful in some use cases.

#### Disadvantages

A lot of effort for something which is as far as I can think of so far is at most a minor inconvenience

**Comment by CyrusNajmabadi** [comment]
You can do this with the 'class' constraint.  Specifically:

```c#
where TDerived : class, TBase
```

This doesn't work without that constraint for the same reason you can't assign a `Func<int>` to a `Func<object>` (even though `int` derives from `object`).
