### ISSUE TITLE
Can I use `Activator.CreateInstance` if constructor have `ref` parameter?

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/csharplang#1876]
Can I use `Activator.CreateInstance` if constructor have `ref` parameter?
As I know I can not pass reference inside `args` array.

**Comment by AlexRadch** [comment]
@svick I think it works only inside `args` array. See example https://dotnetfiddle.net/BJ9Wzm

**Comment by zippec** [comment]
@AlexRadch Your example proves it works as expected and the question is not relevant to C# language. Can you please close this issue?

**Comment by AlexRadch** [comment]
@zippec It works as useless. What about to add normal support for `ref` in c#?

**Comment by HaloFour** [comment]
@AlexRadch 

> It works as useless. What about to add normal support for `ref` in c#?

It works as expected.  The array of arguments is updated.  The issue you have is with `params` where each argument is silently copied into an array.  If the array is updated those values are not copied back.  There's nothing to change here.  You can't have an array of `ref`, so you can't pass `ref` to the locals directly.  The workaround is to skip the `params` voodoo and create/manage the array manually.

**Comment by AlexRadch** [comment]
>  The issue you have is with `params` where each argument is silently copied into an array.

Yes! We can not put `ref` into object so we can not work with `ref` parameters. I think that suck support can be added.
