### ISSUE TITLE
Writing C# multi-line string literal to a file in Linux writes with CRLF

### ISSUE THREAD

**Issue by kichalla** [dotnet/csharplang#1877]
I originally asked this question here: https://stackoverflow.com/questions/52450720/writing-c-sharp-multi-line-string-literal-to-a-file-and-crlf-line-ending

I was trying to write out a multi-line C# string literal to a file and noticed that the line endings of the string literal is always CRLF.

To give more context: I am using .NET Core 2.1 and I am building and running this sample app in **Linux**.

Is this expected? I was hoping that the line endings would actually be LF and not CRLF.

**Repro code:**
```c#
       class Program
        {
            const string script =
            @"#!/bin/bash
    echo Hello
    echo Hi
    echo Hey
    ";
    
            static void Main(string[] args)
            {
                string text;
                if (args.Length > 0)
                {
                    // This gets written as CRLF
                    text = script;
                }
                else
                {
                    // This gets written as LF(probably because StringBuilder figures
                    // in which OS its running and does the right thing)
                    var sb = new StringBuilder();
                    sb.AppendLine("#!/bin/bash");
                    sb.AppendLine("echo Hello");
                    sb.AppendLine("echo Hi");
                    sb.AppendLine("echo Hey");
                    text = sb.ToString();
                }
    
                var path = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid().ToString("N")}.sh");
                File.WriteAllText(path, text);
                Console.WriteLine($"Text written to {path}");
            }
        }
```

**Comment by CyrusNajmabadi** [comment]
Dumb question.  In your *actual* file (which might be good to upload somewhere).  Are there LFs, or CRLFs in teh string literal?  i.e. if i were to open your file and look at the raw bytes of it, what would i see?

**Comment by kichalla** [comment]
@CyrusNajmabadi The file has CRLF line endings. More details below:

I am using a Docker container based on `microsoft/dotnet:2.1-sdk` image and using a a command `sed -n l` to check the line endings within the container itself (I have also tried copying the file from the container to my windows machine and opened the file in VSCode and found LF endings):

```
C:\> docker run -v C:\Users\kichalla\source\repos\MultilineExample\MultilineExample:/app -it microsoft/dotnet:2.1-sdk /bin/bash
root@5484667c0ea8:/# dotnet build /app
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /app/MultilineExample.csproj...
  Generating MSBuild file /app/obj/MultilineExample.csproj.nuget.g.props.
  Generating MSBuild file /app/obj/MultilineExample.csproj.nuget.g.targets.
  Restore completed in 174.57 ms for /app/MultilineExample.csproj.
  MultilineExample -> /app/bin/Debug/netcoreapp2.1/MultilineExample.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.91
root@5484667c0ea8:/# dotnet /app/bin/Debug/netcoreapp2.1/MultilineExample.dll usemultiline
Text written to /tmp/65b0a37ab1bb41abaa8c3fe3702cb944.sh
root@5484667c0ea8:/# chmod +x /tmp/65b0a37ab1bb41abaa8c3fe3702cb944.sh
root@5484667c0ea8:/# /tmp/65b0a37ab1bb41abaa8c3fe3702cb944.sh
bash: /tmp/65b0a37ab1bb41abaa8c3fe3702cb944.sh: /bin/bash^M: bad interpreter: No such file or directory <--------------------------------- error

root@5484667c0ea8:/# sed -n l /tmp/65b0a37ab1bb41abaa8c3fe3702cb944.sh
#!/bin/bash\r$ <----------------------- CRLF
echo Hello\r$ <----------------------- CRLF
echo Hi\r$
echo Hey\r$


<!----------------------------- Using StringBuilder's AppendLine ------------------------------->
root@5484667c0ea8:/# dotnet /app/bin/Debug/netcoreapp2.1/MultilineExample.dll
Text written to /tmp/8e2857cf81bd4f08a72dae46c2dd2d2e.sh
root@5484667c0ea8:/# chmod +x /tmp/8e2857cf81bd4f08a72dae46c2dd2d2e.sh
root@5484667c0ea8:/# /tmp/8e2857cf81bd4f08a72dae46c2dd2d2e.sh
Foo
Bar
root@5484667c0ea8:/# sed -n l /tmp/8e2857cf81bd4f08a72dae46c2dd2d2e.sh
#!/bin/bash$
echo Foo$
echo Bar$
root@5484667c0ea8:/#
```

**Comment by CyrusNajmabadi** [comment]
If the file contains crlfs... then this seems to be behaving correctly and as expected.  

You had a string with crlfs and you wrote that text to a file, using a utility that doesn't touch that sort of thing.  So the behavior is exactly as expected.  If you want arbitrary text to be written in a file in an interpreted fashion (i.e. so that line-endings are reinterpretted for the current platform you're on), then you'd need to either write such a write-file function that does that for you.  Or you'd need to use some existing function that does that for you (i'm unfamiliar with any off the top of my head, but they most likely exist somewhere).

**Comment by CyrusNajmabadi** [comment]
Here's an SO post that might be useful to you: https://stackoverflow.com/questions/7841761/writing-unix-style-text-file-in-c-sharp

**Comment by CyrusNajmabadi** [comment]
Note: it looks like the compiler and language are working exactly as expected and spec'ed.  I think this issue can be closed.

**Comment by kichalla** [comment]
Thanks a lot! @CyrusNajmabadi Thanks for the link too.

**Comment by CyrusNajmabadi** [comment]
Glad to help :)   Feel free to close out.

**Comment by kichalla** [comment]
Just FYI...seems like the approach mentioned in  https://stackoverflow.com/questions/7841761/writing-unix-style-text-file-in-c-sharp doesn't work in case of a multi-line string literal(their CRLF is still maintained)...so I think I will just use `Replace("\r\n", "\n")` on the string literal
