### ISSUE TITLE
Property Block

### ISSUE THREAD

**Issue by ArghamSystem** [dotnet/csharplang#1880]
it would be really cleaner, nicer and faster to code if it was possible to create properties this way:
```
            public string prop
            {
                get
                {
                    return value;
                }
                set
                {
                    currentValue = value;
                }
            }
```
there would not be any need for creating another property or field to hold the value, like this:

```
            public string _myValue { get; set; } 
            public string prop
            {
                get
                {
                    return _myValue;
                }
                set
                {
                    _myValue = value;
                }
            }
```

**Comment by svick** [comment]
A similar idea has already been proposed several times, here is one example: https://github.com/dotnet/csharplang/issues/140.

**Comment by Unknown6656** [comment]
Oh boy - here we go again with the duplicates:

## See https://github.com/dotnet/csharplang/issues/1497#issuecomment-386837762
And ...
#1712
#1643
#1497
#1420
#1336 
#1290 
#1240
(#1059)
#626
#318
#140
#133
_[and there are probably even more]_

**Comment by ArghamSystem** [comment]
I'm sorry, i will close it now.
is there a reason that it has not been done yet ? it seems possible.

**Comment by Unknown6656** [comment]
@ArghamSystem : I am not sure, why this hasn't been championed for a C#8-feature, considering that many people really want it ..... The LDT must have their reasons...

**Comment by Unknown6656** [comment]
@MadsTorgersen Sorry to bother you, but do you know, why the LDT has not considered "property-only scoped fields"?
Many people have asked for it in the past, but AFAIK the LDT hasn't addressed that topic...

**Comment by Neme12** [comment]
I think it comes down to: nobody has championed this.

**Comment by Unknown6656** [comment]
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
