### ISSUE TITLE
Extending the "named elements" feature of tuples to other types

### ISSUE THREAD

**Issue by Richiban** [dotnet/csharplang#1883]
Tuples have this cool feature where the elements of the tuple (Item1, Item2 etc) can be named at compile time without having to declare a new type. These names are implemented via metadata attributes that appear on methods that accept / return tuple types, something like this:

```csharp
public (T1 value1, T2 value2) M();
```

which compiles to:

```csharp
[return: TupleElementNamesAttribute("value1", "value2")]
public ValueTuple<T1, T2> M();
```

Can we generalise this feature a bit more so that, at the point of instantiation, we can give more locally meaningful names to parameters, properties etc that might otherwise have completely generic labels?

Imagine that we have a dictionary that is enumerable as a sequence of tuples (instead of the current KeyValuePair<,>):

```csharp

public class MyDictionary<TKey, TValue>
{
	// ...

	public IEnumerator<(TKey, TValue)> GetEnumerator()
	{
		// ... 
	}

	// ...
}

```

I'd like to be able to instantiate it like this:

```csharp
var myDictionary = new MyDictionary<string english, string french>();
```

Then, when you enumerate it, you get a tuple with the names that were provided in the instantiation:

```csharp

foreach(var kv in myDictionary)
{
	Console.WriteLine($"{kv.english} => {kv.french}");
}

```

It would also be extremely useful for higher order functions, where `Func<int, int, int>` appears to have the signature `int arg1, int arg2`. This leads to one of the few occasions where Intellisense can't help you figure out how to use a method: e.g. the `Select` overload on `IEnumerable<T>`: `Select<T, R>(Func<T, int, R>)`. If, in this example, `T` is also `int` then I _always_ have to look up the docs to figure out which argument to the function is the element itself and which is the index. If the method signature could be written as:

```csharp
public IEnumerable<T> Select<T, R>(Func<T element, int index, R result> selector)
{
	// ...
}
```

then all ambiguity is removed.

In terms of implementation, I see no reason why this couldn't also be implemented through the use of attributes, although I must admit that my understanding of the underlying implementation if Tuples isn't very deep.

Thoughts welcome -- this is a relatively quickly thought-through feature.

**Comment by jnm2** [comment]
The same has been asked for Func and Action, and I would certainly like it for my custom types like OneOf.

**Comment by HaloFour** [comment]
The issue I have with a feature like this is how awkward it would apply to most types.  With `ValueTuple<...>` and `Func<...>` you get a guarantee that each generic type parameter lines up with exactly a single argument or field.  But that's an exception and not a rule.  In the majority of cases a feature like this either wouldn't work at all or would result in really confusing behavior.

**Comment by svick** [comment]
> The same has been asked for Func and Action

That's https://github.com/dotnet/csharplang/issues/269.

**Comment by TheUnlocked** [comment]
@HaloFour One would expect that you could only do this for generics that have been specified with an attribute (or something similar). Like in most cases, if something doesn't make sense in a particular context, it shouldn't be used in that context.
