### ISSUE TITLE
[Proposal] Cache locally defined data for cleaner scope

### ISSUE THREAD

**Issue by ukwd** [dotnet/csharplang#1884]
So one thing that i have found particularly with a class that has a lot of reusable collections is that to avoid allocations i need to re-use the same list, but then for that to work i have to set them at the top of the class when their scope doesn't need to be that high up.

So an example would be where you need to replace all data:

```
//collections are set at the top of the class
List<Vector3> _vertices;
List<Vector2> _uvs;
List<int> _tris;
///////////////////////////////
//Some method in the class
//////////////////////////////
public void UpdateMeshData(Data data){
     _vertices.Clear();  
     _uvs.Clear();
     _tris.Clear();  

    // now proceed to add vertices, tris and uvs
    // push the results to the mesh
    Mesh.AddData(_vertices,_uvs,_tris);
}
```

But my issue with this is the scope is technically wrong. If this method only ever uses these collections then the scope should be in the method. But doing that means you have create a new list every time you call the method and thus you now allocate when the capacity grows.

So if there was a keyword like **cache** this means you can write the scope in the function, but the compiler will treat it as a class level scope, but at development level its inaccessible.

Example:
```
// no longer have our collections declared at the top since thats not where they belong anyway
///////////////////////////////
//Some method in the class
//////////////////////////////
public void UpdateMeshData(Data data){
      
     // the first call of this method creates the collections else it will clear them
     cache
     {
       List<Vector3> _vertices = new List<Vector3>();   
       List<Vector2> _uvs = new List<Vector2>();
       List<int> _tris = new List<int>();
     } 
     else  // if cache has already occurred we don't create we just clear the lists
     {
      _vertices.Clear();
      _uvs.Clear();
      _tris.Clear();  
     }
    // now proceed to add vertices, tris and uvs
    // push the results to the mesh
    Mesh.AddData(_vertices,_uvs,_tris);
}
```

Now the collections are in the correct scope and inaccessible to any other method in this class.

**Comment by CyrusNajmabadi** [comment]
You can use `Lazy<T>` for this purpose.

**Comment by theunrepentantgeek** [comment]
This _could_ be done within a method with something like #832, which proposes a **static** modifier for local variables that would make them persistent between invocations of the method. It would look something like this:

```
public void UpdateMeshData(Data data)
{
    // These would be created once and kept for the lifetime of the class
    static List<Vector3> _vertices = new List<Vector3>();   
    static List<Vector2> _uvs = new List<Vector2>();
    static List<int> _tris = new List<int>();

    // Always clear
    _vertices.Clear();
    _uvs.Clear();
    _tris.Clear();  

    // now proceed to add vertices, tris and uvs
    // push the results to the mesh
    Mesh.AddData(_vertices,_uvs,_tris);
}
````

FWIW, I'd favor more general proposals like #832 that add widely useful features over very narrowly scoped proposals like this one.

**Comment by svick** [comment]
Why do you have to declare the fields at the top of the class instead of just before the method? Is this one of the "I'm asking for a language change, because I can't change my company's code style" proposals?

**Comment by DanFTRX** [comment]
@svick I read it as more of a problem with class scope vs local scope than where in the file it is declared.  But I could be mistaken.

**Comment by gafter** [comment]
Closing as a dup of #832
