### ISSUE TITLE
How is SourceGenerator going？

### ISSUE THREAD

**Issue by forestbat** [dotnet/csharplang#1899]
https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/docs/features/generators.md
I think it's one of the most important feature in C# and roslyn，but since it was announced 2 years passed，seems that no proceed。

**Comment by yaakov-h** [comment]
See the bottom of #107

**Comment by forestbat** [comment]
> 
> 
> See the bottom of #107
It's a bit long and trouble……are there any newest information，such as when or which version of .NET the feature will be realized？

**Comment by yaakov-h** [comment]
Nope. It's currently earmarked for some future major version after C# 8.0. It could be C# 9.0, 10.0, never...

**Comment by jnm2** [comment]
Basically, it's super hard to figure out the whole IDE story and the scenario is not as motivating as other things the teams are doing.
