### ISSUE TITLE
Spec is missing script syntax

### ISSUE THREAD

**Issue by aelij** [dotnet/csharplang#19]
Reference directives, load directives and other differences from the regular syntax (e.g. interleaved type definitions, usings, extension methods, and the generated entry point).

**Comment by gafter** [comment]
This is not intended to be a spec for the scripting variant of C#.

**Comment by svick** [comment]
@gafter Are there plans to specify that somewhere else? If not, shouldn't there be some plans to specify it in some way?

**Comment by gafter** [comment]
That's a great question. If you can find no spec, please file an issue on the Roslyn repo.
