### ISSUE TITLE
Wiki: Nullable Reference Types Preview link to SharpLab should opt-in

### ISSUE THREAD

**Issue by svick** [dotnet/csharplang#1900]
[The *Nullable Reference Types Preview* article on wiki](https://github.com/dotnet/csharplang/wiki/Nullable-Reference-Types-Preview) includes [link to SharpLab with the branch where NRT are being developed pre-selected](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGhhAEssmATEAagB8AAgAYABIICMAbgCwAKEEBmcQCZRAYVEBveaL3jlggCyiAsgAoAlNt367tvQF95joA=).

But, the code in the link does not include the opt-in attribute, so if I just start writing code that uses NRT, I will not get the results I expect.

I think the link should be changed to one that includes the opt-in attribute, e.g.: https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGhhAEssmATEAagB8AAgAYABIICMAbgCwAKHkBtALYB7LtgghxEgHSE4ZGG2URdAYVXL6HCAgDKdgG5sqyXelVlMOOo2QAuvLyggBMouaiAN7yonHiACyiALIAFACU0bHxOdlxAL7y+UA==.

**Comment by YairHalberstadt** [comment]
Closing as Nullable reference types has been released, and so the wiki page is outdated and should be deleted anyway
