### ISSUE TITLE
Failed pattern match makes variable become nullable

### ISSUE THREAD

**Issue by Suchiman** [dotnet/csharplang#1904]
**Version**: 15.8.6 using latest 09/11/18 nullable reference types preview

In the following code, the presence of the `if (ex is ArgumentException)` will make `ex` become analyzed as nullable in the else branch
```csharp
try
{
    throw new InvalidOperationException();
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString()); // ok

    if (ex is ArgumentException)
    {
        throw;
    }

    Console.WriteLine(ex.ToString()); // null dereference reported here
}
```

**Comment by 333fred** [comment]
This issue was moved to dotnet/roslyn#30278

**Comment by 333fred** [comment]
@Suchiman thanks for reporting this issue. I've moved it over to roslyn so we can take a look at it.
