### ISSUE TITLE
System.TimeZoneInfo.ConvertTimeFromUtc bug

### ISSUE THREAD

**Issue by justlearntutors** [dotnet/csharplang#1905]
We want to convert time.

Example
**Localhost**
DateTimeOffset TimeZoneInfoConvert = System.TimeZoneInfo.ConvertTimeFromUtc(DateTime.Parse("10/9/2018 8:00:00 AM"), System.TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time"));

Correct result: 10/9/2018 10:00:00 AM +02:00

**Server**
DateTimeOffset TimeZoneInfoConvert = System.TimeZoneInfo.ConvertTimeFromUtc(DateTime.Parse("10/9/2018 8:00:00 AM"), System.TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time"));

Wrong result: 10/9/2018 10:00:00 AM +00:00

**Comment by yaakov-h** [comment]
This repository is only for the C# language and syntax itself.

For the core .NET libraries, see https://github.com/dotnet/corefx.

**Comment by YairHalberstadt** [comment]
I'm closing as this bug needs to be reported on https://github.com/dotnet/runtime/issues.

If this issue is still troubling you, i recommend you open an issue there - you'll probably have to add a bit more information to help them reproduce it though.
