### ISSUE TITLE
Relax compound statement requirement for TRY/CATCH fake braces

### ISSUE THREAD

**Issue by itadapter** [dotnet/csharplang#1914]
The logical C# design of TRY/CATCH is like so:
```
 try <statement> catch <statement> | finally <statement>
having <statement> = a single statement or compound statement with { }
```
for example, this is a perfectly legal code, as expected. Notice no extra "{}" around foreach and process:
```
  using(var res = new Resource())
     foreach(var item in res.Items)
        process(item);
```

HOWEVER language inconsistency is illustrated with this example:
```
  try
  {
      process(item);
  }
  catch(Exception error)
  {
     handle(error);
  }
```
**Why are "fake" braces required after try/catch/finally?** (even for a non-compound statements)

The proper consistent language parser design would have been allowing for a regular statement after try/catch/finally:
```
   try process(item);
   catch(Exception error) handle(error);
```

Yes, it is a matter of style, but there are many cases where one needs something like: `foreach(var it in items) try do(it); catch log(it);`

**Comment by HaloFour** [comment]
@itadapter 

There can be any number of `catch` clauses and there can be zero or one `finally` clause.  Eliminating the braces would make it impossible for the compiler to disambiguate the following:

```cs
try
try DoSomething();
catch (NullReferenceException) HandleNRE();
catch (IllegalArgumentException) HandleIAE();
catch (Exception) HandleException();
finally CleanUp();
```

There would be three perfectly legal ways to interpret that code.

**Comment by itadapter** [comment]
@HaloFour 
I still do not see the problem per definition above. The "catch" and "finally" keywords relate to the last "try" in the parser state machine. In your example, all catches and finally relate to `try DoSomething()` and your first try is without handler -which is a syntax error (per my suggested grammar).
 If someone wants to shoot themselves in the foot with this nesting- they can, so yes, go and use braces for this, however in many cases we have a quick error handler, especially in in-lined code/lambdas, and extra {} just add bloat.

**Comment by CyrusNajmabadi** [comment]
>I still do not see the problem per definition above. The "catch" and "finally" keywords relate to the last "try" in the parser state machine.

The language grammar would be ambiguous here.  Whether or not that is a disqualifying attribute is up to the LDM to decide.  So far, this hasn't been found valuable enough to warrant someone championing it.

**Comment by HaloFour** [comment]
@itadapter 

The braces add no bloat:

```cs
try { process() }
catch (Exception error) { handle(error); }
```

That is perfectly legal.  Your proposal adds a lot of complication and ambiguousness to the language for the sake of avoiding, at most, two characters per clause.

**Comment by HaloFour** [comment]
Or similarly:

```cs
foreach(var it in items) { try { do(it) } catch { log(it); } }
```

**Comment by HaloFour** [comment]
From [Exception Handling for C++](http://www.stroustrup.com/except89.pdf) 16.8 Appendix D: Syntax Details:

> Allowing exception handlers to be attached to blocks only and not to simple statements simplifies syntax analysis (both for humans and computers) where several exceptions are caught and where nested exception handlers are considered (see Appendix E).

> There seems to be no reason to allow these ambiguities even if there is a trivial and systematic way for a parser to chose one interpretation over another.

**Comment by itadapter** [comment]
@HaloFour
Since I have implemented this in different language syntaxes before, including ObjectPascal all I can say that the presence of "edge cases" in language design is a code/design-smell.  C++ uses completely different LALR parser as a language, whereas C# is simple recursive descent. The very idea of extra syntax elements indicates a deviation from mathematical purity. I know developers who like to put braces around every statement, it is a matter of preference, whereas I am talking about language finite state machine design which has a special "IF" just for TRY construct - that alone bares a question - why?

**Comment by CyrusNajmabadi** [comment]
>  The very idea of extra syntax elements indicates a deviation from mathematical purity

Features are not worked on because of a need for mathematical purity.  features need to be championed by an LDM member who thinks there is enough merit to the community and ecosystem to warrant the time and effort involved here.  So far, no LDM member has felt it has risen to that level.

**Comment by HaloFour** [comment]
@itadapter 

I've already stated why: it eliminates ambiguity, both for the compiler and for the human reading the code.  There's no reason to eliminate the requirement for braces for `try` statements.  At best it reduces the total code by a couple of characters at the cost of making the code more difficult to read.  The fact that some other constructs in the language allow for the removal of braces is irrelevant.  Not a single one of those control statements allow for zero-to-many proceeding clauses which is what introduces the ambiguity.  The closest is `if` with the zero-to-one `else` clauses, and it's generally considered a misfeature that the C/C++/C#/Java languages allow you to use anything but a block there.

**Comment by itadapter** [comment]
@HaloFour 
That's fine, and no one expects you to make any changes, however I encourage you to look at other languages (not just C# and C++)  and to listen what someone is trying to tell you without responding with well-known facts. Once again, C# became now a hybrid language very suitable for functional/declarative programming. Requiring braces for try has always been strange as had they not been required they would have worked just fine as they do in other languages like Delphi. Your remarks regarding "{}" not being bloat may have been applied to 1 liner properties which do make sense: `pub int Age => m_Age;`

**Comment by svick** [comment]
@itadapter 

> Your remarks regarding "{}" not being bloat may have been applied to 1 liner properties which do make sense: `pub int Age => m_Age;`

If you ignore whitespace, requiring `{}` is literally just two characters. The difference between:

```c#
public int Age => m_Age;
```

and:

```c#
public int Age { get { return m_Age; } }
```

is much bigger.

It's also quite a lot of noise that you have to mentally parse, which I think is not really an issue for `{}`.

**Comment by CyrusNajmabadi** [comment]
It's also a matter of how common patterns and the major difference in impact on the final code.  For properties, we started in C#1 with a pattern that would take around a dozen of lines for a property, with tons of excess tokens.  The current patterns get down to 1, with minimal token overhead.  This is not an analgous case for try/catch/finallys.  They're still going to be multiline.  They're still going to be statement-oriented.  The improvement is extremely marginal comparatively (you're removing the unhelpful tokens, not the ones with the most impact).

**Comment by itadapter** [comment]
If you look at the language spec in BNF notation all statements look the same, including:  lock, using, if (which is a composite multi-part statement with optional else), for, while... et. al... 

All I am asking is this: why does "try" statement have a special handling? "if" statement has an optional "else", yet we do not require braces which is 100% correct, as ANY statement may be either a singular or a compound one.

The ideology applied in C++ does not make sense either.

It is understood that no one wants to change this in C#, but the philosophical question still stands.  Another interesting consideration is expression-bodied methods, which could have been done as easily as statement-bodied, like so:
```
  void hello1(str name) writeline($"Hello {name}!");
  void hello2(str name) { writeline($"Hello {name}!"); }

  void add(T item) lock(buckets) buckets.add(item);

  void add(T item) try lock(buckets) buckets.add(item); finally notify();

  void add(T item) 
      try lock(buckets)  
        buckets.add(item);
      finally notify();
```
Although it makes language design more streamlined (less if statements in parser + more ways to write code) I would agree that this would turn C# in something like Scala which is being criticized for abuse potential because of its relaxed syntax. However, that syntax actually makes more sense as it is more general and does not have "special edge cases" like the ones for try/catch now.

**Comment by CyrusNajmabadi** [comment]
> All I am asking is this: why does "try" statement have a special handling?

> but the philosophical question still stands.

I've tried to explain it as best as i can.  The language is designed in an ideological manner. The language is designed by people who champion the things they find the most valuable to provide users.  This has never been believed by someone willing to champion that this should be changed.  That's the "why". :)

**Comment by CyrusNajmabadi** [comment]
> It is understood that no one wants to change this in C#

This is one of the core ideas behind how the language is designed.  If no one wants to change something, it doesn't change.  :)

There's really no more to it than that :)  We can discuss the history here.  We can discuss why some people here don't think this is interesting/important enough to fix.  But i'm not sure i can give you any more "why" than that :)

**Comment by HaloFour** [comment]
@itadapter 

> All I am asking is this: why does "try" statement have a special handling? "if" statement has an optional "else", yet we do not require braces which is 100% correct, as ANY statement may be either a singular or a compound one.

Because `try` is inherently more complicated than `if` given it can have any number of `catch` clauses, not just zero or one.  It was also designed much later than `if` after it was realized how much of a bug vector it was for `if` to not require blocks.  Unfortunately C# copied some of the old warts of C.

Removing braces from `try` doesn't make C# more "streamlined".  It makes C# more complicated and more ambiguous.  The *only* way to possibly make it work is to seriously confine the behavior of `try` in the language, such as forbidding nested `try` statements, forbidding multiple `catch` clauses, etc.  There's **zero** reason to put any effort into making the language more complicated just to remove a few curly braces.

**Comment by CyrusNajmabadi** [comment]
> not sure I get your point of frustration here

I'm not frustrated.  :)

**Comment by CyrusNajmabadi** [comment]
> If you find that this is of no value then ignore it and let someone else react. 

You asked questions.  I've been trying to provide information about that question to the best of my ability.  I've worked on C# language design for many years, so i'm trying to give you my own perspective on how i see this :)

> Where should I, as a technologist with 25+years history supporting MSFT products, write those things?

Perhaps a blog?  I think it's totally reasonable to ask questions here.  But it feels like the questions have been answered.  Not sure what can be done at this point :)

> And I do find this to be strange in C# design, only 2 syntaxes are strange: "try" and "break" in switch.

That's fine.  It's unclear to me if there's any additional information you're looking for.  Is there some question that you're still looking for clarity on?

**Comment by jnm2** [comment]
Dupe of https://github.com/dotnet/csharplang/issues/616 and https://github.com/dotnet/csharplang/issues/1015.
