### ISSUE TITLE
Throw functions

### ISSUE THREAD

**Issue by drozdekl** [dotnet/csharplang#1918]
I'd like to propose new type of methods which do not have return type. Instead of the return type there should be keyword `throw` which indicates that the method throws. In short, every definition from the next code block would be possible:
```csharp 
throw funcA() =>
throw new Exception();

throw funcB(string message) =>
throw new ArgumentException(message);

throw funcC() 
{
    Console.WriteLine("Do something here...");
    throw new Exception();
}
```

Why do I think that it could be useful? 

1) Everyone could use these methods in place where throw expression can be written because the compiler knows that the function throws.
```csharp
int a = obj ?? funcC();
```

2) Throw methods could be used even in switch:
```csharp 
switch (a)
{
    default:
        ThrowMethod();
}
```

3) I somethimes use the pattern which I call "ThrowHelper". It's a static class which helps me with managing exceptions. The interface is something like (I simplified it a lot):

```csharp
public interface IFactory
{
    string DefaultMessage { get; }

    RootException New();

    RootException New(string message);
}

public class RootException : Exception
{
    protected RootException(string message) :
        base(message)
    { }

    public struct Factory : IFactory
    {
        public string DefaultMessage =>
            "RootException default message";

        public RootException New() =>
            new RootException(DefaultMessage);

        public RootException New(string message) =>
            new RootException(message);
    }
}

public class DerivedException : RootException
{
    protected DerivedException(string message) :
        base (message)
    { }

    public new struct Factory : IFactory
    {
        public string DefaultMessage =>
            "DerivedException default message";

        public RootException New() =>
            new DerivedException(DefaultMessage);

        public RootException New(string message) =>
            new DerivedException(message);
    }
}

public static class Throw
{
    public static void From<T>()
        where T : struct, IFactory =>
        throw default(T).New();

    public static void From<T>(string message)
        where T : struct, IFactory =>
        throw default(T).New(message);
}
```

With these definitions I am able to write 
```csharp
Throw.From<RootException.Factory>(); // ok
Throw.From<DerivedException.Factory>(); // ok
Throw.From<DerivedException.Factory>("message"); // ok
var a = obj ?? Throw.From<MyException.Factory>(); // Error now. Would be ok
```

Throw class in my applications is much more complex and is doing some additional work like logging. I'd like to be able to use ?? operator and other features I currently can't. I totally understand if the implementation is difficult or the feature is not useful for anyone except me. Anyway, I decided to place it here for discussion. Thank you very much for reading the whole text and sorry for my English which I know that is not very good.

**Comment by HaloFour** [comment]
My preference for helper methods like this is to have them return the exception, which the caller then throws.  That way it already works with all existing language features without additional changes:

```cs
public static class Error {
    public static RootException From<T>()
        where T : struct, IFactory =>
        default(T).New();
}

throw Error.From<DerivedException.Factory>();
var a = obj ?? Error.From<DerivedException.Factory>();
```

**Comment by jnm2** [comment]
> My preference for helper methods like this is to have them return the exception, which the caller then throws. That way it already works with all existing language features without additional changes:

And doesn't spam the top of the call stack.

**Comment by DavidArno** [comment]
Issue #538, *Proposal: never/bottom type*, relates to this. By supporting a bottom type, which is a subtype of all types and has no value, one of the benefits would be providing a means of marking methods that never return, such as those that always `throw`. So, assuming this type were expressed as `Never`, an example of use would be:
```cs
Never AlwaysThrows() => throw new Exception();

bool TrueOrThrows(bool b)
{
    if (b) return true;
    AlwaysThrows();
}
```
Normally, the compiler would complain that not all paths of `TrueOrThrows` return a value. But since it knows that `AlwaysThrows` is a "never function", there would be no compiler error.

**Comment by arekbal** [comment]
@DavidArno
As I agree very much with usefulness of could-throw information as part of some sort of type system, 
 I have big issue with `Never` as that is some name that some programming language for real-time aware systems could use to describe code which 'never'(as in temporal dimension) trully finishes:
```
Never execute()
{
  loop
  {
     // can't, is disallowed to ever stop.
  }
}
```
