### ISSUE TITLE
how cloud be support dynamically template for fixed buffers during compile time?

### ISSUE THREAD

**Issue by sgf** [dotnet/csharplang#1920]
example:
```C#
public struct User 
{
 public fixed char name[30];
}
```
where i hope i can define I want to define a fixed-size string type like fllows:
```C#
public struct FixedString[int maxLen]
{
 public int Length;
 public byte charset;
 public fixed char Data[maxLen];
 public string ToString(){
  return new string(Data, startIndex, length);
 }
}
```
just look at the **[int maxLen]** 
its a dynamically variable-sized structs **(the sizeof(struct[?]) dynamically during compile time)**
then i cound be define some fields of User like:
```C#
public struct User
{
 public FixedString[30] Name;
 public FixedString[50] Address;
}
```
ye,as u see,the FixedString is still could be when Compile has a fixed size.
we can use sizeof(User) and got size:
Size Of User=sizeof(FixedString[30])+sizeof(FixedString[50])=
sizeof(byte)+sizeof(fixed char Data[30])+
sizeof(byte)+sizeof(fixed char Data[50])=(4+1+60)+(4+1+100)=170

now we can get the Length and charset and read data from FixedString,and we dont need search the '\0'.from the  old buffer.

**What are the benefits of doing so:**
We can save the strings of a fixed size structure.
then we can use pointer directly read and write it like:
```C#
ref T Read<T>() where T : unmanaged 
{
 ...//
}
Read<User>();
```
or
```C#
fixed(char* bp=srcbp){
User* ubp=(User*)bp;
User u=*ubp;
//...
}
```
or
```C#
var size=sizeof(User);//output 170
```
or
```C#
ref user=Read<User>();
user.Name.ToString();
user.Address.ToString();
```

**Comment by YairHalberstadt** [comment]
Hi
I'm sorry, but It's very difficult to understand your issue.
Am I right in thinking that English isn't your first language?
If so, please consider asking someone you know with better English to rewrite your Issue.
Thanks

**Comment by CyrusNajmabadi** [comment]
I believe @sgf is asking for dynamically variable-sized structs.  i.e. he wants to allocate the memory for a struct (including a variable length part) all in one span, and then use it accordingly.

**Comment by Unknown6656** [comment]
If I understood the proposal correctly, @sgf does want a kind of integer-generics/templates in C# -- just like in C++.
e.g:
```csharp
public readonly strcut Vector<int D>
{
	private readonly float[] _coefficients = new float[D];

	public int Dimension => D;

	// ....
}

public readonly strcut Matrix<int N, int M>
{
	// ....

	public (int Width, int Height) Dimensions => (N, M);

	public static Matrix<U, W> operator* (Matrix<U, V> m1, Matrix<V, W> m2) => ....;
}
```
Personally, I like integer generic parameters, however I think that we should be very careful on exactly how it is implemented and where the limitations currently reside...

**Comment by sgf** [comment]
@YairHalberstadt yes,right.english is not my first language.im sorry about my english.
 @CyrusNajmabadi @Unknown6656 Their understanding is correct.

**Comment by ygc369** [comment]
@sgf 
这种“编译时”的变长结构体价值不大，不如要求能在“创建时”指定其内部数组长度的结构体。

**Comment by sgf** [comment]
@ygc369
if support this feature.
thats will it is very convenient to make a serialization base fixed size struct.

**Comment by ygc369** [comment]
@sgf 
我说的“创建时”指定长度的结构体才算是真正跟C/C++语言里的变长结构体等价，其大小是在分配内存时指定的，可以是变量，而不是在编译时就能确定的。
比如：
```C
struct dynamic_string
{
    int length;
    char content[0];
};

void main()
{
    int len, i;
    struct dynamic_string *ds;
    scanf("%d", &len);
    ds = (struct dynamic_string *)malloc(sizeof(struct dynamic_string)+sizeof(char)*len);
    ds->length = len;
    for(i=0; i<len; i++) ds->content[i]='#';
    ......
}
```

**Comment by sgf** [comment]
@ygc369
但是你提到的这个 和C#中的string的并无区别 😂。
或者直接 C#里面 丢一个char[] 数组变量也可以啊。
string本身就是动态长度的。char[] 也可以赋值新长度。

我是想解决 因为C++ 没有反射导致的序列化实现复杂的问题。

**Comment by ygc369** [comment]
@sgf 
C#的string只是个特例而已，如果里面的数组不是char[]，而是int[]，不就没办法用string表示了么？况且string是不可变的，很多情况下不能满足需要。C#里的数组（比如char[], int[]等）是一个独立的对象，我想要的是把一个数组“内嵌”到其他对象里（即其他对象里直接保存数组的内容），而不是在其他对象里保存一个指向数组的引用。比如我希望定义如下对象：
```C#
class A
{
    int length;
    int data[?];
};

A a1 = new(10) A(); //data数组的长度是10
A a2 = new(20) A(); //data数组的长度是20
int n = Console.Read();
A a3 = new(n) A(); //data数组的长度是n
```

**Comment by sgf** [comment]
@ygc369

```
 struct A
    {
        public int length;
        public int[] data;
    };
 
  var a = new A();
            a.data = new int[5];
            a.data = new int[10] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 };
            a.length = a.data.Length;

            Console.WriteLine(string.Join(',',a.data));
```
I have absolutely no idea what your intentions are. What you want, the above test program can be run. I don't know what the difference is with what you want.

我完全无法理解你的意图是什么？你要什么，上述测试程序可以运行。我不清楚和你要的有何区别。
