### ISSUE TITLE
[Proposal] Allow generic structs to match the unmanaged constraint

### ISSUE THREAD

**Issue by SamPruden** [dotnet/csharplang#1923]
```C#
void Foo<T>() where T : unmanaged => throw new NotImplementedException();

// This errors because it doesn't know that (int, int) is unmanaged.
Foo<(int, int)>();
```

I would like the above to work.

I am specifically focused on tuples in my use case, but more generally I would propose that `unmanaged` should be checked _after_ resolving generics. Currently it seems that all generic structs are rejected by `unmanaged`. I propose that a generic struct should only be rejected when, after generic resolution, it has a field of a managed type.

```C#
struct IntWrapper { public int Value; }
struct GenericWrapper<T> { public T Value; }
```

`IntWrapper` can be used with the `unmanaged` constraint.

`GenericWrapper<int>` cannot. I propose that it should be able to be.

**Comment by ufcpp** [comment]
Dup of https://github.com/dotnet/csharplang/issues/1504
[This requires CLR change](https://github.com/dotnet/roslyn/issues/26966#issuecomment-414789680)

**Comment by SamPruden** [comment]
@ufcpp Oops, missed that. Thanks, I'll close this down then. It's a shame that it's blocked, but not very surprising.
