### ISSUE TITLE
Add IEnumerable.SelectMultiple

### ISSUE THREAD

**Issue by OliverHabersetzer** [dotnet/csharplang#1926]
I have a special task where I want to select multiple fields within a List Element:

Given the exemplary class `Range` defined as follows:
```csharp
public class Range
{
    public int Start, End;
}
```

Under usual circumstances you'd have to add these Elements manually like so:

```csharp
List<Range> ranges = new List<Range>();
// Add some elements...
List<int> values = new List<int>();
ranges.ForEach(range =>
{
    values.Add(range.Start);
    values.Add(range.End);
});
```

What I suggest is simplifying this type of calls as follows:

```csharp
List<int> values = ranges.SelectMultiple(
    range => range.Start,
    Range => Range.End
).ToList();
```

This could be enabled by the following extension method:

```csharp
public static class IEnumerableExtensions
{
    public static IEnumerable<TOut> SelectMultiple<TIn, TOut>(this IEnumerable<TIn> inList, params Func<TIn, TOut>[] selectors)
    {
        return inList
            .ToList()
            .SelectMany(inElement => selectors
                .ToList()
                .ConvertAll(selector => selector(inElement)
                )
            );
    }
}
```

**Comment by CyrusNajmabadi** [comment]
This doe not appear to contain a request to change the C# language.  If you'd like to suggest BCL additions, the right place is dotnet/corefx.  Thanks!

**Comment by benaadams** [comment]
That would be: https://github.com/dotnet/corefx 😄

**Comment by jnm2** [comment]
@OliverHabersetzer I've always done `.SelectMany(range => new[] { range.Start, range.End })`. I've actually done it with ranges as well as other things. Wouldn't this existing solution be best both for performance and for consistency/ease of use?

**Comment by OliverHabersetzer** [comment]
> @OliverHabersetzer I've always done `.SelectMany(range => new[] { range.Start, range.End })`. I've actually done it with ranges as well as other things. Wouldn't this existing solution be best both for performance and for consistency/ease of use?

I don't feel like this does the same since you have to explicitly create a new array for every element in the parent `IEnumerable`. I could do some performance testing though.

Thanks ;)

**Comment by OliverHabersetzer** [comment]
> This doe not appear to contain a request to change the C# language. If you'd like to suggest BCL additions, the right place is dotnet/corefx. Thanks!

Oh I didn't know that - thanks for the advise!
