### ISSUE TITLE
Discussion : Name constructor with keyword instead of name

### ISSUE THREAD

**Issue by ebfortin** [dotnet/csharplang#1928]
I find it tedious to repeat the name of a class each time I declare a constructor. IDE helps but still, I see no added value to just repeat the class name. I propose the addition of "ctor" keyword to be used in place of the constructor name. Could also use "dtor" for finalizer.

Even IL understands it. It already use that syntax.

Anyone has an opinion on this?

**Comment by ebfortin** [comment]
Moreso, IL use "ctor" for constructors.

**Comment by jnm2** [comment]
I like this approach the best, and it's currently planned: https://github.com/dotnet/csharplang/issues/100

**Comment by theunrepentantgeek** [comment]
@ebfortin Can you please clarify? Are you talking about use of the type name when _constructing_ an instance, or when _declaring_ the constructor as a part of the definition?

I thought it was the later, but the comment from @jnm2 has me questioning whether I read your proposal correctly.

**Comment by CyrusNajmabadi** [comment]
It seems highly unlikely C# would change here.  Having two ways to do something, where the new way provides only a tiny amount of marginal benefit, would likely not be desirable.

**Comment by jnm2** [comment]
@theunrepentantgeek My mistake, they are talking about declaration.

**Comment by ebfortin** [comment]
> @ebfortin Can you please clarify? Are you talking about use of the type name when _constructing_ an instance, or when _declaring_ the constructor as a part of the definition?
> 
> I thought it was the later, but the comment from @jnm2 has me questioning whether I read your proposal correctly.

When declaring.

**Comment by willard720** [comment]
@ebfortin Just type `ctor` then hit tab twice.

**Comment by arekbal** [comment]
Answers here, seem to be very DRY. 
`ctor(), dtor()` ?
> Having two ways to do something, where the new way provides only a tiny amount of marginal benefit, would likely not be desirable.

Same goes with arrow syntax method definitions... but everyone agrees they are much more brief.
Java didn't want to change so Scala got created and then Kotlin. 
C# didn't want to change, so F# happened, C# suddenly started to change positively.
Pony, Rust happened, C# suddenly got interested in issues it didn't care before.
I am not implying it was anybody's thought, just a general wave of programming world changes.
That thing (constructors repeating name of a class) is a low hanging fruit(almost no risk involved) on a  path to a more brief, easier to consume programming language.

**Comment by CyrusNajmabadi** [comment]
> Same goes with arrow syntax method definitions...

That was a case where there wasn't a "tiny amount of marginal benefit".  

> That thing (constructors repeating name of a class) is a low hanging fruit(almost no risk involved) on a path to a more brief, easier to consume programming language.

See: https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/

Or, as Eric Lippert mentioned:

> And (2) just being a good feature is not enough. Features have to be so compelling that they are worth the enormous dollar costs of designing, implementing, testing, documenting and shipping the feature. They have to be worth the cost of complicating the language

> C# didn't want to change

This has never been the case.  

> Pony, Rust, Midori, TypeScript happened, C# suddenly got interested in issues it didn't care about before.

You are mistaking 'haven't been actively working on' with 'not caring'.  The C# LDM is interested in a wide variety of topics, and has been for decades.  But features *cost*.  It is literally zero sum.  If you take time and effort to work on a certain set of features, that time and effort is not available for others.  So what you see developed are the set of things that are felt to provide a great bang/buck ratio for the development ecosystem out there.

**Comment by arekbal** [comment]
It is always something or the other. You can't have all the cake right? 🍰 So it makes sense with silly and expensive features, or great but also very expensive features to lay them in priority queue and wait until they probably die off.
Tell me, what enormous benefit (apart from brevity, which I very much value) syntax arrow definitions rewarded us. _Couple of characters less, doesn't reduce the amount of errors in code, actually increases them, because, from definition you cannot tell if it returns or not. Leads to confusion between lambda function definition and static definition. Just use brackets dude. Don't forget about them._ 🐇
Don't get me started on IQueryable<> vs IEnumerable<>. ^^

**Comment by arekbal** [comment]
_In not so far future..._
Someone asks what was the point of bringing these shortcuts ctor and dtor(or similar), replacing public with pub and namespace-one-line-per-file-declaration instead of brackets:
>Brevity was the reason. in general the existing form added X additional lines, and Y extra tokens. For the types of trivial, but common, code that could use this feature it was a substantive overhead.

**Comment by MV10** [comment]
#1335

**Comment by Korporal** [comment]
> It seems highly unlikely C# would change here. Having two ways to do something, where the new way provides only a tiny amount of marginal benefit, would likely not be desirable.

@CyrusNajmabadi 

Yet you exhibit support for [this ](https://github.com/dotnet/csharplang/issues/2098)which seems suffer from the same drawbacks: Another way of writing a switch that "provides only a tiny amount of marginal benefit" - or am I missing something?

**Comment by CyrusNajmabadi** [comment]
Yes.  As i mentioned in the other issue, the feature has already been championed.  Meaning the cost of it has already been assessed to be less than the gain overall to the language.  It's not the case of:

1. we have switch expressions, now someone wants to come along and add a new feature to it.

It's the case of:

1. we don't have switch expressions.  we're adding them.  what is the right design for them.

--

Here's another way of thinking about it.  Imagine any proposal has a fixed cost of 1000 LDM-bucks.  That's expensive and needs to present a lot of end value to the user for the LDM to pay that much.  Switch expressions are currently at having value of 10k LDM bucks.  So upping that cost to 10,005 to support consistency here is not really that different. 

However, having to go and spend the 1k LDM-bucks just to do a new way of doing constructors is just not there.  Maybe in the future if the LDM is doing a lot of constructor improvements, and the overall benefit is worth it, this could be rolled into that.  But paying so much to get a tiny marginal benefit is non-sensical.

**Comment by Korporal** [comment]
@CyrusNajmabadi 
> Yes. As i mentioned in the other issue, the feature has already been championed. Meaning the cost of it has already been assessed to be less than the gain overall to the language. It's not the case of:
> 

> 1. we have switch expressions, now someone wants to come along and add a new feature to it.
> 
> It's the case of:
> 
> 1. we don't have switch expressions.  we're adding them.  what is the right design for them.
> 
> --
> 
> Here's another way of thinking about it. Imagine any proposal has a fixed cost of 1000 LDM-bucks. That's expensive and needs to present a lot of end value to the user for the LDM to pay that much. Switch expressions are currently at having value of 10k LDM bucks. So upping that cost to 10,005 to support consistency here is not really that different.
> 

Of course I am in no position to even estimate cost so I can't comment on that, perhaps you could explain (if you have the time) the cost estimate for some of the proposals we make including this particular one? That can only help us going forward, to understand the true costs of some of the stuff we suggest here.

> However, having to go and spend the 1k LDM-bucks just to do a new way of doing constructors is just not there. Maybe in the future if the LDM is doing a lot of constructor improvements, and the overall benefit is worth it, this could be rolled into that. But paying so much to get a tiny marginal benefit is non-sensical.

I'm gonna take some convincing to see the utility in the trailing comma support. Your increasing the scope for unintended errors to go undiagnosed. Right now if someone edits code, copies, pastes etc and in error either removes the true end element or inserts something not intended to be the end element they'll get told off by the compiler.

With this change either scenario is regarded as valid and under the above user edit scenarios a potentially true error will go unreported and perhaps out into the production world.

**Comment by CyrusNajmabadi** [comment]
> Of course I am in no position to even estimate cost so I can't comment on that, perhaps you could explain (if you have the time) the cost estimate for some of the proposals we make including this particular one? That can only help us going forward, to understand the true costs of some of the stuff we suggest here.

Every new feature has a high fixed cost (it's like passing a bill).  You have the meetings with everyone involved.  The impls, the testing, the context switching, the doc'ing, the shipping.  It's a huge fixed cost to even get a feature down this path *and* this is honestly close to zero-sum.  If the time is spent on htat, it's not spent on other things that deliver more value.

However, once you've decided to go down this path and you've paid the fixed costs, then changes/tweaks to something in flight is much less costly.  You already hve someone working on the design/grammar/impl/tests/etc. so saying: can you just tweak things to support X is much less costly.  Indeed, it basically just rolls into the normal cost that you've already accepted as being worth it to pay for this feature. 

Of course, if someone comes along and says "please tweak like so" and that tweaking doubles the cost, then it won't be considered the same as a tweak that basically takes 5 min of time.

**Comment by CyrusNajmabadi** [comment]
> I'm gonna take some convincing to see the utility in the trailing comma support. 

The change was approved.  The people who needed to be convinced were convinced :)

> Your increasing the scope for unintended errors to go undiagnosed. 

What unintended errors?

> Right now if someone edits code, copies, pastes etc and in error either removes the true end element or inserts something not intended to be the end element they'll get told off by the compiler.

I don't know what this means.  On hte other hand, we have ample experience that shows that supporting a trailing comma is not actually a problem in practice (i.e. all the other places in the language that allow this), and it makes for a definitely nicer experience across all editors.  It's not uncommon for people to keep needing to add elements to the end of a list that are very similar to the previous element.  Being able to just copy/paste that last element is a routine operation done by many devs across many IDEs/editors across many languages.  This routine op has a roadbump in it today that is just being removed.  Given the experience that shows this doesn't lead to problems, and given the nicer experience  this provides, it's simple to roll this work into the already approved feature which is coming down the pipe.

**Comment by Korporal** [comment]
> > Of course I am in no position to even estimate cost so I can't comment on that, perhaps you could explain (if you have the time) the cost estimate for some of the proposals we make including this particular one? That can only help us going forward, to understand the true costs of some of the stuff we suggest here.
> 
> Every new feature has a high fixed cost (it's like passing a bill). You have the meetings with everyone involved. The impls, the testing, the context switching, the doc'ing, the shipping. It's a huge fixed cost to even get a feature down this path _and_ this is honestly close to zero-sum. If the time is spent on htat, it's not spent on other things that deliver more value.
> 
> However, once you've decided to go down this path and you've paid the fixed costs, then changes/tweaks to something in flight is much less costly. You already hve someone working on the design/grammar/impl/tests/etc. so saying: can you just tweak things to support X is much less costly. Indeed, it basically just rolls into the normal cost that you've already accepted as being worth it to pay for this feature.
> 
> Of course, if someone comes along and says "please tweak like so" and that tweaking doubles the cost, then it won't be considered the same as a tweak that basically takes 5 min of time.

@CyrusNajmabadi 
So out of curiosity how do you express cost and compare costs? in person hours?

**Comment by Korporal** [comment]
I'll confine my remarks about the trailing comma to that thread, I apologize for derailing this one!

**Comment by CyrusNajmabadi** [comment]
> So out of curiosity how do you express cost and compare costs?

Historically, by the LDM members using their expertise and experience to weight/order things.  It's generally a continuous process, with certain points in product cycles being used to reasses/reorder things.

It's the same way i can read a proposal on a suggested IDE feature and generally give a very precise assessment of the cost to do that feature (including what sort of design tweaks could be considered, and how they would vary the bang/buck outcome of the work).  

Because nearly all of the LDM has actually worked with the language for years,and have been involved directly with the both the impl and the end-to-end process to start with a proposal and take it all the way to a released product, it's pretty easy for them to come to consensus here.

Note: not **everything** works out that way.  For example, NRT was something known to simply be o humongous and so impacting across teh language that it was known that the only way to even get a sense of it was to just 'do it'.  For something this large, this would then be a continual process of exploration/impl/assessment to see if the direction things were going, and the results that were being achieved would justify the costs involved.  But most everything else can be assessed apriori without needing this sort of approach.
