### ISSUE TITLE
Implicit array creation

### ISSUE THREAD

**Issue by OliverHabersetzer** [dotnet/csharplang#1929]
HI!

I want to suggest a shorter way to create arrays without writing `new` or the array type.

What you have to do currently is

```csharp
int[] array = new int[] {1, 42, 1337};
```

I think an easier but type-wise still unambiguous version of this could be

```csharp
int[] array = {1, 42, 1337};
```

In the case of a simple LINQ expression like the one below, the type will be infered by checking all types of the array and using the most specific common type of all elements. In case of mixed types, the type chain will use the next best type. In case of types not having the same parent type, it will be evaluated as an object array.

```csharp
var array = {1, 42}; // type: int[]
var array = {1337, "hello"}; // type: object[]
```

This could be especially usefull when selecting many different elements from a single object, as shown in the following example:

```csharp
List<Range> ranges = new List<Range>();
List<int> values = ranges
    .SelectMany(range => {range.Start, range.End})
    .toList();
```

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/1360
https://github.com/dotnet/csharplang/issues/414

**Comment by OliverHabersetzer** [comment]
> #1360
> #414

Sorry didn't find these - Apparrently wrong keywords! Especially Issue #414 is interesting IMO

**Comment by willard720** [comment]
Can't you already just do `new { 3, 4 };`?

**Comment by jnm2** [comment]
@willard720 `new { A, B }` or `new { A = 3, B = 4 }` is how you create an obejct with an anonymous type. `new[] { 3, 4 }` is the current shortest syntax for creating an array.
