### ISSUE TITLE
Proposal: Allow internal interface members

### ISSUE THREAD

**Issue by JeffCyr** [dotnet/csharplang#1930]
# Context
When using interfaces, you may want to allow the implementation of an interface publicly but restrict the usage of some members to the assembly that defined the interface.

See the discussion in this issue about IThreadPoolWorkItem:
https://github.com/dotnet/corefx/issues/32485

```c#
public interface IThreadPoolWorkItem
{
    void Execute();
}
```
The problem is that we want a type to implement `IThreadPoolWorkItem.Execute` (e.g. `System.Threading.Tasks.Task`), but prevent code outside corefx from calling directly the `Execute` method because it would yield undefined behavior.

# Proposal

Allow the `internal` keyword on interface members. Internal members can be implemented but can't be used outside of the assembly where the interface is defined.

```c#
public interface IFoo
{
    internal void Bar();
}

public class Foo : IFoo
{
    // An internal interface member can only be explicitly implemented
    void IFoo.Bar()
    {
    }
}

Foo o = new Foo();

// Only allowed if IFoo is declared in the current assembly
o.Bar();
```

cc @stephentoub

**Comment by alrz** [comment]
DIM includes modifiers on interface members, but I'm not sure if this particular scenario is covered.

**Comment by gafter** [comment]
We are already doing this as part of the default interface implementations feature. See #52

**Comment by JeffCyr** [comment]
@gafter 

Nice. The proposal is not clear on how the scenario above would be supported tough:

[Modifiers in interfaces](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md#modifiers-in-interfaces)
>Open Issue: We need to specify the precise meaning of the access modifiers such as protected and internal, and which declarations do and do not override them (in a derived interface) or implement them (in a class that implements the interface).

With this interface:
```c#
public interface IThreadPoolWorkItem
{
    internal void Execute();
}
```

Is it `internal` from the `IThreadPoolWorkItem`'s assembly perspective or from the assembly of the type that is going to implement the interface?

If it means internal to the interface's assembly, would this be the appropriate solution?

```c#
public interface IThreadPoolWorkItem
{
    internal void ExecuteInternal()
    {
        Execute();
    }

    protected void Execute();
}
```

**Comment by JeffCyr** [comment]
Also, what is going to happen if a c# 7.X assembly tries to use or implement that interface?

**Comment by willard720** [comment]
@JeffCyr It wouldn't work because it doesn't have access to it, as normal. This isn't breaking old code either, because it's only code with `internal` in front of it.

**Comment by JeffCyr** [comment]
This [design note](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-04-18.md#implementing-inaccessible-interface-members) suggests that this would be a valid solution:

```c#
public interface IThreadPoolWorkItem
{
    internal void ExecuteInternal()
    {
        Execute();
    }

    protected void Execute();
}
```
Still not sure how a c# 7 assembly would interact with that interface

**Comment by JeffCyr** [comment]
Closing the issue since the case seems to be covered by Default Interface Methods
