### ISSUE TITLE
Proposal: Improving IEnumerable Performance

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#1931]
### Motivation

Since `IEnumerable`s are used by both foreach  loops and Linq, their performance is critical for C#.

One concern that the C# team have mentioned concerns them is the shape of the `IEnumerator<T>` interface:

```csharp
public interface IEnumerator<out T>
{
    bool MoveNext();
    T Current { get; }
}
```

The issue is that two interface calls are required per loop iteration. Since interface calls are significantly slower than both instance method calls and virtual method calls (relying as they do on Virtual Stub Dispatch), and cannot be inlined, this can lead to performance issues in tight loops.

See https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-10-03.md where an alternative shape is suggested for `IAsyncEnumerator`.

Whilst the suggested alternative is complicated to implement and consume for  Async Enumerators, it actually works very well for a normal Enumerator, and cuts interface calls by half in all situations:

```csharp
public interface IFastEnumerator<out T>
{
    T TryGetNext(out bool success);
}
```

This could be consumed as follows:

```csharp
while(true)
{
    var value = enumerator.TryMoveNext(out var any);
    if(!any)
         break;
    DoSomething(value);
}
```
The aim of this proposal is to suggest a way to gain from the performance of `IFastEnumerator` without breaking backwards compatibility.

### Proposal

There are a number of steps to this proposal.

1. Add a new interface to BCL `IFastEnumerator`

```csharp
public interface IFastEnumerator<out T> : IEnumerator<T>, IDisposable
{
    T TryGetNext(out bool success);
}
```

Note that this implements `IEnumerator<T>` as well - all three methods must be provided, and must be able to work in tandem. Here is an example implementation for `List<T>`:

```csharp
public struct FastListEnumerator<T> : IFastEnumerator<T>
{
     private readonly List<T> _list;
     ...
     private int _index = -1;
     public T TryGetNext(out bool success)
     {
          success = ++_index == _list.Count;
          return success ? _list[_index] : default (T);
     }

    public bool MoveNext()
    {
          return ++_index  != _list.Count;
     }
     
     public T Current => _index == -1 ? default (T) : _list[_index];
}
```

2. `yield return` now generates an `IFastEnumerator` instead of an `IEnumerator`. Since `IFastEnumerator` implements `IEnumerator`, this does not break backwards compatibility - it just involves adding an extra method.

3. foreach loops should statically check for a `GetEnumerator` method returning a type which has a method `TryMoveNext`. 

If that fails, and the compiler finds a `GetEnumerator` method which returns a type with a `Current` and a `MoveNext` method, then a dynamic check should occur to see if the value returned from `GetEnumerator` implements `IFastEnumerator`.

4. Over time Linq and other places in the BCL which consume an `IEnumerator`manually should be updated to dynamically check for `IFastEnumerator`.

Similarly BCL classes which roll their own Enumerator should be updated to return an `IFastEnumerator`.

5. At some point it may be possible to generate a warning when creating a new `IEnumerator` implementation which doesn't implement `IFastEnumerator`.

### Advantages

Increased performance in a very large percentage of current C# hot paths. Although currently the compiler statically checks the type being used in a `foreach` loop to see if a faster alternative to an ordinary `IEnumerator` is available, in which case this optimisation will not occur (and is not necessary), frequently the type being looped over will only be known at compile time to be an IEnumerable, and so this optimisation will be able to kick in at runtime.

### Disadvantages

Added complexity to the language and compiler.

Dynamic checks may be slower than just using an ordinary Enumerator for small IEnumerables. However I believe this is unlikely, as a dynamic check is very quick, and there are existing examples where the BCL chooses to do this. Consider Linq.Count for example which dynamically checks for `ICollection`.

### Alternatives/Additions

**Use DIM to implement `IEnumerator<T>` for `IFastEnumerator<T>`**

```csharp
public interface IFastEnumerator<out T> : IEnumerator<T>, IDisposable
{
    T TryGetNext(out bool success);

    bool MoveNext()
    {
        var value = TryGetNext(out var any);
        if(any) Current = value;
        return any;
    }

    T Current { get; private set; }
}
```
The advantage to this approach is that only one method has to be defined for `IFastEnumerator`.

However there are a number of issues.

Firstly 3 interface calls are required instead of 2 when consuming an `IFastEnumerator` as an `IEnumerator`.

Secondly, the implementer of TryMoveNext will probably not realise he ought to increment Current, and so it would not be possible to use Current with TryMoveNext, which could cause issues.

Thirdly DIM requires CLR changes, so this will not work with anyone on older runtimes. This is a huge issue, since any existing IEnumerable recompiled with the new C# version will now no longer work on older runtimes, despite no apparent changes to the codebases.

Fourthly as currently planned, DIMs won't allow fields or auto-properties in interfaces, so this may not work.

**IFastEnumerable<T>**

A new interface could be added `IFastEnumerable<T>`:

```csharp
public interface IFastEnumerable<out T> : IEnumerable<T>
{
    IFastEnumerator<T> GetFastEnumerator();
}
```
Then when someone implements `IEnumerable` using yield return, the compiler instead implements `IFastEnumerable` for them.

 Then a foreach loop could statically check for the `GetFastEnumerator` method, as well as/instead of dynamically checking for an `IFastEnumerator`.

The main disadvantage to this, is that a lot of magic goes on under the hood of the compiler, and it's not clear if the benefit of being able to statically check for an `IFastEnumerator` is worth it.

**Comment by svick** [comment]
> foreach loops should dynamically check for an `IFastEnumerator`, so they can use the `TryGetNext` method.

Can you explain in more detail how would that work? Especially since `foreach` is currently mostly pattern-based, not interface-based, so for example it might not be trivial to figure out which `T` to use when casting to `IFastEnumerator<T>`.

Looking at [the spec for `foreach`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-foreach-statement) might be helpful here.

> Increased performance in a very large percentage of current C# hot paths.

I would like to see some evidence for this, especially since:

1. In some cases, `foreach` does not use interfaces calls, because `GetEnumerator` returns a `struct` enumerable. So this would not improve e.g. iterating a `List<T>`.
2. When it comes to LINQ, that already allocates and uses delegate calls, would getting rid of one interface call per iteration actually significantly improve performance?

> Dynamic checks may be slower than just using an ordinary Enumerator for small IEnumerables.

This could be a deal-breaker. Performance optimizations often have to be conservative, in that not regressing performance in some cases might be more important than improving performance in other cases.

> Use DIM to implement `IEnumerator<T>` for `IFastEnumerator<T>`

I don't think this implementation would work. As currently planned, DIMs won't allow fields or auto-properties in interfaces.

**Comment by YairHalberstadt** [comment]
@svick
I have updated my proposal to reflect the various points you've made, and my response to them.

**Comment by svick** [comment]
> However I believe this is unlikely, as a dynamic check is very quick, and there are existing examples where the BCL chooses to do this. Consider Linq.Count for example which dynamically checks for `ICollection`.

Keep in mind that dynamic check for a covariant interface (like `IFastEnumerator<out T>`) is currently much more expensive, see https://github.com/dotnet/coreclr/issues/603.

---

Though I still think the most important thing missing here is actual numbers. You're proposing something whose only goal is to improve performance, but without saying how much it will improve performance. I think without that, it's not possible to gauge whether this is actually desirable.

**Comment by YairHalberstadt** [comment]
That's fair enough @Svick
I will try an do some benchmarking when I get a chance - at the moment I'm out.

**Comment by theunrepentantgeek** [comment]
In the case of `IAsyncEnumerable<T>`, [avoiding an asynchronous transition]( https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-10-03.md#async-streams) by consuming all available items synchronously before calling `WaitForNextAsync()` makes a lot of sense. After all, asynchronous transitions are very expensive.

But I'm not sure I'm comfortable with the assertion being made that the existing `IEnumerator<T>` interface is flawed.

Yes, the existing design requires two accesses via an interface - but this is an extremely common operation, and the runtime folks have a habit of making common operations work extremely quickly.

I created a simple benchmark to compare the existing framework interface with the one proposed here.

The test routines add all the integers from 1 to 1000, accumulating the result in a **long**, here's one:
```
[Benchmark]
public void Framework()
{
    long total = 0;
    var enumerator = new FrameworkEnumerator();
    while (enumerator.MoveNext())
    {
        total += enumerator.Current;
    }

    result = total;
}
```

Check out the [gist](https://gist.github.com/theunrepentantgeek/0b61e24bb23c641dac84bb0c99623547) for the gory details, or if you want to run it yourself.

Here are the results, courtesy of Benchmark.Net:

|    Method |     Mean |     Error |    StdDev |
|---------- |---------:|----------:|----------:|
| Framework | 2.373 us | 0.0451 us | 0.0421 us |
|      Fast | 1.671 us | 0.0199 us | 0.0186 us |

Keep in mind that these readings are for the *entire* calculation, not one iteration of the loop. 

*Technically*, the proposed `IFastEnumerator` would be quicker ... but the difference is so small that *practically*, I can't see it being significant. 

Based on these results, it seems to me that the effect on performance in any meaningful program would be lost in the statistical noise of measurement. There would be a greater performance increase achieved by eliminating a _single_ defensive struct copy, avoiding a _solitary_ string allocation, or specifying the capacity for a `List<T>` on construction.

**Comment by AdamSpeight2008** [comment]
The following interface seems a better fit to the existing usage.
```c#
public interface IFastEnumerator<out T> : IEnumerator<T>, IDisposable
{
    bool TryGetNext(out T value);
}
```

**Comment by YairHalberstadt** [comment]
@AdamSpeight2008
That wouldn't work with covariance

**Comment by MillKaDe** [comment]
I would also prefer this version:
```c#
bool TryGetNext (out T value);
```
because it is much easier to consume:
```c#
var e = SomethingEnumerable.GetEnumerator ();
while (e.TryGetNext (out int i)) DoSomething (i);
```
Maybe both could be added as **Default Interface Methods**,
either like this:
```c#
public bool TryGetNext (out T current) {
  bool success = MoveNext ();
  current = success ? Current : default;
  return success;
}
public T TryGetNext (out bool success)
  => (success = TryGetNext (out T current)) ? current : default;
```
or like this:
```c#
public bool TryGetNext (out T current) {
  current = TryGetNext (out bool success);
  return success;
}
public T TryGetNext (out bool success)
  => (success = MoveNext ()) ? Current : default;
```

**Comment by YairHalberstadt** [comment]
@TheUnrepententGeek
Thank you for that: It is certainly illuminating.

So we see a very large percentage increase in the performance of the loop, but a very small absolute increase.

That means that for tight loops running for many iterations this would actually be a meaningful performance boost.

Now where tight loops tend to be most used, and cause the greatest performance bottleneck, is in Linq.

I think I will try to look into two further things. 

Firstly, how large does the `Enumerable` have to be to compensate for the extra cost of the dynamic cast to `IFastEnumerator`.

Secondly, for Linq methods with very tight loops such as Select, Sum, Cast, Max etc. It would be informative to see if there are any meaningful gains percentagewise in performance for these methods when using a `FastEnumerator`. I could modify the current implementations in CoreFx and benchmark the results.

**Comment by theunrepentantgeek** [comment]
@YairHalberstadt, I suspect you may be missing my point.

In my opinion, based on that benchmarking ...

... if you have a tight loop that is (literally) processing _millions_ of items, then you might save a millisecond or two (and you'd likely save more time by doing the enumeration yourself using a **for** loop or another approach).

... or if you have a loop that is doing anything non-trivial, then the performance improvement is somewhere between negligible and non-existent.

**Comment by willard720** [comment]
Isn't it convention to have the return value be `bool`, and the `out` be the value, so you can do `if (foo.TrySomething(out bar));`?

It''ll convert this:
```csharp
while(true)
{
    var value = enumerator.TryMoveNext(out var any);
    if(!any)
         break;
    DoSomething(value);
}
```

Into this:

```csharp
while(true)
{
    if (!enumerator.TryMoveNext(out var value))
         break;
    DoSomething(value);
}
```

**Comment by HaloFour** [comment]
@willard720 

> Isn't it convention to have the return value be `bool`, and the `out` be the value, so you can do `if (foo.TrySomething(out bar));`?

Yes, but this breaks the covariance of the interface.

**Comment by bbarry** [comment]
Had the initial implementation been up for debate, I would strongly prefer this design, but given the other design already in use, I don't see much reason to add this complexity to the language. When I change the implementation in @theunrepentantgeek's benchmarks to implement `IEnumerator<T>`  and write the type how I would expect someone to implement it:


    public interface IFastEnumerator<out T> : IEnumerator<T>
    {
        T TryGetNext(out bool success);
    }

    public class Enumerator : IFastEnumerator<int>
    {
        private int _value = 0;

        public int TryGetNext(out bool success)
        {
            var lvalue = _value+1;
            _value = lvalue;
            success = lvalue < 1000000;
            return lvalue;
        }

        public int Current => _value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            TryGetNext(out var t);
            return t;
        }

        public void Reset() { }
        object IEnumerator.Current => Current;
        public void Dispose() { }
    }

    public class TestBed
    {
        [Benchmark]
        public long Framework()
        {
            long total = 0;
            Enumerator enumerator = null;
            try
            {
                enumerator = new Enumerator();
                while (enumerator.MoveNext())
                {
                    total += enumerator.Current;
                }
            }
            finally
            {
                enumerator?.Dispose();
            }

            return total;
        }

        [Benchmark]
        public long Fast()
        {
            long total = 0;
            Enumerator enumerator = null;
            try
            {
                enumerator = new Enumerator();
                while (true)
                {
                    int value = enumerator.TryGetNext(out var more);
                    if (!more) break;
                    total += value;
                }
            }
            finally
            {
                enumerator?.Dispose();
            }

            return total;
        }
    }

I get numbers even more suggestive that there is no notable difference in performance; this particular result was one of the ones more favorable to the fast implementation:

Method |       Mean |     Error |    StdDev |
-------------------------|-----------|----------|----------|
Framework | 1,429.3 us |  14.15 us |  11.04 us |
Fast | 1,407.3 us |  27.98 us |  45.98 us |

(there is a notable difference when the calls are forced to be virtual via typing to the interface, but on a hot path if you cared about that difference you would avoid the interface) Full code here with variations:

https://gist.github.com/bbarry/f3090efb39c5664e5271649e9804d59e

**Comment by YairHalberstadt** [comment]
@bbarry
The advantage of this implementation is that often you are dealing with an IEnumerable, and are forced to use the interface methods, which can't be inlined. For example in a Linq method.

**Comment by scalablecory** [comment]
I imagine this will provide an even large benefit with Spectre workarounds effectively removing jump target prediction.

With default interface methods you could keep the interface as `IEnumerable` -- I wouldn't want to bloat LINQ with yet another interface that'd break compatibility with all the existing stuff built around it.

**Comment by omariom** [comment]
@theunrepentantgeek 

The calls to [MoveNext/Current](https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABJgRgG4BYAKB3wIDoAlAVwDs4BLVAU2oGEB7VABxYAbdgCcAymIBuLAMbtkpCgCZs5TAGYqEfMqoB2XOQDe5XOe24hPRgHNcohfSFwlFo2XebLmKLgCyiCyMABQAlB7upp7u7gCQ1na4cDxwiEK4ALy42G6x+VKIorjsjPQcoogpxdmM7ADuuABilRz1PKIA1gCiZRVVHeFEuAD0IwDi7HC95WIDokPkZvmx9QAWwuy4IaWzldXU/jxS7ABy7GBw4WHLKxbRd3cpaRkA1Nm7/Qdc9KKOzHlHrgAL5LGJAxzIZxwLLJVLpQEg26RCwAbX8UzWPAAJgBJARCEIYuBYvEEgDy/FYNmQ1FOPFxjCEwWCtjCAF1kfxRCxCnAtoQdLiWog2h0en05tUADzBOAAPlwk2mkv2gxu4NwDxWmEMdUaIrFXRmX3ViNBmuR3jlYgAZoh5Lhha0GuKTVKOtKePQYQAVeXI7X5YA8HgZI4nc6XRaa9zI9y+3A/P6lGHGXC2KbDC3uHMWbyYPSG13G1XzXAgJ3F9qlvbzWXMAOaoOxbm8qpbOW4AD6hSE9C22Vy8YsI/M1uYSd+/xhmUVvfSA8Rcdj+a0IbDAWOZwuVw1dxbdwX/fYr1ey51hmPA9w0twBGwj4v5jzL/IwKAA==) were completely inlined.
As well as the call to [TryGetNext](https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABJgRgG4BYAKB3wIDoAlAVwDs4BLVAU2oGEB7VABxYAbdgCcAymIBuLAMbtkpCgCZs5TAGYqEfMqoB2XOQDe5XOe24hPRgHNcohfSFwlFo2XebLmKLgCyiCyMABQAlB7upmQAkDHWdrhwPHCIQrgAvLjYSuRxUoiiuOyM9ByiiMlFWYzsAO64AGIocACipeWVPKLhROYA9P0A4uxtHWJdPWG5sTF1ABbC7LghcKL07GF5MdFxMcFwuAVCG5nF4xVV1AAqogCeI3AAcuxgcCE89IfAPDzpyPRZPJkMhpmZ3BDzNt9gAzFYAQgBQIUoOhMWAjkQAGs3JC8VDZjFkql0gBqLLHDZKOIAX22jgBLjOxLSuPMdM8FnB5gA2v5RvMeAATACSAiEIX5cEFovFAHl+KwbMhqE8eCLGEJgsFbGEALrc3D8UQsApwZaEHQi5rIMZlCZVAA8BwAfLhHu17ZduuFDdF8ZhDLUGja7Z0qr1DRz3IbvAcxDDEPJcNaWp7w91HZ9DtcXX7De5rrhbg9Ri83h8vrgfn9cEjgaC2bgObGtJg9KH0w7urgQCnOxdJs7mHnOeZ/XjjabKssDrgAPqU5ZZHLkAsWOPMYv3R7l97Z6u/f6AhtbMcQif48yLtIbUmkpv4+sos43k7LR24AjYH8zK8bww3ypdd2SjcgaSAA=).

**Comment by arekbal** [comment]
These "performance improvements" are _puny_, compared to where modern _for_-_loop_ improvements lie:
- flat memory caches with high locality (interleaved arrays, could improve a lot of _for_s over _struct_s)
- vectorization
- (as an effect and bonus of vectorization), loop unrolling

Whatever improvements you want to make into iterators/enumerators/whatever... these facts have to be considered.
Have a look at [this](https://gist.github.com/arekbal/dd84cd710afc5f7be95eafa0324c1fb3):
     Method |     Mean |      Error     |     StdDev   | Scaled  | ScaledSD |
----------- |---------: |-----------: |-----------:  |-------: |---------:  |
      array    | 825.2 ns | 21.0251 ns| 61.9931 ns |   1.00  |     0.00 
 vectorized | 219.2 ns |  0.8618 ns |  0.8061 ns  |   0.27  |     0.02

Almost 4 times as fast on quite outdated processor.
I don't hope for IFastEnumerable to be optimized into vectorable data... but for the very least it shouldn't make it harder for the compiler to optimize away cases, where memory access is flat(as in items are laid out in continous way) and inlined loop access could be unrolled. I would hope that new IIterator would return elements in 'vector' friendly way...

**Comment by jmarolf** [comment]
I'll go ahead a link to jared's old post on this topice: http://blog.paranoidcoding.com/2014/08/19/rethinking-enumerable.html

If we are going to add a new IEnumerable-like pattern I would prefer it not repeat the issues with the current design.

**Comment by benaadams** [comment]
> Is there any way to do that without introducing a breaking change?

A second pass on generic constraint resolution https://github.com/dotnet/csharplang/issues/982

**Comment by jmarolf** [comment]
@YairHalberstadt presumably its an entirely new interface which several implementations such as linq and foreach pattern match against and use.

**Comment by YairHalberstadt** [comment]
@jmarolf
The problem is, it would require you to write two version of every method - one accepting the old IEnumerable, the other the new. Since you don't know the type of IEnumerator, you can't check for the new IEnumerable dynamically.

**Comment by manofstick** [comment]
This might be of interest: https://github.com/dotnet/corefx/pull/34208

**Comment by Korporal** [comment]
@YairHalberstadt - is there any way you could leverage the upcoming support for default interface implemantations to alter the existing IEnumerator interface? You could add a default implemented TryGetNext then recompile the entire framework. Then update the CLR/codegen to use the new intrface method (who's default implementation simply delegates to older interface method). After that consumers of the interface (.Net Frameworks or customers) could overrride the default implementation as and when they wanted.

**Comment by YairHalberstadt** [comment]
@Korporal

That might work.

One issue with that would be that then calling TryGetNext would call three interface methods if the default implementation is used. So you have better performance in some cases, but worse performance in others. In general the CoreFX team does not like degrading performance anywhere, unless the advantage in the general case is significantly better.

**Comment by NutzNK** [comment]
@YairHalberstadt 

I already create my own library for fix ienumerable<T> performance issue too.
because ienumerable<T> template from Microsoft take several times slower than array iteration.

problem is when collection has been casted to ienumerable<T> by casting or return by some function, ienumerator<T> interface  method "MoveNext" and property "Current" cannot be inlined.


This is standard "Foreach" equivalent code:

using(var enumerator = object.GetEnumerator())
{
  while(enumerator.MoveNext())
  {
    var value = enumerator.Current;
    //code here
  }
}

I would prefer to make "Foreach" instruction support equivalent code like this

using(var enumerator = object.GetEnumerator())
{
  while(enumerator.TryMoveNext(out var value))
  {
    //code here
  }
}

by changing IEnumerator<T> to

public interface IEnumerator<out T> : IDissposable
{
  bool TryGetNext(out T value);
}

then Enumerator should look like this(example for List<T>)

public struct Enumerator : IEnumerator<T>
{
  private T[] items;
  private T current;
  private int index, size;

  public Enumerator(List<T> source)
  {
    items = source.items;
    current = default;
    index = 0;
    size = source.Count;
  }

  public T Current => current;

  [MethodImpl(MethodImplOptions.AggressiveInlining)]
  public bool TryGetNext(out T next)
  {
    int i = index + 1;
    if (i < size)
    {
      next = items[i];
      index = i;
      return true;
    }
    else
    {
      next = default;
      return false;
    }
  }
}

this struct can perform as good as array iteration and give better performance than current IEnumerator<T>.

but next problem is interface that contains method with "out" parameter(s) cannot be co-variant type.
then I would suggest to co-variant type should support type that contains method with "out" parameter(s).

but now this code can use in real life

public interface IEnumerator<T> : IDissposable
{
  T Current;
  bool MoveNext();
  bool TryGetNext(out T value);
}

you can code both normal "foreach" loop and higher performance loop.
but it need to do some more work.
I would recommend to use it in critical sector only.

**Comment by orthoxerox** [comment]
@NutzNK could you please format your code using triple backticks before and after?
````
```c#
public class Foo {}
```
````

**Comment by YairHalberstadt** [comment]
Closing as this wouldn't bring substantial performance benefits. For a much more powerful direction to investigate take a look at https://github.com/dotnet/csharplang/discussions/2482
