### ISSUE TITLE
Feature Request: `assign if null` (?=) operator.

### ISSUE THREAD

**Issue by PhonicUK** [dotnet/csharplang#1935]
My proposal is the addition of a `?=` operator. The following lines would be syntactically equivalent:

```
foo ?= bar;
foo = foo ?? bar;
```

This allows the `?` operator to follow the convention used by string and arithmetic operators of being combined with `=` to change the value of the object it's being used upon instead of having to repeat the name of the object. As with say `foo += bar;` for addition rather than `foo = foo + bar;`.

**Comment by HaloFour** [comment]
#34
