### ISSUE TITLE
A design for nullable opt-in

### ISSUE THREAD

**Issue by MadsTorgersen** [dotnet/csharplang#1939]
# A design for nullable opt-in

At the C# Language Design Meeting on [Oct 3](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-10-03.md) we resolved to express source-level opt-in to the nullable reference types feature through the use of compiler directives.

Here is a proposal for a concrete design that fleshes out more details.

# Contexts
Every line of source code has a nullability context, which consists of an annotation context and a warning context.

## Annotation context
The annotation context for a given line is either *on* or *off*
* When the annotation context is *on*, unannotated reference types are considered non-nullable, and `?`-annotated reference types are considered nullable.
* When the annotation context is *off*, unannotated reference types are considered oblivious, and `?`-annotated reference types yield a warning and are considered oblivious.

## Warning context
The warning context for a given line is either *on* or *off* for each warning id. When a given warning condition occurs on a given line, and the warning context of that warning on that line is *on*, the warning is given. 

# Switches
There are two levels of switches to control nullable behavior:

1. Project-level switches provide default behavior for all files in the project, and are also known as "compiler switches" *I won’t try to detail here how exactly they are specified, since I don’t know enough about it.*
2. File level switches provide behavior for a certain span of lines in a given source file, and are specified by means of `#`-directives in the source code.

At each of the two levels there is a hierarchy of switches:
a. Feature switch: sets the annotation context as well as the warning context for all nullable warnings
b. Warning switch: sets the warning context for all nullable warnings
c. Specific switch: sets the warning context for a specific warning (as today)

Specific trumps general. Specifically:

1.	At the project level, settings for specific warnings (c) trump those for all nullable warnings (b), and both trump the general feature switch (a).
2.	Within a file, a given directive changes the part of the context it controls for subsequent lines, and leaves the rest unchanged from above it

## File-level directives
The directives for the three kinds of switches are:
``` c@
#nullable <setting>                // (a) Set annotation context and all nullable warnings
#pragma warning nullable <setting> // (b) Set all nullable warnings
#pragma warning CSxxxx <setting>   // (c) Set a specific warning, as today
```

# Settings
Current `#pragma` warning directives only have disable and restore settings. We can technically make do with those, but there is more expressiveness that could be had by adding more settings.

## Restoring to default
Since in today’s world all warnings are on by default (*is this correct?*), `restore` simply turns the warning back on. In C# 8.0 it’s going to be common for warnings to be *off* by default (because of project level settings around nullable or warning waves). If directives can only turn *on* and *off*, then the only part of a source file that can adhere to project level settings is the beginning of it, *before* the first directive! If we want to allow returning to project settings later in the file, we need a third setting to do that. I propose reinterpreting `restore` to mean "restore to project level setting" (which could be *off*), and then adding `enable` which would be the dual of `disable` and always turn the warning on.

Example:

``` c#
// To start out the context is based on project settings
public class Dictionary<TKey, TValue>
{
    public Dictionary() { }
    public Dictionary(IDictionary<TKey, TValue> dictionary) { }
#nullable enable // annotations and all warnings are on 
    public Dictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection) { }
#pragma warning CS4321 restore // revert specific warning to project settings
    public Dictionary(IEqualityComparer<TKey>? comparer) { }
#nullable disable // annotations and all warnings are off
    public Dictionary(int capacity) { }
#pragma warning nullable enable // warnings are on, annotations still off
    public Dictionary(IDictionary<TKey, TValue> dictionary, IEqualityComparer<TKey> comparer) { }
#pragma warning nullable restore // warnings restored to project settings, annotations still off
    public Dictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection, IEqualityComparer<TKey> comparer) { }
#nullable restore // annotations and all warnings restored to project settings 
    public Dictionary(int capacity, IEqualityComparer<TKey>? comparer) { }
#pragma warning nullable enable // Warnings are on, annotations remain at project settings
    protected Dictionary(SerializationInfo info, StreamingContext context) { }
}
```

## W-warnings
Furthermore, we need a way to specify that we want only non-W warnings. ("W-warnings" is our completely nondescriptive way of referring to null-warnings that don't directly impact null safety, such as assigning null to a nonnullable local.) I propose a *fourth* setting that only works for nullable, not other kinds of warnings, which could be called `safe`. It means "*off* for W-warnings but *on* for null-safety-critical warnings". I propose we allow it *both* for `#pragma warning nullable` specifically, but also for `#nullable` directly. For the latter it means "turn on annotations, and also warnings, except W-warnings":

``` c#
#nullable disable // annotations and all warnings are off
    public Dictionary(int capacity) { }
#pragma warning nullable safe // non-W warnings are on, annotations still off
    public Dictionary(IDictionary<TKey, TValue> dictionary, IEqualityComparer<TKey> comparer) { }
    public Dictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection, IEqualityComparer<TKey> comparer) { }
#nullable safe // annotations and non-W warnings are on
    public Dictionary(int capacity, IEqualityComparer<TKey>? comparer) { }
#pragma warning nullable enable // All warnings are on, annotations remain on
    protected Dictionary(SerializationInfo info, StreamingContext context) { }
```

## Project-level settings
At the project level we don’t need an equivalent to the `restore` setting, but we would want an equivalent to the `safe` setting. Again, I don’t have a proposal for what project-level switches look like syntactically.

# Scenarios
The above design is proposed with the following prioritized list of scenarios in mind:

1.	I upgrade my code to C# 8.0. *It all still just works.*
2.	I start a new project in C# 8.0. *Nullable just works.*
3.	Scenario 1, plus I want to use nullability everywhere.
4.	Scenario 2, plus I don’t want to use nullability anywhere.
5.	Scenario 1 or 4, plus I want to gradually add nullability annotations and get nullability warnings.
6.	Scenario 2 or 3, plus I want to omit annotations or avoid warnings in some places.
7.	Scenario 1 through 6, plus I want to control warnings separately from annotations.

The complexity of getting into each scenario increases only as priority decreases:

## Scenario 1: Upgrade
The default setting for the project-level feature switch is off, and no code that compiled in C# 7.x will have the new directives in it, so this happens by default without any explicit effort.

## Scenario 2: New project
C# 8.0 project templates will have the project-level feature switch `enable`d. This makes annotation and warning contexts (for all nullable warnings) *on* by default in all source files. I don’t have to do anything.

## Scenario 3: Nullify upgraded project
Set the project level feature switch to `safe` or *on*.

## Scenario 4: De-nullify new project
Remove the project-level feature switch or set it to *off*.

## Scenario 5: Nullify within oblivious project
Add `#nullable safe` or `#nullable enable` directives where applicable.

## Scenario 6: De-nullify within null-aware project
Add `#nullable disable` directives where applicable

## Scenario 7: Control warnings separately
Add `#pragma warning nullable` directives to deviate locally from warning contexts introduced by `#nullable` or the project settings, or add project warning settings to deviate systematically from project feature settings across all files.

# Discussion
The above proposal has some complexity. However I feel like it hits all the scenarios, and makes the complexity “pay for play”, depending on the gnarliness of the user’s situation:

* Scenario 1 and 2 don’t need any new effort from the developer
* Scenario 3 and 4 require toggling a single project-level switch (which we should make good UI for)
* Scenario 5 and 6 require use of `#nullable` directives to turn the whole feature on and off for parts of the code
* Scenario 7 requires project-level warning settings and/or use of `#pragma warning nullable` directives to handle warnings separately from annotations

I think the proposed `restore`/`enable` distinction is useful (even for warnings that are not related to nullability), but we can certainly live without it. However, if we want to do it we need to do it now, since it changes the meaning of `restore` for scenarios we are about to introduce.

I really like using a `safe` setting for disabling W-warnings, because it makes it more first class and enables it to be expressed directly on the feature setting. You don’t *first* have to enable all warnings, and *then* turn some of them back off. However, if we don’t like it we can instead go back to the idea of having a fake diagnostic for the W-warnings, but I think that makes turning the W-warnings off way too obscure.

I previously advocated that the in-file directives should only "work" when the feature was turned on at the project level. I am now convinced that it is important to be able to turn it on per file without churning other files. A specific scenario is generated code that is not annotated: you cannot edit it, and you want to keep it oblivious.

The proposal makes it up to the developer in scenario 5 if/when to "flip" into a scenario 6 situation – that is, to go from file-level opt-in to project level opt-in with file-level opt-out. I think "flipping" is a much less dramatic operation now that we have directives than it would have been with attributes, so I’m not too worried about it.

**Comment by YairHalberstadt** [comment]
Secondly, I presume CoreFX will be updated to use nullable reference type annotations.

Has an study been done to see what effect this will have on an "average" existing code base which turns on warnings but not annotations? Will they be inundated with countless warnings, effectively making this impossible to do except incrementally, or can they expect to only have to deal with a limited number of warnings? 

I understand this will vary hugely depending on the quality of the code base, but it's important to have some sort of idea in order to see whether there is a reasonable upgrade path from no warnings to warnings to annotations.

**Comment by dsaf** [comment]
> Scenario 3 and 4 require toggling a single project-level switch (which we should make good UI for)

Just wanted to mention that I really dislike the current ```Build -> Advanced -> C# latest minor version (latest)``` thing. This is the GUI experience I would use if I wanted users to avoid using some feature. I mean it needs to be explicitly set even for new projects! Should it not be some sort of a big fat flag being prominently displayed on the very first page of some new project wizard?

**Comment by DavidArno** [comment]
As @dsaf says, the current experience around creating projects could be improved here. When I create a core project, let me pick the core version, the language version, whether I want treat warnings as errors and NRT support turned on all from the new project dialogue please.

Currently I just edit the project file directly as setting those first three through the UI is too much of a "where's that feature hidden away?" painful experience.

What would be the ideal experience is the means of easily creating my own custom templates that have things set up the way I want ("cutting edge language;draconian intolerance of warnings and errors"), then I can just use those templates.

**Comment by DavidArno** [comment]
Oh and will there be a "treat all non-annotated assemblies (inc 3rd party) as nullable" option for this feature, or are we stuck with the low-warning count, but unsafe "unannotated == oblivious" as our only option?

**Comment by yaakov-h** [comment]
I assume there would be a way to control the default nullability settings using `Directory.Build.props` for larger projects?

(@dsaf you should try it with `<LangVersion>`, it's a life-saver.)

**Comment by MichaelKetting** [comment]
I've just tried Visual Studio 2019 Preview 1 to take C#8 for a spin and from what I can surmise, the the project-level setting doesn't exist yet, is that correct? I.e. do I have to apply `#nullable enable` to each individual code file?

**Comment by davidnmbond** [comment]
Mads says at 2:17 in this video that it can be set for the whole project but doesn't say how!  

https://www.youtube.com/watch?v=VdC0aoa7ung&feature=youtu.be&t=135

**Comment by ufcpp** [comment]
```xml
<PropertyGroup>
  <NullableReferenceTypes>True</NullableReferenceTypes>
</PropertyGroup>
```

**Comment by MichaelKetting** [comment]
Great, thanks!

**Comment by jeanluc33** [comment]
Absolutely necessary given the amount of legacy generated code (e.g. Visual Studio-generated code from WSDLs, other generated code, etc.).

As a separate item, I hope the other VS teams who do the code generation features can adjust their respective templates to use the new feature (perhaps initially defaulting to variable? if they don't have time to do a full rewrite of the output code).

**Comment by 333fred** [comment]
Nothing left to discuss here.
