### ISSUE TITLE
Feature request: Delegates understanding implemented interface

### ISSUE THREAD

**Issue by mitedo** [dotnet/csharplang#1942]
When a delegate is added and you add it with an event as parameter, it will fail when you use an implemented interface.

> 
    public interface IStuff
    {
        int face { get; }
    }
    class FirstClass : IStuff
    {
        public int face { get; private set; }

    }
    class SecondClass : FirstClass
    {
    }

    class Foobar
    {
        public delegate void AwesomeStuffHandler(object sender, IStuff stuffable);
        public event AwesomeStuffHandler StuffDispatcher;
        
        public Foobar()
        {
            AwesomeStuffHandler(this, new SecondClass());
            this.StuffDispatcher += Foobar_StuffDispatcher;
        }

        private void Foobar_StuffDispatcher(object sender, FirstClass stuffable)
        {

        }
    }

fail:  AwesomeStuffHandler(this, new SecondClass());
fail:    this.StuffDispatcher += Foobar_StuffDispatcher;

It would be absolutely awesome it this works.

**Comment by HaloFour** [comment]
That would break type safety.  You'd be registering a event that could pass an `IStuff` to a method that requires a `FirstClass`.  What happens when that event publishes something other than a `FirstClass`?  You'd get an error at runtime.

**Comment by mitedo** [comment]
Well, it should interpreted it the same way as 
```
IStuff foo = new FirstClass();
IStuff foo = new SecondClass();
```
Otherwise it could throw an `InvalidCastException `or `InvalidOperationException`

It would fix a few problems for me.

**Comment by HaloFour** [comment]
The fact that it could throw would be a problem.  Where variance is permitted in the language (and the runtime) it is intentionally limited to prevent scenarios that would result in an exception being thrown.

You already have a simple workaround; handle the event with a method that accepts `IStuff` and have that method cast and then call `Foobar_StuffDispatcher`.  Then you can decide how to handle the possibility of `stuffable` being something other than `FirstClass`.

**Comment by jnm2** [comment]
C# delegates already support contravariance (method parameters with less derived types) and covariance (return values with more-derived types). https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates

You're asking for covariance with method parameters which would be as disastrous for type safety as array covariance. https://codeblog.jonskeet.uk/2013/06/22/array-covariance-not-just-ugly-but-slow-too/

**Comment by jnm2** [comment]
This is how folks often handle this situation:

```c#
private readonly Dictionary<string, EventHandler> handlers = new Dictionary<string, EventHandler>(StringComparer.OrdinalIgnoreCase);

public void AddEventListener<TEventArgs>(string eventName, EventHandler<TEventArgs> handler)
    where TEventArgs : IFrameworkEvent 
{
    var adaptingHandler = new EventHandler((sender, e) => handler.Invoke(sender, (TEventArgs)e));

    handlers[eventName] = handlers.TryGetValue(eventName, out var existingHandler)
        ? existingHandler + adaptingHandler 
        : adaptingHandler;
}
```

Usage:

```c#
obj.AddEventListener("foo", FooHandler);

void FooHandler(object sender, FooEvent e)
{
    // ...
}
```

With the `handler.Invoke(sender, (TEventArgs)e)`, you're in the driver's seat knowing that consumers of your API will never actually cause an InvalidCastException.

**Comment by mitedo** [comment]
Thank you, This will do.

I'll close the request now (however I still think it would be a win)
