### ISSUE TITLE
Pattern matching shortcut

### ISSUE THREAD

**Issue by taori** [dotnet/csharplang#1950]
I was just writing some code where i wondered if there is a less repetive way of writing this but i could not think of a shorter way.

![grafik](https://user-images.githubusercontent.com/5545184/47368692-5f064700-d6e2-11e8-8a0f-6c934563fdc4.png)

It would be cool if i could just write something like this to capture a methods result
![grafik](https://user-images.githubusercontent.com/5545184/47368781-8f4de580-d6e2-11e8-9b17-af7cb3c3c9ea.png)

Maybe i'm just unaware of a better way of writing this code though.

**Comment by YairHalberstadt** [comment]
The `is var` pattern is a pretty horrible one in my opinion, and it would be nice to have something that made the intent of the programmer clearer.

However, I don't feel like this proposal fits in with existing C# syntax well. If a neater syntax was suggested, I might support it.

I think a similar proposal was suggested recently.

**Comment by ymassad** [comment]
@taori , what does `CurrentChildren.IndexOf` return? `int?`?

**Comment by taori** [comment]
@YairHalberstadt i don't know. I think there are plenty scenarios where the pattern matching is done to check for type compatibility - it's just repetetive if you're planing on working with the value in the context of a condition and in the ongoing block expression

@ymassad No -` int`; for `int?` it would have to be `CurrentChildren?.IndexOf`

**Comment by ymassad** [comment]
@taori ,
> for int? it would have to be CurrentChildren?.IndexOf

I am not sure I understand this.

if `IndexOf` returns `int`, why not simply do something like this:

`if`(CurrentChildren.IndexOf(item) > 0)`

You don't seem to use the `index` variable anywhere else.

**Comment by HaloFour** [comment]
I don't see why pattern matching is at all necessary here.  The following code, in my opinion, reads much better than the pattern matching version or the proposed shorthand:

```cs
var index = CurrentChildren.IndexOf(item);
if (index >= 0)
{
    // do stuff here
}
```

**Comment by jnm2** [comment]
One thing I do occasionally:

```c#
while (CurrentChildren.IndexOf(item) is var index && index >= 0)
{
    // index is not leaked to outer scope
}
```

**Comment by HaloFour** [comment]
@jnm2 

Oof, does combing two abuses make it right?  😉 Don't forget that `break;`

**Comment by jnm2** [comment]
@HaloFour The assumption is that the `while` is actually called for...

**Comment by taori** [comment]
@HaloFour It's clean to read yes, but ever since the feature was released i am using it as an on demand assignment. If there is a multitude of conditions it feels like a chore having to declare an assignment area in order to use values as condition. 

To be honest even with the repetetiveness i prefer `CurrentChildren.IndexOf(item) is var index && index >= 0` over two lines. Hence the request for a shortcut to combine assignment and working with the value. That would result in the least amount of code to accomplish a task

**Comment by taori** [comment]
## oldschool verbose
```
var index = CurrentChildren.IndexOf(item);
if (index >= 0)
{
    // do stuff here
}
```

vs 

## repetetive + abuse
```
if (CurrentChildren.IndexOf(item) is var index && index >= 0)
{
    // do stuff here
}
```


## no verbosity at all
```
if (CurrentChildren.IndexOf(item) :index >= 0)
{
    // do stuff here
}
```

**Comment by jnm2** [comment]
`CurrentChildren.IndexOf(item) :index`

This gets hard to understand when there are ternaries around.

**Comment by HaloFour** [comment]
@taori 

> Hence the request for a shortcut to combine assignment and working with the value.

The `var` pattern is that shortcut.  The only thing that your proposal removes is the declaration, which hides the fact that you are creating a new variable at that point.  I'll take the "verbosity" of 4 additional characters to make that clear.

There are declaration/sequence expressions proposed [here](https://github.com/dotnet/csharplang/issues/973) but, IIRC, they would not leak the variables to the outer context.  And since they involve a proper declaration within the expression they would not be less verbose.

**Comment by taori** [comment]
@HaloFour @jnm2 What about this?

```cs
if (CurrentChildren.IndexOf(item) let index >= 0)
{
    // do stuff with index here
}
```

any other keyword would be fine too obviously. The hidden assignment indeed would be a potential issue. While "as  (the name of the variable)" would be a suitable keyword from a semantic perspective it would be missleading since it is used for type casting.

**Comment by YairHalberstadt** [comment]
@jnm2
I feel like `is var` hides the intent of the programmer. It indicates he's checking for something using pattern matching, rather than assigning something. It's not the worst abuse, but it feels like using the language in a way it wasn't designed for, but happens to work.

**Comment by HaloFour** [comment]
Actually, the combination of the declaration and a second expression there makes it even less apparent what is happening.  What is the allowed syntax of that second clause?  What if that expression necessitated a method call?

**Comment by jnm2** [comment]
@YairHalberstadt I know, but the longer you think about `case var x`, the more the `case` -> `is` replacement makes sense. I would prefer sequence expressions:

```c#
if (var index = CurrentChildren.IndexOf(item); index >= 0)
```

Kinda feels consistent with this:

```c#
for (var index = CurrentChildren.IndexOf(item); index >= 0;)

**Comment by jnm2** [comment]
This would be fun too:

```c#
if ((var index = CurrentChildren.IndexOf(item)) >= 0)
```

@HaloFour Does this make sense?

**Comment by HaloFour** [comment]
@jnm2 

Were sequence/declaration expressions going to be leaky?

**Comment by jnm2** [comment]
I'm not sure. If so, then I'd still use the above, just never with `if` statements.

**Comment by taori** [comment]
@HaloFour I'll have to look up how to write a proper syntax out of this, but my thought in this case is that let makes the preceeding expression forward its result to the following expression. 

I can't type like this either - which would obviously be an easily understood expression but obnoxious to write.

`if ((var index = CurrentChildren.IndexOf (item)) >= 0)`

**Comment by taori** [comment]
> @YairHalberstadt I know, but the longer you think about `case var x`, the more the `case` -> `is` replacement makes sense. I would prefer sequence expressions:
> 
> ```cs
> if (var index = CurrentChildren.IndexOf(item); index >= 0)
> ```
> 
> Kinda feels consistent with this:
> 
> ```cs
> for (var index = CurrentChildren.IndexOf(item); index >= 0;)
> ```

I was starting to think you're making fun of my idea, but you're obviously getting what i'm getting at. :grinning:

My issue is that there are scenarios where declaration + usage of variables is a very slick, brief process and other scenarios where syntax abuse is an easy choice because the clean way of doing it seems more verbose.

It would just be extremely neat if there was a brief way of accomplishing that task without resorting to other "solutions" which are sort of abuse (using for) too.

**Comment by taori** [comment]
Inspired by jnm2 this would be a intuitive version too, while it would be easily read as => though. You get where i am going with this anyway. I just want a way of capturing the preceding expression and immediately work with its result

 ```cs
 if (CurrentChildren.IndexOf(item) -> index >= 0)
 {
     // do stuff with index here
 }
 ```

**Comment by HaloFour** [comment]
@taori 

The `->` operator already exists in C# for pointer dereferencing.

The specific operator doesn't matter, though.  My problem is that whatever is on the right-hand side appears to be some kind of combination of declaration and expression, and that doesn't make much sense.  There's nothing that tells the compiler there that `index` should be a newly declared identifier.  And I can't see how you extrapolate that into arbitrarily complex expressions.

**Comment by jnm2** [comment]
Not making fun at all. Just exploring!

**Comment by taori** [comment]
> 
> 
> Not making fun at all. Just exploring!

Yep, figured after a bit. I know that this sounds like a possibly unnecessary feature, but i've written plenty of LOC just to be able to check code and it would be great if i could write less code and stop the abuse on pattern matching.

Might need your backup here though. I think i don't have the appropriate level of knowledge required to discuss such a topic and whether it is possible and if so - how. I just see that with `for` abuse it seems possible, so i guess there has to be some way this feature could work.

I do however get that anyone involved with the compiler has the job of keeping the compiler sane and healthy.

**Comment by YairHalberstadt** [comment]
Besides for which, I would want to reserve a new operator that looked like an arrow for a more wide-ranging feature, like pipes or something.

I think HaloFours point about making clear that two separate things are going on here - an assignment and a new expression.

The for style syntax here is the best I've seen, but I don't feel it's advantages outway the cost of an easily readable if syntax.

Personally, I would just stick with the verbose style. It's a line longer, but it's clear.

**Comment by taori** [comment]
@YairHalberstadt 
> I think HaloFours point about making clear that two separate things are going on here - an assignment and a new expression.
> 
> The for style syntax here is the best I've seen, but I don't feel it's advantages outway the cost of an easily readable if syntax.
> 
> Personally, I would just stick with the verbose style. It's a line longer, but it's clear.

Now swap the scenario - The same argumentation could and probably was applied to

```
int val;
int.TryParse("123", out val);
```

Now it is 
```
int.TryParse("123", out var val);
```
The same thing is happening here - it is one line less, it is assignment+declaration. I would never in my life go back to writing the previous way of writing it, because it was a giant QOL improvement in terms of writing the code.

**Comment by HaloFour** [comment]
@taori 

> The same thing is happening here - it is one line less, it is assignment+declaration.

Yes, but it's only a declaration, and it still has the syntax of a declaration.  Your proposal is trying to eliminate the declaration syntax as well as include that declaration as an operand within another expression.  Is it particularly obvious what the following statement might do?

```cs
if (SomeExpression() : SomeMethod(foo, bar, baz)) { ... }
```

**Comment by gafter** [comment]
Solving the actual original problem, I would suggest writing

``` c#
if (CurrentChildren.IndexOf(item) >= 0)
```

**Comment by CyrusNajmabadi** [comment]
>Inspired by jnm2 this would be a intuitive version too, while it would be easily read as => though. You get where i am going with this anyway. I just want a way of capturing the preceding expression and immediately work with its result

Absent the availability of something like `is var` i would be far more onboard with having a solutoin here.   But given there is a language feature which is literally: "match anything, and place it in a variabled called 'name'", it seems like that fits the bill perfectly fine for this sort of use case.

**Comment by taori** [comment]
> 
> 
> Solving the actual original problem, I would suggest writing
> 
> ```cs
> if (CurrentChildren.IndexOf(item) >= 0)
> ```

i guess is hould have just used code instead of the image since what i am trying to do is different. using that way if you're not using the index would be obvious

**Comment by taori** [comment]
> 
> 
> @taori
> 
> > The same thing is happening here - it is one line less, it is assignment+declaration.
> 
> Yes, but it's only a declaration, and it still has the syntax of a declaration. Your proposal is trying to eliminate the declaration syntax as well as include that declaration as an operand within another expression. Is it particularly obvious what the following statement might do?
> 
> ```cs
> if (SomeExpression() : SomeMethod(foo, bar, baz)) { ... }
> ```

it would not be obvious yes, but i would only accept identifiernamesyntax instead of methodinvocation syntax if this feature were to exist, since only a name should be valid for that.

**Comment by taori** [comment]
> 
> 
> > Inspired by jnm2 this would be a intuitive version too, while it would be easily read as => though. You get where i am going with this anyway. I just want a way of capturing the preceding expression and immediately work with its result
> 
> Absent the availability of something like `is var` i would be far more onboard with having a solutoin here. But given there is a language feature which is literally: "match anything, and place it in a variabled called 'name'", it seems like that fits the bill perfectly fine for this sort of use case.

it fits this scenario yes, but it is more verbose than it potentially would have to be if this described feature were to exist.

**Comment by HaloFour** [comment]
@taori 

> it would not be obvious yes, but i would only accept identifiernamesyntax instead of methodinvocation syntax if this feature were to exist, since only a name should be valid for that.

But that's not what you're doing.  You have the identifier as an operand within a binary expression.  If it was just the name as an identifier you'd be right back to the `is var` situation, less the `is` and the `var`.  You'd have to define quite a bit of existing syntax to force that operand to only be a newly declared named identifier, and it severely limits where this syntax would even be applicable.  It's almost tailor-made to your use case rather than being general purpose.

> it fits this scenario yes, but it is more verbose than it potentially would have to be if this described feature were to exist.

It's not a race to see how few keystrokes the language requires.  Code is going to be read by developers significantly more often than it is going to be written, so it makes more sense to optimize for clarity rather than being terse.

**Comment by CyrusNajmabadi** [comment]
> it fits this scenario yes, but it is more verbose than it potentially would have to be if this described feature were to exist.

I don't see that as a problem.  This isn't perl after all :)

"is var name" is effectly only 5 chars longer than the shortest this could ever be (i.e. `<punc>name`).  We'll always need the name, and at least one character here.  So i don't really see there as much saving ot be had.
