### ISSUE TITLE
"let" bindings (like F# has) in any expression (not just as a Linq clause)

### ISSUE THREAD

**Issue by n8allan** [dotnet/csharplang#1954]
There are many times in C# when you need to reuse a sub-expression within an expression, and presently one must either duplicate the logic (boo!) or refactor such into a variable assignment.  Such refactoring, however, completely breaks from what is otherwise becoming a highly expressive language.  Functional languages tend to solve this by allowing the binding of a pseudo variable (it's not really a variable because it cannot be assigned to) to a sub-expression so that the binding can be used multiple times in the expression.
```csharp
string CleanName(string name)
  => String.IsNullOrWhitespace(name) 
    ? "" 
    : (
      let n = name.Trim() 
        Char.ToUpper(n[0]) + String.ToLower(n.Substring(1))
    );
```
This isn't just for reuse; it can often lead to more readable code, without the requirement of variable allocation, and the optimization challenges inherent in imperative code.  Another problem with the language without this feature is that refactoring sub-expressions often requires context that is only present within the expression, which leads to the creation of otherwise unnecessary creation of lambdas or methods.

**Comment by HaloFour** [comment]
Check out #973, it allows for variable declarations and assignments within expressions and would behave similarly:

```cs
string CleanName(string name)
    => String.IsNullOrWhitespace(name)
        ? ""
        : (
          var n = name.Trim();
            Char.ToUpper(n[0]) + String.ToLower(n.Substring(1))
        );
```

**Comment by lazyloader** [comment]
I believe there's already a request to use `let` for pattern matching or something

**Comment by n8allan** [comment]
Yes, it appears that #973 covers the spirit of the feature.  Thanks.
