### ISSUE TITLE
Switch expressions

### ISSUE THREAD

**Issue by brunnerh** [dotnet/csharplang#1956]
It would be nice if `switch` could be used as an expression, e.g.

```csharp
var area = switch (shape)
{
	// (Allows single line syntax, because it is an expression)
	case Circle c => Math.Pow(c.Radius, 2) * Math.PI;

	case Rectangle r:
		var w = r.Width;
		var h = r.Height;
		return w * h;
};
```

Probably should throw an exception if the cases are not exhaustive. To be safe one would just add `default => default(T);`.

**Comment by HaloFour** [comment]
This is already a championed proposal and being implemented in C# 8.0, although the syntax is a bit different and each case only supports a single expression.

```cs
var area = shape switch {
    Circle c => c.Radius * 2 * Math.PI,
    Rectangle r => r.Width * r.Height,
    _ => throw new InvalidOperationException("boom")
};
```

**Comment by ufcpp** [comment]
Switch expressions have already been implemented.

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwg4A2APgAIAMABCwIwDcAsACghLAMxcATBwDKACyhEIHAN4BfEeJZSAwjgQYGSkDPmKVXcWAYB7WBwBKUACY44yXh3WCxkhxAwwUBQA5oYcxnIKSsoWHFa2MBwA6jhOMLIePvF2ABIQOMGyMB5eGr7aQspCHDWxLAAsHACyABSRZsimEACU1bVVgrVDHHhQCBxj0BwAvBydUXMA7jgwGLJ9wyobm7W6+mEYMwB8zbCyAHQACtaLLRjnji5u1BwS3RwAVKfpVwCS1Nsdn4AkFQtFkql0sZRuNFi88gUitCxhxZJ5jhxFp9UQDBkDagB9DHpBA3DgUCBY34UJwQAAeAHk4DAGWBHCEIABROkYCBEGA4awUFq9PGbVQCMWeISqIA===

**Comment by brunnerh** [comment]
Oh, nice!
