### ISSUE TITLE
Proposal: Declare single parameter interface methods without a parameter name

### ISSUE THREAD

**Issue by yigitgursoy** [dotnet/csharplang#1958]
If a method accepts only a single parameter, the name of that parameter in an interface of that method is sometimes redundant.

My proposal is to be able to use a syntax like the one below:

```csharp
private class Example : IExample
{
    public int Add(int valueToAdd)
    {
        /* do something */
    }
}

private interface IExample
{
    int Add(int);
}
```

**Comment by DavidArno** [comment]
Really? I'd say the opposite is the case: the parameter name is *always* needed for the interface, but it isn't needed for your implementation. And a common convention to use there is to use `_` as the parameter name to denote it's not used:
```cs
class Example : IExample
{
    public int Add(int _) => throw new NotImplementedException();
}
```

**Comment by yigitgursoy** [comment]
> Really? I'd say the opposite is the case: the parameter name is _always_ needed for the interface, but it isn't needed for your implementation. And a common convention to use there is to use `_` as the parameter name to denote it's not used:
> 
> ```cs
> class Example : IExample
> {
>     public int Add(int _) => throw new NotImplementedException();
> }
> ```

Sorry I've explained myself wrong. (I'm not a native speaker.) Please check the difference in the interface declaration:

int Add(int);

**Comment by stuartstein777** [comment]
> 
> 
> Really? I'd say the opposite is the case: the parameter name is _always_ needed for the interface, but it isn't needed for your implementation. And a common convention to use there is to use `_` as the parameter name to denote it's not used:
> 
> ```cs
> class Example : IExample
> {
>     public int Add(int _) => throw new NotImplementedException();
> }
> ```

I agree with the OP, if you are going to leave the parameter name out anywhere, it would be the interface. You can't leave it out the class as the method needs it to... actually use it... But for the interface why does itneed to be classes that implemen this method takes a single int?

**Comment by YairHalberstadt** [comment]
What is the advantage of missing it out?

**Comment by DavidArno** [comment]
@stuartstein777,

But it isn't being used in the implementation, thus giving it a name there serves no purpose.

But within the interface, it forms part of the documentation of what the method does. `valueToAdd` tells me that value will be added to *something*, thougn the method name, `Add`, gives me no clues what it'll be added to. Remove the parameter and I just have `Add`. So now all I know is that something is added to something and that the parameter is involved somehow, probably.

**Comment by DavidArno** [comment]
@yigitgursoy,

Can you give us a real-world example of such a method?

**Comment by YairHalberstadt** [comment]
@yigitgursoy
In the rare case where there is genuinely no useful information you could add by naming the parameter (and this is rare. Even in the Add case you have how do you know if the parameter is the thing that's being added, or the thing you're adding to, or even the Id of the thing you're adding? Alright, I could guess, but why should I have to?) then you could just call the parameter input, or value, or param, or addend, or whatever, and save adding extra baggage to the language for no reason.

**Comment by yigitgursoy** [comment]
@DavidArno, if you have a lot of parameters (generally you do) and wrap them in an object, the word "request" becomes redundant after some time.
```csharp
public interface IAccountV3ResponseBuilder
{
    Task<LogInResultV3> LogInAsync(LogInCommandRequestV3 request);
    Task<CustomerInfoResultV3> InfoAsync(CustomerInfoCommandRequestV3 request);
    Task<LogOutResultV3> LogOutAsync(LogOutCommandRequestV3 request);
    Task<EncryptResultV3> EncryptAsync(EncryptRequestV3 request);
    Task<DecryptResultV3> DecryptAsync(DecryptRequestV3 request);
}
```

**Comment by HaloFour** [comment]
So don't call it `request`?  Call it `o`, or even `_`.

**Comment by DavidArno** [comment]
> So don't call it request? Call it `o`, or even `_`.

Or, taking the opposite approach, use more detailed names:
```cs
public interface IAccountV3ResponseBuilder
{
    Task<LogInResultV3> LogInAsync(LogInCommandRequestV3 loginCommandRequest);
    Task<CustomerInfoResultV3> InfoAsync(CustomerInfoCommandRequestV3 customerInfoCommandRequest);
    Task<LogOutResultV3> LogOutAsync(LogOutCommandRequestV3 logOutCommandRequest);
    Task<EncryptResultV3> EncryptAsync(EncryptRequestV3 encryptRequest);
    Task<DecryptResultV3> DecryptAsync(DecryptRequestV3 decryptRequest);
}
```

**Comment by jnm2** [comment]
@DavidArno 

> But it isn't being used in the implementation, thus giving it a name there serves no purpose.

Funny you mention this. I've moved in a direction where I consider it important to name unused parameters just to be absolutely clear about why it makes sense to be ignoring it.

**Comment by DavidArno** [comment]
> Now, these parameter names are the same as parameter type names

Aside from losing those ugly *V3*'s of course. 😃 

But it is a matter of style. I'd always go for the longer names, even if they do duplicate the type names. Others are happy with names like `request`, `x` or whatever.

I personally think that removing it completely is a step too far, but that is just opinion.

**Comment by theunrepentantgeek** [comment]
I know that this is just an example - but it's the only non-trivial use that's been provided as motivation so far.

That said, I look at this code:
```
public interface IAccountV3ResponseBuilder
{
    Task<LogInResultV3> LogInAsync(LogInCommandRequestV3 request);
    Task<CustomerInfoResultV3> InfoAsync(CustomerInfoCommandRequestV3 request);
    Task<LogOutResultV3> LogOutAsync(LogOutCommandRequestV3 request);
    Task<EncryptResultV3> EncryptAsync(EncryptRequestV3 request);
    Task<DecryptResultV3> DecryptAsync(DecryptRequestV3 request);
}
```
And, per the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle), I start to wonder if this interface represents a monolith that's doing too much.

I'd like to see another motivating example, one that shows how omission of the parameter name is clearly better, that doesn't have the baggage of this one.

**Comment by dsaf** [comment]
Variable name is just documentation though. What we really need is global and statically checked aliases for primitive types. Otherwise nobody bothers with a specific custom type unless there is more than one field.

**Comment by theunrepentantgeek** [comment]
@dsaf wrote

>  nobody bothers with a specific custom type unless there is more than one field.

Though it's a little off topic for this thread, I offer this proof by contradiction: Not only do I do this (regularly), [I've blogged](http://www.nichesoftware.co.nz/2016/05/27/semantic-types-in-csharp6.html) about the practice and [given presentations](http://www.nichesoftware.co.nz/presentations/semantic-and-immutable-types.html) on the topic as well.

**Comment by Richiban** [comment]
I'm not exactly sure this warrants a language change, but I do actually agree that there are many occasions where, in an interface, the parameter name is meaningless and adds nothing but noise. This is especially true when you're practising DDD (or, at least, avoiding primitive obsession):

```csharp
interface CustomerRepoitory
{
	Customer Get(CustomerId customerId);
}
```

There's no name I could give that parameter that would add any useful information that's not already there in the interface name, method name and parameter type name.

It looked a little odd at first, but I quickly grew to love F#'s interface syntax:

```fsharp
type CustomerRepoitory =
	abstract member Get: CustomerId -> Customer
```

That method declaration adds all the information you need: It's a method called `Get` that takes a `CustomerId` and returns a `Customer`. Unless you're using primitive types parameter names rarely end up being useful, except in method implementations where you obviously need to be able to refer to the value in the method body.

**Comment by yigitgursoy** [comment]
Closed due to negative feedback
