### ISSUE TITLE
Associative Arrays

### ISSUE THREAD

**Issue by Ayomi-kun** [dotnet/csharplang#1963]
Associative Arrays should be a feature added to the new c# release, as this help create a little more flexibility with the language and enabling developers build more while manipulating less data structures

**Comment by orthoxerox** [comment]
`Dictionary<TKey, TValue>` has been in the BCL since .Net 2.0.

**Comment by CyrusNajmabadi** [comment]
@willard720 Please be civil.

**Comment by YairHalberstadt** [comment]
Closing as it's not clear what exactly is being proposed here. If you want to discuss more, let me know and I'll move to a discussion.
