### ISSUE TITLE
Writing private attributes

### ISSUE THREAD

**Issue by srburton** [dotnet/csharplang#1965]
I've been noticing that the pattern may be incorrect I know that was already discussed this at the beginning of the language, plus I as a C# developer I have the right to question.

If C# follows a pattern  "Camel case " because when declaring an attribute to a class is in  "lower case "

Ex:
`Private readonly string _myString `

If we depart from the premise that the ' _ ' is a character then the writing should be 

ex:
`Private readonly string _MyString `

A confusing sense of why it was defined as  "lower case ".

**Comment by YairHalberstadt** [comment]
This is a style convention, and has nothing to with the language.

**Comment by srburton** [comment]
@YairHalberstadt 
Do you know what the C# convention GitHub is? To discuss on this subject

_"bing translator"_

**Comment by srburton** [comment]
Where can I put is issue a link from GitHub to the C# convention?

**Comment by YairHalberstadt** [comment]
It's a convention. It has no GitHub. Every developer/company/project can use their own.

You can change the settings in visual studio to start every private field with a capital if you want right now.

**Comment by DavidArno** [comment]
The official(?) docs at https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members are quite specific in the fact that the guidelines offer no opinion on private fields. Different folk have different opinions, largely governed by how much love or loathing one has for `this.`.

**Comment by DavidArno** [comment]
Oh and they are called fields, BTW. Not attributes. 😃

**Comment by gafter** [comment]
Closing as not a language issue.  Feel free to continue discussion here if you want.
