### ISSUE TITLE
[Proposal] allowing ref (readonly) when declaring casting operators

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#1973]
Currently if you do something like ...:

```csharp
if (DispatchManager?.IsPlaying ?? _DefaultValue)
{
    GameObject.DontDestroyOnLoad(this.gameObject);
}
```
... where IsPlaying returns a ref readonly boolean, the null conditional operator applied on DispatchManager, breaks the "ref-ness" of the IsPlaying getter.

Given that there is not allow to declare an expression like ...:

`if (ref DispatchManager?.IsPlaying ?? ref _DefaultValue) { ... }
`

... a way to bypass that is writing something like the following code:

```csharp
ref readonly var isPlaying = ref DispatchManager == null ? ref _Defaultvalue : ref DispatchManager.IsPlaying;

if (isPlaying)
{
   GameObject.DontDestroyOnLoad(this.gameObject);
}
```
Now, a similar situation occurs if you declare casting operators this way:

```csharp
public static implicit operator TData(BaseContainerClass<TData> container)
{
   return container?.Data; // where Data is a ref (readonly) getter.
}
```

Here you lose the benefit of the ref getter, even if you modify it like this:

```csharp
public static implicit operator TData(BaseContainerClass<TData> container)
{
   return container == null ? _DefaultData : container.Data;
}
```
Why? Because casting operators do not support ref (readonly) scenarios.

Thus, the proposal here is to allow coding something like:

```csharp
public static implicit ref readonly operator TData(BaseContainerClass<TData> container)
{
   return ref container == null ? ref _DefaultData : ref container.Data;
}
```

**Comment by MadsTorgersen** [comment]
How would the refness of a ref-returned implicit conversion result be utilized? Can you write a usage example to help clarify what kinds of scenarios this is for?

**Comment by svick** [comment]
@Ultrahead What is the point of using `ref readonly` to return a reference type? You're not going to avoid any copying by doing that.

**Comment by Ultrahead** [comment]
@svick: I'm coding by inertia :)

**Comment by Joe4evr** [comment]
> where `IsPlaying` returns a ref readonly boolean

Why do this in the first place? `ref (readonly)` returns are meant to be used to avoid copying of *large* structs. When used on pointer-sized-or-less structs, you're actually more likely to *decrease* the performance.

**Comment by Ultrahead** [comment]
Noted. Now focusing on the proposal it-self ...
