### ISSUE TITLE
Switch statement should be simplified by using commas to separate cases, using braces to drop the break statement and support types [c#]

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/csharplang#1977]
_From @jinujoseph on November 1, 2018 8:1_

[View developer community](https://developercommunity.visualstudio.com/content/idea/369109/switch-statement-should-be-simplified-by-using-com.html)

Use braces to enclose statements for each case and drop the break statement. 
Use comma to separate options for a single case. 
Automatically indent and align the cases, and statements. 
Add support for types inside switch statements.

	switch (e.Property.Name)
            {
                case nameof(Session.CurrentServer): 
                case nameof(Session.CurrentUser):   RebuildAll(); break;
                case nameof(Session.CurrentModule): RebuildModules(); break;
                case nameof(Session.CurrentEntity): RebuildEntity(); break;
            }
becomes

	switch (e.Property)
        case Session.CurrentServer,
             Session.CurrentUser    { RebuildAll(); }
        case Session.CurrentModule  { RebuildModules(); }
        case Session.CurrentEntity  { RebuildEntity(); }

_Copied from original issue: dotnet/roslyn#30897_

**Comment by jinujoseph** [comment]
_From @Neme12 on November 1, 2018 8:6_

@jinujoseph It looks like this is a request for a new language feature. I think it should be moved to https://github.com/dotnet/csharplang/

**Comment by DavidArno** [comment]
Part of #1054, *Open LDM Issues in Pattern-Matching*, captures the idea of allowing statement expressions in the new switch *expression*. (See #1558 for some more details), which would potentially allow you to write that as:
```cs
e.Property switch {
    Session.CurrentServer or Session.CurrentUser => RebuildAll(),
    Session.CurrentModule  => RebuildModules(),
    Session.CurrentEntity  => RebuildEntity(),
    _ => HandleDefaultCase();
};
```

There therefore seems little need or benefit to modifying the switch *statement*.

**Comment by willard720** [comment]
@DavidArno I like this syntax more, it's much more succinct, and doesn't have annoying braces for one line statements. 

Which, question, would we be able to do this:
 ```csharp
e.Property switch {
    Session.CurrentServer or Session.CurrentUser
   {
       RebuildAll();
       DoSomething();
    },
    Session.CurrentModule =>
    {
        RebuildModules();
        DoSomethingElse();
    },
    _ => HandleDefaultCase();
};
```

For multiline expressions, which syntax would work, if any?

**Comment by DavidArno** [comment]
@willard720,
> Which, question, would we be able to do this: …

No, that wouldn't be possible, as I understand the plans. You'd be restricted to using statement expressions, not blocks of code. In other words, if you can put it after an expression-bodied method, ie one with `=>`, then it can appear in a switch expression.

The likely solution would simply to wrap the likes of:
```cs
{
    RebuildAll();
    DoSomething();
}
```
in a local function. That local function can then appear in the switch expression.

**Comment by YairHalberstadt** [comment]
Closing this as all these suggestions (or equivalents) would be included in the championed proposal https://github.com/dotnet/csharplang/issues/3038
