### ISSUE TITLE
Question : Can I use just the generic parameter as return type of method or also a deduced type?

### ISSUE THREAD

**Issue by dotChris90** [dotnet/csharplang#1978]
Hello C# fans, 

just come up with a question about generics when
writing some code for numerical stuff. 

Image we have a generic class with 1 generic type parameter. 
The generic type can be any array or jagged array of numerical types
like double, etc.
The generic type shall be the type of a property called storage. 
This storage shall simple store an array.

Now I would like to allow indexing this generic class with storage property
and simple return the index of the storage. 
The C# compiler will forbid this because the element type double is a different class than the storage type (which is an array or jagged array)
but the return type of indexing method must be the element type. 

Now my question is : is there a way to solve this in C# world?
I was asking myself if generics just allow to use the generic type parameter
for return types or if I can use also 
a deduced type like the element type?

Honestly spoken I think the CLR should be capable of this because all important stuff is also known on compilation time.

**Comment by Joe4evr** [comment]
I'm not sure what you're asking for. Do you want to return an array of the type `T`? If so, just do exactly that:
```cs
public class MyClass<T>
{
    public T[] GetStorage() => _storageField;
}
```

**Comment by YairHalberstadt** [comment]
```csharp
public class NewArray<TList, TElement>  where T : IList<TElement>
    {
        protected TList _Storage;

        public TElement this[int i]
        {
            get
            {
                return _Storage[i];
            }

            set
            {
                _Storage[i] = value;
            }
        }
    }
```

**Comment by zippec** [comment]
@YairHalberstadt When they have a follow up (like proposal how to lift that limitation) I would agree.

That aside, if You combine what Yair suggested with #1349 you could end up with almost what you want
`var A = new NewArray<double[][], >(); // this for a 2D Storage.`

**Comment by dotChris90** [comment]
Thanks to all for the reply. 

At end I come up with storage any array (1D,2D Matrix, 3D Tensor, ...) in a single 1D array and store the shape of the storage e.g. int[] {5} or int[] {2 4}. 

So my problem is solved but I just want to ask the following about the language C#. 
Why A method of a generic class can return an array of the generic parameter but not vice versa?

So why generics are limited in this way? So a class NewArray<T> can have methods return T[]? But why we can not have a NewArray<TArray> where TArray is a generic parameter implementing all interfaces of an array but there is no way in C# to return typeof(TArray[0]) .... so the element type of an array. 

I was just wondering and just want to thank all who answered. @YairHalberstadt @zippec thanks for your suggests. 

My problem is solved and you can decide to close this issue or not. :)

**Comment by Joe4evr** [comment]
> (1D,2D Matrix, 3D Tensor, ...)

Now see, if you told us this was your end goal *from the start*, we could've pointed out that [there are already dedicated APIs for this in the works](https://github.com/dotnet/corefx/issues/25779).

When asking for help, it's always better to say what your end goal is [instead of what you think the solution should be](http://xyproblem.info/).

**Comment by dotChris90** [comment]
Ok understand. Sorry for making confusion >. <
