### ISSUE TITLE
Allow type pattern matching to have multiple expression bind to the same variable

### ISSUE THREAD

**Issue by lostmsu** [dotnet/csharplang#1980]
Excerpt from own Roslyn-based code:
```csharp
switch(...) {
...
case var _ when defaultValue is LambdaExpressionSyntax lambda:
case var _ when defaultValue is ParenthesizedExpressionSyntax parenthesized
        && (lambda = parenthesized.Expression as LambdaExpressionSyntax) != null:
  ...
  break;
}
```

Should be able to do:
```csharp
switch(...) {
...
case var _ when defaultValue is LambdaExpressionSyntax lambda:
case var _ when defaultValue is ParenthesizedExpressionSyntax parenthesized
         && parenthesized.Expression is LambdaExpressionSyntax lambda:
  ...
  break;
}
```

Basically, in `expr is Type variable` why can't `variable` be any existing variable of a matching type (e.g. assignable from `Type`). I'd even be ok with `expr is Type out variable`, as long as I don't have to do the `(... = ... as ...) != null`

**Comment by alrz** [comment]
Relates to https://github.com/dotnet/csharplang/issues/118, https://github.com/dotnet/csharplang/issues/1350

**Comment by lostmsu** [comment]
Now I realize this should not be limited to `switch` statements. It should be possible to do it in any expression/statement.
E.g. `success = other is XXX xxx || other is YYY yyy && yyy.Val is XXX xxx;`

**Comment by HaloFour** [comment]
@lostmsu 

Because the use of `||` with patterns already means something else.  This is discussed in more detail in the issues that @alrz posted.

**Comment by lostmsu** [comment]
@HaloFour my understanding is that `or` in above is a special syntax to replaces `case 1: case 2:` with `case 1 or 2:`, and does not have anything to do with type testing pattern matching.

**Comment by HaloFour** [comment]
@lostmsu 

> and does not have anything to do with type testing pattern matching.

Those "type tests" are just a very limited form of pattern, just like those constant patterns.  C# 8.0 will greatly expand on the types of supported patterns, including recursive patterns, and `or` will be a way to combine patterns.  Rewriting your example with recursive property patterns and `or` patterns might look like this:

```cs
success = other is XXX xxx or YYY { Val: XXX xxx };
```

**Comment by YairHalberstadt** [comment]
Closing as championed in https://github.com/dotnet/csharplang/issues/4018
