### ISSUE TITLE
nameof should be available before the variable is declared

### ISSUE THREAD

**Issue by datvm** [dotnet/csharplang#1983]
I think it is an oversight of Visual Studio, not sure if I should post here. Basically, if I write a line like this:

`var output = multipartReader.Values[nameof(output)];`

I will receive the error:

> Cannot use local variable 'output' before it is declared

I understand why, but in this case, `nameof` is a pre-compile directive and it should make perfect sense. I think it should be valid.

**Comment by YairHalberstadt** [comment]
It also doesn't work on sharplab, so it looks like a genuine limitation of Roslyn. I would consider posting this on the Roslyn repo, because it sounds like the sort of thing that could well be a bug.

**Comment by alrz** [comment]
I recall this has been brought up in a design note so it is by design.

Try an explicitly type for `output`, like `object output = ...`

**Comment by datvm** [comment]
@alrz Thanks, it works when using explicit type. Weird though.

**Comment by datvm** [comment]
@YairHalberstadt Thanks, didn't know which is the proper repository to post this. Seem like it's by design. Should I post this on Roslyn now?

**Comment by alrz** [comment]
Relevant notes:  https://github.com/dotnet/csharplang/blob/98043cdc889303d956d540d7ab3bc4f5044a9d3b/meetings/2015/LDM-2015-03-04.md

**Comment by datvm** [comment]
@alrz Thanks, that makes sense. Will close this.
