### ISSUE TITLE
Impossible boxing/unboxing conversions

### ISSUE THREAD

**Issue by LouisFr81** [dotnet/csharplang#199]
In the chapters about boxing and unboxing conversions, it is told the following:

> A value type has a boxing conversion to an interface type  I  if it has a boxing conversion to an interface or delegate type  I0  and  I0  is variance-convertible (Variance conversion) to  I .

and

> A value type  S  has an unboxing conversion from an interface type  I  if it has an unboxing conversion from an interface or delegate type  I0  and either  I0  is variance-convertible to  I  or  I  is variance-convertible to  I0  (Variance conversion).

While those sentences are logically true, they seem to tell there are such things as boxing to a delegate or variance-convertion from delegate to interface.

This was mentioned by Eric Lippert in details on his blog two years ago : https://ericlippert.com/2015/05/26/a-different-copy-paste-error/

**Comment by gafter** [comment]
Sounds like it may be a spec bug.

**Comment by gafter** [comment]
See https://github.com/dotnet/csharplang/pull/76 for a proposed spec fix.

**Comment by BillWagner** [comment]
The incorrect text is not in the standard in dotnet/csharpstandard.

Closing.
