### ISSUE TITLE
Proposal: Generic Argument Wildcards

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#1992]
**IMPORTANT:** This proposal is very different than Java wildcards in terms of its implementation and behavior. It looks similar on the surface but it's a much more elegant solution than extending variance. It follows all existing variance rules and takes advantage of the CLR generic type system to transform the block of code using the unknown type into a generic method that is JITed to use the ACTUAL types of the generic parameters. "Extracted" types can therefore be safely used just like any other generic parameter and everything is compile-time verified so you can't do something wacky like try to pass an `object` into a method that takes a `string` without getting a compiler error.

**Details:**

I've run into many situations where this would be extremely useful but I'll give a couple to start things off:

**A) Eliminate the need for a non-generic interface in addition to a suitable generic interface**

It would help avoid the giant mess often created when generic types need to inherit non-generic versions of the same type in order to be usable when the generic type argument is unknown, and if implemented in an ideal manner where the JIT would emit different versions of the method as needed then it would also eliminate boxing in lots of situations.

Hypothetical example - non-generic `IEnumerable` interface would no longer be needed:

```c#
void IterateIfPossible(object obj)
{
    if (obj is IEnumerable<?> items) 
    {
        foreach (var item in items)
            Console.WriteLine(item);
    }
}
```

This would remove the need to implement a non-generic interface with a bunch of methods that just cast the generic argument typed return value/parameter to `object`.

In this case `var` would be treated as an anonymous generic parameter. The next example shows how to extract that parameter so it can be used like any other generic parameter.

**B) Allow extraction of the unknown type:**

```c#
void Type GetItemType(IEnumerable obj)
{
    if (obj is IEnumerable<?T>) 
    {
        return typeof(T);
    }
    return typeof(object);
}
```

**C) Test if an object inherits a generic type or implements a generic interface and if so use the value in its strongly typed form:**

I don't believe there is currently any way to avoid very messy and slow reflection code to test if an object implements, say, `IList<T>`, and if so then pass it to a method that requires an `IList<T>`. In order to do this:

```c#
private IItemsProcessor GetItemsProcessor(object items)
{
    // Optimize for List<T>
    if (items is List<?T> list)                
        return new ListProcessor<T>(list);

    if (items is IEnumerable<?T> enumerable)
        return new EnumerableProcessor<T>(enumerable);
}
```

I currently have to do this:

```c#
private IItemsProcessor GetItemsProcessor(object items)
{
    var itemsType = items.GetType();
    // GetBaseTypes() is an extension method
    var listType = itemsType.GetBaseTypes().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(List<>));

    // Optimize for indexable collections
    if (listType != null) 
    {
        var itemType = listType.GetGenericArguments()[0];
        var processorType = typeof(ListProcessor<>).MakeGenericType(itemType);

        return (IItemsProcessor)Activator.CreateInstance(processorType, items);
    }

    var enumerableType = itemsType.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));

    if (enumerableType != null)
    {
        var itemType = listType.GetGenericArguments()[0];
        var processorType = typeof(EnumerableProcessor<>).MakeGenericType(itemType);

        return (IItemsProcessor)Activator.CreateInstance(processorType, items);
    }
}
```

**D) Allow generic constraints:**

```c#
void GetDisplayValue(Control control)
{
    if (control is LabelControl<?T> label where T : IDisplay) 
    {
        // LabelControl.Value is a property of type T
        // GetDisplayText() is a method on IDisplay
        return label.Value.GetDisplayText(); 
    }
}
```
This would let you avoid a lot of potential casting and allow method overload resolution to use methods that have compatible constraints on their generic parameters when the unknown value is passed in:

```c#
void Serialize<T>(Field<T> field) where T : class
{
    Serializer.Serialize<T>(field);
}

// ERROR: can't differentiate just on generic constraints
void Serialize<T>(Field<T> field) where T : struct
{
    // But I need to be able to call a method with a T : struct constraint!
    Serializer.FastSerializeValueType<T>(field);
}

// But this would work:

void Serialize(Field field)
{
    if (field is Field<?TValue> valueField where TValue : struct)
    {
        Serializer.FastSerializeValueType<TValue>(field);
    }
    else if (field is Field<?TRef> refField where TRef : class)
    {
        Serializer.Serialize<TRef>(field);
    }
}
```

---------------

**Implementation**

This is a simple demonstration of a roughly equivalent code transform that could be applied to the last example by the compiler to make it work:

```c#
void Serialize<T>(Field field)
{
    try 
    {
        Serialize_struct((dynamic)field);
        return;
    }
    catch (RuntimeBinderException) { } 

    try 
    {
        Serialize_class((dynamic)field);
    }
    catch (RuntimeBinderException) { }   
}

void Serialize_struct<T>(Field<T> field) where T : struct
{
    Serializer.FastSerializeValueType<T>(field);
}

void Serialize_class<T>(Field<T> field) where T : class
{
    Serializer.Serialize<T>(field);
}
```
Dynamic is quite quick here but the dynamic callsite code it outputs could definitely be optimized more (i.e. cutting out the overhead of the try/catch). There may be other optimizations that apply for this specific situation (known single method to call, only varies by generic parameters).

If there are any CLR enhancements that can make it a bit quicker but those can just be stubbed in by newer runtimes. Even without any CLR changes this can be very fast using the existing dynamic features in the runtime.

**Comment by HaloFour** [comment]
This only works in Java as the generic type arguments don't exist at runtime.  The JRE only recognizes the type `Iterable`, it is entirely unaware of whether it was `Iterable<String>` or `Iterable<Integer>` or `Iterable<?>`.  In the CLR that is not the case.  The generic type arguments are reified into the actual type, so `IEnumerable<string>` and `IEnumerable<int>` are entirely different and incompatible types.

I will agree that the reflection APIs in the BCL leave a lot to be desired when it comes to generics.  I've advocated for better APIs here: https://github.com/dotnet/corefx/issues/644

**Comment by ufcpp** [comment]
non-generic IEnumerable interface is not needed:

```cs
using System;
using System.Collections.Generic;

public class Program
{
    static void Main()
    {
        Console.WriteLine(IsEnumerable(new string[1])); // true
        Console.WriteLine(IsEnumerable(new Program[1])); // true
        Console.WriteLine(IsEnumerable(new List<string>())); // true
        Console.WriteLine(IsEnumerable(new List<Program>())); // true
    }

    static bool IsEnumerable(object obj) => obj is IEnumerable<object> items;
}
```

**Comment by mikernet** [comment]
@HaloFour There are definitely ways to implement this on the CLR. I don't have time right this second to articulate the implementation, but it would obviously require runtime support not just compiler support.

**Comment by mikernet** [comment]
@ufcpp In addition to what HaloFour pointed out, there's also the issue of input parameters. That only works with IEnumerable because it's `<out T>`.

**Comment by mikernet** [comment]
@HaloFour I'm pointing to Java as an example of a similar feature. Regardless of how or why it works on Java, there are ways to make this work cleanly on the CLR as well. When I have a bit more time later today or tomorrow I'll follow up with a demonstration of how it could be done.

**Comment by mikernet** [comment]
@ufcpp That only works in that particular case because the generic part of IEnumerable is defined as `<out T>`. Try that with an interface without the `out` part :)

IEnumerable was, as I stated, a hypothetical example. Sadly I doubt IEnumerable and the mess of other collection interfaces is going anywhere anytime soon, but my framework would benefit immensely from this.

**Comment by HaloFour** [comment]
@mikernet 

> I'm pointing to Java as an example of a similar feature. Regardless of how or why it works on Java

The how is important.  The Java language has this ability specifically because of how generics work in that language.  C# can't work around the variance limitations very intentionally imposed by the CLR.  Nor should it.

> there are ways to make this work cleanly on the CLR as well. 

Possibly, but it's exceptionally difficult to justify CLR modifications to support a language change unless the benefit is absolutely enormous and it can't be solved any other way.  This is especially true given that it seems that the .NET Framework will never see such modifications.

**Comment by mikernet** [comment]
@HaloFour I think eliminating the need for redundant non-generic interfaces in 99% of situations where they are currently needed would be a huge win. That's obviously subjective. There are ways to make this work fairly well without CLR cooperation but optimally it would cooperate a bit. Wildcard generic arguments would be useful for more than just C#. Regardless, I presume the runtime isn't doomed to never evolve out of its current state for all eternity just because the .NET Framework isn't evolving anymore. That would be kind of silly.

I never suggested C# should work around the variance limitations imposed by the CLR. I don't think anything I've suggested conceptually requires breaking any variance rules.

I'll go into more detail about potential ways to implement this soon.

**Comment by mikernet** [comment]
@HaloFour Updated my post with a simple implementation to demonstrate viability. I'll play around with ways to optimize this further on an IL level when I have more time.

**Comment by svick** [comment]
if the `dynamic`-based implementation is acceptable, then I'm not sure this feature is needed, because I think this code:

```c#
void IterateIfPossible(object obj)
{
    if (obj is IEnumerable<?T> items where T : IFriendlyDisplay) 
    {
        foreach (T item in items)
            Console.WriteLine($"'{item.FriendlyDisplayText}' is type '{typeof(T)}'");
    }
}
```

is not that much better than this code, which works today:

```c#
void IterateIfPossible(object obj) => IterateIfPossibleImpl((dynamic)obj);

void IterateIfPossibleImpl<T>(IEnumerable<T> items) where T : IFriendlyDisplay
{
    foreach (T item in items)
        Console.WriteLine($"'{item.FriendlyDisplayText}' is type '{typeof(T)}'");
}

void IterateIfPossibleImpl(object _) { }

```

**Comment by mikernet** [comment]
@svick I tend to disagree that it's not much better. That example is rather simple and doesn't require capturing locals between any of the methods and only has a single unknown type with a single unknown parameter, doesn't handle mismatched constraints, etc. This gets very messy very quickly and the alternate pattern is rather obtuse, I can't imagine very many people adopting it, especially for more complicated flows. I can give you some examples if you would like.

The alternate syntax I'm proposing is terse, simple, easily understood and would encourage people to use what I would argue is a much better design that avoids writing redundant non-generic interfaces where they aren't needed.

**Comment by mikernet** [comment]
Here's an example of one more common problem that this transformation could solve nice and cleanly. Granted it doesn't require the wildcard, but there's no reason we couldn't allow the constraint syntax without wildcards since the transformation would work in this case as well:

        void DoSomething<T>(IEnumerable<T> items) where T : class
        {
            // ...
        }

        // ERROR: can't differentiate just on generic constraints
        void DoSomething<T>(IEnumerable<T> items) where T : struct
        {
            // ...
        }

        // But this would work:

        void DoSomething<T>(IEnumerable<T> items)
        {
            if (items is IEnumerable<T> valueItems where T : struct)
            {
                // do something with value type items
                return;
            }

            // do something with reference type items
        }

**Comment by mikernet** [comment]
@svick P.S. your version of the transform which eliminates the type checking line is for all intents and purposes just as fast as the non-generic code with only a single item in my test. This tells me that an optimized implementation could be effectively indistinguishable in performance vs using non-generic interfaces.

**Comment by mikernet** [comment]
One last point before I dip out for a while.

This would fundamentally change how generic interface hierarchies are designed in a lot of cases, eliminating a lot of necessary redundancy and casting boilerplate which propagates throughout some massive class and interface hierarchies. That seems like a much more meaningful proposal than all this pattern matching stuff yet it seems like we are getting pattern matching so I don't understand the negativity towards this. It seems to be this would have wider reaching improvements than pattern matching and the workarounds are more complicated than the workarounds for achieving what pattern matching does so I really don't see why this wouldn't be strongly considered.

**Comment by svick** [comment]
@mikernet I'm not convinced that this is as big a problem as you make it out to be. Sure, a non-generic version of a generic interface is sometimes useful, but creating and using them doesn't require that much boilerplate code (and it will be even less with default interface methods https://github.com/dotnet/csharplang/issues/52).

If you actually need type parameter extraction, then that is harder to do, but I'm not sure that's actually common.

As for negativity, I think that most proposals here will receive a negative initial reaction. If you want to have the proposal to progresses further, it's up to you to convince us, or rather, someone from the Language Design Committee, that it's a change worth making.

**Comment by mikernet** [comment]
Fair enough regarding the convincing, haha. Default interface implementations are an orthogonal issue to this  - we can't create a default non-generic interface implementation that somehow forwards the calls to the unknown generic interface method, so it does nothing to solve this problem.

I think this is a perfect extension to the pattern matching work going on (and could probably help with making that even more powerful) and solves problems and design tradeoffs that I literally face every day building performance critical "lower level" library/framework code.

Even if it's not a big deal (which I disagree about), either is declaring a variable before you use it for an `out` parameter or 90% of the other things being added to make programmer's lives easier.

I'll give you an example of some code in my library. I have a bunch of field types, and this is the hierarchy:

```c#
⋄Field
   ⋄ComputedField
      ⋄ComputedField<T>
   ⋄ReferenceField
      ⋄ReferenceField<T>
   ⋄StreamField
   ⋄TypeConstantField
      ⋄TypeConstantField<T>
   ⋄ValueField
      ⋄ValueField<T>
   ⋄ValueFieldList
      ⋄ValueFieldList<T>
```

All the non-generic types (except for Field and StreamField) along with their associated abstract method definitions and overrides in the generic versions would go away if I could just say `if (field is ValueField<?T> valueField)` instead of having to do `if (field is ValueField valueField)` and then using abstract calls that do casting and all sorts of nasty boilerplate to work. It would probably cut the total number of lines in those files by half and make it way easier to reason about what is going on by eliminating the need to jump around between abstract method implementations in the generic type and common functionality in the base type when it could all be contained in the generic type. Lots of abstract method calls would be avoided as well as casting and boxing.

**Comment by mikernet** [comment]
The particular example above is an especially good one for the following reason: the design of the above classes is exponentially complicated because the hierarchy can't just go `Field - Field<T> - [all the field types]`. I can't have a base `Field<T>` because I can't inherit a non-generic `ValueField` from that generic type, and I need the non-generic type to do things common to value fields. Likewise I can't have a generic base class `EntityCollectionField<T>` that does all common collection things on `T` because I need to have a non-generic `EntityListField` type to support operations on `EntityListField<T>`.

If the language feature I'm proposing was available, the above hierarchy would simplify down to this:

```c#
⋄Field
   ⋄StreamField
   ⋄Field<T>
      ⋄ComputedField<T>
      ⋄EntityCollectionField<T>
         ⋄EntityListField<T>
         ⋄EntitySetField<T>
         ⋄EntityField<T>   
      ⋄TypeConstantField<T>
      ⋄ValueField<T>
      ⋄ValueFieldList<T>
```

If I need to do operations on any `EntityListField<T>` I can just do so directly without needing a base `EntityListField` class that declares a bunch of abstract members that only `EntityListField<T>` implements, does a bunch of casting and conversions and other annoying and useless stuff to make everything work, and splits very tightly coupled logic into two separate classes.

The amount of boilerplate code and error prone inheritance (which requires significant additional testing as well) that this would cut down on would be huge. Even more important than just cutting down boilerplate is how much easier the code would be to understand without the giant inheritance mess. Turning all the code in these classes into a flustercuck by "manually" transforming it into the format you suggested as an alternative that works now would be ludicrous and impossible to follow for anyone.

Because of the way I would be able to organize code with this proposal, most of the situations where I *really* wish I had multiple inheritance would also go away.

There are just so many benefits to this.

**Comment by mikernet** [comment]
Is that a more suitable example to demonstrate why I ***really*** want this? Haha

**Comment by gafter** [comment]
I wonder if [the people who introduced Wildcards to Java](https://dl.acm.org/citation.cfm?id=968162) think that exercise should be repeated for C#.

**Comment by HaloFour** [comment]
@gafter 

> I wonder if the people who introduced Wildcards to Java think that exercise should be repeated for C#.

That might depend on whether or not you patented it.  😁

**Comment by mikernet** [comment]
@gafter I don't follow :confused: Care to elaborate?

**Comment by mikernet** [comment]
@gafter Are you genuinely asking if they might have some input or are you making that statement tongue-in-cheek? I can't tell :laughing:

**Comment by YairHalberstadt** [comment]
@mikernet.
Take a look at the authors of that paper...

**Comment by mikernet** [comment]
@gafter Alright well, what do the people who added it to Java think?

**Comment by mikernet** [comment]
@HaloFour I definitely got that now, that's why I asked him what they think :)

**Comment by gafter** [comment]
I think declaration-site variance (i.e. `in` and `out` on the declaration of interface type parameters) is superior to use-site variance (i.e. wildcards), and having variance at both the declaration site and at the use site would be even worse.

**Comment by mikernet** [comment]
@gafter Why? I don't see how `in`/`out` help me do any of the above.

**Comment by mikernet** [comment]
It also only works on interfaces :/

**Comment by huoyaoyuan** [comment]
Everything is boxed in Java's generics. So if you use reference type only, you can get most functionalities via `in` and `out`.

**Comment by mikernet** [comment]
@huoyaoyuan I'm not sure what you're saying, can you clarify please? If you look at my proposed implementation here, nothing gets boxed so I'm not sure how Java's implementation is relevant. I can't get the most functionality via `in` / `out` with reference types because I need to support basic value types in my interfaces.

**Comment by ufcpp** [comment]
@mikernet 
ValueType can't share generic instantiation. So, ValueType can't be variant regardless whether declaration-site or use-site.

**Comment by mikernet** [comment]
@ufcpp As I've said many times already, I know. What does that have to do with this proposal?

@gafter @ufcpp I think it's important to distinguish my proposal from the Java implementation. This is similar in some respects on the face of it, but completely different than what Java has. It doesn't require any changes to variance rules, works within the current CLR type system and is completely type safe. The wildcard isn't an `object` variant of the generic type parameter...it's a strongly typed anonymous generic parameter extracted from the type. I think my sample implementation makes that very clear.

This is basically just supporting one more level of dynamic dispatch as it applies to generics.

**Comment by mikernet** [comment]
I'll say this one more time so it's clear - this proposal has nothing to do with variance. It's not modifying any variance rules. It is taking advantage of the C# generic type system to dispatch to the appropriate generic method that handles the wildcard/extracted type parameter in its native type form.

**Comment by mikernet** [comment]
I think the "Java has a similar feature" opening line is throwing everyone off...so I've updated the original post to better reflect what this proposal actually is.

**Comment by mikernet** [comment]
Please carefully review the example implementation at the bottom of the first post to understand how variance does not come into play here.

**Comment by zippec** [comment]
@mikernet How do You propose it should work when type implements generic interface multiple times?
```C#
class MultipleEnumerable : IEnumerable<string>, IEnumerable<int> { ... }
...
var obj = new MultipleEnumerable()
if (obj is IEnumerable<?T>) 
    {
        return typeof(T); //what does it return?
    }
```

**Comment by mikernet** [comment]
@zippec Probably the same way dynamic works now in the same situation / how method overload resolution works when trying to match it to a method - throw error "The type arguments cannot be inferred from the usage."
--

**Comment by mikernet** [comment]
Or simply pass over it so that you don't have to worry about exceptions being thrown? That probably makes more sense. I don't know - I'm open to whatever, I think this situation is exceedingly rare.

**Comment by jnm2** [comment]
@zippec Good point. This is logically a `foreach` kind of operation, not an `if` kind of operation. This could be glossed over, but should it be?

**Comment by mikernet** [comment]
Given that doing this causes all sorts of problems in lots of situations, I don't think anyone ever actually does this, and if they do then they can expect wacky behavior all over the place. Personally, I don't think allowing a type to implement the same generic interface multiple times with different type parameters should have ever been allowed but hey here we are, so whatever behavior is standardized here is fine by me.

I don't think throwing an error is appropriate because you are logically just asking "can I use the object as this type", and that operation should never really throw an error. Either just pick the first matching interface that works, or don't match and pass over it.

Mind you this is different than this situation:

```c#
class SingleEnumerable : IEnumerable<string> { ... }
class MultipleEnumerable : SingleEnumerable, IEnumerable<int> { ... }

var obj = new MultipleEnumerable()
if (obj is IEnumerable<?T>) 
    {
        return typeof(T); //what does it return?
    }
```

In that case obviously just return `int`.

**Comment by mikernet** [comment]
```c#
IEnumerable<Type> GetEnumerableTypes(IEnumerable collection)
{
    foreach (IEnumerable<?T> items in obj)
    {
        Console.WriteLine(items.Count());
        yield return typeof(T);
    }
}
```
:rofl: :rofl: :rofl:

**Comment by VanKrock** [comment]
```csharp
        void Iterate<T>(IEnumerable<T> items)
        {
            if (typeof(T).IsClass || typeof(T).IsInterface)
            {
                foreach (var item in items)
                {
                    Console.WriteLine($"{item} : class or interface");
                }
            }
            else
            {
                foreach (var item in items)
                {
                    Console.WriteLine($"{item} : class or interface");
                }
            }
        }

        void Iterate<T>(object items)
        {
            //Anything else
        }
```

**Comment by mikernet** [comment]
@VanKrock You didn't explain what you're trying to show and I can't tell from your code.

**Comment by Thaina** [comment]
@HaloFour @gafter Sorry for digging up old post and this might not be related, but I think I have seen issue that might be related, about complex generic inference

Currently now we might write complex generic like this

```C#
public IEnumerable<T> Flatten<E,T>(E items) where E : IEnumerable<T>
{
}

// Currently now error : cannot be inferred from the usage
object[][] objs;
var flatten = Flatten(objs);
```

I have seen proposal that said it was solve error above. I cannot find it anymore but I think it might also solve this issue too

**Comment by mikernet** [comment]
@Thaina That would be a very nice solution to many (but unfortunately not all) of the use cases presented, especially if it could be used in local functions, and probably has a much higher chance of actually being implemented. If someone could point to that proposal so I can upvote it that would be great :)

**Comment by gafter** [comment]
https://github.com/dotnet/csharplang/issues/3271

**Comment by Thaina** [comment]
@gafter Thank you very much. But actually I think I have been seen this idea a lot more older. Maybe it was just a discussion, or all the way since roslyn

Mention roslyn make me remember I could find it in roslyn

https://github.com/dotnet/roslyn/issues/5023
https://github.com/dotnet/roslyn/issues/15166
