### ISSUE TITLE
Proposal: Allow internal interfaces to implicitly use internal methods for implementation

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#1994]
As the title suggests, loosen the restrictions around internal interfaces so that this works:

```c#
internal interface IInternalInterface
{
    void Method();
}

public class Class : IInternalInterface
{
    internal void Method() { }
}
```
This would allow less boilerplate for these situations and help avoid the quirks that result from using explicit interface implementations.

Are there any negative side effects I haven't considered? From what I can tell it's a non-breaking change that only makes sense but I welcome any discussion as to why it's a bad idea.

**Comment by YairHalberstadt** [comment]
I believe that DIM will include this?

**Comment by yaakov-h** [comment]
How would this be covered by DIM?

**Comment by YairHalberstadt** [comment]
From the proposal:

Modifiers in interfaces
The syntax for an interface is relaxed to permit modifiers on its members. The following are permitted: private, protected, internal, public, virtual, abstract, override, sealed, static, extern.

TODO: check what other modifiers exist.

An interface member whose declaration includes a body is a virtual member unless the sealed or private modifier is used. The virtual modifier may be used on a function member that would otherwise be implicitly virtual. Similarly, although abstract is the default on interface members without bodies, that modifier may be given explicitly. A non-virtual member may be declared using the sealed keyword.

It is an error for a private or sealed function member of an interface to have no body. A private function member may not have the modifier sealed.

Access modifiers may be used on interface members of all kinds of members that are permitted. The access level public is the default but it may be given explicitly.

Open Issue: We need to specify the precise meaning of the access modifiers such as protected and internal, and which declarations do and do not override them (in a derived interface) or implement them (in a class that implements the interface).

**Comment by yaakov-h** [comment]
I believe that only describes members of the interface itself, i.e.

```csharp
internal interface IInterface
{
    internal void Method() { }
}
```

It wouldn't allow an `internal` method on an implementation to satisfy a [default-]public interface member.

**Comment by YairHalberstadt** [comment]
But given that this is only relevant for internal interfaces, you can just specify internal on the interface itself.

**Comment by willard720** [comment]
I feel like this will get denied for the same reason that implicit `static` on `static` classes was denied.

**Comment by mikernet** [comment]
@willard720 I don't follow. Public methods can implicitly implement public interface methods. What does implicit `static` in static classes have to do with mirroring this behavior for internal methods implicitly implementing internal interface methods?

**Comment by ufcpp** [comment]
I feel like explicit interface implementation is just enough

**Comment by HaloFour** [comment]
Internal implementations are legal in VB.NET, although not implicitly:

```vb
Imports System

Public Class C 
    Implements IDisposable

    Friend Sub Dispose() Implements IDisposable.Dispose
    End Sub
End Class
```

**Comment by mikernet** [comment]
@ufcpp I don't really know what "feels like just enough" is really supposed to mean. What feels right is that an internal method can implicitly implement an internal interface and I fail to see any downside to allowing this. Care to explain what about that feels like it goes too far? Seems entirely reasonable to me.

**Comment by yaakov-h** [comment]
> to be directly called from outside the assembly 

The interface itself is internal, so this could not occur.

**Comment by mikernet** [comment]
@theunrepentantgeek If you haven't encountered it before then you haven't used internal interfaces very much before :man_shrugging: I found that it's pretty common when writing library code that doesn't just have everything hanging out in public.

**Comment by mikernet** [comment]
@theunrepentantgeek 
> Other simple changes have adopted because the benefit was extensive.

And other simple changes have been adopted because they are just really easy changes to make that just make sense.

**Comment by DarthVella** [comment]
There'd be an edge case in interface inheritance.

```csharp
public interface A
{
    void MethodA();
}

internal interface B : A
{
    void MethodA(); //public? internal?
}
```

Personally, I would expect any class implementing B.MethodA to require it to be public.

**Comment by mikernet** [comment]
@DarthVella I don't know if this is an issue. They are treated as separate interfaces, so if there's an internal method that satisfies `B.MethodA()` then that would be implicitly mapped and not cause an error, but it would still throw an error that `A.MethodA()` has not been implemented.

**Comment by yaakov-h** [comment]
@DarthVella That would have to keep it's current behaviour for backwards compatibility - it would introduce a new method `B.MethodA()` that hides/shadows `A.MethodA()`.

**Comment by gafter** [comment]
This would be a breaking change (i.e. change the behavior of existing code) for code like this

``` c#
internal interface IInternalInterface
{
    void Method();
}
public class Base : IInternalInterface
{
    void IInternalInterface.M() { }
}
public class Class : Base, IInternalInterface
{
    // In C# 7, this did not implement IInternalInterface.M.
    // With the proposed change, it would.
    internal void M() { }
}
```

Because this proposal would break compatibility for very little benefit, it is not something we would consider.

**Comment by mikernet** [comment]
@gafter Fair enough. As part of DIM and allowing access modifiers on members, is this being considered for abstract interface members marked as internal? It wouldn't be a breaking change in that situation.

**Comment by gafter** [comment]
Correction: we do not support implicit implementation for any but public interface methods.

**Comment by alrz** [comment]
I think this can't be a breaking change:
```cs
internal interface IInternalInterface
{
    internal void Method(); // explicit restrictive modifier
}

public class Class : IInternalInterface
{
    internal void Method() { }
}
```
