### ISSUE TITLE
Proposal: syntax for "global" static fields inside a generic class

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#1995]
There should be syntax available to define a static field inside a generic class such that every closed generic type doesn't point to a different field. Put another way, there should be a way to define a static field that is shared between all instances of that generic class.

The Problem:

```c#
public class List<T> : Collection<T>
{
    private static readonly Dictionary<object, object> _globalCache = new Dictionary<object, object>();

    // ... rest of implementation
}
```

`List<int>` will have a different `_globalCache` than `List<string>`. The only real workaround is to make another non-generic static class and open up the members as `internal`, but that breaks encapsulation and also opens up `_globalCache` to be accessed from other classes inside the assembly, which is not desirable in many cases.

Given that we already have the `[ThreadStatic]` attribute which is kind of in the same category in terms of how it modifies static field behavior then one option is to add a `[GlobalStatic]` attribute.

The downside I see to an attribute vs a keyword is that a keyword could potentially also be applied to a static constructor or static methods to allow for initialization of "global static" members. Perhaps a contextual `global` keyword could be added that worked like so:

```c#
public class List<T> : Collection<T>
{
    private global static readonly Dictionary<object, object> _globalCache;
    private global static readonly int _someVar = InitSomeVar();

    global static List()
    {
        _globalCache = new Dictionary<object, object>();
        // populate cache with intial values...
    }

    private global static int InitSomeVar() => 5;
}
```

My initial thoughts on how this would actually work is that anything marked `global static` would just be moved into a separate anonymous internal static class with internal access modifiers on its members. I think constraining it so that it only supports `private` access modifiers on the original declaration makes the most sense, that way only the declaring class and its nested classes have access to it because otherwise accessing it would be awkward and unintuitive from outside the class anyway without adding more specialized syntax like `List<>.SomePublicMember` which I don't think would really add a lot of value.

**Comment by HaloFour** [comment]
How often does this come up that the mentioned workaround isn't suitable?

**Comment by mikernet** [comment]
Often enough that I took the time to write this. It's just messy and I prefer my OOP languages to properly support OOP principles like encapsulation. Even in the case where the type doesn't inherit from another generic type it would still be much nicer to have everything contained in the same class instead of declaring another unnecessary class just to hold some static fields.

**Comment by mikernet** [comment]
I've been doing a ***lot*** of very generic-heavy and caching heavy programming in the last year so this has come up surprisingly often :)

**Comment by mikernet** [comment]
Hmmm...without `static` it might be tricky to make this a non-breaking change in the event that someone has a `global` class or alias in scope. Perhaps in the exceedingly rare situation where it's ambiguous between the two the class would just "win" for capturing the name and the longer unambiguous `global static` form would need to be used if the keyword is desired instead?

**Comment by HaloFour** [comment]
@mikernet 

> It's just messy and I prefer my OOP languages to properly support OOP principles like encapsulation.

This is correct encapsulation as far as the C# language and the CLR are concerned.  Both `List<int>` and `List<string>` are considered separate types with their own static fields.  This is even true in the case of `List<object>` and `List<string>` even though the JIT will compile them into a single shared implementation.

**Comment by mikernet** [comment]
@HaloFour You're splitting hairs. Encapsulation refers to keeping the concerns of a class within that class, and the `List<T>` type (which IS a type from the perspective of C# and the CLR, just not one that can be instantiated) is the only one that needs to be concerned with the global type. This enables *better* encapsulation.

**Comment by HaloFour** [comment]
@mikernet 

It's an important detail.  Even if the open generic type `List<>` is it's own type it's still a distinct and separate type from `List<int>` or `List<string>`, each of which have their own static fields.  If that wasn't the case there wouldn't be any reason for the JIT to explicitly respect that relationship in the implementation of the shared code between compiled generic types like `List<object>` and `List<string>`.

I get that you want to change this relationship via a syntax change, and that's fine.  My opinion is that given there is a relatively simple workaround available, which has worked since .NET 2.0, that the likelihood of this proposal gaining the traction necessary to be implemented is fairly low.  But that's up to the language design team to decide, assuming any of them champion this issue.

**Comment by HaloFour** [comment]
@mikernet 

> As you just pointed out, the open generic type is its own type that is distinct and separate, and thus it should be able to encapsulate its concerns.

Indeed, but it's distinct from `List<string>` and `List<int>` which encapsulate their own concerns separately.  Considering that open generic types can't be used directly, whether or not they encapsulate a static field is entirely esoteric; you can't access it anyway.

> I don't see how anything you said (regarding CLR representation of the types) is relevant/important to whether or not this should be implemented.

It's not relevant.  I just disagree that the currently behavior doesn't follow OOP encapsulation.

**Comment by mikernet** [comment]
@HaloFour OOP encapsulation isn't an on/off switch. It doesn't either follow encapsulation or not. The more situations you can encapsulate behavior, the better the OOP encapsulation capabilities of a language are. In this particular situation, the language objectively doesn't allow for proper encapsulation of concerns. No language allows for encapsulation of concerns in all cases. It's like perfection - you can never achieve it, but you still work towards it.

I don't know what you're getting at with the esoteric comment. Is allowing any private members entirely esoteric as well just because you can't access them outside of the declaring class and its subclasses?

**Comment by theunrepentantgeek** [comment]
> I don't know what you're getting at with the esoteric comment.

I believe he's referring to `List<>`, `List<string>` and `List<int>` being entirely separate classes - but only two of these three can ever be instantiated.

So it becomes a moot point whether `List<>` has its own static members or not - because none of the code on `List<>` ever executes at all.

**Comment by mikernet** [comment]
> So it becomes a moot point whether `List<>` has its own static members or not - because none of the code on `List<>` ever executes at all.

@theunrepentantgeek Right, except that with this proposal that's no longer the case. Anytime code written in `List<>` (and thus all of its associated concrete type like `List<int>`) or its nested types touch the `global static` members then it will execute, so it would no longer be moot.

**Comment by mikernet** [comment]
I just fail to see how pointing out that `List<>` currently isn't a type that technically has its own members is a relevant point or argument in a proposal looking to change that. I know it currently doesn't, that's why I'm making this proposal!

**Comment by willard720** [comment]
`global` probably isn't the best word. When I think `global static fields` I think about `global` variables which have proven to be really bad. This is basically a "super static" field as it's static to the class and the infinite classes that can spin off it, so I think a name that describes that would be better. 

Something like, `generic static` (`generic` here of course being contextual so as to not break old code) might be more suitable and less confusing.

**Comment by mikernet** [comment]
@willard720 Yeah maybe, I'm not picky on the name. `type static` could be another option, as it is static to the type declaring it.

**Comment by OyasumiLad** [comment]
I imagine most use cases for this could be solved with features currently in the language and at the cost of only a few wasted bytes * types
```
public static class Cache<T>
{
    static Cache() => Shared = typeof(T) == typeof(int) ? new Dictionary<string, object>() : Cache<int>.Shared;

    static Dictionary<string, object> Shared;
    static Dictionary<string, T> Unique = new Dictionary<string, T>();
}
```

And for more complex cases, I would prefer writing an extra internal class over having a new keyword for an extremely rare situation.

**Comment by Logerfo** [comment]
Isn't this achievable via static interface members?

**Comment by DavidArno** [comment]
An easy work-around to this is to ensure you only ever reference one of the types associated with a generic type in order to have such a global static. For example, your example code could be changed to:
```cs
public class List<T>
{
    private static readonly Dictionary<object, object> _globalCache;

    private static Dictionary<object, object> GlobalCache {get;} = List<object>._globalCache;

    static List()
    {
    	if (typeof(T) == typeof(object))
        {
	        _globalCache = new Dictionary<object, object>()
                // populate cache with intial values...
        }
    }
}
```
Then just reference the global cache via `GlobalCache` from any `List<T>` to always get the one copy Since this only requires an extra property and an `if` in the static constructor, inventing a whole new syntax for this seems a little excessive to me.

**Comment by GeirGrusom** [comment]
Inherit from a non-generic class and make the field and constructor `private protected`.

```csharp
public class List
{
  private protected static readonly Dictionary<object, object> _globalCache = new Dictionary<object, object>();

  private protected List()
  {
  }
}

public sealed class List<T> : List
{
}
```

**Comment by mikernet** [comment]
@OyasumiLad @DavidArno Those are fairly clever workarounds that inspired a solution which moves all the hackey code into a helper `SharedGlobal` class for this purpose, so thanks for the inspiration I guess haha...though I still wish there was a nicer way of doing this.

@GeirGrusom If you look at the example, I can't do that.

**Comment by mikernet** [comment]
It's noteworthy to add that the workaround @OyasumiLad suggested only works for read-only reference types, whereas the one @DavidArno posted works for reading and writing any types.

**Comment by OyasumiLad** [comment]
Refactored it a bit to work with value types, and only contain a single instance, should've given a little bit more thought initially.
```
public static class Cache<T>
{
    static Cache() { if(typeof(T) == typeof(int)) _Shared = new Point(10,10); } // Initialize to whatever.

    static Point _Shared;
    public static ref Point Shared => ref Cache<int>._Shared;

    static Dictionary<string, T> Unique = new Dictionary<string, T>();
}
```

```
Console.WriteLine(Cache<float>.Shared); // (10, 10) 
Cache<int>.Shared.X = 5;
Console.WriteLine(Cache<double>.Shared); // (5, 10)
```

**Comment by mikernet** [comment]
@OyasumiLad Yeah that works. I also lied before and misread @DavidArno's solution - it's amost there but doesn't quite work as-is for shared writing - this line:

```c#
private static Dictionary<object, object> GlobalCache {get;} = List<object>._globalCache;
```
Needs to change to this:

```c#
private static Dictionary<object, object> GlobalCache => List<object>._globalCache;
```
And then a set accessor can be added along the same vein if needed. Very similar to your solution in either case. 

I hate finicky hacky code like that though so I just made something that lets me do this:

```c#
public class XList<T>
{
    private static readonly TypeStatic<int> _numListTypes = TypeStatic.Register<int>();
    private static readonly TypeStatic<int> _sharedLabel = TypeStatic.Register<string>(() => "label");

    public static int NumListTypes => _numListTypes.Value;

    public static string SharedLabel
    {
        get => _sharedLabel.Value;
        set => _sharedLabel.Value = value;
    }

    static XList()
    {
        _numListTypes.Value++;
    }

    public static void DoStuff() {}
}


XList<int>.DoStuff();    // XList<>.NumListTypes == 1
XList<string>.DoStuff(); // XList<>.NumListTypes == 2
XList<int>.DoStuff();    // XList<>.NumListTypes == 2
XList<float>.DoStuff();  // XList<>.NumListTypes == 3

XList<int>.Label.ToString() // "label"
XList<string>.Label = "changed label";
XList<int>.Label.ToString() // "changed label"
```

It has a small startup cost on each type initialization and then access is just as fast as a regular field. Registering a type static field in 1000 classes (10 different open generic types with 100 closed types each) only takes 20ms, so I'm happy enough with this as it is.

If anyone is interested in the code let me know and I'll post it.
