### ISSUE TITLE
Finish Design Notes for 2016-11-16

### ISSUE THREAD

**Issue by MadsTorgersen** [dotnet/csharplang#2]
Clean up [design-notes/Notes-2016-11-16](https://github.com/dotnet/csharplang/tree/7981ea1fb4d89571fd41e3b75f7c9f7fc178e837/design-notes/Notes-2016-11-16.md)

**Comment by paulomorgado** [comment]
[design-notes/Notes-2016-11-16.md](design-notes/Notes-2016-11-16.md) is 404
