### ISSUE TITLE
Spec isn't Versioned

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/csharplang#20]
There should be a way to view the spec for each version. Tags or folders I'm thinking

**Comment by BillWagner** [comment]
@SamuelEnglard 

I'd like to close this.  The [dotnet/csharpstandard repo has branches](https://github.com/dotnet/csharpstandard/branches) for each version there. Note that v5 is approved, the v6 and v7 branches are drafts. We'll continue to follow that plan moving forward.

I think that means this issue has been addressed.

**Comment by 333fred** [comment]
I would agree. Closing out.
