### ISSUE TITLE
[Question] Plan for future C# versioning?

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/csharplang#200]
C# 7.0 is on the doorstep, but after C# 7 I have seen mention of 7.1, 7.2 and more versions.

Is there a version numbering roadmap?
If 7.1 is the next planned version number, does this indicate a change in release cadence or scope?

Or is it too early to say?

@MadsTorgersen, @gafter

**Comment by svick** [comment]
I would really like to see the official response on this too. In the meantime, you can look at [the milestones in this repo](https://github.com/dotnet/csharplang/milestones), which are used to categorize championed proposals:

* 7.0: C# 7.0 language features
* 7.1 candidate: Candidates for the C# 7.1 release
* 7.2 candidate: Candidates for the C# 7.2 release
* 7.X candidate: Candidates for one of the C# 7.x releases.
* 8.0 candidate: Candidates for the C# 8.0 release
* X.0 candidate: These features are candidates for some future major release.
* X.X candidate: These candidate features could be included in any major or minor release.

**Comment by AlgorithmsAreCool** [comment]
Yes, i had seen the milestones, but i was more curious about the concept of a minor language release and what the implications are (if any) for cadence.

**Comment by eyalsk** [comment]
@AlgorithmsAreCool I think that they are too busy on RTM and stuff so it might take some time.

You can check @gafter's reply to me [here](https://github.com/dotnet/csharplang/issues/73), hope it helps.

**Comment by gafter** [comment]
We don't have any firm plans for dates and feature content to announce at this time. The milestone labels on championed features (which we are still changing as we discuss things) are the best information we can provide on our thinking. Github will likely never be the mechanism by which we give guidance on product release dates or features. Such things are usually announced on the [Visual Studio Blog](https://blogs.msdn.microsoft.com/visualstudio/).

**Comment by AlgorithmsAreCool** [comment]
Understood. Thanks for the answer.
