### ISSUE TITLE
Proposal: sizeof constant strings

### ISSUE THREAD

**Issue by moien007** [dotnet/csharplang#2005]
What about making sizeof() operator works on constant strings and return string size in **bytes**  ?
```
const string hello = "hello";
int x = sizeof(hello); // x = 5 * 2 
x = sizeof("welcome"); // x = 7 * 2
```

**Comment by DanFTRX** [comment]
Just use an extension method?

```CSharp

public static int LengthBytes(this string @this)
{
    return @this.Length() * 2;
}
```

or if using a non-standard encoding use 

```CSharp
System.Text.ASCIIEncoding.Unicode.GetByteCount(@this);
System.Text.ASCIIEncoding.ASCII.GetByteCount(@this);
```

**Comment by mikernet** [comment]
What are you trying to achieve with this? As in, what are you doing with this value?

**Comment by moien007** [comment]
@mikernet look at the following example

```
const string EchoCommand = "//echo";

void ReadCommand()
{
      int bytesRead = stream.Read(buffer, 0, buffer.Length);
      string text = Encoding.Unicode.GetString(buffer, 0, bytesRead);
      
      if (text.StartsWith(EchoCommand))
      {
            stream.Write(buffer, sizeof(EchoCommand), bytesRead - sizeof(EchoCommand));
            return;
      }

      ......
}

```

**Comment by HaloFour** [comment]
That seems like an exceptionally niche use case.  For any given networking protocol you can calculate those command sizes up front, using the proper encoding (which isn't likely to be .NET's flavor of Unicode anyway).

**Comment by moien007** [comment]
Does all C# features is "overwhelmingly postitive" ?
Doesn't C or C++ have sizeof operator for strings ? and Isn't C# uses their syntax ?
Doesn't any network protocol exist that uses Unicode encoding ?
Do memory reading or function calling is faster than constant values ?  
```
static readonly int EchoCommandSize = Encoding.Unicode.GetByteCount(EchoCommand);

stream.Write(buffer, EchoCommandSize , bytesRead - EchoCommandSize);
```
or
```
stream.Write(buffer, 
Encoding.Unicode.GetByteCount(EchoCommand),
bytesRead - Encoding.Unicode.GetByteCount(EchoCommand));
```

Answer those questions and your win !!!

**Comment by HaloFour** [comment]
> Does all C# features is "overwhelmingly postitive" ?

It's exceptionally expensive to add any new features to the language, in terms of design, implementation and permanent support.  So yes, any new feature has to demonstrate that it's worth all of that effort.

> Doesn't C or C++ have sizeof operator for strings ? and Isn't C# uses their syntax ?

Yes, but `sizeof` with strings has dubious value in C.  And C# certainly doesn't copy everything C did, quite intentionally.

> Doesn't any network protocol exist that uses Unicode encoding ?

Maybe, but you're still talking a small subset of a small subset of use cases.

> Do memory reading or function calling is faster than constant values ?

Not particularly important.  You can calculate those sizes once.

**Comment by theunrepentantgeek** [comment]
> Does all C# features is "overwhelmingly postitive" ?

Yes, absolutely.

Every features starts at [-100 points](https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/). 

(Link is to a blog post by Eric Gunnerson that's highly recommended reading. It's almost 15 years old but still very relevant to the way the LDM works today.)

**Comment by yaakov-h** [comment]
`sizeof` would have to assume a given encoding. In your code sample you're already explicitly using `Encoding.Unicode`, and you really should be using `Encoding.GetByteCount(...)`.

A string has no "size in bytes" until it is encoded with a given encoding. Hardcoding language knowledge of on particular encoding seems like a bad idea, particularly given the current usage of UTF-16 combined with the push towards improved UTF-8 support.

**Comment by moien007** [comment]
oookay
