### ISSUE TITLE
Target Typed ?? and ?:

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#2006]
### Problem

This is a reasonably common pattern:

```csharp
List<int> list = whatever;

//Doesn't compile
//IList<int> someList = list ?? Array.Empty();

//Instead you have to write
IList<int> someList = list ?? (IList<int>)Array.Empty();

```

Similarly this is a reasonably common pattern:

```csharp
List<int> list = whatever;
int[] array = whateverElse;

//Doesn't compile
//IList<int> someList = someCondition ? list :  array;

//Instead you have to write
IList<int> someList = someCondition ? (IList<int>)list : array;

```

In both cases an explicit cast must be inserted into the code, even though from context it is clear what cast should be used.

The cast does not aid readability IMO, and only serves to break up the flow of the code. 

### Proposed Solution

####:Target Typed ?? and ?: Operators

The proposal is to allow context to be used to to work out the target type of a ?? and ?: operator. If a reference conversion exists from both of the parameters of the operator to the target type of the operator, the compiler will automatically insert the casts where necessary.

The rules for when this can be used, and how to calculate the target type, should be the same as those for TargetTypedNew.

See https://github.com/dotnet/csharplang/blob/master/proposals/target-typed-new.md

### Examples

**1**
```csharp
List<int> list = whatever;

IList<int> someList = list ?? Array.Empty();

```

This is compiled to

```csharp
List<int> list = whatever;

IList<int> someList = (IList<int>)list ?? (IList<int>)Array.Empty();
```

**2**

```csharp
List<int> list = whatever;

//Shouldn't compile, as context does not make clear the return type of the operator
//var someList = list ?? Array.Empty();

```

**3**

```csharp

public List<int> SomeList {get; set;}

...

List<int> list = whatever;

//Should Compile
SomeList = list ?? Array.Empty();
```

**4**

```csharp

public class SomeClass
{
    public SomeClass(IList<int> list){}
}

...

List<int> list = whatever;

//Should Compile
var someClass = new SomeClass(list ?? Array.Empty());
```

**Comment by HaloFour** [comment]
#563

**Comment by YairHalberstadt** [comment]
Thanks @HaloFour
