### ISSUE TITLE
Proposal: Have an alternative syntax to C style casts

### ISSUE THREAD

**Issue by johnkellyoxford** [dotnet/csharplang#2009]
C style casts are difficult to search for easily using a simple text finder and personally I find they can be harder to seek out in blocks of code.

I suggest a keyword used, that is functionally equal to current C-style casts, but using the `is/as` style syntax ( var castKeyWord type). A possible keyword for this would be `to`, such as `var s = s to byte;`. Note - this would not have the null return style of the `as` keyword - it would be **exactly the same** as the C cast post compile time.

This would make searching for casts _**much**_ easier, as well as being more visually decipherable, and would create a common cast syntax alongside `is` and `as`.

It's not a breaking change, and wouldn't (shouldn't) change anything lower than the compiler level

**Comment by CyrusNajmabadi** [comment]
You can do this already:

```c#
public static U Cast<T, U>(this T t) {
    return (U)(object)t;
}
```

**Comment by johnkellyoxford** [comment]
@CyrusNajmabadi I understand that, but that's not a language feature and is still arguably less pretty than my suggestion

**Comment by alrz** [comment]
Swift has `as!` and `as?` syntax - likely inspired by C# - for direct and safe casts, respectively.

I think the former still makes sense in C# but not sure if it adds much value now that another syntax exists.

**Comment by CyrusNajmabadi** [comment]
> I understand that, but that's not a language feature 

Yes.  that's the point.  Language features aren't relaly necessary when there are perfectly suitable existing approaches that could be taken :)

**Comment by johnkellyoxford** [comment]
@CyrusNajmabadi The `using` directive, the `lock` keyword, the `??` and `?.` operators, the `yield` keywords, are all just aliases for suitable approaches to their issues (Try-Catch-Dispose, Monitor.Enter, null checks, null checks, full enumerator respectively) . But they're language features :)

**Comment by CyrusNajmabadi** [comment]
I am aware.  I did work on most of those language features :)   In those cases there was enough value to warrant this.  I'm not seeing that value.  Not everythign should be a language feature just because it can be.  Features need to be sufficiently valuable to make it into the language.

>  the yield keywords

This is not really the case. The difference between writing an enumeration by hand, versus using yield is pretty massive.  Hence the value presented by making it an actual language construct.

**Comment by willard720** [comment]
> It's not a breaking change

Yes it is, it's introducing a new keyword. How could that not be a breaking change? Also, it doesn't seem possible to make it a contextual keyword.

What we're talking about is the difference these two ways of writting:

```csharp
Bar bar = Foo.To<bar>();
Bar bar = Foo to bar;
```

It honestly makes no difference. And if you want to find the casts easier, just do ctrl f and search `.To<`.

Compare this to the other features that you mention:

```csharp
// ---- using ---- //

// Before:
public void Bar()
{
    try
    {
        Console.WriteLine("Hello");
    }
    finally 
    {
        if (foo != null)
        {
            ((IDisposable)foo).Dispose();
        }
    }
}

// After:
public void Bar()
{
    using (foo)
    {
        Console.WriteLine("Hello");
    }
} 

// ---- lock ---- //

// Before:
object lockObj = x;
bool lockWasTaken = false;

try
{
    System.Threading.Monitor.Enter(lockObj, ref lockWasTaken);
    // Your code...
}
finally
{
    if (lockWasTaken) 
    {
        System.Threading.Monitor.Exit(lockObj);
    }
}

// After:
lock (x)
{
    // Your code...
}

// ---- ?? ---- //

// Before:
private Bar _d;
public Bar D => _d == null ? _d = new Bar(); : _d; 
...
x = y == null ? new Foobar(); y;

// After:
private Bar _d;
public Bar D => _d  ?? d = new Bar(); 
...
x = y  ?? new Foobar();

// ---- ?. ---- //

// Before:
if (foo != null)
{
    if (foo.Bar != null)
    {
        foo.Bar.FooBar();
    }
}

// After:
foo?.Bar?.FooBar();

// ---- yield --- //

// Before:

    private sealed class <Foo>d__1 : IEnumerator<object>, IDisposable, IEnumerator
{
    private int <>1__state;
    private object <>2__current;

    object IEnumerator<object>.Current
    {
        [DebuggerHidden]
        get
        {
            return <>2__current;
        }
    }

    object IEnumerator.Current
    {
        [DebuggerHidden]
        get
        {
            return <>2__current;
        }
    }
    public <Foo>d__1(int <>1__state)
    {
        this.<>1__state = <>1__state;
    }
    void IDisposable.Dispose()
    {
    }

    private bool MoveNext()
    {
        switch (<>1__state)
        {
            default:
                return false;
            case 0:
            {
                <>1__state = -1;
                List<int> list = (List<int>)(<>2__current = new List<int>());
                <>1__state = 1;
                return true;
            }
            case 1:
                <>1__state = -1;
                return false;
        }
    }

    bool IEnumerator.MoveNext()
    {
        return this.MoveNext();
    }
    void IEnumerator.Reset()
    {
        throw new NotSupportedException();
    }
}

[IteratorStateMachine(typeof(<Foo>d__1))]
public static IEnumerator Foo()
{
    return new <Foo>d__1(0);
}

// After:
public static IEnumerator Foo()
{
    var x = new List<int>();
    yield return x;
}
```

So you see they all tend to be significantly shorter, espically the `yield`. Besides that, they're all very common cases. They also make the writing process easier as we don't have to think so much, notably `yield`, `using` and `lock`. This is very good. Your feature only makes it mildly easier to read, but that's it, so you're core argument is flawed of "why not"

**Comment by khm1600** [comment]
>You can do this already:
>```cs
>public static U Cast<T, U>(this T t) {
>    return (U)(object)t;
>}
>```

Except when `"".Cast<string, int>()` passes compilation.

So I guess we need a way to tell the compiler that "a cast from T to U maybe exist"?

**Comment by DavidArno** [comment]
> So I guess we need a way to tell the compiler that "a cast from T to U exists"?

The compiler doesn't have that even for direct casts. The following will compile and then fail at runtime, so a `Cast<T, U>` is no different:
```cs
_ = (int)(object)"1";
```

**Comment by khm1600** [comment]
>The compiler doesn't have that even for direct casts. 

I think the `t to T` that this proposal is about is identical in meaning to `(T)t`, and `"" to int` won't compile just as `(int)""` won't.

**Comment by PathogenDavid** [comment]
>This would make searching for casts **_much_** easier, as well as being more visually decipherable, and would create a common cast syntax alongside `is` and `as`.

It seems to be that your main motivation for this change is the searching aspect. I'd argue that this is a solution that should be solved by tooling rather than by adding language features.

Scanning entire projects for something like this is trivial with Roslyn. It'd also be much more robust than plain old grepping since it would properly find instances of people using full type names, aliasing type names, (not) using language keyword equivalents, and even implicit casts.

(A generic tool that integrates with Visual Studio and can search for particular `IOperation` or or `SyntaxNode` patterns would be pretty neat in general, actually. Designing a good UI for it would not be fun though.)

Additionally, I'd actually argue adding this new syntax would only serve to make this problem worse for people grepping around because there'd be two different syntaxes to search for.

**Comment by theunrepentantgeek** [comment]
> C style casts are difficult to search for easily using a simple text finder

Unless you're working with some odd coding conventions, a C style case is always of the form `(` `type` `)` - and I think that's pretty easy to find. The only trick seems to be to tell your tooling you're looking for a literal string and not a regex.

What am I missing?

**Comment by willard720** [comment]
Also, you can type `foo.To<Bar>()` as `foo. To <Bar>()` if you really want to make it more readible, though most people would have no problem with the first.

**Comment by juliusfriedman** [comment]
Certainly I would ask how do we override ' to  ' given state or context?

It must be somewhere in the documentation on TypedReference and object headers...

Ntl... this could be implemented as a custom operator also...

Guess Destructured syntax is taking off..

Perhaps placement new is the convention we are after today?

**Comment by gdalsnes** [comment]
Alternative syntax:

`var s = s cast byte;`

_cast_ make more sense than _to_ for me
