### ISSUE TITLE
Proposal: Slicing for Lists,Arrays and Strings like Python

### ISSUE THREAD

**Issue by tahazayed** [dotnet/csharplang#2014]
would you please add slicing for Lists,Arrays and Strings like the one used in [Python](https://www.pythoncentral.io/how-to-slice-listsarrays-and-tuples-in-python/) 

I know there are skip and take but Python style is much better

**Comment by Joe4evr** [comment]
In the case of strings and arrays, you can just call `.AsSpan()` and slice that.

Lists and other arbitrary collections would not be a good fit to slice, because that would require exposing the implementation details.

**Comment by benaadams** [comment]
Champion "slicing" / Range? https://github.com/dotnet/csharplang/issues/185

Probably detailed more clearly in "Building C# 8.0: Ranges and indices" https://blogs.msdn.microsoft.com/dotnet/2018/11/12/building-c-8-0/

**Comment by tahazayed** [comment]
@Joe4ever kindly check Python style from this URL: [https://www.pythoncentral.io/how-to-slice-listsarrays-and-tuples-in-python/](https://www.pythoncentral.io/how-to-slice-listsarrays-and-tuples-in-python/)

much easier

**Comment by HaloFour** [comment]
@tahazayed 

The python syntax was considered as an option, but the team has chosen `..`.  Indexes have value outside of ranges.  It's better to build language features out of smaller features that can be composed together.

**Comment by tahazayed** [comment]
OK, Thanks
