### ISSUE TITLE
Proposal: match bits

### ISSUE THREAD

**Issue by vdisasm** [dotnet/csharplang#2016]
I'd like to discuss following idea

I'm creating disassemblers and it needs machine instruction decoding. i.e. matching many bit patterns and extracting bits.

Expression to test bits is
```c#
if ((value & mask_and) == mask_match)
```

For example, to test bits 0 and 3 are set

```c#
if ((value & 0b_1001) == 0xb_1001)
```
Using pattern matching could be
```
if (value is 0b_1??1)
```
where ``?`` are ignored and can represent any digit
or
```c#
switch (value)
case 0b_1??1:
```

Some problems I can see:
- It should work for binary and hex number, where it is easy to calculate mask for digits, unlike decimals.
- It is incomplete without syntax to easy access bits, like
```
int bits = value[high..low];   or | int bits = value.bits[high..low]; 
value[high..low] = bits;          | value.bits[high..low] = bits;
```
- It won't be widely used

**Comment by YairHalberstadt** [comment]
This is a bit of a niche scenario to add a language feature for. It there a more generally useful proposal underlying this?

**Comment by vdisasm** [comment]
I know, it's very specific.
I doubt there would be mass interest in this, because I can imagine usage of this only when need to manipulate bits. Like low level structures decoding, processing input signals.

**Comment by YairHalberstadt** [comment]
How much of that is currently done in C#?

**Comment by DavidArno** [comment]
@alrz,

I was going to suggest that this could be solved with your [active patterns proposal](https://github.com/dotnet/csharplang/issues/277):
```cs
public static bool BitPatternMatch(this int value. int mask) => (value & mask) == mask;

if (value is BitPatternMatch(0xb_1001)) …

switch (value)
{
    case BitPatternMatch(0xb_1001) : …
```
but you have closed that issue saying that it's no longer required with recursive patterns. How would you solve this with active patterns as I'm confused by your closing comment on that issue?

**Comment by alrz** [comment]
@DavidArno 

In a recursive pattern like that, when the type lookup for `BitPatternMatch` fails, we'll look for a method or an extension method on the target value, e.g. `value.BitPatternMatch(0xb_1001)`.

Each argument can be a:

- (1) constant pattern, 
  - (1a) If the corresponding parameter is not `out`/`ref` we'll pass the constant *value* as the argument.
  - (1b) If the corresponding parameter is `out` we'll match it against the result.
  - (1c) otherwise, an error is produced.
- or (2) some other pattern.
  - (2a) If the corresponding parameter is `out` we'll match it against the result.
  - (2b) otherwise, an error is produced.

This is mostly the same as how we handle  `Deconstruct`, except for the case (1a) and the lookup.

**Comment by alrz** [comment]
>e saying that it's no longer required with recursive patterns

That's not what I was saying. This is still a separate feature, but the proposed parsing style is out of the question.

**Comment by DavidArno** [comment]
@alrz, ah that makes sense. Thanks.

**Comment by vdisasm** [comment]
```
(value & mask) == mask
```

should be 
```
(value & mask1) == mask2
```

First mask tells what bits I want. 2nd mask is to test bits (either set or cleared).

**Comment by DavidArno** [comment]
@vdisasm, recursive patterns, as planned for C# 8, will not support that. Some form of user-definable, extendable, or active pattern (as discussed in #1047, and all possibly the same thing, just with different names) would though. You'd simply write custom code to handle your pattern use-case.

**Comment by vdisasm** [comment]
Thanks I will check that

вт, 20 нояб. 2018 г., 16:09 David Arno notifications@github.com:

**Comment by vdisasm** [comment]
Thanks I will check that
