### ISSUE TITLE
break and continue inhancements

### ISSUE THREAD

**Issue by ghost** [dotnet/csharplang#2024]
`break` and `continue` can be confusing in nested loops. I suggest to add optional key word after them such as:
```
break for;
continue foreach;
break while;
```
If they are used in nested loops of the same type, I suggest to use the loop counter as an identifier:
```
for (var i=0; …………)
{
     for (var j=0; …………)
          break i;
}
```

I don't have a solution to control the break/continue in nested while, unless using goto or a Boolean flag. But it can help in most cases to add this statements:
```
break all; 
break parent;
continue parent; 
```

And Maybe it is better to label nested loops if needed, and use the label with break and continue:
```
Loop1: while{

               while {
                    break Loop1;
                    continue Loop1;
                }
            } 
```

**Comment by Logerfo** [comment]
#869

**Comment by MohammadHamdyGhanem** [comment]
@jnm2 
'break all;' is a shortcut for: 'goto LineEnd;' where 'LineEnd' is placed after the end of the outer loop. It can be implemented easily, and it is commonly usable.

'break parent;' is also practical, becuse two nested loops are the most common situation. If you have three nested loops of the same type, then you can use break to exit the inner loop, break parent to exit the second loop, and break all to exit the outer loop. Four nested loops are not practically common, and it is not likely to be of the same type. So, practically break name, break parent, break all will cover most of the cases.

**Comment by Gnbrkm41** [comment]
@willard720 Probably the innermost for loop. In Visual Basic, you actually have to mention which statement you are exitting ( `Exit { Do | For | Function | Property | Select | Sub | Try | While }` ) and this exits the innermost statement you've mentioned.

**Comment by Gnbrkm41** [comment]
I don't see the reason to allow `break { all | parent }` If we could put an identifier(label?) on each statement, you may want to name one of your loops to 'parent' or 'all' but you wouldn't be able to do so because they'd be reserved.

**Comment by MkazemAkhgary** [comment]
these kind of things rarely happen to me but there is also another way to terminate these loops

```c#
    bool end = false;
    for(int i = 0; !end && (...); i++) {
        for(int j = 0; !end && (...); j++) {
            // ...
            if(when_ever_needed) end = true; // preferably at the end of loop so you dont need continue.
        }
    }
    // rest of code
```c#

most of the times i simply return the value in the inner loops...
some times its better to put these loops in a single method so you can directly return value from inner loops. give these methods meaningful name and you will be fine.

**Comment by Gnbrkm41** [comment]
Certainly possible, but never thought of that. Nice idea.

Also, about returning in loops / refactoring loops into a single method:
https://github.com/dotnet/csharplang/issues/869#issuecomment-326567467 

> Inline returns slow down loops until .NET Core 2.1 dotnet/coreclr#13314 and functions with a loop generally won't inline (without forcing); so wouldn't be so great for very hot loops; though ok for general loops.

**Comment by MohammadHamdyGhanem** [comment]
@willard720 
This is why I made some more suggestions. Note that `break for` will act on the same `break` roles except `break for` affects only for loops (not foreach nor while).
The `break parent` and `break all` can solve any other ambiguities.

I also suggest to allow `break this` for the sake of clarity.

@MkazemAkhgary 
Of course there are solutions and workarounds. Programmers had survived for decades .
The purpose is to make the code shorter and more readable.

**Comment by Gnbrkm41** [comment]
`break this` does not look like a good idea. `this` keyword has always been used as a reference to an instance itself (sort of, since extension method is not really an instance method yet using `this` to declare one; but it kinda works like instance method, you know). I think it may cause some confusion to some people.

the current 'break' statement does the exact same thing too, and people (in general) should already know it as break statement works the same way in other languages as well.

**Comment by jnm2** [comment]
`break this` sounds like `#error`. :D

**Comment by Joe4evr** [comment]
[Cry me a river, build a bridge, and get over it.](https://github.com/dotnet/roslyn/issues/5883#issuecomment-153798232)
![](https://i.imgur.com/ztGjtyZ.png)

**Comment by scalablecory** [comment]
So ideally we wouldn't have loops nested deeply enough where this becomes an actual problem,

But if it ever is a problem, we already have `goto` -- so changing `continue` and `break` is unnecessary.

**Comment by MkazemAkhgary** [comment]
@scalablecory even if that happens i suggest to refactor your method into smaller methods. even if your method isn't in-lined at run time, it shouldn't really affect performance at a noticeable amount.

**Comment by Logerfo** [comment]
@Joe4evr #off-topic why is Neal name printed after his username in your screenshot? Is that an optional setting, an extension...?

**Comment by MkazemAkhgary** [comment]
@Logerfo #off-topic such a godly attention!

**Comment by juliusfriedman** [comment]
Why should the compiler need to write my variables for me?

What if I wanted break x = y = 2;...

Not sure how this adds anything other than syntactical sugar which is needed to be rewritten do yo more useful thiungs with.

**Comment by YairHalberstadt** [comment]
Closing as the OP no longer has a github account, and the proposal has been fairly negatively received. 
If you would like to discuss this further, let me know and I'll move this to a discussion.

**Comment by CyrusNajmabadi** [comment]
Proposal started here: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-15.0/labeled-break-continue.md
Championed Issue here: https://github.com/dotnet/csharplang/issues/9875
Discussion here: https://github.com/dotnet/csharplang/discussions/9876

Closing this out to move discussion there.
