### ISSUE TITLE
Introduce syntax in lambda to capture by value rather than by reference

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/csharplang#2029]
In C#, when a lambda captures a local, it always captures the variable, not the value. In C++, captures are specified explicitly, and it's possible to indicate whether a given variable should be captured by reference or by value.

It would be useful to have a keyword (e.g. `valueof`) to tell the compiler to capture the value rather than the variable:

```csharp
// Captures the variable
var foo = GetFoo();
Func<int> func1 = () => foo;
Expression<Func<int>> expr1 = () => foo;

// Captures the value
var foo = GetFoo();
Func<int> func2 = () => valueof(foo);
Expression<Func<int>> expr2 = () => valueof(foo);
```

In an expression tree, `valueof(foo)` would be a `ConstantExpression` with the value of `foo` at the time the expression is created.

**Comment by YairHalberstadt** [comment]
On the contrary. Everything is captured by value. However the value of reference types is a pointer to an object, not the object.

What you're asking for is fundamentally impossible with C#s memory model.

**Comment by HaloFour** [comment]
What is this proposal attempting to achieve?  Why would it be beneficial to change how the variable is captured and how would it differ from how the capture works today?

**Comment by thomaslevesque** [comment]
@YairHalberstadt I think you misunderstood my point (maybe I didn't express it clearly).

When a variable is captured in a lambda, the variable is hoisted as a field in a closure type. Accessing the variable in the lambda actually accesses that field, and returns whatever value the field has at this point in time. It's "by reference" in the sense that it doesn't make a copy of the value when the lambda is created.

**Comment by YairHalberstadt** [comment]
@thomaslevesque
I see what you mean. I was wrong, and thank you for teaching me better how delegates work in C#

**Comment by thomaslevesque** [comment]
> What is this proposal attempting to achieve? Why would it be beneficial to change how the variable is captured and how would it differ from how the capture works today?

Well, for one thing it would be more efficient (accessing a constant is faster than accessing a field). It also changes the semantic of the capture, in that the value in the lambda is an independent copy of the captured variable, which is often desirable (e.g. in a loop, no need to explicitly make a local copy of the loop variable). It also makes things simpler for code that works on expression trees.

The specific use case that prompted this proposal was that in EF Core, the `FreeText` method only accepts a constant as the `language` argument (see https://github.com/aspnet/EntityFrameworkCore/issues/13315). In other words, you can't do this:

```csharp
int lcid = CultureInfo.CurrentCulture.LCID;
var results = await _dbContext.Items
    .Where(i => EF.Functions.FreeText(m.Text, searchTerm, lcid))
    .ToListAsync();
```

because `lcid` in the lambda is actually `<closure variable>.lcid`, which isn't supported in the EF Core translator. Of course, this problem should be fixed in EF Core itself rather than in the language, but having the ability to explicitly capture the value of `lcid` would have provided a simple workaround.

**Comment by YairHalberstadt** [comment]
So `() => valueof(foo)` is essentially a shorthand for
```csharp
var temp = foo;
() => temp;
```

**Comment by HaloFour** [comment]
@thomaslevesque 

The variable still has to be hoisted into a field on a class instance.  There isn't another mechanism through which the compiler can capture data into a delegate instance.  You're really just changing when that field is assigned.  `foo` can never be a constant in normal lambdas.

The difference is more apparent with expressions since you're asking the compiler to embed the current value of `foo` in a `ConstantExpression`.  But that would be a difference in behavior that doesn't make much sense.  And, as you mentioned, this is to gloss over a limitation of EF, which it sounds like EF should address, not the compiler.  Other than `static` delegates the team has expressed no interest in pursuing capture lists like C++ supports them.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/163

**Comment by theunrepentantgeek** [comment]
> e.g. in a loop, no need to explicitly make a local copy of the loop variable

Small nitpick. This behaviour changed in C# 5 (released 2012): A lambda within a **foreach** loop now captures the current value of the loop variable only; it's as though each iteration of the loop gets a new variable declaration.

This is one of the very few times they've made a breaking change to the language.

See _[Closing over the loop variable considered harmful](https://blogs.msdn.microsoft.com/ericlippert/2009/11/12/closing-over-the-loop-variable-considered-harmful/)_, and [Closing over the loop variable, part two](https://blogs.msdn.microsoft.com/ericlippert/2009/11/16/closing-over-the-loop-variable-part-two/) by Eric Lippert for more details; they're the most authoritative sources I could find quickly.

**Comment by thomaslevesque** [comment]
@theunrepentantgeek yes, I'm aware of this. But there are other scenarios (e.g. `for` loops) where this can be useful.

**Comment by thomaslevesque** [comment]
This proposal never attracted much interest, and is of limited value, so it probably won't happen. Closing to reduce the clutter.

**Comment by CyrusNajmabadi** [comment]
Reactivating and moving to discussion.  :)
