### ISSUE TITLE
Conditional dereference

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#2030]
Just a random thought... can be helpful for fluent libraries or linq as well.
```c#
  x.FuncA().FuncB().(callC)FuncC().FuncD();
```
instead of
```c#
  x = x.FuncA().FuncB();
  if(callC) x = x.FuncC();
  x = x.FuncD(); // or can be merged with first line if order doesn't matter.
```

---

Join multiple calls

```c#
  x.FuncA().FuncB().((callC)FuncC().FuncD()).FuncE();
```
instead of
```c#
  x = x.FuncA().FuncB();
  if(callC) x = x.FuncC().FuncD();
  x = x.FuncE();
```
---
Branch with ternary:

```c#
  x.FuncA().FuncB().(callC) ? FuncC().FuncD() : FuncE().FuncF();
```

Join a branch with parentheses:

```c#
  x.FuncA().FuncB().((callC) ? FuncC().FuncD() : FuncE().FuncF()).FuncG();
```

Its also compatible with null propagation operator but with following restriction.

- method calls inside conditional de-reference can not have null propagation operator unless null value is handled by null coalescing operator or another null propagation comes immediately after conditional de-reference ends.

I know this is an extreme case, but its just a random thought.

**Comment by MkazemAkhgary** [comment]
right, but this one works out of the box.
If i have something like this in one place, I go with if-else approach rather than making extension method.
but i would use the proposed syntax ideally.

**Comment by theunrepentantgeek** [comment]
This proposed syntax would be a breaking change, conflicting with the existing static cast syntax.

**Comment by MkazemAkhgary** [comment]
@theunrepentantgeek hmm, the open parenthesis comes right after `.` operator. how does it conflict?

**Comment by jnm2** [comment]
You could define an extension method and do:

```c#
startExpression
    .FuncA()
    .FuncB()
    .If(cond, _ => _.FuncC())
    .FuncD();

startExpression
    .FuncA()
    .FuncB()
    .If(cond, _ => _.FuncC(), _ => _.AltFuncC())
    .FuncD();
```

**Comment by MkazemAkhgary** [comment]
@jnm2  looks elegant, very nice!
