### ISSUE TITLE
Compile-Time generated method return type

### ISSUE THREAD

**Issue by ymassad** [dotnet/csharplang#2031]
Consider this code:

```
[ReturnValueTypeCalculator(typeof(TypeCalculator1))]
public static object Method1<
    [UsedInCalculation]TParam1,
    [UsedInCalculation]TParam2,
    TParam3>
    (TParam1 param1, TParam2 param2, TParam3 param3)
{
        //calculate return value
        //return...
}

public static class TypeCalculator1
{
    public static ITypeSymbol CalculateType(
        ITypeSymbol t1,
        ITypeSymbol t2)
    {
        //return the return value type or null to tell the compiler that it should not allow the method call on passed parameters
    }
}
```

The return type of `Method1` depends on the types of the expressions (compile-time types, not runtime-types) pass as parameters to the method.

At compile time, for each invocation of `Method1`, the compiler will call `TypeCalculator1.CalculateType` passing the types of the expressions passed to `Method1`. The `ITypeSymbol` comes from Roslyn. The compiler would get the returned type from `TypeCalculator1.CalculateType` and use it to simply cast the return value of `Method1`. 

The `Method1` method will be compiled as is.

Now regarding the compilation of invocations to `Method1`:

`Method1("", 1, 1.0)` would be compiled to `(double)Method1("", 1, 1.0)` assuming `TypeCalculator1.CalculateType` returned the `double` type. Or `(string)Method1("", 1, 1.0)` if `TypeCalculator1.CalculateType` returned the `string` type.

If `TypeCalculator1.CalculateType` returns null for a specific invocation, this means that the compiler shouldn't allow such invocation. Maybe we can also let the `TypeCalculator1.CalculateType` method return a reason via an `out` parameter.

Its the responsibility of the implementer of the `Method1` method to return a value that would cast to the type returned by `TypeCalculator1.CalculateType`. If they don't, as expected the cast will simply throw an `InvalidCastException` at runtime.

This can be used to replace huge C# files that contain huge number of auto generated methods in my projects.

EDIT: `TypeCalculator1` can be required to be in a different assembly so that it would compile even if the project containing `Method1` does not compile. And because the compiler needs `TypeCalculator1` before the compilation of the project containing `Method1` is complete.

**Comment by CyrusNajmabadi** [comment]
Can you give an example of how this would be used in practice?

**Comment by HaloFour** [comment]
This proposal seems extremely narrow in scope and I can't see how it would be useful in general scenarios.  The end result seems like an odd mix of generics/templates and the code that it would produce would be pretty incompatible with normal C# and VB.NET projects given that it would overload solely on the return value.

**Comment by ymassad** [comment]
To explain the proposal more with a dummy example:

Assuming `CalculateType` returns: 
`double` for `(string, int)`
`string` for `(string, uint)`

This would be **like** creating two overloads of `Method1`:



```
public static double Method1<TParam3>(string param1, int param2, TParam3 param3)
{
    //..
}

public static string Method1<TParam3>(string param1, uint param2, TParam3 param3)
{
    //..
}

```

I used bold for "like" because no overloads of `Method1` are generated at compile time.

**Comment by ymassad** [comment]
@CyrusNajmabadi , I have existing code in my projects that I cannot share as is. I will come up with a similar example and share it.

**Comment by HaloFour** [comment]
I'd suggest that, sans the auto-cast, that what you're requesting can already be accomplished by an analyzer.  That would at least be able to warn/error if the return value of `Method1` is not cast to the expected type.

**Comment by theunrepentantgeek** [comment]
This seems like a hyper-specific scenario that would benefit a vanishingly small number of projects. 

I suggest it would be worth going back to the original problem you're trying to solve and identifying a general-purpose language feature that would not only address this problem but be useful in other contexts as well.

**Comment by ymassad** [comment]
@HaloFour , do you mean an analyzer with a code fix? If so, this would require the developer to run the code fix for every invocation? Also this would add the cast to the source code which is inconvenient?

I wish there was a thing like Analyzers but that allows us to modify the semantic model automatically (and automatically the emitted IL), not the syntax tree.

**Comment by CyrusNajmabadi** [comment]
> explain the proposal more with a dummy example:

I'd prefer a non-dummy example.  It's very hard to determine the value of something when it's just toy examples.  With toy examples, i just say: why not just use the actual return type when compiling?

**Comment by HaloFour** [comment]
@ymassad 

> do you mean an analyzer with a code fix?

Maybe.  I meant an analyzer that could tell you if the cast was correct and to produce an error accordingly, but said analyzer could also generate the correct cast for the developer.

> Also this would add the cast to the source code which is inconvenient?

And correct.  The cast *belongs* at the invocation.  The compiler should not be encouraging a design that requires a type erasure custom tooling hack like this.

**Comment by ymassad** [comment]
@HaloFour ,

> The cast belongs at the invocation

The idea is to be able to mimic overloading. Therefore there shouldn't be a cast at the caller.

I think that what I should do is provide a useful example. That will make things easier to understand.

**Comment by jnm2** [comment]
@ymassad Why would casting at the call site prevent mimicking overloading?

> ITypeSymbol 

Your project would have to <PackageReference> a specific version of Roslyn?

What should the compiler do if it's a newer or older version of Roslyn?

**Comment by jnm2** [comment]
@ymassad Why would casting at the call site prevent mimicking overloading?

> ITypeSymbol 

Your project would have to \<PackageReference> a specific version of Roslyn? What should the compiler do if it's a newer or older version of Roslyn?

My guess is that Roslyn (as one possible implementation of the C# spec) is too vast to be added into the C# spec. Consider how much progress has been done keeping the language up to date with the LINQ BCL.

**Comment by ymassad** [comment]
@jnm2 , the idea is to convert existing code that contains thousands of overloads of Method1 to a single method Method1.

The current consuming code does not contain a cast (because each invocation invokes one of the overloads of Method1 that takes the correct types and return the correct type) and I want to keep it as is.

I want to have a million (or more) method overloads in some cases and this is impossible in C# (practically).

Regarding the Rolsyn version, I am not sure I understand the problem. The developer has to reference a version of Roslyn that is compatible with the one the compiler uses. Aren't Roslyn releases highly compatible with each other?

**Comment by jnm2** [comment]
> I want to have a million (or more) method overloads

This is is a ton of IL to ship to production and a ton of pressure on IDEs, e.g. intellisense. From the outside, it feels like any tradeoff is a better tradeoff than this one. Have you considered writing an analyzer to do fancier usage checking at runtime?

> Regarding the Roslyn version, I am not sure I understand the problem. The developer has to reference a version of Roslyn that is compatible with the one the compiler uses. Aren't Roslyn releases highly compatible with each other?

Multiple problems. Once is that you are now shipping the entirety of Roslyn to production. @CyrusNajmabadi or someone can speak to the compatibility, but this seems like a sure way to find new problems. The final and greatest hurdle is what I added last:

> My guess is that Roslyn (as one possible implementation of the C# spec) has too vast an API to be encoded into the C# spec. Consider how much progress has been done keeping the language up to date with the LINQ BCL.

**Comment by ymassad** [comment]
Here is a quick example:

```
public static Func<TInput1, TInput3, TInput4, TOutput> PartiallyInvoke<TInput1, TInput2, TInput3, TInput4, TInput5, TOutput>(
    this Func<TInput1, TInput2, TInput3, TInput4, TInput5, TOutput> function,
    TInput5 input5,
    TInput2 input2)
{
    //...
}
```

This is one overload of `PartiallyInvoke` that allows developers to partially invoke a function. Notice how you invoke parameter 5 and then parameter 2. There would be also another overload where the developer would invoke parameter 2 and then parameter 5.

What if the function has 10 parameter? You need to auto generate many many overloads of this method?

I will post more examples later.

**Comment by ymassad** [comment]
@jnm2 ,

They would be millions of overloads without this feature.

The consuming code would be calling some 200 of these overloads only. But which 200 overloads to call will change as developers will use different ones while maintaining the software.

When calling the single `Method1` method, at runtime, necessary code will be generated for just the 200 cases.

Regarding reference to Rolsyn, I think that the assembly containing `TypeCalculator1` and the Rolsyn dlls it depends on can be safely removed from the binary folder. Or can't they?

If the problem is with the `ReturnValueTypeCalculator` attribute referencing `TypeCalculator1`, the compiler can remove this attribute from the generated assembly because it is not needed at runtime.

Regarding the last point, I don't understand it. Can you elaborate?

**Comment by HaloFour** [comment]
> They would be millions of overloads without this feature.

I'd suggest that something is severely wrong with your design if that is the case.

If your use case is specifically trying to emulate partial invocation across an arbitrary number of arguments in any order for functions of any arity, I'd suggest that such a library has no place in .NET and that you'd probably be happier with a different language that supports such a thing.  You'd have better luck suggesting that the language be modified to actually support partial application and currying rather than trying to hack it through some code generation and type erasure to emulate it in your own library.

> Regarding reference to Rolsyn, I think that the assembly containing TypeCalculator1 and the Rolsyn dlls it depends on can be safely removed from the binary folder. Or can't they?

This repo is not specific to Roslyn or any specific C# compiler.  The specification needs to be general purpose.  However, your proposal forces part of the Roslyn API into part of the C# language in such a way that would make it very difficult, if not impossible, for any non-Roslyn compiler to actually implement it.

**Comment by YairHalberstadt** [comment]
@ymassad
>This is one overload of PartiallyInvoke that allows developers to partially invoke a function. Notice how you invoke parameter 5 and then parameter 2. There would be also another overload where the developer would invoke parameter 2 and then parameter 5.

What would you do if TInput2 = TInput5?

Then you would have a genuine ambiguity, no matter what feature you add to the language.

**Comment by YairHalberstadt** [comment]
In fact if any of the type parameters are equal to each other, it is impossible to disambiguate the desired method call.
