### ISSUE TITLE
Why is string.Empty not a const?

### ISSUE THREAD

**Issue by IanKemp** [dotnet/csharplang#2034]
`string.Empty` is a `static readonly` field, not a literal constant. This precludes its use anywhere that requires a compile-time constant, e.g. attribute constructors and default parameters. This is... annoying, to put it mildly. (It also allows the use of reflection to change the value, useful if you hate yourself and/or your colleagues.)

There have been numerous unanswered questions over the years as to **why** this member was declared as a field and not a literal, for example:

* https://stackoverflow.com/questions/507923/why-isnt-string-empty-a-constant
* https://stackoverflow.com/questions/8485515/meaning-of-confusing-comment-above-string-empty-in-net-bcl-source

The general consensus seems to be that `string`, being one of the earliest classes in the Framework, was created before interning was implemented and thus at the time, the use of a field was necessary to prevent duplication of the value. This is supported by a comment by Eric Lippert on a now-deleted answer on that second question:

> I asked one of the C# old-timers over lunch about this and he did not recall specifically why this decision was made, but conjectured that it had something to do with interning.

A second possibility/reason is in the comment on the field itself: https://referencesource.microsoft.com/#mscorlib/system/string.cs,73

> We need to call the String constructor so that the compiler doesn't mark this as a literal.
> Marking this as a literal would mean that it doesn't show up as a field which we can access
> from native.

This seems to imply that constants cannot be accessed from native code, which doesn't make much sense to me (although I am hardly an expert on native). Even Jon Skeet doesn't know: https://stackoverflow.com/questions/8462697/what-are-native-and-literal-keywords/8462706#comment10464457_8462706

> I don't know - it doesn't make much sense to me, to be honest. I believe it's talking about access from native code, rather than support for native types, but I don't know the details behind the comment.

At the end of the day my questions is pretty simple:

1. If `Empty` had never existed on `System.String` and was being considered for addition today, would it be added as a field or a const? Keeping in mind the (apparent) necessity for access from native code.
2. If the answer to (1) is "const", what would prevent or preclude retrofitting `string.Empty` to be a const now? (I suspect that the answer may differ between Framework and Core, if so please provide that information.)

**Comment by YairHalberstadt** [comment]
I don't know if anyone is using reflection on string.Empty, but if they are, this would be a breaking change.

**Comment by IanKemp** [comment]
> I don't know if anyone is using reflection on string.Empty, but if they are, this would be a breaking change.

I can't see anyone doing that for anything approaching a good reason.

**Comment by YairHalberstadt** [comment]
True.
Is it possible that anyone's using it for a bad reason though? It would only cause a runtime error in that case.The risk is very slight, but the advantages are too.

**Comment by YairHalberstadt** [comment]
More worrying l, it would be a binary (but not source) breaking change on pretty much every single project.

**Comment by benaadams** [comment]
> I don't know if anyone is using reflection on string.Empty, but if they are, this would be a breaking change.

Its explicitly disallowed on .NET Core 3.0 and will throw an exception https://github.com/dotnet/coreclr/issues/21268

**Comment by benaadams** [comment]
I can't migrate it :)

Might be easier to open new issue there as its about api (and effecting all languages) rather than a C# specific thing.

**Comment by IanKemp** [comment]
> I can't migrate it :)
> 
> Might be easier to open new issue there as its about api (and effecting all languages) rather than a C# specific thing.

Done: https://github.com/dotnet/corefx/issues/33765
