### ISSUE TITLE
[Proposal] [Syntax Sugar] Implement this new switch syntax sugar

### ISSUE THREAD

**Issue by ryancdotnet** [dotnet/csharplang#2037]
# A New Syntax for Switch

The switch statement is ready for a syntactical sugar overhaul. Or at least, an alternative for those who prefer one.

## New Syntax
```c#
switch (vehicleType)
{
    VehicleType.Truck
    {
        //logic
    }
    VehicleType.Car
    {
        //logic
    }
    VehicleType.EighteenWheeler,
    VehicleType.MegaHauler
    {
        //BIG logic
    }
    VehicleType.CompactCar
        return "CompactCar";
    default
    {
        throw new NotSupportedException("I don't know what it is you're drivin, mate.");
    }
}
```

## Current Syntax
Compare to the current syntax:
```c#
switch (vehicleType)
{
    case VehicleType.Truck:
        //logic
        break;
    case VehicleType.Car:
        //logic
        break;
    case VehicleType.EighteenWheeler:
    case VehicleType.MegaHauler:
        //BIG logic
        break;
    case VehicleType.CompactCar:
        return "CompactCar";
    default:
        throw new NotSupportedException("I don't know what it is you're drivin, mate.");
}
```

While the new syntax is more lines, it is, in my opinion, cleaner, easier to read, uses fewer specialized keywords, less bug-prone, and sticks with the already understood notion that brackets in C# mean scope.

Keyword and special character usage by example:
New Syntax = `switch { } ( ) default ; ,`
Old Syntax = `switch { } ( ) default ; case break :`

While I am not proposing to eliminate the old syntax, I am asking that this alternative be made available for those who wish to take advantage of it.

**Comment by Unknown6656** [comment]
Are you aware that the LDT (language design team) already wants to introduce `switch`-expressions with an overhauled syntax as an alternative to the "traditional" `switch`-statement?

https://neelbhatt.com/2018/05/19/c-8-0-expected-features-part-iii-switch-statments/

**Comment by ryancdotnet** [comment]
I recently learned about it. But that is not quite what I'm asking for. Switch-expressions really seem valuable when you are always returning. My syntax suggestion allows for traditional control flow, but removes the clutter of "case", "break", and ":", and sticks with naturally-understood concepts such as brackets for scope.

**Comment by CyrusNajmabadi** [comment]
Sounds like six of one, half dozen of another.

**Comment by ryancdotnet** [comment]
> Sounds like six of one, half dozen of another.

Bingo! 😃 

Quite literally exactly. Some folks like sugar, some don't. Choice is good. Too much choice is, IMO, not good. But I feel there is plenty of precedent for alternative coding styles with C#, and this suggestion is not outside the bounds of possibility.

The only way I could see this suggestion gaining traction is through public interest. i.e. this post. I also will not ignore the fact that the beauty of this alternative syntax is a purely subjective opinion held by myself, and may stay that way. 😄 

Thanks for the feedback everyone.

**Comment by YairHalberstadt** [comment]
Closing as the team has championed an overhaul of switch statements, including the removal of `case`, and `break` in https://github.com/dotnet/csharplang/issues/3038
