### ISSUE TITLE
Champion "Nullable type patterns"

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2039]
We currently have declaration patterns that match any value of a type except null

 ``` c#
if (o is string s) ...

if (o is int i) ...
```

but we do not currently permit a nullable type (value or reference) because declaration patterns do not match null

 ``` c#
if (o is string? s) ... // error

if (o is int? i) ... // error
```

However, we *could* permit these syntactic forms, with the meaning that the type of the variable is nullable, and the pattern will match something of that type *including null*.

**Comment by alrz** [comment]
@YairHalberstadt  I can think of one case:
```
class Foo : Base {}
class Bar : Base {}
class Base {}
class C {
     public Base? P { get; }
}

if (c.P is Foo? foo) // if P is Foo or otherwise empty.
```

**Comment by YairHalberstadt** [comment]
@alrz
But if an instance of Base is null, that is very different to it being Foo. At the very least I would want you to explicitly state your intentions that you want to treat null and Foo as the same.

**Comment by alrz** [comment]
Depends on what you're trying to do but I'd agree the null case is likely to be a different branch altogether.

**Comment by DavidArno** [comment]
If I had the following class:
```cs
class Foo<T> where T : class?
{
    public void Bar(T p)
    {
        if (p is T p2)
        {
            Console.WriteLine($"res={p2}");
        }
        else
        {
            Console.WriteLine("no match");
        }
    }
}
```
and I created an instance, `var stringFoo = new Foo<string?>()`, what would be the result of calling `Bar(null)`? Would that `if (p is T p2)` respect the fact that `T` is `string?` and thus match the `null`, or would I have to modify the line to `if (p is T? p2)`?

**Comment by Richiban** [comment]
To reply to @YairHalberstadt, I think that this is necessary, since this is not currently allowed:

```csharp
	object o = null;
	
	if(o is string s || o is null)
	{
            // Do something with s which is a string or null
	}
```

So, without this feature, it's currently not possible to write the above code since `s` is unassigned according to the compiler.

**Comment by YairHalberstadt** [comment]
@DavidArno
I don't see how that could possibly work without runtime changes.

**Comment by DavidArno** [comment]
@YairHalberstadt, which option couldn't work without a runtime change? Or are you saying this feature couldn't work at all with generics without a runtime change? If the latter, then I really don't see any worthwhile use case for this.

**Comment by YairHalberstadt** [comment]
@Richiban
```csharp
var s = a as string;
if(s != null || a == null)
```
Whilst slightly longer, this is at least clear about intentions in the rare cases you would want to do this.

**Comment by alrz** [comment]
you don't need to fallback to `as`
```cs
if !(a is string s) s = null;
var x = s.Length; 
```
This is interesting because `s` is effectively a `string?` now. Turns out it's not handled in NRT yet.

**Comment by alrz** [comment]
Scratch that, it'll assign null on non-null `a` as well.

**Comment by YairHalberstadt** [comment]
What would be the behaviour with nullable value types:

```csharp
String? str = null;
object obj = str;

if(obj is int?) //Is this true or false?
```

**Comment by gafter** [comment]
> What would be the behaviour with nullable value types:

The difference in behavior between `o is int?` and `o is int? x` when `o` is `null` (the former is `false` while the latter is proposed to be true) is one of the most compelling reasons *not* to do this.

**Comment by HaloFour** [comment]
I don't think that this is particularly necessary, or even makes much sense.  `null` has no type, so it's not like you can switch on the theoretical type of the variable if it happens to be `null`.  I expect that given such a feature that people would try to do something like the following and be surprised when it doesn't work as they might expect:

```cs
public void PrintSomething(object o) {
    if (o is string? s) Console.WriteLine("Foo!");
    if (o is Person? p) Console.WriteLine("Bar!");
    Console.WriteLine("Baz!");
}

string s = null;
Person p = null;
PrintSomething(s); // prints Foo
PrintSomething(p); // also prints Foo
```

**Comment by YairHalberstadt** [comment]
@HaloFour
Exactly my concerns, but you articulate things far better than I do.

**Comment by TheUnlocked** [comment]
> The difference in behavior between `o is int?` and `o is int? x` when `o` is `null` (the former is `false` while the latter is proposed to be `true`) is one of the most compelling reasons _not_ to do this.

I think that if language features had been introduced in a different order such that non-nullable reference types existed before this form of pattern matching, it would make sense for `int?` to match `null`. However, given how the language works now, despite how it ideally _should_ work, I agree that the harm of inconsistency or a breaking change far outweigh the benefits of this proposal.

**Comment by jnm2** [comment]
> At the very least I would want you to explicitly state your intentions that you want to treat null and Foo as the same.

This, exactly. I recall doing this kind of check several times, where the same branch handles nulls and instances of a specific type, but it's so rare that it's clearer to be explicit.

**Comment by willard720** [comment]
I think it would make more sense for `x is int? y` to return false if it is `null`, seeing as, just because it's an `int?`, it's not in any usable form that we would most likely want to use.

**Comment by gafter** [comment]
@willard720 We already have a syntax for that.  It is `x is int y`.  This proposed syntax would be for a different semantics, which, although you might not likely want to use it, someone else might.  However, I too am not sure that it is likely enough to warrant the addition of this as a feature.

**Comment by TessenR** [comment]
> > What would be the behaviour with nullable value types:
> 
> The difference in behavior between `o is int?` and `o is int? x` when `o` is `null` (the former is `false` while the latter is proposed to be `true`) is one of the most compelling reasons _not_ to do this.

@gafter Isn't there exactly the same issue with reference types as well?
The following expression is currently valid in C#8 preview and returns `2` if `x` is `null`
```cs
x is string? ? 1 : 2
```

it would be rather strange if `x is string? _ ? 1 : 2` will return `1` instead.

It looks like the nullable reference types feature's design should be finalized with this proposal in mind or we might end up with rather frustrating behavior for the backward compatibility reason.
Although it will be no less bizarre if `x is string?` will accept nulls but `x is int?` won't...

**Comment by RobotAL76** [comment]
Agree with @HaloFour 

Maybe my understanding of `Reference Nullable Types` is not fully clearly but seems that the rare scenario exists which demonstrates doubtful consistency of the proposal.

```c#
object? o = GetObject();
Persons[] persons = GetPersons();

if (o is Person p)
{
   // do something with p
 
   p = persons.First(); // reuse/reassign the variable [non null]
 
   // do something with p
}
```
Now, try to slightly change the code
```c#
if (o is Person p)
{
   // do something with p
 
   p = persons.FirstOrDefault(); // compiler warning about possible null
 
   // do something with p
}
```
Ok, to avoid the warning we want tell the compiler that `p` may be null (nothing about pattern matching)
```c#
if (o is Person? p)
{
   // do something with p
 
   p = persons.FirstOrDefault(); // no warning
 
   // do something with p
}
```
According current proposal we got invalid logic [the constantly `true` condition] and should significantly reformat the code because adding of `?` to the type definition means "allows to be null for variable **and something else into pattern matching context**".

If you see any mistakes at the provided sample, please, describe them.

**Comment by gafter** [comment]
OK, I'm not convinced this is particularly useful, so I'm withdrawing it as a proposal.
