### ISSUE TITLE
ReadOnlySpan should allow ref return of readonly structs

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/csharplang#2040]
# Issue

Returning `readonly struct` from `ReadOnlySpan` as `ref` should be possible.

# Why I want it

- I have several different `classes`. Some of them may modify elements's fields in place, some add/replace elements, some read copy of elements, some obtain readonly ref onto elements. I want make it clear what are capabilities of each of this class to allow write correct code. I want to create `properly typed` sandboxes of developers.

- I want to have view onto same block of memory(array), not copy. I do data oriented design with zero GC by allocating most of memory on start for my game.

- I was inspired by Rust memory management [Data Oriented GUI in Rust by Raph Levien](https://www.youtube.com/watch?v=4YTfxresvS8).

- With C# 8 interfaces with implementation I can do Rust design, I want to emulate Rust memory management either.

- I do not want copy large structs to read (10+ properties). 

# Considerations

- I do not understand, why I cannot get ref to readonly struct from readonly span, because I cannot modify that struct anyway, but want to read on its members.

- Not sure about non GUI or non [ECS](https://en.wikipedia.org/wiki/Entity%E2%80%93component%E2%80%93system) cases if any uses. I want to have previous state of `world` readonly provided with new state of `world` which is read write (in some cases only working with existing elements and in some cases possibility to add/"remove").

- Sometimes I even may want to be very sloppy allowing concurrent writes and some fields reads from readonly refs to get some inputs into neural network (let bots to be stupid a little for some performance gain). I want to run some of my `classes` in parallel.

# Example

```csharp
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace design
{
    [StructLayout(LayoutKind.Sequential)]
    readonly struct ReadPosition
    {
        public readonly float x;
        public readonly float y;
        public readonly float z;
    }

    [StructLayout(LayoutKind.Sequential)]
    struct Position
    {
        public float x;
        public float y;
        public float z;
    }

    public static class Test
    {
        public static unsafe void Run()
        {
            var positions = new  Position[ushort.MaxValue];
            positions[0] = new Position {x = 13, y = 42, z = 123};
            
            // compiles fine - OK
            Span<Position> writeWrite = new Span<Position>(positions);
            ref Position a1 = ref writeWrite[0];
            a1.x = a1.x + 1;

            // fails to compile - OK
            ReadOnlySpan<Position> readWrite = new Span<Position>(positions);
            ref Position a2 = ref readWrite[0];//Cannot use property 'ReadOnlySpan<Position>.this[int]' as a ref or out value because it is a readonly variable 
            a2.x = a2.x + 1;

            fixed (void* positionsPointer = positions)
            {
                // fails to compile - OK
                Span<ReadPosition> writeRead = new Span<ReadPosition>(positionsPointer, positions.Length);
                ref ReadPosition a3 = ref writeRead[0];
                a3.x = a3.x + 1; // A readonly field cannot be assigned to (except in a constructor or a variable initializer)

                // fails to compile - BAD, I want it because readonly struct
                ReadOnlySpan<ReadPosition> readRead = new Span<ReadPosition>(positionsPointer, positions.Length);
                ref ReadPosition a4 = ref readRead[0]; // Cannot use property 'ReadOnlySpan<ReadPosition>.this[int]' as a ref or out value because it is a readonly variable
                a4.x = a4.x + 1;// fails and it is fine

                // I WANT READONLY SPAN TO REF READONLY STRUCT TO AVOID STRUCT COPY IF STRUCT IS VERY LARGE (10+ fields)
            }
        }
    }
}
```

**Comment by NinoFloris** [comment]
There are a few problems with this, 1. the CLR generics restriction of not allowing ref Type arguments, and 2. the C# language restriction of also not allowing ref-like (Span etc) type arguments either, mainly because the CLR does not even support the weaker versions. 

https://github.com/dotnet/csharplang/blob/54fb167419f8fb901df1c4c838964d3f771510bc/proposals/csharp-7.2/span-safety.md

**Comment by dzmitry-lahoda** [comment]
@NinoFloris , I do not understand what you are saying. May be I can clarify.

Now:
1. span + ref return possible.
2. readonly span + ref return is not possible.

I want:
1. span + ref return possible
2.1 readonly span + ref return is not possible if struct is writetable.
2.2 *NEW*  readonly span + ref return is possible if struct is readonly.

Question:
Is 2.2 unsound/leaky? 

As I see you say that 2.2 not possible because of both CLR and C#. But I doubt that CLR has restrictions. Probably C# only restrictions do apply. I just cannot grasp what exactly CLR prevents from your answer.

**Comment by dzmitry-lahoda** [comment]
```
        class Readonly
        {
            private ReadPosition one;
            public ref ReadPosition this[int index] => ref one;
        }

        class Readonly2
        {
            private ReadPosition one;
            public ref readonly ReadPosition this[int index] => ref one;
        }  
```

```
            // compiles - OK
            var myReadonly = new Readonly();
            ref ReadPosition my = ref myReadonly[0];

            // does not compiles - BAD
            var myReadonly2 = new Readonly2();
            ref ReadPosition my2 = ref myReadonly2[0];
```

So to restate:
- If indexer is `readonly` and `struct` is `readonly` than `ref` should be allowed in above case.

**Comment by dzmitry-lahoda** [comment]
`ref readonly`. Sorry for that. I have not found answer on SO...

**Comment by dzmitry-lahoda** [comment]
С# could tune error message which suggest to mark ref return as readonly as part of fix so:)
