### ISSUE TITLE
Consider message tuning for readonly ref returns

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/csharplang#2041]
For case #2040 error message could be changed from:

`Cannot use property 'ReadOnlySpan<ReadPosition>.this[int]' as a ref or out value because it is a readonly variable`

into

`Cannot use property 'ReadOnlySpan<ReadPosition>.this[int]' as a ref or out value because it is a readonly variable. Consider set return as readonly`

or like. 

# Why

`ref` and `readonly` are separate words. I read current error message as if it totally impossibly to `ref` return from `readonly` indexer.  I hope people like me would be guided to add `readonly` to return.

**Comment by YairHalberstadt** [comment]
I believe this issue would be best placed in Roslyn.

**Comment by dzmitry-lahoda** [comment]
&

**Comment by dzmitry-lahoda** [comment]
I think will try to added pull request to Roslyn when will have time.
