### ISSUE TITLE
Error CS8636  Explicit application of 'System.Runtime.CompilerServices.NonNullTypesAttribute' is not allowed.

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/csharplang#2048]
I'm trying to experiment with the new non-null reference types in the VS2019 preview. Everything I can find says that you need to add `[module:NonNullTypes]` to enable the feature in the compiler. However, I'm getting a compiler error:
`Explicit application of 'System.Runtime.CompilerServices.NonNullTypesAttribute' is not allowed.`

Can someone explain what I need to do? This is very confusing.

**Comment by MarkPflug** [comment]
Figured out that I need to add: `<NullableReferenceTypes>true</NullableReferenceTypes>`.

https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types

Not the easiest thing to find. I understand that this is just a preview. It would be nice if "NullableReferenceTypes" showed up in the intellisense listing in the csproj file at least.

**Comment by jmarolf** [comment]
Your project file needs to have to following additional properties added

```XML
<LangVersion>8.0</LangVersion>
<NullableReferenceTypes>True</NullableReferenceTypes>
```

So and example project file would be

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <NullableReferenceTypes>True</NullableReferenceTypes>
  </PropertyGroup>

</Project>
```

**Comment by MarkPflug** [comment]
Finding that documentation was not straightforward. I imagine a lot of people will be installing VS2019 preview just to tinker with this language feature. Would it makes sense for the "new C# project" template to have both of these things enabled by default. I understand why it isn't enabled by default, as it could break existing codebases, but for file=>new project I would imagine most people would want to start with it "on". 
With VS2019 release will the default LangVersion be 8.0? It seems odd that in the preview it is still defaulting to 7.0.

**Comment by yaakov-h** [comment]
> With VS2019 release will the default LangVersion be 8.0?

I believe it will be 7.0 still. The last statement was that C# 8.0 in it's final form will ship some time after VS2019 RTM does.
