### ISSUE TITLE
Discussion: nullable refernce types

### ISSUE THREAD

**Issue by RamanJindal** [dotnet/csharplang#2050]
Team, 
Have few clarifications on nullable reference types.
-  In OOPs, intent of assigning null to a reference type variable is to indicate that object is not initialized/memory is not allocable for object variable. Equivalent to null pointer. Hence, use of constructors/new operator. Now, we are saying reference type cannot/should not be assigned null. Is not it conflicting with how reference types are supposed to work?
- If compiler can check 'string? s' is nullable reference type and can give warning to check for null before dereferencing. Then can not same behavior be implemented for reference types, instead of introducing nullable reference types?

Thanks

**Comment by CyrusNajmabadi** [comment]
> Now, we are saying reference type cannot/should not be assigned null.

No one is saying that.  What is being said is:  If intend for a storage location to be able to store null, then indicate that that is your intent.  By indicating your intent (either that location does or does not store null) the compiler can provide you with information about when you violate your stated intent.

 > If compiler can check 'string? s' is nullable reference type and can give warning to check for null before dereferencing. Then can not same behavior be implemented for reference types, instead of introducing nullable reference types?

This question is a bit confusing. 

"Then can not same behavior be implemented for reference types"

Yes.  In the exact same way.  Just as you marked `string?` as allowing null, you can do the same with any other reference type.  Just do `WhateverType?`

**Comment by HaloFour** [comment]
@RamanJindal

> Then can not same behavior be implemented for reference types, instead of introducing nullable reference types?

Technically yes, but it can't easily do that at the boundaries (parameters, return values, fields).  So you'd need something at those boundaries to better declare intent to the compiler.  For existing analyzers such as Resharper this is done with attributes.  Encoding it in the language makes it a lot less verbose.  Allowing for the same notation for locals keeps things consistent and allows you to warn on nullable assignments earlier.

**Comment by RamanJindal** [comment]
Thanks all for the clarifications. Closing the discussion.
