### ISSUE TITLE
Rang endpoint conditions

### ISSUE THREAD

**Issue by shaair** [dotnet/csharplang#2056]
Can range endpoints take condition? Like

foreach (var name in names[1..(names.length == 3? 2: 1)])

**Comment by willard720** [comment]
#185

**Comment by willard720** [comment]
@svick How does that work? Do those method names have to be those exact names or something? Also, when was the `..` operator added to C#?

**Comment by CyrusNajmabadi** [comment]
> Do those method names have to be those exact names or something?

Which method names?

> Also, when was the .. operator added to C#?

It's an 8.0 feature.

**Comment by CyrusNajmabadi** [comment]
> @svick How does that work?

When you write `expr1..expr2` this is just translated into `Range.Create(expr1, expr2)`.  It doesn't really matter what is in expr1 or expr2, as long as it would be legal to rewrite it as `Range.Create(expr1, expr2)`.  

In your case, your two expressions are `1` and `(names.length == 3? 2: 1)`.  So this is effectively compiled as:  `Range.Create(1, (names.length == 3? 2: 1))`.

**Comment by svick** [comment]
@willard720 

> Do those method names have to be those exact names or something?

If you're talking about the methods in `Range` and `Index` in my SharpLab, then yes: those are methods required by the compiler to compile the code and they have to have those exact names. Normally, they're part of .Net, so you don't have to write them yourself. But if you're using a pre-release compiler on a release framework (which is what SharpLab does), you do.
