### ISSUE TITLE
nullable reference types feature does not warn when an explicit cast is performed

### ISSUE THREAD

**Issue by DurgaPrasadReddyV** [dotnet/csharplang#2070]
Hi Team

Looks like the compiler is not throwing an error when a nullable variable is explicitly type casted to a non-nullable variable as shown inline.

![nrt test](https://user-images.githubusercontent.com/25372077/49874017-5957f280-fe43-11e8-819a-d643578a8c73.JPG)

A "InvalidOperationException" exception is raised during runtime, however there isn't any error/warning shown during compilation.

**Comment by HaloFour** [comment]
I'm going to assume that this is because `int?` is not a reference type and warnings for explicitly casting a nullable value type to a value type aren't a part of this feature.

**Comment by DurgaPrasadReddyV** [comment]
Oh, I see now.
My bad, nullable types are structs which are value types.
It would have been great if nullable types were also considered. Argh.

**Comment by orthoxerox** [comment]
@DurgaPrasadReddyV check out the meeting minutes in the repo, the team is considering extending the feature to nullable value types.
