### ISSUE TITLE
Enumerate used classes in using namespaces statement .

### ISSUE THREAD

**Issue by alexpantyukhin** [dotnet/csharplang#2078]
## Motivation: 
This idea came from from java and python. This feature helps to show strictly what is used and what namespaces it come from.
Especially when serfing code files not from IDE (some web resource github gitlab...)

## Example:
```csharp
using System with Console, Random;

namespace HelloWorld
{
    public class Hello 
    {
        public static void Main() 
        {
            var rInt = (new Random()).Next(0, 100);
            Console.WriteLine("Random value is: " + rInt.ToString());

        }
    }
}
```

Default behavior without `with` will work as it is now (import all classes, enums from namespaces) and this change will not break the existings programs.

**Comment by CyrusNajmabadi** [comment]
How is this different from:

```c#
using Console = System.Console;
using Random = System.Random;
```

?

**Comment by alexpantyukhin** [comment]
@CyrusNajmabadi the difference there is that in suggested approach only one statement is used. For example if you want to import many classes you can do it in one row compactly. IMHO more clear for reading.

**Comment by CyrusNajmabadi** [comment]
That seems like a super niche reason to need this to be at the language level.

**Comment by svick** [comment]
@alexpantyukhin If you want to be explicit, you have a syntax for that. If you want to be compact, you have a syntax for that. The thing that's missing is a syntax that's both explicit and compact. Considering that the explicit syntax is almost never used for this purpose, I think that shows that there isn't much point in adding a more compact syntax for this.

**Comment by alexpantyukhin** [comment]
@svick Yes, you are right that it's used very seldom. But I believe that implicit is better than explicit and using short syntax for that could be good. Would be great to see approximately how many people like to use it.

**Comment by willard720** [comment]
@alexpantyukhin Well, C# strongly disagrees. It is a very explicit language, look at casting for example. Implicit casting is very rare even when it can't go wrong. 

Also, most C# devs use `private` when they don't need to, because we also prefer explicit-ness in C#.

**Comment by markusschaber** [comment]
> But I believe that implicit is better than explicit...

I strongly disagree here. And I'm not the only one. I'm a big fan of the [Zen of Python](https://www.python.org/dev/peps/pep-0020/) which clearly states: "Explicit is better than implicit." :-)

**Comment by alexpantyukhin** [comment]
Okay) got it! :) Thank all for opinon. I guess it's okay to close the issue.
