### ISSUE TITLE
Adding a 'yield all' keyword

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/csharplang#2079]
Currently we have a `yield return` and a `yield return`. While working with these I noticed that it is often needed to return all items of another `IEnumerable<T>` which results in code like
```
foreach (string s in someIEnumerableOfStrings) {
   yield return s;
}
```
I think a shortcut is needed for doing so:
```
yield all someIEnumerableOfStrings;
```
This would make the code far more readable, and would greatly improve working with `yield`.

**Comment by ufcpp** [comment]
dup of https://github.com/dotnet/csharplang/issues/378

**Comment by TheMinefighter** [comment]
@DaZombieKiller I think that might get a bit confusing..

**Comment by TheMinefighter** [comment]
@ufcpp It is the same feature with a different name from a completely different POV (which is probably the reason I weren't able to find that during my research)
