### ISSUE TITLE
Proposal: allow currently mandatory, but syntactically redundant, braces to be optional

### ISSUE THREAD

**Issue by DavidArno** [dotnet/csharplang#208]
- [ ] Proposal added (draft created at [Redundant-brace-removal.md](https://github.com/DavidArno/csharplang/blob/Redundant-brace-removal/proposals/Redundant-brace-removal.md), pull request [#207](https://github.com/dotnet/csharplang/pull/207))
- [ ] Championed
- [ ] Discussed in LDM
- [ ] Decision in LDM
- [ ] Finalized (done, rejected, inactive)
- [ ] Spec'ed

This proposal pulls together a couple of related proposals around removing the need to use `{}`, rather than `;` to terminate a declaration, along with one new opportunities to do so, in the following areas:
* [Single namespace in a file declarations](https://github.com/dotnet/csharplang/issues/137#issuecomment-281794438)
* [Constructors that just call `this` or `base`](https://github.com/dotnet/roslyn/issues/17306)
* Empty interface declarations

Please note, this proposal is a replacement for #181, which included removing braces in properties. This was an unpopular suggestion, so it was closed and that suggestion removed for this proposal.

**Comment by eyalsk** [comment]
I wouldn't mind having a `namespace` statement which can really help reduce nesting in some cases but I think that having namespaces as part of the type is a bit too much, at least for me. :)

Overall, I like the suggestions.

**Comment by DavidArno** [comment]
@eyalsk,

I personally feel that having the namespace as part of the type name offers a good way of combining the two pieces of closely related information into one. I'd be interested to know therefore, the details behind you not being keen on it. Is it a gut feeling/style thing for you, or is there practical reasons to not like it too?

**Comment by eyalsk** [comment]
@DavidArno 

> Is it a gut feeling/style thing for you

This. :)

**Comment by alrz** [comment]
namespace declaratives do not belong to this category as it's not just removing braces from the declaration. All preceding types would belong to that namespace and it wouldn't be empty.

Removal of braces from classes and structs is a part of record proposal.

So this is just about removing braces from empty interfaces and constructors which is very similar to already closed https://github.com/dotnet/roslyn/issues/8985. 
Also, from comments in that thread:

>Really? A language proposal to save one character?

**Comment by MgSam** [comment]
While superficially somewhat similar, do these proposals really belong in a single issue? I think they are and should be separate discussions / units of work (if they ever make it that far).

**Comment by scottdorman** [comment]
Still not a fan of the namespace declaration bits, but definitely think https://github.com/dotnet/roslyn/issues/17306 has merit. Shouldn't that be pulled over as it's own proposal? By combining them, I think there's too much risk that it becomes an "all or nothing" sort of thing.

**Comment by DavidArno** [comment]
I'm planning on closing this proposal as the prevailing view seems to be that these three suggestions should not be bundled into one, but should exist as separate proposals. Please speak up if you disagree, otherwise I'll close this tomorrow.
