### ISSUE TITLE
Allow use of Decimal type in enums

### ISSUE THREAD

**Issue by john-h-k** [dotnet/csharplang#2080]
Allow use of `Decimal / decimal` type in enums, as such:
```
public enum MyEnum : decimal
{ }
```

The primary motivation for this is that it would allow easy implementation of `FlagsAttribute` style enum to have 128 indepedently XOR-able flags, as opposed to the current 64 bit limit (`Int64 / long`)

**Comment by tannergooding** [comment]
This would require a runtime change in order for it to be a valid `enum` type (and meet the `System.Enum` constraint).

**Comment by YairHalberstadt** [comment]
If you genuinely need more than 64 different values for a flags enum, perhaps it would be ideal to try and break it up into 2 flags?

**Comment by fanoI** [comment]
Probably will be better to have a proper (U)Int128 type with full language support (ability to declare constant literals, to declare them in enum's and so on...).

**Comment by yaakov-h** [comment]
@YairHalberstadt we'll just have to build 128-bit processors then...

**Comment by YairHalberstadt** [comment]
@yaakov-h 
Sounds like a plan
