### ISSUE TITLE
Unnecessary Using elimination to be automatic.

### ISSUE THREAD

**Issue by josejmoran** [dotnet/csharplang#2083]
We have seen it. The using statements that are not needed are grayed out. Can the action that grayed out this lines be updated to delete those lines instead?

That will be great.

**Comment by YairHalberstadt** [comment]
This is relevant to Visual Studio, not the C# language. As such, you can suggest it to the visual studio team. Alternatively you could write a Roslyn analyser to do this for you as a code fix.

**Comment by theunrepentantgeek** [comment]
Some developers write the **using** statements at the top first, so they have Intellisense while they're writing the actual code. Having those statements automatically deleted just because they're not used **_yet_** would be unfriendly.

**Comment by BhaaLseN** [comment]
Or you could just enable "Perform additional code cleanup during formatting: Remove unused usings" under "Text Editor" > "C#" > "Code Style" > "Formatting" > "General". Most people that care about those things hit "Format Document" (Ctrl+E, D or Ctrl+K, D depending on your settings) anyways, or use extensions that do it automatically on save.

**Comment by PathogenDavid** [comment]
>use extensions that do it automatically on save.

I've never used this feature of it, but one such extension is [Power Commands for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.PowerCommandsforVisualStudio):

![image](https://user-images.githubusercontent.com/278957/50069520-145bf500-0190-11e9-90b8-2388327f63a0.png)

**Comment by gafter** [comment]
Since this is not a language request for C#, closing.  If you want to reopen it, I recommend the Roslyn repo.  However, I don't think we are likely to have VS just change your code without your consent, so it seems unlikely.
