### ISSUE TITLE
Open LDM Issues in Pattern-Matching (v2)

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2095]
# Open LDM Issues in Pattern-Matching

This is a summary of the remaining open issues for pattern-matching in C# 8.

---
### Reserve `and` and `or` in patterns (open)

In anticipation of possibly permitting `and` and `or` as pattern combinators in the future, we should forbid (or at least warn) when these identifiers are used as the designator in a declaration or recursive pattern.

See also https://github.com/dotnet/roslyn/issues/33425

***Resolution:*** We did not do this in C# 8.0.

---
### Propose to change precedence of switch expression to *primary* (open)

The switch expression is currently at *relational* precedence.  I propose to change it to *primary* precedence.  See https://github.com/dotnet/csharplang/issues/2331 for details.

***Resolution:*** It gets a new precedence just looser than primary.

---
### Single-element positional deconstruction (open)

The current LDM decision on single-element positional deconstruction pattern is that the type is required.

This is particularly inconvenient for tuple types and other generic types, and perhaps impossible for values deconstructed by a dynamic check via `ITuple`.

We should consider if other disambiguation should be permitted (e.g. the presence of a designation).

``` c#
if (o is (3) _)
```

**Resolution 2018-10-10:** Discussed but not resolved.

---
### Disambiguating deconstruction using parameter names (open)

We could permit more than one `Deconstruct` method if we permit disambiguating by parameter names.

``` c#
class Point
{
    public void Deconstruct(double Angle, double Length) => ...;
    public void Deconstruct(int X, int Y) => ...;
}

Point p = ...;
if (p is (X: 3, Y: 4)) ...;
```

Should we do this?

***Resolution:*** No, not at this time.

---
### var pattern for 0 and 1 elements (open)

The var pattern currently requires 2 or more elements because it inherits the grammar for *variable_designation*. However, both 0-element and 1-element var patterns would make sense and are syntactically unambiguous.

``` c#
public class C {
    public void Deconstruct() => throw null;
    public void Deconstruct(out int i) => throw null;
    public void Deconstruct(out int i, out int j) => throw null;
    void M() {
        if (this is var ()) { }          // error
        if (this is var (x1)) { }        // error
        if (this is var (x2, y2)) { }    // ok
    }
}
```

I propose we relax the grammar to permit 0-element and 1-element var patterns.

We could do the same for deconstruction.

***Resolution:*** Approved for patterns.  Left to future consideration for deconstruction.

---
### Kind of member in a property pattern (open)

A property pattern `{ PropName : Pattern }` is used to check if the value of a property or field matches the given pattern.

Besides readable properties and fields, what other kinds of members should be permitted here?
- An indexed property? Possible indexed with a constant?
- An event reference?
- Anything else?

***Resolution:*** None of these at this time.

---
### Restricted types (open)

A recent bug (https://github.com/dotnet/roslyn/pull/27803) revealed how pattern matching interacts with restricted types in interesting ways (when doing type checks).
We should discuss with LDM on whether this should be banned (like pointer types), and if there are actual use cases that need it.

***Resolution:*** Pointers actually work, e.g. `p is null` or `p is var x`.  Restricted types work too.  No action.

---
### Matching using ITuple (open)

I assume that we only intend to permit matching using `ITuple` when the type is omitted?

``` c#
IComparable x = ...;
if (x is ITuple(3, 4)) // (1) permitted?
if (x is object(3, 4)) // (2) permitted?
if (x is SomeTypeThatImplementsITuple(3, 4)) // (3) permitted?
```

***Resolution:*** Confirmed.

---
### Matching using `ITuple` in the presence of an extension `Deconstruct` (needs proposal)

When an extension `Deconstruct` method is present and a type also implements the `ITuple` interface, it is not clear which should take priority. I believe the current LDM position (probably not intentional) is that the extension method is used for the deconstruction declaration or deconstruction assignment, and `ITuple` is used for pattern-matching. We probably want to reconcile these to be the same.

``` c#
public class C : ITuple
{
    int ITuple.Length => 3;
    object ITuple.this[int i] => i + 3;
    public static void Main()
    {
        var t = new C();
        Console.WriteLine(t is (3, 4)); // true? or a compile-time error?
        Console.WriteLine(t is (3, 4, 5)); // true? or a compile-time error?
    }
}
static class Extensions
{
    public static void Deconstruct(this C c, out int X, out int Y) => (X, Y) = (3, 4);
}
```

**Discussion 2018-10-24**: No conclusion. We need a proposal to consider.

***Resolution:*** The current LDM position is confirmed.

---
### Switch expression as a statement expression (closed)

It has been requested that we permit a switch expression to be used as a statement expression. In order to make this work, we'd
1. Permit its type to be `void`.
2. Permit a switch expression to be used as a statement expression if all of the switch arm expressions are statement expressions.
3. Adjust type inference so that `void` is more specific than any other type, so it can be inferred as the result type.

**Resolution 2018-10-10:** Yes! This requires a more precise spec, and it needs to handle `a?.M()` where `M()` returns an uncontrained `T`.  Excluded from C# 8.0.

---
### ITuple vs unconstrained type parameter (closed)

Our current rules require an error in the following, and it will not attempt to match using `ITuple`. Is that what we want?

``` c#
    public static void M<T>(T t)
    {
        Console.WriteLine(t is (3, 4)); // error: no Deconstruct
    }
```

**Resolution 2018-10-24**: Lets keep it an error for now but be open to relaxing it in the future.

---
### Permit a trailing comma in a switch expression (closed)

See https://github.com/dotnet/csharplang/issues/2098

**Resolution 2019-01-09**: Yes.

---
### Rename deconstruct_pattern to positional_pattern (closed)

**Resolution 2019-01-09**: Yes.

---
### Disambiguate declaration patterns with (non-nullable) arrays of nullable type (closed)

The introduction of nullable reference types introduced a breaking change in the parsing of array types. It is recommended that we reconsider the order in which nullable annotations are considered in multidimensional arrays to resolve the ambiguity and permit a compatible implementation.

See https://github.com/dotnet/roslyn/issues/32141

**Partial Resolution per LDM 2019-01-07**: Keep the order of array designators.  But a new syntax resolution rule: following an `is`, `as`, or `new` in an expression, an array type may not end with a `?` unless the `?` is followed by a token that cannot start an expression.  The `?` token (if not considered to be part of the array specifier) will then naturally be considered to be the conditional operator, which restores compatibility with existing code.

**Resolution 2019-01-09**: Reverted.  We are going with second option in https://github.com/dotnet/roslyn/issues/32141#issuecomment-451801073.  See also the "No way to match a multidimensional array with an inner nullable" issue below.

---
### Should SwitchExpressionException capture an unreified tuple input? (closed)

See https://github.com/dotnet/roslyn/issues/31482

**Resolution 2019-01-09**: Yes.

---
### No way to match a multidimensional array with an inner nullable (closed)

Another small issue with our resolution to See https://github.com/dotnet/roslyn/issues/32141.  How do I write a pattern-matching operation where the type is “an array of a nullable array”?  That would (un)naturally be written
``` c#
if (o is string[][]? s)
```
but we decided that, since there is an identifier after the `?`, the `?` designates the start of a ternary operator and this code is a syntax error.  This is something I think people are likely to want to do (since an array typically may contain nulls), so it would be a shame to disallow it.

**Resolution 2019-01-09**: This (and its extension to a problem in recursive patterns) was the straw that broke the camel's back, and caused us to revisit the interaction of the nullable annotation and array dimension specifiers.  The new resolution is that the `?` annotation is a type constructor that can be applied to array types, and an array type does not have any `?` among its array specifiers.  This is the second option in https://github.com/dotnet/roslyn/issues/32141#issuecomment-451801073.

**Comment by jnm2** [comment]
> I think the disambiguation is fine as long as we don't have parenthesized patterns. 

Without parenthesized patterns, `not`, `and`, and `or` patterns are going to be less useful.

**Comment by gafter** [comment]
@alrz Another reason to disallow that is we can't distinguish between `(int.MaxValue) x` (a declaration pattern) and (System.Int32)Int32.MaxValue` (a constant pattern).

**Comment by qrli** [comment]
> I believe the current LDM position (probably not intentional) is that the extension method is used for the deconstruction declaration or deconstruction assignment

The good side is that extension methods can be opt-in by using namespaces, so we can still choose which one to use. 
Though, adding a `using` may change the meaning of the code silently, which is a bit risky. And it is different behavior than extension method with same name as instance method, where instance method wins.

**Comment by gafter** [comment]
> Right, I think the cast ambiguity has been resolved by LDM before

Yes, but that resolution no longer "works" with relaxed rules for when a single-element positional pattern is permitted.

**Comment by alrz** [comment]
Sure but `(var x) {}` could work if you don't want to spell out the type (or can't, in case it's unspeakable).

**Comment by gafter** [comment]
Added

### Rename deconstruct_pattern to positional_pattern

/cc @jcouv

**Comment by gafter** [comment]
Changed the last item to

### Disambiguate declaration patterns with (non-nullable) arrays of nullable type

The introduction of nullable reference types introduced a breaking change in the parsing of array types. It is recommended that we reconsider the order in which nullable annotations are considered in multidimensional arrays to resolve the ambiguity and permit a compatible implementation.

See https://github.com/dotnet/roslyn/issues/32141

**Comment by gafter** [comment]
Added

### Should MatchFailureException capture an unreified tuple input?

See #31482

**Comment by gafter** [comment]
Added a resolution and a new issue:

### Disambiguate declaration patterns with (non-nullable) arrays of nullable type

The introduction of nullable reference types introduced a breaking change in the parsing of array types. It is recommended that we reconsider the order in which nullable annotations are considered in multidimensional arrays to resolve the ambiguity and permit a compatible implementation.

See https://github.com/dotnet/roslyn/issues/32141

Partial Resolution per LDM 2019-01-07: Keep the order of array designators.  But a new syntax resolution rule: following an `is`, `as`, or `new` in an expression, an array type may not end with a `?` unless the `?` is followed by a token that cannot start an expression.  The `?` token (if not considered to be part of the array specifier) will then naturally be considered to be the conditional operator, which restores compatibility with existing code.

### No way to match a multidimensional array with an inner nullable

Another small issue with our resolution to See https://github.com/dotnet/roslyn/issues/32141.  How do I write a pattern-matching operation where the type is “an array of a nullable array”?  That would (un)naturally be written
``` c#
if (o is string[][]? s)
```
but we decided that, since there is an identifier after the type, the `?` designates the start of a ternary operator and this code is a syntax error.  This is something I think people are likely to want to do (since an array typically may contain nulls), so it would be a shame to disallow it.

**Comment by gafter** [comment]
Changed `MatchFailureException` to `SwitchExpressionException` per https://github.com/dotnet/corefx/issues/33284

**Comment by yaakov-h** [comment]
> `SwitchExpressionException`

Say that ten times fast...

**Comment by alrz** [comment]
>No way to match a multidimensional array with an inner nullable

Once we have parenthesized patterns, you could rewrite it as `o is (string[][]? s)`. that wouldn't be ambiguous because there's no ternary-like syntax in patterns.

**Comment by jcouv** [comment]
@alrz Placing parens like `o is (string[][]? s)` seems wrong. Is this a 1-positional pattern?
Probably needs to be `(o is string[][]? s)`.

**Comment by gafter** [comment]
> that wouldn't be ambiguous because there's no ternary-like syntax in patterns

There is a ternary-like syntax in patterns, because an expression is a pattern (to support constant patterns).

**Comment by alrz** [comment]
@jcouv parens around the whole expression probably wouldn't help because a ternary is still possible further ahead (parens around the pattern would be a new feature).

@gafter right, but I think in the presence of the array type, the parser doesn't expect any ternary at this point.

**Comment by gafter** [comment]
I've marked a number of issues resolved based on today's LDM.  Search for **Resolution 2019-01-09**.

In particular we've changed the interaction of array dimension specifiers and the nullable type syntax.  The new resolution is that the `?` annotation is a type constructor that can be applied to array types, and an array type does not have any `?` among its array specifiers.  This is the second option in https://github.com/dotnet/roslyn/issues/32141#issuecomment-451801073.

**Comment by gafter** [comment]
> @gafter Neal Gafter FTE right, but I think in the presence of the array type, the parser doesn't expect any ternary at this point.

This is one ambiguity:
``` c#
    if (e is int[][]? b // ternary or array of nullable array?
                        : c) 
    if (e is int[][]? b // ternary or array of nullable array?
                        && c) 
```
it gets worse with recursive patterns
``` c#
    if (e is int[][]? (3, 4) // ternary or array of nullable array in a recursive pattern?
                        : c) 
    if (e is int[][]? (3, 4) // ternary or array of nullable array in a recursive pattern?
                        && c) 
```
Note that this could be semantically legal if you write an extension `Deconstruct`.

With the resolution from today's LDM, the nullable annotation for the inner array goes between the `]` and the `[`.
``` c#
    if (e is int[][]? b // obviously ternary
                        : c)
    if (e is int[]?[] b // obviously declaration pattern
                        && c)
    if (e is int[][]? (3, 4) // obviously ternary
                        : c) 
    if (e is int[]?[] (3, 4) // obviously recursive pattern
                        && c) 
```

**Comment by alrz** [comment]
>This is one ambiguity:

I was saying that in a hypothetical parenthesized pattern, you can't have a ternary after `?`.

```cs
if (e is (int[][]? x ...))
```
The possible token after `x` could be only a comma for positional patterns, otherwise, this is definitely a declaration pattern with type `int[][]?`.

**Comment by ufcpp** [comment]
Can `Deconstruct` calls be eliminated if all of the sub-patterns are discard?

```cs
using System;

struct X
{
    // Deconstruct methods with side effects
    public void Deconstruct() => Console.WriteLine("side effect in ()");
    public void Deconstruct(out int x)
    {
        Console.WriteLine("side effect in (int)");
        x = 0;
    }

    public void Deconstruct(out int x, out int y)
    {
        Console.WriteLine("side effect in (int, int)");
        (x, y) = (0, 1);
    }
}

class Program
{
    static int Zero() => new X() switch { () => 0 };
    static int One() => new X() switch { var (_) => 0 };
    static int Two() => new X() switch { (_, _) => 0 };

    static int Zero(object x) => x switch { X() => 0, _ => 1 };
    static int One(object x) => x switch { X(_) => 0, _ => 1 };
    static int Two(object x) => x switch { X(_, _) => 0, _ => 1 };

    static void Main()
    {
        // There is no Deconstruct called, no side effect in VS 2019 Preview 2
        Console.WriteLine(Zero());
        Console.WriteLine(One());
        Console.WriteLine(Two());
        Console.WriteLine(Zero(new X()));
        Console.WriteLine(One(new X()));
        Console.WriteLine(Two(new X()));
    }
}
```

**Comment by gafter** [comment]
Can `Deconstruct` calls be eliminated if all of the sub-patterns are discard?

According to the specification, yes.  See https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md#order-of-evaluation-in-pattern-matching which says in part

> The compiler should not invoke functions that cannot affect the result...

**Comment by gafter** [comment]
Added

---
### Reserve `and` and `or` in patterns (open)

In anticipation of possibly permitting `and` and `or` as pattern combinators in the future, we should forbid (or at least warn) when these identifiers are used as the designator in a declaration or recursive pattern.

See also https://github.com/dotnet/roslyn/issues/33425

**Comment by MohammadHamdyGhanem** [comment]
I posted this in #2268 
While I am reading this example in Docs:
```C#
static string Quadrant(Point p) => p switch
{
    (0, 0) => "origin",
    (var x, var y) when x > 0 && y > 0 => "Quadrant 1",
    (var x, var y) when x < 0 && y > 0 => "Quadrant 2",
    (var x, var y) when x < 0 && y < 0 => "Quadrant 3",
    (var x, var y) when x > 0 && y < 0 => "Quadrant 4",
    (var x, var y) => "on a border",
    _ => "unknown"
};
```

I wondered if it can be shorter and more readable to achive the purpose of pattern matching, so  I suggest this:
```C#
static string Quadrant(Point p) => p switch
{
    (0, 0) => "origin",
    (> 0, > 0) => "Quadrant 1",
    (< 0, > 0) => "Quadrant 2",
    (< 0, < 0) => "Quadrant 3",
    (> 0, < 0) => "Quadrant 4",
    (_, _) => "on a border",
    _ => "unknown"
};
```

**Comment by gafter** [comment]
@MohammadHamdyGhanem That idea is already championed by me at https://github.com/dotnet/csharplang/issues/2115 .

**Comment by Thaina** [comment]
```C#
class Point
{
    public void Deconstruct(double Angle, double Length) => ...;
    public void Deconstruct(int X, int Y) => ...;
}

Point p = ...;
if (p is (X: 3.0, Y: 4.0)) ...; // What happen?
if (p is (Angle: 3, Length: 4)) ...; // What happen?
```

**Comment by gafter** [comment]
@Thaina We don't disambiguate or reorder based on parameter names.  All three are ambiguous. As a practical matter, you should have only one `Deconstruct` method for a given arity.  If you do give names, they are required to match the name in their positions.

**Comment by Thaina** [comment]
@gafter That what I ask `What will happen?` should it be warning, error or something?

**Comment by gafter** [comment]
All three are ambiguity errors at compile-time.

**Comment by Thaina** [comment]
@gafter Also this

```C#
if (p is (Angle: 3, Length: 4)) ...;
```

is ambiguous but should it did implicit conversion?

Or is it not allow implicit conversion? What about this case?

```C#
if (p is (Angle: 3f, Length: 4f)) ...;
```

Also if we encourage that we would have many `Deconstruct` functions. What would happen to the assignment deconstruction? Do we already discuss about that somewhere?

**Comment by gafter** [comment]
This is exactly the same behavior as deconstruction.  If you have two deconstruct methods of the needed arity, it is just an error.

**Comment by gafter** [comment]
Added
---
### Propose to change precedence of switch expression to *primary* (open)

The switch expression is currently at *relational* precedence.  I propose to change it to *primary* precedence.  See https://github.com/dotnet/csharplang/issues/2331 for details.

**Comment by gafter** [comment]
All of these open issues are addressed.  Closing.
