### ISSUE TITLE
Proposal: Allow a non-fixed size array embedded in a class

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#210]
Related to https://github.com/dotnet/csharplang/issues/115 and https://github.com/dotnet/roslyn/issues/6055
For example:
class A
{
    int a;
    object o[]; // not same as "object[] o;"
    public A(int a0)
    {   a=a0;  }
}
A aa=new(10) A(5); //aa.o.Length=10, aa.a=5
object o1=aa.o[9]=3; //ok, access to any elements of aa.o is ok
object[] o=aa.o; //compile error! aa.o is not a real array, it's embedded in aa, so it can't be referenced directly!

A class can only have at most one array with dynamic length, but can have more than one inline arrays with fixed length.
for example:
class A
{
int a[10]; // fixed size
int b[20]; //fixed size
object c[]; //dynamic size
}

**Comment by Thaina** [comment]
You could use 3 grave accent to enable code mode

```
 > like this
 > ```C#
 > code
 > ```
```

**Comment by ig-sinicyn** [comment]
@ygc369 
but why? You cannot save anything in terms of allocation size. You had to have an object header for the object array or you will not able to pass the object into another methods.

There's no gain in terms of memory locality as CLR allocates objects sequentially (this is simplified version, I know:) ).

There's no point to use embedded arrays for collection types as there's no way to resize the array.

And finally, there's no way to enable dynamic-sized embedded arrays for structs.

So, what's the point? 😕 


The same relates to #212. There's `stackalloc` for locals and there will be [Span<T> / Memory<T>](https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md) for almost anything else.

What's missing? : )

**Comment by jnm2** [comment]
@Thaina you can also use more than three backticks if what you're trying to show contains three backticks:
`````markdown
````
```c#
code
```
````
`````
