### ISSUE TITLE
Async parallel foreach

### ISSUE THREAD

**Issue by tomesendam** [dotnet/csharplang#2101]
I've had situations where I needed a asynchronous parallel foreach and while it's not rocket science to implement yourself I think it would be a nice feature to be implemented in C#.

However it has to be said that I am not a expert at this at all. And do not know the possible implications of implementing such a feature. Or that the feature is a good idea it all. I would like to hear your thoughts on this! 

Anyway I usually resolved it doing something like this(I've seen it online before but cannot find the source again)

```
        /// <summary>
        ///     Executes a foreach asynchronously.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="source">The source.</param>
        /// <param name="dop">The degrees of parallelism.</param>
        /// <param name="body">The body.</param>
        /// <returns></returns>
        public static Task ForEachAsync<T>(this IEnumerable<T> source, int dop, Func<T, Task> body)
        {
            return Task.WhenAll(
                from partition in System.Collections.Concurrent.Partitioner.Create(source).GetPartitions(dop)
                select Task.Run(async delegate
                {
                    using (partition)
                    {
                        while (partition.MoveNext())
                            await body(partition.Current);
                    }
                }));
        }
```

**Comment by YairHalberstadt** [comment]
Can I suggest you move this to CoreFx, where library requests are taken?
Thanks

**Comment by tomesendam** [comment]
of course! pardon me.
