### ISSUE TITLE
[Feature Request] var pattern in IF statement while making null check

### ISSUE THREAD

**Issue by webwarrior06** [dotnet/csharplang#2102]
Wouldn't it be better if we can create a variable inside IF statement if checked value is not null, like we have in type checking with "is";

**To make it clear;**
```csharp
if(Long.Named.Method.Chain.Or.Static.Etc.Value != null var x){

   //...things related to x variable

}
```

Otherwise, It has to be a variable defined before the IF statement in order not to write long-character variable over and over again. Like this;
```csharp
var x = Long.Named.Method.Chain.Or.Static.Etc.Value;
if(x != null){

}
```

**Comment by ufcpp** [comment]
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgD4ACADAAS0CMA3ALABQ3tAzMwBMjAMLcA3t0bTmLAGyjGAGQD2FAOaMAvAD5GFOABtDnLjMUA5KAFsIAE216Dx0+ZGMAshBgALFQ919IxMpGXcRHygcCkcgl1DpdwBRGAxY5xCzMMYANShDOAh04NcZBOYBWgAWTwAKAEpyySzzaRwwRlrVDQA6K1s7Hq9ffx6IqIoelIwevIKinGRGcQBfRgAPRpbW5ta92QBOWs3SvZXy864VoA=

dup of https://github.com/dotnet/csharplang/issues/1944

**Comment by webwarrior06** [comment]
Thanks for the info guys. I could not realized something similar was proposed before. 😊
It will be very useful. 👍

**Comment by pinkfloydx33** [comment]
Can't you already do the following with C#7 (sure, a bit more verbose)?
`if(Long.Named.Method.Chain.Or.Static.Etc.Value is var x && x != null) ...`

If you know the type, then it's _practically_ the same (but sure, not `var`)
`if(Long.Named.Method.Chain.Or.Static.Etc.Value is SomeType x) ...`

**Comment by webwarrior06** [comment]
@pinkfloydx33 Yeah, the first one is sort of verbose. In fact, the second is better and easy to use for now. We will have this problem solved totally with C# 8 as @DavidArno's post.

**Comment by Joe4evr** [comment]
Please close, then.
