### ISSUE TITLE
[Idea] Calling dispose() when goes out of block / Multiple Using Statements 

### ISSUE THREAD

**Issue by jasonkuo41** [dotnet/csharplang#2103]
## Idea Description
A quick review on: https://stackoverflow.com/questions/1329739/nested-using-statements-in-c-sharp and Issue #1579

In my opinion that it's pretty ugly and unreadable for nested using statements like that.
Especially if you are familiar with C++, which when you wanted to implement RAII-like style functions, nested using doesn't look that good at all.

Using the above-mentioned link as an example, **Originally :**
```cs
using (StreamReader outFile = new StreamReader(outputFile.OpenRead())) {
    using (StreamReader expFile = new StreamReader(expectedFile.OpenRead()))  {
      // Do something here
    } // expFile.Dispose(); is called here
  } // outFile.Dispose(); is called here
```
**Proposal:**
using without two curly brackets

**Explain:**
Variables with `using` keyword in front of it will invoke Dispose Method when it falls out of the current scope.

```cs
void MyCoolFunction (string input) {
   using StreamReader outFile = new StreamReader(outputFile.OpenRead());
   using StreamReader expectFile = new StreamReader(outputFile.OpenRead());
   using SomeDisposable item = new SomeDisposable ();
   // Do something here
} // item.Dispose(); is first called here
  // then expectFile.Dispose(); then outFile.Dispose(); is called
```

## Other Advantage
 - Replaceable with old syntax
``` cs
void MyFunc () {
   // Do Something
   using (SomeDisposable item = new SomeDisposable()) {
       // Do Something
   }
}
```
can be replaced with the following syntax I proposed, but multiple using instances are allowed.
```cs
void MyFunc () {
   // Do Something
   {
       using SomeDisposable item = new SomeDisposable();
       using SomeDisposable2 item = new SomeDisposable2();
       // Do Something
   }
}
```

- Can be easily commented out

``` cs
// using SomeDraftDisposable item = new SomeDisposable();
```

- Possible syntax to assign variable later (Just a draft idea here)

``` cs
using SomeDraftDisposable item;
// Do something
if (Applied()) {
   item = new SomeDisposable () { IsRealiable = true };
} else {
   item = new SomeDiposable ();
}
```

## Note
It's also pretty cool if we could do `using (statement1, statement 2, ...)`, like in #1579 but then it might be *too* overly compact.

Also maybe using the same `using` keyword (maybe?) confusing, adding a new keyword like `local` for this may be plausible. It would look like : 
```cs
{
  DClass alive;
  local DClass item = new DClass();
  local DClass2 item2 = new DClass2();
  // alive = item; is not allowed! vice versa

} // item.Dispose(); and item2.Dispose(); are called, but alive is not
```
It's just a draft idea to make the code cleaner when you need a lot of using at the same time. I admit it's not the best idea, so if you have other ideas, feel free to discuss it here.

Also inspired by the following syntax in C++ :
```cpp
void Func (string input) {
    std::shared_lock<std::shared_mutex> lock1 (mx);
    std::shared_lock<std::shared_mutex> lock2 (mx);
    // Mutex is automatically released when it falls out of block
}
```

**Related**
Issue #1579, Issue #1473

**Comment by ufcpp** [comment]
See "Enhanced using and foreach" in https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md
This has already been championed and prototyped.

**Comment by jasonkuo41** [comment]
Ok wow, yeah I was thinking that why this is not a feature already in C#. It felt so natural to use it in C++.

Another broad idea that I can up along with this concept is this:
**Dynamically Assignable**
``` cs
using SomeDraftDisposable target;
// Do something
if (Applied()) {
   target = new SomeDisposable () { IsRealiable = true };
} else {
   target = new SomeDiposable ();
}
// Call target.Dispose() when 'target' it's out of scope, no matter where
```
Is this concept feasible?

**Comment by HaloFour** [comment]
@jasonkuo41 

I believe that in the prototype that the `using` variable is readonly and must be initialized on declaration.  The team didn't seem terribly keen on the idea of having readonly variables assigned after declaration, even if the language could guarantee assignment exactly once regardless of branching.

**Comment by jasonkuo41** [comment]
@DanFTRX  I know, but it's more limited and restricted. If you have to do something between the two `using`, it may be a bit frustrating. It was mentioned in the answer of StackOverflow link I provided in the beginning.

Say this example
```cs
using (var agrs = new SomeDisposable() { option = Options.None }) {
// Does something (e.g. read some binary data from other sources)
args.Add(new Data());
args.GrabResult(GrabBinaryFromSomething(args));
using (var mystream = new MyStream(args))
   using (var mstream = new MemoryStream()) 
   using (var byteWriter = new BinaryWriter()) {
       // Write Some Binary Data....
   }
}
```

It would be better if the code looks like
```cs
using var agrs = new SomeDisposable() { option = Options.None };
// Let's do things
args.Add(new Data());
args.GrabResult(GrabBinaryFromSomething(args));
{
   using var mystream = new MyStream(args);
   using var mstream = new MemoryStream();
   using var byteWriter = new BinaryWrite(mstream);
   // Does some binary writing
}
```

**Comment by DanFTRX** [comment]
@jasonkuo41 Fair enough, but in that case you should change the example in your post to reflect the actual problem rather than an already solved one.

**Comment by lostmsu** [comment]
This is implemented in C# 8. The issue should be closed.

**Comment by AartBluestoke** [comment]
You can play with this in sharplab:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoaogZgAJSGARASwGcAHCDgQ2AAbGABUAFmzwBzEAEl23XgOEBvatQaamjIigYBVDjAAUAShVEyATmMAiQDwbgEH3bpgNwBfDVvpM9CnkZmXpoW1nYA4hB4MC4e1J40VKSMalRaTCQkDKnp6UQADAwAbnxQDAC2AJ7+SkIwDAC8DNEA7qycAcqiEtJmrsG5VTX8dQB0hiZuAwnuQA=

**Comment by YairHalberstadt** [comment]
Closing as implemented in C# 8
