### ISSUE TITLE
Retrieve the application types or type GUID(s) from the current running application

### ISSUE THREAD

**Issue by JeffIsLife** [dotnet/csharplang#2104]
Retrieve the application types or project type GUID(s) from the current running application.

When designing a NuGet package it may be handy or required to retrieve the application type. 
The information can be used for:
  1. Executing different logic paths depending on the type.
  2. Saving the information in the logs when starting the application. This way we can exclude certain area's when errors occur which will result in faster tracking of the errors.

**Comment by HaloFour** [comment]
This does not seem like the appropriate repo for this request.  You might want a repo specific to Nuget?

**Comment by Joe4evr** [comment]
I'm pretty sure this is a non-starter as the project type GUID isn't emitted into assemblies, far as I know.

**Comment by JeffIsLife** [comment]
Although my example was NuGet specific I still think it should be a common language feature to retrieve the application types in which you are running the application?

**Comment by JeffIsLife** [comment]
Okay, thank you. I will try to create a new request there.
The current use case I have just needs the application type to add the information to the logging.
