### ISSUE TITLE
Allow ref structs to return fields by reference

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2107]
@tmds commented on [Fri Dec 21 2018](https://github.com/dotnet/roslyn/issues/31992)

**Steps to Reproduce**:

```cs
    ref struct A
    {
        private int i;
        public ref int Int => ref i;
    }
```

generates a compilation error:
```
error CS8170: Struct members cannot return 'this' or other instance members by reference
```

Maybe this can be allowed?

**Comment by Thaina** [comment]
Should be. Why it's not allowed in the first place?

**Comment by svick** [comment]
@yaakov-h I think that example on its own would be fine: [just like today when you try to `ref return` the field directly (after changing it to `public`)](https://sharplab.io/#v2:D4JwpgZgBAzgLiArgYzlAygWAFAG8cCQAAgMxQCWAdmuQNw4C+OORAjAGxREBMUAwjnzYoIrmTadw0KmgCSACgCUOUVCGqCANwCGIWFAC8USmADuGJfWGrRRAOxQpsAHR0VohqsZA===), that could produce an error.

The problem is: how does the compiler figure out whether to produce an error or not? [Returning the value of such property is allowed today](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD5QnABAZ2FArgY2HQGUBYAKAG8KBIAAQEYA2dGAOyJgG4L0/06AZnSoM7IgEl0AXgB8ItKx7kAvhQqMWdAEzoAwhWrl+A4ZoViO6CQAoAlL35GTNMAEMoWGejYQA7iT2yiYmdADsFlgAdBLB/ComFCpAA===), so assuming all `ref` properties on structs return a reference to a field on the struct would be a breaking change.

**Comment by huoyaoyuan** [comment]
Why not introducing rust-like lifetime feature to both language and CLR in future? It may also benefit for some other cases.

**Comment by arekbal** [comment]
Isn't `s` dead after the `I()`?

**Comment by Joe4evr** [comment]
@arekbal That's the point, he was responding to the question:
> Why it's not allowed in the first place?

**Comment by arekbal** [comment]
@Joe4evr That's different case...
a) static method
b) returning an indirect reference to a stack variable out of a method defining it...
No lifetimes or scopes required to rule this out...

**Comment by Joe4evr** [comment]
> a) static method

The method `C.I()` being static has no bearing on the lifetime of the `S` instance that is used inside of it. The `S` instance is created inside the stackframe of `I()`, so if it were allowed to return a `ref` to one of `s`'s instance fields, when the stack unwinds to `I()`'s caller, the instance is dead and you'd be left with a pointer to garbage data. 

That is *exactly* what you said the first time, so why are you backtracking over yourself? You can't go around saying that `1` and `1` are different values at different points in time.

**Comment by yaakov-h** [comment]
> The problem is: how does the compiler figure out whether to produce an error or not?

As I mentioned in another issue regarding a similar request, this would effectively bifurcate the entire ref safety system. It would permit a bunch of scenarios that you cannot construct today, but in turn would prohibit a bunch of scenarios that are currently valid, safe syntax.

**Comment by arekbal** [comment]
@Joe4evr I am not backtracking just looking at this thing from different angles. What I meant by pointing out that it is static, is that I could imagine two cases that should be not ruled out in the long game:
1. non-static methods returning a reference bound with `this`.
2. static methods returning a reference to static objects.

But then there is a question of knowing what does reference refer to, reading from declaration, such as in this code:

```
    static ref int PassThrough(ref int x)
    {
        return ref x;
    }
    public static ref int I()
    {
    	var s = new S();
        return ref PassThrough(ref s.I);
    } 
```
I see no easy solution. sref? (_some kind of lifetimes_ lol).

> The S instance is created inside the stackframe of I(), so if it were allowed to return a ref to one of s's instance fields, when the stack unwinds to I()'s caller, the instance is dead and you'd be left with a pointer to garbage data.

You are right, but it does not have to be the case.
Speculating here about the CLR and CIL extension possibilities for the future, but it does not have to be created "inside the stackframe of I()". Could be "created" in stackframe of the caller. Just like C++ compiler optimizer does...

**Comment by glenn-slayden** [comment]
https://github.com/dotnet/roslyn/issues/32203

**Comment by tmds** [comment]
I'm fine if this is closed based on the above discussion.

I hadn't realized it would be hard for the compiler to figure out the `ref` returned to the field is limited to the struct lifetime.

**Comment by Thaina** [comment]
I still wish this could be allow by some means. Maybe using other keyword to clarified that this ref return function is returning the instance field would be possible?

```C#
public interface IMatrixMxN
{
    int M { get; }
    int N { get; }
    in float this[byte i,byte j] { get; } // using `in` instead of `ref` maybe?
}

public struct MyMatrix4x4 : IMatrixMxN
{
	public float M11,M12,...,......;

	public int M => 4;
	public int N => 4;
	public in float this[int i,int j]
	{
		get
		{
			if(i == 0 && j == 0)
				return ref M11;
			....

			throw new Exception();
		}
	}
}

public static MatrixExtension
{
	public static float? Determinant<M>(this in M m) where M : struct,IMatrixMxN
	{
		if(m.M != m.N)
			return null;

		// calculate determinant
		ref float f0 = ref m[0,0]; // cannot return ref with f0 because the function is `in float` not `ref float`
	}
}
```
