### ISSUE TITLE
GC.SuppressFinalize should have compile time warnings for certain situations

### ISSUE THREAD

**Issue by john-h-k** [dotnet/csharplang#2113]
The `GC.SuppressFinalize` method (I checked the official language spec and it's mentioned there so I think this issue fits this repo best) is dodgy at best, and downright dangerous at worst. It completely violates encapsulation as it gives way to mess with the private management of the object through its finalizer and is often a code smell except in the standard Dispose pattern (where it is preferable to a flag due to the high expense of queueing a finalizer).

I suggest that either:
* Calling `GC.SuppressFinalize` on anything other than `this` should invoke a compiler warning. Naturally this can be disabled and is non breaking.
* As well as the measure above, have a new protected method on type `System.Object` - this way, the object's privacy is protected, and cannot be messed with easily from  externally - thatalong the lines of `SuppressFinalize` with no arguments. Have a separate warning for calling `GC.SuppressFinalize(this);` that explicitly recommends switching to this method.

I feel this would be a valid change to the language rather than a separate analyzer as:
* SuppressFinalize *does* have its place, even if it's quite niche. 
* When used wrongly it can have dodgy consequences (though use of `CriticalFinalizerObject` I believe can minimise this behaviour - can anyone confirm?)
* It is a very critical part of the dispose pattern, one of the most used patterns in .NET.

**Comment by YairHalberstadt** [comment]
Given that nobody is likely to use GC.SupressFinalize by mistake, is it fair to assume that anyone who does use it can be expected to know what they are doing?

**Comment by johnkellyoxford** [comment]
@YairHalberstadt that's a fair point, but for example you can't reflect into non public members in a class when operating in a medium trust or lower context yet can still potentially disrupt important finalization code without having access to the source code of the type. It just seems contradictory to much of the rest of the language in principal

**Comment by jmazouri** [comment]
A Roslyn analyzer for this (previously an FxCop rule) is available as [CA1816](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1816-call-gc-suppressfinalize-correctly?view=vs-2017), available via the [Microsoft.NetCore.Analyzers](https://www.nuget.org/packages/Microsoft.NetFramework.Analyzers/) package.

For .NET Framework projects, you can enable this rule through the static analysis settings for your project, and ["Enable Code Analysis on Build"](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code?view=vs-2017).

**Comment by yaakov-h** [comment]
This does not appear to have any relation to the C# language.

**Comment by jnm2** [comment]
> have a new protected method on type System.Object

The additional intellisense clutter would make me very sad. I think fxcop + the current API is ideal.

> except in the standard Dispose pattern

Even more so because the standard pattern has been obsolete since 2010 with .NET 4.0 and SafeHandle. Sadly, MSDN has continued to recommend the legacy method of writing a finalizer which has fewer safety guarantees than SafeHandle and is pure maintenance overhead.

**Comment by 333fred** [comment]
Closing this out, as it's not related to the language. Compiler warnings can be proposed on Roslyn in general, but for this, CA1816 is built into the .NET SDK at this point.
