### ISSUE TITLE
Using tuple as out parameter

### ISSUE THREAD

**Issue by kvalev** [dotnet/csharplang#2118]
I just stumbled upon the following issue and I dont know whether this is a bug or by design: 

```
BlockingCollection<(int, int)> queue = new BlockingCollection<(int, int)>();
bool success = queue.TryTake(out (int x, int y));
```

Which results in the following errors:
```
A ref or out value must be an assignable variable
A declaration is not allowed in this context.
Use of unassigned local variable 'x'
Use of unassigned local variable 'y'
```

However I can use the non-sugarized version of tuples just file:
```
BlockingCollection<(int, int)> queue = new BlockingCollection<(int, int)>();
bool success = queue.TryTake(out ValueTuple<int, int> item);
```

I am curious why the first version is not possible, while the second one is, when they are practically the same thing.

**Comment by YairHalberstadt** [comment]
Change it too

```csharp
BlockingCollection<(int, int)> queue = new BlockingCollection<(int, int)>();
bool success = queue.TryTake(out (int x, int y) somename);
```

**Comment by YairHalberstadt** [comment]
Whats interesting is that this doesn't work:

```csharp
        BlockingCollection<(int, int)> queue = new BlockingCollection<(int, int)>();
	bool success = queue.TryTake(out var (x, y));
```
or this:

```csharp
        BlockingCollection<(int, int)> queue = new BlockingCollection<(int, int)>();
	bool success = queue.TryTake(out (int, int) (x, y));
```

So it looks like deconstruction is not supported in out parameters

**Comment by YairHalberstadt** [comment]
https://github.com/dotnet/csharplang/issues/611

**Comment by kvalev** [comment]
`(int x, int y) somename` indeed does work, but its only advantage is to explicitly specify the tuple names - you still have to deconstruct the tuple manually. Would be quite handy, if deconstruction is supported out-of-the-box.

**Comment by YairHalberstadt** [comment]
@kvalev
That what #611 is requesting

**Comment by gafter** [comment]
Closing as dup of #611
