### ISSUE TITLE
Allow fixed-size value buffers directly inside classes (ref types)

### ISSUE THREAD

**Issue by john-h-k** [dotnet/csharplang#2120]
Currently, this is illegal:
```csharp
class MyClass
{
    /* Other fields etc etc */
    private fixed byte Buffer[4];
    /* More fields */
}
```
It needs to be switched for this
```csharp
class MyClass
{
    private struct MyBuffer
    {
        public fixed byte FixedBuffer[4];
    }
    /* Other fields etc etc */
    private MyBuffer Buffer
    /* More fields */
}
```

While working, this is undesirable because:
* You lose information - it is not initially clear that `MyBuffer` is a fixed buffer type. This can be remedied with an ugly and overcomplex name such as `Int64Fixed16`, which is:
* Still not very clear
* Cannot easily be analyzed by tools
* Is purely stylistic and will differ between developers
* Ambiguous whether size refers to number of items or overall size (16 longs (128 bytes) or 16 bytes (2 longs)?)

I propose this should be replaced by a compile time generated wrapper, so this code will compile:
```csharp
class MyClass
{
    /* Other fields etc etc */
    private fixed byte Buffer[4];
    /* More fields */
}
```
This would be a **purely compile time feature**. My first suggestion for how it would be implemented would be a such;
0. An interface `IFixable<T> where T : unmanaged` is introduced, containing a single method `ref T GetPinnableReference()`. This is along the lines of the current `fixed` statement requirements. 
1. The compiler generates an internal private struct that only contains the requested buffer as a field, and implements the `ref T GetPinnableReference()`, where T is the primitive used in the buffer. This allows the use of the `fixed` statement even though the struct itself is private. It also contains illegal C# symbols (such as `<`, `>`) to prevent any naming conflicts 

2. The class contains this struct in the correct place to preserve the same layout as the intented one in the source code, which again contains illegal characters to prevent conflicts. It is exposed by a get only property with the access level of the containing type represented as an `IFixable<[type]>` where [type] is the buffer element type. Because this pattern is only used in classes it will ALWAYS require fixing to use the buffer so access to the direct pointer is never necessary, access through a `fixed` block is all that is needed.

(You don't set the pointer of course. Access to the pointer as a getter is all that is required to represent equivalent functionality)

This should allow use of fixed buffers in a class in a semantically and syntactically equivalent way to how they are used in structs currently, while preserving more information than the current wrap struct buffer pattern. 

**_Or_**, you could just let it be supported by the CLR. But I don't know enough about the difficulty of implementing this to give any comment on it.

**Comment by CyrusNajmabadi** [comment]
> You lose information - it is not initially clear that MyBuffer is a fixed buffer type

Why is this something i would need to care about?  

> Cannot easily be analyzed by tools

Why can't tools easily analyze this?

> An interface IFixable<T> where T : unmanaged

Why do you need that?  Why can't the compiler just translate all access of `Buffer` through the transparent struct that it wraps around the real fixed-size-buffer field?

> This should allow use of fixed buffers in a class in a semantically and syntactically equivalent way to how they are used in structs currently, while preserving more information than the current wrap struct buffer pattern.

The benefit here seems marginal.  As you've already pointed out, you can already accomplish this today with a wrapper struct.  So it's pretty trivial to just do that and use that instead.

**Comment by Suchiman** [comment]
Fixed size buffers aren't really supported by the CLR right now either.
If you type 
```csharp
struct MyBuffer
{
    public unsafe fixed char FixedBuffer[4];
}
```
it generates a private nested struct with an explicit size specified and one field of buffer type.
```csharp
internal struct MyBuffer
{
    [FixedBuffer(typeof(char), 4)]
    public MyBuffer.<FixedBuffer>e__FixedBuffer FixedBuffer;

    [CompilerGenerated]
    [UnsafeValueType]
    [StructLayout(LayoutKind.Sequential, Size = 8)]
    public struct <FixedBuffer>e__FixedBuffer
    {
        public char FixedElementField;
    }
}
```
Since C# 7.3 it also doesn't require `fixed` since using the indexer can be implemented with GC tracked managed pointers alone: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/indexing-movable-fixed-fields.md
Nontheless it needs to be `unsafe` (which you've never declared in your samples) since it can read uninitialized data or out of bounds.

So there is no reason it couldn't be enabled on classes directly other than this being an unsafe feature (which is generally undesireable) and it was primarly added for interop reasons.

**Comment by Korporal** [comment]
One consequence of adding this support is that one can use inheritance with classes but not structs. This would give an ability to create classes that contain fixed buffers and derive from some helpful base where boiler plate manipulation could reside.

**Comment by Joe4evr** [comment]
@juliusfriedman Because explicit layout is only supported on structs.

**Comment by 333fred** [comment]
Doing some housekeeping: this is a dupe of https://github.com/dotnet/csharplang/issues/1314.
