### ISSUE TITLE
Discussion - Is it feasible to support fixed at a struct level?

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#2122]
I was wondering if it would be feasible for the language to support a `fixed` combined with `this` in a `struct`.

The motivation is to reduce code clutter when doing `unsafe` manipulations on `struct` fields using pointers. Currently one must apply `fixed `multiple times (sometimes nested) to each field but if the entire `struct `were `fixed `this would become unnecessary.

e.g. something like this:

```cs
    public unsafe struct Message
    {
        public fixed char username[32];

        public string Username
        {
            get
            {
                fixed (char * bufferptr = username) return Text.GetStringFromBuffer(bufferptr);
            }
            set
            {
                fixed (char * bufferptr = username) Text.SetAsChars<Message>(value, bufferptr, nameof(username));
            }
        }
    }

```

would become something like:

```cs
    public unsafe struct Message
    {
        public fixed char username[32];

        public string Username
        {
            get
            {
                fixed (this) return Text.GetStringFromBuffer(username);
            }
            set
            {
                fixed (this) Text.SetAsChars<Message>(value, username, nameof(username));
            }
        }
    }

```
(That example is of course trivial with just a single pointer being used).

I think this would amount to the compiler automatically declaring pinned pointers (if I recall their real name) during code generation.

Advantages:

1. Declaration of `fixed `pointers becomes implicit.
2. Eliminates the need to ever nest `fixed `statements when there are multiple buffers/fields being manipulated in methods.
3. Makes the code significantly more readable.
4. Reduces scope for poor code to corrupt memory because no explicit pointer is present.

**Comment by HaloFour** [comment]
@Korporal 

`StructLayoutAttribute` is a pseudo-attribute which informs the C# compiler to emit the appropriate IL metadata for how to layout the struct at runtime.  The following C#:

```cs
[StructLayout(LayoutKind.Explicit, Size = 128)]
public struct Foo { }
``` 

produces the following IL:

```
.class public explicit ansi sealed beforefieldinit Foo
    extends [mscorlib]System.ValueType
{
    .pack 0
    .size 128

}
```

**Comment by Korporal** [comment]
Thanks, I'm clearly wrong I must be thinking of something else.

**Comment by Korporal** [comment]
@YairHalberstadt
@tannergooding

> https://github.com/dotnet/csharplang/blob/master/proposals/fixed-sized-buffers.md
> 
> This would give you all that and more

It seems that that proposal only refers to _fixed size buffers_, in general we can manipulate any kind of struct type field via a pointer and these also require `fixed`.

**Comment by tannergooding** [comment]
The following code is already valid:
```csharp
fixed (Message* pMessage = &this)
{
    return GetStringFromBuffer(pMessage->username);
}
```

The same also works for fields which are not fixed-sized buffer by explicitly taking the address of the field: `&pMessage->Field`

**Comment by Korporal** [comment]
@tannergooding - I never thought of that, it's certainly good enough. Thanks.

**Comment by Joe4evr** [comment]
Please close the issue if you find there are no changes needed to be made. :roll_eyes:
