### ISSUE TITLE
Inconsistent/ambigious C# 'default' operator behavior with value types

### ISSUE THREAD

**Issue by SherifRefaat** [dotnet/csharplang#2125]
Hi, I am not entirely sure about this. But personally, I don't think this is ever right in terms of secure coding.
Here it is:

`Guid? x = default(Guid?); this is equivalent to Guid? x = default;`
which produce `null` (it is fine).

Let's have the following
`Guid y = Guid.NewGuid();`
then
`Guid? z = (y == default) ? y : default(Guid?);`
this will make `z` equal to `null`. Which again is valid. But if you do
`Guid? z = (y == default) ? y : default;`
this will make `z` equal to `00000000-0000-0000-0000-000000000000` (default value of `System.Guid`)

Implicitly, you mean here the `default` for `z` **not** `y`.

I think this is a problem in terms of secure coding since `z == null` will always fail since it is equal to `00000000-0000-0000-0000-000000000000`
More worse (in my opinion), this `z == default` will always evaluate to false since it contains the default value of `Guid` not `Guid?`

By the way, it seems that this behavior is consistent with all `T?` or `Nullable<T>` where T is a value type.

Thanks.

**Comment by CyrusNajmabadi** [comment]
This is all as per the C# language specification.  If this is something you don't like, you can always write a Roslyn analyzer to check your code and identify these places for you.

**Comment by Grauenwolf** [comment]
> Implicitly, you mean here the default for z not y.

Let's pretend that is true. Here is an example of why it would be a bad idea. 

If you extract the expression as a variable, then the result of that expression would change: 

   Guid y = Guid.NewGuid();
   var temp = (y == default) ? y : default; //this line doesn't know about z
   Guid? z = temp;

There is also the issue of `var` itself. If you use `Guid? z` to determine the type of `default`, then you must also use `var temp` to determine the type of `default` in my example. But wait, the type of `default` determines the type of `var temp`, so the question is undecidable. 

Furthermore, what about implicit conversions.

    Foo z = (y == default) ? y : default;

Since there is an implicit conversion from `Guid` to `Foo`, does that mean `default` is of type `Foo`?

**Comment by Grauenwolf** [comment]
Personally I think you should be using `null` or `.Empty` for comparisons in the first place. `default` is mostly for generics and default properties. 

Why does more characters than necessary?

**Comment by Grauenwolf** [comment]
Also, this is a intentionally bad example. 

Guid? z = (y == default) ? y : default;

Reduces to

Guid? z = (y == default) ? default : default;

And that reduces to 

Guid? z = default(Guid);

And now the code isn't confusing at all.

**Comment by SherifRefaat** [comment]
@CyrusNajmabadi here are a couple of points for you:

1. Compilers should not choose for programers, instead, there should be an error saying that this statement/expression is ambigious. This is not something new or I am inventing. _It is the current state in all languages I have seen_.
2. Using `default` over `default(...)` will hurt the readability of C#. Because it is insane that everytime I find somebody using `default`, i have to trace the type to see whether it is a value or reference type because the behavior is different.
3. Let’s say, that what I am saying is true, would like to push this as a change to C# lang minor version and do a Rosylin Analyser to tell people about the breaking change. I think you will find this unreasonable, at least, it is for me.

**Comment by yaakov-h** [comment]
> Guid? z = (y == default) ? y : default;
>
> Reduces to
>
> Guid? z = (y == default) ? default : default;

This seems misleading.

```csharp
 Guid? z = (y == default) ? y : default;
```

This is effectively, assuming `y` is still a `Guid`:

```csharp
 Guid? z = (y == default(typeof(y))) ? y : default(target-type);
```

Which is then:

```csharp
 Guid? z = (y == default(Guid)) ? y : default(target-type);
```

This can then be simplified to:

```csharp
 Guid? z = (y == default(Guid)) ? default(Guid) : default(target-type);
```

However, the target type of the _entire expression_ is `Guid?`, not `Guid`. The two `default`s refer to two different types and should not be confused for one another.

> Because it is insane that everytime I find somebody using default, i have to trace the type to see whether it is a value or reference type because the behavior is different.

If you're using Visual Studio, the hover tooltip will tell you the exact type being inferred, in exactly the same manner as `var`.

**Comment by SherifRefaat** [comment]
> Also, this is a intentionally bad example.
> 
> Guid? z = (y == default) ? y : default;
> 
> Reduces to
> 
> Guid? z = (y == default) ? default : default;
> 
> And that reduces to
> 
> Guid? z = default(Guid);
> 
> And now the code isn't confusing at all.

You are giving a plausible example which I find unrealistic at all. The piece of code I originally posted comming out of an actual program that is in production.

Another point worth mentioning (@CyrusNajmabadi @Grauenwolf), very ironic one, if you wrote `default(Guid?)`, you will find an analyzer telling you to just remove the brackets, which clearly is not right. Also, seems that the programer who did the analyzer did not know that it will behaive differently with nullable value types.

**Comment by SherifRefaat** [comment]
@yaakov-h Visual Studio is not a part of the C# language. It is an IDE, simply, an text editor tool. You can not just say, well, look at the tooltip!

**Comment by CyrusNajmabadi** [comment]
> Another point worth mentioning (@CyrusNajmabadi @Grauenwolf), very ironic one, if you wrote default(Guid?), you will find an analyzer telling you to just remove the brackets, which clearly is not right. 

That is not true.  The IDE understands this:

![image](https://user-images.githubusercontent.com/4564579/50870067-634e1200-136b-11e9-81cf-d6a54c9d010d.png)

However, if you write:

![image](https://user-images.githubusercontent.com/4564579/50870081-71039780-136b-11e9-922d-650fe32d5f73.png)

Then the IDE correctly determines that this can be simplified to:

![image](https://user-images.githubusercontent.com/4564579/50870092-8082e080-136b-11e9-9f92-be5ac9692948.png)

**Comment by CyrusNajmabadi** [comment]
@SherifRefaat I would recommend taking the discussion about breaking changes to gitter.im/dotnet/csharplang.  It's going to be a non-starter here.

**Comment by SherifRefaat** [comment]
@CyrusNajmabadi Okay. Thanks for your time.
