### ISSUE TITLE
ref get set property or indexer

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#2137]
Why i can't have 

```c#
public ref T this[int index]
{
    get // ref either here or at property signature
    {
        return ref array[index]; // this is indeed simplified.
    }
    set // can not have setter in this property.
    {
       array[index] = value; // this is indeed simplified.
    }
}
```

Whats wrong with that? I know i can use a method instead but i'm wondering if there is strong reason for disallowing this. why is it disallowed for indexers too? 

To me it perfectly makes sense to have by ref getter and no-ref setter. please enlighten me with your knowledge. thanks in advance.

---

also ref/value semantics doesn't apply to setters. why not just ignore that and allow setter inside ref property?

(the only place ref/value setter may have some meanings is for properties inside mutable structs. but even if its by value, it would probably be a bug)

**Comment by MkazemAkhgary** [comment]
Thanks, I thought it would better to know if there is something wrong with this rather than making a proposal. because it would be declined anyway if there is a reason.

**Comment by MillKaDe** [comment]
@MkazemAkhgary 

If the indexer's getter returns a **ref**, you don't need a setter.
The getter returns a ref, so you can store something at the place where that ref points to.

```c#
using System;
public class BunchOfInts {
  int[] ints;
  public BunchOfInts (int num) => ints = new int[num];
  // public ref int this[int i] { get => ref ints[i]; }
  public ref int this[int i] => ref ints[i];
}

public static class Program {
  public static void Main() {
    int num = 5;
    var bi = new BunchOfInts (num);
    for (int i = 0; i < num; i++) bi[i] = i;
    for (int i = 0; i < num; i++) Console.Write ($"{bi[i]},");
    Console.WriteLine ();
  }
}
```

**Comment by MkazemAkhgary** [comment]
@MillKaDe Holy cow! now i see why. thanks a lot!
