### ISSUE TITLE
Champion "half" auto property

### ISSUE THREAD

**Issue by rhalaly** [dotnet/csharplang#2138]
# Background
Auto properties are awesome - short and simple. Full properties fill "too long" because the maintenance of the backing field - you have to declare the field and implement the getter and the setter by yourself (of course you can use snippets) but it makes the code much longer than auto properties.

In some cases, you want to do a small behavior of modification to the auto property but without to implement and maintain a full property. For example, when using `INotifyPropertyChanged` or use a small filter in the `getter` and/or `setter`, you have to use full property.

# Proposal
Instead of using "auto property" or "full property", let's have a "half" auto property!
The property will behave in that way:
* The getter will be able to use the keyword `value` (like the setter) that represent the stored value in the backing field and return the processed value.
* The setter will be able to use `return` that will represent the value that should be stored in the backing field.

Some examples (that without that feature, will have to be written as full property):
* `public int Price { get; set => value < 0 ? 0 : value }`
* `public string FirstName { get; set { onPropertyChanged(); return value.Trim(); } }`
* `public string EntityName { get => value.replace("_", " "); set; }`

# Why this is useful?
1. Improve productivity.
2. Helps to keep a shorter, more readable and more maintainable code.
3. Prevent developers to use the backing field directly without the property (getters & setters). But if they really want to use the backing filed, then they can still use a full property.

**Comment by alrz** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/140

**Comment by yaakov-h** [comment]
This seems very similar to #140.

Though your example wouldn't work for `INotifyPropertyChanged`, because you would be triggering the `PropertyChanged` event _before_ changing the property value.

**Comment by rhalaly** [comment]
Missed that issue... thanks!

**Comment by jnm2** [comment]
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
