### ISSUE TITLE
setting anonymously-typed variable to null?

### ISSUE THREAD

**Issue by Spongman** [dotnet/csharplang#2142]
valid c#7 code that gives a CS8600 warning in c#8:
```c$
var foo = new {};
foo = null;
```

IMHO the lack of `var?` in c#8 is a huge hole, especially wrt existing code.

**Comment by DavidArno** [comment]
Which C# 8 compiler are you using to get that warning? I've tried in VS2019 Preview 1.1 and [using master on sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgMwAEhATKQAoID2A5gLABQA3q6V+WYQIwA2cgBZSAWQiYAdgAoAlJ24cWASG6k0EBKWx06pALykpcAO6k2AXwDcrFSt36jUgK4AbN7ZbrLrS0A=) and neither gives me a warning.

**Comment by yaakov-h** [comment]
@DavidArno `#nullable enable` 😉

**Comment by DavidArno** [comment]
@yaakov-h, oh, of course. Thanks.

```cs
var foo = new {};
foo = null!;
```
Problem solved.

**Comment by DavidArno** [comment]
@orthoxerox 

True, we've simply suppressed the warning. But I strongly disagree with the claim that "*the lack of `var?` in c#8 is a huge hole*". There are numerous work-arounds, such as `null!` and using `object?` instead of `var`. 

`var?` might be slightly beneficial is some edge cases, but it hardly seems compelling compared with the hundreds of other things that could be added to the language.

**Comment by Spongman** [comment]
yeah, the problem with these workarounds (`null!` and `object?`) is that neither are sufficient in all but the most trivial example - i assume you understand that the example above is a minimal repro from significantly more complex real-world code?

`null!` is insufficient since, as @orthoxerox pointed out, the variable declaration is still non-nullable which  means that you can later pass a `null` value into a non-null-accepting function without warning:

```
{
  void Bar(string bar) {}

  var foo = new {};
  foo = null!;
  Bar(foo); // no warning
}
```

and `object?` ?. seriously? how does one call `Enumerable.Select<T>` on an `object?` ?

my opinion is still humble, but increasing less so.

**Comment by gafter** [comment]
`#nullable safeonly`

**Comment by MrJul** [comment]
I think the main problem is that surprisingly, there's no way to explicitly "cast" from a non-nullable expression to a nullable one without specifying the receiving type explicitly (for the opposite, you can use `!`).

Fortunately this can be worked around:

```C#
public static T? ToNullable<T>(T value) where T : class => value;
...
var foo = ToNullable(new {});
foo = null;
```

**Comment by Spongman** [comment]
@MrJul great workaround! a little hacky, but still, it plugs the hole somewhat.

**Comment by YairHalberstadt** [comment]
Closing as this no longer gives a warning on more recent compiler versions
