### ISSUE TITLE
Proposal: allow Nullable<T> for type constraints

### ISSUE THREAD

**Issue by lachbaer** [dotnet/csharplang#215]
Currently it is not possible to define a type constraint for nullable types.  I just ran into this issue.

```C#
public bool AsClikeBoolean<T> (T value) where T : Nullable<> // or "where T?"

// these work:
public bool AsClikeBoolean<T> (T value) where T : class
    => value != null;
public bool AsClikeBoolean<T> (T value) where T : struct
    => ! value.Equals(default(T));
```
Probably the underlying changes outweigh the use of it?

**Comment by CyrusNajmabadi** [comment]
> public bool AsClikeBoolean<T> (T value) where T : Nullable<>

What is this trying to say?  That T must be nullable?  If that's the case, you can just write:

```c#
public void M<T>(T? value) where T : struct
{
}
```

**Comment by lachbaer** [comment]
@CyrusNajmabadi 
Damn it 😳 I searched the web for a solution of this and didn't find it, except for complex solutions and statements saying that it is not possible.
Thanks!!!
