### ISSUE TITLE
Shorter syntax for nested foreach loops

### ISSUE THREAD

**Issue by thargol1** [dotnet/csharplang#2150]
# Shorter syntax for nested foreach loops.

Allow multiple loop declarations within the parentheses of foreach()

## Why
* Less indent levels
* Less code

## Example
```csharp
// Current code for nested foreach loops
foreach (var customer in Customer)
{
	foreach (var order in customer.Orders )
	{
		foreach (var line in order.Lines)
		{
			// Do something customer, order and line
		}
	}
}

// Proposed code for nested foreach loops
foreach (var customer in Customer, var order in customer.Orders, var line in order.Lines)
{
	// Do something customer, order and line
}
```
This example is a bit contrived. I seldom use triple nested loops, but double nested are quite regular.

## Implementation
The compiler rewrites the new syntax to the old syntax.

### Note
I did search for similar issues and could not find them. If they do exist please explain how to find them.

**Comment by jwooley** [comment]
I'm not sure I see the benefit of the shortened syntax and it feels like I loose control. For example, I wouldn't want to set the value for the customer for each iteration of order.lines. With the presence of default interface implementation, would adding a default implementation on IEnumerable of Each (or ForEach) like we have in IX make sense. That would allow for the following "shortened" syntax:

```
Customer.Each(customer => 
{
    customer.Orders.Each(order => 
    {
        order.Lines.Each(line =>
        {
            // Do something with customer, order, line
        });
    });
});
```

**Comment by gafter** [comment]
``` c#
foreach (var customer in Customer)
foreach (var order in customer.Orders )
foreach (var line in order.Lines)
{
	// Do something customer, order and line
}
```
- Less indent levels
- Less code
- No language change

**Comment by theunrepentantgeek** [comment]
```
foreach (var customer in Customer, var order in customer.Orders, var line in order.Lines)
{
	// Do something customer, order and line
}
```

My first thought when I saw this code was that all three would be iterated in parallel, effectively defining `(customer, order, line)` as a tuple, and I wondered why anyone would want that ... 

... then I read the rest of the proposal.

👎 because almost invariably(1), nested loops are a code smell that the method is doing too much.

(1) Exception being matrix manipulation, etc, but that's niche.

**Comment by thargol1** [comment]
I withdraw this proposal. @gafter is right about the syntax, if only the code-formatters wouldn't indent it automatically. @theunrepentantgeek  is right about the code smell.

And I just realized the short syntax is possible with Linq. `from customer in Customers, order in customer.Order` etc.

@jwooley: using delegates is a performance killer in my experience.

**Comment by Joe4evr** [comment]
@thargol1 
> using delegates is a performance killer in my experience.

[And yet you're deciding to use LINQ?!](https://sharplab.io/#v2:CYLg1APgAgDABFAjAFgNwFgBQsGIHQAyAlgHYCOG2iAbAgExwAKWA3lnB7rVMnMeQAokAZgA8AYQCuAZwAuAewC2AUwBOAPjgBjGQpWrpASnac2mThbgA3AIaq4JaXAC8cAGaql23UrVxS3nK+BiaWcACQ4e6einDyqsB+ATpB+ngA8glq0qFhedFeADakyv4kcVmqhCU55vn50sqFylqycMUkyngAcjYqlBYAvljDmFhQwvR8Jay5E7jwvSpwLHAA5sqyqHCjo/NQDJmJqrN1HPuIYvzKmtdOqxtbOyPjkwdwUqlqpxYXYkdqTQAgwrdabba7IA)
