### ISSUE TITLE
Context blocks for modifiers and attributes

### ISSUE THREAD

**Issue by RobotAL76** [dotnet/csharplang#2157]
Please, look at code samples
```c#
class Person
{
    [DataMember] public string FirstName { get; set; }
    [DataMember] public string LastName { get; set; }
    [DataMember] public string Address { get; set; }
    [DataMember] public int Age { get; set; }
}
```
```c#
class Person
{
    [DataMember] public
    (
        string FirstName { get; set; }
        string LastName { get; set; }
        string Address { get; set; }
        int Age { get; set; }
    )
}
```
```c#
static class Winmm
{
    [DllImport("winmm.dll")] public static extern MmResult waveOutPrepareHeader(IntPtr hWaveOut, WaveHeader lpWaveOutHdr, int uSize);
    [DllImport("winmm.dll")] public static extern MmResult waveOutUnprepareHeader(IntPtr hWaveOut, WaveHeader lpWaveOutHdr, int uSize);
    [DllImport("winmm.dll")] public static extern MmResult waveOutWrite(IntPtr hWaveOut, WaveHeader lpWaveOutHdr, int uSize);
    [DllImport("winmm.dll")] public static extern Int32 mmioStringToFOURCC([MarshalAs(UnmanagedType.LPStr)] String s, int flags);
    [DllImport("winmm.dll")] public static extern Int32 waveOutGetNumDevs();
}
```
```c#
static class Winmm
{
    [DllImport("winmm.dll")] public static extern
    [
        MmResult waveOutPrepareHeader(IntPtr hWaveOut, WaveHeader lpWaveOutHdr, int uSize);
        MmResult waveOutUnprepareHeader(IntPtr hWaveOut, WaveHeader lpWaveOutHdr, int uSize);
        MmResult waveOutWrite(IntPtr hWaveOut, WaveHeader lpWaveOutHdr, int uSize);
        Int32 mmioStringToFOURCC([MarshalAs(UnmanagedType.LPStr)] String s, int flags);
        Int32 waveOutGetNumDevs();
    ]
}
```
Open questions:
1. should be used Parentheses `( ... )` like in samples or Brackets `[ ... ]` or even Braces `{ ... }`
2. possible generalizations for other modifier keywords and their combinations (`private`, `protected`, `internal`, `public`, `static`, `abstract`, `readonly`, `const`, `extern`)
```c#
class Person
{
    // ???
    [DataMember] // private
    (
        string FirstName { get; set; }
        string LastName { get; set; }
        string Address { get; set; }
        int Age { get; set; }
    )
}
 
/* possible, should be allowed recursive and empty variations too with any valid order */
class AnyClass
{
    public
    (
        static
        (
            readonly
            (
                 object AnyField = new object();
            )
        )
 
        const
        (
        )
    )
}
 
class Person
{
    [DataMember] public
    (
        string FirstName { get; set; }
        string LastName { get; set; }
        [AnyCustomAttribute] string Address { get; set; }  /* should be allowed ??? */
 
        readonly object AnyField;
    )
 
    [DataMember(Name="age")] public int Age { get; set; }
 
    public static readonly
    (
        object StaticField1 = new object();
        object StaticField2 = new object();
        /* ... */
    )
 
    private readonly
    (
        object InstanceField3 = new object();
        object InstanceField4 = new object();
        /* ... */
    )
}
```
The main goal of the proposal is minimization of repeating modifiers and attributes.

Related issues:
https://github.com/dotnet/csharplang/issues/1391
https://github.com/dotnet/csharplang/issues/818

**Comment by RobotAL76** [comment]
@svick 
Thank for your opinion!

Seems that it is like two sides of the same coin.

Sometimes for non well-generalized cases full forms are required, of course.
```c#
class Person
{
    [DataMember(Name="First_Name")] public string FirstName { get; set; }
    [DataMember(Name="Last_Name")] public string LastName { get; set; }
    [DataMember] public string Address { get; set; }
    [DataMember] public int Age { get; set; }
}
```
But when the code (or architecture of a solution) highly generalized it is possible to use more aesthetic variations.
```c#
class Person
{
    [DataMember] public
    (
        string FirstName { get; set; }
        string LastName { get; set; }
        string Address { get; set; }
        int Age { get; set; }
    )
}
```
This is like a special kind of mathematical beauty
```
a*x + b*y + c*z

a*x + a*y + a*z = a*(x + y + z) 

a*x + a*z + c*z = a*(x + z)  + c*z = a*z + (a + c)*z
```

**Comment by theunrepentantgeek** [comment]
Not all - nor even most - mathematical operations are associative like that.

I cut my teeth as a professional developer on Delphi, where class declarations are grouped into sections by visibility:

``` delphi
type TDemo = class
  private 
    mFullName: string;
    mKnownAs: string;
    mFamilyName: string;
  public
    property FullName: string read GetFullName write SetFullName;
    property KnownAs: string read GetKnownAs write SetKnownAs;
    property FamilyName: string read GetFamilyName write SetFamilyName;
end;
```

Delphi even went as far as separating declaration from implementation. (Please forgive any syntax errors in the above, it's been a while ...)

Thing is, in retrospect, all that mandated grouping had a grossly negative effect on the readability of the code. Tightly related members could end up dozens, even hundreds of lines apart in the code, because of the mandated structure.

The groupings you propose wouldn't be used to group four or five lines, they'd be surrounding hundreds or thousands of lines of code, making it much much harder to understand the code being read on screen.

Imagine what happens if I extracted a method for reuse and it _silently_ was declared as **static** because of a modifier hundreds of lines earlier in the file.

Having to separately declare attributes, visibility and other modifiers on each member isn't a bug of the c# language, it's a feature. And a good one at that.

**Comment by RobotAL76** [comment]
@theunrepentantgeek 
Thank for your point of view!

The problem and the feature of Delphi is **required** grouping in sections according modifiers.
The feature and the problem of C# is **required** duplication of modifiers for each member.

Seems that the most powerful and balanced approach is allowing of two possible options when developer may choose and apply the better variation for a concrete case.

**Comment by jnm2** [comment]
@RobotAL76 Is the only difference between this issue and #818 that you're brainstorming additional syntax options?

**Comment by RobotAL76** [comment]
@jnm2 
There are two key differences: syntax and recursive generalization with mathematical [associative property](https://en.wikipedia.org/wiki/Associative_property).

**Comment by gafter** [comment]
Brainstorming on #818 can continue there.
