### ISSUE TITLE
Add interfaces for primitives

### ISSUE THREAD

**Issue by JustNrik** [dotnet/csharplang#2166]
My suggestion is to add the following interfaces
```cs
public interface IPrimitive { }
public interface INumeric : IPrimitive { }
public interface INonNumeric : IPrimitive { } // used for Char, String, DateTime, DateTimeOffset and TimeSpan
public interface IInteger : INumeric { } // used for Byte, Int16/32/64 and possibly BigInteger
public interface IReal : INumeric { } // used for Single, Double and Decimal
public interface IComplex : INumeric { } // used for complex numbers maybe?
```
Although they don't have any member to implement (pretty much "cosmetic" interfaces) they would be useful for generic constrains. For example:
```cs
public struct Vector<TX, TY> 
    where X : IReal 
    where Y : IReal
{
    public TX X { get; set; }
    public TY Y { get; set; }

    public Vector(TX x, TY y)
    {
        X = x;
        Y = y;
    }
}
```
So we could use it as:
```cs
var vector = new Vector<float, float>(5.0f, 2.5f);
``` 
instead of creating 3 different structs with pretty much the same logic

What do you think guys?

**Comment by svick** [comment]
If those interfaces don't have any members, how are you going to implement that logic? Say, you wanted to be able to add two `Vector`s together. How do you implement that?

If you mean that this would be only for types that don't have any members that operate with the `T`s, then what would be the point of those constraints?

**Comment by scalablecory** [comment]
A better idea of a "static interface" has been floated in the past, which would allow defining static methods and operators. Not sure where that is, there's probably an issue for it still.

**Comment by JustNrik** [comment]
> 
> 
> If those interfaces don't have any members, how are you going to implement that logic? Say, you wanted to be able to add two `Vector`s together. How do you implement that?
> 
> If you mean that this would be only for types that don't have any members that operate with the `T`s, then what would be the point of those constraints?

What I meant is, to have a common interfaces between primitive types, just as an example, let's take vectors. Why should I make a so many vector structs when I could have a generic one? which currently ins't possible unless you make conversions and a load of methods, for example, a simple `Vector<int, int>` has its logic, but there could be a bigger vector, like `Vector<long, long>`, they both will have exactly the same logic, the only difference is that `Vector<int, int>` properties will be both `int` and `Vector<long, long>` properties will be `long`, this would also be useful for methods that involve working with numbers, for example, you could have a method to do math operations with whole numbers instead of creating an overload with the same logic for int, long, etc... They could have members as well I just don't know which ones all primitives have, one could be `MaxValue` and `MinValue` but that would require the interface to accept static/const members, which is possible since as far as I know, CRL allows constants on interfaces but they aren't allowed on .NET langs by design, so these interfaces would end up being like this:
```cs
public interface INumeric<T> where T : INumeric
{
    const T MaxValue;
    const T MinValue;
}
```
Another possibility would be to make `INumeric<T>` to inherit all interfaces numeric primitives implement, like `IComparable<T>`, `IEquatable<T>`, etc... So the interface won't be there just empty being a make up



> 
> 
> > A better idea of a "static interface" has been floated in the past, which would allow defining static methods and operators. Not sure where that is, there's probably an issue for it still.
> 
> You might be thinking of [Shapes](https://github.com/dotnet/csharplang/issues/164), which sounds like what OP is suggesting here.

Not exactly but my suggestion is related to it somehow, the idea of Shapes is really interesting

**Comment by GalaxiaGuy** [comment]
Interestingly, this must have seriously investigated at some point:

https://github.com/Microsoft/referencesource/search?q=iarithmetic&unscoped_q=iarithmetic

**Comment by johnkellyoxford** [comment]
Personally I would just want this as a generic constraint. E.g, `void Meth<T>() where T : primitive`

**Comment by JustNrik** [comment]
> 
> 
> Personally I would just want this as a generic constraint. E.g, `void Meth<T>() where T : primitive`

That'd work too, but here should be more constrains, like for numeric and non-numeric (date and string/char)

**Comment by JustNrik** [comment]
> 
> 
> Neither DateTime nor String is primitive

Oh I see, decimal isn't a primitive either so I guess numeric constrain would be better?

**Comment by johnkellyoxford** [comment]
I guess, though a primitive constraint might still have uses

**Comment by jnm2** [comment]
@johnkellyoxford 

> `void Meth`

What now? :D

**Comment by HaloFour** [comment]
> (assuming the possibility of static/const members on interfaces)

Neither static nor const members make sense on interfaces.  The former requires an instance through which to perform a vtable lookup in order to implement a virtual dispatch.  The latter is not a proper member and requires that the compiler resolve and replace with the actual value at compile time.

I'd think all of the functionality that you're looking for can be accomplished through shapes, which will be significantly more flexible and performant than normal interfaces could be in these circumstances.

**Comment by chucker** [comment]
>>You might be thinking of Shapes, which sounds like what OP is suggesting here.

>Not exactly but my suggestion is related to it somehow, the idea of Shapes is really interesting
>
>In general, my suggestion would look kind of like this (assuming the possibility of static/const members on interfaces):
>
>[..] `static bool TryParse(string s, IFormatProvider provider, out T result);`
>
>you may get an idea from here I guess

I feel like this is quite close to the Shapes and Extensions proposal:

* you want to retroactively add a contract* to _existing_ types such as `System.Int32`. Interfaces currently only work if predefined in the type. Short of writing your own implementation of `int`, it's not currently possible to add any further contract.
* you want that contract to have static members. Interfaces only support instance members.

Both of these are precisely the example given by Mads: first, he defines a contract `public shape SGroup<T>`, using a shape. Then, he implements this for `int` using an extension: `public extension IntGroup of int : SGroup<int>`. So now we're retroactively implementing code that works on `int`. _And_ that contract has static members.

From my understanding, in a world where `int.TryParse`, `double.TryParse` and so forth didn't already exist and Shapes and Extensions _did_, they would instead be declared inside an `SParseable<T>`.

Since you said "not exactly" — semantics aside, is there something in particular about your proposal that differs?

*) I'm avoiding the word _interface_ or _shape_ in favor of something more all-encompassing.

**Comment by JustNrik** [comment]
> 
> 
> > > You might be thinking of Shapes, which sounds like what OP is suggesting here.
> 
> > Not exactly but my suggestion is related to it somehow, the idea of Shapes is really interesting
> > In general, my suggestion would look kind of like this (assuming the possibility of static/const members on interfaces):
> > [..] `static bool TryParse(string s, IFormatProvider provider, out T result);`
> > you may get an idea from here I guess
> 
> I feel like this is quite close to the Shapes and Extensions proposal:
> 
>     * you want to retroactively add a contract* to _existing_ types such as `System.Int32`. Interfaces currently only work if predefined in the type. Short of writing your own implementation of `int`, it's not currently possible to add any further contract.
> 
>     * you want that contract to have static members. Interfaces only support instance members.
> 
> 
> Both of these are precisely the example given by Mads: first, he defines a contract `public shape SGroup<T>`, using a shape. Then, he implements this for `int` using an extension: `public extension IntGroup of int : SGroup<int>`. So now we're retroactively implementing code that works on `int`. _And_ that contract has static members.
> 
> From my understanding, in a world where `int.TryParse`, `double.TryParse` and so forth didn't already exist and Shapes and Extensions _did_, they would instead be declared inside an `SParseable<T>`.
> 
> Since you said "not exactly" — semantics aside, is there something in particular about your proposal that differs?
> 
> *) I'm avoiding the word _interface_ or _shape_ in favor of something more all-encompassing.

I was thinking in smth like this: https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABJgRgG4BYAKB1wGUALRAJwAcAZRYAOgCUBXAOzgCWqAKaky5ANoApAXADiw3sPoCAxgAo4AT0bCA9gDN1A/gEpTMXDPmLlazTv1GANnt4Bzc5esKlKjdq6hupy3AIAJuYAuuSYAMz4BBD4AEy4AIIqcDQigqoAPAAqAHy4AO40ysK4hbgguMhw9NyqcOQA3uS43fgJhMm1VNzATYit6rXOwgZwlrUq7jRwpl09nWQ9m7gCBrgOQUaFprgAvCe4gU7GZisbW93r990AkJgA7HtH6nrAAFbCrVM6muy2+fwByymM1wAFo9iZQT9/oCFktTGInrgAL6re7CZzIao7PaXYJHU7nUkuNyeW6Yx6YnrvT5ApEQoHqVweVngwFQuCwvZczxg5HLVHLDFPHF3PEE4S4rYMxm4AD0quoND03Gc4Vw4WmiB1AuAYwA1hc9A1XGVcIxENlLMgWjRcCh8Hh6NMpq0BG5FZj1ZbcKpKqoLQY9PRcHpGAB9IYjehjAWIXh61SIZzOEzuC50NqyxnZeh6W1KW0AOT0cAAkqhGFMRPxhOEAKJgVTCRiCNzqdEBnoyzYyrFAA

Although, I haven't benchmarked to see if it is poor performant as people claims.
