### ISSUE TITLE
Implementing interfaces with inherited members

### ISSUE THREAD

**Issue by Laurnz** [dotnet/csharplang#2170]
I want to implement in my Bar class the member MyFoo as Foo and not as IFoo.
````
interface IFoo { }

interface IBar
{
    IFoo MyFoo
    {
        get;
    }
}

class Foo : IFoo { }

class Bar : IBar
{
    public Foo MyFoo
    {
        get;
    }
}
````
I want to make it possible for classes that reference Bar directly (and not over the interface IBar) to have access to for example more methods in MyFoo than IFoo has by default.

Why is this not possible?

**Comment by YairHalberstadt** [comment]
#49

**Comment by MkazemAkhgary** [comment]
If your case is simple you can do this

```c#
class Bar : IBar
{
    public Foo MyFoo
    {
        get;
    }

    IFoo IBar.MyFoo => MyFoo;
}
```

but for complex hierarchies, this isn't really practical.

**Comment by gafter** [comment]
Dup of #49
