### ISSUE TITLE
Proposal: Succinct variable assignment

### ISSUE THREAD

**Issue by bradley8** [dotnet/csharplang#2172]
In TypeScript a type can be injected and assigned to a variable in a single succinct line of code like so.

```
export class MyClass {
constructor(private privateMember: Member){
  }
} 
```

Would it be possible (and sensible) for this excellent TypeScript construct to be made available in C#?
The standard verbose boilerplate approach below.

```
export class MyClass{
private _privateMember;
constructor(member: Member){
   this._privateMember = member;
   }
}
```

**Comment by YairHalberstadt** [comment]
See the Records proposal

**Comment by Richiban** [comment]
@YairHalberstadt This has nothing to do with records (except for the fact that records can also do this).

It's a general feature known as a 'primary constructor', and has been suggested multiple times before, but unfortunately has not gained any traction with the language team.

**Comment by HaloFour** [comment]
@Richiban 

It has gained traction, to the degree that they tried to design it out in some depth on [CodePlex](https://archive.codeplex.com/?p=roslyn) (sorry, with the repo archived I can't deep link).  It got sucked into the rabbit hole of people wanting it to be a fully-featured alternative to normal constructors which led to some ... "interesting" syntax and scoping behaviors.  And they're still included in the record proposal, if only in a more limited form.  But recent team proposals for records have also included additional keywords like "data" to drive the record functionality, so it's possible that primary constructors will remain general purpose and not tied to records.  I doubt we'll see any movement on that until after C# 8.0 is released.

**Comment by Richiban** [comment]
@HaloFour I'm very glad to hear that the team has been considering an extra keyword for record functionality, both because I think this is a good step for records as well as for primary constructors.

We'll have to see what comes out of future language versions; all we can do here is make our case on GitHub and hope we can get our point across correctly and politely 😃

**Comment by bradley8** [comment]
> @YairHalberstadt This has nothing to do with records (except for the fact that records can also do this).
> 
> @bradley8 It's a general feature known as a 'primary constructor', and has been suggested multiple times before, but unfortunately has not gained any traction with the language team.

@Richiban Thanks! I had a feeling it had probably been suggested before but I couldn't find anything with a search. Now that I know what it's called I know what to search for.   ; )

**Comment by Joe4evr** [comment]
Please close, though.
