### ISSUE TITLE
IReadOnlyDictionary variance

### ISSUE THREAD

**Issue by fast4shoot** [dotnet/csharplang#2175]
`IReadOnlyDictionary` is currently invariant in both its key and its value.

It should be contravariant in the key and covariant in the value, similarly to how `IReadOnlyCollection` is covariant in the value.

The following should logically be legal, but isn't because of the invariance:

```C#
IReadOnlyDictionary<object, string> dict = new Dictionary<object, string>();
IReadOnlyDictionary<string, string> dict2 = dict; // key contravariance
IReadOnlyDictionary<object, object> dict3 = dict; // value covariance
IReadOnlyDictionary<string, object> dict4 = dict; // both
```

**Comment by HaloFour** [comment]
This would be a BCL request, not a language request.  You can submit those here:  https://github.com/dotnet/corefx/issues

That said, looking at the interface I don't think it would be possible to make it variant.  You have the indexer which accepts `TKey` and the `Keys` member which returns an `IEnumerable<TKey>` so `TKey` couldn't be variant.  You also have `TryGetValue` which passes a `ref TValue` so `TValue` can't be variant.

**Comment by fast4shoot** [comment]
>This would be a BCL request, not a language request. You can submit those here: https://github.com/dotnet/corefx/issues

Good point, sorry about that.

>the Keys member which returns an IEnumerable<TKey> so TKey couldn't be variant

I must've missed that previously, but you're right. The fact that one can enumerate the keys does indeed make key contravariance impossible.

> You also have TryGetValue which passes a ref TValue so TValue can't be variant.

So apparently there's nothing like `out` in the CLR and so the `out TValue` is really a `ref TValue` which means that `TValue` can't be covariant. Unfortunate.
