### ISSUE TITLE
Please port design notes from codeplex

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2178]
@gafter commented on [Mon Sep 19 2016](https://github.com/dotnet/roslyn/issues/13920)

There are many LDM notes orphaned at

http://roslyn.codeplex.com/wikipage?title=CSharp%20Language%20Design%20Notes&referringTitle=Documentation

Please port them into this repository.

**Comment by YairHalberstadt** [comment]
I think they've all been ported - I can't find any on codeplex which aren't here.

**Comment by gafter** [comment]
I have checked as well and I agree that they've all been ported.
