### ISSUE TITLE
Allow in to be used inside for

### ISSUE THREAD

**Issue by lust666** [dotnet/csharplang#2185]
That would be an alternative to using `foreach`. One keyword could be used for all types of loops then. The only problem is `foreach` would become useless.

```csharp
for (var foo in foos)
{
}
```

Originally proposed in https://github.com/dotnet/csharplang/issues/2184

**Comment by MeikTranel** [comment]
`for` and `foreach` difference isnt automatic indexing.  

`foreach` builds on top of IEnumerable, GetEnumerator and MoveNext, while the ol' `for` loop is explicit about some kind of counting/indexing mechanism.
`IEnumerable `does not imply any order, while `for` does. Merging these back together would mean we'd have to weaken `for` and put `foreach` into obsolescence, for no gain other than reducing keywords (and we wouldnt even reduce. you can't just deprecate foreach. people would kill over this).
