### ISSUE TITLE
fixed declarations

### ISSUE THREAD

**Issue by tannergooding** [dotnet/csharplang#2186]
### Summary

Much in the same way that `using declarations` have been enabled in the language, we should allow `fixed declarations`.

### Motiviation

The motiviations, design, and considerations are essentially the same as for `using declarations` and `fixed` was listed as a possible `future expansion` in the original `using declaration` proposal: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/using.md#future-expansions

**Comment by YairHalberstadt** [comment]
Defer currently wouldn't be able to be used here, but maybe that might be a better path to go down?

**Comment by Perksey** [comment]
+1

**Comment by john-h-k** [comment]
would also love this much
