### ISSUE TITLE
Add a compiler error for struct with overlapped reference field

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/csharplang#2189]
I would expect the compiler to emit an error for the following program:

```
using System;
using System.Runtime.InteropServices;

class Program
{
    static void Main()
    {
        new Foo(Guid.NewGuid());
    }
}

[StructLayout(LayoutKind.Explicit)]
struct Foo
{
    public Foo(object o)
    {
        this = default;
        this.o = o;
    }

    public Foo(Guid g)
    {
        this = default;
        this.g = g;
    }

    [FieldOffset(0)]
    readonly object o;
    [FieldOffset(0)]
    Guid g;
}
```
Instead the result is a `TypeLoadException` for `Foo` at runtime. Detecting this scenario seems like it should be pretty straightforward at compile time. The issue might be less obvious if instead of `object`, the other field was a struct which itself contained a reference field.

Oh. As I was writing this, I think I realized why this might not work. If one of the overlapped fields was a struct defined in a separate assembly, then if the other assembly changed to _add_ a ref field to that struct, then my `Foo` struct would _become_ unloadable after it was compiled, and a `TypeLoadException` would be the only way to report that. Still, it seems like it would be worth alerting me that my own code is trying to do something impossible with a compiler error.

**Comment by Joe4evr** [comment]
On the one hand, adding warnings/errors to code that didn't have errors before is a massive breaking change that may prevent people from upgrading their compiler, so the team is quite adverse to doing so.
On the other hand, it seems this unconditionally throws at runtime, so it never would never have been working in the first place.
> The issue might be less obvious if instead of `object`, the other field was a struct which itself contained a reference field.

True, but the compiler now has a heuristic to detect such cases that is used for the `unmanaged` generic constraint, so it could be pretty trivial to hook into that for determining these kinds of overlaps.

**Comment by benaadams** [comment]
objects overlapping objects; is ok, its structs overlapping objects that's a no no. (As the struct data would give the GC a gibberish object pointer)

**Comment by MarkPflug** [comment]
@benaadams Yeah, I understand that. I'm suggesting that since the result would be gibberish (hence the TypeLoadException to prevent what would result in an inevitable access violation crash) it should be a compiler error or at the very least a warning when you define a struct that is in obvious violation.

**Comment by benaadams** [comment]
Makes sense

**Comment by CyrusNajmabadi** [comment]
@MarkPflug Couldn't this be done as an analyzer?  It's unclear why this would need to go into the compiler.

**Comment by tannergooding** [comment]
@CyrusNajmabadi, you could imagine that this would actually be needed if unions ever got first class support. But, I don't think it is necessarily worthwhile as a standalone feature.

**Comment by MarkPflug** [comment]
Yes, I'll admit this is a rare scenario, and is probably esoteric enough that most people would never encounter it. Why would it need to go into the compiler? It seems like code that can't possibly be correct at runtime, and can be identified at compile time is worth warning the developer about. Could it be implemented as an analyzer? Probably.

**Comment by CyrusNajmabadi** [comment]
> Could it be implemented as an analyzer? Probably.

Then i would definitely recommend that.  You could do that right now with existing available tools, and it wouldn't occupy any Roslyn resources (i.e. team members) at all to do so.
