### ISSUE TITLE
Do something with IReadOnlyCollection and ICollection. We needs good abstractions hierarchy.

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/csharplang#219]
Just drop IReadOnly****, mark them obsolete.
We can't do anything with backward compatibility here. 
If we inherit ICollection from IReadOnlyCollection we will broke existing code.
See: http://stackoverflow.com/questions/12622539/why-doesnt-generic-icollection-implement-ireadonlycollection-in-net-4-5

But may be sometime will be good point do do this breaking change, provide tools for migration automation. 

And also IReadOnly*** is not clear solution, we needs IReadable*** and IImmutable****

This is not-null reference types like problem. But it's second after nullability.
Let's start/continue to solve this problem.

**Comment by jnm2** [comment]
I like this except that so many .NET libraries, not just the BCL, have accepted that IReadOnly == IReadable and follow that convention. I don't see any wins in fixing it in the BCL after it's sunk in and spread so far. *I* choose ReadOnly over Readable because that's what it means to everyone now and it communicates precisely what I intend.

**Comment by dmitriyse** [comment]
If we can't do anything in CLR, We can use not-null reference  approach. ICollection annotated with ImmutableAttribute or ReadableAttribute should be handled by compiler and DevTools to block from writing to a collection.
```C#
public void SomeReadOnlyConsumer(IReadable<T> c){}
```
or 
```C#
public void SomeReadOnlyConsumer(readable ICollection<T> c){}
```

can be treated by CLR as
``` C#
public void SomeReadOnlyConsumer([Readable[]]ICollection<T> c){}
```

Toolset will save us!

**Comment by dmitriyse** [comment]
IReadOnly == IReadable, Yes i agree it's not a bit trouble. We just needs IImmutable and some way to annotate semantic of each variable/argument/field/property.

**Comment by HaloFour** [comment]
This has nothing to do with C# the language.  I'd suggest proposing this at the [CoreFX](https://github.com/dotnet/corefx) repository.

Although this argument has already happened [here](https://github.com/dotnet/corefx/issues/1973).  In short, too late, that ship has long since sailed.

**Comment by dmitriyse** [comment]
Yes i will duplicate. But i disagree without that nothing to do with C#. Non-Null reference is also "too late" feature. But it will be finally appear in C# 8.0.
THE SAME APPROACH POSSIBLE.
```CSharp
public void MyMethod(readable ICollection<T> c)
where T: new
{
     c.Add(new T()) // Compiller Error/Warning.
}
``` 
It's toolset/C# languate related solution method.

**Comment by dmitriyse** [comment]
```CSharp
public void MyMethod(readonly ICollection<T> c)
where T: new
{
     c.Add(new T()) // Compiller Error/Warning.
}

public void MyMethod(immutable ICollection<T> c)
where T: new
{
     c.Add(new T()) // Compiller Error/Warning.
}
``` 

This would be killing feature, that can greatly improve compile-time checking.

**Comment by dmitriyse** [comment]
```CSharp
public class MyClass
{
    public readonly ISet<string> MyStrings {get;} = new HashSet(){"dog", "cat", "blackjack"};
}

public void Test()
{
    var a = new MyClass();
    a.Contains("dog"); // Good usage.
    a.MyStrings.Add("mouse"); // Compiler error/warning.
}
```

**Comment by dmitriyse** [comment]
There is more suitable solution for this general problem:
https://github.com/dotnet/csharplang/issues/222
https://github.com/dotnet/corefx/issues/16660
https://github.com/dotnet/corefx/issues/16661
https://github.com/dotnet/corefx/issues/1973

So I am closing this issue on C# Language repository.

**Comment by svick** [comment]
Not sure if you've arrived at a similar idea independently, or if you were inspired by it, but the approach of marking variables as `readable` and `immutable` sounds very similar to what @joeduffy describes Midori (experimental OS based on C#/.Net) did. Though [their system](http://joeduffyblog.com/2016/11/30/15-years-of-concurrency/#the-model) was much more comprehensive and complicated and was mostly about concurrency safety.

**Comment by dmitriyse** [comment]
Thank you for this link, I will inspect their work and result.
