### ISSUE TITLE
[Proposal]: foreach add index

### ISSUE THREAD

**Issue by ichensky** [dotnet/csharplang#2192]
For code: 
```csharp
foreach (var key in keys) { ... }
```
add not required param `index`
```csharp
foreach (var key, index in keys) { ... }
```
that, this code would be equal to the (without yield return scenario): 
```csharp
int index=0; 
foreach (var key in keys) { 
...
index++;
}
```

**Comment by devSoheilAlizadeh** [comment]
This is duplicate to #1584

**Comment by willard720** [comment]
There is a clever way to do this with tuples that you should look into. I say that because I forgot how to

**Comment by jnm2** [comment]
@willard720 Are you thinking of https://github.com/dotnet/csharplang/issues/1584#issuecomment-393486675?

**Comment by YairHalberstadt** [comment]
Closing as duplicate of #1584
