### ISSUE TITLE
Control how constructors and deconstructors are auto generated

### ISSUE THREAD

**Issue by ghost** [dotnet/csharplang#2203]
# Suggestion:
Use a DeConstructable attribute to mark class properties that will be use to generate the class constructors and deconstructors. This attribute receives an order param to control the corresponding params order in the in constructors and deconstructors. This will allow us to control which properties will be De/Constructed and which will be not, and in what order.

```
class Class1
{
   [DeConstructable(1)] public int Id { get; set; }
   [DeConstructable(2)] public string Name { get; set; }
   public string Notes { get; set; } // Not De/Constructable
   [DeConstructable(3)] public int Age { get; set; }
}
```

# Usage:
```
var x = new Class1(1, "Adam", 10);
x.Notes = "……";
var (ID, Name , Age) = x;
```

# Implementation:
C# can compile Class1 to:
```
class Class1
{
   public int Id { get; set; }
   public string Name { get; set; }
   public string Notes { get; set; }
   public int Age { get; set; }

   public Class1(int id) => Id = id;
   public Class1(int id, string name): this(id) => name = Name;
   public Class1(int id, string name, int age) : this(id, name) => age = Age;

   public void Deconstruct(out int id, out string name)
   {
      id = Id;
      name = Name;
   }

   public void Deconstruct(out int id, out string name, out int age)
   {
      (id, name) = this;
      age = Age;
   }
}
```

**Comment by MkazemAkhgary** [comment]
I think it would be better if Records had this feautre automatically

**Comment by MohammadHamdyGhanem** [comment]
@MkazemAkhgary
Ok, but this will need to shorten the syntax, say:
```
public class Class1([DC(1)] int ID, [DC(2)] string Name, string Notes, [DC(3)] int Age);
```

Or it is best for records to use the order by which the properties appear, but use an attribute to exclude some properties:
```
public class Class1(int ID, string Name, [NoCD] string Notes, int Age);
```

Anyway, my general perposal is also sutable for classes and structures that have full methods and other members. So, I think it is useful.

Note:
Maybe we need another attribute to mark some properties to be used in deconstruction only, to be used in modyfimg existing .NET classes and structures to have defualt deconstructors. They allready have constructors, but it will be nice to have deconstructors too.

**Comment by yaakov-h** [comment]
What's the advantage of:

```csharp
class Class1
{
   [DeConstructable(1)] public int Id { get; set; }
   [DeConstructable(2)] public string Name { get; set; }
   public string Notes { get; set; } // Not De/Constructable
   [DeConstructable(3)] public int Age { get; set; }
}
```

over

```csharp
class Class1
{
   public int Id { get; set; }
   public string Name { get; set; }
   public string Notes { get; set; }
   public int Age { get; set; }

  public void Deconstruct(out int id, out string name) => (id, name) = (Id, Name);
  public void Deconstruct(out int id, out string name, out int age) => (id, name, age) = (Id, Name, Age);
}
```

?

It's not a huge amount of effort to write a deconstructor, it doesn't simplify the code a whole bunch, it doesn't give you anywhere to drop a breakpoint, and requires the compiler do a bunch of extra work and a handful of attributes instead of writing just one or two lines of code.

Also, why would we emit N deconstructors for N properties? This seems like an incredibly niche case.

And why skip a single-param deconstructor (`void Deconstruct (out int id)`), but then emit one for every other combination?

So far you've described something that perhaps the language/compiler _could_ do, but no compelling reason as to _why_ it should do such a thing.

**Comment by MkazemAkhgary** [comment]
>I think it would be better if Records had this feautre automatically

By automatically i meant without attributes. i.e deconstruct all fields

**Comment by yaakov-h** [comment]
I think that was a part of the records proposals already.

**Comment by MohammadHamdyGhanem** [comment]
@yaakov-h
> I think that was a part of the records proposals already.

And what about Classes and structures ?
I want a way to deconstruct already existing .net Classes without writing millions of extension methods!.. I think adding some attributes to exsisting classes will not break code, and can be done by the community.

**Comment by MkazemAkhgary** [comment]
You are not dealing with millions of classes do you? If you do, you shouldn't write them by hand!

Thats what code generation tools are for. For example you can use T4 text templates. Basically you write code to write code for you!

**Comment by yaakov-h** [comment]
If they're your own classes - which they would have to be in order to add attributes - then you could write a tool that uses Roslyn to parse the classes and generate the `Deconstruct` methods for you.

**Comment by YairHalberstadt** [comment]
Closing as this exact proposal can now be easily achieved using C# 9 SourceGenerators
