### ISSUE TITLE
nullable checking doesn't go far enough to check non-nullable variables being set to null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/csharplang#2205]
The following code snippet shows a situation where a non-nullable string gets inadvertently assigned null.
Limitations like this mean that we can't trust the nullable warnings - which makes the feature less useful as people will then not trust it and will abandon trying to fix their code.

To reproduce, paste the following code into a C# console project, and set the project to use the C#8 compiler with #nullable enable set.

Note that there's no warning produced, but the string gets set to null.

			string str;
			{
				using ( RegistryKey rk = Registry.CurrentUser.OpenSubKey( &quot;Software&quot; ) )
				{
					// No warning, but the cast from a null object will result in null
					str = (string) rk.GetValue( &quot;WontExist&quot; );
				}
			}
			if ( str == null )
			{
				Console.WriteLine( &quot;It is null&quot; );
			}

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/412355/nullable-checking-doesnt-go-far-enough-to-check-no.html
VSTS ticketId: 754373_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Arshia001** [comment]
I'm just trying out C# 8, and I've already found at least 2 different ways to get an NRE with null checks enabled. The subject of this issue is the more serious one. One can never assume external libraries to be correctly implemented. Unless null-oblivious types are assumed to be nullable, this entire null checking feature is rather pointless in any mid-sized project. When was the last time anyone made anything with no dependencies on any external libraries?

I'm in favor of having at least `#nullable strict` as @ewlloyd put it, though I also fail to see how null checks would be beneficious in non-strict mode. Sure, *most* libraries probably don't return nulls where you expect a value, but then again, *most* code within a module also doesn't.

To me it looks like null checks were created specifically for the rarer cases where somebody makes an unintentional mistake. Library authors aren't necessarily better than other programmers, they also make mistakes. Besides, once C# 8 is released, the more heavily used libraries' authors would probably update their code with nullability checks. You'd then be left with the more esoteric libraries, which are also more likely to contain mistakes. Voila, NRE's in your C# 8 code.

**Comment by Joe4evr** [comment]
> To me it looks like null checks were created specifically for the ~~rarer~~ **most common** cases where somebody makes an unintentional mistake.

Nail, meet head. (Also, FTFY.)

The mantra of NRTs is "We can protect you from Murphy, not from Machiavelli." You can subvert the null-warnings in dozens of different ways, but you'd have to go through the trouble of writing really convoluted/non-conventional code to do so.

**Comment by Arshia001** [comment]
> most common cases

@Joe4evr Most common cases that happen to **result in errors** rarely. Otherwise, you'd have a hard time passing tests and making it to production.

> you'd have to go through the trouble of writing really convoluted/non-conventional code to do so.

Or, just wait for null checks to catch on before using them. Better to have absolute safety in two years than have 90% safety now IMO.

**Comment by ewlloyd** [comment]
I'd thrown the `#nullable strict` in as a thought experiment, to point out the ultimate folly of an opt-in approach. We need the compiler to assume that all null-oblivious assemblies should be coerced to yield nullable types, even if the type declarations receive magic question marks that don't appear in their source code. Anything less is null-safety theater, and an exercise in futility.

You've got one shot at getting this right, or NRTs will be widely UNused, and eventually slink off into the night, say, around C#9 or 10.

**Comment by theunrepentantgeek** [comment]
> Or, just wait for null checks to catch on before using them. Better to have absolute safety in two years than have 90% safety now IMO. And then there's the opt-in thing.

If everybody waits for two years before adopting, then in two years time we'll be in exactly the same place we are *right now*.

You can be sure the feature will be improved over time.

Since 100% safety is actually unachievable, I'll take 80% safety now and look forward to 95% safety as things evolve.

**Comment by Arshia001** [comment]
> If everybody waits for two years before adopting, then in two years time we'll be in exactly the same place we are right now.

T = 0: C# 8 is released.
T = 3 months: People start picking it up.
T = 6 months: Most heavily used libraries are starting to add null safety.
T = 12 month: The libraries you depend on now probably have null safety built in. You can wait some more for that last library author, or just add a bunch of null checks and be done with it.

In return, you now have 100% null safety in the F#/Kotlin sense: You're probably 99% safe as long as nobody's intentionally messing stuff up. Yes, you can never be 100% safe. Who's going to stop you from modifying a non-nullable property with reflection? But you're safe as long as you stick to the rules. The language and the compiler and the code analyzers are there to back you up.

Unfortunately, the same cannot be said for the current design though.

> I'd thrown the #nullable strict in as a thought experiment, to point out the ultimate folly of an opt-in approach.

NRT's are an opt-in feature themselves. I'm all for forcing null-oblivious types to be nullable, but I guess some people could live with the compromise. They'll get their fair share of NRE's and hopefully start opting in.

**Comment by ewlloyd** [comment]
> NRT's are an opt-in feature themselves. I'm all for forcing null-oblivious types to be nullable, but I guess some people could live with the compromise. They'll get their fair share of NRE's and hopefully start opting in.

Exactly. But if you opt into NRTs, you should expect to get the full Monty, and not have to take on the cognitive load of remembering whether a given type is null-oblivious or not. If someone wants to exempt a given type or assembly from the NRT world, they can opt it out -- and on their own overworked head be it.

**Comment by marksmeltzer** [comment]
I am still a huge fan of creating a C# successor language that merges the best of C#, TypeScript and F# into a new language... Hell, probably just making TypeScript a .NET language would be amazing. Basic idea there is to allow calling all of the legacy APIs, and the legacy APIs could even be doctored with additional metadata to assist the editor.

Unless we have a clean break from the everything is nullable past, the language will have all of this messy compromise.

I love all of the the changes that C# 8 and on are bringing, but we really need a way of allowing breaking changes into C# itself to really move it forward to break free of past design decisions. 

Other than the nullable strict pragma, I would love to see the C# compiler have a version range capability: add the ability to set the minimum language feature version. 

So, if I set a project to C# latest minor, I might also set the C# minimum version to 8.1 (hypothetical) wherein nullablility is strictly required for compilation - i.e. same as TypeScipt. 

If I have some older projects that are too much work to port entirely, I can make progress over time and eventually move up the minimum C# version. 

Adding the minimum version capability would allow each C# release to come with a list of things that are obsolete, but will still compile (as warnings?), and a list of things removed completely. So the rule could be to mark language features  as obsolete one release, and removed the next. 

Adding a minimum version capability to the project settings and compiler at least provides a way out of the legacy language features that the community agrees should be removed.

Regards,

**Comment by Arshia001** [comment]
> Hell, probably just making TypeScript a .NET language would be amazing.

Do **not** go putting JavaScript in my .Net please.

**Comment by Arshia001** [comment]
So... NRT is 'With the release of .NET Core 3.0 Preview 7, ... considered "feature complete"' and we never got any special treatment for null-oblivious libraries, meaning with the final version of C# 8 we can still get NREs at runtime. Am I correct?

**Comment by CyrusNajmabadi** [comment]
> meaning with the final version of C# 8 we can still get NREs at runtime. Am I correct?

Correct.  Indeed, NRT has *zero* runtime impact.

**Comment by Arshia001** [comment]
@CyrusNajmabadi Yes, I was talking about the treatment of null-oblivious libraries, which is (to the best of my knowledge) to treat them as non-nullable nonetheless, which means we can get NRE's the compiler doesn't catch.

**Comment by CyrusNajmabadi** [comment]
> which means we can get NRE's the compiler doesn't catch.

Yes.  I'm just being clear that in 8.0 there will already be many NREs the compiler doesn't catch.  So this doesn't change much there.

**Comment by Arshia001** [comment]
> I'm just being clear that in 8.0 there will already be many NREs the compiler doesn't catch.

Oh, I was under the impression that this was supposed to be a complete solution to the problem. Good to know that!

**Comment by CyrusNajmabadi** [comment]
> Oh, I was under the impression that this was supposed to be a complete solution to the problem.

It is not.  It is a set of checks for common types of mistakes to help find and eliminate very probable bugs.  To be 'complete' it would have to flip things around and likely end up with a system that gave tons of false positives, which would likely cause an enormous around of developer fatigue around adoption.

So, the system opts now to surface highly suspect issues, at the cost of masking some real issues.

**Comment by ewlloyd** [comment]
So null-oblivious libraries can still pollute our NRT-checked code, and we'll have no obvious way of flushing them out. Is there anything on the backlog to _at least_ give us an opt-in with `#nullable strict` or somesuch?

**Comment by CyrusNajmabadi** [comment]
@ewlloyd You're welcome to open an issue asking for this so it can be appropriate reviewed.  You could also just write your own analyzer for this sort of thing if you wanted :)

**Comment by ewlloyd** [comment]
Fair enough -- I just might! :-)
