### ISSUE TITLE
Use Span<T> with `fixed` fields

### ISSUE THREAD

**Issue by AArnott** [dotnet/csharplang#2208]
_From @AArnott on February 9, 2019 18:37_

C# structs can have inline arrays like this:

```cs
unsafe struct Some
{
   private fixed byte something[4];
}
```

But then `something` is typed as `byte*`. With `Span<T>` we should have a *safe* alternative. Something like:

```cs
ref struct Some
{
    private fixed Span<byte> something[4];
}
```

This removes the `unsafe` keyword and lets us use `Span<T>` which embeds the length, making it safer.

_Copied from original issue: dotnet/roslyn#33272_

**Comment by tannergooding** [comment]
This is very similar to the already championed `fixed-sized buffers` proposal: https://github.com/dotnet/csharplang/issues/1314 (which proposes supporting `fixed-sized buffers` of any type and relying on `ref returning indexers`).

**Comment by YairHalberstadt** [comment]
Closing as effectively subsumed by https://github.com/dotnet/csharplang/issues/1314, and decided in https://github.com/dotnet/csharplang/issues/1502 that it's not currently under consideration.
