### ISSUE TITLE
Proposal: add cons support to C#

### ISSUE THREAD

**Issue by DavidArno** [dotnet/csharplang#221]
Many languages offer a "cons" feature, which is often denoted with the `::` syntax. It would be good to use that syntax in C#, but it is already used for alias qualifiers. So I've used `[:]` here. The syntax has two purposes:
1. To allow the head and the rest of a list (the tail) to be split,
2. To allow a new item to be added to the head of a list:

Using the `[:]` notation, these two purposes would be used as follows:
```
var a = (some sort of list)
var c = [b:a]; // c is a new list with b as its first element
var [d:e] = c; // d == b, e == a
``` 
In a departure from the common implementation of cons, I'd also suggest that the head can itself be a whole list, rather than just an item:
```
var a = (some sort of list)
var c = [b:a];
var d = (some sort of list)

var e = [c:d]; // e is the joining of the lists, c & d, with b being the first element
``` 

As a prerequisite, any type that can use the cons syntax will have to implement the following interface:
```cs
public interface IConsEnumerable<T> : IEnumerable<T>
{
    (T head, IConsEnumerable<T> tail) Cons();
    IConsEnumerable<T> Cons(T head);
    IConsEnumerable<T> Cons(IEnumerable<T> head);
}
```

By extending `IEnumerable<T>`, a cons enumeration can then be used anywhere that the former can. In addition though, by adding an extension method:
```cs
public static IConsEnumerable<T> ToCons(this IEnumerable<T> enumeration) => ...
```
the compiler can substitute `::` expressions for one of the methods in the `IConsEnumerable<T>` interface and/or that extension method:
```
var a = new List<int> { 1, 2 };
var b = new List<int> { 1, 2 };
var c = [1:a]; // == var c = a.ToCons().Cons(1);
var d = [c:d]; // == var d = c.Cons(d);
var [e:f] = d; // == var (e, f) = d.Cons();
```

Because cons lists can (have to be) constantly re-read, any implementation of `IConsEnumerable<T>` has to support being re-enumerated, unlike `IEnumerable<T>`. This can have the added bonus of meaning that `someEnumerations.ToCons()` creates a lazy overlay over that enumeration, which can avoid the overhead of having to call `ToList()` when the whole enumeration isn't then read.

I have a working implementation of an implementation of `IConsEnumerable<T>` at [ConsEnumerable.cs](https://github.com/DavidArno/SuccincT/blob/master/SuccincT/Functional/ConsEnumerable.cs), though it should be noted that this is C# 6 code, so doesn't yet use a tuple as the return type. It uses a simple "cache the enumerations as a linked list" approach. More performant solutions are likely possible.

What I haven't yet done is considered what the implications of this proposal would be on cons pattern matching. My gut feeling is that it would help solve this by addressing the re-enumerating problem, but I've not yet properly thought this though, so could be wrong.

**Updated: @svick has pointed out that `::` cannot be used as it is existing valid syntax for namespace aliases, so I've replaced it with `[:]`**

**Comment by orthoxerox** [comment]
@DavidArno 

What are the benefits of having cons lists?

**Comment by DavidArno** [comment]
You would have to start with the hardest question! 😁 

There are various uses for them, but their real strength comes when they are supported in pattern matching too.

Let's say I have a an array: `[1,1,4,4,4,5,6,7,7]` and I want to transform that into details of the value and length of each number run, resulting in: `[(1,2),(4,3),(5,1),(6,1),(7,2)]`

That can be done with a for loop, for example and by building a list as you go. Alternatively, cons can be used to turn it into a single, recursive, expression:
```cs
IEnumerable<(int, value, int count)> ComputeRunLengths(IEnumerable<int> sequence) =>
    sequence match (
        case [] : new List<(int, value, int count)>(),
        case x :: [] :  new List<(int, value, int count)>{ (x, 1) },
        case value :: remainder when ComputeRunLength(remainder) is var h :: t : 
            h.value == value  ? (value, h.count++) :: t : (value, 1) :: (h :: t)
    );
````
Obviously, it's worth noting that, since C# doesn't support tail call optimisation, I've not bothered to structure it so that the recursion can be optimised away. So it's not a performant example, but it hopefully shows the power of cons.

**Comment by HaloFour** [comment]
Cons is interesting but I don't know that it's particularly useful in C# where people are more familiar and more likely to use one of the various BCL collection classes.  I'd rather see good support for patterns over arrays/collections than something completely new.

**Comment by alrz** [comment]
#16494?

**Comment by DavidArno** [comment]
@alrz,

That provides a means of doing `var x :: y = (some list)` by doing `var (x, y) = (some list)`, but it doesn't provide the ability to add items to the list.

**Comment by DavidArno** [comment]
@HaloFour,

This proposal is for cons support on **all** types that implement `IEnumerable<T>`, not just some new F# list-like type.

And I believe (though to reiterate, I've not properly checked yet), it also creates a means of enabling cons pattern matching on `IEnumerable<T>`, without the problems of re-enumerating that enumerable directly.

**Comment by HaloFour** [comment]
@DavidArno 

For appending to lists I don't know that the operator makes sense.  We already have a shorthand to initialize a collection.  This proposal also doesn't address collection literals as it seems to imply that whatever list has already been created.  What would the literal `1 :: 2 :: 3` mean?

As for patterns, I'm fine with the pattern syntax but I question the need for anything special to enable implementation.  My opinion is still that the compiler could be smart enough to automatically dip into an `IEnumerable<T>` and extract/cache only the items it needs to perform each test as well as return the remainder, caching additionally extracted values if need be.  Sure, enumerable implementations that are mutable or calculated could screw with that, but you have the same problem if you stick an interface in front of it.

**Comment by MgSam** [comment]
I don't understand what benefits this proposal offers over the existing linq methods. 

As for your example:

``` C#
var a = new[] { 1, 1, 4, 4, 4, 5, 6, 7, 7 };
var result = a.GroupBy(a => a).Select(a => Tuple.Create(a.First(), a.Count())).ToArray();
```

**Comment by MgSam** [comment]
Or actually, even more simply:

``` C#
var result = a.GroupBy(b => b, (i, g) => Tuple.Create(i, g.Count())).ToArray();
```

**Comment by DavidArno** [comment]
@MgSam,

Ah, good point. My example data set wasn't a good one, as I didn't have the numbers repeating. I've updated it to an example that group by doesn't handle. Thanks.

**Comment by DavidArno** [comment]
@HaloFour,
> For appending to lists I don't know that the operator makes sense. We already have a shorthand to initialize a collection. 

We do. And I've avoided going anywhere near the way F# initialises lists as (a) there already exists ways of doing it in C# and (b) the way F# does it conflicts with ideas for slices and ranges in other proposals. Plus, please remember that cons prepends to a list; never appends.

> This proposal also doesn't address collection literals as it seems to imply that whatever list has already been created. What would the literal 1 :: 2 :: 3 mean?

It wouldn't. It would be a compilation error. `1 :: 2 :: new List<int> { 3 };` would work though. The most right element of a succession of `x :: y` expressions has to be a collection that implements `IEnumerable<T>`.

> As for patterns, I'm fine with the pattern syntax but I question the need for anything special to enable implementation. My opinion is still that the compiler could be smart enough to automatically dip into an IEnumerable<T> and extract/cache only the items it needs to perform each test as well as return the remainder, caching additionally extracted values if need be. 

But that is exactly what this proposal provides: a means of dipping into an `IEnumerable<T>` and caching the items read to avoid re-enumerating the original.

> Sure, enumerable implementations that are mutable or calculated could screw with that, but you have the same problem if you stick an interface in front of it.

It's not just an interface. Behind that is a wrapper over the enumeration that handles lazy reading, caching and head::tail splitting.

**Comment by HaloFour** [comment]
@DavidArno 

> But that is exactly what this proposal provides: a means of dipping into an IEnumerable<T> and caching the items read to avoid re-enumerating the original.

> It's not just an interface. Behind that is a wrapper over the enumeration that handles lazy reading, caching and head::tail splitting.

Yes, but only for the wrapped instance.  The underlying `IEnumerable<T>`, which you are more likely to be tossing around, will still feel the effects of having been read.  If you're passing that `IEnumerable<T>` to several methods that internally wrapping with `IConsEnumerable<T>` and performing various pattern matches you're still evaluating that underlying `IEnumerable<T>` multiple times.

As such I'd rather keep the functionality separate.  A cons pattern would work over enumerables and the compiler will cache off read values and manage the head(s)/tail splitting as necessary.  For people who want to cache/manage their enumerables a little more proactively, and not just with pattern matching, the BCL could add a `Memoize` extension method to LINQ.

But something tells me that we might be more likely to see list-based patterns rather than cons-based patterns.  The concept of cons is just a bit too alien to the world of C#.

**Comment by AdamSpeight2008** [comment]
@HaloFour Reactive Extensions aka System.Interactive have a Memoize extension method.

**Comment by svick** [comment]
My thoughts:

1. Cons makes a lot of sense in a language that prefers recursion over iteration. C# is not one of those languages, so I think cons is not that useful.
2. `System.Collections.Immutable` collections have existed for a while and [are not used much](https://apisof.net/catalog/System.Collections.Immutable), so I think adding syntax that's mostly useful only for working with one specific kind of immutable collection does not make much sense.
2. Some form of pattern matching for collections would be useful. I hope it's going to be considered when pattern matching is expanded in the future. (See e.g. https://github.com/dotnet/roslyn/issues/10631 and https://github.com/dotnet/roslyn/issues/9485.)
3. I'm not sure `::` would be usable for this in C#, since it's already [the namespace alias qualifier](https://msdn.microsoft.com/en-us/library/htccxtad.aspx). For example, `a::b` is already a valid expression. And I think that inventing some new syntax would make this proposal even less desirable, since it would be unfamiliar to people who know cons from other languages.
5. LINQ already contains `Concat()` and `Prepend()`, which I think should be enough for the construction case. Though adding something like `Memoize` would be useful.

**Comment by orthoxerox** [comment]
@svick Does LINQ really contain `Prepend()`?

**Comment by svick** [comment]
@orthoxerox [It does on .Net Core](https://apisof.net/catalog/System.Linq.Enumerable.Prepend%3CTSource%3E(IEnumerable%3CTSource%3E,TSource)) and [it should be included in some future version of .Net Framework](https://github.com/dotnet/corefx/issues/9085).

**Comment by vladd** [comment]
Cons basically makes sense on the collections implemented as linked lists. On other collection types (even more, on an _arbitrary_ `IEnumerable<T>`), it's going to be inefficient.

As an example, removing items from the beginning of an `IEnumerable<T>` one by one by using many `.Skip(1)`'s in a row [tends to bring quadratic processing time](https://en.wikichip.org/wiki/schlemiel_the_painter%27s_algorithm), instead of the customary linear one.

Including such a feature into a language means that the feature is endorsed by language team, this in turn makes it necessary to support efficient implementation on all collections. This would need a lot of effort on BCL side and would possibly make the collection-processing patterns which are used now less efficient.

**Comment by DavidArno** [comment]
@vladd,

> Cons basically makes sense on the collections implemented as linked lists. On other collection types (even more, on an arbitrary `IEnumerable<T>`), it's going to be inefficient.

This need not be the case, and isn't the case for the implementation that I link to in the OP. The solution is to simply wrap that `IEnumerable<T>` in a type that creates a linked-list as it enumerates its encapsulated `IEnumerable<T>`, which is what `ConsEnumerable` does.

**Comment by DavidArno** [comment]
@svick,


> Cons makes a lot of sense in a language that prefers recursion over iteration. C# is not one of those languages, so I think cons is not that useful.

If you have an `IEnumerable<T>` and want to add values to it, the common way to do so currently is to read the entire enumeration and convert it to a `List<T>`, then append values. Cons provides a much more performant way: it prepends the values without touching the original enumeration until it needs to be read.

> System.Collections.Immutable collections have existed for a while and are not used much, so I think adding syntax that's mostly useful only for working with one specific kind of immutable collection does not make much sense.

I'm not proposing adding syntax that will only work for one type. It works for every single existing type that implements `IEnumerable<T>`.

> Some form of pattern matching for collections would be useful. I hope it's going to be considered when pattern matching is expanded in the future. (See e.g. dotnet/roslyn#10631 and dotnet/roslyn#9485.)
I'm not sure :: would be usable for this in C#, since it's already the namespace alias qualifier. For example, a::b is already a valid expression. And I think that inventing some new syntax would make this proposal even less desirable, since it would be unfamiliar to people who know cons from other languages.

Leaving aside the fact that you haven't shown any real reasons for why it's undesirable, you make a good point: `::` wouldn't work as that's existing syntax. I shall update the proposal to reflect that.

> LINQ already contains Concat() and Prepend(), which I think should be enough for the construction case. Though adding something like Memoize would be useful.

That could work. It doesn't address how to pattern match on collections though. Any thoughts on that?

**Comment by DavidArno** [comment]
@HaloFour,

> Yes, but only for the wrapped instance. The underlying `IEnumerable<T>`, which you are more likely to be tossing around, will still feel the effects of having been read. If you're passing that `IEnumerable<T>` to several methods that internally wrapping with `IConsEnumerable<T>` and performing various pattern matches you're still evaluating that underlying `IEnumerable<T>` multiple times.

That is a valid concern, however that is an existing problem that the compiler doesn't detect. If I pass an `IEnumerable<T>` to multiple methods, the compiler doesn't warn me that it'll be read many times. Perhaps it should.
