### ISSUE TITLE
Arrays are covariant over nullable references but interfaces aren't

### ISSUE THREAD

**Issue by roji** [dotnet/csharplang#2224]
(not sure if this belongs here or in roslyn)

Using VS2019 preview3, arrays are covariant over nullable types:

```c#
string?[] arrr = new string[0];
```

However, trying the same thing with a covariant interface generates a warning:

```c#
IEnumerable<int> e1 = new List<int>();
IEnumerable<int?> e2 = e1;
```

**Comment by HaloFour** [comment]
@roji 

`int` is not a reference type and neither is `int?`, so the NRT feature doesn't apply.  `int?` is actually `Nullable<int>` which is a struct.  Structs cannot participate in generic variance.  Trying to convert from `IEnumerable<int>` to `IEnumerable<int?>` is a compiler error, as it should be.

**Comment by roji** [comment]
Apologies, how embarrassing... That was a copy-paste error.
