### ISSUE TITLE
Proposal: Implicit co/contravariance for nullable reference types

### ISSUE THREAD

**Issue by roji** [dotnet/csharplang#2225]
Continuation of discussion from https://github.com/dotnet/roslyn/issues/33010.

Since nullable and non-nullable reference types are in fact the same type in runtime, it seems like it could be beneficial to allow the following:

```c#
Task<string> Foo() => Task.FromResult("foo");
Task<string?> Bar() => Foo();

List<string?> nList = new List<string>();
```

As @jaredpar pointed out, it's possible to add a bang operator to force this cast, but it seems like that operator is normally reserved for cases where there's programmer knowledge to which the compiler has no access. In the cases above the compiler is perfectly capable of guaranteeing the safety, and so could provide frictionless, ceremony-free safe casting. The same seems to hold also for contravariance.

The special casing of NRTs can be justified by the fact that they are in fact identical with their non-nullable counterparts in runtime. For reference compare with #1301, which is about a similar request for NVT covariance (which is a very different thing).

**Comment by gafter** [comment]
Your proposal is not safe.  If there are two references to a list, one of which has type `List<string?>` and the other is `List<string>`, one could place a null in using the former, and then get it out (without the necessary warning) from the latter.  That shows that the proposed variance is not safe.

**Comment by roji** [comment]
Thanks for the explanation, I had not thought this through.
