### ISSUE TITLE
Proposal: Static extention methods

### ISSUE THREAD

**Issue by EDaneshpanahi** [dotnet/csharplang#2226]
Usage of static extension methods would allow for adding methods as static methods of base class. See below for an example

```
public static Min(this Math, params int[] numbers){...}
```

**Comment by yaakov-h** [comment]
https://github.com/dotnet/csharplang/issues/192

**Comment by jnm2** [comment]
@EDaneshpanahi Please close so that we don't have so many issues hanging open here.
