### ISSUE TITLE
Suggested implemention with ref readonly structs and readonly structs

### ISSUE THREAD

**Issue by msedi** [dotnet/csharplang#2233]
I'm doing heavy math using Vector algebra and have a Vector3D struct.
I just want to have this structs readonly/immutable for performance reasons. I have the same for Matrix3D, Matrixc4D, Point3D Point4D, Vector3D, etc.

With the possibilities like ref readonly struct and readonly struct I assume I can gain some performance benefits when updating my structures to that behavior.

The problem here is that I obviously have to implement Vector3D twice, once for ref readonly and once for readonly.

In the end it doesn't make sense doing all the things twice, especially when it comes to possible errors in the containing math.

What would be your suggested strategy for this? Span<> and Memory<> are a good example. What would be the suggestions for e.g. Vector3D and Vector3DRef? Do I have to create multiple operators, e.g.

```
public static implicit Vector3D operator+ (Vector3D vec1, Vector3D vec2);
public static implicit Vector3D operator+ (Vector3D vec1, Vector3DRef vec2);
```

Or does it make sense at all to have a Vector3D and Vector3DRef?

I think this is not such a rarely done approach, so it would be nice to hear how others do it? It would prefer something like a "partial" struct description where I can add the individual implementations, but I have no good clue how this can be done.

**Comment by YairHalberstadt** [comment]
What's the purpose of a Vector3dRef? To provide a vector over a span?

**Comment by msedi** [comment]
Maybe that some point I don't understand. 

It should be stack type only. So it should live only in a single method call. Maybe I understand some things not quite correctly with the ref readonly. I was assuming I get some additional performance, or is the ref readonly only some indicator that the type is not allowed to be elevated on the heap when necessary to prevent possible impacts?

If this is the case and the runtime does not distinguish between ref readonly and readonly that my approach really doesn't make sense.

**Comment by MkazemAkhgary** [comment]
you are making it really complicated, introducing a problem to solve a non-existing problem. did you measure the performance and verified using readonly structs is the actual overhead? 

by the way structs live in stack as long as they are not boxed or not referenced by an object in heap. 

I suggest you to look for utilizing GPU if you are already not doing this.

**Comment by msedi** [comment]
@MkazemAkhgary: You may be right. That's the reason why I ask. I didn't measured performance so far, but I also wanted to understand if ref readonly is only a syntactic difference or if the runtim takes special care about the ref readonly. I'll try to do some benchmarks.

And yes, we already looked into GPU things, but GPU means that currently I'm tightly bound to some graphics cards. Especially when you work with CUDA you are very fixed to this hardware. A lot of things run quite well in C#, so for these special things it's currently not necessary to go to GPU.

Nevertheless, improving performance is always nice ;-)

**Comment by YairHalberstadt** [comment]
Ref readonly provides no inherent performance benefits over a readonly struct. it's only advantage is the it can store another ref like type.
