### ISSUE TITLE
Discussion: Lower (e as Type)! to a direct cast

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#2234]
There are various proposals to introduce a postfix syntax for a direct cast. Instead, we could translate the combination of `as` and `!`-operators to a direct cast under the hood.

If the cast was not successful and it is dotted off, the code will throw anyways. We can assume that in the presence of the suppression operator, user expect it to succeed and it would be safe to emit the castclass instruction.

On the other hand, if there's no dereference, we have silently passed an unexpected `null` and there's a potential bug in the code, (see https://github.com/dotnet/csharplang/issues/2149 on that).

At the end of the day, we most definitely expect `(e as Type)!` to succeed and it would make sense to emit castclass instead.

**Comment by Joe4evr** [comment]
The whole purpose of `as` is to *not* fall over and cry should the cast fail. Conflating that syntax with something that *will* fall over and cry is very much Pit Of Failure material. If you want the semantics of a direct cast, then write a direct cast.

**Comment by jnm2** [comment]
If `!` here meant "fall over and cry," i.e. it actually threw an exception if `e` is null, then I kinda like this. 

If it throws inconsistently (throwing in the non-`Type` instance scenario but not the `null` scenario), I agree that it's a pit of failure. It would also feel off-balance.

**Comment by gafter** [comment]
The semantics of the annotations introduced through the nullable reference types feature are intended to have no impact on the runtime semantics of the program.  This requests that they do, but we've discussed the design approach at length and we are very comfortable where we are.
