### ISSUE TITLE
Generic Methods Constrained by Enclosing Scope

### ISSUE THREAD

**Issue by Tom01098** [dotnet/csharplang#2239]
It is currently impossible to have a generic method which is dependant on the generic parameters in the enclosing scope. Consider

```C#
public class List<T>
{
    // ...
    public void Sort()
    {
        if(!(T is IComparable))
        {
            throw new Exception(....);
        }

        // Now we can sort, because T is IComparable
    }
    // ...
}
```

This is ugly as it moves a definite error from compile-time to run-time. With my proposal of using the `when` keyword similarly to how the `where` keyword is used to constrain the type parameter, the compiler can be sure of the validity of calling the method.

```C#
public class List<T>
{
    // ...
    public void Sort()
        when T : IComparable
    {
        // T is compile-time guaranteed to be IComparable for this method to be callable
    }
    // ...
}
```

## Extension methods
This functionality is already offered by extension methods, however it is cleaner and more readable to use the proposed `when` clause due to locality.

```C#
public static void Sort(this List<T> list)
    where T : IComparable
{
    // T is compile-time guaranteed to be IComparable for this method to be callable
}
```

**Comment by YairHalberstadt** [comment]
I think this is exactly what extension methods were designed for. Namely utility methods which are not core to the functionality of the type. IMO almost any method which can be implemented as an extension method should be, as that makes you think about exactly what is the API of your object, and what are just utilities built on top of that API. This is especially the case for methods which only makes sense for a subset of the possible type arguments that can be provided. Doing so also reduces the number of dependencies the type relies on, allowing it to be refactored more easily.

Now there will be certain cases where you need access to private member's of the type to implement your suggested `when` methods, meaning extensions won't work. There are two suggestions I can offer:

1. **Rethink your API:** If there's some extension method you want to add to a type, but can't, that hints that your API isn't quite expressive enough.

2. **Make the members protected/private protected instead, and create a subtype of the class. Eg. Create a class ```SortableList<T> : List<T> where T : IComparable```. This is often really ugly, comes with a lot of limitations, and is a bit of a hack, but there probably are cases where this is your only option.

**Comment by HaloFour** [comment]
How exactly would this behave if you try to call the `Sort` method if `T` is not `IComparable`?  Is the compiler supposed to enforce that `T` doesn't fit the constraint?  What about if the method call is made with a compiler that doesn't understand this constraint, such as any existing C# compiler?  Is that intended to then be a runtime error?

The CLR has no facility to describe or enforce this kind of constraint.  The best the compiler can do is to emit the code as you've described above, where it checks whether or not `T` implements the interface and throws if it doesn't.

The method `List<T>.Sort` that accepts no parameters already exists today, do you have a different use case that demonstrates why that strategy cannot apply?

**Comment by Tom01098** [comment]
The point about backwards-compatibility means that this idea won't work I agree, I suppose extension methods are the best we've got :)
