### ISSUE TITLE
Proposal: GetLongHashCode()

### ISSUE THREAD

**Issue by JustNrik** [dotnet/csharplang#2240]
Basically, GetHashCode() but returning `long` instead. Enabled for 64bits only (?)

This would be useful to avoid hashcode collitions with big collections and collections that uses long/ulong as key.

**Comment by YairHalberstadt** [comment]
Can you explain in more detail what this proposal is? So you want to add a virtual method to object? If so this is .Net not C# specific, and to be blunt, is probably dead on arrival.

**Comment by benaadams** [comment]
Should raise in https://github.com/dotnet/corefx which is for the apis

**Comment by HaloFour** [comment]
Apart from being a pretty big change to the CLR and BCL, none of the existing collections could possibly work with this.  I doubt (m)any of them support more than 2^32 items anyway, and I doubt that there's much call in the BCL to provide such large collection types so they would likely push for such a thing to be provided via NuGet.

It'd be completely possible for you to implement such collections along with a version of `IEqualityComparer` that produced and used 64-bit hash codes.

```cs
public interface IBigEqualityComparer<T> : IEqualityComparer<T> {
    long GetLongHashCode();
}

public class BigDictionary<TKey, TValue> : IDictionary<TKey, TValue> {
    public BigDictionary(IBigEqualityComparer<TKey> comparer) { ... }
}
```

**Comment by AartBluestoke** [comment]
"I doubt (m)any of them support more than 2^32 items"
This probably isn't about count of objects in the dictionary, it's about hash collision chance. With 32 bit hash functions you will typically (50% chance) run into collisions with less than 80k objects in a dictionary. even 64 bit hash functions have a 1% chance of collision at 600 million objects. (exact maths on collision probability can be found from https://preshing.com/20110504/hash-collision-probabilities/)
![image](https://user-images.githubusercontent.com/1892829/53212734-3dba6500-369a-11e9-9a50-0d4219968e2b.png)
