### ISSUE TITLE
New keyword to generate a single-cast delegate with implementation.

### ISSUE THREAD

**Issue by strpipe** [dotnet/csharplang#2242]
Hello,

I want the compiler to create a delegate for me and assign a method to an instance when I precede a method declaration with a keyword. This means by preceding a method with the keyword I get the same as the following:

```
public delegate void Log_Signature(string value);
public static Log_Signature Log = Log_Impl;
private static void Log_Impl(string value) {
    //do something
}
```

What do you think about it?

**Comment by HaloFour** [comment]
I think it's something that would be very rarely used (likely not at all by the vast majority of C# developers).  You'd still have to name the delegate and specify its visibility.

**Comment by strpipe** [comment]
Thank you, I understand that it might be rarely used and that alone will prevent it from being implemented, however, I am pretty sure that the name of the delegate and it's visibility could be inferred from the original function declaration.
