### ISSUE TITLE
Proposal: static assembly linking

### ISSUE THREAD

**Issue by Opiumtm** [dotnet/csharplang#2251]
I propose ability of C# compiler to link IL code from external .NET assembly statically.
I.e. doing mostly the same work that well-known ILMerge utility does. 
As additional feature, only really used types should be statically linked to output assembly.

Potential problems:

1. Q: What should reflection report on statically imported types?
A: Should report them as if they're the part of target assembly, qualified with the target assembly instead of original one.

2. Q: What about DLL conflicts? If there is library A, library B that statically link library A, and library C that normally reference both A and B libraries? What about inheritance?
A: Types should be statically imported as internal types and it should be prohibited to expose statically imported type in a public API (as you can't do it with regular internal type). Technically, statically imported types would be different nominal types with different full-qualified type name (qualified with target assembly instead of original one).

3. Q: What about assemblies, referenced by the linked assembly?
A: Should be manually referenced or statically imported by target assembly. If statically imported type depends on type from assembly that isn't imported nor referenced by target assembly - then it should be compilation error.

4. Q: What if linked assembly rely on reflection for its own types and its logic could be broken with static assembly linking?
A: Static linking is an explicitly made decision useful for special use cases. One of such cases is to make assemblies intended for static linking in the first place. Most of things could be broken by static linking of arbitrary assembly, but it shouldn't be any attempts to "fix" such potentially fragile things. If it's became broken then it's OK. 

In general, this feature is useful for code reuse that otherwise would require multiple assembly builds for incompatible compilation targets, as an alternative to .net standard assembly (probably because there is already a 3rd-party assembly and no source code available). Another use case  (non-common) is requirement for single-file DLL output (dynamically loaded plugin for some program/service, for example).

**Comment by HaloFour** [comment]
What does this have to do with the C# syntax?  Sounds like it'd be, at most, a compiler flag, which should be requested on the Roslyn repo.

**Comment by Joe4evr** [comment]
Have you looked at [IL Linker](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md)? :upside_down_face:

**Comment by YairHalberstadt** [comment]
Closing as this seems like it's a tooling issue not a C# one.

If you want to pursue this, I suggest opening a discussion on https://github.com/dotnet/roslyn
