### ISSUE TITLE
lengthy arrow functions

### ISSUE THREAD

**Issue by sgf** [dotnet/csharplang#2258]
The syntax from the moment of birth, I have a problem however there were no suitable way feesback to the C # team. Now I have to say it.
**how about change "=>" to ".."**
as u see.
the define a lambda will changed:

(a,b,c)=>a+b+c  //oringe
(a,b,c)=>{return a+b+c;}
(a,b,c)..a+b+c //new
(a,b,c)..{return a+b+c;}

The benefits:
1. do not need to enter when you enter "=" and ">"(4 keys input times), Direct need ".." (two keys input times)
2. the Semantic Function calls defines".", and the Lambda ( a function pointer ) is defined as two ".." It's also easy to understand
3. Moreover, shorter expression, may be one of two lines of code you don't know, but when the function is nested more time, shorter expression makes the code more clear

by the way:
New features are always good, 
but to abandon the obsolete syntax are often very significant ( this can reduce the complexity of the historical burden and compiler implementation ).
**Simple and clean, easy to understand first.**

**If you have a better idea it would be better.**

**Comment by CyrusNajmabadi** [comment]
>     3\. shorter expression

I'm not seeing how your proposal makes anything shorter.

**Comment by sgf** [comment]
> > ```
> > 3\. shorter expression
> > ```
> 
> I'm not seeing how your proposal makes anything shorter.
> 
> 1. This seems to be an entirely equivalent way of stating something, without bringing any benefit.
> 2. `..` already has meaning for upcoming versions of C#.  It is the `range operator`.  i.e. you can say `i..j`.  That makes this sort of code extremely ambiguous.

Can support multiple uses like the Arrow functions, currently the arrow functions used to replace the "case" and ":" by use switch in
Pattern matching

**Comment by HaloFour** [comment]
There's nothing "obsolete" about "arrow functions".  They were added relatively recently and specifically to allow for simple members to be declared just like existing lambda syntax.  That both decreases verbosity in the simple case and remains internally consistent.

Your syntax offers absolutely nothing except a redundant, if not bewildering, way to accomplish something that can already be done.  It's the exact same number of characters and offers no improvement over the existing syntax.

**Comment by sgf** [comment]
> 关于“箭头功能”并没有“过时”。它们是相对最近添加的，特别是允许简单的成员声明就像现有的lambda语法一样。这既降低了简单情况下的冗长程度，又保持内部一致。
> 
> 你的语法绝对没有提供任何东西，除了一种冗余的，如果不是令人困惑的方式来完成已经可以完成的事情。这是完全相同的字符数，并且与现有语法相比没有任何改进。



> There's nothing "obsolete" about "arrow functions". They were added relatively recently and specifically to allow for simple members to be declared just like existing lambda syntax. That both decreases verbosity in the simple case and remains internally consistent.
> 
> Your syntax offers absolutely nothing except a redundant, if not bewildering, way to accomplish something that can already be done. It's the exact same number of characters and offers no improvement over the existing syntax.
Agree,
The changes raise very limited indeed.

If there can better be only one character and enter a simple need only enter once, and don't need to press shift+"？".
 but its hard to find any better on semantic choices and keys on the keyboard that already exists.

**Comment by CyrusNajmabadi** [comment]
> If there can better be only one character and enter a simple need only enter once, and don't need to press shift+"some key".

As mentioned, `..` already means something for C#.  Your syntax is literally ambiguous.  i.e, `(c)..(c+c)` would now mean two things.  It would be a `range` (from `c` to `c+c`) and it would now also be a lambda with a single arg that returned that arg added to itself.

This is effectively a non-starter.

Furthermore, `=>` was very intentionally picked.  It's an arrow.  It is used to convey the flow of inputs to ouputs.  It is easy to read, and has been picked up by the entire C# ecosystem in a short period of time.  Your new syntax is a step back from that.  Nothing about `..` indicates that it's a `lambda`.  It's not only ambiuous with ranges (as mentioned above), but it is also something that often means something else in *other* languages.  For example `..` and `...` are often used as traversal operators in path/query languages.  Finally, a series of dots often means to `spread` out a value.   

Your syntax is extremely alien, and doesn't really add any value.

**Comment by PathogenDavid** [comment]
>If there can better be only one character and enter a simple need only enter once, and don't need to press shift+"some key".

If typing is hard for you, I'm afraid you may have made a poor choice of career/hobby.

---

On a more serious note, if you have an actual medical issue that makes it hard for you to type, I'd suggest making a macro with something like [AutoHotkey](https://www.autohotkey.com/). (Although I'd suggest something like `,.` instead of `..` to avoid issues with typing ellipses and ranges.)
