### ISSUE TITLE
C# 8 switch expression exhaustiveness for Enum

### ISSUE THREAD

**Issue by hez2010** [dotnet/csharplang#2266]
with following code:
```csharp
using System;

namespace Test
{
    enum TestEnum
    {
        A, B, C, D
    }
    class Program
    {
        static void Main(string[] args)
        {
            TestEnum x = TestEnum.C;
            var y = x switch //The switch expression does not handle all possible inputs (it is not exhaustive)
            {
                TestEnum.A => 1,
                TestEnum.B => 2,
                TestEnum.C => 3,
                TestEnum.D => 4
            };
        }
    }
}
```

Related to #2228 , but this time is for Enum.
As for an Enum type value, I think that the compiler can know whether it is exhaustive or not, and in this scenario the "_ =>" may not be required.

**Comment by theunrepentantgeek** [comment]
There might be only four *named* values for the enum, but any **int** can be cast to that value ... this is perfectly legal ...

``` cs
TextEnum x = (TestEnum)42;
```

Changing this would be a breaking change for a very large amount of code ...

**Comment by grokys** [comment]
Couldn't the switch expression be considered exhaustive if all enum values are present, but throw a `SwitchExpressionException` if a value is encountered for which there is no enum value? This would allow exhaustiveness checking for the common case.

**Comment by jaybuckman** [comment]
Why not have 'strict' enums and throw errors when an invalid cast occurs?  
    enum strict TestEnum {A, B, C, D}
Then we wouldn't have to always add default cases to the switch expressions.  It seems with the null checking in C# 10, that things are headed in this direction...
As for breaking things, why are we using enums for things that don't have a finite set of values?

**Comment by svick** [comment]
@jaybuckman I think discriminated unions (https://github.com/dotnet/csharplang/issues/113) will be able to serve as those "strict enums". E.g. with the [current proposal](https://github.com/dotnet/csharplang/blob/24f05b3/proposals/discriminated-unions.md), the code would be:

```c#
enum class TestEnum
{
    A, B, C, D
}

**Comment by 333fred** [comment]
That's https://github.com/dotnet/csharplang/issues/3179.
