### ISSUE TITLE
while (){} else {}

### ISSUE THREAD

**Issue by yotam180** [dotnet/csharplang#227]
It might sound like a silly feature, but I usually find Python's `while: else:` syntax [very useful.](http://stackoverflow.com/questions/3295938/else-clause-on-python-while-statement)

For those who are not familiar with Python, an `else` clause written after a `while` loop executes only if the while exited naturally (e.g not via a "break" statement).

Such addition to C# might be useful in my opinion.

**Comment by HaloFour** [comment]
Seems like a behavior very easily emulated with existing language features, especially for as infrequent as such a feature would be used.  Also, your description of the behavior is not what I would expect given the syntax.  I'd expect that `else` would execute only if the `while` condition was never true.

**Comment by dmitriyse** [comment]
This is the sort of flow control sugar. The only benefit is saving of some lines of code.
I don't know any nowadays research what micro-patters are really very popular and can be optimized by new flow control abstractions.
May be we miss some abstractions above if, while/do, for, foreach, 
This is very scientific work to find those patterns. I suppose we should analyze tons of code and find most frequent verbosity.
I believe that we can find more than one such kind of optimizations.

P.S.
@yotam180 description is correct.

```CSharp
    
    for(int i =0; i < 100; i++)
    {
         if (i %3 ==0 && i%7 == 0)
         {
              Console.WriteLine($"Magic number = {i}");
              break ;
         }
    }
    else
    {
         Console.WriteLine("No magic numbers found.")
    }
```

**Comment by dmitriyse** [comment]
Unfortunately we have too many features with much higher priority. There are not strong necessity of such features.
But if this feature will ever appears in the language, I will use it frequently.

**Comment by dmitriyse** [comment]
Also this proposal is non toxic. No any breaking changes for binaries/CLR/source code.
Only parsers and analyzers should be improved, but this improvement not so hard.

**Comment by jnm2** [comment]
@dmitriyse

> Also this proposal is non toxic. No any breaking changes for binaries/CLR/source code.

Hmm, wouldn't it be a breaking change for this code?

```c#
if (Foo())
    while (condition) { }
else
    Bar();    
```

**Comment by HaloFour** [comment]
@jnm2

> Hmm, wouldn't it be a breaking change for this code?

Good catch.

**Comment by dmitriyse** [comment]
@jnm2 seems you send to the scaffold this proposal. :)

**Comment by dmitriyse** [comment]
But still we need at least one 100500 votes for this feature to pop it in backlog.

**Comment by Thaina** [comment]
For me, both `else` and `otherwise` is not naturally translate into your proposal

If I see `while(){} else {}` or `while(){} otherwise {}` I would think that the code in `else` or `otherwise` will be run over **ONLY IF** the while loop **NEVER** got in

For the behaviour you propose I would like to have `while(){} then {}` instead

And normally what I would do is checking the last state from loop

```C#
    for(int i =0; i < 100; i++)
    {
         if (i %3 ==0 && i%7 == 0)
         {
              Console.WriteLine($"Magic number = {i}");
              break ;
         }
    }

    if(i == 101)
    {
         Console.WriteLine("No magic numbers found.")
    }
```

**Comment by DavidArno** [comment]
@Thaina,

Pah, why use `var` and `if/else`? Make the whole thing a single statement due to the beauty of `is var` 😀 
```cs
Console.WriteLine(Enumerable.Range(0, 100).Where((i) => i % 3 == 0 && i % 7 == 0) 
                  is var magicNumbers &&
                  magicNumbers.Count() < 1 
                  ? "No magic numbers found."
                  : $"Magic number = {string.Join(",", magicNumbers)}");
```

**Comment by dmitriyse** [comment]
This all about readability.
Assume you have far more complicated bodies instead of Console.WriteLine

Compare this:
```CSharp
    
    for(int i =0; i < 100; i++)
    {
         if (i %3 ==0 && i%7 == 0)
         {
              Console.WriteLine($"Magic number = {i}");
              break ;
         }
    }
    otherwise
    {
         Console.WriteLine("No magic numbers found.")
    }
```
And this:
```CSharp
onsole.WriteLine(Enumerable.Range(0, 100).Where((i) => i % 3 == 0 && i % 7 == 0) 
                  is var magicNumbers &&
                  magicNumbers.Count() < 1 
                  ? "No magic numbers found."
                  : $"Magic number = {string.Join(",", magicNumbers)}");
```

How milliseconds you will spend to understand what code will do in the first and the second cases...

**Comment by DavidArno** [comment]
@dmitriyse,

It depends which style of code you are used to reading and writing. 

I personally prefer a more declarative approach to code and find my code far easier to read than a bunch of for loops and nested ifs/otherwise's etc. And, unless I used `otherwise` a lot, I'd have to go and read up on what it did as the proposal (and Python's implementation) are non-intuitive as I'd expect it only to execute if the for loop isn't entered; not because `break` wasn't executed.

**Comment by dmitriyse** [comment]
You are right, everybody include me firstly understand differently than it is in Python specification.
It's clear from first comment votes.

```CSharp
    for(int i =0; i < 100; i++)
    {
         if (i %3 ==0 && i%7 == 0)
         {
              Console.WriteLine($"Magic number = {i}");
              break ;
         }
    }
    uninterrupted // this can save situation
    {
         Console.WriteLine("No magic numbers found.")
    }
```
Again I am taking in account that this feature will give small impact and cover small fraction of cases bot far more than zero.

**Comment by Thaina** [comment]
For me LINQ is **far** more readable. Just @DavidArno sample is too extreme

In your case if you just want one number is would be easier

```C#
var n = 0.To(99).Where((i) => i % 3 ==0 && i % 7 == 0).DefaultIfEmpty(-1).First();
Console.WriteLine(n < 0 ? "No magic numbers found." : ("Magic number is " + n));
```

**Comment by Thaina** [comment]
Also instead of `uninterrupted` block we could make local function to `return` instead of `break`

I would prefer writing fast `return` instead of marking a block that just run only for a complete loop

```C#
void DoSomething()
{
     FindMagicNumber();

     void FindMagicNumber()
     {
         for(int i =0; i < 100; i++)
         {
             if (i % 3 ==0 && i % 7 == 0)
             {
                 Console.WriteLine($"Magic number = {i}");
                 return;
             }
        }

        Console.WriteLine("No magic numbers found.")
     }
}
```

**Comment by dmitriyse** [comment]
Cool, especially with value tuples.
You show us that we have already rich language. Let python live his life.

Probably it's time to close this proposal ?
