### ISSUE TITLE
Records proposal - implementing With with lambda expressions

### ISSUE THREAD

**Issue by kofifus** [dotnet/csharplang#2272]
This is for the c# 8 record proposal (https://github.com/dotnet/csharplang/blob/98043cdc889303d956d540d7ab3bc4f5044a9d3b/proposals/records.md)

Not an issue but just to show that `With` can be implemented quite elegantly and efficiently with C#7 and caching lambda expressions, see https://github.com/kofifus/With or https://github.com/ababik/Remute

With `With` you can do:

```
var org = new Organization("Organization", new Department("Development Department", new Employee("John", "Doe")));
var mutatedOrg = org.With(x => x.Sales.Manager.FirstName, "Foo");

Object.ReferenceEquals(org.Sales.Manager, mutatedOrg.Sales.Manager)); // false
Object.ReferenceEquals(org.Sales, mutatedOrg.Sales)); // false
Object.ReferenceEquals(org.Name, mutatedOrg.Name)); // true
Object.ReferenceEquals(org.Sales.Title, mutatedOrg.Sales.Title)); // true
```
Feel free to close this I didn't know how else to inform you.

**Comment by Tom01098** [comment]
This repo is for the language, if you'd like to make a suggestion to the BCL then [Corefx](https://github.com/dotnet/corefx/issues) is probably where you want to put it.

**Comment by kofifus** [comment]
Thanks Tom01098 - I want this to go to those involved with the records propposal - https://github.com/dotnet/csharplang/blob/98043cdc889303d956d540d7ab3bc4f5044a9d3b/proposals/records.md

Is there a way to access a discussion of a particular proposal ?

**Comment by Tom01098** [comment]
There is an issue for records but I can't find it, I'd recommend to tailor this issue towards records if that is what you want.

**Comment by yaakov-h** [comment]
The championed issue for Records is #39.

**Comment by kofifus** [comment]
thanks!
