### ISSUE TITLE
Pattern matching KeyValuePair types in foreach() 

### ISSUE THREAD

**Issue by bdelsey64** [dotnet/csharplang#2274]
Consider allowing the user to directly type and name the key/value pair identifiers in a foreach() statement where the expression is a collection of KeyValuePair<TKey, TValue> types.

For example, instead of:

`foreach (KeyValuePair<string, int> kvp in employees)
{
    string name = kvp.Key;
    int age = kvp.Value;

    ...
}`

It would be preferable to write something similar to the following with inline variable types and names clearly defined:

`foreach (<string name, int age> in employees)
{
    ...
}`

**Comment by HaloFour** [comment]
You can add the following extension:

```cs
public static class KeyValuePairExtensions {
    public static void Deconstruct<TKey, TValue>(this KeyValuePair<TKey, TValue> pair, out TKey key, out TValue value) {
        key = pair.Key;
        value = pair.Value;
    }
}
```

Then you can do:

```cs
foreach (var (name, age) in employees) {
}
```

Hopefully the BCL will add a `Deconstruct` method to `KeyValuePair<TKey, TValue>` directly so that you don't have to provide your own.

**Comment by bdelsey64** [comment]
Perfect! Thank you

**Comment by MattDillard** [comment]
For what it's worth, this `Deconstruct` method [is present](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2.deconstruct?view=netcore-2.2&viewFallbackFrom=netframework-4.7.2) in .NET Core. It's just not available in the .NET Framework BCL.
