### ISSUE TITLE
Feature request: Allow parameter default argument to be a property value

### ISSUE THREAD

**Issue by msedi** [dotnet/csharplang#2275]
Currently we have the [CallerMemberName] that helps to ease writing property getters and setters.
We, for example, always do it in the following way:

```
public int PropertyName
{
  get => GetProperty();
  set => SetProperty(value);
}
```
where

```
public T GetProperty<T>(T propertyValueDefault = default, 
  [CallerMemberName]string propertyName = "")
```

and

```
public void SetProperty<T>(T propertyValue, 
  [CallerMemberName]string propertyName = "");`
```

This normally works just fine, but the code is not symmetric, you always have to enter the value as method parameter. I would therefore suggest a possibility to let the compiler deduce the corresponding parameter, which is in this case `value`. So that we can write:

```
public int PropertyName
{
  get => GetProperty();
  set => SetProperty();
}
```

In the end `SetProperty` could look like this:

```
public void SetProperty<T>(T propertyValue = value, 
  [CallerMemberName]string propertyName = "");
```

for this special case. I could understand that this might confuse people since `value `is also a contextual keyword, so another suggestion could be

```
public void SetProperty<T>(T propertyValue = default(value), 
  [CallerMemberName]string propertyName = "");
```

I can currently see no other use case where this would be needed.

**Comment by YairHalberstadt** [comment]
I'm struggling to understand this.

You're suggesting that in any Method `M(p)`, I could define a default value for `p`, such that if no value is provided for M, and M, is called from a property setter, it will have a default value of the implicit value parameter of the setter?

That is just really wierd.

It sounds to me like this is literally just adding a lot of complexity to the language for the sake of making a really obscure scenario 5 letters shorter to type.

Perhaps I misunderstood the proposal, or I'm not seeing the advantages it provides?

**Comment by msedi** [comment]
@YairHalberstadt: At least it was clear to me ;-) The only thing I'm saying is that it would be nice to have the example with the getter and setter to be and look symmetric.

In the end I only need something where the compiler could rewrite the SetProperty method in the setter from

```
public int PropertyName
{
  get => GetProperty();
  set => SetProperty();
}
```

to something 

public int PropertyName
{
  get => GetProperty();
  set => SetProperty(value);
}

as this also happens with the [CallerMemberName]. Of course writing SetProperty(value) is pretty easy, but if you are writing many components that do something like the example above, gets pretty annoying. Moreover is is pretty annoying to write the above code in general multiple times. So what I would prefer in would be more like a roslyn rewrite of my code

```
[ReplaceBy(Getter=GetProperty, Setter=SetProperty)]
public int Property1 {get; set;}

```

Property1 is rewritten to 

public int PropertyName
{
  get => GetProperty();
  set => SetProperty(value);
}

I don't like the attribute syntax here, because in the end it's much more work to write indeed, this should be only some example to discuss

I think I can summarize this to that I need some general entry point to rewrite my code during compilation in roslyn, similar to C# so that I can do the things I need for myself.

**Comment by yaakov-h** [comment]
That would be #107 then.

**Comment by HaloFour** [comment]
> The only thing I'm saying is that it would be nice to have the example with the getter and setter to look symmetric.

Why?  Getters and setters are not symmetric.

**Comment by msedi** [comment]
@HaloFour: Right, I just was saying they should **look like symmetric**. Nevertheless if #107 solves my real problem that's just fine.
