### ISSUE TITLE
Proposal: Syntactic sugar for (x => x.AProperty)

### ISSUE THREAD

**Issue by AndreasHassing** [dotnet/csharplang#2280]
# Dot lambda property access sugar

It would be syntactically distinct and concise to be able to write out a lambda `x => x.Property` as `.Property` instead (when the surrounding context knows the type of `.`).

I often find myself doing things like:

```csharp
IEnumerable<KeyValuePair> myKvps = GetMyKvps();

return myKvps.ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
```

And would love it if it was possible to do:

```csharp
IEnumerable<KeyValuePair> myKvps = GetMyKvps();

return myKvps.ToDictionary(.Key, .Value);
```

What do _you_ think?

**Comment by Joe4evr** [comment]
Duplicate of #91.

**Comment by AndreasHassing** [comment]
My search-fu has deteriorated! Thanks @Joe4evr 😄.
