### ISSUE TITLE
Proposal: Compact syntax for multi-statement blocks

### ISSUE THREAD

**Issue by n-stefan** [dotnet/csharplang#2281]
Currently single-statement `if/else if/else` blocks can be written as:

```csharp
if (Condition1)
    StatementA;
else if (Condition2)
    StatementB;
else
    StatementC;
```

But for multi-statement blocks braces are needed:

```csharp
if (Condition1)
{
    StatementA;
    StatementB;
}
else if (Condition2)
{
    StatementC;
    StatementD;
}
else
{
    StatementE;
    StatementF;
}
```

The proposal is for an additional, more compact syntax:

```csharp
if (Condition1)
    StatementA;
    StatementB.
else if (Condition2)
    StatementC;
    StatementD.
else
    StatementE;
    StatementF.
```

The last statement in each block is followed by a period (.) instead of a semicolon (;).
The syntax would save two lines per block while remaining very close to the single-statement form. Proper indentation would make the extent of the blocks very easy to see, however the compiler would only care about the period that closes the block, so it would work even with broken indentation.
The following would also be possible:

```csharp
if (Condition1)
    StatementA; StatementB.
else if (Condition2)
    StatementC; StatementD.
else
    StatementE; StatementF.
```

And this (even more compact):

```csharp
if (Condition1) StatementA; StatementB.
else if (Condition2) StatementC; StatementD.
else StatementE; StatementF.
```

The choice of period to end blocks seems natural (just like it ends sentences in written natural language), but another character could also be used instead.
The syntax would not necessarily be limited to `if/else if/else` blocks.

**Comment by stuartstein777** [comment]
I might be being stupid here but what if the last statement was say

    return foo;

This becomes 

    return foo.

That's probably a compiler error, as it will be expecting you to reference a method / property after the dot.

I don't think a dot can work here, can it?

**Comment by YairHalberstadt** [comment]
> The syntax would save two lines per block while remaining very close to the single-statement form.

You can already do this. You can even use the really compact form you suggested!

```csharp
if (Condition1) { StatementA; StatementB; }
else if (Condition2) { StatementC; StatementD; }
else { StatementE; StatementF; }
```

**Comment by stuartstein777** [comment]
Maybe if Visual Studio / VSCode had a way to turn the { } brackets colour the same colour as the text editor background, people who hate these can just make them "invisible".

Obviously joking but mabye not... *ponders*

**Comment by HaloFour** [comment]
There are .NET-based languages that don't use curly brackets.

The funny thing about your suggestion is that it us lifted almost directly from COBOL.  I don't care how much one might dislike the grammar of C#, there are way worse options.  (Or, if that is your preference, there are multiple commercially supported COBOL compilers for .NET)

**Comment by YairHalberstadt** [comment]
I'm pretty sure a Vs extension could do that

**Comment by MgSam** [comment]
This is purely a style issue. In other languages it's much more common to not use new lines for curly braces. There's no reason you can't do this in C#.
``` C#
if (Condition1) {
    StatementA;
    StatementB;
} else if (Condition2) {
    StatementC;
    StatementD;
} else {
    StatementE;
    StatementF;
}
```

**Comment by n-stefan** [comment]
@stuartstein777
It wouldn't be a compiler error, it would be treated as end-of-block.
Another character instead of period could also be used, as noted in the proposal.

@YairHalberstadt
Obviously, in that case the syntax saves two characters per line (+ two more if spaces are also used).

@MgSam
Sure, but it still saves characters and a line for the final brace (and aligns the if/else if/else nicely).

I don't hate the braces at all, just looking for ways to shorten the syntax.

**Comment by YairHalberstadt** [comment]
@n-stefan

It is not one of the aims of the C# Language to save on a small number of characters here and there. Any proposal whose only purpose is to do that is not gonna get accepted I'm afraid.

Now there are a number of features which have been added to the language which do reduce boilerplate. But they have a different purpose - their aim is to reduce noise in the language, so you can express what you're trying to do more clearly, and spend fewer characters on the uninteresting things, like exactly how a property works.

In your case, I don't see the proposal doing that - if anything it makes the language more noisy

**Comment by HaloFour** [comment]
> Sure, but it still saves characters and a line for the final brace (and aligns the if/else if/else nicely)

You're free to put the curly braces anywhere you want, including at the end of the line.

> I don't hate the braces at all, just looking for ways to shorten the syntax.

This proposal doesn't make anything appreciably shorter, but it does make it a lot harder to reason about.  A multi-statement terminator like `.` would be easy to forget, completely changing the meaning of the code.  It would also be very easy to miss when reading the code.

Trying to compact everything down to be as small as possible doesn't make code easier to write or more maintainable.  This is evident in how many whitespace sensitive languages, like Python, have coding guidelines which dictate additional whitespace in order to make clear what indentation can't do alone.

**Comment by bbarry** [comment]
```csharp
if (Condition1)
    StatementA;
    StatementB.
else if (Condition2)
    StatementC;
    StatementD.
else
    StatementE;
    StatementF.
StatementGIsAmbiguous;
```

**Comment by MgSam** [comment]
> @n-stefan
> 
> It is not one of the aims of the C# Language to save on a small number of characters here and there. Any proposal whose only purpose is to do that is not gonna get accepted I'm afraid.

😄 Tell that to pattern matching, expression-bodied methods, `out` declarations, `default`, the `??=` operator, the `in` keyword; just to name a few of the more recent ones. A huge amount of the LDT's time is spent designing features which save just a few characters.

**Comment by CyrusNajmabadi** [comment]
@MgSam But @n-stefan is correct.  The aim of C# is not to save on a small number of characters here and there.  The goals are often about productivity.  And it happens to be the case that the features that are felt to help productivity are designed to not be overly verbose.

**Comment by n-stefan** [comment]
Or the classic example of lambdas, saving one character at a time.
The syntax would be similar to whitespace sensitive languages, without actually being whitespace sensitive.
A missing period (when there's also no semicolon) would be flagged by the compiler. Proper indentation would make it easy to read; bad indentation also makes brace syntax hard to read.
Importantly it is not meant to replace the brace syntax.

**Comment by theunrepentantgeek** [comment]
> A huge amount of the LDT's time is spent designing features which save just a few characters.

Importantly though, these features don't ONLY save just a few characters, they address other value as well.

**Comment by HaloFour** [comment]
Importantly this proposal is for a block-end syntax without a block-begin syntax.  That means that anywhere the compiler supports a block (which is anywhere a statement is supported) the compiler now has to consider that it could be the start of a block.  It then has to parse ahead an arbitrary number of statements to find a potential matching `.`.  But it has to also do that for literally every statement that appears within that "block".  Even if that were limited to where the compiler expects embedded-statements that's an untenable situation.

Indentation doesn't exist to C# as anything more than trivia.  The compiler can't know that you're using `.` wrong or in an incorrect position.  It only knows what is legal to parse.  This proposal is too ambiguous and offers no value to those who aren't offended by curly braces.

**Comment by ufcpp** [comment]
see https://github.com/dotnet/roslyn/issues/13731

**Comment by n-stefan** [comment]
That's a proposal for a whitespace sensitive language, with new keywords; this is not.

**Comment by gafter** [comment]
This proposal would change the behavior of this existing code

``` c#
if (e)
    Stmt1;
else
    M1();
    M2().
M3();
```

**Comment by n-stefan** [comment]
Not sure I follow, you mean replacing a semicolon after M2() with a period?
Yes, that would change the behavior, but the intent is also different: if M2() is followed by a semicolon, the else branch is only intended to encompass M1(), while when followed by a period both M1() and M2().
Only M1() part of else branch (indentation of M2() wrong):
```csharp
if (e)
    Stmt1;
else
    M1();
    M2();
M3();
```

Both M1() and M2() part of else branch:
```csharp
if (e)
    Stmt1;
else
    M1();
    M2().
M3();
```

**Comment by YairHalberstadt** [comment]
```
if (e)
    Stmt1;
else
    M1();
    M2().
M3();
```

This is already legal, and means something else

**Comment by n-stefan** [comment]
Right, if formatting is not a concern.
Another character could be used instead of period, though choosing the perfect fit is not trivial.

**Comment by YairHalberstadt** [comment]
C# is not formatting sensitive, and I do not believe that is likely to change.

**Comment by HaloFour** [comment]
@n-stefan 

> Another character could be used instead of period, though choosing the perfect fit is not trivial.

You could always add the character after the semicolon.  That would eliminate that ambiguity.

But you still have the problem that if any embedded-statement can be implicitly a block that it would be ambiguous to determine to which block a given terminating character belongs.

```cs
if (cond1)
    S1();
    S2();
    if (cond2) S3();
    S4(). // do I only execute if cond2 is true?
```

So, for that purpose, I also propose a character that starts these blocks.

I think I have a good combination of characters that would work here, too.  What about `{` and `}`?  They would fit in with the existing syntax and history of C languages.

**Comment by DaZombieKiller** [comment]
While I'm of the opinion that this is an incredibly unnecessary feature, wouldn't it be far better to have syntax reminiscent of the C/C++ comma operator instead?

```cs
     if (conda) statement1, statement2;
else if (condb) statement1, statement2, statement3;
else            statement1;
```

**Comment by gafter** [comment]
The premise of this request and many of the follow-on comments is that the semicolon is used to terminate a statement.  That isn't quite correct.  The semicolon is *part* of many statements.  And there are many statements that do not have a semicolon.  The semicolon is certainly not a statement separator or anything like it.

Here are a few examples of statements that do not end with a semicolon:
- `{ }`
- `switch (e) { }`
- `while (e) { }`
- `if (e) { }`

**Comment by n-stefan** [comment]
@DaZombieKiller
Looks nice, clean, not too different from the proposed syntax.
@gafter
You are right about the premise :)

Closing issue.
