### ISSUE TITLE
Introduce a local scope for enum (with Flags attribute) to reduce code repetition

### ISSUE THREAD

**Issue by techfan101** [dotnet/csharplang#2282]
When using an `enum` with the `Flags` attribute, it is very common to OR the members of the enumeration together.  With current C# syntax, this causes a lot of unsightly repetition.  This is especially troublesome when the name of the `enum` is particularly long.   Consider the following:
```csharp
[Flags]
public enum MyEnum
{
  Member1 = 1,
  Member2 = 2,
  Member3 = 4
}
```
Some common use cases include variable or field initializations, conditional clauses, method invocations, and attribute parameters:
```csharp
var state = MyEnum.Member1 | MyEnum.Member2 | MyEnum.Member3;

if ((state & (MyEnum.Member1 | MyEnum.Member2 | MyEnum.Member3)) == 0)
  return;

MyMethod(MyEnum.Member1 | MyEnum.Member2 | MyEnum.Member3);

[MyAttribute(MyEnum.Member1 | MyEnum.Member2 | MyEnum.Member3)]
```
All of these could be improved, by allowing a local scope where the member names can be used without referencing the `enum` name.  I propose the following syntax:
```csharp
var state = MyEnum{ Member1 | Member2 | Member3 };

if ((state & MyEnum{ Member1 | Member2 | Member3 }) == 0)
  return;

MyMethod(MyEnum{ Member1 | Member2 | Member3 });

[MyAttribute(MyEnum{ Member1 | Member2 | Member3 })]
```
To avoid overwhelming the reader, I’ve intentionally used shorter `enum` and member names.   The impact of this change, would be considerably more dramatic were the names longer.

I’ll leave it up to the implementers to decide exactly what would be allowed within the block.  I would suggest a minimum of the member names and all logical operators.   Although, an alternative would be to allow anything and simply report compiler errors if and when naming ambiguities occur.

To clarify a bit, consider the case of Lambda expressions.
```csharp
myParm => { myMethod(myParm); }
```
In the above case, `myParm` only has visibility within the `{ ... }` block.  What I'm suggesting is that the unqualified member names for an `enum` would have similar visibility within the enclosing `{ ... }` block.
```csharp
MyEnum { MyMethod(Member1); myVariable = Member2; }
```
While this would undoubtedly be more challenging to implement than the more limited case I suggested as a minimum, it might be worth the effort.  Again, I'd leave that up to the folks who actually have to implement it.

**Comment by YairHalberstadt** [comment]
`using static` is a similar feature for a accessing static members directly. That might be a good place to start from syntax wise.

**Comment by techfan101** [comment]
Thank you for the idea.  That does employ similar rules for resolving names to what I envisioned.  It may indeed serve as a good model.  However, I believe `using static` applies to the entire module.   To be useful, this would require much finer granularity for the altered scope.   This is why I suggested a local block enclosed in curly brackets.

**Comment by HaloFour** [comment]
There have been discussions about having the compiler resolve enums by only the member name where it can be done unambiguously:

https://github.com/dotnet/csharplang/issues/321

I don't believe this has been championed yet and there are likely a lot of devils in the details.

**Comment by techfan101** [comment]
@HaloFour, I share enthusiasm for their motivation, but not their implementation :)  Seriously, to me, that approach seems a little "wild west".  I guess I prefer to be more explicit in conveying my intent to the compiler.  I don't mind mentioning the `enum` name once, I simply despise repeating long names a bunch of times.

**Comment by HaloFour** [comment]
@techfan101 

Maybe, but their approach would be much more broadly applicable where it seems that this proposal would only benefit those cases where you're specifically doing bitwise operations.

**Comment by techfan101** [comment]
@HaloFour I guess it really depends on how ambitious the implementers get.  The **minimum** I hoped for was that it would promote the visibility of the member names and allow bitwise operations.  However, it need not be so limited.   You could allow pretty much any code, as is the case with all of the other `{ ... }` blocks in C#.  For example, it could work similarly to lambda expressions, but making the member names visible within the block (instead of the lambda parameters).  For me, the important thing is that I can control what regions of code are affected, instead of relying on the compiler to guess.

**Comment by techfan101** [comment]
Closing this in favor of a more generalized approach: issue [#2287](https://github.com/dotnet/csharplang/issues/2287).
