### ISSUE TITLE
Proposal: short-form notation for Span<T> and ReadOnlySpan<T>

### ISSUE THREAD

**Issue by VG9tIEhpY2tsaW5n** [dotnet/csharplang#2289]
The new generic `by ref struct` types `Span<T>` and `ReadOnlySpan<T>` are very useful for passing around well-constrained slices of arrays without allocating additional memory on the heap.

I think the pair are useful enough to merit a new syntactic sugar to reduce the length of declaring them: similar to how `byte?` is just an alias for `Nullable<byte>`, I propose that `Span<byte>` could be represented by something similar to `byte$`, and perhaps `ReadOnlySpan<byte>` could become `byte~`.

**Comment by YairHalberstadt** [comment]
To be honest, I imagine that 95% of code bases will never use Span, whereas I estimate that 95% of codebases use Nullable

**Comment by VG9tIEhpY2tsaW5n** [comment]
@YairHalberstadt that's a fair point. Especially since there would have to be not one but _two_ post-fix characters dedicated to this syntax. I've been refactoring a lot of code into using these types lately which is why I thought this might be a good idea, but it is definitely situational.

**Comment by VG9tIEhpY2tsaW5n** [comment]
If anyone finds this and thinks this would benefit them, I think the following is a good enough workaround:
```
using Span = System.Span<byte>;
using RSpan = System.ReadOnlySpan<byte>;
```
Wish I'd thought to do this hours ago.
