### ISSUE TITLE
Question: discards in non-deconstructing assignments

### ISSUE THREAD

**Issue by controlflow** [dotnet/csharplang#229]
What was the reason to include this kind of discards (based on symbol binding fallback) in the language?
```c#
_ = 42;
```

Currently discards are used for a few purposes:
1. To ignore the value of `out` parameter: `M(out _)` (I do not understand why `M(out var _)` was not enough);
2. To indicate the amount of components you want to deconstruct the value into while ignoring some of  the deconstructed values: `(var a, _, bar b) = e;` or `(a, _, b) = e;` (calls `Deconstruct` with 3 `out` parameters).

I can't see how single-value discards can be any useful. Maybe they allow user to explicitly state that the value is ignored to suppress some analyzers reporting pure method invocations without return value usages? But that's generally shouldn't be done :/

Right now it seems like this is a **bug**, since method [GetContainingDeconstruction](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/SyntaxExtensions.cs,6acf57546734d3fa) (used to check binding fallback) returns the assignment expression without any deconstruction happening in LHS despite the documentation stating "this declaration or identifier is part of a deconstruction".

If such single-value discards were intended, why compiler was not updated to handle more context where value is ignored, for example, in conditional method invocations with non-liftable return types?
```c#
class C {
  T M<T>() {
    var t = this?.M<T>(); // error CS0023, can't lift `T` unconstrained type
    this?.M<T>(); // OK, value is ignored, no need to lift it's type!
    _ = this?.M<T>(); // error CS0023, why?
    _ = _ = this?.M<T>(); // CS0023 again
      
    return default(T);
  }
}
```

Please, clarify the design decisions around such kind of single-value discards. Thanks!

**Comment by alrz** [comment]
>What was the reason to include this kind of discards (based on symbol binding fallback) in the language?

the reason is somehow hard-coded in the compiler: https://github.com/dotnet/roslyn/issues/15695

**Comment by agocke** [comment]
```csharp
// returns a task, but we don't want to wait on it. Not assigning gives a warning
_ = MyFuncAsync();
```

**Comment by gafter** [comment]
> error CS0023, why?

Because if you didn't get that error, what would be the type of the assignment expression?

**Comment by DavidArno** [comment]
@gafter,

Why does it matter what the type is as it's discarded? Surely the two line,
```cs
this?.M<T>(); 
_ = this?.M<T>();
```
should be semantically identical, with the second simply reassuring the compiler that you really don't care about the result?

**Comment by gafter** [comment]
@DavidArno As it turns out, the assignment expression is defined in such a way that the type of the right-hand operand is required to make sense of it.

**Comment by controlflow** [comment]
@gafter what is the type of `this?.M<T>()` expression then? Why invocation expression like this "make sense" without definite return type and assignment expression is not?

The assignment expression itself is in context where it's value is ignored, why would somebody care about it's type?

**Comment by DavidArno** [comment]
@gafter,

So is it just a case of "that's the way it is", or is this an area where the compiler could be improved in future?

**Comment by gafter** [comment]
@DavidArno I can imagine a language change that defines special behavior for the assignment expression when the left-hand-side is a discard.

**Comment by bbarry** [comment]
@controlflow 

> what is the type of `this?.M<T>()` expression then? Why invocation expression like this "make sense" without definite expression type and assignment expression is not?

`this?.M<T>(); ` is an [expression statement](https://github.com/dotnet/csharplang/blob/master/spec/statements.md#expression-statements) containing an [invocation expression](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#invocation-expressions). I don't see anywhere where an invocation expression return type being restricted at all in this case. There is a bit to explicitly permit `void` in such cases (which I think is unnecessary?: Are all possible invocation expressions legal as expression statements?).

@DavidArno 

> Surely the two line should be semantically identical

But they aren't syntactically identical. The former is an expression statement containing an invocation expression (which is not constrained) and the latter is an [expression statement](https://github.com/dotnet/csharplang/blob/master/spec/statements.md#expression-statements) containing an [assignment](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#assignment-operators), specifically a [simple assignment](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#simple-assignment), where it explicitly states:

> In a simple assignment, the right operand must be an expression that is implicitly convertible to the type of the left operand.

Thus the type must be evaluated here.

**Comment by controlflow** [comment]
@bbarry 

> this?.M<T>(); is an expression statement containing an invocation expression. I don't see anywhere where an invocation expression return type being restricted at all in this case.

Actually, this is not "invocation expression" contained in "expression statement", this is C# 6.0 "conditional access expression" (not in spec yet) + it contains "invocation expression" :)

I was only trying to demonstrate how the concept of "ignored value" (used to allow conditional calls with non-liftable return type) has bad intersection with `_ = e` expression that is exactly "ignore this value" construct now. You can justify this from current spec as long as you like, but this looks weird from user's point of view.

Can we go back to discussion on why we need `_ = e` in a first place, please?

**Comment by HaloFour** [comment]
@controlflow 

IIRC it's a side effect of the way discards are implemented.  It shuts up some overzealous analyzers, but that's about it.

**Comment by DavidArno** [comment]
@controlflow,
> Can we go back to discussion on why we need _ = e in a first place, please?

Because it's good practice. Just having:
```cs
this?.M<T>();
```
ought to be at least a warning, as `M<T>()` returns `T`, yet the statement treats it as a `void`. Whereas:
```cs
_ = this?.M<T>();
```
is explicitly stating that you understand that `M<T>()` returns `T`, but you don't care about the result. Unfortunately, it gives a compiler error.

Yet, on the other hand,,
```cs
_ = 42;
```
is pointless, and I hope/assume that either the compiler in non-debug mode, or the JIT, would simply remove it.

Unfortunately, we are in the position where the compiler allows pointless uses of discards, but gives an error in situations where their use ought to be legitimate. Bit awkward, really.

**Comment by bbarry** [comment]
It still isn't type restricted (And it is in the [spec](https://github.com/dotnet/csharplang/blob/d432a56ddde3085b96f8dc94b8984243a12e1e52/spec/expressions.md#null-conditional-expressions-as-statement-expressions) here as a "null conditional invocation expression").

But the language has shipped. As weird as this intersection of concepts is, we have it now. I completely agree it is awkward, but I think the fix should be to allow the assignment somehow, rather than disallow discard simple assignment or disallow invocations that return something unrepresentable or disallow invocations that return anything at all.  I'd argue that this concept of "ignored value" should be more invasive.

**Comment by DavidArno** [comment]
I agree with your point re `_ = Console.WriteLine("um");` suddenly being valid syntax. That just seems a bit too weird. Also it's only going to be awkward for a time as the planned allowance of discards in lambda (and hopefully, method) signatures will improve this feature.

**Comment by alrz** [comment]
Wait, `void M() => _ = M();` [already works](https://tryroslyn.azurewebsites.net/#b:master/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcBYAUAB2ACMAbMAYxnJIEMQQYBhGAbzxg5gDcB7MAExgBZABQBKGAF4AfDAD6U4eJy4AvkA=). 😮

**Comment by DavidArno** [comment]
Ha, looks like @gafter at least doesn't like the fact that `_ = SomeVoidMethod()` is supported. Good find there, @alrz. [Compiler permits `_ = M()` for void-returning method](https://github.com/dotnet/roslyn/issues/17674).

**Comment by jcouv** [comment]
I think the question was resolved. I'll go ahead and close the issue. 
Feel free to re-open if that was not the case. Thanks
