### ISSUE TITLE
Unary Operators Missing from Table

### ISSUE THREAD

**Issue by Timothy-Liu** [dotnet/csharplang#2297]
**Where:**
https://github.com/dotnet/csharplang/blob/master/spec/expressions.md

**What:**
In the table of **Operator precedence and associativity**, the unary operators are **+ - ! ~ ++x --x (T)x**. But, in the text description **Unary operators**, the unary operators are described as "The **? , + , - , ! , ~ , ++ , -- , cast, and await** operators are called the unary operators." Or say, **?** and **await** are missing from the table.

**Comment by TheUnlocked** [comment]
I would say that `await` is more of a keyword than an operator, and `?` is more of a macro to wrap a type with `Nullable<T>` (or as a message to the compiler in C# 8+), not an expression.

**Comment by svick** [comment]
@TheUnlocked

[The `await` expression](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#await-expressions) is listed in the unary operators section, so it is an operator according to the spec.

And when the spec talks about the `?` operator, I believe it means [the null conditional operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#null-conditional-operator): `?.` and `?[]`.

**Comment by TheUnlocked** [comment]
Huh, okay.

**Comment by BillWagner** [comment]
The standard text [§12.4.2](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#1242-operator-precedence-and-associativity) lists these correct.

Closing this, as completed.
