### ISSUE TITLE
Allow something like unconstrained 'static ref T Test<T>(this in T o) => ref o;'

### ISSUE THREAD

**Issue by RobotAL76** [dotnet/csharplang#2300]
Hello! Possible, I don't understand something clearly, please, feel free to correct me.

According my personal experience it is great aesthetic pleasure to write chained method calls instead of direct outing of local variables. For example
```c#
var item = GetItem();
collection1.Add(item);
collection2.Add(item);
item.DoSomething();
```
may be replaced by
```c#
GetItem().AddTo(collection1).AddTo(collection2).DoSomething();
```
where
```c#
public static T AddTo<T>(this T item, ICollection<T> collecton)
{
	collecton.Add(item);
	return item;
}
```

Similar extension methods nice for reference types, but I worried about value types because, if I understand correctly, each additional chained call cause overhead copying of value during passing arguments between methods.

Looks that it is possible slightly optimize this code specially for value types
```c#
GetItem().To(out var _).AddByRefTo(collection1).AddByRefTo(collection2).DoSomething();
```
where
```c#
public static ref T To<T>(this T o, out T x) { x = o; return ref x; }
public static ref T AddByRefTo<T>(this ref T item, ICollection<T> collecton) where T : struct
{
	collecton.Add(item);
	return ref item;
}
```

But this code looks not so elegant because require explicit outing of visually unused variable 'To(out var _)'. And most annoying that it is not possible to use the same method name for both overloads
```c#
static T AddTo<T>(this T item, ICollection<T> collecton) // for reference and unconstrained types
static ref T AddTo<T>(this ref T item, ICollection<T> collecton) where T : struct
```

Maybe there is sense to allow something unconstrained like
```c#
/* usable for reference and value types */
public static ref T AddTo<T>(this in T item, ICollection<T> collecton)
{
	collecton.Add(item);
	return ref item;
}
```
with possibility of implicit outing of variables
```c#
new AnyStruct().AddTo(collection1).AddTo(collection2).DoSomething();
```
that means
```c#
new AnyStruct().To(out var _).AddByRefTo(collection1).AddByRefTo(collection2).DoSomething();
```

What do you think?

**Comment by gafter** [comment]
I think the problem you're trying to solve is one of your own creation.  I don't find the programming style elegant at all.

**Comment by RobotAL76** [comment]
@gafter 
Ok, maybe this code style not for common using but are you sure that there is not a bottleneck at all?

_In general sense C# doesn't allow to create unconstrained generic extension methods which doesn't cause copying of value types._

**Comment by RobotAL76** [comment]
@gafter 
And yes, this issue inspired by https://github.com/dotnet/csharplang/issues/2217 and @HaloFour hacky proposal https://github.com/dotnet/csharplang/issues/2217#issuecomment-462915855

Seems that it is possible to work more efficient with structs in C# via creation of implicit references at value types like out variables.

I am not very clear with structs compilation background but for me looks that something missing.

**Comment by TAGC** [comment]
Is Makeloft back?

**Comment by gafter** [comment]
@TAGC Yes.

The proposal in the title is not safe.  It would allow a caller with a `ref readonly` in hand to call this method and obtain a `ref` to the same object, thus undermining the `readonly` modifier.  Therefore I am closing this suggestion as something we would never do.

**Comment by RobotAL76** [comment]
@gafter so, an expected result. :)

According your remark this still may have sense
```c#
    static in T Test<T>(this in T o) => in o;
```
