### ISSUE TITLE
Fast type definition on compile time (An additional shortcut type definition compared to the similar DTO for Poco)

### ISSUE THREAD

**Issue by sgf** [dotnet/csharplang#2307]
```C#
//we can define a short master type (or calls root type) --AAA
@AAA
{
	Id:int
	Name:string
	Age:int
	Address:string
	Add:{Name,Age,Address}
 //we can define a short link type inside in AAA just link the AAA's Name,Age,Address 
}
//or define outside of the AAA in any where we need;
AAA.Add:AAA{Name,Age,Address} >> AAA.Add{Name,Age,Address}  //define Add >> more short
	output:AAA_Insert{Name,Age,Address}
AAA.IdOnly:AAA!Add{Name,Age,Address} >> AAA.IdOnly:!Add  //exclude Add >> more short
	output: AAA_IdOnly{Id}
AAA.Insert:AAA!Id   >>AAA.Insert!Id // exclude Id >> more short
	output: AAA_Insert{Name,Age,Address}

//use
var add=AAA.Add{Name=?,Age=?,Address=?}
//or
var add=AAA.Add(name,age,address)
//or
var add=AAA.Add(Name:?,Age:?)
insert(add);

remove(AAA.IdOnly(?));
```

Composite Pattern ???

**Comment by gafter** [comment]
I have no idea what this is trying to say.

**Comment by sgf** [comment]
i want to say if you want to do it in C# should define to much types:

```C#
public class AAA
{
public int Id {get;set;}
public string Name {get;set;}
public int Age {get;set;}
public string Address {get;set;}
}

public class AAA_Add
{
public string Name {get;set;}
public int Age {get;set;}
public string Address {get;set;}
}


public class AAA_IdOnly
{
public int Id {get;set;}
}

public class AAA_Insert
{
public string Name {get;set;}
public int Age {get;set;}
public string Address {get;set;}
}
```

if support short type define:

```C#
@AAA
{
	Id:int
	Name:string
	Age:int
	Address:string
	Add:{Name,Age,Address}
}

AAA.Add{Name,Age,Address}
 AAA.IdOnly:!Add
AAA.Insert!Id
```

**Comment by yaakov-h** [comment]
Whatever it is that you're trying to propose, it's totally unreadable and doesn't fit in with any preceding syntax whatsoever.

**Comment by mcosmin222** [comment]
This seems to be some sort of smart typing from scripted languages. Given that nobody understands what it is trying to be, I guess this will never be implemented.

**Comment by DanFTRX** [comment]
It looks like he wants to be able to grab an object representation of another object but with restricted access to only certain fields.  And he has proposed some sort of syntax towards accomplishing that.

**Comment by TPFInferno** [comment]
@DanFTRX

So an interface?

**Comment by DanFTRX** [comment]
@TPFInferno Looks like it, some sort of interface that is anonymously created by its implementation.  I don't know for sure though, I didn't write the proposal.  Nor do I think its a great idea.

**Comment by khm1600** [comment]
Records (#39) and slicing (as in "object slicing") of such types?

**Comment by willard720** [comment]
Can you just use words to explain what you want to do and what we can't do?

This is so unreadable, I have no idea what you want.

**Comment by sgf** [comment]
> Can you just use words to explain what you want to do and what we can't do?
> 
> This is so unreadable, I have no idea what you want.

This topic provides an easy way to support freely combining fields or attributes.
They are compiled and strongly typed and produce independent types.
But they may have the same fields or perhaps different fields.

This way you don't have to define a myriad of different Dtos in a regular way for a particular scenario.


maybe i should be close this issue.
Because almost no one can understand. 😂

**Comment by CyrusNajmabadi** [comment]
> Because almost no one can understand. 

Yeah.  You really need to come up with some real examples of code that is difficult to write today, and show what problem this is actually solving.  As it stands, I have no idea what you're actually asking for.
