### ISSUE TITLE
Re-exportable `using` aliases

### ISSUE THREAD

**Issue by narfanar** [dotnet/csharplang#2308]
Request for:

```cs
namespace MyNamespace {
    public using MyType = ExternalType<MyOthertype>;
}

// In another file
using MyNamespace;
namespace Something {
    // REQUEST here is to be able to do:
    MyType foo;
}
```

Right now we can do:

```cs
public class MyType : ExternalType<MyOtherType> {}
```

But I'm not super clear on the pros/cons here. (Actually got nooo idea; but didn't find much discussion online about the feature or this workaround, so hoping for some discussion here.)

**Comment by yaakov-h** [comment]
Related to #259; possible duplicate of #1170.

**Comment by narfanar** [comment]
It's a generalization of #259 

#1170 is actually looking for implicits (as in Scala) but asking for this (public aliases) as a workaround. Or that's how I read it.

Assuming equal support for `internal` and `public` aliases, what's currently supported is "file `private`" aliases. That's why I said "re-exportable" instead of any particular access modifier.

I'd close this if #259 comes to include public aliases as well. It seems overly focused on `internal`. Are the considerations that different?

**Comment by narfanar** [comment]
#1300 is another (maybe more relevant) issue.

I don't think there's anything #1300 misses? It's referring to `typedef` from C++, but there's already mention of the enhanced `using` in C++ as well.

There's talk about generics and such in different proposals. A re-exportable aliasing mechanism should support acting as type functions to be usable for type partial application.
