### ISSUE TITLE
NullableContextOptions and nullable generic type

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/csharplang#2309]
``` XML
<NullableContextOptions>enable</NullableContextOptions>
```
``` C#
static void Test<T>(out T? value) //Error!
{
    value = default;
}
```

**Comment by yaakov-h** [comment]
Yes, and?

> error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.

The error message tells you exactly what's wrong and how to fix it.

`T?` on a reference type is compiled to `T` but the compiler can emit warnings based on flow analysis.

`T?` on a value type is compiled to `Nullable<T>`.

The two cannot co-exist, so you have to specify either `where T : class` or `where T : struct`.

**Comment by Joe4evr** [comment]
That said, there should be an additional attribute (along the lines of `[MaybeNull]`, I forget the *exact* name) specifically for this case that will inform the flow analysis at the callsite that if `T` is a reference-type, it has to be checked for null before it can be dereferenced.

**Comment by TheUnlocked** [comment]
It could be useful to have the language automatically generate an overload for both cases where applicable, though you'd probably want an additional attribute or keyword for that.

**Comment by pengweiqhca** [comment]
I want CanBeNull generic type, both value types and reference types.

**Comment by pengweiqhca** [comment]
Or can be add overload by where T : class and where T : struct

**Comment by hez2010** [comment]
I think compiling T? on a reference type to T is incomplete for C# type system, and it causes inconsistance between value type and reference type.

In my opinion T? should be always compiled to Nullable<T>. At least there should be an option for users to opt-in "strict nullable context".

**Comment by yaakov-h** [comment]
@hez2010 `Nullable<T>` is declared as `public struct Nullable<T> where T : struct`. It is impossible for `T` to be a reference type.

**Comment by hez2010** [comment]
@yaakov-h 
Hmmmmm.... why not add a `public class Nullable<T> where T : class` for nullable reference type?

**Comment by yaakov-h** [comment]
@hez2010 see also: https://github.com/dotnet/csharplang/issues/2361#issuecomment-476270839

**Comment by Joe4evr** [comment]
@hez2010 See *also* [the 4 year old decision that wrapper structs are a no-go](https://github.com/dotnet/roslyn/blob/106fe577615bc6c29271d2abb15e5d67771609c1/docs/designNotes/2015-03-10%2C17%20C%23%20Design%20Meeting.md):
> the most damning objection to the wrapper structs is probably the degree to which they would hamper interoperation between the different variations of a type. For instance, the conversion from `string!` to `string` and on to `string?` wouldn't be a reference conversion at runtime. Hence, `IEnumerable<string!>` wouldn't convert to `IEnumerable<string>`, despite covariance.

**Comment by hez2010** [comment]
I think what we really need is to separate types to nullable types and non-nullable types, but not the fake nullable type with a compile-time check. 

We can consider nullable types as Monads. 

The current nullable reference type implementation  only does compile-time check and the only benefit is to prevent nullable types' spread in your own codes, which didn't solve the actual problem. 

I think breaking changes are must for it, otherwise the nullable reference type won't play the role it deserves.

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/csharplang/issues/2194

**Comment by YairHalberstadt** [comment]
Closing as implemented in C# 9
