### ISSUE TITLE
Proposal: Allow ref local variable re-initialized

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#233]
When a ref local var is initialized, it can't refer to another location. This limitation is disappointing for me. I wish to remove this limit.
```C#
static void foo()
{
    int a=10, b=20;
    ref int r=ref a; //init
    ...... //do something
    ref r=ref b; //compile error!  So sad!
    ......
}

/*Sometimes we want to do like this*/
static ref int find(int n);
static void foo()
{
    ref int r;
    int i;
    for(i=0;i<10;i++)
    {
        ref r=ref find(i); //this should be allowed!
        ......  //do something with r
    }
}
```

**Comment by Thaina** [comment]
`ref var` should treat like `const` and cannot reinitialized. I love this limitation because it make a variable scope and proof that logic is not astray

For any other purpose that might come up. I prefer to have `ref iterator` and `anonymous local function`

**Comment by DavidArno** [comment]
@ygc369,

Just declare the variables where they're used and this problem goes away:
```cs
static ref int find(int n) => ...

static void foo()
{
    for (var i = 0; i < 10; i++)
    {
        ref var r= ref find(i);
        ......  //do something with r
    }
}
```

**Comment by Thaina** [comment]
Well actually I was convinced that this is required in some case

**First**, Iteration, as the OP was posted

```C#
ref FoundObject r;
for (var i = 0; i < 10; i++)
{
    r = ref find(i);
    ......  //do something with r
}
// use r of last found
```

Well, I would prefer local function for this case. But we don't have anonymous local function yet so it a bit dirty

```C#
ref FoundObject r = ref Do10GetLast();
// use r

ref FoundObject Do10GetLast()
{
    for (var i = 0; i < 10; i++)
    {
        ref var r = ref find(i);
        ......  //do something with r

        if(i == 9)
            return r;
    }

    throw new Exception();
}
```

I wish we could have anonymous local function

```C#
ref FoundObject r = exec { // just made up syntax
    for (var i = 0; i < 10; i++)
    {
        ref var r = ref find(i);
        ......  //do something with r

        if(i == 9)
            return r;
    }
};

// use r
```

**Second**, try/catch

```C#
ref FoundObject r;
try
{
     r = ref find(10);
}
catch
{
     r = ref find(0);
}
// use r
```

This would be solved with one line try/catch
```C#
ref var r = try ref find(10) catch ref find(0);
```
But this feature has no consensus yet

**Third**, actually any kind of block in general has the same problem. It need to be fixed one by one unless we agree with your proposal

For `if/else` case is easiest that we already have `?:`. But there are many vase we don't support one line like that. `try/catch` is one example

**Comment by DavidArno** [comment]
@Thaina,
 In all those cases, the code can be improved and, as a by-product, the need to change the reference held by a `ref var` can be avoided. For example, looping over ten items, performing an action on each, then taking the last item and performing more actions could be a code smell. So I'd refactor it to make it clearer what the code is doing, eg:
```cs
for (var i = 0; i < 9; i++)
{
    ref var r = ref find(i);
    DoSomethingWith(r);
}

ref var lastR = ref find(9);
DoSomethingWith(lastR);
DoSomethingElseWith(lastR);
```

However, the language team like their "C# is mutable by default" mantra, so I suspect this request will be implemented, and the "pit of failure" will be dug a little deeper...

**Comment by Thaina** [comment]
I like mutable data but I don't think it is the same thing as changing reference of variable, which I hate
