### ISSUE TITLE
Execution of future c# code in VS2017 March 2019 update

### ISSUE THREAD

**Issue by mcmikecreations** [dotnet/csharplang#2332]
This will be hard for me to explain since I'm just a student, but I'll do my best. When I run the application in debug mode with a lot of breakpoints, some code is executed ahead for some reason and some variables are set to values that break the application. If I click the "Disable all breakpoints" button, everything works OK. If I enable them all again, it starts to crash again.
I tried switching to Release Mode and continue to debug (although debug in release mode is reasonably limited), the program still works fine. Moreover, the code is executed ahead (and sets variables) during each "Step Over" or "Step Into" click, so if I had an int with an increment in like 10 lines of code ahead, its value would increase by 10 when I reach it. I can give code and record a video if necessary.

**Comment by jmarolf** [comment]
Thanks for this! I believe this belongs on the Visual Studio tooling repo for C#: https://github.com/dotnet/roslyn

**Comment by mcmikecreations** [comment]
> 
> 
> Thanks for this! I believe this belongs on the Visual Studio tooling repo for C#: https://github.com/dotnet/roslyn

Is there a way to transfer the issue or should I open a new one there?

**Comment by mcmikecreations** [comment]
If anyone comes across this, I opened an issue at the [dotnet/roslyn repo](https://github.com/dotnet/roslyn/issues/34019#issue-419714576).
