### ISSUE TITLE
Allow for Static Extensions

### ISSUE THREAD

**Issue by KitoCoding** [dotnet/csharplang#2334]
I am hoping to get rid of wrapper classes. I love the idea of extension classes but I cannot add an extension method to a static class. For example: I want extension methods for ConfigurationManager.  So when i try to add an extension method to a static class I get the error "'ConfigurationManager': static types cannot be used as parameters" for the following code.

```
public static class ConfigurationManagerExtensions
{
    public static void RunSettings(this ConfigurationManager cManager) { }
}
```

Doing this forces me to change my class to a wrapper class. 

```
public static class ConfigurationManagerWrapper
{
    public static void RunSettings() { }
}
```

so now instead of going using the following code:

`ConfigurationManager.RunSettings()`

Where ConfigurationManger is well known class used in the System.Configuration namespace. I now have to tell my developers to use the Wrapper class

`ConfigurationManagerWrapper.RunSettings()`

What is the purpose of not allowing this ability to make static extensions?  Id love to see them in a future update. I would find this extremely useful

**Comment by YairHalberstadt** [comment]
Would #1988 solve your issues?

**Comment by KitoCoding** [comment]
> Would #1988 solve your issues?

Its a similar issue, but there is no solution to that issue.

**Comment by YairHalberstadt** [comment]
Yes there is. It suggests that you should be allowed to just make your own class called ConfigurationManager and reference both directly.

**Comment by KitoCoding** [comment]
Thats a suggestion. Not a solution.

**Comment by HaloFour** [comment]
> Not a solution to the existing features.

There is no existing solution for the feature you're looking for.  That issue is a proposal to look into adding such a feature.  If you have a different idea as to how to implement such a proposal feel free to write one up.

> What is the purpose of not allowing this ability to make static extensions? Id love to see them in a future update.

The reason the syntax you attempted failed is because you can't declare a parameter or a variable of a `static` class.  It doesn't make any sense to.  Something like "static extension methods" would have to be a new feature that has to go through a separate design process.

**Comment by KitoCoding** [comment]
Yeah sorry I thought it was clear it was a feature suggestion. I guess I forgot to add the tag. I understand there's not a current solution

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by YairHalberstadt** [comment]
But the feature suggestion as is makes no sense syntactically. Adding a parameter of a static type is meaningless.

It will have to be reworked syntactically, at it which point I imagine it will look something like #1988.

**Comment by KitoCoding** [comment]
Yes, and im sure your suggestion works theoretically, but its not a solution. Which is why i said your proposed solution is just that, a proposal, not a solution.

**Comment by HaloFour** [comment]
This will likely fall out naturally from the discussion/proposal around "extension everything" which aims to expand on extension methods to support other members, both static and instance, and possibly even interface implementations:

https://github.com/dotnet/csharplang/issues/192
https://github.com/dotnet/roslyn/issues/11159
https://github.com/dotnet/csharplang/issues/1711

**Comment by juliusfriedman** [comment]
But can't you write a more conventional static method and just drop the this?

Yeah you won't get intellisense on that type (Configuration manager) but you will get it from the namespace where the static function is imported... E g. ConfigurationManagerHelper...

Optionally use composition to make a class which gets a ConfigurationManager and add you methods to that class.

**Comment by YairHalberstadt** [comment]
Unfortunately I can't move this issue to a discussion due to a Github bug.

I'll close it instead as I think this area is suitably covered by https://github.com/dotnet/csharplang/issues/192 and #1711

If you wnat to discuss this more, feel free to open a new discussion and link this issue.
