### ISSUE TITLE
Choose type instead of namespace when applicable

### ISSUE THREAD

**Issue by andre-ss6** [dotnet/csharplang#2336]
Today if you have: 

```csharp
namespace Company.Models {
  public class Foo {  }
}

namespace Company.Foo {
  public class Bar {
    Bar() { var x = new List<Foo>(); }
  }
}
```

The compiler will give you an error saying that Foo is a namespace, but used like a type.  I suggest making the compiler able to understand that, since a namespace cannot be used as a type parameter, the type should be chosen.

I may be overlooking some things, but I guess that this could also apply to most, if not all, other situations like this. Some seem especially tricky, like `Foo.Do()` (which could also apply, since this is syntax for method invocation and there can be no methods declared in namespaces). We could, however, do this for the most obvious - and most common - cases at least, like the aforementioned example.

**Comment by HaloFour** [comment]
This works fine:

```cs
namespace Company.Models {
  public class Foo {  }
}

namespace Company.Foo {
    using Company.Models;
    using System.Collections.Generic;
  public class Bar {
    Bar() { var x = new List<Foo>(); }
  }
}
```

**Comment by andre-ss6** [comment]
Oooh, I didn't know that! And I kept asking myself for a long time "How come they have no solution for this yet?!" Hahaha! Learning every day! I'll try it out on work tomorrow. Thanks!
