### ISSUE TITLE
String interpolation should use implicit casts before resorting to ToString

### ISSUE THREAD

**Issue by xxbiohazrdxx** [dotnet/csharplang#2338]
Let's say we have a class, TestObject. That object has an implicit string operator to cast the object to a string.

```
public class TestObject
{
	private string Value;

	public TestObject(string TestValue)
	{
		Value = TestValue;
	}

	public static implicit operator string(TestObject object)
	{
		return Value;
	}
}
```

If I were to call an method that expects a string, let's say

```
var Test = new TestObject("Hello World!");
File.WriteAllLines("output.txt", Test);
```

And open output.txt, I would see the expected output:
`Hello World!`

However. If I use string interpolation:

```
var Test = new TestObject("Hello World!");
File.WriteAllLines("output.txt", $"Interpolated {Test}");
```

I would expect the text in output.txt to be the following:
`Interpolated Hello World!`

Instead, what happens is the string interpolation uses the `ToString` method. Since I have not overridden `ToString` on `TestObject`, it is called on the base class `Object` which returns the name of the class. Opening output.txt you will see:
`Interpolated TestObject`

**Comment by HaloFour** [comment]
This would be a breaking change.

**Comment by YairHalberstadt** [comment]
I don't see why you would add an implicit operator without overriding tostring

Besides, I think this is a library issue, not a language one.

**Comment by xxbiohazrdxx** [comment]
Well I put it there first and they said to bring it over to the csharplang repo because it was a language issue. Honestly it probably spans multiple repos.

**Comment by YairHalberstadt** [comment]
😂
It not on purpose, honest!
Can you link the issue please?

**Comment by HaloFour** [comment]
It's sort of a combination.  In these cases string interpolation is really just syntax candy for `String.Format`, which itself doesn't understand implicit conversions (as every argument it gets is an `object`).  You could argue that interpolation should do something different, but that would almost definitely cause breaking changes to existing code.

**Comment by tannergooding** [comment]
I instructed the issue to be moved off CoreFX as it is not something the library can impact (https://github.com/dotnet/corefx/issues/36011).

I believe @YairHalberstadt, however, is stating that this is an issue with the `TestObject` type, in that it implements an implicit cast but does not override `ToString`.

**Comment by YairHalberstadt** [comment]
I was arguing that `string.Format` would have to change, which is a library method

**Comment by tannergooding** [comment]
> I was arguing that string.Format would have to change, which is a library method

That can't/won't happen. `string.Format` would only be able to support implicit casts via reflection and that will basically make it a non-starter.

That makes the request for implicit conversion to be supported a language feature. But that likely won't happen due to back-compat concerns (these also exist for changing `string.Format`).

The real underlying issue here, however, is that you have a library that provides an implicit cast to `string` but that you do not also override `ToString` (which will also impact things like the debugger and basically every other library call that relies on `ToString`).

**Comment by xxbiohazrdxx** [comment]
I was aware that string interpolation was syntactic sugar for `string.Format()` but I thought this worked there. It does not.

So really, as long as the behavior is consistent, I'd agree that it would be hard to argue for a brekaing change.

**Comment by YairHalberstadt** [comment]
Do you want to close this issue in that case?

**Comment by juliusfriedman** [comment]
This can be achieved already with conditional formatting in the template or an overloaded call which selects the correct template?

**Comment by YairHalberstadt** [comment]
Closing as the suggestion here would be a breaking change, and unfortunately due to a bug with github I can't move to a discussion.

If you would like to discuss this more, please open a new discussion and link this.
