### ISSUE TITLE
Nullable Reference Types where are the Annotation attributes?

### ISSUE THREAD

**Issue by FutureTD** [dotnet/csharplang#2350]
Reading the Nullable reference types page I see this:

Annotation attributes
The following attributes are recognized and affect nullability analysis:

[AssertsTrue] (illustrated by Debug.Assert)
[AssertsFalse] (illustrated by Assert.False in test frameworks)
[EnsuresNotNull] (for a parameter of a method that throws if that parameter is null)
[NotNullWhenTrue] (useful for the out parameter in TryGetValue methods)
[NotNullWhenFalse] (illustrated by string.IsNullOrEmpty)

I am using the latest Visual Studio 2019 RC, were these annotations removed or changed to something else because I can not find them anywhere.

**Comment by yaakov-h** [comment]
You have to define those attributes yourself in the correct namespace. They are not part of the BCL yet.

**Comment by FutureTD** [comment]
Oh ok, so I just need to create those attributes myself and It will be used by the nullability analysis?

**Comment by YairHalberstadt** [comment]
Yep
