### ISSUE TITLE
Add an "unless" keyword

### ISSUE THREAD

**Issue by crmckenzie** [dotnet/csharplang#2352]
Ruby has some nice syntax that appears easy to add to C#. Others have already suggested adding the trailing `if` statement:

```csharp
return result if value > 0;
```

Likewise, ruby as the `unless` keyword which is similarly useful.

```csharp
return x/y unless y == 0;
throw new DivideByZeroException();
```

I'd love to see both the trailing `if` and `unless` statements added to the language. Of course, `continue,` `yield,` and `break` should also support this trailing conditional syntax.

**Comment by HaloFour** [comment]
```cs
if (value > 0) return result;
```

and

```cs
if (y == 0) throw new DivideByZeroException();
return x/y;
```

There's really no reason to add all new syntax just to reverse the order of the clauses.  And given that the condition is the most important aspect of the statement it doesn't make a lot of sense to try to hide it at the end.

**Comment by yaakov-h** [comment]
Related to #560.

**Comment by DavidArno** [comment]
Re the second example,
```cs
return y != 0 ? x/y : throw new DivideByZeroException();
```
Why complicate things by adding yet another keyword and spreading the expression over two lines?

**Comment by dsaf** [comment]
This is not going to be done:

1) Potentially introduces a whole new keyword for such a minuscule use case.
2) Introduces some new bracket-less condition syntax.
3) Introduces some new syntax with reverse order of condition vs outcome.

**Comment by jnm2** [comment]
This is a repeat of previous conversations.

Trailing `if`: https://github.com/dotnet/csharplang/issues/724.

Very similar: https://github.com/dotnet/csharplang/issues/325, https://github.com/dotnet/csharplang/issues/453, https://github.com/dotnet/csharplang/issues/1493, https://github.com/dotnet/csharplang/issues/1785, https://github.com/dotnet/csharplang/issues/2261.

**Comment by willard720** [comment]
You're a verison of the code is much more confusing than the way we currently have it. I feel like I have to solve a riddle to figure out what it means. Also, you're hidng the most important part of the conditional - the condition - just to sound more native.

**Comment by vbcodec** [comment]
this proposal boils down to removing excessive amount of braces

**Comment by crmckenzie** [comment]
Having worked in Ruby for a year or so, I found the above syntax to be much more expressive in certain contexts. I certainly didn't use it everywhere, and like anything else it can be misused. It would be syntactic sugar in the same way that `foreach` and `using` are.

**Comment by svick** [comment]
> It would be syntactic sugar in the same way that `foreach` and `using` are.

Both `foreach` and `using` significantly simplify code. Trailing `if` only rearranges it.

**Comment by crmckenzie** [comment]
My opinion is that in many contexts trailing conditionals dramatically aid expressiveness. I spend much of my time rearranging code to make it more expressive and I miss having this tool--much the way I miss having LINQ when working in other languages.

**Comment by Mteheran** [comment]
another way to do the same thing.

**Comment by juliusfriedman** [comment]
I think you meant to post this in https://github.com/dotnet/vblang

**Comment by YairHalberstadt** [comment]
Closing as due to a github bug I cannot move to a discussion, and this proposal received very little support. Feel free to open a new discussion and reference this issue if you want to discuss this more.

**Comment by mattiasnordqvist** [comment]
Just strolling around github post-C#9-release reading "There's really no reason to add all new syntax just to ....".
