### ISSUE TITLE
[Typo] Typo in spec/introduction.md - Upper case 'X' should be lower case 'x'

### ISSUE THREAD

**Issue by Timothy-Liu** [dotnet/csharplang#2353]
In spec/introduction.md, the table of operators. The row of **Null coalescing**, **X ?? y** should be **x ?? y**.

**Comment by Logerfo** [comment]
Do you want to send a pull request fixing it? The team is usually open to that.

**Comment by BillWagner** [comment]
Closing as this chapter was removed from the standard by the ECMA commitee in C# 5.0
