### ISSUE TITLE
[feature request] method override-when

### ISSUE THREAD

**Issue by enihcam** [dotnet/csharplang#2354]
An example explains everything.

**Current syntax:**
```
public override Task<IResourceEntity> InsertResourceAsync(TraceContext traceContext, IResourceEntity resourceEntity)
{
    if (resourceEntity.ProvisioningState != ProvisioningState.Creating)
    {
        return base.InsertResourceAsync(traceContext, resourceEntity);
    }

    //OVERRIDDEN BEHAVIOR HERE
}
```

**Expected syntax:**
```
public override Task<IResourceEntity> InsertResourceAsync(TraceContext traceContext, IResourceEntity resourceEntity)
        when (resourceEntity.ProvisioningState == ProvisioningState.Creating)
{
    //OVERRIDDEN BEHAVIOR HERE
}
```

**Comment by YairHalberstadt** [comment]
You've already given a perfectly valid alternative to your suggested new syntax. What is wrong with the alternative that you require some new syntax?

**Comment by Opiumtm** [comment]
@YairHalberstadt 

>You've already given a perfectly valid alternative to your suggested new syntax. What is wrong with the alternative that you require some new syntax?

Less boilerplate, I guess.
But proposed feature doesn't look clean and won't make code more readable.

**Comment by enihcam** [comment]
@YairHalberstadt @Opiumtm
I assume the new syntax is for validating before entering a method, whereas the old one takes place from inside of the method. Entering the method could introduce extra overheads (e.g. context switch, extra stack frame, triggering some other constructors/lazy methods)

**Comment by YairHalberstadt** [comment]
@Enihcam
Avoiding entering the method would require changes to the CLR. That's not going to happen.

**Comment by YairHalberstadt** [comment]
> triggering some other constructors/lazy methods)

How would entering a method do that?

> extra stack frame

The guard would probably also require an extra stack frame. It can't be inlined since it is virtual.

> context switch
How so?

**Comment by enihcam** [comment]
@YairHalberstadt think about copy constructors.

**Comment by YairHalberstadt** [comment]
C# does not have copy constructors

**Comment by enihcam** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-write-a-copy-constructor, but sorry what i mean is pass-by-value, i.e. a [struct](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/).

**Comment by YairHalberstadt** [comment]
If your struct is large enough that you want to avoid risking a copy, pass by ref.

**Comment by YairHalberstadt** [comment]
Also, Pass by Value is a trivial memCopy. It cannot trigger any function calls. It is highly highly likely that the cost of the abstraction required to add a guard to a method will be an order of magnitude greater than the cost of copying the struct.

**Comment by enihcam** [comment]
let's not mix the scenarios together. memcopy is already a cost.

I cannot enumerate every single scenario for you, but i believe there are many.
and i believe many of them have alternatives.

I agree that many language features are optional. if you are uncomfortable with one of them, what you can do is to find anther one, not to ask other devs to not to use it. right?

**Comment by HaloFour** [comment]
A similar subject was raised about the idea of including patterns in method signatures and the LDM stated that they were not interested in such things being embedded in the signature.

This is a solved problem and the proposed syntax is marginally less verbose than the existing syntax.  Any further benefits would require CLR changes, which has an excessively high bar, and is very unlikely to be considered.

**Comment by enihcam** [comment]
Good to know it's a CLR change. well, you can close it.
