### ISSUE TITLE
README's say "C# 6.0" in many places

### ISSUE THREAD

**Issue by bdrelling** [dotnet/csharplang#2360]
Examples:

https://github.com/dotnet/csharplang/blob/master/README.md
>Full C# 6 language specification (draft) in the spec folder

https://github.com/dotnet/csharplang/blob/master/spec/README.md
>Version 6
>This is an unofficial draft, posted here for convenience. When we submit a C# 6.0 spec proposal to ECMA (who is currently finalizing the C# 5.0 Standard), it will be shared here.

**Comment by YairHalberstadt** [comment]
That is because it is correct. There is no C# 7 spec.

**Comment by bdrelling** [comment]
Well then... I guess that makes sense then!
