### ISSUE TITLE
Add detailed message to NullPointerException describing what is null

### ISSUE THREAD

**Issue by albertmata** [dotnet/csharplang#2365]
This will save huge amount of time while debugging.

Please see document discussing same proposal in Java language.
https://openjdk.java.net/jeps/8220715

**Comment by yaakov-h** [comment]
This is an issue for the runtime, not the language.

As it stands, this has already been solved. The runtime does not provide the application with a string containing the original source code to explain what is null, but the debugger system pieces it together.

https://github.com/dotnet/coreclr/issues/25

**Comment by HaloFour** [comment]
[Some variation](https://bugs.openjdk.java.net/browse/JDK-4834738) of that JEP has been proposed for more than 15 years.  It's never been accepted and it's considered a potential security vulnerability that will expose details of the underlying program.

**Comment by BhaaLseN** [comment]
Besides, if you're _actually_ debugging, you'd be seeing this (Visual Studio 2017 and later):
![NullReferenceException detail in Visual Studio 2017](https://user-images.githubusercontent.com/826052/55095742-f10ee300-50b8-11e9-9f77-c1df82342b23.png)

**Comment by albertmata** [comment]
Yes I know, this is not the scenario. It would be useful when you only have
the stacktrace of the error, when the error happens in a production
environment or you don't have the data or the steps to reproduce it.

I understand the security implications, but as the Java request says, other
exceptions can disclose variable names, i.e. ArgumentNullException.

**Comment by HaloFour** [comment]
@albertmata 

> I understand the security implications, but as the Java request says, other
exceptions can disclose variable names, i.e. ArgumentNullException.

Only if the code is very explicitly written to do so.  The language doesn't automatically populate the argument name.

**Comment by softlion** [comment]
> " It's never been accepted and it's considered a potential security vulnerability"

Not in debug mode. No more insecure than standard C# that you can disassemble to source code in 2 seconds.

**Comment by HaloFour** [comment]
@softlion 

> Not in debug mode. No more insecure than standard C# that you can disassemble to source code in 2 seconds.

And I'd suggest that it's also not a good idea to embed the IL of the assembly in the exception message either.  Exceptions, particularly exception messages, are broadcast to a much wider audience than has access to the assembly.

**Comment by yaakov-h** [comment]
like the Yellow Screen of Death in IIS.

**Comment by gafter** [comment]
There is no `NullPointerException` in .NET.

**Comment by YairHalberstadt** [comment]
Closing as this would have to be done by the runtime
