### ISSUE TITLE
c# 8.0 NullableContextOptions not working with calling methods

### ISSUE THREAD

**Issue by Yuzlol** [dotnet/csharplang#2366]
With my current project i worked the first time with C# 8.0 and the "NullableContextOptions" enabled.
It seems like the compiler doesnt recognize my null-checks if i call them with a method or a guardclass.
Example :

        public void checkNull(AccountDto? accDto)
        {
            if (accDto == null)
                throw new Exception();
        }

        public Account(AccountDto? accDto)
        {
            // NullCheck with method
            checkNull(accDto);
            this.Id = accDto.Id; //compiler warning

            // Inline NullCheck
            if (accDto == null)
                throw new Exception();
            this.Id = accDto.Id;   // No Warning / Working
         

My current solution is to use the null-forgiving operator:

            this.Id = accDto!.Id;

Why does it not recognize my null check?

**Comment by ufcpp** [comment]
See Annotation attributes section in https://github.com/dotnet/csharplang/wiki/Nullable-Reference-Types-Preview
