### ISSUE TITLE
Official release C# 7.0

### ISSUE THREAD

**Issue by GerjanOnline** [dotnet/csharplang#237]
I am a bit confused, Is C# 7.0 officially released or not? Is it shipped together with Visual Studio 2017?

Only [this](https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/) post mentions:

> New versions of the .NET Languages are included in Visual Studio. You can now use C# 7, Visual Basic 15 and F# 4.1. C# 7 is already supported with .NET Core (just by using the latest Roslyn!). 

But that links to a [post](https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/) of August 2016. I would expect some more ceremony around it and an official blog post, right?

PS: I am not sure this is the right repo, sorry if this is the case

**Comment by GerjanOnline** [comment]
I have found: https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md#c-70-and-vb-15

All have state "Finishing", so it will be released soon?

**Comment by DavidArno** [comment]
I think that @MadsTorgersen and the team have been up to their eyeballs in preparing for VS2017 and in publicising what's new in C# 7. And this repo was created in a hurry after a lot of pushback from the community over their email list plans. They all likely now need a bit of a break.

So I'm guessing that we should see more team involvement here shortly, such as updates to this and the Roslyn repo, along with more engagement from them, in a week or two.

**Comment by dman2306** [comment]
The VS2017 release notes at https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes state:

> C# and Visual Basic - Extends support for new C# 7.0 and Visual Basic 15 language features, and introduces new refactorings that allow you to organize source code with one action.

**Comment by GerjanOnline** [comment]
Hm yes, this seems the best coverage so far:

https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#a-idcsharpvb-ac-and-visual-basic

**Comment by mpawelski** [comment]
Yep, seems that there is no nice blog/msdn page describing current state on new features. For example the link @GerjanOnline gave has reference to old patternMatching roslyn page without mentioning that wildcard character changed to `_` from `*`

**Comment by GerjanOnline** [comment]
Nice discovery @mpawelski 

But like you said, I still expect a blog post that can be upvoted on Hackernews / Reddit 😈

**Comment by gafter** [comment]
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes

**Comment by MgSam** [comment]
@gafter Talk about understated announcements!

**Comment by Sebazzz** [comment]
It appears the `Microsoft.Net.Compilers` and `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` packages need to be updated as well to support the new C# features.

**Comment by MgSam** [comment]
Good point. I thought `ValueTuple` was moving into the BCL so that you didn't need to go get a NuGet package just to start writing C#. Seems a pretty lousy state to be in for the RTM.

**Comment by dman2306** [comment]
@MgSam 
It will be but according to https://github.com/dotnet/roslyn/issues/13177 it will "ship in the first version after 4.7" which seems like a long time to wait... I'm sure they have their reasons, but I'd love to know why that is a good decision.

**Comment by GerjanOnline** [comment]
For completeness, here are the videos related to C# 7:

New Features in C# 7.0, by @MadsTorgersen
https://channel9.msdn.com/Events/Visual-Studio/Visual-Studio-2017-Launch/T130

.NET Productivity Improvements, by @kuhlenh 
https://channel9.msdn.com/Events/Visual-Studio/Visual-Studio-2017-Launch/T102

Exploring C# Productivity in Visual Studio 2017, by @MadsTorgersen and @kuhlenh 
https://channel9.msdn.com/Events/Visual-Studio/Visual-Studio-2017-Launch/140

**Comment by GerjanOnline** [comment]
Here it is:

https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/

Thanks @MadsTorgersen

**Comment by BillWagner** [comment]
There's also this on the .NET documentation set:

https://docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-7

**Comment by GerjanOnline** [comment]
Hackernews: https://news.ycombinator.com/item?id=13834511
