### ISSUE TITLE
C# 8.0 Bug: NRTs can cause ambiguous explicit interface implementations

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#2370]
Consider the following code:

```C#
#nullable enable
interface I
{
    void Foo<T>(T? value) where T : class;
    void Foo<T>(T? value) where T : struct;
}

class C2 : I
{
    void I.Foo<T>(T? value) { }
}
```

`void I.Foo<T>(T? value) { }` is a valid implementation of both interface members. There is currently no way of disambiguating which one it implements.

The current behavior of the compiler is to assume that it implements the first method declared by the interface. Thus this compiles:

```csharp
#nullable enable
interface I
{
    void Foo<T>(T? value) where T : class;
    void Foo<T>(T? value) where T : struct;
}

class C2 : I
{
    void I.Foo<T>(T? value) { }
    public void Foo<T>(T? value) where T : struct {}
}
``` 

but this doesn't:

```csharp
#nullable enable
interface I
{
    void Foo<T>(T? value) where T : struct;
    void Foo<T>(T? value) where T : class;
}

class C2 : I
{
    void I.Foo<T>(T? value) { }
    public void Foo<T>(T? value) where T : struct {}
}
```

This is obviously nonsensical.

See https://github.com/dotnet/roslyn/issues/34508

**Comment by YairHalberstadt** [comment]
@gafter, @jcouv, I believe you are both working on NRTs?

**Comment by jcouv** [comment]
Thanks for reporting this. We're looking into it.

**Comment by yaakov-h** [comment]
Why does the explicit implementation get to omit the generic constraints?

**Comment by YairHalberstadt** [comment]
@jcouv
By way I am currently implementing a fix for dotnet/roslyn#34508, so once the correct behaviour is decided, I am happy to include that in the fix.

**Comment by YairHalberstadt** [comment]
As I see it, there are two valid outlooks.

1. This is an error, as it is ambiguous which of the two methods it implements.

2. The following currently compiles in C# 7:

```csharp
interface I
{
    void Foo<T>([nullable] T value) where T : class;
    void Foo<T>(T? value) where T : struct;
}

class C2 : I
{
    void I.Foo<T>(T? value) { }
}
```

Part of the principal of NRTs is that they don't affect overload resolution. So you should be able to change that program to:

```csharp
#nullable enable
interface I
{
    void Foo<T>(T? value) where T : struct;
    void Foo<T>(T? value) where T : class;
}

class C2 : I
{
    void I.Foo<T>(T? value) { }
    public void Foo<T>(T? value) where T : struct {}
}
```

And the program should compile and run exactly the same as before.

This would mean that in the case of an ambiguity, we should remove all nullability annotations, and select the one that would have been selected in C# 7.

**Comment by yaakov-h** [comment]
(2) doesn't compile in C# 7, it results in `error CS0535: 'C2' does not implement interface member 'I.Foo<T>(T)'`.

**Comment by YairHalberstadt** [comment]
```csharp
interface I
{
    void Foo<T>([nullable] T value) where T : class;
    void Foo<T>(T? value) where T : struct;
}

class C2 : I
{
    public void Foo<T>(T value){}
    void I.Foo<T>(T? value) { }
}

```

This compiles.

**Comment by YairHalberstadt** [comment]
As a point of reference, this compiles fine pre C# 8:

```csharp
public interface Interface<T>
{
    void Method<V>(int i) where V : new();
    void Method<V>(T i);
}

public class Class : Interface<int>
{
    void Interface<int>.Method<V>(int i) { var x  = new V(); } //this explicitly implements both methods in Interface<int>
    public void Method<V>(int i) { } //this is here to avoid CS0535 - not implementing interface method
}
```

but produces a warning:

> warning CS0473: Explicit interface implementation 'Class.Interface<int>.Method<V>(int)' matches more than one interface member. Which interface member is actually chosen is implementation-dependent. Consider using a non-explicit implementation instead.

However when you switch around the order in which the interface members are declared it fails to compile:

```csharp
public interface Interface<T>
{
    void Method<V>(T i);
    void Method<V>(int i) where V : new();
}

public class Class : Interface<int>
{
    void Interface<int>.Method<V>(int i) { var x  = new V(); } //this explicitly implements both methods in Interface<int>
    public void Method<V>(int i) { } //this is here to avoid CS0535 - not implementing interface method
}
```

Given that that is the case, I think the correct thing to do is to either produce a warning here as well, and have 'implementation defined behavior', or to say that if any C# 8.0 features are used, we should produce an error, as it is safe to so, and in a case like this an error is probably better than arbitrary implementation defined behavior.

**Comment by YairHalberstadt** [comment]
Closing as fixed
