### ISSUE TITLE
[Missing] In introducton.md -> Classes and objects

### ISSUE THREAD

**Issue by Timothy-Liu** [dotnet/csharplang#2371]
[Missing] In introducton.md -> Classes and objects -> The two-line code after the paragraph starts with "Instances of classes are created using the `new` operator, ..." -> **csharp** coding style is missing.

**Comment by Unknown6656** [comment]
I proposed a change:
https://github.com/Unknown6656/csharplang/commit/379747044fcec2441ba332462b9751629d3e1f1e

**Comment by svick** [comment]
@Unknown6656 Is seems you have not created a Pull Request with that change. Is that intentional?

**Comment by Unknown6656** [comment]
@svick : Thank you for your notice ... no, that was indeed unintentional.

**Comment by YairHalberstadt** [comment]
Closing as fices in #2371
