### ISSUE TITLE
Please look again at xoofx's suggestions

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#238]
Most of his suggestions are very good and reasonable, especially these below:
1. from http://xoofx.com/blog/2015/10/08/stackalloc-for-class-with-roslyn-and-coreclr/
> 1. Allocation on the stack of reference types (the subject of this post)
> 2. Embedded allocation of a reference type within another reference type (fat type)
> 3. Single Owner/Borrowed reference

2. from http://xoofx.com/blog/2017/01/17/the-stark-programming-language-experiment/
> ......There will be also a single ownership allocation that will allow allocate on the heap but without having the GC to track these references (would be tracked by single ownership and destruction on last owner disposed)......

**Comment by ygc369** [comment]
@xoofx
Here are some of my ideas, which I think worth considering:
1. Optimization for LOH GC: https://github.com/dotnet/coreclr/issues/555
2. Optimization about generation GC: https://github.com/dotnet/coreclr/issues/1856 and https://github.com/dotnet/coreclr/issues/1855
3. If stack-alloc-for-class is implemented and a stack-allocated object has finalizer, then its finalizer should be executed once its last reference goes out of scope, not need wait until GC finishes.

**Comment by jnm2** [comment]
Fyi, work has started on stack-allocated objects. https://github.com/dotnet/coreclr/pull/20251
