### ISSUE TITLE
Will MS create a new language, or continue to extand C#?

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#239]
According to  Joe Duffy's blog(http://joeduffyblog.com/2013/12/27/csharp-for-systems-programming/), MS seems to be developing a new language based on C#. Will this come ture? Or will MS merge the features of the "new" language into C#? If so, when?

**Comment by yaakov-h** [comment]
This sounds like [Midori](http://joeduffyblog.com/2015/11/03/blogging-about-midori/), which was eventually scrapped.

**Comment by Thaina** [comment]
Quite sure that if it not distinct enough from C# it will be adopted as language feature

But if there is breaking change feature they would consider make new language

**Comment by fanoI** [comment]
In my opinion M# could yet have a space a part for Midori and I don't think that all what they did for Midore could be moved into C# without changing too much is nature:

1.  Objects was declared into the stack and only in rare case in the heap with RIAA and all as C++!
2.  More easy to get access to low level thing (pointers as first citizen?)
3.  Possibility as C++/CLI to generate unverifiable code

In some sense one could call M# "C++/CLI without C"...

**Comment by orthoxerox** [comment]
I can think of only two cases where a company created a new language and tried hard to make everyone switch to it.

1. Objective-C to Swift. Objective-C was 30 years old when Swift was announced and they were reasonably different.
2. VB to VB.Net. VB 1.0 was released in 1991 and replacing it with VB.Net 11 years later was a failure. 15 years later, VB6/VBA is still alive and kicking.

I feel that Microsoft is not going to replace C# with some kind of C#++ as their preferred general purpose programming language with fewer warts in the nearest 10 years or so. They are not going to repeat the VB mistake.

**Comment by ygc369** [comment]
Even though MS doesn't want replace C# with M#, it should make M# public at least, and let visual studio vNext support M#.

**Comment by HaloFour** [comment]
@ygc369 

MS has made probably a dozen other C#-spinoff languages in the past, mostly using C# as the basis for testing other programming theory.  Off of the top of my head I can think of Axum, Polyphonic C#, X# and Cω.  The good ideas are often distilled and integrated into C# proper.  I'd severely doubt that MS would expend the effort to mature any of those projects further to the point where it would be suitable for commercial use.  That's a large liability in terms of development and support.  It was a pretty big deal that this happened with F#.

**Comment by AlgorithmsAreCool** [comment]
From what I've read one of the key successes for Midori/M# was aggressive iteration. They added a feature, tested it and if it didn't work out, they removed it. 

Now that C# has picked up great features from a lot of these research languages, I wish that we could reset and redefine C# based on the modern set of desirable features now that we know what works well. We could simplify a lot of language constructs, shrink the compiler and prevent C# turning into C++ with layer after layer of deprecated/old syntax.

**Comment by MgSam** [comment]
@AlgorithmsAreCool They could do this if they were willing to make breaking changes where it makes sense and use analyzers to attempt to upgrade legacy code to the new language version (a la Swift). The team has even floated this idea several times before, though it's not clear to me why it keeps getting rejected.

**Comment by AlgorithmsAreCool** [comment]
@MgSam Go did something similar with GoFix

**Comment by jnm2** [comment]
> Go did something similar with GoFix

Scalable naming strategy, that 😆

**Comment by fanoI** [comment]
My idea is that an eventual M# would not replace C# as F# does not replaced anything, M# could take the role of C++/CLI but without the weird syntax inherited from C/C++.

**Comment by ygc369** [comment]
@fanoI 
I agree with you.
I hope MS to make M# public, thus we would have F#/C#/M# at the same time, for different development.
F#: high-level
C#: mid-level
M#: low-level

**Comment by AlgorithmsAreCool** [comment]
I'm not sure that layering makes sense, C# is multi paradigm and 'competes' in the same space as F# for the most part. 

But I do think that a more M#/Rust like variant of C# would be very valuable. Performance oriented fiddly features could easily go there and not add even more complexity to C#.

**Comment by gulshan** [comment]
I proposed a big break in a future version C#. It should still be binary compatible with previous versions btw. It was here- https://github.com/dotnet/roslyn/issues/16103

**Comment by playsomethingsaxman** [comment]
C++ is in dire pain and needs to die. A non-GC offshoot of C# needs to become the new de-facto native language without the misery of header files and declaration order. Time is being lost on difficult development because the C++ committee solves everything but the actual problem.

**Comment by eyalsk** [comment]
@playsomethingsaxman You can say that on any language really, not sure why C++ is in dire pain? I'm following and using it and it works for me so what exactly are the actual problems? I mean I doubt that your own problems are everyone's problem. :)

Compilation time, header files and whatnot are problems but isn't the point of modules to make this more manageable?

**Comment by fanoI** [comment]
As old headers and C compatibility should always be present C++ will never be a safe language to use, modules will be only another thing added to a language that has already a giant syntax!

There is space for "safe native code":
http://joeduffyblog.com/2015/12/19/safe-native-code

**Comment by jcouv** [comment]
Here's the latest [.NET language strategy](https://blogs.msdn.microsoft.com/dotnet/?p=8925).

**Comment by ygc369** [comment]
@jcouv 
The article didn't answer the question: whether would MS make M# open?
