### ISSUE TITLE
Proposal: skip Task keyword with async methods

### ISSUE THREAD

**Issue by MelnikovIG** [dotnet/csharplang#2395]
I guess in 99% cases when we are using `async` we are assuming there is `Task` or `Task<T>` returned from method. What if we can skip using `Task` with `async` (make it as sytax sugar, it will be converted to `Task` like now)? There is some thoughts of new syntax:

- `async Task SomeTask(){...}`  -> 
`async SomeTask(){...}`
- `async Task<T> SomeTask(){...}`  -> 
`async T SomeTask(){...}`
- `async void SomeTask(){...}`  -> 
same as before
- `async ValueTask<T> SomeTask(){...}`  -> 
`asyncv T SomeTask(){...}` or  
`async value T SomeTask(){...}` or 
same as before
- `async YouTaskLikeType SomeTask(){...}`  -> 
same as before

I know maybe i missed some corner cases but i think u got my idea.

**Comment by HaloFour** [comment]
The team explicitly decided that `Task` or `Task<T>` should be a part of the method signature as that is what the method is actually returning.  I don't see that anything has changed that should result in that decision being changed.

Given that you'd still have to explicitly spell out an alternate task-like class, how would you differential between `MyTaskLike<T>` and `Task<MyTaskLike<T>>`?

**Comment by marksmeltzer** [comment]
He is probably referring to ValueTask<T> and its IValueTaskSource interface (or whatever it is called). That interface enables creating task-like reusable components to enable pooling scenarios, etc.

Regards,

________________________________

**Comment by MelnikovIG** [comment]
@HaloFour I see, thanks for example, it will be really confused and undefined.  But maybe additional keyword instead o async can solve this? Rough example is 'asyncw' (async with task wrapper). So we could use `asyncw T`  and `asyncw MyTaskLike<T>`. Just thoughts to reduce `async Task` everywhere.

**Comment by HaloFour** [comment]
@marksmeltzer 

He mentions it, yes, with a specific `value` keyword intended to refer to it.  Currently the C# has no concept of `ValueTask<T>`, it only relies on the recent changes that allow for custom types to be used in `async` methods.

@MelnikovIG 

I don't see why you'd want to reduce the incidence of the actual return types of methods.  `async` is not a part of the signature and doesn't affect the return type.

**Comment by marksmeltzer** [comment]
I agree that any keyword changes should not impact the actual return type in any way.

Async is an intent keyboard used to tell the compiler to generate a state machine. The return type is merely a type parameter on that state machine pattern implementation.

Regards,

________________________________

**Comment by yaakov-h** [comment]
This would be a breaking change.
