### ISSUE TITLE
Should proposals being added from the Roslyn repo follow the proposal template?

### ISSUE THREAD

**Issue by scottdorman** [dotnet/csharplang#24]
Should the proposals being pulled in from the Roslyn repo follow the new proposal template format? For example, the [Nullable Reference Types proposal](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md) doesn't really follow the template.

**Comment by gafter** [comment]
Yes, members of the LDM plan to follow the template as we integrate proposals into this repo.
