### ISSUE TITLE
Extension method call resolves to not-most-specific overload

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/csharplang#2405]
I'm not sure if this is intended behavior or a bug or just something that hasn't really come up before, but it definitely feels non-intuitive.

The intuitive behavior, in my mind, would be that a call to an extension method, with many in-scope overloads, resolves to the "most-specific" overload (based on the inheritance tree). There are two situiations in the following demo where this is not true.

1. [One overload is within a shared namespace, and one is not](https://github.com/JakenVeina/ExtensionMethodResolutionTest/blob/732c98b2cdedce4e0a5d4d52395d46dd236892b9/ExtensionMethodResolutionTest/SubNamespace2/MyOtherClass.cs#L10)
In this case, two `.Abstract()` extension methods are available to call upon an instance of `MyClass`, one that takes a parameter of type `MyClass` and one that takes `IMyInterface` which is implemented by `MyClass`. Clearly, the one that takes `MyClass` is "most-specific" however the one that takes `IMyInterface` gets chosen, seemingly because it exists in a namespace (`BaseNamespace`) that is shared with the current namespace (`BaseNamespace.SubNamespace2`). Interestingly, moving the `using` statement for the namespace (`BaseNamespace.SubNamespace1`) that contains the other extension method, to the inside of the current `namespace` statement changes the resolution result, and the `MyClass` overload is called instead.

2. [Extension method call matches itself](https://github.com/JakenVeina/ExtensionMethodResolutionTest/blob/732c98b2cdedce4e0a5d4d52395d46dd236892b9/ExtensionMethodResolutionTest/Core/MyInterface.cs#L14)
In this case, the extension method I would like to call is, again, the "most-specific" one that takes `MyClass` rather than just `IMyInterface`. However, because the extension method itself is a candidate for the attempted call, it always takes precedence, resulting in infinite recursion. Unlike above, moving the `using` statement within the `namespace` statement does not change the resolution result.

**Comment by DavidArno** [comment]
By design, C# resolves overloads, including extension methods, primarily based on "namespace distance". [Eric Lippert wrote an excellent blog post explaining this a few years ago](https://ericlippert.com/2013/12/23/closer-is-better/). It's only if two methods are at the same "distance" that other rules around best fit for types come into play.

**Comment by JakenVeina** [comment]
Excellent, thank you. That definitely explains what I'm seeing.

I did some searching on docs.microsoft before posting this, and didn't find much in the way of "rules" for overload resolution. Did I perhaps just not search well enough, or is this more of an "unofficial rule"?

**Comment by gafter** [comment]
@JakenVeina The formal, technical rules are described in the C# language specification. See the section https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#extension-method-invocations specifically the part that begins

> The search for `C` proceeds as follows:
> 
> - Starting with the closest enclosing namespace declaration, continuing with each enclosing namespace declaration, and ending with the containing compilation unit, successive attempts are made to find a candidate set of extension methods:
