### ISSUE TITLE
NRT: Calling ImmutableArray.Create(object?) results in an ImmutableArray<object> instead of an ImmutableArray<object?>

### ISSUE THREAD

**Issue by Zenexer** [dotnet/csharplang#2407]
The following results in CS8619 because it is understood as `object ImmutableArray.Create<object>(object)` instead of `object? ImmutableArray.Create<object?>(object?)`:

``` cs
object? x = 1;
ImmutableArray<object?> y = ImmutableArray.Create(x);
```

The following workaround kind of works, but results in IDE0059:

``` cs
object? x = 1;
ImmutableArray<object?> y = ImmutableArray.Create<object?>(x);
```

This issue is particular problematic because this doesn't result in a nullability warning:

``` cs
object? x = null;
var y = ImmutableArray.Create(x);
object z = y[0];
```

This does, but it doesn't work for properties/fields because they don't support implicit types:

``` cs
object? x = null;
var y = ImmutableArray.Create<object?>(x);
object z = y[0];
```

Results in IDE0001:

``` cs
const object? Null = null;
ImmutableArray<object?> IDE0001 { get; } = ImmutableArray.Create<object?>(Null);
```

**Comment by Zenexer** [comment]
Seems like there are a few issues here:

* IDE0059 should be ruled out if the type parameter is forcing a different method signature to be used.
* The `ImmutableArray<object>` from `ImmutableArray.Create(object)` is considered to have a non-nullable type parameter in an NRT context, even though it was instantiated outside an NRT context (and is therefore nullable).
* It seems as though the same method signatures are used regardless of whether NRT is enabled--that is.

With the exception of the first issue, these seem like pretty significant design issues in NRT with no easy solution.

**Comment by svick** [comment]
What is `object ImmutableArray.Create(object)`? I don't see it in [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray.create?view=netcore-2.2).

**Comment by Zenexer** [comment]
@svick Actually, I think I misread something.  You're correct, there is no `ImmutableArray.Create(object)`.  I've misdiagnosed the issue, but the bug is still present.

**Comment by Zenexer** [comment]
@svick I've updated the issue to remove that error.

**Comment by Zenexer** [comment]
A generalization of the error is shown below.  It should work with a fresh project targeting netcoreapp3.0 and C# 8.0 with NRT enabled.

``` cs
class Example<T>
{
    public T Value { get; }

    public Example(T value) => Value = value;
}

class Test
{
    public static Example<T> Create<T>(T item) => new Example<T>(item);

    public static void CS8600()
    {
        object? x = null;
        var y = Create(x);
        object z = y.Value;  // CS8600 here
    }

    public static void CS8619()
    {
        object? x = 1;
        Example<object?> y = Create(x);  // CS8619 here
    }
}
```

**Comment by Zenexer** [comment]
Generalization of the issue attached: [Sandbox.zip](https://github.com/dotnet/csharplang/files/3056618/Sandbox.zip)

Here's the important part:

``` cs
class Example<T>
{
    public T Value { get; }

    public Example(T value) => Value = value;
}

class Test
{
    public static Example<T> Create<T>(T item) => new Example<T>(item);

    public static void CS8600()
    {
        object? x = null;
        var y = Create(x);
        object z = y.Value;  // CS8600
    }

    public static void CS8619()
    {
        object? x = 1;
        Example<object?> y = Create(x);  // CS8619
    }
}
```
