### ISSUE TITLE
Provide a way to determine the memory alignment of unmanaged structs

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#2408]
This is to discuss adding a capability for managed code to determine the memory alignment needs of any unmanaged struct. For certain interop scenarios we may need to allocate struct instances outside the AppDomain (for example in user heap accessible to other code, perhaps native code).

These "manually" allocated instances would be exposed to managed code as `ref `values.

However when the raw memory is allocated we must ensure that the (artificially generated) `ref `is aligned in the same way it would be aligned by the CLR so that these returned ref values are wholly compatible to managed code.

A struct containing just byte fields for example can be aligned more flexibly than a struct containing just double fields or decimal fields, in principle we could craft code to analyze the struct since we know the alignment needs of all primitives and the rules used by the CLR, but to future proof this more is needed, for example SIMD it seems can have stringent alignment needs..

**Comment by tannergooding** [comment]
This sounds like a request for a framework API supported by the runtime, rather than a language feature request.

**Comment by Korporal** [comment]
> This sounds like a request for a framework API supported by the runtime, rather than a language feature request.

Where would you submit this then Tanner?

Thx

**Comment by tannergooding** [comment]
`dotnet/corefx` most likely. The API review process is detailed here: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md#steps and the first step includes a "good example" for the template that the API review team likes seeing.

I imagine this would likely exist in `System.Runtime.InteropServices`, possibly as a `Marshal.AlignmentOf<T>()` method. You could also potentially foresee a `Unsafe.AlignmentOf<T>()` method (in `System.Runtime.CompilerServices`) that would give the managed alignment (which is not always the same since the GC doesn't provide support for 16-byte alignment today, as an example).

**Comment by Korporal** [comment]
@tannergooding - Thanks, this is helpful. I guess we could simply insist on alignments being 8 byte - period and that would be 100% compatible with the CLR - today?

**Comment by tannergooding** [comment]
> I guess we could simply insist on alignments being 8 byte - period and that would be 100% compatible with the CLR - today?

I believe so. But, I'm not an expert on the GC semantics or what future plans (if any) there are.

**Comment by PathogenDavid** [comment]
Related:

* https://github.com/dotnet/coreclr/issues/14388
* https://github.com/dotnet/corefx/issues/22790
* https://github.com/dotnet/coreclr/issues/5195

-------------

> However when the raw memory is allocated we must ensure that the (artificially generated) `ref` is aligned in the same way it would be aligned by the CLR so that these returned ref values are wholly compatible to managed code.

Do we? I don't think the CLR is particularly alignment-sensitive.

**Comment by johnkellyoxford** [comment]
@Korporal iirc on Windows x86/64 and on Linux x86/64 `malloc` will be *at least* 8 byte aligned anyway, so you should be fine if you are allocating it from there (I believe it will always be 8 byte aligned on 32 bit, 16 for 64 bit on both OS's). However, not the greatest solution. But no need for a custom allocator to get that alignment or anything unpleasant

**Comment by Korporal** [comment]
> @Korporal iirc on Windows x86/64 and on Linux x86/64 `malloc` will be _at least_ 8 byte aligned anyway, so you should be fine if you are allocating it from there (I believe it will always be 8 byte aligned on 32 bit, 16 for 64 bit on both OS's). However, not the greatest solution. But no need for a custom allocator to get that alignment or anything unpleasant

@johnkellyoxford - Hi John, yes you are correct but in our case we are not relying on any existing `malloc/free` or `Marshal.AllocHGlobal`  though these are fine for unit tests. We have our own algorithm and will also allow an alignment integer to be passed in to force align a returned address (ref).

For now our default is 8 byte alignment, the alignment of a .Net struct is (if I recall work I did years ago) the largest alignment of all embedded fields be they primitive fields or structs. I may have created a .Net utility to analyze a struct via reflection and determine the maximum field alignment, again I think this never > 8.

**Comment by Korporal** [comment]
> Related:
> 
> * [dotnet/coreclr#14388](https://github.com/dotnet/coreclr/issues/14388)
> * [dotnet/corefx#22790](https://github.com/dotnet/corefx/issues/22790)
> * [dotnet/coreclr#5195](https://github.com/dotnet/coreclr/issues/5195)
> 
> > However when the raw memory is allocated we must ensure that the (artificially generated) `ref` is aligned in the same way it would be aligned by the CLR so that these returned ref values are wholly compatible to managed code.
> 
> Do we? I don't think the CLR is particularly alignment-sensitive.

Well I can easily test that, I could align a struct that contains a double or decimal on say a 3 byte aligned address, but I've assumed this would lead to unexpected runtime behavior or crashes.

**Comment by Korporal** [comment]
I've moved this to here:

https://github.com/dotnet/corefx/issues/36792

**Comment by tannergooding** [comment]
@Korporal, could you close this issue since you've moved it to corefx (assuming you aren't intending to push this one further)?

**Comment by PathogenDavid** [comment]
Oh, I see what you're asking for now. You need to query the alignment, not specify it. I somehow saw both dots without connecting them.

I think you're likely to find that the CLR considers alignment of allocated objects to be an implementation detail and they don't want to commit to exposing it. Good luck either way!

**Comment by Korporal** [comment]
Closing this one because it's been moved now.
