### ISSUE TITLE
Proposal: Embedded allocation of a reference type within another reference type

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#241]
We can call this "inline". An inline class should act as a struct with same fields.
For example:
```C#
class A
{
    int a;
}

class B
{
    int b;
    inline A aa; 
}

/* The compiler should translate code above to code below */
class A
{
    int a;
}

class B
{
    int b;
    struct {
        int a;
    } aa; //pseudo-code of C style, just to show my idea. 
}
```

**Comment by orthoxerox** [comment]
1. What's the point of inlining classes beyond the base class?
2. Class A must be sealed, or its length at runtime will be indeterminate.

**Comment by benaadams** [comment]
struct will inline this way

create class and struct with same data and implement their methods via generic by ref extensions (https://github.com/dotnet/csharplang/issues/186) if they were also available on classes (readonly by ref extensions?)
