### ISSUE TITLE
Proposal: Moving CS8618 'Non-nullable field is uninitialized' to the construction place

### ISSUE THREAD

**Issue by alexk8** [dotnet/csharplang#2411]
```c#
class A{
  public string str; //warning: not initialized
}
```
This warning is something bad by design,
it fits badly into deserialization concept which is used everywhere! (json,EF,ORM,Mappers,etc)
I suggest that it's caller's responsibility to construct object properly,
I'd like to see something like this:
```c#

#nullable enable

class A{
  public string str; //do not warn (not initialized)!!! that' a lot of pain
}

void Main(){
  A a1 = new A(); //do warn: "str is not initialized"
  A a2 = new A{str="str"}; //ok
}
```
---------------
*** EDITED  ***
some other crazy ideas:
```c#
  A a3 = deserialize A(a => {
    //a.str = "str";
  }); //throws runtime error "str is not initialized"
```

**Comment by YairHalberstadt** [comment]
#2328

**Comment by Unknown6656** [comment]
_@alexk8 This has nothing to to with the proposal at all, however, I have to say, that your profile picture gave my sleep-depraved brain quite a start! good one!_
![image](https://user-images.githubusercontent.com/8807985/55900999-be8cdc00-5bc8-11e9-9008-0b447039ac14.png)

**Comment by Joe4evr** [comment]
> This warning is something bad by design

Only because the warning is in the wrong place. Proposing to fix that by putting a new keyword into the language like this has an absurdly high bar, whereas the linked proposal would solve the same problem at a much lower cost and that is more in-line with the design of NRTs.

**Comment by marksmeltzer** [comment]
I agree with @Joe4evr. The solutions proposed on #2328 are far more useful.

**Comment by alexk8** [comment]
> Only because the warning is in the wrong place. Proposing to fix that by putting a new keyword into the language like this has an absurdly high bar, whereas the linked proposal would solve the same problem at a much lower cost and that is more in-line with the design of NRTs.

Agree, but NRTs concept does introduce lots of new magic, doesn't it? Let's say that's separete, quite crazy proposal, but why not?  Of course "deserializaton" can be done totaly by reflection, The only thing I'd like to have is null-checks after weak runtime construction, in more optimal and strightforward way - compiler generated. This probably does not require keyword itself, some other magic may happen in compiletime, it needs only a hint to do that. Somebody may invent other way, I've just shown my general idea. 
[MustInitialize] from #2328 would be quite messy (used everywhere), this behaviour should be default by design IMHO

**Comment by alexk8** [comment]
However, I agree that this "deserialization" stuff is not really needed. The main problem is: 
> the warning is in the wrong place.

**Comment by alexk8** [comment]
closing this issue in favour of 2328

**Comment by alexk8** [comment]
I've decided to reopen the issue just to ask - Is it even possible to move the warning to the construction side, by default?

**Comment by alexk8** [comment]
Found more similar #2109
closing
