### ISSUE TITLE
shorthand syntax for ANDing of relational operators

### ISSUE THREAD

**Issue by MovGP0** [dotnet/csharplang#2412]
## Issue
I often write LINQ code that looks like the following: 

```csharp
from entry in Entries
where from <= entry.Date
where entry.Date <= till
select entry
```

A shorter version to write this would be:

```csharp
from entry in Entries
where from <= entry.Date && entry.Date <= till
select entry
```
However, it seems redundant to write that `entry.Date` multiple times. Especially since this is another change for the deveolper to make an error (albeit an small one). 

## Proposal

It should be possible to express the same relationship with the following code:

```csharp
from entry in Entries
where from <= entry.Date <= till
select entry
```

It should also be possible to use the `<` operator, which gives the following variants:

```csharp
where from <= entry.Date <= till
where from <= entry.Date < till
where from < entry.Date <= till
where from < entry.Date < till
```

This syntax should be intuitive for developers, since it is often used in elementary mathematics courses. 

The syntax should be expanded by the C# compiler. This way, there will be no need to change LINQ compilers and allows the syntax to be used in other control constructs as well: 

```csharp
if (from <= current <= till)
{
   // do something...
}
``` 

```csharp
while (from <= current <= till)
{
   // do something...
}
``` 

The syntax should work with every datatype, which implements the `<` or `<=` operator (or both). 

## Non-Goal

It might not be a good idea to have this syntax for other operatiors like `>`, `>=`, `==`, etc., since something like that might confuse the developer, because of the violation of the [left-is-less and right-is-more metaphor][1]. 

A similar confusion might be the SQL equivalent of writing 

```sql
WHERE entry.[Date] BETWEEN (@from, @till)
```

since this order also violates the intuitive left-is-less and right-is-more methaphor. 

## References

[1]: George Lakoff and Mark Johnson, Metaphors We Live By, 1980, ISBN 978-0226468013

**Comment by YairHalberstadt** [comment]
This would be a breaking change, as the following program would stop compiling:
```csharp
public class C {
    public bool M() {
        return 5 <= 10 <= new C();
    }
    
    public static bool operator <= (bool a, C b) => true;
    
    public static bool operator >= (bool a, C b) => false;
}
```

https://sharplab.io/#v2:D4AQzABCBMEMIQN4FgBQENUgIwPa4BsIBZACgEok1MaoB2CAVggB4BeCARgAZWOA7AKYB3eBQDc1TAF8pGOViicAbBDyEIuAA6CATgEMALrl18IpdUX0AaeGspsAfBEO6AroMnpMC8EtWWmjoGxqaOHBb4VrYI2A7OAGb6BADOnmjSQA

**Comment by RobotAL76** [comment]
@MovGP0 
As alternative you may encapsulate comparision logic into sets of extension methods

```c#
static bool IsInRange(this DateTime value, DateTime from, DateTime till) =>
        value > from && value < till;
    
static bool IsInLeftRange(this DateTime value, DateTime from, DateTime till) =>
        value >= from && value < till;
    
static bool IsInRightRange(this DateTime value, DateTime from, DateTime till) =>
        value > from && value <= till;
    
static bool IsInFullRange(this DateTime value, DateTime from, DateTime till) =>
        value >= from && value <= till;
```
and use like
```c#
if (entry.Date.IsInFullRange(from, till))
{
     …
}
```

**Comment by yaakov-h** [comment]
Active Patterns (#277) could also be another way to solve this, with something like `where foo is Between(lowerBound, upperBound)`.

**Comment by HaloFour** [comment]
Or a combination of ["and" patterns](https://github.com/dotnet/csharplang/issues/1350) with [relational patterns](https://github.com/dotnet/csharplang/issues/2115):

`where foo is >= lowerBound and < upperBound`

**Comment by gafter** [comment]
Pattern-matching alternatives do not work unless the limits are constants.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/217

**Comment by MovGP0** [comment]
@RobotaAL76 

This solution doesn't seem right to me. While it is possible to use extension methods, extention methods can't be compiled to SQL by the LINQ compiler. 

Also you are violating the left-to-right order and reinventing the `between` keyword order from SQL, as I stated in the non-goals statement.

**Comment by RobotAL76** [comment]
@gafter 

> Pattern-matching alternatives do not work unless the limits are constants.

Why is pattern-matching oriented only at constant expressions?

IMHO, it is provokes to hardcode style syntax

```c#
if (value is 42) Console.WriteLine("Hit!");
```
instead
```c#
if (value is UserSettings.CustomizableMagicValue) Console.WriteLine("Hit!");
```

Of course, there are available another syntax variations
```c#
value == UserSettings.CustomizableMagicValue
Equals(value, UserSettings.CustomizableMagicValue)
```
But what reasons interfere to generalize all matching operations (for types and values too) into `is`-based syntax ? For example usually I use following extension-based variations together and really feel good
```c#
if (value.Is(42)) Console.WriteLine("Hit!");
if (value.Is(UserSettings.CustomizableMagicValue)) Console.WriteLine("Hit!");

if (value.Is<int>()) Console.WriteLine($"{value} is int");
```
Currently `value.Is(42)` has much better flexibility for me and preferred then `value is 42` because in perspective I can replace the temporary debug constant by any dynamic variable without significant changing style of my code.

**Comment by RobotAL76** [comment]
@MovGP0 

> This solution doesn't seem right to me. While it is possible to use extension methods, extention methods can't be compiled to SQL by the LINQ compiler.

So, maybe it is true.

> Also you are violating the left-to-right order and reinventing the between keyword order from SQL, as I stated in the non-goals statement.

But if order is really important you can reorder it like
```c#
if (Range.Full(from, value, till)) …
/* or tuple-based */
if ((from, value, till).Full()) ...
```
Interestingly that in more general sense if allowed
```c#
if (a < b) ...
if (a < b < c) ...
```
seems that should be allowed expressions of arbitrary length too
```c#
if (a < b < c < d) ...
if (a < b < c < d < e) …
etc...
```

**Comment by RobotAL76** [comment]
[It is just for fun :)](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMBuAWAChUAmdY1AZmxwDZtTaB2TAb2My+xtwdQAsmALIBDAJZQAFAEp2nbooBuosJimiYmAEZaAxlrhaApnIC86nFtJaqWgVvQzCRRYoVvMAei+ZxAM3VRTAAeHVDMPQi4TAA+TFMPNx8/QI0I7UwAMizwsKicyOjs3Jj4xNdPVKCAOgAZYwBnRqltGXqmlr12huapOHaAcTBjUWApUxqAYQALYz0Aa1kZJKraAE4pACJgSGMt51XuYwAbRuMN7f9RM/3Dyq4AX2JnoiS+RhExmaS2KqOuNRaPwAKwhVoAewhJ0wACUmhATsAtJJgJgGv5gDJ4r0WsAZuJGn4oGiTsZMSiSZgwOIAOYzLGYMyxAFuKDGADu2DBkOhlKxsSksiZ8SkZMxERp9OR1LpDJk9zWrKBH1QPO0UJh8MaiJlqPR5IFBr6+MJ3PBGr5xKN/n5sul5hZDzWmHZXLVFs1/OxQsdmFZig4zpd3BUaikIx1SK04sZFn8shcIc8qFYEYRSJKmFjkrlMql8qTyceiv+we4Kvo5t5WozeqpGKNw1G41NRI9Ne98Vt1vt8pFAe4burlpOXd9A/LniDybcYfUkd1McN5kwCdLs8BacXmcKOfiBfzeY3LpLRc8yt4VdHmFm8yWbZHmrhda7a7965q2t158wjyAA)

```c#
        var (a, b, c, d, e) = (1, 2, 3, 4, 0);
        
        // if (a < b < c < d > e)
        // if (a < b && b < c && c < d && d > e)

        if (a.Less(b).Less(c).Less(d).Great(e).Check())
            Console.WriteLine("true");
        else Console.WriteLine("false");
```

**Comment by gafter** [comment]
> Why is pattern-matching oriented only at constant expressions?

So that the set of patterns, e.g. in a switch, can be analyzed at compile-time and we can produce good code for the full set of patterns rather than a series of if-then-else tests.

**Comment by gafter** [comment]
> It is just for fun :)

It isn't fun.  It is the sort of annoying distraction that has gotten you kicked out of this repository repeatedly.

**Comment by RobotAL76** [comment]
@gafter 
Seems that you are not a fun of experimental abstract functional programming.

But if you like to discuss more practical questions welcome to [the thread](https://github.com/dotnet/csharplang/issues/2431).
:)

**Comment by YairHalberstadt** [comment]
Unfortunately I can't move this to a discussion due to a bug with github, so I'm going to close this. Feel free to open a new discussion referencing this issue.
