### ISSUE TITLE
Set variable in helper method and it changes in parent scope.

### ISSUE THREAD

**Issue by wooden-utensil** [dotnet/csharplang#2413]
So I was wondering if it's possible to set a variable in a helper method for example:
```c#
public static void setX(this Point a, int val) {
    a = new Point(val, a.Y);
    // Will `a` change in the place where this function is called from?
}
```
If this is not possible, can you recommend an alternative solution?

**Comment by Joe4evr** [comment]
Just mark the `Point` parameter to be passed by `ref`.

Side note: you should follow standard conventions and name your methods in PascalCase.

**Comment by marksmeltzer** [comment]
@joe4evr

Dumb question: is that possible for extension methods? I've never tried on the assumption it isn't possible.

**Comment by PathogenDavid** [comment]
@marksmeltzer 

Yup, it was [added in C# 7.2](https://github.com/dotnet/csharplang/issues/186), although only for structs.

[Here's an example of it in action.](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYwCYgNQB8ACADAAT4CMA3ALABQt+AzMQM5woDGcxACgPYCWqOLQDetYhNJNBXABrUakqcRnEAmgqXjJjHgKEAKVWBgqhxAJ4BKbRLGKlk2cQC8xMJscS1ry54kAvrS2yrwAbgCmiIj8GBGkZCQAKrwAymyCAOYGNg5eLgB8xAAkAEQiFbIBpiJqAfWlCkF0NLrkEKQATHoyAKJgcBGozPy8w6IhbWQd+FDEqRFwsgZwABb8zMSIEQBmPeZhpqphAIYANrleEoXEYb6oEQDu+3AGp2emYQB0alZNwa0mO0ugkAOwTPLKYGzYgAWROghyIXsVxet3uTxeBkShFMnUIhD+ISU5AAnG8iZClN8FktsZ1KaiyRT/MRms0gA==)

**Comment by wooden-utensil** [comment]
> Just mark the `Point` parameter to be passed by `ref`.
> 
> Side note: you should follow standard conventions and name your methods in PascalCase.

I thought is was lowerCamelCase and UpperCamelCase.
