### ISSUE TITLE
Allow 'when' exception filters without enclosing parenthesis

### ISSUE THREAD

**Issue by johnkellyoxford** [dotnet/csharplang#2415]
Currently, an exception filter requires parenthesis around it, such as:
```catch (Exception) when (e.Message is null)```
This is markedly different to a catch filter, which does not
```
switch (str)
{
    case " " when str.Length is 3:
    
}
```
To have consistency, `when` should not require brackets in either case, in my opinion

**Comment by yaakov-h** [comment]
I believe it's forced due to an ambiguity.

`case foo when ...:` has a `:` to terminate the statement;

`catch (Exception ex) when foo { ... }` would have no clear terminator for the filter expression, so the curly braces could either belong to the filter, or be the beginning of the catch body.

**Comment by marksmeltzer** [comment]
@yaakov-h simple fix: require balanced surrounding parentheses:
```csharp
catch (Exception ex) when (foo) { ... }
```
