### ISSUE TITLE
[Proposal]: add syntax sugar for `&&`

### ISSUE THREAD

**Issue by ichensky** [dotnet/csharplang#2416]
For ex. we have code, that compare values:
```csharp
int a = 1, b = 1, c = 2, d = 3;
if (a == b && b == c && c == d) { ... }
if (a > b && b > c && c > d) { ... }
if (a > b && b < c && c > d) { ... }
```
Proposal add ability to compare values in a such way: 
```csharp
if (a == b == c == d) { ... }
if (a > b > c > d) { ... }
if (a > b < c > d) { ... }
```

**Comment by YairHalberstadt** [comment]
This looks very similar to #2412.

It is also a breaking change as this currently is a valid expression:

```csharp
true == false == true == false //evaluates to true
```

Under your suggested change, this expression would evaluate to false.
