### ISSUE TITLE
Proposal: Operator for swapping variables

### ISSUE THREAD

**Issue by LWChris** [dotnet/csharplang#2417]
Swapping the content of two variables is a very common thing to do. However, this requires an additional variable, which I have to declare, the name doesn't matter and will usually be "temp" anyway, and I have to put three lines for one operation:

    var temp = x;
    x = y;
    y = x;

Hence I'm proposing a new binary operator `><` to swap values: `x >< y;`

I am chosing `><` over `<>` to avoid confusion, because `<>` most likely makes people switching from VB.NET to C# believe it was the inequality comparison.

The result should be the original value of `x`, since this means chaining the operator behaves according to the natural understanding of what would happen when reading from left to right and performing the operations one after another:

    // cyclic swap
    x >< y >< z;

    // same as
    (x >< y) >< z;

    // same as
    x >< y;
    y >< z;

    // means
    var temp1 = x;
    x = y;
    y = temp1;

    var temp2 = y;
    y = z;
    z = temp2;

    // All four blocks are leading to
    // x' = y
    // y' = z
    // z' = x

**Comment by hez2010** [comment]
You can already use
```csharp
int x = 1, y = 2;
(x, y) = (y, x);
```

**Comment by LWChris** [comment]
Since when? Must've missed out on that.

**Comment by hez2010** [comment]
@LWChris Since C# 7.0.

**Comment by LWChris** [comment]
Thanks, I missed that out but not local function. Well, the operator was shorter and doesn't look like a tuple was created, but I can live with that.

**Comment by HaloFour** [comment]
> and doesn't look like a tuple was created,

As of I believe C# 7.1 the compiler optimizes away the creation of a tuple.
