### ISSUE TITLE
Proposal: Single ownership

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#242]
(from http://xoofx.com/blog/2017/01/17/the-stark-programming-language-experiment/)

> There will be a single ownership allocation that will allow allocate on the heap but without having the GC to track these references (would be tracked by single ownership and destruction on last owner disposed)

We can use syntax "unique" and "move" to express this feature:
```C#
class A 
{
    int a;
}
class B
{
    unique A aa;  // "aa" would hold an "unique" reference to an instance of class A
}
......
static void foo()
{
    var b=new B();
    b.aa=unique new A(); //both sides of "=" should be "unique"
    ......
    unique var a0=move b.aa; 
    /*after "move", local variable a0 get ownership and b.aa become null. 
      If not use keyword "move", compile error */
    ......
    a0=null; // "a0" destruction here! If class A has finalizer, execute it here, if not, free memory
    .......
}
......
unique class C
{
    ......
    void func()
    {
        unique var c=new C(); //the whole class C is unique, so do not need keyword "unique" before "new"
        ......
    }
}
```
In fact, we can see single ownership as a simplified reference count (RC) mechanism which only allow rc to be one or zero. This can get 90% benefit of a full RC system with only 10% work of a full one.
Additionally, I suggest that the "unique" object can support weak reference to it, of course, at most one weak ref. (Usage: In the unique object's finalizer, we can put the object to a weak ref list for reuse later, like some kind of object pool/cache.)

**Comment by gulshan** [comment]
Related- [Proposal: move](https://github.com/dotnet/roslyn/issues/160) by @stephentoub
