### ISSUE TITLE
C# Services

### ISSUE THREAD

**Issue by chadmichel** [dotnet/csharplang#2420]
C# services as first class citizens. 

Services would have a few different behaviors
* All methods are async by default, no synchronous methods. Callers do not need to specify await, await is assumed.
* Services do not have public properties.
* Services can only be instantiated through some sort of builder/factory.
* Services can be easily hosted as WebAPI (like a controller).

As an example, the OrderService can be written as a class. 

```
    public class OrderService : IOrderService
    {
        public async Task<Order> FindOrder(int id)
        {
            // Some code...
        }

        public async Task SubmitOrder(Order order)
        {
            // Some code...
        }
    }
```

But if we have a service type things can just be defaulted. Instead of adding an async keyword, it would be async by default. No need for Task.

 ```
 public service OrderService : IOrderService
    {
        public Order FindOrder(int id)
        {
            // Some code...
        }

        public void SubmitOrder(Order order)
        {
            // Some code...
        }
    }
```

**Comment by DanFTRX** [comment]
In regards to your bullets:

> All methods are async by default, no synchronous methods. Callers do not need to specify await, await is assumed.

Automatically awaiting every Task returning function is a regression not a feature.  There are plenty of valid use cases in which you do not want to await a returned task immediately.  (Mainly because Task does not distinguish between an async Task and a Thread backed Task)

> Services do not have public properties.

This seems kindof pointless

> Services can only be instantiated through some sort of builder/factory.

There is no standardized builder/factory pattern in the C# language.  So thats a no-go

> Services can be easily hosted as WebAPI (like a controller).

This is super vague.

**Comment by HaloFour** [comment]
I really don't see the point.  You're "service" version is only ever so slightly less verbose.

> All methods are async by default, no synchronous methods. Callers do not need to specify await, await is assumed.

The language team decided to make `async` and `await` explicit specifically because it would be both exceptionally confusing and ambiguous to not do so.

**Comment by gafter** [comment]
You have not said what problem you're trying to solve.

**Comment by chadmichel** [comment]
The primary problem would be the leaking of async / await into all methods and method calls. I understand not changing the existing c# classes / methods, but trying to create a parallel world for services that behave more async first.

**Comment by gafter** [comment]
@chadmichel I understand what you're trying to do.  I just don't know why.

No matter what you do to the syntax, existing methods are not async, and you need async methods.  Today, you write that parallel world of async APIs by adding the `async` modifier on the methods.  So now you have a solution.  What more do you need?

**Comment by chadmichel** [comment]
@gafter,  I agree that the existing syntax is enough to achieve most what I am hoping to achieve with “service”. But, I am thinking of a “service” as a way of flipping to a more async default world from the existing sync world of C#.

**Comment by orthoxerox** [comment]
@chadmichel How would a service method obtain the real return value of a method you don't want to await immediately?

**Comment by chadmichel** [comment]
@orthoxerox I hadn’t really thought about that option. I assumed you usually would want to wait, but their would maybe have to be a keyword to not wait.
