### ISSUE TITLE
Concept of generic matching

### ISSUE THREAD

**Issue by RobotAL76** [dotnet/csharplang#2431]
C# has an interesting transform which keeps invariant of result for value types and reference values at non-`null` context
```c#
/* where */
T y = ...
x != null && y != null

Equals(x, y) <=> x is T && Equals(x, y)
```
So, if we have

```c#
switch(x)
{
    case 0: return "Zero";
    case 42: return "Magic Hit!";
    default: return "${x}";
}
```

it is possible to rewrite

```c#
switch(x)
{
    case int i when i == 0: return "Zero";
    case int i when i == 42: return "Magic Hit!";
    default: return "${x}";
}
```

Then for example I want to replace `magic constant 42` by a customizable value from settings

```c#
switch(x)
{
    case int i when i == 0: return "Zero";
    case int i when i == Settings.CustomizableMagicValue: return "Magic Hit!";
    default: return "${x}";
}
```

Good, this is valid code. But now I want to do the backward transform

```c#
switch(x)
{
    case 0: return "Zero";
    case Settings.CustomizableMagicValue: return "Magic Hit!"; /* O-o-ops! Compile error */
    default: return "${x}";
}
```

We got the compile error and looks that symmetry of `switch` operator is violated.

**Proposals**

1. Seem that there is sense to allow non-constant expressions into switch operator and pattern-matching expressions like
```c#
if (x is Settings.CustomizableMagicValue)
```
Because constant oriented syntax implicitly pushes to hardcode style when magic values defined into the code instead customizable settings and dynamic variables

2. Generalize matching as a core concept of equality checks

There are many ways to do closely similar things
```c#
object.Equals(x, 42)
object.Equals(x, y)

EqualityComparer<T>.Default.Equals(x, 42)
EqualityComparer<T>.Default.Equals(x, y)

x == 42
x == y

x is 42
x is y /* missed */
```
Moreover seems that generic matching `x is y` may be most pretty and elegant generic solution which encapsulates advantages of another approaches.

I tried to use extension-based matching at several my own projects and feel self really good because this is very generalized approach which helps to write matching code into the unity manner

```c#
if (x.Is<int>())
if (x.Is(42))
if (x.Is(default))
if (x.Is(null))
if (x.Is(y))
```

------
<details>
  <summary>Show more details</summary>

So, I asked to Neal

> Why is pattern-matching oriented only at constant expressions?

and got [the answer
](https://github.com/dotnet/csharplang/issues/2412#issuecomment-482251579
)
> So that the set of patterns, e.g. in a switch, can be analyzed at compile-time and we can produce good code for the full set of patterns rather than a series of if-then-else tests.

Well... If I understand correctly good code supposes minimized count of equality checks and boxing/unboxing conversions.

Consider a trivial mathematical example
```c#
a*c + a*d + b*c + b*d = 
a*(c + d) + b*(c + d) = 
(a + b)*(c + d)
```

There are several expressions which produce the same result but have different effectivity because multiplication is more expensive then addition. This intuition may be expanded into `switch` too.

An source expression
```c#
static string MatchingStep0(object o)
{
           switch (o)
           {
                      case 1: return "one";
                      case 2: return "two";
      
                      case "abc": return "ABC";
                      case "xyz": return "zyx";

                      case int i when i > 2: return "too many";
                      case int i: return "too few";

                      case string s: return s;
      
                      case null: return "is null";
                      default: return default;
           }
}
```
       
Rewrite like
```c#
static string MatchingStep1(object o)
{
           switch (o)
           {
                      case int i when i == 1: return "one";
                      case int i when i == 2: return "two";
                      case int i when i > 2: return "too many";
                      case int i: return "too few";
      
                      case string s when s.Is("abc"): return "ABC";
                      case string s when s.Is("xyz"): return "zyx";
                      case string s: return s;
      
                      case null: return "is null";
                      default: return default;
           }
}
```
       
On this step we see that value matching is like particular case of type matching with condition.
Looks that switch syntax has broken symmetry between type and value matching...

Rewrite to
```c#
static string MatchStep2(object o)
{
           int i;
           string s;
           if (o.Is<int>(out i) && i.Is(1)) return "one";
           if (o.Is<int>(out i) && i.Is(2)) return "two";
           if (o.Is<int>(out i) && i > 2) return "too many";
           if (o.Is<int>(out i)) return "too few";

           if (o.Is<string>(out s) && s.Is("abc")) return "ABC";
           if (o.Is<string>(out s) && s.Is("xyz")) return "zyx";
           if (o.Is<string>(out s)) return s;

           if (o.Is(null)) return "is null";
           return default;
}
```
       
Now we perfectly see that this code may be significantly optimized
```c#
static string MatchStep3(object o)
{
           if (o.Is(out int i))
                      return
                                 i.Is(1) ? "one" :
                                 i.Is(2) ? "two" :
                                 i > 2 ? "too many" :
                                 "too few";

           if (o.Is(out string s))
                      return
                                 s.Is("abc") ? "ABC" :
                                 s.Is("xyz") ? "zyx" :
                                 s;

           if (o.Is(null)) return "is null";
                   return default;
}
```
      
Looks better but try to improve
```c#
static string MatchStep4(object o) => o.Match
(
            (int i) =>
                     i.Is(1) ? "one" :
                     i.Is(2) ? "two" :
                     i > 2 ? "too many" :
                     "too few",

            (string s) =>
                     s.Is("abc") ? "ABC" :
                     s.Is("xyz") ? "zyx" :
                     s,

            (object _) => default,
      
            () => "is null"
);
```
            
Done.

What are [this steps](https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLAChYMQFjejKAZgQCY4BhOAbwznoRKhzgFkAKASjodvQbgBfDMIJiAkAHoAVHAAqACwCmcADIBDAHYBzAK7rtKgKIAPAC5LNAZwCWAe2txpkjOOLYAbHAAO6gE5mNuoANmRqRq584lKy1HbBwBQOFuaCAHQACrpm7NSaSgDuSZopZoKcadQUIcEAYn52ALYAcoXFpYJOLujR7khecgAacFlmADxyADTygwB87GYKNlbycHbTQ3AmnHAAvLNb+L1MiF5+SgBmMyPZExtzC0srcmvT51eb23sH74cYrjE4PltOpAg4ugC+qc4AAjOzxODNOw5RbLWHw0Iwnb7OAAQhh+ABMnRJhsOjgF3OKgAbiFdCpGqCAMZLcnOSEnLxwhFGACO+mCVgm8zJq3U01FLyx3zgfIFNjMAE8ko1fOc/MK0gARS7qXTBMxpOUhKzscWwziEnpuTnohEASSFcnmqOea2xBzseN2QP1wSONs8dtCjuFjzRL3Wqy+OONgvYUe2yDgxLjTvmictEOtUK5GLgoed4bdUbsMIAVkomWYth6tmlC/MdgAyZuy/kmhPTdhyThJjlB7kh9PFtYVqs1qMvGOehsjltttPsHucTMB3PBgum11jyvV167ie1mVLtf/HO2odbpHjIs7yN1r27H2aP3ry/5x03sP3g/Tuu4nYc7sP2F6Dp+VjfneTyHvuU7HjigHAaBxzgQ6kHIj+MGRtMZZ7jWM54kBjogZaA79JuX7IqOeFHqW477oRSEkaB5HQlejajnIAD87pwAUyjnKsIBwFYZh+Lo+44kBAAS6hWAAanSSjJsSXoRtmqEURxI73rx8FfAJShCS8IliRJUmznJinKXArbtgKppAUpwT0tMKGBtpEFYRpU68YZgkqKZoniZJNY4iYaTWS59J2YuHbxomaQxUoZESJ57EQVBLrYfpOxGSZcBmaFllEcBaVaZl6HZVx+kbMeBVBUVIUWeFBzMaaHkbjpNW/n5DWBcJLVhTKHWkVa0TEkg8AwvJSjAHAtKuQyzKstomkZV4ZI1iqapKKO00HodJjTAAyuJZLaLt/jLOCTJNGqt2aHscDnX4l3Xe9VgOGkADyfjAGSIQegCbiIDAaSfftibTPdqo3d9mhpTwAj0Buh1yHYb0HeDfHSe+QYY1j4k0Qxk6PtxaSY29l1cATXnoTj8BRsdZ0XTon1PXAcOPYjj6Qw9/j7Sd3OC19DgVCRMAVZtlHbjBtFwbhZNbGz70c2LXM8wjEsysRnU7BAEBrFTxN+FwyGm9jnCw5rfP01Vw43kzR24yLNMa/D4vPdr3sAfrIG217T0y91WXUTuiuTsr+Gq697NXXbd1J0jo0ByLvshxNgJKt4K1mCyl0bWH6E+SWuHZNGdYgS9diS6aocfqX0FolHeOenAEaqbIXq4i+fpxXAudKHYFwrnOACCVi2NomjqDCwRKPUTQJmkADiShmHIip51wlriOy6Ul8OZewdHayV9O9UXDUs1MgA1ilL3ALq+pmCD1riDXPr62GFSYwmSutI/AWjgLxFcXoRI32CMEO+j9lIVFGOwX4WJs7EmHtzeSgQ2TdEql4NuFAFBaEMNvPOp82512+KDdSKxXwwLgEbIeO8R5j17HOFKpCVCMJoQWYo1JjKBAXioXifCBGQyIToJQnCuxMLzqPFc0w6HBB2CJOw2cNwvExqfB8esHYDHkHYchKtKE4ggeI4hUjmF/z0XAX4mjDEt3LhfGs/4aBbFrsmKAAB2WxlxDhCDYmcPx9ijGx1LJfY81B3E+jMYQixnDrEIB8b8EwyZRB4N8R8XiWjHFnwPHYS+/l8qDWCuZEaUSTAvR7NxVcnjkl+NSQEo+toXhT20e3NYNjWm6WwvkiJhFKk/y6XANpuSKHX1vuoB+T8fQvxvm/fmnEdjgN7JAikkzpnKWGaMnKrdjEVxcXHF40DYFTPgctZ+r8DR1kGSbKe7ATlwJShVUQ55ZZqkCCEMIqgIg9CiLLOQv1K6sFWhMe0mgNhArMLs544LRYlCUOYaYUAACsEwoUHC) demonstrate?

Seems that good design suppose better structuration of code and separation of type and value matching logic.
</details>

**Comment by YairHalberstadt** [comment]
I find this extremely difficult to follow.

Can I suggest that you remove the mathematical cruft, and keep strictly on point.

What is it you want to achieve?
What is your current method of achieving that?
Why is it deficient?
What is your proposed solution?

As I've stated before, the LDC is extremely pragmatic, and is not interested in making the language symmetrical by some arbitrary  mathematical definition. They are interested in helping C# developers solve real life problems. If you focus on that, you are more likely to convince them to take your ideas on board.

**Comment by RobotAL76** [comment]
> What is it you want to achieve?

**Goal 1**
Generic manner of different checks for type and value matching without limitations of constant expressions
```c#
x is 42 /* const */
x is y /* variable */
x is AnyValue /* property */
x is GetY() /* method */

x is int
x is int i
```

**Goal 2**
Push developers by syntax to separate type and value matching logic at `switch`-like expressions for generation of more effective code.

> What is your current method of achieving that?

I use custom extension methods.

> Why is it deficient?

Exclusively for me it is deficient, but another developers don't know that possible to use generic approach instead mixing of similar things `Equals`, `==`, `is`.

> What is your proposed solution?

The first step is removing of compiler restrictions...

**Comment by YairHalberstadt** [comment]
> Push developers by syntax to separate type and value matching logic at switch-like expressions for generation of more effective code.

What do you mean by that?

**Comment by gafter** [comment]
Patterns and expressions are different things by design.  A pattern such as `Bar()` under this proposal would be ambiguous between a method invocation and a deconstruction, each of which would require distinct lookup rules.  We have no intent to merge expressions and patterns.
