### ISSUE TITLE
Change handling of CancellationToken for async iterators

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2434]
@MadsTorgersen wrote by email on April 4 2019 a proposal that will be discussed at an upcoming LDM.  Here is that email.

---
***[Tl;dr: I am concerned that we made the right decision for iterator writers rather than consumers regarding cancellation tokens]***

I’ve been thinking about the decision we made last week in the Design Review around how to surface cancellation tokens in an async iterator. We looked at two options: having the cancellation token as a specially attributed optional parameter, as we do with CallerNameAttribute etc., or having a special name inside the iterator body by which to refer to the cancellation token. We chose the latter (using the name “cancellationToken”):
``` c#
    static async IAsyncEnumerable<string> GetNamesAsync()
    {
        string[] names = { "Ahmed", "Beatrice", "Carmen", "Daniel", "Edouard", "Friedrich", "Gertrude" };
        foreach (var name in names)
        {
            await Task.Delay(300, cancellationToken);
            yield return name;
        }
    }
```

I think what we chose is the “cleanest”. However, I am starting to wonder if it was the best in practice for the _consumption_ side. It seems to me that there is a common case and a general case. In the general case you may `await foreach` over any existing IAsyncEnumerable, and so it’s important that you can supply a cancellation token after the fact. The `WithCancellation` extension method accomplishes that:
``` c#
        var query = GetNamesAsync().Where(name => name.Length > 6);
       …
        await foreach (var name in query.WithCancellation(token))
        {
            WriteLine(name);
        }
```
In the _common_ case, however, you foreach the IAsyncEnumerable once, immediately as you receive it from some async iterator method. Here the above approach seems unnecessarily cumbersome:
``` c#
        await foreach (var name in GetNamesAsync().WithCancellation(token))
        {
            WriteLine(name);
        }
```
Also, folks are likely to forget calling `WithCancellation`.

With the other proposal, the one we rejected, the declaration adds a little extra gunk to its header:
``` c#
    static async IAsyncEnumerable<string> GetNamesAsync([Cancellation] CancellationToken cancellationToken = default)
    {
        string[] names = { "Ahmed", "Beatrice", "Carmen", "Daniel", "Edouard", "Friedrich", "Gertrude" };
        foreach (var name in names)
        {
            await Task.Delay(300, cancellationToken);
            yield return name;
        }
    }
```
This is not altogether nasty, as adding cancellation tokens to signatures always looks like this, and the IDE could suggest adding the attribute if you forget. The attribute/optional trick itself, as mentioned, is already used elsewhere in C#.

The semantics implemented by the compiler would be that any token passed in through `WithCancellation` (and on to the `GetAsyncEnumerator` method) in a given enumeration wins. However, if that one is the default token (never cancels), then the original parameter (if any) is used.

For the consumer, this means that in the common case they can pass the token directly to the iterator method, like they are used to for other async methods:
``` c#
        await foreach (var name in GetNamesAsync(token))
        {
            WriteLine(name);
        }
```
This is much more straightforward and familiar, and the risk of forgetting to pass the token is low, since it shows up in completion as an optional parameter. Looking at it, this is code I’d much rather _write_ and much rather _read_ than the explicit `WithCancellation` version.

It does run the risk that a cancellation token is accidentally passed “too early”:
``` c#
        var query = GetNamesAsync(token).Where(name => name.Length > 6); // Oops
```
I think this is of limited risk. If there even _is_ a token around to pass in, it is likely to be the same as the one later used for enumeration. And if a different token _is_ eventually used for enumeration, that one wins.

All in all I feel like we made the right decision for the producers instead of the consumers of async streams.

---
PS! My toy code in case you want to play around with it yourself:
``` c#
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using static System.Console;

class Program
{
    static async Task Main(string[] args)
    {
        var cts = new CancellationTokenSource();
        var task = MAsync(cts.Token);
        await Task.Delay(8000);
        cts.Cancel();
        await task;
    }

    static async Task MAsync(CancellationToken token)
    {
        await foreach (var name in GetNamesAsync())
        {
            WriteLine(name);
        }
        await foreach (var name in GetNamesAsync().WithCancellation(token))
        {
            WriteLine(name);
        }
        await foreach (var name in GetNamesAsync(token))
        {
            WriteLine(name);
        }
        var query = GetNamesAsync(token).Where(name => name.Length > 6); // Oops
        await foreach (var name in query.WithCancellation(token))
        {
            WriteLine(name);
        }

    }

    class CancellationAttribute : Attribute { }
    static async IAsyncEnumerable<string> GetNamesAsync([Cancellation] CancellationToken cancellationToken = default)
    {
        string[] names = { "Ahmed", "Beatrice", "Carmen", "Daniel", "Edouard", "Friedrich", "Gertrude" };
        foreach (var name in names)
        {
            await Task.Delay(300, cancellationToken);
            yield return name;
        }
    }
}

public static class Extensions
{ 
    public static async IAsyncEnumerable<T> Where<T>(this IAsyncEnumerable<T> source, Func<T, bool> predicate)
    {
        await foreach (T element in source)
        {
            if (predicate(element)) yield return element;
        }
    }
}
```

**Comment by marksmeltzer** [comment]
Could you comment more on the "too early" case? From the provided example, I am not perceiving any obvious risk.

Regards,

**Comment by orthoxerox** [comment]
> It does run the risk that a cancellation token is accidentally passed “too early”:

If `token` is cancelled, won't `await foreach` inside `Where` pick up on that and stop? Or is Mads worried that the token will be inserted because IntelliSense asks you to and then simply discarded?

**Comment by quinmars** [comment]
```csharp
var names = GetNamesAsync(token);
```

Will use one cancellation token per enumerable, although cancellation happens on the enumerator level. I find that very confusing.

**Comment by marksmeltzer** [comment]
Nevermind. I see now from the whole code sample what the implied issue is. However, I think it is a manufactured issue...

For the "too soon" case, the ideal solution eliminates the "WithCancelation()" call entirely:

Like all current async code, if I want my code to be cancelable, I should have the method accept a cancelation token, and then pass that explicitly down the stack to my cancelable code.

In the case that only the enumeration itself should be cancelable, I would explicitly check for cancelation on the token in the body of the foreach loop - there's no need or intrinsic benefit to having a WithCancelation method available.

That is precisely because there will be cases where the token cannot be passed further down the stack, and the foreach loop's body with be place to check for cancelation. Specifically, the loop body may make several async calls that each don't accept cancelation tokens, in which case the token would need to be checked explicitly before/after each async call.

That is exactly analogous to how cancelation is handled in today's async code: cancelation implementation is up to the developer to handle it explicitly, and it should be exactly analogous with async enumeration. Developers should not have to learn a separate pattern for async enumerable cancelation.

Regards
,

**Comment by scalablecory** [comment]
Passing a cancellation token into the generator method too tightly couples a reusable "cold" enumerable to a single "hot" execution. This breaks LINQ.

`GetEnumerator()` is a much more flexible place to pass cancellation tokens.

**Comment by marksmeltzer** [comment]
I don't see any breakage at all in the actual example - and of course you are correct: the developer should not pass the task cancelation token to the reusable enumerable. However in this sample cases it doesn't appear to be reusable. Is the conversation about how to support cancelation in new async Linq APIs?

The old PLinq APIs already supported passing cancelation token down the stack, and any new async Linq APIs should be exactly analogous to the PLinq APIs and enhanced as needed to add missing cancelation support.

My point is simple: reusing the existing paradigms for explict cancelation support is highly preferable.

Regards,

**Comment by gafter** [comment]
The LDM confirmed the change in https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-04-15.md#proposal-for-cancellationtoken-in-iterator-method

**Comment by quinmars** [comment]
Just as a sidenote: the `Where` implementation is missing the cancellation token. With the old proposal it would have been:

```csharp
public static async IAsyncEnumerable<T> Where<T>(this IAsyncEnumerable<T> source, Func<T, bool> predicate)
{
    await foreach (T element in source.WithCancellation(cancellationToken))
    {
        if (predicate(element)) yield return element;
    }
}
```
or with the new proposal (note the exposed cancellation token)
```csharp
public static async IAsyncEnumerable<T> Where<T>(this IAsyncEnumerable<T> source, Func<T, bool> predicate, [DefaultCancellation] CancellationToken token = default)
{
    await foreach (T element in source.WithCancellation(token))
    {
        if (predicate(element)) yield return element;
    }
}
```
In reality it will probably look more like that:

```csharp
public static IAsyncEnumerable<T> Where<T>(this IAsyncEnumerable<T> source, Func<T, bool> predicate)
{
    if (source == null) throw new ArgumentNullException(nameof(source));
    if (predicate == null) throw new ArgumentNullException(nameof(predicate));

    return iter(source, predicate);

    static async IAsyncEnumerable<T> iter<T>(this IAsyncEnumerable<T> s, Func<T, bool> p, [DefaultCancellation] CancellationToken token = default)
    {
        await foreach (T element in s.WithCancellation(token))
        {
            if (p(element)) yield return element;
        }
    }
}
```
So it is not necessary to expose the superfluous cancellation token in the operator's public API, but the operators cannot benefit from the planed null-checking argument modifier `!`.
