### ISSUE TITLE
Recommend <remarks> rather than <remark>

### ISSUE THREAD

**Issue by carlreinke** [dotnet/csharplang#2435]
The C# documentation recommends the [`<remark>`](https://github.com/dotnet/csharplang/blob/eafa3a5f513559449765bf4928d529455a788a76/spec/documentation-comments.md#remark) tag, but everyone uses `<remarks>`.

* Visual Studio Intellisence \
![image](https://user-images.githubusercontent.com/11667451/56099609-6b6aa000-5ecc-11e9-80d1-2f5a47a1fe15.png)
* [Sandcastle](https://ewsoftware.github.io/XMLCommentsGuide/html/3671b61e-0695-4f0f-bcb5-7cf9108dd642.htm) -- `<remarks>`
* [doxygen](http://www.doxygen.nl/manual/xmlcmds.html) -- `<remarks>`
* [Microsoft C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/remarks) -- `<remarks>`

**Comment by sharwell** [comment]
It looks like this was incorrectly modified from the orginal text in [ECMA-334](https://ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf) §D.3.12.
