### ISSUE TITLE
c# 8.0 index operator causes System.InvalidProgramException

### ISSUE THREAD

**Issue by LaterStart** [dotnet/csharplang#2438]
Hi,

I've started .NET Core 3.0 project using C# 8.0 (beta) language version and have encountered an error while using new index operator. 

I was trying to access last element of a string => s[^1];

Program does compile but throws at run time.
System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'

Any ideas?

(IDE: Visual Studio 2019 Community)

**Comment by svick** [comment]
I think this is a duplicate of https://github.com/dotnet/roslyn/issues/34209.

**Comment by marksmeltzer** [comment]
Should be fixed in the next release - bug is fixed already in the master build.

**Comment by yaakov-h** [comment]
Looking at Roslyn's branching I don't expect the fix to land until 16.1 Preview 3.

**Comment by gafter** [comment]
duplicate of dotnet/roslyn#34209.
