### ISSUE TITLE
Pattern Matching with generics

### ISSUE THREAD

**Issue by LaterStart** [dotnet/csharplang#2440]
Hi,

Why it isn't possible to match generic type by base class or interface in switch statement like this:

```
private static void MyMethod(IHttpActionResult payload){
switch (payload)
            {
                case OkNegotiatedContentResult<MYBASE OR INTERFACE> success:
                    break;
                case BadRequestErrorMessageResult error:
                    break;
            }
}
```
I am able to match only exact type, but not using base class or interface as template type.

(C# Language Version: 7.1)

**Comment by YairHalberstadt** [comment]
Yes it does work:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABABgAJiBGAbgFgAoMyqgFnoceIGZKAmcgGFyAb0bkJlXtQBslVuQCyEAJaYAFAEpR4yXqgB3FTADGAC3LrMcA+QAyK2AB5qpAHxbtYhnt+ST0HAs3E4A9sAAVnAmMG7kADaOqCwAnOoARJCmZnA46Zo0lADsHH5+OHAAZhDo8cnEJbp+AL6lks2MzUA===

I think you may be being bitten by [covariance and contravariance](https://docs.microsoft.com/en-us/dotnet/standard/generics/covariance-and-contravariance)

**Comment by gafter** [comment]
@LaterStart Can you please give a complete example (even a sharplab link like @YairHalberstadt did)?

**Comment by LaterStart** [comment]
@gafter Unfortunately I am unable to paste you an sharplab example, therefore I've pasted you MVC WebApi example you may run on your PC locally and verify.

```
using System;
using System.Web.Http;
using System.Web.Http.Results;

namespace WebApplication1.Controllers
{
    public interface IMyInterface { }

    public class MyDerived : IMyInterface { }

    [RoutePrefix("home")]
    public class MyController : ApiController
    {
        [HttpGet]
        [Route("test")]
        public IHttpActionResult SomeAPIEndpoint()
        {
            return MyHelper.ProcessRequest(() => { return Ok(new MyDerived()); });            
        }
    }

    public static class MyHelper
    {
        public static IHttpActionResult ProcessRequest(Func<IHttpActionResult> endpoint)
        {
            var result = endpoint.Invoke();
            MyMethod(result);

            return result;
        }

        private static void MyMethod(IHttpActionResult payload)
        {
            switch (payload)
            {
                case OkNegotiatedContentResult<MyDerived> success:
                    break;
                case BadRequestErrorMessageResult error:
                    break;
            }
        }
    }
}
```

I would swap line 36 `case OkNegotiatedContentResult<IMyInterface> success:`
with `case OkNegotiatedContentResult<MyDerived> success:` I would get a match. Using interface or even base class it skips the switch without matching, in case of successful request.

**Comment by YairHalberstadt** [comment]
This is expected as OkNegotiatedContentResult is not covariant.

**Comment by gafter** [comment]
As @YairHalberstadt points out, the `payload` received by `MyMethod` is of the concrete type `OkNegotiatedContentResult<MyDerived>`.  Trying to match it with some other type that it isn't won't work.
