### ISSUE TITLE
What is the implied constraint for a type parameter of a partial?

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2450]
What is the implied type parameter constraint in
``` c#
#nullable disable
partial class C<T> { }
#nullable enable
partial class C<T> { }
```
If there were only the first declaration, the constraint would be "oblivious object".  If there were only the second declaration, the constraint would be "nullable object".

Is this an error?

**Comment by YairHalberstadt** [comment]
I think the only sensible option would be an error.

**Comment by gafter** [comment]
@YairHalberstadt I think that is reasonable.  This issue was created to track an LDM agenda item in https://github.com/dotnet/csharplang/tree/master/meetings/2019

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/issues/35179 for a description of the LDM resolution.  That is an issue tracking the implementation.

**Comment by YairHalberstadt** [comment]
Closing as implemented with the following specification:

> For a partial type, the constraints (implied or explicit) for the various parts of a partial must agree. This is an existing rule. We extend this rule for nullability to say that they must agree in nullability annotations as well (or we produce an error for an annotated/unannotated disagreement). We use the invariant merging rules to merge the constraints from the various parts. The resulting merged constraints are used by the compiler in users of the type and within the body of the partial type.
>
> For a partial method, callers of the method are analyzed against the declaration. The body of the implementation is analyzed against the implementation's declared or implied constraints. We produce a warning at the implementation if there is a mismatch of type parameter constraints of nullable annotations annotated vs unannotated (though a mismatch with oblivious is ignored).
