### ISSUE TITLE
yield return true on TryMethods

### ISSUE THREAD

**Issue by JustNrik** [dotnet/csharplang#2454]
```cs
public static bool TryGetSomething(object key, out Something something)
{
    // some logic to determine if it's totally possible to retrieve Something
    yield return true; // If you discard the output, the method will end here returning true directly
    // some slightly expensive operation to get the output
}
```

Basically, in some situations we call a TryMethod but we don't use the output, we just discard it. Yet, the method will still get the output and assign it to the discard. This would be a performance benefit in case you need to use the TryMethod but you don't actually want the output.

Another example of use case is TryParse, in some situations for us it's easier to use BigInteger.TryParse to check if a string contains a number that may be insanely high, but BigInteger will parse it anyways and output a BigInteger althought we don't actually want it, which is expensive in terms of performance

**Comment by HaloFour** [comment]
Why is this any better than an `if` statement where you return `false` from the method?  `Try` methods don't follow the behavior of iterators at all, so it makes no sense to have `yield` in there, and successful or not the method is required to assign something to the `out` parameters.

**Comment by YairHalberstadt** [comment]
A number of questions:

1. How does the compiler know if the output is discarded?
2. What is the code gen for this? How would it work?
3. In the example you gave of Big integer.TryParse, the method parses the number as it goes along. By the time it knows it's a number, it's already done all the work. This sounds like premature optimisation. Can you give concrete examples of real life cases where this would actually improve performance?

**Comment by HaloFour** [comment]
> This would be a performance benefit in case you need to use the TryMethod but you don't actually want the output.

> How does the compiler know if the output is discarded?

Good point, I missed that.  The method can't know that you don't care about the `out` parameters.  Discards are purely compiler candy, the compiler is still required to emit locals into which those values are assigned, and the method itself would never know that this is the case.  You'd need some kind of separate overload.  But as @YairHalberstadt points out much of the work in these methods is in figuring out if it can return a value at all.  By the time this is known it likely already has the value, so assigning it to the `out` parameter has minimal cost.

**Comment by Korporal** [comment]
> ```cs
> public static bool TryGetSomething(object key, out Something something)
> {
>     // some logic to determine if it's totally possible to retrieve Something
>     yield return true; // If you discard the output, the method will end here returning true directly
>     // some slightly expensive operation to get the output
> }
> ```
> 
> Basically, in some situations we call a TryMethod but we don't use the output, we just discard it. Yet, the method will still get the output and assign it to the discard. This would be a performance benefit in case you need to use the TryMethod but you don't actually want the output.
> 
> Another example of use case is TryParse, in some situations for us it's easier to use BigInteger.TryParse to check if a string contains a number that may be insanely high, but BigInteger will parse it anyways and output a BigInteger althought we don't actually want it, which is expensive in terms of performance

@JustNrik 

This seems to be a weird request or I haven't understood you. `yield return` is for sequences - period.

Does your problem therefore involve sequences? if so then what you want is just LINQ suorely?

`things_we_dont_want_to_discard = some_data_source.Where(s => <some condition>);`

?

**Comment by DavidArno** [comment]
How about using lazy evaluation for the result:
```cs
public static bool TryGetSomething(object key, out Func<Something> somethingGetter)
{
    // some logic to determine if it's totally possible to retrieve Something
    somethingGetter = getSomething;
    return true; 

    Something getSomething()
    {
        // some slightly expensive operation to get the output
    }
}
```

**Comment by johnkellyoxford** [comment]
Why do you need `yield return true`? Just remove `yield`, keep it as `return true` and all is good. I am thoroughly confused by this...

**Comment by DavidArno** [comment]
@johnkellyoxford & @Korporal,

The purpose of the `yield return` here is conceptually similar to its use with iterators, as I understand the OP, which is why they picked it.

Effectively what the OP wants to do is return `true` or `false` and then, if the value of the `out` parameter is used, re-enter the method and compute that. This is similar to the idea of iterators where we "re-enter" the method to get the next value after the `yield return`.

As others have said though, this relies on the compiler being able to correctly determine that that `out` parameter is used and to lower the code to a form that can then handle computing the value later. This is likely an edge-case scenario: determining that boolean result typically requires computer the value and when it doesn't, a thread-safe way of handling that test then get approach would be needed. 

This suggests that scenarios where this feature would be needed are rare. And, as I show in my code above, it's already possible to handle this exact use case by returning a `Func<ValueType>` rather than `ValueType` via the `out` parameter. So this doesn't seem a compelling feature request to me.

**Comment by johnkellyoxford** [comment]
yeah, or just return a `Lazy<T>`

**Comment by DavidArno** [comment]
@johnkellyoxford, yes that would likely work too.

**Comment by jnm2** [comment]
Lazy is a little heavier or more opinionated than Func, so I'd leave the decision to wrap up to the caller.
