### ISSUE TITLE
Proposal: inlined arrays

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#2455]
If a class has an array as a field, sometimes we want to inline/embed the array in the class memory layout. Thus, we can reduce object number and GC pressure (embedded array is not an independent object, just a part of another object). This is like fixed buffer proposal, but there's important difference----the size of fixed buffer must be known at compile time, while the size of inlined array could be specified at runtime (when allocating the outer class object). To reduce complexity, we can add a limitation----a class could only have at most one inlined array and the inlined array must be one-dimensional.
Proposed syntax:
```C#
class A
{
    string s;
    bool t;
    object arr[]; //embedded array, syntax similar to fixed buffer, but do not specify array size.
    public A(string s, bool t) 
    {
        this.s = s;
        this.t = t;
        int i;
        for(i=0; i<LengthOf(this.arr); i++) // use syntax "LengthOf" to get the length of embedded array
        {    
            this.arr[i] = (object)i;    
        }
    }
}

int main(int args, string[] argv)
{
    var a = new[args] A("abc", true); // use syntax "new[ size ]" to specify the size of embedded array. In this example, the size is equal to "args".
    ......
}
```

**Comment by HaloFour** [comment]
This is basically the same as your own proposal #2393 except with slightly different syntax.  It has the same problems, too.  The size of a type cannot depend on any arguments passed to it, and it especially can't depend on values not known until runtime.

**Comment by ygc369** [comment]
@HaloFour 
I closed that proposal, this one is better.
> The size of a type cannot depend on any arguments passed to it, and it especially can't depend on values not known until runtime.

What about string and Array? Their size depends on argument.

**Comment by tannergooding** [comment]
And they are not inline, they are references to data.

**Comment by ygc369** [comment]
@tannergooding 
As far as I know, string class contains a length field and an inlined char array. I want to have self-defined such things.

**Comment by HaloFour** [comment]
@ygc369 

Both strings and arrays are a special case by the runtime.  There isn't a facility to make that general purpose, nor is there a way to embed the contents of one reference type within another.

**Comment by ygc369** [comment]
@HaloFour I know what you said. If there's already such mechanism, there would not be this proposal. I just propose to provide such mechanism.

**Comment by theunrepentantgeek** [comment]
I think you might be missing something @ygc369 ... there's no mechanism exposed by the runtime (any of them) that would support the C# language doing what you request.

History shows that any C# language change that is dependent upon parallel run-time changes has to meet a very high bar to even be considered. 

You might be well served checking out the [CoreClr](https://github.com/dotnet/coreclr) repo to ascertain their appetite for such a change.

**Comment by GSPP** [comment]
This could be extended to allow inlining of any reference type.

Why not just use a `struct` in those cases`? You might not control that type. For example, you might want to inline a `FileStream` or some other framework class.

Often, aggregation ob objects is exactly 1:1. The outer object stores exactly one inner object. That's a great case for inlining.

**Comment by huoyaoyuan** [comment]
I'll say this proposal totally useless.
If the type is stack-holded temporary, wasting several bytes does not mind. 
If the type is long-living on the heap, a reference to allocated array is same.
If the type is passed as parameter on stack, it's size will be very limited that can be declared to different types for every 4 or 8 byte aligned size.

**Comment by johnkellyoxford** [comment]
yeah, it just kinda seems useless... GC will still have to trawl the array for references
