### ISSUE TITLE
Proposal: provide a general/common way to get the size of a class

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#2456]
I want to get the size of a class (its memory usage in bytes), but C# does not have such ways.
For example, GC.TryStartNoGCRegion(long totalSize) need an argument to specify the allocation size, if I can't get the sizes of classes, how can I know the total size?
```C#
class A
{
    int a;
    byte b;
    char c;
}

int main()
{
    int n=GetSizeOf(A); //get the size of class A
    GC.TryStartNoGCRegion(n);
    var a = new A();
    GC.EndNoGCRegion();
}
```

**Comment by benaadams** [comment]
@SergeyTeplyakov's ObjectLayoutInspector  https://www.nuget.org/packages/ObjectLayoutInspector/ has various methods
```csharp
class A
{
    int a;
    byte b;
    char c;
}

public static void Main(string[] args)
{
    ObjectLayoutInspector.TypeLayout.PrintLayout<A>(recursively: true);
}
```
Will output
```
Type layout for 'A'
Size: 8 bytes. Paddings: 1 bytes (%12 of empty space)
|============================|
| Object Header (8 bytes)    |
|----------------------------|
| Method Table Ptr (8 bytes) |
|============================|
|   0-3: Int32 a (4 bytes)   |
|----------------------------|
|   4-5: Char c (2 bytes)    |
|----------------------------|
|     6: Byte b (1 byte)     |
|----------------------------|
|     7: padding (1 byte)    |
|============================|
```

So you could do
```csharp
int main()
{
    int n = ObjectLayoutInspector.TypeLayout.GetLayout<A>().FullSize; //get the size of class A
    GC.TryStartNoGCRegion(n);
    var a = new A();
    GC.EndNoGCRegion();
}
```
Also an overload to use a type cache etc.

Note if A allocates any other classes in its constructor the size of the pointer to them would be included; but not the size of the object allocated.

**Comment by johnkellyoxford** [comment]
There was an issue on coreclr or corefx to expose a public method to do this. You can do `Unsafe.SizeOf<T>()` with the unsafe package, but `sizeof` on a reference type returns the size of the reference

**Comment by Korporal** [comment]
@ygc369 - I just looked at https://github.com/SergeyTeplyakov/ObjectLayoutInspector and agree with @benaadams. I wrote very similar code about a decade ago in works fine. It can even give you the size if the class/struct contains C# references (e.g. string references) because ultimately these are just 32/64 bit ints - more or less.
