### ISSUE TITLE
Proposal: consider sizeof(T) where T is a value type with a constant size to be a constant expression

### ISSUE THREAD

**Issue by phxvyper** [dotnet/csharplang#2457]
`sizeof(T)` where `T` is a value type that has a size known time at compile time should be considered a constant expression.

Example:
```cs
[StructLayout(LayoutKind.Sequential)]
public struct RawInputHeader
{
    public int Type;
    public int Size;
    public int Device;
    public int Param;
}

[StructLayout(LayoutKind.Explicit)]
public unsafe struct RawInput
{
    [FieldOffset(0)] public RawInputHeader Header;
    [FieldOffset(sizeof(RawInputHeader))] public RawHid Hid;
    [FieldOffset(sizeof(RawInputHeader))] public RawMouse Mouse;
    [FieldOffset(sizeof(RawInputHeader))] public RawKeyboard Keyboard1;
}
```
produces error on `sizeof(RawInputHeader)`: 
```
An attribute argument must be a constant expression, 'typeof()' expression or array creation expression of an attribute parameter type
```

**Comment by tannergooding** [comment]
There is no guarantee that `RawInputHeader` has a constant size. It is computed at runtime because varying platforms or architectures may have different alignment or packing requirements that change the size of a user-defined struct from what you might expect.

**Comment by phxvyper** [comment]
> There is no guarantee that `RawInputHeader` has a constant size. It is computed at runtime because varying platforms or architectures may have different alignment or packing requirements that change the size of a user-defined struct from what you might expect.

I honestly didnt even account for the fact that C# is typically compiled to be JIT'd by a runtime. Whoops, feels bad :(

What would you think would work here instead, just doing 
```cs
sizeof(int) * 4
```
and deal with the fact that ill have to change the `* 4` later if the struct ever changes?

**Comment by phxvyper** [comment]
Gunna go ahead and close this since its invalid <3 thanks for quick response.
