### ISSUE TITLE
Suggestion：Allows developers to reuse custom classes at run time using the ‘constraint’ keyword.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/csharplang#2462]
We created a class with TypeBuilder/FieldBuilder/PropertyBuilder, named ClassA.

Developers can use this class, as follows：

```C#
/*
 *    class A  (in memory)
 *    ----  field: string Name 
 *    ----  field: int Age
 */

//--keywords----variable----customer class-----
    constraint  instance = Customer.CreateClassA();

//  Use it like a normal class，but not dynimac.
    instance.Name = "test";
    instance.Age = 28;

//There is almost no performance loss.
```

Some scenes.

Automatically generate entity classes according to the database table structure.
Type mapping from entity class fields to database table fields.

Is this possible?

**Comment by yaakov-h** [comment]
What would `constraint` mean, and how would the compiler know anything at all about class `A` in order to understand members, functions etc. without a type definition?

**Comment by NMSAzulX** [comment]
@yaakov-h   'constraint' means that it is not a fully dynamic instance, it has a fixed memory structure, and it can be automatically translated into runtime-generated classes. We know the fields, properties, and methods of this class (which is business-related), although it is generated dynamically.
We use TypeBuilder(reflaction/emit) to define a class dynamically.  We can use 'constraint' to represent this class when we are writing code in IDE.

**Comment by Joe4evr** [comment]
> We know the fields, properties, and methods of this class (which is business-related)

But how will the compiler know that these fields, properties, and methods are valid?

**Comment by NMSAzulX** [comment]
@Joe4evr  Thanks for responding.  

I'm sorry I don't know the compiler, but I guess Hierarchical-Compilation might solve the problem.

TypeBuilder：

We have a scene. When the program starts running, we request the database to get the table structure, and automatically generate the class.

**Comment by DavidArno** [comment]
[F# has something similar to this, in the form of type providers](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/).

However, it's worth noting that this is a compile-time feature. Trying to generate these types at runtime most certainly doesn't have "*almost no performance loss*"; it has huge performance implications. And if they are generated at runtime, there's no way for the compiler to know about them, so you have to use dynamic.

**Comment by NMSAzulX** [comment]
@yaakov-h @Joe4evr @DavidArno  I see. Thank you.       : )
