### ISSUE TITLE
Method which returns nested Awaitable do not warn developers to write multiple awaits.

### ISSUE THREAD

**Issue by walterlv** [dotnet/csharplang#2464]
This issue has been moved to https://github.com/dotnet/roslyn/issues/35232 .

Assume that we have a method that returns nested awaitables:

```csharp
Task<Task> FooAsync()
{
    throw new NotImplementedException();
}
```

If developers forget to await it, C# language will warn the developers to add an `await` keyboard:

```csharp
FooAsync();
```

But if we add one `await`, the C# language will not warn the developers to add another required `await` keyword:

```csharp
await FooAsync();
```

The correct usage is:

```csharp
await await FooAsync();
```

I think that C# language should add this warning because we sometimes cannot find out this incorrect usage ourselves especially in UI applications:

```csharp
await await Dispatcher.InvokeAsync(async ()=>
{
    // Ignored codes.
});
```

**Comment by CyrusNajmabadi** [comment]
1. This is not a language suggestion.  This is a suggestion about a new compiler warning.  As such, it should be in dotnet/roslyn.
2.  This would be a breaking change since previously acceptable code would now break.  However, it could come in a 'warning wave'.  Tagging @gafter for visibility.
3. Instead of needing the compiler to do this, you could always write your own Roslyn analyzer/fixer for this case.  The system and infrastructure is already there for this, and it's quite easy to do.

**Comment by walterlv** [comment]
@CyrusNajmabadi 
1. Do I need to move this issue to dotnet/Roslyn?
2. I think this warning should be embedded in first-party Roslyn analyzing because in most situations `await` lost may cause unexpected behavior.

**Comment by CyrusNajmabadi** [comment]
> Do I need to move this issue to dotnet/Roslyn?

That would be helpful :)

> I think this warning should be embedded in first-party Roslyn analyzing because in most situations await lost may cause unexpected behavior.

You can recommend this over at dotnet/Roslyn-Analyzers.  However, this could nto be part of the compiler itself because of hte break.  That said, i think dotnet/roslyn-analzyers would be amenable to this (esp. if you contributed the analyzer/fix yourself).  

Cheers!

**Comment by CyrusNajmabadi** [comment]
Scratch what i said about dotnet/roslyn.  This should go to https://github.com/dotnet/roslyn-analyzers

**Comment by lindexi** [comment]
I can write the code

                Foo foo = new Foo();
                await await await await await await await await await await await await await await await await await await await await foo;

    public class Foo : INotifyCompletion
    {
        public Foo GetAwaiter()
        {
            return new Foo();
        }

        public bool IsCompleted { get; }

        public Foo GetResult()
        {
            return this;
        }

        /// <inheritdoc />
        public void OnCompleted(Action continuation)
        {
        }
    }

**Comment by YairHalberstadt** [comment]
Closing as moved to roslyn
