### ISSUE TITLE
Sum types

### ISSUE THREAD

**Issue by hez2010** [dotnet/csharplang#2469]
Is there any way to write sum types (aka. Enum class, tagged union) in C#?
```haskell
data Weekday = Monday | Tuesday | .....
```

**Comment by HaloFour** [comment]
There are proposals to add that to the language:

https://github.com/dotnet/csharplang/issues/113

**Comment by gulshan** [comment]
Also see #399 for union types, not tagged union though.

**Comment by YairHalberstadt** [comment]
Closing as duplicate of https://github.com/dotnet/csharplang/issues/113 / https://github.com/dotnet/csharplang/discussions/399
