### ISSUE TITLE
Proposal: Target typed null coalescing (`??`) expression

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#2473]
See #2460

For a null coalescing expression  `e1 ?? e2`, when there is no common type for `e1` and `e2`, we define a new null coalescing expression conversion that permits an implicit conversion from the null coalescing expression to any type `T` for which both:

A) There is a conversion-from-expression from `e1` to `T`, or there is no such conversion, but the type of `e1` is a nullable value type of type `T1?` and there is an implicit conversion from `T1` to `T`.

B) There is a conversion-from-expression from `e2` to `T`. 

It is an error if a null coalescing expression neither has a common type between `e1` and `e2` nor is subject to a null coalescing expression conversion.

Eg, the following will become legal:

```csharp
M(List<int> list, uint? u)
{
    IEnumerable<int> x = list ?? Array.Empty<int>();

    long l = u ?? -1;
}
```

LDM Meeting:

https://github.com/dotnet/csharplang/blob/a3d67d141501101af9dbb9e8192ca8b4c717e316/meetings/2020/LDM-2020-09-09.md#proposal-target-typed-null-coalescing--expression

**Comment by YairHalberstadt** [comment]
@gafter

**Comment by TonyValenti** [comment]
Instead of target typing, why not have it look at the inheritance and interfaces implemented by both and thus allow var?

**Comment by TonyValenti** [comment]
Actually, instead of that, why not return a "T" type that is all shared interfaces and classes?

**Comment by YairHalberstadt** [comment]
@TonyValenti
This is consistent with the championed proposal for the conditional expression, #2460.

If that proposal were to change, I would change this one too.

**Comment by gulshan** [comment]
@TonyValenti what you are describing is Union type. Check #399

**Comment by gafter** [comment]
This proposal has been approved by the LDM for the next opportunity after C# 8.0 (resources permitting).

**Comment by Rubidium37** [comment]
> 
> 
> Instead of target typing, why not have it look at the inheritance and interfaces implemented by both and thus allow var?

Inheritance should be honored, interfaces should be ignored:

- When Multiple interfaces are implemented by both types, the compiler would find an ambiguity.

- On value types with a common interface, unwanted boxing could occur.

**Comment by Acerby** [comment]
Its nice to think that there is some especially clever logic for handling pre-existing a??b expressions. Why not keep this and just add a fall-back that in effect replaces (a??b) with ((a!=null)?a:b) in the case where it would currently fail with type incompatibility.
Current inconsistency between current handing of  ((a!=null)?a:b)  and  (a??b)  can be often be unexpected/confusing.

**Comment by 333fred** [comment]
This was [discussed in LDM](https://github.com/dotnet/csharplang/blob/a3d67d141501101af9dbb9e8192ca8b4c717e316/meetings/2020/LDM-2020-09-09.md#proposal-target-typed-null-coalescing--expression), and rejected:

> When attempting to spec and implement this, we found that it doesn't actually work well in practice, as ?? has a number of complicated rules around type resolution already and what part should be target-typed is confusing. We believe that, given the investigation, we won't be moving this one forward, and it moves to the Likely Never milestone.
