### ISSUE TITLE
Incorrect Warning CS8602 where using ReferenceEquals

### ISSUE THREAD

**Issue by sport-monkey** [dotnet/csharplang#2479]
The following generates two compiler warnings of `[CS8602] Possible dereference of a null reference.` As I'm running with `TreatWarningsAsErrors = true` this fails to build.

The compiler seems unaware that neither x or y cannot be null at `x.GetType() != y.GetType()`

```
    public class GenericComparer<TType> : IEqualityComparer<TType>
    {
        public bool Equals(TType x, TType y)
        {
            if (ReferenceEquals(x, y))
            {
                return true;
            }

            if (ReferenceEquals(null, x) || x.GetType() != y.GetType())
            {
                return false;
            }

            return Compare(x, y);
        }
    }
```

Changing to one of the below is a workaround, but Rider (correctly) tells me for `x?` that  `Conditional access qualifier expression is known not to be null` 
```
        public bool Equals(TType x, TType y)
        {
            if (ReferenceEquals(x, y))
            {
                return true;
            }

            if (ReferenceEquals(null, x) || x?.GetType() != y?.GetType())
            {
                return false;
            }

            return Properties().AreEqual(x, y);
        }
```

**Comment by svick** [comment]
I think this is a known issue that is tracked at https://github.com/dotnet/roslyn/issues/26761.

Though one thing I don't understand: why can't `y` be `null` in `y.GetType()`? You're not comparing `y` with `null` anywhere.

**Comment by sport-monkey** [comment]
Whoops, I should be comparing `y` and I don't know why I'm not.

**Comment by YairHalberstadt** [comment]
Closing as once you fix the bug pointed out by @svick, this currently works as expected.
