### ISSUE TITLE
Proposal: "not null" pattern or expression

### ISSUE THREAD

**Issue by savahmel** [dotnet/csharplang#2481]
The common null-check pattern: 
```C#
if (a.b.c != null) { Foo(a.b.c); } 
```
Has several potential issues: 
1. It throws an exception if a or a.b is null 
2. It is not null-safe since a or b or c can become null after the condition but before the method call
3. If != operator is overridden, it might not perform an actual null check
4. Some performance overhead 

All these issues are solved by the pattern: 

```C#
if (a?.b?.c is {} x) { Foo(x); } 
```

However, it is less elegant and more typing than the original one. 
Since the original code pattern is very common, to make the safer alternative more attractive it could be made cleaner and shorter. 

The proposal is to support one of the following syntaxes to behave exactly as the code above. 
```C#
if (a.b.c not null x) { Foo(x); }    // 1
if (a.b.c !null x) { Foo(x); }    // 2
if (a.b.c ! x) { Foo(x); }    // 3
if (a.b.c !! x) { Foo(x); }    // 4
if (a.b.c !? x) { Foo(x); }    // 5
if (a.b.c exists x) { Foo(x); }    // 6
if (a.b.c is some x) { Foo(x); }    // 7
```
x - is optional

**Comment by savahmel** [comment]
Sorry, the proposal was not well though of.

**Comment by theunrepentantgeek** [comment]
This sounded familiar so I went searching - seems that #246 & #27 are closely related.

**Comment by savahmel** [comment]
@theunrepentantgeek except for null-propagation

**Comment by savahmel** [comment]
Changing the meaning of dot operator based on the context must be a too drastic change. Withdrawing the proposal, also due to the negative feedback.
