### ISSUE TITLE
Proposal: add an F-bound or CRTP (CRGP?) constraint  for generic type parameters

### ISSUE THREAD

**Issue by TyreeJackson** [dotnet/csharplang#2495]
# Problem:

An abstract class, let's name `BaseClass`, is defined that contains a type parameter, let's name `TSubClass`, intended to represent the future subclass version of the `BaseClass<TSubClass>` itself.  Currently, we can constraint `TSubClass` to `BaseClass<TSubClass>` using `where TSubClass : BaseClass<TSubClass>` and ensure that TSubClass is itself **a** subclass of BaseClass.  However, we cannot guarantee that `TSubClass` is **the** subclass of `BaseClass<TSubClass>` that **is** deriving `BaseClass<TSubClass>`.  This makes it risky to assume that any given instance of a subclass of `BaseClass<TSubClass>` is actually `TSubClass` within any member of `BaseClass<TSubClass>`.  Here is an example illustrating the point:

``` cs
public class BaseClass<TSubClass> where TSubClass : BaseClass<TSubClass>
{
    public TSubClass DoSomething()
    {
        /* do something interesting */
        return this; // <- currently results in 'error CS0266: Cannot implicitly 
                     // convert type 'BaseClass<TSubClass>' to 'TSubClass'. An 
                     // explicit conversion exists (are you missing a cast?)' 
    }
}

public class SubClass1 : BaseClass<SubClass1>
{
    public SubClass1 DoSomethingSpecific()
    {
        /* do something interesting */
        return this;
    }
}

public class SubClass2 : BaseClass<SubClass1>
{
    public SubClass2 DoSomethingElseSpecific()
    {
        /* do something interesting */
        return this;
    }
}
```

The first obvious usage for being able to implicity return TSubClass reliably is for the construction of _fluent interface_ classes that aggregate information where the sub classes are expected to expand the _language_.  Of course, there are other uses like where `BaseClass<TSubClass>` might attempt to pass itself as an argument to another method where the parameter is typed to `TSubClass` with the same constraint `where TSubClass : BaseClass<TSubClass>`.  The only semi safe option in these cases is to validate that `this` is a type of `TSubClass` and throw a runtime exception if it is not.  It would be far more ideal if we could know this at compile time.  Logically, there should be nothing to stop the compiler from being able to ensure this safety with a proper constraint.  Which leads me to...
# A proposal for a new type constraint:

Introduce a new generic type constraint to enforce the following compile time checks:
1. Enforce that the constrained type parameter must subclass the class where the type parameter is defined (the same as specifying `TSubClass : BaseClass<TSubClass>` [note that this is redundant with check 3, but I'm including it to associate this specialized constraint with the already existing subclass constraint type];
2. Enforce that the class where the type parameter is defined must be marked abstract as the constraint would not make sense on a concrete or sealed class;
3. Enforce either...
   - ... that the type argument for the constrained type parameter must be **the** class type that is deriving the BaseClass and not some other class type that has already derived the BaseClass allowing the compiler to either assign the constrained type to `this` instead of the abstract form or validate that `this` implicitly converts to the constrained type;
   - ... or that the type argument for the constrained type parameter must also be a type parameter on the subclass that is constrained with the same new type constraint and enforce the same checks upon the subclass type parameter;

As a suggestion for the keyword for the new type constraint might I offer up the following three possibilities:
1. `this`; example usage: `BaseClass<TSubClass> where TSubClass : this {}`
2. `subclassed`; example usage: `BaseClass<TSubClass> where TSubClass : subclassed {}`
3. `concrete`; example usage: `BaseClass<TSubClass> where TSubClass : concrete {}`

With this new constraint the following would be possible:

``` cs
// Demonstrates an invalid declared use of the new proposed type constraint (using
// 'this' as the constraint keyword) on a non-compliant base class that is not marked
// abstract
public class NonAbstractBaseClass<TSubClass>
    where TSubClass : this // <- would result in error CS????: The type
    // 'NonAbstractBaseClass<TSubClass>' must be marked 
    // abstract in order to use the 'this' type constraint on a 
    // type argument defined on the class.
{
}

// Demonstrates a valid declared use of the new proposed type constraint (using 'this'
// as the constraint keyword)
public abstract class BaseClass<TSubClass>
    where TSubClass : this
{
    public TSubClass DoSomething()
    {
        /* do something interesting */
        return this; // <- would no longer throw a compilation error
    }
}

// Demonstrates a class that provides a legal type argument for the 'this'
// constrained type parameter
public class SubClass1 : BaseClass<SubClass1>
{
    public SubClass1 DoSomethingSpecific()
    {
        /* do something interesting */
        return this;
    }
}

// Demonstrates a class that does not provide a legal type argument for the 'this'
// constrained type parameter
public class SubClass2 : BaseClass<SubClass1> // <- would result in error CS0311: The 
    // type 'SubClass1' cannot be used as type 
    // parameter 'TSubClass' in the generic 
    // type or method 'BaseClass<TSubClass>'.
    // There is no implicit reference 
    // conversion from 'SubClass2' to 
    // 'SubClass1'
{
    public SubClass2 DoSomethingElseSpecific()
    {
        /* do something interesting */
        return this;
    }
}

// Demonstrates an intermediate class that provides a legal type argument for the
// 'this' constrained type parameter by supplying a type parameter of its class that
// is also constrained with the 'this' type constraint
public abstract class IntermediateClass<TSubClass> : BaseClass<TSubClass>
    where TSubClass : this
    {
        public TSubClass DoSomethingIntermediateLike()
        {
            /* do something interesting */
            return this;
        }
    }

// Demonstrates a class that provides a legal type argument for the 'this'
// constrained type parameter to an intermediate abstract generic class that
// passes the type parameter as a type argument to another 'this' constrained
// type parameter of an abstract generic class
public class SubClass3 : IntermediateClass<SubClass3>
{
    public SubClass3 DoSomethingEvenMoreSpecific()
    {
        /* do something interesting */
        return this;
    }
}

// Demonstrates instantiation of the legally defined classes, SubClass1 and
// SubClass3 and verifies that the type resolution of the return parameters works
// correctly in support of the definition of fluent interface like methods on the
// generic classes.
public class TestSubClasses
{
    public void TestThem()
    {
        var subClass1 = new SubClass1();
        var subClass3 = new SubClass3();

        subClass1.DoSomething()
            .DoSomethingSpecific();

        subClass3.DoSomething()
            .DoSomethingIntermediateLike()
            .DoSomethingEvenMoreSpecific();

    }
}
```

_Note that since all of the checks would be handled at compile time both for the definition of the abstract generic class with the constrained generic type parameter and for the definition of the consuming subclass providing the constraint checked generic type argument, I don't see a reason why the CLR would need to be updated to support this new constraint type.  All uses of 'this' within the abstract class would be checked by the compiler and which could emit the proper IL.  Enforcing that the subclass must be abstract, and that the type argument must be the subclass that is being defined or another constrained type parameter on the subclass could also be checked by the compiler._

**Comment by GeeLaw** [comment]
@TyreeJackson There isn't a circular base dependency, since the hierarchy would be as follows:

- `BaseClass<SubClass2>` is a `System.Object`
- `SubClass1` is a `BaseClass<SubClass2>`
- `SubClass2` is a `SubClass1`

However, the example provided by @phi1010 should result in compiler error, because `abstract class B<T> where T : this` should have the following semantics:

```csharp
// This must return true for all invocations.
static bool Check<T>(B<T> that)
{
  // that is T or that is null
  return ReferenceEquals(that as T, that);
}
```

Now consider the aforementioned example, we would have `Check<SubClass2>(new SubClass1()) == false`.

---

A more problematic example is as follows:

```csharp
public abstract class Base<T> where T : this { }
public abstract class Helper<T> : Base<Derived<T>> { }
public class Derived<T> : Helper<T> { }
public sealed class FurtherDerived<T> : Derived<T> { }
``` 

You would want this to succeed for the sake for intermediate helpers and further derivations. However, since no constraint is put on `T` of `Helper`, one might write:

```csharp
// BOOM!
public abstract class Evil<T> : Helper<T> { }
```

Unless the compiler and the runtime traverse the full type hierarchy whenever a type is instantiated, it can never find out the constraint violation. Currently, only the directly related types need to be checked when instantiating a type, and adding `T : this` would downgrade the efficiency a lot.

I don't see an elegant fix to the constraint specs for now. Any thoughts would be appreciated!

---

I would like to mention a work around, using what I call companion `struct`s. It also provides the capability of static polymorphism without virtual dispatching, and provides efficient run-time check of correct inheritance relationship. Example below,

```csharp
public abstract class CRTP<T, TOverrides>
  where TOverrides : struct, CRTP<T, TOverrides>.IOverrides
{
  public interface IOverrides
  {
    T That { get; }
    void SetThat(T that);
    void StaticPolymorphism();
  }
  protected TOverrides MyOverrides;
  protected CRTP()
  {
    MyOverrides.SetThat((T)this);
  }
  T Fluent()
  {
    MyOverrides.StaticPolymorphism();
    return MyOverrides.That;
  }
}

public class Example : CRTP<Example, Example.Overrides>
{
  public struct Overrides : IOverrides
  {
    public Example That { get; private set; }
    // MUST NOT implement as "That = that;".
    public void SetThat(Example that) { that.MyOverrides.That = that; }
    // MUST NOT succeed if That is null.
    public void StaticPolymorphism() { That.DoWork(); }
  }
  private void DoWork() { Console.WriteLine("No virtual method call!"); }
}

// new Mistake() throws InvalidCastException.
// This is also a fairly obvious error.
public class Mistake : CRTP<Example, Example.Overrides> { }
// Valid if Example inherits Possible, or Possible could be an optional helper class.
public abstract class Possible : CRTP<Example, Example.Overrides> { }
// Aside from the obvious error, this will not compile since
// Example.Overrides does NOT implement CRTP<Mistake2, Example.Overrides>.IOverrides.
public abstract class Mistake2 : CRTP<Mistake2, Example.Overrides> { }

// A more generic helper might take the actual override struct as a parameter.
public abstract class Helper<T> : CRTP<Derived<T>, Derived<T>.Overrides> { }
public class Derived<T> : Helper<T>
{
  public struct Overrides : IOverrides { /* blah */ }
}
```

I recently discovered this trick (probably not the first to do so), and documented it [in my blog](https://geelaw.blog/entries/csharp-crtp-static-polymorphism-friendship/).

**Comment by 333fred** [comment]
Closing as effectively a duplicate of https://github.com/dotnet/csharplang/discussions/169.
