### ISSUE TITLE
Proposal: Support covariant generic classes and structs

### ISSUE THREAD

**Issue by PhilipCavanagh** [dotnet/csharplang#2498]
With C# moving towards a more functional approach, I'm finding myself using monad types more frequently. Types like `Task<T>`, `Lazy<T>`, `Option<T>`, `Maybe<T>`, etc. would benefit from being allowed to be covariant in their generic types. They are also frequently the sort of types that would benefit from being structs, which means that having them implement a covariant interface loses much of their benefit.

This proposal would alleviate a particular pain in would-be covariant types which contain an async method:

```
public interface IAsyncValueGenerator<T>
{
    Task<T> GenerateValueAsync();
}
```

If `Task<T>` could be made covariant, then so could the interface.

Specifically, a class or struct can be declared as covariant in its generic parameter only if that parameter type only appears in out positions. A simple test for this is to strip out all access modifiers, implementations, fields and constructors and changing the class or struct to an interface. If the interface could be made covariant, then so can the original class/struct.

**Comment by Frassle** [comment]
Variance on a struct might still make sense from a type-safety point of view. Take ImmutableArray<T> structs, you should be able to assign an ImmutableArray<string> to ImmutableArray<object>, the fact that the backing array is still a string[] isn't a problem all the bits are the same and this would be type safe.

**Comment by egil** [comment]
Would this not be relevant for `readonly struct` as well?

**Comment by PCavan** [comment]
It would - a struct being readonly would automatically qualify it for covariance on each of its type arguments.

**Comment by Joe4evr** [comment]
@PCavan I'd say such types should still explicitly declare to be variant, just to avoid (potential) strange behavior changes, but that's about the only nit I see with that.

**Comment by PCavan** [comment]
@Joe4evr I can't think of an example where automatically adding covariance to readonly structs would change behaviour (which is not to say there isn't one).

Given that readonly structs aren't covariant now, any compiling code must be using the exact same compile-time type argument as the struct instantiation, and because that option is guaranteed to be available now, the compiler would continue to choose that option even if the struct were covariant as the exact match is always the best match.

```
public readonly struct Option<T> { ... }

public interface IOptionalAcceptor
{
    void Accept(Option<string> x);
    void Accept(Option<object> x);
    void Accept(Option<IComparable> x);
}

...

Option<string> x = Option.From("Hello world");
IOptionalAcceptor a = ...;

// This will choose Accept(Option<string>).
// Removing Accept(Option<string>>) will fail to compile with or without auto-covariant readonly structs (ambiguous method call vs no valid method).
a.Accept(x); 
```

On the other hand, preferring explicitness on these things seems to be C#'s way of doing things (e.g. having to use `out`, `ref` at call sites), so maybe it ought to be opt-in.

**Comment by yaakov-h** [comment]
IIRC, automatically adding covariance would break readonly structs that have mutable storage from another object, e.g.:

```cs
using System.Collections.Generic;

public readonly struct Listy<T> {
    
    public Listy(List<T> list) => this.list = list;
    
    readonly List<T> list;
    
    public T Get(int i) => list[i];
    public void Add(T t) => list.Add(t);
}
```

**Comment by PCavan** [comment]
@yaakov-h Ah, good point. I was surprised that was legal C# code when I read it, but this is another case of "Read-only does not mean immutable".

**Comment by ufcpp** [comment]
Could structs be covariant if all of its fields are covariant?

**Comment by andre-ss6** [comment]
This would marry well with records (#89) I think. Immutability comes for free, which makes it that easier to implement covariant classes. 

And it's currently a pain to deal with this limitation when you want to use generic variance on "data" classes (without behavior/logic), as you have to use interfaces, and the code starts looking quite insane when you have interfaces all over for just passing data around.

**Comment by PCavan** [comment]
@andre-ss6 Yes it would, but I was considering whether immutability implies generic covariance. The `Identity` method above would be valid on an immutable struct, but would exclude the struct from covariance on `T`.

**Comment by jam40jeff** [comment]
> I wonder if custom async builders would allow for a variant `Task<T>` analog.

https://github.com/jam40jeff/ITask
