### ISSUE TITLE
dynamic interface Proposal.

### ISSUE THREAD

**Issue by MiddleTommy** [dotnet/csharplang#2499]
I have always thought duck typing was a feature worth looking at. I understand how it doesn't work well in a typed language and quickly becomes like javascript. The dynamic keyword was the compromise but that looses compiler checking and allows simple type checking errors. I would like to propose a new Feature I call dynamic interfaces:
The syntax would be like this

dynamic interface IFoo{...}

The difference between a standard interface and a dynamic interface is that a dynamic interface never gets implemented. It is mainly used by the compiler and intellisense.

Example:

``` C#
//From third party library
public class Existing 
{
    public string Bar {get;set;}
}

//From another library
public class Another
{
   public string Bar {get;set;}
}

// your code
public dynamic interface IFoo
{
   string Bar {get;set;}
}

public class Test
{
      public void TestBar(IFoo foo)
      {
              var str = foo.Bar;
              Console.WriteLine($"Bar = {str}");
      }
      public void Test()
      {
              var ex = new Existing();
              TestBar(ex);

              var an = new Another();
              TestBar(an);
      }

}
```

Where this could really get interesting is with Extension Methods. You could extend objects based on their Methods and Properties instead of their class inheritance. 

This also fits nicely with Pattern Matching. It would allow you to pre-define your Pattern with a dynamic interface and then simply use the "is" operator in a switch statement. This would take pattern matching to the next level.

``` C#
var ex = new Existing();
switch(ex)
{
     case ex is IFoo:
            .....
            break;
}
```

**Comment by kulics** [comment]
I also really need this feature of the dynamic interface.
I wrote a language for .NET, which simplifies a lot of syntax and hopes to be a .NET tool that is more suitable for getting started.
[https://github.com/kulics/xs](Xs Lang)
One of the most needed features is the dynamic interface, which makes the language syntax simpler and makes it easier to assemble interesting features.
Regardless of whether this proposal has the opportunity to be promoted, at least I have to declare my support for this feature.

**Comment by bbarry** [comment]
This looks like a duplicate of #164 to me.

**Comment by YairHalberstadt** [comment]
@bbarry 
This proposal was opened 3 years ago in Roslyn, and moved by gafter 14 days ago.

**Comment by HaloFour** [comment]
I have a feeling that it falls under the umbrella with shapes/type-classes/extension-interfaces/whatever-its-called-today.

@kulics 

Does your language transpile to C#?  If not I'm not sure how these proposals would benefit your language.  You could follow whatever IL generation lead the C# team decides to do, but even if CLR changes end up on the table to help in facilitating this I doubt it will ever be as transparent as just passing some arbitrary reference which does not implement an interface to a method that expects an instance of that interface.  I expect the compiler will need to be involved at some level to generate a bridge/witness type.

**Comment by kulics** [comment]
@HaloFour 
I think the dynamic interface is a more suitable name for C#, which does not increase the C# keyword, but also describes its function, which is very suitable.

Regardless of what it is called, it is increasingly a feature that can have a significant impact on C#, and its importance is not lower than the generics of the year.

I sincerely hope that one day I will hear exciting news. Maybe this process has to be promoted by everyone who has this desire.

My language is currently translated to C#, I think it is not ready to translate to IL, it still needs to be grammatically tested, preferably the opinions of C# users.
Although I can implement dynamic interface features inside this language, if C# supports this feature, it will be easier for the two languages to interact, so I also hope that C# can support it.

If you are interested, please feel free to browse the grammar of this language. I will be very happy if I can receive your opinion.

**Comment by HaloFour** [comment]
@kulics 

> I think the dynamic interface is a more suitable name for C#, which does not increase the C# keyword, but also describes its function, which is very suitable.

I personally don't think "dynamic interfaces" is the right description as the feature as described isn't about introducing new kinds of interfaces but instead about ways of taking existing interfaces and existing types and defining the extensions that allows that type to appear to implement that interface.  "Extension implementation" is probably a better term, although exactly what it's called is a lot less relevant to what it actually does.

I think this is the most recent exploration on the subject:  https://github.com/dotnet/csharplang/issues/1711

This is all very early in design, though, so it could go in any direction.

**Comment by marksmeltzer** [comment]
Is this a very different concept from duck typing? 🤔

**Comment by kulics** [comment]
@HaloFour 
"Extension implementation" are easier to think of as using extensions to make classes implement interfaces.
But the interface design discussed in this topic is closer to the implicit interface of golang or the concept of C++.

In fact, we just want a duck type that supports static checking, no matter what its name is. We want this feature if we want to get the benefits of a duck type without losing the benefits of a strong type.

This may be a trend, more and more people will consider this, I am very concerned about the subsequent development.

**Comment by Joe4evr** [comment]
> In fact, we just want a duck type that supports static checking, no matter what its name is. We want this feature if we want to get the benefits of a duck type without losing the benefits of a strong type.

Then Shapes is 100% what you want and you should keep an eye out for what's gonna happen in that space.

**Comment by kulics** [comment]
@Joe4evr 
Yes, I am also very concerned about it, I hope the C# team can pay attention to our needs.

**Comment by HaloFour** [comment]
@kulics 

> "Extension implementation" are easier to think of as using extensions to make classes implement interfaces.

Yes.  This is a good thing.

> But the interface design discussed in this topic is closer to the implicit interface of golang or the concept of C++.

"Extension implementation" solves both, and has several other distinct advantages.

1. You don't have to define a new type of interface.  The feature would work with all existing interfaces and all existing APIs expecting those interfaces.  Adding a new "dynamic interface" or "shape" type splits the ecosystem and provides no immediate benefits to users.
2. It makes it much easier to bridge the gap between a type that implements 90% of a given interface via extension members.  This is true even if you don't own and can't modify either the interface or the target type.

It's also possible that if the type exposes all of the members needed to implement a given interface that the "witness type" can automatically be created by the compiler, which effectively covers duck typing as well.  If the team can enable more scenarios that's something that is definitely in their interest.

**Comment by marksmeltzer** [comment]
@HaloFour I was reading up on #1711 -- a very fascinating discussion with lots of great ideas. I am not too thrilled about the concept of witness types though, unless they could be implemented as free abstractions. Until we can get the JIT improvements to cast an interface implemented on struct without boxing, I am assuming the witness will need to be allocated.

It is probably worth the trade off even if an allocation is required. However, what's happening there is essentially an automatically generated implementation of a decorator pattern and there will be a bit of a performance trade off due to the extra layer of indirection (two pointers instead of one).

While I have wanted duck typing for a while (which doesn't necessarily require a witness), the concept of being able to attach arbitrary interfaces to existing classes via extensions is a very cool concept -- it does seem to require something like a witness since there could be multiple extensions that apply the same interface with a different implementation. So the witness is required to disambiguate, in principle. So in that case, the witness is basically an implementation of the classic decorator pattern.

I would presume that one could even override a class' default implementation for an interface to use an extension instead with an appropriately configured witness (not sure what the syntax would look like -- maybe the interface extension would be invoked explicitly in that case).

**Comment by marksmeltzer** [comment]
@kulics to solve the problem for your transpiled language in the meantime, you can just generate decorated classes to take whatever input and implement whatever interface on the decorator and inject the user defined logic into the decorator's interface implementation. Easy peasy. No fundamental changes are needed for C# to pull that off. (You could use the same approach even for emitting LLVM or CLI op code.)

Most language syntax is just a sugary coating around design patterns anyway.

**Comment by HaloFour** [comment]
@marksmeltzer 

> Until we can get the JIT improvements to cast an interface implemented on struct without boxing, I am assuming the witness will need to be allocated.

The witness is a struct, so there is no additional allocation.  They also only contain pass-through methods to the real members, which are very easily inlined by the JIT.  That approach was chosen specifically because it should be a zero-cost abstraction.
