### ISSUE TITLE
Temporary transform type in specific block

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#2501]
As oppose to feature Is-As from pattern matching https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md

``` C#
if (expr is string s) {
    // code using s
}
```

I would like to propose syntax for temporary transform type of variable in a block

``` C#
object obj;
var(obj as string) {
    int l0 = obj.Length; // No error, obj temporarily be string in this block
}

int l1 = obj.Length; // Compiler error
```

It work like `if(a is Type)` in kotlin that would make compiler see the variable `a` in `if` block as a type specified automatically. But since that would be a breaking change in C# so it could be another syntax that never been used before

If the object is not that type, or null, then it would skip the block like it testing `if(obj is string)`

Also it would be possible for

``` C#
var(s = obj as string) {
    // code using s , obj is still object. but not come in this block if s is null
}
```

ps. Another idea is reusing keyword `try` in `if`

``` C#
if(obj try string && !string.IsNullOrWhiteSpace(obj)) {  // obj would become string after try expression
    int l0 = obj.Length;
}
```

ps2. Another keyword would be better? `for(obj as string) { }` `const(obj as string) { }` `let(obj as string) { }`
or maybe we don't need keyword

``` C#
(obj as string)
{
    int l0 = obj.Length;
}
```

**Comment by TonyValenti** [comment]
This makes me think of nullability tracking except with types.

**Comment by TonyValenti** [comment]
Also, if this is implemented, I think that the type of obj in the block should be the union of its current type and whatever types/interfaces were fulfilled in order to fulfill the IF statement.
