### ISSUE TITLE
Pre- Posthook auto generated getter and setter functions

### ISSUE THREAD

**Issue by Spacefish** [dotnet/csharplang#2502]
Could we have something like

`
[CompilerServices.PostSetHook(MyClass.PostSet)]
class MyClass : INotifyPropertyChanged {
  public event PropertyChangedEventHandler PropertyChanged;

  string PropertyA {get; set;}
  string PropertyB {get; set;}

  internal static void PostSet(object instance, string propertyName, object value) {
       instance.PropertyChanged?.Invoke(instance, new PropertyChangedEventArgs(propertyName));
  }
}
`

The compiler should inline the postSet function to every autogenerated Property Setter. This should be availiable for set get add remove as pre and post actions.. So one does not have to implement it for each and every property if they all do the same!

**Comment by MechanoRealist** [comment]
Any progress on this? 🤔

**Comment by HaloFour** [comment]
Nobody from the language team has championed to take this proposal through language design.  Without a champion there will not be progress on this.
