### ISSUE TITLE
IRefEnumerable support to foreach and array

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#2503]
Follow up from return ref feature. I would like to have `IRefEnumerable<T>` interface included in core C#

``` C#
public interface IRefEnumerable<T>
{
    IRefEnumerator<T> GetEnumerator()
}

public interface IRefEnumerator<T>
{
    ref T Current { get; }
    bool MoveNext { get; }
}
```

Which should be implemented natively to array. It should support `foreach` too. And there should be whole set of Linq implementation support ref argument

But, well, ref linq may be need to ask in corefx (I was once create #7978). But aside from that, native array and foreach support on this feature would require roslyn support I think

**Comment by omariom** [comment]
[It is supported for pattern based enumerables](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABADAAgwRgG4BYAKAwGY8AmHAYRwG8ydW8qMUcBZACgEocLNs1JtxOAMoAHAIYA7ADwBLeQBcAfDgDOc+TgC8OeTADuOVWoDaAVgC6JMRNbDnAM2gxZYABY5esG4W6jgAbsE6evyuEqLOrAC+MeLJbB6w3n4BMEGWYREm5nQQEAA2AtFOznHxSVU4dSn12mpQAK5gavQlpTE1zpQ4AKLybQC2MFCyatA4AOIwaiPjk9PQAoZahcOjE1MzUAKO8UL14oMt7Z07K/vQqaz9J+w4wD08EKEwAHIwCGobAxaVptGDHZ4uM7xQaBYJdOhtKCwEJAnCw3jbSxWfB2fhWLAOB4NGJ1BJAA===)
