### ISSUE TITLE
 reading selected nodes of the xml file

### ISSUE THREAD

**Issue by KodowyWojtek** [dotnet/csharplang#2508]
Hello everybody. I would like to ask is it possible to read selected nodes of the xml file? C#

If i load xml file which contains sth like that:

```
<object>
<field>
<name> astor </name>
<value>int </value>
</field>
</object>
```

I would like to load only object, field, name but i dont want to load value. Is it possible?

**Comment by YairHalberstadt** [comment]
https://github.com/dotnet/csharplang/issues/2491#issuecomment-489735754

**Comment by YairHalberstadt** [comment]
Closing as not relevant to this repo
