### ISSUE TITLE
[Proposal] Create a way of having a member with a name that is the same as its enclosing type

### ISSUE THREAD

**Issue by hamarb123** [dotnet/csharplang#2511]
Currently, the following code is not possible (this code in particular should not ever be posilble as it could be ambiguous): 
```c#
public class ClassName
{
    public void ClassName()
    {
        DoStuffHere();
    }
}
```
This is because the compiler doesn't allow you to have a member with the same name as the enclosing type, because that is how the constructor is declared in C# `public ClassName() { ConstructorCodeHere() }`
There is a similar problem in VB.NET, which is the `New()` method (VB.NET constructor), for example:
```vb.net
Public Class ClassName
    Public Sub New()
    End Sub
End Class
```
declares a class named `ClassName`, with a constructor that takes 0 arguments.
Note: members named `ClassName` are allowed in `ClassName` in VB.NET (but not C#)

BUT!!! VB.NET has a solution for naming things with keywords, such as `Object` or `Integer`, which is to enclose the name in square brackets [], for example:
```vb.net
Public Class ClassName
    Public Sub Integer()
    End Sub
End Class
```
is not allowed, as `Integer` is a keyword, but
```vb.net
Public Class ClassName
    Public Sub [Integer]()
    End Sub
End Class
```
is allowed, and will compile into a `void` named `Integer` (without the square brackets), and can be accessed in C# as simply `Integer`, as it is not a keyword in C#.
In C#, there is a similar pattern, which is to add a @ character to the start of the member name, for example:
```c#
public class ClassName
{
    int string => 0;
}
```
is not allowed, whereas
```c#
public class ClassName
{
    int @string => 0;
}
```
is allowed and will compile into `string` instead of `@string`, as the @ symbol simply informs the compiler to not treat it as a keyword.
The difference of this pattern between VB.NET and C# is that in VB.NET, the following is completely legal:
```vb.net
Public Class ClassName
    Public Sub [New]()
    End Sub
End Class
```
and will compile as expected, whereas in C#, the following is not legal:
```c#
public class ClassName
{
    public void @ClassName()
    {
    }
}
```
and the compiler simply complains saying "error CS0542: 'ClassName': member names cannot be the same as their enclosing type".
Using the @ symbol removes the ambiguity, so it should be allowed.
The C# language specification should allow this, if the member has an @ symbol at the start, it should be compiled without the @ symbol (just like everything else that starts with one).
The example above should be callable like so:
```c#
ClassName variable1 = new ClassName();
variable1.@ClassName();
```
which is the same usage as calling other @ members.

The reason I specifically want this is because I have old code that requires libraries to have a `Load()` method in a `Load` class, if the method and class are not named exactly this, it will not work, so currently I am limited to 2 options: a VB.NET wrapper OR VB.NET code only. I would like to write this library completely in C#, and this is how it can be done. I'm sure there would also be other applications for this.

**Comment by FiniteReality** [comment]
This seems like a very edge-case usecase and more likely to cause maintainability issues than it is to solve.

Is there any reason you can't just rename the class or method? Using your example, a `Load` class seems extremely vague... What does it load? If you're grouping up multiple "loaders", couldn't you use, say, `Loaders.LoadMyTypes()`?

**Comment by hamarb123** [comment]
@FiniteReality firstly, the old library uses reflection to lookup the class 'Load' and then the void 'Load()' in that class, it cannot be changed for various reasons. Secondly, I don't think it would be that hard to change as you only have to change the test that says it cannot be named the same as the enclosing type.
Also, it appears that C# already can call these functions if they get declared, for example:
In VB.NET
```vb.net
Public Class Class1
    Public Sub Class1()
        Console.WriteLine("Message1")
    End Sub
End Class
```
and in C# (referencing VB.NET)
```c#
Class1 c = new Class1();
c.Class1();
```
will compile and produce the output as expected.
So all that needs to be changed in theory is this line here: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L1188
to allow it if it was declared with an @ symbol.
Also the closing and reopening was an accident.
