### ISSUE TITLE
Shortcut for  "object == null"

### ISSUE THREAD

**Issue by reschjo** [dotnet/csharplang#2525]
I very oftend use "if(Object == null) or if(Object != null)" in my sourcecode.
It would be great to have a shortcut like "if(?Object)" for that.
The return value would be "true" if the Object exists (not null) or "false" if the object doesn't exist (is null)

**Comment by tpetrina** [comment]
For the former you can use `if (o is null)`. For the latter use `if (o is object)`

**Comment by HaloFour** [comment]
Or `if (o is {})` which will work for checking that `o` is not null in C# 8.0 when that is released

**Comment by DavidArno** [comment]
And of course, when we get nullable reference types with C# 8, the need to scatter `if (o is null)` throughout the code should largely go away.

**Comment by VanKrock** [comment]
You can to use ?? ?: ?.

**Comment by yaakov-h** [comment]
Duplicate of #545, which was closed.

**Comment by reschjo** [comment]
@yaakov-h  you are right. I closed the duplicated issue.

ToAll: Thanks for your answers !
