### ISSUE TITLE
Proposal: C# code rewrite/lowering at design/compile time

### ISSUE THREAD

**Issue by msedi** [dotnet/csharplang#2526]
I'm sure someone has asked for this before but I couldn't find any reference to it.

**Background**
In our development team we are often in situations where the C# language support is not enough and some things can be expressed in a shorter form. An example is the newly introduced `Range`, where the syntax `m..n` is translated into a `Range` struct that can further be used in following methods. This is very handy, but is "hardcoded" in the roslyn process.

As explained, we sometimes need something similar, for example, years ago, we already created something similar to Range with a MATLAB-like syntax, since this is the origin where our team came from. We wanted to make it as simple as possible and recreated the MATLAB/matrix style access by creating our own Matrix class.

The problem was, MATLAB supported a very unique mini language to index the elements inside the matrix. Just as an example, 1:10, 1:1:10, 1:end, etc. The details don't matter, but the problem was that C# doesn't understand this mini language (of course). So we needed to find a way bring this into the language. Since there was no way, we decided to write it as a string and parse the string. So `1:10` was then `"1:10"` which of course works, but is not the nicest solution, since we only get runtime errors, but no compile time errors.

**Proposal**
So finally, I suggest to have a roslyn code rewrite/lowering/transform possibility that is able to hook into the parsing process in front of the real roslyn process. Having this, I would be able to transform the code, for example 1:10 can be created in a similar way, `Range` is rewritten.

The transformation process should be pluggable and always run in the design time compilation and the real compilation. Sure, some problems might occur and the transfomation process should not take too long so that the real roslyn process is not disturbed. But currently tools like PostSharp or Fody, etc. have to attach to the process afterwards and disassemble the code, which might be even worse.

**Comment by CyrusNajmabadi** [comment]
> that is able to hook into the parsing process in front of the real roslyn process.

This is almost certainly a non-starter.  Parsing is a non-trivial part of roslyn, and has deep implications for things like being able to do incremental processing quickly and, most importantly, correctly.  

> Do you see any solution with the current possibilies we have with Roslyn? Let's say a code rewrite afterwards?

Yes, you could certainly write your own tool that uses roslyn that takes in normal c# code (perhaps annotated with string/comments/attributes), and spits out more C# code that is then compiled normally.

**Comment by msedi** [comment]
Related to: [#2526](https://github.com/dotnet/csharplang/issues/2526)
