### ISSUE TITLE
[Umbrella] Generics Improvements

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#253]
## default type parameters

Proposal: https://github.com/dotnet/roslyn/issues/6248

```cs
class X<TService = DefaultService> {}
```

Since types with identical names can be defined with different arities, it might be easier to require the diamond syntax (or missing type arguments) to disambiguate type arities. But not requiring it would provide source-compat such that you can add a type parameter with a default value, without changing use sites.
```cs
class Y : X {} // X<DefaultService>
```
One possible restriction to simplify binding rules is to disallow identical type names where there exists a type with default type parameters.
```cs
//ERROR
class X {}
class X<T = C> {}
```
However, even with this restriction there can be ambiguous type names, in those cases we prefer the non-generic type.
```cs
namespace N0 { class X {} }
namespace N1 { class X<T = C> {} }
namespace N2 {
    using N0;
    using N1;
    class C : X {} // N0.X
}
```
If we want to select the default parameter we can use `X<>` syntax or named type arguments.

We can also disallow leading default type parameters just like method default parameters,

```cs
class X<T = C, U> {} // ERROR
```

#### `this` as default type parameter

In some cases it's useful to define a default type parameter of the inheriting type (if any).

```cs

interface IEquitable<T = this> {}

class X : IEquitable {} // IEquitable<X>

```
It'd be nice to also constrain such types to the inheriting type, in case that it's explicitly specified. (https://github.com/dotnet/csharplang/issues/169)

```cs
interface IEquitable<T = this> where T : this {}

class X : IEquitable<Y> {} // ERROR

```

But this would be a C#-only restriction as CLR does not support such constraints. Note that this constraint only applies to the derived types so it might be preferable to restrict it to interfaces and abstract classes.

## Named type arguments

Proposal: https://github.com/dotnet/roslyn/issues/6207

Named type arguments are useful for various use cases:

- When only a few type parameters cannot be inferred.

```cs
U F<T, U>(T t) { .. }

var x = F<U:short>(1); // F<int, short>

```

- To specify a few default type parameters,

```cs
class C<T = X, U = Y> {}

new C<U: Z>();
```

- Or just for better readability,

```cs
var x = F<TResult: int>();

```

Again, just like named arguments, named type arguments do not need to be in the same order that they are declared, as long as all non-default type parameters are specified.

```cs
void F<T, U, V = C>() {}

F<U: A, T: B>();
```

It will be possible to mix positional and named type arguments,

```cs
F<A, U:B>();
```

## Inline type parameter constraints

Proposal: https://github.com/dotnet/roslyn/issues/7671

With numerous type parameters, type constraints require duplicating every type parameter to the point that it's somehow confusing, 

```cs
internal abstract class AbstractUseCoalesceExpressionForNullableDiagnosticAnalyzer<
  TSyntaxKind,
  TExpressionSyntax,
  TConditionalExpressionSyntax,
  TBinaryExpressionSyntax,
  TMemberAccessExpression,
  TPrefixUnaryExpressinSyntax> : AbstractCodeStyleDiagnosticAnalyzer
  where TSyntaxKind : struct
  where TExpressionSyntax : SyntaxNode
  where TConditionalExpressionSyntax : TExpressionSyntax
  where TBinaryExpressionSyntax : TExpressionSyntax
  where TMemberAccessExpression : TExpressionSyntax
  where TPrefixUnaryExpressinSyntax : TExpressinSyntax
```

Inlining type parameters could significantly reduce noise around the type declaration,
```cs
internal abstract class AbstractUseCoalesceExpressionForNullableDiagnosticAnalyzer<
  TSyntaxKind : struct,
  TExpressionSyntax : SyntaxNode,
  TConditionalExpressionSyntax : TExpressionSyntax,
  TBinaryExpressionSyntax : TExpressionSyntax,
  TMemberAccessExpression : TExpressionSyntax,
  TPrefixUnaryExpressinSyntax : TExpressionSyntax> : AbstractCodeStyleDiagnosticAnalyzer
```
This syntax would bring type parameter constraints closer to their declaration,
```cs
void F<T, U : IEnumerable<T>>(U source) {}
```

Inlined type constraints can be mixed with type parameters, e.g.

```cs
class IEquitable<T : this = this> {}
```

Multiple type constraints can be inlined using "intersection types", using whatever syntax that they're going to use,
```cs
void F<T : Interface1 | Interface2>() {}
```

However, it might be actually preferable to only allow "simple" type constraints in this manner.

## Inferred type arguments

Even if a type parameter does not have a default, the compiler can infer it in some circumstances,

- Constructors (https://github.com/dotnet/roslyn/issues/2319)

```cs
new Nullable(1); // Nullable<int>
```
- Collection initializers (https://github.com/dotnet/roslyn/issues/1470)

```cs
new List { 1 } // List<int>
```

- Static members (https://github.com/dotnet/roslyn/issues/8214)
```cs
class X<T> { public static void F(T x) {} }

X.F(1); // X<int>
```

- Target typing (https://github.com/dotnet/roslyn/issues/5429)

```cs
T F<T>() { .. }

int x = F(); // F<int>

```

- Inference from the first usage (locals only)

```cs
var x = new List();
x.Add(1); // infers List<int>
```

- Inference from assignment

```cs
private readonly Dictionary _map = new() { { "key", 1 } }; // Dictionary<string, int>
```

As for binding, we will prefer non-generic types just like default type parameters described above. So if there exist multiple type with the same name it wouldn't be possible to use type inference in the use-site.

**Comment by eyalsk** [comment]
Related to #151 

p.s. The first part of the post reminds me TypeScript's generic defaults. :)

**Comment by TheOtherSamP** [comment]
I'm the original poster of #169 (`this` constraint) and it's nice to see that getting a little attention, thanks for including it. I'd avoided talking about defaults because it was a little out of scope and I was considering name collisions to be a pretty big no-go, but if that was in there that would really tidy usage of that feature up and make it nearly seamless.

I'm not entirely clear on the state of the CLR and how feasible requests requiring changes are right now on a short timeframe, but I would prefer to see this implemented as a CLR constraint rather than a C# only one. Does anyone know if they'd consider it a no-go breaking change to implement a feature like this as C# only and then move it to a CLR restriction at a later time? I think that would mostly be fine.

I also have a few other generics requests lounging about in my head, so if his has a chance to grow into a big discussion on generics I may try to get those posted soon.

**Comment by dmitriyse** [comment]
Please also consider to merge this proposal to the umbrella https://github.com/dotnet/csharplang/issues/193
In short words, this simplifies "heavy generic methods" declaration (for very strict typing).

**Comment by dmitriyse** [comment]
Please also consider to cover by the umbrella this proposal https://github.com/dotnet/csharplang/issues/266 .

**Comment by GeirGrusom** [comment]
Partially inferred generic arguments:

```csharp
    TResult GetValue<TKey, TResult>(TKey key) { ... }

    var result = GetValue<int>("abc");
```

alternatively

```csharp
    var result = GetValue<, int>("abc");
```

Partially resolved generic aliases:

```csharp
    using StringDictionary<T> = Dictionary<string, T>;
```

**Comment by alrz** [comment]
@GeirGrusom For the first example you could use named argument names. For generic aliases see #90.

**Comment by GeirGrusom** [comment]
@alrz Ah yes, I missed that part.

**Comment by gulshan** [comment]
#268 proposing `x is Some<var> i` type pattern for generic types.

**Comment by gafter** [comment]
Umbrella topics/proposals like this make it difficult for the individual ideas under the umbrella to be considered by the LDM.

**Comment by alrz** [comment]
Right. I'll try to separate these out into multiple issues.

**Comment by weitzhandler** [comment]
I dig the whole idea of taking generics inference a step further.
I didn't find it was clear, but it's also important to include only some of the generic types while omitting the inferred ones, this could be easily achieved with named parameters indeed.

**Comment by weitzhandler** [comment]
@alrz Did you split them up yet? If so, please link them here.

**Comment by alrz** [comment]
@weitzhandler  #78, #79 #80, #81

**Comment by alrz** [comment]
@weitzhandler  #278, #279, #280, #281

**Comment by ymassad** [comment]
@alrz , did you create an issue for "Inference from the first usage"?
