### ISSUE TITLE
isnot keywork support

### ISSUE THREAD

**Issue by skarllot** [dotnet/csharplang#2531]
## Motivation:
A keywork that allow reversed `is` logic gives a better looking code specially for complex conditions.

### Before:
```csharp
if (age < 21 || (!(animal is Tiger) && season is Winter))
    return;
```

### After:
```csharp
if (age < 21 || (animal isnot Tiger && season is Winter))
    return;
```

**Comment by CyrusNajmabadi** [comment]
This is part of teh `not pattern` proposal here: https://github.com/dotnet/csharplang/issues/1350

You would be able to say `animal is not Tiger`.  So you can likely close this out.  Cheers!

**Comment by skarllot** [comment]
> This is part of teh `not pattern` proposal here: #1350
> 
> You would be able to say `animal is not Tiger`. So you can likely close this out. Cheers!

This is a way more complex than a `isnot` keyword.

**Comment by YairHalberstadt** [comment]
`is not` is way more complicated than `isnot`?
Or the whole proposal is easy more complicated? Because that while proposal is Championed and very likely to occur.

**Comment by CyrusNajmabadi** [comment]
> This is a way more complex than a isnot keyword.

that's not the case.  the `not` pattern fits under the pattern bucket, and thus can be used in the entire pattern matching system.  the `isnot` keyword would be an entirely new concept usable only in one place.  It would add an entirely new, and non-cohesive feature over the `not` pattern, making it more complex.  

Finally, `isnot` is not (no pun intended) going to happen.  `is not` actually stands a strong chance of happening.  So hopefully you'll be able to make peace with things :)

**Comment by gafter** [comment]
I'd love to have a keyword pronounced "eye snot", but I'm afraid it just isn't likely given it would be redundant with the proposed `not` pattern combinator.
