### ISSUE TITLE
Force named parameters when having positional parameters of same type

### ISSUE THREAD

**Issue by tzachshabtay** [dotnet/csharplang#2538]
A common programming bug is when you put positional arguments out of order:

```csharp
function doSomething(int x, int y) {...}

doSomething(y, x); //oh oh, this is wrong!
```

Here's @DustinCampbell doing this mistake live on stage (minute 24): https://mybuild.techcommunity.microsoft.com/sessions/77032?source=sessions

I'm thinking we can solve these kind of bugs completely if the compiler disallows using positional arguments when the signature has 2 arguments (or more) with the same type, i.e we would be forced to used named arguments:

```csharp
doSomething(x: x, y: y);
```

As this might break existing programs, we can do it as an opt-in with the same pattern used for nullable references.

**Comment by theunrepentantgeek** [comment]
Rather than breaking (literally) billions of lines of existing C# code, this looks like a situation where a code analyzer would be a great solution, allowing those interested in this rule to opt-in.

**Comment by gfoidl** [comment]
> `doSomething(y, x); //oh oh, this is wrong!`

This call could also be intentional, when swapped evaluation is needed.

Besides the code analyzer mentioned by @theunrepentantgeek (unit/integration) should cover and detect this.

**Comment by YairHalberstadt** [comment]
Closing this, as this is exactly the scenario code analyzers were designed for.

**Comment by awojtas** [comment]
I don't agree this should be closed - relying on analysers and tests are great safety nets, but the language itself should support this directly. And you it can be implemented without breaking years and years of existing C# code.

I suggest that methods are allowed to be declared like Dart allows:
void myMethod({int x, int y});

When the parameters are enclosed in curly braces then the named parameters must be specifically named by the caller.

**Comment by CyrusNajmabadi** [comment]
> but the language itself should support this directly

I don't think there's an interest in this given how suitable analyzers are for this task.  The language efforts are better spent in areas that can't be easily solved in that fashion.

**Comment by mykolav** [comment]
Hi, @tzachshabtay @theunrepentantgeek 

I happened to develop an analyzer that suggests using named argument if it comes across a call to a method which has two or more arguments of the same type in a row. The diagnostic's severity level is configurable. You can check it out here: https://github.com/mykolav/use-named-args-fs

And another one that lets enforce calling a marked method with named arguments only. Calling this method with positional arguments triggers a compile-time diagnostic. It is an error by default but the severity can be configured. The repository is here: https://github.com/mykolav/require-named-args-fs 

Glad if people find these useful.
