### ISSUE TITLE
Proposal: File scoped namespaces

### ISSUE THREAD

**Issue by MgSam** [dotnet/csharplang#2546]
### Background

.NET style guidelines recommend having at most one namespace per file. The current namespace syntax only allows block scope, resulting in every file typically having all of its contents (save using statements) wrapped in a namespace block. This leads to both vertical space being wasted (the curly braces used to delimit the block) and more importantly, horizontal space being wasted, with all of the important content indented by an extra tab (if style guidelines are being followed). The indentation from the namespace block conveys no useful information- it is just code bloat.

``` C#
using System.Collections.Generic;

namespace Foo 
{
    public class Bar
    {
          ... // Potentially hundreds of lines of code, 
              // all of which has an extra indentation because 
              // of the namespace but is not actually conveying any useful information
    }
}
```
### Proposal

Allow a single namespace declaration per file that has no braces and therefore no block scope. Every class written in the file is a member of this namespace. It would be an error to attempt to introduce a second namespace declaration of any kind (including one with block scope). The single namespace declaration would be valid in the outermost scope only. It would be valid to appear at any part of the file in this scope, although style guidelines would recommend putting it at the top.

``` C#
namespace Foo;

using System.Collections.Generic;

public class Bar
{
    ...
}
```
#### Previous Discussion

[Code Plex](https://roslyn.codeplex.com/discussions/544391)
#### Uservoice (vote for the feature)

http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7181921-file-scoped-namespaces

**Comment by GlassGrass** [comment]
I like fully qualified naming style such as suggested by @jnm2 and @paulomorgado. This is consistent with type-using grammar, and also with type declaration grammar in MSIL.

**Comment by ssg** [comment]
I wrote my thoughts about file-scoped namespace directives here: https://medium.com/@ssg/a-pledge-for-namespace-directives-in-c-15a322504a15

**Comment by janniksam** [comment]
Although this proposal is over 5 years old now, I personally do love this idea aswell.
Since C# 8.0 introduced using declarations, in my opinion this is the next big step to work on.

Personally I never saw (well, remember) a file, that contained more than one namespace. This would save some indentation in all my files, so I can abuse it for one more nested if to annoy my co-workers in the next pull-request with... ;)

**Comment by mkArtak** [comment]
What about supporting `implicit namespaces`?
In majority of projects I've worked for, the namespace is always a combination of `projectName` + `folder structure to current file`. If this can be treated as `default`, there won't even be a need to specify namespaces explicitly.

Of course, for completeness, this will require:
- to have an ability to define a root project-level namespace (which I think is already supported through the `RootNamespace` property in the project file).
- a mechanism to override, which is what this issue about

**Comment by ssg** [comment]
@mkArtak An upgrade to that model would entail reorganizing your project folder structure (or your code) significantly which is very intrusive in my opinion. File-scoped directives, on the other hand, can even work with a simple refactor (even find & replace perhaps), and would not even change the diff significantly if you omit whitespace.

Also, C# namespace directives are case-sensitive while MacOS/Windows file systems are not. My Spider-sense says trouble.

**Comment by mkArtak** [comment]
@ssg, for an existing project scenario you're referring to, you will still be able to specify explicitly the namespace per file. My proposal goes a step beyond that by eliminating the need for specifying the namespace if the name matches the convention `[default namespace].[folder structure]`
As for for the OS case sensitivity, these I think are minor technical challenges, which can be solved using a few more project-level properties.

**Comment by umbarov** [comment]
I like this idea. Pros are less indents and compactness . Other programming languages like Java, Go, Rust, Python do not use namespace braces. I spend a lot of time on review and I get annoyed by the indents and horizontal scrolling. Another advantage is that the code is left-aligned.

**Comment by 333fred** [comment]
Closing as a duplicate of #137.
