### ISSUE TITLE
[Proposal][Roslyn] Add structural typing support

### ISSUE THREAD

**Issue by glennblock** [dotnet/csharplang#2548]
This proposal is based on discussions with @MadsTorgersen and @DavidFowl. The design incorporates feedback from @crmckenzie and @edandersen.

In golang [interfaces](https://golang.org/ref/spec#Interface_types) are structural and implicit. Once an interface is declared, all go types that have the members defined in the interface present, automatically become implementers of that interface. This provides benefits for testability and extensibility. 

C# interfaces today require the implementer to explicitly implement the interface. C# does have the dynamic keyword however when you use dynamic, you lose all compile time checking / type safety. Interfaces in golang however allow retaining type safety while reducing type coupling (because the implemented does not have to explicitly implement the interface).

The proposal is to add structurally typed interface support to C#.
## Overview

Here is an example of how interfaces work in go.

``` go
//Based on https://tour.golang.org/methods/5, but further simplified
type Writer interface {
    Write(b []byte) (n int, err error)
}

func output(w Writer, msg string) {
  ... 
}

func main() {
    var w Writer

    // os.Stdout implements Writer
    w = os.Stdout
    output(w, "Hello World");
}
```

The user's code defines a `Writer` interface with a `Write` method. Next an `output` function is defined which accepts a `Writer`. Finally in the `main` function the code then creates a new `Writer` instance and sets the built in go `os.Stdout` object to that instance. The setting of the value succeeds though the `Stdout` object had no prior knowledge of the `Writer` interface.

From a testability perspective this is extremely nice. If the user wants to test the `output` function, he/she can easily provide a mock `Writer`. It is not required to use any special mocking tools, nor do custom adapters and wrapper classes have to be created to wrap the native framework objects to make them testable. This will be beneficial for testing sealed classes, or non-virtual members.

From an extensibility perspective this is also nice as new Writers can easily be plugged in simply by defining new types with the required members.
## Proposal

Allow add structural typing support for interfaces in .NET. Several variant approaches are proposed.
### Benefits
- Allows existing .NET classes to be more easily tested.
- Implementers of libraries have to jump through less hoops to make their libraries testable.
- Simplifies authoring of 3rd party extensions, removes the need for a shared library reference.
- Enables new scenarios for anonymous types
### Variant 1 - Structural keyword

One way to do this would be to introduce a new `structural` keyword which defines a structural interface. A `structural` is similar to a standard interface behavior-wise with one big exception, it is implicitly implemented by any class that has the members defined in the structural interface. The members of the interface can be any valid reference or value type.
#### Example

Below is a sample C# snippet illustrating a scenario where this could be used. The example is more complicated than the go example for illustration of a real world pain point. It uses `System.Web.HttpRequest`, a class that today is often difficult to test against because it is sealed. Today testing is improved through helper/wrapper classes like `System.Web.HttpRequestBase` and `System.Web.HttpRequestWrapper`. These put a burden on frameworks to support these helpers and they add complexity.

Let's assume a library has a method which performs validation against the current request.

``` csharp
public structural IHttpRequest() {
    string UserAgent {get;}
}

public class RequestValidator {
    private IHttpRequest _req;

    public RequestValidator(IHttpRequest req) {
        _req = req;    
    }

    public void ValidateUserAgent() {
        var ua = _req.UserAgent;
        if (ua == null) {
          throw new ArgumentException("UserAgent", "User Agent must be provided");
        }
    }
}

//in prod code somenwhere
public class Handler {
    public void HandleRequest(HttpContext context) {
        var req = context.Request;
        var validator = new Validator(req);
        validator.ValidateUserAgent();
    }
}

//unit test, checks to see the QueryString is accessed.
using Xunit;
using Should;

public class ValidatorTests {
    [Fact]
    public void ValidateUserAgentThrowsExceptionWhenUserAgentIsNull() {
        var mock = new Mock<IHttpRequest>();
        mock.SetupGet(r=>r.UserAgent).Returns(null);
        var validator = new RequestValidator(mock.Object);
        var ex = Assert.Throws<ArgumentException>(()=>validator.ValidateUserAgent());
        ex.Message.ShouldEqual("User Agent must be provided");  
    }

    [Fact]
    public void ValidateUserAgentShouldSucceedWhenUserAgentIsNotNull() {
        var mock = new Mock<IHttpRequest>();
        mock.SetupGet(r=>r.UserAgent).Returns("foo");
        var validator = new RequestValidator(mock.Object);
        validator.ValidateUserAgent();
    }
}
```

A few details about the code
- `IHttpRequest` defines a structural interface. This was created by the library author and and is not part of the .NET framework.
- `RequestValidator` is the system under test. It validates the UserAgent on the request and accepts an IHttpRequest instance.
- `Handler` is a class deployed to production which passes in the current HttpContext.Request. HttpRequest becomes an implicit implementer of IHttpRequest as it matches on members.
- The unit tests mocks the request using the structural interface in order to test the `Handler` class.
- No wrapper or utility types are needed i.e. `HttpRequestBase`, `HttpRequestWrapper`.

The high level benefit illustrated here is being able to easily test the RequestValidator class though the types that it relies on themselves were not designed in a testable manner.  
### Variant 2 - Structural attribute at the callsite (suggested by @crmckenzie)

In this variant the implementer of a method declares in the definition that one or more members are structurally matched. This is done via the useage of a new `[Structural]` attribute which is applied to a member that has an interface-type. Similar to Variant 1, all objects which have the members defined in the interface present, will match. 

Note: Once the instance has been received within the method, it can be set to a variable of the same interface type or passed as a parameter to a method that accepts a parameter of that interface whether it is marked structural or not. This is in order to remove the need to declare structural in a viral manner throughout the code.
#### Example:

``` csharp
public IHttpRequest() {
    string UserAgent {get;}
}

public class RequestValidator {
    //not necessary to be marked as Structural
    private IHttpRequest _req;

    public RequestValidator([Structural] IHttpRequest req) {
        _req = req;    
    }

    public void ValidateUserAgent() {
        var ua = _req.UserAgent;
        if (ua == null) {
          throw new ArgumentException("UserAgent", "User Agent must be provided");
        }
    }
}

//in prod code somenwhere
public class Handler {
    public void HandleRequest(HttpContext context) {
        var req = context.Request;
        var validator = new Validator(req);
        validator.ValidateUserAgent();
    }
}

//unit test, checks to see the QueryString is accessed.
using Xunit;
using Should;

public class ValidatorTests {
    [Fact]
    public void ValidateUserAgentThrowsExceptionWhenUserAgentIsNull() {
        var mock = new Mock<IHttpRequest>();
        mock.SetupGet(r=>r.UserAgent).Returns(null);
        var validator = new RequestValidator(mock.Object);
        var ex = Assert.Throws<ArgumentException>(()=>validator.ValidateUserAgent());
        ex.Message.ShouldEqual("User Agent must be provided");  
    }

    [Fact]
    public void ValidateUserAgentShouldSucceedWhenUserAgentIsNotNull() {
        var mock = new Mock<IHttpRequest>();
        mock.SetupGet(r=>r.UserAgent).Returns("foo");
        var validator = new RequestValidator(mock.Object);
        validator.ValidateUserAgent();
    }
}
```

Differences between this code and Variant 1. 
- `IHttpRequest` defines a standard interface rather than a `Structural`. 
- `RequestValidator` defines the req parameter as `[Structural]`
### Variant 3 - All interfaces are implicitly matched on structure, does not require any specific annotation or types. (suggested by @clipperhouse)

With this variant, the suggested functionality will just work without any special type or annotation required. 

Any object that matches an interface on structure will automatically implement that interface. This aligns closest to how go does it.
## Questions
- Q: Will general casting work i.e. I can cast `Foo` to `IFoo` simply because `Foo` has the members?
- Q: Should the structural match be recursive? Meaning `StructuralA` can have params of type `StructuralB` and `StructuralC`?
- Q: How does this work with the type system. What will `Type.GetInterfaces` return?
## Notes
- A completely diff approach is to allow defining the expected interface inline within the method using a declarative syntax. `Scala` supports [both](http://docs.scala-lang.org/style/types.html) approaches.

**Comment by TheNightFall** [comment]
Would be possible to use as a anonymous generic type specified as a new generic constraint?

class foo {
  void Bar<T>(T whatever)
      where T : class, //or struct
                        {
                              Name: string; 
                              bool Bar(decimal x);
                         }
   { 
        whatever.Bar(10m);
        Console.WriteLine(whatever.Name);
   }
}
