### ISSUE TITLE
DoesNotReturnAttribute should affect definite assignment

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#2555]
The compiler is introducing a new attribute `DoesNotReturn` that will affect nullability analysis.

I think it would make sense for the compiler to enforce this strictly, and for it to affect definite assignment as well.

It is possible that someone using a different .NET language/old compiler could add this attribute to a method which does in fact return. However this will only lead to undefined behaviour, not unsafe behaviour, because the C# compiler zeroes out the stack before calling a method. I believe that the benefits therefore outway the risk.

See also: https://github.com/dotnet/csharplang/issues/538

**Comment by Joe4evr** [comment]
Also related: #739

**Comment by 333fred** [comment]
When we talked about this attribute during CoreFX design, we were pretty explicit that an attribute alone should not affect code generation and definite analysis in this manner. If we ever want to go down the route of affecting definite assignment, we will need to introduce new syntax, likely a conditional keyword such as `never` or `noreturn`. That could add this attribute, but it will likely also be accompanied by a modreq to prevent downlevel breaks.

**Comment by YairHalberstadt** [comment]
Then wouldn't now be the right time to add this feature, rather than have two equivalent syntaxes? Or is it too close to C# 8 to do this?

**Comment by 333fred** [comment]
To be clear, this wouldn't be two equivalent syntaxes. One would likely supersede the other, with the explicit `never` syntax allowing the compiler to enforce the condition in the method body. The attribute alone will _never_ affect code in this manner.

As to the timing, yes, I think we're likely too close to C# 8 to make such a change.

**Comment by jnm2** [comment]
I believe this is where the conversation started during the API review livestream: https://youtu.be/zAhOxraBsi0?t=3665 (almost 20 min)

**Comment by YairHalberstadt** [comment]
Closing in favour of #538, as this isn't planned in the C# 8 timeframe anyway.

**Comment by johnkellyoxford** [comment]
Closed, but thought it was worth mentioning for anyone else who sees this, the addition of `SkipLocalsInitAttribute` could cause issues with garbage data being returned as the stack isn't zeroed
