### ISSUE TITLE
Proposal: Enable chain-calling on void return methods/Void methods return its instance at language level

### ISSUE THREAD

**Issue by datvm** [dotnet/csharplang#2560]
Currently any method that does not return (`void`) stops all further calling. At language level, it may be useful to enable chain-calling as if the method returns the instance itself.

```
public class Foo
{
    public void DoSomething1() { }
    public void SetSomething2(int a) { }
    public void SetSomething3(string b) { }
    public void SetSomething4(decimal c) { }
}
```

Currently we have to refer the instance for calling, for example:

```
    var f = new Foo();
    f.DoSomething1();
    f.SetSomething2(1); 
    f.SetSomething3("Bar");
    f.SetSomething4(1.2M);
```

With this proposal we can chain-calling like a Builder without changing old code:

```
    var f = new Foo()
        .DoSomething1()
        .SetSomething2(1)
        .SetSomething3("Bar")
        .SetSomething4(1.2M);
```

I don't know if there is any side-effect, but this should not affect legacy code as it's currently impossible to follow up any void method.

Note: I am not proposing to change the actual return signature, only the language itself. Reflection on such method should still have `void` return, not the type.

This could be a duplicate because I don't think it's unpopular, but I tried my best searching and found no issue like this yet. Sorry if it is a duplicate.

**Comment by canton7** [comment]
Surely a better approach would be VB's `with` statement, then you could write something like:

```csharp
with (f)
{
    .DoSomething1();
    .SetSomething2(1);
    .Property = "value";
}
```

1. This work even when the methods don't return `void`
2. You're not pretending that a void-returning method actually returns an object (I can only imagine the looks on people's faces when they find code which is calling methods on `void`, and try to work out what the method receiver actually is. I imagine some expletives would be involved)
3. It also covers properties, events, etc.

`with` is already discussed in #1534.

**Comment by ufcpp** [comment]
In addition to https://github.com/dotnet/csharplang/issues/1534, there are some similar issues: https://github.com/dotnet/csharplang/issues/781, https://github.com/dotnet/csharplang/issues/902

**Comment by datvm** [comment]
Thanks, closing this one.
