### ISSUE TITLE
Proposal: Object table initialization

### ISSUE THREAD

**Issue by yolofy** [dotnet/csharplang#2564]
Make the initialization of multiple objects easy and readable. Especially useful in unit tests

Example:
 ```
var savedLocations = new[]
      {
         new SavedLocation
         {
             Id = "12345",
             Label = "Amsterdam",
             Icon = Icon.Station
         },
         new SavedLocation
         {
             Id = "12346",
             Label = "Museum",
             Icon = Icon.Poi
         },
         new SavedLocation
         {
             Id = "12347",
             Label = "Work",
             Icon = Icon.Work
         }
     };
```

Improve to:
```
 var savedLocations2 = new SavedLocation
     [    Id,           Label,          Icon,
          ("12345",     "Amsterdam",    Icon.Station),
          ("12346",     "Museum",       Icon.Poi),
          ("12347",     "Work",         Icon.Work)
     ];
```

Or:
```
    var savedLocations3 = new SavedLocation
    [
        Id =    ("12345",      "12346",  "12347"),
        Label = ("Amsterdam",  "Museum", "Work"),
        Icon =  (Icon.Station, Icon.Poi, Icon.Work)
    ];
```

**Comment by svick** [comment]
Is performance important for you? If not you, I think you could make something like the following code work with reflection:

```c#
CreateArray<SavedLocation>(
    nameof(SavedLocation.Id), nameof(SavedLocation.Label), nameof(SavedLocation.Icon),
    ("12345", "Amsterdam", Icon.Station),
    ("12346", "Museum",    Icon.Poi),
    ("12347", "Work",      Icon.Work))
```

Also, why can't you use a constructor? With that, you can write your code today as:

```c#
new[]
{
   new SavedLocation("12345", "Amsterdam", Icon.Station),
   new SavedLocation("12346", "Museum",    Icon.Poi),
   new SavedLocation("12347", "Work",      Icon.Work)
}
```

And with target-typed new (https://github.com/dotnet/csharplang/issues/100), in C# 8.1, you'll probably be able to shorten that to:

```c#
new SavedLocation[]
{
   new("12345", "Amsterdam", Icon.Station),
   new("12346", "Museum",    Icon.Poi),
   new("12347", "Work",      Icon.Work)
}
```

**Comment by yolofy** [comment]
> Also, why can't you use a constructor? With that, you can write your code today as:
> 
> ```cs
> new[]
> {
>    new SavedLocation("12345", "Amsterdam", Icon.Station),
>    new SavedLocation("12346", "Museum",    Icon.Poi),
>    new SavedLocation("12347", "Work",      Icon.Work)
> }
> ```
These classes are in libraries I can't change.

> 
> And with target-typed new (#100), in C# 8.1, you'll probably be able to shorten that to:
> 
> ```cs
> new SavedLocation[]
> {
>    new("12345", "Amsterdam", Icon.Station),
>    new("12346", "Museum",    Icon.Poi),
>    new("12347", "Work",      Icon.Work)
> }
> ```
Looks nice, same problem

**Comment by canton7** [comment]
> These classes are in libraries I can't change.

You can just create your own helper function:

```csharp
public static SavedLocation Location(string id, string label, Icon icon) => 
    new SavedLocation() { Id = id, Label = label, Icon = icon };
```

Then:

```csharp
new[]
{
    Location("12345", "Amsterdam", Icon.Station),
    Location("12346", "Museum", Icon.Poi),
    Location("12347", "Work", Icon.Work),
}
```

**Comment by yolofy** [comment]
> > These classes are in libraries I can't change.
> 
> You can just create your own helper method:

I know it's possible, but I don't want to create and maintain a helper method for every type.

**Comment by canton7** [comment]
> I don't want to create

You want the C# team to spend thousands of man-hours specifying, developing, testing, and documenting a new language feature, and you're asking millions of C# developers to learn this new syntax, so you can avoid writing a few one-line helper methods? I'm afraid that probably means this isn't going anywhere.

> and maintain a helper method for every type.

Just to add an extra point....

You said "maintain". If you have to maintain it, that implies that `SavedLocation` is going to be changed over time. If that's going to happen, adding a layer of abstraction here is a *good* thing - it means you only need to change one helper method, instead of every element in your array.

**Comment by yolofy** [comment]
> > I don't want to create
> 
> You want the C# team to spend thousands of man-hours specifying, developing, testing, and documenting a new language feature, and you're asking millions of C# developers to learn this new syntax, so you can avoid writing a few one-line helper methods? I'm afraid that probably means this isn't going anywhere.
> 
You are exaggerating. I'm sharing my thoughts on improving the language with the intention that everybody can benefit from it. I think everbody would like to write less code, it's one of the reasons why improvements such as "target-type new" are made. It's a proposal not an order, if you don't like it don't do it. I don't understand the hostility, is this the wrong place to share and discuss proposals?

> The length of the helper method is not far off the length of your proposed table header: `[ Id, Label, Icon,`

Let's be factual:
```
private static SavedLocation Location(string id, string label, Icon icon) => new SavedLocation() { Id = id, Label = label, Icon = icon }; //137 characters, 115 without whitespace
[    Id,           Label,          Icon, //40 characters, 15 without whitespace
```
the helper method is 3,425 times more code including whitespaces. Without whitespace it's 7,6 times more. Are you trolling me?
> 
> > and maintain a helper method for every type.
> 
> Just to add an extra point....
> 
> You said "maintain". If you have to maintain it, that implies that `SavedLocation` is going to be changed over time. If that's going to happen, adding a layer of abstraction here is a _good_ thing - it means you only need to change one helper method, instead of every element in your array.

This doesn't add up. For example when a Description property is added to SavedLocation and I want to set it with different values, I still need to change every element in my array AND the helper method.

**Comment by canton7** [comment]
(Note that neither I nor most of the other people commenting on issues here are part of Microsoft)

> You are exaggerating

Almost certainly the opposite. I'm just trying to highlight that adding new features to the language is a big effort, and trying to put your request into that context. This isn't an afternoon's work: this is a large effort across multiple teams. You've acknowledged that a simple alternative within the language already exists, and this is a reason why I think this is unlikely to happen.

> the helper method is 3.425 times more code including whitespaces. Without whitespace it's 7.6 times more. Are you trolling me?

It's a difference of 100 characters, which I'd say is "not far off". It took me 20 seconds to type the helper method, and I'm not a particularly fast typer.

> This doesn't add up. For example when a Description property is added to SavedLocation and I want to set it with different values, I still need to change every element in my array AND the helper method.

Right, if you're simply adding data, then yes you need to change the helper method as well. That took me about 10 seconds. If something else changes though, like one of the property names is changed, then you don't need to update the array.

Just to be clear: I'm not trolling, or exaggerting, and I don't mean to be hostile. I started off by trying to help you, within the language. After you rejected that, I'm now only trying to set your expectations by saying that this is unlikely to go further, since there are already ways of doing something close to what you want.

**Comment by yaakov-h** [comment]
You could also abuse collection initializers to achieve the same effect.

**Comment by DavidArno** [comment]
Since target-typed new (#100) hasn't been implemented yet, it might be able to support:
```cs
new SavedLocation[]
{
   new { "12345", "Amsterdam", Icon.Station },
   new { "12346", "Museum",    Icon.Poi },
   new { "12347", "Work",      Icon.Work }
};
```
so I'd have thought it better to appeal for target-typed new to support object initialisers, rather than requesting another syntax.

**Comment by canton7** [comment]
@DavidArno How does it know which property has the value "12345"?

**Comment by DavidArno** [comment]
@canton7, oh damn. Got too far ahead of myself. That post is complete nonsense. Deleting it 😆

**Comment by canton7** [comment]
Target-typed new will support `new() { Id = "12345" }`, etc, to be fair

**Comment by mburbea** [comment]
You could also get the compact syntax with an extension method
```cs
static class SavedLocationExtensions
{
   public static void Add(this ICollection<SavedLocation> l, string id, string label, Icon icon)
     => l.Add(new SavedLocation { Id = id, Label = label, Icon = icon });
}
...
var table = Table = new List<SavedLocation>
        {
            { "12345",     "Amsterdam",    Icon.Station},
            { "12346",     "Museum",       Icon.Poi },
            {"12347",     "Work",         Icon.Work }
        };
```

**Comment by yolofy** [comment]
Thanks for the help guys. It turns out it is possible within the c# language. 

I ended up creating Tuple Tables: 
- source: https://github.com/yolofy/TupleTables
- nuget: https://www.nuget.org/packages/Yolofy.TupleTables/ (may not be indexed yet)

#### Example usage
```cs
 var table = TupleTable<Person>.Create
                  (p => p.Id,           p2 => p2.Name,  p3 => p3.Age,   p4 => p4.Gender,
                  (Guid.NewGuid(),      "Xumina",       15,             Gender.Female),
                  (Guid.NewGuid(),      "Bale",         26,             Gender.Male),
                  (Guid.NewGuid(),      "Robin",        30,             Gender.Neutral),
                  (Guid.NewGuid(),      "Adama",        25,             Gender.Female),
                  (Guid.NewGuid(),      "Theodore",     43,             Gender.Male),
                  (Guid.NewGuid(),      "Georgios",     82,             Gender.Male),
                  (Guid.NewGuid(),      "Anastasia",    14,             Gender.Female),
                  (Guid.NewGuid(),      "William",      39,             Gender.Male),
                  (Guid.NewGuid(),      "Yuina",        55,             Gender.Female),
                  (Guid.NewGuid(),      "Eden",         62,             Gender.Neutral));
```
