### ISSUE TITLE
Proposal: a method that allows all waits to be completed is declared a normal method

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/csharplang#2565]
before:
```cpp
public static async System.Threading.Tasks.Task<string> test_func () {
    return await System.Threading.Tasks.Task.Run (() => {
        Thread.Sleep (1000);
        return "test";
    });
}
```

after:
```cpp
public static string test_func () {
    return await System.Threading.Tasks.Task.Run (() => {
        Thread.Sleep (1000);
        return "test";
    });
}
```

It may be a bit of an anti-design principle, but in some cases it does save a lot of code.

**Comment by johnkellyoxford** [comment]
tl;dr this is impossible

**Comment by Tom01098** [comment]
If you want the method to be synchronous, just use `Task.Result` in the method and return that.

> It may be a bit of an anti-design principle, but in some cases it does save a lot of code.

It only saves the keyword `async` and the type name - if you fully qualified it, it would only be `Task<string>`. It also means that with this change, you would no longer be able to determine if a method is asynchronous or not based off its signature.

**Comment by canton7** [comment]
Presumably your `test_func` would block for 1 second?

If so, why not just write:

```csharp
public static string test_func()
{
    Thread.Sleep(1000);
    return "test";
}
```

**Comment by fawdlstty** [comment]
@Tom01098 Method USES asynchronous functions inside the method, but the method itself is synchronous

**Comment by johnkellyoxford** [comment]
It just doesn't work with async. [This](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQY4B0AkgPIDchJ5OArIwUwMzlakDCpAN6FSY8jwwAOckgA8FYgD5SAOWgBbAIYAbAIIBnAJ4A7MAFkYAFwAWEACYAKAJTDR4jxgDs5AJykAMQBLHRhKACUYLXs9HR0AFRgEK0NTMEcAIgznDg8AX3cxQolyGQx5RRV4myCDcwBXAytIq3qoE3KAZSsoIJMAcxc3Ag9PHF9MgCEYADNoGD9s3NGxRVJYA3qdK1IAXj9AkLDI6NiEpJTjM0yl4rGJjOm52EWcu/FvdZhN7eWxAoIeSAA) demonstrates why

Async is a state machine, you can't just tell it to execute in its entirety unfortunately without blocking issues. Even where it is possible, it should not be promoted through a lang feature, as it is bad design

**Comment by canton7** [comment]
@fawdlstty If you've got a synchronous method which needs to perform asynchronous operations and block until they complete, then use `Task.Wait()` / `Task.Result` as appropriate (and beware of deadlocks)

**Comment by fawdlstty** [comment]
@canton7 Sorry, my example might not be intuitive, but I'm going to take another example where I'm going to assume that I'm computing a string locally, and then I'm going to ask the network to get the new string, and then I'm going to return the splicing
```csharp
public static string test_func () {
    System.Threading.Tasks.Task<string> t = System.Threading.Tasks.Task.Run (() => {
        // do something...
        Thread.Sleep (1000);
        return "test";
    });
    // do something...
    Thread.Sleep (1000);
    string a = "build ";
    return a + await t;
}
```

**Comment by canton7** [comment]
So...

```csharp
public static string test_func () {
    System.Threading.Tasks.Task<string> t = System.Threading.Tasks.Task.Run (() => {
        // do something...
        Thread.Sleep (1000);
        return "test";
    });
    // do something...
    Thread.Sleep (1000);
    string a = "build ";
    return a + t.Result;
}
```

**Comment by fawdlstty** [comment]
:cry:

**Comment by fawdlstty** [comment]
可能不是task，仅仅是async函数，在调用的时候不需再创建一个Task用来获取返回值

**Comment by fawdlstty** [comment]
Presumably the compiler encounters this situation and automatically wraps it with task.run

**Comment by johnkellyoxford** [comment]
what situation

**Comment by canton7** [comment]
> It may not be a task, just an async function that doesn't need to create a task to get the return value when called

I don't follow. Async functions can return `Task` or `void`. If they return `void`, then they're "fire-and-forget", and you can't get a result out of them. If they return `Task`, then they... need to return a `Task`, and you can call `.Wait()` or `.Result` on it.

**Comment by fawdlstty** [comment]
:sweat_smile:I see, this is a boring question

**Comment by fawdlstty** [comment]
thanks
