### ISSUE TITLE
Constraint missing (async function must return one of these types) in draft C# specification

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2567]
The following program

``` cs
using System;
class C
{
    static void Main()
    {
        // error CS4010: Cannot convert async anonymous method to delegate type 'System.Func<int>'. An async anonymous method may return void, Task or Task, none of which are convertible to 'System.Func<int>'.
        Func<int> x = async delegate {
            throw null;
        };
    }
}
```

Is rejected by the compiler.

Seeking guidance from the language spec, I could not find anything to forbid this program. Perhaps there is a constraint missing in 6.5 (“If F is async, D has the return type `void`, `Task`, or `Task<T>` for some `T`.”) or misworded?

**Comment by BillWagner** [comment]
This was addressed in the C# 5.0 standard in [§15.15.1](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/classes.md#15151-general).

Closing.
