### ISSUE TITLE
Object Initializer shows getter-only properties.

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#2573]
I think this is more of a VS thing but I'm not sure where to put it.

If you have this class:
````
public class Foo {
  public string Name {get; set;}
  public int Age {get; private set;}
}
````

When you type:
````
var F = new Foo() {
  //Popup appears here
````
The autocomplete popup lists Age as a member.  It shouldn't.  It can't be set.

**Comment by CyrusNajmabadi** [comment]
Tony, can you move this to dotnet/roslyn.  That's the right place for this.  Thanks!
