### ISSUE TITLE
Casting oblivious nullable type to nullable and dereferencing does not report warning

### ISSUE THREAD

**Issue by duracellko** [dotnet/csharplang#2575]
When a method returns oblivious nullable type and it is assigned to explicitly nullable variable, compiler still does not report warning, when dereferencing the variable.

More details in sample repository [https://github.com/duracellko/CS8Nullable](https://github.com/duracellko/CS8Nullable).

**Comment by YairHalberstadt** [comment]
This is by design. The type a variable is assigned to does not affect its nullable flow state.
