### ISSUE TITLE
Proposal: Allow yield return in anonymous functions

### ISSUE THREAD

**Issue by hez2010** [dotnet/csharplang#2583]
Allow yield return in an anonymous function:
```csharp
var func = new Func<int, IEnumerable<int>>((n) => 
{
    for (var i = 0; i < n; i++) yield return i;
});

foreach (var i in func(1000)) .......
```

**Comment by ufcpp** [comment]
See https://github.com/dotnet/roslyn/issues/24#issuecomment-70448545, https://github.com/dotnet/roslyn/issues/24#issuecomment-239875217

> This scenario is better served with local functions, which can be iterators.

**Comment by CyrusNajmabadi** [comment]
Specifically, you can just take the above and write it as:

```c#
IEnumerable<int> func(int n) 
{
    for (var i = 0; i < n; i++) yield return i;
};

foreach (var i in func(1000)) .......
```

**Comment by mdealer** [comment]
It all depends on the specific case! From a bystanders perspective not supporting this in a certain corner of the language makes it inconsistent. 

I've got a system that I could fix by adding 10 lines of code with this, but now I have to resort changing APIs, introducing new classes etc. That's very 1980s, especially considering C# been getting more and more functional over time.

**Comment by CyrusNajmabadi** [comment]
> I've got a system that I could fix by adding 10 lines of code with this, but now I have to resort changing APIs, introducing new classes etc.

Why?

**Comment by mdealer** [comment]
@CyrusNajmabadi What do you mean? If I can't create an anonymous function that creates objects while iterating anywhere to pass it as argument, then I have to look for a class to put it in. That can have consequences.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi What do you mean? If I can't create an anonymous function that creates objects while iterating anywhere to pass it as argument, then I have to look for a class to put it in. 

No, you don' tneed a class.  There are lots of options.  You can have a sibling method/property.  Or you can have a local function.

>  That can have consequences.

I'm not sure what hte consequences would be of this.  A local function is just as capable here, and doesn't require any sort of classes to be created.

**Comment by CyrusNajmabadi** [comment]
> Why can't this be an anonymous function in the first place?

Because it hasn't been important enough to support that niche case when there are suitable alternatives already available in the language.  Resources are limited, and they're being allocated ot language features felt to be more impactful to the community and ecosystem. :)

**Comment by Prinsn** [comment]
The "in the first place" is answered by https://stackoverflow.com/a/1217757/2489966, to the degree that you can follow the specifics of the blog posts.
