### ISSUE TITLE
Allow creating a tuple of ref structs

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#2584]
Tuples are often treated as collections of elements rather than a type in and of themselves by the language. For example see https://github.com/dotnet/roslyn/issues/35695.

They are also very useful when it is necessary to return multiple values from a function.

Tuples are already special cased by the compiler.

For these reasons I think it would make sense to allow creating tuples containing ref structs. The tuples themselves would be considered to be ref structs.

Here are two use cases that I came across today:

```csharp
(ReadOnlySpan<char> beginning, ReadOnlySpan<char> end) Split(string str, int index) => (str.SubString(0, index), str.SubString(index));
```

And

```csharp
var (directory, file, extension) = (GetDirectoryName(path.AsSpan()), GetFileNameWithoutExtension(path.AsSpan()), GetExtension(path.AsSpan()));
```

**Comment by Joe4evr** [comment]
The only way this could even be allowed is to duplicate the `ValueTuple` types to a set of `RefValueTuple`s or something. They also wouldn't be able to implement `ITuple` because ref structs can't implement interfaces.

**Comment by YairHalberstadt** [comment]
@Joe4evr

I believe (but am not sure) that ref structs are purely a language concept, not a runtime one, so I don't think that's true.

Of course the language would have to make sure that such a tuple is never boxed or cast to ITuple. I imagine that's doable though.

Alternatively, creating a RefStructTuple should also be perfectly doable.

**Comment by svick** [comment]
@YairHalberstadt 

> I believe (but am not sure) that ref structs are purely a language concept, not a runtime one

They're not. For example, [if you try to create a regular `struct` with a field of type `Span<T>` using Reflection.Emit](https://gist.github.com/svick/f72b644625dbdbbe6b05e2d8d36710e7), you get the exception:

> System.TypeLoadException: A ByRef-like type cannot be used as the type for an instance field in a non-ByRef-like type.

**Comment by johnkellyoxford** [comment]
> I believe (but am not sure) that ref structs are purely a language concept, not a runtime one, so I don't think that's true.

No, they are properly runtime supported afaik (at least on core). `ByRefLikeAttribute` on a `struct` enforces it, and will prevent it being used as a generic type param or being boxed. 

This would require allowing `ref struct`s to be generic type params with a constraint like `where T : ref struct` i believe
