### ISSUE TITLE
Proposal: treat methods as delegates

### ISSUE THREAD

**Issue by hez2010** [dotnet/csharplang#2604]
## Proposal: treat methods as delegates

```csharp
static int TestMethod(int x) => x;
static void Main(string[] args)
{
    var result = TestMethod.Invoke(3); // same with TestMethod(3), TestMethod is Func<int, int>
}
```

With this proposal, we can extend the method itself by extension methods. For example:
```csharp
public static class FuncExtensions
{
    public static Func<T, Func<U, V>> Currying<T, U, V>(this Func<T, U, V> f) => x => y => f(x, y);
}

class Program
{
    static int Test(int a, int b) => a + b;
    static Main(string[] args)
    {
        Test.Currying()(4)(6); //10
    }
}
```

and there will be no need to create a Func:
```csharp
public static class FuncExtensions
{
    public static Func<T, Func<U, V>> Currying<T, U, V>(this Func<T, U, V> f) => x => y => f(x, y);
}

class Program
{
    static int Test(int a, int b) => a + b;
    static Main(string[] args)
    {
        new Func<int, int, int>((x, y) => Test(x, y)).Currying()(4)(6); // it's redundant
    }
}
```

**Comment by HaloFour** [comment]
What problem is this trying to solve?  How would you deal with overloads?

**Comment by hez2010** [comment]
@HaloFour It's especially useful for functional programming in C#.
Although we have F#, but if we can treat functions/methods in C# as delegates (Func, Action), it will be better.

**Comment by HaloFour** [comment]
But what problems does that solve?  You can create and use delegates pretty easily.  You can pass method groups as arguments to methods directly, as long as the delegate type can be resolved unambiguously.  And conversion through a delegate adds overhead both in allocations and during invocations.

And you'll have to resolve for the overload problem.  Functional languages don't offer overloads, at least in the same contexts where you can use currying or application.

**Comment by Tom01098** [comment]
I love currying and partial application in F#, but it really isn't suited to the way that C#s model of programming works. I think that it pretty much only works with the calling syntax in functional languages, and might cause havoc with overloading as mentioned above.

**Comment by setbbtjl8wwq** [comment]
@hez2010
You may use instead
```c#
new Func<int, int, int>((x, y) => Test(x, y)).Currying()(4)(6)
```
more shorter syntax
```c#
((Func<int, int, int>) Test).Currying()(4)(6)
```
or even define a set of extension methods
```c#
public static Func<Z> Func<Z>(Func<Z> f) => f;
public static Func<A, Z> Func<A, Z>(Func<A, Z> f) => f;
public static Func<A, B, Z> Func<A, B, Z>(Func<A, B, Z> f) => f;
public static Func<A, B, C, Z> Func<A, B, C, Z>(Func<A, B, C, Z> f) => f;
/* etc */

public static Action Action(Action a) => a;
public static Action<A> Action<A>(Action<A> a) => a;
public static Action<A, B> Action<A, B>(Action<A, B> a) => a;
public static Action<A, B, C> Action<A, B, C>(Action<A, B, C> a) => a;
/* etc */
```
and use it like
```c#
New.Func((int x, int y) => x + y).Currying()(4)(6);
```
[The example](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUBgBjwwGYACAbzzJrOttUwDYyBLKYMgFQFMBnYAAp2nAIYw2HMgCMAlGQC8APjKiyiGQG56NHWQzo9VXLVNkAbqLCrFZQYNQBWADwiJbycCXzeA2QDoAYQgwMABPdgBzQVlBABZYplltEzMaRgBOQVFkvVM82ktraVsAOR4Ad38nexEyAA93KTD5ZQb1MhagkPComPjE3NS0zME5FNMAXzxp3GJyRhYMfUcAUXrgHig+VgB7bbxjU1QF5hXnLgknZwBVCQA1JRVg0IioSIuJO7JHwWAAC1YfHOlzI30eZAAZq0VPVFCowvCoYJGp0hrN5vozstyhVDnoAJAnLFLFwALRU1wpDnJKmhSMhKQJRNOpOcAEEJBTzpyyNTrrzufS2oy8MziYseRIAEJcykuXmyvlKGkcmVyqEwqFMlkkqVkJWBDUC9VkI3K1WKiTmoVa0W4cWs/WGiQAEWNCtN5vdFpNButbo1wrpOol2M9/rNgbIqw9asj3oksd9EZdZB9ydtDNDTr9aYzEgAYnGrVH00mi3LLV7o8ni8rNdmxbrJXmA+WY5WyABxEs1jt1iS9lPx/MVsj14dZkU5vVtssFidDiQACT7CdrXeHa5HpcTnaXPdXQbtKWbYaWmHQWPQDivqi1olnravHMpr/ZKsY6DfD6RT/PXMPxld8f0VL9gINFQcn/Z9sUgw1QNHa0ILAr1oMfODLzQjd0yQvc3VQ5CFww2DALnBD2wzfD+2ou8cLHGNSLaACHRbeCGKo8dCxo3DFx4+jiP3OtmOgrCbyEzdD27XjGMHHsiIIgct1E1RxO/STlOk1dZK4g9Jx0wSlP45cyBXVTWMmIA===).

**Comment by ymassad** [comment]
Related: #1943

**Comment by hez2010** [comment]
I think this is already covered by lambda improvements.
