### ISSUE TITLE
Proposal: "Not Propagation"

### ISSUE THREAD

**Issue by dogbiscuituk** [dotnet/csharplang#2605]
myForm.radioButtonNO.Checked = myModel.UseFeature;
myForm.radioButtonYES.Checked = myModel.!UseFeature;

The .! operator extracts a (boolean) property value and logically negates it.

**Comment by aikidos** [comment]
Why not:
```csharp
myForm.radioButtonYES.Checked = !myModel.UseFeature;
```

**Comment by dogbiscuituk** [comment]
Because it's UseFeature I want to negate, not myModel.

**Comment by yaakov-h** [comment]
Member access has higher priority than negation.

`!myModel.UseFeature` is the same as `!(myModel.UseFeature)`.

In a similar vein, `!true.ToString()` is a compiler error, not the same as `false.ToString()`.

**Comment by dogbiscuituk** [comment]
Yes, granted all of that is obvious. Still the '!' in my example is much more clearly associated with the property than the object.

**Comment by ufcpp** [comment]
```cs
static bool Negate(this bool x) => !x;
myModel.UseFeature.Negate();
```

is not enough?

**Comment by dogbiscuituk** [comment]
I was just about to bring up that very example! It shows we already have something similar in the language as it stands - the Negate() is more clearly attached to the property in this fluid syntax, which only strengthens my case for the new operator.

**Comment by dogbiscuituk** [comment]
This might be a good point to state I _was_ originally trolling, and would have been first to spit the dummy if anyone had taken this idea seriously. But after further thought, I'm wondering whether there might be a use for a more general version of this syntax, something along the lines of

    result = myModel.(p=>p<0)Property

where the equivalent of a Select lambda can be inserted between the dot and the object hosting the target property?

**Comment by dogbiscuituk** [comment]
Purely for readability/scanability of course, everything it enables is already doable using only very slightly more (or perhaps less) torturous syntax. But that's true of any additional language feature, after you've reached Turing completeness!

**Comment by CyrusNajmabadi** [comment]
> I was just about to bring up that very example! It shows we already have something similar in the language as it stands - the Negate() is more clearly attached to the property in this fluid syntax, which only strengthens my case for the new operator.

The `!` operator has been part of mainstream programming language for more than 50 years.  The precedence has been well established and understood.  There's no need to fix anything here as nothing is broken.

> Yes, granted all of that is obvious. 

If it's obvious, then there is no value in adding a new and different way to do the exact same thing.  Doing this also limits our ability to use that sort of syntax for some other purpose (for example some sort of null-realted operator a-la `.?`.

**Comment by dogbiscuituk** [comment]
> The ! operator has been part of mainstream programming language for more than 50 years. 

I've been programming for almost all of those 50 years, and honestly cannot remember seeing the "!" operator in BASIC, Fortran, Algol, Pascal, or any flavour of assembler. Would be genuinely interested to learn its provenance if that's true.

> There's no need to fix anything here as nothing is broken.

That accords perfectly with my own opinion! As already explained, this proposal was intended in a humorous vein.

**Comment by CyrusNajmabadi** [comment]
>Would be genuinely interested to learn its provenance if that's true.

It's been around since 'B', if not earlier.    C, C++, Java, C#, Objective-C and more use it for this purpose.

**Comment by dogbiscuituk** [comment]
Was already aware of those, none of which is "more than 50 years" old - I think B is the oldest, and might celebrate its 50th this year? Again, chops if I'm wrong.

**Comment by CyrusNajmabadi** [comment]
> none of which is "more than 50 years" old

It goes back at least 50 years (i haven't looked to see if it goes back further).  There are a wealth of languages since (including several of the most popular of today) that continue to use it for the exact same meaning.  It's a non-broken construct that doesn't need replacement :)

**Comment by dogbiscuituk** [comment]
It's lucky to have such a staunch defender!

**Comment by svick** [comment]
If I was designing a brand new language, I might consider using a different syntax for negation. But I don't think it makes sense to introduce something like that to C#, which already has a well-established and well-understood way to do negation.

On the other hand, I like it when what I'm *typing* matches my thought process and I don't have to jump back and forth in the editor. Which is why I like [ReSharper postfix templates](https://www.jetbrains.com/help/resharper/Postfix_Templates.html): when my though process goes something like:

> **If** **myModel**'s **UseFeature** is **not** set …

I type:

```c#
if (myModel.UseFeature.not)
```

But R# converts that to:

```c#
if (!myModel.UseFeature)
```

**Comment by dogbiscuituk** [comment]
[...] I like [ReSharper postfix templates](https://www.jetbrains.com/help/resharper/Postfix_Templates.html): when my though process goes something like:
> 
> > **If** **myModel**'s **UseFeature** is **not** set …
> 
> I type:
> 
> ```cs
> if (myModel.UseFeature.not)
> ```
> 
> But R# converts that to:
> 
> ```cs
> if (!myModel.UseFeature)
> ```

Lovely. The negation is even more visible, and being a template, it's completely optional. I bet we could implement the entire Forth language as postfix templates!

**Comment by 333fred** [comment]
> This might be a good point to state I was originally trolling, and would have been first to spit the dummy if anyone had taken this idea seriously.

@dogbiscuituk if you're not serious about this proposal, please consider closing it.
