### ISSUE TITLE
Relax 'using static' for 'extension methods'

### ISSUE THREAD

**Issue by setbbtjl8wwq** [dotnet/csharplang#2606]
So, at [the real project](https://www.microsoft.com/en-us/p/solfeggio-education-edition/9p4ddj3q9q73) there are sets of mathematical methods.

For example Window (Apodization) Functions for signal processing
```c#
	public delegate double ApodizationFunc(double binIndex, double frameSize);

	public class Windowing
	{
		public static double Rectangle(double n, double frameSize) => 1;
		public static double Gausse(double n, double frameSize) => default;
		public static double Hamming(double n, double frameSize) =>  default;
		public static double Hann(double n, double frameSize) =>  default;
	}
```
or Scale Functions for visualization purposes
```c#
	public delegate double ScaleFunc(double value);

	public static class ScaleFuncs
	{
		public static double Lineal(double value) => value;

		public static double Log2(double value) =>
			value > 0d ? +Math.Log(+value, 2d) :
			value < 0d ? -Math.Log(-value, 2d) :
			0d;

		public static double Log(double value) =>
			value > 0d ? +Math.Log(+value) :
			value < 0d ? -Math.Log(-value) :
			0d;

		public static double Exp(double value) =>
			value > 0d ? +Math.Exp(+value) :
			value < 0d ? -Math.Exp(-value) :
			0d;

		public static double Sqrt(double value) =>
			value > 0d ? +Math.Sqrt(+value) :
			value < 0d ? -Math.Sqrt(-value) :
			0d;
	}
```
at some places they used like

```c#
using static Rainbow.Windowing;

public ApodizationFunc[] Windows { get; set; } =
{
	Gausse,
	Hamming,
	Hann,
	Rectangle,
};
```
```c#
using static Rainbow.ScaleFuncs;

public ScaleFunc[] AllScaleFuncs = new ScaleFunc[] { Lineal, Log2, Log, Exp, Sqrt };

public ScaleFunc VisualScaleFunc { get; set; } = Lineal;
```
Then I want to extend this functions to get ability use them like extension methods
```c#
//public static double Lineal(double value) => value;
public static double Lineal(this double value) => value;
```
but this simple modification breaks a code which depends from `using static` directives and force to use a full variation
```c#
public ScaleFunc VisualScaleFunc { get; set; } = ScaleFuncs.Lineal;
```

Is it possible to relax `using static` for `extension methods` too? Or is there some unobvious ambiguity?

**Comment by yaakov-h** [comment]
Interesting, I didn't know about this.

For anyone else who wants a [simple playground](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4DsJjlADhAxnAAgFEAPeFKASwHsKBYAKAG9GC2CABAZk4EYA2TgCZiZVuxYN20zjw4DOAFlHkAJgAoA9ACoCMABaUoBbZoLVgAKzi4Y5gJQEmBAL7i2bhp8ZoM2PIQAwtQIcIyS0hwADCpwFDQUANzunDHygqTkVLRQAHSZyVLsKdwEqnAANnAA5hDwSgQAIgCuYGAAngCycAbUGhbWtg6F0iVyIoEpETJspRzKneoDNnbU9inS0zPS1PlkcRr2I9ue2wQb7KUtbV09+n0EAHLq60UzWzIAkBwA7LEoqkSxTeMlO7E8LiAA), click that link. Remove the comment start/end markers to see the problem.

I wonder why it doesn't count as a delegate once it has `this` applied to the first argument.

**Comment by svick** [comment]
@yaakov-h 

> I wonder why it doesn't count as a delegate once it has `this` applied to the first argument.

[The relevant LDM notes say:](https://github.com/dotnet/csharplang/blob/98043cd/meetings/2014/LDM-2014-02-10.md#extension-methods)

> On the other hand, extension methods are designed to be used as such: you only call them as static methods to disambiguate. So it seems wrong if they are allowed to pollute the top-level namespace as static methods. […] Conclusion: We will import extension methods as extension methods, but not as static methods. This seems to hit the best usability point.

**Comment by setbbtjl8wwq** [comment]
@svick 
For me looks strange that `static extension methods` have treated as non-static into `using static` context.

And code overhead (duplication or wrapping math methods for both using as statics and as extensions) is worst then hypothetical pollution of a namespace.

**Comment by miloush** [comment]
I have to say that I tend to include `this` in static methods when it makes sense to let the consumers choose whether to call a method directly or as an extension method. I was under the impression that adding `this` (similar to adding `params`) to an argument is a syntactic sugar expanding the usage, and didn't expect either to actually restrict it, that is confusing indeed.

**Comment by gafter** [comment]
We won't change this because (1) It was designed, quite intentionally to work this way, and (2) Changing the name lookup rules would change the meaning of existing code.
