### ISSUE TITLE
Make new keyword optional when creating instances just as Dart

### ISSUE THREAD

**Issue by imgen** [dotnet/csharplang#2607]
In Dart, we can create a new instance of a class like below
```
var x = ClassA();
```
I think it's quite good, esp. with nested instantiation

**Comment by canton7** [comment]
Surely this is a breaking change, if there's a method called `ClassA`?

**Comment by Unknown6656** [comment]
There is a proposal to use the following instead (#100):
```csharp
ClassA x = new();
```
This would use the same amount of characters as your proposal.

Besides, this proposal is a duplicate of #350.

**Comment by WrongBit** [comment]
Variant with:
    ClassA x = new();
...is mostly helpful, but doesn't work when ClassA is abstract or it is "parent", which should be assigned with derived type. But I agree, shorter syntax could be nice:
    ClassA x = new; // who needs these parents??
    ClassB y = new(some args);

**Comment by YairHalberstadt** [comment]
CLosing as duplicate of https://github.com/dotnet/csharplang/issues/350
