### ISSUE TITLE
[Proposal] is not operator

### ISSUE THREAD

**Issue by montyclt** [dotnet/csharplang#2624]
The oppisite to `is` operator is sounround the expression into parenthesis and negate it. This is difficult to read, specially when is used into a `if` because it has two parenthesis.

```cs
if (!(obj is null))
{
    // obj is not null
}
```
Instead of doing this, I propose `if not` operator:

```cs
if (obj is not null)
{
    // obj is not null
}
```

Negating `is`, the object won't cast, so the `if not` operator won't allow doing this:

```cs
if (obj is not Person person)
{
    // That don't have sense, obj cannot cast to Person, and person variable won't exist.
}
```

**Comment by benaadams** [comment]
Can use `is object` for a not null test
```csharp
if (obj is object)
{
    // obj is not null
}
```

**Comment by Tom01098** [comment]
As `is object` already exists and has been pointed out, can you give an example of where else this would be used? I can't think of a scenario where you would type check that something is not a certain type.

**Comment by montyclt** [comment]
> Can use `is object` for a not null test
> 
> ```cs
> if (obj is object)
> {
>     // obj is not null
> }
> ```

I had not thought to use `is object`.

**Comment by yaakov-h** [comment]
See #882 for a better approach to negation.

Upcoming pattern matching changes will also allow `foo is {}` to be used as a null check.
