### ISSUE TITLE
Warning proposal for this?

### ISSUE THREAD

**Issue by TekuSP** [dotnet/csharplang#2626]
Hi,

When working in my unnamed company I saw a code using "this?" like "this?.Property".
This should generate a warning as "this" can never be a null.

I tried googling it and it looks like unique case.

Thank you

**Comment by YairHalberstadt** [comment]
You can write a Roslyn analyser for it if you want. You can even make it an error. Adding a warning to legal code is a breaking change.

**Comment by TekuSP** [comment]
Is it legal code? I mean who does that? Who casts this to this? ?

**Comment by YairHalberstadt** [comment]
You yourself found it, so presumably other people have it as well. If they have treat warnings as errors on, and they update their version of c#, suddenly their code will fail to compile, despite it being perfectly valid.

There would be more of an argument to make if this was actually dangerous, or this changed the semantics of the code, but given that it's not, there seems to be limited benefit in making this a warning.

**Comment by TekuSP** [comment]
Can be this treated as "Messages" then at least?

**Comment by YairHalberstadt** [comment]
I'm not the one who decides (I have no connection with Microsoft), but I would suggest you raise an issue on Roslyn analysers if you want a publicly available analyser.

**Comment by canton7** [comment]
Note that it's [possible for `this` to be `null`](https://referencesource.microsoft.com/#mscorlib/system/string.cs,550). This is a product of how the method was called: if it's a non-virtual call, it's technically possible for `this` to be `null`. However, the C# compiler will never call a method in a way that means that `this` might be `null`, so everyone ignores the issue (and rightly so). 

You specific bit of code *might* have a reason for null-checking `this`, though...
