### ISSUE TITLE
Improve writing int array to file performance

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/csharplang#2631]
If I have an `int` array, I can write it to a binary file using the following code.

```cs
using (BinaryWriter writer = new BinaryWriter(File.Open(path, FileMode.Create)))
{
    for (int i = 0; i < array.Length; i++)
        writer.Write(array[i]);
    writer.Close();
}
```

But this approach is not optimal. An `int` array is stored in contiguous memory, so I don't understand why there isn't a way to write the entire array in a single call, as I could with a `byte` array (or as I could with C or C++).

I was hoping the newer `Span` could help me here. But `BinaryWriter.Write()` has no overload that accepts `Span<int>`, and you cannot convert an `int[]` to `Span<byte>`.

It's hard to see why these restrictions are necessary. Either allow us to create a `Span<byte>` from other array types, or add a `BinaryWrite.Write()` overload that accepts `Span<int>` or `int[]`.

**Comment by canton7** [comment]
This sounds more like a question for StackOverflow, or perhaps CoreFX. It's certainly not a language feature request.

**Comment by canton7** [comment]
Also, if you don't care about endianness:

```csharp
Span<int> ints = new[] { 1, 2, 3, 4, 5 };
Span<byte> bytes = MemoryMarshal.AsBytes(ints);
writer.Write(bytes);
```

**Comment by SoftCircuits** [comment]
> This sounds more like a question for StackOverflow, or perhaps CoreFX. It's certainly not a language feature request.

Well, I asked a similar question on StackOverflow and it seemed like there wasn't any options that didn't involve allocating and/or copying data, which kind of defeats the purpose of any optimization.

If `Span<>` could be more flexible then it seems like it would be a language issue. I will look into posting in CoreFX.

As far as `MemoryMarshal.AsBytes()`, I don't know what this method does internally. Can you tell me if it allocates or copies any memory? (I prefer not to write unsafe code.)

**Comment by canton7** [comment]
I gave you your answer - you shouldn't need to ask CoreFX to tell you the same thing.

You'll find the [source of `MemoryMarshal.AsBytes` here](https://source.dot.net/#System.Private.CoreLib/shared/System/Runtime/InteropServices/MemoryMarshal.Fast.cs,8b1d9e863a3a8843). As you can see, it does not copy.

**Comment by SoftCircuits** [comment]
My question on StackOverflow did get a number of suggestions. I was trying to avoid any allocating or copying, and unsafe code.

I'll explore `MemoryMarshal.AsBytes`. Maybe that's what I need.

I was thinking it might be nice to allow a `Span<byte>` to be created from an `int[]`. But maybe you are right that there are other efficient options.

**Comment by canton7** [comment]
> I was thinking it might be nice to allow a Span<byte> to be created from an int[].

You can, using `MemoryMarshal.AsBytes`, or `MemoryMarshal.Cast`, or a combination of `Unsafe.As` and `Unsafe.SizeOf`.

Adding these sorts of methods directly onto `Span<T>` would be silly. It makes sense that they're a bit hidden away in classes with scary-sounding names, since you need to be aware of things like endianness to use them safely.

> I'll explore MemoryMarshal.AsBytes

Please do. I tested it before posting it, and it does work. I've wasted my time if you don't try it ><

**Comment by SoftCircuits** [comment]
I'm writing some performance tests now against my original code.

Thanks for your help.

**Comment by SoftCircuits** [comment]
BTW, are you sure `MemoryMarshal.AsBytes()` doesn't allocate any memory? It returns `new Span<byte>`.

**Comment by canton7** [comment]
Yes, very sure. A `Span<T>` is a pointer to some other memory somewhere else. `new[] { 1, 2, 3, 4, 5 }` allocates an array on the heap. `Span<int> ints` is a pointer to the start of that array. The `Span<byte>` is a pointer into that same array of memory, but will read it byte-by-byte instead of int-by-int.

**Comment by SoftCircuits** [comment]
The constructor initialized the member variables. But where are they stored? And I thought `new` allocates memory for an object before calling its constructor.

**Comment by canton7** [comment]
`Span<T>` is a struct. Structs are value types, and are allocated either on the stack (for locals), or inside their parent object (for fields). (In fact, `Span<T>` is a "ref struct", which means it can only ever be allocated on the stack).

This is really C# 101 - I recommend grabbing a beginners' book.

**Comment by SoftCircuits** [comment]
Well, I appreciate your input. I've been programming over 30 years so no need to suggest I'm a beginner. These are just some newer constructs that I don't yet understand what they do internally (and most C# beginners books don't really cover this type of stuff).

**Comment by canton7** [comment]
I didn't suggest you were a beginner to programming, but I suggested that a beginners' book might be a good way to get up to speed on some basic C# - the sort of stuff that it's easy to miss when hopping between languages. Every C# book I've ever read has covered the difference between a class and a struct.

**Comment by SoftCircuits** [comment]
I learned about the difference between a class and a struct (reference vs value type) perhaps a couple of decades ago. I apologize if you think that's where I'm confused.

(And I have Skeet's book, although perhaps I should consider a newer addition.)
