### ISSUE TITLE
[DEFAULT] CleanCode 

### ISSUE THREAD

**Issue by srburton** [dotnet/csharplang#2646]
The method `default (Type) ` is very useful, plus see some changes to improve aesthetics and reduce pollution without code, My proposal is based on `default` know what type is expected and it will convert itself. Only when requested will he have the option of override.

**Current:**

```csharp
public int ReturnInt(){
   return default(int);
}
```

**CleanCode**

```csharp

public int Return(){
   return default;
}

public List<T> Return<T>(){
   return default;
}

public List<T> Return<T>(string empty = default)
{
   return default;
}

public T Return<T>(string empty = default)
{
   return default;
}

// ---------------- override ----------------------------


public object Return()
{
   return default;
}

public object Return()
{
   return default(string);
}

public object Return(object abc = default(string))
{
   return default(int);
}

```

**Comment by HaloFour** [comment]
`default` was added as shorthand for `default(T)` in C# 7.1.  Every one of those "clean" methods compiles, with the exception of the last one, which doesn't make sense anyway.

**Comment by srburton** [comment]
Thank you. I upgraded to c# 7.1 and it worked. 👍 👍 👍 👍 👍

**Comment by Joe4evr** [comment]
Please close.
