### ISSUE TITLE
await in synchronous method

### ISSUE THREAD

**Issue by aiodintsov** [dotnet/csharplang#2648]
# await in synchronous methods

* [x] Proposed
* [ ] Prototype: [Not Started](https://github.com/PROTOTYPE_OWNER/roslyn/BRANCH_NAME)
* [ ] Implementation: [Not Started](https://github.com/dotnet/roslyn/BRANCH_NAME)
* [ ] Specification: [Not Started](pr/1)

## Summary

introduce support for `await` method in synchronous context in this manner:

```c#
public static void Execute()
{
    var result = await ExecuteAsync();
}
```

`await` keyword in synchronous method would behave similarly to `GetAwaiter().GetResult()` and is syntactic sugar. 

## Motivation

using asynchronous methods in synchronous context is common and often resolved as one of these cases:

```c#
public static T Execute()
{
    var result = ExecuteAsync().GetAwaiter().GetResult(); // pattern 1
    var result = ExecuteAsync().Result; // pattern 2
}
```

There are discussions around which method is better and why and there are supports of both; however patterns are present and are boilerplate code and clutter.

* This will improve language aesthetics and remove clutter.
* It will simplify use of asynchronous methods from synchronous methods with well defined side effects.
* It will ensure that promotion of a synchronous method with asynchronous methods used in it doesn't have blocking residues.
* It is intuitively clear.

## Detailed Design

Implementation chosen by compiler may be different but such implementation would guarantee exception propagation with correct context and exception unwrapping.

Additional benefit is that converting such method to synchronous becomes intuitive:

```c#
public static void OtherMethod()
{
    var result = await ExecuteAsync();
    // next statement
}

public static async Task OtherMethod()
{
    var result = await ExecuteAsync();
    // next statement
}
```

converting `OtherMethod` from synchronous to `async` doesn't require changes to the method code while all side effects remain the same, including the fact that `// next statement` only executes after completion of `ExecuteAsync()`

## Drawbacks

Risk of abuse with `GetAwaiter().GetResult()` is present despite missing of this feature as it may already be abused as is.

However propagating `async` up the calling tree will ensure that synchronous method that get converted to async don't contain blocking leftovers with `GetAwaiter()`

## Alternatives

It would be possible to use a different keyword or a new keyword for this for example `sync`

```c#
public static void OtherMethod()
{
    var result = sync ExecuteAsync();
}
```

However perception of behavior of such keyword (wait for the result and then continue) would be to similar to `await` in asynchronous methods.

Also it would still requite to go through the code and replace all `async` with `sync` in the method body when changing it between asynchronous and synchronous.

## Unresolved questions

TBD

## Desgin meetings

TBD

**Comment by HaloFour** [comment]
Apart from the synchronization/deadlocking issues which already make blocking on `async` calls perilous in synchronous methods, this is also not possible from a syntax point of view.  The reason that the `async` keyword was added to the C# language was to force `await` to be a keyword within a method.  Otherwise it would not be possible for the compiler to distinguish whether `await (foo)` was a method call or an attempt to await the result of the expression `(foo)`.

**Comment by aiodintsov** [comment]
> ... this is also not possible from a syntax point of view...

Could you please expand on this statement?

Obviously implementation of `await` would depend on context but source code interpretation is straightforward and from syntax point of view should not be problematic.

**Comment by scalablecory** [comment]
In addition to @HaloFour's feedback,

I rather like the big sore thumb a `.Wait()` or `.GetAwaiter.GetResult()` is. Using them legitimately isn't common, so it makes finding an obvious mistake easy.

**Comment by HaloFour** [comment]
@aiodintsov 

Here's an article that explains it in some detail: https://blogs.msdn.microsoft.com/ericlippert/2010/11/11/asynchrony-in-c-5-part-six-whither-async/

In short, the team decided that attempting to treat `await` as a contextual keyword would be too problematic, so they had the choice of either using a double keyword (like `yield return` in iterators) or applying a keyword to the method signature to promote `await` to a reserved keyword within the method.  They chose the latter.

**Comment by YairHalberstadt** [comment]
The number of legitimate usages of sync over async is very small, and decreasing (with async main in C# 7, and async streams in C# 8).

I think rather than making it easier to do something which is highly problematic, we should look into reducing the remaining hurdles where making a method async is hard.

**Comment by canton7** [comment]
:-1: from me. Apart from the syntactic issues, it means that if you see an `await`, you have to go and look at the method signature to see whether it's going to block the current thread.

Add to that the fact that people have spent 7 years getting used to the fact that `await` does *not* mean "block the current thread", and they now need to unlearn that, and instead learn to always check the method signature as well.

Finally `await` means "asynchronous wait", but with your proposal it would no longer be asynchronous...

**Comment by canton7** [comment]
This will also be a source of bugs. Imagine you're editing a method, and you add an await, without checking whether the method is async. It compiles, so you move on, not realising that you actually added a blocking wait.

It will also catch newbies out, who don't realise that the async on the method signature is so critical.

Imagine you're doing a code review of a UI application. One of the things you're checking is that nothing blocks the UI thread. Previously if you saw an await, you would nod and move on. Now you've got to go and find the method signature every single time, and that might involve some clicking if the review tool has hidden it.

I'm afraid the first thing I would do if this syntax was introduced would be to write an analyser which forbids it.

**Comment by aiodintsov** [comment]
Thank you for your feedback everyone. A lot of interesting read and I am with you that it should be easier to do async rather than fall victim to blockages in async world.

The idea came to me after seeing yet another code sample on MSDN with `GetAwaiter().GetResult()` for no obvious reason though I believe with `async Main()` it is going to be less of an issue as well.

**Comment by mcosmin222** [comment]
The patterns you describe should not be common. If you encountered them in a project a lot, then someone was doing  something very wrong.

Afaik, the pattern doesn't block if the task already completed by the time you call GetResult. So it would make sense to use it if you started the async operation sometime before you need the result. This is a somewhat more commom situation, but you'd still want to await in case the operation didn't finish.

**Comment by Joe4evr** [comment]
> Afaik, the pattern doesn't block if the task already completed by the time you call GetResult. So it would make sense to use it if you started the async operation sometime before you need the result. This is a somewhat more commom situation, but you'd still want to await in case the operation didn't finish.

Even then, you'd still ***always*** want to do it in the following way:
```cs
var t = ExecuteAsync(); //kick off execution of the task
DoStuffInTheMeanTime(); //true parallel work
var result = await t; //only now do you need the result
```

**Comment by mcosmin222** [comment]
Yes, exactly. Come to think of it, the only pace where you'd use GetResults is in combination with ContinueWith.

**Comment by aiodintsov** [comment]
It's clear there is overwhelming consensus against this feature proposal. So I am closing it down.
