### ISSUE TITLE
How to specify 'old' behavior for type parameters with nullable reference types?

### ISSUE THREAD

**Issue by AndreasHeisel** [dotnet/csharplang#2659]
I'am currently trying to adopt nullable reference types. I didn't found a way to express the 'old' behavior of unconstraint type parameters (could either be a struct or a nullable reference type).

If I have

``` csharp
public class Foo<T>
{
  public Foo()
  {}

  public T SomeProperty { get; }
}
```

I get CS8618 Non-nullable property 'SomeProperty' is uninitialized.

Trying to make the property nullable

``` csharp
public class Foo<T>
{
  public Foo()
  {}

  public T? SomeProperty { get; }
}
```
leads to  CS8627 A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.

But constraints are 'logical and' and this would need `struct | class?`.

How do I get rid of the warnings and get the desired behavior?

**Comment by Tom01098** [comment]
Why do you have a readonly property which is not set in the constructor?

**Comment by AndreasHeisel** [comment]
> Why do you have a readonly property which is not set in the constructor?

Because this is a minimal sample. In reality, there are additional constructors as well as a setter. But their presence doesn't influence the warnings/errors.

**Comment by Tom01098** [comment]
I haven't used NRTs before, but off the top of my head this might not be possible because nullable structs and classes are different things entirely and must be known at compile time.

**Comment by yaakov-h** [comment]
There's a set of attributes you can use, but they're about to change (fairly drastically) with the upcoming .NET Core 3.0 Preview 7. I can't find docs on the new attributes at the moment, anyone else want to chime in?

**Comment by canton7** [comment]
[These LDM minutes](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md) are the fairly close to the current state, I think?

**Comment by AndreasHeisel** [comment]
@canton7 : Looks promising. I will give it a try. 

Thanks
