### ISSUE TITLE
Using ConfigureAwait in "await using" declaration

### ISSUE THREAD

**Issue by cincuranet** [dotnet/csharplang#2661]
**Version Used**: 
3.0.100-preview3-010431

**Steps to Reproduce**:

When running the code below, the compiler says `error CS1061: 'ConfiguredAsyncDisposable' does not contain a definition for 'Dummy' and no accessible extension method 'Dummy' accepting a first argument of type 'ConfiguredAsyncDisposable' could be found (are you missing a using directive or an assembly reference?)` which makes absolute sense.

```csharp
namespace test
{
	class AwaitUsingConfigureAwaitTest: IAsyncDisposable
	{
		public async ValueTask DisposeAsync()
		{
			await Task.CompletedTask;	
		}

		public async Task FooBar()
		{
			await using (var test = new AwaitUsingConfigureAwaitTest().ConfigureAwait(false))
			{
				test.Dummy();
			}
		}

		public void Dummy() { }
	}
}
```

That means the code has to be written like this.

```csharp
public async Task FooBar()
{
	var test = new AwaitUsingConfigureAwaitTest();
	await using (test.ConfigureAwait(false))
	{
		test.Dummy();
	}
}
```

Not as succinct as before. 

Is this the final state of this feature or is there some work still pending around this area?

**Comment by jcouv** [comment]
Tagging @stephentoub  as well

**Comment by agocke** [comment]
This is the final state of the feature for C# 8.

**Comment by DenSmoke** [comment]
```C#
var connection = new SqlConnection(Options.ConnectionString);
await using (connection.ConfigureAwait(false))
{
    var command = new SqlCommand(Query, connection) { CommandTimeout = Options.CommandTimeout };
    await using (command.ConfigureAwait(false))
    {
        await connection.OpenAsync().ConfigureAwait(false);
        var sqlDependency = new SqlDependency(command);
        sqlDependency.OnChange += SqlDependencyOnChange;
        CurrentSqlDependency = sqlDependency;
        await using var reader = (await command.ExecuteReaderAsync().ConfigureAwait(false)).ConfigureAwait(false);
    }
}
```
Instead of this:
```C#
await using var sc = new SqlConnection(Options.ConnectionString);
await using var command = new SqlCommand(Query, sc) { CommandTimeout = Options.CommandTimeout };
await sc.OpenAsync().ConfigureAwait(false);
var sqlDependency = new SqlDependency(command);
sqlDependency.OnChange += SqlDependencyOnChange;
CurrentSqlDependency = sqlDependency;
await using var reader = await command.ExecuteReaderAsync().ConfigureAwait(false);
```
I think it needs to be reviewed. I almost don't know situations when we need to continue on captured context. Even in UI I just use something like Dispatcher.Invoke or SynchronizationContext.Post and don't worry about context.

**Comment by qrli** [comment]
The `ConfigureAwait(false)` thing again and it is becoming more messy.
Instead of continuing this, I'd propose to have a standard way to leave the current synchronization context. It could be an API in corefx, not necessarily a language feature.

As some examples from discussions here before:
```cs
async Task Foo() {
  await AsyncHelper.LeaveSynchronizationContext();
  ... // effectively all awaits here behave like ConfigureAwait(false)'ed
}
```
Or
```cs
async Task Foo() {
  using (AsyncHelper.NoSynchronizationContext()) {
    ... // effectively all awaits here behave like ConfigureAwait(false)'ed
  }
}
```
Or with some compiler magic to make it nicer:
```cs
[ConfigureAwait(false)] // or maybe name it [NoSynchronizationContext]
async Task Foo() {
  ... // effectively all awaits here behave like ConfigureAwait(false)'ed
}
```
This can also relief the complains on `ConfigureAwait(false)`.
