### ISSUE TITLE
Discussion: C# Support for fixed sized arrays with enum indexes

### ISSUE THREAD

**Issue by RemmondSoftTechInc** [dotnet/csharplang#2667]
An array could be declared with an enum type as its index:

enum Color { Red, Green, Blue };

int[Color] colorValueMap = new [Color] { 1, 2, 3 };

the compiler would return an error if the above "new [Colors] { 1, 2, 3 }" didn't have the same number of elements as enum Color.

array values would be accessed using the enum as the index E.g:

var i = colorValueMap[Color.Red]

I've used this concept a lot in Delphi Object Pascal.  The advantage is that if a developer ever adds a new enum Color (e.g Purple) then the compiler will prevent the code from compiling until they add a matching colorValueMap value.  

It's very useful for keeping mapped data in sync in an application to prevent runtime errors.  A downside is the developer must make sure the order of the map values matches the order of the enum (never really found this to be an issue).

Currently in C# to get similar functionality I use a Dictionary (e.g. Dictionary<Color, int>) but this won't return a compiler error if a new value is added to the enum Color and thus it's very easy for a developer to add a new enum value and not remember to update the related enum Color maps (e.g colorValueMap).  It's even more useful when it's a multi dimensional array, with Dictionary syntax the maps become very verbose.

**Comment by HaloFour** [comment]
Treating enum members implicitly as integral values isn't permitted by the language in general.  Doing so for indexes doesn't make a lot of sense, particularly given that enum members don't need to be a simple set of incrementing ordinals.  What would happen in this case?

```cs
public enum Color {
    Red = -1,
    Green = 255,
    Blue = int.MaxValue
}
```

**Comment by RemmondSoftTechInc** [comment]
Delphi Object Pascal has the same capability to assign integer values to enum values yet it supports using enums as array indexes.  I'm not sure the magic that goes on with the compiler, but i think it must treat the enum items as unique entities beyond their assigned integer value.

**Comment by HaloFour** [comment]
The CLR doesn't offer such a facility, the only value for each enum element is whatever integral value has been assigned.  It doesn't even have to be an `int`.  There is no other ordinal value that you could use.  This Delphi behavior doesn't sound like it maps well to the CLR or to C#.  I'd suggest that `Dictionary<TKey, TValue>` keyed by the enum is the appropriate route, and if you want the compiler to help identify if you accidentally miss a value you could write an analyzer.

**Comment by CyrusNajmabadi** [comment]
```c#
var colorValueMap = new Dictionary<Color, int> { [Color.Red] = 1, [Color.Green] = 2, [Color.Blue] = 3 };
```

?

**Comment by RemmondSoftTechInc** [comment]
It was/is the magic of the compiler preventing you from missing a value that made it so useful. 
I'll investigate writing an analyzer.
Interestingly, the version of Delphi I was using (V11) was compiling to .NET 2.x. framework (dropped in V12).
Appreciate the feed back.

**Comment by YairHalberstadt** [comment]
If you want to guarantee that every enum is accounted for, switch expressions sound like the better way to that than an array.

**Comment by RemmondSoftTechInc** [comment]
Switch won't catch it at compile time, no?  
Like a Dictionary won't catch it at compile time.  Both are run time errors.
The magic was, my best buddy, the compiler would catch the mistake.

**Comment by HaloFour** [comment]
Switch expressions will check exhaustiveness and warn if you don't cover all of the possible values.  Unfortunately because an enum is just an integral value under the hood you are also required to handle invalid values.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoUnAZgAI4A7AVzCoGEB7DVhKgb1Kv6oAlOABMkVAOII4dcQCEM9OKQC+pctXwsefAZSo4CABioBZABRsOXAMYBKHSQHODAdio2qUAO5oYNgAtHFxCXK04AOmERKgBeAD4qACJpESSkXVDQ8IQIqRlaOMSkgHNpOiTMlxUAbiq1EhUgA=

**Comment by RemmondSoftTechInc** [comment]
@HaloFour Interesting example, never seen a switch expression like that.  How would you handle the invalid values?  Is it using the catch all "_" ?  If so, I guess that would remove the exhaustiveness warning eh?

**Comment by HaloFour** [comment]
@RemmondSoftTechInc

> Is it using the catch all "_" ? If so, I guess that would remove the exhaustiveness warning eh?

Correct, which unfortunately breaks the behavior that you're looking for in that the compiler would enforce that you match all values of the enum.

**Comment by HaloFour** [comment]
@gafter 

It's probably too late at this point but I'd suggest that the current approach of requiring that the developer provide a catch-all for `switch` expressions on enum will lead to programmer error in the case of wanting to add new values to the enum.  The compiler will not warn that the existing `switch` expressions now aren't exhaustive for "valid" values of that enum due to the catch-all which more likely than not will probably just lead to a `throw` expression and isn't much more helpful than just omitting that catch-all in the first place.

This may end up in the realm of analyzers, but I think there's value in ensuring that `switch` expressions (and probably statements as well) cover all of the "valid" values of an enum.

**Comment by YairHalberstadt** [comment]
@HaloFour
This a thousand times over

**Comment by RemmondSoftTechInc** [comment]
I'm not overly fond of the switch idea, it sounds like a new "explicit" flag would be required to not break old code.  The switch is also a relatively expensive solution given it's just a fancy form of if/then.  Using arrays, or maybe a dictionary type, that required all enums to be present would be faster from a value lookup stand point.  I've created my own EnumArray class that ensures all enums have a matching value, but the check occurs at run-time.  Since most of my maps are static in static classes, I'm assuming the app will crash on startup with an error about non-matching values.  This should be good enough for my requirements.

**Comment by HaloFour** [comment]
@RemmondSoftTechInc 

The `switch` expression is already going to be in C# 8.0 which is due to be released in a few months.

> The switch is also a relatively expensive solution given it's just a fancy form of if/then.

Expensive in what way?  For a simple enum the compiler can emit a jump table which is about as fast as you can get, performance wise.

>  I've created my own EnumArray class that ensures all enums have a matching value, but the check occurs at run-time.

You could write an analyzer that ensures that those assignments are made at compile time.

**Comment by RemmondSoftTechInc** [comment]
@HaloFour 
Re: switch statement... oh, didn't realize for simple enums it can emit a jump table for a switch statement, that would be faster. 

Could that idea be applied to arrays then?  Simple enums as array indexes?  I'm not quite sure what a "simple enum" is vs not, I'm assuming an enum with no values assigned, just ints starting at 0? If that's the case the compiler could do that magic of mapping it to an array index without gaps.  If it's not a simple enum then throw a compile error (Simple enums only for array indexes).

**Comment by RemmondSoftTechInc** [comment]
One thing I wasn't 100% sure on is if C# gives you an error if you allocate an array without the correct number of elements:

**static int[] test = new int[4] { 1, 2, 3 };**

this gives me the error: 

**Error CS0847 An array initializer of length '4' is expected**

which is great.

so just need that little step further:

**enum Color { Red, Green, Blue }**

**static int[] test = new int[Color] { 1, 2 };**

would give me: 

**Error CS0847 An array initializer of length '3' is expected**

**Comment by alexis-idigo** [comment]
This would be a very useful feature.
I use enums intensively due to their clear semantic and compile check.
How this topic has been closed without any Close indication?
