### ISSUE TITLE
Feature request: Partial enums

### ISSUE THREAD

**Issue by TheProxyRE** [dotnet/csharplang#2669]
Ok so I thought of maybe of doing the partial keyword on enums
for large enum files like for example cil OpCode list

# Example
for example to do it like this

```csharp
//ArithmeticOpCodes.cs
public partial enum Code
{
Add,
Div,
Mul,
Rem,
Neg
}
```
and
```csharp
//ArithmeticBitwiseOpCodes.cs
public partial enum Code
{
Shl,
Shr,
Shr_Un,
And,
Or,
Xor,
Not
}
```

and after compiling those 2 (or more) concatenate like any other normal enum in finalized clr module

# Issue
The only issue I can see here is the order of unspecified enum values
in the case above its not sure which enum part should be "First" in ordering
so I thought maybe to sort it by file name, or if user want to change the order
maybe some enum placeholder can be done like
```csharp
//ArithmeticOpCodes.cs
[RosyinEnumUtilis(Order = 0)]
public partial enum Code
```
```csharp
//ArithmeticBitwiseOpCodes.cs
[RosyinEnumUtilis(Order = 1)]
public partial enum Code
```
or by simply specifying the first value in enum like in standard c language
like 
```csharp
//ArithmeticBitwiseOpCodes.cs
public partial enum Code
{
Shl = 10,
Shr,  //should be 11
....
}
```

**Comment by mcosmin222** [comment]
But why? Partial classes make sense when using designers and other code generation tools because they separate human authored code from machine generated code. This cannot be done with enums.

**Comment by TheProxyRE** [comment]
> But why? Partial classes make sense when using designers and other code generation tools because they separate human authored code from machine generated code. This cannot be done with enums.

Why wouldn't it be enum is just a class when compiled and partial on enum would yield the same result.
Enum, when compiled, is class with System.Enum as a class and const int fields that represent their values.
And this wouldn't affect anything compiler wise either because of compiler doesn't use those fields most of the times, it 90% because it instead of using ldsfld opcode with Const field, it just use const value and load as plain integer, fields are used only when you want to do something thru reflection with them, or enumerate all enums, but still partial wouldn't mind this because it concatenates all partials into 1 large class. Also this concatenation works for all partial classes, wouldn't be just for enums, I can recommend you to compile a couple of partial classes into some assembly and check the result with some IL viewer (i recommend dnspy you can find it here on GitHub)

Also if you work with large enums it's much easier to sort/separate them in partial classes so it's easier to navigate thru them

**Comment by Tom01098** [comment]
You can always format your enum using whitespace and comments.

It seems like this would be a lot of work for the language team for something that doesn't provide that much benefit.

**Comment by HaloFour** [comment]
> Why wouldn't it be enum is just a class when compiled and partial on enum would yield the same result.

As you mentioned, the difference with enum is that the order of the members matters.  To implement this feature the compiler team would have to add new features that would explicitly specify that behavior.  Given said behavior would have no utility outside of partial enums that would mean that partial enums would need to provide enough of a benefit to justify that cost in terms of time and effort.  I believe that the number of enums that would benefit from this feature, either due to being excessively large or due to being partially generated, is vanishingly small.

**Comment by DaZombieKiller** [comment]
That gets me wondering: what happens with `[StructLayout(Sequential)] partial class` and `partial struct` with regards to ordering?

**Comment by TheProxyRE** [comment]
> That gets me wondering: what happens with `[StructLayout(Sequential)] partial class` and `partial struct` with regards to ordering?

Ok Structs are by default Sequential and I did a small test and seems like it sorts it by member name
![image](https://user-images.githubusercontent.com/12687236/61513686-36577780-a9fe-11e9-8b90-d4476c76d1bd.png)
and the same goes for class with forced sequential
![image](https://user-images.githubusercontent.com/12687236/61513784-7159ab00-a9fe-11e9-9637-62fcbe21d9cc.png)

so I guess there are already some rules regarding finalized struct/class after partial concatenating
