### ISSUE TITLE
Nullable conflicts with generic function returning T or default(T)

### ISSUE THREAD

**Issue by yhvicey** [dotnet/csharplang#2670]
I have a helper method to get an instance of type `T`, or `default(T)` in some condition. Sample:

```cs
public T GetOrDefault<T>(...)
{
    bool condition = (...);
    T value = (...);
    return condition ? value : default; // warning CS8653: A default expression introduces a null value when 'T' is a non-nullable reference type.
}
```

*P.S. This warning won't show up neither in Visual Studio nor VSCode, might need to create an issue in roslyn repo.*

And if I declared the return type to `T?`, compiler complains:

    error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.

Is this by design? What's the correct way to declare a method which intent to get an instance or default value of a type?

**Comment by yhvicey** [comment]
Created rolsyn issue: dotnet/Roslyn#37362

**Comment by yaakov-h** [comment]
I think the `[return: AllowsNull]` attribute was built for this case.

**Comment by yhvicey** [comment]
Looks like currently `AllowNullAttribute` only supports Property, Field and Parameter.
BTW, could you please help point out where's the doc for the syntax `[return: SomeAttribute]`? Thanks in advance!

**Comment by DaZombieKiller** [comment]
Would using `default!` help?

```CSharp
public T GetOrDefault<T>(...)
{
    bool condition = (...);
    T value        = (...);
    return condition ? value : default!;
}
```

**Comment by yhvicey** [comment]
Adding `!` to `default` did resolve the warning. But IMHO, `!` imply that "this expression won't be `null`", however `default` can be null if `T` is reference type

**Comment by YairHalberstadt** [comment]
I think MaybeNull is the attribute you want

**Comment by yaakov-h** [comment]
@YairHalberstadt that does sound more correct

**Comment by yhvicey** [comment]
Found some related LDMs and seems there're lot's of nullable-related attributes: `[MaybeNull]`, `[AllowNull]`, `[NotNull]` and `[DisallowNull]`. Will all those attributes be simplified?

**Comment by yaakov-h** [comment]
Probably not at this stage of the game. We're about 2 months from release and the latest set of attributes will only be shipping for the first time in the _next_ Visual Studio preview build, AFAIK.

**Comment by 333fred** [comment]
Yes, the `MaybeNull` attribute is what is designed for this case.

**Comment by 333fred** [comment]
Specifically, there's two types of attributes: input, and output. `MaybeNull` and `NotNull` can be applied to outputs, and change the nullability of that output from the signature. `AllowNull` and `DisallowNull` can be applied to inputs. There are times when you need to have separate control of either the input or output, and thus we need to have all four of these.

**Comment by RexTremendae** [comment]
What if I want to write a class that have a method that returns a generic type T, but that sometimes it needs to use default(T). This could for example be a kind of lookup class with an out paramter (think TryGetValue() on a Dictionary<,>). I still want to make sure I never get null back, so default(T)! is not really solving my problem. I do realize that default(T) for a reference type would be null, but if I could dream for a bit I would like to define a default value other than null and constraint the generic to only allow types with a non-null default defined. Any thoughts on this?

**Comment by Joe4evr** [comment]
@RexTremendae In the case of `TryGetValue()`, you annotate your `out` param with `[NotNullWhen(true)]`.

**Comment by 333fred** [comment]
As the original question has been answered, I'm closing this issue. Please open a new issue for follow up questions.
