### ISSUE TITLE
[Bug] C#8.0 - Struct member causes a cycle in the struct layout

### ISSUE THREAD

**Issue by louthy** [dotnet/csharplang#2681]
I started converting [language-ext](https://github.com/louthy/language-ext) over to C# 8.0 and immediately ran into a regression.  

Static members of generic structs (where the type is the struct itself) now throw an error where they didn't before.
```
error CS0523: Struct member 'Test<A>.Value' of type 'Test<A>' causes a cycle in the struct layout
```
This is a simple test-case:
```c#
    public struct Test<A>
    {
        public readonly static Test<A> Value = new Test<A>();
    }
```
I use this heavily for the ad-hoc polymorphism feature of lang-ext; although I could drop it, it does seem rather arbitrary.

```c#
    public struct EqSeq<A> : Eq<Seq<A>>
    {
        public static readonly EqSeq<A> Inst = default(EqSeq<A>);

        /// <summary>
        /// Equality check
        /// </summary>
        [Pure]
        public bool Equals(Seq<A> x, Seq<A> y) =>
            default(EqSeq<EqDefault<A>, A>).Equals(x, y);

        /// <summary>
        /// Get hash code of the value
        /// </summary>
        /// <param name="x">Value to get the hash code of</param>
        /// <returns>The hash code of x</returns>
        [Pure]
        public int GetHashCode(Seq<A> x) =>
            default(EqSeq<EqDefault<A>, A>).GetHashCode(x);
    }
```

**Comment by YairHalberstadt** [comment]
This looks like an issue for GitHub.com/dotnet/roslyn

**Comment by louthy** [comment]
@YairHalberstadt Yep, posted it there, thanks

**Comment by YairHalberstadt** [comment]
I cannot reproduce this on sharplab, so maybe it's been fixed?

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ACX2ACAzNrAgK4DGM2AKnLADwCCAfALABQe2A3p99yLYEcCCgD2AOwA2ATwIBGAGy16MZi2wA1CNLJxsAXmyS4Ad1WNWACgCUAbn54AvkA=
