### ISSUE TITLE
Proposal: try-catch continue;

### ISSUE THREAD

**Issue by SnGmng** [dotnet/csharplang#2684]
It would be nice if there is an option to use the "continue;" keyword inside a catch block. Currently, the execution after the "catch" block continues after the catch block (or in the finally block), but there is no way to continue the execution in the try block. Here is an example: Consider this code:

```
public void DoSomething(string[] jsonData)
{
    try 
    {
        Url = GetUrl("href", ""));
        imageUrl = GetAttributeValue("src");
        title = jsonData[1];
        releaseYear = jsonData[2];
        seasonnr = int.Parse(jsonData[3]);
        genre = Util.GenreFromString(jsonData[4]);
        subGenre = Util.GenreFromString(jsonData[5]);
        language = jsonData[6];
        subType = SomeFunction()
        ...
    }
    catch
    {
    
    }
}
```
If any of these statements throws a exception, every statement in the "try" block that is after the statement that threw the exception is not executed. To archieve that every statement is executed, you would have to make a try-catch block for EVERY statement and that would take ages and looks ugly:

```
public void DoSomething(string[] jsonData)
{
    try
    {
        Url = GetUrl("href", ""));
    }
    catch { }
    try
    {
        imageUrl = GetAttributeValue("src");
    }
    catch { }
    try
    {
        title = jsonData[1];
    }
    catch { }
    try
    {
        releaseYear = jsonData[2];
    }
    catch { }
    ...
}
```
The "continue;" statement would fix this:
```
public void DoSomething(string[] jsonData)
{
    try 
    {
        Url = GetUrl("href", ""));
        imageUrl = GetAttributeValue("src");
        title = jsonData[1];

        // if this statement fails for example,
        releaseYear = jsonData[2];
        // after the "catch" block, execution would continue here
        seasonnr = int.Parse(jsonData[3]);

        genre = Util.GenreFromString(jsonData[4]);
        subGenre = Util.GenreFromString(jsonData[5]);
        language = jsonData[6];
        subType = SomeFunction()
        ...
    }
    catch
    {
        // Do some diagnostics here, etc.
        // then continue in the "try" block
        continue;
    }
}
```

**Comment by theunrepentantgeek** [comment]
This looks very much like the old `on error resume next` from the days of VB6 and would likely _at least_ as fertile a source of subtle and hard to diagnose bugs.

Why "at least"?

Because applications written in VB6 didn't need to accommodate asynchrony and other constructs common in modern development.

**Comment by SnGmng** [comment]
> This looks very much like the old `on error resume next` from the days of VB6 and would likely _at least_ as fertile a source of subtle and hard to diagnose bugs.
> 
> Why "at least"?
> 
> Because applications written in VB6 didn't need to accommodate asynchrony and other constructs common in modern development.

Yeah but unlike with `on error resume next`, you _can_ diagnose bugs just as much as normal, because the "catch" block is _still_ executed:

```
catch (Exception ex)
{
    Debug.WriteLine("Do some diagnostics, exception source, handling or whatever here")
    continue;
}
```

**Comment by CyrusNajmabadi** [comment]
`continue` is already legal in a `catch` block:

```c#
        foreach (var a in Enumerable.Range(1, 2))
        {
            try
            {

            }
            catch
            {
                continue;
            }
        }
```

This would change semantics.

**Comment by HaloFour** [comment]
Being able to jump backwards into the `try` block is quite unstructured and would require some very nasty IL which likely would not work well with the existing state machinery used by `async` or by iterators.  This is very much like the existing `On Error`/`Resume Next` feature of VB.NET which was carried over for legacy purposes but is discouraged in lieu of using `Try`/`Catch` instead.

And, as has already been mentioned, `continue` is legal within a `catch` block if the `try`/`catch` is nested within a loop.

**Comment by canton7** [comment]
What about:

```csharp
try
{
    var x = ThisMethodThrows();
    DoSomethingWith(x);
}
catch { continue; /* Or whatever keyword */ }
```

Presumably the `continue` continues execution at the line `DoSomethingWith(x)`? What value does `x` have there? `ThisMethodThrows` threw an exception, and so didn't return a value that could be assigned to `x`.

**Comment by SnGmng** [comment]
> What about:
> 
> ```cs
> try
> {
>     var x = ThisMethodThrows();
>     DoSomethingWith(x);
> }
> catch { continue; /* Or whatever keyword */ }
> ```
> 
> Presumably the `continue` continues execution at the line `DoSomethingWith(x)`? What value does `x` have there? `ThisMethodThrows` threw an exception, and so didn't return a value that could be assigned to `x`.

This would generate the well known compiler error: `CS0103  C# The name 'x' does not exist in the current context`. But this doesnt matter anymore because canton7 already explained to me why this feature cant be implemented unfortunalely and i agree with him, allthough i would find this feature very useful (atleast for me).

**Comment by canton7** [comment]
So you could only ever use `continue` where the corresponding `try` block did not have data dependencies between any two statements, is that what you're saying? That severely limits its usefulness...

**Comment by SnGmng** [comment]
> `continue` is already legal in a `catch` block:
> 
> ```cs
>         foreach (var a in Enumerable.Range(1, 2))
>         {
>             try
>             {
> 
>             }
>             catch
>             {
>                 continue;
>             }
>         }
> ```
> 
> This would change semantics.

If i would i apply this to the example i showed above, it would just throw the same error 2 times, because it starts the execution at the beginning of the try block and not after the statement that threw the exeption. I would have to use Relection to make it work like this.

**Comment by CyrusNajmabadi** [comment]
> If i would i apply this to the example i showed above, it would just throw the same error 2 times, because it starts the execution at the beginning of the try block 

"start[ing] the execution at the beginning of the try block" **is** breaking semantics.  It has nothing to with errors being thrown.  It has to do with the same code that has *already* shipped now doing something different now than it did in the past.

**Comment by SnGmng** [comment]
> So you could only ever use `continue` where the corresponding `try` block did not have data dependencies between any two statements, is that what you're saying? That severely limits its usefulness...

Using the `continue` would be the same as chaining multiple try and catch blocks, like the example above. If you want to have data dependencies between any two statements, just declare the variable outside of the `try` block. In this case `x` would be `null`

**Comment by CyrusNajmabadi** [comment]
>Using the continue would be the same as chaining multiple try and catch blocks,

Again, this would *break* existing code.

this code works *today*:

```c#
        foreach (var a in Enumerable.Range(1, 2))
        {
            ... code above hte try ...

            try
            {
                var x = ThisMethodThrows();
                DoSomethingWith(x);
            }
            catch
            {
                continue;
            }
        }
```

That 'continue' will send you back to the loop.  It is not acceptable to do anything but that.

**Comment by SnGmng** [comment]
In my last comment i was adressing canton7s comment, not yours. Anyways, i misinterpreted your first comment, and as i already said, im already convinced that this feature is not as good as i imagined it to be in my mind.

**Comment by canton7** [comment]
I think this would be both highly confusing, and the opposite of the "pit of success". I've written a lot of code, and I have never written a chain of try/catch blocks around every single line, where each catch block is identical, as in your example. Different method calls will throw different exceptions, which will need different catch blocks and different handling. 

What not write yourself a method like:

```csharp
public static void Do(Action action) 
{
    try
    {
        action();
    } 
    catch { } 
} 

public static void Do<T>(Func<T> func) 
{
    try
    {
        return func();
    } 
    catch { } 
} 
```
And then you can wrap every operation which might fail in `Do(...) `. 

(This is all assuming you pick a different keyword of course)

**Comment by SnGmng** [comment]
As i said, i already admitted that my idea is trash. The example code i mentioned is actually real world code i am working on right now, and if you know any other way how i could avoid chaining try-catch blocks in the example above, please let me know. Otherwise i would like to close this issue.

**Comment by canton7** [comment]
... But in your example, there's a data dependency between the expression which fetches the value to assign to the property, and the expression which actually assigns it. (Or in other words, what happens if you fail to *get* the value to adding to the property?) Therefore your code cannot compile, per your own explanation above.

I gave you the code for a couple of methods which might help.

You are the only one here with the power to close this issue :P
