### ISSUE TITLE
Feature request: new operator ?= :

### ISSUE THREAD

**Issue by AHulshoff** [dotnet/csharplang#2685]
It would be nice if there is an operator that could replace an if statement without an else clause.
I frequently come across statements like:
`if (x % 5 == 1)
{
     y = x * 2;
}`

Something like the following would be nice to have:
`y ?= x % 5 == 1 : x * 2;`

Basically, that would mean the operator would be build up like:
`result ?= condition : consequence;`

**Comment by spydacarnage** [comment]
What would `y` equal if the condition is false?

Especially in a declaration scenario:
```csharp
int y ?= x % 5 == 1 : x * 2;
```

**Comment by AHulshoff** [comment]
In that case, y would remain unchanged.
What it should replace is a situation like this:
`y = x % 5 == 1 ? x * 2 : y;`

**Comment by canton7** [comment]
The question was particularly about a declaration scenario, where you're both declaring and initialising the variable at the same time, e.g. 

```csharp
int y ?= x % 5 == 1 : x * 2;
```

Note the `int y` which declares the variable. What value would `y` have after the line of code above, given that it didn't have a previous value, so it can't "remain unchanged".

**Comment by HaloFour** [comment]
I don't see why the proposed syntax is nicer.  It's not less verbose (you can omit the braces), it just moves things around and buries the conditional, which should be the most important part of the statement.

**Comment by AHulshoff** [comment]
> The question was particularly about a declaration scenario, where you're both declaring and initialising the variable at the same time, e.g.
> 
> ```cs
> int y ?= x % 5 == 1 : x * 2;
> ```
> 
> Note the `int y` which declares the variable. What value would `y` have after the line of code above, given that it didn't have a previous value, so it can't "remain unchanged".

`y` would have the default value when it is not going to be initialized. Just like an uninitialized variable, so the variable would be in the same state as just declaring the variable without assigning a value.

**Comment by canton7** [comment]
> Just like an uninitialized variable, so the variable would be in the same state as just declaring the variable without assigning a value.

Uh, local variables *have* to be assigned. You cannot write:

```csharp
int x;
Console.WriteLine(x);
```

Your proposal would change this, and allow local variables to be used before being assigned in some cases.

**Comment by AHulshoff** [comment]
> I don't see why the proposed syntax is nicer. It's not less verbose (you can omit the braces), it just moves things around and buries the conditional, which should be the most important part of the statement.

In what way does that differentiate with the ?: operator? The shortcoming of this operator is that you always have to define the alternative. Another option would be to make the alternative not mandatory in?: operator.

**Comment by CyrusNajmabadi** [comment]
> Just like an uninitialized variable, so the variable would be in the same state as just declaring the variable without assigning a value.

If it is potentially uninitialized, you would not be able to use it.

**Comment by CyrusNajmabadi** [comment]
`In what way does that differentiate with the ?: operator? `

with `?:` you always have a value, so teh variable is always initialized.

> Another option would be to make the alternative not mandatory in?: operator.

If you don't provide the alternative, then what value does your variable have?  If the answer is "it isn't initialized", then there's literally *nothing* you can do with it except assign a value to it (which would thne defeat the purpose of any partial-initializer you already gave).

**Comment by AHulshoff** [comment]
Hmm, point well taken...
