### ISSUE TITLE
Nullary and string.empty

### ISSUE THREAD

**Issue by mbreaton** [dotnet/csharplang#2692]
a common pattern i come across is `var str = string.IsNullorEmpty(str) ? "default" : str`. Unfortunately the nullary(?) operator (`??`) only works with nulls and not empty strings. It may be useful to have another nullary type (perhaps `???`) which would provide that functionality?

```
var str = str ??? "default"
```

**Comment by TonyValenti** [comment]
@mbreaton - I suggest the following (forgive casing. On my phone)

Public static string WithValue(this String This, string Value){
Return string.IsNullOrEmpty(This) ? Value : This;
}

**Comment by yaakov-h** [comment]
A common pattern I've seen is `str.NullIfEmpty() ?? "default"`.
