### ISSUE TITLE
Distinguish between concrete and abstract ranges

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/csharplang#2693]
concrete range: 2 .. 17
abstract range: 2 .. ^17

the concrete range can have use on its own, e.g. by foreach'ing over it.
the abstract range can only be used to get other ranges or be applied on some collection to get the elements in that range.

Let ConcreteRange inherit from Range and have it additionally have GetEnumerator().

**Comment by CyrusNajmabadi** [comment]
> Let ConcreteRange inherit from Range 

`Range` is a struct.  Nothin can inherit from it.

> the concrete range can have use on its own, e.g. by foreach'ing over it.
> the abstract range can only be used to get other ranges or be applied on some collection to get the elements in that range.

I'm not getting the value here.  What is this needed for?

**Comment by AdmiralSnyder** [comment]
being not able to write 
`foreach (var i in 3 .. 17)`
feels counterintuitive and I didn't find a discussion on that when I looked for it, so I brought it up.
Didn't think about struct, though...

**Comment by CyrusNajmabadi** [comment]
> feels counterintuitive

You don't need a language feature for that.  Just ask Corefx to augment range like so:

```c#
public struct Range
{
     public Enumerator GetEnumerator() { /* ... provide the impl for them ... */ }
     public struct Enumerator { /* ... more impl ... */ }
}
```

Now Ranges will be enumerable without any need for language changes.  Feel free to close this out and propose issue/Pr over at dotnet/corefx.  Thanks!

**Comment by AdmiralSnyder** [comment]
adding an Enumerator to Range itself will lead to the problem that abstract ranges (ones that have  a ^7 at any end) simply cannot be enumerated, so what should happen? throwing? not yielding?

**Comment by CyrusNajmabadi** [comment]
>  so what should happen? throwing? not yielding?

What would you have wanted C# to do when enuemrating a Range?  Whatever you watned C# to do, you could just encode in your GetEnumerator method.

**Comment by canton7** [comment]
@AdmiralSnyder I suggest looking into how ranges have been designed. Whether a range is from the end is captured by [`Index.IsFromEnd`](https://docs.microsoft.com/en-us/dotnet/api/system.index.isfromend?view=netstandard-2.1#System_Index_IsFromEnd), rather than in the type system. There is no way to tell at compile-time whether a given range starts or ends at the end. Since we are very close to C# 8, that will almost certainly not change.

That said, I'm personally opposed to having `foreach (int i in 0..10)` mean the same as `for (int i = 0; i < 10; i++)`. We have a perfectly good `for` loop syntax already, and there is no need to introduce something which looks different but means exactly the same.

**Comment by vladd** [comment]
@canton7 For example, in Swift range is a generic over index type. C# could have the same, making Range<int> iterable and Range<Index> non-iterable. (This would perhaps require extension GetEnumerator() which is not actually present in the current C#.)

**Comment by pie-flavor** [comment]
@canton7 It may be perfectly good syntax but it's syntax not related to ranges. I could also say `for (using var enumerator = thing.GetEnumerator(); enumerator.MoveNext(); enumerator.Current)` (or whatever the correct syntax is), but `foreach` is just so much cleaner. You could say that you want to increment repeatedly until the mutable variable no longer is less than ten, or you could just say give me every number between 0 and 10.

**Comment by YairHalberstadt** [comment]
I'm going to close this as Ranges have already shipped, and any changes to how they worked now would be a breaking change.

You can foreach over a range in C# 9.0 by defining an extension GetEnumerator, like the one defined in [this package](https://www.nuget.org/packages/RangeForeach/)
