### ISSUE TITLE
Feature request: Easy declaration of bitwise enums

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/csharplang#2696]
Often times, one would make an enum with explicit values for use as bitwise flags that can be combined together using bitwise operators such as `&`, `|`, and `^`. [Example usage](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=netframework-4.8):

```
enum MultiHue
{
  Black = 1,
  Red = 2,
  Green = 4,
  Blue = 8
};
```

What I propose is a way to easily declare these enums with these values, such that you would not need to write `= 8` etc, and C# would automatically know that the next value is double the previous value, similarly to how enums already increase values by 1 by default. Example syntax:

```
bitwise enum MultiHue
{
  Black, // Value is 1
  Red, // Value is 2
  Green, // Value is 4
  Blue // Value is 8
};
```

The page I linked above also included "None" at the beginning set to a value of zero. I think a zero value at the beginning would be confusing to include by default, as it would break the pattern of "next = previous * 2", however we could easily allow including a "None" value like this:

```
bitwise enum MultiHue
{
  None = 0, // Value is 0
  Black = 1, // Value is 1 (explicit to keep with the pattern)
  Red, // Value is 2
  Green, // Value is 4
  Blue // Value is 8
};
```

**Comment by yaakov-h** [comment]
Duplicate of #1178?

**Comment by DaZombieKiller** [comment]
Why not just do this?:

```CSharp
[Flags]
public enum MultiHue
{
    None  = 0,
    Black = 1 << 0,
    Red   = 1 << 1,
    Green = 1 << 2,
    Blue  = 1 << 3,
}
```

I've always found this far superior to manually writing out `1, 2, 4, 8, etc`. Not sure why it's not more common.

**Comment by CyrusNajmabadi** [comment]
or just:

```c#
[Flags]
public enum MultiHue
{
    None  = 0b0000,
    Black = 0b0001,
    Red   = 0b0010,
    Green = 0b0100,
    Blue  = 0b1000,
}
```

**Comment by mburbea** [comment]
The other issue is you can declare named flags on an enum that represent multiple states. 
[Flags]
public enum P
{
    None = 0,
    Read = 1,
    Write = 2,
    ReadWrite = Read | Write,
    Execute = 4
}

Without explicitly defining a value how would this work?

**Comment by aaronfranke** [comment]
@mburbea Like this:

```
[Flags]
public bitwise enum P
{
    Read, // Value is 1
    Write, // Value is 2
    Execute, // Value is 4
    ReadWrite = Read | Write // Value is 3
    // If you included another entry here without an explicit value it would be 6
}
```

Also, how could this proposal possibly cause issues? It's optional.

**Comment by DaZombieKiller** [comment]
> Also, how could this proposal possibly cause issues? It's optional.

It's less that it could cause issues per se, and more that it doesn't have enough value to be considered over other feature proposals in its current form. There are multiple ways to clearly define flags already, and (in my opinion) defining a flags enum isn't a common enough action to warrant special syntax (and a whole new keyword!).

**Comment by aaronfranke** [comment]
The sequence that would make the most sense to me is `next = previous * 2`. C# already has an automatic sequence of `next = previous + 1`, and my proposal is arguably the 2nd most used case.

However, it doesn't necessarily have to be a keyword, maybe `[Flags]` could be used. https://github.com/dotnet/csharplang/issues/1178

**Comment by CyrusNajmabadi** [comment]
> The sequence that would make the most sense to me is next = previous * 2

What doesn't make sense about the existing ways to do this that were specified above?  For example the binary approach is simple and clear and doesn't require any sort of additional operator or math operations.

**Comment by aaronfranke** [comment]
The existing ways make perfect sense, but I'm wondering if there can be a simpler syntax.

As @Korporal stated in his issue about `[Flags]`:

> but sadly requires the developer to manually specify the value of each member using one of several options, all of which are laborious:

> https://stackoverflow.com/questions/10558621/any-trick-to-defining-an-enum-as-flags-powers-of-2-without-eventually-needing-a/47729978#47729978

> So why not provide a way to do this automatically (and reliably, reducing risk of typos that could go undetected even in heavy testing)?

**Comment by DaZombieKiller** [comment]
> Another argument is that an easy and consistent way to do this would reduce the need for multiple competing standards

That just reminds me of this:

![](https://imgs.xkcd.com/comics/standards.png)

I'm not really seeing the benefit, manually specifying the values isn't too much effort. Especially with only a small handful of values.

**Comment by CyrusNajmabadi** [comment]
> So why not provide a way to do this automatically 

Because features start out at [Minus 100](https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/), and this jsut doesn't seem valuable enough to warrant the huge amount of work to get it into the language.

> (and reliably, reducing risk of typos that could go undetected even in heavy testing)?

If concerned about typos, then you can trivially write an analyzer to check that your flags enum is written properly.

**Comment by aaronfranke** [comment]
I'll close this since it's effectively a duplicate of https://github.com/dotnet/csharplang/issues/1178. A few years down the line, if that's implemented and I still have issues, I'll re-open this.
