### ISSUE TITLE
Bring back Andy! or some other logo for C#

### ISSUE THREAD

**Issue by HappyTreesDev** [dotnet/csharplang#2708]
A long time ago C# had a logo called Andy based off of the creator. It would be great to bring back the logo or make a new one to represent the language. The official logo would help with branding of the language and its usage all over the place. Maybe a logo that adds space to support the compiler used or the framework used along with the language.

**Comment by Gnbrkm41** [comment]
Whatever the new logo might be, it must be better than the [Gopher](https://www.bing.com/search?q=Golang+gopher) :^)

**Comment by orthoxerox** [comment]
Wasn't there a Superman/gemstone-styled logo already?

**Comment by LokiMidgard** [comment]
Oreyl uses the Grey Crowned Crane (African Crowned Crane)

**Comment by DongchengWang** [comment]
Or just a simple "C#" logo like this?

![csharp-dotnet](https://user-images.githubusercontent.com/29004603/75462714-9dd79b80-59bf-11ea-8e6b-575765733340.png)

It's great to have a official logo even the simplest one.
