### ISSUE TITLE
[Proposal] Mutating auto properties

### ISSUE THREAD

**Issue by montyclt** [dotnet/csharplang#2712]
Today, if a property need to do some logic, we need to write a backing field for this property, see this example where name is automatically uppercased:

```cs
public class Person
{
    private string _name;

    public string Name
    {
        get => _name;
        set => _name = value.ToUpper();
    }
}
```
My proposal is allow mutations in auto properties like this:

```cs
public class Person
{
    public string Name { get; set => value.ToUpper() }

    // Or without inline:
    public string Name
    {
        get;
        set
        {
            return value.ToUpper();
        }
    }
}
```

This feauture can reduce significally the verbosity writting classes. The main problem that I can see is that `set` method return value is `void` and changing it to the type of property is an important breaking change. I have not idea how handle this problem.

**Comment by yaakov-h** [comment]
I would expect that with #140, which many consider the gold-standard proposal for next evolving autoproperties, one would be able to do:

```csharp
public class Person
{
    public string Name
    {
        get;
        set => field = value.ToUpper();
    }
}
```

I just hope that one gets done some day.

**Comment by montyclt** [comment]
I did'n notice about #140. I love the idea of `field` keyword. I close this as duplicated.

**Comment by jnm2** [comment]
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
