### ISSUE TITLE
Access violation when calling interface default implementation

### ISSUE THREAD

**Issue by gpeipman** [dotnet/csharplang#2714]
I managed to crash IIS and Kestrel with this code (0xc0000005 - Access Violation):

```
public interface IDummy
{
    void SayHello()
    {
        Debug.WriteLine("Hello");
    }
}

public abstract class AbstractDummy : IDummy
{
    public virtual void SayHello()
    {
        ((IDummy)this).SayHello();
    }
}

public class Dummy : AbstractDummy
{
    public override void SayHello()
    {
        base.SayHello();
    }
}

var dummy = new Dummy();
Dummy.SayHello();
```

**Comment by HaloFour** [comment]
This repo is specifically about the design and evolution of C# as a language.  If you've found a problem with the implementation of the feature in the runtime you might want to take it to [CoreCLR](https://github.com/dotnet/coreclr) which is the repo for .NET Core.

Incidentally, are you running this app under .NET Core?

**Comment by yyjdelete** [comment]
The above code lead to an StackOverflowException.
`dummy.SayHello()`: Dummy.SayHello()
while (true) 
{
    call `base.SayHello()`: AbstractDummy.SayHello()
    call `((IDummy)this).SayHello();`: Dummy.SayHello()->`AbstractDummy.SayHello()` implement `IDummy.SayHello()` and `Dummy.SayHello()` override it.
}


And StackOverflowException may lead to 0xc0000005(Access Violation) if it happen on an async path and an debugger is attached.
https://github.com/dotnet/coreclr/issues/18541

**Comment by gpeipman** [comment]
Weird... this code works:

``` csharp
public interface IDummy
{
    void SayHello2()
    {
        Debug.WriteLine("Hello");
    }
}

public abstract class AbstractDummy : IDummy
{
    public virtual void SayHello()
    {
        ((IDummy)this).SayHello2();
    }
}

public class Dummy : AbstractDummy
{
    public override void SayHello()
    {
        base.SayHello();
    }
}
```
For this code I get errors about Dummy and AbstractDummy not having method SayHello2(); I tried to make SayHello2() public but still same problem.

``` csharp
public class Dummy : AbstractDummy
{
    public override void SayHello()
    {
        this.SayHello2();
        base.SayHello2();
    }
}
```

**Comment by gpeipman** [comment]
And yes, I'm running this code on .NET Core 3.0 Preview 7.

**Comment by yaakov-h** [comment]
That seems to follow the design of DIM.

**Comment by canton7** [comment]
According to "Base interface invocations" [here](https://github.com/dotnet/csharplang/issues/288), what you want is `IDummy.base.SayHello()`?

**Comment by YairHalberstadt** [comment]
Closing as the given code StackOverflows, which is why you get this exception. See https://github.com/dotnet/csharplang/issues/2714#issuecomment-519069799 for an explanation of why.
