### ISSUE TITLE
Proposal: Provide an easy way to execute C# code stored in a string variable at runtime

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#272]
For example:
```C#
string code=Console.Readline();
bool ok=TryExecute(code); //ok=true if execute successfully, otherwise ok=false
```

**Comment by DavidArno** [comment]
There already are various ways of compiling and executing C# code at runtime, such as using [`CSharpCodeProvider`](https://www.codeproject.com/Tips/715891/Compiling-Csharp-Code-at-Runtime) or [Roslyn](http://www.tugberkugurlu.com/archive/compiling-c-sharp-code-into-memory-and-executing-it-with-roslyn). In all cases, you could then create a library that provides a `TryExecute` wrapping around those solutions.

Providing this as a language feature seems complete overkill to me though.

**Comment by svick** [comment]
Why isn't `await CSharpScript.EvaluateAsync(code);` (or even just `await EvaluateAsync(code);` with `using static`) good enough for you?

**Comment by vbcodec** [comment]
also pls VB execution :)

**Comment by elcergey** [comment]
Actually, that would make it look like scripting languages (evals, EXEC and so on). Modern languages generally implement this with the help of libraries.
