### ISSUE TITLE
string.Format("{{{0}}}", Guid.NewGuid()) throw FormatException

### ISSUE THREAD

**Issue by paveliak** [dotnet/csharplang#2723]
Hi

There seems to be an issue with escaping curly braces in the format string when custom format specifier is provided. Below is a test program with and without format specifier. First line works fine. Second line throws FormatException. Tested on VStudio 16.2.0 targeting NetFX 4.7.2.

```
            Console.WriteLine(string.Format("{{{0}}}", Guid.NewGuid()));
            Console.WriteLine(string.Format("{{{0:N}}}", Guid.NewGuid()));
```
Output:
```
{55b5e097-edc2-453b-b1e8-8b364d8be083}

Unhandled Exception: System.FormatException: Format String can be only "D", "d", "N", "n", "P", "p", "B", "b", "X" or "x".
   at System.Guid.ToString(String format, IFormatProvider provider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at RedisClusterTest.Program.Main(String[] args)
```

Thanks,
Pavel

**Comment by svick** [comment]
A clearer way to reproduce this:

```c#
using System;

class Program
{
    static void Main() => Console.WriteLine(string.Format("{{{0:N}}}", new C()));
}

class C : IFormattable
{
    public string ToString(string format, IFormatProvider formatProvider) => $"'{format}'";
}
```

This prints `{'N}'`, when the expectation is that it should print `{'N'}`.

Though this is not related to the C# language, this issue should be moved to the dotnet/corefx repo.

**Comment by svick** [comment]
Though it looks like this behavior has been known for a very long time and is not actually a bug, see [*String.Format gottach*](https://blogs.msdn.microsoft.com/brada/2003/12/26/string-format-gottach/) from 2003.

**Comment by yaakov-h** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/2114

**Comment by paveliak** [comment]
Thanks. Closing.
