### ISSUE TITLE
Question: Why are attempts to change the exception from inside the filter are silently ignored?

### ISSUE THREAD

**Issue by quixoticaxis** [dotnet/csharplang#2725]
There is a question that I can't find the answer to, and it bothers me for quite a while. There is no clause in ECMA-334 or in [github spec](https://github.com/dotnet/csharplang/blob/master/spec/statements.md#the-try-statement) (at least I didn't find it) that explains why exception filter cannot change the exception. Don't get me wrong, I'm not implying it should be possible.

Look at this code:
```
Boolean TryToChangeException(ref Exception e)
{
    e = new InvalidOperationException();
    return false;
}
```

```
try
{
    throw new Exception();
}
catch(Exception exception1) when TryToChangeException(ref exception1)
{
    // this block is not executed
}
catch(Exception exception2)
{
    // this block is executed
    if (exception2 is InvalidOperationException)
    {
        Console.WriteLine("This is never printed.");
    }
}
```

The exception filter which accepts `ref` arguments is working not as it could be expected. My main question is whether this scenario is described somewhere in the spec. I'm also wondering why not forbid passing arguments by reference into the exception filters.

**Comment by YairHalberstadt** [comment]
exception1 is a different variable to exception2, so this seems right to me.

**Comment by YairHalberstadt** [comment]
This is roughly equivalent to:

```csharp
Exception e;
Exception exception1 = e;
TryToChangeException(ref exception1);
Exception exception2 = e;
if (exception2 is InvalidOperationException)
    {
        Console.WriteLine("This is never printed.");
    }
```

**Comment by yaakov-h** [comment]
For the same reason that this doesn't print InvalidOperationException:

```
Exception ex = new ArgumentException();
var ex2 = ex;
TryToChangeException(ref ex2);
Console.WriteLine(ex);
```

The exception filter gets _a_ reference to the current exception object, but is powerless to change it.

**Comment by quixoticaxis** [comment]
Yeah, thanks a lot. My bad, it's definitely obvious, I guess it's one of those times when you the answer is near you (each catch block with an exception variable introduces a local), but you miss it and go too deep. I've spent the last tree hours looking at the CIL and native disassembly.
