### ISSUE TITLE
Dont require parenthesis for delegate on right hand side of ?? operator

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#2730]
Currently this fails to compile:

```csharp
using System;

public class C<T> {
    Func<T, bool> _selector;
    public C(Func<T, bool> selector) {
        _selector = selector ?? _ => true;
    }
    
    // use _selector here
}
```

Instead you have to use parenthesis around the delegate:

```csharp
using System;

public class C<T> {
    Func<T, bool> _selector;
    public C(Func<T, bool> selector) {
        _selector = selector ?? (_ => true);
    }
    
    // use _selector here
}
```

It's not terrible, but it's a little annoying. Also it's not immediately obvious that you should use parenthesis. When I just now encountered this, I changed it to an if statement, before somebody pointed out I could just parenthesis this.

Off the top of my head I can't see why this shouldn't parse correctly.

So 
a) is there some reason this can't be parsed as I would expect it too?
b) if there is no such reason, can this be fixed? :-)

**Comment by ronnygunawan** [comment]
> a) is there some reason this can't be parsed as I would expect it too?

It's already described in spec that ?? has higher precedence than =>
https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#operators

**Comment by YairHalberstadt** [comment]
Thanks @ronnygunawen

I guess this'll just be an annoyance I'll have to live with. I wonder why ??= Works then?

**Comment by YairHalberstadt** [comment]
Ah, because all the `something=` operators have the same precedence as =>
