### ISSUE TITLE
Proposal: Allow optional deconstruction of tuples

### ISSUE THREAD

**Issue by jsk95** [dotnet/csharplang#2732]
Often when writing method that returns tuples, I don't want to deconstruct every element every time.

![image](https://user-images.githubusercontent.com/48934750/63484957-9c4f8700-c4f5-11e9-9bc8-4657b2727a08.png)

If there are less variables than elements during deconstruction, it should just ignore the rest instead of forcing the use of discard `_` for every element you don't care about at the time of usage.

**Comment by Tom01098** [comment]
I feel like this could be a problem if someone forgets to deconstruct all the elements. IMO things should be kept explicit, you should have to tell the compiler that you understand you're discarding elements.

**Comment by jsk95** [comment]
> I feel like this could be a problem if someone forgets to deconstruct all the elements

How can you forget to deconstruct all the elements? You either need the result or you don't

**Comment by jsk95** [comment]
It's like saying we shouldn't have optional parameters because you might forget to pass the paremeters in

**Comment by Tom01098** [comment]
With optional parameters, the method itself has to deal with the problem when the parameters are not given. Here, it isn't obvious from first look what has happened.

**Comment by Richiban** [comment]
I'm not sure this will be useful very often at all; how often will it be that you wish to deconstruct a tuple but ignore exactly the last element(s)?

At least with the explicit discard you can ignore any elements you wish:

```csharp
var (_, y, z) = GetDimensions();
```

**Comment by HaloFour** [comment]
Deconstructors are resolved only by their arity.  If you could omit the targets implicitly that would make it substantially more difficult for the compiler to resolve the proper deconstructor, especially if they are overloaded.

If you find yourself doing this often with a type you don't control you could add an extension deconstructor which has an arity of 2 which itself will discard the elements you don't want:

```cs
public static class TestExtensions {
    public static void Deconstruct(this Test obj, out int x, out int y) =>
        (x, y, _) = obj;
}
```

**Comment by jsk95** [comment]
> I'm not sure this will be useful very often at all; how often will it be that you wish to deconstruct a tuple but ignore exactly the last element(s)?

Pretty often. I put my least important ones at the end. Why would I propose this feature if I didn't run into this frequently?

> If you find yourself doing this often with a type you don't control you could add an extension deconstructor which has an arity of 2 which itself will discard the elements you don't want:

I was talking about deconstructing tuples not user defined types

**Comment by Tom01098** [comment]
I don’t believe there is any difference to the compiler when decompiling a tuple or a user-defined type, so you would probably get both thrown in with this feature.

Still, this is why discards were added to the language. Making it less explicit makes it harder to understand the code from first glance for only a few characters saved.

**Comment by ashmind** [comment]
(Disclaimer: I know @jsk95 in person, so I might be biased)

Personally I think this would make sense on two fronts:

1. I think it's nicely symmetrical with optional args. Same as I can add more args to a method, and have it still be source (but not binary) compatible, I would like to be able to add more return values and not break the source. We had some cases in unit-tests where I wanted to add a new optional element to the tuple returned by the test helper, but it would require updating a lot of calls. Yes we could have used a proper type, but same can be said about method arguments.

2. We can already ignore the whole return value of any method, is ignoring tail tuple values much worse than that?

**Comment by alrz** [comment]
>We can already ignore the whole return value of any method, is ignoring tail tuple values much worse than that?

I think so, because that's a whole new type. Consider this:
```cs
switch (o)
{
    case (var x, _): break;
    case (var x, _, _): break;
}
```
Each case matches a tuple with a different length which denotes a separate type completely.

**Comment by ashmind** [comment]
Hmm, right, you could still support it by inverting the case order, and to me it does make sense, but it also does make it a breaking change compared to the current behavior. And if this one is inconsistent with var definition, it would certainly be confusing.

So maybe it can't be done as it is a breaking change anyways, unless it's just for definitions, which seems inconsistent.

**Comment by jsk95** [comment]
@alrz raises a valid issue for backwards compatibility. I'll close this.
