### ISSUE TITLE
Exploring future of try expression

### ISSUE THREAD

**Issue by gulshan** [dotnet/csharplang#2734]
There was a discussion regarding what try expressions may look like two years ago. Since then, a change has been made in C# language- how match or switch expression looks like. With the chosen syntax of switch expression, most of the then proposals of try expression syntax are outdated now. I am not proposing a single try expression syntax here. Rather I am trying to explore different paths try expression can take in future for C#. I can basically imagine four syntaxes for try expression. To describe them, I want to use the following snippet with current try-catch syntax, which then will be translated to syntax of the respective proposals. Given a method, `User Authenticate(Credential credential)` which may throw `ValidationException` or `AuthenticationException`-
```csharp
try
{
    var user = Authenticate(cred);
    user.DoStuff();
}
catch (ValidationException e)
{
    Logger.LogException("Invalid credential", e);
}
catch (AuthenticationException e)
{
    Logger.LogException("Not authentic credential", e);
}
```

`try` expression
---
`try` expression evaluated to a `Result` object combining success and exception cases. Then `switch` expression can be applied on the result object. Given example will be-
```csharp
var userResult = try Authenticate(cred);
var user = userResult switch {
    User user => user,
    ValidationException e => Logger.LogExceptionAndReturnNull("Invalid credential", e),
    AuthenticationException e => Logger.LogExceptionAndReturnNull("Inauthentic credential", e),
};
user?.DoStuff();
```
Or it can be-
```csharp
var userResult = try Authenticate(cred);
if(userResult is User user)
{
    user.DoStuff();
}
else
{
    userResult switch {
        ValidationException e => Logger.LogException("Invalid credential", e),
        AuthenticationException e => Logger.LogException("Inauthentic credential", e),
    };
}
```
Or it can be-
```csharp
// assuming all arms are evaluated to void
try Authenticate(cred) switch {
    User user => user.DoStuff(),
    ValidationException e => Logger.LogException("Invalid credential", e),
    AuthenticationException e => Logger.LogException("Inauthentic credential", e),
};
```
Notice calling `LogExceptionAndReturnNull` method in some cases, as all arms of switch expression have to return value of same type.

**Pros:**
- Result type, for those who like it.

**Cons:**
- Result type, for those who dislike it. It is a kind of "swallow all" pattern, not goes well with C# style I think.

`try ... switch` expression
---
The `try ... switch` expression will be extending the current switch syntax to catch and handle exception cases, when input is given with a `try`. Given example will be-
```csharp
var user = try Authenticate(cred) switch {
    User user => user,
    ValidationException e => Logger.LogExceptionAndReturnNull("Invalid credential", e),
    AuthenticationException e => Logger.LogExceptionAndReturnNull("Inauthentic credential", e),
};
user?.DoStuff();
```
Or it can be-
```csharp
// assuming all arms are evaluated to void
try Authenticate(cred) switch {
    User user => user.DoStuff(),
    ValidationException e => Logger.LogException("Invalid credential", e),
    AuthenticationException e => Logger.LogException("Inauthentic credential", e),
};
```
`LogExceptionAndReturnNull` has been used here also.

**Pros:**
- Unlike previous one, it is not a "swallow all" pattern- unhandled exceptions are thrown, unless decided that the `default` or `_` arm/case will also swallow all other exception.
- Good when user is trying to do simple and similar(of same return type) operations for all success and exception cases.

**Cons:**
- No syntactic distinction among success and exception cases.
- All arms of switch expression have to return value of same type, which can be irritating.
- May be confusing regarding what `default` or `_` case is doing with exceptions not already handled.

`try ... catch` expression 1
---
Here `catch` part will use same syntax as current `switch`, but will catch and handle **only exception cases**. Unhandled exceptions will be thrown. The result in the success case can be handled in any way necessary. Given example will be-
```csharp
var user = try Authenticate(cred) catch {
    ValidationException e => Logger.LogExceptionAndReturnNull("Invalid credential", e),
    AuthenticationException e => Logger.LogExceptionAndReturnNull("Inauthentic credential", e),
};
user?.DoStuff();
```
Or it can be-
```csharp
try Authenticate(cred) catch {
    ValidationException e => Logger.LogExceptionAndReturnNull("Invalid credential", e),
    AuthenticationException e => Logger.LogExceptionAndReturnNull("Inauthentic credential", e),
}?.DoStuff();
```
`LogExceptionAndReturnNull` has been used here as well.

**Pros:**
- Success and exception cases are clearly separated.

**Cons:**
- All arms of catch part have to return a default value of same type, which can be irritating.

`try ... catch` expression 2
---
This is same as the previous one, except catch parts does not have to (or cannot) supply a default value. For all handled exceptions, the default value is simply `null`. The `??` operator can be used to provide other default values. Like previous one, unhandled exceptions will be thrown. So here arms/cases of the catch **do not contribute to the type of resultant expression**. Given example will be-
```csharp
var user = try Authenticate(cred) catch {
    ValidationException e => Logger.LogException("Invalid credential", e),
    AuthenticationException e => Logger.LogException("Inauthentic credential", e),
};
user?.DoStuff();
```
Or it can be-
```csharp
try Authenticate(cred) catch {
    ValidationException e => Logger.LogException("Invalid credential", e),
    AuthenticationException e => Logger.LogException("Inauthentic credential", e),
}?.DoStuff();
```

**Pros:**
- Success and exception cases are clearly separated.
- Most concise syntax in my opinion.

**Cons:**
- Cannot have separate default values for different exceptions.
- There may be confusion regarding catch cases not contributing to the result.

For last two proposals, I don't like allowing a swallow-all `_` or default case. But someone can be for it. Personally I like the last syntax. Let's discuss which one do you like and why. Did I miss pros or cons of any syntax? And also, can there be any other syntax for try expression?

Some related issues and discussions can be found in #1019 and other issues it referenced.

**Comment by reflectronic** [comment]
Some of this sounds similar to Midori's [dataflow-oriented syntax sugar](http://joeduffyblog.com/2016/02/07/the-error-model/#syntactic-sugar) around try/catch.

**Comment by gulshan** [comment]
BTW, the initial version of the third syntax was proposed by @Pxtl here- https://github.com/dotnet/csharplang/issues/980#issuecomment-512510359

**Comment by DanFTRX** [comment]
None of the proposed syntaxes are functionally equivalent to your current syntax example..  The example has the `user.DoStuff()` in the try catch, the rest don't.

**Comment by uygary** [comment]
I don't think any of the `try expression` or `try ... switch expression` approaches would really work. They cannot possibly handle something like this:
`FooException GetMappedException(Bar barResult)
{
    /* Do stuff... */
}
FooException mappedException;
try
{
    mappedException = GetMappedException(errorResult);
}
catch(FooException ex)
{
    /* Do stuff... */
}`

The `try ... catch expression`s could work though.

**Comment by Thaina** [comment]
I prefer option 1 because it would be almost the same as `switch expression`

Another option. Maybe `switch expression` should support `catch` and `finally` and we could mixing `case` and `catch` and `finally` in the same place

```C#
var user = Authenticate(cred) switch {
    case {} u => u,
    catch ValidationException e => Logger.LogExceptionAndReturnNull("Invalid credential", e),
    catch AuthenticationException e => Logger.LogExceptionAndReturnNull("Inauthentic credential", e),
}
```

**Comment by Thaina** [comment]
@Hosch250 C# at the moment can use `switch` syntax to check the type

```C#
object obj = DoSomeThing();
switch(obj)
{
    case int i: return "number : " + i.ToString();
    case long l: return "number : " + l.ToString();
    case float f: return "number : " + f.ToString();
    case string s: return "string : " + s.ToString();
}
```

**Comment by MV10** [comment]
I think @DanFTRX  raises a great point, and in general this seems to create more problems than it solves. In fact, I'm not actually sure what problem it is meant to solve: I can't think of a use-case for what amounts to conflating assignment and non-local, non-block-level exception handling.

Crucially, what happens to unhandled exceptions? Should it just float around, quietly put on hold in this `Result` object until the code happens to call this new `switch` syntax? Say the `Result` is passed elsewhere. Should an unhandled exception throw again if the `Result` exception is evaluated more than once?

How does this work if you need a `finally`-style cleanup?

In the unlikely event somebody has a real need for this, you can handle it yourself by returning a tuple like  `(UserInfo info, Exception exception)`. Then the second `if-else` example works without any new syntax (just a little additional work inside the target method). But that seems like considerably more effort and complexity-coupling than the current `try-catch` syntax.

**Comment by Pxtl** [comment]
Personally, I strongly want this.  I often find the absence of this feature causes the constant repetition of the variable name in declare varname => try => set varname value.  If a method throws an exception and I want to handle it but still return an object to the caller, this is needed.

Definitely prefer `try ... catch` expression 1.  It's an expression - expressions should return something.   The non-return syntax seems to defeat the purpose.
