### ISSUE TITLE
Why are interface methods allowed to have return types that are static?

### ISSUE THREAD

**Issue by stakx** [dotnet/csharplang#2739]
Could anyone here please help me understand why the following program fragment is valid C# (or, at least, is treated as such by the Roslyn compiler)?

```csharp
static class StaticClass { }

interface IX
{
    StaticClass P { get; }  // Why is this permissible?
}
```

If I attempt to implement above interface, I will run into an error:

```csharp
class X : IX
{
    public StaticClass P => throw new NotImplementableException();
    //                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    // CS0722: 'StaticClass': static types cannot be used as return types
}
```

Which makes sense, since there's no way that getter can ever return an instance of `StaticClass`.

Strangely enough, static types can also be used as parameter types in interfaces:

```csharp
interface IY
{
    StaticClass M(StaticClass p);
}
```

How would I ever be able to call such a method? And if I implemented that method, what could I possibly do with `p` (except perhaps `return` it)?

If you can point me to the relevant parts of the C# spec that explains all of this, I'd be grateful.

**Comment by CyrusNajmabadi** [comment]
Most likely a bug.  Consider moving to dotnet/roslyn.

**Comment by stakx** [comment]
Closing here as this has been tagged as a bug over at the Roslyn repo, which I assume implies that the spec already forbids this. Thanks!
