### ISSUE TITLE
Shorter method to change null value

### ISSUE THREAD

**Issue by frodegil** [dotnet/csharplang#2743]
Hi C# team

Instead of

`nullableVariable = nullableVariable ?? "Default non-null value";`

it would be nice to just use a short-circuit

`nullableVariable ??= "Default non-null value";`

**Comment by svick** [comment]
[That code is already valid in the current C# 8.0 preview](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgEwAEAwqQN4CwAUKY6YQCykCyAFIQIwAMpAHYBXADaiIwUXABqEBJknSAlNXpMNQsRKmz5i3aQD8RgLykARABE42CGJhCA9oIC0I8aTQRRwuBYBudSYAX3oQoA=) and so it should work in the final version of C# 8.0, which is planned to be released next month.

For more details, see https://github.com/dotnet/csharplang/issues/34.

**Comment by YairHalberstadt** [comment]
Closing as implemented
