### ISSUE TITLE
Allow lambda to reference a variable when the lambda is created during that variable's first assignment.

### ISSUE THREAD

**Issue by TheUnlocked** [dotnet/csharplang#2744]
Currently this code is not legal:
```csharp
Func<int, int> factorial = n => n <= 1 ? 1 : n * factorial(n-1);
```
It produces the error `Use of unassigned local variable 'x'` because at the time that the lambda is being evaluated, `factorial` has not yet been assigned. However, that can be sort of annoying, and this is a completely legitimate thing to want to do (Because factorial could just be broken into a local function, I'll provide an example of an even more "real" case later).

There is a workaround to this, but it involves breaking this statement up into two lines:
```csharp
Func<int, int> factorial = null;  // Now factorial is assigned
factorial = n => n <= 1 ? 1 : n * factorial(n-1);
```
This seems unnecessary and confusing, especially for developers used to more functional languages where such an odd restriction does not exist (I personally had to search stackoverflow to figure this one out). My proposal is to lift this restriction, which could be done by the compiler automatically breaking up the statement into the two lines, for example.

### Real use case:

This is a simplified version of what I was trying to do when I discovered that I couldn't:

```csharp
class Foo : IFoo {
    public Func<IFoo> fooAction;
    public string fooString;
    public Foo (Func<IFoo> fooAction, string fooString) {
        this.fooAction = fooAction;
        this.fooString = fooString;
    }
}

Foo obj = new Foo(() => obj, "Hello, World!"); // oops! Use of unassigned local variable 'obj'
```

### Possible extension of this proposal:
This proposal would work for self-recursive functions, but that's not always going to be what you want. To give a minimal example:
```csharp
Action a = () => b(); // Cannot use local variable 'b' before it is declared
Action b = () => a(); // ok
```
An extension of this proposal could be to allow any undeclared or unassigned function to be used in a lambda expression as long as the compiler can _prove_ that the lambda expression won't be called before the variable is declared and assigned.

**Comment by scalablecory** [comment]
Can accomplish this by instead using a local function.
```c#
int factorial(int n) => n <= 1 ? 1 : n * factorial(n - 1);
```

**Comment by TheUnlocked** [comment]
@scalablecory 
I mention that in my question, which is why I included the "real use case" section.

**Comment by svick** [comment]
@TheUnlocked But there, you're not referencing the variable the lambda is assigned to, you're referencing an object that receives the lambda in its constructor. If you attempted to invoke the lambda in that constructor, what would it return? C# tries quite hard to prevent you from accessing unitialized variables and half-initialized objects, and that's a good thing.

Regarding:

> especially for developers used to more functional languages where such an odd restriction does not exist

Depends on the language. A language like Haskell has the advantage of being purely functional. A language like F# doesn't, so [such code gives you a scary warning](https://sharplab.io/#v2:DYLgZgzgPgLgngBwKYAIDCAKAHiFBXAOwEsYUBaAPnQEoUBeFAY2AEMIIUkCATAWACgBwJKQBOSRiiz10GFGEIoMtSlJTUgA):

> warning FS0040: This and other recursive references to the object(s) being defined will be checked for initialization-soundness at runtime through the use of a delayed reference. This is because you are defining one or more recursive objects, rather than recursive functions.

**Comment by TheUnlocked** [comment]
> But there, you're not referencing the variable the lambda is assigned to, you're referencing an object that receives the lambda in its constructor.

Right, maybe I should edit the issue title to be a bit more clear.

**Comment by pie-flavor** [comment]
But the error is correct. When you are calling the constructor, `obj` won't have been initialized correctly until the constructor completes. So if the constructor calls the delegate, who knows what happens. If you explicitly initialize to null first, then the constructor calling the delegate will just get null out of it.

**Comment by TheUnlocked** [comment]
Of course the error is correct. My proposal is to remove that error for this particular pattern.

**Comment by scalablecory** [comment]
The benefit here isn't clear. Can you give a killer example of something this enables or significantly simplifies?

**Comment by TheUnlocked** [comment]
I gave my examples. It's initially unclear why the error occurs or how to fix it to someone who is used to writing code like that, and could interrupt their workflow (like it did mine) to figure out a solution.

Alternatively, there could be a code fix added to show a user how to resolve this. However, simply doing that via analyzers wouldn't work because if you knew to include the analyzer, you wouldn't need the analyzer.

**Comment by scalablecory** [comment]
Okay. I don't think this proposal to enable this pattern provides enough benefit. I do like to support ease of learning a language though, and so I can see some benefit in an improved error message when a variable is declared and referenced in a single statement. That suggestion would need to be made in over in the [Rosyln repo](https://github.com/dotnet/roslyn).

**Comment by gafter** [comment]
> Allow lambda to reference a variable when the lambda is created during that variable's first assignment.

So would this be legal?

``` c#
int f = M(() => (f + 1));
```

**Comment by TheUnlocked** [comment]
That's a fair point. As I've written the proposal it probably would be legal (initialize `f` to `default(int)` i.e. `0`) but it definitely feels wrong.

**Comment by TheUnlocked** [comment]
This may be of relevance. It appears that this restriction is already lifted in C# Interactive, and it works as I describe in this proposal.
![image](https://user-images.githubusercontent.com/10186337/64087872-db0ee980-cd0c-11e9-955c-02b152046473.png)

**Comment by Joe4evr** [comment]
That's only because the `f`s inside of the lambdas are shadowing the outer variable now. See also dotnet/roslyn#38377

**Comment by TheUnlocked** [comment]
Since it seems like this would make more sense to handle in terms of tooling, I'm closing this and I've made a new issue in rosyln (https://github.com/dotnet/roslyn/issues/38446).
