### ISSUE TITLE
New keyword { get; set; init; }

### ISSUE THREAD

**Issue by srburton** [dotnet/csharplang#2747]
This proposal comes to make the code cleaner since `get` and` set` came to help us programmers. I believe `init` will make the code less polluted when we need to initialize many properties, avoiding the famous NullPointerException.
I think the good use of the technique will make the code look better.

Today:

```cSharp

public class Abc
{ 
  public List<string> Property {get; set;}   
 
  public Abc(){
    Property = new List<string();
  }
}

```

Solution:

```cSharp

public class Abc
{ 
  public List<string> Property {get; set; init; }   
}

```

**Comment by Joe4evr** [comment]
Why not simply use `public List<string> Property {get; set;} = new List<string>();`?

**Comment by YairHalberstadt** [comment]
With target typed new, this becomes:

`public List<string> Property {get; set;} = new()` which is one character longer.

**Comment by DavidArno** [comment]
> Superior in terms of beauty and functionality eg:

Beauty clearly is in the eye of the beholder here. Your code example,
```cs
public class Abc
{ 
  public List<string> Property {
        get;
        set;  
        init {
            value.add("Apple");
        } 
      }
}
```
is certainly not beautiful in my view. You aren't following the common C# brace style convention, and the code is long and rambling, so is for from beautiful. And as others have told you, target typed-new is proposed for a future language version, and so you code example possibly could then be expressed as:
```cs
public class Abc
{ 
  public List<string> Property { get; set; } = new { "Apple" };  
}
```
which is far superior in my view. Others may disagree though as the subject of code beauty is so subjective.

I therefore see no benefit to this proposal.

**Comment by svick** [comment]
@DavidArno Tiny correction: based on [the proposal](https://github.com/dotnet/csharplang/blob/master/proposals/target-typed-new.md#detailed-design), I believe the syntax would have to be:

```c#
public List<string> Property { get; set; } = new() { "Apple" };  
```

Though that doesn't change anything about what you said.

**Comment by pie-flavor** [comment]
You say beauty, I say clarity. With `new()`, I know exactly what is meant; it is supposed to call the default constructor. If I wanted to call a single-arg constructor, I'd say `new("whatever")`. Your proposed feature only works with a zero-arg constructor.
