### ISSUE TITLE
[Proposal] string.Format supports named placeholders

### ISSUE THREAD

**Issue by ahdung** [dotnet/csharplang#2749]
I hope can do this:
```c#
var s = "my name is {Name}, was born on {Birthday:yyyy-MM-dd}, so i am {Age:D2} years old, repeat, my name is {Name}";

Use(string.Format(s, new {Age=21, Name="asdf", Birthday=DateTime.Parse("xx")}));

//still support ordinal
Use(string.Format(s, "asdf", DateTime.Parse("xx"), 21));
```

**Comment by YairHalberstadt** [comment]
Do you won't this to be a compile time feature, or a runtime feature? If it's a runtime feature, than this probably should only require changes in string.format.

**Comment by YairHalberstadt** [comment]
As described here, I think this request should be in coreFX

**Comment by ahdung** [comment]
@YairHalberstadt Agree, thank you.

**Comment by canton7** [comment]
There are various libraries which provide this already (SmartFormat.NET comes to mind, but I'm sure there are others).

**Comment by canton7** [comment]
@uygary One very common use-case is if you want to put your strings in some sort of resources file, perhaps for internationalization.

**Comment by canton7** [comment]
> Again, whatever that would be passed into string.Format() could as easily be passed into string interpolation.

This is simply not true. Imagine something very simple like this:

```csharp
public static class Strings
{
    public static string NameString { get; } = "His name is {Name} and his surname is {Surname}";
}

...

Print(String.Format(Strings.NameString, foo));
```

That won't work, obviously. This is a very common pattern when you have internationalized strings, except that the `Strings` class (or its equivalent) will get the strings from a resources file.

**Comment by ahdung** [comment]
@uygary Templatable

**Comment by YairHalberstadt** [comment]
Closing as this is an issue for dotnet/runtime
