### ISSUE TITLE
[Proposal] A using statemnt for settings files to generate strongly typed settings

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/csharplang#2751]
I suggest to add an easy way to import settings files (json and xml) as a strongly types objects, like this:

```C#
using MySettings = "mysettings.json";
```

Or:
```VB.NET
Imports MySettings = "mysettings.xml";
```

Note that quoting the file name prevents any ambiguity with namespaces.

Implementation:
1. Roslyn can parse the setting file, generate the necessary classes to represent its structure, and add static/shared fields in these classes to hold the setting values.

2. To prevent naming conflictions between classes generated from multiple settings files, classes can be added to a name space based on the file path and name, such as: 
`namespace mysettings.json`
`namespace config.mysettings.xml`

3. The using statement can appear at many files, but of course the strongly typed settings will be generated once for the same file, and used from anywhere.

4. At each build, the last modified date of the setting file should be checked to update the generated classes if necessary.

This way, we just add a single line of code at top of the file to have access to the settings with intelligence support.

**Comment by alrz** [comment]
>strongly typed settings

aspnetcore already solved this problem with `IOptions<T>`, although you have to declare `T` yourself.

Moreover, the lack of generators feature shouldn't stop you from automating the code generation, you could just write a tool to generate it for you, and if necessary, have it run somewhere along the build pipeline.

**Comment by VBAndCs** [comment]
Surprise :
ASP.NET Core bodies told me that VS.NET already translates JSON to classes
https://user-images.githubusercontent.com/4734691/63812279-bb2b9000-c8de-11e9-86a9-897ef2e24d30.png
This can be built on to make the feature I suggested. I will sebd this to user voice.

**Comment by gulshan** [comment]
I think my proposal #1614 tried to address similar concerns in a different manner.
