### ISSUE TITLE
[Propousal] Deterministic auto-implemented property backing field name

### ISSUE THREAD

**Issue by redradist** [dotnet/csharplang#2752]
With **_auto-implemented property backing field name_** is anonymous (unknown), but it would be nice to have deterministic name for this field
It would be nice for such frameworks like **_Entity Framework_** (and other future frameworks), in such case **_Entity Framework_** would know how to access backing field without providing setter for it

Consider the following example:

```csharp
public interface IPerson
{
    string Name { get; }
}

public class Person : IPerson
{
    public string Name { get; }
}
```

In such case **_Entity Framework_** cannot access backing field because it does not know it name and I need to make workaround for this like:

```csharp
public interface IPerson
{
    string Name { get; }
}

public class Person : IPerson
{
    public string Name { get; private set; }
}
```

It is tedious to write by hand every time ...

My suggestion to add deterministic backing field name for **_auto-implemented properties_** like this:

```csharp
public interface IPerson
{
    string Name { get; }
}

public class Person : IPerson
{
    private _name; // auto generated deterministic backing field
    public string Name
    {
        get
        {
            return _name; // also generated code
        }
    }
}
```

**Comment by svick** [comment]
What would happen if `Person` already had a member called `_name`?

**Comment by DaZombieKiller** [comment]
Isn't the name of the backing field already deterministic? It merely isn't _specified_, to my knowledge. The backing field gets the `[CompilerGenerated]` attribute, and follows the naming scheme of `<PropertyName>k__BackingField`.

> in such case Entity Framework would know how to access backing field without providing setter for it
I think that could alternatively be solved with something like this:
```cs
[field: BackingFieldFor(nameof(MyProperty))]
public int MyProperty { get; }
```

**Comment by yaakov-h** [comment]
@DaZombieKiller I cannot tell if that is ingenious, or a total hack.

**Comment by khellang** [comment]
Indeed, as @DaZombieKiller mentioned, the name of auto-generated backing fields is deterministic, is't simply not part of any specification. See [the Roslyn code that generates the names](https://github.com/dotnet/roslyn/blob/de6c369ad12e12657c660fa563b91e36130b9160/src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs#L28-L32).

**Comment by redradist** [comment]
> 
> 
> What would happen if `Person` already had a member called `_name`?

I do not see any issue that name of property will clash with member called _name, it seems like bad design if user has member with similiar name as auto-implemented property, why it cannot be compilation error ?
Backward compatability ? Have somebody before implemeting auto-implemented property feature asked community what the choise should be ? No ...
From my point of view it will simplified realization of a lot of framework and user would not be enforced to change code for using particukar framework ...

**Comment by redradist** [comment]
> 
> 
> > why it cannot be compilation error ?
> 
> Because it would break existing code, or worse, subtly change the meaning of existing code. That pretty much makes it a non-starter right there. And the only benefit of this would be that it works more seamlessly with a single ORM, EFCore specifically. What if another ORM doesn't follow the "_name" convention for fields?

No, you do not see an issue in general !!
It will work not only for ORM, EFCore, but for all other framework which would like to rely on deterministic backing field ... and it could be a lot of frameworks !!

Framework writes will win and user will win (they should not make any custom backing fields) !!

**Comment by redradist** [comment]
> 
> 
> > Have somebody before implemeting auto-implemented property feature asked community what the choise should be ? No ...
> 
> Citation needed.
> 
> How do you _know_ that the C# language team never asked that question?

I have not found any old community question which is available on forums and etc

**Comment by HaloFour** [comment]
@redradist 

> No, you do not see an issue in general !!

The simple answer is not to rely on the backing field, not of auto-properties and not of normal properties.  Faking "immutability" through reflection directly against a readonly field is always inherently brittle.  All of these frameworks already work perfectly well out of the box when you add a setter, which is exactly what you should do.  Breaking the language doesn't seem remotely worth making is slightly less verbose to define these properties while encouraging bad practices such as relying on the private implementation details of these types.

**Comment by redradist** [comment]
> 
> 
> @redradist
> 
> > No, you do not see an issue in general !!
> 
> The simple answer is not to rely on the backing field, not of auto-properties and not of normal properties. Faking "immutability" through reflection directly against a readonly field is always inherently brittle. All of these frameworks already work perfectly well out of the box when you add a setter, which is exactly what you should do. Breaking the language doesn't seem remotely worth making is slightly less verbose to define these properties while encouraging bad practices such as relying on the private implementation details of these types.

Better to enfore 3 million developer to enfore to write this tedious code than to help and generate it instead with predictable name for backing field on which frameworks can rely ?!

**Comment by yaakov-h** [comment]
@redradist why should frameworks even attempt to set a read-only property? It's read-only for a reason. Read-only does not mean writable, it means read-only. If you define a setter, then it's a read-write property, and these frameworks work as you would expect.

**Comment by HaloFour** [comment]
@redradist 

> Better to enfore 3 million developer to enfore to write this tedious code than to help and generate it instead with predictable name for backing field on which frameworks can rely ?!

I disagree with this idea that four characters are tedious.  You want the property to be writable, thus a setter is appropriate.  Relying on frameworks to overwrite `initonly` fields via reflection post-construction is inherently brittle and poor design.  This is why EFCore supports binding to constructors.  Yes, it's more code, but it's correct code.  C# is not in a race to be as terse as possible.

**Comment by spydacarnage** [comment]
I've recently moved all my object binding to use constructors and I found
that Visual Studio will even write the constructor for you, so it's
actually less to write (•‿•)

**Comment by redradist** [comment]
Guys, I close the issue
Looks like you are right, because backing field is readonly after all, I was wrong

**Comment by redradist** [comment]
Seems like this feature was reborn with C# 10 `field` proposal ...
Yeah, but this one got more dislikes than C# 10 `field` proposal ))) Just comment )

**Comment by 333fred** [comment]
> Seems like this feature was reborn with C# 10 `field` proposal ...
> Yeah, but this one got more dislikes than C# 10 `field` proposal ))) Just comment )

Not really. The name in metadata is still not specified.
