### ISSUE TITLE
[unconfirmed] BREAKING CHANGE between C#7 and C#8

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/csharplang#2758]
One could write the following code in C#7:
```csharp
class A
{
    public static implicit operator (int a, int b)(A a) => (4, 2);
}

A a = ....;
(int a, int b) = a;
```
Note the lack of any `Deconstruct`-method!

-----

However, when using the newest version of Visual Studio 2019 (v.16.3.0 prev2) with .NETCore 3.0.0-prev8 and C#8, one has to declare a suitable `Deconstruct`-method:
```csharp
A a = ....;
(int a, int b) = a; // CS1061 : 'A' does not contain a definition for 'Deconstruct' and no accessible extension method 'A' accepting a first argument of type 'A' could be found (are you missing a using directive or an assembly reference?)
```

This is a **huge** breaking change between C#7 and C#8!
(I know for a fact multiple devs at my university which make heavy uses of implicit operators instead of `Deconstruct`s and it would break all their code bases of the past year).

-----

**EDIT:** Currently, I am unable to verify that - I will come back in the upcoming days to back up my claims.

**Comment by Unknown6656** [comment]
I am pretty sure, that it was possible to wirte that code in VS2015, as I have seen a couple of guys doing it. However, I do not have VS2015 installed on any available machine, so I cannot currently verify that.
Does sharplab.io have an "older" compiler branch to test this?

**Comment by YairHalberstadt** [comment]
@Unknown6656

What happens if you test it with C# 6 on VS2017?

**Comment by Unknown6656** [comment]
I think tuples were not introduced to C#6, they came to C#7 IIRC.

**Comment by YairHalberstadt** [comment]
True. My bad.

**Comment by Unknown6656** [comment]
@HaloFour : Thank you very much for testing this. My guess is that the devs I was speaking about may have been using some kind of preview-version of the compiler (or something similar).

I will close this issue for now until I can reproduce my claims.

**Comment by svick** [comment]
I have tried to compile the following code using Microsoft.CodeAnalysis.CSharp:

```c#
class A
{
    public static implicit operator (int a, int b)(A a) => (4, 2);

    void M(A a)
    {
        (int x, int y) = a;
    }
}
```

Version 2.0.0-beta3 reports:

> (7,24): error CS1001: Identifier expected

Version 2.0.0-beta4 reports the familiar:

> (7,26): error CS1061: 'A' does not contain a definition for 'Deconstruct' and no extension method 'Deconstruct' accepting a first argument of type 'A' could be found (are you missing a using directive or an assembly reference?)
> (7,26): error CS8206: No Deconstruct instance or extension method was found for type 'A', with 2 out parameters.

So unless this changed back and forth, I don't think there was even an official beta where code like that compiled.
