### ISSUE TITLE
[discussion] Initializing class member

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/csharplang#2759]
```csharp
public class A {
    public int a;
    public int b;
}
// now support
var obj1 = new { a, b };
var obj2 = new A { a = 10, b = 20 };
// discuss support for new syntax grammar
var obj3 = new A { a, b };
```

**Comment by YairHalberstadt** [comment]
This already has a meaning. Is is a collection initialiser.

**Comment by Tom01098** [comment]
What does
```C#
var obj3 = new A { a, b };
```
mean over
```C#
var obj3 = new A();
```
?

**Comment by fawdlstty** [comment]
create new object and initialize member, I has lose some code:
```csharp
int a = 10, b = 20;
var obj3 = new A { a, b }; // equal to: var obj2 = new A { a = a, b = b };
```

**Comment by Richiban** [comment]
@fawdlstty not going to work like Javascript due to the casing of C# naming conventions. C# devs name their local variables `a` but their class properties `A`.

Also, as others have said, `new A { a, b }` already has a meaning. Here's an example:

Given

```csharp
public class A : IEnumerable<object>
{
	// IEnumerable methods here...

	public void Add(object newObject) {}
}
```

We can call

```csharp
int a = 10, b = 20;
var obj3 = new A { a, b }; 
```

**Comment by fawdlstty** [comment]
While this topic doesn't make sense anymore, I'd like to know why they conflict, only for classes that don't have an collection initialiser.

**Comment by Tom01098** [comment]
Because it could potentially introduce ambiguity between classes with a collection initialiser - is
```C#
var obj3 = new A { a, b };
```
creating a collection of type A containing a and b, or an object of type A with fields inside assigned to a and b? Additionally, you could just use a constructor and use a different bracket:
```C#
var obj3 = new A(a, b);
```
