### ISSUE TITLE
Make "async" optional

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#2760]
When working with enumerators, I can return values one of two ways, either with ````yield return```` or ````return```` and the compiler is smart enough to not allow me to mix them so I can't do things like this:

````
//Invalid Code:
private IEnumerable<string> Something() {
            yield return "";

            return new string[] { };
        }
````

With async code, I feel like it is similar, however, it, annoyingly, requires that I put "async" on the method and change it if I go from having a "return" to an "await".

I believe that ````async```` should not be required on methods (just like nothing special is required on IEnumerable methods) and I should be able to return either a value or a task in a way that is similar to enumerables without having to change my method.

**Comment by HaloFour** [comment]
The reason that `async` is required is to force `await` to be a keyword.  It could not be added as a contextual keyword without being ambiguous.  This was avoided in iterators as the team used the combination of keywords, `yield return` and `yield break`, which made it otherwise unambiguous.

**Comment by DanFTRX** [comment]
@HaloFour Do you have an example of some code where it would be ambigious?  I'm sure it exists I just  couldn't think of one and was curious.

**Comment by HaloFour** [comment]
Here's a blog posting on the subject:

https://blogs.msdn.microsoft.com/ericlippert/2010/11/11/asynchrony-in-c-5-part-six-whither-async/

**Comment by pie-flavor** [comment]
Not to mention:
```csharp
Task Foo()
{
    DoThing();
}
```
If `async` is optional, there's no way of knowing whether you meant actually execute synchronously and just forgot to return `Task.CompletedTask`.

**Comment by TonyValenti** [comment]
@pie-flavor -
I still think await should be necessary. Just not async as it requires refactoring a method in multiple places.

**Comment by CyrusNajmabadi** [comment]
> I still think `await` should be necessary. Just not `async`

This can't be done because it would make the grammar of the language highly ambiguous.  For example, what would `await + foo()` mean?  What would `await (bar())` mean?

**Comment by YairHalberstadt** [comment]
Closing because, as discussed this isn't really possible.
