### ISSUE TITLE
Should we allow switch on generic?

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#2761]
```C#
T Parse<T>(string s)
{
    switch(T)
    {
        case string:
            return s; // could assume type in the specific block
        case int:
            return int.Parse(s);
        case long:
            return long.Parse(s);
        case float:
            return float.Parse(s);
        case double:
            return double.Parse(s);
        case MyCustomClass:
            return new MyCustomClass(s);
        case MyCustomStruct:
            return new MyCustomStruct(s);
        case class: // is it possible?
            return null;
        default:
            return default(T);
    }
}
```

**Comment by YairHalberstadt** [comment]
I commonly have this case, and I need to do the horrific

```csharp
switch (typeof(T))
{
    case var t when t == typeof(string):...
    case var t when t == typeof(int):...
}
```

However my preferred solution would be switching on type which is already a proposal. https://github.com/dotnet/csharplang/issues/356. I feel this makes more sense conceptually than switching on a type parameter

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/356 ?

**Comment by Thaina** [comment]
@YairHalberstadt @ufcpp I already did `case var t where t == typeof(SomeType)` already but there was  2 points. It can't infer inheritance. And it can't infer return type (but this might not be possible)

```C#
T Parse<T>(object s)
{
    switch(typeof(T))
    {
        case typeof(string):
            return s; // Error, must use `return (T)s;` or `return (T)((object)s)`
//...
        default:
            return default(T);
    }
}
```

I wish that 

```C#
T Parse<T>(object s)
{
    switch(T)
    {
        case string:
            return s; // No error
//...
        default:
            return default(T);
    }
}
```

And it also more verbose that we need to `typeof` everywhere. Even the type inference is not possible I think this syntax is still better

**Comment by YairHalberstadt** [comment]
@Thaina

Currently the language has no concept of inferring the type of a generic type parameter.

If it did, maybe the following ought to work as well:

```csharp
T M(T t)
{
   if (t is string s) //T is a supertype of string
       return "hello + s";
}
```

For example. 

However I think that is a much bigger feature than just switching on T, and I'm not sure the benefits are significant enough to make it worth it.

**Comment by reflectronic** [comment]
1. I don't think there's a way to express this (especially matching on `class` etc.) in IL without calling into reflection, although we already have prior precedent to doing this with `new T()`.
2. If we do this, it should be extended generally to patterns (so you can do, for example, `if (T is string)`.

**Comment by YairHalberstadt** [comment]
@reflectronic

Whilst technically it does call into reflection,  it should only need the Type APIs , which are very fast, so I don't think that should be a problem.

**Comment by DavidArno** [comment]
What would be useful for me on occasions is the ability to use switch with generics in the following way:
```cs
class C<T1, T2>
{
    private T1 _t1;
    private T2 _t2;

    public T GetValueOf<T>()
        => T switch {
            T1 => _t1,
            T2 => _t2,
            _ => throw new InvalidOperationException()
        };
}
```
such that eg in the first branch, the compiler knows that `T` is the same type as `T1`, so no cast is required of `_t1` to `T`.

However, I suspect this is real edge-case stuff and that the ROI of implementing it would be low.

**Comment by ufcpp** [comment]
In such a edge case, `Unsafe.As` is enough, IMO.

```cs
class C<T1, T2>
{
    private T1 _t1;
    private T2 _t2;

    public T GetValueOf<T>()
    {
        if (typeof(T) == typeof(T1)) return Unsafe.As<T1, T>(ref _t1);
        if (typeof(T) == typeof(T2)) return Unsafe.As<T2, T>(ref _t2);
        throw new InvalidOperationException();
    }
}
```

**Comment by DavidArno** [comment]
@ufcpp,

**Comment by ufcpp** [comment]
The `Unsafe.As` can avoid boxing for value types while the `ItemAs` can not.
Anyway, there exists work around.

**Comment by Thaina** [comment]
@ufcpp There are always exist a workaround for `new` syntax such as "Always `alloc` then don't forget to call `init` so we don't need `new` keyword"

**Comment by setbbtjl8wwq** [comment]
@Thaina
Just an idea (but with boxing for legacy CLRs)
```c#
using System;

public static class Program
{
	public static void Main()
	{
		var s = "4";
        
		Console.WriteLine(s.Parse<string>());
		Console.WriteLine(s.Parse<int>());
		Console.WriteLine(s.Parse<double>());
		Console.WriteLine(s.Parse<MyCustomClass>());
        
		Console.WriteLine(s.Parse<string>().GetType());
		Console.WriteLine(s.Parse<int>().GetType());
		Console.WriteLine(s.Parse<double>().GetType());
		Console.WriteLine(s.Parse<MyCustomClass>().GetType());
	}
    
	static T Parse<T>(this string s) => TypeOf<T>.Match
	(
		() => s,
		() => int.Parse(s),
		() => double.Parse(s),
		() => new MyCustomClass(s)
	);
    
	class MyCustomClass
	{
		private string _s;
		public MyCustomClass(string s) => _s = s;
		public override string ToString() => $"[{_s}]";
	}
}

public static class TypeOf<T>
{
	private static readonly Type RawType = typeof(T);
	
	/* possible, may be used Unsafe.As instead casting (T)(object)a.Invoke() */
	public static T Match() => default;
	public static T Match<A>(Func<A> a) => RawType == typeof(A) ? (T)(object)a.Invoke() : Match();
	public static T Match<A, B>(Func<A> a, Func<B> b) => RawType == typeof(A) ? (T)(object)a.Invoke() : Match(b);
	public static T Match<A, B, C>(Func<A> a, Func<B> b, Func<C> c) => RawType == typeof(A) ? (T)(object)a.Invoke() : Match(b, c);
	public static T Match<A, B, C, D>(Func<A> a, Func<B> b, Func<C> c, Func<D> d) => RawType == typeof(A) ? (T)(object)a.Invoke() : Match(b, c, d);
	/* etc */
}


```
[online compiler](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHjAZjwG88BIDdCs3c8gNwEMwACAZ1YF5WAiAFl4BuPKzHixFSpgCcACnYA6AAot2AUwA8qTAAYAfHICURkXWnylqsBs0BLKMEMmz9HZZVqtcAPYQARgA26s6mUu4KnjZaALIAngDCEOzAPgC2CYFM7OyhZhIS4bKR1rY6BsaKAOLqwAAqcQAO6sZh5hFWXvaOztW1Dc2trhYlXb4Bwb019U0tLkUepbGJyakZWTlT/bNDFAC+ouIUOgBsrHWsS5p1hsAAFnac5RxG3PrnswDyAGbX+ooxJjAADGdwocikxjeHBgkNeXHeDmAUQ0CiMsPMUIRrHGQXUKJa7HRcOhUHUAHdWPEkil0plsuw0RQ2oU6BgqStaesGTQpI0wHZmMB1KxngB9djDVCEDk0tb0nJyZ5E6ES7gcKUynwMdRgAVwEXPOo+ADKwAFUAA5lj3gASXgAbRIEr2AF1hPs8Ad8LhpaLMGd2QN1D8/qQKPzBUDDQHWGB1ExfFBAnEPs1WAAlJjk4Pq4CzHzfOR1NrkCgAegAVKxGj4cnY8TBWGkmKn/CLkuo4KwAKpQdhMb74gCCnAcKQT3eB2WADktrGLRjkPn8ACt1MDgEYmIoAJJQBg+ADWc1YlfLxxlp3OVKBoJtOPU3yYEECwFcfuvF0BILummHhioAArP+7xMPC7xZjmszcDw+bNIWcjDq8AD8C4lsua4bluO77oeJ5QiAt6/sYH5XrG353n+w5NgAQoBIEAawTBNsBmj0aw/gQZm2a5lwcEFkWyGsGhi6Yeum7bnuB7HqeRE/veXFkf6ZyUb+/50U2CQMaBzGsSBHH+PpmjaawwLcVBfECQhQmoehS4rhJOHSfhcnEYpTbmcpX7udRmmsAkTYACI6UxLGigZ7xGRFJnvMCxkhTiFm8TB/GsPB6iIcJokYY52FSXhsmEb5cjRfFSWuFWrC1MCZ4Xrg3p4EAA)
