### ISSUE TITLE
[Proposal] Class Locals (New Access Modifier)

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/csharplang#2769]
# Class Locals

## Summary
Class locals are class members declared with `local` access modifier. Class locals cannot be accessed using member access operator `.` except when being accessed from `this`, making it impossible for the members to be accessed from any other objects including objects of the same type.

## Motivation
Encapsulation in today's C# cannot be done perfectly. Objects of the same type can still access each other's private members, beating the purpose of encapsulating it into a property. Sample case:
```csharp
// Without proper encapsulation
class Hero
{
    private int _hitPoints;
    public int HitPoints
    {
        get => _hitPoints;
    }
    // or public int HitPoints { get; private set; }

    private readonly int _attackPower;
    private readonly int _damageReduction;

    public void DealDamageTo(Hero otherHero)
    {
        // Accessing other object's _hitPoints and _damageReduction field directly.
        // This is not a good OOP practice.
        otherHero._hitPoints -= (this._attackPower - otherHero._damageReduction);
    }
}

// With proper encapsulation
class Hero
{
    private int _hitPoints;
    public int HitPoints
    {
        get => _hitPoints;
    }
    // or public int HitPoints { get; private set; }

    private readonly int _attackPower;
    private readonly int _damageReduction;

    public void ReceiveDamage(int attackPower)
    {
        this._hitPoints -= (attackPower - this._damageReduction);
    }

    public void DealDamageTo(Hero otherHero)
    {
        // Proper encapsulation, but it's still tricky to write.
        // One typo and we can mistype it as otherHero._attackPower
        otherHero.ReceiveDamage(this._attackPower);
    }
}

// Written using class locals
class Hero
{
    local int _hitPoints;
    public int HitPoints
    {
        get => _hitPoints;
    }
    // or public int HitPoints { get; local set; }

    local readonly int _attackPower;
    local readonly int _damageReduction;

    public void ReceiveDamage(int attackPower)
    {
        this._hitPoints -= (attackPower - this._damageReduction);
    }

    public void DealDamageTo(Hero otherHero)
    {
        otherHero.ReceiveDamage(this._attackPower);

        // Following lines will produce compilation errors:

        // Example 1: accessing other object's local fields using member access operator
        // Error: otherHero._hitPoints is inaccessible due to its protection level.
        // Error: otherHero._damageReduction is inaccessible due to its protection level.
        otherHero._hitPoints -= (this._attackPower - otherHero._damageReduction);

        // Example 2: typo mistyping 'this' as 'otherHero'
        // Error: otherHero._attackPower is inaccessible due to its protection level.
        otherHero.ReceiveDamage(otherHero._attackPower);
    }
}
```

## Detailed Design
- Class locals are fields, properties, indexers, methods or property accessors which are declared with `local` access modifier.
- `local` access modifier is a new access modifier in addition to current `public`, `internal`, `protected`, `protected internal`, `private protected`, and `private`
- `local` members cannot be accessed from other classes including derived classes, similar to `private`
- `local` members cannot be accessed by using member access operator `.` on a local variable, property, expression, or parameter.
- Member access operator can be used to access local member of `this`
- Member access operator cannot be used to access local member of `base`
- `local` members cannot be static.
- `local` members cannot be const.
- `local` cannot be applied to constructors.
- `local` cannot be used in structs.
- You can use any existing attributes as if you're decorating a private member.

### How the protection works:
```csharp
class Foo
{
    local int _value;

    public void Bar(Foo other) {
        _value = 1; // OK
        this._value = 1; // OK
        other._value = 1; // Error: other._value is inaccessible due to its protection level
        Foo me = this;
        me._value = 1; // Error: me._value is inaccessible due to its protection level (even if me is this)
    }
}
```

#### Fields
```csharp
class Person
{
    // _money cannot be accessed using member access operator
    local decimal _money;

    public void Pay(Person other, decimal amount)
    {
        _money -= amount;
        other._money += amount; // Error: other._money is inaccessible due to its protection level.
    }
}
```

#### Properties
```csharp
class Person
{
    // Money cannot be accessed using member access operator
    local decimal Money { get; set; }

    // Savings is read-only when accessed using member access operator
    private decimal Savings { get; local set; }

    // Cash is write-only when accessed using member access operator
    private decimal Cash { local get; set; }
}
```

#### Methods
```csharp
class Person
{
    local decimal _money;

    private void ReceiveMoney(decimal amount)
    {
        _money += amount;
    }

    // Other person cannot make this person pay
    local void Pay(Person other, decimal amount)
    {
        _money -= amount;
        other.ReceiveMoney(amount);
    }
}
```

## Alternative names to `local`
In case you don't like the name of the keyword, here are some alternatives:
- `hidden`
```csharp
hidden decimal _money;
// pro: intuitive and easy to understand
// con: the word 'hidden' is commonly used as local variable name
```

- `sealed`
```csharp
sealed decimal _money;
// pro: 'sealed' is already a reserved keyword
// con: the meaning of 'sealed' keyword will be inconsistent with current meaning
```

**Comment by YairHalberstadt** [comment]
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/2718

**Comment by ronnygunawan** [comment]
> This looks like a duplicate of #2718

Yes it's a fix of #2718

**Comment by yaakov-h** [comment]
I feel like it doesn't address any of the issues raised in #2718, so it's basically a duplicate with different syntax being bikeshedded.

Why does this need full-blown language support? It still seems like something you could build fairly trivially with an Attribute and an Analyzer for your own highly-cautious projects.

**Comment by ronnygunawan** [comment]
This proposal actually solves issues raised in #2718:
1. The only change we need to make to the compiler is how the member access operator works. We don't need to change anything in run time. The analogy is that this is more like `IReadOnlyList<T>` instead of `ImmutableList<T>` when enforcing list immutability. Only in compile time, not run time.
2. Don't like too many new keywords: `open`, `closed`, `shared`, `rigid`? This proposal only has one: `local` and it is an access modifier, not an extra modifier.
3. On static accessibility: `local` member cannot be `const` or `static`

**Comment by YairHalberstadt** [comment]
@ronnygunawan

I think the chief issue with that proposal was that most people didnt think it was necessary tbh.

I agree this is a better version, but I think that the LDCs time could be better spent elsewhere.

**Comment by CyrusNajmabadi** [comment]
Almost any time a feature is proposed that *limits* what you can do in the language, a good thing to explain is: why is it not suitable and appropriate to just do this with an analyzer?

**Comment by ronnygunawan** [comment]
You guys are correct. I couldn't find a good case where a field should be declared as `local` instead of `private`. After extended testing, I came into the same conclusion that installing an analyzer that raises warning whenever a `private` field is accessed using dot operator is enough. I haven't found any special case where suppressing such warning is necessary.
