### ISSUE TITLE
[Proposal] appendable method modifier

### ISSUE THREAD

**Issue by giovani-luigi** [dotnet/csharplang#2771]
## Summary:
The proposal is a new modifier `append` that allow the child class to extend the functionality of a method declared as `appendable`, without overriding its initial functionality as in `override`.

### Motivation
Consider a virtual method `virtual void draw()`. To **extend** for example such method, in the child the programmer would have to call `base.draw()` followed by the additional desired code. There are some scenarios, where the code in the base class is required to run always, and failing to do so, by missing the `base.draw()`, could result in unexpected behavior. Many User interface controls use this override to allow visual style customization through overrides in a inherited class. Sometimes missing the call to the base class method, from the child class, will lead to undesired results, when child functionalities depend on resources setup within the parent code. Using append modifier, the code makes explicit to the child class designer that his code will run after a minimal setup is performed, without the base class having to write an extra function where the overridable placeholder will be calles (as seen in the "Old way 2" below).

### Proposed solution
 By using a new modifier such as `appendable void draw()` the designer of the base class is assured that his code will always run. The child class will then extend the method functionalities by either appending to it by defining the method as: `public append void draw()`

### Old way 1 (base class leaves responsibility to the child):
```
class BaseClass {
    public virtual void draw() {
        Console.WriteLine("Base");
    }
}
class ChildClass : BaseClass {
    public override void draw() {
        base.draw();
        Console.WriteLine("Child");  // extension of the base class functionalities
    }
}
```

**Output when calling `ChildClass.draw()` :**
> Base
> Child

### Old way 2 (base class enforces the parent code to run always):
```
class BaseClass {
    public void drawAll() {
        Console.WriteLine("Base");
        draw();
    }
    public virtual void draw() {
        // empty overridable placeholder method
    }
}
class ChildClass : BaseClass {
    public override void draw() {
        Console.WriteLine("Child"); // extension of the base class functionalities
    }
}
```
**Output when calling `ChildClass.draw()` :**
> Child

**Output when calling `ChildClass.drawAll()` :**
> Base
> Child

### New proposed way:
```
class BaseClass {
    public appendable void draw() {
        Console.WriteLine("Base");
    }
}
class ChildClass : BaseClass {
    public append void draw() {
        Console.WriteLine("Child"); // extension of the base class functionalities
    }
}
```

**Output when calling `ChildClass.draw()` :**
> Base
> Child

## Further development
In this methodology, the child could also use both `append` and `prepend` modifier. In the latter, the child code executes before the parent.

**Comment by HaloFour** [comment]
How do you propose this syntax works when there is a return value?  How does the "appended" logic use, modify or return that return value?  Same with `out` and `ref` parameters?  And with "prepended" logic, how do you modify the arguments before calling the base?

This proposal doesn't seem to add much to normal overriding of `virtual` methods.  At best it seems like it wants to force that the base is called and the the override happens in a specific order. But there are no details here as to how that would be enforced or work with other programming languages.  And the use case provided seems quite narrow.

The motivation feels like it would be better solved with an attribute and an analyzer that would warn or error if the base method is not called.

**Comment by MV10** [comment]
I've authored and maintained some very large libraries and have run into this problem regularly. At first I was on board with the OP's idea, but HaloFour's attribute and warning approach appeals to me more. That would also make it easy to ensure base-class constructors are called.

**Comment by canton7** [comment]
Personally I don't see what's wrong with "Old way 2 (base class enforces the parent code to run always)". It's a grand total of 13 characters longer than your proposal (ignoring whitespace), and you get full control over the return value, `out` and `ref`, modifying any parameters, etc.

If you're worried about people mistakenly calling `draw` instead of `drawAll` you could put in a proposal for C++'s `private virtual` methods, but that's a separate matter.
