### ISSUE TITLE
[Proposal] Implicit lambda parameter and trailing lambda in C#

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/csharplang#2781]
```csharp
var filtered = items.Where { Price > 9.99m }
                    .OrderBy { Name }
                    .ToList();
```

## Implicit lambda parameter:
- Allow omitting `() =>` when lambda has no parameter.
- Allow omitting `arg1 =>` when lambda has only one parameter.
- Lambda with implicit parameter must always be enclosed in braces.
- If lambda is ambiguous between `() =>` and `arg1 =>`, then implicit parameter can't be used.
- Members of implicit parameter can be directly used without member access operator, and will also hide names from enclosing type.
- The implicit parameter can be accessed using `value` keyword.
- `async` can be placed before the opening brace.
- `this` is unaffected. It still refers to enclosing type.

## Trailing lambda:
- If last parameter of a method is a lambda with implicit parameter, then the lambda can be written after the closing parentheses.
- If the method only have one such parameter, then the parentheses can be omitted too.
- Trailing lambda can be used in constructors as long as there is no overload that can cause conflict between trailing lambda and object initializer. eg:
```csharp
class Foo {
    public Foo(int x) { }
    public Foo(int x, Func<int, bool> f) { }
}

var foo = new Foo(10) { value % 2 == 0 }; // this is illegal because Foo has a
                                          // shorter constructor without the trailing lambda.

var foo = new Foo(10, f: { value % 2 == 0 }); // this is fine
```

## Examples:
```csharp
class Item {
    public string Name { get; set; }
    public decimal Price { get; set; }
}
```

### Functions
```csharp
// normal lambda
var filtered = items.Where(i => i.Price > 9.99m)
                    .OrderBy(i => i.Name)
                    .ToList();

// with implicit lambda parameter
var filtered = items.Where({ Price > 9.99m })
                    .OrderBy({ Name })
                    .ToList();

// with trailing lambda
var filtered = items.Where { Price > 9.99m }
                    .OrderBy { Name }
                    .ToList();
```

### Actions
```csharp
// normal lambda
items.ForEach(i => {
    Debug.WriteLine(i.Name);
    Console.WriteLine(i.Price);
});

// with implicit lambda parameter
items.ForEach({
    Debug.WriteLine(Name);
    Console.WriteLine(value.Price); // 'value' can be omitted
});

// with trailing lambda
items.ForEach {
    Debug.WriteLine(Name);
    Console.WriteLine(value.Price); // 'value' can be omitted
};
```

### Method with multiple lambda
```csharp
// normal lambda
var priceByName = items.ToDictionary(i => i.Name, i => i.Price);

// with implicit lambda parameter
var priceByName = items.ToDictionary({ Name }, { Price });

// with trailing lambda
var priceByName = items.ToDictionary({ Name }) { Price };
```

### Get creative with trailing lambda
```csharp
// VB-style With block
// note: following methods are not System.Console's static methods
With (console) {
    WriteLine("Hello World");
    BackgroundColor(ConsoleColor.Green);
    WriteLine("I am Green");
};

// fire and forget
Task.Run async {
    await Task.Delay(10000);
};

// foreach value in Range
ForEach(0..100) {
    Console.WriteLine(value);
};
```

**Comment by HaloFour** [comment]
Very similar to https://github.com/dotnet/csharplang/issues/1151

Kotlin and Scala both have a flavor of this feature (or set of features which can be combined to achieve this kind of syntax) and it can be useful to define DSL-like syntax.  Although, IMO, Scala takes it a bit too far as you can omit the dot operator (sometimes) and you can omit the parenthesis (sometimes).

**Comment by ronnygunawan** [comment]
#1151 went too far imo, it retargets what `this` refers to. In my opinion, the ability to retarget `this` doesn't fit in C#.

**Comment by orthoxerox** [comment]
@ronnygunawan wrll, your suggestion retargets `value` instead. Retargeting `this` or at least bringing the members of the parameter into scope would be very useful for writing DSLs.

**Comment by ronnygunawan** [comment]
@orthoxerox well, I think both retargeting `value` and `this` has their own problems then. Retargeting `value` limits lambda's usability when used inside a property setter, while retargeting `this` hides the original `this` from enclosing type.

Kotlin and Java solve the `this` retargeting problem using `EnclosingClassName@this`, and for the `value` retargeting problem, `value` keyword can be replaced by a new keyword `it`.

**Comment by marchy** [comment]
Is this on the consideration list for C# 11 / C# 12?

The RemObjects C# compiler supports this [Trailing Closures](https://docs.elementscompiler.com/Hydrogene/LanguageExtensions/TrailingClosures/) feature quite nicely, and Swift and Kotlin have supported this from the get-go (5+ years now). Would be great to see C# catch up to this modern must-have that can unlock all sorts of DSL-style APIs.

_NOTE: Swift has since extended to support [multiple trailing closures](https://www.hackingwithswift.com/swift/5.3/multiple-trailing-closures) (full [feature spec](https://github.com/apple/swift-evolution/blob/master/proposals/0279-multiple-trailing-closures.md)), thus directly supporting scenarios such as the example given above:_


_STRETCH: Not sure if compatible with C# named parameters overall, but being able to optionally specify those as well would make it these much more readable/useful as well._


**Some very useful real-world examples from functional-style utilities:**
```
//
// EXAMPLE 1
//
// current lambdas
DateTimeOffset rangeEndDate = endDateTime?.IfNotNull( endDateTime_ =>
		endDateTime_.StartOfDay() - ((crossesMidnight) ? 1 : 0).Days(),
	otherwise: () => startDateTime.StartOfDay() );

// with trailing lambda
DateTimeOffset rangeEndDate = endDateTime?.IfNotNull(
	value.StartOfDay() - ((crossesMidnight) ? 1 : 0).Days()
){ startDateTime.StartOfDay() };

// with multiple & named trailing lambdas (STRETCH)
DateTimeOffset rangeEndDate = endDateTime?.IfNotNull {
	value.StartOfDay() - ((crossesMidnight) ? 1 : 0).Days()
}, otherwise: { startDateTime.StartOfDay() };


//
// EXAMPLE 2
//
// current lambdas
GeoCoordinate? coordinate = Try.CatchingAsNull<ArgumentOutOfRangeException, GeoCoordinate?>( () =>
	new GeoCoordinate( place.geoCoordinate.latitude, place.geoCoordinate.longitude ),
@catch: x => { // NOTE: indentation hack to make it "feel" like a trailing lambda
	Log.LogError( $"Geo-coordinate for content #{attraction.id} out of bounds: ({place.geoCoordinate.latitude}, {place.geoCoordinate.longitude}). Error: {x.Message}" );
});

// with trailing lambda
GeoCoordinate? coordinate = Try.CatchingAsNull<ArgumentOutOfRangeException, GeoCoordinate?>( 
	new GeoCoordinate( place.geoCoordinate.latitude, place.geoCoordinate.longitude )
){ // NOTE: no indentation hack. Trailing lambdas naturally style back to the containing statement's indentation
	Log.LogError( $"Geo-coordinate for content #{place.id} out of bounds: ({place.geoCoordinate.latitude}, {place.geoCoordinate.longitude}). Error: {value.Message}" );
};

// with multiple & named trailing lambdas (STRETCH)
GeoCoordinate? coordinate = Try.CatchingAsNull<ArgumentOutOfRangeException, GeoCoordinate?>{
	new GeoCoordinate( place.geoCoordinate.latitude, place.geoCoordinate.longitude )
}, @catch: x => {
	Log.LogError( $"Geo-coordinate for content #{attraction.id} out of bounds: ({place.geoCoordinate.latitude}, {place.geoCoordinate.longitude}). Error: {x.Message}" );
};
```
