### ISSUE TITLE
Discussion: Inline type constraints

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#279]
## Inline type constraints

Proposal: https://github.com/dotnet/roslyn/issues/7671

With numerous type parameters, type constraints require duplicating every type parameter to the point that it's somehow confusing, 

```cs
internal abstract class AbstractUseCoalesceExpressionForNullableDiagnosticAnalyzer<
  TSyntaxKind,
  TExpressionSyntax,
  TConditionalExpressionSyntax,
  TBinaryExpressionSyntax,
  TMemberAccessExpression,
  TPrefixUnaryExpressinSyntax> : AbstractCodeStyleDiagnosticAnalyzer
  where TSyntaxKind : struct
  where TExpressionSyntax : SyntaxNode
  where TConditionalExpressionSyntax : TExpressionSyntax
  where TBinaryExpressionSyntax : TExpressionSyntax
  where TMemberAccessExpression : TExpressionSyntax
  where TPrefixUnaryExpressinSyntax : TExpressinSyntax
```

Inlining type parameters could significantly reduce noise around the type declaration,
```cs
internal abstract class AbstractUseCoalesceExpressionForNullableDiagnosticAnalyzer<
  TSyntaxKind : struct,
  TExpressionSyntax : SyntaxNode,
  TConditionalExpressionSyntax : TExpressionSyntax,
  TBinaryExpressionSyntax : TExpressionSyntax,
  TMemberAccessExpression : TExpressionSyntax,
  TPrefixUnaryExpressinSyntax : TExpressionSyntax> : AbstractCodeStyleDiagnosticAnalyzer
```
This syntax would bring type parameter constraints closer to their declaration,
```cs
void F<T, U : IEnumerable<T>>(U source) {}
```

Inlined type constraints can be mixed with default type parameters (#278), e.g.

```cs
class IEquitable<T : this = this> {}
```

Multiple type constraints can be inlined using "intersection types", using whatever syntax that they're going to use,
```cs
void F<T : Interface1 | Interface2>() {}
```

However, it might be actually preferable to only allow "simple" type constraints in this manner.

**Comment by elcergey** [comment]
Support this. Would be quite handy.

**Comment by TonyValenti** [comment]
This is a great proposal.  I would also love it if constraints were automatically inherited based on inference.

For example, this code is redundant:
````

Public class Super< T : Person> : Base<T> {

}

public class Base<T : Person> {

}
````

I should be able to say:
````

Public class Super<T> : Base<T> {

}

public class Base<T : Person> {

}
````
And have Super's ````T```` automatically pick up the T:Person constraint from Base.  I've found it really annoying when I have a base class that has certain constraints and every time I work with a base class, I have to go change the constraints on every single derivative.

**Comment by alrz** [comment]
@TonyValenti https://ericlippert.com/2013/07/15/why-are-generic-constraints-not-inherited/
