### ISSUE TITLE
The compiler doesn't warn about a non-nullable reference property in value types

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/csharplang#2791]
When nullable is enabled the compiler notifies that a reference type property in a class should be marked as nullable when there is no value assigned to it on initialization, but it doesn't do this for value types containing reference type properties. In the last case there is no way to specify the default value for a property since there is no parameterless constructor, and such properties are always initialized as `null`.

```csharp
#nullable enable

class ClassType
{
    public string Value { get; set; } // warning CS8618: Non-nullable property 'Value' is uninitialized. Consider declaring the property as nullable.
}

struct ValueType
{
    public string Value { get; set; } // no warning
}
```

Compiler version: '3.3.0-ci (<developer build>)'.
Language version: preview.

**Comment by Joe4evr** [comment]
@YohDeadfall But you get a warning upon consumption, see https://github.com/dotnet/csharplang/issues/2328#issuecomment-471564414
