### ISSUE TITLE
Allow type parameter to be used in attributes

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/csharplang#2808]
```csharp
[Union(0, typeof(Bar<T>))]
class Foo<T>
{
}
```

**Comment by dsaf** [comment]
Not going to be done any time soon https://github.com/dotnet/csharplang/issues/124

**Comment by yaakov-h** [comment]
This seems different to #124. `UnionAttribute` isn't generic itself, but referring to the generic type argument `T` on the class it's applied to.

**Comment by Joe4evr** [comment]
This would require instantiating the attribute for every type argument passed to `Foo<T>`, which I don't know is feasible, but it sure doesn't sound desirable.

**Comment by canton7** [comment]
What are you trying to achieve? Can you use `[Union(0, typeof(Bar<>))]`?

**Comment by Joe4evr** [comment]
If I understand correctly, what he wants is for example
```cs
//attribute instantiated as 'Union(0, typeof(Bar<string>))'
var attr1 = typeof(Foo<string>).GetAttribute<UnionAttribute>();

//attribute instantiated as 'Union(0, typeof(Bar<int[]>))'
var attr2 = typeof(Foo<int[]>).GetAttribute<UnionAttribute>();
```

**Comment by canton7** [comment]
Agreed that that's what he's asking for, but I'm questioning whether he *needs* that, or whether he can get away with `typeof(Bar<>)` (not everyone knows you can do `typeof(Bar<>)`)

**Comment by ronnygunawan** [comment]
It's to make it easier to deserialize properties where the type is a generic interface or an abstract class.

Instead of always writing custom formatter like this for MessagePack deserialization:
```csharp
[MessagePackObject]
class Item<T> {
    [Key(0), MessagePackFormatter(typeof(FooTDerivedClassFormatter))]
    public Foo<T> Foo { get; set; }
}

abstract class Foo<T> {
}

class Bar<T> : Foo<T> {
}
```

Allowing T to be used in attribute parameter would allow:
```csharp
[MessagePackObject]
class Item<T> {
    [Key(0)] // no need to write so many custom formatters
    public Foo<T> Foo { get; set; }
}

[Union(0, typeof(Bar<T>))]
abstract class Foo<T> {
}

class Bar<T> : Foo<T> {
}
```

Json serializer and other serializers have similar problem, and I think they would also benefit from this feature.

> Can you use `[Union(0, typeof(Bar<>))]`?

In this case, T is required to decide how the rest of the message is deserialized. Thus, it can't be omitted.

**Comment by YairHalberstadt** [comment]
Closing as championed at #124
