### ISSUE TITLE
New interface implementing IDisposable exposing dispose state information 

### ISSUE THREAD

**Issue by JiriCepelkaFirstLineSoftware** [dotnet/csharplang#2817]
Sometimes I could be convenient to know if IDisposable implementation is already disposed without exercising some try/catch about [ObjectDisposedException](https://docs.microsoft.com/en-us/dotnet/api/system.objectdisposedexception?view=netframework-4.8) or other/similar cases.

Instance:

    var request = (HttpWebRequest)WebRequest.Create("http://www.seznam.cz");
    
    using (var response = request.GetResponse())
    {
        using (var responseStream = response.GetResponseStream())
        {
            using (var streamReader = new StreamReader(responseStream))
            {
                responseStream.ReadByte();
                WriteLine("responseStream: " + responseStream.CanRead);
            }
    
            WriteLine("responseStream: " + responseStream.CanRead);
            responseStream.ReadByte();        
        }    
    }

`responseStream: True`
`responseStream: False`

`The request was aborted: The connection was closed unexpectedly.`
`  + System.Net.ConnectStream.Read(byte[], int, int)`
`  + System.IO.Stream.ReadByte()`

Instead of rely on exact implementation one could easily extract information needed from bool property.

    interface IDisposableExt : IDisposable { 
        bool AlreadyDisposed { get; }
    }

To **prevent braking change** this could be new interface implementing IDisposable.

**Implementation**
Yet nowadays developer is responsible for implementing IDisposable pattern properly. Specifically: call _GC.SuppressFinalize(this)_, release object resources only once, handle finalizer/consumer call case and further more responsibilities on this. Regard this pattern there already exists private field bool disposed.

`private bool disposed = false;`

Since that transforming such a private bool field to public bool property is little-effort change in responsibility (IDisposable pattern).

`bool AlreadyDisposed { get; }`

**Comment by YairHalberstadt** [comment]
This would be a request for dotnet/CoreFx.

However this would be a breaking change. Even with DIMs the default implementation couldn't do anything useful so would be confusing.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
I thought about break so maybe I should state it extra.

**Comment by YairHalberstadt** [comment]
How would this be implemented? Would developers be expected to manually set AlreadyDisposed? Or should something magically generate this code for them?

If so what should do that? The runtime, or C#?

The runtime doesn't have any special knowledge of IDisposable AFAIK, and I don't think we would want to change that.

A language change would mean that you would need to recompile all existing code to get this to work. Given that not doing so would be a breaking change, that's basically an impossible requirement.

**Comment by YairHalberstadt** [comment]
> To prevent braking change this could be new interface implementing IDisposable.

What language changes are you suggesting, if any?

**Comment by yaakov-h** [comment]
I don’t see how your example helps create the case for such a feature. In your example you already have this information through CanRead. Then, after seeing that CanRead is false, you’ve called ReadByte, which thrown an exception because you can’t read from it...

Furthermore, you shouldn’t *need* to know. If you have an object and you can’t tell if it’s disposed or not, you have a bug in your object lifecycle management.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> I don’t see how your example helps create the case for such a feature. In your example you already have this information through CanRead. Then, after seeing that CanRead is false, you’ve called ReadByte, which thrown an exception because you can’t read from it...
> 
> Furthermore, you shouldn’t _need_ to know. If you have an object and you can’t tell if it’s disposed or not, you have a bug in your object lifecycle management.

You’re missing the intention. There is not problem in determining if object is or is not disposed. Problem is that each time you can find such information in different way. That could be considered uncommon approach with no benefit.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> 
> 
> How would this be implemented? Would developers be expected to manually set AlreadyDisposed? Or should something magically generate this code for them?
> 
> If so what should do that? The runtime, or C#?
> 
> The runtime doesn't have any special knowledge of IDisposable AFAIK, and I don't think we would want to change that.
> 
> A language change would mean that you would need to recompile all existing code to get this to work. Given that not doing so would be a breaking change, that's basically an impossible requirement.

I supplied missing information. No changes in runtime, no breaking changes. Just new IDisposable implementing interface and small pattern change.

**Comment by YairHalberstadt** [comment]
As far as I can see this requires no language changes so should be moved to https://github.com/dotnet/corefx

**Comment by HaloFour** [comment]
At this point in the game I'd suggest it's way too late for a change like this.  If it were accepted to CoreFX as a DIMed addition to the `IDisposable` interface that would lead to all existing disposables either appearing perpetually disposed or perpetually undisposed.  There's no way for the runtime to accurately reflect whether or not `Dispose` was called.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> At this point in the game I'd suggest it's way too late for a change like this. If it were accepted to CoreFX as a DIMed addition to the `IDisposable` interface that would lead to all existing disposables either appearing perpetually disposed or perpetually undisposed. There's no way for the runtime to accurately reflect whether or not `Dispose` was called.

I don’t read you well. What is DIM? Why such addition would lead to that state? Why not to introduce new interface?

**Comment by HaloFour** [comment]
@JiriCepelkaFirstLineSoftware 

> Why not to introduce new interface?

That would do nothing to help the thousands or millions of existing disposable types.

> There is not problem in determining if object is or is not disposed. Problem is that each time you can find such information in different way.

I don't see why that is a problem.  Disposal means a lot of different things to a lot of different classes.

In either case, as mentioned, this is a question for [CoreFX](https://github.com/dotnet/corefx) as it involves changes to the library and not to the language.

**Comment by Joe4evr** [comment]
"DIM" means Default Interface Members, which technically allows you to add new members to an interface without breaking your downstream implementers, but there's no way to do that for determining if Dispose was called.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> 
> 
> @JiriCepelkaFirstLineSoftware
> 
> > Why not to introduce new interface?
> 
> That would do nothing to help the thousands or millions of existing disposable types.
> 
> > There is not problem in determining if object is or is not disposed. Problem is that each time you can find such information in different way.
> 
> I don't see why that is a problem. Disposal means a lot of different things to a lot of different classes.
> 
> In either case, as mentioned, this is a question for [CoreFX](https://github.com/dotnet/corefx) as it involves changes to the library and not to the language.

Ok, ok. CoreFX – https://github.com/dotnet/corefx/issues/41256.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> "DIM" means Default Interface Members, which technically allows you to add new members to an interface without breaking your downstream implementers, but there's no way to do that for determining if Dispose was called.

Aha, thank you for information. The rest I read well.
