### ISSUE TITLE
Relax 'out' keword as optional for joined variable declarations

### ISSUE THREAD

**Issue by setbbtjl8wwq** [dotnet/csharplang#2818]
Current syntax
```c#
int i;
int.TryParse(s, out i)

int.TryParse(s, out int i)

int.TryParse(s, out var i)
```
Relaxed `out`
```c#
int i;
int.TryParse(s, out i)

int.TryParse(s, int i)

int.TryParse(s, var i)
```
Why not?

**Comment by HaloFour** [comment]
@setbbtjl8wwq 

> Why not?

More important question is "why"?  The `out` modifier is an important part of the signature.  It indicates that you're calling the method with a reference to the underlying type.  It's also necessary for overload resolution.

**Comment by canton7** [comment]
Related: https://github.com/dotnet/csharplang/issues/2778

**Comment by setbbtjl8wwq** [comment]
@HaloFour
According your logic `in` keyword "is an important part of the signature" too, but this is valid code
```c#
int Test(in int i) => i;

int i = 0;
Test(in i);
Test(i);
```

> More important question is "why"?

Mathematical beauty and symmetry (according the Group Theory).
Removing of unnecessary keywords from the code. Generalization...

**Comment by DanFTRX** [comment]
@HaloFour In this case wouldn't overload resolution be fine because his proposal still requires either the out keyword or a variable declaration in place?  
```CSharp
   int i;
   int.TryParse(s, out i);
   int.TryParse(s, int j);  <-- Presence of declaration indicates implicit out keyword
```

I can only see the problems that would exist if you could just pass an already defined variable identifier in without the out keyword like the following:
```CSharp
   int i;
   int.TryParse(s, i); <-- Can't tell if out parameter or just regular parameter
```

Note I am not advocating for/against this proposal, I just wanted to make sure my understanding was correct.

**Comment by HaloFour** [comment]
@setbbtjl8wwq 

> According your logic `in` keyword "is an important part of the signature" too, but this is valid code

`in` does change the type of the parameter in question, but not the semantics.  There's no expectation that the value of the variable passed as an `in` parameter might change.

> Mathematical beauty and symmetry (according the Group Theory).
> Removing of unnecessary keywords from the code. Generalization...

Clarity is much more important than "beauty" or "symmetry".  I disagree with the concept that those keywords are unnecessary.

**Comment by Pretasoc** [comment]
@setbbtjl8wwq 
>Mathematical beauty and symmetry (according the Group Theory).

I don't understand the relation between the syntax of a method call an group theory.

**Comment by setbbtjl8wwq** [comment]
@DanFTRX 
Your understanding is right. Relaxing is valid only for joined declarations.
```c#
   int i;
   int.TryParse(s, out i);
   int.TryParse(s, int j);  // Presence of declaration indicates implicit out keyword
```
```c#
   int i;
   int.TryParse(s, out i); // 'out' keyword is requried
```

**Comment by setbbtjl8wwq** [comment]
@HaloFour 

> in does change the type of the parameter in question, but not the semantics. There's no expectation that the value of the variable passed as an in parameter might change

Intuitively
> Presence of declaration indicates implicit out keyword

**Comment by ronnygunawan** [comment]
> The `out` modifier is an important part of the signature. It indicates that you're calling the method with a reference to the underlying type. It's also necessary for overload resolution.

But since a method can't have overload which differs only on parameter modifiers (`ref` vs `out`, `ref` vs `in`), I believe this is a non-issue.

![foo](https://user-images.githubusercontent.com/3048897/65447751-72291600-de61-11e9-8c96-f837b967893f.png)

**Comment by setbbtjl8wwq** [comment]
@Pretasoc 

> I don't understand the relation between the syntax of a method call an group theory.

So, this relations with the Group Theory is very thin but I try to explain at simple sample.

Consider two syntax variations
```c#
/* expression of type A */
int i;
int.TryParse(s, out i)
```
and
```c#
/* expression of type B */
int.TryParse(s, out int i)
```

At first we have `Id (Identity) transform` which translates `expression of type A` into `expression of type A` and `expression of type B` into `expression of type B`. Stay the same in another words.

Then we have `X transform` which translates `expression of type A` into `expression of type B` and `expression of type B` into `expression of type B`

Then we have `Y transform` which translates `expression of type B` into `expression of type A` and `expression of type A` into `expression of type A`

So, now we have a set of tansforms `(Id, X, Y)`

Consider this set according the [group axioms](https://en.wikipedia.org/wiki/Group_(mathematics)):
**Closure**
X( X(expression) ) == X(expression)
Y( Y(expression) ) == Y(expression)
X( Y(expression) ) == Id(expression)
Y( X(expression) ) == Id(expression)
**Associativity**
for example
Id( X( Y(expression) ) ) == X( Y( Id(expression) ) )
**Identity element**
Exists
**Inverse element**
var expression = A|B type;
Id(expression) == X( Y(expression) )
Id(expression) == Y( X(expression) )
Exists

Seems, that we have really strict mathematical group.


But if we try consider slightly different kinds of expressions by this principles
```c#
/* expression of type C */
int i = 5;
int.TryParse(s, out i)
```
and
```c#
/* expression of type D */
int.TryParse(s, out int i = 5) // compile error
```
We may found the language limitation which breaks mathematical group. It is not possible to apply transforms similar like X and Y. We have only primitive group from single `Id transform` which translates `expression of type C` into `expression of type C`. No more.


Of course, I am not professional mathematical, just amatory and can misunderstood something.

**Comment by TheUnlocked** [comment]
This would syntactically conflict with a far more useful potential feature of variable declaration expressions (i.e. `Foo(int i = 14)`). While such a feature is not in any way planned (as far as I know), ruining the potential of that feature seems like a high cost for what ultimately would save four characters while decreasing legibility.

**Comment by theunrepentantgeek** [comment]
Requiring the **out** keyword _at the call site_ is one example where C# diverged from languages that went before.

This was somewhat controversial when C# was first introduced, back around 2000 - and there was a fair amount of information shared by Anders Hejlsberg and others about why they felt the keyword was needed to avoid programmer confusion and application defects.

The closest reference I've been able to Google is [this StackOverflow answer from 2009](https://stackoverflow.com/a/620457/30280); unfortunately, it doesn't link to anything from the C# team themselves.

**Comment by eelstork** [comment]
@setbbtjl8wwq I appreciate your point, but there is a key difference between the `in` and `out` modifiers here:
- With an `out` or `ref` param the argument is required (or allowed) to be mutated. Arguably, C# is already [lacking immutability semantics](http://blog.dunnhq.com/index.php/2017/12/15/readonly-parameters-in-c-a-step-closer-to-immutability/); without the `out` param a casual reader may not understand that the argument may be mutated.
- In contrast, `in` is in continuity with pass by value - either way the argument won't be mutated, so this can be omitted without damaging readability.

If I was looking for places where a data type is mutated, I'd search for `out` and `ref`; from this point of view, verbosity in `int.TryParse(s, out int i)` is preferable to elegance.

**Comment by setbbtjl8wwq** [comment]
@eelstork 
IMHO, there are key difference between mutation and initialization of variables.
```c#
int i = default;

/* mutations for left and right side assignments */
i = 5;
5.To(out i); /* 'out' signalize about mutation */
```

 ```c#
/* initializations for left and right side assignments */
var i = 5;
5.To(out var i);

// because there is not a mutation we can avoid 'out'
5.To(var i);

```

**Comment by eelstork** [comment]
Valid point.
