### ISSUE TITLE
C# 7 Out variables inconstant scoping with flow control qualifiers

### ISSUE THREAD

**Issue by zezba9000** [dotnet/csharplang#282]
Continuation of topic: [Rolsyn Git Page Link](https://github.com/dotnet/roslyn/issues/17669#issuecomment-286963316)

Because this topic stilled seems to be in maybe a state of conflict I decided to continue the discussion.

QUOTE from original post:

> **Version Used:**
> C# 7 (VS 2017)
> 
> **Steps to Reproduce:**
> if (Foo(out int i))
> {
> i.ToString();// valid scope
> }
> 
> i.ToString();// 'i' can be used outside of the 'if' scope block?
> 
> **Expected Behavior:**
> 'i' should only live in the if's scope.
> 
> Just like any flow control qualifier such as 'for' or 'while' the scope of variables should start within the '()' brackets. Otherwise this is just syntax sugar without any real value as its inconstant with the rest of the C# syntax. Maybe I'm missing something but just feels wrong.
> 
> **Actual Behavior:**
> 'i' can be used outside of the if's scope.

**Comment by HaloFour** [comment]
Is there anything left to discuss?  This horse was beaten to death a while ago and despite various objections the LDM decided to implement "leaky" scope anyway.  The compiler has already shipped with this behavior.  Even if you could find a novel and Earth-shattering argument as for why the decision wasn't correct, changing it would be a breaking change.

**Comment by CyrusNajmabadi** [comment]
I agree with @HaloFour .  We're very well aware of the leakyness of the approach we took.  Indeed, it was a conscious, deliberate decision to provide what we felt was the best feature overall for the most number of customers.  So far, the feature has been received as we had expected.  Those who want leakyness are able to use the feature effectively.  Those who don't want leakyness, but don't reuse names, do not have a problem.  But those who don't want leakyness and do want to reuse names are unable to.  This was a known limitation with this approach that we understood and decided was acceptable.

**Comment by zezba9000** [comment]
Ok just sounded like others wanted to add. Closing issue.
