### ISSUE TITLE
Nullable Reference Types analysis can be thrown off by condition

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/csharplang#2820]
See screenshot here:
Iv enabled NRT im on .net core 3.0 release and latest visual studio.

![image](https://user-images.githubusercontent.com/4672627/65468457-0bedc480-de5c-11e9-87a1-f8f87cd40cbb.png)

then if I add in a call with a condition on a value being not null...

![image](https://user-images.githubusercontent.com/4672627/65468540-45becb00-de5c-11e9-9898-0199e86e3c42.png)

It seems to suggest to the compiler that after this line, x might be null, because the programmer checked for it being null.

Is this intended behavior?

```
My helper methods are defined as:

[MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ContractAnnotation("condition:false=>stop")]        
        public static void Requires<TException>(bool condition) where TException : Exception, new()
        {
            if (!condition)
            {
                throw new TException();
            }
        }
```

**Comment by 333fred** [comment]
`Contract.Requires<TException>` needs a `[DoesNotReturnIf(false)]` on the condition. See how [`Debug.Assert`](https://source.dot.net/#System.Private.CoreLib/shared/System/Diagnostics/Debug.cs,80) does it. If that still doesn't fix it, I'd suggest opening an issue on dotnet/roslyn, as this isn't the right venue.

**Comment by 333fred** [comment]
Also, yes, the warning is intended behavior. `!= null` is a pure null test: https://github.com/dotnet/csharplang/blob/c229cae634/meetings/2019/LDM-2019-02-20.md#deliberate-tests-for-nullability

**Comment by danwalmsley** [comment]
@333fred many thanks for feedback, I will test your suggestions.
