### ISSUE TITLE
Type Judgment/Conversion Expand

### ISSUE THREAD

**Issue by LeaFrock** [dotnet/csharplang#2832]
While I read the source code of 'Dictionary<TKey, TValue>', I see the codes below,
` if (dictionary.GetType() == typeof(Dictionary<TKey, TValue>))`
            `{`
                `Dictionary<TKey, TValue> d = (Dictionary<TKey, TValue>)dictionary;`
                `……`
               ` return;`
           ` }`
with comments below.

> It is likely that the passed-in dictionary is Dictionary<TKey,TValue>. When this is the case,
> avoid the enumerator allocation and overhead by looping through the entries array directly.
> We only do this when dictionary is Dictionary<TKey,TValue> and not a subclass, to maintain
> back-compat with subclasses that may have overridden the enumerator behavior.

It's really reasonable, but the codes seem to be a little bit ugly. It writes twice but just wants to do one thing. And will the compiler be smart enough to optimize the codes with avoiding repeated type judgment?
C# has already got 'is/as' in use to judge/convert types, and in C# 7. 0 we can write codes like "if a is B b" to avoid the old ones like "if(a is B){var c = (B)a; ....}".  So can we do anything easier for judging/converting the **accurrate** type? Take 'is' for example, if we have a keyword 'simple-is',
`//B is subclass of A, and B has no subclasses. A b = new B();`
`b is A    //true`
`b simple-is A    //false, because the actual type of 'a' is B.`
`b simple-is B    //true`
It's just an example instead of a suggestion. This issue hopes to discuss with others on the possible optimization of the detail above.

P.S. Here is the link, from row 103. [https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs](url).

**Comment by YairHalberstadt** [comment]
The question is how common this is. I would say the number of times I've needed this is extremely low, whereas I use is a dozen times a day. 

It's not worth adding a keyword for rare use cases, which already have perfectly valid ways of doing them. Otherwise C# would end up with thousands of keywords for every possible scenario.

**Comment by LeaFrock** [comment]
> The question is how common this is. I would say the number of times I've needed this is extremely low, whereas I use is a dozen times a day.
> 
> It's not worth adding a keyword for rare use cases, which already have perfectly valid ways of doing them. Otherwise C# would end up with thousands of keywords for every possible scenario.

I've emphasized that adding a keyword is just for example instead of suggestion. In fact I have no good ideas, so I commit this issue and hope to discuss with you.
Also, I don't agree with you about the low use of it. Now the detail happens in FCL, and the source codes of Dictionary(and other similar codes) may be executed for millions of times. In my opinion, it's a short point which could be optimized. 
Of course, everyone has their own opinions. Let's have a full exchange of views.

**Comment by YairHalberstadt** [comment]
> may be executed for millions of times. In my opinion, it's a short point which could be optimized.

I would suggest taking a look at the outputted IL and JIT. If you think it is inneficient, you could suggest to roslyn/coreclr to recognise and optimise this pattern.

**Comment by canton7** [comment]
Looks like the JIT already does some fancy stuff:

```csharp
public class C {
    public bool M(object o) {
        return o is C;
    }
    public bool N(object o) {
        return o.GetType() == typeof(C);
    }
}
```

Produces:

```asm
C.M(System.Object)
    L0000: mov ecx, 0x1ba7c6f8
    L0005: call 0x62df6140
    L000a: test eax, eax
    L000c: setnz al
    L000f: movzx eax, al
    L0012: ret

C.N(System.Object)
    L0000: cmp dword [edx], 0x1ba7c6f8
    L0006: setz al
    L0009: movzx eax, al
    L000c: ret
```

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgZgARYBMeAwngN4CwAUHnQfsAPZMA2eAsgBRPABWcAMYw8TAJQUa9aQQDsovAEsopANxT6AXw11ceZmzwA5HvyEjxk2jN3ymAOgDicGABUAngAc4XCQF4/PBgvOCYAMy4SMXVrOm1qTSA==)

**Comment by HaloFour** [comment]
The runtime already optimizes for that pattern in a number of places.  For example, it can emit specialized generic code when comparing `typeof(T)` to a specific type within a generic method.

As for language ergonomics, switching on type has been suggested in the past, but I don't think it got a lot of support from the language team:

```cs
switch (o.GetType()) {
    case string: // do stuff
    case Dictionary<string, int>: // do other stuff
}
```

**Comment by LeaFrock** [comment]
> I would suggest taking a look at the outputted IL and JIT. If you think it is inefficient, you could suggest to roslyn/coreclr to recognise and optimise this pattern.

That's an idea. It makes sense if the compiler is(or could be) smart enough. I'll do some experiments. Thanks!

**Comment by canton7** [comment]
> It makes sense if the compiler is(or could be) smart enough. I'll do some experiments. 

The compiler isn't smart enough (nor should it be), but the runtime is. See my post above.

**Comment by LeaFrock** [comment]
> The compiler isn't smart enough (nor should it be), but the runtime is. See my post above.

Thanks. I've read it. But my question is not about the difference between 'is' and 'GetType()'. It's that,
`if(a.GetType()==typeof(B))`
`{`
`var b = (B)a; `
`........`
`}`
**How many times the type judgment occurs? Only once? Or twice?**
In the past, I remember the answer was 'twice' in the old codes like  `if(a is B){var b= (B)a;...}`. But now in C# 7.x, we can write the codes like 'if(a is B b){.....}', and the answer is 'once'. If my memory or understanding is wrong, please tell me.
I know the compiler or runtime is upgrading, but you can see that the feature also depends on the side of language.

**Comment by canton7** [comment]
If you see the assembly in my post, you'll see that the runtime optimized `o.GetType() == typeof(C);` down to effectively a single `cmp` instruction. That's near enough free.

There will be a small cost to any subsequent `(C)o` of course, but you're only paying this cost once, because the `o.GetType() == typeof(C);` is basically free.

**Comment by LeaFrock** [comment]
> because the `o.GetType() == typeof(C)` is basically free.

Oh I got it. You mean the cost of judging type once can basically be ignored, comparing with the one of type conversion, right?

**Comment by canton7** [comment]
> You mean the cost of judging type once can basically be ignored, comparing with the one of type conversion, right?

Yes. `o.GetType() == typeof(C)` is so cheap that you can ignore it.

**Comment by LeaFrock** [comment]
> Yes. `o.GetType() == typeof(C)` is so cheap that you can ignore it.

Thanks, that could be a reason for me to give up. 
But I still want to keep this issue open in a week to see if someone can dig more interesting things and take new discussions.

**Comment by huoyaoyuan** [comment]
This check can be done by a simple helper though:
```csharp
public bool IsExact<T>(object obj, out T exact)
    where T : class
{
    if (obj.GetType() == typeof(T))
    {
        exact = (T)exact;
        return true;
    }
    else
    {
        exact = null;
        return false;
    }
}
```

If CLR does inline and degeneralization, the code should be optimized.

**Comment by LeaFrock** [comment]
>But I still want to keep this issue open in a week to see if someone can dig more interesting things and take new discussions.

Thanks for all replies above. Close this issue.
