### ISSUE TITLE
[Proposal] Cascade notation

### ISSUE THREAD

**Issue by montyclt** [dotnet/csharplang#2842]
I sugest to add cascade notation like Dart to C#, so this allow to use any object as fluent API without worrying about if the design of the API is fluent or not.

```
IList<string> names = new List<string>();

names
    ..Add("Mary")
    ..Add("Peter")
    ..Add("John");
```
In this example, the return type of `Add(string)` is ignored and `names` list is returned.

This notation will allow call setters like this:

```
var person = new Person();

person
    ..FirstName = "John"
    ..LastName = "Doe"
    ..Age = 18;
```

This feature solve the problem of #902

[More info about cascade notation in dart.](https://dart.dev/guides/language/language-tour#cascade-notation-)

**Comment by canton7** [comment]
Suggested [as part of #2580](https://github.com/dotnet/csharplang/issues/2580#issuecomment-499931484)

**Comment by montyclt** [comment]
Sorry @canton7, I did't see it.

**Comment by montyclt** [comment]
I'll still this issue open (for now) because the OP in #2580 don't suggest exactly the same.

**Comment by Joe4evr** [comment]
Still an exact duplicate of #1825.

**Comment by montyclt** [comment]
Thanks @Joe4evr. I close it.
