### ISSUE TITLE
Null coalescing operator for strings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/csharplang#2848]
<p>While it's possible to use the null coalescing operator with strings to assign a default value when <b>the strings can be null</b>, the null coalescing operator can't be use with TextBox.Text properties because they are never null, but they can be empty strings.</p><p>It would be helpful to extend the null coalescing operator for strings and make them treating empty string as they were null strings. By this way instead of programming:</p><pre>s0 = String.IsNullOrEmpty(myTextBox.Text) ? sDefault : myTextBox.Text;</pre><p></p><p>we can use the shorter and easier to read form:</p><pre>s0 = myTextBox.Text ?? sDefault :</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/374856/null-coalescing-operator-for-strings.html
VSTS ticketId: 723588_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/4/2018, 08:13 PM (17 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by Thaina** [comment]
I disagree on the change. But I understand what you come from. I also wish that there should be  `"".NullIfEmpty()` and `"".NullIfWhiteSpace()` extension method in the core BCL

**Comment by YairHalberstadt** [comment]
Closing as this is a very large breaking change, and so is not really possible.
