### ISSUE TITLE
C#8 reference nullability for LINQ?

### ISSUE THREAD

**Issue by zeroskyx** [dotnet/csharplang#2855]
Greetings,

is it possible that LINQ (and especially IEnumerable<T>) has not yet been updated to the new nullability features?

Especially IEnumerable<T> does not appear to issue any CS8602 (Dereference of a possibly null reference) at the moment.

**Comment by yaakov-h** [comment]
What’s your target framework?

**Comment by canton7** [comment]
Linq has been annotated in corefx, but I don't believe it made the .NET Core 3.0 release.

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Linq/ref/System.Linq.cs
This is what you get in 3.0:
https://github.com/dotnet/corefx/blob/release/3.0/src/System.Linq/ref/System.Linq.cs

> is it possible that LINQ (and especially IEnumerable) has not yet been updated to the new nullability features?

Only CoreLib gets nullable enabled in 3.0.

**Comment by YairHalberstadt** [comment]
Linq has now been annotated. For future reference such questions should be directed to dotnet/runtime
