### ISSUE TITLE
Draft Spec for Switch Expression as a Statement Expression in C# 9.0

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2860]
We add the switch expression to the set of syntactic forms permitted in an *expression_statement*:

```antlr
expression_statement
    : statement_expression ';'
    ;

statement_expression
    : switch_expression
    // in addition to all the other forms specified elsewhere
    ;
```

When a switch expression is used as a *statement_expression*,
- the expression of each arm of the switch expression is required to be a *statement_expression* or a *throw_expression*; and
- the switch expression is not required to have a type.

**Comment by gafter** [comment]
This is a draft spec for https://github.com/dotnet/csharplang/issues/2632

**Comment by mrlife** [comment]
Is this still planned and does it provide support for this?

https://dotnetfiddle.net/E2mrrC

**Comment by 333fred** [comment]
Closing this out, it is tracked by #2632. If we decide to move forward with the proposal, we can check the spec in at that point.
