### ISSUE TITLE
C# proposal: implicitly convert nullable bool to bool

### ISSUE THREAD

**Issue by mariusGundersen** [dotnet/csharplang#2861]
Given the following

```C#
bool? maybe = true;

if(maybe){
  Console.WriteLine("Success");
}
```

What is the expected result? The actual result is that compilation fails with the error "Cannot implicitly convert type 'bool?' to 'bool'.". That seems weird to me. I can understand why other nullable types cannot be implicitly converted to their non-nullable equivalent, but for `Nullable<bool>` that is slightly annoying, since now I need to write `if(maybe == true)`. 

I therefore propose that nullable bool can be implicitly converted to bool, such that `null` => `false`.

**Comment by stepanbenes** [comment]
The `null` value is generally considered as "I don't know" value. So, why should it be interpreted as `false`?

**Comment by spydacarnage** [comment]
If you consider that `if (maybe)` is shorthand for `if (maybe == true)`, yet they work differently.

If a `bool?` is null, then it isn't `true`, so while `null` shouldn't be interpreted as `false`, it should be interpreted as not `true`, and thus should fail `if (maybe)`, as opposed to having a compiler error.

**Comment by HaloFour** [comment]
This was an intentional design choice to force the developer to consider `bool?` as a proper tristate.  `null` is neither `true` nor `false` and treating it as either implicitly can lead to accidental logic errors.

**Comment by elpoul** [comment]
`if (<expression>)` is a shorthand for `if (<expression> == true)` only if `<expression>` is a boolean expression itself. In my experience I've seen as many instances of `if (maybe ?? true)` as `if (maybe ?? false)` so I do believe that in nullable booleans it makes more sense to be explicit.

**Comment by canton7** [comment]
> If you consider that if (maybe) is shorthand for if (maybe == true), yet they work differently.

Is it? Why not `if (maybe != false)`?

**Comment by spydacarnage** [comment]
@canton7  - A fair question, and one that needs investigation of the underlying IL to answer.  I'm not an expert on IL codes, but it seems that both `if (maybe)` and `if (maybe == true)` produce the same code - `brfalse.s`, which, according to the reference "Transfers control to a target instruction if value is false, a null reference, or zero.", so it equates a null reference to `false`.

(not that I'm arguing against the provided reason behind the original design - I was just intrigued by you questioning something I've thought was true for a very long time!)

**Comment by mariusGundersen** [comment]
Having `if(maybe)` be equivalent to `if(maybe == true)` does not prevent using `if(!maybe)`, `if(maybe == false)`, `if(maybe != true)` or `if(maybe != false)` when that is needed. 

condition/maybe | true | false | null
-----------|------|------|-----
`if(maybe == true)` | true | false | false
`if(maybe == false)` | false | true | false
`if(maybe != true)` | false | true | true
`if(maybe != false)` | true | true | false
`if(maybe == null)` | false | false | true
`if(maybe != null)` | true | true | false
`if(maybe)` | true | false | false
`if(!maybe)` | false | true | true

**Comment by canton7** [comment]
@spydacarnage The IL doesn't matter - that's an implementation detail. I'm talking at the semantic level. 

You said that `if (maybe)` was definitely shorthand for `if (maybe == true)`, and I countered that this isn't true - it could just as easily be any other expression which has the same output for `bool`, but might have a different output for `bool?`. In fact, `if (thing)` is not defined if `thing` is not a `bool`, to applying it to `bool?` is nonsensical.
