### ISSUE TITLE
Suggestion: Relax CS0748 for lambdas receiving a ref/out parameter

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/csharplang#2863]
This is quite minor, but I'd like to throw it out there for discussion and consideration.

Suppose you have a delegate that receives a parameter by `ref`/`out`:
```cs
public delegate void RefAction<T, TState>(ref T obj, TState state);

// API method:
public void M<TState>(RefAction<Foo, TState> action, TState state);
```
Currently, writing a lambda of this signature requires writing out the *full* parameter list.
```cs
M((ref Foo foo, Bar bar) => { ... }, someBar);
```
It'd be much nicer (and more intuitive) if the `ref` can be applied while still having the parameters implicitly typed:
```cs
// Currently yields 'CS0748: Inconsistent lambda parameter usage; parameter types must be all explicit or all implicit'
M((ref foo, bar) => { ... }, someBar);
```

**Comment by svick** [comment]
This is a duplicate of https://github.com/dotnet/csharplang/issues/338.

**Comment by Joe4evr** [comment]
Okay, this is why such suggestions should list the error number because that's what I searched on before opening. 🙄
