### ISSUE TITLE
Discussion: New Operator/Keyword To Chain Expressions

### ISSUE THREAD

**Issue by ZacharyPatten** [dotnet/csharplang#2864]
I think it would be really cool if C# had an operator or keyword to chain expressions together and resolve to the final expression in the chain. For example:
```csharp
public static T Resolve<T>(Action action, T result)
{
	action();
	return result;
}

// usage example
return File.Exists("hello world.txt")
	? Resolve(() => LoadFile("hello world.txt"), true))
	: false;
```
That works, but it is rather ugly and has to wrap the expression inside a delegate. That could be avoided if a new keyword or operator was added to the language. Example:
```csharp
return File.Exists("hello world.txt")
	? LoadFile("hello world.txt") := true
	: false;
```
Compiles to something like...
```csharp
return File.Exists("hello world.txt")
	? CompilerGeneratedMethod()
	: false;

bool CompilerGeneratedMethod()
{
	LoadFile("hello world.txt");
	return true;
}
```
It should support capture variables like lambdas already do of course.

For the example I used the **:=** operator, but it could be a keyword too. Not sure what a good keyword would be though... **mask** or **resolve** maybe? eh... idk. I'm sure this kind of feature exists in other languages, so someone could provide a better keyword.

Chaining more than 2 expressions together could be compiled to the same method. I don't think each operator/keyword in a chain would need a separate compile-time generated method.

You could do some interesting stuff like:

```csharp
int MyMethod() =>
	DoX() :=
	DoY() :=
	DoZ() :=
	42;
```
Compiles to something like...
```csharp
int MyMethod() =>CompilerGeneratedMethod();

int CompilerGeneratedMethod()
{
	DoX();
	DoY();
	DoZ();
	return 42;
}
```

Which would allow for more functional-style programming in C#.

**EDIT:**
A colon might be a better operator than colon + equal.
```csharp
int MyMethod() =>
	DoX():
	DoY():
	DoZ():
	42;
```

**Comment by ZacharyPatten** [comment]
I think this is related to #377 

Personally, I think a binary operator looks a lot cleaner than parenthesis and semicolons, but I'm not sure if there are things that "sequence expressions" could do that a binary operator could not.

**Comment by Joe4evr** [comment]
Mostly a duplicate of #577.

**Comment by ZacharyPatten** [comment]
@Joe4evr That is a little different because #577 is only described to link "void" return methods. With this chain operator, the expression could resolve to any type (including void), but all those values would be discarded.

**Comment by alrz** [comment]
Indeed, this is a different syntax suggestion for #377

```cs
=> (X(); Y(); Z(); e);
=> X() := Y(): = Z() := e;
```
Beside the fact that this has nothing to do with assignments, your proposal doesn't offer any particular advantages over sequence expresions. I personally prefer block expressions: https://github.com/dotnet/csharplang/issues/2632#issuecomment-538431238

**Comment by ZacharyPatten** [comment]
We definitely have different tastes in syntax. :D There are so many features that already use parentheses and semicolons that I feel adding another feature with them will really hurt the language's readability.

Also, I just want to note that there is no reason it has to be an operator that is two characters long. If there is a one-character operator that would be better than it would actually be less characters than sequence expressions. Example:

```csharp
// sequence expressions #377 
=> (X(); Y(); Z(); e); // spaces
=> (X();Y();Z();e); // no spaces

// colon binary operator
=> X() : Y() : Z() : e; // spaces
=> X() :Y() :Z() :e; // left space
=> X(): Y(): Z(): e; // right space
=> X():Y():Z():e; // no spaces

// colon + equals binary operator
=> X() := Y() := Z() := e; // spaces
=> X() :=Y() :=Z() :=e; // left space
=> X():= Y():= Z():= e; // right space
=> X():=Y():=Z():=e; // no spaces
```

Examples of "a ? b + : c"...
```csharp
// sequence expressions
=> a ? b : (c; d);

// colon binary operator
=> a ? b : (c : d);

// colon + equal binary operator
=> a ? b : (c := d);
```

Examples of method calls to look like functional programming:
```csharp
int MyMethod() =>(
	DoX();
	DoY();
	DoZ();
	42);

// colon binary operator
int MyMethod() =>
	DoX() :
	DoY() :
	DoZ() :
	42;

// colon binary operator (without spaces)
int MyMethod() =>
	DoX():
	DoY():
	DoZ():
	42;

// colon + equal binary operator
int MyMethod() =>
	DoX() :=
	DoY() :=
	DoZ() :=
	42;
```

**Comment by DaZombieKiller** [comment]
This reminds me of #2281, and I think the same suggestion I provided there applies here:
> wouldn't it be far better to have syntax reminiscent of the C/C++ comma operator instead?
> ```cs
>      if (conda) statement1, statement2;
> else if (condb) statement1, statement2, statement3;
> else            statement1;
> ```

So your example would translate to:
```cs
int MyMethod() =>
    DoX(),
    DoY(),
    DoZ(),
    42;
```

**Comment by ZacharyPatten** [comment]
@DaZombieKiller While commas aren't my personal preference, I honestly don't care what operator they choose; I just want the feature. :P I think this is my personal preference list:

1. colon":"
2. colon+equal ":="
3. comma ","
4. hyphen+greaterthan "->"

I just really don't like sequence expressions compared to a binary operator. Especially adding another parentheses feature to the language is ridiculous. There are so many parenthesis features already. If they decide to go with sequence expressions... I hope they at least choose different operators than parentheses.

**Comment by JustNrik** [comment]
What's the advantage of this feature over writting a wrapper like (or a generic TryAction):
```cs
public static bool TryLoadFile(string filePath)
{
    if (!File.Exists(filePath)) return false;
    LoadFile(filePath);
    return true;
}
```
so you can use it like this:
```cs
public bool SomeMethod()
{
    return TryLoadFile("hello world.txt");
}
```
?

Personally, I don't find anything useful in this feature. And if it was about readability, you wouldn't be doing `condition ? true : false` or `condition ? somethingThatReturnsBool() : false` in the first place because it's either unnecessarily redundant or it could be written in a better way like `condition && somethingThatReturnsBool()`

**Comment by ZacharyPatten** [comment]
@JustNrik

Yes you can always refactor code into a method, but I could say the same thing before they added the "a ? b : c" operator to the language, and yet that was still added. Just because code might be refactor-able into a different method design doesn't mean that features like this should be disregarded IMO. Here is an example that (if it was not implemented with "if" statements) would require three extra methods if they did not already exist:

Before Operator:
```csharp
public static Yummy MakeMeASamich()
{
	var wich = GetYoBread();
	wich.Add(HaveButter ?
		GetDatButter() :
		HaveRanch ?
		GetDatRanch() :
		Nothing);
	if (HaveDoritos)
	{
		wich.Add(GetDosDoritoes().CrushDoritos());
	}
	else
	{
		ShedATear();
	}
	if (HaveMeat)
	{
		wich.Add(GetDatMeat());
	}
	else
	{
		YellAtWife();
		WaitForWifeToGetMeat();
		wich.Add(GetDatMeat());
	}
	if (HaveCheese)
	{
		wich.Add(GetDatCheese());
	}
	else
	{
		BreakIntoNeighborHouse();
		FindCheese();
		Run();
		wich.Add(GetDatCheese());
	}
	return wich;
}
```

After Operator:
```csharp
public static Yummy MakeMeASamich()
{
	var wich = GetYoBread();
	wich.Add(HaveButter ?
		GetDatButter() :
		HaveRanch ?
		GetDatRanch() :
		Nothing);
	wich.Add(HaveDoritos ?
		GetDosDoritoes().CrushDoritos() :
		ShedATear() :=
		Nothing);
	wich.Add(HaveMeat ?
		GetDatMeat() :
		YellAtWife() :=
		WaitForWifeToGetMeat() :=
		GetDatMeat());
	wich.Add(HaveCheese ?
		GetDatCheese() :
		BreakIntoNeighborHouse() :=
		FindCheese() :=
		Run() :=
		GetDatCheese());
	return wich;
}
```

**BUT! while writing this example, I realized that this operator would not support declarations, while sequence expressions likely would. I didn't realize that. Example:**

```csharp
// with binary operator
public static Yummy MakeMeASamich() =>
	var wich = GetYoBread() := // <- this won't work
	wich.Add(HaveButter ?
		GetDatButter() :
		HaveRanch ?
		GetDatRanch() :
		Nothing) :=
	wich.Add(HaveDoritos ?
		GetDosDoritoes().CrushDoritos() :
		ShedATear() :=
		Nothing) :=
	wich.Add(HaveMeat ?
		GetDatMeat() :
		YellAtWife() :=
		WaitForWifeToGetMeat() :=
		GetDatMeat()) :=
	wich.Add(HaveCheese ?
		GetDatCheese() :
		BreakIntoNeighborHouse() :=
		FindCheese() :=
		Run() :=
		GetDatCheese()) :=
	wich;

// with sequence expression
public static Yummy MakeMeASamich() => (
	var wich = GetYoBread();
	wich.Add(HaveButter ?
		GetDatButter() :
		HaveRanch ?
		GetDatRanch() :
		Nothing);
	wich.Add(HaveDoritos ?
		GetDosDoritoes().CrushDoritos() :
		(ShedATear();
		Nothing));
	wich.Add(HaveMeat ?
		GetDatMeat() :
		(YellAtWife();
		WaitForWifeToGetMeat();
		GetDatMeat()));
	wich.Add(HaveCheese ?
		GetDatCheese() :
		(BreakIntoNeighborHouse();
		FindCheese();
		Run();
		GetDatCheese()));
	wich);
```

So... sequence expressions are better and would help with more situations.

**Comment by ZacharyPatten** [comment]
As I no longer agree with this issue (I prefer sequence expressions #377) I am closing this issue...
