### ISSUE TITLE
out and ref parameters in xml doc string cref in specification differ from roslyn implementation

### ISSUE THREAD

**Issue by dlech** [dotnet/csharplang#2865]
According to <https://github.com/dotnet/csharplang/blob/master/spec/documentation-comments.md#id-string-format>...

> Arguments having the out or ref modifier have an @ following their type name. Arguments passed by value or via params have no special notation.

However Microsoft.CodeAnalysis 3.3.1 gives a warning. Instead it accepts the syntax "out <type>".

Example:

```C#
using System;

/// <summary>
/// <see cref="M()"/>
/// <see cref="M(string,out string)"/> <!-- no warning -->
/// <see cref="M(string,string@)"/> <!-- warning -->
/// </summary>
public class C {
    public C() {
    }
    
    public void M() {
    }
    
    public void M(string a, out string b) {
        b = default;
    }
}
```

Is the spec incorrect or is there a bug in the compiler?

**Comment by Joe4evr** [comment]
I think that spec refers to how the *actual* XML documentation file is encoded, not how you write XML docs in your code.

**Comment by dlech** [comment]
Ah, that makes sense. Thanks.
