### ISSUE TITLE
Allow switch expression to return dynamic

### ISSUE THREAD

**Issue by saeed-badar** [dotnet/csharplang#2868]
New switch expressions are fantastic in C# 8. However, it would be nice to have the capability of switch expression to evaluate as dynamic.

e.g,

```
dynamic result = something switch
{
 "a" => new object1(),
 "b" => new object2()
}
```

**Comment by svick** [comment]
[That code compiles fine for me.](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMACAwgWAFADe+GJGKALBgLIAUKAjAAwYDOA9gLYTAAWMAdgHMAlMVJE8pKRgAmCfgEMOMAMYYoEFgFcANsAwBeVp258hrAO4xgKnmOkYJDhwCIFLwwD4M/CBYxsAEYAVhAqwPQ0wgA09s4kLoEeBt6+/kGh4WhRcVIAvgDccXn4JXj46AEhYRGOZZUZNZgEeUA=)

**Comment by saeed-badar** [comment]
Apparently a problem in sharplab. [Please check on dotnetfiddle.](https://dotnetfiddle.net/2RWsLT)

**Comment by HaloFour** [comment]
Sounds like a problem with dotnetfiddle, works fine in Visual Studio:

![image](https://user-images.githubusercontent.com/10102290/66269882-d95ca800-e81b-11e9-8813-638f87ee8d99.png)

**Comment by saeed-badar** [comment]
Am I missing something?

![image](https://user-images.githubusercontent.com/53142106/66270024-daafc400-e85f-11e9-9543-515b68334de2.png)

**Comment by YairHalberstadt** [comment]
@saeed-badar

What is your version of visual studio? What Language version are you on.

**Comment by saeed-badar** [comment]
VS 2019, 16.2.5.
<LangVersion>8.0</LangVersion>

**Comment by svick** [comment]
@saeed-badar VS 16.2 only contains a preview version of C# 8.0. You should upgrade to 16.3 if you want to use C# 8.0.

**Comment by YairHalberstadt** [comment]
@saeed-badar.

C# 8 is only officially supported on VS 16.3

Try upgrading

**Comment by saeed-badar** [comment]
My mistake... thought I had the latest version.
