### ISSUE TITLE
nullability of value parameter in properties

### ISSUE THREAD

**Issue by dlech** [dotnet/csharplang#2870]
**Version Used**: master (23 September 2019) via https://sharplab.io

**Steps to Reproduce**:

```C#
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

public class C {
    string? Getter() {
        return null;
    }
    
    void Setter(string s) {
    }
    
    [DisallowNull]
    public string? Property {
        get => Getter();
        set => Setter(value); // get unexpected warning here
    }
    
    public void Test() {
        Property = ""; // no warning here as expected
        Property = null; // get warning here as expected
        Setter(Property); // get warning here as expected
    }
}
```

**Expected Behavior**: Given a property with the `DisallowNull` attribute it should mean that the return value can be null but `value` parameter of the setter cannot be null.

**Actual Behavior**: The code analysis gets this right when assigning to a property, but not in the property declaration.

**Comment by agocke** [comment]
Moving to csharplang because this is by-design for the compiler
