### ISSUE TITLE
C# Proposal: Simple way to call constructor?

### ISSUE THREAD

**Issue by DusanPaulovic** [dotnet/csharplang#2874]
Hi there, maybe it would be useful to have a way to call default constructor of the class during the initialization process. 
Now we must do this:

`private readonly ClassWithLongName<GenericArg1, GenericArg2> _fieldName = new ClassWithLongName<GenericArg1, GenericArg2>();`

I would like to short it to:
`private readonly MySuperClassWithLongName<GenericArg1, GenericArg2> _superClass = new();`

And with args:
`= new(arg1, arg2)`

**Comment by HaloFour** [comment]
https://github.com/dotnet/csharplang/issues/100

**Comment by DusanPaulovic** [comment]
OK, already exists.
