### ISSUE TITLE
the new syntax, using class

### ISSUE THREAD

**Issue by ChanyaKushima** [dotnet/csharplang#2875]
# The First
I often write the code like below.
For example:
~~~
using Math=System.Math;
~~~
However, `Math` is used twice in this. This is bad code.
So I thought the solution.
It is new syntax, `using class`.
# New Syntax
Example:
~~~
using class System.Math;
~~~
This mean `using Math=System.Math`. So another class in `System` namespace can't be used.
No need to write `Math` twice.

**Comment by CyrusNajmabadi** [comment]
> However, Math is used twice in this. This is bad code.

What is bad about this?

**Comment by theunrepentantgeek** [comment]
What about
```
using static System.Math;
```
?

Which has been around since C# 6.

**Comment by ChanyaKushima** [comment]
@CyrusNajmabadi 
If A in `using A=B.A;` have a long name, you might make a mistake. This A is necessary to reduce the mistake.

**Comment by CyrusNajmabadi** [comment]
> If A in using A=B.A; have a long name, you might make a mistake. This syntax is necessary to reduce the mistake.

What "mistake"?  The purpose of a using alias is to allow you to bring in a type with a different name.  That's the reason why it exists :)

So i can do this:

```c#
using Math1 = System.Math;
using Math2 = AnotherLib.Math;

...

Math2.Sin(...);
```

**Comment by ChanyaKushima** [comment]
@theunrepentantgeek 
I think `using static` is very useful, but it can't be written like below.
~~~
using static System.Math;
class Foo{
    void M(){
        Math.Sin(1);   // NG
        Sin(1);            // OK
    }
}
~~~
So, it is difficult to determine if a method in Foo or Math. As `using static` increases, it becomes more difficult it.
And, `using static` can't be used as variable type.

**Comment by HaloFour** [comment]
You get to choose the alias with `using`, so choose a shorter alias.  The fact that you can choose the class name as the alias is not a fault of the existing syntax.  I seriously doubt many people find themselves aliasing a class by the same name.

**Comment by ChanyaKushima** [comment]
@CyrusNajmabadi 
this syntax show effect if you want alias to have the same name.

**Comment by CyrusNajmabadi** [comment]
> this syntax show effect if you want alias to have the same name.

I'm not seeing the value there :-/

if you want to reference the actual symbol, by its actual name, you can do so with:

```c#
using System;

...

Math.Whatever(...);
```

That works well and has been supported since forever.  Likely 99.99% of all C# code does this.

**Comment by huoyaoyuan** [comment]
I guess you want something like `using std::string` in C++. But organization of standard library in C# is very different from C++.
In C++, **nearly everything** from STL are under the `std` namespace, and many global functions directly under namespace, making `using namespace std` a very bad practice. And `usings` in `.h` files will be transitive to other files, making things even worse.
Comparing to C#, most classes are under sub-namespaces of `System`, and everything are inside a class, so `using System` is a good practice. It won't import plenty of symbols into scope, neither polluting other files.

**Comment by DavidArno** [comment]
You state,
> I often write the code like below.
For example:
`using Math=System.Math;`

The obvious question here is "why?" What do you achieve by writing this that isn't achieved with a simple `using System;` statement?

**Comment by YairHalberstadt** [comment]
>  I seriously doubt many people find themselves aliasing a class by the same name.

I do this when bringing two namespaces into scope which contain a class with the same name, and I want to only use one of the classes.

This isn't frequent enough to warrant language support though.
