### ISSUE TITLE
Feature request: simple fixed statement

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/csharplang#2876]
Allow this:
```cs
fixed (int* p = &pt.x)
{
    *p = 1;
}
```

to be simplified into:
```cs
fixed int* p = &pt.x;
*p = 1;
```

just like how "simple `using`" statement works. The variables will be unpinned at the end of containing scope.

### Pinning multiple variables
```cs
fixed (int* p1 = &point.x)
{
    fixed (double* p2 = &arr[5])
    {
        // Do something with p1 and p2.
    }
}
```

can be simplified into:
```cs
fixed int* p1 = &point.x;
fixed double* p2 = &arr[5];
// Do something with p1 and p2.
```

### Pinning multiple variables of same type
```cs
fixed (byte* ps = srcarray, pd = dstarray)
{
    // Do something with ps and pd.
}
```

can be simplified into:
```cs
fixed byte* ps = srcarray, pd = dstarray;
// Do something with ps and pd.
```

**Comment by DaZombieKiller** [comment]
I think it'd be great if this could be used as an expression, as well

**Comment by huoyaoyuan** [comment]
Mentioned in #2451.

**Comment by ronnygunawan** [comment]
@DaZombieKiller can you provide an example of what you are proposing?

**Comment by DaZombieKiller** [comment]
> 
> 
> @DaZombieKiller can you provide an example of what you are proposing?

Something along the lines of
```cs
DoSomethingWithPointer(fixed &value);
```

**Comment by tannergooding** [comment]
Dupe of https://github.com/dotnet/csharplang/issues/2186

**Comment by ronnygunawan** [comment]
This issue is a duplicate of #2186 
I'm closing this issue.
