### ISSUE TITLE
Spread operator like in es6

### ISSUE THREAD

**Issue by damian2** [dotnet/csharplang#2879]
class Foo 
    {
       string MyStringProp {get;set;}
       int MyIntProp {get;set;}
    }

    class Bar 
    {
       string MyStringProp {get;set;}
       int MyIntProp {get;set;}
       int MyOtherIntProp {get;set;}
    }

    var foo = new Foo
    {
        MyStringProp = "test1",
        MyIntProp = 5
    };

before:

    var bar = new Bar
    {
        MyStringProp = foo.MyStringProp,
        MyIntProp = foo.MyIntProp,
        MyOtherIntProp = 4
    };
after:

    var bar = new Bar
    {
        ...foo,
        MyOtherIntProp = 4
    };

**Comment by ronnygunawan** [comment]
You'll be able to do this with the proposed [records](https://github.com/dotnet/csharplang/blob/master/proposals/records.md):

```cs
var bar = foo with { MyOtherIntProp = 4 };
```

**Comment by HaloFour** [comment]
I don't think "withers" covers anonymous classes or composing instances of new types from instances of other types.

**Comment by bbarry** [comment]
I don't like how this leaves the order which the properties are evaluated up to the version of the compiler.

Supposing you have this code:

    class Foo 
    {
      string _s;
      int _i;
      public string S 
      {
        get
        {
          Console.WriteLine("Foo.S_get");
          return _s;
        }
        set 
        {
          Console.WriteLine("Foo.S_set");
          _s = value;
        }
      }
      public int I
      {
        get
        {
          Console.WriteLine("Foo.I_get");
          return _s;
        }
        set 
        {
          Console.WriteLine("Foo.I_set");
          _s = value;
        }
      }
    }

    class Bar 
    {
      int _i;
      string _s;
      public int I
      {
        get
        {
          Console.WriteLine("Bar.I_get");
          return _s;
        }
        set 
        {
          Console.WriteLine("Bar.I_set");
          _s = value;
        }
      }
      public string S 
      {
        get
        {
          Console.WriteLine("Bar.S_get");
          return _s;
        }
        set 
        {
          Console.WriteLine("Bar.S_set");
          _s = value;
        }
      }
      public int Baz { get; set; }
    }


Given this code, what order do the console writes happen?

    var bar = new Bar
    {
      ...foo,
      Baz= 4
    };

**Comment by spydacarnage** [comment]
The pedantic answer is that none of them run because the code won't compile
(you're setting and returning _s in your int I property.

However, assuming that's not what you meant, I would assume the compiler
would be written to use _an_ order, but that would probably be alphabetical.

**Comment by theunrepentantgeek** [comment]
I don't know what effect this operator has on JavaScript developers, but (on first inspection) it would seem to introduce a very fragile form of tight coupling between classes.

``` csharp
var bar = new Bar
{
    MyStringProp = foo.MyStringProp,
    MyIntProp = foo.MyIntProp,
    MyOtherIntProp = 4
};
```
With the above code, any renaming of the properties of `foo` will result in code that still does exactly what is intended - two properties from `foo` will be copied across to `bar`.

``` csharp
var bar = new Bar
{
    ...foo,
    MyOtherIntProp = 4
};
```

On the other hand, the link between `foo` and `bar` here is far more tenuous.

Renaming either `MyStringProp` or `MyIntProp` from `foo` would *silently* result in the value not being copied across. No warning, no error, just missing data. 

Even worse, an innocent enhancement of foo - a new property on `foo` that *accidentally* matched an existing property on `bar` would result in unexpected behaviour. Either the value would be silently copied across (if they're type compatible) or you'd get a compiler error (if they weren't).

To me, this behaviour is inconsistent with the strongly typed nature of the C# language.

**Comment by damian2** [comment]
You would have the same problem using AutoMapper, but I think most of the programmers using it.

**Comment by ronnygunawan** [comment]
> Renaming either `MyStringProp` or `MyIntProp` from `foo` would _silently_ result in the value not being copied across. No warning, no error, just missing data.

I think a proper implementation would not allow spread receiver to not have all spread object's properties.

**Comment by Vlad-Stryapko** [comment]
> You would have the same problem using AutoMapper, but I think most of the programmers using it.

I've worked with dozens of projects with AutoMapper and I can assure you debugging and reasoning about the code with implicit effects is not a pleasurable experience. 

IMO it's better to write a bit more but be able to easily see which property is used and which is not. I'm strongly against implicit assignments and mappings just because one has to spend one more minute to explicitly write them down.

**Comment by jzabroski** [comment]
@ronnygunawan I think you're missing the motivation for the syntactic sugar.

@damian2 I think the motivation for this operator is poor. The saying goes, "Amateurs imitate, professionals steal."; the **true motivation** for this operator is best given in the dart language GitHub, [introduced in Dart 2.3](https://medium.com/flutter-community/whats-new-in-dart-2-3-1a7050e2408d): 

> 1. The `Spread` operator (`…`)
> Consider the following List of Text Widgets:
>
> ```dart
> List<Widget> northAmericanCountries = [
>   Text('USA'),
>   Text('Canada')
> ];
>
> List<Widget> asianCountries = [
>   Text('India'),
>   Text('China')
> ];
>
> List<Widget> europeanCountries = [
>   Text('France'),
>   Text('Germany'),
>   Text('Italy')
> ];
> ```
>
> If we were to add all of these to a `Row` Widget, normally, we’d be doing something like this:
>
> The problem with this is that if you wanted to add `asianCountries` first and then add `northAmericanCountries`, you’d have to include `asianCountries` first in the `Row` like so:
>
> ```dart
> Row(
>   children: asianCountries
>             ..addAll(northAmericanCountries)
>             ..addAll(europeanCountries),
> )
> ```
> This requires you to re-order the `addAll` methods to your lists, which isn’t exactly convenient or ideal.
>
> Enter, the new `Spread` operator! With the `Spread` operator, you can achieve the above result easily:
> 
> ```dart
> Row(
>      children: [
>                ...northAmericanCountries
>                ...asianCountries
>                ...europeanCountries
>                ]
> )
> ```
> And this can be easily re-ordered like so:
>
> ```dart
> Row(
>      children: [
>                ...asianCountries
>                ...northAmericanCountries
>                ...europeanCountries
>                ]
> )
> ```

**Comment by IlBaffo** [comment]
> I've worked with dozens of projects with AutoMapper and I can assure you debugging and reasoning about the code with implicit effects is not a pleasurable experience.
> 
> IMO it's better to write a bit more but be able to easily see which property is used and which is not. I'm strongly against implicit assignments and mappings just because one has to spend one more minute to explicitly write them down.

I'm with you on that but, in my case, is not about "one minute" because, especially in LOB applications I end up with a lot of EntityFramework `Select`s wich can't be DRYed out because they have to be translated to SQL and there are a lot of properties.
What happens is that I have an Order object with some navigation properties maybe two or three levels deep with 20/30 properties and that tends to grow a lot.

Now imagine that you'd like to add a property with the value from the current "request" and you have to inject it with some AutoMapper's wodoo.

What I dislike the most, apart from writing a lot, is that this has to be done via reflection wasting resources for something that is known at compile time.

But yes, I think that it can be fragile and needs to be well thougth and limited to specific use-cases.
