### ISSUE TITLE
Cannot assign `default` to [MaybeNull]

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#2880]
I find this behavior somewhat unintuitive. 
```cs
#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
public class C { 
    [return: MaybeNull]
    public T M<T>() {
        return default; // warns - why this need null suppression?
    }
}
```
We already specified the return type as MaybeNull, so presumably, `default` should be fine.

**Comment by sharwell** [comment]
Related to dotnet/roslyn#30953

**Comment by ufcpp** [comment]
https://github.com/dotnet/roslyn/issues/36039

**Comment by alrz** [comment]
Thanks for the links.

This particular case was called out in https://github.com/dotnet/roslyn/issues/30953#issuecomment-509334985


>Our current plan is for nullability attributes like `[return: MaybeNull]` not to affect method bodies. So `return default;` would still warn for now. We will look at refining this post C# 8 RTM.
