### ISSUE TITLE
Allow the constant pattern to declare a variable

### ISSUE THREAD

**Issue by reflectronic** [dotnet/csharplang#2885]
Currently a constant pattern is not allowed to declare a variable with the matched result. While this makes sense when testing if the pattern *matched* — you already specified on which value the pattern would match — it becomes more annoying when you are testing if the pattern *didn't match.* 

Currently you can work around this by using the `var` pattern as such:
```cs
// compiles today
if (ComputeValue() is var index && index is 10)
{
	 Console.WriteLine("Index is 10");
}
else
{
	Console.WriteLine($"Index is not 10; Index is {index}");
}
```

However, this seems like an abuse of pattern matching, and becomes even more obscured with more complicated patterns. I propose that the above example look more like:
```cs
if (ComputeValue() is 10 index)
{
	Console.WriteLine("Index is 10");
}
else
{
	Console.WriteLine($"Index is not 10; Index is {index}");
}
```

**Comment by CyrusNajmabadi** [comment]
I believe 'and' patterns will address this.  i.e. you can say:

`ComputeValue() is var index and not 10` or
`ComputeValue() is not 10 and var index`.

So i'm not really in support of this request.

**Comment by HaloFour** [comment]
@reflectronic 

> ```cs
> if (ComputeValue() is not 10 index)`
> ```

What type is `index` here?  What if `ComputeValue()` returns `object`?

**Comment by reflectronic** [comment]
> What type is index here? What if ComputeValue() returns object?

Those questions need to be resolved for `not` patterns in general; the same could be asked for `if (ComputeValue() is not string str)` (which would probably not be allowed)

> I believe 'and' patterns will address this

That's fair, although I think it is clearer to not have to use `and` patterns to work around it & also more consistent with other types of patterns

**Comment by YairHalberstadt** [comment]
What you're really asking here is for the ability to declare variables with not patterns.

I think the main issue with this is that it's not clear what the following means:

`x is not int y`

Does it mean:

`x is (not (int y))`

Or:

`x is ((not int) y)`

The first interpretation would be useful if you did the following:

```csharp
if (x is not int y)
{}
else
{ // y is definitely assigned here and can be used }
```

You require it to mean the second interpretation.

However this is inconsistent with `and` patterns. For example:

```csharp
if (x is IFoo y and IBar z) // both y and z are definitely assigned here;
```
We don't interpret `x is IFoo and IBar y` as `x is ((IFoo and IBar) y)`. Neither will this be possible in nice way unless we have intersection and union types.

**Comment by reflectronic** [comment]
> What you're really asking here is for the ability to declare variables with not patterns.

I mean, I think it should work without using the `not` pattern as well. I wrote code using  the workaround (ignoring the bit with the `not` pattern) and it works completely fine today. This is just to get rid of having to use the `var` pattern as a clever workaround.

**Comment by CyrusNajmabadi** [comment]
i agree with the concern about ambiguity.  If every pattern can end with a name, you fundamentally make it confusing as to what `not pat name` means.  is is `not (pat name)` or is it `(not (pat) name)`. 

Furthermore, if htey can all have names, you could effectively have `not (pat name1) name2` which is just really really confusing :)

I would far prefer to make it very *narrow* as to which patterns can introduce names.  either the  `Type ..extra.. name` pattern or the `var name` pattern (which is like a simple form of the Type-Name pattern).

**Comment by HaloFour** [comment]
Using a guard is not a workaround.  There are always going to be limitations as to what can be expressed conditionally with patterns.  The ability to extract values and perform further comparisons is pretty idiomatic in a lot of languages that have pattern matching.

**Comment by reflectronic** [comment]
> If every pattern can end with a name, you fundamentally make it confusing as to what `not pat name` means. 

That’s an issue with the proposal for `not` patterns. Maybe adding variable declarations for more patterns exacerbates the issue, but whatever solution is chosen for other patterns will work for this one. You don’t have to use this with `not` patterns.

> The ability to extract values and perform further comparisons is pretty idiomatic in a lot of languages that have pattern matching.

Right, which this proposal facilitates.

**Comment by DanFTRX** [comment]
@reflectronic Perhaps update your proposal with an example that isn't a not pattern just to clear up the confusion.

**Comment by reflectronic** [comment]
Sure.

**Comment by setbbtjl8wwq** [comment]
@reflectronic 
As alternative for your case currently works fine
```cs
if (ComputeValue().To(out var index) is 10)
{
	Console.WriteLine("Index is 10");
}
else
{
	Console.WriteLine($"Index is not 10; Index is {index}");
}
```
where
```cs
// public static T To<T>(this T o, out T x) => x = o;

/* optimized for value types */
public static ref T To<T>(this T o, out T x) { x = o; return ref x; }
```

**Comment by yaakov-h** [comment]
@setbbtjl8wwq the OP already has an alternative, further alternatives are not the subject of this discussion.

Please refrain from pushing your extension methods everywhere, you’ve been banned for the same before.

**Comment by YairHalberstadt** [comment]
> ```csharp
> if (ComputeValue() is 10 index)
> {
> 	Console.WriteLine("Index is 10");
> }
> else
> {
> 	Console.WriteLine($"Index is not 10; Index is {index}");
> }
> ```

This is inconsistent with how pattern matching works. The variable declared by a pattern is only definitely assigned where the pattern matches. For example:

```csharp
if (ComputeValue() is int index)
{
    //index is definitely assigned here and can be used
}
else
{
	// index in not definitely assigned here and can't be used
}
```

**Comment by reflectronic** [comment]
> This is inconsistent with how pattern matching works.

Yeah, I realized that a while afterwards. I was hoping that maybe there would be cases that the definite assignment could flow through like the `var` pattern, but that is separate work & would be beneficial for all patterns (e.g. for `if (StringReturningMethod() is { Length: 5 } m)`, `m` would ideally be available in both branches). 

I also talked about the issue with Cyrus a little bit. One of his concerns is that doing this would introduce grammatical ambiguity; i.e. today an expression of the form `object is X.Y z` always represents, syntactically, a type pattern, but adding this feature would necessitate disambiguating that expression later in binding, which is something they specifically tried to not do with patterns.
 
So yeah, this proposal is stuck in a state of flux & using the `var` pattern is, frankly, fine, especially with `and` combinators.

**Comment by setbbtjl8wwq** [comment]
@yaakov-h 

> the OP already has an alternative, further alternatives are not the subject of this discussion.
> Please refrain from pushing your extension methods everywhere, you’ve been banned for the same before.

The original message has been addressed to @reflectronic , because he may doesn't know about this pattern. Sure, it is normal to suggest alternatively solutions for proposals.

This solution have pushed only for valid cases, if you feel that there are so many cases, possible that C# designers missed something useful.

**Comment by Richiban** [comment]
@reflectronic 

In your original example, you have:

```csharp
if (ComputeValue() is 10 index)
{
	Console.WriteLine("Index is 10");
}
else
{
	Console.WriteLine($"Index is not 10; Index is {index}");
}
```

But there's something I'm not following: why do you want `index` to be in scope for the true branch? You've matched it against a constant, therefore you know its value and having a variable for it is pretty useless.

If you want to match against a constant and then introduce a variable for it in the `else` branch, you'd be much better off using a switch statement:

```csharp
switch (ComputeValue())
{
	case 10:
		Console.WriteLine("Index is 10");
		break;
	case var index:
		Console.WriteLine($"Index is not 10; Index is {index}");
		break;
}
```

or, better yet, a switch expression:

```csharp
Console.WriteLine(
	ComputeValue() switch {
		10 => "Index is 10",
		var index => $"Index is not 10; Index is {index}"
	}
);
```

**Comment by gafter** [comment]
However, this seems like an abuse of pattern matching, and becomes even more obscured with more complicated patterns. I propose that the above example look more like:
```csharp
if (ComputeValue() is 10 index)
{
	Console.WriteLine("Index is 10");
}
else
{
	Console.WriteLine($"Index is not 10; Index is {index}");
}
```

Pattern variables are only definitely assigned when the pattern matches.  So even if we permit this, `index` is not definitely assigned in the else clause.  Under no circumstances would `index` be definitely assigned and have any value other than `10`.

**Comment by reflectronic** [comment]
Right.
