### ISSUE TITLE
Compiler Bug: Infinite loop in RELEASE after upgrade to C#8.0 Compiler

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#2886]
Hi All,
Please see the example below which functions correctly in release mode with the C# 7.3 compiler but does not work correctly when compiled with the C# 8.0 compiler.

Expected Results:
"DONE!" is displayed

Actual Results:
In Debug: "DONE" is displayed
In Release: Infinite loop

Stepping through the code, it seems as if the value of ````Creating```` is cached inside of the While loop and never re-evaluated.

````
using System;
using System.Threading;

namespace ConsoleApp37 {
    class Program {
        static void Main(string[] args) {
            var C = new ThreadedObject<Object>(() => new object());

            Console.WriteLine("DONE!");

        }


        public class ThreadedObject<T> {
            public T Object { get; private set; }
            public Thread Thread { get; private set; }

            public ThreadedObject(Func<T> Creator) {
                var Creating = true;

                Thread = ThreadInvoke(() => {
                    Object = Creator();
                    Creating = false;
                });


                while (Creating) {
                    //Do nothing.  Wait for Creating to be true
                }

            }

            private static Thread ThreadInvoke(Action A, ApartmentState ApartmentState = ApartmentState.STA) {

                var T = new System.Threading.Thread(() => {
                    A();
                });
                T.SetApartmentState(ApartmentState);
                T.Start();

                return T;
            }

        }

    }

}
````

**Comment by CyrusNajmabadi** [comment]
> Please see the example below which functions correctly in release mode with the C# 7.3 compiler but does not work correctly when compiled with the C# 8.0 compiler.

Is there a difference in IL here?  Are you running on the same runtime?

**Comment by TonyValenti** [comment]
@CyrusNajmabadi - 
I am not technically saavy enough to know how to compare IL, however, we have an app that is running in production on .NET 4.7/4.8 compiled with the C#7.3 compile that came with VS 16.2 and the code above functions as expected in release mode.

The code above does not function correctly in release mode for .NET 4.8 or .NET Core 3.0.

**Comment by yaakov-h** [comment]
Isn't this an issue for dotnet/roslyn?

**Comment by canton7** [comment]
In my (somewhat limited) understanding, I don't think there's anything unexpected here?

You're writing to a variable in one thread, while reading from it in another. There's no explicit synchronization, and I don't see [any constructs](https://stackoverflow.com/questions/6581848/memory-barrier-generators) which would introduce a memory barrier. Therefore my understanding is that the runtime is well within its rights to give you an infinite loop?

**Comment by YairHalberstadt** [comment]
> I'd argue that the compiler here is missing an opportunity to generate better code (whether inlining locals like this is a good thing and worth the complexity it adds to the compiler might be debatable) and that in this particular case it could even identify that code following the loop is unreachable (because it would predictably optimize away the local).

Roslyn is not an optimising compiler. It tries to find the most efficient IL to represent the C# program directly, but it is does not attempt more involved optimisations.

I implemented the optimisation where it combines the two display classes for the closure. This was done since the implementation of closures is completely unspecified by the specification (just their semantics), and it is an optimisation out of reach of the JIT (since the JIT can't combine classes into one).
