### ISSUE TITLE
Add DoesNotReturnIfNull nullable annotation

### ISSUE THREAD

**Issue by bbartels** [dotnet/csharplang#2887]
This would be very useful for Unit Test frameworks, as methods such as Assert.NotNull would have no way of telling the compiler that the passed object will not be null if the method terminates properly.

xUnit related issue here: https://github.com/xunit/xunit/issues/2011#

```csharp
var obj = new object();
Assert.NotNull(obj);
Assert.NotEqual(string.Empty, obj.ToString()); // CS8602 Dereference of a possibly null reference
```

**Comment by yaakov-h** [comment]
`[EnsuresNotNull]`?

**Comment by YairHalberstadt** [comment]
@yaakov-h

That would be inconsistent with `DoesNotReturnIf` attribute.

**Comment by yaakov-h** [comment]
Hmm, I thought that already existed, I must have remembered it from an earlier beta.

But `[NotNull]` does seem to have [the desired effect](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4GIB2BXANlghgIywgAII0CiBYAKBoAEAmARnoAZi6mA6AERlwDmaAPYBnYDADGorgGFhAEwgBBclgSiYogNw16AZg5MAbBwbFZNAN57qxex0OdTdACzEAsrhhoAFJ1YAbQBdYlwoAVEAShoHYhs7OIdhfAArCElgAH5iYWIAXmJMHF1EpOJlUVFoYC4AOWFgOuwsX2Eo0vL7YS4AFWEAZWBYNAFfDtiHAF8aGdpqOicTMwqqmutJ+0WjF3cGppbfQP3mnFCU9Myc9s3427j4YjbiLSKWqOJgAAsoYQB3IoQAEASTQYFwWBgCgA8gAHaC4CTCNAAUQAHpIILCkX4AETA4DEP64URvHAAQlxEzKxDmcyAA===), and the same as I remember from EnsuresNotNull.

**Comment by bbartels** [comment]
I must have forgotten to add '?' to the method parameter when I double checked the claims made. If the method accepts a nullable object it compiles without warnings.
I guess the attribute could have been named something more descriptive (similar to DoesNotReturnIf), but does actually behave in the desired way!
