### ISSUE TITLE
"break if" and "continue if"

### ISSUE THREAD

**Issue by mattiasnordqvist** [dotnet/csharplang#2888]
Consider
```
foreach(...) 
{
    ...
    if (x >= w) break;
    ...
}
```
It is "hard" to read and it kind of breaks some peoples code conventions regarding required curly brackets. Inserting the brackets and it is suddenly four lines of code to break out of the loop.

I'd like to write this instead.
```
foreach(...) 
{
    ...
    break if (x >= w);
    ...
}
```
It's more readable and there are no missing curly brackets (because there's no room for any at all)

This could look the same with `continue` as well.

**Comment by HaloFour** [comment]
IMO the condition is the more important part of the statement and it makes more sense for it to appear first.  Beyond that it introduces redundant syntax with no benefit other than to work around the overzealous application of a particular coding style.

**Comment by HaloFour** [comment]
Here's another similar proposal:

https://github.com/dotnet/csharplang/issues/724

**Comment by Scott-Caldwell** [comment]
I don't think it makes sense to design the language around people's/companies' arbitrary style requirements. It will likely be *significantly* easier, cheaper, and quicker to convince your company to allow you to use `if` statements without braces than it will be to change the language.

In general, I'm not in favor of adding language features that introduce *slightly different* syntax for existing features. Especially in cases like this, where it's just rearranging the words. It just complicates the language and code bases without much appreciable benefit.

**Comment by mattiasnordqvist** [comment]
Ok ok I see your point.  Let's forget about it. :)
