### ISSUE TITLE
The null-forgiving operator spec is either incomplete or inconsistent with implementation

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/csharplang#2892]
From [spec](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/nullable-reference-types-specification.md):

> The null-forgiving operator
The post-fix ! operator is called the null-forgiving operator.
>
>primary_expression
    : ...
    | null_forgiving_expression
    ;
>    
>null_forgiving_expression
    : primary_expression '!'
    ;
>The primary_expression must be of a reference type.
>
>The postfix ! operator has no runtime effect - it evaluates to the result of the underlying expression. Its only role is to change the null state of the expression, and to limit warnings given on its use.

But I just found out that the operator is also used to suppress warnings about receiver nullability mismatch:

```cs
List<string?> list = new List<string?>();

List<string> list1 = list.Where(x => x != null).ToList(); // warning CS8619
List<string> list2 = list.Where(x => x != null).ToList<string>(); // warning CS8620
List<string> list3 = list.Where(x => x != null).ToList()!; // no warning. CS8619 is suppressed.
List<string> list4 = list.Where(x => x != null)!.ToList<string>(); // no warning. CS8620 is suppressed.
```

**Comment by yaakov-h** [comment]
> the operator is also used to suppress warnings

Is this not what the spec defines as "to limit warnings given on its use"?

**Comment by 333fred** [comment]
> Is this not what the spec defines as "to limit warnings given on its use"?

Yes, this is correct as written.
