### ISSUE TITLE
Proposal: Arithmetic and Bitwise operators for (U)Int16 and (S)Byte

### ISSUE THREAD

**Issue by MineCake147E** [dotnet/csharplang#2895]
The C# language forces users to cast (U)Int16 and (S)Byte to (U)Int32 and divide, like:  
```csharp
public static ushort Div(ushort value) => (ushort)(value / 19u);
```
We can rewrite it without casts like:
```csharp
public static ushort Div2(ushort value)
{
    value /= 19;
    return value;
}
```
But, even if we use `/=` operator , the RyuJIT compiles it into the assembly like:
```asm
    L0000: movzx edx, cx
    L0003: mov ecx, 0x6bca1af3
    L0008: mov eax, ecx
    L000a: imul edx
    L000c: mov eax, edx
    L000e: shr eax, 0x1f
    L0011: sar edx, 0x3
    L0014: add eax, edx
    L0016: movzx ecx, ax
    L0019: mov eax, ecx
    L001b: ret
```
which casts into `int` first, and divides.
C++ allows us to directly divide `unsigned short`. So, I suggest adding supports for Arithmetic and Bitwise operations for `ushort`, `short`, `byte`, and `sbyte`.

**Comment by HaloFour** [comment]
I'd recommend opening an issue on [CoreCLR](https://github.com/dotnet/coreclr) to look into optimizing the JIT.  C# can only work with the IL opcodes provided and `div` and I don't see how the compiler can emit better IL in this case.

**Comment by MineCake147E** [comment]
Thank you for your instant reply and advice.  
I will reconsider it and re-post on the [CoreCLR](https://github.com/dotnet/coreclr/).  

By the way, the C# still disallows us to directly divide the `ushort` value by `ushort` value.  
Is there any idea about it?

**Comment by HaloFour** [comment]
@MineCake147E 

> By the way, the C# still disallows us to directly divide the `ushort` value by `ushort` value.
Is there any idea about it?

I think it's due to the `div` IL opcode always pushing a 32-bit integer onto the evaluation stack when dividing integers.  The same problem manifests with `short`.

**Comment by MineCake147E** [comment]
Oops, there are some issues about IL remaining.
Closing.

**Comment by KalleOlaviNiemitalo** [comment]
It seems you did not open an issue on CoreCLR yet, so I am replying here.

> ```assembly
>     L0000: movzx edx, cx
>     L0003: mov ecx, 0x6bca1af3
>     L0008: mov eax, ecx
>     L000a: imul edx
>     L000c: mov eax, edx
>     L000e: shr eax, 0x1f
>     L0011: sar edx, 0x3
>     L0014: add eax, edx
>     L0016: movzx ecx, ax
>     L0019: mov eax, ecx
>     L001b: ret
> ```

I guess you'd want something like this instead (i386):

```assembly
    L0000: movzx eax, cx
    L0003: inc eax
    L0004: imul eax, eax, 0x35e5 ; result <= 0x35e50000, fits in eax
    L000a: shr eax, 0x12
    L000c: ret
```

That would be shorter but I did not measure whether it is actually faster.

Correctness tested with:

```perl
use integer;
foreach my $input (0..0xffff) {
    my $correct = $input / 19;
    my $guess = (($input + 1) * 0x35e5) / 0x40000;
    die "$input: $guess != $correct" unless $guess == $correct;
}
```
