### ISSUE TITLE
C# Proposal: Omit enum type for switch (expressions) when obvious

### ISSUE THREAD

**Issue by Joelius300** [dotnet/csharplang#2897]
Let's say you have an enum:
```
enum Direction 
{
    Up, Down, Left, Right
}
```

If you want to use this enum in a switch expression (or a switch statement), you always have to fully qualify the name. Here's a working (of course not real world) example:
```
Direction value = Direction.Up;
string position = value switch
{
    Direction.Up => "Top",
    Direction.Down => "Bottom",
    Direction.Left => "Left",
    Direction.Right => "Right",
    _ => throw new Exception()
};
```

Now, I think it would be nice if it was possible to remove the redundant `Direction` and just write it like this:
```
Direction value = Direction.Up;
string position = value switch
{
    Up => "Top",
    Down => "Bottom",
    Left => "Left",
    Right => "Right",
    _ => throw new Exception()
};
```

I don't know if this is worth implementing but I think it looks nice and would be a good way to remove redundant code.

**Comment by canton7** [comment]
Duplicate of #764.

**Comment by Joelius300** [comment]
@canton7 Agreed :) 

I'll close this issue here as I don't think it's needed.

**Comment by theunrepentantgeek** [comment]
As I just [commented](https://github.com/dotnet/csharplang/issues/764#issuecomment-544283015) on #764, I think this can already be done with `using static`.

**Comment by benaadams** [comment]
As @theunrepentantgeek points out this should work?

```csharp
using static Direction;

// ...

Direction value = Up;
string position = value switch
{
    Up => "Top",
    Down => "Bottom",
    Left => "Left",
    Right => "Right",
    _ => throw new Exception()
};
```

**Comment by Joelius300** [comment]
You're correct but as mentioned in #764 (e.g. [this comment](https://github.com/dotnet/csharplang/issues/764#issuecomment-523675308)), that's not exactly what I'm looking for. It's a possible solution but the collisions are troublesome.

Also @theunrepentantgeek , this was already mentioned a few comments earlier in the linked post :)
