### ISSUE TITLE
Error required for override changing return type between object and dynamic

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#290]
According to 10.6.4 of the C# spec:

> A compile-time error occurs unless all of the following are true for an override declaration:
> ...
> - The override method and the overridden base method have the same return type.

However, none of the C# compilers diagnose this:

``` cs
public class A
{
    public virtual object M() { return null; }
}

public class B : A
{
    public override dynamic M() { return null; }
}
```

I suspect this is an error in the language spec rather than a compiler bug.

(ported from https://github.com/dotnet/roslyn/issues/4012)

**Comment by BillWagner** [comment]
The current spec using the term "identity conversion", rather than "have the same return type."  

The current text for "identity conversion" includes this statement:

> "Because `object` and `dynamic` are considered equivalent there is an identity conversion between `object` and `dynamic`, and between constructed types that are the same when replacing all occurrences of `dynamic` with `object`."

The current standard fixes this issue. Closing.
