### ISSUE TITLE
Support for nameof(Interface<>.Property)

### ISSUE THREAD

**Issue by rchs819** [dotnet/csharplang#2905]
Consider the following
```csharp
public interface Vehicle 
{
   void Run();
}
```
It's cool that we could do
```csharp
nameof(Vehicle.Run); // "Run"
```

But when it comes to Generic Interface like
```csharp
public interface Vechicle<TEngine>
{
   void Run();
}
```
We cannot do 
```csharp
nameof(Vehicle<>.Run); // Syntax error
```
In my use case, I have to stuff in a class `TEngine` to make it work
```csharp
nameof(Vehicle<object>.Run); // "Run"
```
---
**Questions**
Is it possible to support `nameof(Interface<>.Property)` like `typeof(Interface<>)` ?

**Comment by yaakov-h** [comment]
Duplicate of #702.

**Comment by rchs819** [comment]
Thanks @yaakov-h , will close the issue
