### ISSUE TITLE
Proposal: Infer namespace from signature

### ISSUE THREAD

**Issue by taori** [dotnet/csharplang#2907]
I was just writing up some code and figured that some code noise could be reduced if this feature were to exist:

	namespace NamespaceA
	{
		public class Settings
		{

		}
	}
	namespace NamespaceB
	{
		public class Settings
		{

		}
	}

	namespace ServiceNamespace {
		public class SomeService
		{
			public void MethodA(NamespaceA.Settings settings) { }
			public void MethodB(NamespaceB.Settings settings) { }
			public void MethodOverload(NamespaceB.Settings settings) { }
			public void MethodOverload(NamespaceA.Settings settings) { }
		}
	}
	namespace ConsumerService {
		public class Program
		{
			public void Main()
			{
				var service = new SomeService();
				// semantically the full namespace should not be required here, since it is known which type is to be expected here?
				service.MethodA(new NamespaceA.Settings());
				// semantically the full namespace should not be required here, since it is known which type is to be expected here?
				service.MethodB(new NamespaceB.Settings());

				// full namespace required here since it is unclear which type is supposed to be used in this case
				service.MethodOverload(new NamespaceA.Settings());
				// full namespace required here since it is unclear which type is supposed to be used in this case
				service.MethodOverload(new NamespaceB.Settings());
			}
			public void MethodB(NamespaceB.Settings settings) { }
		}
	}

**Comment by DavidArno** [comment]
In my view, the problem here isn't that the compiler doesn't infer the type for you. The problem is that you have created multiple classes with the same names. 

Therefore the solution is to fix that, but giving them better, unique names, rather than changing the language to accommodate bad practice.

**Comment by taori** [comment]
That is not the point. When developing modules you might end up adding redundant class prefixes, which are already part of the modules full namespace, merely to have distinctive class names where a more generic name would suffice. 

This is a requirement similar to removing the enums declaration name where the type can be infered, so merely the enum value would be required

**Comment by HaloFour** [comment]
This is why aliases exist in the language.

**Comment by taori** [comment]
I'm aware that namespaces aliases exist - i've proposed this, because in this case they technically would not be necessary

**Comment by ZacharyPatten** [comment]
I think #100 would help here.

**Comment by alrz** [comment]
The type would be bound by the time overload resolution kicks in. So this is suggesting to target-type new even if type is present and check if the specified type name matches.

It wouldn't be easy to come up with a spec that doesn't incur breaking changes, which, in my opinion, is a sign that you are solving the wrong problem. Also #100 most likely addresses this issue.

I'd prefer we invest in global aliases to make it easier to deal with name conflicts and keep it consistent across files without copy/pasting usings in all of them.

**Comment by taori** [comment]
@ZacharyPatten True - this would be a non issue if #100 were to be implemented at the same time as improving even more noise
