### ISSUE TITLE
LINQ query materialization in-language syntax (ToArray/ToList/Single/Sum etc.)

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/csharplang#291]
Hi,

I almost never use C# LINQ when I need a one liner, because then I have to wrap the whole query in parentheses or use a variable:

    var query = from u in people
                       where u.Age > 30
                       select u.Name;
    var result = query.ToArray();

Or

    var result = (from u in people
                        where u.Age > 30
                        select u.Name).ToArray();

Both ways are not so aesthetic.

As suggested in [this](https://github.com/dotnet/roslyn/issues/100#issuecomment-115544173) post, please extend the built-in LINQ features in the language itself to include execution/materialization capabilities.

Here are some other related posts that's worth reading:

* [roslyn/#3571: [Proposal] extend language integrated query clauses with "apply" clause](https://github.com/dotnet/roslyn/issues/3571)
* [#101: Champion "Query-foreach (`do` query termination)"](https://github.com/dotnet/roslyn/issues/101)
* [roslyn/#100: Extend LINQ syntax](https://github.com/dotnet/roslyn/issues/100) (mentioned above)
* [roslyn/#3486: [Little Feature Request] LINQ query materialization](https://github.com/dotnet/roslyn/issues/3486)

Personally I like the first couple most as it's simple, requires no big introduction of new keywords and is flexible. But the first one is also a great point.

**Comment by alrz** [comment]
Related to this [#100 (comment)](https://github.com/dotnet/roslyn/issues/100#issuecomment-239918884) and somehow https://github.com/dotnet/csharplang/issues/101.

**Comment by weitzhandler** [comment]
@alrz 
As stated in my question it is, but that issue closed in order to be posted here. So that's what I did.

**Comment by weitzhandler** [comment]
I'm closing this issue as it was already offered [here](https://github.com/dotnet/csharplang/issues/101#issuecomment-285885522)

**Comment by orthoxerox** [comment]
No, please reopen it. #101 is about a different proposal, let's use this one to discuss passing the result to a collector.

**Comment by weitzhandler** [comment]
@orthoxerox 
See the 3rd comment on that post.

**Comment by aluanhaddad** [comment]
I would definitely appreciate such a feature.
