### ISSUE TITLE
[Proposal] Allow class/instance Fields to be scoped to Property definitions

### ISSUE THREAD

**Issue by bjorg** [dotnet/csharplang#2913]
# Local Property Fields

## Summary
This proposal is to address a limitation in C# when attempting to design C# classes to improve the developer experience around properties and their backing fields. The issue at heart is that a class designer cannot restrict access to explicit backing fields for that are intended to be exclusively used by their properties. 

## Use Case 1: Isolate property backing fields from misuse
Consider the following class. The intent is that every time the `Left` or `Right` properties are set, the assigned item has also its `Parent` field set. This implementation is vulnerable to a new developer inadvertently directly setting `_leftItem` or `_rightItem` when adding new functionality to the class (no such problem for derived classes).

**Current Syntax:**
```csharp
public class Node {
    public Node Parent { get; private set; }

    private Node _leftItem;
    public Node Left {
        get => _leftItem;
        set => {
            _leftItem = value;
            value.Parent = this;
        }
    }

    private Node _rightItem;
    public Node Right {
        get => _rightItem;
        set => {
            _rightItem = value;
            value.Parent = this;
        }
    }
}
```

By allowing to move the backing field declartion into the property, we gain two benefits. First, we make it impossible for the backing field to be manipulated directly. We also remove the overhead of giving each backing field a new, unique name (i.e. the implementation for the `Left` and `Right` properties are now identical).

**Proposed Syntax:**
```csharp
public class Node {
    public Node Parent { get; private set; }

    public Node Left {
        Node _item; // <-- local property field; scoped to property implementation
        get => _item;
        set => {
            _item = value;
            value.Parent = this;
        }
    }

    public Node Right {
        Node _item; // <-- local property field; scoped to property implementation
        get => _item;
        set => {
            _item = value;
            value.Parent = this;
        }
    }
}
```

## Use Case 2: Hide implementation details of properties
Similarly to _Use Case 1_, we can use local property fields to hide implementation details. Consider the following example, which provides convenient access to a `Lazy<T>` field. By using a local property field, the `_lazyLargeObject` instance field is not visible outside of the property implementation, which simplifies the developer experience for auto-complete/intellisense inspection.

```csharp
class MyClass {
    public int MyLargeObject {
        Lazy<LargeObject> _lazyLargeObject = new Lazy<LargeObject>(() => { ... });
        get => _lazyLargeObject.Value;
    }
}
```

## Use Case 3: Isolate static fields from misuse
Similar to _Use Case 1_, but using a static field in an instance property. In this example, the instance property uses a static local field to initialize an instance of the `Random` class once and then have exclusive access to it.

```csharp
class MyClass {
    public int NextRandomNumber {
        static Random _random = new Random();
        get => _random.Next();
    }
}
```

## Implementation
I don't have enough knowledge of the C# compiler to make a concrete recommendation, but here is my guess at the scope of this proposal.
1. Allow one or more field definitions with initialization inside properties bodies (`{ }`)
2. Scope local property fields to only be visible to the property body. Similar to property backing fields, these local property fields are not visible to the rest of the class/instance.
3. Allow Local property fields on both static and instance properties. For static properties, the local fields would need to be prefixed with `static`.
4. Access modifiers (`public`, `private`, ...) are not allows on local property fields. They are always `private`.

## Benefits
* Reduce visible fields in an instance/class, when these are meant for exclusive use by their respective properties.
* Eliminate the risk of accidental misuse of explicit backing fields.
* Immediate juxtaposition of explicit backing field and their usages.
* Reduce complexity for developers (or code generators) in uniquely naming backing fields since they are scoped to the property implementation.

**Comment by theunrepentantgeek** [comment]
I think this is a near-duplicate of #140 - Proposal: Semi-Auto-Properties; `field` keyword

**Comment by bjorg** [comment]
I spent some time searching for a previously filed issue, but apparently didn't look hard enough. My proposal seems to be dup of #133 (which is linked from $140), but without the notion of exposing the backing field as `field`.

**Comment by Joe4evr** [comment]
@bjorg So why is this issue still open?

**Comment by Unknown6656** [comment]
Oh boy - here we go again with the duplicates:

#2647
#1880
#1712
#1643
#1497
#1420
#1336 
#1290 
#1240
(#1059)
#626
#318
#140
#133
_[and there are probably even more]_

# Do please consider closing this issue if at least one of the other ones would solve it in order to keep the amount of duplicates low.

### _why do I always have to write that?_

**Comment by bjorg** [comment]
I reviewed the linked issues. They are not all duplicates, but some are. For future reference, I'm listing them here before closing this issue.

#1712 
#1420
#1336 
#626
#133 

Looks like a lot of folks have asked for this. Maybe someday! Thx.

**Comment by Unknown6656** [comment]
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md

**Comment by jnm2** [comment]
@Unknown6656 #140 (use backing field without naming it) was discussed in that meeting, but this issue is a duplicate of #133 (declare normal fields with property scope) which is a different and partially independent request.
