### ISSUE TITLE
[Proposal]: try-only statement

### ISSUE THREAD

**Issue by federicotomasi** [dotnet/csharplang#2914]
I think it would be nice to have a short hand for try-catch construct with empty catch

```
try
{
    [...]
}
catch { }
```

i.e. just
```
try
{
    [...]
}
```

`catch` clause should be optional and should be used only to catch specific exception types or if Exception object is needed for further operations (logging, wrapping, etc)

**Comment by ZacharyPatten** [comment]
This encourages bad practices. If you are using try catches with empty catches that your code should likely be refactored. For example, rather than using a try at all, you should use a `Try` + `MyMethod` similar to `int.TryParse`.

If I had a dollar for every I ran into an unlogged exception in code... I would buy Microsoft and change the compiler so that empty catches would no longer compile.

**Comment by federicotomasi** [comment]
I understand what you're saying here and I agree in a certain way in not encouraging bad practices like empty catch claused, but sometimes you just want to try execute something that may fail and, if it does, it should do it silently, especially when you want to execute third-party code and don't really know what is going to happen in exceptional conditions.

I report here the use case which made me propose this short-hand: I want to log an object with an unknown structure as a JSON (imagine using Json.NET or another third party json serializer) in a catch clause (i.e. an object related to the exception), but I don't know if it contains binary data, circular references or something else. So I just want my code to try and in case fail silently if it have to, no need for a catch behavior.

It's a great powers = great responsabilities situation here, but I just propose a short hand for an already existing exception handling strategy (sometimes, not having a strategy is a strategy).

**Comment by HaloFour** [comment]
> It's a great powers = great responsibilities situation here

Yes, in that the compiler has great power and thus has the responsibility to not encourage anti-patterns such as ignoring exceptions.  Easier syntax is a tacit encouragement that the given code is the appropriate way to do something.

**Comment by federicotomasi** [comment]
Also allowing this syntax

`catch { }`

instead of this syntax

`catch (Exception ex) { }`

is IMHO an encourage in non explicit exception handling; if the compilers has to allow ti, at least it could allow in a compact way.

**Comment by HaloFour** [comment]
@federicotomasi 

> is IMHO an encourage in non explicit exception handling;

Which the developer is forced to do something about, which is the correct thing to do.  If the developer wishes to omit any statements in that `catch` block, that is their prerogative, but it is almost always the wrong thing to do.  Thus the compiler shouldn't make doing the wrong thing easier than doing the right thing.

**Comment by federicotomasi** [comment]
My point is, the compiler is already making things easier by admitting not to declare the `Exception ` variable in the catch clause, forcing the developer to declare an empty statement which is actually not useful. Thinking at it, I would be ok with one of the followings:

- make the catch clause optional (my first proposal, actually not that good)
- make back the `Exception` object mandatory in catch clause
- make mandatory to write a body in the `catch` clause (which may also not use the `Exception` object; if it's unused, it makes sense it can be omitted)

**Comment by federicotomasi** [comment]
> ultimately it's the programmer's job to decide what they want to do.

Yeah, I definitely agree with tour last statement, but for some reason nobody wants to give to those programmers who have decided not to handle the exception a compact and readable way to do this lmao. Closing this
