### ISSUE TITLE
Nullable version of unmanaged type should be unmanaged too

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/csharplang#2916]
**Version Used**: VS 16.3.1

Following code:
```C#
private static void Foo<T>()
    where T : unmanaged
{ }

private static unsafe void Bar()
{
    Foo<int?>();
}
```
reports error: "The type 'int? must be a non-nullable value type...'".

[Documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/unmanaged-types) states: "Any user-defined struct type that contains fields of unmanaged types...". Don't know why it talks only about "user-defined" structs (maybe because of ```Span<T>```?) but I don't know about any reason for disallowing nullable types. They are just structs with two fields (```bool``` and ```T```). So when ```T``` is unmanaged than ```T?``` is unmanaged too.

I'm really depressed of this. I've expected constructed unmanaged types would have worked already in C# 7.3. Now I hoped it would be supported by 8.0 because of explicit addition of support for constructed unmanaged types but it's still not usable enough.
Now I'm workarounding this issue by using ```Unsafe``` class and using runtime checks for checking that ```T``` is unmanaged/blittable (allowing nullable types). It would be nice to have compile time support for this.

Thanks.

**Comment by agocke** [comment]
Moved  to csharplang, since this would be a language change. I think it's a fine request and as long as the CLR can handle the unmanaged constructed type (that is, Nullable<T> is like any other unmanaged constructed type in that T must be unmanaged after construction), then I don't see why we shouldn't do it.

**Comment by john-h-k** [comment]
The reason for this is that the `unmanaged` constraint implicitly specifies the `struct` constraint, which forbids nullables

**Comment by kindermannhubert** [comment]
@john-h-k Oh, I see. Now, it makes sense. Thanks! 👍

You just need to provide special overrides for nullable versions (just like when you work with struct nullable generics).

This compiles fine (just example):
```C#
private static T* Foo<T>(T x)
    where T : unmanaged
{
    return &x;
}

private static T?* Foo<T>(T? x)
    where T : unmanaged
{
    return &x;
}
```
In that case there is probably no changes to compiler required.

> the unmanaged constraint implicitly specifies the struct constraint

Maybe this should be explicitly stated in documentation? You can see it when you decompile method using unmanaged constraint but I was able to confuse few people here with this issue 😄.

**Comment by HaloFour** [comment]
@john-h-k 

> The reason for this is that the unmanaged constraint implicitly specifies the struct constraint, which forbids nullables

I don't believe that is the case.  `Nullable<T>`, which backs nullable value types, is a [struct](https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1?view=netframework-4.8).

**Comment by kindermannhubert** [comment]
@HaloFour It is. Just try the example at top (when I was requesting change) and replace ```unmanaged``` with ```struct```. It won't compile as well. Example in my reply to @john-h-k shows how to use ```T?*```.

**Comment by HaloFour** [comment]
@kindermannhubert @john-h-k 

Huh, that's interesting.  I'm kind of surprised I've never run into that before.

**Comment by Joe4evr** [comment]
> I don't believe that is the case. `Nullable<T>`, which backs nullable value types, is a [struct](https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1?view=netframework-4.8).

Yes, but `Nullable<T>` is specifically excluded from the `struct` constraint. You can't declare a variable of `Nullable<int?>`, for example.

**Comment by kindermannhubert** [comment]
Because of this it's quite unfortunate you cannot have same type for working with all unmanaged types (you need one for nonnullable values and one for nullable values).
For example:
```C#
public class SomeTypeNonNullable<T>
    where T : unmanaged
{
    private readonly T value;
    //...
}

public class SomeTypeNullable<T>
    where T : unmanaged
{
    private readonly T? value;
    //...
}
```
Now i solve it like this:
```C#
public class SomeType<T>
{
    private readonly T value;

    public SomeType(T value)
    {
        ASSERT_T_IS_UNMANAGED(); //checked at runtime :-/
        this.value = value;
    }
    //...
}
```
With that you lose compile-time checking for T constraint. When you need to make use of 'unmanagedness' of T you need to for example use Unsafe and casting ```ref T``` to ```T*```.

Guessing this is the only way now, am I right?

**Comment by HaloFour** [comment]
Seems like this would require changes to the runtime.  The `unmanaged` constraint doesn't exist in the CLR, it's really just the `struct` constraint with a custom attribute that the C# compiler interprets.  If the CLR forbids using `Nullable<T>` as a generic argument when constrained by `struct` then that would need to change.

**Comment by reflectronic** [comment]
The `unmanaged` constraint currently emits in IL a `valuetype` constraint and a `System.ValueType` base type constraint. Removing the `valuetype` constraint would allow `Nullable<T>` as a generic argument.

**Comment by Joe4evr** [comment]
@reflectronic A slight problem with that is that will cause all argument types to be boxed since `System.ValueType` behaves like a class, IIRC.

**Comment by reflectronic** [comment]
@Joe4evr The generic type/method will still be re-instantiated per value type, so there shouldn't be any boxing.

**Comment by pkulikov** [comment]
It looks like a concrete nullable version of an unmanaged type behaves like an unmanaged type: the `sizeof` and `stackalloc` operators are applicable, one can create a pointer.

```csharp
class Program
{
    public struct Number<T> where T : unmanaged
    {
        public T number;
        public Number(T n) => number = n;
    }

    public unsafe static void Main()
    {
        Console.WriteLine(sizeof(int?));
        int? b = null;
        int?* c = &b;
        Console.WriteLine((long)c);
        Console.WriteLine(c->HasValue);  // output: False
        Span<int?> xs = stackalloc int?[] { 0, null, 2 };

        Console.WriteLine(sizeof(Number<double>?));
        Number<double>? d = null;
        Number<double>?* e = &d;
        Console.WriteLine((long)e);
        Console.WriteLine(e->HasValue);  // output: False
        Span<Number<double>?> ys = stackalloc Number<double>?[] { null, new Number<double>(4.0) };
    }
}
```

So, given a nullable unmanaged type:

- Is it not unmanaged type that behaves in most cases like unmanaged type OR
- Is it an unmanaged type that *doesn't* satisfy the `unmanaged` constraint?

**Comment by Joe4evr** [comment]
> So, given a nullable unmanaged type:
> 
> * Is it not unmanaged type that behaves in most cases like unmanaged type OR
> * Is it an unmanaged type that _doesn't_ satisfy the `unmanaged` constraint?

The answer is Option C: It's an unmanaged type that doesn't satisfy the ***`struct`*** constraint (which is implicit when using the `unmanaged` constraint).

**Comment by gafter** [comment]
@Joe4evr Given that state of affairs, I don't know how precisely we would change the language specification to accomplish the desired behavior.

**Comment by reflectronic** [comment]
@gafter Separate the `unmanaged` constraint from the `struct` constraint. `unmanaged` should act like a `System.ValueType` base type constraint instead of a `valuetype` IL constraint.

**Comment by agocke** [comment]
As @john-h-k mentioned, the problem is that the `unmanaged constraint` implies `struct`, and modifying that would be a breaking change.

This change is dead in the water.
