### ISSUE TITLE
Function Pointer Syntax

### ISSUE THREAD

**Issue by 333fred** [dotnet/csharplang#2917]
### Current State

Currently, we have the following syntax proposal for function pointers (grammar slightly corrected from the proposal):

```antlr
pointer_type
    : ...
    | funcptr_type
    ;

funcptr_type = 
    'func' '*' calling_convention? return_type '(' (type (',' type)* )? ')' |
    '(' funcptr_type ')' ;

calling_convention = 
    'cdecl' |
    'managed' |
    'stdcall' | 
    'thiscall' |
    'unmanaged' ;
```

This grammar has a few different problems, mainly around parsing:

1. `func` can be a variable bound to an existing construct, and this is impossible to figure out at parsing time. This means that we would potentially need to use semantic analysis to inform how the tree should parse. `var` has this problem, but to a lesser extent, as we can parse just the single token and reinterpret it later. A function pointer has many tokens as part of it, and if we determine that the `func` should have been bound to a local later in the process, we currently do not have the facilities to handle this.
1. Error recovery of specific scenarios requires an exponential number of parsing passes. Consider the following scenario:
   ```cs
   func* func* invalidcallingconvention (int, int)(string)()
   ```
   The proper interpretation of this can be clarified with these parens:
   ```cs
   func* (func* invalidcallingconvention (int, int)(string))()
   ```
   However, in order to interpret it in this manner, we have to parse the inner function pointer a minimum of twice. The first time we parse, we interpret as `func* invalidcallingconvention(int, int)`, and then later notice that there's a trailing `(`. We then have to retry parsing of the inner function pointer, this time being greedy and assuming that `invalidcallingconvention` is in fact that, and not a return type itself. They're somewhat unlikely scenarios, but handling this correctly without blowing up the compiler is tricky and each successive case requires an exponentially larger number of parse attempts.

### New Syntax Proposal

In order to handle these issues, I propose a new syntax for defining a function pointer, inspired by the `Func<T>` type we all know and love today:

```antlr
pointer_type
    : ...
    | funcptr_type
    ;

funcptr_type
    : calling_convention '*' '<' (type ',')* return_type '>'
    ;

calling_convention
    : 'func'
    | 'cdecl'
    | 'managed'
    | 'stdcall'
    | 'thiscall'
    | 'unmanaged'
    ;
```

The `func` calling convention represents the default, which is `managed`. The `unmanaged` calling convention represents the default calling convention for native code on the current platform, and is encoded as `winapi`. All `calling_convention`s are contextual keywords when followed by a `*<`.

Some examples of this new syntax:

```cs
func*<void> // A function pointer that takes nothing and returns nothing, with the default calling convention
cdecl*<int, void> // A function pointer that takes an int and returns nothing, with the cdecl calling convention
managed*<func*<void>, func*<void>> // A function pointer that takes an function pointer, and returns a function pointer. The inner function pointers take and return nothing and have the default calling convention. The outer function pointer has the managed calling convention explicitly.

// The example from above:
func*<invalidcallingconvention*<string, (int, int)>>
```

This proposal has a few advantages:

1. It is completely unambiguous. `identifier*<` is not a legal sequence of characters in C# today, and can be unambiguously differentiated from existing syntax. Because of this, even if you have a type named any `calling_convention`, we can correctly interpret these identifiers as contextual keywords. It also allows us to add new calling conventions as the runtime expands to support them in the future, without making source-breaking changes.
2. Error recovery scenarios are simple here. Because `identifier*<` is a completely new syntax, there's no exponential recovery from nameless tuples. This syntax can be parsed in one single pass, regardless of whether an invalid calling convention was supplied.

#### Using Alias Declarations

This would require all function pointer types to be declared as a using alias, and disallow raw function pointer definitions outside the alias. In order to be usable, this would likely require an approach for a solution-wide, external facing typedef feature. Because the syntax would be unambiguous in a using alias, this solves issue 1. However, it would still suffer from issue 2, and because we like to consider the IDE experience, in all likelyhood we'll still need to be able parse these types in other places in order to produce decent error information.

**Comment by CyrusNajmabadi** [comment]
nit:  much easier to read ad:

```
funcptr_type
    : 'func' '*' calling_convention? return_type '(' (type (',' type)* )? ')'
    | '(' funcptr_type ')' ;
```

**Comment by CyrusNajmabadi** [comment]
Minor thoughts:

1. `*<`.  This is def a clever way to ensure no ambiguity.  And there's an appeal in that `*` represents `pointer` and thus `func*` represents `func pointer`.  that said, i'd also be ok with removing the `*` and effectively making thse contextual keywords.  i.e. just allow `func<int, void>`.  We'd bind like normal, would find that it wouldn't bind to anything, and would then rebind contextually as a function pointer.  I personally like the symettry here of this just being a special built-in generic type that happens to have this meaning.  Note: this a minor complaint and i'm fine with keepin `*` for pure explicitness.1

**Comment by AartBluestoke** [comment]
we can't currently use void as a type (in the same way that a generic Func<int,void> isn't a valid thing, and we end up with Action<int> instead). I believe it would cause confusion if func*<int,void> was a thing, but Func<int,void> wasn't. 

(note, my preference is that Func<int,void> would be a thing, but that would be a different proposal)

I believe there are several proposals around for using void (or other 'bottom' types), for which this may be contribute to the value of.

**Comment by CyrusNajmabadi** [comment]
> I believe it would cause confusion if func*<int,void> was a thing, but Func<int,void> wasn't.

I'm ok with that confusion.  Function pointers are extremely specialized beasts.  I don't think the rules there have to impact the rules elsewhere.

**Comment by CyrusNajmabadi** [comment]
For example, we can't use `void` in a generic instantiation.  But we use it in a method return type, or in `typeof`, or in a pointer type.  The rules around where `void` are/aren't allowed are pretty unique.  So adding one more very special case doesn't bother me.

**Comment by YairHalberstadt** [comment]
> just allow func<int, void>

I'm not sure we would want people to end up with a func pointer if they misspelt Func.

**Comment by 333fred** [comment]
> I'm not sure we would want people to end up with a func pointer if they misspelt Func.

Agreed on this. There is also an open question on whether we'd even have `func*`, or just have all the calling conventions with no default.

**Comment by 333fred** [comment]
> there's part of me that wants all function pointers to start with the same syntax, and have the different callign conventions called out somehow as sub-features of the node.

Agreed on this point as well. But as you said, I wasn't able to find a way to make this work with the current syntax in a way that fit well. I considered `func*<cdecl, void>` for about a second before violently erasing it from the whiteboard in horror.

**Comment by 333fred** [comment]
> I believe it would cause confusion if func*<int,void> was a thing, but Func<int,void> wasn't.

Function pointers are not designed to be used by the average programmer. Much like the other interop and unsafe code areas, they're designed to enable a small subset of library authors to enable performant solutions for 90% of .NET users. I'm perfectly fine with saying that, just like everything else to do with pointers, you need to know what you're doing.

**Comment by alrz** [comment]
>Function pointers are not designed to be used by the average programmer. 

I think we should choose something with a "pretty syntax for delegates" in mind.

As far as I remember there were two requests regarding delegates:

- Named parameters in delegate types, like tuples e.g. `Action<int index> action;`
- Function types in general where they don't have a corresponding delegate type

If we want to keep design space open for any of these, perhaps the syntax chosen here should be forward compatible - capable of representing non-pointer function types as well. We probably don't want two *very different* function syntaxes in the language.

**Comment by hez2010** [comment]
What if there's a generic method? How to represent it with the new syntax?

For example:
```
int MyFunc<T>(T input1, T input2);
```

**Comment by tannergooding** [comment]
> You cannot have a function pointer to a generic method.

Something worth considering is this might be true today, but it might not be true "always", and so a new syntax might prevent future extensions to the language.

**Comment by 333fred** [comment]
> I think we should choose something with a "pretty syntax for delegates" in mind.

I think this is a poor issue to try and use to get a pretty delegate syntax. As mentioned, these are not intended for broad use. We already have multiple ways of specifying method types, both via standard delegate declaration, and via Action/Func (I consider these so broadly used that they're a pattern in their own right, despite being just delegates). Both of the proposed syntaxes are similar to an existing method signature definition, so I'm not particularly concerned with about "_two very different_ function type syntaxes"

**Comment by 333fred** [comment]
> Something worth considering is this might be true today, but it might not be true "always", and so a new syntax might prevent future extensions to the language.

True, though there would have to be some pretty big changes to enable that. Regardless, the new syntax can be extended to support it, though it would be ugly:

```cs
func*<T><T, T, int>
```

**Comment by tannergooding** [comment]
It's also worth calling out that the number of calling conventions could grow in the future and so this should be considered with any syntax proposal.

IIRC, you had indicated that since `keyword*<` is invalid today, this should never be a problem even as new calling conventions (e.g. vectorcall) are introduced.

**Comment by tannergooding** [comment]
My thoughts are mainly that I'm not a fan of the syntax; but I could teach myself (and my binding generator) to understand it. At the end of the day, function pointers have never been "pretty" in any language and I'd rather have them than not 😄 

I do like the idea of the using aliases, as I think we will need to go down that route eventually anyways. I would have questions around how attributes or other modifiers would be placed on these.

Alternatively, if we are already going to need some kind of type definitions anyways, we could just go with `public func* return-type Name(parameter-list)` (so basically the delegate syntax but swapping out the `delegate` keyword) and support placing the calling convention via an attribute (which is how `DllImport` already works).

**Comment by CyrusNajmabadi** [comment]
> We try to be a friendly compiler, the first refactoring I see someone wanting to add is "alright, move this thing to a using", and we're back in the same problem area.

We don't allow tuples in aliases, and that is truly annoying.  I'm ok with alias+funcptr not being a place that matters at all :)

**Comment by 333fred** [comment]
Andy will have the full LDM notes up later, but we ended up settling on this syntax:

```antlr
funcptr_type
    : 'delegate' calling_convention? '*' '<' (type ',')* return_type '>'
    ;

calling_convention
    : 'cdecl'
    | 'managed'
    | 'stdcall'
    | 'thiscall'
    | 'unmanaged'
    ;
```

I need to make some additional modifications to support `ref/out/in`, but otherwise we are ok with this as the syntax moving forward.

**Comment by CyrusNajmabadi** [comment]
@333fred I like that!  Very much solves my #2 point in https://github.com/dotnet/csharplang/issues/2917#issuecomment-547692306 as well.  So that makes me happy.  `delegate` (esp. as `anonymous  methods` are rare) is a nice way to make this look very distinct from 'normal' code :)

**Comment by alrz** [comment]
This looks nice `delegate* <int, void>` and can be possibly extended to a non-pointer function type.

My only concern is `calling_convention` being a keyword. I'm aware that an attribute is considered already but since we can't apply attributes everywhere it doesn't cover all the places.

Could we take advantage of "attributes everywhere" (https://github.com/dotnet/csharplang/issues/2478) proposal here? 

Another approach is to permit a string literal `delegate* "cdecl" <int, void>` in that it doesn't need too many special keywords for any convention.

**Comment by 333fred** [comment]
@alrz we specifically don't want attributes here. First, there's nowhere to put them in metadata. Second, we don't want attributes affecting type identity, which calling convention needs to.

**Comment by CyrusNajmabadi** [comment]
> My only concern is calling_convention being a keyword

That seems necessary to me so that hte compiler can determine compatibility.  For example a cdecl funcptr should not be assignable to a funcptr with an incompatible calling convention, etc. etc.

**Comment by HaloFour** [comment]
@333fred 

> First, there's nowhere to put them in metadata. Second, we don't want attributes affecting type identity, which calling convention needs to.

I don't have a horse in this game but I'm not sure how this argument applies.  P/Invoke already demonstrates how the C# compiler can apply such pseudo-attributes and enforce additional validation/constraints beyond what it does for standard custom attributes.  A theoretical function pointer pseudo-attribute could be applied in the same manner.

That said, exactly how is the metadata for function pointers going to be exposed?  How will the compiler know that an API requires a compatible "cdecl" function pointer?

**Comment by 333fred** [comment]
Function pointers are in CLR spec, exposed as their own token. We need to confirm with the runtime team as there's a few places in the spec where it's not clear, but MethodDefSpec and MethodRefSpec should be able to support this.

> such pseudo-attributes and enforce additional validation/constraints beyond what it does for standard custom attributes

These psuedo-attributes do not affect type identity, unlike calling convention. Additionally, if we wanted to put attributes on function pointer tokens, we'd have to come up with some wrapper struct with an `Invoke` method, because there is literally no table for us to store these attributes in.

**Comment by HaloFour** [comment]
> These psuedo-attributes do not affect type identity, unlike calling convention. Additionally, if we wanted to put attributes on function pointer tokens, we'd have to come up with some wrapper struct with an `Invoke` method, because there is literally no table for us to store these attributes in.

They're pseudo-attributes, they can do whatever you want them to do.  They aren't stored as attribute metadata.  The compiler could do the exact same thing it would do with a `cdecl` keyword, but using attribute syntax instead.  That's why the 13 pseudo-attributes exist in the BCL, so that languages didn't have to add keywords for each of them (unless they wanted to).  😁

**Comment by 333fred** [comment]
The point is not that we can't store them correctly, the point is that no attributes today affect type identity. You can theoretically overload on a calling convention (whether we'll let you do so in C# is an open question, but you certainly could in IL), so encoding these as attributes syntactically would be a first for the language, and not a good precedent to set imo.

**Comment by CyrusNajmabadi** [comment]
> so encoding these as attributes syntactically would be a first for the language, and not a good precedent to set imo.

i also get very very nervous about dependencies on attributes primarily because of the binding requirements and all sorts of wonkyness there.  In general, i know in the past that needing attributes can greatly complicate things as they involve a separate sort of binding that happens with the other phases.  it often works out in the end, but often at the end of deep complexity and lots of infinite loops that someone has to figure out hte rules on how to break in the roslyn compiler :)

**Comment by reflectronic** [comment]
I would prefer the `*` go after the parameter list (e.g. `delegate<int, int>* x = null`); that way, it's more congruent with how pointer types canonically work, especially considering something like [first-class delegate types](https://github.com/dotnet/csharplang/issues/470) where the same syntax could be reused sans the asterisk.

I would also appreciate named parameters.

**Comment by alrz** [comment]
FWIW, this is how it looks like in Rust[ `extern "cdecl" fn(T) -> R`](https://github.com/rust-lang-nursery/rustc-perf/blob/master/collector/benchmarks/script-servo/components/malloc_size_of/lib.rs#L70), that is, it's a qualifier on the type, much like `ref`. So taking the suggestion from @reflectronic, it would be
```cs
delegate stdcall<int, void>* f;
// vs
extern "stdcall" delegate<int, void>* f;
```
I don't care much for verbosity since this should be pretty rare. :)

**Comment by gafter** [comment]
We will need to support `ref`, `out`, `in`, `readonly ref` in the parameters as well.

**Comment by reflectronic** [comment]
The PR’d update to the proposal [includes support for byref.](https://github.com/dotnet/csharplang/pull/2923/files#diff-f256c76ada597ecd8ec0e344d8cb5a61R105)

**Comment by mjsabby** [comment]
Is it possible to reconsider the unsafe requirement for emitting the `ldftn`? i.e. the lone syntax  `&SomeFunction`.

Consider the scenario that a library author exposes a source generator to add code like &SomeInterestingFunctionInTheOriginalSourceCode to the project, this would now require the user of the library to declare their assembly unsafe.

This is a poor user experience for code that can be verified. The unsafety comes when someone does `calli` which can be tucked away in the library itself.

**Comment by sakno** [comment]
Is it possible to add the ability to instantiate delegate instance from the pointer? For example:
```csharp
delegate*<int, void> ptr = &SomeFunction;
Action<int> action = new Action<int>(ptr);
```

**Comment by tannergooding** [comment]
You would need to use `Marshal.GetDelegateForFunctionPointer`

**Comment by sakno** [comment]
@tannergooding , is it allowed for pointers to managed methods?
> The GetDelegateForFunctionPointer<TDelegate>(IntPtr) method has the following restrictions:
    Generics are not supported in interop scenarios.
    You can use this method only for pure unmanaged function pointers.
    You cannot use this method with function pointers obtained through C++.

**Comment by alrz** [comment]
A similar question I had, is it possible for it to point to an instance method where the instance object is passed as the first argument? (kind of like open delegates, but for pointers)

**Comment by sakno** [comment]
I just tested your suggestion:
```
System.ArgumentException : The specified Type must not be a generic type definition. (Parameter 't')
```
Code for test:
```csharp
delegate*<string, int> parse = &int.Parse;
var d = Marshal.GetDelegateForFunctionPointer<Func<string, int>>(new IntPtr(parse));
Equal(123, d("123"));
```
That's why I would like to ask authors of this PR to include this small addition.

**Comment by 333fred** [comment]
That would need to be a separate feature request.

**Comment by sakno** [comment]
Done: #3680

**Comment by 333fred** [comment]
Closing this out. Any future discussion should take place on the championed issue thread.
