### ISSUE TITLE
Tertiary assignment on a nullable type wont compile if one case is non nullable and one is nullable

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/csharplang#2944]
I'm trying to assign a value to a null-able type via a tertiary assignment where:
`case true: assign non-nullable`
`case false: assign null`
```
DateTime? assignee;
DateTime assignment;
var condition = false;

assignee = condition ? assignment: null;
```
This results in the compile error: Cannot convert DateTime to nullable.

I would assume that the compiler would translate this into something like:
```
DateTime? assignee;
DateTime assignment;
var condition = false;

if(condition) {
    assignee = assignment;
}else{
    assignee = null;
}
```
Which compiles fine.
Whats actually going on here?

**Comment by spydacarnage** [comment]
You can use:

`assignee = condition ? assignment : default(DateTime?)`

**Comment by ronnygunawan** [comment]
Related to #2832 #881

**Comment by KieranDevvs** [comment]
> You can use:
> 
> `assignee = condition ? assignment : default(DateTime?)`

Seems like a bit of a hack, but I guess it works for now.

**Comment by 333fred** [comment]
This would be addressed by https://github.com/dotnet/csharplang/issues/2823, which is currently on the table for c# 9

**Comment by gafter** [comment]
Closing as duplicate
