### ISSUE TITLE
Proposal: Conditional Compilation in XML Comments

### ISSUE THREAD

**Issue by dotMorten** [dotnet/csharplang#295]
Please support conditional compilation within XML documentation comments. This has been a source of pain with cross-compiled code for a long time. Often linked code files are used to share source between different target platforms of the same API; however, as a result often times the documentation comments must change conditionally as well. As of now, there's no good way around this limitation - you have to duplicate the entire XML comments conditionally, rather than just each section or line.

**Steps to Reproduce**:
1. Create the following property with doc in a class:

``` csharp
        /// <summary>
        /// Turns the GPS on or off
        /// </summary>
        /// <remarks>
        /// <para>Will turn on the system location service.</para>
        /// <para>Make sure you have enabled the location capability in your application's manifest. See
#if NETFX_CORE
        /// https://msdn.microsoft.com/en-us/library/windows/apps/br211423.aspx
#elif __ANDROID__
        /// http://developer.android.com/guide/topics/manifest/manifest-intro.html 
#endif
        /// for more information
        /// </para>
        /// </remarks>
        public bool IsGpsEnabled { get; set; }
```
1. Enable XML documentation generation 
2. Build

**Expected Behavior**:
No build warnings. XML is generated with platform specific remarks. This allows me to add a couple of platform specific remarks. Currently you have to if-def the entire code summary section, causing a lot of documentation to be duplicated, rather than just the areas that differ

**Actual Behavior**:
Several build warnings

```
warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'remarks'.'
1>\Class1.cs(25,13,25,14): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.'
1>\Class1.cs(9,18,9,24): warning CS1591: Missing XML comment for publicly visible type or member 'Class1'
1>\Class1.cs(11,9,11,10): warning CS1587: XML comment is not placed on a valid language element
```

And the generated XML:

``` xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ClassLibrary1</name>
    </assembly>
    <members>
        <!-- Badly formed XML comment ignored for member "P:ClassLibrary1.Class1.IsGpsEnabled" -->
    </members>
</doc>
```

Moved over from: https://github.com/dotnet/roslyn/issues/96

**Comment by terrajobst** [comment]
@dotMorten 

Let's say instead of allowing `#if` in doc comments we'd extend the XML vocabulary to allow for expressing conditional sections, like so:

```C#
/// <summary>
/// Turns the GPS on or off
/// </summary>
/// <remarks>
/// <para>Will turn on the system location service.</para>
/// <para specificTo="NETFX_CORE">
/// Make sure you have enabled the location capability in your application's manifest. See
/// https://msdn.microsoft.com/en-us/library/windows/apps/br211423.aspx
/// for more information.
/// </para>
/// <para specificTo="__ANDROID__">
/// Make sure you have enabled the location capability in your application's manifest. See
/// http://developer.android.com/guide/topics/manifest/manifest-intro.html
/// for more information.
/// </para>
/// </remarks>
public bool IsGpsEnabled { get; set; }
```

In your example that seems overly verbose; but I think there is a general need for marking parts of the documentation as only applying to a particular .NET platform or operating system. It would be nice if we could record this in the .XML file and allow the documentation tool to output them accordingly, i..e by placing them in specific sections with title or header or even making their visibility conditional on some context switcher on the web page.

Thoughts?

**Comment by jnm2** [comment]
@terrajobst I think keeping the current `#if` syntax is better. It would be more consistent with `#pragma warning disable`/`restore` lines in the XML documentation lines.

**Comment by nil4** [comment]
@terrajobst `#if` directives are documented to [support boolean operators, including `==`, `!=`, `&&`, `||` and `!`](https://msdn.microsoft.com/en-us/library/4y6tbswk.aspx), e.g. `#if (DEBUG && !MYTEST)`. It's unclear how the proposed `specificTo` attribute would cope with these and reduce duplication for more complex conditions.

**Comment by dotMorten** [comment]
@terrajobst Your approach won't work. We're compiling different binaries, which would then have different XML doc pieces. You would never need a "merged" xml doc, as the xml doc generated is specific to that binary. Second you would assume any consumer of that xml doc has the exact same If-Def defined. You would have to use the TFM instead, but TFM is quite different from if-defs which can be very custom (and most often are).

I think your suggestion comes from a point of view of .NET Standard usage. In that case, you wouldn't filter documentation, but make them different sections/paragraphs, so the user of the library would realize they need to do different things on different platforms with the same API.

**Comment by dotMorten** [comment]
An argument was made in the old thread that changing this was against the spec that states doc comments _have_ be to consecutive.

However I think the spec leaves plenty of room for interpretation here, and the way I read it, seems to support it's allowed.

> The conditional compilation directives are used to conditionally include or exclude portions of a source file.

If the section is excluded, that means the doc comments in fact does become consecutive.

> The selected conditional_section, if any, is processed as a normal input_section: the source code contained in the section must adhere to the lexical grammar; tokens are generated from the source code in the section; and pre-processing directives in the section have the prescribed effects.

and

> The remaining conditional_sections, if any, are processed as skipped_sections: except for pre-processing directives, the source code in the section need not adhere to the lexical grammar; 

After excluding/including the section, the source code now adheres to the lexical grammar.

These directives are called _pre_ processing for a reason. If you pre-process the code, then the documentation is in fact following the spec.

**Comment by FransBouma** [comment]
I ran into this today and it's odd that this happens at all. I'm with @dotMorten in that pre-processing should produce the actual lexical source processed by the lexer/parser and it's surprising that this doesn't work this way today.

Any news on this (but as this issue is rather old, I guess: nope) ?

**Comment by terrajobst** [comment]
@dotMorten 

> You would never need a "merged" xml doc, as the xml doc generated is specific to that binary. 

I was thinking about how we'd surface `#if` in documentation experiences that are produced from the .xml files (e.g. docs.microsoft.com). I guess considering that we basically don't use tripple slash comments as the source of truth for online docs it doesn't really matter.

**Comment by jnm2** [comment]
How do we not already have this? You can’t be serious:

```cs
#if NETSTANDARD1_3
        /// <summary>
        /// <para>
        /// Selects the ultimate shadowing property just like <see langword="dynamic"/> would,
        /// rather than throwing <see cref="AmbiguousMatchException"/>
        /// for properties that shadow properties of a different property type.
        /// </para>
        /// <para>
        /// If you request both public and nonpublic properties, every public property is preferred
        /// over every nonpublic property. It would violate the principle of least surprise for a
        /// derived class’s implementation detail to be chosen over the public API for a type.
        /// </para>
        /// </summary>
#elif NETSTANDARD1_6
        /// <summary>
        /// <para>
        /// Selects the ultimate shadowing property just like <see langword="dynamic"/> would,
        /// rather than throwing <see cref="AmbiguousMatchException"/>
        /// for properties that shadow properties of a different property type
        /// which is what <see cref="TypeInfo.GetProperty(string, BindingFlags)"/> does.
        /// </para>
        /// <para>
        /// If you request both public and nonpublic properties, every public property is preferred
        /// over every nonpublic property. It would violate the principle of least surprise for a
        /// derived class’s implementation detail to be chosen over the public API for a type.
        /// </para>
        /// </summary>
        /// <param name="type">See <see cref="TypeInfo.GetProperty(string, BindingFlags)"/>.</param>
        /// <param name="name">See <see cref="TypeInfo.GetProperty(string, BindingFlags)"/>.</param>
        /// <param name="bindingFlags">See <see cref="TypeInfo.GetProperty(string, BindingFlags)"/>.</param>
#else
        /// <summary>
        /// <para>
        /// Selects the ultimate shadowing property just like <see langword="dynamic"/> would,
        /// rather than throwing <see cref="AmbiguousMatchException"/>
        /// for properties that shadow properties of a different property type
        /// which is what <see cref="Type.GetProperty(string, BindingFlags)"/> does.
        /// </para>
        /// <para>
        /// If you request both public and nonpublic properties, every public property is preferred
        /// over every nonpublic property. It would violate the principle of least surprise for a
        /// derived class’s implementation detail to be chosen over the public API for a type.
        /// </para>
        /// </summary>
        /// <param name="type">See <see cref="Type.GetProperty(string, BindingFlags)"/>.</param>
        /// <param name="name">See <see cref="Type.GetProperty(string, BindingFlags)"/>.</param>
        /// <param name="bindingFlags">See <see cref="Type.GetProperty(string, BindingFlags)"/>.</param>
#endif
```

**Comment by CyrusNajmabadi** [comment]
> How do we not already have this? You can’t be serious:

Seems like you're the first to ever ask for it :)

**Comment by CyrusNajmabadi** [comment]
> However I think the spec leaves plenty of room for interpretation here, and the way I read it, seems to support it's allowed.

> These directives are called pre processing for a reason. If you pre-process the code, then the documentation is in fact following the spec.

The thing is, it's not really 'pre processing'.  It's in-situ processing.  That's why, for example, you can write the following:

```c#
Console.WriteLine(@"

#if false
This is all inside the string and will get printed to the console
#endif

");
```

If this truly were preprocessed, then the part between "#if false" and "#endif" would be entirely removed.  

Now, that said, i don't see any real problem with the compiler taking the sections of trivia that are doc comments, removing the disabled text sections, and doing final analysis as if it was one contiguous region of doc comments.

**Comment by jnm2** [comment]
> Seems like you're the first to ever ask for it :)

I'm sorry, I didn't mean that to sound harsh. @dotMorten says at the top this has been a source of pain for people for a long time. It just got real for me.

This should be easy to approve and then super easy to implement in roslyn, shouldn't it?

**Comment by jnm2** [comment]
> ```cs
> Console.WriteLine(@"
> 
> #if false
> This is all inside the string and will get printed to the console
> #endif
> 
> ");
> ```
> 
> If this truly were preprocessed, then the part between "#if false" and "#endif" would be entirely removed.

This just blew my mind. 😃

**Comment by CyrusNajmabadi** [comment]
> This should be easy to approve and then super easy to implement in roslyn, shouldn't it?

There would certainly be complexity.  Enough that i would not call it "super easy to implement".  For example, the lexer would have to have pretty interesting changes to it.  Consider the following simple case:

```c#
/// <Summary>
#if false
...
#endif
/// <Summary>
```

Recall that *currently* parsing of doc comments happens in situ with *trivia* scanning.  i.e. while you're in the middle of a scan, and you are handling trivia, we recursively go into parsing XML for the doc comment.  THis parse would then have to essentially pause and store state while it recursively handled the ```#if ar || bi && tra (ry) || (sub && expression)``` section.  Then, once it got out of the #if/#elif#else/#endif region it would have to pop back it's doc comment parsing state to continue.

Certainly doable.  But also something that would take methodical work to ensure that no bucks/strangeness what introduced while this happened.

This would also certainly change the roslyn parse tree model (a breaking change which we would have to accept).

Today, the above xml snippet would be three distinct trivia sections.  Now, you'd want it to be one section (so you could get one single structured trivia node out).

**Comment by dotMorten** [comment]
Only medium? Let's do it! 😁

@jnm2 your example does actually work. The trick is to if-def the ENTIRE XML doc section. However that usually means lots of duplicate XML doc to maintain when often it's just a single paragraph or less that needs to be tweaked for each platform.

**Comment by jnm2** [comment]
@dotMorten Yep, the example was what I was complaining about. 😃
