### ISSUE TITLE
Support for Range Get Enumerator

### ISSUE THREAD

**Issue by xCyborg** [dotnet/csharplang#2952]
I'd like to get you thoughts on this:
![image](https://user-images.githubusercontent.com/10322873/68632151-d5dcd080-04ed-11ea-88df-65580bc99094.png)
Would it be worthwhile to add GetEnumerator support for Range type so we can write the code above?

**Comment by KoziLord** [comment]
I'd rather see this be added to `for` loops, example:
`for (int i in 0..8)`
or with an optional iterator...
`for (int i in 0..8; i +=2)`

**Comment by jeroen-mostert** [comment]
`Enumerable.Range` already exists, and the `Range` type is more flexible than that -- the semantics of going through `^2..^0` are not clear. Is it an error? Does it go negative? (But then the resulting numbers aren't usable as indexes.) Does it produce a sequence of `Index`? (But then you need to call `.Value` for this case specifically, defeating the purpose of a shorter syntax.) `-2..0` is not allowed, as indexes can't be negative.

Allowing this as a `for` loop is discussed in #2810.

**Comment by HaloFour** [comment]
Ranges are also end-exclusive, so `foreach (var i in 0..5)` would produce numbers from 0 to 4.  This would be equivalent to `for (int i = 0; i < 5; i++)`.

**Comment by V0ldek** [comment]
If we allowed the `foreach` pattern to be implemented via extension methods, this would be a pretty easy change to include as a Nuget package. Just write your custom `GetEnumerator` extension on a Range. 
There's an old proposal for that which might or might not be dead:
https://github.com/dotnet/csharplang/issues/600

**Comment by khyperia** [comment]
> `Enumerable.Range` already exists

`Enumerable.Range` allocates, implementing IEnumerable for ranges (via struct iterator) would not. This is incredibly important for performance, and blocks a lot of use cases.

Also note that this isn't a C# language feature, but rather a library one - see https://github.com/dotnet/runtime/issues/462

**Comment by 333fred** [comment]
I'm closing this as not a C# issue. If someone would like `System.Range` to define a `GetEnumerator` method, the appropriate place for it would be on dotnet/runtime.
