### ISSUE TITLE
[question] why IoC used construct function?

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/csharplang#2958]
```csharp
public class IocTest1 {
    private readonly IIocMapper _iocMapper;
    private readonly IIocLogger _iocLogger;

    public IocTest1 (IIocMapper iocMapper, IIocLogger iocLogger) {
        _iocMapper = iocMapper;
        _iocLogger = iocLogger;
    }
}

public class IocTest2 {
    [AutoLoad]
    private readonly IIocMapper _iocMapper;
    [AutoLoad]
    private readonly IIocLogger _iocLogger;
}
```

I would like to know why the general IoC method is not automatically loaded as follows?

**Comment by fawdlstty** [comment]
or define a keyword:

`private readonly IIocMapper _iocMapper = _autoload_;`

**Comment by quinmars** [comment]
It sounds like you are looking for [MEF](https://docs.microsoft.com/de-de/dotnet/framework/mef/).

**Comment by yaakov-h** [comment]
Unity can also do the same for properties.

Regardless, this is really a library concern, and not related to the language.

**Comment by fawdlstty** [comment]
If placed in the library, enumeration will consume a lot of time; If you put it in a language, you can generate optimal IoC code, so I think it's a language issue

**Comment by DavidArno** [comment]
> ...If you put it in a language, you can generate optimal IoC code...

IoC is a runtime feature, not a compile-time one. Adding it to the language would result in the compiler generating code that would do that runtime resolution. So it would be no faster. IoC belongs in libraries, not the language.
