### ISSUE TITLE
[Proposal] Constructor Parameter Assignment

### ISSUE THREAD

**Issue by StaticSphere** [dotnet/csharplang#2961]
I'd love to see TypeScript's constructor parameter assignments pulled in to C#. So, instead of

```
private int _x;
private int _y;

public Rectangle(int x, int y)
{
  this._x = x;
  this._y = y;
}
```
you'd let the compiler do this:

```
public Rectangle(private int x, private int y)
{
}
```

Presumably, this would make x and y private properties, as opposed to fields, but if I wanted a field, then I'd use the existing syntax.

**Comment by YairHalberstadt** [comment]
Take a look at https://github.com/dotnet/csharplang/issues/2691 and the proposal that links to

**Comment by StaticSphere** [comment]
Sweet, thanks! I did some looking before posting this, but obviously missed it. I'll go ahead and close this issue.
