### ISSUE TITLE
Discriminated Unions Proposal

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#2962]
@agocke added a proposal for discriminated Unions a few hours ago. I wanted to make a few comments, but you can't comment on a proposal so I thought I'd make this issue to discuss.

The proposal is at https://github.com/dotnet/csharplang/blob/master/proposals/discriminated-unions.md

**Comment by YairHalberstadt** [comment]
### ValueType DUs

Are you considering ValueType DUs to help reduce allocations.

I think rust's design involving a union and a tag should work in c#, as it is possible to specify that fields in a struct should occupy the same location.

### Top Level Members

If the enum is represented as an abstract class, should it be possible to add top level members to the enum?

I think Niko Matsakis suggestions for DU improvements in Rust which I know @agocke has seen, do a good job of explaining the benefits of allowing this. I'll try to link them soon.

**Comment by YairHalberstadt** [comment]
I linked the blog posts in an earlier comment [here](https://github.com/dotnet/csharplang/issues/113#issuecomment-513532191)

**Comment by 333fred** [comment]
> If the enum is represented as an abstract class, should it be possible to add top level members to the enum?

Yes, we discussed this explicitly during LDM. The intent is that you can declare a regular partial part of enum Type and put anything you want in there. We also talked about ending the enum section with a semicolon (ie Java-style) and letting you put standard class stuff after that as well. We still need to design if/how base constructors would work in these scenarios, but it's very much on the table.

**Comment by Trayani** [comment]
I'm up for value-type unions and more importantly, for arbitrary type.
I mean, we can already do most of what is being proposed with interfaces and/or abstract classes.

What we cannot do is to make generic struct types for patterns like: result-or-exception, T-or-Array<T>, possibly even Value-or-Object.
We can already tinker with `[StructLayout(LayoutKind.Explicit)]` , but it is limited to non-generic values-only or classes-only. Could we get more support for this attribute?

**Comment by Richiban** [comment]
Really excited about this; Discriminated Unions are the one feature of any language that I sorely miss with C# and cannot really replicate using other means. Like your designs 👍 

I'm puzzled as to why these will differ from other types though in being `partial` by default. Is there any reason, perhaps one that's not listed in the proposal doc, as to why it would be undesirable or onerous to require the partial keyword?

**Comment by Joe4evr** [comment]
> I'm puzzled as to why these will differ from other types though in being `partial` by default. Is there any reason, perhaps one that's not listed in the proposal doc, as to why it would be undesirable or onerous to require the partial keyword?

The use of `partial` in proposals is just a thing done to keep sample code concise, though it makes a lot more sense when you're proposing to add new API to an existing type. I very much doubt it's actually required in the declaration (especially considering that `partial` is purely a design-time feature, there's no such thing in IL) and the grammar even lists it as `'partial'?` with the question mark indicating it's an optional term.

**Comment by agocke** [comment]
Just added the notes from our discussion of this proposal on Wednesday: https://github.com/dotnet/csharplang/issues/2968

re: struct discriminated unions, I think we should do them and there's a natural parallel here, but it's just out of scope for me right now. I'm trying not to design too many things at the same time

**Comment by Richiban** [comment]
@agocke Any thoughts yet on generic discriminated unions?

Since C# doesn't have a bottom type (aka Nothing or Never) it's not going to be possible to have a generic DU with non-generic cases (or cases with a different arity from the base). 

The easy example of this would be either `Option<T>` or a singly linked list.

**Comment by AartBluestoke** [comment]
> Open questions on the LDM: "Is switching against an argument with an enum class static type guaranteed to be constant-time?"  

I don't believe anywhere else the language spec talks about implementation constraints of O(N) vs O(log(N)). For small N, a Logn scaling implementation (or even hotpath optimisation based on frequency of occurrence from profiling) is often quicker than the overhead of guaranteeing a constant time implementation.

eg: https://github.com/dotnet/csharplang/blob/5dd11df6976beb761c68091cda13475f88ecd9a7/proposals/csharp-8.0/patterns.md
has a small section titled "some possible optimisations" as the only limitations on implementation within the runtime (other than re-ordering)

eg: how compilers implement non-enum switch statements with small (or large) numbers of branches. often "guaranteed constant time" involves some type of hash, jump and collision resolution, which would be more effort than log_2(n) nested if's.

**Comment by agocke** [comment]
@Richiban 

I expect you would define Option as essentially

```C#
enum class Option<T>
{
    Some(T t),
    None
}
```

It's true that you don't have a single None instance for all Option types, but I don't think it's that much of a problem. The only drawback I can see is that when mapping from an `Option<T>` to an `Option<U>` you have to explicitly map between Nones, which doesn't seem that bad.

**Comment by Richiban** [comment]
@agocke I thought as much.

Will there be any special type inference support, perhaps with https://github.com/dotnet/csharplang/issues/2926 (Name lookup for simple name when target type known)?

Basically, what I'd really like to avoid is having to write `Option<string>.None` everywhere, especially if it can be target-typed.

In C# `var x = None` is never going to work where a target type is not available, because you need either a bottom type (as previously mentioned, a la Kotlin, Scala etc) or to allow for generic values (a la Haskell and F#) which means that the generic parameter does not need to be inferred immediately, but can be left for later.

**Comment by agocke** [comment]
Right, `var x = None` won't work, but `Option<string> x = None` should work with #2926. It's not quite as short, but in C# we have a principle that we won't infer a type you can't say, and you can't give a variable an open type (`Option<> x`) in C#. Slightly more verbose but not crazy. In addition, if your return type is `Option<string>` you could just return `None` directly.

**Comment by orthoxerox** [comment]
@Richiban we *might* get a bottom type in some later version of C#, #538 has been championed.

@agocke any chance #538 could be re-triaged to the same milestone as DUs?

**Comment by agocke** [comment]
I don't see how a bottom type would help you in this scenario, since classes are invariant.

**Comment by Richiban** [comment]
As I said before, I'm very much looking forward to getting these DUs! There's a lot of work to be done in the future to make them fully featured, however. For example, this is how you properly model an `Option` in Kotlin.

```
public sealed class Option<out T>
    
public object None : Option<Nothing>()
public data class Some<T>(val value: T) : Option<T>()
```

Unfortunately it makes use of quite a number of features that C# doesn't have:

1. **Covariance in classes**. Necessary for an `Option<Banana>` to be assignable to `Option<Fruit>` etc.
2. **Free objects**. See: `None`. An object declaration is both a type and a value, i.e. a singleton. Can participate in inheritance hierarchies, as in this case.
3. **Sealed classes**. Necessary for the compiler to be able to prove completeness.
4. **Bottom type (Nothing)**. Allows the singleton `None`, in conjunction with (1), to be assignable to `Option<T>` for any `T`.

In addition, it uses a record (marked by the `data` keyword) that gives the `Some` class a public property, structural equality etc.

**Comment by agocke** [comment]
> Covariance in classes. Necessary for an Option<Banana> to be assignable to Option<Fruit> etc.

I don't think this is necessary for all use cases. I doubt this will be in V1 regardless, since variance is a part of the CLR type system and this would require also changing the CLR.

**Comment by gafter** [comment]
> Open questions on the LDM: "Is switching against an argument with an enum class static type guaranteed to be constant-time?"

FYI, our current expectation is yes.  More precisely, we expect amortized constant time performance based on runtime support that we are planning in .Net core 5.  Having said that, we cannot prevent someone else from supplying a "bad" runtime implementation that violates these expectations.

**Comment by orthoxerox** [comment]
Linking #113 (the championed issue)
