### ISSUE TITLE
Switch Expression Syntax with Block

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#2964]
Hi All,
How do I do the following in a switch expression?

````
var Value = input switch {
  0 => 0,
 //How do I do this part?
 _ => {
    var r = 1;
    return r;
  }
};

````

Thanks so much!

**Comment by spydacarnage** [comment]
You can't, basically.

If you just want to return 1, you can just write _ => 1

If you want to set the variable r as well as Value, but only if input isn't
0, you can't. Even if that was valid, r would only have scope within the
block, and wouldn't carry on past the switch expression.

**Comment by TonyValenti** [comment]
Interesting!  Based on the ````=>```` syntax, I really perceived that what was on the right hand was an anonymous function which would allow block style syntax.  From what I'm hearing, that is not correct though.

Am I right?

**Comment by spydacarnage** [comment]
No, you're not allowed blocks; only simple expressions.

If you need to do some calculation work and then return a single value, you
can create a local function and use that as the expression to return, but
that still wouldn't be able to set a second variable.

**Comment by HaloFour** [comment]
There are some proposals to explore allowing multiple statements to act as an expression:

https://github.com/dotnet/csharplang/issues/377

**Comment by gafter** [comment]
Either #377 or define a local function and call it.

**Comment by YairHalberstadt** [comment]
Closing as championed at https://github.com/dotnet/csharplang/issues/3037
