### ISSUE TITLE
Check if Type is Interface

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#2965]
What is the correct way for me to do the following with generics?

````
public static void Foo<T>() {
  if(T is BaseClass U){
    Foo2<U>();
  } else {
    Foo1<T>();
  }
}

public static void Foo1<T>() {

}

public static void Foo2<T>() where T:BaseClass {

}
````

**Comment by CyrusNajmabadi** [comment]
you'll have to use reflection.  I'd recommend sending these questions to gitter.im/dotnet/csharplang (or roslyn), or using discord :)
