### ISSUE TITLE
Prevent value type from being used in Nullable<T>

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#2969]
This is relatively minor but I've run into it a couple times recently. My initial thought process is that this may not be possible to do gracefully (causes complications with generics) and/or may not be worth the effort but I figured I would put it out there to see what other people's thoughts are. There may also be some clever trick to do this that I'm not seeing at the moment.

If a value type has a suitable "empty" default value then it would be nice to prevent it from being used in nullable as this is almost certainly undesirable. For example, we have a `Range32` struct with a `Range32.Empty` value that is equal to the default value, so it doesn't make much sense to allow people to do `Range32?` or `Nullable<Range32>`.

In terms of syntax, could be something like one of these:

```c#
struct Range32! // ! can indicate "don't allow nullable usage"
{
} 

struct Range32? // ? can indicate "this type already kinda has its own nullable behavior"
{
} 
```

It's easy to catch violations when the type is used directly but the biggest problem I see with this is enforcing it on generics, i.e: 

```c#
public class SomeClass<T> where T : struct
{
    public T? NullableValue { get; }
}
```
Is it wise to prevent someone from doing `SomeClass<Range32>`? I suspect that may have unintended consequences. There might be a graceful solution I'm not thinking of at the moment.

**Comment by theunrepentantgeek** [comment]
This would seem to be an ideal application for a custom analyzer, one that catches use of `Nullable<Range32>` and flags it with a warning.

No need for special syntax, just using the extension points already present.

**Comment by mikernet** [comment]
@theunrepentantgeek I forgot to suggest that it is probably better to make it a warning instead of an error, which would effectively make it an error if you treat warnings as errors. I think you're definitely right though. I'm not sure why I didn't think about writing a custom analyzer which can do just that, so great suggestion! Thanks :)

**Comment by sharwell** [comment]
Note that for the analyzer approach, you would also need to verify that the struct didn't get passed as a generic type argument when the generic parameter has the `struct` or `unmanaged` constraint.

**Comment by mikernet** [comment]
@sharwell The problem with that is that many (most?) types and methods that use a `struct` constraint do not actually use the type as a nullable and having warnings that need to be suppressed in all those places might be a bit annoying and overbearing. 

We will probably still add a custom analyzer to catch direct uses of nullable value types that probably shouldn't be nullable but the generic case is the one that tends to slip through code reviews because it can be a lot more subtle. 

The particular case that sparked this issue was a generic serialization method akin to `WriteOptionalValue<T>(T? value)` which was used instead of `WriteValue<T>(T value)` to write out potentially empty ranges, causing an unnecessary extra byte to be written out as well as another related issue that significantly affected efficiency. If this method was used directly then the custom analyzer would have an easy time catching it but it was used a bit deeper than that through a generic type heirarchy. Then there are interfaces and things of that sort which make it virtually impossible to track type nullable usage.

I've come to the conclusion that anything more than simple analysis of direct `Nullable<T>` usage without better type support is a losing battle.
