### ISSUE TITLE
Generic sub-type constraint not working with nullable features of c# 8

### ISSUE THREAD

**Issue by staa99** [dotnet/csharplang#2971]
I have done some searching and I found no useful results. I originally posted this on SO.

How do you specify that a generic reference type is nullable when a subclass constraint is used in c# 8?

I know quite well that it is sufficient to add where T: class to specify that a generic Type parameter T is a reference type. This way, the nullable reference annotations and warning features of c# 8 will work perfectly.

However, there's the case where the generic type parameter T is a sub-type of another class, say SomeClass. Now, when you add where T: SomeClass, you are basically telling the compiler that T is a reference type which is a sub-type of SomeClass, since a value type cannot be a sub-type of a reference type. However, the compiler doesn't seem to understand this when it comes to the nullable reference annotations and warning features of c# 8. How do you make it clear to the compiler?

Want to see some code? This is what I mean:
```
// this compiles
class ClassA<T> where T: class
{
    public GenericType<T?> DoSomething()
    {
        thrown new NotImplementedException();
    }
}
```

```
// this doesn't compile, but SomeClass is a class and it should work
class ClassA<T> where T: SomeClass
{
    // here, you get the classic:
    // Only non-nullable value type could be underlying of 'System.Nullable'
    // What this makes clear is that the compiler doesn't understand that
    // T is strictly a reference Type now
    public GenericType<T?> DoSomething()
    {
        thrown new NotImplementedException();
    }
}
```
Thanks

**Comment by staa99** [comment]
Kindly note that I already enabled the nullable feature, and the issue appears to be because the implementation of the nullable feature doesn't treat that particular case.

**Comment by staa99** [comment]
Oh, it appears this was actually an intellisense issue, it compiles just fine.

**Comment by staa99** [comment]
I closed it since it's actually a Resharper intellisense issue

**Comment by dgadelha** [comment]
same here, running `Invalidate Caches / Restart` -> `Invalidate and Restart` on Rider fixed the problem
