### ISSUE TITLE
Discussion: Recursive property patterns and generic types

### ISSUE THREAD

**Issue by HaloFour** [dotnet/csharplang#2974]
@Suchiman noticed that currently C# doesn't allow you to use a recursive property pattern with a generic type within a generic method.  However, you can use type switch and recursive positional patterns.  This seems like an odd omission.  Is there a plan to allow for recursive property patterns with generic types in the future?

```cs
public class Foo<T> {
    public int Bar { get; set; } = 0;
    
    public void Deconstruct(out int x, out int y) {
        x = 1;
        y = 2;
    }
}

public class C {
    public void M<T>(object o) {
        // all work
        if (o is Foo<int>) { }
        if (o is Foo<int> f1) { }
        if (o is Foo<int>(1, 2)) { }
        if (o is Foo<int> { Bar: 0 }) { }
        
        // also work
        if (o is Foo<T>) { }
        if (o is Foo<T> f2) { }
        if (o is Foo<T>(1, 2)) { }
        
        // doesn't work?
        if (o is Foo<T> { Bar : 0 }) { }
    }
}
```

**Comment by svick** [comment]
I believe this is a duplicate of https://github.com/dotnet/roslyn/issues/38121, which is already fixed in master. And your code compiles fine for me with .Net Core SDK version 5.0.100-alpha1-013867.

**Comment by HaloFour** [comment]
Sweet.  That felt like it would have been a very strange omission.  Thanks!
