### ISSUE TITLE
Revise spec for C# 7.6.2.1 Invariant meaning in blocks

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#298]
Please revise the C# language specification section 7.6.2.1 according to the changes we made in Roslyn. See also https://github.com/Microsoft/CodeContracts/pull/209

**Comment by BillWagner** [comment]
@gafter @MadsTorgersen 

I can't find the quoted text from the link above.  Has this been fixed?

**Comment by BillWagner** [comment]
The reference above refers to [12.8.4](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#1284-simple-names). The subclause on invariant meaning in blocks has been removed in the standard. I believe this can be closed, but I'll wait for @MadsTorgersen to confirm.

**Comment by MadsTorgersen** [comment]
I agree that this can be closed.
