### ISSUE TITLE
Enabling nullable reference context forces too many "?" suffixes.

### ISSUE THREAD

**Issue by Yen-David** [dotnet/csharplang#2983]
Both "string" and "int" should indicate default behaviors, while "string?" and "int?" indicate nullable types and "string!" and "int!" indicate non-nullable types, for syntactical consistency. Defaults should be set as follows, to adhere to Internet protocol conventions, loose on inputs and strict on outputs, given that most API's prefer location transparency, local and remote alike: (1) inputs default to nullable and outputs to non-nullable; (2) returns and getters default to non-nullable to make null propagation optional, while out parameters and setters default to nullable for default values, especially in the case of TryXXX() methods, which make all nullable returns obsolete; (3) public and protected member inputs default to nullable for caller-friendliness and Internet-friendliness, as all inputs should be optional and have good defaults, while internal and private member inputs to non-nullable, as nulls should be handled at the "public surface".

This way, we can eliminate most type suffixes and encourage a very well-behaving API design.

**Comment by yaakov-h** [comment]
This is inconsistent and confusing. The definition of a type shouldn't have a different meaning when used in a different context.

It's also a breaking change with little benefit if any, so it's likely dead in the water from the get-go.

**Comment by HaloFour** [comment]
This feature has already shipped so it's quite a bit too late to redesign it.  The current design is based on several years worth of open discussions on these forums.

**Comment by Yen-David** [comment]
I am making a new class library using the new nullable context, which must be enabled in the project file to take effect showing how intrusive the breaking change is (the change of the interpretation of "string" from a nullable one to a non-nullable one. However, if this breaking change will be eventually imposed on all C# projects, instead of being an option, I am okay. That the nullable context remains an option is my fear, because we end up with two extremes of C# developers, like Democrats and Republicans, impossible to reconcile.

**Comment by CyrusNajmabadi** [comment]
> to take effect showing how intrusive the breaking change is

There should be no breaking change with this feature.

> (the change of the interpretation of "string" from a nullable one to a non-nullable one

The language never changed the interpretation for existing code.  The only way to get it to think of an existing type as nullable, is to *change* your code/project somehow (i.e. using `#nullable` or changing your project file).  So tehre is no break here since you always made a change *yourself* to ask for these semantics.  

Breaks occur when teh meaning of *previous* code changes, where all you did was move to a newer compiler.  That's not what's happening here, so there is no break.

**Comment by CyrusNajmabadi** [comment]
> However, if this breaking change will be eventually imposed on all C# projects, instead of being an option, I am okay.

This is unlikely to ever happen (or at least, is so far out as to not be relevant).  The ability to compile existing code with the same meaning is a core promise that C#/Roslyn makes.

**Comment by CyrusNajmabadi** [comment]
> That the nullable context remains an option is my fear, because we end up with two extremes of C# developers

There should be no extremes going on.  Both camps can write code that interoperates with each other.  Non-nullable code can import and use nullable code (and vice versa).  The feature was very carefully designed to ensure that that woudl be entirely possible.

**Comment by Yen-David** [comment]
So, I am making a new library. Should I turn the option on or not? Why not make it a default for all new C# projects? Why must I turn it on manually every time, if it's that good? I am afraid that this feature would not last, subject to fierce changes in the new few years, up to 2023 when .Net 8 is shipped.

**Comment by MgSam** [comment]
> So, I am making a new library. Should I turn the option on or not? Why not make it a default for all new C# projects? Why must I turn it on manually every time, if it's that good? I am afraid that this feature would not last, subject to fierce changes in the next few years, up to 2023 when .Net 8 is shipped.

This is an excellent point. The vast majority of developers never change the default settings. I'd be really interested to see statistics on usage of this feature several years after the fact.

**Comment by yaakov-h** [comment]
I'm pretty sure the intent is to change the default before those several years are up...

**Comment by ronnygunawan** [comment]
> So, I am making a new library. Should I turn the option on or not? Why not make it a default for all new C# projects? Why must I turn it on manually every time, if it's that good? I am afraid that this feature would not last, subject to fierce changes in the next few years, up to 2023 when .Net 8 is shipped.

Even if you write the library with nullable turned off, you can multi-target your library to include netstandard2.1 and then annotate your public parameters with [AllowNull] attribute. That way you can provide support to developers who want to use your library with NRT analysis enabled.

**Comment by yaakov-h** [comment]
You can also technically annotate your library even if its target framework is older/earlier than netstandard2.1/netcoreapp3.0... 😉

**Comment by Yen-David** [comment]
That's funny. If I complain about too many "?"'s as type suffixes, I won't mind too many annotations like [AllowNull]'s? I'm trying to type less. That's all. As a matter of fact, you can't stop people from missing parameters on the Internet, which explains why you need to have good defaults for all parameters, even the method names themselves. Nulls are perfect for this purpose. Your default is to disallow nulls. That's the problem!

**Comment by HaloFour** [comment]
C# isn't the Internet.  Most methods don't and can't accept `null`.  Defaulting to non-null reduces the need to annotate the majority of the language.

**Comment by Yen-David** [comment]
No, it's just a design mentality. C# methods should accept nulls 99.99% of the time, including default properties and methods. It's okay. I am not complaining anymore, because I now sound like the extreme minority. You can close the issue if you want. I still prefer the trio syntax "string!", "string" and "string?" for back compatibility, however. You can have "int!", "int" and "int?" for syntactical consistency. If you program in C++, you realize that nothing is nullable by default, until you make it a pointer! If you do make it a pointer, then everything is nullable by default. Early C++ is perfect as a language in terms of syntactical consistency except that it doesn't have a standard GC like .Net.

**Comment by Yen-David** [comment]
I'm going to make a new programming language, maybe called I# for Internet programming, or U# for union-based set & logic programming, or even better, U&I# for both, all on .Net 5. Hmm... I just don't know when I will start or even finish.

**Comment by HaloFour** [comment]
> C# methods should accept nulls 99.999% of the time, including default properties and methods.

I disagree with this and in my experience so do most languages and runtimes.  Defaulting to some value in the case of missing or invalid input is dangerous, moreso that failing fast.  The majority of the .NET BCL, and most of the third-party libraries, expect reference parameters to be not-`null`.  And even if the library can gracefully defend against `null`, odds are more likely than not that if the consuming code is passing `null` that it's due to an error on their end, so silently doing something is not a good thing.

I'd suggest that even if you feel that your libraries can gracefully handle `null` that you still keep your reference parameters as non-nullable except in those cases where you explicitly expect that a consumer will be passing `null`.  Even if your code can defend against the `null` and degrade gracefully to some default behavior it's likely to help consumers of your libraries identify bugs in their own code.

**Comment by Yen-David** [comment]
Most coders who want a GC don't want to be as careful as you wish. If you forgive nulls and replace them with good defaults silently, they will love you more. If your coders want to be that careful, they should program in C++ and forgo any GC. You want to be either careful or careless, because any half way through or middle ground between the two spawns a fierce battlefield. People get confused.

However, you're right. There are those who love a GC but hate nulls, for some reason.

**Comment by YairHalberstadt** [comment]
I love a GC because I'm not a good enough programmer to make sure I manage memory correctly, and I don't want to have undefined behaviour going on without me realising it.

I love methods which throw when I pass in null because *I'm not a good enough programmer to make sure I don't accidentally get null in some places where I don't expect it*, and I don't want unexpected behaviour going on without me realising it.

**Comment by HaloFour** [comment]
> Most coders who want a GC don't want to be as careful as you wish. 

GC has nothing to do with it.  I've not seen a garbage collected language that behaves as you describe.  Afterall, how can you open a file with a name of `null`?  Or download a file from a URL of `null`?  Most of the time there's logically nothing you can do when handed a `null`.  The correct thing to do is to fail quickly with an appropriate exception that describes why the call failed.

The same is true of the Internet, which is why 4xx series HTTP status codes exist, especially 400 and 404.

**Comment by theunrepentantgeek** [comment]
>  If you forgive nulls and replace them with good defaults silently, they will love you more.

In my experience, this is an extremely good way to introduce subtle bugs throughout your code.

There's a reason that **fail fast** is almost universally accepted as best practice.

By all means apply [The Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle) _at the edges_ of your subsystems - I do this myself.

But internally, within that boundary? Not on your life. Never. No how. Everything is rigorous, or an exception is thrown.

**Comment by Yen-David** [comment]
I agree. If you're talking about URI's, including file paths and URL's, for sure, they don't accept nulls. However, 90% of parameters, meaning the extra options, do accept nulls. Do you overload relentlessly, or use default parameter values gracefully? When I say 99.999%, I mean most methods don't take URI's.

**Comment by HaloFour** [comment]
> However, 90% of parameters, meaning the extra options, do accept nulls.

My experience is the direct opposite of this.

> Do you overload relentlessly, or use default parameter values gracefully?

Where it makes sense, yes.

If this is the coding pattern you follow I think you will find yourself in the minority and fighting against the design of the feature which was to meet the needs of the majority of developers.  But, as I mentioned, even if you do explicitly permit `null` and handle them gracefully you're more than likely doing your consumers a favor by leaving those parameters as not-nullable.

**Comment by Yen-David** [comment]
It's okay. Default behaviors are language-dependent and not framework-dependent. I am just experimenting with something, possibly a GUI-based language like visual programming. If you are sure that most C# coders will love your new syntax, please go for it. However, not making nullable reference context a default for brand new C# projects indicates that deep down, you aren't too sure.

**Comment by HaloFour** [comment]
@Yen-David 

> However, not making nullable reference context a default for brand new C# projects indicates that deep down, you aren't too sure.

It indicates that as a fairly major change to the .NET type system that it's desirable to have a period of transition during which projects can opt-in to the new behaviors as they make any necessary changes to their code.  It's also to allow for the language team to adjust some of the analysis based on patterns that are identified after launching C# 8.0.

The majority of code that accepts reference parameters can and does throw when you pass a `null`.  Defaulting to nullable for parameters not only wouldn't address this, it would also require the majority of developers annotate the majority of their code to indicate what it already does.  That would be a poor design choice.

**Comment by Yen-David** [comment]
@HaloFour, good to hear that you eventually want to make nullable reference context mandatory. I'm just worried that you might cut it if people don't embrace it as you wish. Sacrificing 5% of developers is always okay, but I don't want to be one of them. I am protecting all my fields and variables with my own structs against new changes, for now. It's just a base library for GUI-based visual programming, where customers set their rules, policies and best practices. I'd rather avoid code politics. The fights are endless...

**Comment by ronnygunawan** [comment]
> That's funny. If I complain about too many "?"'s as type suffixes, I won't mind too many annotations like [AllowNull]'s? I'm trying to type less. That's all.

With the method I mentioned, you only have to annotate your **publicly exposed parameters**, not everything in your library. That's significant.

**Comment by Yen-David** [comment]
When COM wasn't good enough, .Net was born. When .Net isn't good enough, UI# is born! It's time to focus on a new platform. Let bygones be bygones. Let hydrogen be hydrogen, and anti-hydrogen anti-hydrogen. Null or not null, what say you?

For example, "bool TryParse(string? input, [NotNullWhen(returnValue: true)] out double? result)". Why is "string?" nullable? Well, it's because you don't want to piss off callers, new and old. Why keep on denying if you know deep down that I am right? We aren't teenagers anymore. The Internet is right: forgiving on inputs and relentlessly strict on outputs!

Anyway, I agreed not to disagree anymore. Shall we close the issue? You and I can both do it. I won't object.

**Comment by HaloFour** [comment]
> Why keep on denying if you know deep down that I am right?

Simple, because you're not.  The vast majority of code isn't `TryParse`, nor should it be.  Graceful degradation is a great thing, but implicit behavior on illegal input is a horrible thing, and violating a contract should fail fast rather than do what will almost invariably be the wrong thing.

> The Internet is right

Go try to enter a bunch of random Strings into the address bar of your browser and see how true that is.  404 is the Internet's `NullReferenceException`, and it is also the most common error you'll experience on the Internet.  400 is the Internet's `ArgumentException`, and it's easily the second most common error.  A web site that doesn't vigorously validate input is a web site supplying usernames and passwords to hoards of hackers.

**Comment by Randy-Buchholz** [comment]
> Defaults should be set as follows, to adhere to Internet protocol conventions, loose on inputs and strict on outputs, 

We've been trying to dig out of the problems this pholosophy caused for decades.

**Comment by Yen-David** [comment]
@HaloFour, my observation today from .Net BCL is that FP tends to be null-tolerant and OOP null-intolerant. It seems to have more to do with possible side effects and the fundamental understanding of a reference. If a reference refers to a state, it shouldn't be null. However, if it refers to a value, nullability is great.

URI's are different. URI's can never be null. We already agreed on that. They are identities, neither states nor values.

**Comment by CyrusNajmabadi** [comment]
> FP tends to be null-tolerant

That's def not the case.  FP doesn't generally even have null.  It will use things like sum-types to represent an option that may or may not be there.  Code must then handle this.  It cannot ignore it.  This "you must be explicit about what you take and you must handle either having the value or not" is what NRT pushes .net closer to.

**Comment by CyrusNajmabadi** [comment]
> It's time to focus on a new platform

Sure.  Feel free to go suggest this for new platforms.  .net is not a new platform.  It's nearly 20 years old and has a long commitment to back-compat and gentle progress.  

Your concerns were considered and taken into account with the designs and implementation of NRT over the past 4 years.  They were rejected.  These issues aren't going to be relitigated.

**Comment by Yen-David** [comment]
@CyrusNajmabadi, hey, you're back! SQL is very null-tolerant. Sum() works well on nulls.

**Comment by HaloFour** [comment]
> FP tends to be null-tolerant

FP is certainly not null-tolerant.  Most FP languages have no concept of null.  The closest you get is a Maybe/Option monad, and every parameter needs to be explicitly declared to accept that type, and the method needs to explicitly unwrap the underlying value.  A partial match on `None` will fail.  FPs built on OOP frameworks (like F# on .NET or Scala on JRE) generally handle `null` exceptionally poorly (pun intended) because they assume that `null` can't happen.

> SQL is very null-tolerant.

NULL in SQL is a very different concept from `null` in OOP.  And generally NULL is to be avoided via constraints.  Trying to pass NULL to a table that doesn't accept NULL will fail, as it should.  NULL is viral, in that anything + NULL is NULL, so NULL easily pollutes aggregates.  RDBMSes are certainly one place where one must not gracefully degrade on the case of NULL.  MySQL used to implicitly insert a default value when trying to insert a NULL into a NOT NULL field and it was universally ridiculed for it and that is now disallowed by default.

**Comment by Yen-David** [comment]
@HaloFour, Maybe/Option is null-tolerant, because it accepts nulls and forces a check before reading. SQL is fantastic with nulls, because you always have to keep nulls in mind, such as Sum(Case When...) where a null check is always the first case to handle. That's what I mean by null tolerance, because you expect nulls to happen everywhere in your code. This way, callers of your libraries don't need to worry much about nulls. So, we essentially agree with each other.

**Comment by CyrusNajmabadi** [comment]
> SQL is very null-tolerant

Not in my experience.  We definitely don't alow them to get into our DBs at all.

**Comment by CyrusNajmabadi** [comment]
> @HaloFour, Maybe/Option is null-tolerant, because it accepts nulls and forces a check before reading. 

It's not tolerant.  You can't even pass 'null' along.  You must pass something Some or None.  Nulls cannot sneak in as something in the same domain as your T.

**Comment by Yen-David** [comment]
@CyrusNajmabadi, what's a domain? It's just a type check, no? Can the "is" keyword allow a null to pass? Hey, but you ARE CHECKING IT (what I mean by null tolerance)! You see, in SQL, you get an array of nullable elements. How can you fail the entire array or throw an Exception just because one element fails? That's just too null-intolerant!

Okay, I'm done today. It's 9 pm here already. I need to go to bed soon.

**Comment by CyrusNajmabadi** [comment]
> what's a domain? 

The set of values that are allowed by your type.  In most FP systems, 'null' is not in the domain of a type.

> Can the "is" keyword allow a null to pass?

No. 

> You see, in SQL

SQL is not relevant to the discussion.  It's one language.  It's not a language .net is trying to model it's type system after.

> How can you fail the entire array or throw an Exception just because one element fails?

I'm not understanding your question.  Are you asking mechanically?  It's pretty simple, you check for null, and you throw.  

> That's just too null-intolerant!

Then don't do it.  No one is forcing you to.  If you want to be null-tolerant, be null-tolerant.

**Comment by Yen-David** [comment]
@CyrusNajmabadi, you're getting too serious. So, it's my turn to keep it simple.

1. We don't do SQL in .Net. (But, don't we have Linq?)
2. We don't do nulls in SQL. (But, don't we have left/right joins?)
3. We throw null exceptions if that's the case. (But, don't we try to save trillions/gazillions of CPU cycles by trying not to throw a null exception after a mere single null in the grids?)
4. We don't scale to billions or trillions of objects with .Net. (But, don't we still handle millions of objects in .Net every day?)

That's right. We don't want to waste billions of CPU cycles with a null exception. We want to be null-tolerant by handling them gracefully. Nulls form an integral part of computation, just like zeroes in mathematics. We don't ban zeroes, do we?

**Comment by Yen-David** [comment]
@CyrusNajmabadi, a joke just came to mind. We don't fail the entire humanity just because one single Adam sins. That's unfair!

**Comment by yaakov-h** [comment]
@Yen-David Objective-C tried to ignore/propagate `nil` values (the equivalent of `null`) and it was so awful overall that Apple went completely the other direction with Swift and replaced it with the `Optional<T>` behaviour that @CyrusNajmabadi described above.

Let's _not_ relive that experience in C#.

**Comment by theunrepentantgeek** [comment]
Tony Hoare invented **null** and here's what he has said about it in 2009:

> I call it my billion-dollar mistake. It was the invention of the null reference in 1965. At that time, I was designing the first comprehensive type system for references in an object oriented language (ALGOL W). My goal was to ensure that all use of references should be absolutely safe, with checking performed automatically by the compiler. But I couldn't resist the temptation to put in a null reference, simply because it was so easy to implement. This has led to innumerable errors, vulnerabilities, and system crashes, which have probably caused a billion dollars of pain and damage in the last forty years.

Research I've read indicates the true cost to the economy as in excess of $US 1 billion dollars to the US Economy alone ... _each year_.

Sure, **null** has it's place. There are situations where it's very useful. 

But, **null** is not universally appropriate and to assert that it is ignores 50 years of history.

**Comment by CyrusNajmabadi** [comment]
> We don't do SQL in .Net. 

Correct. 

> We don't do nulls in SQL.

What sql does is not relevant here.  C# and .net are not looking to sql for their null semantics.

> We throw null exceptions if that's the case. (But, don't we try to save trillions/gazillions of CPU cycles by trying not to throw a null exception after a mere single null in the grids?)

No.  We want to eliminate nulls for sneaking in as much as we can given the design of the language/platform over the last 20 years.

> We don't scale to billions or trillions of objects with .Net. 

I have no idea what this means.

> We want to be null-tolerant by handling them gracefully. 

No.  We don't.

>  Nulls form an integral part of computation, just like zeroes in mathematics.

We do not want nulls to be in the domains of types.  More often than not they are *not* an integral part of computation.  So the language is moving to match waht is more common and normal and safe.

**Comment by Yen-David** [comment]
@yaakov-h, I agree with you. We accept null in inputs and replace them with good defaults without ever propagating them. Good defaults, instead of null exceptions, can be the remedy.

**Comment by CyrusNajmabadi** [comment]
> Good defaults, instead of null exceptions, can be the remedy

You're welcome to make that change in your own libraries.  There won't be any changes in the core language or APIs in this regard.

**Comment by Yen-David** [comment]
@CyrusNajmabadi, shall we close the issue now?

**Comment by CyrusNajmabadi** [comment]
> Good defaults, instead of null exceptions, can be the remedy

You're welcome to make that change in your own libraries.  There won't be any changes in the core language or APIs in this regard.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi, shall we close the issue now?

It's up to you.

**Comment by Yen-David** [comment]
Sure thing, good night for now!
