### ISSUE TITLE
Extend pattern matching for non-constant values

### ISSUE THREAD

**Issue by setbbtjl8wwq** [dotnet/csharplang#2984]
At the current moment native C# pattern matching expressions works only with constant values.
Some time ago introduction #2850 into C# 9 pattern matching had been published.
There is a scope of new features but all of them are constant based too.

For example, possible, this is will be valid syntax
```cs
bool IsValidAge(int x) => x is (>= 0 and <10) or (>= 20 and < 30) or (== 25);
```
The kind of a condition is not very necessary but there is a unobvious problem when we try to replace some hardcoded values
```cs
/* compile error */
bool IsValidAge(int x) => x is (>= 0 and <10) or (>= 20 and < 30) or (== Settings.MagicAge);
```
Because non-constant values is not supported we forced to mix different code styles or even rewrite the full pattern matching expression into old style manner
```cs
/* mixing of code styles */
bool IsValidAge(int x) => x is (>= 0 and <10) or (>= 20 and x < 30) || x == Settings.MagicAge;

/* avoiding of pattern matching */
bool IsValidAge(int x) => (x >= 0 && x <10) || (x >= 20 && x < 30) || x == Settings.MagicAge;
```
---------
It will be nice if pattern matching will be support non-constant expressions too, for example

```cs
if (x is 25) ...

var y = 25;
if (x is y) ...
```

**Comment by gafter** [comment]
Expressions are not "old style" and patterns "new style", not are patterns somehow "preferred" to expressions.  Both are part of the language and each has its place.  Patterns are a way of expressing tests in which the language can more efficiently perform the analysis by relaxing order of evaluation and determining the relationship between the constants matched.  These simply do not apply to general non-constant values.  Expressions work fine to express these situations, and expressions should continue to be used to write them.
