### ISSUE TITLE
Switch expression "Cannot resolve symbol" new variable 

### ISSUE THREAD

**Issue by lekia** [dotnet/csharplang#2990]
![Annotation 2019-11-26 102143](https://user-images.githubusercontent.com/11898314/69594428-47149b80-1037-11ea-9510-d21ae151e732.jpg)
![Annotation 2019-11-26 102501](https://user-images.githubusercontent.com/11898314/69594430-4845c880-1037-11ea-8423-bb131ae2fc40.jpg)

That's quite embarrassed. New variables can be declared but cannot be used. (So does it using "when" clause.)
`                    obj = obj switch
                        {
                        _ => int.TryParse(index, out var intIndex) ? intIndex : 0
                        };
`
`                    obj = obj switch
                        {
                        _ => int.TryParse(index, out var intIndex) ? int.TryParse(index, out var intIndex) ? intIndex : 0: 0
                        };`

Lagacy switch works as usual.
`
                    switch (obj)
                    {
                        default: obj = int.TryParse(index, out var intIndex) ? intIndex : 0;
                            break;
                    }`

And it works as well if we simply leave the variable alone and parse the string again.
`
                    obj = obj switch
                        {
                        _ => int.TryParse(index, out var intIndex) ? int.Parse(index) : 0
                        };`

**Comment by 333fred** [comment]
For that first example, `obj = obj switch { _ => int.TryParse(index, out var intIndex) ? intIndex : 0 };`, I'm not seeing that in VS 2019 Update 3:
![image](https://user-images.githubusercontent.com/2371880/69596208-dab28180-0fcf-11ea-81df-741c6c3575ef.png)
Do you have an extension installed that doesn't understand it? It looks like it could be Resharper, you'll probably want to update to one of their EAPs. Note that there's no compile error there: if hit build it will compile just fine.

For that second example, you've declared `intIndex` twice. See how the second declaration is squiggled? That's an actual compile error, unlike the first example. VS does not make text red when there's an error, it just squiggles under the text there's an error at.

**Comment by lekia** [comment]
> For that first example, `obj = obj switch { _ => int.TryParse(index, out var intIndex) ? intIndex : 0 };`, I'm not seeing that in VS 2019 Update 3:
> ![image](https://user-images.githubusercontent.com/2371880/69596208-dab28180-0fcf-11ea-81df-741c6c3575ef.png)
> Do you have an extension installed that doesn't understand it? It looks like it could be Resharper, you'll probably want to update to one of their EAPs. Note that there's no compile error there: if you hit build it will compile just fine.
> 
> For that second example, you've declared `intIndex` twice. See how the second declaration is squiggled? That's an actual compile error, unlike the first example. VS does not make text red when there's an error, it just squiggles under the text there's an error at.

Maybe it was the old R#'s bad. I havn't compiled it yet because I have lots of errors to resolve... But this kind of errors gets really confusing since I don't know if they are real errors. You said that it has nothing to do with C# or VS so I close this question.

For the second one, I know that's an error and I did this on purpose to show that the variable is declared (since it won't allow me to declare again) and VS knew the variable did existed, but it just didn't allow me to use it.
