### ISSUE TITLE
Proposal: inferred type construction

### ISSUE THREAD

**Issue by LegoCylon** [dotnet/csharplang#2994]
C# 7.1 recently added support for deducing the type of default given contextual information (i.e. the left hand side of an assignment expression).

It would save a lot of redundant typing to be able to do the same with new so long as the type can be inferred from the context:
```csharp
float f = new; // equivalent for value types to default or default(T)
StringBuilder sb = new; // equivalent for reference types to new T()
```

Ideally it should support parameter passing as usual:
```csharp
string s = new("-", 5); // produces "-----" just like new string("-", 5) would.
```

It should also work as default does when passing arguments to unambiguous parameters:
```csharp
StringBuilder sb = new;
sb.AppendLine(new("-", 5)); // As above
```

And in field/property initializers:
```csharp
public class Example {
    public StringBuilder m_field = new;
    public string Property { get; set; } = new;
}
```

While a good IDE can infer the type for you and save typing, eliminating a redundant type with inferred new means that you can avoid accidental conversions (when possible) and unlike default ensure that you have a valid variable to use regardless of whether it's a value or reference type.

From an implementation point of view, I believe it should just be syntactic sugar for the actual type, similar to the default literal.

**Comment by DavidArno** [comment]
See #100. This is currently planned (but obviously subject to change) for v9.

**Comment by LegoCylon** [comment]
Awesome news. I'll close this as a duplicate. Thank you!
