### ISSUE TITLE
Proposal: Enumerable enums

### ISSUE THREAD

**Issue by LegoCylon** [dotnet/csharplang#2998]
I often want to be able to use a foreach over all the values in an enum type. These are some options I've found to accomplish this task but they all require compromises:
- Add a "Count" value to the end of the enum and either use a for loop or foreach with Enumerable.Range and the count value. However, this has the downside of needing to cast both ways between int & the enum as well as requiring an additional value that may have unintended consequences (such as considering the Count a valid value when it's really just a convenience). If the enums are flags, then you also won't get the expected values if you just assume 0 to Count.
- Add a "Count" static readonly int to an extension type which uses System.Enum.GetValues. This has the downside of not being a constant and also using reflection. It also doesn't handle the enums being flags, as above.
- Use foreach with System.Enum.GetValues or GetNames directly and then unbox/convert the values back to the enum type. This has the downside of needing to perform the conversion each time it's iterated although it does handle the values being flags.
- Add a "Values" static readonly IReadOnlyList<T> to an extension which caches the results of System.Enum.GetValues in a typesafe manner. This has the downside of using a static and having to populate it dynamically (most easily with a static constructor or Lazy).

Ideally I'd like to be able to do this:
```csharp
enum TestEnum {
   Zero,
   One,
   Two,
}

// If TestEnum is updated to intrinsically implement IEnumerable<T>, this prints:
// Zero
// One
// Two
foreach (TestEnum value in Enum.GetValues<TestEnum>()) {
    Console.WriteLine(value.ToString());
}
```

Ideally it should also be possible to use default literals, too:
```csharp
foreach (TestEnum value in default) {
    // same as above
}
```

**Comment by HaloFour** [comment]
I don't think it makes much sense for a value of an enum to be enumerable, or for it to enumerate over all of the values of the type of that enum.

You could easily accomplish this today with a generic helper function.


[SharpLab Example](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWAChMAGAAk1ygG4ijMBmC3CC7MgUVWQFsAJAKYAbAA4DEAZzIBvImXkUmlVpQYAeACoA+MgDUAhkOQCJmrQAoAlGQDuAC3ECyGsiDIS4KAMZwYnbjwycgohGgDaALpk+oiI+gCeZAC8ZObhEdZcvAB0AOICcAZGJuZw8WIA9gBmaZaWtIQhIZgA7NGxCQ0hAL5EvYT0SuwAwkGNCjjssuNNZFUViAL6XnapACL6cAIaAJY8AgDSO6gAJmQncADWZMf+vIKi4hLZRcamG1u7+0enFnVjs1mlAAnOYLpd6sFZv0en0gA)

**Comment by HaloFour** [comment]
Actually the following also works just fine:

```cs
        foreach (DateTimeKind dtk in Enum.GetValues(typeof(DateTimeKind))) {
            Console.WriteLine(dtk);
        }
```

**Comment by LegoCylon** [comment]
@HaloFour using Enum.GetValues boxes, though (since it isn't generic and can't return a typed array).

Per https://docs.microsoft.com/en-us/dotnet/api/system.enum.getvalues?view=netframework-4.7.2#remarks it also has the side effect of enumerating them in ascending order, not the order they are defined.

**Comment by LegoCylon** [comment]
For the record, I'd also accept a generic implementation of Enum.GetValues. I just proposed the alternative version since it was shorter to write.

**Comment by DaZombieKiller** [comment]
If we had pattern-based `foreach` you could do this:
```cs
public static class EnumExtensions
{
    public static Enumerator<T> GetEnumerator<T>(this T @enum)
        where T : struct, Enum
    {
        return new Enumerator<T>();
    }

    public struct Enumerator<T>
        where T : struct, Enum
    {
        static readonly T[] Values;

        static Enumerator() => Values = (T[])Enum.GetValues(typeof(T));

        int index;

        public T Current { get; private set; }
        
        public bool MoveNext()
        {
            if (index >= Values.Length)
                return false;

            Current = Values[index++];
            return true;
        }
    }
}
```

**Comment by LegoCylon** [comment]
@DaZombieKiller Yeah, that's effectively what I've done in my own code (it's option 4 in my list of alternatives).

However, it still requires boxing and reflection to access the values (at least initially).

I just wanted to propose that it is officially implemented (and ideally without boxing/reflection) to save folks from reimplementing the pattern.

**Comment by DaZombieKiller** [comment]
@LegoCylon `Array` is a reference type, and you can cast it to `T[]`. There is no boxing here.

**Comment by LegoCylon** [comment]
@DaZombieKiller good point, Rider was complaining that it was boxing without the explicit cast.

**Comment by LegoCylon** [comment]
Wrapping System.Enum.GetValues still has the unfortunate side effect of returning the results in ascending order, though, but I suppose that shouldn't change if GetValues<T> existed (for consistency).

**Comment by CyrusNajmabadi** [comment]
> still has the unfortunate side effect of returning the results in ascending order

As opposed to?

**Comment by DaZombieKiller** [comment]
@LegoCylon Easily solved with a simple reverse enumerator, if you'd prefer the opposite.
```cs
public static class ArrayExtensions
{
    public static ReverseEnumerator<T> AsReverse<T>(this T[] array)
        => new ReverseEnumerator<T>(array);

    public struct ReverseEnumerator<T>
    {
        public ReverseEnumerator(T[] array) : this()
        {
            Array = array;
            index = array.Length - 1;
        }

        public T[] Array { get; }

        public T Current { get; private set; }

        int index;

        public bool MoveNext()
        {
            if (index < 0)
                return false;

            Current = Array[index--];
            return true;
        }

        public ReverseEnumerator<T> GetEnumerator() => this;
    }
}

// ...

foreach (var value in GetValues<TestEnum>().AsReverse())
    Console.WriteLine(value);
```

**Comment by LegoCylon** [comment]
@DaZombieKiller My point was it doesn't let you enumerate in the defined order.

enum Test {
    Two = 2,
    Ten = 10,
    Zero = 0
}

// Prints
// Zero
// Two
// Ten
foreach (var value in (Test[])Enum.GetValues(typeof(Test))) {
    Console.WriteLine(value);
}

**Comment by CyrusNajmabadi** [comment]
>  My point was it doesn't let you enumerate in the defined order

I don't believe there is any 'defined' order for enum values.  Can you point to something in the language spec that you think indicates there should be?

**Comment by DaZombieKiller** [comment]
@LegoCylon I'm not sure what the purpose would be of iterating in the order of definition. Moreover, I'm not even sure if that information is even retained in the compiled binary (I don't think it is). Do you have a particular case where this form of iteration would be useful?

**Comment by LegoCylon** [comment]
@CyrusNajmabadi by 'defined order' I mean literally the order that I defined them in the code. I don't know anywhere in the spec that specifies an order; I'm just surprised that places like GetValues are specific about the order being mutated from the definition.

@DaZombieKiller without having read the remarks about GetValues ordering before, my intuition was that definition order was preserved. There may be good reasons for it to always be in ascending order, but it wasn't what I expected. Sure, I could generate some code to create a definition-order preserving enumerator, but that feels like swatting a fly with a bazooka! 

As for a situation where the definition order is important, let's say that you have a set of values you want to associate with a hash code:

```csharp
enum Fruit {
    Apple = 0x9128a412, // These are made up hash values just to illustrate my point
    Banana = 0x17880b99,
    Strawberry = 0xa1778980,
}
```

If I want to display the values in a dropdown, then the order I get them back is going to be Banana, Apple, Strawberry (from both Enum.GetValues and Enum.GetNames). Sure, all the values are there, but they're not in an order that's intuitive to work with if you don't know the hash codes.  I agree that code generation can definitely help with this problem, but my point in suggesting the proposal to begin with was to identify a problem I've run into on multiple projects and it seems like there's a benefit to streamlining here, particularly when there are potentially non-trivial performance differences between casting and not casting.

**Comment by DaZombieKiller** [comment]
@LegoCylon 
> without having read the remarks about GetValues ordering before, my intuition was that definition order was preserved.

The main issue with that is C# is not the only .NET language. The definition order of the `enum` is a concept very closely tied to the language that it was defined in. So as it's language-specific I don't think source generators are too big a leap here (but of course, that's only my opinion).

For the use case you presented, I'd argue that relying on the definition order of the `enum` is fragile for this reason. I'd suggest using a separate array where you specify the values in the order you want such as `new[] { Fruit.Apple, Fruit.Banana, Fruit.Strawberry }`.

There are of course a plethora of other solutions too, but that's the first that came to mind.

**Comment by LegoCylon** [comment]
@DaZombieKiller fair point about C# not being the only .NET language. I guess that's another reason to prefer a language solution rather than a framework solution (i.e. the originally suggested `foreach (Test value in default)`).

I think it's a shame that the definition order is considered fragile (especially considering that enums have few properties as is), but maybe the ship has sailed on that.

You're right, defining a separate array is certainly possible but I'd prefer not to repeat myself (or rely on code gen) to achieve something that seems like it should be intrinsically available.

**Comment by theunrepentantgeek** [comment]
It doesn't avoid the repetition - but in similar situations I've used a unit test to ensure no-one misses a necessary update later on. Here's an example

``` csharp

public enum Colour
{
    Black,
    Red,
    Green,
    Blue,
    White
}

public readonly Colour[] Colours 
    = new []{ Black, Blue, Green, Red, White };
    
[Fact]
public void AllColoursShouldBePresent()
{
    foreach(var c in Enum.GetValues(typeof(Colour)))
    {
        Colours.Should().Contain(c);
    }
}
```

**Comment by LegoCylon** [comment]
A friend suggested this alternative enumeration syntax:

```csharp
foreach (TestEnum value) {
...
}
```

**Comment by canton7** [comment]
> A friend suggested this alternative enumeration syntax

That has no precedent for that anywhere in the language.

You're suggesting that `foreach (TestEnum value)` would enumerate the elements in the order that they were defined in, as opposed to `foreach (TestEnum value in Enum.GetValues(typeof(TestEnum)))` which would enumerate them in numerical order? That's really not obvious.

----

When things start getting more complex than a normal `enum` can handle, consider Java-style enums. There's a bit of boilerplate, but not much more than an enum + array + unit test.

```cs
public struct Fruit
{
    private static readonly List<Fruit> values = new List<Fruit>();
    public static IReadOnlyList<Fruit> Values => Values;
    
    public static Fruit Apple { get; } = Add(0x0128a412);
    public static Fruit Banana { get; } = Add(0x17880b99);
    public static Fruit Strawberry { get; } = Add(0x01778980);
    
    public int HashCode { get; }
    
    private Fruit(int hashCode) => HashCode = hashCode;
    
    private static Fruit Add(int hashCode)
    {
        var color = new Fruit(hashCode);
        values.Add(color);
        return color;
    }
}
```

**Comment by LegoCylon** [comment]
> That has no precedent anywhere in the language.

Agreed, I think its simplicity may make it more confusing to some about what it's accomplishing.

> You're suggesting that foreach (TestEnum value) would enumerate the elements in the order that they were defined in, as opposed to foreach (TestEnum value in Enum.GetValues(typeof(TestEnum))) which would enumerate them in numerical order? That's really not obvious.

I agree that it wouldn't be obvious that the order of enumeration would be different. I think the ship has probably sailed on GetValues enumerating in ascending order, but I would love to have an option to match the order of the definition (perhaps with an optional parameter).

> consider Java-style enums

I appreciate the suggestion (and have used java-style enums in the past when I need more than a numerical value) but I specifically made this proposal to eliminate the boilerplate.

After seeing some good points above, I think it's probably best to consolidate the proposal to:
- Adding a generic version of Enum.GetValues to avoid having to remember cast to avoid boxing.
- Updating Enum.GetNames, the original Enum.GetValues, and the generic Enum.GetValues to have an optional enumeration order parameter to allow you to request to enumerate in ascending order (as-is) or definition order.
- If a syntactic sugar version is added (i.e. `foreach (Fruit f in default)`), then it makes sense for it to match the existing behavior (enumerate in ascending order). Even though I don't find that intuitive, it's better to maintain consistency between options.

**Comment by HaloFour** [comment]
Why does this need a language feature at all?  It feels like we've spent more energy discussing the problem than the aggregate of time ever spent trying to solve it, which is still many of orders of magnitude less than any language-based solution.  If you want a generic type-safe solution that returns in lexical order, take it up with CoreFX, or write your own using field-based reflection.  There's no need for a language change here.

**Comment by LegoCylon** [comment]
@HaloFour why should any given language feature exist? Just because we *can* work around it with code gen, etc shouldn't automatically invalidate a proposal. 

i.e. look at default literal or switch expressions - do we really need them as a language feature? Probably not, you can work around either of them, but they save people implementation time. That's all I'm looking to do here.

**Comment by HaloFour** [comment]
@LegoCylon 

Because they offer enough benefit in common enough use cases to warrant attention by the language team for inclusion.  People write the kinds of expressions that would benefit from switch expressions and default literals all the time.  I'm far from convinced that the need to enumerate over the values of an enum happens often enough at runtime to necessitate a language feature over the exceedingly simple method already offered by the runtime.

**Comment by canton7** [comment]
Note that you can't get fields in declaration order using reflection -- the order of fields returned by `Type.GetFields` is unspecified. Currently there is no way of getting the declaration order of an enum: it would need either a compiler or runtime change. In either case, you've got the compatibilty to think of, where code which is expecting to fetch enum members in declaration order can't, either because it's looking at an enum which was compiled using an older compiler version, or because it's running on an older runtime. 

So even if this were implemented, either you'd have to be prepared to handle the case where you were given the enum members *not* in declaration order (even though you asked for declaration order), or you would get an exception.

**Comment by HaloFour** [comment]
@canton7 

> Note that you can't get fields in declaration order using reflection

You could in your own helper method by using an attribute applied to the enum fields to specify an order.  You would be required to manually apply the attributes with the appropriate values, though.

**Comment by canton7** [comment]
It's true, and you can use `[CallerLineNumber]` to help with that.

**Comment by DaZombieKiller** [comment]
@canton7
> you can use `[CallerLineNumber]` to help with that.

Woah, TIL.
```cs
public sealed class PreserveOrderAttribute : Attribute
{
    public int Line { get; }
    public PreserveOrderAttribute([CallerLineNumber] int line = -1) => Line = line;
}

public enum EnumTest
{
    [PreserveOrder] A,
    [PreserveOrder] B,
    [PreserveOrder] C,
}

public static void Main()
{
    foreach (string name in Enum.GetNames(typeof(EnumTest)))
    {
        var field = typeof(EnumTest).GetField(name);
        var attr  = field.GetCustomAttribute<PreserveOrderAttribute>();
        
        if (attr is null)
            continue;
        
        Console.WriteLine("{0} {1}", field.Name, attr.Line);
    }
}
```

**Comment by canton7** [comment]
The caveats are that you need to check for duplicates, in case someone put two attributes on the same line, and it's also worth checking `[Caller Filename]` in case someone's using a partial type (although enums can't be partial, of course).

**Comment by BrunoZell** [comment]
@LegoCylon Check out [Enums.NET](https://github.com/TylerBrinkley/Enums.NET) and https://github.com/dotnet/corefx/issues/15453

**Comment by LegoCylon** [comment]
Since it doesn't seem like anyone else but me is interested in this as a language feature, I'm going to close this request and pursue it as a framework request.

Thanks for your feedback.

**Comment by HaloFour** [comment]
@canton7 

Actually couldn't you sort the fields by MetadataToken?  I know that they're guaranteed to be in declaration order for sequential types as that is how the TypeLoader sorts the fields.  I don't know if that's necessarily true for non-sequential types, but it would mean that the compiler would need two different emitting strategies for sequential and auto types and that seems kinda pointless, no?  Testing locally does seem to indicate that this does work, with both auto types and enums, but that's a small sample size.

**Comment by LegoCylon** [comment]
@HaloFour interesting idea. Looks like that has been discussed before: https://stackoverflow.com/questions/25147228/sort-enums-in-declaration-order

**Comment by tpetrina** [comment]
> I don't think it makes much sense for a value of an enum to be enumerable, or for it to enumerate over all of the values of the type of that enum.

I find it really hard not to read this sentence with a confused look. Enumeration of values _should_ be enumerable...it's right there in the name!

**Comment by HaloFour** [comment]
@tpetrina 

> > I don't think it makes much sense for a value of an enum to be enumerable, or for it to enumerate over all of the values of the type of that enum.

> I find it really hard not to read this sentence with a confused look. Enumeration of values should be enumerable...it's right there in the name!

The keywords being "for a value of an enum".  IIRC the original proposal included being able to `foreach` over `new SomeEnum()` or `default(SomeEnum)`.

That said, the "enumeration" of an `enum` and the "enumeration" of an `IEnumerable` are two very different and unrelated things.  It's a little unfortunate that .NET went with `IEnumerable` but I guess calling it `IIterable` would've been too on the nose.
