### ISSUE TITLE
Update nullable-reference-types proposal based on 2016-11-16 design notes

### ISSUE THREAD

**Issue by MadsTorgersen** [dotnet/csharplang#3]
Update [proposals/nullable-reference-types.md](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md) according to [meetings/LDM-2016-11-16.md](https://github.com/dotnet/csharplang/blob/master/meetings/2016/LDM-2016-11-16.md).

**Comment by paulomorgado** [comment]
[tings/LDM-2016-11-16.md](tings/LDM-2016-11-16.md) is 404

**Comment by scottdorman** [comment]
@paulomorgado Here's the correct [link](https://github.com/dotnet/csharplang/blob/master/meetings/2016/LDM-2016-11-16.md).

**Comment by gafter** [comment]
Link corrected.

**Comment by 333fred** [comment]
The specification work is well underway at csharpstandard. Closing this out.
