### ISSUE TITLE
valueOfT == default throws NullReferenceException

### ISSUE THREAD

**Issue by nilnul** [dotnet/csharplang#3000]
Suppose we have:

```
class C1{
    int val;
     static public bool operator ==(C1 a, C1 b) => a.val==b.val;
}
```
then 
`
var c=new C1();
if(c == default){ }
`
would result in exception.

This is against the expectation that here `c == default` shall work the same way like `c==null` as `default` here evaluates to `null`

**Comment by nilnul** [comment]
I got it wrong.
`c==null` throws exception as well, 'cuz the overloaded operator "==" is called.
is this behavior expected? I think when right hand side is `null`, no need to call the overloaded `==`.

[a workaround for this currently is using `c is null`]

**Comment by canton7** [comment]
Yes, this is expected. You need to check for null in your `==` operator, and in any `Equals` methods, etc.

**Comment by 333fred** [comment]
Since the question has been answered, I'm closing this issue.
