### ISSUE TITLE
Print array

### ISSUE THREAD

**Issue by cup** [dotnet/csharplang#3001]
I can create a program like this:

~~~cs
using System;
class App {
   static void Main() {
      int[] a1 = {10, 20};
      Console.WriteLine(a1);
   }
}
~~~

but it doesnt give expected output:

~~~
System.Int32[]
~~~

I checked online:

https://stackoverflow.com/questions/16265247

and people suggest to loop through the array. Is that really necessary? Many
other languages dont require that, like Go:

~~~go
package main
import "fmt"
func main() {
   a1 := []int{10, 20}
   fmt.Println(a1)
}
~~~

Nim:

~~~nim
var a1 = [10, 20]
echo a1
~~~

D:

~~~d
import std.stdio;
void main() {
   auto a1 = [10, 20];
   a1.writeln;
}
~~~

JavaScript:

~~~js
let a1 = [10, 20];
console.log(a1);
~~~

Python:

~~~py
a1 = [10, 20]
print(a1)
~~~

**Comment by yaakov-h** [comment]
This isn't controlled by the C# language, it's entirely up to the runtime AFAIK.

**Comment by cup** [comment]
https://github.com/dotnet/coreclr/issues/27960

**Comment by HaloFour** [comment]
Or you can write a helper function that loops and formats the output.  For as often as I find it useful to output an array to text (which is borderline never) I don't think remotely justifies a language or runtime change.

**Comment by cup** [comment]
@HaloFour it you consider my example above, and the fact that every major programming language has this capability, it would appear that *it is justified*, and that you are in the minority.

**Comment by HaloFour** [comment]
@cup 

> it you consider my examples above, and the fact that nearly every
> major programming language has this capability, it would appear that _it is
> justified_, and that you are in the minority.

I'd suggest that your list of examples is exceptionally short and very specifically curated to highlight those few languages that behave in this manner.  The vast majority of programming languages don't automatically convert arrays into strings, let alone format their contents into a printable manner.  It'd be a giant waste for non-scripting languages to do this.

**Comment by HaloFour** [comment]
This will print out what you're expecting:

```cs
using System;
class App {
   static void Main() {
      int[] a1 = {10, 20};
      Console.WriteLine(String.Join(",", a1));
   }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWACgcACAQQAcKSBvIkhzXCEzKEgWQEMBLVACgCUtegzF84AbQC6JLrhIBeWrgAMMEtlUBfANyixrXAE5+AZTiI+AcwB0AKQD2ffgCIY7ubkGD9hMdpE2kA)

**Comment by cup** [comment]
@HaloFour cool, heres some more. Rust:

~~~rust
fn main() {
   let a1 = [10,20];
   println!("{:?}", a1);   
}
~~~

Dart:

~~~dart
void main() {
   var a1 = [10,20];
   print(a1);
}
~~~

PHP:

~~~php
$a1 = [10, 20];
print_r($a1);
~~~

Ruby:

~~~rb
a1 = [10, 20]
p a1
~~~

Julia:

~~~jl
a1 = [10, 20]
println(a1)
~~~

**Comment by jmarolf** [comment]
@cup I would file this on the [dotnet/runtime](https://github.com/dotnet/runtime) repo. If we were to add an overload to the `Console` class that accepted an `IEnumerable` this would work as you expect.

```csharp
public static void WriteLine(IEnumerable array)
{
    Console.WriteLine(string.Join(",", array));
}
```

**Comment by cup** [comment]
https://github.com/dotnet/runtime/issues/425

**Comment by HaloFour** [comment]
> I am interested in printing an array with a language built-in.

So go use one of those languages then.  C# doesn't do that, nor does it have any reason to.  Neither does C, C++, Java, Scala, Groovy, or most programming languages.  The functionality is easily accomplished through a one-liner using helper functions provided by the BCL.  This approach is also infinitely better than baking it into the language as the developer has the ability to choose the formatting, such as a delimiter.

C# does nothing special with arrays here.  It calls a BCL method that accepts `Object`.  That method internally calls `ToString()` on that `Object`.  If the type happens to override `ToString()` then it'll print/output whatever that overridden format is.  `System.Array` does not override `ToString()`, thus the default implementation in `Object` is used, which prints out the type name.  That has been the behavior for nearly 20 years.  Changing it now will almost certainly break existing programs.

**Comment by cup** [comment]
@HaloFour can you get out of here? Youve made your opinion, loud and clear. Ive
given many example of languages that do this, so we just disagree.

Theres certainly a use for it, else 10 other languages wouldnt have implemented
it. Unless you have something further thats actually constructive, please stop.

**Comment by HaloFour** [comment]
@cup 

> Theres certainly a use for it, else 10 other languages wouldnt have implemented it. 

Lots of languages do lots of things.  That's not reason enough to change C#.  The onus is going to be on you to demonstrate that the feature will have enough of a benefit to enough people to justify the extremely high cost of adding it to the language.

> I will add further that the `Join` suggestion being proposed is obviously weak.
What if the elements are strings, and what if the elements contain your chosen
delimiter?

The BCL offers multiple ways to format said array as well.

Either way, as myself and others have suggested, this is a request for the runtime, not the language.  The language knows nothing of formatting values for output.

**Comment by AartBluestoke** [comment]
@cup Halo's main objection is that the language itself doesn't specify implementation behaviour for array-to-string conversion, it speaks about higher level constructs like what a function call is. 

In general the correct array-to-string conversion is highly context dependent, for everyone that wants a neat CSV style out, someone else will want a Json formatted token set.

If you believe that the console writer should have a "sensible" default behaviour when converting arrays to strings, then you are suggesting addition to the runtime implementation ; Halo suggested you file this issue over at dotnet/runtime to implement them.

**Comment by cup** [comment]
> The onus is going to be on you to demonstrate that the feature will have
> enough of a benefit

@HaloFour the onus is on the language developers, if they decide that feature
parity is an important goal, and if so what features.

> to enough people to justify the extremely high cost of adding it to the
> language.

is this a joke? I recently (this year) submitted a pull request to the PHP repo
that adds a new print function, similar to the one I am proposing here. Not
including testing the commit was 20 lines of code.

If this C# change is not implemented I dont care, as you said I can just use one
of the other languages. My purpose here was mainly to document what I see as a
(runtime) failing of C#.

If this issue is closed or ignored, so be it.

**Comment by HaloFour** [comment]
> is this a joke? I recently (this year) submitted a pull request to the PHP repo that adds a new print function, similar to the one I am proposing here. Not including testing the commit was 20 lines of C code.

No, this is not a joke.  The language design process of C# is considerably more conservative.  Such a PR to the C# compiler will certainly be closed.  Every language feature proposal must be championed by a member of the language design team and debated through language design meetings.  A proper specification needs to be drawn up and a battery of tests designed and proven that not only will the new feature work but that no other feature is broken.  C# is a 19 year old language, millions of programs depend on it, and every language feature needs to be supported, commercially, for perpetuity.

**Comment by cup** [comment]
Cool.

**Comment by khm1600** [comment]
> I will add further that the Join suggestion being proposed is obviously weak.
What if the elements are strings, and what if the elements contain your chosen
delimiter? Again, other languages have multiple ways to handle this gracefully.

```cs
var arr = new[] {",", "."};

string.Join(", ", arr.Select(x => $"\"{x}\""));
arr.Aggregate(new StringBuilder(), 
              (acc, next) => acc.Append($", \"{next}\""), 
              x => x.ToString().Substring(2));
// Both evaluates to 
// ",", "."
```
It's a little bit too much for simple situations, but you can use your delimiter of choice and format of choice.

**Comment by canton7** [comment]
This is definitely a request for a change in the standard library, *not* a request for a change in the language itself. This would probably be solved by an overload for e.g. `Console.WriteLine` (but many other methods besides, e.g. on `TextWriter`) which takes an `IEnumerable<T>`.

If you want to peruse this, corefx is probably the place to do it.

**Comment by YairHalberstadt** [comment]
@canton7 
CoreFX is no longer the place. It's now dotnet/runtime

**Comment by Unknown6656** [comment]
This would be a breaking change.

**Comment by jrmoreno1** [comment]
@jmarolf : when and if extension everywhere is released, you would be able to add static extension method to Console, effectively doing the same thing, but only for your own projects.

**Comment by 333fred** [comment]
This is not a language change request. If you would like the runtime behavior to change, please file an issue on dotnet/runtime.
