### ISSUE TITLE
Nullable reference types on typeof

### ISSUE THREAD

**Issue by maxtoroq** [dotnet/csharplang#3003]
```
var t = typeof(string?);
(1,9): error CS8639: The typeof operator cannot be used on a nullable reference type
```

Why? I don't see any value in throwing this error. Of course `string?` is a type (reference), so why can't I get its type? On the other hand, this breaks code generation scenarios, e.g. `string?` is part of another non-c# file, and I use that snippet to generate `typeof(string?)`.

**Comment by huoyaoyuan** [comment]
Because nullable reference type does not have a standalone runtime representation. When using reflection, it's represented by `NullableContextAttribute` on the target member.

**Comment by CyrusNajmabadi** [comment]
> On the other hand, this breaks code generation scenarios, e.g. string? is part of another non-c# file, and I use that snippet to generate typeof(string?).

Sounds like the code generator should be fixed.

**Comment by maxtoroq** [comment]
> 
> 
> > On the other hand, this breaks code generation scenarios, e.g. string? is part of another non-c# file, and I use that snippet to generate typeof(string?).
> 
> Sounds like the code generator should be fixed.

No shit, what a genius.

**Comment by CyrusNajmabadi** [comment]
In that case, it sounds like the lang/compiler are doing the right thing, and the issue exists outside their purview. 

> Why? I don't see any value in throwing this error. 

This has been answered now. Because supporting code generators is not as valuable as stopping people from writing nonsensical, and likely buggy, code.

**Comment by richlander** [comment]
@maxtoroq -- I hid your comment as "Abuse". It was reported as a CoC violation and is abusive. Please use more constructive language.
