### ISSUE TITLE
Tweaks to switch expressions to make it more C# style.

### ISSUE THREAD

**Issue by xCyborg** [dotnet/csharplang#3005]
I understand it's too late for a full review of switch expression in C# but I propose to relax the rules to make it possible to write them like this:

//switch as expression
int number= 0;

```csharp
var state =  switch (number)
{
    (0) => "Zero", // also could use ' ; '
    (1) => "One",
    (2) => "Two",
     _ => "NO valid number"
};
```

Also make non returning statements compatible with the switch expression syntax and add support to statement blocks:

```csharp
 switch (number)
{
    (0) => Console.WriteLine("Zero"); // semi-colon
               Console.WriteLine("Zero Again"); // preferably add more statements like
                                 // this or enclosed in  a statement block => { ... } 
    (1) => Console.WriteLine("One");
    (2) => Console.WriteLine("Two");
     _ => Console.WriteLine("NO valid number");
}; // give or take the ' ; '

```

This may even be used to return a lambda to a delegate:

```csharp
Action action = switch (number)
{
    (0) => Console.WriteLine("Zero"); // semi-colon
     _ => Console.WriteLine("Non-zero number");
};
action();
```

Also makes it less confusing when returning the switch result:

```csharp
return switch (number)
{
    (0) => "Zero",
    .....
};

```
This seems to me way more in line with traditional C# syntax and that's how find other languages have done like Java.

Those changes could fit very nicely and add much more power to the current design shortcomings.

**Comment by HaloFour** [comment]
Allowing for `switch` expressions to be used with statements is a championed proposal, the effort did not fit into the C# 8.0 timeframe:

https://github.com/dotnet/csharplang/issues/2632
https://github.com/dotnet/csharplang/issues/2860

As for the syntax, many forms were discussed during the design phase, including the one you suggest, but the team settled on the syntax that shipped with C# 8.0.  I don't think that there's reason to revisit that as the different syntax doesn't change the behavior or capabilities of the feature.

Here's one such issue discussing the syntax choices.  I know I've seen more.

https://github.com/dotnet/csharplang/issues/487

**Comment by xCyborg** [comment]
@HaloFour

I'm not suggesting changing the syntax, just to relax the rules to incorporate the proposed syntax.
That current one is not very intuitive in my mind and unheard of in any language I saw.

At least to permit changing <switch><variable> position, I can't think of anything horrible is gonna happen.

**Comment by HaloFour** [comment]
I will say that the one thing that I like about the Java switch expression is the ability for them to contain a block of multiple statements.  C# is exploring sequence expressions which would enable arbitrary groupings of statements to be an expression, but IMO it's a weird syntax:

https://github.com/dotnet/csharplang/issues/377

**Comment by HaloFour** [comment]
> At least to permit changing position, I can't think of anything horrible is gonna happen.

Expending effort to add two ways to do the same thing is a waste of time.

Scala uses in-fix `match` expressions similar to C#:

```scala
import scala.util.Random

val x: Int = Random.nextInt(10)

var result = x match {
  case 0 => "zero"
  case 1 => "one"
  case 2 => "two"
  case _ => "other"
}
```

```cs
var random = new Random();
var x = random.Next(10);

var result = x switch {
    0 => "zero",
    1 => "one",
    2 => "two",
    _ => "other"
};
```

**Comment by xCyborg** [comment]
Yes in Scala it kinda makes sense because they're using `match` keyword, that is when x matches case return value.

But with switch it's different, it doesn't imply the same meaning, not to mention that C# always used C style switches, so it doesn't make sense to use it as a functional match.
Only adds discrepancy.

Take Java 12 for instance, they did it the right way you'd expect.

>int numLetters = switch (day) {
    case MONDAY, FRIDAY, SUNDAY -> 6;
    case TUESDAY                -> 7;
    case THURSDAY, SATURDAY     -> 8;
    case WEDNESDAY              -> 9;
};

**Comment by xCyborg** [comment]
@HaloFoor

Even in Microsoft's own F# it goes like this:

```
let detectZeroAND point =
    match point with
    | (0, 0) -> printfn "Both values zero."
```

**Comment by HaloFour** [comment]
@xCyborg 

At that point it's a matter of style and preference.  The language team debated over the syntax and chose an infix operator over a prefix keyword.  One isn't superior to the other, just different.  I don't think it's worth relitigating settled (and shipped) design.  I'd rather worry about adding more functionality, like being able to express multiple conditions for a single case.

**Comment by xCyborg** [comment]
@HaloFour

Also in Microsoft's own F# it goes like this:

```let detectZeroAND point =
    match point with
    | (0, 0) -> printfn "Both values zero."
```

**Comment by xCyborg** [comment]
@HaloFour

Also in Microsoft's own F# it goes like this:

```
let detectZeroAND point =
    match point with
    | (0, 0) -> printfn "Both values zero."
```

**Comment by DavidArno** [comment]
> I propose to relax the rules to make it possible to write them like this...

The issue with "relaxing the rules" is that you then make the language more complex. There'd then be three valid ways of expressing the exact same functionality:
```cs
var state = switch (number) {
    (0) => "Zero", 
    (1) => "One",
    (2) => "Two",
    _ => "NO valid number"
};

var state = switch (number) {
    (0) => "Zero";
    (1) => "One";
    (2) => "Two";
    _ => "NO valid number"
};

var state = number switch {
    0 => "Zero", 
    1 => "One",
    2 => "Two",
    _ => "NO valid number"
};
```
Arguably the advantage of this is that those that don't like the last format can choose one of the previous two. But the disadvantage is this then means the compiler needs to understand all three, all three need to be properly documented and developers need to learn all three in order to be able to read and understand others' code.

The time and effort involved in those disadvantages far outweigh the tiny convenience this flexibility brings.

I'm biased here as I argued in favour of the current syntax (though I'd have preferred `match` over `switch` but accepted there were good reasons for not introducing a new keyword), but I completed disagree with your final line:
> Those changes could fit very nicely and add much more power to the current design shortcomings

I don't accept there are any shortcomings to the design, beyond it not yet supporting statement expressions, and what you are proposing would just add more complexity, rather than power, to the design.

**Comment by xCyborg** [comment]
@DavidArno No there would only be:
```csharp
var state = switch number {
    0 => "Zero", 
    1 => "One",
    2 => "Two",
    _ => "NO valid number"
};
```
And hopefully the deprecated:
```csharp
var state = number switch {
    0 => "Zero", 
    1 => "One",
    2 => "Two",
    _ => "NO valid number"
};
```
This is hardly noticeable, a slight "switch" in the switch expression to be more in line with other languages and common C# sense, nothing more.

I read in the What's new page for C# 8.0 that the main reason for that was to be able distinguish between switch statements and expression but a simple assignment operator or `return` before would suffice.

It's totally incoherent, this has already created a split, by relaxing the rules I'm talking about damage control because when you add features from here on out like statement expressions.

Which syntax you're gonna choose.
```csharp
int i = 23;
i switch
{
   23 => Console.WriteLine("23"),
   _ => Console.WriteLine("Else")
};
```
Or:
```csharp
int i = 23;
switch i
{
   23 => Console.WriteLine("23"),
   _ => Console.WriteLine("Else")
};
```
Or:

```csharp
int i = 23;
switch(i)
{
   23 => Console.WriteLine("23");
   _ => Console.WriteLine("Else");
}
```
You see my point?
How would a possible if expression would now look if you wrote it as:
```csharp
var int result = number if ... {
```

**Comment by xCyborg** [comment]
@DavidArno I'll tell you how it all should have been:
It should have been like this from the beginning
First statements for feature parity.
```csharp
switch (number)
{
    0 => Console.WriteLine("Zero");
             Console.WriteLine("Zero Again");
    1 => Console.WriteLine("One");
    2, 3 => Console.WriteLine("Two or Three");
     _ => Console.WriteLine("NO valid number");
}
```
Then expressions:
```sharp
string result  = switch (number)
{
    0 => "Zero";
    1 => "One";
    2 => "Two";
     _ => "NO valid number";
}
```
There you have it all, can't be more simple than that?
Don't you agree?

**Comment by HaloFour** [comment]
@xCyborg 

> And hopefully the deprecated:

That would be two ways, one of which is brand new yet deprecated?  That's awful messaging.

We get it, you don't like the syntax.  Sorry.  But it's not going to change simply because you don't like it.  The team went through dozens of options, including the one you're proposing, so it's not like they weren't aware of it at the time.  And your syntax doesn't do anything to change the behavior of the expression in any way.  So there's zero benefit to adopting it.

Sorry, it's not going to happen.

**Comment by CyrusNajmabadi** [comment]
> though I'd have preferred `match` over `switch` but

Note: from an impl perspective this is *much* more costly.  contextual kewords are a PITA to deal with and involve lots of lookahead and care to ensure that you're not breaking existing code.  i.e.

`match (some.long + expression)`

is this a call to a method called `match`?  Or is it the start of a `match` expressoin.  We def liked `switch` because as a keyword it's only legal in hte places we make it legal.  It's extremely easy to make a determination.

**Comment by theunrepentantgeek** [comment]
@xCyborg wrote

> Those changes could fit very nicely and add much more power to the current design shortcomings.

The language team is justifiably reticent to make breaking changes to the C# language, so the existing syntax for **switch** expressions and **switch** statements won't be removed nor deprecated.

Thus these changes would make the language larger, increasing the cognitive load on every developer using C# (they'd need to be aware of every variant of the syntax) while not actually increasing the power of the language at all. 

Language changes need to be more than just nice ideas, they need to provide a significant benefit for a wide subsection of the developer community. https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/

**Comment by xCyborg** [comment]
@theunrepentantgeek You should've said that to the Roslyn team.
Don't you think the language team already dumped a huge cognitive load on us on with the latest few releases of C#, `switch` is just one case point, now we need to be aware of all the polymorphism in its use, the classic switch, all the permutations of switch patterns including property and tuples, the weird switch expressions + the upcoming expression statements and more pattern matching.

You telling me this didn't make the language "larger"?
And none of it plays nice with the other, don't you think I wouldn't be ranting here if I'm not already overblown by this level of complication.
I know it's too late, but don't tell me it's all perfect so far because it's clearly **NOT**.

**Comment by CyrusNajmabadi** [comment]
Lots of feedback was given. The language changes were the result of a large balancing act between many goals.

**Comment by CyrusNajmabadi** [comment]
> but don't tell me it's all perfect 

No one has argued this. The position is that your proposal doesn't substantively improve things, and it also has major drawbacks.

**Comment by CyrusNajmabadi** [comment]
> ... Deprecated ...
> This is hardly noticeable, 

This would be a massive breaking change. There is no way that would happen for such a minor syntactic tweak

**Comment by xCyborg** [comment]
Alright then, we still could do the right thing with expression-bodied switch statements:

```csharp
switch (number)
{
    0 => Console.WriteLine("Zero");
         Console.WriteLine("Zero Again");
    1 => Console.WriteLine("One");
    2, 3 => Console.WriteLine("Two or Three");
    _ => Console.WriteLine("NO valid number");
}
```

**Comment by HaloFour** [comment]
@xCyborg 

> Alright then, we still could do the right thing with expression-bodied switch statements

There is no "right thing".  For every possible decision as to what syntax to use for a given feature there will be people who disagree.  Invariably there will be people who think that your preference is the "wrong thing."  The team already went through many options and made their decision.  If the team needed unanimous approval to implement a feature the language would never evolve at all.

**Comment by CyrusNajmabadi** [comment]
> Alright then, we still could do the right thing with expression-bodied switch statements:

There are proposals already (i believe) for how we might support many expressions or statements inside a switch expression.

**Comment by gafter** [comment]
> At least to permit changing position, I can't think of anything horrible is gonna happen.

Here are the worst two horrible things that would happen:
1. There is no simple way to parse an expression such as `a + switch b {...} because `switch` is lower precedence.  We would have to change the precedence (to primary/prefix).  Which means changing between prefix and postfix would change the meaning of code.
2. This would cause terrible parsing cascaded errors during typing, as typing an assignment statement on the line before a switch would cause the switch to change to be considered an expression until the semicolon is typed.  Experiencing this myself was what caused me to change it.

Just because you can't think of all the bad things that would happen doesn't mean there aren't any.

**Comment by 333fred** [comment]
Thanks for submitting this proposal. Unfortunately, the team does not feel that this proposal is in line with the current or future direction of the C# language. As such we are closing it. Infix vs prefix operators were heavily debating during the initial design process, and having a year's experience with the shipped syntax we feel that we are happy with it.
