### ISSUE TITLE
remove Task keyword from a async method.

### ISSUE THREAD

**Issue by lbgitjp** [dotnet/csharplang#3007]
in a c#'s async method, the return value's type is not match the method declaration's return type, it looks like a syntax error.

for example:

    private async Task<int> MethodName()
    {
       ...
        return 42;
    }

in the above method declaration, it need a Task\<int\> type return value , but the method return a int  type value,  this is a syntax errors.
the method better be:

    private async int MethodName()
    {
       ...
        return 42;
    }

when the users write the **async** keyword in a method declaration,
they have told the c# complier to encapsulated  the return value and the method declaration's return type in a Task type simultaneously, 
but now, the the c# complier only do a half job, it  has encapsulated  the  return value in a Task\<return value\> type automatic, but not encapsulate the return type of a method's declaration from xxx to Task<xxx> too.

thanks!

**Comment by YairHalberstadt** [comment]
I understand the sentiment, but there are a number of reasons that I think this is extremely unlikely to happen.

a) This would be a massive breaking change. It would break almost any modern C# code base.
b) async can be used with other Task-like types such as ValueTask
c) this was discussed when async was introduced and strongly considered, but ultimately for various reasons was rejected. You would have to suggest something has changed to make it worth taking another look.

**Comment by sharwell** [comment]
📝 `Task<TResult>` is not the only type that can be returned from an `async` method. Other examples are:

* `async Task`: removing `Task` leaves the code with `async void`, but this already has a very different meaning in C#
* `async ValueTask`: similar to `async Task`, but with a different task implementation
* `async ValueTask<TResult>`
* Custom task-like types with their own state machine implementations defined in user-provided code

This gets even more complex when you consider today a valid return type from an `async` method is `Task<ValueTask<int>>`.

**Comment by lbgitjp** [comment]
can't the compiler declare a inner type (for example **InnerAsyncType**) only be used for async keyword and only can be used by the compiler? 
this type **InnerAsyncType** never be seen by the users, never possible be used by the user, in only can be used by the complier.

for example:

    private async int MethodName()
    {
       ...
        return 42;
    }

when see the above method, the compiler changed to below:

    private InnerAsyncType<int> MethodName()
    {
       ...
        return InnerAsyncType<42>;
    }

thanks

**Comment by 333fred** [comment]
> can't the compiler declare a inner type (for example InnerAsyncType) only be used for async keyword and only can be used by the compiler?

Could we? Absolutely we could. However, the async feature was explicitly designed to make that `InnerAsyncType` user-specifiable, for the specific purpose of enabling things like `ValueTask` and other task-like types. For example, the Reactive.NET framework uses this to provide their own task-like type. It's a bit more ceremony for things like it, but it makes the language significantly more expressive and powerful.

**Comment by lbgitjp** [comment]
Thank you for your explanation.

But it caused a obvious syntax errors.

It is not right to allow obvious syntax errors from the beging for some features , I don't think any feature only can be achieved through wrong syntax.

If you decalre a method return Task/ValueTask/xxxTask, you can still run it use **ContinueWith**, it has not  syntax errors. 
or you can even add a new function such like AwaitTask(Task) to run a task, it has not  syntax errors too.

But c# use a bad way, it mix using  **async** keyword and Task Type.

should only allow a **async** keyword method be called by **await** keyword, these two keyword are a pair.

It's bad to mix  use Task syntax with it async syntax.

thanks!

**Comment by CyrusNajmabadi** [comment]
> But it caused a obvious syntax errors.

There don't appear to be any syntax errors with how the language is currently specified.

**Comment by jmarolf** [comment]
I could see a way forward here if we said that in this case:

```csharp
private async int MethodName() {}
```

The compiler would synthesize its own task-like return type for the user, leaving the option for the user to specify 
```csharp
private async ValueTask<int> MethodName() {}
```
or any other task-like type if they so chose.  The question really is, what type should the compiler synthesize? Or to put it another way, what is the type of `var` here?

```csharp
public static int Main() {
  var result = MethodName();
}
```

I assume the most reasonable thing to do would be to have `var` be of type `Task<int>`

**Comment by HaloFour** [comment]
@jmarolf 

But what if the return type is itself a task-like?  Or you intend to return a task-like wrapped in a task-like?  What if the return value had an implicit conversion to that task-like?  Seems like it could quickly get confusing and you wouldn'tbe able to figure out the return type of the method without interpreting the body.  IMO, the actual return type of the method is more important than saving a couple of keystrokes.

**Comment by yaakov-h** [comment]
Even a compromise like that feels too similar to the vetoed “inferred return types” / “var returns” feature request.
