### ISSUE TITLE
Draft spec for local function attributes

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/csharplang#3008]
Related to #1888

## Attributes

Local function declarations are now permitted to have [attributes](https://github.com/dotnet/csharplang/blob/bb997294540bd02f939d60514634ccaa7abc659c/spec/attributes.md). Parameters and type parameters on local functions are also allowed to have attributes.

Attributes with a specified meaning when applied to a method, its parameters, or its type parameters will have the same meaning when applied to a local function, its parameters, or its type parameters, respectively.

A local function can be made conditional in the same sense as a [conditional method](https://github.com/dotnet/csharplang/blob/98043cdc889303d956d540d7ab3bc4f5044a9d3b/spec/attributes.md#the-conditional-attribute) by decorating it with a `[ConditionalAttribute]`. A conditional local function must also be `static`.

## Extern

The `extern` modifier is now permitted on local functions. This makes the local function external in the same sense as an [external method](https://github.com/dotnet/csharplang/blob/892af9016b3317a8fae12d195014dc38ba51cf16/spec/classes.md#external-methods).

Similarly to an external method, the *local-function-body* of an external local function must be a semicolon. A semicolon *local-function-body* is only permitted on an external local function. 

An external local function must also be `static`.

## Syntax

The [local functions grammar](https://github.com/dotnet/csharplang/blob/bb997294540bd02f939d60514634ccaa7abc659c/proposals/csharp-7.0/local-functions.md#syntax-grammar) is modified as follows:
```
local-function-header
    : attributes? local-function-modifiers? return-type identifier type-parameter-list?
        ( formal-parameter-list? ) type-parameter-constraints-clauses
    ;

local-function-modifiers
    : (async | unsafe | static | extern)*
    ;

local-function-body
    : block
    | arrow-expression-body
    | ';'
    ;
```

**Comment by svick** [comment]
For `extern` methods that use `DllImport`, the method name is usually used by the runtime to figure out which function to import. Since the compiler mangles names for local functions, does this mean that `extern` local functions would be required to explicitly specify `DllImportAttribute.EntryPoint`?

In other words, would the code in https://github.com/dotnet/csharplang/issues/2740 work as is at runtime?

**Comment by HaloFour** [comment]
@svick

`DllImport` is a pseudo-attribute, no?  I'd think that the compiler would write out the metadata with the original name and not the mangled name.  That wouldn't work for custom attributes, though.

**Comment by RikkiGibson** [comment]
When using DllImport on a local function, it is expected that the EntryPoint defaults to the name of the local function as it appears in source.

**Comment by svick** [comment]
@HaloFour Yeah, you're right, I didn't think of that.

@RikkiGibson Good to know.

**Comment by RikkiGibson** [comment]
In the test plan review for this feature, we came up with a scenario where definite assignment safety could be violated in local functions.

```cs
using System.Diagnostics;
using System;

class C
{
    void M()
    {
        int x;
        local1();
        Console.WriteLine(x);
 
        [Conditional("DEBUG")]       
        void local1()
        {
            x = 42;
        }
    }
}
```

In this scenario, `x` is considered definitely assigned after the call to `local1`. But if the compilation doesn't define a "DEBUG" symbol, we won't actually emit the call in IL, and we will end up reading uninitialized local variables.

We think we can solve this by adding the requirement that a local function with ConditionalAttribute must be static.

**Comment by jcouv** [comment]
Closing in favor of https://github.com/dotnet/csharplang/issues/1888 (added link to speclet there)
