### ISSUE TITLE
How to Pass Default Parameters

### ISSUE THREAD

**Issue by mustafauzun0** [dotnet/csharplang#3009]
I want some variables in the function to remain in their default state

JS Way:

function testFunction(arg1="hi", arg2="person") {
 console.log(arg1 + " " + arg2)
}

testFunction(undefined, "mustafa")

output: hi mustafa

C# Way: ?

Maybe we need a new keyword

**Comment by jmarolf** [comment]
@mustafauzun0 does this not work for you?

```csharp
void testFunction(string arg1="hi", string arg2="person") {
	Console.Writeline(arg1 + " " + arg2)
}
```

```csharp
testFunction(arg2:"mustafa")
```

**Comment by mustafauzun0** [comment]
Thanks @jmarolf
