### ISSUE TITLE
Champion "Support extension methods everywhere"

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#301]
- [ ] Proposal added
- [ ] Discussed in LDM
- [ ] Decision in LDM
- [ ] Finalized (done, rejected, inactive)
- [ ] Spec'ed

See also https://github.com/dotnet/roslyn/issues/4565 
I've labeled this "Proposal Champion" because it has been triaged by the LDM, but we don't actually have a champion at this point.

**Comment by TylerBrinkley** [comment]
See also [dotnet/roslyn#16271](https://github.com/dotnet/roslyn/issues/16271)

**Comment by needo2** [comment]
> We decided it would be easier on both programmers and the compiler if we limit the number of places that you have to look for extension methods.

If this is an issue it can be made to accept only private methods for non-static classes.
I wish to be able to build fluent code that will only run inside the class.

**Comment by stamminator** [comment]
Not being able to create extension methods in non-static classes prevents me from using dependency-injected logging inside the extension methods. This makes unit testing difficult and forces me to break things out into services, which adds more complexity than is called for.

Being able to do this would make things much simpler:

```csharp
public class ModelConversionExtensions
{
	private readonly ILogger<ModelConversionExtensions> _logger;
	public ModelConversionExtensions(ILogger<ModelConversionExtensions> logger) => _logger = logger;

	public static DataModel? ConvertToDataModel(this ViewModel vm)
	{
		try
		{
			return new DataModel() { foo_bar = vm.FooBar };
		}
		catch
		{
			_logger.LogError($"Could not convert {nameof(ViewModel)} with Id of {vm.Id} to {nameof(DataModel)}");
			return null;
		}
	}
}
```

**Comment by HaloFour** [comment]
@stamminator 

> Not being able to create extension methods in non-static classes prevents me from using dependency-injected logging inside the extension methods.

A static member cannot access instance members without an instance.  You cannot accomplish what you're describing without some kind of global state, which is pretty much faux pas in a dependency/unit paradigm.  However, you could easily accomplish it via:

```cs
public static class ModelConversionExtensions
{
    private static ILogger<ModelConversionExtensions> _logger = SomeDefaultLogger;

    public static void RegisterLogger(ILogger<ModelConversionExtensions> logger) => _logger = logger;

    public static DataModel? ConvertToDataModel(this ViewModel vm)
    {
        try
        {
            return new DataModel() { foo_bar = vm.FooBar };
        }
        catch
        {
            _logger.LogError($"Could not convert {nameof(ViewModel)} with Id of {vm.Id} to {nameof(DataModel)}");
            return null;
        }
    }
}
```
