### ISSUE TITLE
[Question] array initializer unexpected behavior

### ISSUE THREAD

**Issue by CrispyDrone** [dotnet/csharplang#3014]
Hi,

I seem to be experiencing some unexpected behavior in regards to array creation expression/initializers.

I tried finding additional information about this in the c# language specification, but was unable to. In fact I couldn't even find the part in the specification that says `{ }` is a valid form of an array creation expression (<http://www.ecma-international.org/publications/standards/Ecma-334.htm>).

I have a type `InvoiceDocument` with a property `public byte[] Addendum { get; set; }`

```csharp
byte[] k = { };
var l = new InvoiceDocument
{
    Addendum = { }
};
var m = new InvoiceDocument
{
    Addendum = new byte[] { }
};
```

In this case I get the following results:
1. k = `byte[0]`
2. l.Addendum = `null`
3. m.Addendum = `byte[0]`

Number 2 is unexpected for me. I would assume that after the creation of the invoice document `Addendum` would refer to `byte[0]` instead of null.

**Comment by YairHalberstadt** [comment]
This is a funny one.

```
var l = new InvoiceDocument
{
    Addendum = { 1, 2, 3 }
};
```
Is defined as being equavelent to:

```csharp
var temp = new InvoiceDocument();
temp.Addendum.Add(1);
temp.Addendum.Add(2);
temp.Addendum.Add(3);
```

This would throw a null reference exception, but here you don't actually initialise it with any values so that doesn't happen. This should probably be a warning.

If you're wondering when this is useful, it would be if your class looked like this:

```csharp
public class InvoiceDocument
{
    public List<byte> Addendum { get; } = new List<byte>();
}
```

**Comment by quinmars** [comment]
Infact

```csharp
var l = new InvoiceDocument
{
    Addendum = { 1, 2, 3 }
};
```
would not compile, because the array does not have an `Add` method. The empty braces `{}` are not a collection initializer, but a "simple" object initializer. Following would compile:

```csharp
var l = new InvoiceDocument
{
    Addendum = { [0] = 1, [1] = 2, [2] = 3 }
};
```

**Comment by CrispyDrone** [comment]
Ok, I see. Thanks for clarifying this 😄
