### ISSUE TITLE
Chainable await syntax

### ISSUE THREAD

**Issue by VilemProchazka** [dotnet/csharplang#3018]
Frequently you need a single property of an object returned from an async method. Due to the async behavior it leads to code that in unnecessarily verbal.

**Example for non-async method:**
`var currentUserId = GetCurrentUser().UserId;`

**1. example for async method:**
```
var currentUser = await GetCurrentUser();
var currentUserId = currentUser.UserId;
```

This leads to unnecessary assignment and more lines of code that don't have any useful purpose. It also makes refactoring existing methods from sync to async non-straightforward.

**2. example for async method**
`var currentUserId = (await GetCurrentUser()).UserId;`

This leads to a harder to read code due to the added "step" for figuring out the purpose of the brackets. It also makes you stop while writing, because the process of transferring logic from your head to code stops following a linear path and you need to go back to enclose what you just wrote with brackets.

**Proposed solution: Chainable await**
I propose adding a new keyword that would act as an indicator of await scope ending and would be used at the end of an async call. 

Some possibilities for the syntax:
`var currentUserId = await GetCurrentUser()$.UserId;`
`var currentUserId = GetCurrentUser()$.UserId;`

The second example would make it possible do away with await entirely and could be used even when you don't want to chain:
`var currentUser = GetCurrentUser()$;`

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/835
https://github.com/dotnet/csharplang/issues/827
