### ISSUE TITLE
Compiler should let to compare value of generic parameter to default value

### ISSUE THREAD

**Issue by joostas** [dotnet/csharplang#3029]
**Version Used**: 
dotnet --version
3.1.100
**Steps to Reproduce**:
1.  Minimal code to reproduce issue
```cs
private bool HasValue<T>(T value) => value != default;
```

**Expected Behavior**:
Code compiles
**Actual Behavior**:
Compilation error:
>error CS0019: Operator '!=' cannot be applied to operands of type 'T' and 'default'

Notes:
Code compiles without any errors and warnings if I use 3.0.100 version.

**Comment by jaredpar** [comment]
Moving to csharplang as this is a language question, not a compiler one. 

The decision though was firmly in favor of not allowing this. There is no reasonable way to do this comparison. The way the comparison worked in the time this was allowed effectively did a null check which is unlikely the intent of the author.

**Comment by yaakov-h** [comment]
This was quite explicit and treated as a bugfix as per item 3 [here](https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20post%20VS2019.md).

**Comment by joostas** [comment]
> This was quite explicit and treated as a bugfix as per item 3 [here](https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20post%20VS2019.md).

Thanks for a link. I missed it.
