### ISSUE TITLE
'oninit' property keyword.

### ISSUE THREAD

**Issue by wrkettlitz** [dotnet/csharplang#3033]
### The Problem:

A lot of class 'models' look like something like this:

``` C#
public class Person
{
	[Required]
	public string Name { get; set; }
	public string MiddleName { get; set; }
	[Required]
	public string LastName { get; set; }
}
```
Thanks to [C# nullable reference types ](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) we can now write:

``` C#
public class Person
{
	public string Name { get; set; }
	public string? MiddleName { get; set; }
	public string LastName { get; set; }
}

```
Also nullable reference types helps us avoid unexpected null reference errors. 

However the problem is that we now have the following warning on the Name and LastName property: 

> Non-nullable field is uninitialized. Consider declaring as nullable.

This can easily be fixed by declaring a constructor:
``` C#
public class Person
{
	public Person(string name, string lastname) =>
		(Name, LastName) = (name, lastname);
	public string Name { get; set; }
	public string? MiddleName { get; set; }
	public string LastName { get; set; }
}
```

But as you can see the constructor simply sets values on the properties and does nothing else.
The downside of this is that we not only have to write more code, which can be a lot depending on the class, but consumers of the class also lose information.

Compare this:

``` C#
var person1 = new Person
{
	LastName = "Maniac",
	Name = "Peter",
};
```
With this:
```C# 
var person2 = new Person("Napoleon", "Bonaparte");
```

Although the difference is minor, the first example shows more information to the consumer, not only does the consumer know for sure that he/she is setting properties, he/she also gets Intellisense suggestions about other properties.  

### My Proposal:

The "oninit" property keyword.

The oninit keyword only declares a guideline to the consumer. In essence it just moves the responsibility of the initialization of the property from the implementer to the consumer. 

For example: 
``` C#
public class Person
{
	public string Name { get; set; oninit; }
	public string? MiddleName { get; set; }
	public string LastName { get; set, oninit; }
}
```
This implementation does not cause the "Non-nullable field is uninitialized"-warning, since we declared that it should be initialized on consumption.

If we now try to make a Person object like this. 

``` C#
var person3 = new Person
{
	Name = "Jessy"
};
```
We, the consumers, now get an warning that LastName is not initialized because it has the oninit keyword, is not nullable and does not have a default value set. 

Of course if the class looked like this:

``` C#
public class Person
{
        public Person(string name, string lastname) =>
		(Name, LastName) = (name, lastname);
	public string Name { get; set; oninit; }
	public string? MiddleName { get; set; }
	public string LastName { get; set; oninit; }
}
```
And we used the constructor to initialize the properties we wouldn't have gotten the warning either. 

We can also add a property like: 
``` C#
public int Age{ get; oninit; }
```
This property does allow setting it's value during constructing but not afterwards, because it does not have a setter.

``` C#
var person4 = new Person
{
        // Other inits...
	Age = 5 // No error, no warning
}
var person 5 = new Person
{
	Name = Rosa,
	LastName = Luxemburg
} //Error Age not set.
```
This simulates the behavior of not providing enough arguments to a constructor.  

If age was a nullable int? or had a default value set, we would not have gotten an error but we would not be able to set it afterwards either.
person5.Age = 30; //Error readonly
If age had a setter, there would only be a warning instead. 

### Bonus proposal

In this case the oninit keyword says how many of the following properties should be initialized. 
This is a quick idea i had. ¯\_(ツ)_/¯

``` C#
public class Car
{
	oninit(1)
		{
			public Brand Brand { get; }
			public string BrandId { get; }
		}
} 
```

**Comment by erik-kallen** [comment]
Related: #2830, which unfortunately got very little attention. This problem needs to be solved in one way or another in order for NRT to be useful in application code

**Comment by YairHalberstadt** [comment]
Closing as championed at https://github.com/dotnet/csharplang/issues/3630
