### ISSUE TITLE
Added: LDM Notes for Dec. 16, 2019

### ISSUE THREAD

**Issue by agocke** [dotnet/csharplang#3036]
https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-12-16.md

Agenda:

1. Switch expression as statement
2. Triage

**Comment by YairHalberstadt** [comment]
Why is changing the scoping rules of nameof a breaking change? The same program produces the identical same IL.

The difference is that if you rename one in the future using tooling, it will/will not change the nameof. However that's not a breaking change, and I think it's generally understood that when doing a refactoring you do have to check the output. Given that it's likely the user actually meant the parameter if it was used in an attribute on a method that's probably not a bad thing either.

Trying @cyrusnajmabadi who previously argued this wasn't a breaking change.

**Comment by YairHalberstadt** [comment]
I see I misunderstood. Deleting this and the above.

**Comment by qrli** [comment]
For break expression, I think a larger picture need to be considered. If we compare to other functional languages like F#, match/switch is not the only use case. It is also applicable for if-else, etc.

Infuture, we may also want to write in C#:
```
var foo = if (condition) { bar(); break 1; } else { break 2; }
```
Then the `break` would look weird and confusing.
