### ISSUE TITLE
Proposal: Compile Time Macros via Expression Trees.

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#3040]
## Proposal: Compile Time Macros via Expression Trees.

There have been many requests to add some sort of metaprogramming capability to C#.

There has been some reluctance to make this a first class language feature for a number of reasons:

1. It makes type checking involve running arbitrary user code. This can cause a bad IDE experience.

2. It requires exposing compiler internals to the language.

This proposal is an attempt to solve those problems by providing a limited macro functionality based off expression trees.

### Syntax

A macro would look like a normal method declaration, with the following conditions:

1. It must have the "macro" modifier
2. It must be static
3. All it's parameter types and return types must be Expression Trees

The macro will be called in exactly the same way as a normal method.

For example:

Definition:
```csharp
public static macro Expression<Func<T, string>> Serialise<T>() => ...
```
Usage:
```csharp
Serialise<MyClass>()(m)
```

### Semantics.

To avoid circular references, a macro cannot be used in the same assembly as defined it. Alternatively the compiler could detect circular references, and make them an error.

Type checking proceeds exactly as normal, except than:
a) an expression used in a macro must be stateless. It cannot capture any variables, only constants. See the Capturing State section below for an extension that would allow this to work.
b) a macro returning an `Expression<T>` is type checked as if it is a method returning `T`

After type checking the compiler creates a reference assembly. It then uses this reference assembly to create expression trees for the parameters  and calls the macro with these trees (the macro is treated as the entry point to the assembly - in order to improve performance it might be recommended to AOT compile any dll containing a macro).

If the macro throws, or returns null, it will be considered a compile time error. Perhaps a well known exception could be used if you want to specify the error message, error code or location.

The compiler then calls `.Compile()` on the resultant `Expression<T>` and replaces the call to the macro with the compiled delegate.

The order in which macros are expanded is undefined behaviour. It's also undefined behaviour whether the compiler will use a new process for each call to the macro, or reuse the same process. For that reason making a stateful macro is an extremely bad idea.

### Advantages

1. Only existing constructs in C# are used. No more compiler internals are exposed than previously were.
2. Expression Trees are a well known construct in C#. There already exists a large ecosystem supporting them.
3. Type checking does not require calling the macros, so the IDE experience should not be affected.

### Disadvantages/Limitations

1. Does not allow you to do anything you couldn't before using expression trees. It's advantages are that it allows you to move the associated overhead to compile time, and statically check your usage of expression trees. These are not general purpose macros - they cannot affect the type system.
2. Expression trees provide limited information compared to SyntaxTree or IOperation, which are much richer models.
3. Compilation becomes much more complicated
4. Expression trees don't expose the full range of C# features. They have not been updated in a long time.**
5. Because the compiler has to prove any parameters are stateless, it cannot be passed around. It must be declared in the same method as it is used.

** The reason they have not been updated is that a downstream consumer might use the newer features before an upstream library knows how to cope with them. This would not be an issue for this model, as you would get an error at compile rather than runtime in such a case.

### IDE Experience

A good IDE experience could be achieved by simply ignoring the macros. When a document is visibly displayed to the user, the IDE could run the macro on a background thread in order to display errors to the user if the macro fails.

It should be possible to create tools which can show you the expanded expression tree, as well as decompilers which can convert it to C#, but I don't believe this is necessary for a MVP.

It is important to create a good debugging experience for macros. One way of doing this might be to allow the macro to be called at runtime instead of compile time, perhaps via some sort of preprocessor directive, or compiler switch.

### Open questions

Should the argument to a macro be allowed to call another macro? More generally should macros be allowed in expression trees?

### Suggested Use Cases

1. Compile time code generation and type checking for serialization/deserialization.
2. Enabling features like `fullNameOf(() => A.B.C)` without any runtime overhead.
3. compile time checking that expressions used in ORM queries are valid and can be handled by the ORM

### Out Of Scope

This is not a full blown code generator. It's not meant to replace T4. All it can do is take things which are already possible using expressions, and make them work at compile time, for both performance benefits, and to get errors at compile time.

### Extension: Capturing State

The inability to capture state is a significant limitation.
 
One way of allowing this would be for the macro to be of the form:

```csharp
public static macro Expression<Func<state, TDelegate>> Name<state [typeparams]>([params])
```

The macro must have a type parameter with the special name `state` and must return an `Expression<Func<state, TDelegate>>` where TDelegete is any Delegate type.

Then any expressions that are passed in are rewritten to accept a state parameter instead. So `() => x` becomes `state => state.x`.

The call to the macro is rewritten as a call to the macro followed by passing in the state. So `macro(() => x)` becomes `macro<$GeneratedStateClass>(state => x)(state)`.

During type checking the macro is treated as if it had type `TDelegate`.

**Comment by Joe4evr** [comment]
> Expression trees don't expose the full range of C# features. They have not been updated in a long time.**

Related: #2545.

**Comment by orthoxerox** [comment]
I think we really need a system that describes what we need macros for. There's a great start at https://github.com/dotnet/csharplang/issues/107#issuecomment-398765753, but I think it can be detailed further:

1. We take something that's totally not C# (WSDL, XSD, protobuf, SQL) and generate valid C# types out of it
2. We take something that's not valid C#, but with valid members or statements/expressions and generate valid C# types out of it (Razor)
3. We take existing valid C# types and generate new valid C# types or add new members to them (with partial classes it's more or less the same exercise) (that's what https://github.com/AArnott/CodeGeneration.Roslyn does, and what the current proposal in the Roslyn repo is about)
4. We take existing valid C# type definitions with *invalid* members or statements/expressions inside and rewrite them (generators, async/await would be this if they were implemented outside the compiler)
5. We take existing valid C# members and *rewrite* them (INotifyPropertyChanged, memoization, logging, etc) (replace/original, the other prototype in the VB repo, Fody)
6. We take existing valid C# statements or expressions and *rewrite* them (this proposal)
7. We take *invalid* C# statements or expressions and *rewrite* them (this is technically a subset of 4)

Practically all of this can be solved by macros and reader macros in Lisps, and I think the fewer different mechanisms C# has for this, the better.

Speaking about this proposal specifically, I think its powers are too limited. For example, one of my use cases for macros is emulating a function that returns from the caller. I don't think it can solve it, even though it belongs to group 6.

**Comment by YairHalberstadt** [comment]
@orthoxerox can you give an example of what you mean by:

> emulating a function that returns from the caller

**Comment by eyalsk** [comment]
> Should the argument to a macro be allowed to call another macro? More generally should macros be allowed in expression trees?

I think that this would be a useful feature for the same reason it is available to existing code.

> It must have a visibility of at least internal

Any reason for this?

**Comment by YairHalberstadt** [comment]
>> It must have a visibility of at least internal

> Any reason for this?

@eyalsk I was thinking that if a macro cannot be used outside the assembly in which it's defined, then there would be no point in it being private. Since I left that as an open question I've removed the rule.

**Comment by orthoxerox** [comment]
@YairHalberstadt 

Sure. I have a function with multiple guard clauses and other early returns when we stray off the happy path. Every early return requires either the housekeeping code A or the housekeeping code B, both of which are extracted to helper functions.

This means every early return looks like one of these:
```c#
CleanUpA(someObject);
return;
//or
CleanUpB(someObject);
return;
```

I would like to avoid repeating the `return;` statement everywhere, especially since it's easy to miss. I'd rather both cleanup functions returned the from caller themselves. The code is on a hot path, so I don't want to throw in the cleanup functions and catch in the caller.

A macro would allow me to just inline the cleanup code along with the return statement everywhere I use `CleanUpAAndReturn(someObject)`.

**Comment by YairHalberstadt** [comment]
@orthoxerox 

I see.

The problem is that This form of macro cannot change anything outside of it's context.

Of course you could put the entire method inside a macro:

```csharp
return earlyReturn(() => {
// all your code goes here
});
```

But that means that expression trees will have to be extended to support all C# features, as well as statement body lambdas.

**Comment by orthoxerox** [comment]
I've brushed up on the state of macros in Nemerle, and it looks like my classification is not complex enough to cover them all. Their macros that operate on types and members (3, 4, 5 in my list) are invoked in three different phases of the compiler: https://github.com/rsdn/nemerle/wiki/Macros-tutorial#Execution-stages with different semantics.

**Comment by svick** [comment]
What would be the advantage of making this part of the language, instead of building it as a Fody addin? I think such addin could get quite close to this proposal in terms of both syntax and functionality.

**Comment by YairHalberstadt** [comment]
@svick 

I've had a lot of ideas about how this could be improved with further syntax sugar, and language features, to make it usable in a wider range of scenarios, and with less ceremony. For example, would it be possible for the compiler to treat the result of the macro as a constant, for purposes of attribute arguments? How could we make the syntax friendly enough that you could write `log.DebugMacro(expression)` and have it converted to `if (log.IsEnabled(Debug)) log.Debug(expression);`? Etc.

I haven't added them here as the post is already long enough, and already a pretty big ask.

If this was written as part of fody it would be impossible to develop much further. I think putting this in as a language feature would have the advantage of allowing it to develop into a more powerful set of features over time. Besides people are often afraid of using Fody and other 'magic' and rather inbuilt language features.

Personally I'm not sure I would vote for acting on this proposal - its not clear to me it's benefits outway it's costs. However I think it is interesting enough that it's worth bringing up.

**Comment by AartBluestoke** [comment]
@svick IL weavers increase the cost of every build, negatively impact the accuracy of analyzers, and permanently remove the ability to use Edit and Continue. A C# language feature would not have these downsides.
( this is a copied comment from a different issue where someone suggested "just use fody to hack the language" - https://github.com/dotnet/csharplang/issues/2145#issuecomment-570324621 )

**Comment by YairHalberstadt** [comment]
The only advantage of this proposal over something using roslyn directly is that it allows macros to be part of the language. With source generators it's been made clear that macro style functionality will be provided outside the language using roslyn. As such I see no need for this proposal.
