### ISSUE TITLE
Propsal: constructor allow multiple arguments

### ISSUE THREAD

**Issue by AngryShoes** [dotnet/csharplang#3043]
I try some new features in C# 7.0, one of them supports expression bodies for constructor. however I find only one argument is allowed in expression bodies. for example:
```csharp
class Person
    {
        private string name;
        private string address;
        public string Name { get => name; set => name = value ?? ""; }
        public string Address { get => address; set => address = value ?? ""; }
        public Person(string name) => Name = name;
        public Person(string name, string address) =>{ Name = name, Address = address; }// don't support more than one argument and compile error
    }
```
FYI. maybe it supports multiple arguments in constructor expression bodies will be better? 
https://devblogs.microsoft.com/dotnet/new-features-in-c-7-0/

**Comment by HaloFour** [comment]
You can do this:

```cs
class Person {
    private string name;
    private string address;

    public Person(string name, string address) =>
        (this.name, this.address) = (name, address);
}
```

The compiler is smart enough to elide the creation and deconstruction of the tuple so that it becomes two simple assignments.

**Comment by AngryShoes** [comment]
Thanks for your explanation.
This ticket will be closed now.
