### ISSUE TITLE
Syntax to choose CurrentCulture/InvariantCulture  for interpolated strings

### ISSUE THREAD

**Issue by whut** [dotnet/csharplang#3044]
C# introduced interpolated string, but with no obvious way to decide which CultureInfo to use during formatting.

Currently it is possible to use InvariantCulture like this:

``` csharp
FormattableString.Invariant($"count: {count}")
```

This requires code to target .NET 4.6 and allocates the FormatabbleString instance instead of just generating call to string.Format.

This could be improved by adding some syntax to explicitly choose CultureInfo, like:

``` csharp
$"count: {count}"c    // this will call string.Format with CultureInfo.CurrentCulture
$"count: {count}"i    // this will call string.Format with CultureInfo.InvariantCulture
$"count: {count}"     // as it is now, this will call string.Format without CultureInfo, effectively CurrentCulture
```

This will compile to just string.Format and will not require targeting .NET 4.6.

Also it will be easy to add analyzer to enforce setting the `c` and `i` suffixes always, like we have now in FxCop for string.Format and others.

**Comment by eyalsk** [comment]
dup #177

**Comment by tofalck** [comment]
Perhaps a syntax like below could be used in that it would use the one set right after $, and let any of the placeholder override the default per needs?

This would align with the current overall syntax and enable in-string flexibility?

```
$:en-US"?latitude={lat:F4}&longitude={lon:F4}&amount={amount:C:da-DK}"
$:env"?latitude={lat:F4:invariant}&longitude={lon:F4:invariant}&amount={amount:C}"
```

**Comment by 333fred** [comment]
This was addressed in C# 10 with interpolated string handlers: `string.Create(CultureInfo.InvariantCulture, $"{somevalue} is formatted with invariant culture")` will do this.

**Comment by ufcpp** [comment]
It is more painful to lose CultureInfo in nested interpolation rather than the length of the code.
https://github.com/dotnet/csharplang/discussions/6882

**Comment by DmitryMak** [comment]
A related issue is that `CA1305: Specify IFormatProvider` warning does not apply to interpolated strings (as described [here](https://github.com/dotnet/runtime/issues/88902)). IMHO having no short symmetrical syntax for Current and Invariant cultures makes Globalization warnings ineffective. Should there be no Globalization warnings or should they require a verbose explicit syntax?

```
string.Create(CultureInfo.InvariantCulture, $"{somevalue})
string.Create(CultureInfo.CurrentCulture, $"{somevalue})
```

The warning wouldn't even be required if there was a short symmetrical syntax
```
#"{somevalue} // invariant culture
$"{somevalue} // current culture
```

**Comment by julealgon** [comment]
This requirement to me feels like it would need the exact same underlying mechanism as collection literals would for allowing the passing of constructor parameters.
- https://github.com/dotnet/csharplang/issues/7822#issuecomment-2135333056

If a syntax such as the one I mentioned there was put in place, it would be general enough to apply to interpolation as well:
```csharp
$"{somevalue}"(CultureInfo.InvariantCulture)
```
Or
```csharp
$"{somevalue}" with (CultureInfo.InvariantCulture)
```

@TahirAhmadov This is why I was pushing so much for orthogonality in that other thread. Here we have another very similar situation where a common syntax would be greatly beneficial. You dismissed my suggested general syntax by saying this:
> I can't see the need for a special literal syntax for these types.

But here we are. This is basically the exact same problem, but with interpolated literals. A syntax that was specific for collection literals would not work here and would force a different syntax for passing constructor-like arguments.

**Comment by CyrusNajmabadi** [comment]
the idea of special syntax for these different feature areas is that htey benefit from dedicated syntax per-domain.  For example, one could think of an string as a collection of characters.  That doesn't mean the same syntax for collection-exprs is what we want for strings.  When something is important enough, we actually go away from uniform syntax to specialized syntax.

It's very possible that will be true here as well.  

IMO, for one, i absolutely do not want collection-exprs bogged down by a heavyweight syntax for arguments.  The idea behind collection-exprs is for syntactic overhead to be at an absolute minimum.  That's why, for example, we are not going with `[ [k] = v ]` for dictionaries, even though we use `[k] = v` in object initializers.  We genuinely don't want hte syntax to be as heavyweight as that.

**Comment by julealgon** [comment]
> the idea of special syntax for these different feature areas is that htey benefit from dedicated syntax per-domain. **For example, one could think of an string as a collection of characters. That doesn't mean the same syntax for collection-exprs is what we want for strings.** 

Well I can speak for myself that the reason I suggested the general syntax was not based on that at all... it was just to make sure the new "capability" of allowing to pass extra parameters for short-hand/literals was as orthogonal as possible in the language and could be used consistently in as many cases as possible.

The fact it fits (IMHO) this case here is just a consequence of that, of it being orthogonal.

> When something is important enough, we actually go away from uniform syntax to specialized syntax.

Fair enough, but I just don't see the reason to create dedicated syntax in this (these) particular cases when there are alternatives that are just as clean that apply globally.

> IMO, for one, i absolutely do not want collection-exprs bogged down by a heavyweight syntax for arguments. 

Is this really heavyweight though? It's an extra parenthesis with the desired value... there are like 2 extra characters other than the actual intent there.

```csharp
$"{somevalue}"(CultureInfo.InvariantCulture)
```

Yet here we have proposals for weird stuff like `$i"{somevalue}"`... that's _so_ specific though. What about even other cultures? Are we adding a single-letter identifier for each one? What if I create my own `CultureInfo` object and want to pass that in? Now that would not be possible? Why create such a limiting syntax for something that takes an unbounded number of arguments in the first place.

Maybe we could even go one step further and come up with something like "implicit static using" and allow this without an explicit `static using` at the top of each file:

```csharp
$"{somevalue}"(InvariantCulture)
```

Can you get more concise than that without being limiting and cryptic?

**Comment by colejohnson66** [comment]
https://github.com/dotnet/csharplang/discussions/177#discussioncomment-9619408

**Comment by julealgon** [comment]
@colejohnson66 were you trying to make some point? Can you elaborate?
