### ISSUE TITLE
Proposal: Add exception-safety support for IDisposable in non-owning context

### ISSUE THREAD

**Issue by wmx16835** [dotnet/csharplang#3052]
**The Problem**

Currently, the "using" keyword guarantees exception-safety in a specific context by disposing the associated resources even if an exception is thrown in the block. However, RAII is not always appreciated when using resources. For example:

``` C#
Resource resource = new Resource();   // "Resource" is a class that implements the interface "IDisposable"
Configure(resource, currentContext);  // "Configure" is a method to configure the "resource"; "currentContext" represents a capture of runtime context
SaveToExternal(resource);             // "SaveToExternal" is a method that consumes the "resource" and may have side-effect
```

The code will work fine if every function call returns normally. However, when an exception is thrown during configuration (the second line), "SaveToExternal" will not execute and the "resource" leaks.

We do not have this issue in C++ because of move semantics.

**The Solution**

I would propose a utility method:

``` C#
public static TResource UseWithoutOwning<TResource>(TResource resource, Action<TResource> usingAction) where TResource : IDisposable;
```

It provides the mechanism of using disposable resources in an exception-safe way without binding the ownership to the current context. Its implementation is also straightforward (probably also check for null reference at runtime):

``` C#
public static TResource UseWithoutOwning<TResource>(TResource resource, Action<TResource> usingAction) where TResource : IDisposable
{
    try
    {
        usingAction(resource);
    }
    catch
    {
        resource.Dispose();
        throw;
    }
    return resource;
}
```

With the proposed method above, the 3-line motivating example could be refactored into:

``` C#
Resource resource = UseWithoutOwning(new Resource(), theResource => Configure(theResource, currentContext));
SaveToExternal(resource);
```

It has similar behaviour except for exception-safty -- if the call to "Configure" throws, "resource.Dispose()" will be called automatically.

I am looking forward to your valuable comments.

Thanks,
Mingxin Wang

**Comment by YairHalberstadt** [comment]
Firstly this is a library request, and so should be asked at dotnet/runtime.

Secondly I'm not sure I understand. What is wrong with:

```csharp
using Resource resource = new Resource(); 
Configure(resource, currentContext);
SaveToExternal(resource);
```

Is it that you don't want dispose to be called after configure, only during?

If so that seems like a very niche use case, and doesn't feel like it belongs in the standard library. You could easily provide it in a nuget package and use it wherever you want.

**Comment by mikedn** [comment]
I'm guessing that a more complete/clear example is
```C#
Resource resource = new Resource();
Configure(resource, currentContext);
SaveToExternal(resource);
return resource; // that would explain why using is not an option here
```
> We do not have this issue in C++ because of move semantics.

I'd say that the reason this issue doesn't exist in C++ has less to do with move semantics and a lot more to do with many other C++ aspects that ultimately make RAII possible - possibility of passing any class "by value" rather than just by pointer/reference, presence of destructors, copy constructors etc.

C# doesn't have any of that and if you're intention was to ask for that then good luck, it might be nice to have but it's probably not feasible.

And as already @YairHalberstadt stated, `UseWithoutOwning` is not a language request and I'd add that it doesn't really solve the problem except in particular cases such as the one in your example. As such, it's just a little utility function that you can add to your project if you find yourself needing it often.

**Comment by wmx16835** [comment]
> Firstly this is a library request, and so should be asked at dotnet/runtime.

Sorry for posting it in a wrong channel, I will reopen it in dotnet/runtime as suggested.

> Secondly I'm not sure I understand. What is wrong with:
> 
> ```cs
> using Resource resource = new Resource(); 
> Configure(resource, currentContext);
> SaveToExternal(resource);
> ```
> 
> Is it that you don't want dispose to be called after configure, only during?

I want to avoid leak even if `Configure` throws. The resource is expected to be disposed in an external context in normal control flow.

Here is a concrete use case in our production: we want to construct an instance of `MultipartContent`, which consists of multiple instances of `HttpStreamContent`. Both of the two classes are defined in namespace `System.Net.Http` and implement `IDisposable`. In normal control flow, an instance of `MultipartContent` is initially created, and other instances of `HttpStreamContent` are created & configured, accordingly. When the instance of `MultipartContent` is no longer needed, its `Dispose` method is expected to be called, but it is not necessary to call `Dispose` on any instance of `HttpStreamContent` since they have become a part of `MultipartContent`. The problem is that, when an exception is thrown when configuring an instance of `HttpStreamContent` before it is added to `MultipartContent`, the instances could not be disposed properly before the exception throws to outer scope.

**Comment by wmx16835** [comment]
> I'm guessing that a more complete/clear example is
> 
> ```cs
> Resource resource = new Resource();
> Configure(resource, currentContext);
> SaveToExternal(resource);
> return resource; // that would explain why using is not an option here
> ```

Thanks, that looks better.

> > We do not have this issue in C++ because of move semantics.
> 
> I'd say that the reason this issue doesn't exist in C++ has less to do with move semantics and a lot more to do with many other C++ aspects that ultimately make RAII possible - possibility of passing any class "by value" rather than just by pointer/reference, presence of destructors, copy constructors etc.

I agree. "move semantics" is also built on top of "value semantics".

> C# doesn't have any of that and if you're intention was to ask for that then good luck, it might be nice to have but it's probably not feasible.

I do not think it feasible to add complete value semantics into C# either, but since we need exception-safety, I think such workaround is necessary.

> And as already @YairHalberstadt stated, `UseWithoutOwning` is not a language request and I'd add that it doesn't really solve the problem except in particular cases such as the one in your example.

I will close the issue in this channel since it is a library request, sorry. However, I think it does solve the problem, because "whether to dispose a resource or not" is an "yes or no" option in a certain context. "using" is designed for "yes", and the proposed library is for "no". Comparing to C# with C++, every scoped value in C++ is a "using" in C#; every call to `UseWithoutOwning` is a "move construction" in C++.

**Comment by mikedn** [comment]
FWIW something that could be perhaps be called "move" may be a more reasonable language feature:
```C#
Resource Create()
{
    using Resource resource = new Resource();
    Configure(resource);
    return move resource;
}
```
that would expand to
```C#
Resource Create()
{
    using Resource resource = new Resource();
    Configure(resource);
    Resource temp = resource;
    resource = null;
    return temp;
}
```
Though it would certainly need a better keyword than "move".

And it cannot be simulated with a method like:
```C#
static T Move<T>(ref T o) where T : class
{
    T temp = o;
    o = null;
    return temp;
}
```
so it kind of needs to be a language feature.

**Comment by wmx16835** [comment]
> FWIW something that could be perhaps be called "move" may be a more reasonable language feature:
> 
> ```cs
> Resource Create()
> {
>     using Resource resource = new Resource();
>     Configure(resource);
>     return move resource;
> }
> ```

This solution looks clean, but I am not confident enough about the motivation to solve this problem at the language level.

> that would expand to
> 
> ```cs
> Resource Create()
> {
>     using Resource resource = new Resource();
>     Configure(resource);
>     Resource temp = resource;
>     resource = null;
>     return temp;
> }
> ```

The code won't compile today because it is not allowed to assign another value to a "using" variable, otherwise we may redefine the semantics of "using", which would be much more difficult.

**Comment by svick** [comment]
I think the situation where a disposable object is not disposed due to an exception is fairly common in C#. But the method proposed here is not really a solution, because it's applicable only in a small subset of cases where this happens. So, what is the solution? We don't need one. As long as this doesn't happen too often,  doing nothing should be okay, since the GC and finalizers will eventually clean up the leaked resources.

**Comment by wmx16835** [comment]
@svick 

> But the method proposed here is not really a solution, because it's applicable only in a small subset of cases where this happens.

I do not think so. Could you provide some concrete cases in the "major subset" where the proposed solution is not applicable?

> As long as this doesn't happen too often, doing nothing should be okay, since the GC and finalizers will eventually clean up the leaked resources.

Although I cannot tell whether it is "often" enough for the motivation, because I have not done any statistical research yet, I do see a lot of cases in our production code. GC and finalizers may help with this kind of issue, but it is not always reliable (and won't work at all in some particular cases), that is the reason why we need "IDisposable" to prevent leak and have introduced the keyword "using".

**Comment by wmx16835** [comment]
The issue was moved to [dotnet/runtime #1150](https://github.com/dotnet/runtime/issues/1150).

**Comment by wmx16835** [comment]
I reopened this issue because several feedback have suggested this to become a core language feature. Therefore I would like to see more comments from experts in this group. Please let me know if one issue shall not be posted in both csharplang and runtime.

**Comment by YairHalberstadt** [comment]
@wmx16835 

I think if you want to suggest a language feature you have to suggest the syntax and semantics for your feature.

I think it extremely unlikely that a special syntax for your current proposed library method would be added. A new language feature is orders of magnitude more expensive than new library features, so if there was doubt whether it's common enough to belong in the standard library, it almost definitely does not belong in the language.

Instead you would need to come up with a more wide ranging design for adding full support for move semantics to C#.

Even then be aware that the vast majority of proposals, especially large, wide ranging proposals do not get implemented. I would estimate it at about 1/500 for large, community suggested features.

**Comment by ronnygunawan** [comment]
This looks fine to me:
```cs
Resource Create()
{
    Resource resource = new Resource();
    Configure(resource);
    return resource;
}

// caller:
using Resource resource = Create();
```

If `Configure` threw an exception, then the `using` statement won't be reached.
If `Configure` didn't throw an exception, then the `using` statement will be reached.

**Comment by wmx16835** [comment]
@YairHalberstadt 

Thank you for the comments. I would much prefer to persue it as a pure library feature since it is apparently implementable, unless there is a sence of strong consensus among the library experts to make it a language feature.

**Comment by wmx16835** [comment]
@ronnygunawan

> This looks fine to me:
> 
> ```cs
> Resource Create()
> {
>     Resource resource = new Resource();
>     Configure(resource);
>     return resource;
> }
> 
> // caller:
> using Resource resource = Create();
> ```
> 
> If `Configure` threw an exception, then the `using` statement won't be reached.

And the `resource` created inside the `Create` method leaks.

**Comment by ronnygunawan** [comment]
Since, the Create method returns a type that implements IDisposable, then it becomes caller's responsibility to dispose it.

You can add `Microsoft.CodeAnalysis.FxCopAnalyzers` nuget package to your project to detect such leak. It will produce warning whenever an `IDisposable` object is not disposed before all references to it are out of scope:

```cs
void Foo() {
    Resource resource = Create(); // warning: Call System.IDisposable.Dispose on object created by 'Create()' before all references to it are out of scope.
}
```

**Comment by HaloFour** [comment]
I have a helper class for this.  It's basically a composite disposable in which you can register one or more other disposables, but you can "release" ownership of the disposables so that they aren't disposed at the end of the using block.

```cs
using (var builder = new DisposableBuilder())
{
    var resource1 = builder.Using(new Resource1());
    var resource2 = builder.Using(new Resource2());
    Configure(resource1, resource2);
    
    return builder.Build(() => new WrappingResource(resource1, resource2));
}
```

Up until the call to `Build` returns successfully the `builder` will dispose any resource registered through the call to `Using`.

**Comment by svick** [comment]
@wmx16835 

> > But the method proposed here is not really a solution, because it's applicable only in a small subset of cases where this happens.
> 
> I do not think so. Could you provide some concrete cases in the "major subset" where the proposed solution is not applicable?

I was thinking of cases like when you have a constructor that initializes multiple disposables and can also throw:

```c#
class C : IDisposable
{
    readonly Resource1 resource1;
    readonly Resource2 resource2;
    
    C()
    {
        resource1 = CreateResource1();
        resource2 = CreateResource2();
        MethodThatCouldThrow();
    }
    
    /// IDisposable implementation, etc.
}
```

I don't see how the method you proposed could be used here, considering that a `readonly` field can't be initialized from a lambda.

> > As long as this doesn't happen too often, doing nothing should be okay, since the GC and finalizers will eventually clean up the leaked resources.
> 
> Although I cannot tell whether it is "often" enough for the motivation, because I have not done any statistical research yet, I do see a lot of cases in our production code. GC and finalizers may help with this kind of issue, but it is not always reliable (and won't work at all in some particular cases), that is the reason why we need "IDisposable" to prevent leak and have introduced the keyword "using".

Well, does this cause actual issues in your production code?

It's true that finalizers are not good enough as a general solution. But I think that for these situations, they are adequate, because the leaks should be rare and short-lived. Certainly better than having to worry about exception safety like you do in C++.

Also, in what cases will finalizers "not work at all"?

**Comment by wmx16835** [comment]
Please refer to [the latest revision of this issue](https://github.com/dotnet/runtime/issues/1163).

@HaloFour and @svick 
I have updated the design with detailed wording. The "Consideration" part in the new revision may address your concern.

Thanks,
Mingxin Wang
