### ISSUE TITLE
Proposal: Adds Caller Info attribute for class name

### ISSUE THREAD

**Issue by leandromoh** [dotnet/csharplang#3056]
We have attributes for FilePath, LineNumber, Member, but nothing to the type/class name.

Reference:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/caller-information

**Comment by HaloFour** [comment]
Check out #87

**Comment by leandromoh** [comment]
@HaloFour it is even better than I could thought. However, I saw this issue was created 14 Feb 2017.. Any prevision?

**Comment by YairHalberstadt** [comment]
Closing as subsumed by https://github.com/dotnet/csharplang/discussions/87
