### ISSUE TITLE
Introduce a "lazy" declaration modifier as shorthand for Lazy<T> implementation.

### ISSUE THREAD

**Issue by adamjstone** [dotnet/csharplang#3057]
# Abstract

The `Lazy<T>` type is useful in type definitions for which usage of internal resources varies heavily depending on consuming scenarios. But making use of this feature can require writing a lot of code.

Consider this example:

```cs
public class Foo
{
    public Foo(IConfiguration configuration) { Configuration = configuration; }
    public ExpensiveObject Bar => LazyExpensiveObject;
    private ExpensiveObject InitializeExpensiveObject() => new ExpensiveObject(Configuration);
    private readonly IConfiguration Configuration;
    private Lazy<ExpensiveObject> LazyExpensiveObject = new Lazy<ExpensiveObject>(InitializeExpensiveObject);
}
```

The addition of a shorthand `lazy` declaration modifier would hide this machinery from the developer. The resulting source would look like this.

```cs
public class Foo
{
    public Foo(IConfiguration configuration) { Configuration = configuration; }
    public lazy ExpensiveObject Bar => new ExpensiveObject(Configuration);
    private readonly IConfiguration Configuration;
}
```

# Discussion

Additional thoughts and open questions are discussed below.

## Lazy{T} Members

Notice in my example that the member `Bar` is not of type `Lazy<ExpensiveObject>`. I am deliberately proposing, for this use case, that `IsValueCreated` information is hidden from the developer completely. Perhaps there are good reasons not to do that but I'm proposing this as an abstraction for all of those details, which users are choosing by employing the shorthand.

## LazyThreadSafetyMode

The feature as I have proposed it here does not permit developers to specify a `LazyThreadSafetyMode` for the `Lazy<T>` constructor. The default would have to be used when employing the keyword or (I'm not sure I like this), additional keywords could be use to alter that. For example:

```cs
// Specifies that LazyThreadSafetyMode.ExecutionAndPublication is used.
lazy var bar = locked new ExpensiveObject(Configuration); 

// Specifies that LazyThreadSafetyMode.None is used.
lazy var baz = volatile new ExpensiveObject(Configuration); 

// Specifies that LazyThreadSafetyMode.Publication is used.
lazy var qux = new ExpensiveObject(Configuration);
```

**Comment by Joe4evr** [comment]
This is pretty much a duplicate of #312.

**Comment by adamjstone** [comment]
Closing since, as @Joe4evr pointed out, another issue is closely related and already has a deep history of conversation.
