### ISSUE TITLE
Relax necessity of adding `f` to floating numbers

### ISSUE THREAD

**Issue by RUSshy** [dotnet/csharplang#3063]
Currently this code doesn't compile

``float myFloat = 5.0;``

I need to add ``f`` at the end, which is annoying

This rule doesn't exist in C++, not even in D or Rust

**Comment by YairHalberstadt** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/2929

**Comment by RUSshy** [comment]
oops my bad! thanks
