### ISSUE TITLE
AllowNullAttribute not working as intended?

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3065]
This example straight from the [_Try out Nullable Reference Types_](https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/) article does not seem to be working correctly for me:

```c#
public class MyClass
{
    private string _innerValue = string.Empty;

    [AllowNull]
    public string MyValue {
        get {
            return _innerValue;
        }
        set {
            _innerValue = value ?? string.Empty;
        }
    }
}

var y = new MyClass();
y.MyValue = null; // Error: CS8625 Cannot convert null literal to non-nullable reference type.
```

I can't seem to get `[AllowNull]` to work correctly in any case. This is in a .NET Core 3 project using VS2019 16.4.2. Switching to .NET Core 3.1 does not fix the issue either.

Am I missing something here?

**Comment by yaakov-h** [comment]
I cannot reproduce the error on either SharpLab or locally with the .NET Core 3.1 SDK.

**Comment by canton7** [comment]
([SharpLab link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEA3GUCWAZgJ5oAmIA1AD4ACATAIwCwAULQAwAEtjAdABF8AQwDmAOwgBnDPjBS+AYQhkYAQXHCANsSn4pAbjYBicQFctW4cC0wuMTTZhtaAZh70uirgG82XAJ53WhQuAFkACgBKX39A+OxhKC5iLgBeLnEYAHdw4kUrKSloo1Z4+OI+MOIANW0zOwzzS1L4gF82DtYXYM9qguEitj8ywIAHAkSMO15uAH18cSyoOq0G9J5GDj4AUQBbMYxiUriAgG01SwhsgDkLLQBdU6DN7mrV9ZHywNEYDFjRt94rQAOxcBZLPAfGCtIFdIFcKR/AEI+IQ5bQjaJNZ2AD8uNeuwOR1h33hgS6bSAA=))

**Comment by mikernet** [comment]
Haha...my mistake...my attribute was coming from the wrong namespace from another package :/ When I pasted it into SharpLab to test it out it also wasn't working but that was for a different reason, but it all makes sense now. Thanks for the working SharpLab example, helped me figure it out.

**Comment by canton7** [comment]
I think the attribues in `System.Diagnostics.CodeAnalysis` are meant for you to add to your code, and the ones in `System.Runtime.CompilerServices` are inserted automatically by the compiler.
