### ISSUE TITLE
Unnecessary "Argument cannot be used for parameter due to differences in the nullability of reference types" (CS8620)

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3067]
Is there is any reason for this to be throwing CS8620:

```c#
private string GetFormattedMessage(IDictionary<string, object?> tokenValues) { }

var tokens = new Dictionary<string, object>();
string message = GetFormattedMessage(tokens); // CS8620 - differences in nullability
```

Why can't I pass in a type with a non-nullable reference type generic argument into a parameter that accepts the same type argument as nullable? Maybe I'm missing something, but that seems to me like the equivalent of not allowing a `string` to be passed into a `string?` parameter.

**Comment by HaloFour** [comment]
@mikernet 

It's a problem of variance.  `GetFormattedMessage` could do this:

```cs
private string GetFormattedMessage(IDictionary<string, object?> tokenValues) {
    tokenValues.Add("foo", null);
}
```

The compiler wouldn't warn about that.

**Comment by mikernet** [comment]
I know what the problem is. I just don't think it should be a problem. Why would it be?

**Comment by HaloFour** [comment]
Same reason you can't pass a `Dictionary<string, string>` to a method that accepts `IDictionary<string, object>`.

**Comment by mikernet** [comment]
I deleted my previous comment, the second I hit post I realized what you said :) 

Well dammit...I would use `IReadOnlyDictionary` if it read-only collections weren't so broken and useless but alas I can't. Alrighty, thanks.
