### ISSUE TITLE
What is a "where T : class?" constraint?

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3069]
I'm writing some nullable analysis code and found this constraint mentioned in several places and this code compiles but I can't for the life of me figure out what effect the `?` has on code when added to the `class` constraint:

```c#
public class MyList<T> where T : class?
{
    public void Add(T value) { }
}

// compiles fine even though constraint is different:
public class MyDerivedList<T> : MyList<T> where T : class 
{
}

var list = new MyList<string>(); // compiles fine even though T parameter is not nullable
list.Add(null); // still gives error that the parameter can't be null
```
So far it seems like it behaves the same as if the constraint was just `class` instead of `class?`.

**Comment by mikernet** [comment]
Nevermind, I got it...`class?` allows you to do `var x = new MyList<string?>()` whereas `class` does not. Holy cow, NRTs are way more complex than it first appears...so many nuances to consider.

**Comment by 333fred** [comment]
@mikernet, please consider using either the gitter (https://gitter.im/dotnet/roslyn) or the csharp discord (https://discord.gg/csharp) as avenues for these questions, rather than opening issues on this repo. This repo is intended for language proposals.

**Comment by mikernet** [comment]
@333fred My apologies, NRTs apparently aren't very well documented yet so I figured this might come up if someone has the same question but I realize now this is probably not the right place for that.

**Comment by 333fred** [comment]
If you see issues with the docs, they can be filed on the docs repo here: https://github.com/dotnet/docs
