### ISSUE TITLE
Discussion: event subscription in object initializers

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#307]
Moved from https://github.com/dotnet/roslyn/issues/5365

Extend object initializer block to support event subscriptions:
```cs
var timer = new DispatcherTimer {
    Tick += delegate {},
    Interval = TimeSpan.FromSeconds(1d),
};
```
->
```cs
var timer = new DispatcherTimer();
timer.Tick += delegate {};
timer.Interval = TimeSpan.FromSeconds(1d);
```
**Open question:** should we allow multiple event subscriptions for a single event at a time?
```cs
var timer = new C{
    Event += delegate {},
    Event += delegate {},
};
```

**Comment by drewnoakes** [comment]
I'd love to see this. It'd allow several construction/initialisation operations to become single expressions, which play nicely with other C# features that reduce nesting such as expression bodies, null coalescing, ternary conditionals...

**Comment by CortiWins** [comment]
I would love this!

**Comment by blair-ahlquist** [comment]
No. The feature that should be implemented is like this: Whenever curly braces are used directly after an object, that object's properties and methods can be referred to directly. The return value for the resulting expression is the original object. It wouldn't be required to come directly after a constructor.

    public class C
    {
        public event EventHandler SomethingChanged;
        public string Name { get; set; }
        public void Initialize(IInterface i);
    }

And then:

    someC = c.{ Name = "SomeC";
    SomethingChanged += someC_SomethingChanged;
    Initialize(i);
    };
I set a property, registered for an event, and called a method all within the curly braces. The return value for the expression was then set to `someC`. More better. It covers the requested behavior for events and does so much more.
