### ISSUE TITLE
Support Static Abstract on Interface

### ISSUE THREAD

**Issue by Randy-Buchholz** [dotnet/csharplang#3070]
Interfaces have taken many perspectives/forms these days, but one remains the idea of a simple contract -> "a class that implements this interface will provide these methods". There are cases where it makes sense to say, "a class that implements this interface will provide a static method with this signature". 
In C# 8 we can create statics on interfaces, but they must declare a body. 
```
// valid:
interface IFoo {
  static void Bar() { ... }
}

// not valid
interface IFoo {
  static void Bar();
}
```
Allowing `static abstract` would provide the basic "contract nature" for static members -
```
interface IFoo {
   static abstract void Bar();
}
```
This would require, in the realizing class,
```
class Foo : IFoo {
   public static void Bar() { ... }
}
```
_____________________________
This is useful for things like Builders,
```
class MyHostedService : BackgroundService, ICustomHostedService {
  // ICustomHostedService features
  public static IHostBuilder CreateBuilder () { … }
}
```  
with
```
interface ICustomHostedService {
   // stuff
   static abstract IHostBuilder CreateBuilder();
}
```
I can be explicit about `MyHostedService` needing to realize a static Builder.

**Comment by HaloFour** [comment]
See:

#1711
#164

Whatever design results from those explorations may enable what you describe, but with the current design of both the language and the runtime the concept of a virtual static interface member doesn't make sense because virtual dispatch requires an instance through which a virtual table can be interrogated in order to determine what method to invoke.  With static methods there is no instance and no vtable, you can only call one specific method, and that method needs to be known at compile time.

**Comment by Trayani** [comment]
Besides what has already been said, have you considered to use generics?
Something along these lines:

```
interface ICustomHostedService {
   // for non-generic references
   IHostBuilder CreateBuilder();
}

interface IGenericCustomHostedService<T> : ICustomHostedService  {
  IHostBuilder ICustomHostedService.CreateBuilder() => new HostBuilder<T>();
  static IHostBuilder CreateGenericBuilder<T>() => new HostBuilder<T>();
}
```

**Comment by Randy-Buchholz** [comment]
@HaloFour My thought is that you wouldn't/couldn't invoke a static abstract on the interface. It would be purely contractual. Along Mads Item 3 - "the interface must implement a corresponding static member".  Declaring the static abstract wouldn't error, but trying to call it (on the interface) would. I don't know the internals so I'm sure it's much more complex, but essentially the design-time error is suppressed, and the check for implemented members checks for existance. It wouldn't need to exist in the virtual table since it can't be called.

I'm finding a need for this with nullables. Nullables are great, but they highlight a business/technology gap and temporality. I.e., something may required at use (business), but not required at creation (technology). So there is a time period were the item could be null, but is logically not nullable. As long as there is a value at first use we don't care what form it took between creation and first use. There seems to be a standard approach to addressing this - `.Empty`. In it's simplest form - `public static Empty => new Foo()`.  Looking at interfaces from the contract/specification perspective, I want to be able to specify that the realizing class will provide `Empty`. So in my (specifying) interface I should be able to indicate that. This way I can make the item not-null and have a "dummy" value to cover the temporal gap if I don't have a required value at creation. (Aside - `Empty` could become first-class -if a class has `Empty` it could be served from `default` for not-nulls.)

@Trayani That's the approach I'm currently taking.
