### ISSUE TITLE
Interface Classic

### ISSUE THREAD

**Issue by Randy-Buchholz** [dotnet/csharplang#3072]
Related to: https://github.com/dotnet/csharplang/issues/3070

Proposed: Applying `static abstract` to an interface indicates that the interface is a contract/specification only.

When I first encountered interfaces (circa 1985) they were pretty simple. They were a specification for the public methods (only) a class (not object/instance) must realize. They defined intended behavior. Times have changed, and modern interfaces contain more than just methods, they apply to objects, and now (C#8) they have their own implementations. These changes are (for the most part) good, but have been giving interfaces a split personality. In #3070 @HaloFour pointed out that `static abstract` methods didn't make sense from an implementation perspective - they wouldn't exist in the instances. It seems we are loosing some of the contractual design nature of interfaces.

In theory, it might be time to split off a new construct for these "hybrid" (part implementation, part contract) interfaces, but that is not a reality. It does seem to make sense, though, that a designer should be able to "design to interfaces" without having to consider the underlying implementation details; and to use interfaces in the "classic" way.

The basic idea of this proposal is to provide a way for designers to indicate that an given interface does nothing more than define a logical specification. The `static abstract` modifier might be a way to do this. It could be implemented similarly to how nullable reference types are implemented - as complier warnings and not deep language changes.

Declaring an interface as `static abstract` would mean that it is not intended to be "used directly". I don't know how implementation might actually work, but conceptually, opting into abstract interfaces adds a little preprocessing that results in a standard interface. Three general things take place.

First, warnings are generated in the IDE when disallowed conditions exist. E.g., IFoo.Bar() -> "Warning: Invoking method on abstract interface".

Second, analysis ensures that classes implement the specified behavior. This would not be limited to directly or through inheritance, but could also look for extension methods that provide the behavior.

Third, the preprocessor scrubs invalid syntax before handing it to the complier. E.g., 
```
abstract interface Foo {
   static int Bar();
}
```
becomes
```
interface Foo {
   // static int Bar();
}
```
Using `static abstract interface` is logically consistent, as `static` implies an association with a class, not instance. And `abstract` implies a concept, not a concretion.

This approach let's us better "program to interfaces" in the classical sense by specifying a "contract" and ensuring (by warning) that that behavior is implemented directly, through inheritance, or by extension, and loosens some of the constraints on interfaces imposed by the language implementation (i.e. statics without bodies on interfaces).

**Comment by mikernet** [comment]
I can actually kinda see where you are going with some of this. I don't know if I agree with all the details of your proposal but I have run into situations where all types that implement a particular interface *should* also implement a static method with a particular signature, i.e. a builder. That method is ultimately called by reflection but enforcing that all `IWhatever` implementations contain some required static method can definitely be a handy enforcement tool.

I don't know if extending this concept to instance methods makes sense though - what's wrong with just using interfaces the way they currently exist for that?

**Comment by jmarolf** [comment]
The intention with default interface methods was to make certain parts of a contract _optional_. A lot of people appear to feel that being able to add a default implementation fundamentally changed how interfaces should be considered. I would argue that is not the case. Interfaces are still contracts its just that some of that contract is optional.

**Comment by Randy-Buchholz** [comment]
I tried a few variations of this in my modeling tools and have come to agree with everyone. It feels a little weird. I extended my tools to allow "design hints" that don't get generated in the interfaces, but optionally the classes. I can reverse engineer the code and run my checks to see if base classes or extension methods implement the hints.
