### ISSUE TITLE
Aggregation blocks

### ISSUE THREAD

**Issue by 0x000000EF** [dotnet/csharplang#3077]
There is a very common scenario in programmig when we apply an array of logical conditions for the same variable
```cs
if (name.Contains("Wi-Fi") || name.Contains("Bluetooth") || name.Length is 9)
```
Nice to have something like this to avoid repeating and simplify `null`-checks
```cs
if (name.[Contains("Wi-Fi") || Contains("Bluetooth") || Length is 9])

if (name?.[Contains("Wi-Fi") || Contains("Bluetooth") || Length is 9] is true)

if (GetName().[Contains("Wi-Fi") || Contains("Bluetooth") || Length is 9])

if (GetName()?.[Contains("Wi-Fi") || Contains("Bluetooth") || Length is 9] is true)
```
Recursion
```cs
if (name.[Contains("Wi-Fi") || Contains("Bluetooth") || Length.[ is 9 || > 16]])

if (name.[Contains("Wi-Fi") or Contains("Bluetooth") or Length.[ is 9 or > 16]])
```
Possible `with`-like generalization
```cs
//GetItem()?.
item?.
[
   CallInstanceMethod();
   PropertyA = valueA;
   PropertyB.
   [
      PropertyC = valueC;
   ]
]
```

**Comment by RUSshy** [comment]
not sure if adding a feature just for this specific usecase is a good idea

if C# had better lambda/scope functions/high order functions like in kotlin or swift, we could easily do something like

kotlin:
```kotlin
val name = "something interesting"
fun main(args: Array<String>) {
    println( with(name) { contains("interesting") } )  
    println( with(name) { contains("interesting") && length == 5 } )
}

// true
// false
```

And that would benefits many other use cases, especially when it comes to DSLs, and that's something C# needs ASAP


playground: https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS4zLjYxIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoidmFsIG5hbWUgPSBcInNvbWV0aGluZyBpbnRlcmVzdGluZ1wiXG5cblxuZnVuIG1haW4oYXJnczogQXJyYXk8U3RyaW5nPikge1xuXG4gICAgcHJpbnRsbiggd2l0aChuYW1lKSB7IGNvbnRhaW5zKFwiaW50ZXJlc3RpbmdcIikgfSApXG4gICAgXG4gICAgcHJpbnRsbiggd2l0aChuYW1lKSB7IGNvbnRhaW5zKFwiaW50ZXJlc3RpbmdcIikgJiYgbGVuZ3RoID09IDUgfSApXG59In0=
