### ISSUE TITLE
Allow explicit control of beforefieldinit (especially with NRTs)

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3080]
As a library developer I'm constantly mangling code that would otherwise be much simpler and easier to understand to avoid writing a static constructor that causes the `beforefieldinit` flag to be removed. Usually, this involves adding a superfluous `static bool _initialized = Initialize()` field or returning one of the field values with the `Initialize()` method and setting the rest of the fields inside it. This means my read-only fields can't be marked `readonly`, and has now become more of a burden with NRTs because now I have to make reference fields all nullable or silence the warning by setting them to `default!`.

Can we please add a `[BeforeFieldInit(bool)]` attribute that controls static initialization behavior?

This is a long-standing issue that I've seen discussed countless times in other places (StackOverflow questions, forum posts, team meetings, library PRs, also just found this one in Roslyn: https://github.com/dotnet/roslyn/issues/4448) with a very simple fix which will make NRTs much more pleasant. I think that makes it a good candidate for immediate implementation. It will also remove the need to have empty static constructors which often get mistaken for something that can be removed with no undesirable effects.

**Comment by YairHalberstadt** [comment]
Why do you need to avoid `beforefieldinit` from being removed?

**Comment by mikernet** [comment]
Performance

**Comment by YairHalberstadt** [comment]
Do you have some measurements of the performance impact of beforeFieldsInit?

**Comment by mikernet** [comment]
The performance impact of adding a static constructor is well understood and has been measured many times before. Offhand I don't have the numbers, but it adds overhead to every single static field access on the type which can add up.

**Comment by mikernet** [comment]
This is a long-standing issue that is well understood. See the last 2 posts in this thread: https://github.com/dotnet/roslyn/issues/4448

**Comment by mikernet** [comment]
The "avoid static constructor" issue comes up in lots of libraries. The presence or absence of a static constructor vs field initializers is a very odd way to forcibly determine how the type is initialized but that ship has sailed, so there should at least be a mechanism available to specify what you want.

**Comment by mikernet** [comment]
These tests measure a 30% difference: http://nickberardi.com/static-constructors-in-net-3-5-still-a-bad-thing/

This guy experienced a much larger difference: https://stackoverflow.com/questions/14570846/why-does-adding-beforefieldinit-drasticly-improve-the-execution-speed-of-generic

These are old posts though, and maybe I'm micro-benchmarking incorrectly because the simple test I just rigged up isn't showing a difference...so it might be the case that "non-beforefieldinit" field access has been optimized recently. If that's the case, then I can't see why `beforefieldinit` would ever be desirable anymore though, and the attribute would still be nice so that I don't have to litter static constructors everywhere, haha.

Does anyone have more insight into this?

**Comment by mikernet** [comment]
Nevermind, I'm seeing a 10% difference in my test now, so it may have been optimized so it isn't as bad as before, but there's still a difference there.

**Comment by YairHalberstadt** [comment]
Tiered compilation (which is enabled by default in more recent .Net Core runtimes) should be able to eliminate the overhead as when it rejits it knows the static constructor has been called. If this isn't happening maybe you should raise an issue on dotnet/runtime.

**Comment by mikernet** [comment]
The following consistently shows a 15% performance penalty for the static constructor:

```c#
public static class StaticCctor
{
	public static bool Value { get; set; }
	
	static StaticCctor() { 
		Value = true;
	}
}

public static class FieldInit
{
	public static bool Value { get; set; } = true;
}

void Main()
{
	int iterations = 100000000;
	bool result;
	
	for (int i = 0; i < 5; i++) {
		RunTest("field init", () => {
			bool value = false;
			for (int i = 0; i < iterations; i++) {
				value = FieldInit.Value;
			}
		});
	}
	
	
	for (int i = 0; i < 5; i++) {
		RunTest("static cctor", () => {
			bool value = false;
			for (int i = 0; i < iterations; i++) {
				value = StaticCctor.Value;
			}
		});
	}
}

public static void RunTest(string name, Action action)
{
	try {
		var sw = new Stopwatch();
		action();
		
		sw.Start();
		
		action();
			
		sw.Stop();
		
		Console.WriteLine($"{name.PadLeft(20)}: {sw.Elapsed}");
	}
	catch (Exception ex) {
		Console.WriteLine($"{name.PadLeft(20)}: {ex.Message}");
	}
}
```

**Comment by mikernet** [comment]
Given how fast field access is, the actual penalty for the field access is in actuality going to be much higher than 15% as a large percentage of the execution time of that simple loop will be taken up by iterating the loop.

**Comment by YairHalberstadt** [comment]
@mikernet

I would suggest using BenchmarkDotNet for performance testing. IMO a homegrown testing framework is practically worthless.

**Comment by mikernet** [comment]
Here ya go:

```
| Method |      Mean |     Error |    StdDev |
|------- |----------:|----------:|----------:|
| Static | 18.870 us | 0.1066 us | 0.0997 us |
|  Field |  2.713 us | 0.0099 us | 0.0092 us |
```

Code:

```c#
const int iterations = 10000;

public static class StaticCctor
{
    public static bool Value { get; set; }

    static StaticCctor()
    {
        Value = true;
    }
}

public static class FieldInit
{
    public static bool Value { get; set; } = true;
}

public class BeforeFieldInit
{
    [Benchmark]
    public void Static()
    {
        bool value;

        for (int i = 0; i < iterations; i++)
            value = StaticCctor.Value;

    }

    [Benchmark]
    public void Field()
    {
        bool value;

        for (int i = 0; i < iterations; i++)
            value = FieldInit.Value;
    }
}
```

**Comment by YairHalberstadt** [comment]
That does look quite significant (of course the chances are it will be minor in most normal code, as it will usually be dwarfed by other factors, but I can imagine there are some cases where it is actually a bottleneck).

I would again suggest bringing this up with dotnet/runtime, as if tiered compilation can solve this, that would have the benefits of working automatically for all code without needing to manually add the attribute.

**Comment by mikernet** [comment]
Unfortunately (or fortunately? I do love it immensely, haha) I almost exclusively work on highly performance-sensitive library code like core database engine logic, entity object frameworks, etc, haha.

**Comment by mikernet** [comment]
It's not so much about being a "bottleneck" so much as even a 5% gain for a set of optimizations in the type of library code I work on is a huge win.

**Comment by mikernet** [comment]
Performance issues aside, controlling the timing of when you want a class to run its static initialization shouldn't be controlled entirely by the presence or absence of a static constructor.

**Comment by mikernet** [comment]
Oops...my home-rolled benchmark code shows the same results as benchmark.net, I was just accidentally running in debug mode :/ That makes more sense.

**Comment by jmarolf** [comment]
We should talk to @stephentoub and others working on corefx and get their opinion. If anyone has this as a pain point it is them.

**Comment by YairHalberstadt** [comment]
There's been some extremely helpful input from @AndyAyersMS and @jkotas over at https://github.com/dotnet/runtime/issues/1327.

If I may summarize the discussion there:

1. In general tiered compilation can mostly eliminate the overhead from removing `beforefieldsinit`.
2. In some cases the tier 1 Jit happens too early, before the static constructor is called.
3. If this proves to be a pain point, there are a couple of techniques that could be used to solve this in the Jit.

I think this implies that there's unlikely to be a need for this language feature from a performance perspective. Instead, it would be useful to gather evidence that this is an issue that affects real world code, not just benchmarks. That would provide an incentive to optimize this in the Jit.

There may of course still be a desire for this attribute for reasons of semantics rather than performance. However I think that is a rather niche case, and unlikely to be implemented as a language feature.

Instead something like https://github.com/alexb5dh/BeforeFieldInit.Fody might be more appropriate for those who do want to be able to configure this.

**Comment by mikernet** [comment]
@YairHalberstadt Great to know about the Fody add-in, thanks for pointing that out! I'll probably end using it for now, but weavers come with their own set of issues that would be nice to avoid.

**Comment by mikernet** [comment]
Still curious what @stephentoub thinks of this as he's been trying to eliminate static constructors in the BCL and I'm sure this attribute could be liberally applied in many other places in the BCL to continue those efforts without having to refactor all the static constructors.

**Comment by stephentoub** [comment]
I currently personally don't think adding such a control would be worth it.

**Comment by mikernet** [comment]
Fair enough then, I'll close the issue. Thanks for your input.
