### ISSUE TITLE
Allow #! directive to occur on any line of a script submission

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/csharplang#3082]
In order to support [magic commands](https://ipython.readthedocs.io/en/stable/interactive/magics.html) that are syntactically correct C# and can also be used between other lines of C# code within a submission, the proposal is to use `#!` as the .NET magic command directive. This directive is currently allowed on the first line of a script submission but disallowed on subsequent lines. 

The current .NET Jupyter implementation uses the IPython syntax but this is not workable in the long term. For more context, see https://github.com/dotnet/try/issues/577. 

The following illustrates an existing use case (cell 4) and the resulting error when using `#!` after the first line of a submission (cell 5):

![image](https://user-images.githubusercontent.com/547415/71845824-04a29d80-307e-11ea-8c1e-6ee366b22f6c.png)

**Comment by YairHalberstadt** [comment]
Closing as championed at https://github.com/dotnet/csharplang/issues/3507

**Comment by 333fred** [comment]
This is separate from the shebang proposal.

**Comment by 333fred** [comment]
Talked with Jon offline. Going to close this out as it's no longer necessary (and any future feature requests here might be more related to LSP).
