### ISSUE TITLE
Reference properties similar to Action/Func

### ISSUE THREAD

**Issue by xZise** [dotnet/csharplang#3084]
Hi, I've tried searching for this feature, but it seems you cannot get a reference to a property similar to how you can get one to a method of a class.

So I'm proposing to add a special notation to get the reference to a property, similar to how `AddressOf` gets the reference to a method in VB.net. In my example I've used `@` before a property, but more like a place holder for a better notation. This returns a `Property<T>` object (or one of the two interfaces if it only supports a getter or setter) which basically "facades" the real property in back.

Then you could have something like this.
```C#
class FirstExample
{
    bool Enabled { get; set; }
}

class SecondExample
{
    bool Focused { get; set; }
}

void Main()
{
    FirstExample e = new FirstExample();
    ToogleBool(@e.Enabled)
    SecondExample e2 = new SecondExample();
    ToogleBool(@e2.Focused)
    // Currently this needs to implemented this way
    ToogleBoolOld(() => e2.Focused, b => e2.Focused = b);
}

void ToogleBool(Property<bool> prop)
{
    prop.Set(!prop.Get());
    prop.Value = !prop.Value;  // Alternative
}

void ToogleBoolOld(Func<bool> setter, Action<bool> getter)
{
    setter(!getter());
}
```

My idea was that there are two interfaces and a class representing a property, something like this:
```C#
interface IReadProperty<T>
{
    T Get();
    T Value { get; }  // Alternative
}

interface IWriteProperty<T>
{
    void Set(T value);
    T Value { set; }  // Alternative
}

sealed class Property<T> : IReadProperty<T>, IWriteProperty<T>
{
}
```

Here a showcase why there are different interfaces/classes:
```C#
class ReadOnly
{
    string Name { get; }
    bool Active { get; }
}

class WriteOnly
{
    string SinkHole { set; }
}

void Example(ReadOnly r, WriteOnly w)
{
    PrintString(@r.Name);
    WriteUsername(@w.SinkHole);
    ToogleBool(@r.Active);  // Does not work, because Property<bool> != IReadProperty<bool>
}

void PrintString(IReadProperty<string> prop)
{
    Console.WriteLine(prop.Value);
}

void WriteUsername(IWriteProperty<string> prop)
{
    prop.Value = Environment.UserName;
}
```

In theory the `IReadProperty<T>` could be an alias for `Func<T>` and `IWriteProperty<T>` for `Action<T>`, but I'm not sure how this could be "implemented". So that this could work too:
```C#
void PrintString(Func<string> func)
{
    Console.WriteLine(func());
}
```

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/1677 ?
