### ISSUE TITLE
How to remove warning after checking against null in void method?

### ISSUE THREAD

**Issue by Advitalitum** [dotnet/csharplang#3088]
Warning CS8602 on line ```var length = args.Length;```
#2366 not helped. There is no attribute called EnsuresNotNullAttribute
```csharp
internal class Program
{
	private static void Main(string[]? args)
	{
		ValidateAgainstNullAndThrow(args);

		var length = args.Length;
		
		Console.WriteLine("Hello World!");
	}

	private static void ValidateAgainstNullAndThrow(string[]? args)
	{
		if (args is null)
		{
			throw new ArgumentNullException();
		}
	}
}
```

**Comment by 333fred** [comment]
Use the `[NotNull]` attribute on the argument of `ValidateAgainstNullAndThrow`.

**Comment by Advitalitum** [comment]
Mark argument that can be null as [NotNull]? Is this correct?

**Comment by 333fred** [comment]
That's correct. `NotNull/MaybeNull` are _output_ modifiers. They do not affect the starting state of the argument. `AllowNull/DisallowNull` are input modifiers, and would warn you if you passed null in.

**Comment by 333fred** [comment]
See the docs here: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-attributes#specify-post-conditions-maybenull-and-notnull
