### ISSUE TITLE
Better DebuggerDisplay for Lambdas

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3089]
It would be really nice if the DebuggerDisplay for Lambdas showed all captured variables.

**Comment by YairHalberstadt** [comment]
@TonyValenti that would be a request for visual studio user voice.

**Comment by TonyValenti** [comment]
Done!  If you want to vote on it:
https://developercommunity.visualstudio.com/idea/880268/better-debuggerdisplay-for-lambdas.html
