### ISSUE TITLE
Proposal: new operator like nameof, but for whole expression

### ISSUE THREAD

**Issue by leandromoh** [dotnet/csharplang#3100]
since `nameof` operator returns only the last member of the expression, to get the full path we must call `nameof` multiple times, as follow:

```c#
$"{nameof(httpContext)}.{nameof(httpContext.Response)}.{nameof(httpContext.Response.StatusCode)}"
```
to get the `httpContext.Response.StatusCode` string

if c# would have a new operator that get whole expression, only the last call would be sufficient. so I propose a new operator to do this job, that returns the same previous string.
```c#
fullnameof(httpContext.Response.StatusCode) == "httpContext.Response.StatusCode" // true
```

**Comment by alrz** [comment]
This will work in some future release, likely vnext
```cs
static string FullNameOf(object e, [CallerArgumentExpression(nameof(e))] string n = null) => n;
```

**Comment by Joe4evr** [comment]
For reference: https://github.com/dotnet/csharplang/blob/master/proposals/caller-argument-expression.md

**Comment by leandromoh** [comment]
thanks for the references! C# has a lot to improve meta-programming :/

**Comment by ds1709** [comment]
This feature will be useful in cases when you need full namespace on compile time, such as attributes, e.g., XmlnsDefenutionAttribute in WPF where you should specify full CLR namespace.

**Comment by dersia** [comment]
I am not sure if I like this as is.
If I want the full name I could always call `typeof(T).FullName` and since there is effort to make this a constant at compile time that would be sufficient even for attributes.

I would rather have a `nameof(class.member.member)` that gives back exactly what I've put in `class.member.member`

Sometimes I just need the path without names pace, sometimes I need only the path even without the class name.

**Comment by stevenbrix** [comment]
@dersia, however `typeof` doesn't work for namespaces, so you're stuck using `nameof`.

**Comment by dersia** [comment]
@stevenbrix probably this is why I said, that I'd rather have a nameof that returns exactly what you have give it, just the namespace, sure.

You can always use  typeof(T).FullName - nameof(T) to get the namespace (and path if nested).
