### ISSUE TITLE
Proposal: support var keyword for method and static types.

### ISSUE THREAD

**Issue by aaroncaffrey** [dotnet/csharplang#3105]
I propose a feature for c# that the var keyword could be used in more places instead of explicit type declarations.  Specifically, the declaration of static members and the declaration of methods where the return type can be detected.  In the case of methods with no return type, var could also detect (infer) void.  This would allow for concise, simpler and cleaner syntax whilst still allowing for explicit declarations if required.

```
//old syntax: 
public static List<int> list = new List<int>();

//new syntax:
public static var list = new List<int>();


//methods: old syntax:
public List<int> get_ints()
{
    return new List<int>() { 1, 2, 3, 4, 5 };
}

//methods: new syntax:
public var get_ints()
{
//either:
 return new List<int> { 1, 2, 3, 4, 5 };
//or:
 return new var { 1, 2, 3, 4, 5 }; // Arrays and Lists could be differentiated between for example using {} or [].
}

// Also const, but less important/useful:
// const values: old syntax
const int i = 1;

// const values: new syntax
const var i = 1;

**Comment by AartBluestoke** [comment]
1) var could never be part of the method signature, this is critical information that must never be hidden, and often could not be easily inferred. People will often only look at the sig and not the contents.

2) target typed new (#100 ) provides the same simplification, but on the other side of the equals. "I have a List that has just been created (as an object of the same type)" makes more sense to me than "i have a thing (its type doesn't matter) that is a new List"

**Comment by aaroncaffrey** [comment]
To say that var could never be part of a method signature is just not true; many other languages support exactly this.  Also, is it not the case that either enclosures, anonymous functions, and lambda statements all can return a variable without explicit type declarations, by using type inference, equivalent to using the var keyword?  Moreover, var is an explicit type, just inferred, so the type can be easily viewed if using an IDE.  Additionally, I don't agree that it is difficult to infer a return type, the compiler has to do exactly that to check that the returned value actually matches the return type.

**Comment by gafter** [comment]
I don't know what "can be detected" means. That simple phrase is a deep nest of ambiguity and is the reason this feature request has been rejected over and over again.

```csharp
var Fib(int n) => (n < 2) ? 1 : Fib(n - 1) + Fib(n - 2);
```

Anyway, that's my floating-point version of a simple fibonacci number generator.

**Comment by aaroncaffrey** [comment]
I mean type inference.  In any case, one last shot, could the compiler not just reject ambiguous declarations?

**Comment by mikernet** [comment]
As @gafter alluded to, there are issues with cycles when resolving a `var` return type and the C# compiler would have to be completely uprooted to support something like this and it would still be limited. 

Regardless, having `var` anywhere in a method signature is a bad idea (in my opinion) because small changes to a method body can easily cause unintended and difficult to detect changes to the resulting method signature, which would make it **way** too easy to accidentally introduce breaking changes to your code.
