### ISSUE TITLE
typeof Declaration

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3111]
It would be really nice to be able to use ````typeof(member)```` as an alias for the type of another member.  This would make areas of the code "refactoring proof" and allow type changes in one area to automatically ripple to related APIs.

For example:
````
GetMember<typeof(DevModeA.Drive.Printer.Papersize)>(MemberReference);
//Same as: GetMember<PrinterPaperSizeEnum>(MemberReference);
````
or
````
typeof(MyClass.BaseMember) x = CalculateDerived();
//Same as: BaseClass x = CalculateDerived();
````

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/1294.

**Comment by TonyValenti** [comment]
Yep!  I'll close this one.
