### ISSUE TITLE
Quiz on LOH

### ISSUE THREAD

**Issue by nur858** [dotnet/csharplang#3113]
I am setting some quiz questions. There have been some questions raised about the following question. I am not sure if this is the right place but I would really appreciate any comment. Mostly I would like to know if the question is the right to evaluate someone's understanding of LOH.

Suppose a Dictionary<Product> type collection contains 1000 objects and takes 100kb of memory and is short-lived. Which one is true?
* The object is assigned to GEN0 heap
* The object can be efficiently garbage collected
* The object is compacted
* This type object can potentially shrink usable memory over time

**Comment by YairHalberstadt** [comment]
I would suggest the dotnet/runtime gitter

**Comment by nur858** [comment]
Thanks. Closing
