### ISSUE TITLE
Pattern matching and unassigned local variable

### ISSUE THREAD

**Issue by kofifus** [dotnet/csharplang#3114]
A very common programming idiom is to have a function returning an error state (ok/bad) and results, a common way to do this in C# is with `out` - `public bool TryGetValue(TKey key, out TValue value)`

I find `out` visually confusing, I prefer having the output on the left of the function name and the input on the right:

```
(bool ok, string name1, string name2) MyFunc() {
  if (DateTime.Now.Year > 2020) return (false, "", ""); // error 
  return (true, "some value", "some value");
}
```

My coding style is often to test for errors first and exit, I would like to do that without introducing another variable as that gets confusing with multiple calls needing ok1, ok2 etc ..

I would like to do:
```
void f() {
  if (MyFunc() is (false, var name1, var name2)) return;
  Console.WriteLine(name1);
}
```

This would express my intent very clearly without introducing an unneeded ok variable, however this results in `Error CS0165 Use of unassigned local variable 'name1'` after the `if`

Looking in sharplab - https://sharplab.io/#gist:d85241726b13674be5418064b1816034 I see the result of MyFunc is there but the compiler does not assign name1 & name2 

Why is that ? I would like to suggest this will be ammended as it can be a simple/useful way to code this common scenario..

**Comment by HaloFour** [comment]
@kofifus 

This behavior is very intentional and very correct.  In any language that has pattern matching the pattern variables are not assigned unless the entire pattern is successfully matched.

**Comment by kofifus** [comment]
@HaloFour 

> The language isn't deconstructing the tuple into the variables and then comparing the constant, it's comparing the constant first.

Yes true, I can see that in the sharplab.io

Why aren't the variable assigned ? I can see no penalty in terms of performance as they can just be optimized to the value tuple elements, it all seems like missing syntactic sugar to me unless I'm missing something ? this would be very useful

**Comment by HaloFour** [comment]
@kofifus 

It's not a matter of performance, it's a matter of the entire pattern matching.  If the pattern didn't match, there's nothing to assign to those variables.  It's not like the deconstruction happens first into those variables and then the pattern is applied.  It's an all-or-none situation.  That pattern could be applied to any type, including non-tuples or incompatible tuples.

**Comment by kofifus** [comment]
OK, I see .. in this case though in order to find out if the pattern matches , MyFunc is called and so all the variables are available so the compiler could make them available ... but I guess the answer is no ..

**Comment by DavidArno** [comment]
This is very easily handled with existing pattern matching features: assign the `ok` to a variable and then test it. That way, your other variables get assigned too:
```cs
void f() 
{
  if (MyFunc() is var (ok, name1, name2) && !ok) return;
  Console.WriteLine(name1);
}
```

**Comment by Richiban** [comment]
@kofifus Your use case will work fine if you just flip the condition:

```csharp
void f() {
      if (!(MyFunc() is (true, var name1, var name2))) return;
        
      Console.WriteLine(name1);
    }
```

This pattern is exactly the reason that the pattern variables were designed to be 'leaky'.

**Comment by kofifus** [comment]
@Richiban that's exactly what I needed, thanks
