### ISSUE TITLE
Bodyless Constructors and Methods

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3119]
Always writing a body can be a frequent minor annoyance and I'm personally just irked by the aesthetic of empty blocks.

Constructors, before:

```c#
public StringProcessor() : this(default(Encoding))
{
}

public StringProcessor(CountType countType) : this(default(Encoding), countType)
{
}

public StringProcessor(string? encodingName, CountType countType = default)
    : this(GetEncoding(encodingName), countType)
{
}

public StringProcessor(Encoding? encoding, CountType byteCountType = default)
    : base(byteCountType.FixedCount)
{
    Encoding = encoding ?? .....
   // rest of constructor
}
```

Constructors, after:

```c#
public StringProcessor() : this(default(Encoding));

public StringProcessor(CountType countType) : this(default(Encoding), countType);

public StringProcessor(string? encodingName, CountType countType = default)
    : this(GetEncoding(encodingName), countType);

public StringProcessor(Encoding? encoding, CountType byteCountType = default)
    : base(byteCountType.FixedCount)
{
    Encoding = encoding ?? .....
   // rest of constructor
}
```

Empty virtual methods, before:

```c#
public abstract class ClientConnection
{
    // Required:

    public abstract void Authenticate(string username, string password);

    public abstract void DispatchMessage(string message);

    // Optional:

    protected virtual void ProcessElevationRequest(ElevationRequest request)
    {
    }

    protected virtual void OnHeartbeatReceived()
    {
    }
}
```

Empty virtual methods, after:
```c#
public abstract class ClientConnection
{
    // Required:

    public abstract void Authenticate(string username, string password);

    public abstract void DispatchMessage(string message);

    // Optional:

    protected virtual void ProcessElevationRequest(ElevationRequest request);

    protected virtual void OnHeartbeatReceived();
}
```

**Comment by CyrusNajmabadi** [comment]
You could just write them like so:

`void Foo(){}`

If you really want them on one line.

**Comment by canton7** [comment]
We already have that syntax, but it's used for things which declare a method but don't give it a body (i.e. abstract methods, interface methods, partial methods). Under this proposal, if I see a method with no braces, I have to take account of context (e.g. are we in an interface or a class) to know whether I'm looking at a method declaration, or something which also declared an empty body.

Not worth it just to save 2 characters, IMO.

**Comment by mikernet** [comment]
@canton7 You don't need to look at the type context, you will know based on whether the method definition is abstract, virtual, or neither.

**Comment by mikernet** [comment]
Oh, wait, I see what you mean. I suppose you would, but if you don't know if you're currently looking at a method or an interface then you have bigger problems, haha.

**Comment by mikernet** [comment]
You might be right about DIMs...I haven't jumped into using those yet and looking at the syntax, that might be an issue. I'll have a closer look and if it seems like it'll be a problem then I'll close this issue.

**Comment by mikernet** [comment]
Yeah, this gets weird with DIMs. Nevermind :)
