### ISSUE TITLE
Expression.Property performance

### ISSUE THREAD

**Issue by IAmTheCShark** [dotnet/csharplang#3121]
`Expression.Property`'s performance heavily relies on the ammount of Properties in the target object when the Expression is a LambdaExpression like

`() => Foo`

It ultimately comes down to the Method [Expression.GetProperty](https://referencesource.microsoft.com/#System.Core/Microsoft/Scripting/Ast/MemberExpression.cs,291)
```
private static PropertyInfo GetProperty(MethodInfo mi) {
            Type type = mi.DeclaringType;
            BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic;
            flags |= (mi.IsStatic) ? BindingFlags.Static : BindingFlags.Instance;
            PropertyInfo[] props = type.GetProperties(flags);
            foreach (PropertyInfo pi in props) {
                if (pi.CanRead && CheckMethod(mi, pi.GetGetMethod(true))) {
                    return pi;
                }
                if (pi.CanWrite && CheckMethod(mi, pi.GetSetMethod(true))) {
                    return pi;
                }
            }
            throw Error.MethodNotPropertyAccessor(mi.DeclaringType, mi.Name);
        }
```

that needs to iterate over all the objects Properties to get the corresponding PropertyInfo for the MethodInfo that is used due to the fact that the compiler used RuntimeMethodHandle under the hood.

This is what the compiler does (according to [sharplab.io](sharplab.io)):
`Dump(Expression.Lambda<Func<string>>(Expression.Property(Expression.Constant(this, typeof(C)), (MethodInfo)MethodBase.GetMethodFromHandle((RuntimeMethodHandle)/*OpCode not supported: LdMemberToken*/)), Array.Empty<ParameterExpression>()));`
   

An Idea to fix this is would be to expose a fast way to get a PropertyInfo from its get or set method or even use the PropertyInfo directly instead.

I can provide a Unittest that demonstrates the performancedifference between two objects, one with 500 and one with 10 properties.

I am really sorry if I picked the wrong repo again.

**Comment by HaloFour** [comment]
You can't get a runtime handle for the property directly.  The CLR only offers runtime handles for methods, fields and events.  Looking up a property info from a method handle of one of getter accessor method is probably the faster way to look it up compared to by name or other methods, which would still have to iterate over the properties.  Can you demonstrate a faster way to resolve propertied by reflection at runtime?

**Comment by IAmTheCShark** [comment]
@HaloFour yes, `Type.GetProperty(string)` for example is faster.
All you need to do is check for special name and skip the get_ / set_:

Also I suggested exposing a fast "official"  api like `PropertyInfo.FromMethod(MethodInfo)` or something.

**Comment by canton7** [comment]
I think there's already a cache, and it's used for `Type.GetProperty(string)`. I can't see a reason why `Expression.Property(MethodInfo)` can't at least start by testing whether the `MethodInfo`'s name starts with "get_" or "set_", and trying `Type.GetProperty(methodInfo.Name.Substring(4)` if so -- it can check whether it's definitely got the right property before returning, and can fallback to the current behaviour if for some reason it doesn't find anything.

Although that's a question for runtime, not csharplang.

**Comment by HaloFour** [comment]
@canton7 

> I can't see a reason why `Expression.Property(MethodInfo)` can't at least start by testing whether the MethodInfo's name starts with "get_" or "set_"

The runtime doesn't enforce that naming convention.  The methods could be named quite literally anything, including invalid C# identifiers.

If anything I think it'd be more appropriate if the runtime could cache the properties by the runtime method handle of the getter accessor method.  That should provide the same benefit.

**Comment by canton7** [comment]
@HaloFour 

Indeed, which is why I was very clear that, if the naming convention wasn't followed, it would fall back to the current behaviour at very little additional cost.

Introducing another cache will be a harder argument to make, I think (although you might be able to get it through)

**Comment by HaloFour** [comment]
Never hurts to ask, I opened https://github.com/dotnet/runtime/issues/2011 to see if they would be amenable to such a cache.

**Comment by YairHalberstadt** [comment]
This is definitely not the right repo for this suggestion. Since dotnet/runtime#2011 was opened and closed with:

> Closing as this is a feature request. This library is effectively archived and new features do not meet the bar for changes.

I think it makes most sense to just close this issue.
