### ISSUE TITLE
Compiler incorrectly handles NotNullWhen when explicitly testing the result

### ISSUE THREAD

**Issue by foxesknow** [dotnet/csharplang#3129]
If a method has the **[NotNullWhen(false)]** attribute applied to a parameter then the compiler does not support explicit checking of the return value against false. Logical negation is supported, and works as expected.

Regardless of the merits of such a test I believe that comparing with ** == false** should be the same from a nullable reference type perspective as doing **!** on the result, and therefore I believe this is a bug in the implementation of nullable reference types.

```
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

namespace CoreConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            string? value = Initialize();

            if(IsNullOrWhiteSpace(value) == false)
            {
                // Compiler thinks value may be null
                Console.WriteLine(value);
            }

            if(!IsNullOrWhiteSpace(value))
            {
                // Compiler knows value isn't null
                Console.WriteLine(value);
            }
        }

        static string? Initialize()
        {
            return null;
        }

        static bool IsNullOrWhiteSpace([NotNullWhen(false)]string? value)
        {
            return string.IsNullOrWhiteSpace(value);
        }
    }
}
```

**Comment by AartBluestoke** [comment]
The problem is that == is a binary opperator.
bool Equals(this bool a, bool b)
Unless there is a language level special case for bool, it is hard to say how the return value of this function influences the null state of the string.

**Comment by foxesknow** [comment]
The fact it's a binary operator shouldn't prevent the the correct analysis of the flow here.

The language already has special case support for boolean values in relation to nullable reference types. Attributes like  **NotNullWhen** introduce this support so that flow analysis can be performed correctly - the issue here is that it's not been fully implemented. Flagging a parameter as not being null when false is returned shouldn't cause a problem when I compare the return value to false. It's pretty explicit and introduced a special case which says the analysis only works with certain operators.

**Comment by 333fred** [comment]
@jcouv has been looking at stuff in this area.

**Comment by jcouv** [comment]
PR https://github.com/dotnet/roslyn/pull/41349 should fix this.
