### ISSUE TITLE
Task state machine switching position

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [dotnet/csharplang#3131]
When you run task in background (without await) this task code will run synchronously untill first await within it, but state machine switching is happening AFTER first await, which means calling method will wait first await too.
Is there any reason for this behaviour or it was made non intensional?
I'm asking because while asynchronous in not parallel, that's not obvious that first await will run in same thread (synchronously) where calling method is running.
Maybe changing this behaviour to switching BEFORE await is good idea?
Because now I'm thinking to add Task.Yield() as first line to all my async methods

**Comment by CyrusNajmabadi** [comment]
> Is there any reason for this behaviour 

Yes, it was intentional.

> that's not obvious that first await will run in same thread (synchronously) where calling method is running.

1. We felt it was sensible.  The point where a continuation happens is where the code actually does the 'await'.
2. this allows code to do things like error checking up front and have that actually impact the calling code.  Something that was much more confusing for people when that *didn't* happen.

> Maybe changing this behaviour to switching BEFORE await is good idea?

At this point that would be impossible.  It would be a huge breaking change that very likely would break many applications that are intentionally depending on the current behavior.

> Because now I'm thinking to add Task.Yield() as first line to all my async methods

Go for it :)

**Comment by amis92** [comment]
I'll just drop in to say that there's `Task.Run` if you specifically want to go to 'background'. I don't think yield will work as you might want it to for some cases, as it's a bit more dependent on process/task processor time allocation.

**Comment by CaCTuCaTu4ECKuu** [comment]
When I hit this behaviour I thought of Task.Run but It it looks like a crutch.
If it is intensional then, as I understand, running background task using Task.Run is preferred way to go?
What possible problems I can face if I use Task.Yield? In my case I can't see difference, but maybe there's something I should keep in mind?

**Comment by YairHalberstadt** [comment]
`Task.Yield` means that you'll be causing allocations, and suffering the overhead of task scheduling for no reason. In some domains this may not matter, but in others it most definitely does.

If not running something on the same thread is important than explicitly calling `Task.Run` is probably the way to go.

**Comment by amis92** [comment]
The difference is, if you use Task.Yield() you just say to the current thread: "go back to me when you can" while Task.Run is "ask scheduler to run this delegate". For UI apps (desktop, mobile) the difference is that if you run your method on UI thread, Task.Yield will not push the remainder of the method off that thread - on the contrary, Yield means "I want to execute on that context, but it might be a bit later than now". `Run` means "run this on any thread" which for UI apps will mostly mean non-UI threads.

**Comment by CaCTuCaTu4ECKuu** [comment]
Thanks for all the info.
In my case I have behaviour that will get advantage if switching will happen before await and now I see I may better run Task.Run in around 50% of method calls to await it later, but I guess you get what you get and at least there's an options
