### ISSUE TITLE
in-keyword

### ISSUE THREAD

**Issue by IAmTheCShark** [dotnet/csharplang#316]
C# really could use an `in` or alternatively `is in` keyword like other languages (e.g. TSQL) offer.

It allways feels wrong writing code like

    if (new[] {1,2,3,4}.Contains(id)) {

    }
    
    if (id == 1 || id == 2 || id == 3 || id == 4) {

    }

    switch(id)
    {
       case 1: case 2: case 3: case 4: {  ...  } break;
    }

    public static bool IsIn<T>(this T value, params T[] values) => values.Contains(value);

    if(id.IsIn(1,2,3,4)) {

    }

when this would feel / look so much better

    if (id in { 1,2,3,4 }) {

    }

The compiler should be able to generate something like the `switch` statement out of this so that there is no arraycreation involved like the extensionmethod does.

Making it work for Enumerables is a bonus

    if (id in listOfIds) {
    }
where the compiler should just translate it into `Enumerable.Contains`

I think this is connected to `Discussion: Range operator` #198

**Comment by DavidArno** [comment]
[Active patterns](https://github.com/dotnet/csharplang/issues/277) (coupled with [Permit IEnumerable<T> as the type of a params parameter](https://github.com/dotnet/csharplang/issues/179)) would completely cover this use case (and many, many more);
```cs
public bool InPattern<T>(this IEnumerable<T> collection, T matchValue) =>
    collection.Contains(matchValue);

...
if (id is In(1,2,3,4)) 
{
}

switch(id)
{
   case In(1,2,3,4) : ...
}

**Comment by alrz** [comment]
Active patterns are not extremely useful here a regular extension method works just fine,
```cs
static bool In<T>(this T value, params T[] values) { .. }

if (value.In(1, 2, 3)) 
```
unless you want to use it in a `switch` statement.

OR patterns (https://github.com/dotnet/csharplang/issues/118) can also be helpful.
```cs
if (value is 1 | 2 | 3)
```

**Comment by IAmTheCShark** [comment]
@alrz I know it is nitpicking but the extensionmethod comes with a few "drawbacks"
Most important to mention is the array creating, while my idea of that keyword was to avoids this.

Apart from that you might need a reference to the assembly where that extensionmethod is located plus a using statement to make it avaible.
