### ISSUE TITLE
Proposal: Shorter property syntax for object encapsulation and propery getters and setters

### ISSUE THREAD

**Issue by thargol1** [dotnet/csharplang#3169]
This is a proposal for a shorter syntax for read-write properties. When implemented it saves 4 lines of code per use.

Take a look at this code:
```csharp
public class A
{
	private B b;

	public A(B b) => this.b = b;

	public Name
	{
		get => b.Name;
		set => b.Name = value;
	}
}
```

This is a pattern often used when inheritance is not possible, e.g. if B is sealed of if you already inherit from another class.

Proposal for shorter syntax:

```csharp
public class A
{
	private B b;

	public A(B b) => this.b = b;

	public string Name <=> b.Name;
}

```

In some cases explicit typecasting is needed, e.g. when encapsulating untyped collections:
```csharp
public class A
{
	private NameValueCollection values;

	public A(NameValueCollection values) => this.values = values;

	public string Name <=> (string)values["Name"];

	// Compiles to:
	//public string Name
	//{
	//	get => (string)values["Name"];
	//	set => values["Name"] = value;
	//}
}

```
The syntax is an obvious variation on `=>`, but with a bidirectional arrow.

I looked for similar proposals but did not find them. I they do exists please enlighten me how to find them, e.g. which keywords to use. #528 covers the same topic but is not what I'm looking for.

**Comment by yaakov-h** [comment]
This appears to be a duplicate of #1007.

**Comment by Unknown6656** [comment]
#1327
#1571
#1691
#1735

**Comment by thargol1** [comment]
Duplicate of #1007
