### ISSUE TITLE
C# Unicode Operators

### ISSUE THREAD

**Issue by mikaeldui** [dotnet/csharplang#3172]
**Version Used**: 
3.1

**Steps to Reproduce**:
1. Use Unicode operators instead of the normal, like ≥ instead of >=.
2. Try compile.
3. See the error.

**Expected Behavior**:
**Unicode operators should be supported** as Unicode is widely available and limited support has already been introduced in C#.

**Actual Behavior**:
C# doesn't recognize Unicode operators and only compiles if one's using ASCII alternatives. This means more energy is spent reading and writing code than what'd be needed using Unicode operators.

**Comment by AdamSobieski** [comment]
I would like to indicate an approach utilized by Mathematica for [entering special characters and mathematical notation](https://reference.wolfram.com/language/tutorial/SpecialCharacters-MathematicalAndOtherNotation.html). In Mathematica, one utilizes the escape key before and after a string, that string being an alias for a desired symbol or glyph. So, `[esc]>=[esc]` transforms into `≥` in the editor.

Also, Unicode symbols or mathematical notations needn't be in the syntaxes of programming languages for editors or IDE's to render special characters, glyphs or mathematical notations. One could define, instead, a means of recognizing and transforming syntactically valid strings, for example `^intersection^`, into glyphs or symbols identified by the text strings, in this case `intersection`, which could then be rendered as `∩` while appearing as `^intersection^` in a source code file.

**Comment by amis92** [comment]
> means of recognizing and transforming syntactically valid strings

Isn't that exactly what Fira Code font does with ligatures? As it was linked above? https://github.com/tonsky/FiraCode/wiki/Visual-Studio-Instructions

**Comment by CyrusNajmabadi** [comment]
> In Mathematica, one utilizes the escape key before and after a string, that string being an alias for a desired symbol or glyph. So, [esc]>=[esc] transforms into ≥ in the editor.

Note:

1. this seems to be an editor request.
2. This seems unnecessary.  It's already possible to get this transformation in editors.  i.e. in my VS this is what `>=` already looks like:

![image](https://user-images.githubusercontent.com/4564579/74070815-f1555b80-49b6-11ea-95df-7d8461bfffdd.png)

This already works well as this character appropriately takes up two columns of width, ensuring that all monospaced alignment of code works properly.

**Comment by CyrusNajmabadi** [comment]
> One could define, instead, a means of recognizing and transforming syntactically valid strings, for example ^intersection^, into glyphs or symbols identified by the text strings, in this case intersection, which could then be rendered as ∩ while appearing as ^intersection^ in a source code file.

This already exists in VS today.  You can already create things like projection-buffers and the like.  i.e. you could setup projection buffers such that the `^intersection^` was projected out, and `∩` was shown instead.

In a very real sense this is how tools like Razor work.  It's how you can embed languages in C# (or vice versa).

**Comment by thargol1** [comment]
See also #1941 (shameless case of self promoting).
