### ISSUE TITLE
Proposal: Allow using shift operator for any object.

### ISSUE THREAD

**Issue by nathan130200** [dotnet/csharplang#3178]
This proposal is for allow overload shift operators  `<<` and `>>` in custom classes instead only for bit flags.

For example working with streams (C-like streams operator):
```csharp
public class StreamWriter
{
  // Stream writer stuff.

  public static StreamWriter operator <<(StreamWriter writer, string line)
  {
    writer.WriteLine(line);
    return writer;
  }
}
```

Usage example:

```csharp
var sw = new StreamWriter("file.txt");
sw << "Hello World" << Environment.NewLine;
sw << "This is right shift operator proposal" << Environment.NewLine;
sw.Dispose();
```

Both for input streams:

```csharp
 // socket initialization stuff
var ns = new NetworkStream(socket);

int magic = default;
int size = default;

ns >> magic;
ns >> size;

var buffer = new byte[size];
ns >> buffer;
```

An logging example:

```csharp
public class Logger
{
  public static Logger operator <<(Logger logger, string message)
  {
    logger.WriteLine(message);
    return logger;
  }
}

// Example

var logger = LogManager.GetLogger("MyProgram");
logger << "Hello world!" << Environment.NewLine;
```

**Comment by canton7** [comment]
Preventing users from defining their own shift operators is a deliberate C# design decision. Related: https://github.com/dotnet/csharplang/issues/1955

**Comment by nathan130200** [comment]
I don't known what the problem implementing custom shift operators, is a good enchancement in C# language like ValueTuples.

**Comment by HaloFour** [comment]
Trying to avoid the C++ syntax with streams was a deliberate choice.  `<<` and `>>` should be reserved for bit-shift-related operations.

**Comment by nathan130200** [comment]
`<<` and `>>` operators is not C++ exclusive syntax.

**Comment by tannergooding** [comment]
Correct, but C++ is one of the languages that most commonly tries to use operators in "interesting" ways for the non primitive types. For example, using `/` to combine two paths or using `<<` and `>>` for piping objects into/outof streams.

Using operators for "non standard" things can significantly raise the barrier for being able to just look at a piece of code and know what it is doing and so C# and .NET as a whole have guidelines that strongly recommend against doing such things: <https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads>

**Comment by nathan130200** [comment]
@tannergooding Thank you for information!
