### ISSUE TITLE
[Tuple specification] Tuple Literals/Tuple Expressions

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharplang#3186]
Hi, all! My role in the V7 proposals work is to take reasonably baked proposals and turn them into spec text, following the ISO|Ecma standard format. My first attempt at doing that was with the 7.0 Tuple proposal. [BTW, I'm rather new to GitHub, so bear with me as I "get up to speed."]

That proposal put tuple literals in the "literals" section of the "Lexical structure" chapter, which resulted in push back from @gafter (https://github.com/dotnet/csharplang/pull/3031#discussion_r359012562) and @sharwell (https://github.com/dotnet/csharplang/pull/3141#discussion_r374220368). While I'm no grammarian, I'm included to agree with them that what we are currently calling a "tuple literal" is **not** a literal; in any event, it's certainly not a single token like other kinds of literal.

The current proposal does *not* include any text re the syntax and semantics of "literal expressions," and it seems to me that all the stuff currently classified as tuple literal-related should be moved to a new expression form, "tuple expressions" in the "Expressions" chapter. And we should stop using the term "tuple literal" and use "tuple expression" instead. **Do you agree on the move and the term renaming?**

If so, where does the tuple-expression production go in the grammar from a precedence point of view?

**Comment by BillWagner** [comment]
https://github.com/dotnet/csharplang/pull/3031#discussion_r359007801 also applies to this discussion.

**Comment by gafter** [comment]
I agree, except that I think it is fine to call it a "tuple literal" with the understanding (or clarification) that it is not a lexical literal.

**Comment by RexJaeschke** [comment]
OK; I moved tuple literals from "Lexical structure" to "Expressions", naming this new section "Tuple literal expressions". [Most sections in the "Expressions" chapter dealing with specific operators have names ending in "operators" or "expressions."]

I still have the outstanding question, "Where does the tuple-expression production go in the grammar from a precedence point of view?"

**Comment by gafter** [comment]
It goes in the same place that a parenthesized expression goes, which I think is *primary*

**Comment by BillWagner** [comment]
All this text was added in the C# 7 standard
