### ISSUE TITLE
[Tuple Specification] numerous additions needed for discards and deconstruction

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharplang#3197]
The description of deconstruction is not complete:

1. The grammar production needs to express both initialization and assignment on the LHS of a deconstruction.
1. The RHS of a deconstruction could be any type that supports deconstruction (tuple or any type with a candidate accessible `Deconstruct` method.) That isn't specified in the grammar.
1. The scope and definite assignment state of the destination of a deconstruction must be specified.
1. Can deconstruction be a compound assignment? (Stated another way, what is the type of a deconstruction assignment expression?
1. The example that shows a `Deconstruct` method needs to be replaced by specification language for the rules of a Deconstruct method.

Deconstruction is mentioned in the same breath as assignment. If deconstruction can only occur on the LHS of a (simple?, compound?) assignment, should deconstruction be covered under assignment rather than in its own section? If the two are in separate sections, the expression grammar needs to have the new production, tuple_deconstruction_expression, plugged into it. Support for tuple deconstruction could be the beginning of a more general pattern support mechanism to come later. If that is the case, perhaps we should admit that and start using pattern-related terminology and organization. If so, that suggests tuple deconstruction should be separate from the assignment operator, in a (pre-)patterns section that will be expanded over future spec versions.

**Comment by michael-hawker** [comment]
Related to #1358?

**Comment by BillWagner** [comment]
This has been added in the C# 7 standard
