### ISSUE TITLE
Using generics in generic type constraint

### ISSUE THREAD

**Issue by mitkodi** [dotnet/csharplang#3208]
Sorry if it was answered somewhere, but I can't find it.
What about to have something like this:
```c#
class Entity<TKey>{}
class Repository<TEntity> where TEntity : Entity<TKey>{}
```
so we'll be able to instantiate a `Repository` specifying only the `TEntity` type:
```c#
new Repository<TEntity>()
```

**Comment by YairHalberstadt** [comment]
@mitkodi 
There are a number of languages which allow something similar to this.
For example some languages have associated types, higher kinder types, or ML style modules.

This is a complex area, and It's difficult to tell whether they would solve your problem, without having a fuller example of what your classes look like. It also may be that existing patterns in C# could solve your problem.

For example:
```csharp
class Entity<TKey> : IEntity{}
class Repository<TEntity> where TEntity : IEntity{}
```

**Comment by mitkodi** [comment]
Thank you @YairHalberstadt but I don't think it could solve it.
Here is a simplified version of what I had in mind:
```c#
public class Entity<TKey>
{
    public TKey Id { get; set; }
}

public class Person : Entity<int>
{
    ...
}

public class File : Entity<Guid>
{
    ....
}

public class Repositroy<TEntity> where TEntity : Entity<TKey>
{
    public TEntity GetById(TKey id)
    {
        ....
    }

    public TKey Insert(TEntity entity) {
    {
        ....
    }
}
```
so, it can be possible to do something like this:
```c#
    Repository<Person> people;
    Repository<File> files:
    ....
    var person = people.GetById(...);
    var file = files.GetById(...);
    ....
    person = new Person {...}
    var personId = people.Insert(person);

    file = new File {...}
    var fineId = files.Insert(file);
```
The main idea is. Let's have two entity types - Person and File and Person.

**Comment by YairHalberstadt** [comment]
Rust/Scala Associated types would allow you to do that as follows:

```csharp
public class Entity
{
    public abstract type TKey;
    public TKey Id { get; set; }
}

public class Person : Entity
{
    public override type TKey = int;
    ...
}

public class File : Entity
{
    public override type TKey = Guid;
    ....
}

public class Repository<TEntity> where TEntity : Entity
{
    public TEntity GetById(TEntity.TKey id)
    {
        ....
    }

    public TEntity.TKey Insert(TEntity entity) {
    {
        ....
    }
}
```

This can sometimes be nicer than using generics.

**Comment by mitkodi** [comment]
But this pattern is also not supported, does it?

**Comment by YairHalberstadt** [comment]
@mitkodi 

Nope but it exists in other languages, which makes it much easier to design and evaluate.

**Comment by GalaxiaGuy** [comment]
Is this the same as this: https://github.com/dotnet/csharplang/issues/1328 ?

**Comment by NutzNK** [comment]
I would be great if we can code some thing similar like this.
But I have my own idea about pattern too.

1. 1st thing is generic type specialization.
```C#
public class GenericType<T> // This is default generic class.
{
    //Code here
}

public class GenericType<T> where T : int// This is specialized generic class of specified type
{
    //Code here
}

public class GenericType<T> where T : IComparable<T>// This is specialized generic class for interface.
{
    //Code here
}
```

2. 2nd thing is nested generic type declaration.
```C#
public Interface IEntity<TKey>
{
    TKey Id { get; set; }
}

public class Repository<TKey>
{
    TypeDef TEntity : IEntity<TKey>;
    public TEntity GetById(TKey id)
    {
        //Code here
    }

    public TKey Insert(TEntity entity) {
    {
        //Code here
    }
}
```

**Comment by YairHalberstadt** [comment]
@NutzNK 

That looks like a completely seperate proposal. Please open a seperate issue for it.

**Comment by NutzNK** [comment]
@YairHalberstadt Ok, the 1st item is difference but the 2nd item should be the same concept but different pattern.
let me check for existing issue for 1st item.

**Comment by Pyrdacor** [comment]
> Sorry if it was answered somewhere, but I can't find it.
> What about to have something like this:
> 
> ```cs
> class Entity<TKey>{}
> class Repository<TEntity> where TEntity : Entity<TKey>{}
> ```
> 
> so we'll be able to instantiate a `Repository` specifying only the `TEntity` type:
> 
> ```cs
> new Repository<TEntity>()
> ```

I don't really get the point of this. How would I specify `TKey` in your example? Is it determined by type inference?

Why not just use the following? What would be the advantage?

    class Repository<TKey>
    {
        // use Entity<TKey> here
    }

**Comment by mitkodi** [comment]
Yes @Pyrdacor, the main idea is to be able to infer `TKey` from `TEntity`. At the moment we have to explicitly specify it (i.e. `class Repository<Tentity, TKey> where TEntity : Entity<TKey>`), which is redundant and will lead to compilation error if you try to declare an instance of `Repositroy<EntityType, KeyType>` with non compatible `KeyType`:

For example the following:
```c#
class Person : Entity<int>{}
...
Repository<Person, Guid> _repository;
```
will lead to *There is no implicit reference conversation from Person to Entity&lt;Guid&gt;*

**Comment by Joe4evr** [comment]
I don't see how this is much different from #1349.

**Comment by mitkodi** [comment]
@Joe4evr, maybe the difference is that I mean only the type declaration.

**Comment by HaloFour** [comment]
Associated types do seem like they would be a clean way to syntactically solve the problem, however I don't see how that would lower to anything except normal generic type parameters in the CLR.  The CLR still requires that type to parameterize any members and there's only one way to convey that.  Furthermore, the raw name of the generic type is driven by the arity of generic type parameters which is why C# allows for `Repository<TEntity>` and `Repository<TEntity, TKey>` to be two distinct types.

I can't imagine that generics themselves would be overhauled in the CLR.  They're complicated enough, to the extent that they were almost never added to begin with.  I have a feeling issues like this would be better solved through improved generic type argument inference in the C# language so that both generic type arguments would not have to be specified if one argument could be derived from the other.

**Comment by Pyrdacor** [comment]
@HaloFour I think improved generic type inference in C# is exactly what was asked for here. Not changes to the CLR. The compiler should be able to inference `TKey` in the example. No extra types or changes to generic types are needed for this imho.

**Comment by HaloFour** [comment]
@Pyrdacor 

At the time of creation I can agree.  I still think that the syntax should reflect the arity of the generic type arguments, e.g. `var repo = new Repository<Person, _>();` or similar.  But I think that the generic type parameter is still necessary at declaration as that drives the contract of the type.

**Comment by Pyrdacor** [comment]
How about

```cs
class Entity<TKey>{}
class Repository<TEntity, TKey = _> where TEntity : Entity<TKey>{}
```

So TKey can be given but if not, it defaults to TKey of Entity. You can also pass TKey explicitly as _ as you mentioned. If the compiler can't inference the type then, it generates an error.

**Comment by HaloFour** [comment]
Why would that need a change in the declaration?  If the compiler is going to be doing the inference it could try to base that on the existing generic parameter constraints which already establishes the relationship.  New syntax would require new metadata to support it and wouldn't work for existing types.

**Comment by Pyrdacor** [comment]
What do you mean by new syntax here? The discard operator in place of a type?

What if I want the user to explicitly provide a TKey that should not be inferenced from the underlying TKey then?

**Comment by HaloFour** [comment]
@Pyrdacor 

> What if I want the user to explicitly provide a TKey that should not be inferenced from the underlying TKey then?

Then you'd provide it at the point of consumption, like you do today.

```cs
// today
var repo = new Repository<Person, Guid>();

// proposed
var repo = new Repository<Person, _>(); // second parameter inferred as Guid
```

I don't think that the declaration of the class itself needs to be changed for that to be implemented.

**Comment by Pyrdacor** [comment]
No I mean what if I want to force the user of my class to provide a different type. I have to do it in the class declaration.

So in your example above I may want to deny the second possibility.

**Comment by HaloFour** [comment]
@Pyrdacor 

> So in your example above I may want to deny the second possibility.

Why would you care if someone else used generic type inference?  You can't stop them from doing it now where it's already supported.

**Comment by Pyrdacor** [comment]
True. Ok you're right.
