### ISSUE TITLE
Ref locals in looping constructs — strange spec/functionality gap

### ISSUE THREAD

**Issue by reflectronic** [dotnet/csharplang#3209]
There are [multiple](https://github.com/dotnet/csharplang/issues/933#issue-260034948) [sources](https://github.com/dotnet/csharplang/issues/461#issuecomment-377711676) [that claim](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-01-24.md#ref-locals-in-looping-constructs) that this feature was intended to be released in C# 7.3, as a part of the greater ref-reassignment feature. However, there needs to be some clarification as to the intended behavior of this feature:

- There appears to be no specification for this feature.
- The feature partially works today, but [strangely not for arrays.](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEA3GUCWAZgJ4A+AAgEwCMAsAFDkAMABOdQHQBKArgHYZ8AWxgcAwhCEAHfABs8AZTzZ8YGAGcA3AwbkAzG0osxLBgG8GLK2wPkULALIAKfAIDaAXRYIAlKfrWLBYBgdaE0DAAhmAAFixOsIQs2JFQLABeLK7efmYsAL6W1oUhVkVW+mz2AGJOClKRfAA8rhgAfDnlQV2B4bDRcQkwSSlpmdm+QQVdJV2VdiwAGk4Agp2l3Ru9EQPxicmpGVl8OVMlgSWzjLZGK+ZzBgCifDwiUJEY0CwA4jAYz688B9oE4/ABeDoAE2GkR4sgw2g2D0MLABb2BUC6wVC1kq/HUkUIMBY+1axh4UFgAhYEJJwxYAFU+ASiRwVuouMMWgI2k4XrJZD5ETiyltcQZgBAILJHBBcAA5GAIDCgmkdDBQHgwYXFLoMfJAA)
- The language grammar does not indicate that this feature should exist.

Ref-local variables without initializers, which were [mentioned](https://github.com/dotnet/csharplang/issues/933#issue-260034948) alongside this very feature [(and discussed briefly in LDM)](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-01-24.md#uninitialized-ref-locals) as an "addition" to the ref-reassignment feature, currently do *not* function at all. So all of this leads me to believe that this feature wasn't intended to actually ship?

**Comment by agocke** [comment]
Yup, there's no spec for this feature.

**Comment by 333fred** [comment]
Closing this out, as C# 7 now has a complete ECMA spec.
