### ISSUE TITLE
Proposal: Deconstruct overloads for Array<T>

### ISSUE THREAD

**Issue by gsfreema** [dotnet/csharplang#3215]
Other languages such as javascript and python provide the ability to deconstruct an array into named variables. One example where this can be useful is when you have a string with known parts and a separator. A simple example would be a key and value separated by a semicolon. In C#6, someone could write the following code.

```cs
var parts = s.Split(';');

if (parts.Length > 1)
{
    var k = parts[0];
    var v = parts[1];
    // use k and v
}
```

C#7 introduced ValueTuple and Deconstruction so this could be condensed.

```cs
var parts = s.Split(';');

if (parts.Length > 1)
{
    var (k, v) = (parts[0], parts[1]);
    // use k and v
}
```

Taking this one step further with Deconstruct overloads on Array<T> would allow for this code.

```cs
var parts = s.Split(';');

if (parts.Length > 1)
{
    var (k, v) = parts;
    // use k and v
}
```

Given that arrays can have various lengths, Array would need to have many overloads with 1 to N out parameters to have this feature work. It should be easy enough to justify an upper limit on out parameters because too much deconstruction is just bad code. Also, tuples do something similar already where there is a limit on the number of items they can have.

There is also a question as to what happens if you're trying to deconstruct an array into more variables than there are items in the array. The code you would write by hand today would check the length before accessing items in the array so you don't run into an ArgumentOutOfRangeException. I would expect the same to happen here. If you're trying to deconstruct into 3+ variables and you only have 2 items in the array, you should receive an ArgumentOutOfRangeException.

**Comment by HaloFour** [comment]
Since such an operation is inherently fallible that should be implemented as a pattern rather than as deconstruction.  Recursive variable patterns would allow you to deconstruct the elements into variables (or perform further match operations) on the individual elements.

I know that there are existing proposals for array/list/collection patterns, I will try to dig them up.

**Comment by HaloFour** [comment]
See https://github.com/dotnet/csharplang/issues/1039

**Comment by HaloFour** [comment]
Also note that you can implement deconstructors as extension methods, so you can already achieve this functionality without a language or runtime change.  However, as deconstruction is considered infallible you don't have a lot of good choices for handling when an array doesn't have enough elements.  At best you could throw, which is far from a good experience.

[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoaogZgAIiykmSGBBKKAQwE8Aoggww8AZwCWEcQwDe1BoqaNmrIigYARGJHEZcYDAB4AKgD4AFBgAWEsQxMBtALoMe3fmgYQcGBwxgAGxgAW1EMAAYASjkFJXig0PCIhgBeNw8+RwjnAG44xQBfAoYS+iYWJg1tXTF9HENTSxs7BxcM3j4vHz8TAOCwvEju339EwYwyGPkqeISB5LSO/my8kvmkobIl907HMjXZpWKjxTKVSvUtHWk6g2NzK1t7J1ddz29RvvHkkd7+zaTP5jBZDEjTdZKH5DFLpd5ZHL5U5zaGTHaZfaHOZQ0EYdhwjEkLHHErnCpqao3PT3JpPVqvZZdT7/VERYHfXFkdkAiYkbmougQ5EbCawxmrJHYxSo7YEvYHSVS1H48VExXYgXovZ0YlFagnWgkRgzeKkdgmqXMCLtezpPAwADu7VkDAARAAJIKBCCuryugDq0ECABNXQxCuq5gA3dwMCwAB3cQIYiageJi6TEkdNZAAnBYACSu2SpyaFOSlkiFACErqikZOhSAA===)

**Comment by Pyrdacor** [comment]
Wouldn't it better to add a `Split` or `TrySplit` that returns a `Tuple`? And this as an extension method of your own lib? Cause a split can not know the length of the resulting array and it seems very specific to your input and use case.

If such deconstruction would be implemented I would prefer a general approach to add a "ignore the rest" operator for all deconstructions. Like:

    (var x, _*) = someValue;
    (var y, _+) = someValue;

**Comment by CyrusNajmabadi** [comment]
If you're ignoring the rest... Why not write:

`var x = someValue.First()`

?

**Comment by Pyrdacor** [comment]
> If you're ignoring the rest... Why not write:
> 
> `var x = someValue.First()`
> 
> ?

Cause:

    var (x, y, z, _*) = someArrayOrBigTuple;

**Comment by CyrusNajmabadi** [comment]
This proposal is for arrays though...

**Comment by Pyrdacor** [comment]
> If such deconstruction would be implemented I would prefer a general approach to add a "ignore the rest" operator for all deconstructions. Like:
> 
> ```
> (var x, _*) = someValue;
> (var y, _+) = someValue;
> ```



> This proposal is for arrays though...

Please read my above message. I said:

> If such deconstruction would be implemented I would prefer _a general approach_ to add a "ignore the rest" operator for all deconstructions. Like:
> 
> ```
> (var x, _*) = someValue;
> (var y, _+) = someValue;
> ```

**Comment by HaloFour** [comment]
@Pyrdacor 

> This general approach would be more useful for tuples and custom destructors but it would also solve the given issue for arrays.

The compiler knows what method to call based on the arity of the deconstruction.  A spread operator there throws that completely out the window.  It also doesn't work well for arrays in that case because the compiler has no idea how many elements are in the array.  For arrays (and other lists) I think deconstruction makes little sense, that's something much better suited to a pattern where you can recursively match on the contents.  That's also where I think a spread/discard pattern makes sense.

**Comment by Pyrdacor** [comment]
> @Pyrdacor
> 
> > This general approach would be more useful for tuples and custom destructors but it would also solve the given issue for arrays.
> 
> The compiler knows what method to call based on the arity of the deconstruction. A spread operator there throws that completely out the window. It also doesn't work well for arrays in that case because the compiler has no idea how many elements are in the array. For arrays (and other lists) I think deconstruction makes little sense, that's something much better suited to a pattern where you can recursively match on the contents. That's also where I think a spread/discard pattern makes sense.

I agree. Patterns would be a much better approach without the risk of runtime exceptions. That's why I said: *If such deconstruction would be implemented I would prefer...*

**Comment by YairHalberstadt** [comment]
Closing as championed between https://github.com/dotnet/csharplang/pull/3245 and https://github.com/dotnet/csharplang/issues/4082
