### ISSUE TITLE
Make switch expressions fluent

### ISSUE THREAD

**Issue by JKamsker** [dotnet/csharplang#3234]
In c# 8.0 [Switch Expressions](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions) were introduced. 

I, as a Developer would love to see a way to modify the result of a switch expression with further extension methods.

As a result, it would look something like this:

```csharp
int a = 1;
var b = a switch
{
	1 => "ONE",
	2 => "TWO",
	3 => "THREE",
	_ => throw new ArgumentOutOfRangeException()
}.ToLower();
```

**Comment by yaakov-h** [comment]
If you add two parentheses, you can do this already:

```csharp
int a = 1;
var b = (a switch
{
    1 => "ONE",
    2 => "TWO",
    3 => "THREE",
    _ => throw new ArgumentOutOfRangeException()
}).ToLower();
```

**Comment by J-kit** [comment]
@yaakov-h This does not work, when the source of the switch expression is a streamed value, such as
```csharp
var myColl = new List<int>()
{
    1,
    2,
    3,
    4
}.FirstOrDefault(x => x % 2 == 0) switch
{
    1 => "ONE",
    2 => "TWO",
    3 => "THREE",
    4 => "FOUR",
    _ => throw new ArgumentOutOfRangeException()
};
```

You would have to add parentheses over the whole command, starting with `new List<int>`. What if there are multiple switch statements chained together? This would result in an ugly pile of parentheses.

**Comment by Joe4evr** [comment]
[That whole block compiles perfectly fine without added parentheses.](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKBQBgAIUMAWAblwOIwDoAZGAOwEdK8BmYtQgYVwDeuQiOJcSRALIAKAJTDRQnKJXEA7ISYQA7oUYBnYAB5mwAHxyFqwkuvWMAGit2RaJ8peiO7z6NLOVAF9aADEYKEMAeSgAEQg4AEMAVwAbYGkAD0IAXjNCLIBSQh5s7MJ8WUJ9bRhgAGMACwDFZvscvIAiSIA5AFEOn19i9sIOgBUAdUiB1tUuXNGxgAkAJV7+wd9SEY6QyIBVFZmPXwB9EeAGqAB7XS1dAEEoAHMkgFsIJmBIpO+4FYSTGeEF6GTqEAADsAYNcmJYTqpAuwgrhAkA=) What is it that you want?

**Comment by J-kit** [comment]
> [That whole block compiles perfectly fine without added parentheses.](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKBQBgAIUMAWAblwOIwDoAZGAOwEdK8BmYtQgYVwDeuQiOJcSRALIAKAJTDRQnKJXEA7ISYQA7oUYBnYAB5mwAHxyFqwkuvWMAGit2RaJ8peiO7z6NLOVAF9aADEYKEMAeSgAEQg4AEMAVwAbYGkAD0IAXjNCLIBSQh5s7MJ8WUJ9bRhgAGMACwDFZvscvIAiSIA5AFEOn19i9sIOgBUAdUiB1tUuXNGxgAkAJV7+wd9SEY6QyIBVFZmPXwB9EeAGqAB7XS1dAEEoAHMkgFsIJmBIpO+4FYSTGeEF6GTqEAADsAYNcmJYTqpAuwgrhAkA=) What is it that you want?

[No, i mean this](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKBQBgAIUMAWAblwOIwDoAZGAOwEdK8BmYtQgYVwDeuQiOJcSRALIAKAJTDRQnKJXEA7ISYQA7oUYBnYAB5mwAHxyFqwkuvWMAGit2RaJ8peiO7z6NLOVAF9aADEYKEMAeSgAEQg4AEMAVwAbYGkAD0IAXjNCLIBSQh5s7MJ8WUJ9bRhgAGMACwDFZvscvIAiSIA5AFEOn19i9sIOgBUAdUiB1tUuXNGxgAkAJV7+wd9SEY6QyIBVFZmPXwB9EeAGqAB7XS1dAEEoAHMkgFsIJmBIpO+4FYSTGeEF6GTqEAADsAYNcmJYTqpgmNrvRbtA5OwgrhAkA)

**Comment by Pyrdacor** [comment]
Then just do [this](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKBQBgAIUMAWAblwOIwDoAZGAOwEdK8BmYtQgYVwDeuQiOJcSRALIAKAJTDRQnKJXEA7IWlMIAd0KMAzsAA8zYAD45C1YSU2bGADTX7ItM+WvRHD19GkXFQBfWgAxGCgjAHkoABEIOABDAFcAG2BpAA9CAF5zQmyAUkIeHJzCfFlCAx0YYABjAAtAxRaHXPyAIiiAOQBRTt8/Eo7CToAVAHUowbbVLjyx8YAJACU+gaG/UlHO0KiAVVXZzz8AfVHgRqgAez1tPQBBKABzZIBbCCZgKOSfuFWiSYLwgfUy9QgAAdgDAbkwrKdVEFZLRxjd6HdoHJ2MFcEEgA===). :)

**Comment by J-kit** [comment]
> Then just do [this](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKBQBgAIUMAWAblwOIwDoAZGAOwEdK8BmYtQgYVwDeuQiOJcSRALIAKAJTDRQnKJXEA7IWlMIAd0KMAzsAA8zYAD45C1YSU2bGADTX7ItM+WvRHD19GkXFQBfWgAxGCgjAHkoABEIOABDAFcAG2BpAA9CAF5zQmyAUkIeHJzCfFlCAx0YYABjAAtAxRaHXPyAIiiAOQBRTt8/Eo7CToAVAHUowbbVLjyx8YAJACU+gaG/UlHO0KiAVVXZzz8AfVHgRqgAez1tPQBBKABzZIBbCCZgKOSfuFWiSYLwgfUy9QgAAdgDAbkwrKdVEFZLRxjd6HdoHJ2MFcEEgA===). :)

The whole issue is to not use ugly parentheses. 
Doing them could end in such an insane chain for example:
```csharp
var res = (((((new List<int>()
{
   1,
   2,
   3,
   4
}.FirstOrDefault(x => x % 2 == 0) switch
{
   1 => "ONE",
   2 => "TWO",
   3 => "THREE",
   4 => "FOUR",
   _ => throw new ArgumentOutOfRangeException()
}).ToLower() switch
{
   "one" => 1,
   "two" => 2,
   "three" => 3,
   "four" => 4,
   _ => throw new ArgumentOutOfRangeException()
}) + 1) % 4) switch
{
	1 => "ONE",
	2 => "TWO",
	3 => "THREE",
	4 => "FOUR",
	_ => throw new ArgumentOutOfRangeException()
}).ToLower();
```

**Comment by J-kit** [comment]
> > Then just do [this](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKBQBgAIUMAWAblwOIwDoAZGAOwEdK8BmYtQgYVwDeuQiOJcSRALIAKAJTDRQnKJXEA7IWlMIAd0KMAzsAA8zYAD45C1YSU2bGADTX7ItM+WvRHD19GkXFQBfWgAxGCgjAHkoABEIOABDAFcAG2BpAA9CAF5zQmyAUkIeHJzCfFlCAx0YYABjAAtAxRaHXPyAIiiAOQBRTt8/Eo7CToAVAHUowbbVLjyx8YAJACU+gaG/UlHO0KiAVVXZzz8AfVHgRqgAez1tPQBBKABzZIBbCCZgKOSfuFWiSYLwgfUy9QgAAdgDAbkwrKdVEFZLRxjd6HdoHJ2MFcEEgA===). :)
> 
> The whole issue is to not use ugly parentheses.
> Doing them could end in such an insane chain for example:
> 
> ```cs
> var res = (((((new List<int>()
> {
>    1,
>    2,
>    3,
>    4
> }.FirstOrDefault(x => x % 2 == 0) switch
> {
>    1 => "ONE",
>    2 => "TWO",
>    3 => "THREE",
>    4 => "FOUR",
>    _ => throw new ArgumentOutOfRangeException()
> }).ToLower() switch
> {
>    "one" => 1,
>    "two" => 2,
>    "three" => 3,
>    "four" => 4,
>    _ => throw new ArgumentOutOfRangeException()
> }) + 1) % 4) switch
> {
> 	1 => "ONE",
> 	2 => "TWO",
> 	3 => "THREE",
> 	4 => "FOUR",
> 	_ => throw new ArgumentOutOfRangeException()
> }).ToLower();
> ```

Can you tell the difference which parenthesis belongs to which expression?

**Comment by YairHalberstadt** [comment]
@J-kit 

Realistically, I think in such a situation it makes sense to use a temporary variable.

**Comment by J-kit** [comment]
@YairHalberstadt Sure. A temporary variable would be one solution, but streaming the data could also be a quite nice thing. I don't know if it would add to code cleanliness but this feature feels like it's missing from c#

**Comment by Pyrdacor** [comment]
@JKamsker Your example would look ugly even without the parentheses. You should not chain a hundred times.

But I get your point now. An TValue expression should be able to be used in chained expressions and the switch expression is an exception to it as it uses curly brackets instead of parentheses. This is a fair point imho and is strange as you say it.

I am not very with the new switch as well. Unnecessarily replacing the default keyword with the discard operator while not really discarding anything feels so bad. And yet as I understand you the curly brackets seem very misplaced for an expression as well. :(

**Comment by 333fred** [comment]
To be clear, the current precedence of the switch expression was explicitly chosen, you can see the notes on it there: https://github.com/dotnet/csharplang/blob/c229cae634bd59a6a13b9ed464a4cab782a95e5d/meetings/2019/LDM-2019-03-13.md#precedence-of-the-switch-expression. We cannot change it as that would be a breaking change, and I do not think that being able to dot off a switch expression would be worth the break.

**Comment by Pyrdacor** [comment]
I think the other way around would be much better so one could use switch expressions inside other expressions. Why should I put something into parentheses which is already a surrounded single compound expression. Makes not much sense.

**Comment by CyrusNajmabadi** [comment]
> Why should I put something into parentheses which is already a surrounded single compound expression. Makes not much sense.

Because it was felt that it was more likely for people to want to do the things mentioned in the link discussion versus dotting off hte switch.  Indeed, I think you are the first person that has asked for the latter capability.

**Comment by eyalsk** [comment]
> I don't know if it would add to code cleanliness but this feature feels like it's missing from c#

Personally, I wouldn't want to see such code so in my opinion it's a feature it isn't one. :D

**Comment by Pyrdacor** [comment]
> > Why should I put something into parentheses which is already a surrounded single compound expression. Makes not much sense.
> 
> Because it was felt that it was more likely for people to want to do the things mentioned in the link discussion versus dotting off hte switch. Indeed, I think you are the first person that has asked for the latter capability.

My problem with it is that the switch looks very similar to a method call of one of the variables.

    x = a + b switch... 
    x = a + b.Add...

So for me it seems that the switch is bound to b only. So I wouldn't expect it to be

    (a + b) switch...

Because I would need to do so with methods

    (a + b).SomeMethod...

I guess this is also the reason why it looks odd for chaining. As switching is kind of a filter it makes much sense to me to chain the switch result.

**Comment by eyalsk** [comment]
> As switching is kind of a filter it makes much sense to me to chain the switch result.

It makes sense but it's like reading something without any sort of punctuation to me which a variable provides, at least that's how I parses it.

**Comment by yaakov-h** [comment]
Can I suggest another alternative that allows chaining, and doesn't require any further language changes?

```csharp
int a = 1;
var b = a switch
{
	1 => "ONE",
	2 => "TWO",
	3 => "THREE",
	_ => throw new ArgumentOutOfRangeException()
} switch { var c => c.ToLower() };
```

**Comment by Pyrdacor** [comment]
> > As switching is kind of a filter it makes much sense to me to chain the switch result.
> 
> It makes sense but it's like reading something without any sort of punctuation to me which a variable provides, at least that's how I parse it or think about it.

If you are used to Linq you would know this kind of syntax as you chain a lot and sometimes add more logic into a step like select or where. This is actually very similar to the switch syntax. Java with its stream functionality is basically full of such code. If this is good or bad practice is another story but chaining with some curly brackets along the way is not a totally rare thing. You could of course put the logic into a separate method and you can also do this with the switch.

**Comment by Pyrdacor** [comment]
> Can I suggest another alternative that allows chaining, and doesn't require any further language changes?
> 
> ```cs
> int a = 1;
> var b = a switch
> {
> 	1 => "ONE",
> 	2 => "TWO",
> 	3 => "THREE",
> 	_ => throw new ArgumentOutOfRangeException()
> } switch { var c => c.ToLower() };
> ```

This is limited to switch chaining and produces unnecessary overhead to work around the syntax limitations. Even the additional parentheses look cleaner.

**Comment by CyrusNajmabadi** [comment]
I'm not seeing any syntax options that look clean to me.  It's just not a conducive syntax for fluent processing.

**Comment by eyalsk** [comment]
@Pyrdacor Yes, I'm fairly familiar with LINQ but this seems like chaining for the sake of terseness and not really for the sake of readability, LINQ reads well because it was design as a query from the get go and even then when things gets fairly complex it's time to stop and refactor, you don't keep on chaining because you can.

I get it there might be scenarios where this is desired but I dunno I'd probably still use a variable.

**Comment by Thaina** [comment]
I am very agree that just always parentheses it add verbosity to no end

Or maybe we should have operator for piping things?

**Comment by JKamsker** [comment]
Piping would be an awesome feature @Thaina

**Comment by spydacarnage** [comment]
While I would love to see a Pipe operator, it wouldn't help in the OP's example unless you had an extra static `ToLower(string)` method (as far as I'm aware, you can't Pipe into an instance method of the piped instance).

**Comment by Joe4evr** [comment]
I knew this was asked about before: [Here's a post by Gafter](https://github.com/dotnet/csharplang/issues/3005#issuecomment-563372161) that explains why it's not possible to change the precedence rules for `switch` expressions.

**Comment by YairHalberstadt** [comment]
Closing this because [as discussed](https://github.com/dotnet/csharplang/issues/3234#issuecomment-590992926) this would be a breaking change.
