### ISSUE TITLE
Class should be sealed by default unless it is marked as (for example) extendable

### ISSUE THREAD

**Issue by jvanlangen** [dotnet/csharplang#3235]
I'm using the FxCopAnalyzers to gain a better understanding of the quality of program code.

When implementing interfaces like IDisposable it's complaining with "CA1063: Implement IDisposable correctly". Meaning that I should provide an overridable implementation of Dispose(bool) or I should mark the class as sealed. Which is justified in this case, but I rather mark my class the other way around as extendable which enables the virtual and the new keyword (same like abstract for abstract classes does) this will prevent such thoughtless non-sealed implementations.

I think it should be an intention to write an extendable class.

**Comment by YairHalberstadt** [comment]
This would be a hugely breaking change, and is not going to happen.

**Comment by CyrusNajmabadi** [comment]
Agreed.  There is no way for this to happen.  If you want to ensure that all your types are sealed by default, you can do so by writing an an appropriate analyzer for your projects/domain.

**Comment by theunrepentantgeek** [comment]
Writing an analyzer is the recommended approach - but if you find that daunting, you can also do this by writing a unit test to fail your build. Here's an example, where I'm using [xUnit](https://xunit.net/) as my test framework:

``` c#
[Theory]
[MemberData(nameof(FindImmutableTypes))]
public void ImmutableTypesShouldBeSealedOrAbstract(Type type)
{
    type.Should().Match(t => t.IsAbstract || t.IsSealed);
}

public static IEnumerable<object[]> FindImmutableTypes()
    => from t in GetImmutableTypes()
       select new object[] { t };
       
private static IEnumerable<Type> GetImmutableTypes()
    => from t in typeof(WordTutorApplication).Assembly.GetTypes()
       where t.IsImmutableType()
       select t;
```

This isn't as good as an analyzer because it doesn't give you real time warnings in your IDE, but I've found this a reasonable alternative.

The full code is in my [WordTutor](https://github.com/theunrepentantgeek/wordtutor/blob/master/tests/WordTutor.Core.Tests/ConventionTests/ImmutabilityTests.cs) project on GitHub.

**Comment by 333fred** [comment]
I'm going to close this: this is not a change that we can consider for C#. If I could go back in time and change C# 1.0 this would be on my shortlist to change, but it's not something we can do today m

**Comment by andradf** [comment]
Could it be done in a similar manner as non-nullable reference types have? Where for the time being it's opt in and the scoping of it can be done using directives?

**Comment by 333fred** [comment]
> Could it be done in a similar manner as non-nullable reference types have?

Technically? Yes. However, consider the benefit tradeoff here. Nrt tries to solve a problem that has cost literally billions of dollars (perhaps more!) by introducing what is effectively a new dialect of C#. We could do that for other issues, but I can't think of anything worth that cost.
