### ISSUE TITLE
sealed partial v partial sealed?

### ISSUE THREAD

**Issue by stuartstein777** [dotnet/csharplang#3236]
Would it be possible for the order of sealed and partial to not matter?

i.e. this compiles
```
internal sealed partial class Foo { }
```

This doesn't.

```
internal partial sealed class Foo {}
```

Thanks

**Comment by DavidArno** [comment]
For what it's worth, the second example reads as if it's only a partially sealed class, whereas the former is a sealed version of a partial class. So the latter feels grammatically incorrect to me.

Not sure that's a very good reason to oppose this though. 😄

**Comment by alrz** [comment]
https://github.com/dotnet/csharplang/issues/946

**Comment by stuartstein777** [comment]
Didn't realise it was a duplicate. I'll close
