### ISSUE TITLE
Expose the fault IL feature

### ISSUE THREAD

**Issue by Mrnikbobjeff** [dotnet/csharplang#3240]
In the IL standard we have the fault exception handling mechanism outlined. It is not currently available in C#, even though there are use cases for it. I would love to have language support for this to not have to fall back to IL weaving.
For details see [II.19.6 Fault handlers ](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf)

**Comment by svick** [comment]
Related previous discussions: https://github.com/dotnet/csharplang/issues/434 and https://github.com/dotnet/roslyn/issues/14831.

Also, I think that when discussing a feature, it's important to understand what its use cases are, just saying they exist is not sufficient. So, what are the use cases?

**Comment by Mrnikbobjeff** [comment]
The problem prompting this ticket for me was the necessity to rethrow often in catch handlers after returning types requiring disposal, but only if an exception was thrown. I had to rethrow exceptions in certain catch handlers, which lead to quite a lot of code bloat. The fault handler is perfect for such a scenario, as it allows you to not rethrow the exception and still have a handler which is called on exceptions. I'll put a code sample up as soon as I can. Another indicator that there are valid use cases for this is is the fact that fault handlers are already emitted when yielding in a using block. The idea as far as I can tell is to not dabble with the exception by rethrowing but simply disposing on an error. Finally is not an option there as it would dispose too early.

**Comment by jnm2** [comment]
`finally` is the option I use due to missing the fault feature. Better to introduce a variable than to rethrow an exception.

```cs
var disposable = new DisposableThing();
var success = false;
try
{
    SomethingThatCouldThrow();
    success = true;
    return disposable;
}
finally
{
    if (!success) disposable.Dispose();
}
```

**Comment by popcatalin81** [comment]
@Mrnikbobjeff why is the fault so much better than `catch...throw;`?
Assuming how this would be implemented in C# a typical comparison case would look like: 
```csharp

    try
    {
       /// do some wprk
    }
    catch
    {
        tran.Rollback();    
        throw;
    }
```
An with hypotetical fault
```csharp
    try
    {
        /// do some wprk
    }
    fault
    {
        tran.Rollback();
    }
```
It does not look like a big improvement

- You cannot filter by exception type in a fault block
- You cannot inspect or make use of the exception object if a fault block

An the use cases or even potential performance improvements are questionable for the general case.

**Comment by Mrnikbobjeff** [comment]
> `finally` is the option I use due to missing the fault feature. Better to introduce a variable than to rethrow an exception.
> 
> ```cs
> var disposable = new DisposableThing();
> var success = false;
> try
> {
>     SomethingThatCouldThrow();
>     success = true;
>     return disposable;
> }
> finally
> {
>     if (!success) disposable.Dispose();
> }
> ```
> 
> If this happens a lot, I use a helper class to implement this pattern with `using`:
> 
> ```cs
> using var tempFile = OwnershipTracker.Create(new TempFile());
> 
> // Do stuff with the temporary file that involves reading from sources that may throw.
> // E.g.:
> using var file = File.Create(tempFile.OwnedInstance);
> await stream.CopyToAsync(file, cancellationToken).ConfigureAwait(false);
> 
> return tempFile.ReleaseOwnership();
> ```
> 
> Implementation: https://gist.github.com/jnm2/2302a81f7b8797d9e59a84c69d1e12bf

This is definitely the cleanest possible alternative but still way worse than simply declaring a fault handler, as this basically emulates a fault handler without the ability to add catch handlers on a per case basis. @popcatalin81 is correct that this simple try block does not get better with a fault handler. Now consider a try block with several different catch handlers which may execute logic on an individual basis. Netiher answer does offer a solution here (Sure, you could pass in an action or something into the quoted answer but this would make the code even more convoluted). I will send my code sample as soon as I return from my vacation.

**Comment by canton7** [comment]
Couldn't you also do something like:

```cs
var disposable = new DisposableThing();
try
{
    try
    {
        Stuff...
    }
    catch (A a) { }
    catch (B b) { }
}
catch
{
    disposable.Dispose();
    throw;
}
```

Sure it's still uglier than a `fault` handler, but it's not the worst thing in the world.

**Comment by Mrnikbobjeff** [comment]
I will quote from Bart de Smet's on fault handlers, he expressed thought very concisely, about the purpose of the fault handler:
"If an exception happens during [the try block], we end up in the finally block and come to conclude success was never set to true. This indicates an error happened, and we should handle the fault case. However, this technique can get a bit tricky when there are different paths exiting the try block: one could return from the enclosing method in various places, requiring the “success = true” code to be sprinkled around. This is exactly what exception handling was designed for: reducing clutter in your code that has to do with error condition/code tracking. So, we’re defeating that purpose."
