### ISSUE TITLE
Proposal: namespace declaration

### ISSUE THREAD

**Issue by JipingWang** [dotnet/csharplang#3248]
To simplify namespace usage as the following (let's call it namespace declaration),
```csharp
namespace package1 {
    // some classes for package-1
}
namespace package2 {
    // some other classes for package-2
}
```

to
```csharp
namespace package1; 
// some classes for package-1

namespace package2; 
// some other classes for package-2
```

Comments:
Inspired by [using declaration in C# 8.0](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations), the proposed change saves the top level indent and a pair of braces.

**Comment by MgSam** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/2546, https://github.com/dotnet/csharplang/issues/137

**Comment by martind0** [comment]
Good idea

**Comment by EatsLemons** [comment]
Should be awesome in a combine with https://github.com/dotnet/csharplang/issues/3117

**Comment by 333fred** [comment]
Closing as a duplicate of #137.
