### ISSUE TITLE
[Discussion] Conditional Returns

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/csharplang#325]
I was playing around where I was returning an early check result and didn't like having the `return` in the middle of the line. The intent was more important than the condition. I thought a conditional return would be nice. Then I though about the common practice of having a single return at the bottom of a method and wrap things in cases and ifs to support this. It adds a lot of wordiness. Even with multiple returns, sometimes these get wrapped in cases. A potentially cleaner coding style can be used if we had conditional returns. In the simplest form it just allows reversing the keyword and predicate:
```
// Instead of
if ( !_myObject.Exists() ) return await GetReturnStuffAsync();

// Intent comes first
return ( !_myObject.Exists() ) await GetReturnStuffAsync();
```
This can eliminate a lot of if's and cases
```
public (bool success, string result, object details)  Foo(Item inItem) {
   return ( !CheckItem(inItem) ) => (false, "CheckFail", null);

   var bar = DoWork();

   // Fail
    return ( !bar.success ) => (
        success : bar.success ,
        result : Convert.Result( bar.ActivityResult ),
        details : thing.where( s=>s.Details == bar.detailsKey )
    );
   
    // Pass
    return ( bar.success ) => (
        ...
        ...
        ...
    );
    
    // Default
    return (false, "fail", null);
}
```
You have to be aware of the order of things, but with the changes to `switch` with pattern matching, you have to now anyway.

**Comment by HaloFour** [comment]
The following is already legal C# syntax:

```cs
return (foo) => bar;
```

Even if you eliminated that ambiguity I don't see much utility in this proposal.  All it seems to do is conflate conditions with returning values.  In my opinion it doesn't improve readability of the code and the keystroke savings is minimal, at best.

**Comment by MgSam** [comment]
This syntax is confusing and I think it accomplishes exactly the opposite of your stated goal of putting intent first. `if-then` is logic 101, spilling part of the result outside of the if clause upends that.

**Comment by Thaina** [comment]
I was once propose syntax `return if` to work like you suggest in guard statement

https://github.com/dotnet/roslyn/issues/11562

**Comment by DavidArno** [comment]
Another use case for the `match` expression and supporting pattern matching on tuples:
```cs
public (bool success, string result, object details)  Foo(Item inItem) =>
    (CheckItem(inItem) is var checkresult, checkResult ? DoWork() : default) match (
        case (false, _) : (false, "CheckFail", null),
        case (_, bar) when !bar.success: (
            bar.success,
            Convert.Result( bar.ActivityResult ),
            thing.Where(s=>s.Details == bar.detailsKey)),
        case (_, bar): (
            ...
            ...
            ...)
    );
```
(ignored the "default" as that's unreachable)

**Comment by svick** [comment]
Ruby has something similar, where you can write a condition *after* a statement, for example:

```ruby
return result if condition
```

During the short time when I used Ruby, I found code like that very confusing, so I don't think adding something similar to C# would be a good idea.
