### ISSUE TITLE
Generic Type Precompiling

### ISSUE THREAD

**Issue by SinDynasty** [dotnet/csharplang#3251]
### Generic Type Precompiling

```
    public abstract class MyAbstractClass { }

    public class MyClass1 : MyAbstractClass { }

    public class MyClass2 : MyAbstractClass { }

    public class MyClass3 : MyAbstractClass { }

    public class MyGenericClass<T>
        where T : MyAbstractClass
        maybe MyGenericClass<MyClass1>, MyGenericClass<MyClass2>
    {

    }
```

**maybe** is a keyword，indicates which types need to be precompiled.

.NET 5 can AOT, if add this keyword, i can indicates which types need to be precompiled, for example MyGenericClass\<MyClass1\> and MyGenericClass\<MyClass2\>.

Of course MyGenericClass\<MyClass3\> will be JIT, because this type have not indicated with "maybe"

**Comment by huoyaoyuan** [comment]
There's nothing required in language.
Today you can write
```csharp
[assembly: SomeAttribute(typeof(MyGenericClass<MyClass1>))]
```
and the toolchain can use it to indicate which need to be precompiled.

The old NGen toolchain also has a mechanism to do this:
```csharp
[MethodImpl(MethodImplOptions.NoOptimizing)]
void JitGenericHelper()
{
    var unused1 = new MyGenericClass<MyClass1>();
    var unused2 = new MyGenericClass<MyClass2>();
}
```
