### ISSUE TITLE
Proposal:Delegate type inheriting closure

### ISSUE THREAD

**Issue by RamType-0** [dotnet/csharplang#3253]
C# compiler creates class and its instance implicitly in many situation.(e.g. lambda expression,async 
 state machine,and iterator)
and at almost every situation,they used together with Delegate class.

I thought that if this kind of auto generated class inherits delegate type,
we could reduce number of objects per using lambda expression,async method,iterator,and so on.

**Comment by svick** [comment]
If I understand what you're saying correctly, I have previously proposed the same thing at https://github.com/dotnet/runtime/issues/8362.

My conclusion from that discussion and some measurements I made is that the savings in the number of bytes allocated (which is the important metric here, not the number of objects) would be quite low and not worth the non-trivial amount of effort required to make this work.

**Comment by RamType-0** [comment]
> If I understand what you're saying correctly, I have previously proposed the same thing at [dotnet/runtime#8362](https://github.com/dotnet/runtime/issues/8362).
You are right. This is duplicate.but I still dont think that it is not worth.
Because GC performance are affected mainly by number of objects,
and this feature also improves locality of memory access.

**Comment by RamType-0** [comment]
#Duplicate
Duplicate of #8362
