### ISSUE TITLE
typo/open reference in "partial methods" block

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/csharplang#3256]
shouldn't this line:
  It is a compile-time error to create a delegate to method (Delegate creation expressions).
be this:
  It is a compile-time error to create a delegate to M (Delegate creation expressions).
?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d94b01ab-fe87-23fc-44b6-da9f3f627bd5
* Version Independent ID: a86008b1-2fdd-bbb9-3bbf-8fc8c51c1b71
* Content: [Classes - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#feedback)
* Content Source: [spec/classes.md](https://github.com/dotnet/csharplang/blob/master/spec/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Closing as fixed in the [C# 6 standard.](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/classes.md#1569-partial-methods)
