### ISSUE TITLE
Missing section on switch expressions

### ISSUE THREAD

**Issue by 333fred** [dotnet/csharplang#3265]
The only docs we have on switch expressions is on the "What's new in C# 8.0" page. We should add more comprehensive docs here and elsewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e783650c-e063-e268-316e-564362cb1e37
* Version Independent ID: aa9f4996-cab4-0bed-6452-213342453785
* Content: [Expressions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#feedback)
* Content Source: [spec/expressions.md](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Switch expressions have been added to Learn:

- [Switch expression language reference](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/switch-expression)
- [Patterns language reference](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/patterns)

I'll close this 

/cc @333fred
