### ISSUE TITLE
Named tuple type alias 

### ISSUE THREAD

**Issue by uvero** [dotnet/csharplang#3276]
**C#** currently supports tuples with specifically-named properties, like defining:

```cs
(double x, double y) point = (1,2); // to access - point.x, point.y
```

Which is great, by the way. It allows creating simple struct-ish types that you can use, for example, for return types or type arguments.

However, a repetitiveness problem may arise: if your function, say, returns an `IReadOnlyCollection<(int id, string result)>` (sorry for lack of creativity), and you'll want another function to accept that as a parameter, you need to again write `IReadOnlyCollection<(int id, string result)>`, which gets more frustrating when names get just a bit longer.

What I'm suggesting is that you'd be able to declare a named-tuple like a named type:

```cs
public type Point = (int x, int y);
```

I've seen a suggestion to do that similar to a `using` directive, similar to how you can already write something like:

```cs
using ShortTypeName = SomeGenericType<TArg1, TArg2>;
```

But what I'm suggesting is something that will have an access modifier and can be part of a namespace or nested in another type, similar to a delegate declaration. That way you can use it outside of the same CS file, unlike an alias of a using directive.

**Comment by canton7** [comment]
Sounds a lot like Records. See  #3231, #3226, #3213, #3170, #3146, #3137, #2750, #2699, #2691, #1667, and many more besides.

**Comment by ufcpp** [comment]
see also https://github.com/dotnet/csharplang/issues/423

**Comment by YairHalberstadt** [comment]
Closing as duplicate between https://github.com/dotnet/csharplang/issues/410, https://github.com/dotnet/csharplang/discussions/259, https://github.com/dotnet/csharplang/issues/423
