### ISSUE TITLE
C# Constructor Shorthand

### ISSUE THREAD

**Issue by TropicalThunder** [dotnet/csharplang#3279]
Much like the Typescript language, it would be nice to get rid of the tedious writing of constructors when using dependency injection.

Today I will write something like:

```
public class TestClass
{
	private readonly DatabaseContext _context;

	public TestClass(DatabaseContext context)
	{
		_context = context;
	}  
}

```
My suggestion is that we could write something like this in the future:

```
public class TestClass
{
    public TestClass(private DatabaseContext context) { }  
}

```

**Comment by canton7** [comment]
This looks similar to records. See  #3231, #3226, #3213, #3170, #3146, #3137, #2750, #2699, #2691, #1667, and many more besides.

**Comment by TropicalThunder** [comment]
> This looks similar to records. See #3231, #3226, #3213, #3170, #3146, #3137, #2750, #2699, #2691, #1667, and many more besides.

The others propose several other large and more comprehensive changes whereas this is much more specific, and that ought to be looked at for the future.

**Comment by DavidArno** [comment]
Those other "*large and more comprehensive changes*" completely cover what you are proposing here though. So this is just a syntax variation on what is already in planning for v9. So this is really just a duplicate request.

**Comment by TropicalThunder** [comment]
>  So this is just a syntax variation on what is already in planning for v9.

That I did not know. Thanks! All I am saying is that _something_ has to be done.

**Comment by Richiban** [comment]
This is not *records* but *primary constructors*, which also have their own proposal. https://github.com/dotnet/csharplang/issues/2691

**Comment by canton7** [comment]
@Richiban Eh, primary constructors let you say:

```cs
public class C(int i, string s)
{
    ...
}
```

which isn't what this issue says. The idea of primary constructors is an older one which sort of got subsumed into the records proposal, if I'm following things correctly. #2691 is in the list of issues I gave as references, either way.

**Comment by Richiban** [comment]
@canton7 The syntax is slightly different, but the feature is the same--my class has a dependency (a field), let me write it once in such a way that it gets set in a constructor.

Records are a quick and clean way of defining a class with value equality and, _in addition_, an auto-generated constructor.

**Comment by canton7** [comment]
@Richiban They keep humming and harring about whether value equality is part of records, or its own separate thing. I think it's safe to say that all discussion around the idea of "let me declare all of these properties, and a constructor to assign to them, with minimal effort" come under the heading of "Records" these days.

**Comment by yulObraz** [comment]
It looks like I hate the records already... The records as I understude are structures with simplified construction. I am not so deep in language specification to say something about theese things. I have't felt necessity in them. But I need simplified construction of complex class with DI. Surely I will never compare classes by theese properties. So vary important problem of records is not important in this case.

**Comment by OskarKlintrot** [comment]
@yulObraz Records are a quick and easy way to write DTO classes and has nothing to do with this issue. This issue is to get the same [shorthand that Typescript has](https://dev.to/satansdeer/typescript-constructor-shorthand-3ibd). I think records are [inspired from F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/records).

**Comment by Richiban** [comment]
It now seems pretty possible that C# will get primary constructors (ironically enough they talk about it in a _records_ LDM notes: https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-27.md)

**Comment by Richiban** [comment]
Primary constructors will allow something similar to this: 

```csharp
public class C(ServiceA a, ServiceB b)
{
	public void M()
	{
		a.DoSomething();
		b.DoSomethingElse();
	}
}
```

**Comment by YairHalberstadt** [comment]
Closing, as this is being considered as part of the discussion surrounding primary constructors: https://github.com/dotnet/csharplang/issues/2691
