### ISSUE TITLE
How to read this pseudo code?

### ISSUE THREAD

**Issue by hjkl950217** [dotnet/csharplang#3283]
hll，

I like this project so much that it shows me how the C # language is documented. But I often come across this code when reading proposals:
```antlr
pointer_type
    : ...
    | funcptr_type
    ;
```
address: [function-pointer-syntax](https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md#function-pointer-syntax) 

**What is it?**

I want to know its name so that I can easily read the information to understand this pseudo code.

thank you very much~

**Comment by HaloFour** [comment]
It's [ANTLR](https://www.antlr.org/) syntax for defining language parsers.

**Comment by hjkl950217** [comment]
非常感谢！我从来没有见过。
-------------------------------------
thank you very much! I have never seen it before.
