### ISSUE TITLE
Question: why System.Void isn't accessible from C#?

### ISSUE THREAD

**Issue by Opiumtm** [dotnet/csharplang#3288]
This code

``` C#
var l = new List<System.Void>();
```

don't compile with error

> System.Void cannot be used from C# -- use typeof(void) to get the void type object

Well, `List<System.Void>` is meaningless. But there are scenarios when value type meaning literally "nothing" is needed.

Imagine this:

``` C#
public interface IActionWithResult<T>
{
    Task<T> Execute();
}
```

and class, implementing this interface

``` C#
// we don't return any result as there is no result
public class MyActionWithoutResult : IActionWithResult<System.Void>
{
    public Task<System.Void> Execute()
    {
        // some code
    }
}
```

wouldn't compile with the same error

> System.Void cannot be used from C# -- use typeof(void) to get the void type object

Because of it there are different delegate types and many other - `Action<T>` and `Func<T1, T2>`
If C# have similar to [F# Unit](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/unit-type) built-in type, there will be no need for separate `Action` and `Func` types.

On CLR level `void` type seems to be of value type `System.Void`, but this type (value meaning literally "nothing") isn't accessible from C#. Why?

Is it CLR limitation?

**Comment by CyrusNajmabadi** [comment]
Closing out.  Question has been answered.
