### ISSUE TITLE
Proposal: Allow optional parameters in any location

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#3293]
Now the optional parameters in C# function have a limitation: they must be after all mandatory parameters. This limitation is reasonable before C# 7.0. But C# 7.0 introduced "discards" feature (https://github.com/dotnet/csharplang/issues/422), I think that it is possible to remove that limitation by using "discard" feature.
For example:
```C#
static int foo(int a=10, int b) { ...... } // allow optional parameter with default value to locate in front of mandatory parameter
static void main() 
{
    int c = foo(_, 20); // when an optional parameter in front of mandatory parameter is omitted, discard syntax ('_') must be used to occupy its location.
    ......
}
```

**Comment by jnm2** [comment]
Discussion on optional parameters that follow `params`: https://github.com/dotnet/csharplang/issues/1458

**Comment by ygc369** [comment]
@jnm2 
#1458 seems not same with this proposal.

**Comment by jnm2** [comment]
@ygc369 Right; it is related.

**Comment by tannergooding** [comment]
You can already do this today, its just a bit more verbose:

**Comment by tannergooding** [comment]
I think the above workaround should be sufficient for the extremely rare scenario (such as certain Interop code) where you want to have an optional parameter that is not last or immediately preceding another optional parameter.

**Comment by ygc369** [comment]
@tannergooding
Thanks for providing the workaround. But I think that my proposal provides a more friendly syntax, and it should not be hard to implement.
