### ISSUE TITLE
Allow methods which can only be called from ctors and can set readonly fields

### ISSUE THREAD

**Issue by drauch** [dotnet/csharplang#3318]
Sometimes you want to refactor ctor readonly-field-initializing code into own methods but can't do so. We could add "initializer methods" which are private, can only be called from within a ctor and which are able to set readonly fields.

Possible syntax:
```
public MyClass ()
{
    InitializeA();
    InitializeB();
    [...]
}

private initializer void InitializeA ()
{
    _readonlyField = "SomeValue";
}
```

**Comment by eyalsk** [comment]
Dup #1871, #348, 1296.

**Comment by jnm2** [comment]
@drauch Nice avatar.

**Comment by drauch** [comment]
> @drauch Nice avatar.

Hopefully I'm allowed to use my issue for a little bit of chit chat: Thanks. Some advertisment for this very great point&click game: https://amanita-design.net/games/machinarium.html
