### ISSUE TITLE
Override static methods -- why not?

### ISSUE THREAD

**Issue by kyanha** [dotnet/csharplang#3321]
As it stands, static methods cannot be marked virtual or override.  Static methods also go to the deepest point on the inheritance tree that define them.  This is causing me trouble with (e.g.) BouncyCastle's C# library.

```cs
namespace Org.BouncyCastle.Asn1 {
  public class Asn1Object : Asn1Encodable {
    static Asn1Object GetInstance(object obj) {}
  }

  public class Asn1Sequence : Asn1Object, IEnumerable {
    static Asn1Sequence GetInstance(object obj) {}
  }
}

namespace ThingThatUsesBC {
using Org.BouncyCastle.Asn1;
  public class MyClass {
    internal MyClass(Asn1Sequence seq) {}
    public GetInstance(object obj) {
      return (new MyClass(Asn1Sequence.GetInstance(obj))); // fails because it's type Asn1Object
    }
  }
}
```

In MyClass, the reference to Asn1Sequence.GetInstance doesn't go to Asn1Sequence's static method, it goes to Asn1Object's.  There is no way to mark the base class's static implementation as virtual, and there is no way to mark the derived class's static implementation as override.

Why is this not allowed (particularly with full specification of the static method I'm trying to access)?

**Comment by kyanha** [comment]
closing because I need to do more investigation.

**Comment by theunrepentantgeek** [comment]
Check out **class** methods as supported by Borland Delphi. 

I don't know about more recent versions, as my experience was with Delphi 7 and earlier (before the product was purchased by Embarcadero), but the approach was rather nice. 

In Delphi's Object Pascal you could declare an **virtual class** method and then **override** it in descendent classes. You could also pass around a type and use that to call the class methods without needing an instance.

**Comment by kyanha** [comment]
Reopening because yeah, this still makes no sense, even after investigation.

Why can I not specify which class's static method (of the same name) by specifically naming the class?  All attempts to do so simply go back to the static method of that name closest to the root of the class derivation tree.

**Comment by jnm2** [comment]
@kyanha If you're naming the class at each call site, why not use the `new` keyword instead?

**Comment by CyrusNajmabadi** [comment]
The above code is failing because your methods are private.  Make them accessible and you'll have no trouble using them.

**Comment by gafter** [comment]
See the section **Static interface members** in https://github.com/dotnet/csharplang/issues/1711

**Comment by YairHalberstadt** [comment]
Closing as being considered as part of https://github.com/dotnet/csharplang/issues/1711
