### ISSUE TITLE
Could we allow `in this T` for generic that has type constraint?

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#3331]
With this code

```C#
public static class SomeClass
{
	public static int SomeFunction<T>(in this T foo) => 0;
}
```

It cause this error

```
The first parameter of the 'in' extension method 'SomeFunction' must be a concrete (non-generic) value type
```

I guess this error is because `in this` must be `struct`. But then I wish this code below should be possible

```C#
public static class SomeClass
{
	public static int SomeFunction<T>(in this T foo) where T : struct,ICollection
	{
		return foo.Count;
	}
}
```

Is it have any innate problem?

edit: If it possible for `in this` should it also possible for `ref this` ?

**Comment by RikkiGibson** [comment]
if you could constrain to a readonly interface that might be solvable: #3055

**Comment by Thaina** [comment]
@tannergooding I see. That is perfectly logical reason. Thank you for clarification

And so this is actually a duplicate issue as @RikkiGibson has pointing out. So I will close this issue

**Comment by IllidanS4** [comment]
Also see the related discussion [here](https://github.com/dotnet/roslyn/issues/24601) for ideas how to solve this. I can see the rationale behind this decision, as none of the code examples in this thread would *ever* work as intended (they would have to create a defensive copy and so `in` doesn't help much), but there are still some reason where this could be used today and `readonly` members would bring a couple more.

**Comment by RikkiGibson** [comment]
it feels like it might at least help to hint in the diagnostic that 'ref this' would work.

**Comment by tannergooding** [comment]
I don't know if hinting `ref this` is correct. They have different semantics when applied to `readonly` fields and a few other bits.
