### ISSUE TITLE
"yield all" to return multiple values at once in an iterator

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/csharplang#3338]
_Apologies if this has already been suggested (which is likely), but I couldn't find a relevant issue..._

Currently, if you need an iterator to return values from a collection, you need to iterate over the collection, e.g.

```csharp
public IEnumerable<T> GetAllValues()
{
    yield return _firstValue;
    foreach (var value in _otherValues)
        yield return value;
    yield return _lastValue;
}
```

It would be nice to be able to do this instead:

```csharp
public IEnumerable<T> GetAllValues()
{
    yield return _firstValue;
    yield all _otherValues
    yield return _lastValue;
}
```

(the `yield all` keyword is just an idea, something else might be better)

This feature exists in F# (`yield!`)

**Comment by alexrp** [comment]
See #378 and #1599.

**Comment by CyrusNajmabadi** [comment]
Closing as a dupe.
