### ISSUE TITLE
injection stack

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/csharplang#3343]
In injection-oriented frameworks such as asp.net core, the error stack is often difficult to express error messages, such as class A constructor injecting class B constructor, but class B constructor throwing an exception, the call stack is usually not helpful.
It is recommended to add injection stack to facilitate problem location. Such as:
```csharp
interface IB {}
class A {
	public A (IB b) {}
}
class B : IB {
	public B () { throw new Exception (); }
}
```

The display effect is as follows:
```
Injection stack:
line xx: public B () { throw new Exception (); }
line xx: public A (IB b) {}
```

**Comment by fawdlstty** [comment]
Maybe not related to language?

**Comment by fawdlstty** [comment]
It might be possible to add a unified way of recording the injection stack so that different injection libraries can be unified

**Comment by CyrusNajmabadi** [comment]
@fawdlstty I don't see any request from you on what you'd like to change in the language here :)
