### ISSUE TITLE
PoM/BoM Project/Bill of Materials

### ISSUE THREAD

**Issue by peni4142** [dotnet/csharplang#3344]
I am missing a Project of Materials!

What I expect that to be.

If you include that thing(can even be one file), you are only allowed to include NugetPackages from that List, but you don't have to.

The benefit I expect from that is nothing less than to solve the DLL-hell.

You can define one in your company, including that in every project and you all have the same DLLs/NugetPackages.

### case studies:
- **Update/add/delete a Package** Maybe you have it in a git project. You make a Pull-Request, your buddies can agree or disagree. On agree, everyone has to update.

- **You get to know a Package is corrupt** Just delete it and you are sure, no one is using that anymore

**Comment by YairHalberstadt** [comment]
This sounds like a request a different repository
Perhaps Microsoft/msbuild?

**Comment by peni4142** [comment]
I try that
