### ISSUE TITLE
Null-forgiving operator ambiguity in "x ! is null"

### ISSUE THREAD

**Issue by michkot** [dotnet/csharplang#3345]
After switching to C#8, the expression `x !is null` is legal and does not throw any warning at me. IMHO this can lead to a confusion that it is equal to `!(x is null)`.

Note: something like `is-not null` would be really nice, as using "is null" is the right tool for the job, instead of "== null" (custom-operators danger) or Object.IsReferenceEqual(x, null).

**Comment by Happypig375** [comment]
[C# 9 `not` patterns save the day!](https://github.com/dotnet/csharplang/issues/1350)

**Comment by 333fred** [comment]
Closing as a duplicate.

**Comment by HaloFour** [comment]
A trick of the whitespace, might be something a style guide or analyzer might want to warn on.

**Comment by michkot** [comment]
Wanting a "is-not" is more of note in this @333fred than the core of the thing.

> A trick of the whitespace, might be something a style guide or analyzer might want to warn on.

Exactly: should I re-post the issue in other repo?

**Comment by YairHalberstadt** [comment]
a) Roslyn might be a good repo for this
b) @jnm2 was discussing greying out unnecessary null suppression operators. That would help in most cases here. What's the status on that @jnm2?

**Comment by 333fred** [comment]
Well, the `x !is null` syntax is legal and unambiguous today, so that is not something the language can do anything about.

**Comment by jnm2** [comment]
@YairHalberstadt It's waiting for design review by the Roslyn team: https://github.com/dotnet/roslyn/issues/41574

**Comment by michkot** [comment]
> Well, the `x !is null` syntax is legal and **unambiguous** today, so that is not something the language can do anything about.

Unambiguous in compiler/lang-spec sense, yes. Not necessarily for people... (who never know the spec in detail, I personally did a lot of missing/one-too-much negation errors).

**Comment by 333fred** [comment]
> Unambiguous in compiler/lang-spec sense, yes. Not necessarily for people...

Sure. But that's why it's not something the language can do anything about. I'd suggest making an issue on roslyn for formatter changes.

**Comment by CyrusNajmabadi** [comment]
>  and does not throw any warning at me. 

You can always write an analyzer here if you think this warrants avoidance in your code.
