### ISSUE TITLE
Target Typed New

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3349]
It would be great if I could do something like this:

````
public class MyClass1 {
  public MyClass2 Member {get; set;}
}

public class MyClass2 {

}

....

var C = new MyClass1 {
  //This is currently not valid because C# thinks I'm creating an anonymous type.
  Member = new {

  }
}
````

It would be great to be able to just type ````new { ... }````` when the target type is a class with a public default constructor.

**Comment by svick** [comment]
This feature is planned for C# 9.0 and AFAICT, has already been implemented (by @alrz); see https://github.com/dotnet/csharplang/issues/100 and [Language Feature Status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md). [Though the syntax is slightly different:](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQygg5hG6CeADhACaoB2EA7gDQwgBuECAlmPjSSANQA+AAgCYAjAFgAUBKEACAMISA3hOkrp/ACzSAsgAoAlMtVLxq09IaY50gLzTKVbflkAbKMmTDpxs2a0QAtsDMNnbU+oY+AL4A3BHSkRIJkuL8AMxqgo4ubh5ehmlZru6ZfoHBCjgw0dLIuNFJSVLpMlpORciZxolAA==) `new()` (or `new() {}`).

**Comment by alrz** [comment]
This is just merged to 16.7p1 branch.

**Comment by MgSam** [comment]
@arlz Congrats!!

**Comment by 333fred** [comment]
Closing as duplicate and already implemented.
