### ISSUE TITLE
on enum vs Enum

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/csharplang#3351]
Typically in C# the keywords map directly to their corresponding classes for example

`int.Parse` is equal to `Int32.Parse`

for `enum` it seems that none of the methods defined on `Enum` are exposed through the `enum` keyword, i.e. I feel like:

`enum.GetValues` should be the same as `Enum.GetValues` this way one can use the same style when declaring and accessing a `enum` and getting their values or other operations.

Is there a reason `enum` is handled differently than `Enum`?

Consider also the following:

`System.Enum test = SomeEnum;` -> `SomeEnum is a type, which is not valid in the given context`

` System.Enum test = typeof(SomeEnum);` -> `Cannot implicitly convert Type to System.Enum`

**Comment by HaloFour** [comment]
> Typically in C# the keywords map directly to their corresponding classes for example

That's only true of keywords that happen to be type aliases.  `int` is one of them, and is used interchangeably with the type it aliases.  `enum` is not, it is a keyword used in entirely different contexts and not as a type.

I'm not sure what I'm supposed to be considering with your last two statements.  Neither look like they should compile to me.

**Comment by juliusfriedman** [comment]
Well my first question is why is `enum` not a type alias?

The code does not compile but was food for thought...

Consider:

`Enum @enum = System.Enum;` -> `Enum is a type, which is not valid in the given context`

`Enum @enum = null;` Compiles fine however `@enum.GetType()` throws a NRE

**Comment by HaloFour** [comment]
> Well my first question is why is `enum` not a type alias?

Why would it be?  How often would you need or want to declare a field/local of type `enum` rather than as a concrete enum type?  There's nearly no value to using `System.Enum` directly, so there's no reason for it to be a type alias.

You can do the following now:

```cs
System.Enum value = DayOfWeek.Friday;
```

But I'd have to question why anyone would want to.

**Comment by CyrusNajmabadi** [comment]
> Well my first question is why is enum not a type alias?

Language questions go in reverse.  The default state for everything is: because it wasn't designed that way.  And for that to change, as good reason has to be given :)

**Comment by juliusfriedman** [comment]
> But I'd have to question why anyone would want to.

When working with multiple `enum` types especially now that `Enum` is allowed as a generic constraint as shown as minimally possible below:

```
public static void EnumTest<TEnum>() where TEnum : Enum
	{
		
	}
```

**Comment by HaloFour** [comment]
> When working with multiple `enum` types especially now that `Enum` is allowed as a generic constraint as shown as minimally possible below:

I'd have to dig up the design notes/comments at the time but IIRC it was decided to not make `enum` the keyword be the generic type constraint so that they weren't forced to make decisions as to how it would behave or to limit how they might design that in the future.  So the only language change was to lift the limitation preventing you from using `System.Enum` as a generic type parameter constraint (which the CLR has supported since 2.0).

Note that if you're working with `System.Enum` as a generic type constraint that by default the enums will be boxed because through some fluke of the type system `System.Enum` is itself a reference type.  You can satisfy the constraint with `System.Enum` as the generic type argument (which makes no sense) and it's possible to pass `null` values.  You'll want to combine that constraint with the `struct` constraint which forces the generic type argument to be an actual concrete enum type.

**Comment by 333fred** [comment]
Is there a language proposal here, or has the question been answered?

**Comment by juliusfriedman** [comment]
I am proposing that `enum` be treated just as `int` and should correspond to `Enum`

**Comment by HaloFour** [comment]
@juliusfriedman 

> I am proposing that enum be treated just as `int` is to `Int32` and should correspond to `Enum`

Under what circumstances?  And why?  What benefit does it provide?

**Comment by juliusfriedman** [comment]
1) Symmetry, can you provide an example of another such type which has a difference between the keyword and the type? 
2) I believe in certain cases keywords and aliases can refer to different types, e.g. `string` is not always the same exact type as `System.String` i.e. depending on how the references are made in the project. Thus it would allow you to always refer to the `enum` instance in which the keyword was bound and allow the `Enum` to exist as a separate type. (Especially useful if `Enum` was previously aliased)
3) when used in generic constraints, we allow `struct`, `int` etc and now since we allow `enum` it would be suiting to type the same thing in the constraint rather than `Enum`

**Comment by HaloFour** [comment]
> Symmetry, can you provide an example of another such type which has a difference between the keyword and the type?

`struct`, which `enum` is more akin to that any specific type alias.  You can't define a variable of type `struct`.  Seems perfectly symmetrical already, not that being so is a goal.

> I believe in certain cases keywords and aliases can refer to different types, e.g. `string` is not always the same exact type as `System.String` i.e. depending on how the references are made in the project.

I don't believe this is true.  Even if it was, that seems extremely niche.

> When used in generic constraints, we allow `struct`, `int` etc and now since we allow enum it would be suiting to type the same thing in the constraint rather than `Enum`

Why?  The existing generic constraint is very specifically only for `System.Enum`, without conveying any additional behavior or benefits.  Making `enum` mean the same thing as `Enum` here would complicate or eliminate the possibility of making a more capable `enum` constraint in the future.

There are no problems solved by this suggestion, short of saving having to hold shift for a single character.

**Comment by juliusfriedman** [comment]
You mention struct however struct is really just an implementation of `ValueType` no?

For instance:

```
struct Test { }

ValueType test = new Test();
```

Compiles fine...

Perhaps `struct` should also be forwarded to mean `ValueType` as that would also provide more symmetry but again I believe your rebuttal would be the same (What problem does this solve)

I don't mean to argue on the point of `string` not being equal to `String` however I can imagine a contrived example in which a program which hosts 32 bit and 64 bit objects from different processes and `String` in one process is not the same as `String` in the other....

Since `Enum` can only contain value types anyway it's already kind of backwards that `Enum` is a class and yet I digress from my original proposal and question. (`ValueType` is also a class)

If you find the proposal lacking your more than welcome to close it however I feel the symmetry would be beneficial in it's own regard especially when `Enum` has been aliased. (using my contrived example or otherwise)

Thank you for your time.

**Comment by 333fred** [comment]
> I am proposing that `enum` be treated just as `int` is to `Int32` and should correspond to `Enum`

As @HaloFour has said, this would eliminate the possibility of having a true `enum` constraint in the future. As a general rule, all feature proposals start at -100 points (see https://docs.microsoft.com/en-us/archive/blogs/ericgu/minus-100-points for the history of the metric). For me, this does not make it back to 0.
