### ISSUE TITLE
Proposal: Bitwise primary operators

### ISSUE THREAD

**Issue by TheXDS** [dotnet/csharplang#3352]
# Bitwise primary operators

* [x] Proposed
* [ ] Prototype: [Complete](https://github.com/PROTOTYPE_OWNER/roslyn/BRANCH_NAME)
* [ ] Implementation: [In Progress](https://github.com/dotnet/roslyn/BRANCH_NAME)
* [ ] Specification: [Not Started](pr/1)

## Summary

CLR has increment and decrement primary operators for all numeric types, such as `++` and `--`. But notably, it lacks some handy primary operatos for bitwise transformation of values as short hands. This proposes the introduction of a "flip bits and assign" (`~~`) operator and a "flip bits and assign, except these bits" (`~=`) operator.

<a name="motivation"/>
## Motivation

Sometimes it would be useful to flip a boolean flag based on its current value, or maybe apply a two's complement operation directly to an integer value. Currently such transformations rely on syntax such as `boolFlag = !boolFlag` for `bool` or  `numericMask = ~numericMask` for any other integer numeric type; which while explicit, could feel very clunky, especially if variables with long names are used.

## Detailed design

I'm proposing the introduction of the `~~` and `~=` primary operators, which should negate all bits in a value. This operator should be available for all integer numeric types (except `IntPtr`) and for `bool`.

The idea is to replace both the `boolFlag = !boolFlag` and `numericMask = ~numericMask` expressions with a simpler `value~~`, which is shorter, still concise and doesn't make the previous code snippet any more readable, while the `~=` operator will aid to filter out undesired bit changes.

Applications could use state flags, or bitmask calculations using bitwise negation, or complement a value transformation for criptographic purposes. If a user-defined `struct` could be represented as a bitstream, it can benefit from overriding those operators.

<a name="boolcase"/>

#### Boolean flag switching

Consider the following situation:
``` c#
public class BlinkingController
{
    private System.Timers.Timer _blinkTimer;

    // Actual implementation might turn on/off a lamp using GPIO, serial, WebAPI, etc.
    public bool BusyStatusLightBulb { get; private set; }

    public BlinkingController()
    {
        // Make the light blink each 500 ms.
        _blinkTimer = new System.Timers.Timer(500);
        _blinkTimer.Elapsed += (sender, e) => BusyStatusLightBulb = !BusyStatusLightBulb;

        _blinkTimer.Start();
    }
}
```
While simple enough to understand, might be considered redundant and clunky because of the long name used in the property. In this case, the `BusyStatusLightBulb` property just needs to flip its value each 500 milleseconds. The line 12 above could be rewritten as:
``` c#
        _blinkTimer.Elapsed += (sender, e) => BusyStatusLightBulb~~;
```

#### Integral types and enums
For all integral types, the `~~` operator will flip all of their bits. The unary `~` operator is already present in C#, and it produces a two's complement value of the input. The `~~`will combine the operation of producing such a value and assigning it to the same variable for which its value was bit-flipped:

<a name="valuecase"/>

``` c#
byte pattern = 0b_0000_1010;

/* Some operations with 'pattern' */

pattern = ~pattern; // now, it should have a value of 0b_1111_0101
```
that expression could be rewritten as:
``` c#
byte pattern = 0b_0000_1010;

/* Some operations with 'pattern' */

pattern~~; // now, it should have a value of 0b_1111_0101
```

<a name="enumcase"/>

Now, consider this next situation:
``` c#
    // Note: the 'DaysOfWeek' enum makes reference to a new enum where 
    // each day is a flag, not the 'System.DayOfWeek' enum.
    DaysOfWeek firstGroup = DaysOfWeek.Monday | DaysOfWeek.Wednessday | DaysOfWeek.Friday;
    DaysOfWeek secondGroup = DaysOfWeek.Thursday | DaysOfWeek.Tuesday | DaysOfWeek.Saturday;
    bool onFirstGroup = false;

    // Alternate job days assignation arbitrarily
    foreach (var job in AllJobs)
    {
        job.DayAssignation = onFirstGroup ? firstGroup : secondGroup;
	onFirstGroup = !onFirstGroup;
    }
```
Enums could harness the potential of bit-flipping using only defined enum values. 
``` c#
    // Note: the 'DaysOfWeek' enum makes reference to a new enum where 
    // each day is a flag, not the 'System.DayOfWeek' enum.
    DaysOfWeek group = DaysOfWeek.Monday | DaysOfWeek.Wednessday | DaysOfWeek.Friday;
    
    // Alternate job days assignation arbitrarily as an example.
    foreach (var job in AllJobs)
    {
        job.WorkingDays = group~~; // Spoiler alert: This has a problem...
    }
```
After flipping the variable `group`, its effective value should be equal to the days defined in the `DaysOfWeek` enumeration that werent present in its previous value, and those which were, shall not be.

But this particular case has a problem. It will also flip the `DaysOfWeek.Sunday` flag unexpectedly. This could be fixed by introducing a binary variant of the `~~` operator: the `~=` compound operator. At the right of the `~=` operator will be an expression that indicates which flags shall not be changed.
The previous code could be easily fixed by changing the code as follows:
``` c#
    // Note: the 'DaysOfWeek' enum makes reference to a new enum where 
    // each day is a flag, not the 'System.DayOfWeek' enum.
    DaysOfWeek group = DaysOfWeek.Monday | DaysOfWeek.Wednessday | DaysOfWeek.Friday;
    
    // Alternate job days assignation arbitrarily as an example.
    foreach (var job in AllJobs)
    {
        job.WorkingDays = assignation;
        assignation ~= DaysOfWeek.Sunday;

        // For higher compactness, could be written as:
        // job.WorkingDays = (assignation ~~= DaysOfWeek.Sunday);
    }
```
The `~=` operator should also be available for integral types, but not for `bool`. The same flip logic applies for integral types, but of course it is not bound to a particular set of flags definition, instead operating over all the bits. Casting an `enum` value into an integral type should also have this behavior.

## Other considerations

As by other similar operators, there should be prefixing versions of the `~~` operator that performs the operation before returning a value.

Ideally, if technically feasible, the `~=` could be implemented by default as the following snippet, removing the need for the mandatory overload:
``` c#
value = ~value ^ exclusions;
```
If the feature above isn't feasible, then if either `~~` or the  `~=` are overloaded, the other one must be overloaded also.

## Drawbacks

Most situations may just require to set a value explicitly in order to increase readability of the code, and to property understand what value should be in a variable. the `~~` operator will not work in those situations, as it just tells the programmer that all bits in that particular variable have been flipped. Such situations may include, for example, setting a _busy_ flag during some lenghty operation (explicitly knowing that the flag became true at the beginning and false at the end is more readable that just flipping its state).

## Alternatives

As of now, the only alternative to the `~~` operator would be to keep using the existing syntax, such as the one presented in the [Motivation](#motivation) section or in the examples provided [here](#boolcase), [here](#valuecase) and [here](#enumcase).

## Unresolved questions

the `~=` operator could be confusing because it contains an equality symbol, which it correctly informs that the variable on the left will be updated, but it's not clear if the value on the right will be present or not on the new value, since it is just implied as "keep these bits as-is". If some other combination of special characters could yield a clearer indication of the actual result of the operation, this proposal should be udated with the new operator.

Also, to keep the language consistent, the `~~` operator for `bool` values could be foregone and replaced with an independant version, the `!!` operator. This operator shall work in the same manner as the proposed `~~` operator for boolean values.

**Comment by YairHalberstadt** [comment]
> Sometimes it would be useful to flip a boolean flag based on its current value, or maybe apply a two's complement operation directly to an integer value. Currently such transformations rely on syntax such as boolFlag = !boolFlag for bool or numericMask = ~numericMask for any other integer numeric type; which while explicit, could feel very clunky, especially if variables with long names are used.

The --/++ operators are used hundreds of times in almost every single code base.

In the vast majority of code bases `~` is used at most a handful of times, and the current solution `numericMask = ~numericMask` is already pretty short.

I really don't see any reason to introduce any new syntax here.

**Comment by TheXDS** [comment]
True, maybe such bitwise operators would be seldom used. I was thinking more on a _completeness_ perpective, I mean... we have all these arithmetic operators, and bitwise logic is not particularly broad.

Maybe if I ever come with more useful bitwise operators or uses this proposal could go somewhere. I actually use bitwise operations a lot with flags and enumerations.

**Comment by SingleAccretion** [comment]
I would personally find `~=` highly confusing, because `~` is not a binary operator, thus the symmetry with `-=`, `+=` and `^=` is broken.
I would personally be fine with `~~`, but:
1. What are semantics of `~~` when used in an expression context? Does the proposal include the prefix form? There seems to be a lot of possibilities for introducing inconsistencies.
2. We can use extension methods to emulate the functionality (I think this is worth adding to the "Alternatives" section of the proposal):
````
public static void Toggle(this ref bool b) => b != b;
````

**Comment by 333fred** [comment]
> True, maybe such bitwise operators would be seldom used. I was thinking more on a _completeness_ perspective... 

Developing new language features is very expensive. Unless the gain is worth it, we usually don't add features for the sake of completeness.

**Comment by shaggygi** [comment]
@TheXDS There is somewhat related work being done on [Bit Manipulation here](https://github.com/dotnet/runtime/issues/27382).  Does this help?

**Comment by TheXDS** [comment]
@shaggygi actually yes, it is somewhat related to this. Thank you BTW, I didn't realize #27382 was on the works. I'm closing this proposal as it didn't go anywhere. Maybe when #27382 is complete, I may revisit this idea.
