### ISSUE TITLE
Initialization-only setters

### ISSUE THREAD

**Issue by doomchild** [dotnet/csharplang#3358]
Currently, if I have a class like the following, deserialization "works" (in the sense of not throwing an exception), but the deserialized instance doesn't have the expected value.

```csharp
public class MyImmutableType
{
  [XmlAttribute("value")]
  [JsonPropertyName("value")]
  public int Value { get; }
}
  
class Program
{
  static void Main(string[] args)
  {
    XmlSerializer xmlSerializer = new XmlSerializer(typeof(MyImmutableType));
    string toDeserializeXml = "<MyImmutableType value=\"1\" />";
    MyImmutableType myImmutableType;

    using (StringReader reader = new StringReader(toDeserializeXml))
    {
      myImmutableType = (MyImmutableType) xmlSerializer.Deserialize(reader);
    }
    
    //This *should* print '1', but will in fact print '0'.
    Console.WriteLine(myImmutableType.Value);
  }
}
```

There needs to be some way to specify that a setter is only usable during initialization.  Having a separate serialization-only setter is definitely not elegant.  What I _want_ to write is something like this:

```csharp
public class MyImmutableType
{
  [XmlAttribute("value")]
  [JsonPropertyName("value")]
  public int Value { get; initonly set; }
}
```

**Comment by 333fred** [comment]
Init only is almost certainly coming as part of records: https://github.com/dotnet/csharplang/issues/39. In fact, we discussed it at length earlier today in language design. Closing as a duplicate.

**Comment by doomchild** [comment]
I picked `initonly` because I remembered seeing it somewhere (although I'm blanking now).  My main thrust was that serialization is a weird intuition-defying edge case, and this would be one way to handle it.

**Comment by 333fred** [comment]
I don't think it's junk useful for serialization: it's useful for immutable objects in general :). That's why we're looking at it.

**Comment by doomchild** [comment]
Oh absolutely. I just wanted to make sure that I expressed myself correctly.
