### ISSUE TITLE
Easier if else if else

### ISSUE THREAD

**Issue by giaphat71** [dotnet/csharplang#3362]
Sometime we need to write lots of if else for every case happen, i think it can be shortened like this:
` on (a==b)
    {  
    	//code 
    }  
    or (true by default)  
    {
	     ...
    }
    or
    {
    	...
    }`

This is more readable and easy for life in my think. Sorry if this annoy.

**Comment by theunrepentantgeek** [comment]
It's not clear what syntax you're proposing, would you please expand on the details?

I'd also suggest you should expand on why the existing constructs (if statements, switch statements, and switch expressions) are inadequate.

**Comment by giaphat71** [comment]
I cant write markdown lead to this, this is my idea for a shorthand for a series of if()else if() else if()... . The "true by default" is just an information, not the language, like you have no if() at the default case.

**Comment by CyrusNajmabadi** [comment]
@giaphat71 I think there may be a language barrier here :)   Could you provide a fuller example of what code you would ike to be able to write *and* what it would currently be equivalent to. To write markdown you can use ` ```c# ` on its own line to start, then write your example, then end with ` ``` ` on its own line as well.  Thanks!

**Comment by giaphat71** [comment]
Ah ok, i can read English but cant write good. Like this 
```c#
on ( type == 'a'){
//proccess product type a
}
or (type =='b' && customerisvip())
{
//process type b
}
or
{
//show error etc
}
```
The equivalent for this is replacing ‘on’ with ‘if’ and ‘or’ with ‘else if’, this is easy by replace before compiling, but more readable when having more product type. 
On and or is just my suggest, it not need to be that.
Additionally, i think c# can be write as a scripting language by using a preprocessor that place code in place ( the main function) then compile and run, if this happen, it will be so cool.

**Comment by CyrusNajmabadi** [comment]
Thanks for the suggestion! :)  However, it's highly unlikely this would be taken.  `if/else` is one of the most idiomatic constructs in all of programming.  It is ubiquitous and well understood.  Creating a new construct which serves the exact same purpose would just make the language more confusing and would increase the burden to teach people and for people to read and work with code.

> Additionally, i think c# can be write as a scripting language by using a preprocessor that place code in place ( the main function) then compile and run, if this happen, it will be so cool.

1. Please try to keep issues specific and separate.  We don't want to have issues that are discussing lots of different issues as it jsut gets confusing :)
2. There's already work on something similar to what i think you're asking for here: https://github.com/dotnet/csharplang/blob/master/proposals/Simple-programs.md

Thanks!

**Comment by CyrusNajmabadi** [comment]
I'm going to close this out.  Direct synonyms to existing constructs really are not going to be taken without seeing some sort of overwhelming ecosystem desire to move in that direction.

Thanks for the feedback though! :)
