### ISSUE TITLE
Improve definite assignment to understand coalescing with false and nullable comparison with true

### ISSUE THREAD

**Issue by jnm2** [dotnet/csharplang#3365]
These are forms of the same logic from most preferred to least preferred. The compiler does not consider them to be the same for the purpose of definite assignment, but it should.

The `?? false` and `== true` guarantee that execution cannot move inside the `if` block without first calling TryGetValue and assigning the `out` parameter:

```cs
using System;
using System.Collections.Generic;

class C
{
    void M(IReadOnlyDictionary<int, int> expr)
    {
        if (expr?.TryGetValue(42, out var value1) ?? false)
        {
            // ❌ CS0165: Use of unassigned local variable 'value1'
            Console.WriteLine(value1);   
        }
        
        if (expr?.TryGetValue(42, out var value2) == true)
        {
            // ❌ CS0165: Use of unassigned local variable 'value2'
            Console.WriteLine(value2);   
        }
        
        if (expr is { } && expr.TryGetValue(42, out var value3))
        {
            Console.WriteLine(value3);   
        }
    }
}
```

Similar but for pattern matching rather than out parameters, and not involving nullability: https://github.com/dotnet/csharplang/issues/801

**Comment by hez2010** [comment]
Seems that Roslyn always forgot to analyze patterns like `if (a?.b ?? false)` and `if (a?.b == true)`, even in NRT analysis 😄

**Comment by jnm2** [comment]
@hez2010 My understanding is that the C# definite assignment spec needs to be updated before Roslyn can do anything about the examples I gave in this issue, unlike the nullability warnings you mention.

**Comment by 333fred** [comment]
That's correct @jnm2. While I'm interested in championing this, I'd like to sit down with the definite assignment spec and see the level of change we'd need to make to support it, so before I actually tag it and such I'll work on that.

**Comment by jnm2** [comment]
My first example is a duplicate of #916. Is my second example close enough to close this as a dupe? (Hate to lose the 13 upvotes though..)

**Comment by 333fred** [comment]
Yeah, it's pretty much exactly the same as those. I will say that while I still want to come up with a spec for how this would work, I have not had the time (as you might be able to tell). If a community member wanted to make a proposal for how to modify the definite assignment rules, that's probably what would drive progress here.

**Comment by jnm2** [comment]
Okay, closing this in favor of the original at https://github.com/dotnet/csharplang/issues/916. Please upvote and follow there.
