### ISSUE TITLE
Proposal: Readonly Computed Properties

### ISSUE THREAD

**Issue by eyalsk** [dotnet/csharplang#3373]
# Readonly Computed Properties

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Provide a syntactic sugar to `get` only properties aka Readonly Computed Properties in some languages, e.g., [Swift](https://docs.swift.org/swift-book/LanguageGuide/Properties.html#ID261):
```Swift
struct Cuboid {
    var width = 0.0, height = 0.0, depth = 0.0
    var volume: Double {
        return width * height * depth
    }
}
```

## Motivation
[motivation]: #motivation

Since C# 6 we can use expression-bodied properties like so:
```C#
public int Position => CurrentPosition + _offset;
```
However, say we want to change that and accumulate the position and then reset the offset the only way to achieve that is to fall back to a method or use the traditional syntax like so:
```C#
public int Position 
{
    get 
    {
        var pos = CurrentPosition += _offset;
        _offset = 0;
        return pos;
    }
}
```

## Detailed design
[design]: #detailed-design

Given the above motivation I propose the following addition to the language:
```C#
public int Position => {
    var pos = CurrentPosition += _offset;
    _offset = 0;
    return pos;
}
```

## Drawbacks
[drawbacks]: #drawbacks

Most computed properties are fairly simple so this might be a niche.

## Alternatives
[alternatives]: #alternatives

1. Use the traditional way as shown above.
2. Define a helper method and then call it from the property.

The only downside here is that both approaches are verbose.

**Comment by jnm2** [comment]
The proposed syntax is consistent with statement-bodied lambdas.

**Comment by 333fred** [comment]
The only way I could see us doing this is via block expressions. It seems too specific and only providing a minor syntactic shorthand otherwise.

**Comment by MgSam** [comment]
You can make a hacky extension method to allow you to essentially write blocks in areas where only expressions are allowed. I don't use this often but sometimes it's a lifesaver in a small getter or in an ORM context that only allows expressions.

``` C#
public static TOut Do<TIn, TOut>(this T obj, Func<TIn, TOut> func) 
{
    return func(obj);
}
```

Your use case is a little weird because you're mutating two different variables in your getter but I still think it could work.
``` C#
public int Position => _offset.Do(o => { 
    //Write whatever you want in here
    CurrentPosition += o; 
    _offset = 0; 
    return pos;
};
```

**Comment by eyalsk** [comment]
@MgSam That's a good suggestion and you can probably store the delegate to avoid the extra allocations but then you have few moving parts to do an extremely simple thing.

> Your use case is a little weird 

You're right, it is weird and I actually changed it. ;)

Like I wrote in my proposal it's really a niche and the only reason I made it is because I thought I needed it and didn't see any discussions about it which might imply that the use-case is fairly rare.
