### ISSUE TITLE
Concomitant Struct

### ISSUE THREAD

**Issue by 2bhuinianhua** [dotnet/csharplang#3374]
Struct "S" is always comming with Struct "M".
So,can "S" be bound to "M",and don't appear alone.
Just like:
```C#
public Struct Binding<M> S 
{
　int x ;
　int y ;
}
```
The the new syntax of declaration statement :
```C#
<S>M m = 0 ; 
```

**Comment by 2bhuinianhua** [comment]
Can it complete in a nuget package by Roslyn/MSBuild?

**Comment by huoyaoyuan** [comment]
It seems that you are using same types (`int`, `string`) for different purposes, and want to limit which extension methods are available on them.
I think #1695 should be a better approach.
