### ISSUE TITLE
try with no catch

### ISSUE THREAD

**Issue by eidylon** [dotnet/csharplang#3383]
Not a major feature, but figured I'd throw it out there. Didn't see it in searching the issues. 

It would be nice to be able to write a try block without a catch. Something like...

    try {
        ... do something here that might throw an exception ...
    }

There are times semi-occasionally, but not super frequently, where I want to perform a certain bit of code, and truly don't care if it errors. So I want to run it, if it works, great, if it fails, don't care. 

Would look a little cleaner and nicer than doing 

    try {
        ... do something here that might throw an exception ...
    } catch { }

That's all.

**Comment by theunrepentantgeek** [comment]
See #2914

**Comment by eidylon** [comment]
> 
> 
> See #2914

Yeah, same issue. Not sure why when i searched for "try catch" it didn't come up. 
Sorry about that. I'll close this ticket.
