### ISSUE TITLE
Allow 'Else' on ForEach

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3385]
It would be great if ForEach could have an optional 'Else' branch that would occur if no iterations occurred.

````

foreach(var item in collection) {
   ...
} else {
  Console.Writeline("Enumeration yielded no results");
}

````

**Comment by HaloFour** [comment]
https://github.com/dotnet/csharplang/issues/1025

**Comment by 333fred** [comment]
Closing as a duplicate.
