### ISSUE TITLE
[Proposal] Iterator tuple

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/csharplang#3395]
I suggest to use iterator tuple in foreach loopsand from queries to operate on adjacent elements in two or more collections.
For example:
LinQ has a Zip method, to operate on pairs of elements in two collections (not a cross product):
```
int[] numbers = { 1, 2, 3, 4 };
string[] words = { "one", "two", "three" };
var result = numbers.Zip(words, (n, w) => n + " " + w);
```

I suggest to write it in LinQ s as:
```
result = from (n, w) in (numbers, words)
         select n + " " + w;
```

and in foreach:
 ```
foreach (n, w) in (numbers, words)
   console.WriteLine(n + " " + w);
```

**Comment by theunrepentantgeek** [comment]
There are two many possible different implementations for this to work as a language feature.

For example, what do you want to happen if the two sequences are different lengths? 

* Do you want iteration to terminate as soon as the shorter sequence is finished? or, 
* Should iteration continue until both sequences are exhausted? If so, what value should be provided in place of the exhausted sequence? or,
* Should the length of iteration be controlled by the first sequence, stopping when that is exhausted? 

My point is that there is no way the language can implement this in a way that is satisfactory for all users - or even most of them. Even within a single project, I'd expected different methods would need different implementations.

**Comment by VBAndCs** [comment]
> there is no way the language can implement this in a way that is satisfactory for all users - or even most of them. 

I disagree. You can always find a way or another.
We can run on the shortest sequence as Zip does. Or we can define n, w as `Iterator<T>`. that has Value and HasValue properties, an a cast operation to cast it directly to T by returning the value, so, we can write:
```
foreach (n, w) in (numbers, words)
{  
  if (!n.HasValue)
      Console.WriteLine("? " + w);
  else if (!w.HasValue)
     Console.WriteLine(n + " ?");
  else
    Console.WriteLine(n + " " + w);
}
```

**Comment by 333fred** [comment]
Personally, the only times I would want this feature would be when I've already asserted that the lists have the same length, and I would want it to error if they have different lengths. Between the two of us, we've already disagreed on behavior. So I don't think it's as clear cut as you make it out to be, and I agree with @theunrepentantgeek that we could never implement this in a way that is actually what the user wants in most cases.

**Comment by CyrusNajmabadi** [comment]
This is already possible with:

```c#
result = from (n, w) in numbers.Zip(words, (n, w) => (n, w))
         select n + " " + w;
```

**Comment by CyrusNajmabadi** [comment]
You can also just do this today:

```c#
        int[] numbers = { 1, 2, 3, 4 };
        string[] words = { "one", "two", "three" };

        var result = from x in (numbers, words)
                     select x.Item1 + " " + x.Item2;
```

By providing a suitable extension method like so:

```c#
public static class Extensions
{
    public static IEnumerable<TResult> Select<TSource1, TSource2, TResult>(
        this (IEnumerable<TSource1>, IEnumerable<TSource2>) source,
        Func<(TSource1, TSource2), TResult> selector)
    {
        return source.Item1.Zip(source.Item2, (a, b) => (a, b)).Select(selector);
    }
}
```

Bam, now you have whatever semantics you want for what it means to select over a tuple of data sources.

**Comment by MgSam** [comment]
I think your foreach use case could be achieved just be added a simple single-parameter overload of Zip to make it look cleaner.
``` C#
///<summary>Zips two enumerables together into a enumerable of their tuples.</summary>
public static IEnumerable<(TFirst, TSecond)> Zip<TFirst, TSecond>(
    this IEnumerable<TFirst> first, IEnumerable<TSecond> second) => 
        first.Zip(second, (f, z) => (f, z));

foreach (n, w) in numbers.Zip(words)
  console.WriteLine(n + " " + w);
```

While I don't think your suggestion merits a language feature, I am puzzled by the "there are many possible implementations" comments. Zip has been around for 10+ years- it seems like the decision on what the implementation should be was made a long time ago.

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
@MgSam 
Nice workarounds, but what about:
```
foreach (x, y, z) in (A, B, C)
  console.WriteLine($"{x}, {y}, {z});
```

Let's think of this as a general way to treat many single dimension arrays as one table, with the ability to deal with null cells if we use the `Iterator<T>` implementation .

**Comment by HaloFour** [comment]
@VBAndCs 

It's trivial to write implementations of `Zip` that can handle any number of iterables.  The point is that such transformations belong in libraries, not in the language.

**Comment by YairHalberstadt** [comment]
If extension GetEnumerator makes it into 9 (which at the moment seems likely), you could do this easily:

```csharp
public static IEnumerator<(T1, T2)> GetEnumerator<T1, T2>(this (IEnumerable<T1> a, IEnumerable<T2> b) tuple) => tuple.a.Zip(tuple.b, (a,b) => (a,b)). GetEnumerator ();
```

You could define 10 overloads for different number of elements. I doubt you'd need more than that.

**Comment by CyrusNajmabadi** [comment]
> @MgSam
> Nice workarounds, but what about:

What about them?  Just add another overload. This is very common in .net to deal with things like different func arities, or different tuple sizes. 

The language generally won't take costly proposals just to save users from writing a 1-liner they can distribute in a nuget package.

**Comment by eyalsk** [comment]
@MgSam I'm not sure whether you misread what @theunrepentantgeek wrote but he probably meant that if this was accepted as a language feature there are multiple ways to design this feature and still users wouldn't be too happy about it, at least that's how I read it so I'm not sure why would past implementation should affect the future? with that said we all probably agree on the part where this belongs to a library.

**Comment by CyrusNajmabadi** [comment]
Closing out as this can sensibly be provided today through a library.  Out of scope for the language.

**Comment by svick** [comment]
@MgSam [That overload already exists since .Net Core 3.0.](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip?view=netcore-3.0#System_Linq_Enumerable_Zip__2_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___1__)
