### ISSUE TITLE
Proposal: Make "new" keyword optional for value type initialization

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/csharplang#3401]
We should introduce semantics in order to distinguish value type initialisation from reference type initialization.

This will would make the intent of your code clearer.

# Background

The ```new``` keyword followed by a constructor invocation is in C++ used to indicate that an object allocation is taking place on the heap. If this is omitted in C++ then the object will be allocated on the stack.

C# should introduce similar semantics by making the ```new``` keyword optional when calling a constructor of a value type.

This can be added to the language without breaking existing code.

The feature should be enabled by default. Adding an analyzer that is warning developers when they initialize value types using ```new```.

# Reasons

Here are some reasons for implementing this:

1. Clarity - makes the intent clearer by signifying what is a reference object versus a value object allocation.
2. It looks nice with value types like structs and records. Makes the developer experience more pleasant.
3. Consistency - It is consistent with C/C++, and familiar to programmers coming from those languages. In a way, this is honoring C#'s heritage as a descendant of C/C++.

# Example

The following code shows what this feature would look like:

``` csharp
struct Foo 
{
    int _c;

    public Foo(int c) 
    {
        _c = c;
    }
}

var foo = Foo(42);
```

Since ```new```  is not being used here, we can assume that this is a value and not a reference being assigned to the variable "foo".

# Target type inference

With target type inference (#100) the assignment could be further simplified as:

```csharp

Foo foo = 42;
``` 

And with multiple parameters:

```csharp
Foo foo = (42, "Foo");
``` 

Now the syntax is suspiciously similar to ```ValueTuple```. You can implement your own Tuple-like class.

# Analyzer

Since this should be enabled by default, there should be an analyzer warning when using ```new```:

```
var foo = new Foo(42);
          ^^^
```

Message:
```
The "new" keyword should not be used when initializing a value type.
```

Or similar.

**Comment by HaloFour** [comment]
Dupe of #350

> Since this should be enabled by default, there should be an analyzer warning when using `new`:

This is a breaking change.  Stylistic preferences aside, there absolutely nothing wrong with using `new` to call the constructor of a value type.

**Comment by eyalsk** [comment]
> 3\. Consistency - It is consistent with C/C++, and familiar to programmers coming from those languages. In a way, this is honoring C#'s heritage as a descendant of C/C++.

Isn't it much better for the language to be consistent with itself as opposed to other languages? 😉

**Comment by theunrepentantgeek** [comment]
There's no more reason for C# to be consistent with C or C++ than there is for it to be consistent with Go, Rust, TypeScript, JavaScript, Object Pascal, Java, Scala, Swift, Objective C, Objective Pascal, or Prolog.

C# isn't some kind of C++ lite, it's an entirely different language.

> This can be added to the language without breaking existing code.
> The feature should be enabled by default. Adding an analyzer that is warning developers when they initialize value types using **new**.

Making **new** optional and a warning when used for a value type would be a breaking change. 

In the following code, removing the **new** keyword would change the code from instantiation of the value type `Trigger` to instead calling the private method `Trigger()`.

``` csharp
public struct Trigger
{
    public string Name { get; }
    public Trigger(string name) => Name = name;
}

public class Demo {
    public void Main() {
        var foo = new Trigger("Bob");
        // ... elided ...
    }
    
    private bool Trigger(string name) => string.IsNullOrWhiteSpace(name);
}
```

The syntax of C# includes a few clues to disambiguate between type names and other possible identifier types - the keyword **new** is one of these. Removing it makes parsing much more difficult, while introducing no additional expressive power to the language.

**Comment by sgf** [comment]
This is very unreasonable because it will make developers think too much and carry too much psychological burden.
How to allocate is automatically determined by the compiler based on the type definition. Better than C ++ only has value types by default. It only takes developers to care about how to allocate (on the heap or on the stack), and because C # has value type semantics, it does not require programmers to show distinction (control how to allocate).

**Comment by robertsundstrom** [comment]
OK. I did not consider everything.
