### ISSUE TITLE
[Proposal] Continue or break in assignment statement

### ISSUE THREAD

**Issue by devsamt** [dotnet/csharplang#3408]
Actually, we have possibility to `throw Exception` if `null` in assignment statement like this:

    var foo = default(string);
    var bar = foo ?? throw new NullReferenceException();

I would like to proposal a possibility to `continue` or `break` loop if `null` in assignment statement like this:

    foreach (var foo in new string[] { null, "a", "b", "c" })
    {
        var bar = foo ?? continue;
        // ...
    }

**Comment by HaloFour** [comment]
https://github.com/dotnet/csharplang/issues/176

https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-06-27.md#returnbreakcontinue-as-expressions

**Comment by devsamt** [comment]
OK, thank you for your response
