### ISSUE TITLE
Please allow partial properties

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3412]
The above would be great.  Just needed it and never knew we only got partial classes and methods.

**Comment by HaloFour** [comment]
Can you explain why they would be great?  What use cases would they solve?  How would the syntax work?  What does a "partial" getter do?

Partial methods have some fairly strict rules.  They exist for the purpose of generated/designer code to expose specific optional integration points.  That's why partial methods must be private and must not return a value.  It's entirely optional to provide an implementation, and if that implementation is not provided those partial method invocations are erased.  None of that seems to make sense with properties.

**Comment by YairHalberstadt** [comment]
The team is planning partial properties for a future version of C#, but decided there wasn't time for C# 9.

**Comment by TonyValenti** [comment]
The use case I have is that I need to be able to add metadata to auto-generated properties.

**Comment by canton7** [comment]
@TonyValenti You might be able to use the TypeDescriptor stuff for that, although it's less convenient.

Another great use-case would be for implementing INotifyPropertyChanged using source generators.

**Comment by YairHalberstadt** [comment]
> The team is planning partial properties for a future version of C#

Apparently not after all. See notes at https://github.com/dotnet/csharplang/issues/3413

**Comment by ViIvanov** [comment]
> The use case I have is that I need to be able to add metadata to auto-generated properties.

What kind of metadata do you mean? Attributes?

**Comment by 333fred** [comment]
The notes there are honestly worded far more strongly than I remember our decision being.

**Comment by CyrusNajmabadi** [comment]
Me as well.

**Comment by jfontsaballs** [comment]
In my opinion, partial properties would be a very good fit with source code generators in a variety of cases where the code for a property is used repeatedly. The most obvious case are ViewModels, where you have a lot of properties that basically do the same: get and set the value and call the `OnPropertyChanged` method.

Writing this inside a class deriving from each library's view model base class:
`public partial string MyProperty {get; set;}`

Could allow generation of this code:
`private string _MyProperty;
public partial string MyProperty {
    get => _MyProperty; 
    set {
        _MyProperty = value;
        OnPropertyChanged(nameof(MyProperty));
    }
}`

**Comment by spydacarnage** [comment]
That is literally one of the first examples they give for source code generators - you supply an attribute-tagged backing field and it produces the property for you.  That way, you don't need a partial property.
```csharp
[AutoNotify("MyProperty")]
private string _myProperty;
```

**Comment by jfontsaballs** [comment]
I believe the having the property on the human written code would allow the backing field to become a hidden implementation detail. It could be tagged to prevent it from appearing on intellisense thus making it very difficult to misuse the field instead of the property.

**Comment by jfontsaballs** [comment]
Allowing for edition of existing code as proposed in #3772 would reduce the need for partial properties, as their implementation could be modified without being marked partial.
