### ISSUE TITLE
Integration of Contructor Parameters and their class backing fields

### ISSUE THREAD

**Issue by Discovery-support** [dotnet/csharplang#3415]
Feature: add a `this.` prefix to a constructor parameter to automatically assign the value to a class backing field.

`class Widget {`
`	public Widget(int this.age) {`
`	int age;`
`	void DisplayAge() {`
`		Console.WriteLine($"Age is {age}");`
`	}`
`}`
Prevents an error where the class backing field is not assigned. 
Useful especially when using DI to inject many services.

**Comment by HaloFour** [comment]
See: #2691

Primary constructors will capture the parameters and make them usable throughout the class:

```cs
class Widget(int age) {
    void DisplayAge() {
        Console.WriteLine($"Age is {age}");
    }
}
```

**Comment by Discovery-support** [comment]
@HaloFour  

The code below does not compile: `A namespace cannot directly contain members...`
What am I missing?

```
using System;
using System.Collections.Generic;
using System.Text;

namespace Discovery.ServerEnv.Services
{
    class Widget(int age) {
        void DisplayAge()
        {
            Console.WriteLine($"Age is {age}");
        }
    }
}
```

**Comment by HaloFour** [comment]
Primary constructors haven't shipped with the language yet.  It's slated for C# 9.0 which is due later this year, although that's never guaranteed.

**Comment by CyrusNajmabadi** [comment]
He's saying there's a proposal already to support this. Not that this is already supported :-)

**Comment by Discovery-support** [comment]
@HaloFour @CyrusNajmabadi  thank you!!!  I wondered how I had missed that trick when coding.
