### ISSUE TITLE
Allow overriding *and* "new" on same method

### ISSUE THREAD

**Issue by AArnott** [dotnet/csharplang#3416]
Consider this case where a base class has a virtual factory method, and a derived type overrides it to return a derived type from the factory method:

```cs
public class Base {
    public virtual A M() {
        return new A();
    }
    
    public class A { }
}

public class Derived : Base {
    public override A M() {
        return new B();
    }
    
    public class B : A { }
}
```

But this means folks using `Derived` directly don't get the type safety of knowing that `Derived.M()` returns an instance of `B`.

What would be great is if like "explicit interface implementations" we had "explicit override implementations" or something else that would allow syntax like this:

```cs
public class Base {
    public virtual A M() {
        return new A();
    }
    
    public class A { }
}

public class Derived : Base {
    override A Base.M() => this.M();

    public new B M() {
        return new B();
    }
    
    public class B : A { }
}
```

Notice how the override is no longer public (and explicitly identifies the member being overridden) and we can define a `new B M()` method.
This allows folks accessing `Derived` directly to call `M()` and get a `B` back, but polymorphism still works because we have *also* overridden `M()` on the base type.

**Comment by HaloFour** [comment]
For your use case the team is planning one better: [Covariant Returns](https://github.com/dotnet/csharplang/issues/49)

That would enable you to write it as follows:

```cs
public class Base {
    public virtual A M() {
        return new A();
    }
    
    public class A { }
}

public class Derived : Base {
    public override B M() {
        return new B();
    }
    
    public class B : A { }
}
```
