### ISSUE TITLE
[Proposal] Extend Null-Conditional Operator to Support Skipping Code

### ISSUE THREAD

**Issue by ChayimFriedman2** [dotnet/csharplang#3424]
Related #2883 , #3034 .

## Motivation

The null conditional operator is super useful, especially with the introduction of nullable reference types to C# 8.
However, whilst I forgot about
```c#
if (obj != null && obj.Property != null) // Do not reverse order!
{
    obj.Property.Method();
}
```
and replaced it with `obj?.Property?.Method()` - which is much more readable by the way, I still find myself writing tons of code of the following forms:
```c#
if (obj != null && obj.Property != null) // Can be shorten with `if (obj?.Property != null)`
{
    other = obj.Property; // The operator won't help here because I don't want to touch `other` if either `obj` or `obj.Property` are null.
}

if (someParam != null)
{
    Method(someParam);
}
```
And similar.

## Solution

I propose extending the null conditional operator to (let me know if I forgot something):
 - Method arguments.
 - Assignments.
 - The variable in `foreach` blocks.

When used in these contexts, the operator means "if the result of this expression is null, then eliminate the whole statement". That is,
```c#
Method(arg?);

a = b?;

foreach (var a in b?)
{
}
```
is translated to
```c#
if (arg != null) { Method(arg); }

if (b != null) { a = b; }

if (b != null)
{
    foreach (var a in b) { }
}
```

This will also get rid of the related proposals above.

## Details

With variable declaration+assignment, the scope shall be outside of the virtual `if` - `var a = b?;` gets translated to
```c#
TYPE a;
if (b != null) { a = b; }
```
and not
```c#
if (b != null) { var a = b; }
```
Also of course the variable `a` is considered uninitialized.

**Comment by HaloFour** [comment]
Relevant: https://github.com/dotnet/roslyn/issues/5961

https://github.com/dotnet/roslyn/issues/5961#issuecomment-149952131

**Comment by ChayimFriedman2** [comment]
Duplicate of dotnet/roslyn#5961

**Comment by YairHalberstadt** [comment]
@ChayimFriedman2 

I would keep this open as that's in the wrong repository.

**Comment by svick** [comment]
@YairHalberstadt It is, but the reason it was closed (https://github.com/dotnet/roslyn/issues/5961#issuecomment-149952131) still applies:

> I can't imagine anyone on the language design team championing this proposal, and that is what it would take for this (or any other proposal) to happen.
