### ISSUE TITLE
Minecraft Mod C# / gradlew setupDecompWorkspace  Error 501 HTTPS required

### ISSUE THREAD

**Issue by TheSaikos** [dotnet/csharplang#3426]
Hello,
So today I wanted to start learning a bit C# to make my own minecraft mods.I downloaded Visual Studio and the Minecraft Developer Package.I started my first project for forge 1.8 and when the command "gradlew setupDecompWorkspace --refresh-dependencies" gets automatically runned it provides an error after about 15 seconds and spits out the error "Error: Main class GradleStart couldnt be found or loaded".I didnt really find much help on Google,but I hope you guys can help me out.

**Comment by eyalsk** [comment]
@TheSaikos This is the C# language design repository and the totally wrong place to ask these sorts of questions, you should probably try the Minecraft forum, StackOverflow or Discord.

**Comment by 333fred** [comment]
Hi @TheSaikos! Unfortunately, you've stumbled into the wrong place here. Minecraft mods are made in Java, not C#, and this repository isn't for help with programs. I'd suggest starting by Googling for Minecraft mod tutorials: this [one](https://blog.usejournal.com/a-beginners-guide-to-modding-minecraft-9a42536495f6) looks comprehensive and relatively new. The Minecraft Developer Pack has not been updated in a long time and it would not surprise me if it just doesn't work anymore, given that it's 5 years out of date at this point. I hope that helps, and good luck!
