### ISSUE TITLE
Question: Compile time Exhaustiveness checking of Enum Indexed properties

### ISSUE THREAD

**Issue by Honga1** [dotnet/csharplang#3427]
Is it possible to achieve exhaustiveness checking in c# with properties, indexed classes or dictionaries? 

Apologies if my terminology is not on topic. I'm a c# beginner.

In TypeScript I can use string literals to achieve this
```TS
type Animals = 'cat' | 'dog' | 'bird';
type MakeSound = () => void;

type MustImplement<T extends string, A> = {
  [key in T]: A;
}

class AnimalsMakeSound implements MustImplement<Animals, MakeSound> {
  /**
   * Class 'AnimalsMakeSound' incorrectly implements interface 'MustImplement<Animals, MakeSound>'.
   * Type 'AnimalsMakeSound' is missing the following properties from type 'MustImplement<Animals, MakeSound>': cat, dog, birdts(2420)
   */
}
```

The closest I've come is something like this:
```cs
using MakeSound = System.Action;
enum Animals {
  cat,
  dog,
  bird,
}

public interface MustImplement<T, A> where T : Enum {
  public abstract A this[T index] {
    get;
  }
}

class AnimalsMakeSound : MustImplement<Animals, MakeSound> {
  public MakeSound this[Animals index] {
    get => makeAnySound;
  }
  /** ^^ This should not complete the abstract interface. It should error as all indices should be 'implemented' seperately */
}
```

**My desired pattern:**
```cs
class AnimalsMakeSound : MustImplement<Animals, MakeSound> {
  public MakeSound this['cat'] {
    get => makeCatSound;
  }
  public MakeSound this['dog'] {
    get => makeDogSound;
  }
  public MakeSound this['bird'] {
    get => makeBirdSound;
  }
}
```

This application for this is that I want to require, at compile time, a consumer of my interface to implement methods to handle their chosen animals.

**Comment by svick** [comment]
What exactly are the rules for when the code should cause an error? In C#, throwing an exception is always valid instead of returning a value, so I don't think you can somehow forbid throwing. Though maybe you could write an analyzer to detect the situation and produce a custom error.

**Comment by Honga1** [comment]
> What exactly are the rules for when the code should cause an error? In C#, throwing an exception is always valid instead of returning a value, so I don't think you can somehow forbid throwing. Though maybe you could write an analyzer to detect the situation and produce a custom error.

@svick I think I wasn't perfectly clear. My expected result would be that you have to, per index, specify a result.

Desired 'Correct' pattern to make the compiler happy
```cs
class AnimalsMakeSound : MustImplement<Animals, MakeSound> {
  public MakeSound this['cat'] {
    get => makeCatSound;
  }
  public MakeSound this['dog'] {
    get => makeDogSound;
  }
  public MakeSound this['bird'] {
    get => makeBirdSound;
  }
}
```

**Comment by svick** [comment]
@Honga1 There's nothing like that in C#. Discriminated unions (https://github.com/dotnet/csharplang/issues/113) are being considered for a future version, but those are still not exactly what you're asking for.

**Comment by Richiban** [comment]
I'm afraid that what you're asking for is very much something only Typescript can do due to the fact that's built on top of Javascript.

**Comment by Honga1** [comment]
Thank you both for your help :) Very much looking forward to discriminated unions.
