### ISSUE TITLE
[Proposal] Member access operator

### ISSUE THREAD

**Issue by egortech** [dotnet/csharplang#3446]
Currently, there is not able to set custom member access routing that would be useful for wrapper type like we already have in Nullable<T> operator ?., I proposed to add and allow to overload such operator for given type T that wrap type TWrap:

```csharp
public static TWrap operator*(T value)
public static TWrap operator->(T value)
```

For example, we have in Framework type Lazy<T>property Value that provide value of type T, if we want to access some member or call function M of T currenly we should write, for example:

```csharp
var f = new Lazy<Point>(i => new Point(0, 0));
var length = Math.Sqrt(Math.Pow(f.Value.X + f.Value.Y, 2));
var p = f.Value;
```

With proposed operator it can be written like:

```csharp
var f = new Lazy<Point>(i => new Point(0, 0));
var length = Math.Sqrt(Math.Pow(f->X + f->Y, 2));
var p = *f;
```

We already have such semantic for a pointer type, so it can be expanded for a custom type, too.

Sorry if I duplicated a similar proposal somehow.

**Comment by DaZombieKiller** [comment]
This would be an abuse of operator overloading (imo) and only really serves to make the code less clear. `*` and `->` are synonymous with pointers, and suddenly having them appear in safe code with non-pointer values would be very confusing, and probably syntactically ambiguous in some situations.

**Comment by egortech** [comment]
It can be used in WeakReference<T> scenario or another custom reference-like type, for example in the implementation of some sort of smart pointer like in C++.

**Comment by CyrusNajmabadi** [comment]
> It can be used in WeakReference scenario or another custom reference-like type

Those are the *last* place i would ever want to overload these operators.  I absolutely do not want to treat the weak-ref the same as teh wrapped type.
