### ISSUE TITLE
implementing a nullable guard method for a specific member

### ISSUE THREAD

**Issue by bitbonk** [dotnet/csharplang#3447]
Consider the following code:

```
private Foo? fooMember;

public void DoSomethingWithFoo()
{
    this.VerifyFooNotNull();
    this.fooMember.DoSomething(); // Warning CS8602: Dereference of a possibly null reference.
}

private void VerifyFooNotNull()
{
     if (this.fooMember == null)
    {
        throw new InvalidOperationException("Foo must be initialized");
    }
}
```

Is there an attribute or similar I could apply to `VerifyFooNotNull` so that the CS8602 warning goes away?

**Comment by KalleOlaviNiemitalo** [comment]
In C# 9, `MemberNotNullAttribute` from <https://github.com/dotnet/roslyn/issues/41438> seems to cover this.

**Comment by 333fred** [comment]
Yep, that should be covered by MemberNotNull. I'm going to close this as a duplicate, let me know if that's not quite the same as what you're looking for and I can reopen. https://github.com/dotnet/csharplang/issues/3297
