### ISSUE TITLE
Proposal: using declaration without var

### ISSUE THREAD

**Issue by SebastianSchumann** [dotnet/csharplang#3449]
# What we can do using C#8:

Thanks to the new language feature [using declaration](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations) of C # 8, we can separate code more clearly. We use this feature in lock statements like this (needs [Nito.AsyncEx](https://www.nuget.org/packages/Nito.AsyncEx)):

_Pre C#8_

    using (await this._semaphore.LockAsync())
    {
        // ...
    }

_Using C#8_

    using var lockHandle = await this._semaphore.LockAsync();
   
    // ...

This looks better because the logic code is not poluted by handling the locking mechanism.

But we don't need the `lockHandle`. The pre-C#8-code doesn't need to define a variable. The problem above leeds to code like:

    using var @finally = ...

# Proposal

It should be valid to use a `using declaration` without to declare a variable:

    using await this._semaphore.LockAsync();

The advantage is that you can create multiple using statements to bundle cleanup tasks without creating useless variable names `@finally`, `@finally1` ...

_Discards_

I am not for the use of discards at this point (currently it's not supported) because discards has a meaning of _there is something returned but I don't care about it_. This is not true for using declarations. We need the returned value to be freed at the end of the code block.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/3444
