### ISSUE TITLE
[Proposal] FirstOrNull or FirstOrValue Linq method

### ISSUE THREAD

**Issue by kevin-meyers** [dotnet/csharplang#3457]
I see many people who get caught by and don't understand FirstOrDefault in any use case that isn't an object. Even on the official docs the examples end up using many methods (like string.IsNullOrEmpty) just to capture the same logic.

I propose a True FirstOrNull which searches for the first to satisfy the boolean function, or returns Null so it can be used in conjunction with other powerful methods like coalesce (??).

The other idea is to let the dev define the value if the constraint is not satisfied, circumventing the need to use coalescing, and just define their return.

Also apologies if this is not formatted properly I am very new to C#, and also open-source anything.

**Comment by jnm2** [comment]
Duplicate of dotnet/runtime#28650. FirstOrValue would be FirstOrNull() ?? defaultValue.

**Comment by kevin-meyers** [comment]
Yep sorry I didn't check first, I won't let it happen again, thank you for the quick response!

**Comment by CyrusNajmabadi** [comment]
> Yep sorry I didn't check first, I won't let it happen again,

No need to be sorry :)   it can be really tough to find dupes :)
