### ISSUE TITLE
Proposal: Provide syntax to play music in strings, like QBasic

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#346]
QBasic has "play" command to play music which is stored in strings, why VB and C# can't? 
I hope that VB and C# have the same ability to play music without a music file.

**Comment by HaloFour** [comment]
Anyone can write a library that provides this functionality.  It has no place being built into the language.

**Comment by ygc369** [comment]
@HaloFour
Anyone can write this? Are you sure? How to write? Could you give an example? Don't tell me to use a lot of sound files. 
Maybe I should not put this proposal here, I should put it in Corefx repo. But I don't think this proposal is worthless. If you only have a music book, how would you program to play it using C#?

**Comment by yaakov-h** [comment]
C# shouldn't play any other note. 😄

**Comment by orthoxerox** [comment]
@ygc369 try https://github.com/naudio/NAudio

**Comment by alrz** [comment]
cool.

**Comment by ygc369** [comment]
@orthoxerox 
NAudio does not support this.
see https://github.com/naudio/NAudio/issues/206
