### ISSUE TITLE
Proposal: Static Generics

### ISSUE THREAD

**Issue by hez2010** [dotnet/csharplang#3460]
## Proposal: Static Generics
For people who are not familiar with Static Generics, please see https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/statically-resolved-type-parameters

## Proposed syntax
Use `inline` to mark the functions/classes are resolved from caller,`'T` for static generic type parameters.

```csharp
inline void 'T Foo<'T>('T x, 'T y)
{
    return x + y; // requires static member '+'
}

void Main()
{
    var x = Foo(5, 6); // 11
    var y = Foo("Hel", "lo"); // "Hello"
    var z = Foo(new { }, 234); // error
}
```

**Comment by Richiban** [comment]
This functionality will hopefully be provided by the shapes proposal. https://github.com/dotnet/csharplang/issues/164

**Comment by huoyaoyuan** [comment]
An enhancement of generic type system should have been planned for C# 10 (See [Language Version Planning](https://github.com/dotnet/csharplang/projects/4#column-6335666)). We don't need to open new issues for specific scenarios, as the enhancement are supposed to be wider.

The language team is currently completing C# 9 that features records. Once C# 9 has been completed, they should be able to focus on the enhancement.

**Comment by 333fred** [comment]
There is some type system improvement stuff triaged into 10, but I wouldn't expect anything really big until 11. Some of the stuff in 10 is there to make sure we talk about it during that time frame.

**Comment by RUSshy** [comment]
I personally not a fan of the ` syntax, not only it is hard to read (looks like a font artifact) and it is hard to type in non QWERTY keyboards

**Comment by Lemmingh** [comment]
[**Generic method**](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generic-methods) has already **made code analysis awkward** sometimes, for example, [locking](https://devblogs.microsoft.com/dotnet/automatically-find-latent-bugs-in-your-code-with-net-5/#do-not-allow-locks-on-non-reference-types).

I'm afraid the **current** proposal would introduce more hard-to-lint cases.

IMHO, restrictions should be added at least. What about:

* must not exceed `internal`.
* must specify **type parameter constraints**.

**Comment by YairHalberstadt** [comment]
Closing as being looked at as part of https://github.com/dotnet/csharplang/discussions/164, #1711
