### ISSUE TITLE
Feature Request: Enhancements to the 'using' declaration

### ISSUE THREAD

**Issue by simon-curtis** [dotnet/csharplang#3463]
## Objective 

To enhance the 'using' syntax and create more options for when an ambigous reference is detected.

## Methods

For the following proposals, please assume we are using the following class library:

```
namespace Namespace {
    public interface ICommonClass {
        void SayHi();
    }

    public abstract class CommonClass : ICommonClass {
        protected string welcomeString = "Hi from Namespace.CommonClass"!;
        public CommonClass() {}
        public virtual void SayHi() => Console.WriteLine(welcomeString);
    }
    
    public class SingleClass : CommonClass, ICommonClass  {
        public SingleClass() {
            this.welcomeString = "Hello from Namespace.SingleClass"!;
        }
    }
}

namespace Namespace.Child {
    public class CommonClass : Namespace.CommonClass, ICommonClass {
        public CommonClass() {
            this.welcomeString = "Hey from Namespace.Child.CommonClass"; 
        }
    } 
}
```

### Proposal 1: Chaining 

Chain together declarations in the using statements to create a hierarchy of import order.

_Like implementing multiple configBuilders in web.config's appSettings (Ref: [Configuration Builders](https://github.com/aspnet/MicrosoftConfigurationBuilders#appsettings-parameters))_

```
using Namespace.Child, Namespace;
```

This would be the cleanest way of implementing this, but different in-line namespaces could be messy. For example: `using CustomLibrary.SqlClient, System.Data.SqlClient;`

### Proposal 2: 'Overrides' attribute

If you have ambiguous references from two completely separate libraries, use a `[Overrides(...)]`

```
using Namespace;
[Overrides(Namespace)]
using Namespace.Child;

// for every ambiguous reference, the preferred namespace is implied.

var x = new CommonClass(); 
// equals
var x = new Namespace.Child.CommonClass();
```

### Proposal 3: Destructuring

Avoid importing unnecessary references using JS-like destructuring. Does not override references, so ambiguity would still need to be handled.

```
using System.Data;
// imports all references, in this case just CommonClass
using Namespace.Child; 

// only import essential references
using SingleClass, ICommonClass from Namespace; 

...

namespace Example {
    class CoolCommonClass : CommonClass, ICommonClass {
        public CoolCommonClass() {
            this.welcomeString = "Ciao from Example.CommonClass";
        }

        public override void SayHi() => Console.WriteLine(welcomeString + "! (Overridden)");
    }

    public static void Main(string[] args) {
        var singleClass = new SingleClass();
        singleClass.SayHi(); // Output : Hello from Namespace.SingleClass
        
        var commonClass = new CommonClass();
        commonClass.SayHi(); // Output : Hey from Namespace.Child.CommonClass

        var coolCommonClass = new CoolCommonClass();
        coolCommonClass.SayHi(); // Output : Ciao from Example.CommonClass! (Overridden)
    }
}
```

Using tuples to create a new _filtered_ namespace. *I don't really know tuples, sorry if this is wrong

```
using System.Data;
using Namespace.Child;
using (class SingleClass, interface ICommonClass) Namespace;
using (class SingleClass, interface ICommonClass) *Alias* = Namespace; (optional)
```

### Proposal 4: New 'prefer' keyword

The 'prefer' syntax will tell the compiler to prefer one namespace over another in the event of ambiguous reference. 

```
using System;
using Namespace;
using Namespace.Child;

prefer CommonClass from Namespace.Child; 
// or for all references...
prefer Namespace.Child;

namespace Example {
    class ExampleClass {
        public ExampleClass() {
            var commonClass = new CommonClass();
            commonClass.SayHi(); // output: "Hey from Namespace.Child.CommonClass"
        }
    }
}
```
_Note: Intellisense could advise if the prefer declaration is not being used, similar to unused variables_ 

This could allow for encapsulation depending on where it's implemented.

```
using System;
// here for file encapsulation

namespace Example {
    // here for this namespace, within file

    class ExampleClass {
        // here for just this class

        public ExampleClass() {
            // here for just this method
        }
    }
}
```

## Real Life Example

I have recently inherited a project that has a class library that has a namespace structure:

    - DynamicReporting
    - DynamicReporting.Reports
    - DynamicReporting.Graphs
    - DynamicReporting.Exports

The problem is:

- Reports, Graphs, and Exports all implement an abstract class "SectionMap" from DynamicReporting
- None of the child namespaces implement the very widely used class "Template" from DynamicReporting. 

I cannot include both of them in the file as it creates ambiguous references.

Due to this webforms app already owning namespaces for Reports, Graphs, and Exports I cannot use:

```
using DynamicReporting;
...
var x = Reports.SectionMap();

// but could use (annoying, but correct)
var x = DynamicReporting.Reports.SectionMap();
```

This means I have the following options (all valid, just time consuming):

1) Use `using DynamicReporting;` and explicitly referencing children namespaces `var map = new DynamicReporting.Reports.SectionMap()`

2) Use `using DynamicReporting.Reports;` and explicitly referring to DynamicReporting `var template = new DynamicReporting.Template()`

3) Use aliases for the imports, this would be good for decoupling as I could easily change out the class library. However, using aliases can cause naming confusion and reduce readability. 

4) Use internal for the abstract classes in DynamicReporting. (_probably the best option_) - although, in this particular scenario, this class library only exists because it supports a legacy system that will soon be deprecated. After this happens, we plan on merging this library for development simplicity but this will break the encapsulation.

5) Implement the missing classes from DynamicReporting in each of the children. This could work, but required more work maintaining it

---

_Please note: I am only a junior developer so there may be a better way to do this that I do not know about, also please excuse any code smells/errors in the proposal example code they aren't supposed to work - just give an idea_

**Comment by HaloFour** [comment]
Resolving ambiguous references is one of the idiomatic uses for aliases.  Why would that make the code less readable or confusin?

**Comment by simon-curtis** [comment]
@HaloFour yeah I guess you could be right.

My thinking was readability and continuity mainly. *Maybe I'm wrong, speaking as a junior here so please excuse my ignorance*

In my real life example the previous developer had done a bit of this, all over the codebase you have the likes of "DR", "DRExport", "DynamicExport" dotted around, meaning in large codebases you are constantly checking. Not to mention making it more difficult to refactor. Surely a larger code base with more people could get more confusing, no?

Also, I believe I have solved the problem for now by moving all of my abstract classes into their own branch of the namespace - don't know why I didn't think of that sooner *doh!*
