### ISSUE TITLE
Implicit conversion/cast operators from interface types

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/csharplang#3464]
During some code developement today, I wanted to write something like this:
```csharp
public class MySpecialCollection
    : IEnumerable<double>
{
    // ...

    public static implicit operator MySpecialCollection(IEnumerable<double> values) => ....;
}
```
to allow some user code like the following:
```csharp
void Main()
{
    MySpecialCollection coll1 = ...;
    MySpecialCollection coll2 = from double d in coll1
                                ...
                                select d + 42.0;
}
```

Obviously, the code would not compile:
> CS0552: 'MySpecialCollection.implicit operator MySpecialCollection(IEnumerable<double>)': user-defined conversions to or from an interface are not allowed.

Aside from wanting this code to work, it got me thinking:
_Why_ did Microsoft take this design choice at that time? What were the specific reasons? I hardly think that it was an CLR-issue, as operators get compiled to (specially named) methods in the background -- so any conversion operator invocation should work exactly like an equivalent static method invocation.

<br/>

Bonus points if you are a member on the LDT and you can tell me whether the team would be open to relaxing this conversion rule/limitation.

**Comment by YairHalberstadt** [comment]
https://stackoverflow.com/questions/2433204/why-cant-i-use-interface-with-explicit-operator

> User-defined conversions are not allowed to convert from or to interface-types. In particular, this restriction ensures that no user-defined transformations occur when converting to an interface-type, and that a conversion to an interface-type succeeds only if the object being converted actually implements the specified interface-type.

**Comment by Unknown6656** [comment]
Oh, well that is more than understandable.
Thank you!

**Comment by huoyaoyuan** [comment]
The recommended usage of conversion in linq is an explicit `ToXXX` extension method, like `ToArray`, `ToList`, `ToHashSet`.

**Comment by 333fred** [comment]
> Oh, well that is more than understandable.
> Thank you!
> 
> **EDIT:** On second thoughts, however, it is understandable when converting _to_ an interface.
> The other way around (e.g. like in my original post) does not make to much sense in my opinion......

That would be odd for the same reason: you just converted a thing from an interface type, yet you cannot go back to that interface?
```cs
I i = ...;
C c = i;
Console.WriteLine(c is I); // Never returns false today (Assuming I is an interface) 
```
