### ISSUE TITLE
Nullable Enable and Generics default

### ISSUE THREAD

**Issue by HavenDV** [dotnet/csharplang#3471]
After adding [`<Nullable>enable</Nullable>` or `#nullable enable`](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types), I ran into the following problem with my Generic methods:

This does not work:
```cs
public T? GetDefault<T>()
{
    return default;
}
```
[![enter image description here][1]][1]

This works with warning:
```cs
public T GetDefault<T>()
{
   return default;
}
```
[![enter image description here][2]][2]

This works individually, but not together.
```cs
public T? GetDefault<T>() where T : class
{
    return default;
}

public T? GetDefault<T>() where T : struct
{
    return default;
}
```
[![enter image description here][3]][3]

Logically, the first method should work.
What is the correct way out of this situation without creating several methods and suppressing warning?

P.S.
At the moment, I have not found anything better than this solution:
```cs
public T GetDefault<T>()
{
    return default!;
}

public void OtherMethod()
{
    string value1 = GetDefault<string>();
    string value2 = GetDefault<string?>();
    string? value3 = GetDefault<string?>();
}
```
[![enter image description here][4]][4]

  [1]: https://i.stack.imgur.com/yxaEI.png
  [2]: https://i.stack.imgur.com/upbEp.png
  [3]: https://i.stack.imgur.com/qrtMZ.png
  [4]: https://i.stack.imgur.com/HnTHw.png

**Comment by bbarry** [comment]
agree it is frustrating; not much to do about it I think now though.

Here is what I do:

    [return: MaybeNull]
    public T GetDefault<T>() => default!;

    public void OtherMethod()
    {
    #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
        string value1 = GetDefault<string>();
    #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
        string? value2 = GetDefault<string?>();
        string? value3 = GetDefault<string>();
    }

**Comment by 333fred** [comment]
C# 9 will bring `T??`: https://github.com/dotnet/csharplang/issues/3297.

Until then, you can use @bbarry's solution. Note that the pragma warning suppressions would only be needed if you attempted to assign a `string?` to a `string`, as is done on the first line of `OtherMethod` there.

**Comment by 333fred** [comment]
You can see the full set of attributes that can inform nullable analysis here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis.

**Comment by HavenDV** [comment]
An interesting thing - Visual Studio offers this edit:
![image](https://user-images.githubusercontent.com/3002068/82497415-8a0c8300-9b31-11ea-8a25-2fd867f33b33.png)

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv for VS issue above.

**Comment by HavenDV** [comment]
Is there a way to use the [MaybeNull] attribute in a .Net Standard 2.0 project?

**Comment by bbarry** [comment]
I think you might be able to declare the attributes as internal in the correct namespace within your assembly? I haven't tried because targeting .Net standard leaves too many warts for me to deal with so I gave up and multitarget just net48 and netcoreapp3.1. Hopefully net5/6+ will improve things and let me gain mono/uwp/xamarin/etc. runtime support before I actually need them.

https://github.com/dotnet/runtime/issues/29617#issuecomment-494505569

**Comment by HavenDV** [comment]
What about the situation where I need to deliver a nuget package that contains a public function with this attribute?

**Comment by bbarry** [comment]
The compiler is looking for an attribute on the type with the full name (no assembly though) of `System.Diagnostics.CodeAnalysis.MaybeNullAttribute`.

It isn't looking for a specific type.

This is similar to how async works in earlier versions of .net framework. The internal attribute would have the same name.

**Comment by YairHalberstadt** [comment]
The original example is now legal in C# 9
```csharp
public T? GetDefault<T>()
{
    return default;
}
```
