### ISSUE TITLE
typeof(member)

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3473]
Please allow typeof(...) to return the declared type of a member.
````
public interface MyInterface {
  string Foo {get; set;
}

....
var Type = typeof(MyInterface.Foo);
//Same as typeof(string)

````

**Comment by Joe4evr** [comment]
Would be better served if C# ever got `infoof`, since that's much more flexible.

**Comment by HaloFour** [comment]
I kind of miss the Informix 4GL feature where you could declare a variable based on the type of another variable or member of a structure.  Made refactoring very easy.  😄

**Comment by Richiban** [comment]
@HaloFour Typescript has that, and it's pretty great. You can pass any expression to `typeof` and it'll give you its static type.

```typescript

const expr = { x: 4, y: 5 }

type T = typeof expr
```

**Comment by hez2010** [comment]
I think this may be useful for:
```csharp
var x = new { X = 1 }; // <>f__AnonymousType0<<X>j__TPar>
var t = x.GetType().GetConstructor(new [] { typeof(int) });
decltype(x) y = t.Invoke(new object[] { 5 }); // <>f__AnonymousType0<<X>j__TPar>
```

**Comment by luizfernandonb** [comment]
Good suggestion
