### ISSUE TITLE
Discussion: Not having to declare namespaces for non-conflicting names, based on project depencencies

### ISSUE THREAD

**Issue by skleanthous** [dotnet/csharplang#3477]
## Overview

When following single responsibility principle, and good encapsulation of logic, very often I find myself ending up having many, many smaller files, with a significant amount of `using` statements, which provide little benefit to the maintainer of the solution.

I would like to have the compiler discover the FQN of types used in code through the existing project references, and not have to explicitly maintain the list of references. This already happens in some respect within IDE's where you have the ability to automatically add missing namespace references based on the existing project references.

Currently, I am not aware of anyone using the namespaces to understand the code, since all modern IDE's have the ability to provide full type information when hovering over the type or variable.

## What I'd propose is

- If a namespace is specified, try to resolve types using that namespace first
- When resolving a type through the explicitly provided namespances fails, try to discover an accessible type definition in the project and the project references
   - If exactly one type matches, automatically and implicitly add the reference, so it doesn't have to exist writen in source code
   - If no accssible type matches or if more than one match, emit a compilation error

## Benefits

- Readability of code
- Smaller code files / less noise
- A bit less effort

## Drawbacks

Outside of IDE's following this may cause some confusion, althgouh in such environments, one has the option to write using statements explicitly

**Comment by YairHalberstadt** [comment]
Unfortunately, once you have a reasonable number of assembly references, almost every type is ambiguous. Even worse, every time a library maintainer adds a new type, it will break many consumers who had so far only had one type with that name, and now have multiple.
