### ISSUE TITLE
(Proposal) Extension properties and indexers

### ISSUE THREAD

**Issue by lachbaer** [dotnet/csharplang#349]
Normally, `IsXyz` should be a boolean property. As *"extension properties"* are not allowed this is implemented as extension methods, what breaks the appearance a bit.

I propose to introduce *extension properties*:
```C#
        // code originally from Roslyn/TypeSymbolExtensions.cs
        // currently implemented as methods
        public static bool IsIntrinsicType[this TypeSymbol type]
        {
            get => type.SpecialType.IsIntrinsicType;
        }

        public static bool IsPartial[this TypeSymbol type]
        {
            get
            {
                var nt = type as SourceNamedTypeSymbol;
                return (object)nt != null && nt.IsPartial;
            }
        }

        public static bool IsPointerType[this TypeSymbol type]
        {
            get => type is PointerTypeSymbol;
        }
```
The method characterising parantheses are just replaced by brackets.
I think it will not break the overall appearance of properties and indexers, because for indexers the index is also passed as parameter within brackets, and it will also allow for extension indexers
```C#
public int this[this ExtendedType type, int index]
{
    get => {NOP};
    set => {NOP};
}
```

**Comment by HaloFour** [comment]
#192 

"Extension everything" would apply to properties.
