### ISSUE TITLE
[suggestion] expressof expression

### ISSUE THREAD

**Issue by surfsky** [dotnet/csharplang#3499]
Because linq expression is so difficult to write and read, I prefer the expressof expression. The below codes will create a System.Linq.Expressions.Expresson objects:

``` c#
var exp = expressof(Person.Name);
var exp = expressof(DbElement.Value <= 10);
```
will create expression objects, like:

``` csharp
Expression<Func<Person, string>> exp = t => t.Name;
Expression<Func<DbElement,bool>> exp = t => t.Value <= 10;
```

**Comment by nawfalhasan** [comment]
Suggestion is not clear. What expression does it return? May be explicitly typing `exp` is more helpful for everyone

**Comment by Joe4evr** [comment]
@nawfalhasan He likely means `System.Linq.Expressions.Expresison`.

**Comment by svick** [comment]
How is that better than the following?

```c#
Expression<Func<string>> exp = () => Person.Name;
```

Keep in mind that in the most common situations, you can use type inference to avoid specifying the type explicitly.

**Comment by surfsky** [comment]
Yes, @svick, It's I wanted.

``` csharp
Expression<Func<Person, object>> exp = t => t.Name;

->

var exp = exprssof(Person.Name);
```

The later expression is simply and readable.

**Comment by CyrusNajmabadi** [comment]
Please explain how your proposal works.  i.e. what the syntax is that you support and what the rules are for how hte language should interpret it.  For example, it appears as if `expressof(DbElement.Value <= 10)` is short for `(Expression<Func<DbElement,bool>>)(t => t.Value <= 10)`, but what are the rules that accomplishes that?

**Comment by RamType-0** [comment]
```C#
var exp = expressof(Person.Name);
```

With this syntax, we are missing information about Expression's type.
These are candidates.

1. `Expression<Func<Person, string>>`
2. `Expression<Action<Person>>`
3. `Expression<PersonToString>`
`PersonToString` is previously defined as `delegate string PersonToString(Person person);`

**Comment by surfsky** [comment]
When I write a extension function with expression like below:

``` csharp
        /// <summary>Get Expression' s Name</summary>
        public static string GetName(this Expression expr)
        {
            if (expr == null)
                return "";
            if (expr is LambdaExpression le)
                return GetName(le.Body);
            if (expr is UnaryExpression ue)
                return GetName((MemberExpression)ue.Operand);
            if (expr is MemberExpression me)
            {
                var name = me.Member.Name;
                if (me.Expression is MemberExpression)
                    return GetName(me.Expression) + "." + name;
                else
                    return name;
            }
            if (expr is ParameterExpression pe)
                return pe.Type.Name;
            return "";
        }
```

Then I write  unit test codes:

``` csharp
        [TestMethod()]
        public void GetNameTest()
        {
            Expression<Func<Person, string>> exp1 = t => t.Name;  // It's so long...
            var exp1 = expressof(Person.Name);          // It's my wish

            Assert.AreEqual(exp1.GetName(), "Name");
        }
```

It's only a simply example. However we will meet other complex expression type, It's hard to write the expression type, so I get this idea.

Just like：
``` csharp
nameof(Person.Name)     : Name           // Get name for Person.Name
typeof(Person.Name)     : String         // Get type for Person.Name。It's a discussing issue
expressof(Person.Name)  : t=> t.Name     // Get expression to fetch Person.Name
expressof(Person.Age > 10)  : t=> t.Age > 10     // Get expression to fetch Person.Age compare to 10
```

**Comment by surfsky** [comment]
@RamType-0 

``` csharp
var exp = expressof(Person.Name);
```

- The init type is from ```Person``` 
- The result type is from expression ```Person.Name```, is System.String type
- So we can get the func type : ```Func<Person, string>```
- And get the expression : ```Expression<Func<Person, string>>```

**Comment by RamType-0** [comment]
> * So we can get the func type : `Func<Person, string>`

Why is it not `Expression<Action<Person>>` or
`Expression<PersonToString>`?

**Comment by surfsky** [comment]
....eeee......The return type is from the expression in expressof(....). e.g.

``` csharp
public class Person
{
     public string Name {get;set;}
     public int Age {get;set;}
     public void Smile(){}
}

var exp1 = express(Person.Name);
var exp2 = express(Person.Age > 10);
var exp3 = express(Person.Smile());

means

Expression<Func<Person, string>> exp1 = t => t.Name;
Expression<Func<Person, bool>>   exp2 = t => t.Age > 10;
Expression<Action<Person>>       exp3 = t => t.Smile();





```
Person.Name is string Type, so we return Func<..., string>

**Comment by RamType-0** [comment]
```C#
using System;
public class C {
    
    public delegate bool IntToBool(int i);
    public delegate void IntAction(int i);
    
    public void M(Func<int,bool> f){} 
    public void M(Action<int> f){} 
    public void M(IntToBool f){} 
    public void M(IntAction f){} 
    public void M() {
        M(i=>true);
    }
}
```

With this code,C# compiler says that `M(i=>true)` is ambiguous between `M(IntToBool)` and `M(Func<int,bool>)`.

Why can you determine the type of `expressof(Person.Age > 10)` ?

**Comment by CyrusNajmabadi** [comment]
> ....eeee......The return type is inferred from the expression in expressof(....). e.g.

How are the parameter types inferred.  Let's say i want a `Expression<Func<Person, Person, bool>>`.  Today i can write:

```c#
Expression<Func<Person, Person, bool>> isOlder = (p1, p2) => p1.Age > p2.Age;
```

How do i write that with expressof?

```c#
var isOlder = expressof(Person.Age > Person.Age);
```

? How do we know each `Person` refers to a different parameter?

If they always create 'fresh' parameters, then how do i write:

```c#
Expression<Func<Person, string>> fullName = p => p.FirstName + " " + p.LastName;
```

?

If i write that with expressof i get:


```c#
var fullName = expressof(Person.FirstName + " " + Person.LastName);
```

But in the original example we said that would give us two fresh parameters.  

How can you distinguish tehse cases?

**Comment by HaloFour** [comment]
I question how often one needs to obtain an `Expression<Func<...>>` directly without going through LINQ or some other API that already greatly simplifies the developer experience.  Manually constructing an expression tree from individual components is not a common scenario.

It's also simple enough to handle this with a helper method:

```cs
static class Program {
    static Expression<Func<T, TR>> expressof<T, TR>(Expression<Func<T, TR>> expression) => expression;
    
    static void Main() {
        
        var exp = expressof((Person p) => p.Name);
    }
}
```

Theoretically something like method references could make this even simpler, as the following is legal in Java:

```java
public class Program {
    static <T, TR> Function<T, TR> expressof(Function<T, TR> expression) {
        return expression;
    };
    
    static void main(String[] args) {
        var exp = expressof(Person::getName);
    }
}
```

**Comment by surfsky** [comment]
@HaloFour 
``` cs
static Expression<Func<T, TR>> expressof<T, TR>(Expression<Func<T, TR>> expression) => expression;
```
It works, even if it's a little weird ;-)

**Comment by surfsky** [comment]
@CyrusNajmabadi 
use halofour's function:

```cs
Expression<Func<Person, Person, bool>> isOlder = (p1, p2) => p1.Age > p2.Age;
```
can be changed to

```cs
var isOlder = expressof((Person p1, Person p2) => p1.Age > p2.Age);
```

thanks HaloFour

**Comment by CyrusNajmabadi** [comment]
Closingout.  Simply solved with a library function without need for lang feature.
