### ISSUE TITLE
[suggestion] Multiline string """ expression

### ISSUE THREAD

**Issue by surfsky** [dotnet/csharplang#3500]
We can use """ string expresssion to simply multiline text construction, just like dart/python syntax:

``` csharp
var txt = """
    any multi line text" with ' and "
    any multi line text" with ' and "
    any multi line text" with ' and "
    """;
```

**Comment by yaakov-h** [comment]
This looks like #89 but with different syntax.

**Comment by surfsky** [comment]
Use """ mulitline string expression to avoid  escape character ‘  or ""

It's readable much more.

**Comment by 333fred** [comment]
Closing as a duplicate of #89.
