### ISSUE TITLE
C# adds get_ Prefix to Referenced VB.Net Properties with Attributes

### ISSUE THREAD

**Issue by Intelli-Soft** [dotnet/csharplang#3504]
I am using VB.Net and C# side by side in the same project (.net core)

In my VB.Net Project I have a simple ReadOnly Property like this:
`Public ReadOnly Property PropertyWithAttribute(Demo As String) As String
        Get
            Return Demo.ToString
        End Get
End Property`

In the C# project this proptery get's translated into: Class.get_PropertyWithAttribute("");

So, the property gets an unexpected "get_" prefix, what is not needed.
THX in advance
Harald

**Comment by CyrusNajmabadi** [comment]
This is by design.  Parameterized properties are not supported in C#.  So C# only sees the methods in IL (in htis case, named `get_PropertyWithAttribute`
