### ISSUE TITLE
[Proposal] "doublecontine" , to contine outer  loop

### ISSUE THREAD

**Issue by 2bhuinianhua** [dotnet/csharplang#3511]
### doublebreak and doublecontine

I want that the C# can have a "_doublecontine_" statement in the double loop statement，to simplify Code-A to Code-B when I want to continue the outer loop without extra flag .

#### Code-A:
```c#
for (int i = 0; i < 10; i++)
{
　　bool continueFlag = false;//①
　　for (int j = 0; j < 10; j++)
　　{
　　　　bool condition = true;
　　　　if (condition)
　　　　{
　　　　　　continueFlag = true;//②
　　　　　　break;//③
　　　　}
　　}
　　if (continueFlag)//④
　　　　continue;//⑤
}
```

#### Code-B:
```c#
for (int i = 0; i < 10; i++)
{
　　for (int j = 0; j < 10; j++)
　　{
　　　　bool condition = true;
　　　　if (condition)
　　　　　　doublecontinue;//①Just one statement
　　}
}
```

Code-B is easier to _write_ and _read_. 

Don't say "goto" or subfunction to me , that's bad.

What's samilar can be : _doublebreak , treblecontinue , treblebreak_.

**Comment by CyrusNajmabadi** [comment]
I've updated your OP to be formatted better.

Why not just use a subfunction or goto?  There's nothing wrong with them.  Note: an assertion that something is "that's bad" isnt' really an argument that will fly here :)

**Comment by CyrusNajmabadi** [comment]
There is practically no way we ould have these keywords.  There may be alternate proposals asking to do what java does.  i.e.:

```c#
outer:
for (int i = 0; i < 10; i++)
{
　　for (int j = 0; j < 10; j++)
　　{
　　　　bool condition = true;
　　　　if (condition)
　　　　　　continue outer;
　　}
}
```

**Comment by hez2010** [comment]
I think C# could add an optional parameter to `continue` and `break`, just like what bash did.

```csharp
for (int i = 0; i < 10; i++)
{
　　for (int j = 0; j < 10; j++)
　　{
　　　　bool condition = true;
　　　　if (condition)
　　　　　　continue 2;
　　}
}
```

**Comment by Joe4evr** [comment]
@CyrusNajmabadi [Please don't be serious about that.](https://github.com/dotnet/roslyn/issues/5883#issuecomment-153800104)

@2bhuinianhua I highly disagree that your version B is easier to read (which is very important as code is read several orders of magnitude more than it is written). However, you can do the following *today*, without even a single `continue` statement, and I find it to be much more understandable than your proposed syntax:
```cs
bool condition = true;
for (int i = 0; condition && i < 10; i++)
{
　　for (int j = 0; condition && j < 10; j++)
　　{
        if (j == 5)
            condition = false;
　　}
}
```

**Comment by canton7** [comment]
That falls down if you have foreach loops however.

**Comment by 2bhuinianhua** [comment]
I have given the simple edition,so you don't understand.@Joe4evr
I give the full edition.
For Code-B:
```
//do something
for (int i = 0; i < 10; i++)
{
　　//do something
　　for (int j = 0; j < 10; j++)
　　{
　　　　bool condition = true;
　　　　//do something
　   　   //Maybe , condition change
　　　　if (condition)
　　　　　　doublecontinue;//①Just one statement
　　　　//do something
　　}
　   //do something
　   //do something
}
//do something
```
For Code-A:
//do something
for (int i = 0; i < 10; i++)
{
　　//do something
　　bool continueFlag = false;//①
　　for (int j = 0; j < 10; j++)
　　{
　　　　bool condition = true;
　　　　//do something
　　　　if (condition)
　　　　{
　　　　　　continueFlag = true;//②
　　　　　　break;//③
　　　　}
　　}
　　if (continueFlag)//④
　　　　continue;//⑤
　　//do something
　　//do something
}
//do something

**Comment by 2bhuinianhua** [comment]
> That falls down if you have foreach loops however.
What?
If foreach,Code-A will be like:

List<int> ls = new List<int>();
//do something
foreach (var i in ls)
{
　　//do something
　　bool continueFlag = false;//①
　　for (int j = 0; j < 10; j++)
　　{
　　　　bool condition = true;
　　　　//do something
　　　　if (condition)
　　　　{
　　　　　　continueFlag = true;//②
　　　　　　break;//③
　　　　}
　　}
　　if (continueFlag)//④
　　　　continue;//⑤
　　//do something　　
}

**Comment by canton7** [comment]
@2bhuinianhua I was responding to @Joe4evr

**Comment by eyalsk** [comment]
@2bhuinianhua 

> Don't say "goto" or subfunction to me , that's bad.

Not in all circumstances and this is one of the scenarios where it's not bad at all, it's just right.

**Comment by theunrepentantgeek** [comment]
> Don't say "goto" or subfunction to me , that's bad.

Why not? Why deliberately exclude language features that already exist that allow you to solve this problem in straightforward fashion?

In the vast majority of situations, nested loops are a code smell, highlighting something that needs to be refactored into a separate method. My experience is doing so almost always reveals edge cases that hadn't been considered, resulting in code with fewer defects that's easier to read.

In the remaining cases, use of the **goto** keyword not only solves the problem in a simple way, but the presence of such a rarely used feature of the language encourages readers to consider the nested loop carefully.

Regrettably, Edgar Dijkstra's original paper [_Go To Statement Considerered Harmful_](https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf) is extremely dense reading; As I recall, the consensus that emerged from the debate surrounding his paper was that ill-disciplined use of Go To was the problem, especially non-local use. 

Also, note that the original development process for C# was _**not**_ to take C++ and take things out, but to start with a very simple language and add in features that were useful. C# includes **goto** statement quite deliberately; it's not simply a feature of another language they forgot to remove.

**Comment by CyrusNajmabadi** [comment]
Proposal started here: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-15.0/labeled-break-continue.md
Championed Issue here: https://github.com/dotnet/csharplang/issues/9875
Discussion here: https://github.com/dotnet/csharplang/discussions/9876

Closing this out to move discussion there.
