### ISSUE TITLE
Params - allow trailing comma

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3512]
When I have a method that accepts a params argument, please allow me to provide a trailing comma in the arg list:

````
var data = MyMethod("Something",
    Value1,
    Value2,
    Value3,
    etc,  // <- Currently that comma isn't allowed
    );

````

**Comment by dstarkowski** [comment]
Already reported here #1824

**Comment by svick** [comment]
This is a subset of https://github.com/dotnet/csharplang/issues/3512.

**Comment by 333fred** [comment]
Closing as a duplicate.
