### ISSUE TITLE
Nullable<T> doesn't have type guard

### ISSUE THREAD

**Issue by NN---** [dotnet/csharplang#3514]
Even if you compare with `null`, the compiler doesn't treat the value as non nullable.

```cs
void f(int? x)
{
   if (x != null) g(x); // Error, int? is not convertible to int
}

void g(int x) { }
```

**Comment by 333fred** [comment]
C# does not have Kotlin-style smart casting: `int?` and `int` are completely separate types and doing a cast doesn't implicitly change the type of the variable in the success branch. Instead, I'd suggest doing a pattern match, like so:
```cs
if (x is int y) g(y);
```
This will introduce a new variable that pulls the `int` out of the `int?`. We can't introduce a smart-cast-style system into C# as this would be a massive breaking change.

**Comment by NN---** [comment]
Unfortunately you cannot use `var` here since it will be treated as nullable reference.

```cs
if (x is var y) { // y is string? 
```

I would like to have some syntax for non nullable `var`:

```cs
if (x is notnull var y) { // y is string 
```

**Comment by 333fred** [comment]
You can use the `{}` pattern for this:
```cs
int? x = null;
if (x is {} y1) Console.WriteLine("not printed: x is null");
x = 1;
if (x is {} y2) Console.WriteLine("printed: x is not null");
```

If you were to run this, only the second `WriteLine` will be printed. https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUBgBjwwGYACAbzzJrI3UutuYEspgB+MgDzIF4yUCABthAbibMaLAGZkAFLxYBnSgF8yAT0wBKOpgCc8gERQA9sDIAHMG2ABTBDzIrBI4cZ0TcU2rwGY3r7ScoouqhQamuh6qIYmNnaOIM6u5pZCop5BtGp4akA==

**Comment by 333fred** [comment]
`y1` and `y2` are `int` here.

**Comment by NN---** [comment]
Thanks . Missed that syntax with variable.

Do you know if assertion syntax is planned ?
So one could write in a test

```
Assert.NotNull(x);

Now x is not null here
```

Or it breaks code for the same reason mentioned above ?

**Comment by 333fred** [comment]
```cs
void NotNull<T>([NotNull] T t) => _ = t ?? throw new ArgumentNullException();
```

Would work.

**Comment by yaakov-h** [comment]
Wouldn't that only work for reference types?

**Comment by 333fred** [comment]
Nope

**Comment by bbarry** [comment]
You can do it with 2 methods so you have the same syntax everywhere:

```csharp
class Assert {
  void NotNull<T>([NotNull] T t, out T result) where T : class => result = t ?? throw new ArgumentNullException();
  void NotNull<T>([NotNull] T? t, out T result) where T : struct => result = t ?? throw new ArgumentNullException();
}
```

used as:

```csharp
Assert.NotNull(x, out var notnullx);

// Now notnullx is not null here and is the correct type
```

Unfortunately the constraints infect the codebase and duplicate methods and classes up the stack until the types are known. I'm hoping source generators will be useful to duplicate a method and add a constraint but that will not solve the problem completely either...

**Comment by NN---** [comment]
Unfortunately this is not how NUnit defines its assert , but a nice idea.

**Comment by yaakov-h** [comment]
The canonical way in NUnit is `Assert.That(x, Is.Not.Null)` which has no way for the compiler to infer nullability no matter how many attributes you want to slap on to things.

**Comment by NN---** [comment]
> The canonical way in NUnit is `Assert.That(x, Is.Not.Null)` which has no way for the compiler to infer nullability no matter how many attributes you want to slap on to things.

But you can put in Assert.NotNull methods

**Comment by yaakov-h** [comment]
That method, along with others in NUnit’s Classic Model, are provided for backwards compatibility only.

**Comment by NN---** [comment]
I am aware of this.
And yet in 3.x I suppose you won’t remove it and maybe even in 4.x.
So why not :)
