### ISSUE TITLE
Produce an expression tree for method groups.

### ISSUE THREAD

**Issue by bbarry** [dotnet/csharplang#3519]
Suggesting this instead of commenting on #2545 because this shouldn't require any additional commitments from teams outside of the language team and should be completely compatible with existing expression tree usages.

Currently you can use method groups in place of lambda calls:

```csharp
var allowed = users.Where(IsAllowed);
```

and it works for calls expecting a compatible delegate type.

It would be nice if you could do the same for locations where the compatible expression type is used and:

```csharp
var allowed = users.Where(IsAllowed);
```

lowered to:

```csharp
var allowed = users.Where(p => IsAllowed(p));
```

 and then further lowered as this expression is today.

**Comment by eyalsk** [comment]
@bbarry What you're proposing is valid today, are you proposing to change this behaviour? and how does `p` automagically passed to `IsAllowed` I don't get it.
