### ISSUE TITLE
Non Nullable Interfaces

### ISSUE THREAD

**Issue by Frank0101** [dotnet/csharplang#3522]
Hello everyone,
given how Structs work, being a ValueType, is unlikely that they will ever allow inheritance from anything other than interfaces (https://github.com/dotnet/csharplang/issues/524).

For me the main problem with Structs inheriting from Interfaces is that the Struct is a ValueType, while the Interface is not. So by referring a Struct through an interface I lose the benefit of being sure that I can't receive NULL as value.

A fix would be to have a way for defining a special type of interfaces for which we grant that they behave as a valueType in terms of not accepting NULL

**Comment by ufcpp** [comment]
```cs
void M<T>() where T : struct, IInterface
```
?

**Comment by eyalsk** [comment]
@ufcpp I'm not totally sure because he didn't say anything about generics but based on his last statement he might mean something like this `IMyInterface foo = new MyStruct(); foo = null;` but `MyStruct foo = null` would raise an error. Also, he didn't say anything about NRT so he might be using an old version of the language or has it disabled.

**Comment by Enderlook** [comment]
Maybe he talks about something like `NonNullable<IMyInterface>`? Thought that doesn't sounds very helpful...

**Comment by Frank0101** [comment]
Thanks @eyalsk, that's exactly what I meant. Yes I'm aware of NRT but it doesn't grant a strong defence against Null values and is not yet widely used

**Comment by PathogenDavid** [comment]
Non-nullable interface references won't provide a strong defense either. When you assign a struct to an interface storage location, you are implicitly boxing it. Boxes are stored on the heap, and as such you are storing a reference to that box. Meaning it can reference nothing, or null.

Even if the runtime provides some sort of value interfaces thing, the virtual dispatch table could still be empty, making all of the method references null.

**Comment by JustNrik** [comment]
Only interfaces can inherit interfaces, classes and struct **implement** interfaces, they don't inherit them. 

Also, how would this be implemented in the first place? Like, unless interfaces were fake and the language was duck typed, structs will always be boxed since interfaces are reference types, so there's really no way to implement something like this...

**Comment by Frank0101** [comment]
@JustNrik I was talking about the fact that structs can't inherit and they can only implement interfaces, thanks for allowing me to clarify.

I would implement them as a special type of interface that behaves as a value type (and maybe can only be used with structs), so that is not possible to assign null to a reference of such type. Trying to assign null would trigger a compilation error or something like that. But don't know how complex/feasible that would be, hence i'm just dropping the idea on the table to see what you guys think.

**Comment by theunrepentantgeek** [comment]
It seems to me that Shapes (#164) and/or Roles (#1711) would achieve the goals of the OP as a side effect, and those represent design work that's already under way.

**Comment by jnm2** [comment]
> Trying to assign null would trigger a compilation error or something like that.

Sounds achievable with marker attributes and Roslyn analyzers in a way that works all the way back to C# 1.0.

**Comment by Frank0101** [comment]
> Sounds achievable with marker attributes and Roslyn analyzers in a way that works all the way back to C# 1.0.

How would this work?

**Comment by Frank0101** [comment]
@theunrepentantgeek I like both Shapes and TypeClasses, but not sure how they would solve my problem. However will check carefully. Thanks!

**Comment by jnm2** [comment]
@Frank0101 You'd make up an attribute like `[DisallowNullableReferences]` and put it on your interface definition. Then you'd write a Roslyn analyzer that errors if you try to pass null as that interface type.

**Comment by Frank0101** [comment]
> You'd make up an attribute like [DisallowNullableReferences] and put it on your interface definition. Then you'd write a Roslyn analyzer that errors if you try to pass null as an interface type marked with [DisallowNullableReferences].

As far as I've seen analyzers can only generate warnings, they can't stop the build (please don't tell me to turn on the option to error for warnings because I already know 😄  )

**Comment by Frank0101** [comment]
@jnm2 never mind, found out! https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019

Yes an analyser could work! Thanks!

**Comment by Joe4evr** [comment]
Please close if you're done with this issue. 🙃

**Comment by jnm2** [comment]
@Frank0101 As the analyzer author, you can set the default severity to any of five levels. As an end user, you can override the severity of any diagnostic ID to any of the five levels using the 'Configure severity in .editorconfig' light bulb option in VS.

**Comment by Frank0101** [comment]
@jnm2 splendid! Thank you very much!
Closing the issue
