### ISSUE TITLE
Nameof shortcut for non static members 'from(nameof(Book)) 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/csharplang#3524]
1. I have next non static classes with non static properties (known as POCO):

```
Person.Name
Person.Title
WorkRelation.Manages
Book.Title
Book.PublishedIn
```

2. I have next fluent DSL based queries:

Gremlin:
```
g.V().has("Name","gremlin").
  repeat(in("Manages")).
    until(has("Title","ceo")).
  path().by("Name")
```

cOOQ:
```
create.select("Title")
      .from("Book")
      .where("PublishedIn", eq(2011))
      .orderBy("Title")
```

3. I want to be able to write:

```
g.V().has(Person.Name,"gremlin").
  repeat(in(WorkRelation.Manages)).
    until(has(Person.Title,"ceo")).
  path().by(Person.Name)

create.select(Book.Title)
      .from(Book)
      .where(Book.PublishedIn, eq(2011))
      .orderBy(Book.Title)
```

4. Above is shortcut for:

```
g.V().has(nameof(Person.Name),"gremlin").
  repeat(in(nameof(WorkRelation.Manages))).
    until(has(nameof(Person.Title),"ceo")).
  path().by(nameof(Person.Name))

create.select(nameof(Book.Title))
      .from(nameof(Book))
      .where(nameof(Book.PublishedIn), eq(2011))
      .orderBy(nameof(Book.Title))
```

5. So DSL is "strongly typed", but with less boilerplate.

6.

**Comment by HaloFour** [comment]
Sounds like a DSL that would benefit from using LINQ expressions instead of (or in addition to) names.  Having a form of method reference syntax that only returns the name of the reference sounds like it would have virtually no use cases outside of your specific DSL scenario, especially since this is exactly why `nameof` was added to the syntax in the first place.

**Comment by dzmitry-lahoda** [comment]
> Sounds like a DSL that would benefit from using LINQ expressions instead of (or in addition to) names. Having a form of method reference syntax that only returns the name of the reference sounds like it would have virtually no use cases outside of your specific DSL scenario, especially since this is exactly why `nameof` was added to the syntax in the first place.
