### ISSUE TITLE
Shortcut for nameof/typeof in case of non static members and type names

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/csharplang#3525]
1. I have next non static classes with non static properties (known as POCO):

```
Person.Name
Person.Title
WorkRelation.Manages
Book.Title
Book.PublishedIn
```

2. I have next fluent DSL based queries:

Gremlin:
```csharp
g.V().has("Name","gremlin").
  repeat(in("Manages")).
    until(has("Title","ceo")).
  path().by("Name")
```

cOOQ:
```csharp
create.select("Title")
      .from("Book")
      .where("PublishedIn", eq(2011))
      .orderBy("Title")
```

3. I want to be able to write:

```csharp
g.V().has(Person.Name,"gremlin").
  repeat(in(WorkRelation.Manages)).
    until(has(Person.Title,"ceo")).
  path().by(Person.Name)

create.select(Book.Title)
      .from(Book)
      .where(Book.PublishedIn, eq(2011))
      .orderBy(Book.Title)
```

4. Above is shortcut for:

```csharp
g.V().has(nameof(Person.Name),"gremlin").
  repeat(in(nameof(WorkRelation.Manages))).
    until(has(nameof(Person.Title),"ceo")).
  path().by(nameof(Person.Name))

create.select(nameof(Book.Title))
      .from(nameof(Book))
      .where(nameof(Book.PublishedIn), eq(2011))
      .orderBy(nameof(Book.Title))
```

5. So DSL is "strongly typed", but with less boilerplate.

6. `nameof` can be dropped in case when parameter is `string`

7. Writing as in 3 could be possible if parameters are `Type`. `typeof` is to be omitted in this case.

8. Yet another modern query language DSL example:
```csharp
Value value = await client.Query(Get(Ref(Collection(nameof(Product)), "123456789")));
```
```csharp
Value value = await client.Query(Get(Ref(Collection(Product), "123456789")));
````

9. I believe there are more cases for typeof/nameof simplification - not only query DSLs.

**Comment by dzmitry-lahoda** [comment]
From @HaloFour 
> Sounds like a DSL that would benefit from using LINQ expressions instead of (or in addition to) names. Having a form of method reference syntax that only returns the name of the reference sounds like it would have virtually no use cases outside of your specific DSL scenario, especially since this is exactly why `nameof` was added to the syntax in the first place.

**Comment by dzmitry-lahoda** [comment]
I have mentioned 3 query DSLs. There are orher DSLs, for example container registrations or ElasticSearch terms indexing. Parameters could get name or type. LINQ looks weird for Gremlin, Fauna and rich SQL queries. May be some other rich query languages. I talking about case without code generation tooling, unlike in Entity Framework. Also I am talking about the case to avoid many '=>'  when it prevents easy reading of queries. Mentioned DSL are mid form beetwin expressions and pure strings, usually filled with adhoc query builders.

**Comment by dzmitry-lahoda** [comment]
@HaloFour could you please explain 'especially since this is exactly why nameof was added to the syntax in the first place'? Thanks

**Comment by HaloFour** [comment]
@dzmitry-lahoda 

`nameof` was added to the language specifically to get the name of a variable or member.  Having the lack of `nameof` also do the same thing would add confusing duplicity to the language.  The suggested syntax, `M(Person.Name)` is already legal C#.

If you have POCO representations of objects for these DSLs than the use of expressions is perfectly reasonable.  And you don't have to buy into the LINQ-syntax, any method can work with expressions just by accepting a parameter of `Expression<T>` where `T` is a delegate, and that expression can be inspected for members and the names of those members extracted.  Every single one of those DSLs above could be designed to take advantage of expressions without changing their structure much.

**Comment by dzmitry-lahoda** [comment]
1. LINQ book example is of `book => book` noise. And example is most simple possible SQL statement. Except that most simplest case is already not so pretty, it does not scale (see references queires next) to more complex queries well. 
2. Entity Framework is state of the art LINQ provider, but I yet to see any example of complex query like these https://blog.jooq.org/2016/04/25/10-sql-tricks-that-you-didnt-think-were-possible/ to be expressed in LINQ or in fluent LINQ modes with expressions in EF. While SQLAlchemy and jOOQ can express these with ease.
3. If try to push `expressions` to limit we will get something as `=>` noisy as NEST (see example in the end for simple NEST query with `ff => ff` https://stackoverflow.com/a/31070948/173073). While with simplified `nameof` we could be better.
4. ElasticSearch has JSON API which of its own noise and lack of typing. NEST has `expression free` low level object builder DSL. I think with shortcuts for `nameof` and `typeof` there is room of 3rd kind of API.
5. Add here that in some cases field names has non C# compatible semantics, easy to express as string, need more extensibility and attributes for expressions which are not visible if you steer at LINQ query and need support from provider. Need to check POCO attributes, while could use pure strings for such cases. 
5. Expression must be parsed - which takes time during runtime. And expression can express any function, which is not so well typed API either - fails in runtime.
6. One case of possible feature conflict is static properties, but this are out of proposal.
7. Another case is conflict with `this.Book.Name` when `this.` is omitted. But for that kind of conflict one should put query code into POCO class. Which is not expected. 
8. What are other possible conflicts with existing method parameters? When user could misuse value instead of name.
9. For gremlin query like these `sting based typing` is sane approach, i doubt it is possible to be sane in `x => x`:

```csharp
g.V().has(label, 'composite').
                local(
                match(
                        __.as('the_composite').out().
                                        or(
                                        __.in('use').has(id, 'joe'),
                                        __.out('upto').in('use').in('role').has(id, 'joe')
                                ).store('in_the_user'),
                        __.as('the_composite').
                                where(
                                        __.out().where(without(
                                                'in_the_user'
                                        )).count().is(0)
                                ).
                                store('owned')
                ).select('owned')
        )
```
I see how better it will be with simplified nameof, but using expressions with => will make things much more ugly.

**Comment by dzmitry-lahoda** [comment]
Alternatives to this feature:
1. One was rejected proposal to have symbol prefix instead of nameof. It was rejected, one of argumens was usage of &

**Comment by dzmitry-lahoda** [comment]
Another alternative.
When I type:
```csharp
Book b;
g.where(b.Title, eq("Gremlin")).select(b.Date)
```
`where` and `select` both accept generic struct `NameValue<T>` which contains `Name - name of property of string; Value of type T`. 

Not sure how to find such proposal. What name would be for it?

**Comment by HaloFour** [comment]
@dzmitry-lahoda 

You don't need to write a LINQ provider to use expressions.

Here's an example that uses an expression to get the name of a member:

[SharpLab](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACOSB0AMgJZQCO+AogB4AOYApgM5PED2UTA3OunAMy4E2AEJs2Aa2wBvdNnm5BeHABViwADYMZ2AOYNgXbEwNGAvugtpeGJcIDCMuQoG4kANjc4AsgwC2AEYMYAByAIZ+DAA8KgA02CoASgB8ABQ09MysHFFwAKwx8UnJydgMdIws7FAAlE5oCo3YAG5hYNiRgcEZldlQ2AC82Km+XWA9WdV15ZlVHPhiACYAnjwNTfJwAOwd/kHjFZPzo/v44ZFrjVaNzpsIwrLrG63tUBHaQyfB5wypqWKSbABcQSOoDUrAyT4NSaBg1S4bNwATlSb0i8Nu2CsZiAA===)

You can see in it's simplest form this is painfully easy to write.  These are the idiomatic ways to approach DSLs like this.

> One was rejected proposal to have symbol prefix instead of nameof. It was rejected, one of argumens was usage of `&`

`&` is already a reference pointer in C#, so that was never going to be considered as a serious alternative.  `nameof` is a much better syntax for obtaining the name of a member.  It tells you exactly what it does.  And given the more verbose form was what the team decided upon for this syntax it's very, very unlikely that any other form will be considered, especially to optimize around Stringly-typed DSLs.

And, IMO, a prefix form is _much_ uglier than either `nameof` or lambda expressions.  Trying to make code terser does not make it more readable.  Generally the exact opposite is true.

**Comment by dzmitry-lahoda** [comment]
> And, IMO, a prefix form is much uglier than either nameof or lambda expressions.

May be simple example?
Like `select(book => book.Title)` and `select(nameof(Book.Title))`  are way better than `select(Book.Title)`?

> Trying to make code terser does not make it more readable. Generally the exact opposite is true.

It is too generic statement. Sometimes yes, sometimes not. Why would C# add so much sugar to make object initializers and auto immutable properties? You state that these features do make code `less readable`? I bet you not - so your statement cannot be used as argument as it is essence.

Please look at examples of NEST and Gremlin queries. I see them as ugly if to make this `=>` based - and they are.

Also, I am not only for to be terse,  but for be little more typed. Proposal suggests to replace string literals with strings from type system.

**Comment by dzmitry-lahoda** [comment]
Thanks for referencing example on SharpLab - good one. My PRs are in `ExpressionToCode` and in `FastExpressionCompiler`, and I did custom LINQ to ES query provider - so I have good understanding what `expressions` are from these expriences.

**Comment by HaloFour** [comment]
> `select(Book.Title)`

That is already legal C# syntax, so you're not going to get that.  I find `select($(Book.Title))` to be much uglier than `select(nameof(Book.Title))`, especially since it doesn't remotely inform you of what it's doing.

> Why would C# add so much sugar to make object initializers and auto immutable properties?

Because these are _very_ commonly used.  Stringly-typed DSLs are not, and even when they are you already have C# syntax candy for working with them, `nameof`, which works perfectly fine.  You're asking for duplicate syntax for an existing feature to optimize around an uncommon use case and specifically for stylistic reasons.  That's not a good reason to add a feature to a language.

**Comment by dzmitry-lahoda** [comment]
```
select(`Book.Title`) 
```
? 

May be fluent style integration DSLs are not so common, but `nameof` and `=>` are not `perfectly` fine IMHO.

**Comment by dzmitry-lahoda** [comment]
@HaloFour or next variant
```
class Book {
  string Title;
}
Book r;
select(r.Title) //
select<T>(ParamInfo<T> paramInfo)
struct ParamInfo<T> // T is string in our case
{
  string NameOf;
  // next optional if there is a case - property info, value of type T, type info (book) or second type parameters of K (Book in the case)
}

// and untyped version
select(ParamInfo paramInfo)
struct ParamInfo {
  string NameOf;
// optional PropertyInfo, type of instance on which property is called, 
}
```
So any property passed into `param info` method wraped into relevant type and name metadata? Similar to hacks done for format string and spans, etc.  But declaring `Book r` is weird. But having internal function with query inside allows for `BookQuery(Book book = default, ...)`. Some kind of non instantiated instances. I guess there could be proposal for this either somewhere.

**Comment by HaloFour** [comment]
@dzmitry-lahoda 

> May be fluent style integration DSLs are not so common, but `nameof` and `=>` are not perfectly fine IMHO.

We're going to have to disagree here.  These existing features are not only "perfectly fine", but they're also canonical and idiomatic.  Plenty of DSLs, especially query DSLs, are designed around these features.

> `select(r.Title)`

Again, already legal syntax, and already means something completely different.  The syntax you want cannot use existing grammar without being ambiguous or changing the meaning of existing source.  There's no reason to expect that something that looks like a property accessor should be anything other than a property accessor.

**Comment by dzmitry-lahoda** [comment]
I meant sugar for next code:
```
Book book;
select<string>(new ParamaInfo { Nameof = nameof(book.Title), Value = book.Value})
// so i have explcitly code method to accept ParamInfo to get sugar
```

It is property accessor + nameof. Like caller member name on this instance of extension.

**Comment by HaloFour** [comment]
Check this proposal out:  https://github.com/dotnet/csharplang/issues/287

**Comment by dzmitry-lahoda** [comment]
Seems 287 can be properly abused, but still need to create dummy variable instead of being more clean with
```
`Book.Title`
```
