### ISSUE TITLE
Proposal: Functions as first-class citizens through syntactic sugar

### ISSUE THREAD

**Issue by Moke-RS** [dotnet/csharplang#3532]
### Background

Delegates are objects  which represent a method and, optionally, the "this" object associated with that method. It can be passed to methods, and a reference to it can be stored in a structure or class. 

Delegates are very useful but not so convenient to write and use. Then, when .Net Framework 3.5 was released, it came with 3 special delegates: Action, Func and the less known Predicate.

They came to make it easier to write and use delegates, as in:

`Func<int, int> MultiplyByTwo = (number) => number * 2;`

A quick search through current proposals though is enough to see that despite being easier to use than delegate statements, they are still not the perfect solution. Action's and Func's with 5 parameters or more are really hard to read and write, and lack some "features" of real functions as naming parameters for example.

### Proposal

My proposal is to be able to transform any function in a first-class citizen, at least syntactic  sugar-wise, by adding a modifier to the function declaration.

Example:

_Let's say that we have this function which calculates a discount:_

`public int CalculateDiscount(int value, DiscountRule rule, bool isPartner) { ... }`

and let's say we want to transform it into a first-class function (kind of) so we can pass it as a parameter to another function or store in a variable or return it as a result of another function.

_Then when we add a special modifier:_

`public _modifier_ int CalculateDiscount(int value, DiscountRule rule, bool isPartner) { ... }`

_the compiler would interpret it as_ 

`public Func<int, rule, bool, int> CalculateDiscount  = (value, rule, isPartner) => { ...  }`

I don't know yet how to call this modifier. I had thought in _ref_ as in "we can reference this function so ref" but _ref_ already exist as a function modifier and it is used for another purpose.

Instead of a word it could be a handle:

`public int $CalculateDiscount(int value, DiscountRule rule, bool isPartner) { ... }`

### Overloads

One special situation is when there is a function overload. In this case the compiler would need to be smart enough to know which function is being referenced through the parameters being used.

**Comment by HaloFour** [comment]
What problem does this proposal solve?  It's already pretty trivial to pass a method group as a delegate parameter.  When and where would you use these automatically created delegate instances?  And what would you do if you actually wanted to pass them to a method that accepted some other nominal delegate type?

**Comment by Moke-RS** [comment]
You're right. 

I was trying to figure it out how to make it easier to use as first-class citizens but it does not solve the problem of passing them as parameter to  a method that accepted some other nominal delegate type, as you correct pointed out. 

I will close this.
