### ISSUE TITLE
Memory allocation of empty string on managed heap

### ISSUE THREAD

**Issue by stulzq** [dotnet/csharplang#3533]
Hello.

Today I saw someone dump analyzing C# code，found empty string takes up 32 bytes.  On 64-bit systems, .NET Core 3.1, the reference takes up 8 bytes.  My question: how is the 24 bytes allocated on the managed heap? I can't understand why 24 bytes are allocated. Thanks.

My test code, calculate the size of the empty string occupied on the managed heap:

````csharp
public static void Main(string[] args)
{
    Console.WriteLine(SizeOf(string.Empty));
}

static long SizeOf(object obj)
{
    if (obj == null) return 0;
    try
    {
        using MemoryStream stream = new MemoryStream();
        new BinaryFormatter().Serialize(stream, obj);
        return stream.Length;
    }
    catch
    {
        return -1;
    }
}
````

Output: 24

**Comment by benaadams** [comment]
```
Type layout for 'String'
Size: 8 bytes. Paddings: 2 bytes (%25 of empty space)
|======================================|
| Object Header (8 bytes)              |
|--------------------------------------|
| Method Table Ptr (8 bytes)           |
|======================================|
|   0-3: Int32 _stringLength (4 bytes) | // 0
|--------------------------------------|
|   4-5: Char _firstChar (2 bytes)     | // null terminator
|--------------------------------------|
|   6-7: padding (2 bytes)             |
|======================================|
```
8 bytes + 8 bytes  + 8 bytes = 24 bytes

However `string.Empty` will only be allocated once no matter how many times its used.

**Comment by stulzq** [comment]
@benaadams Thank you for your answer, it is very helpful to me.

**Comment by CyrusNajmabadi** [comment]
In general, questions like this can go to gitter.im/dotnet/runtime.  THanks!
