### ISSUE TITLE
[Proposal] `var` declaration "anywhere" in a method

### ISSUE THREAD

**Issue by pmunin** [dotnet/csharplang#3536]
There is common pattern when developers use class representing method arguments. E.g. [EventArgs](https://docs.microsoft.com/en-us/dotnet/api/system.eventargs).

Pretty common situation, when those classes contain R/W properties or fields (i.e. output arguments) - e.g. [FillErrorEventArgs.Continue](https://docs.microsoft.com/en-us/dotnet/api/system.data.fillerroreventargs).

Currently developer needs to write this:
```
var args = new FillErrorEventArgs { ... };
myComponent.OnFillError(this, args);
return args.Continue;
```
It would be nice if a Developer can declare var args in the method parameter instantiation, i.e.:
```
myComponent.OnFillError(this, var args = new FillErrorEventArgs{...});
return args.Continue;
```

Also why not to allow declare vars anywhere in the method? E.g.:
```
if(var cond1=CalculateCondition1())
{
//Handle Condition1
}
...
if(var cond2=CalculateCondition1())
{
//Handle Condition2
}

return cond1 && cond2;
```
or
```
while(var cond1 = CalculateCond1() || var cond2 = CalculateCond2() )
{
// if(cond1) ...
// if(cond2) ...
}
```

PS: Currently developer can declare vars using following ways:
1) local variable `var myVar = ...`
2) out parameters e.g. `dictionary.TryGetValue(key, out var myVar)`
3) `using(var myVar=...)` (scoped to using block)
4) `for[each](var myVar=...` (scoped to the for[each] block)

**Comment by ufcpp** [comment]
dup of https://github.com/dotnet/csharplang/issues/973

**Comment by leandromoh** [comment]
I think lines/statements will get even longer, what difficutls understand the code.
in your example line size duplicated.

**Comment by 333fred** [comment]
Closing as a duplicate.

**Comment by theunrepentantgeek** [comment]
FWIW, the OP omitted pattern matching as a way to declare variables.

If you really want to use this style of ultradense and difficult to read code, you can pretty much do it already using patterns:

``` csharp
if (CalculateCondition1() is var cond1)
{
    // Handle Condition1
}
...
if (CalculateCondition1() is var cond2)
{
    // Handle Condition2
}

return cond1 && cond2;
```

or

``` csharp
while (CalculateCond1() is var cond1 || CalculateCond2() is var cond2)
{
    // if (cond1) ...
    // if (cond2) ...
}
```

**Comment by pmunin** [comment]
@theunrepentantgeek 
Unfortunately none of your examples work.  `CalculateCondition() is var cond` always returns true (even when `CalculateCondition()` returned false.

https://dotnetfiddle.net/CqQyxZ

I guess the real workaround could be `CalculateCondition1() is var cond1 && cond1` - but this would indeed make code look ugly and less readable.
