### ISSUE TITLE
Fields lazy initialization

### ISSUE THREAD

**Issue by NN---** [dotnet/csharplang#3539]
Today you must either always initialize or add your own method to wrap initialization.

The intent is to create an object only when there is a usage like adding new elements to list.

```cs
class A{

public readonly List<int> lst = new List<int>();

}

new A().lst.Add(1);
```

Or 

```cs
class A{

public readonly List<int> lst ;

void Add(int v){
(lst ??= new List<int>()).Add(v);
}

}

new A().Add(1);
```

It would be nice to have some syntax with lazy initialization , e.g. `ref this` extension method or anything else.

**Comment by Joe4evr** [comment]
This would be solved by #140:
```cs
public List<int> lst => field ??= new List<int>();
```

**Comment by NN---** [comment]
It is not the same.
In your example the list is created when anyone calls getter.
I want it to be created only when anyone wants to call an Add or any other method.

**Comment by Joe4evr** [comment]
> I want it to be created only when anyone wants to call an Add or any other method.

![](https://i.imgur.com/jks6Qqr.png)

**Comment by NN---** [comment]
Currently any solution has an overhead of creating an object even if it will not be used.

Option with getter is not good enough since it is sufficient to me to serialize `null` and not create an empty object.

**Comment by theunrepentantgeek** [comment]
@NN I think you need to augment the OP with details of _exactly_ what you expect the compiler to do. At the moment it's lacking in definition. 

I can see maybe a dozen different ways that the compiler could implement some form of lazy instantiation (with differences in behaviour due to locking, async vs thread support, exception management, timing of creation, visibility of side effects, uniqueness, etc), but I want to hear what *you* have in mind.

**Comment by Joe4evr** [comment]
> Currently any solution has an overhead of creating an object even if it will not be used.

I don't know what you're thinking, but that's an outright lie: The expression `field ??= new List<int>();` will keep the backing field `null` if it isn't used, which is exactly what say you want.

**Comment by HaloFour** [comment]
@NN--- 

You can use this: https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1?view=netcore-3.1

What you're asking for can't be accomplished at the language level.  A `List<int>` can only ever be `null` or a valid instance of `List<int>`.  It's not possible for it to be `null` _until_ you try to call a method on it in which case it automagickally becomes allocated.  You'd need some kind of abstraction for that, like `Lazy<T>`.

**Comment by Joe4evr** [comment]
> You'd need some kind of abstraction for that, like `Lazy<T>`.

Or its allocation-free alternative: [`LazyInitializer.EnsureInitialized`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.lazyinitializer.ensureinitialized?view=netcore-3.1#System_Threading_LazyInitializer_EnsureInitialized__1___0__).

Or `??=`.

**Comment by NN---** [comment]
@HaloFour Right. It means that it can be only a runtime feature.

Thank you all.
I do understand why people are confused and disagree but having a field always initialized or always created on getter in some cases is a premature pessimisation.

**Comment by Joe4evr** [comment]
> having a field always initialized or always created on getter in some cases is a premature pessimisation.

You asked for a way to not create an object until you start using it, so subsequently rejecting the various ways that you can accomplish that exact goal is what's causing the confusion.

**Comment by HaloFour** [comment]
@Joe4evr

> Or its allocation-free alternative: LazyInitializer.EnsureInitialized.
> Or ??=.

In this case the ask seems to be that the value returned by the property remain lazy until it is first used, e.g. a method is called on it.  So those mentioned solutions don't fit the bill, you'd need `Lazy<T>` is something like it.

**Comment by jnm2** [comment]
Lazy\<T> would be equivalent to LazyInitializer.EnsureInitialized or ??=, guarding access to the actual instance by creating it on first access.

The List\<T>.Add method itself already lazily allocates an internal array inside the List\<T> only on the first call if I remember right, so I think the system is already operating the way @NN--- would want.

**Comment by HaloFour** [comment]
@jnm2 

> Lazy<T> would be equivalent to LazyInitializer.EnsureInitialized or ??=, guarding access to the actual instance by creating it on first access.

Except that this initializes the `List<T>` on first access to the property, not on the first use of the `List<T>`, which is explicitly what this proposal is requesting.

> The List<T>.Add method itself already lazily allocates an internal array inside the List<T> only on the first call if I remember right

Depending on the constructor used, yes it does, but that wouldn't apply to any and all other possible types that someone might want to use a feature like this (or `Lazy<T>`) with.

**Comment by jnm2** [comment]
> Except that this initializes the `List<T>` on first access to the property, not on the first use of the `List<T>`, which is explicitly what this proposal is requesting.

@HaloFour There is an equivalence between first access to the property and first access to the Lazy\<T>.Value property. I can't think of a reason to access the property without initializing that wouldn't translate into a need to access Lazy\<T>.Value anyway.

**Comment by eyalsk** [comment]
From the language standpoint types are mostly a black box so the only option is either to wrap the type or use `??=`, alternatively, implement your own version of the type to make it as lazy as you need.

**Comment by HaloFour** [comment]
@jnm2 

> There is an equivalence between first access to the property and first access to the Lazy<T>.Value property.

Not if the property is returning `Lazy<T>` (or something that behaves like `Lazy<T>`), which is explicitly what the poster of this proposal is requesting.

**Comment by jnm2** [comment]
I see, so what Lazy<T> gives is the ability to share out the "reference" to the list before it is allocated and used.

In the case of List<T>, this is already happening under the covers without needing an additional Lazy<T> allocation. But in the general case you would need a separate allocation to share out the "reference" before instantiating.
