### ISSUE TITLE
Proposal: nameof expression for generics without type

### ISSUE THREAD

**Issue by petarpetrovt** [dotnet/csharplang#3543]
**Proposed syntax:**
`nameof(Dummy<>.PropertyName)`
`nameof(Dummy<,>.PropertyName)`

**Current alternative:**
`nameof(Dummy<int>.PropertyName)`
`nameof(Dummy<int, int>.PropertyName)`

**Benefits:**
Simplicity and readability (syntactic sugar).

**Risk:**
idk

**Comment by yaakov-h** [comment]
Duplicate of #702.

**Comment by petarpetrovt** [comment]
@yaakov-h oh yeah sory
