### ISSUE TITLE
[Proposal] Implicit and automatic implementation of Deconstruct function in records of C #9.0

### ISSUE THREAD

**Issue by tarikguney** [dotnet/csharplang#3545]
Implicit and automatic implementation of `Deconstruct` method in classes or at least in C# 9.0 records would help to increase the adoption of Deconstruct semantics among the language users by making it more easily accessible without the extra code. All of the public properties of a data class can automatically be converted to deconstructables. Any thoughts on this?

**Comment by HaloFour** [comment]
@tarikguney 

Records with a primary constructor will automatically get a Deconstruct method.  Those without a primary constructor will not as there is no inherent order of members within a type and reordering member declarations should not result in breaking code.

**Comment by hez2010** [comment]
I don't see the reason for limit deconstruct to primary constructor only.
Actually you can create Deconstruct() for every constructor.

```charp
using System;
public class C {
    private int x;
    private int y;
    private int z;
    public C(int x, int y) { ... }
    public C(int x, int y, int z) { ... }
    public void Deconstruct(out int x, out int y) { ... }
    public void Deconstruct(out int x, out int y, out int z) { ... }
    
    public void M() {
        var x = new C();
        var (a, b) = x;
        var (c, d, e) = x;
    }
}
```

**Comment by YairHalberstadt** [comment]
@hez2010 constructor parameters don't necessarily correspond to fields or properties, so I don't see how that would work.

**Comment by HaloFour** [comment]
@hez2010 

> I don't see the reason for limit deconstruct to primary constructor only.
> Actually you can create Deconstruct() for every constructor.

Primary constructors result in public members being exposed for every parameter, so there is a built-in one-to-one relationship between the parameters and properties that the compiler can expect, and it is known that those values will be publicly accessible.  For regular constructor parameters none of this is the case.

**Comment by hez2010** [comment]
@YairHalberstadt 
> constructor parameters don't necessarily correspond to fields or properties

uhhh sorry, I forgot that 😄

**Comment by 333fred** [comment]
As @HaloFour has pointed out, this is covered by existing proposals. I'm closing this as a duplicate.
