### ISSUE TITLE
[Proposal] "friend" modifier + "friend" keyword (A c# style implementation, not like c++)

### ISSUE THREAD

**Issue by giovani-luigi** [dotnet/csharplang#3549]
### Summary: 

Introduce the friend access modifier, allowing to create certain object composition
where the contained objects have access to some container functionality that is
not exposed outside the container.

### Motivation:
Sometimes we want to provide functionality only to instances that we trust.
Through the protected access modifier we only can achieve that only by inheritance.

I know that this has been suggested other times, but I am presenting a way of making it
somewhat safer than other implementations.

		
### Goal:

The goal is to make fields from a class available to the objects inside of 
it, without exposing them to the outside world. As in the example, sometimes we 
want to expose a functionality to instances contained inside the class, but we
don't want to allow anyone else to use that functionality. In the example, `john` and 
`anne` can shutdown the alarm system in the House. But from outside, no one should 
be able to.
	
This is very useful in breaking down a big class in components, and delegating
responsibilities to these components. The container has functionality that you
want to share between contained instances, but you do not want to expose to
other objects that are not friends with the container.
	
### Proposal:

	Introduce the "friend" access modifier together with the friend keyword constraint
	when passing a parameter, so an object can only be passed as friend.
	
### Example:
```
public class House{

	public Resident _john = new Resident(friend this);
	
	public Resident _anne = new Resident(this); // error! parameter must be passed as friend
	
	friend void ShutdownAlarm() {
		// shutdown the alarm of the house
	}
}

public class Resident {	
	
	friend House _house;
	
	public Resident(friend House house){
		_house = house;
	}	

	private ShutdownAlarm() {
		_house.ShutdownAlarm();	// ok!
	}
	
}

public class Main{

	var house = new House();
	
	house.ShutdownAlarm(); // error! not accessible
	
}

```

**Comment by HaloFour** [comment]
#2073

**Comment by svick** [comment]
I'm confused about this line:

```c#
friend House _house;
```

Does this mean that `_house` is exposed to the friends of this class or that this class can access `friend` members of `_house`?

**Comment by giovani-luigi** [comment]
It means that the `_house` instance of `House` has privilege to access `friend` members of `House`. The access modifier there was implicit (private) but there is room for ambiguity as you noticed. I initially realized that, but did not think further about this ambiguity. 

There are some ways to solve it... 
It may be that the syntax of that particular declaration should be changed. The compiler will need a way to tell whether that instance has access to the friend fields after initialization, for example, if I change the assignment after initialized. The compiler needs to prevent non-friend assignments. I used the access modifier (probably incorrectly) to inform this. 

Possibility **no. 1**:
It could be enough just to move the keyword to the other side of the type like: 
`private House friend _house;` 

in this case the instance is private to the class, but requires "friend" assignments. (I would try to keep as close as possible from current features of the language). 
The ambiguity case in previous example, now would look like: `friend House friend _house;`

**Comment by bigredd0087** [comment]
I don't understand how this doesn't expose private internals to the outside world. If I mark the field in my class with friend then don't I have access to all of its private members? Looking at your example it seems like anybody could create a House and as long as they mark the field that they store it in as friend then they have access the private internals.

**Comment by giovani-luigi** [comment]
> I don't understand how this doesn't expose private internals to the outside world. If I mark the field in my class with friend then don't I have access to all of its private members? Looking at your example it seems like anybody could create a House and as long as they mark the field that they store it in as friend then they have access the private internals.

No, you misunderstood the proposed usage of keyword and constraint. Both parties are aware of the "friend" relationship, during the assignment. Also, only "friends" are visible, private remain private no matter what.

**Comment by jnm2** [comment]
> Introduce the fiend access modifier

Missing an 'r' there

**Comment by bigredd0087** [comment]
In your example what keeps Main from declaring house a friend and then having access to ShutDownAlarm?

**Comment by giovani-luigi** [comment]
> In your example what keeps Main from declaring house a friend and then having access to ShutDownAlarm?

Nothing, but I understand your point. My idea is based in that the contract is built in initialization and assignment. Therefore if someone handles the instance to you that is not friend, then you cannot access friend members. In your example you own the instance, so you can do whatever you need, including accessing its friend members. I would rather have a better protection too as you suggested in your example, but this implementation doesn't cover that. Any suggestions perhaps?

**Comment by bigredd0087** [comment]
Nested types provide access to all members of the containing type. No language changes needed.
