### ISSUE TITLE
Proposal: Allow Changing the Return Type of a Virtual Method/Property to Derived Type

### ISSUE THREAD

**Issue by ChayimFriedman2** [dotnet/csharplang#3553]
Often, we have a base class (or interface) with a virtual property of some type, or virtual method of some type.

But in the derived classes, we know more. We know that the type will always be a specific, derived type of the one declared in the base class.

When dealing with the API through the base class, there is no problem. We must be general enough to handle all cases.

But sometimes, we deal directly with the derived's API. And we want functionalities special to the derived type. Now, a redundant cast is needed in C# today.

An example will clarify (inspired by Roslyn):

We have two supported languages: C# and VB. There is an abstract `SourceCode` class, which has a `Compile()` method, returns a `SyntaxTree`. C#'s one is called `CSharpSourceCode` and returns a `CSharpSyntaxTree`, while the one of VB is called `VisualBasicSourceCode` and returns `VisualBasicSyntaxTree`.

OK. Now, we've realized that C# was added support for source generators, while VB not (yet, I hope 😉). And we want to have a simple way to see whether an AST is affected by some source generator. So, we added a method `bool IsAffectedBy(SourceGenerator generator)`. Alright.

I'm an end user. I'm compiling a C# program, and want to see if a source generator is affecting it. So I try the following code:

```c#
var code = new CSharpSourceCode(@"System.Console.WriteLine(""Hello C#""!");
var ast = code.Compile();
Console.WriteLine($"My little program is {ast.IsAffectedBy(myCoolGenerator) ? "" : "not "}affected by my cool source generator.");
```

Of course it won't compile. And I'm asking: why? We **DO** know that we'll always have `CSharpSyntaxTree`. If nothing magical happen, there's no way around. Why can't we tell the compiler "Hey, did you see this method? Yeah, I know that in the base class it returns `SyntaxTree`, but trust me, here it will never return something other than `CSharpSyntaxTree` (of course don't just trust me - check me). Don't worry, they're compatible - CSharpSyntaxTree is a subclass of `SyntaxTree`". Or in a little more formal way, why can't we change the return type of `CSharpSourceCode.Compile()` to the subclass `CSharpSyntaxTree`?

Fortunately, there's still hope ❤️. We can add this to the language! I'm not sure whether this will require changes in the CLR, hope and think that not. But if yes, we can add this to #3170, at least.

**Comment by HaloFour** [comment]
https://github.com/dotnet/csharplang/issues/49

**Comment by CyrusNajmabadi** [comment]
Closing as dupe.  Covariant returns are also planned and in progress for a near-term release of C#.

**Comment by ChayimFriedman2** [comment]
I didn't find the right word, covariance. Even the examples are same!...
