### ISSUE TITLE
switch expressions are unable to return ref - inconsistent behavior with ? operator

### ISSUE THREAD

**Issue by AJosephsen** [dotnet/csharplang#3559]
I am able to do the following with the ? operator
`(lowerBound < upperBound ? ref lowerBound : ref upperBound) = mid;`

But not with the switch expression
```
(lowerBound < upperBound ) switch
{
	(true) => ref lowerBound,
	(false) =>ref upperBound,
} = mid;
```

This seems inconsistent

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/3326.

**Comment by AJosephsen** [comment]
You are right
This is a duplicate of #3326.
