### ISSUE TITLE
Proposal: switch on System.Type

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#356]
@alrz commented on [Tue Jan 26 2016](https://github.com/dotnet/roslyn/issues/8194)

When it comes to runtime type comparison, [there are multiple ways to do so](http://blogs.msdn.com/b/vancem/archive/2006/10/01/779503.aspx), it's more cumbersome if you want to do it multiple times with `if else`. it would be really nice if we could literally `switch` on `System.Type` or `System.RuntimeTypeHandle` and compiler choose the fastest way, like using `TypeHandle`.

``` cs
Type type = ...;
switch(type) {
  case typeof(Foo): ... break;
  case typeof(Bar): ... break;
}
```

---

@GeirGrusom commented on [Tue Jan 26 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-175426114)

It's planned that you can [switch on type](https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md) in C# 7.

I think it will look like this:

``` csharp
switch(baz)
{
    case Foo foo:
        foo.DoFoo();
        break;
    case Bar bar:
        bar.DoBar();
        break;
}
```

---

@alrz commented on [Wed Jan 27 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-175546805)

@GeirGrusom That's not what I'm talking about.

---

@orthoxerox commented on [Wed Jan 27 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-175687563)

Well, it would be nice if types were first-class citizens, but that would require CLR support, I think.

---

@alrz commented on [Wed Jan 27 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-175688708)

@orthoxerox I even suspect that this behavior can be neatly implemented as an extension `is` operator (if that would be possible). So, no CLR support is required at all.

---

@HaloFour commented on [Wed Jan 27 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-175716309)

The CLR is fully capable of handling the logic.  The question is how such a statement should be expanded.  I'd imagine it would produce the same IL as a series of `if`/`else` statements since the IL `switch` opcode only works when the values are a range starting at 0 which the runtime type handle would not be.

``` cs
Type type = obj.GetType();
switch (type)
{
    case typeof(Foo):
        Console.WriteLine("Foo!");
        break;
    case typeof(Bar):
        Console.WriteLine("Foo!");
        break;
    case typeof(Baz):
    default:
        Console.WriteLine("Baz or Something Else!");
        break;
    case typeof(Frob):
        Console.WriteLine("Frob!");
        break;
}
```

effectively equivalent to:

``` cs
Type type = obj.GetType();
if (typeof(Foo).IsEquivalentTo(type))
{
    Console.WriteLine("Foo!");
}
else if (typeof(Bar).IsEquivalentTo(type))
{
    Console.WriteLine("Bar!");
}
else if (typeof(Frob).IsEquivalentTo(type))
{
    Console.WriteLine("Frob!");
}
else
{
    Console.WriteLine("Baz or Something Else!");
}
```

---

@alrz commented on [Wed Jan 27 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-175718455)

@HaloFour `switch` with pattern-matching already turns to mix of `if`, `else` and `switch` (at least this is what F# does). So I assume this can be done in a similar way. Also, I don't know about `IsEquivalentTo` but comparing `TypeHandle` causes no type load and will be emitted directly to IL (see the link in the opening post).

---

@HaloFour commented on [Wed Jan 27 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-175727090)

@alrz In IL it's all conditional branch opcodes, unless the condition meets the incredibly narrow requirements to make it work with `switch`.  I assume that ADTs in F# have an incrementing tag field which do meet those requirements.

If `if (typeof(Frob).TypeHandle.Equals(type))` is appreciably more efficient then sure, that's probably what the compiler should emit.

---

@drewnoakes commented on [Thu Jan 28 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-176100436)

Should this only match exact types? What about derived types? Would `case typeof(object)` catch everything or only `new object()`? Either way it's going to surprise someone somewhere.

---

@alrz commented on [Thu Jan 28 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-176101952)

@drewnoakes That would be actually nice but then it will depend on the order and we might lose `TypeHandle` optimization.

---

@AdamSpeight2008 commented on [Thu Jan 28 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-176123567)

Or it'll turn it into a dictionary lookup, similar to VB.net's `Select Case`

---

@CnSimonChan commented on [Sat Apr 09 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-207867184)

Seems you can do it in future branch
![snip_20160410064405](https://cloud.githubusercontent.com/assets/1330321/14406886/acd14546-fee7-11e5-9784-e38da4ba3f61.png)
But the compiler will crash when compiling it :(

---

@alrz commented on [Sat Apr 09 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-207932835)

@CnSimonChan I think that's because `switch` is already relaxed to accept any expression type (depending on the branch you're on) and this doesn't seem to be something that you'd get it "for free" via pattern-matching. So I think they should make it explicitly an error or consider implementing it.

---

@gafter commented on [Mon Apr 11 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-208447659)

@CnSimonChan Reported as #10459

---

@gafter commented on [Mon Apr 11 2016](https://github.com/dotnet/roslyn/issues/8194#issuecomment-208455851)

Since we have to fix the compiler crash, lets just make this work.

---

@weitzhandler commented on [Mon Mar 06 2017](https://github.com/dotnet/roslyn/issues/8194#issuecomment-284390496)

A compelling feature I come a lot across with. I'd love to see this implemented.

**Comment by jnm2** [comment]
This would be good for scenarios where I have a type but no instance to switch on.

**Comment by Spongman** [comment]
I just ran into this and was really surprised that, given c#7's new switch statement stuff, that this simple case was still not covered.

**Comment by YairHalberstadt** [comment]
@gafter

Do you think this could be championed? You indicated above that you thought it was worth doing, and I think it fits nicely in with pattern matching.

I would be happy to implement it.

**Comment by gafter** [comment]
@YairHalberstadt I am not interested in championing this.

**Comment by YairHalberstadt** [comment]
@gafter

Understood. That's a pity. It's only a minor feature, but it comes up quite regularly. For example you suggested I use it in https://github.com/dotnet/roslyn/pull/32843#discussion_r264916537

**Comment by gafter** [comment]
> For example you suggested I use it

That was not what I meant by "switching on the type".  I meant something like

``` c#
switch (someObject)
{
    case SomeType1 s1:
        ....
    case SomeType1 s2:
        ...
    case SomeType3 s3:
        ...
}
```

I'm working on our options for making this compile reliably to a constant-time dispatch in future versions (likely C# 9 or so) without any source changes.

**Comment by Happypig375** [comment]
My TypeConverters will look so much better when this is implemented!
