### ISSUE TITLE
Property paths pattern

### ISSUE THREAD

**Issue by mariodvm** [dotnet/csharplang#3565]
Hello there 
Isn't it too much ceremony?

```CSharp
node switch 
{ 
    UnaryExpression { Operand: { Type: { Name: var operandTypeName }}} => ... 
}
```

I propose to allow property paths as a variation of property patterns:

```CSharp
node switch 
{ 
    UnaryExpression { Operand.Type.Name: var operandTypeName } => ... 
}
```
thanks and be healthy :)

**Comment by iskandersierra** [comment]
Yes! I like the idea. We could even include null checks there:
```csharp
node switch 
{ 
    UnaryExpression { Operand.Type?.Name: var operandTypeName } => ... 
}
```

**Comment by mariodvm** [comment]
In that line of things... maybe we could even think about _Expressions_ patterns? like this...
```CSharp
node switch 
{ 
    UnaryExpression { Operand.Type?.GetMethods().Length: var methodCount }  => ... 
}
```

**Comment by bigredd0087** [comment]
There would be no need for the null check. Property patterns already check for null.

**Comment by YairHalberstadt** [comment]
Closing as 'duplicate' of https://github.com/dotnet/csharplang/discussions/4114. Whilst this was created earlier, that seems to have generated more discussion so I'd rather continue further discussion there: https://github.com/dotnet/csharplang/discussions/4114.
