### ISSUE TITLE
Proposal: return random double within a specified range

### ISSUE THREAD

**Issue by JansthcirlU** [dotnet/csharplang#3568]
The `Random` class is often used to add noise to data, so it would be nice if there was a method that could specify a random output between two values like `Next(int min, int max)` but for doubles instead: `NextDoubleRange(double min, double max)` where `min` and `max` are -1 and 1 respectively by default.

Example using current C#:
```c#
Random rng = new Random();
double mean = 10; // Mean value
double deviation = 5; // Maximum deviation from the mean
double x1 = mean + deviation * (2 * rng.NextDouble() - 1); // One option
double x2 = mean + deviation * rng.Next(-1,2) * rng.NextDouble(); // Another option
```
But with the new method you could write:
```c#
Random rng = new Random();
double mean = 10; // Mean value
double deviation = 5; // Maximum deviation from the mean
double x1 = mean + deviation * rng.NextDoubleRange(); // One option
double x2 = mean + rng.NextDoubleRange(-deviation, deviation); // Another option
```
This would also be useful to create biased noise:
```c#
Random rng = new Random();
double mean = 10;
double under = 5;
double over = 7;
double x1 = mean + rng.NextDoubleRange(-under, over); // Equivalent to:
                                                      // mean = 11
                                                      // deviation = 6
```

**Comment by orthoxerox** [comment]
BCL changes should go to https://github.com/dotnet/runtime

**Comment by jnm2** [comment]
Also, when you open this issue there, use the [API proposal](https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md) issue template.

**Comment by JansthcirlU** [comment]
I have re-submitted my issue over at https://github.com/dotnet/runtime/issues/37905, so I will close this.
