### ISSUE TITLE
Unexpected convert errors on oprators and shifts

### ISSUE THREAD

**Issue by rootflood** [dotnet/csharplang#3572]
hi, i have unexpected errors which shouldn't be
```c#
    enum Access:byte
    {
        //0
        Read=0,
        //1
        Write=1
    }
    enum Socket_Access_Sequence : byte
    {
        //10
        Read_Then_Write = Access.Read | Access.Write << 1,
        //01
        Write_Then_Read = Access.Write | Access.Read << 1
    }

    class Program
    {
        public static void Main()
        {
            // unexpected
            //Error Operator '<<' cannot be applied to operands of type 'Access' and 'int'
            Access A = Access.Write << 2;

            // unexpected
            //Error Operator '<<' cannot be applied to operands of type 'Access' and 'int'
            Socket_Access_Sequence SAS =Access.Read | Access.Write << 2;

            byte b = 0;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b << 3;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b + 1;
        }
    }
```
but this is valid
```c#
    enum Socket_Access_Sequence : byte
    {
        Read_Then_Write = Access.Read | Access.Write << 1,
        Write_Then_Read = Access.Write | Access.Read << 1
    }
```

**Comment by svick** [comment]
I believe this is correct according to the spec. The `<<` operator does not exist for enums, which is why your code doesn't compile. The reason why the same code does compile when you're defining the value of an enum member is [the following part of the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#enum-members):

> Within an enum member initializer, values of other enum members are always treated as having the type of their underlying type, so that casts are not necessary when referring to other enum members.

But those casts are necessary in other cases.

**Comment by rootflood** [comment]
>> @svick The << operator does not exist for enums

can you explane why this is valid
```c#
    enum Socket_Access_Sequence : byte
    {
        Read_Then_Write = Access.Read | Access.Write << 1,
        Write_Then_Read = Access.Write | Access.Read << 1
    }
```

**Comment by svick** [comment]
@rootflood I did and also quoted the part of the C# spec that makes that code valid. Was that not clear?

**Comment by rootflood** [comment]
I talking about that shift
>> Access.Write << 1

**Comment by CyrusNajmabadi** [comment]
> can you explane why this is valid
> I talking about that shift

Yes, he quoted the part of the spec that explains that:

```
Within an enum member initializer, values of other enum members are always treated as having the type of their underlying type, so that casts are not necessary when referring to other enum members.
```

So in that context: `Access.Read | Access.Write << 1,` is effectively   `(int)Access.Read | (int)Access.Write << 1`.

**Comment by rootflood** [comment]
sorry but I'm very confuse
```c#
    public enum MyE : int
    {
        //01
        TheE1=1,
        //10
        TheE2=2
    }
   
    class Program
    {
        public static void Main()
        {
            MyE E = MyE.TheE1|MyE.TheE2; // "Or" is ok
            E = MyE.TheE1 & MyE.TheE2; // "And" is ok
            E = ~MyE.TheE1; // "Bit" is ok
            E = MyE.TheE1 << 2; // why its not ok?
        }
    }
```

**Comment by svick** [comment]
@rootflood Because those other operators are explicitly allowed by [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#enum-values-and-operations):

> The following operators can be used on values of enum types: `==`, `!=`, `<`, `>`, `<=`, `>=`, binary `+`, binary `-`, `^`, `&`, `|`, `~` , `++` and `--`.

Since `<<` is not listed there, it can't be used on enums under normal circumstances.

**Comment by 333fred** [comment]
Generally speaking, we don't want to encourage manual bitshifting on enums outside the enum. If `Access.Read << 2` is important to you, it should be a named flag in the enum, not a magic value you create outside the enum. This can lead to brittle code.

**Comment by CyrusNajmabadi** [comment]
>  `= MyE.TheE1 << 2; // why its not ok?`

Because the spec does not allow for bitshifting enum values by arbitrary integers anywhere *outside* the declaration of hte enum itself.

**Comment by rootflood** [comment]
> @CyrusNajmabadi Because the spec does not allow for bitshifting enum values by arbitrary integers anywhere outside the declaration of hte enum itself.

> @333fred Generally speaking, we don't want to encourage manual bitshifting on enums outside the enum.

a few is correct, just a few, i saw all documents before of making this issue
why you reacting to me just like the compiler? i saw all documents [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#enum-values-and-operations), please open your mind :)
enums acting a little like numbers but they have own separate type
so we can using that in as different situations, we can use that as bitwise flags or we can use that as numeric names

```c#
    public enum MyEnum : int
    {
        TheE1=0,
        TheE2=1,
        TheE3=3,
        TheE4=4
    }
   
    class Program
    {
        public static void Main()
        {
            MyEnum E = MyEnum.TheE1 | MyEnum.TheE2;
            Console.WriteLine(E.ToString());
            // Output is TheE2 which is correct in bitwise but is wrong as selected values of the range

            E = MyEnum.TheE4 | MyEnum.TheE2;
            Console.WriteLine(E.ToString());
            // Output is 5 , MyEnum not contain 5

            Console.WriteLine((E & MyEnum.TheE1).ToString());
            // Output is TheE1 , i knew this

            //Error: The operand of an increment or decrement operator must be a variable, property or indexer
            E = ++MyEnum.TheE1;
            E = MyEnum.TheE1++;

        }
    }
```
if we using an "enum: byte" as bitwise then we have 8 bit flag and 8 option
but if we using that as numeric then we have 256 options here
different using for each needs different rules not same
for example "OR,AND Operators" can work in bitwise but can't work well in numeric

so rules shouldn't be explicit and should be based on how we using, so why we have explicit errors here when we can change the "enum type" out of range or in wrong case via that explicit rules? 
this is what's confusing me

i think c# must do separate using for each of enum using https://github.com/dotnet/csharplang/issues/3179
or c# let us implicit cast like numbers

the other cast problem which i have is
```c#
        public static void Main()
        {
            byte b = 0;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b << 3;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b + 1;
        }
```

**Comment by 333fred** [comment]
> why you reacting to me just like the compiler? i saw all documents [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#enum-values-and-operations), please open your mind :)

I'm reacting like I'm reacting because that's my honest opinion. Changing this does not seem like a good idea to me. 

> enums acting a little like numbers but they have own separate type
> so we can using that in as different situations, we can use that as bitwise flags or we can use that as numeric names

That's not how enums were designed. They're not intended to act as numbers. They can be bitwise anded and ored because they're intended to act as flags, so you can do things like `ConversionKind.Implicit | ConversionKind.Nullable` to mean an implicit nullable conversion. But they're intentionally not supposed to act as numbers. Adding or bitshifting flags outside the enum isn't a good idea. The reason enums exist is to give names to magic numbers, and adding or bitshifting enums in any context other than creating a new enum name is just introducing a new magic number.

Your proposal is really struggling from lack of a motivating example beyond you expecting it to work. You need to convince a member of the language design team that this proposal is worth adding to the language, and currently I'm seeing nothing but downsides.

**Comment by CyrusNajmabadi** [comment]
> so we can using that in as different situations, we can use that as bitwise flags or we can use that as numeric names

If you want to use as a number, there are solutions already available to that: just use a number. I.e. `const int TheE2 = 1`. 

For enums we every specifically do not think general math operations should work by default, since they can give you values you don't have a name for. So, if you really want to go and do numeric with, you are required to add the appropriate casts out/in of the enum domain.  This is very intentional to call or in the code explicitly what may be happening.

**Comment by rootflood** [comment]
closed as answers contradiction with "enum types" documents 
[Enums](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums) , [Enumeration types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum#enumeration-types-as-bit-flags)
Documents info:
>The associated value of an enum member is assigned either implicitly or explicitly.

>The default value of an enumeration type E is the value produced by expression (E)0, even if zero doesn't have the corresponding enum member.

>You use an enumeration type to represent a choice from a set of mutually exclusive values or a combination of choices. To represent a combination of choices, define an enumeration type as bit flags. [Enumeration types as bit flags](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum#enumeration-types-as-bit-flags)

>For any enumeration type, there exist explicit conversions between the enumeration type and its underlying integral type. If you cast an enum value to its underlying type, the result is the associated integral value of an enum member.[Enum Conversions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum#conversions)

>the enumeration type comparison operators simply compare the underlying integral values of the two operands. [Enumeration comparison operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#enumeration-comparison-operators)
>
```c#
bool operator ==(E x, E y);
bool operator !=(E x, E y);
bool operator <(E x, E y);
bool operator >(E x, E y);
bool operator <=(E x, E y);
bool operator >=(E x, E y);
```
>The explicit enumeration conversions are: [Explicit enumeration conversions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#explicit-enumeration-conversions)

    From sbyte, byte, short, ushort, int, uint, long, ulong, char, float, double, or decimal to any enum_type.
    From any enum_type to sbyte, byte, short, ushort, int, uint, long, ulong, char, float, double, or decimal.
    From any enum_type to any other enum_type.

>The set of values that an enum type can take on is not limited by its enum members. In particular, any value of the underlying type of an enum can be cast to the enum type, and is a distinct valid value of that enum type.
[Enum values and operations](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#enum-values-and-operations)

**Comment by CyrusNajmabadi** [comment]
> closed as answers contradiction with "enum types" documents

I don't see any contradiction with those documents.

**Comment by rootflood** [comment]
@CyrusNajmabadi sorry about long discussion but there is
i closed this and this isn't important anymore, you can ignore it if you want
so thanks all
if you want details about contradiction:
1:
> @333fred >> Generally speaking, we don't want to encourage manual bitshifting on enums outside the enum.

>@CyrusNajmabadi>>  Because the spec does not allow for bitshifting enum values by arbitrary integers anywhere outside the declaration of hte enum itself.

>@CyrusNajmabadi>> For enums we every specifically do not think general math operations should work by default, since they can give you values you don't have a name for. So, if you really want to go and do numeric with, you are required to add the appropriate casts out/in of the enum domain.

The set of values that an enum type can take on is not limited by its enum members. [Enum values and operations](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#enum-values-and-operations)

Valid Example:
```c#
    class Program
    {
        public enum a {a1=1}

        public static void Main()
        {
            // no error
            a a = a.a1 + 1000;
        }
    }
```
2:
> @333fred >>That's not how enums were designed. They're not intended to act as numbers. They can be bitwise anded and ored because they're intended to act as flags

You use an enumeration type to represent a choice from a set of mutually exclusive values or a combination of choices. To represent a combination of choices, define an enumeration type as bit flags. [Enumeration types as bit flags](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum#enumeration-types-as-bit-flags)

that are most contradictions.

**Comment by CyrusNajmabadi** [comment]
I don't see contradictions here.

>The set of values that an enum type can take on is not limited by its enum members.


Yes.  That's understood.  The question is if that is encouraged or not.  As @333fred said:we don't want to encourage manual bitshifting

There's no contradictoin here.  Something may be possible, but still may not be something we think is a *good idea*.  And the language is commonly designed about restricting people from doing things we don't think are a good idea, even if it would be possible to allow it.

**Comment by CyrusNajmabadi** [comment]
> @333fred >>That's not how enums were designed. They're not intended to act as numbers. They can be bitwise anded and ored because they're intended to act as flags

This is not a contradiction either.  THey're designed to be used as flags as one of the main use cases.  So flag-oriented operations are supported.  Shifting is not viwed as a flag-oriented operation.  So it's not allowed.  This is still in line with what was being said before.

**Comment by rootflood** [comment]
> @CyrusNajmabadi So flag-oriented operations are supported. Shifting is not viwed as a flag-oriented operation.

But this isn't look like flag-oriented operation:
```c#
    class Program
    {
        public enum a {a1=1}

        public static void Main()
        {
            // no error
            a a = a.a1 + 1000;
        }
    }
```

**Comment by CyrusNajmabadi** [comment]
Yes?

I'm not seeing the contradiction.  I never claimed + was a flag-oriented.  I claimed that we think it's fine to view enums as flags, and thus `&` or `|` makes sense for them.

If you want this new operator supported, a compelling argument woudl have to be made why it's valuable to have.

**Comment by rootflood** [comment]
> @CyrusNajmabadi >> why it's valuable to have

It's not valuable, c# deserve to have it as perfect language
And it's not what I want, it's just an offer
May you denying this but there is strong logic behine of the story

> @CyrusNajmabadi >> and thus & or | makes sense for them.

Is + operator make sense for them?

**Comment by CyrusNajmabadi** [comment]
`+` is already supported, so i'm not sure what's being asked for there.  We would not disallow something unless there was *very* strong cause to due to our breaking change compat promises :)

> c# deserve to have it as perfect language

Well, we can disagree on what helps move in toward/away from perfection :)

**Comment by rootflood** [comment]
OK, what about this? Do you think it's a bug or my mistake? :) 
```c#
        public static void Main()
        {
            byte b = 0;
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b << 3;

            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b + 1;
        }
```

**Comment by HaloFour** [comment]
@rootflood 

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/arithmetic-operators
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#numeric-promotions

> When operands are of other integral types (`sbyte`, `byte`, `short`, `ushort`, or `char`), their values are converted to the `int` type, which is also the result type of an operation.

**Comment by rootflood** [comment]
@HaloFour I just thinking even c++ did have't same restrictions like that you told
However Thanks, you convinced me, anyway, anyshape, you're right

**Comment by CyrusNajmabadi** [comment]
> OK, what about this? Do you think it's a bug or my mistake? :)

It's a bug in your code as per the rules of the language. If you want the language to change, you can make proposals to that effect.  Note that there are very significant consequences of doing something like that.  For example, consider the following:

```c#
using System;

class Program
{
    void Foo(Func<int, int> f) { }
    void Foo(Func<byte, byte> f) { }

    void Goo()
    {
        Foo(x => x + 1);
    }
}
```

This is currently legal, and Foo binds to the first call.  If you make it legal to add ints to bytes (and get bytes back), this will break as it will become ambiguous.

**Comment by rootflood** [comment]
> @CyrusNajmabadi >> This is currently legal, and Foo binds to the first call. If you make it legal to add ints to bytes (and get bytes back), this will break as it will become ambiguous.

I think that is defenely ambiguous, but after change still that can be legal, how? Answer is x isn't byte or int, x is anymose type and that rule can limited only on anymose types, let me declare the oprators:
```c#
int operator +(anymose x1, int x2) => ((int) x1) + x2;
```

**Comment by rootflood** [comment]
Other is 
> Foo(x => x + 1);

"1" isn't int or byte, that is number, so we can have anymose_number
So:
```c#
int operator +(anymose x1, anymose_number x2) => ((int) x1) + ((int) x2);
```

**Comment by rootflood** [comment]
> @CyrusNajmabadi If you want the language to change, you can make proposals to that effect.

That's not good idea for me, I think if I make new proposal then you denying that anyway at all

**Comment by CyrusNajmabadi** [comment]
> That's not good idea for me, I think if I make new proposal then you denying that anyway at all


Most proposals don't make it into the language. However, things that are not proposed never make it into the language. If you (out someone else) don't make a proposal, it won't happen. 

And yes, people may argue for or against the proposal. That's the point of them :-)

**Comment by rootflood** [comment]
@CyrusNajmabadi 
I think there isn't big social for tell most of needs and valume peoples like and dislike that,
Other is c# team have own desions and that is more understanable for own team, and that is good
Other is c# now is heavy for computers, our idea may make that heavier
Other is improving c# now can be very much hard and any idea even with a little change make that harder, I think the cost is growing logarithmic
So as summary I can just wait and see what happen next

**Comment by rootflood** [comment]
i have a question, HaloFour is in the language team or is people?
