### ISSUE TITLE
Proposal: Short custom read/write Property data source

### ISSUE THREAD

**Issue by TCLNA** [dotnet/csharplang#3580]
Hi,
Preamble: I may not have seen the solution for this, and I am also sorry if it's a duplicate (even if I kinda guessed it was).

Context
---------------------------------------------------
__Quick getter expression definition:__
```c# 
public string Property => this._data;
```
Issue: is readonly, also defines an expresion, and not a source.

__Automatic props:__
```c#
public string Property { get; set; }
```
Issue: (see [c-sharp-automatic-properties-to-wrap-private-fields](https://stackoverflow.com/questions/17589459/c-sharp-automatic-properties-to-wrap-private-fields))

Proposal
---------------------------------------------------
Creating an alias to to allow quick read/write Property source binding.

Possible Implementations
---------------------------------------------------
Fitting an operator/keyword between the definition and the getter/setter braces.

__Before:__
```c#
// full auto
public string Name { get; set; }

// custom source
public string Description
{
  get => this._description;
  set => this._description = value;
}

// custom source wrapping
public byte[] Content
{
  get => this._file.Content;
  set => this._file.Content = value;
}
```

__After:__
```c#
// full auto
public string Name { get; set; }

// custom source
public  string Description from this._description { get; set; }

// custom source wrapping
public byte[] Content from this._file.Content { get; set; }

// custom source wrapping and custom getter/setter combination
public Custom Custom from this._custom
{
  get => source;
  set => source = value;
}
```

Variations
---------------------------------------------------
Typing `from` is still tidious, why not those alternatives:

- For `from`: `to`, `alias`, `bind`, `:`, `::`, `<=>`, `->`, `...(SOURCE)`, ... `=>` ?

- For `source`:  `old`,  `alias`, `src`, `from`

> I advise smashing on your keyboard to find other candidates

I tried to propose a way of implementing something that I think a lot of C# devs would be happy to see, but I would be glad if this issue was marked as a duplicate, or if there is a simple workaround that I didn't know existed.
Please tell me what you think of it !

PS:
---------------------------------------------------
Thanks a lot for reading ! 😄

**Comment by TCLNA** [comment]
Nevermind, I found it !
#140

**Comment by Unknown6656** [comment]
possible duplicates:
#2913
#2647
#1880
#1712
#1643
#1497
#1420
#1336
#1290
#1240
(#1059)
#626
#318
#140
#133
