### ISSUE TITLE
proposal: Anonymous Number Type

### ISSUE THREAD

**Issue by rootflood** [dotnet/csharplang#3586]
Anonymous Number Type must provide a convenient way to cast any number to strong types like int, byte or others to explicitly define a number type first. is not available at the source code level.
the default cast of Anonymous Number is int32 type.

reason:
based on https://github.com/dotnet/csharplang/issues/3572 we have some sort of bugs in operations like +,-,<<,.... 
```c#
        public static void Main()
        {
            byte b = 0;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b << 3;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b + 1;
        }
```

what is that Anonymous Number:
any number which is defined directly is Anonymous Number
```c#
var Number = 1; // "1" is Anonymous Number but after setting to "var Number" that number get strong type int32
Console.WriteLine(Number.GetType()); // Output >> System.Int32
```

Lifetime:
the Anonymous Number is live until that set to the variable and not usable as type.
because of [this problem](https://github.com/dotnet/csharplang/issues/3572#issuecomment-646323382) default type of Anonymous Number is "int" .

```c#
using System;

class Program
{
    void Foo(Func<int, int> f) { }
    void Foo(Func<byte, byte> f) { }

    void Goo()
    {
        Foo(x => x + 1);
        // type of x is not clear so we have ambiguous selector 
        // x+1 is Anonymous Number too and default type of Anonymous Number is int32, so "1" getting int32 type by default
       // so the compiler selected "void Foo(Func<int, int> f)" via type of "1 : int"
    }
}
```
Operations between Anonymous Numbers:
every operations between two Anonymous Number can have constant result by default.
```c#
var Number = 1+2; // "1+2=3" and "3" is Anonymous Number but after setting to "var Number" that number get strong type int32
Console.WriteLine(Number.GetType()); // Output >> System.Int32
```
Important:
this feature didn't affected into operators anyshape
this feature didn't affected into result of any function and need cast keyword
so that problem still exist "i think that wasn't a problem because of .net"

so we may need to direct operators like
```c#
byte operator +(byte a, byte b)
```
[such info in stackoverflow](https://stackoverflow.com/questions/941584/byte-byte-int-why)

**Comment by HaloFour** [comment]
This sounds very complicated and confusing.  The current C# behavior has been there for 20 years and is well documented and understood.  For those niche situations where bit-twiddling is necessary it's already very easy to be explicit about which numeric types you're working with through both literal suffixes and casts, which the compiler and JIT are intelligent enough to elide.

**Comment by rootflood** [comment]
@HaloFour 
after 20 years why the c# didn't know what is implicit and what is explicit?
```c#
            Int16 b = 0;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'Short'. An explicit conversion exists (are you missing a cast?)
            b = b + 1;
```

**Comment by rootflood** [comment]
> @HaloFour >> This sounds very complicated and confusing.

This is very simple

>Foo(x => x + 1);

1 is unknown so compiler trying to find type of the "1" in (x => x + 1)
because type of the x is unknown so compiler decisis to set type of the "1" to int32 by default

>Int16 b = 0;
>b = b + 1;

1 is unknown so compiler trying to find type of the "1" in (b = b + 1)
because type of the b is Int16 so compiler decisis to set type of the "1" to Int16

very simple, isn't?

**Comment by HaloFour** [comment]
@rootflood 

> after 20 years why the c# didn't know what is implicit and what is explicit?

It does, and it wants you to be explicit there, on purpose.  That's why this behavior is very intentionally written into the spec.

> very simple, isn't?

Nope, and it's a breaking change.  The result of `b + 1` is already an int32, changing that would affect overload resolution:

```cs
void M(short x) => Console.WriteLine("short");
void M(int x) => Console.WriteLine("int");

short b = 0;
M(b + 1);
```

Today that will print "int", you're suggesting it print "short" instead.

**Comment by rootflood** [comment]
@HaloFour ok you are right :)

**Comment by rootflood** [comment]
@HaloFour do you know what is really complicated and confusing?
this:
```c#
    class Program
    {
        static void M(byte x) => Console.WriteLine("byte");
        static void M(int x) => Console.WriteLine("int");

        public static void Main()
        {
            byte b0 = 0;
            byte b1 = 1;
            M(b0 + 1); // Output > int
            M(b0 + b1); // Output > int
            M((byte)(b0 + b1)); // Output > byte
        }
    }
```
and this:
```c#
    class Program
    {
        static void M(double x) => Console.WriteLine("double ");
        static void M(int x) => Console.WriteLine("int");

        public static void Main()
        {
            double b0 = 0;
            double b1 = 1;
            M(b0 + 1); // Output > double 
            M(b0 + b1); // Output > double 
            M((byte)(b0 + b1)); // Output > int
        }
    }
```
so yes i don't know how describe that to my students
and i can't imagine how they trying to make a solution for his problems via this operators

**Comment by HaloFour** [comment]
@rootflood 

Overloading is very confusing, especially when it comes to the compiler trying to guess the "best candidate" from a list of multiple options all of which require an implicit conversion.  That's why languages like Go don't allow it, and several C# team members have stated that if they could restart C# from scratch they probably wouldn't allow it either.

**Comment by rootflood** [comment]
@HaloFour 
this isn't come from Overloading selector, this is come from operators also
```c#
    class Program
    {
        static void M(byte x) => Console.WriteLine("byte");
        static void M(int x) => Console.WriteLine("int");

        public static void Main()
        {
            byte b0 = 0;
            byte b1 = 1;
            M(b0 + 1); // int Operator +(int x1, int x2)
            M(b0 + b1); // type of b0,b1 is byte but we have > int Operator +(int x1, int x2)
            M((byte)(b0 + b1)); //(byte) ( int Operator +(int x1, int x2) )
        }
    }
```
and
```c#
    class Program
    {
        static void M(double x) => Console.WriteLine("double ");
        static void M(int x) => Console.WriteLine("int");

        public static void Main()
        {
            double b0 = 0;
            double b1 = 1;
            M(b0 + 1); // double Operator +(double x1, double x2)
            M(b0 + b1); // double Operator +(double x1, double x2) 
            M((byte)(b0 + b1)); // >> implicit cast to int by default > (int)(byte) double Operator +(double x1, double x2)
        }
    }
```

**Comment by rootflood** [comment]
@HaloFour 
this is much understandable and tell you the real reason :
```c#
    class Program
    {
        public static void Main()
        {
            byte b1 = 1;
            byte b2 = 2;
            var b3 = b1 + b2;
            Console.WriteLine(b3.GetType());
            // Output is System.Int32
        }
    }
```
so where is overloads? :)

**Comment by HaloFour** [comment]
Operators aren't methods on primitives types in C# or the .NET runtime.  They are IL opcodes, which are translated into machine language opcodes by the runtime.  And they also have a well documented behavior when it comes to the data types being used:

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.add

**Comment by rootflood** [comment]
> @HaloFour >> Operators aren't methods on primitives types in C# or the .NET runtime. They are IL opcodes, which are translated into machine language opcodes by the runtime. And they also have a well 

i didn't talking about overload resolution at all :)
that was your told

> @HaloFour >> Nope, and it's a breaking change. The result of b + 1 is already an int32, changing that would affect overload resolution

**Comment by HaloFour** [comment]
@rootflood 

> i didn't talking about overload resolution at all

Because I was pointing out where your proposal would impact overload resolution.

**Comment by rootflood** [comment]
@HaloFour 
what is this proposal title?
do you see any describe like "overload" in first?
the overload works just perfect in my examples and i hasn't any problem with that

**Comment by rootflood** [comment]
@HaloFour 
i realy like criticisms because that can help to see dark sides of our idea but if that is a really criticisms.

**Comment by HaloFour** [comment]
@rootflood 

So if the "anonymous number" converts back into an int32 on being passed to a method or other scenarios, such that it doesn't break existing code, then what's the point of it at all?  The type of any variable declared by `var` needs to be determined by the expression used to assign it.  Having it "change" based on how you use it would be very confusing and against the design of `var`.  I don't see why it's worth trying to change the semantics of how arithmetic works in a 20 year old language and I'm very suspicious that it's possible without introducing breaking changes.  I see no problem with the language requiring you to be explicit here.

**Comment by rootflood** [comment]
anonymous number is virtual, it's not a type and cant using in IL
that not for var only
that come to fix this unexpected implicit errors:
```c#
            byte b = 0;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b << 3;

            // unexpected
            //Error Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
            b = b + 1;
```
before of this c# declared all constant numbers as int
```c#
var i=1; // 1 is int
```
and this get to us unexpected implicit error
so why b1 is fine and b2,b3 is not?
```c#
            byte b1 = 1 + 2;
            byte b2 = b1 + 2;
            byte b3 = b1 + b2;

            double d1 = 1;
            var d2 = d1 + 2; // why type of "2" is int? that must be double
```

**Comment by HaloFour** [comment]
You're not using "anonymous numbers" anywhere in that example.  You're trying to assign the result of an int32 expression back to a byte.  You want the C# compiler to start guessing what you meant there and automatically coerce numeric types?  I'd say that's more confusing and potentially error prone.

```cs
            double d1 = 1;
            var d2 = d1 + 2; // why type of "2" is int? that must be double
```

`d2` is a `double` here

**Comment by rootflood** [comment]
i think this problem can patch (not fix) without this proposal
if we can have 
>byte operator +(byte b1, byte b2) 
```c#
byte operator +(byte b1, byte b2)           
byte b = 0;            
// fine
b = b + 1;
```
but problem still exist because type of "1" is "int" and not byte

**Comment by rootflood** [comment]
> @HaloFour >> d2 is a double here

yes that is because of casting int to double
```c#
        public static void Main()
        {
            double d1 = 1;
            int i = 2;
            var d2 = d1 + i ;
        }
```

**Comment by HaloFour** [comment]
Either way, these language and runtime semantics have been clearly defined and have been like this for 20 years.  I don't find it compelling to rewrite these parts of the spec/language/runtime to make it slightly easier to do 8- or 16-bit math.

**Comment by rootflood** [comment]
> @HaloFour >> to make it slightly easier to do 8- or 16-bit math.

do you think that is my reason? my reason is c# must be enough smart to know that isn't implicit
and what that you say is also important but it's not my reason
so is this mean this must continue for next 20 year also?
and you must know vb.net also fixed that problem anyway 
they use extra cast only
```vb
        Dim b As Byte
        b = b + 5 ' this is fine. the result castes to byte
```
and also c++ haven't same bug like that

**Comment by HaloFour** [comment]
@rootflood 

And the result of the decisions in both languages impacts the behavior at runtime.  `255 + 1` results in a runtime exception in VB.NET due to the implicit narrowing conversion.  The same expression results in an unchecked overflow in C++ and the result is `0`.

**Comment by rootflood** [comment]
@HaloFour 
can you describe to me why peoples should put proposal here?
you say the c# is perfect and have 20 years history and don't need any changes
i can just say you are right anyway and any shape
may you don't want to growing and i say yes you are right, that have less risks
but risks make mean to my life :) .

**Comment by PathogenDavid** [comment]
Look, I don't like this particular behavior in C# either. However, as much as you and I resent the fact that various arithmetic operators aren't defined for `short`, `ushort`, `byte`, and `sbyte`, it doesn't change the fact that it's been like that for a very long time. Whether we like it or not, there's a lot of code out there that actually relies on this numeric promotion. Changing the rules now would break things.

> very simple, isn't?

I'm actually not entirely sure what you're proposing here at all. It seems like you're talking about changing the existing semantics of the language, that's almost always a non-starter.

> based on #3572 we have some sort of bugs in operations like +,-,<<,....

You need to reevaluate your definition of the word "bug". This is a well-documented aspect of C#'s design. At best it is a quirk in the language.

> so is this mean this must continue for next 20 year also?

Yes. Because changing it now means breaking all the code written over the past 20 years.

------------

If you don't like this behavior, you're better off making your own `RootfloodByte` and `RootfloodShort` struct wrapper that provides the semantics you want.

**Comment by rootflood** [comment]
@HaloFour that even not related to any things which we told, do you copy that from some document?
There is not jit, there is c#
At runtime we have own exceptions, there is compile error not an exception 
Do you know what is differents or I must tech that also?

**Comment by rootflood** [comment]
@PathogenDavid
 i using vb. Net when c# can't do something, 
>RootfloodByte

:D ok I thinking, that was awesome

**Comment by rootflood** [comment]
> @PathogenDavid >>I'm actually not entirely sure what you're proposing here at all. It seems like you're talking about changing the existing semantics of the language, that's almost always a non-starter.

So please read what I told left to right

**Comment by rootflood** [comment]
closed because they know what they doing :)

**Comment by rootflood** [comment]
> @HaloFour >> VB.NET due to the implicit narrowing conversion.

they know this code isn't implicit so they patched (not fixed) that via implicit narrowing conversions
```vb
        ' vb.net
        Dim b As Byte
        b = b + 5 ' this is fine. the result castes to byte
```
other is i didn't talking about conversion, i talking about strong type numbers so its not even implicit, that is exactly explicit
so yes you didn't know what am i talking about, if you are confusing that's not my fault, you was able to ask at first not now
"byte = byte + byte" is exactly explicit and didn't need to any conversion and must haven't any conversion
> @rootflood >> Anonymous Number Type must provide a convenient way to cast any number to strong types like int, byte or others to explicitly define a number type first.

did you remember that?
you can check flowing links for more info:
[Widening and Narrowing Conversions (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/widening-and-narrowing-conversions)

but however i can't convince you because you thinking internally and setting your bugs which is in your mind to me

**Comment by rootflood** [comment]
@HaloFour 
aw, i thing "byte = byte + byte" isn't explicit, that is implicit but Widening and not Narrowing

**Comment by rootflood** [comment]
Reopen as can be solution for https://github.com/dotnet/csharplang/issues/2929 https://github.com/dotnet/csharplang/issues/2929#issuecomment-549662899

**Comment by rootflood** [comment]
> @HaloFour >> it's a breaking change.

i think you are right at all, c# can't have a breaking change.
closed because of breaking change needs.

**Comment by rootflood** [comment]
@HaloFour excuse me but narrowing not related. 
That related to https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked

What is that point which may I missed?
I didn't got that

**Comment by HaloFour** [comment]
Converting from an `int` to a `byte` is a narrowing conversion, there is the opportunity for error or loss of data.

**Comment by rootflood** [comment]
@HaloFour 
i know that but what is the point?
i mean the result after that is just same
do you mean 
> byte operator +(byte b1, byte b2) // is missed the narrowing conversion

or if you mean cast can miss the narrowing conversion?
because its safe and not missing
```c#
            byte b = 1;
            b += 255; // no runtime error
            b = 1; // no runtime error
            b =(byte) (b + 255); // b==0 & no runtime error
            checked
            {
                b = 1;
                b =(byte) (b + 255); // Overflow Exception
            }
```

i editing the "proposal: Auto Cast for +,-,*,.... Oprators"
i want knows is that missed and how
can you write me an c# example?

**Comment by rootflood** [comment]
ok thanks.

**Comment by rootflood** [comment]
@PathogenDavid 
Well, I want tell something which is not related to this post
I want tell something to you and any one like you,
Are you still using lite DB? Or sql lite or any thing?
We aren't using that, do you know why? Because we can't wait for our fetures which we need, so we made other one, that can work in network and is much much faster than sql lite or lite DB. 
That started from 2018 and now that is the best option and any other dbs can't work for us like that.
So do you think we puted that in GitHub for public users? No, you ain't deserve to use that, and when you tell me I must make my rootfloodbyte its just fine for me and we are started our language and we hard trying to make new option for our and not for you. 
I just put last performance Check of our DB and you can just looking and can't using.
So yes I thinking very hard to our new option

**Comment by CyrusNajmabadi** [comment]
@rootflood: Starting a post with "Well, I want tell something which is not related to this post", is a pretty sure way to know that this is probably not something you should be posting here.

**Comment by rootflood** [comment]
@CyrusNajmabadi sorry, I delete that and this
