### ISSUE TITLE
[Proposal] Let code know the nullability of its generic type parameter

### ISSUE THREAD

**Issue by betty-crokker** [dotnet/csharplang#3587]
If I write this code:

```
#nullable enable
public class Holder<T>
{
    public readonly T Value;
    public Holder(object source, PropertyInfo prop)
    {
        Value = (T)prop.GetValue(source);
    }
}
#nullable disable

```
There is (seemingly) no way to make this null-safe - by which I mean the desired functionality is the following:
1. If I create Holder\<int\> and the property is of type int, everything is fine (the cast to 'T' will throw an exception if GetValue() returned null or float or anything else)
2. If I create Holder<string?> and the property is of type string (which means GetValue() can return null), everything is fine
3. If I create Holder\<string\> and prop.GetValue() returns null, an exception is thrown
4. No compiler warnings

Right now the nullability of type T is only known to the compiler, can we push this information into runtime by creating one new attribute?

```
#nullable enable
public class Holder<T>
{
    public readonly T Value;
    public Holder(object source, PropertyInfo prop)
    {
        SetValue((T)prop.GetValue(source));
    }
  private SetValue([ThrowExceptionIfNullabilityViolated] T value)
  {
     Value = value;
  }
}
#nullable disable

```

**Comment by HaloFour** [comment]
Sounds like #2145 covers the second half of this proposal?

Note that this is orthogonal to NRTs, which are intentionally not supposed to change the semantics of the code.  IMO reflection helpers like this are responsible for containing the code to enforce non-nullability (and type-safety in general).

**Comment by betty-crokker** [comment]
Sorry @HaloFour  I think I modified my code just as you were typing, which means when you say "second half of this proposal", it's now "the entire proposal" :-)
But to your point, I don't think #2145 quite covers it.  This and #2145 are certainly similar, but my proposal is specific to generic types (I think) which is a different flavor of problem

**Comment by betty-crokker** [comment]
So while this and #2145 have some similarities, there are some basic differences:
1) #2145 is a proposed syntax change to make code easier to write, but the functionality it describes is already something the C# language supports.  What I'm looking for, you can't do in C# right now.
2) #2145 always throws an exception if the parameter is null - I only want the exception thrown if the parameter is null and it shouldn't be.

**Comment by HaloFour** [comment]
> I only want the exception thrown if the parameter is null and it shouldn't be.

That might be more of a challenge.  The class itself would not know that it's being used in a nullable-enabled scenario or that the generic type argument is or isn't nullable.  That information doesn't exist at runtime.  Even if it did, though, as mentioned NRTs are not supposed to impact the behavior of the code.  At most you could possibly enforce the non-nullability by examining the attributes on the `PropertyInfo`, but that isn't necessarily going to be the same as the generic type argument of this helper class.

**Comment by betty-crokker** [comment]
I would say the "NRTs are not supposed to impact the behavior of the code" is "more what you'd call "guidelines" than actual rules." (grin)
Distinguishing between Holder<string> and Holder<string?> in code is completely impossible in the current C# version (as far as I can tell).  I tried examining attributes on the PropertyInfo, the Holder class itself, typeof(T), and everything is completely identical between Holder<string> and Holder<string?>.  I think it's a good design goal to keep NRTs out of runtime, but this is a specific class of example where I don't think there is any other way to meet the bigger goals (preventing unexpected null pointer execptions)

**Comment by betty-crokker** [comment]
And just to point something out for the discussion in general, this is not a problem specific to PropertyInfo.GetValue(); it happens every time you find yourself at the border where "this value can be null" and "this value can't be null" meet.  You can imagine that FieldInfo.GetValue() has the same issue, as well as MethodInfo.Invoke() but also any time you have a function that might return null, and you are trying to jam that return value into a generic class that may or may not accept null values.

**Comment by HaloFour** [comment]
>  I tried examining attributes on the `PropertyInfo`

The `PropertyInfo` will have an attribute called `System.Runtime.CompilerServices.NullableAttribute` on it.

> but this is a specific class of example where I don't think there is any other way to meet the bigger goals (preventing unexpected null pointer exceptions)

Once you wade into that territory it's up to the author of the class to negotiate the metadata and handle the type appropriately.  This generic type parameter of the `Holder<T>` class is kind of pointless because it's inherently not type-safe.  There's nothing about the language that will prevent you from declaring a `Holder<int>` with a `PropertyInfo`/`FieldInfo`/`MethodInfo` of a `string` member, let alone anything to do with nullability.

**Comment by rootflood** [comment]
Is this can help?
```c#
public class Holder<T>
where T : struct
{
    public readonly T Value;
    public Holder(object source, PropertyInfo prop)
    {
        SetValue((T)prop.GetValue(source));
    }
  private SetValue(T value)
  {
     Value = value;
  }
}
```

**Comment by betty-crokker** [comment]
@HaloFour  - Alas, the custom attributes on the property would not be helpful, because the nullability restrictions aren't there.  The property's GetValue() is allowed to return null - and it should be.  The problem is, I have a generic class that may or may not accept nulls.  As I said before, it's at the interface between these two nullability worlds where the problem lies.  
And if I print out information on typeof(Holder<string>) and typeof(Holder<string?>), they are exactly 100% identical.  Same if inside of Holder<> I print out information on typeof(T), it is exactly 100% identical between the Holder\<string\> and Holder<string?> case.

**Comment by betty-crokker** [comment]
@rootflood You have a solution, but it's to a different problem (grin).  Yes, if I restrict myself to structs, then the nullability gets easy.  There's a similar solution where I add the "where T: notnull" constraint to Holder.  But I'm creating library classes that are going to be used for structs, for nullable classes, and for non-nullable classes.

**Comment by betty-crokker** [comment]
@HaloFour - yes, if I construct a Holder<int> and then pass it a PropertyInfo that returns a string, it's going to throw an exception when it tries to cast the return value of GetValue() to type T.  That's standard casting behavior and I'm not trying to avoid or change it in any way.  The problem I'm trying to solve is that I want a Holder<> class that guarantees to its users that the value of Value meets the criteria they have specified.  Right now, if one of my users defines a class Holder<string> (indicating, in the C# 8 #nullable world, that they don't want nulls) I cannot give that to them.  All these changes to eliminate null pointers are great - they just need to go a tiny bit further.

**Comment by HaloFour** [comment]
@betty-crokker 

> And if I print out information on typeof(Holder) and typeof(Holder<string?>), they are exactly 100% identical. Same if inside of Holder<> I print out information on typeof(T), it is exactly 100% identical between the Holder<string> and Holder<string?> case.

Yes they are.  NRT metadata doesn't exist at runtime beyond those attributes, and they have no bearing on the semantics of the compiled code.  That's a very intentional aspect of the design of NRTs.  It's the responsibility of your helper class to negotiate the metadata that exists to enforce any appropriate type-safety, just as it is if this generic type argument doesn't match the actual runtime type of the property and throw the appropriate runtime exception.

**Comment by rootflood** [comment]
@betty-crokker can you write example of that type which you told

**Comment by betty-crokker** [comment]
@HaloFour - the appropriate metadata DOES NOT EXIST.  If it did I would be happy to use it.  The information DOES NOT EXIST currently that would allow me to enforce null-safety.

When a user creates a class Holder\<string\> (with #nullable enabled of course), that is defining a contract where the Holder class pledges that Value will never equal null.  With C# 8, the only choices are:
1) Have Holder\<string\> throw up its hands and say "you know what, I know you said Value shouldn't be null but I can't figure it out so it's up to you" (e.g. [MaybeNull])
2) Have Holder<string?> reject null values even though the user specifically said they were OK

**Comment by betty-crokker** [comment]
@rootflood I'm sorry, I don't know what you are asking for

**Comment by HaloFour** [comment]
@betty-crokker 

> the appropriate metadata DOES NOT EXIST.

It does exist on the `PropertyInfo` and will state the potential nullability of the property itself.  You can check that the property itself shouldn't be `null` and throw if it happens to be.

> When a user creates a class Holder<string> (with #nullable enabled of course), that is defining a contract where the Holder class pledges that Value will never equal null.

You're correct, NRTs can't do this.  That is by design.  NRTs are not a part of the type system and they have zero enforcement.  A property that claims that it won't return `null` can still return `null` if the author chooses to ignore the warnings.  And your `Holder<T>` can't enforce that the property doesn't return `null` based on the generic type argument because the nullability of `T` does not exist at runtime.  You're going to need to accept a separate flag if you decide that you want that enforcement in your code.

**Comment by rootflood** [comment]
@betty-crokker do you need thrown ex at runtime or get error at compile time?

**Comment by betty-crokker** [comment]
@rootflood It can't be at compile time because the value of prop.GetValue() won't be known until run time.

**Comment by rootflood** [comment]
so this can get exception in runtime:
```c#
    public class HolderStruct<T>
        where T : struct
    {
        public readonly T Value;
        public HolderStruct(object source, PropertyInfo prop)
        {
            Value = (T)prop.GetValue(source);
        }
    }

    public class HolderClass<T>
    where T : class
    {
        public readonly T Value;
        public HolderClass(object source, PropertyInfo prop)
        {
            Value = (T)prop.GetValue(source);
            if (Value == default)
                throw new NullReferenceException();
        }
    }
```

**Comment by betty-crokker** [comment]
@rootflood Yes but if I have HolderClass<string?> I don't want the exception thrown because a null value is just fine.  It's only if I have HolderClass\<string\> that I want the exception thrown.

**Comment by betty-crokker** [comment]
I just had a thought on another potential fix.  What if C# had a [GenericType] parameter - similar to how C# currently has the [CallerMemberName] attribute that is set by the compiler depending on the context?

```
#nullable enable
public class Holder<T>
{
    public readonly T Value;
    public Holder(object source, PropertyInfo prop)
    {
        SetValue((T)prop.GetValue(source));
    }
    void SetValue(T value, [GenericType(T)] Type typeOfT= null)
    {
      if ((value == null)&&(typeOfT!= null)&&(Nullable.GetUnderlyingType(typeOfT) == null))
         throw new Exception("Can't set Holder Value to null");
       Value = value;
    }
}
#nullable disable

```
Notice that in this proposed change, xType is NOT the same as typeof(T).  Whether I have Holder\<string\> or Holder<string?>, typeof(T) is string in both cases.  I'm proposing that xType is Nullable\<string\> when it's inside Holder<string?> and just plain string when it's inside Holder\<string\>.

**Comment by rootflood** [comment]
@betty-crokker so its impossible because that feature didn't change the type
this mean typeof(string)==typeof(string?)

```c#
    class Program
    {
        public static void Main()
        {
            var isSame = IsString<string?>(); // true
        }

        public static bool IsString<t>()
        {
            return typeof(t) == typeof(string);
        }
    }
```
so how c# known what can must do?
what is your solution?

**Comment by HaloFour** [comment]
`string` and `string?` are the same type.  There is no runtime metadata to differentiate the two, and `Nullable<string>` is illegal as the `T` is constrained to `struct`.

**Comment by rootflood** [comment]
@HaloFour did you even checking before talk?

**Comment by betty-crokker** [comment]
@HaloFour is correct, Nullable<string> is not allowed.

**Comment by betty-crokker** [comment]
So if the regular Type system won't work, what about some new nullability value?

```
#nullable enable
public class Holder<T>
{
    public readonly T Value;
    public Holder(object source, PropertyInfo prop)
    {
        SetValue((T)prop.GetValue(source));
    }
    void SetValue(T value, [Nullability(T)] byte nullability= 0)
    {
      if ((value == null)&&(nullability == some_value))
         throw new Exception("Can't set Holder Value to null");
       Value = value;
    }
}
#nullable disable

```

**Comment by betty-crokker** [comment]
@rootflood There is no solution to my problem with the current version of C#.  I've proposed two solutions in this thread - the one near the top (proposing adding a new attribute [ThrowExceptionIfNullabilityViolated]) and now this latest proposed solution (adding a CompilerServices attribute [Nullability])

**Comment by CyrusNajmabadi** [comment]
> I would say the "NRTs are not supposed to impact the behavior of the code" is "more what you'd call "guidelines" than actual rules." (grin)

To be clear, this was an explicit goal and not something that "fell out".  We very very very intentionally designed and spec'ed with the idea that NRT will not effect runtime behavior.

**Comment by betty-crokker** [comment]
@CyrusNajmabadi I was mostly looking for a reason to slip in a "Pirates of the Caribbean" quote :-)

**Comment by betty-crokker** [comment]
@CyrusNajmabadi and @HaloFour  Does my latest proposal (adding a [Nullability] CompilerServices attribute) smell like it violates the "NRT does not affect runtime behavior" restriction?

**Comment by rootflood** [comment]
@betty-crokker 
imagine that cant work in other assembly
i mean that feature which you told is just before compile
so if you compile some type like "string?" and adding reference that dll which has "string?"
then even via that feature you cant find that Nullable sign because there is no sign in the assembly

**Comment by rootflood** [comment]
@betty-crokker 
but no worry, you can handle it now
let me write:
```c#
    public class SafeNull:Attribute
    { }

    public class Parent
    {
        [SafeNull]
        public string Child{get;set;}
    }
```
that always can work via checking in PropertyInfo 
other solution is cache accepted types in a variable and then check that

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I was mostly looking for a reason to slip in a "Pirates of the Caribbean" quote :-)

🏴‍☠️

**Comment by betty-crokker** [comment]
This discussion got so long, and had several different ideas thrown around, so I've re-submitted it as #3601 for clarity
