### ISSUE TITLE
Proposal: Add NRT attributes to generic type parameters

### ISSUE THREAD

**Issue by betty-crokker** [dotnet/csharplang#3594]
Example:

Dictionary<int, [NotNull] string> myDictionary;

The standard System.Collections.Generic.Dictionary has its TValue type parameter marked as [NullableAttribute(2)] ("may be null") but this allows me to have the compiler help me ensure that I don't put any null values into myDictionary.

**Comment by HaloFour** [comment]
@betty-crokker 

The compiler already tracks a nullability of generic type arguments:

```cs
var dict = new Dictionary<int, string>();
dict.Add(1, null); // <-- warns here
```

**Comment by betty-crokker** [comment]
Argh.  Then I'm confused about NullableAttribute.  If I "Go to Definition" on Dictionary, it shows this:

`public` class Dictionary<TKey, [NullableAttribute(2)] TValue>

and according to various [online ](https://stackoverflow.com/questions/53658961/does-c-sharp-8-annotate-nullable-properties-and-parameters)`https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md`, NullableAttribute(2) means "nullable".

**Comment by HaloFour** [comment]
Yes, the generic type parameter may be nullable, but the compiler will enforce that based on actual usage.  If the generic type argument used for that parameter is non-nullable then the compiler will enforce non-nullability:

```cs
var dict1 = new Dictionary<int, string>();
dict1.Add(1, null); // <-- warns here

var dict2 = new Dictionary<int, string?>();
dict2.Add(1, null); // no warning here
```

**Comment by betty-crokker** [comment]
Interesting.  So let's say I was offline for whatever reason (so I couldn't post to github or stackoverflow), and was wondering whether Dictionary<> allowed the TValue to be null or not.  Is that information documented somewhere?

**Comment by HaloFour** [comment]
There is a `notnull` generic type constraint which can be used to specify that `TValue` can not be a nullable reference type.  If that's not applied then the generic argument can be nullable or non-nullable.  In the case of a generic container like `Dictionary<TKey, TValue>` you can only know based on the actual generic type arguments, the container itself doesn't care.

**Comment by 333fred** [comment]
If you look at intellisense, it'll tell you. The TValue is unconstrained. Therefore, it could be anything you substitute, and you'll be warned if you attempt to use it in a bad way.
Another note: it's not a great idea to try and decode `NullableAttribute` by hand. The compiler has a packing algorithm that requires you to know all the context of the attribute in order to interpret it. Let the IDE do that for you.

**Comment by betty-crokker** [comment]
Doh!  I forgot about the notnull constraint.  Thanks.
