### ISSUE TITLE
More nullable attributes

### ISSUE THREAD

**Issue by NN---** [dotnet/csharplang#3596]
## Background and Motivation

Current nullable attributes doesn't allow to express all control flows.

## Proposed API

```cs
DoesNotReturnIfNullAttribute
DoesReturnIfNullAttribute
```

## Usage Examples

```cs
public static void NotNull([DoesNotReturnIfNull] object? anObject)
public static void Null([DoesReturnIfNull] object? anObject)
```

```cs
void f(object? a, object? b)
{
  NotNull(a); 
  // Here a is object
  var aa = a.ToString(); // OK

  Null(b);
  // Here b is null
  var bb = b.ToString(); // Error
  
  NotNull(b); // Unreachable code
}

```

## Alternative Designs

Didn't find

## Risks

Don't see any risk here.

**Comment by NN---** [comment]
The usage is for assertions libraries.
Current solution is:

```cs
void f(object? a)
{
  NotNull(a); 
  
  var aa = a!.ToString(); // Today must use null assertion operator  since compiler thinks `a` can be null :(
}

```

**Comment by stephentoub** [comment]
> The usage is for assertions libraries.

That's achieved with [NotNull] on the argument, as @KalleOlaviNiemitalo cited.

**Comment by 333fred** [comment]
For example:

```cs
void ThrowIfNull([NotNull] object? param) 
    => _ = param ?? throw new ArgumentNullException();
```

**Comment by NN---** [comment]
Sorry.
Didn’t know it works this way.

**Comment by 333fred** [comment]
Closing out as the question has been answered.

**Comment by NN---** [comment]
How I achieve the opposite behavior ?
I want to say variable is null only if function returns ?

**Comment by 333fred** [comment]
`MaybeNull`

**Comment by NN---** [comment]
Thanks !
Didn't know the attributes work this way.

**Comment by NN---** [comment]
For instance I define method:
```cs
class Assert
{
   public static void Null([MaybeNull] object? anObject)
}
```

Can compiler understand that after calling it `Assert.Null(a);`, the variable `a` is always null ?

**Comment by 333fred** [comment]
It understands that it could be null, which is the same thing from the purpose of nullable analysis.

**Comment by NN---** [comment]
So there is no way to say it is definitely null. Right ?

It could be possible with some new attribute such as DoesReturnIfNullAttribute.

**Comment by yaakov-h** [comment]
What's the point of an attribute that says "this will be null"?

**Comment by NN---** [comment]
This is what exactly `Assert.Null` does in all testing frameworks.

The point is to help analyzers to prevent useless code like:

```cs
Assert.Null(a);

if (a != null)  // Expression is always false
{
  ...
}
```

**Comment by yaakov-h** [comment]
The compiler doesn't do that though, you would have to be using a third-party Analyzer.

And if you have a third-party Analyzer, then you can define third-party attributes, and get what you need in much faster, without needing the LDM, C# compiler changes, C# runtime changes, and C# 10.0 or higher.
