### ISSUE TITLE
[Proposal] Fields scoped to property accessors

### ISSUE THREAD

**Issue by Lehonti** [dotnet/csharplang#3598]
Let's say we have this:

``` cs
class CheckBoxModel : INotifyPropertyChanged {
    
    private bool _checked = false; // No reason other code inside this class should see this field
    public bool Checked {
        get => _checked;
        set {
            _checked = value;
            NotifyPropertyChanged(nameof(Checked));
        }
    }
    
    public event PropertyChangedEventHandler PropertyChanged;
    protected void NotifyPropertyChanged (string name) {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}
```

What about this?

``` cs
class CheckBoxModel : INotifyPropertyChanged {
    
    public bool Checked {
        private bool _checked = false; // Visible to this particular property accessor only
        get => _checked;
        set {
            _checked = value;
            NotifyPropertyChanged(nameof(Checked));
        }
    }
    
    public event PropertyChangedEventHandler PropertyChanged;
    protected void NotifyPropertyChanged (string name) {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}
```

More generally, we could have several 'visibility blocks' inside a single class.

---

As a side note, something could be devised to cut the boilerplate that is currently unavoidable for a property which notifies of changes to itself. The asker of [this question](https://stackoverflow.com/questions/1315621/implementing-inotifypropertychanged-does-a-better-way-exist) on StackOverflow suggested something like `{get; set; notify;}` which is beautiful, but I'm not sure it's the right approach (mainly because I'm wary of language features that depend on a specific library implementation, even if it's in the standard library).

**Comment by HaloFour** [comment]
Check out #133

**Comment by Lehonti** [comment]
Thanks, @HaloFour. I'm going to close this one then
