### ISSUE TITLE
Allow nameof to be used with a generic class without declaring the generic type

### ISSUE THREAD

**Issue by Rand-Random** [dotnet/csharplang#3606]
This is currently impossible

    nameof(HashSet<>.Count)

You will have to write 

    nameof(HashSet<string>.Count)

Since `HashSet<>` is valid in 

    typeof(HashSet<>)

I was surprised to see it not working in `nameof`.

**Comment by huoyaoyuan** [comment]
Duplicate of #702

**Comment by Rand-Random** [comment]
@huoyaoyuan 
Sorry for the duplicate, shouldn't have given up hope as I searched and looked only at the results of the first page.
Your issue was on the second page.
