### ISSUE TITLE
[Question] The keyword designing

### ISSUE THREAD

**Issue by Sunnie-Shine** [dotnet/csharplang#3609]
Hi friends. There are two questions about keyword designing that I am stuck in.

The first one is, why keyword `group by` clause consist of two keywords, but `orderby` is not?

We using extension methods will write like this:

```csharp
var selection1 = people.GroupBy(person => person.Age);
var selection2 = people.OrderBy(person => person.Age);
```

They're both written like `xxx.xxxBy(lambda)`, but the Linq expression of those two are different:

```csharp
// With a field between `group` and `by`.
var selection1 = from person in people group person by person.Age;
// No field between `order` and `by`.
var selection2 = from person in people orderby person.Age/* ascending or descending */;
```

The second question. The keyword `notnull`, a generic constraint, is a combined one used to indicate the generic type cannot contain `null` value. In C# 9, we introduce the keyword `not`, so `not null` is a pattern as a null-value checking pattern.

However, as a beginner for C# language, I'm always confuse about `notnull` and `not null` these two. I know they are raised
with time difference, but why `notnull` cannot also be a keyword used for null-value checking? Or else `not null` why not be a
generic constraint?

I'm looking forward to the answer about them. Thanks! 😃

**Comment by huoyaoyuan** [comment]
At my sight, the designs are consistent: if it's a monolithic word at semantic level, it will be one keyword. The situation is avoided that two keywords must be used together.

For the LINQ case:
There is something to write with in `group by`, so they have to be two words. But it's not the case in `orderby`.

For `notnull`:
The one used in generic constraint is a monolithic word, because there's no logical concept in constraint. As opposed, `not null` in pattern matching is really two syntax tokens. The `not` can be followed by any pattern.

**Comment by Sunnie-Shine** [comment]
> At my sight, the designs are consistent: if it's a monolithic word at semantic level, it will be one keyword. The situation is avoided that two keywords must be used together.
> 
> For the LINQ case:
> There is something to write with in `group by`, so they have to be two words. But it's not the case in `orderby`.
> 
> For `notnull`:
> The one used in generic constraint is a monolithic word, because there's no logical concept in constraint. As opposed, `not null` in pattern matching is really two syntax tokens. The `not` can be followed by any pattern.

Thanks for your explanation. I think your opinions are right and reasonable. 😆 C# is a powerful and efficient programming language, but the architecture of its syntax is too huge. 😢
