### ISSUE TITLE
Alternative syntax for null parameter checking

### ISSUE THREAD

**Issue by theunrepentantgeek** [dotnet/csharplang#3620]
I realize the [2020-06-17](https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-17.md) and [2020-06-24](https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-24.md#Parameter-Null-Checking) have at this point agreed on the `!!` syntax for null parameter validation. 

I'm hopeful that this can be changed.

It's nigh on traditional by now (at least, there's a lot of precedent) for the person in my position disagreeing with those on the LDM to post a long winded offensive rant containing personal attacks on everyone who's ever been involved in decision making on the language. 

Instead of taking that misjudged aggressive approach, I'm going to try something else ... a constructive argument. 

In the [context of null reference types](https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-csharp/), @MadsTorgersen wrote:

> Naively, this suggests that we add two new kinds of reference types: “safely nonnullable” reference types (maybe written string!) and “safely nullable” reference types (maybe written string?) in addition to the current, unhappy reference types.
> We’re not going to do that. 
> [omitted]
> In a certain weird way we want something that’s more intrusive in the beginning (complains about current code) and less intrusive in the long run (requires fewer changes to existing code).

There were a bunch of other blog posts and discussions prior to November 2017 where the potential syntax for NRT was **string** (for null-oblivious), **string?** for nullable, and **string!** for non-nullable, though I've been unable to find references over the last couple of days.

As I recall it, there were two major reasons not to go with the **string!** syntax:

* A desire to allow easy migration of existing code (having to explicitly mark every type as not-nullable would be labour intensive and error prone; many projects would therefore never migrate).
* A view that suffixing `!` all over the code suffered from the problem of "making the new feature stand out", introducing a wart in the language.

BTW, that's a reference to a blog post by @gafter , [*Making new language features Stand Out*](http://gafter.blogspot.com/2017/06/making-new-language-features-stand-out.html):

> There is a phenomenon I've noticed in the way community members react to proposed new language features. The new feature seems odd, and different, and contrary to the way the language was before. So they want the syntax of the feature to be odd, and different, and clearly distinguish the new feature from all of the old features of the language.

Suffixing parameter identifiers all over the code with `!!` seems like it is doing both of these things: choosing a syntax that deliberately!! stands!! out!!, and doing something in a way that differs from what goes before.

Another issue with the `!!` syntax is that it's closed - unlike the vvast majority of enhancements that have been made to the C# language, it's a dead end that does exactly one thing (albeit a thing that's commonly needed).

A side observation - in some ways the discussion feels like everyone has just gotten tired, they agree that the feature is useful, and they're settling for a mediocre syntax because *some* solution is better than *no* solution. I may be reading things completely wrong here, and I duly apologise if I've made that mistake. 

In the spirit of suggesting solutions, rather than just pointing out problems, I'd like to highlight one of the forms mentioned in the [2020-06-17](https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-17.md): Using the existing **when** keyword:

Taking the example from #2145:

``` csharp
// Before
void Insert(string s)
{
    if (s is null)
    {
        throw new ArgumentNullException(nameof(s));
    {
    ...
}

// After
void Insert(string s)
    when s is not null
{
  ...
}
```

* To me (with 16 years of C# experience) this *feels* like C#, where `s!!` does not. Still, I understand that this is a vague and nebulous thing, and others will disagree with me.
* The code is still substantially shorter than the original, especially when formatted in [Allman style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) the way that Visual Studio does by default.
* Experienced C# developers who read this are likely to be able to guess what this does - conforming to Scott Guthrie's goals of having a "pit of success"; the syntax doesn't need to be memorized or looked up. 
* Best of all, the expression that follows the **when** keyword can be *any boolean expression*. This isn't code contracts, it's just parameter validation - but it naturally allows other checks without requiring any new syntax. A higher ROI for the effort of changing the language.

``` csharp
void Insert(string s)
    when !String.IsNullOrEmpty(s)
{
  ...
}
```

One last thought ... maybe using **where** would make more sense ... generalizing the existing **where** clause that's already present:

``` csharp
// After
void Insert(string s)
    where s is not null
{
  ...
}
```

Anyway, thanks for taking the time to read to the end! I (fervently!) hope this comes across in the constructive way that I intend.

**Comment by BhaaLseN** [comment]
I'm impartial to the `!!` syntax at this point, but I kinda like the proposed option here because it lets me specify _other_ reasons for rejecting a parameter.

Especially for strings, we often treat `null` and `string.Empty` the same (because in the end, it isn't a string with at least one character that can be used for something) yet prefer `ArgumentNullException` over `ArgumentException` there (mainly to reserve `ArgumentException` for business requirements like matching a pattern, starting with a prefix or whatever; vs. being empty).

On the other hand, this reasoning seems heavily geared towards `string` with very little use for other classes - _unless_ it also had a way to specify the exception being thrown. But at that point, we're somewhere around code contract territory or might as well just write the classic code inside the method that we used to.

**Comment by eyalsk** [comment]
@theunrepentantgeek Feels like DbC but then when and if they gonna introduce it into the language how would you express something like a postcondition? if anything this should be `requires` and `ensures`.

**Comment by HaloFour** [comment]
The LDM explicitly considered a variant of the syntax you're suggesting here, so I don't know why this issue would make them reconsider.  It's not really adding anything new to consider.  As for tying it to method contracts, that's an idea that hasn't moved what, 6 years?

As for the suffix argument around NRTs, null parameter validation is orthogonal to NRTs.  You'll be able to use it outside of a `#nullable enabled` context.  Unlike most of the other forms, it's also one where the syntax would allow use in the middle of an expression within the code, which is called out in the meeting notes.  Every other alternative proposed was limited specifically to the method signature.

**Comment by eyalsk** [comment]
@HaloFour The syntax suggests that you can do more than null checking so I'm not really tying it to anything but factually the syntax does and DbC hasn't moved for ~6 years but it's still championed and this has to mean something, I hope.

**Comment by HaloFour** [comment]
@eyalsk 

> The proposed syntax suggests that you can do more than null checking so I'm not really tying it to anything but factually the syntax does.

Yes it does, but that's the problem with it.  You can't design only the nullability checking aspect of method contracts and ship it.  Method contracts have a _lot_ of other baggage that needs to be ironed out.  For example, the principle proponent on the C# team who has championed that issue since pretty much Roslyn went open source advocated that a violated contract fail fast, not throw an exception.  That was a major point of contention, as it would be here.  Method contracts aren't remotely at a point where _any_ part of it could be shipped.

The C# team has also expressed that they like the idea that `!!` could be used _within_ a method to arbitrarily enforce a null check, which is something that a method contract like syntax could not accomplish.

**Comment by eyalsk** [comment]
@HaloFour Yeah, I mostly agree with you.

> Method contracts are also supposed to be elided on release builds, so you lose any and all of the enforcement that null parameter checking is supposed to provide.

Can be tuned, at least Code Contracts gave you the option to do so.

> The C# team has also expressed that they like the idea that !! could be used within a method to arbitrarily enforce a null check, which is something that a method contract like syntax could not accomplish.

I'm not against the idea of `!!` even though like the OP and some other people I dislike the syntax I know that this feature and DbC are independent but I brought it up because again the proposed syntax suggests more than just a null check at runtime.

**Comment by CyrusNajmabadi** [comment]
> One last thought ... maybe using where would make more sense ... generalizing the existing where clause that's already present:

We considered many possible designs, including things like dbc and other forms very similar to what you propose.  There was practically no support for it, even when people were able to vote on *all* the approaches they were interested in seeing.

**Comment by CyrusNajmabadi** [comment]
> it's a dead end that does exactly one thing (albeit a thing that's commonly needed).

I don't feel that that is the case. While `!` is the suppress null operator, `!!` is the enforce operator. So I see it being usable elsewhere as the short hand for: blow up immediately if things go awry.

**Comment by CyrusNajmabadi** [comment]
> A side observation - in some ways the discussion feels like everyone has just gotten tired, they agree that the feature is useful, and they're settling for a mediocre syntax because some solution is better than no solution. I may be reading things completely wrong here, and I duly apologise if I've made that mistake.

I honestly don't know where that is coming from. I think it's really simple: people like `!`, but there was enough sympathy around the problem of `!` being silent in method bodies, but being the opposite on a parameter. So we brainstormed many student approaches here and landed in `!!` as the most liked option. 

It also seemed to fit c# and our heritage. I.e. having both single and double character versions of operators like `&` and `&&`, or `+` and `++`.

**Comment by yaakov-h** [comment]
> I don't feel that that is the case. While `!` is the suppress null operator, `!!` is the enforce operator. So I see it being usable elsewhere as the short hand for: blow up immediately if things go awry.

What could `!!!` be then? fail-fast? 😄

**Comment by rafaelsc** [comment]
I really think the C# needs to should some syntax that is future proof. And to me `!!` is not future proof. Because in the future I want more power from the language.

I'm a real fan of the old [CodeContracs ](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/code-contracts). And I would love to see CodeContracs be integrated in the language like in [Spec#](https://en.wikipedia.org/wiki/Spec_Sharp)

And I think null parameter checking should have a system using a contract-like syntax, to enable adding more contracts checking in the C#.

This system should be similar to the **Spec#** or like the theunrepentantgeek  suggestion or this https://github.com/dotnet/csharplang/issues/2145#issuecomment-454423292

**Comment by rafaelsc** [comment]
Related discussion: https://github.com/dotnet/csharplang/issues/2145

**Comment by CyrusNajmabadi** [comment]
Contracts were explaining considered by the ldg here and we're explicitly rejected as being overkill for this. We did not want a simple concept like this to take an excessive amount of loc. If it helps, think of this as complimentary to contracts. If we ever added contracts, then `!!` would still be shorthand for 'not null' in contract-eze

**Comment by theunrepentantgeek** [comment]
I deliberately stayed out of this discussion as I'd said my piece when I opened this issue. I also didn't want to go in circles relitigating issues that had already been discussed ad nauseum elsewhere. 

In the interests of keeping things tidy, I'm going to close this issue. Thanks everyone for their thoughts.

**Comment by tagcode** [comment]
I don't know why annotation has been disqualified as possible solution. [NotNull] is more elequent than '!!', and removes need for another syntax token. Compiler could inject invocation to attribute.Inspect(ref stack-address, "action"). 
```C#
void Do([NotNull] string action)
{
}
```

There could be ParameterAttribute&lt;T&gt; for validation of different sorts.
```
System.Attribute
└── System.ParameterAttribute<T>
      └── System.NotNullAttribute
```

ParameterAttribute<T> has reusability.
```C#
[AttributeUsage(System.AttributeTargets.Parameter, Inherited=true)]
public abstract class ParameterAttribute<T> : Attribute
{
    [DebuggerHidden]
    public abstract void Inspect(ref T value, string parameterName);
}

public class NotNullAttribute : ParameterAttribute<object> where T : class
{
    [DebuggerHidden]
    public override void Inspect(ref T value, string parameterName)
    {
        if (value is null) throw new ArgumentNullException(parameterName);
    }
}
```


There could be [NotDefault] for value-types.

```C#
void Do([NotDefault<int>] int id)
{
}
```

Inherited from ParameterAttribute as well.
```
System.Attribute
└── System.ParameterAttribute<T>
      └── System.NotDefaultAttribute
```

```C#
public class NotDefaultAttribute<T> : ParameterAttribute<T> where T : class
{
    [DebuggerHidden]
    public override void Inspect(ref T value, string parameterName)
    {
        if (value is default) throw new ArgumentNullException(parameterName);
    }
}
```

**Comment by CyrusNajmabadi** [comment]
>  don't know why annotation has been disqualified as possible solution. [NotNull] is more elequent than '!!', and removes need for another syntax token. Compiler could inject invocation

`[NotNull]` already has meaning (compile time only, no runtime impact).  So we would not be able to change the meaning there.
