### ISSUE TITLE
Records and debugger display

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3625]
It would be really nice if records also provided an auto implemented virtual DebuggerDisplay property that showed the Key properties.  It would make viewing the object in the debugger so much more useful.

**Comment by jnm2** [comment]
Yes, very glad you filed this. I think implementing ToString would automatically create the debugger display that I'd expect to see.

**Comment by HaloFour** [comment]
My concerns with implementing this as `ToString` is that it may expose information by default that shouldn't be exposed and that it represents another way in which records will diverge from structs, which currently return their type name.  I could see there being more value having the compiler spit out a private debugger display method, or even just having the tooling recognize that the type is a record and to display the elements as if there was a debugger display method.

**Comment by TonyValenti** [comment]
Speaking frankly, I really wish that .NET made a lot more extensive use of DebuggerDisplay.  I really feel as though nearly every object should have one that at least provides some summary information.

**Comment by theunrepentantgeek** [comment]
Just including an automatic `[DebuggerDisplay]` attribute on each record would be super useful. 

I agree with @HaloFour though, that an automatically generated `ToString()` is risky - it could lead to the exposure of PII, for example.

**Comment by MgSam** [comment]
ToString is useful for logging as well as debugging. It sucks that to log records we'll have to manually write / generate ToString.

Frankly, any of the currently available solutions have problems. To really solve nicely this we'd need either a keyword or for the team to re-open the book on AOP in the future.

**Comment by YairHalberstadt** [comment]
ToString is automatically implemented so this should no longer be necessary.
