### ISSUE TITLE
Proposal: Not condition in switch statement.

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [dotnet/csharplang#3635]
# Summary 

This proposal adds a way to exclude a value from a case in a switch statement or expression without using a when clause.

# Motivation

Consider two arbitrary enums in an arbitrary situation:

```
enum Level 
{
  Low,
  Medium,
  High
}

enum Speed
{
  Slow,
  Medium,
  Fast
}
```

With switch statements in C# you have a default case with the following :
 ```
switch (Level, Speed)
{
    case (Level: Level.Low, Speed: _ ):
        return true;
}
```

But there's currently no way to exclude a value from a case statement:  *
```
switch (Level, Speed)
{
    case (Level: Level.Low, Speed: !Speed.Fast):
        return true;
}
```

The current solution to this problem is to add all the values as cases which is not maintainable or scalable: *
```
switch (Level, Speed)
{
    case (Level: Level.Low, Speed: Speed.Slow):
    case (Level: Level.Low, Speed: Speed.Medium):
        return true;
}


```
The proposal is the same for the switch expression:
```
return (Level, Speed) switch
{
    (Level: Level.Low, Speed: !Speed.Fast) => true;
}
```
vs
```
return (Level, Speed) switch
{
    (Level: Level.Low, Speed: Speed.Slow) => true,
    (Level: Level.Low, Speed: Speed.Medium) => true
}
```

## * **Please note:**
I understand you can use a when clause in a switch expression such as in the following example:
```
return (Level, Speed) switch
{
    var (level, speed) when level == Level.Low &&  speed != Speed.Fast => true;
}
```
But this makes for a lot of code to do something simple and decreases the readability of the code by increasing the mental math necessary as can be seen in the following examples:
```
return (Level, Speed) switch
{
    (Level.Low,    !Speed.Fast)   => true,
    (Level.Medium, !Speed.Medium) => true,
    (!Level.High,  !Speed.Fast)   => false
}
```
vs 
```
return (Level, Speed) switch
{
    var (level, speed) when level == Level.Low     &&  speed != Speed.Fast   => true,
    var (level, speed) when level == Level.Medium  &&  speed != Speed.Medium => true,
    var (level, speed) when level != Level.High    &&  speed != Speed.Fast   => false
}
```

_Imagine adding another enum into the switch expression..._

**Comment by ufcpp** [comment]
already implemented in C# 9.0

```cs
            (Level.Low, not Speed.Fast) => true,
            (Level.Medium, not Speed.Medium) => true,
            (not Level.High, not Speed.Fast) => false
```
