### ISSUE TITLE
Make <summary> optional in XML doc comments

### ISSUE THREAD

**Issue by lostmsu** [dotnet/csharplang#3637]
These make writing documentation in a nicer way in F#: [F# single-line xmldoc](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation#example-1).

The proposal is to treat
```csharp
/// This is a great function,
/// that does good
void DoGood() => ...;
```
the same way as
```csharp
/// <summary>This is a great function, that does good</summary>
void DoGood() => ...;
```

**Comment by jnm2** [comment]
This would be a consequence of any of these existing issues:
https://github.com/dotnet/csharplang/issues/878
https://github.com/dotnet/csharplang/issues/891
https://github.com/dotnet/csharplang/issues/2394

**Comment by sharwell** [comment]
Duplicate of #2394

**Comment by YairHalberstadt** [comment]
Closing as duplicate of #2394
