### ISSUE TITLE
Ability to create a "scope" block

### ISSUE THREAD

**Issue by shlomisderot** [dotnet/csharplang#3643]
I thought to borrow some Javascript feature, kind of Javascript closure mechanism.

It will be nice if I could create a "scope" block where I can use the same variables name inside the block and use "shared" variables inside each block,

From the following example, I declared a two "scope" blocks, in each one I declared a string variable called "local", and both blocks use shared variable called "shared"

Example code:

            string shared = "from shared";

            scope {
                string local = "local 1";
                System.Console.WriteLine($"{shared} - {local}");
            }

            scope {
                string local = "local 2";
                System.Console.WriteLine($"{shared} - {local}");
            }

Expected output:

            // from shared - local 1
            // from shared - local 2

I think this can raise the code consistency, this can make the maintenance more easier,  and of course, it will reduce the use of #region if you can expand/collapse the "scope" blocks

**Comment by chrisoverzero** [comment]
This [is already possible][sharplab] with no keyword, even.

[sharplab]: https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQiAM7EGYAEA3uvqfogkSWTXEpvgM4AWAhmAKYAm+AvPgCIAZmAD2AWyZtOXAQG501GqWJpl68vXwAbUQGNW2voN0GjSeUo2k6ATgAUAEgGEW7bgF98AWiKnDHgIAlApqGh6KYeqq1rRa/kb8Agn4CJZRsXZOLm4yXr6ECYEhVjQRGeUeQA=

**Comment by 333fred** [comment]
Closing as implemented since C# 1.0 🙂
