### ISSUE TITLE
Records should allow attributes on the primary constructor

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/csharplang#3650]
Slightly related to dotnet/roslyn#44691

Currently there is no way to declare attributes on the primary constructor of a record.

```cs
[Attr] // ... no target or distinct syntax exists for the primary constructor
record Rec(int X, int Y);
```

If we decide to allow declaring an explicit "body" for a primary constructor, we could make it so attributes may be applied to that syntax which solely corresponds to the constructor.

```cs
record Rec(int X, int Y)
{
    data int Z;

    // strawman "body" syntax with an attribute:
    [Attr]
    {
        Z = X + Y;
    }
}
```

**Comment by HaloFour** [comment]
Sounds like we need more attribute targets?

```cs
[constructor: Attr]
public record Rec(
    [property: Foo] int X,
    [field: NonSerialized] int Y
);
```

**Comment by 333fred** [comment]
We had a discussion on the internal mailing list, and the sentiment seemed to be preferring `method` as the target. It's already the target you use on constructors today:

```
 using System;
[AttributeUsage(AttributeTargets.Constructor)]
public class Attr : Attribute{}
public class C {
    [method: Attr]
    public C()
    {
    }
}
```

**Comment by bbarry** [comment]
Would it make sense that `[method:...]` attributes added to the class would get attached to all constructors in general?

**Comment by RikkiGibson** [comment]
I would not attach such attributes to any explicitly declared constructors within the record. One could argue that such attributes should be attached to the synthesized copy constructor as well as the primary constructor, though. I personally do not see utility in this because I see the copy constructor as an implementation detail of with-expressions that users should not need to customize.
