### ISSUE TITLE
'typeof(T).FullName' is never null

### ISSUE THREAD

**Issue by sharwell** [dotnet/csharplang#3664]
**Version Used**: 3.7, targeting netcoreapp3.1

**Steps to Reproduce**:

```csharp
#nullable enable

class C
{
  string TypeName => typeof(C).FullName;
}
```

**Expected Behavior**:

No warning is reported for the expression returned from `TypeName`.

**Actual Behavior**:

> warning CS8603: Possible null reference return.

**Additional Information**:

While the `FullName` property can return `null` in some cases, it cannot return null for the syntax seen here. There is no way to annotate the property as having a non-null value conditioned on language-specific syntax producing the `Type` instance.

**Comment by Joe4evr** [comment]
Asked about this some time ago myself. Stephen gave a good explanation: https://github.com/dotnet/runtime/issues/31558#issuecomment-557932606
