### ISSUE TITLE
Make anonymous types castable to tuples

### ISSUE THREAD

**Issue by Happypig375** [dotnet/csharplang#368]
As tuples are introduced in C# 7, will it make anonymous types obsolete?
No, of course!
Consider:
```
using static System.Console;
var Anonymous = new { X = 10, Y = 12.5 };
var Tuple = (X: 10, Y: 12.5);
var ClassicTuple = System.Tuple.Create(10, 12.5);

//Read the object (Anonymous prints out the names)
WriteLine(Anonymous); //{ X = 10, Y = 12.5 }
WriteLine(Tuple); //(10, 12.5)
WriteLine(ClassicTuple); //(10, 12.5)

//Read a value (Tuple has two fields for the same value)
WriteLine(Anonymous.X); //10
WriteLine(Tuple.X); //10
WriteLine(Tuple.Item1); //10
WriteLine(ClassicTuple.Item1); //10

//Write a value?
Anonymous.Y = Anonymous.X; //error CS0200: Property or indexer '<anonymous type: int X, double Y>.Y' cannot be assigned to -- it is read only
Tuple.Y = Tuple.Item1; //Success
ClassicTuple.Item2 = ClassicTuple.Item1; //error CS0200: Property or indexer 'Tuple<int, double>.Item2' cannot be assigned to -- it is read only
```
Anonymous types: immutable with arbitrary names
System.ValueTuple: mutable with arbitrary names
System.Tuple: immutable without arbitrary names

So, anonymous types and tuples both have their own strengths and weaknesses.

However, tuples can be parameters of a method and anonymous types can't:
`void UseTuple(((int A, int B, int C) Inner, int D) Tuple)`

Therefore, some way to put an anonymous type into a tuple parameter would be nice.
`var Anon = new { Inner = new { A = 0, B = 1, C = -1 }, D = int.MaxValue };`

**Option 1: Implicit type conversion**
`UseTuple(Anon);`
Pro: Less typing
Con: A narrowing conversion should not be implicit

**Option 2: Explicit type conversion**
`UseTuple((((int A, int B, int C) Inner, int D))Anon);`
Pro: Be explicit about using the cast
Con: More typing

**Option 3: Extension method**
`UseTuple(Anon.ToTuple());`
Pro: "Oh, I'm casting it to a tuple"
Con: Can't be easily implemented

**Option 4: Simply allow an anonymous type to be a parmeter**
`void UseTuple(new { new { int A, int B, int C } Inner, int D } Tuple)`
Alternative syntax: `void UseTuple({{ int A, int B, int C } Inner, int D } Tuple)`
Pro: Straightforward
Con: Curly brackets in parameter declarations

**Comment by svick** [comment]
What is the point? Why would you create an anonymous type if you know the method takes a tuple?

**Comment by wanton7** [comment]
Anonymous types are not obsolete you can't example serialize tuples. Well you can but if I understood correctly it will serialize it with Item1... fields.

Also you can already call method Foo that takes tuple of (string a, string b) with Foo((a: "1", b: "2"));

If you care about performance, when creating anonymous type you are creating new instance that garbage collector needs to collect. But tuple just uses value type ValueTuple that's allocated from stack.

**Comment by Happypig375** [comment]
As this suggestion is disliked with good reasons, I might as well close this issue.
