### ISSUE TITLE
readonly generic constraint

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/csharplang#3691]
Consider

```c#
public static T M<T>(T t){ return default; }
```
Something which is not allowed
```c#
public static T M2<T>(T t) where T : readonly { return default; }
```
Another thing that is allowed but has a hole IMHO
```c#
public static T M<T>(in T t){ return default; }
```
Specifically 
```c#
public static T M<T>(in T t) where T : struct { return default; }
```

Uninteresting code
```c#
public static T M<T>(in T t) where T : struct { return default; }
    public void M() 
    {
        var m = M<int>(default);
        Console.WriteLine(m);//0 (0x00000000)
    }
```

I propose that the `readonly` generic constrain be created such that if the type is not `readonly` or passed by `in` that the compiler should throw a warning CSXXX otherwise should compile as allowed.

The spec should be modified if required such that if a method in which `return default` is used in the aforementioned scenario and the param is not passed by `in` or declared `readonly` then the result should be `null` otherwise the `in` value and not another `new default` value

 Motivation memory protection semantics can be built around this inter alia

To be combined with the other proposed or existing constrains such as but not limited to `struct` or `interface`

Possibly make `readonly` available as a method keyword everywhere.

**Comment by yaakov-h** [comment]
why is returning default from a method a "hole" in `in`?

**Comment by juliusfriedman** [comment]
because we allocate for the supposed given already allocated value.

**Comment by yaakov-h** [comment]
... would you care to elaborate? That still doesn't make sense.

**Comment by juliusfriedman** [comment]
What does't that we do something we should not?

**Comment by canton7** [comment]
I can see an *argument* for allowing:

```cs
public interface IS { void Foo(); }
public readonly struct S { public void Foo() { } }

public void M<T>(in T s) where T : readonly, IS
{
    s.Foo(); // Doesn't make a defensive copy of 's'
}
```

However: 

1. I suspect #3055 is a better way of doing this, and
2. That doesn't seem to be what this proposal is about *anyway*

----------------------------

In fact, I'm having a very hard time trying to understand what's being proposed. Let me walk through my confusion:

> if a method in which return default is used in the aforementioned scenario

OK, so we've got a generic method with a `where T : readonly` constraint. Presumably this implies `where T : struct`, since only structs can be readonly?

> and the param is not passed by in or declared readonly

Is this meant to parse as "and (the param is not passed by in) or (declared readonly)" or should it be "and (the param is not (passed by in) or (declared readonly))"? Params can't be "declared readonly" anyway, so I'm going to ignore that bit for now and read it as "and the param is not passed by in".

OK, so we're looking at a method like:

```cs
public T M<T>(T t) where T : struct, readonly
{
    return default;
}
```

> then the result should be null

Wait, what? `T` has to be a struct. Structs can't be null.

> otherwise the in value and not another new default value

What does "the result should be null otherwise the in value" mean? What determines whether `default` produces `null` or "the in value"? What even is "the in value", since we're describing a method which doesn't have any `in` parameters?

**Comment by juliusfriedman** [comment]
I am good with https://github.com/dotnet/csharplang/issues/3055 doing what it does there, here is different.

**Comment by canton7** [comment]
What does `readonly` have to do with returning values from a method?

C# already has `readonly` methods, they were introduced before `readonly struct`.

**Comment by juliusfriedman** [comment]
> What does `readonly` have to do with returning values from a method?
> 
> C# already has `readonly` methods, they were introduced before `readonly struct`.

Where does one read about the semantics of `readnly` methods tbh not that familiar.

**Comment by canton7** [comment]
A `readonly struct` is just a struct where all members are `readonly` (it enforces that all fields are `readonly`, and implicitly makes all methods `readonly`). [See here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/readonly-instance-members)

**Comment by juliusfriedman** [comment]
> A `readonly struct` is just a struct where all members are `readonly` (it enforces that all fields are `readonly`, and implicitly makes all methods `readonly`). [See here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/readonly-instance-members)

I know about readonly strcuts, I need to learn about readonly methods. I cannot find any ref to this in the docs you linked can you cite the ecma spec part?

**Comment by mikernet** [comment]
> no return other that t should be made due to the readonly constraint.

So are you saying that `return default` would actually `return t`?

**Comment by mikernet** [comment]
From what I understand you're saying you don't want the `in T t` value to be copied and returned because it is already on the caller's stack?

**Comment by canton7** [comment]
I linked the spec proposal -- that's the best we have. We only have an ECMA spec for C# 5.

The "Motivation" section lays it out. [This doc](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code) talks about it a bit as well.

`readonly` structs and methods are used with the `in` modifier. `in` passes in the struct by reference, but it also promises that the copy of the struct owned by the caller won't be modified by the method. In order to ensure this, the compiler would normally insert defensive copies of the struct whenever one of its fields is changed, or one of its methods is called (because the compiler doesn't know whether a method might mutate the struct), so that any mutations happen to a copy, not the original held by the caller.

For example:

```cs
public class C
{
    public void Test()
    {
        S original = new S();
        M(in original);
    }
    
    public void M(in S s)
    {
        s.NonReadonly();
    }
}

public struct S
{
    public void NonReadonly() { }
}
```

[SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLIN7LpGYZQAs6AKgKYDOALgBQCUhxBSxX6AyugPYAnAJYBzYQDsAhgBt0AXnQTqAd14sA3G27oAso0kCR46TOZbOxAL7b0ttJgr7DfWq0tEOOorQB0AOX4JACVqKWAgmQBPTVsbJHjkBwZBAFcAY3pefHtSCkCQsIiJaJZ0PHR4qyA)

The compiler inserts a hidden copy of `s` just before calling `NonReadonly()`, so that if `NonReadonly` mutates the struct, then `original` isn't changed.

If you give the struct a `readonly` method, then the compiler ensures that it cannot mutate the struct. This means that it's free to call the method without making a hidden copy:

```cs
using System;
public class C
{
    public void Test()
    {
        S original = new S();
        M(in original);
    }
    
    public void M(in S s)
    {
        s.Readonly();
    }
}

public struct S
{
    public readonly void Readonly() { }
}
```

[SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLIN7LpGYZQAs6AKgKYDOALgBQCUhxBSxX6AyugPYAnAJYBzYQDsAhgBt0AXnQTqAd14sA3G27oAso0kCR46TOZbOxAL7b0ttJgr7DfWq0tEOOorQB0AJWopYH4JGQBPTVsbJBjkBwZBAFcAY3pefHsMQSCQsPDHdEDg0IiWdDx0GKsgA==)

There's no hidden copy of `s` here.

A `readonly` struct will make all of the struct's methods `readonly` (and ensures that all fields are `readonly`), so you don't need to put `readonly` on each and every method.

**Comment by mikernet** [comment]
> From what I understand you're saying you don't want the in T t value to be copied and returned because it is already on the caller's stack?

Follow-up: is it possible that during inlining the JIT elides this? I don't know.

**Comment by juliusfriedman** [comment]
Ewww this is on struts only? why?

**Comment by canton7** [comment]
... because you can have `readonly struct` but not `readonly class`, and can't have `readonly` methods on a class? Because the entire point of `readonly` types is around `in` and passing structs by reference?

**Comment by juliusfriedman** [comment]
> ... because you can have `readonly struct` but not `readonly class`, and can't have `readonly` methods on a class? Because the entire point of `readonly` types is around `in` and passing structs by reference?

You miss the point, I have a struct I pass by in

**Comment by canton7** [comment]
Then why did you say 

> Ewww this is on structs only? why?

?

**Comment by juliusfriedman** [comment]
> Then why did you say
> 
> > Ewww this is on structs only? why?
> 
> ?

Because why, any method should be able to designate `readonly` on return.

**Comment by HaloFour** [comment]
`readonly` structs+methods exist to inform the compiler to not make defensive copies of the struct for the sake of guarding against in-situ modification.  Classes can't be defensively copied.  The `in`/`readonly ref` is just a `ref` where the developer is promising that they are not attempting to modify the struct.

The `T` passed into the generic method by-ref has nothing to do with the value returned from the method, so I don't really understand what this proposal is attempting to accomplish.  Returning anything other than `default(T)` would be wrong.  Even returning a `ref T` of the `in T` would be wrong as that breaks the promise that the struct cannot be modified as the callee cannot make any guarantees about the caller.  At best you'd need `in` returns to extend that promise to the caller.

**Comment by canton7** [comment]
> Because why, any method should be able to designate readonly on return.

What do you mean by "on return"? `readonly` has nothing to do with returns.

**Comment by juliusfriedman** [comment]
> `readonly` structs+methods exist to inform the compiler to not make defensive copies of the struct for the sake of guarding against in-situ modification. Classes can't be defensively copied. The `in`/`readonly ref` is just a `ref` where the developer is promising that they are not attempting to modify the struct.
> 
> The `T` passed into the generic method by-ref has nothing to do with the value returned from the method, so I don't really understand what this proposal is attempting to accomplish. Returning anything other than `default(T)` would be wrong. Even returning a `ref T` of the `in T` would be wrong as that breaks the promise that the struct cannot be modified as the callee cannot make any guarantees about the caller. At best you'd need `in` returns to extend that promise to the caller.

I like readonly structs.

**Comment by juliusfriedman** [comment]
> > Because why, any method should be able to designate readonly on return.
> 
> What do you mean by "on return"? `readonly` has nothing to do with returns.

Perhaps it should in some cases where I return the `in`

**Comment by HaloFour** [comment]
Ah, so you want something like this:

```cs
    public readonly ref T M<T>(in T v) where T : struct {
        return ref v;
    }
```

**Comment by canton7** [comment]
I'm trying to get you to explain how you think `readonly` relates to returns, because I and others are really struggling to understand what you *want*

**Comment by juliusfriedman** [comment]
> Ah, so you want something like this:
> 
> ```cs
>     public readonly ref T M<T>(in T v) where T : struct {
>         return ref v;
>     }
> ```

I could palette that.

**Comment by HaloFour** [comment]
Nod, this interrogation/negotiation style of "proposal" is exhausting.

**Comment by canton7** [comment]
I considered `readonly ref`, but none of this examples in the OP have `ref` in them

**Comment by mikernet** [comment]
Is this kinda what you want?

```c#
public static in T M<T>(in T t) where T : struct { return t; }
```

Where the return value must be an `in T` value so that the `in` ref can just be return without a copy?

**Comment by juliusfriedman** [comment]
> I considered `readonly ref`, but none of this examples in the OP have `ref` in them, so I assumed that wasn't what they were asking about.

I can add them it just makes it harder or worse imho

**Comment by canton7** [comment]
It can't be more confusing than what you have already 😈 

Is it correct that you want to be able to write something like this:

```cs
public ref T M<T>(ref T v) where T : struct {
    return ref v;
}
```

But where the parameter is `in`, not `ref`?

**Comment by mikernet** [comment]
> I think AFG

What's AFG? I haven't heard that one before. Sorry if I'm just illiterate with internet speak

**Comment by juliusfriedman** [comment]
I like that example and will say yes but I really like @mikernet example also

```c#
public static in T M<T>(in T t) where T : struct { return t; }
```

Although I would prefer to read it as

```c#
public static readonly T M<T>(in T t) where T : struct { return t; }
```

**Comment by juliusfriedman** [comment]
> > I think AFG
> 
> What's AFG? I haven't heard that one before. Sorry if I'm just illiterate with internet speak

At first glance, sorry

**Comment by canton7** [comment]
> ```cs
> public static readonly T M<T>(in T t) where T : struct { return t; }
> ```

The problem here is that you're returning a pointer to a struct, but `readonly` does not in any way imply a pointer. `ref`, `in` and `out` imply pointers.

**Comment by HaloFour** [comment]
Initially the syntax for `in` was proposed to be `readonly ref`.  It was changed to `in` to make it more ergonomic despite being a somewhat niche feature, a decision that still riles some individuals on this repo.  `readonly ref` makes sense here as it describes what it is, a `ref` that is `readonly`.

**Comment by canton7** [comment]
Sure, `readonly ref T M<T>` is clearish. That's different to `readonly T M<T>` which means something entirely different.

**Comment by juliusfriedman** [comment]
> Sure, `readonly ref T M<T>()` is clearish. That's different to `readonly T M<T>()` which means something entirely different.

That;s why I like @mikernet's example. 

`readonly ref` is something different but plausible.

**Comment by canton7** [comment]
I would recommend updating your OP, and clarifying that you want to be able to *return* a reference to a struct from a method, and allow that reference to be one that was passed into the method using `in`. Nothing to do with `readonly` generic type constraints or `default`.

**Comment by juliusfriedman** [comment]
Will do asap

**Comment by 333fred** [comment]
> I would recommend updating your OP, and clarifying that you want to be able to *return* a reference to a struct from a method, and allow that reference to be one that was passed into the method using `in`. Nothing to do with `readonly` generic type constraints or `default`.

To be clear, that's already possible: https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLIN7LpHqHFroBOApgGaVUCGwA9gHYA2AnugCroCyAHh4A+ABQBLVr3QA3AJToA7gAsq1GSHQBnAC4UArgGNd6AkmKXMAdnp1ZAblJEAvshdA==

@juliusfriedman we appreciate the enthusiasm. But your proposals need more work. You need to understand the spec and propose actual changes that don't conflict with the existing language. Afaict, this has been 30+ messages to understand that you are trying to propose something that already exists.

**Comment by HaloFour** [comment]
D'oh, didn't realize it was `ref readonly` and that it was already added to the language! :D

**Comment by mikernet** [comment]
🤣 Haha, whoooops.

**Comment by CyrusNajmabadi** [comment]
> @juliusfriedman we appreciate the enthusiasm. But your proposals need more work. You need to understand the spec and propose actual changes that don't conflict with the existing language. Afaict, this has been 30+ messages to understand that you are trying to propose something that already exists.

I agree with Fred here.  And this ties into the conversation you and I were having yesterday on emphasizing clarity and providing more context and information to assist with the discussion.  Being vague and responding cryptically does not help your proposals out.

Given taht this appears to be a proposal for something that already exists, I'm goign to close this out.  You are more than welcome to continue making proposals here.  My only request is that you invest a little more time into them to help save a lot of people spending many hours trying to unpack exactly what it is you are referring to.

Thanks much!

**Comment by juliusfriedman** [comment]
No prob so long as you do the diligence you promised and we reopen when appropriate?

otherwise i find this very faux paus`

**Comment by mikernet** [comment]
Why would this be reopened? The exact feature you are proposing already exists, the syntax for it is above.

**Comment by juliusfriedman** [comment]
> Why would this be reopened? The exact feature you are proposing already exists, the syntax for it is above.

I said when and if...
