### ISSUE TITLE
const, nullref keyword

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/csharplang#3693]
```c#
public const T M<T>(){ return default; }
```
const just means the result will NEVER be null (except) when it's the `nullref`.

```c#
public const T M<T>() where T : unmanaged { return default; } //nullref if `T` is `ref struct`, `readonly`
```

```c#
public const T M<T>() where T : class{ return default; } //null
```

```c#
public const T M<T>(in T) where T : readonly{ return default; } //nullref if t is not assigned
```

What is `nullref`, `nullptr` from C++

`nullref` is the only value allowed to be assigned to a ref value other than a reference to an existing value and should be assigned with `= nullref`

`T` must be a type which is either an `interface`, `class` or `object` which cannot be null, `readonly struct` would be allowed, `ref struct` would be allowed, `struct` would be allowed but those values must be passed by `ref` or `in` or be marked as `readonly` otherwise compiler error CXXX should be thrown.

`nullref` should be returned from methods which violate the `readonly` constraint at the CIL spec level.

`Unsafe.AsConst` will be needed potentially 
and you would cast it away with the other methods in `Unsafe`

**Comment by yaakov-h** [comment]
I can't make heads or tails of this whatsoever.

**Comment by juliusfriedman** [comment]
Will do better improving it with time.

**Comment by canton7** [comment]
Yeah, I don't understand this. What is `nullref`? There isn't a single `ref` in any of your code examples: I thought at first it meant you could do `ref Foo foo = nullref`, but the examples don't bear this out. It's also not clear why `unmanaged` and `readonly` get involved.

**Comment by huoyaoyuan** [comment]
You are asking about the same semantics of `Unsafe.NullRef<T>`.

That's **extremely dangerous** so that the corelib team didn't even make it public.

If you are really confidential about what you are doing, and care a lot about the performance, **you can always get the value without language support** (using `Unsafe` families).

**Comment by JustNrik** [comment]
> 
> 
> You are asking about the same semantics of `Unsafe.NullRef<T>`.
> 
> That's **extremely dangerous** so that the corelib team didn't even make it public.

Off-Topic: Isn't `Unsafe.NullRef<T>` literally `Unsafe.AsRef<T>(null)`?

**Comment by canton7** [comment]
> Off-Topic: Isn't `Unsafe.NullRef<T>` literally `Unsafe.AsRef<T>(null)`?

Looks to be public, and an alias of `Unsafe.AsRef<T>(null)` [to me](https://source.dot.net/#System.Private.CoreLib/Unsafe.cs,7627a03642316a5d):

```cs
public static ref T NullRef<T>()
{
    return ref Unsafe.AsRef<T>(null);
 
    // ldc.i4.0
    // conv.u
    // ret
}
```

**Comment by CyrusNajmabadi** [comment]
> Will do better improving it with time.

@juliusfriedman Your enthusiasm is appreciated.  However, this is not a repo to simply throw barely fleshed out thoughts at.  Proposals are treated seriously and are expected to have a reasonable level of time and effort put into them so as to not consume excess time from all the people who have to read and try to understand it.

If you want to discuss your *ideas* with people so you can flesh them out better, tehre are better avenues to do that.  Specifically gitter.im/dotnet/csharplang, or discord.gg/csharp.  Once you've really gotten an idea that you think is good, and has a lot of the design understood (including the pros/cons/etc), and you're out of the "needs work" phase, then that's def a good time to actually make the proposal.

**Comment by juliusfriedman** [comment]
Sir, we had a discussion where you said a lot of people make proposals which don't make sense.

This proposal IMHO does not fit into that category.

With such being typed if you feel differently then you are free to do as you will.

Thank you for your time and I apologize for any inconvenience.

**Comment by john-h-k** [comment]
> That's **extremely dangerous** so that the corelib team didn't even make it public.

I don't think dangerous is the right term. It has no inherent danger, it just breaks the language rules that a `ref` isn't `null`. It is well-defined at the IL level as semantically being the same as a null object reference

**Comment by Unknown6656** [comment]
@jaredpar  or @333fred
You can close this issue as the OP has been banned from this repository.
