### ISSUE TITLE
Throw expression should not prevent target typing succeeding

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#3697]
The following codes fails to compile:

```csharp
public class C
{
    public int M(bool b) {
        return b ? default : throw null;
    }
}
```

```csharp
using System;

public class C
{
    public Func<int> M(bool b) {
        return b ? () => 42 : throw null;
    }
}
```

with:

> `error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'default' and '<throw expression>'`

and

> `error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'lambda expression' and '<throw expression>'`

I suggest that the spec is updated so that any branches which result in a throw expression are ignored for target typing.

Note that this is already legal with switch expressions:

```csharp
public class C
{
    public int M(bool b) {
        return b switch {
            true => default,
            false => throw null,
        };
    }
}
```

**Comment by YairHalberstadt** [comment]
@RikkiGibson thinks this should be part of target typed conditional: https://github.com/dotnet/roslyn/issues/46039

**Comment by svick** [comment]
[Both snippets already compile on the "Target-typed conditional" branch.](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQygg5hG6CeADgJYB2WANDCAG4QLFj4A+AAgEwCMAsAFB+sAzAAIOwgMJ8A3n2FzRIsjGEBZTgApgAey0AbYcACUwmb3nnRAdgPCA/MIAmEMFDi7lIYTAAWCLQHdhUjddAG5ZeQBfCLkYhVEAVgAeJQA+VXZNHX0jEzjzVmtgO2F1YwBedIAWdmFPHz9A4N0wuOjeSKA=)
