### ISSUE TITLE
Simplify to get PropertyInfo with new keyword 'propertyof'

### ISSUE THREAD

**Issue by ice1e0** [dotnet/csharplang#3704]
Today it is possible to get a type with `typeof(DateTime)`.

I often need to get the `System.Reflection.PropertyInfo` of a specific property of a class, so I often then call:
``` csharp
var dateProperty = typeof(DateTime).GetProperty(nameof(DateTime.Date));
```

## New keyword suggestion

Introduce a **propertyof** keyword making it easier to get the property info by calling:
``` csharp
var dateProperty = propertyof(DateTime.Date);
```

**Comment by svick** [comment]
Closely related and more general proposal: https://github.com/dotnet/csharplang/issues/712.

**Comment by 333fred** [comment]
Closing as a subset of the linked proposal.
