### ISSUE TITLE
Proposal: Allow discard variable for null-coalescing assignment operator in Property

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/csharplang#3715]
For this pattern:
`private IAPIClient _apiClient;`
`public IAPIClient ApiClient => _apiClient ??= DependencyService.Resolve<IAPIClient>();`

Simplify it to:
`public IAPIClient ApiClient => _ ??= DependencyService.Resolve<IAPIClient>();`

Rationale:
1. _apiClient never needs to be called anyways and would be default(IAPIClient) if called before ApiClient.
2. Resolving on the property is a "lazy" implementation so we don't have to resolve IAPIClient before it is accessed.

**Comment by HaloFour** [comment]
See this: #140

The team has expressed interest in implementing this proposal.

**Comment by DeanFaizal** [comment]
Thanks! I see the exact suggestion in the thread. Closing this to reduce noise.
