### ISSUE TITLE
[proposal] improve inference when passing methods as generic func parameter

### ISSUE THREAD

**Issue by leandromoh** [dotnet/csharplang#3722]
lets consider follow methods:

```c#
string Operation(int a);

void Foo(Func<int, string> func);

void Bar<T1, TResult>(Func<T1, TResult> func);

Foo(Operation); // this compiles!
Bar(Operation); // this not
```

Is there some way to improve this inference?

**Comment by CyrusNajmabadi** [comment]
> Is there some way to improve this inference?

Do you have a language proposal on how to improve the inference here?

**Comment by JustNrik** [comment]
`Bar<int, string>(Operation)` will work, but I don't know why the compiler can't infer it, it really should be able to infer it... I think?

**Comment by jnm2** [comment]
@JustNrik A proposal would explain specifically what steps the compiler would take to break down the problem and fit it into the existing spec.
