### ISSUE TITLE
Allow expression trees to contain assignment operators

### ISSUE THREAD

**Issue by R2D221** [dotnet/csharplang#3724]
As of C# 8, if you to try to use an assignment operator in a lambda expression, like so:

    M(() => a = b);

the compiler marks it as Error CS0832: An expression tree may not contain an assignment operator.

However, the framework does have a way to build assignment expressions: https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.assign

So, what's stopping the compiler from supporting this scenario?

**Comment by svick** [comment]
This is a subset of https://github.com/dotnet/csharplang/issues/2545.

**Comment by 333fred** [comment]
Closing out, as svick has pointed out this is a subset of an existing issue.
