### ISSUE TITLE
Proposal:   Get caller information for logging or testing

### ISSUE THREAD

**Issue by darrenoakey** [dotnet/csharplang#3726]
**the problem**
there's a class of code - like logging code, assertions, or discovery methods that is not very big, but needs information about the caller.    eg:

     Log.info("hello world")     // really wants the class, method, file, and line number it's called from
     var theString = EmbeddedResource.AsString( "blah.txt")    // wants the assembly its called from
     AssertEquals( 10, 3 + 4 + 4 )    // wants the text of the expressions

**the hacks** 

- in the first case, we use fody or post sharp to replace Log.info with Log.Info( typeof(enclosing class), nameof(method), "hello world")
- in the second case - we at runtime get the calling stack, ignore our bits of it, and then get the assembly from the first item
- in the third case, in the assert, at runtime, we get the code location, check if it matches our expected shape, and if the code is actually where we expect it - we then find the code file and line from the stack trace, and then parse the assert equals statement - so we can correctly say  "10 does not equal 11 (3+4+4)"  - instead of "10 does not equal 11"

**the proposal** 

obviously the hacks are not ideal, but in a library call any amount of hacks are justified to make the call a little cleaner, as something like log.info is only ugly once, but is called thousands of times.   Just as obviously - in every case, the compiler always knows everything about the method call site, so could trivially inject any information about it.   

So the proposal is to have lots of stuff about the method call injectable.  Swift does something like this, allowing you declare parameters like x : String = #filepath  - so a similar notation would be great to get any of:

- method name
- method info
- method owner class as string
- method owner class as Type
- method owner assembly
- method variables and parameters, including "this" - as a dictionary  (this would enable creating a function like "scalar" which you could call like return theDatabase.scalar( "select count(*) from values where someDatabaseVariable = {someLocalFunctionVariableOrParameter}")
- parameter expression as string
- parameter expression as expression
- filename
- file path
- file line number

**Comment by benaadams** [comment]
Can add the parameters to method annotated with `[CallerMemberName]`, `[CallerFilePath]`,`[CallerLineNumber]`?

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/caller-information

**Comment by darrenoakey** [comment]
yep - so I just want _heaps_ more

**Comment by theunrepentantgeek** [comment]
This issue seems to be a duplicate/subset of #87

**Comment by darrenoakey** [comment]
yeah - it does seem to be a duplicate - except for my one about getting the dictionary of parameters - haven't seen anyone asking for that - but it would enable sooo many cool things.   For instance it would have allowed people to implement something like $"hello {blah}" many years ago.

and my main point would be - I can't see any reason _not_ to do anything.  You are literally just generating code at the insertion point - it's all stuff the compiler knows at that point - it's not doing anything special to the method except marking some flag like "oh and we want you to put all the local variables in a dictionary and send it along" - in each case - someone could just add the information by hand - but there will never be as clean or as performant a way of doing it compared to the compiler going .. "oh they also want this information.. ok... I'll generate the code to add it"

**Comment by darrenoakey** [comment]
closing because of duplicate
