### ISSUE TITLE
proposal: static extension methods

### ISSUE THREAD

**Issue by darrenoakey** [dotnet/csharplang#3727]
in my opinion - extension methods are the greatest single addition to c# in its history.... because they open up libraries - they deal with the discovery problem.  People don't have have to have carefully read through every line of every library that someone else has added to the system - they just notice that more functionality is available when they hit "." - and if it does what they want, they are likely to use it.

**the problem**
the problem is - they aren't really consistent - you can add an extension method to any _instance_ - but you can't add an extension method to a type - so for instance a string - you can add a thousand extra functions to add to a single string, but there are also factory type functions on "String" - and there is no way to write your own.

**the proposal**
So the idea would be that you can just do the following:

`
    public static String HorizontalLine<this String>( int size) {return new String("-", size );}
`

**Example: Interface factories**
The most common reason I'd want to use it is for anytime you have a "pluggable" interface.  For instance suppose you support lots of file formats - and you make a

`
    interface IGraphicsFileFormat<T> : IGraphicsFileFormat where T: IGraphicsFileFormat<T>
    {
           T  FromRaw( RawImage image );
           RawImage ToRaw( T image )
     }
`

Obviously you want someone using it to know all the formats that are out there, but there's no easy way of discovering them.   However, if you could just do this:

`
    public class Gif : IGraphicsFileFormat<Gif> 
   { 
      .... 
     }
    public static class GifExtensions
    {
          public static IGraphicsFileFormat<Gif> Gif<this IGraphicsFileFormat>() {return Gif.Instance();}
    }
`
then you can have many different formats coming from many different libraries with a very consistent way of accessing them

**Example: Extending static interfaces**
As people go more and more functional - things with side effects are turning into completely static interfaces - for example System.Console.   This is a good thing, but we have no way of extending them.   So for instance, if you create a way of displaying a dictionary as a table - you would be able to just write:

`
public static void WriteTable<this Console>( object value ) 
{
     ...
}
`
and anyone using console is going to notice that there are lots of other helper functions

**Comment by MgSam** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/2505

**Comment by Joe4evr** [comment]
Please close duplicate issues.

**Comment by darrenoakey** [comment]
closing because of duplicate
