### ISSUE TITLE
proposal: extension methods can live anywhere

### ISSUE THREAD

**Issue by darrenoakey** [dotnet/csharplang#3728]
**problem**
we love extension methods - but we love them so much that basically every library class or interface comes with them... but a) its more work to create an extra class just for the extension methods and b) there's almost always a more logical place to put them

**solution**
allow extension methods to be specified inside any class or interface definition

**example: interfaces with helper methods**
with basically any interface, you can define helper functionality just in terms of the interface.  it seems silly to have to put that helper functionality in a different place.  eg

```
   public interface IOrderBookLevel
   {
         double? BidPrice {get;}
         double? OfferPrice {get;}
         static double? Spread( this IOrderBookLevel value )
         { return ((value.BidPrice==null) || (value.OfferPrice==null)) ? null : value.OfferPrice - value.BidPrice;}
    }

```

**example: helper conversions**
anytime you add some sort of stronger type for something, you end up having conversion methods to and from it.  Sometimes those are implicit, which _can_ be put on the type, but sometimes you want them explicit, and it would be handy to be able to put them on the type as well. eg

```
   public class Filename 
   {
        public void Delete() { File.Delete( _underlying);}
        ...
       public static Filename AsFilename( this String asString) 
       {
          return new Filename( asString );
       }
    }
```

**Comment by jnm2** [comment]
I very much love the concept of interfaces declaring extension methods for other types.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/2571
https://github.com/dotnet/csharplang/issues/850

**Comment by darrenoakey** [comment]
It occurs to me that half of this could be implemented using c# source generators.  if we define a This annotation, then we could just do

```
 public static String Blah([This] string x, int y ) {...}
```

anywhere, and a generator could just generate a static class that just calls the above function.   a little harder with interfaces though :(

**Comment by yaakov-h** [comment]
Why would you declare an extension method on an interface inside that interface when we now have DIM?

**Comment by darrenoakey** [comment]
because
a) default interface methods can be overridden - for pure helper methods, you don't really want that
b) I suspect (haven't checked) dims affect the size of the object?
but most importantly 
c) the extension method just as often goes the other way - ie providing a conversion _to_ the interface from some other type

**Comment by YairHalberstadt** [comment]
> a) default interface methods can be overridden - for pure helper methods, you don't really want that
> b) I suspect (haven't checked) dims affect the size of the object?

DIMs can be sealed. And they wouldn't affect the size of the object.

**Comment by svick** [comment]
I think another problem with DIMs is that they are not inherited. So, for some type `OrderBookLevel` that implements `IOrderBookLevel`, and assuming `Spread` is a `sealed` DIM, the following works:

```c#
IOrderBookLevel obl = new OrderBookLevel();
return obl.Spread();
```

But this doesn't:

```c#
var obl = new OrderBookLevel();
return obl.Spread();
```

**Comment by darrenoakey** [comment]
closing because of duplicate

**Comment by jnm2** [comment]
Where else is it requested that interfaces can declare extension methods?
