### ISSUE TITLE
C# 9.0 determine if a type is a 'record' via reflection

### ISSUE THREAD

**Issue by kofifus** [dotnet/csharplang#3732]
Is there an official way to detrmine if a type is a 'record' via reflection ?
Looking [here](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGMD2A3KCCWUAdjKkvAkcgD4ACATAIwCwAUG7QMwAESWCAE24AFBJgFx0MNgG823Bdy5LGABm4A5KAFsI3GdwDmEGAG5uyE+YC+8xcvwluAYVgRDmBAE8AkkIPGZhZW3LasYUA==) I was thinking about maybe detecting the `EqualityContract` property:

```
var isRecord = ((TypeInfo)typeof(MyRec)).DeclaredProperties.Any(x => x.Name=="EqualityContract");
```

 but that feels hackish :(

**Comment by 333fred** [comment]
There is not only not an official way to do this, it is explicitly against the design of the feature. The intent for records is that, hopefully with C# 10, we'll get to a point where making a class a record is purely a convenience choice, and that every other part of the feature will be achievable through some form of syntax. It should not be a breaking change to change a type from a record to a class, and we even imagine that an IDE refactoring could automatically move a type to and from record syntax without clients noticing. For C# there are some places where we didn't quite achieve this, but that's the goal.

**Comment by kofifus** [comment]
The deeper motivation here is to know if a type is both immutable and with value semantics. I have a small list basic and core types that satisfy that and at various places check use reflection to check for that etc, since records satisfy that I can include them also hence my question. (I can then use reflection to check that all members of the record are themselves immutable with value semantics etc).

**Comment by 333fred** [comment]
That sounds more like a compile-time analyzer scenario, to flag a type of it's immutable, rather than a record scenario. It's perfectly possible to create a mutable record, so just being a record is no guarantee of that type of behavior.

**Comment by AartBluestoke** [comment]
"t's perfectly possible to create a mutable record" -- sounds like that should be documented, i'm sure kofifus and I are not the only people who (without thinking too deeply) would assume that records are readonly ...

**Comment by kofifus** [comment]
@AartBluestoke I think what is meant is that while all the members of  a record are readonly they may be of mutable types which makes the record itself mutable. IMO C# has a real weak point with immutability but I think @333fred comment is true that an analyzer is the better way to go here

**Comment by 333fred** [comment]
> @AartBluestoke I think what is meant is that while all the members of  a record are readonly they may be of mutable types which makes the record itself mutable. IMO C# has a real weak point with immutability but I think @333fred comment is true that an analyzer is the better way to go here

No, you can have setters on record properties. Records do not mean immutable. They have defaults that pull you in that direction, but they are not immutable-only types.

**Comment by kofifus** [comment]
@333fred ah ok got it .. must say that is disappointing news

**Comment by MichaRotstein** [comment]
@333fred 

> That sounds more like a compile-time analyzer scenario

Can an analyzer identify a record ? if yes how ?

Thanks

**Comment by CyrusNajmabadi** [comment]
Yes. An analyzer would be able to tell. It could just examine the syntax if the type.

**Comment by MichaRotstein** [comment]
Thanks @CyrusNajmabadi , what do you mean by "examine the syntax if the type" ?

**Comment by ufcpp** [comment]
`syntaxNode is RecordDeclarationSyntax`

e.g. https://github.com/ufcpp/MemberAccessGenerator/blob/master/src/MemberAccessGenerator/MemberAccessGenerator.cs#L209

**Comment by kofifus** [comment]
thanks @ufcpp

**Comment by 0xced** [comment]
I wanted to know if a type is a record to avoid serializing the `EqualityContract` property. In the end I checked if the property has a `CompilerGeneratedAttribute`. See https://github.com/mstum/Simplexcel/pull/42

**Comment by colejohnson66** [comment]
But why would you need to enforce that? If someone wants to shove a POD object into a container, why prevent them?

**Comment by Timovzl** [comment]
Oh, I wasn't implying that detecting records is a full solution to separating services from non-services. But I'm not the only one taking a heuristics-based approach, and detecting records has certainly helped with mine. I'd prefer to do it without my own extension method.

I understand that you might choose a different approach to tackle that use case. That's a trade-off concerning purely the use case. Priorities differ.

The point was to illustrate that there are reasons for developers to want to know at runtime whether a type is a record.

**Comment by CyrusNajmabadi** [comment]
> But I'm not the only one taking a heuristics-based approach

If you're ok with a heuristic approach, it's simple.  Check for the clone method with the particular name at runtime.

**Comment by Timovzl** [comment]
> Check for the clone method with the particular name at runtime.

Yes, or the equality thing. The request is to support this with something like an IsRecord property, rather than rolling your own extension that inspects a type’s methods.

(For full clarity, heuristics referred to separating services from non-services, not evaluating whether something is a record.)

**Comment by CyrusNajmabadi** [comment]
> The request is to support this with something like an IsRecord property, 

This exists if you use hte Roslyn API.  If you want reflection to support this, it has to be a dotnet/runtime request.  Roslyn doesn't control that.
