### ISSUE TITLE
Permit variable declaration under "or patterns".

### ISSUE THREAD

**Issue by Happypig375** [dotnet/csharplang#3740]
According to https://github.com/dotnet/csharplang/blob/6901635c383801e4d177085587aaccadaa7b2f11/proposals/patterns3.md#variable-definitions-and-definite-assignment, we will not be able to declare pattern variables under "or patterns". 
Obviously this should be supported. We should at least allow cases where all branches of the "or pattern" declare the same number of variables of the same types. (For variables of different types, we should wait for #399.)

An example that this can simplify is 

https://github.com/verybadcat/CSharpMath/blob/b8a5ab0ff9789627edf2f05927291a87631b29a0/CSharpMath.Evaluation/Evaluation.cs#L395-L403

The `when` clause can be simplified by #3435, but we still need to permit variable declaration under "or patterns" to merge the two cases into one and eliminate the unnecessary `goto`.

**Comment by jnm2** [comment]
I'd like the ability to declare variables on either side of `||` too:

```cs
return value is TInner inner || innerConverter.ConvertFrom(context, culture, value) is TInner inner
    ? Wrap(inner)
    : base.ConvertFrom(context, culture, value);
```

**Comment by huoyaoyuan** [comment]
> I'd like the ability to declare variables on either side of `||` too:
> 
> ```cs
> return value is TInner inner || innerConverter.ConvertFrom(context, culture, value) is TInner inner
>     ? Wrap(inner)
>     : base.ConvertFrom(context, culture, value);
> ```

```cs
((value as TInner) ?? (innerConverter.ConvertFrom(context, culture, value) as TInner)) is {} inner
```

Well you do have an alternative, and I'd say they are both ugly syntax.

**Comment by jnm2** [comment]
I can't use `as` because TInner is not constrained to `class`.

**Comment by YairHalberstadt** [comment]
Closing as championed at https://github.com/dotnet/csharplang/issues/4018
