### ISSUE TITLE
Struct containing a non-nullable reference type allow access the unitializated reference type

### ISSUE THREAD

**Issue by Neo-Ciber94** [dotnet/csharplang#3752]
The compiler don't give me any warning in this situation and I suppose it should. Is this behaviour intended?

I am using **netcore 3.1**.

```csharp
#nullable enable
using System;

class Program
{
    static void Main()
    {
        var person = default(Person);

        Console.WriteLine(person.Name.Length); // NullReferenceException
    }
}

public struct Person
{
    public string Name { get; set; }
    public int Age { get; set; }
}
```

**Comment by ufcpp** [comment]
This is known issue and may need [non-defaultable struct types and parameterless struct constructors](https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-07-01.md).

**Comment by jnm2** [comment]
I keep tripping on this as well.

**Comment by saltukkos** [comment]
I don't know, guys. "Non-defaultable struct types" is "non-defaultable struct types", but this is bad work of designing team until we have the ability to create default struct with not nullable reference type without any warning in "nullable-safe" context.
We should either forbid defining not-nullable fields in structs (at least with warning) or try to warn user when creating this structs with `default(MyStruct)`, `new MyStruct()`, `new MyStruct[10]` and other ways.

**Comment by saltukkos** [comment]
I think this issue should be reopened to discuss how to deal with NRT with structs IN CURRENT scenarios, "we will fix it, maybe, in case we will implement the `non-defaultable struct types`" is not the answer.
