### ISSUE TITLE
[Discussion] Discriminated Unions features "shopping list"

### ISSUE THREAD

**Issue by DavidArno** [dotnet/csharplang#3760]
This is a write-up of my thoughts on what the "shape" of sum types (ie Discriminated Unions) in C# could look like. Throughout this article, I just refer to them as "unions".

In [Remaining design work in and around records](https://github.com/dotnet/csharplang/issues/3707), Mads mentions at the end that "*We've said that we'd look at discriminated union scenarios once we got records under control. That time has come. The design space is wide open at this point.*". This is an area that I've been thinking about for some time. As such I felt it now a good time to publish my effective "shopping list" of wants for unions in C#.

For the purposes of this article, I've invented syntax for how one might express union types. This is arbitrary syntax. I feel it consistent with the rest of the language, but the syntax used is unimportant. What I'm seeking to do here is express ideas around the functionality of unions and not to plant a flag in the ground of a particular syntax form.

For many of the examples here, I've borrowed heavily from [F# for fun and profit](https://fsharpforfunandprofit.com/posts/discriminated-unions/).

## A simple union ##

A union of an `int` and a `bool` would look something like this:
```c#
enum struct IntOrBool
{
    I { int },
    B { bool }
} 
```
Here, an instance of `IntOrBool` can either be an `I of int`, or it can be a `B of bool`. As such, pattern matching can be used to determine which it is. We can match against the 
```c#
var oneOfThem = new IntOrBool.I(2);
if (oneOfThem is I { var i })
{
    // it is an I in this case, and i is an int == 2 
}
```

`I` and `B` can be thought of as just being case labels, rather than definitely types themselves. Effectively how thy are handled by the compiler should be seen as an implementation detail.

## Shortcutting the labels for matching simple unions

In the example union above, both `I` and `B` are just wrappers over other single types. As such, the pattern match may be simplified to:
```c#
var oneOfThem = new IntOrBool.I(2);
if (oneOfThem is int i)
{
    // it is an I, which just wraps int and so the pattern matches 
}
```
The reasoning behind this is largely driven by the way nullable structs are handled by pattern matching. It seems desirable to have `int?` and `Option<int>` be handled the same when pattern matching them:
```c#
int? x = 1;
Option<int> y = 1;

if (x is int i1) ... // we don't express this as if (x is int? { int i1 }) ...
if (y is int i2) ... // therefore if (y is Some { int i2 })... seems burdensome in comparison to nullables
```
This could only apply where there was ambiguity over which case was being matched, so for:
```c#
enum Result<T>
{
    Success(T value),
    Error(string message),
}

var result = Result<string>.Error("message");
if (result is string value) ... // this would be an error as both Success and Error could match here
```

## Unions can be structs or classes ##

In the following example, `IntOrBool` is a struct and `IntOrString` a class. The usual rules of pass by value/reference would therefore apply to them, respectively:

```c#
enum struct IntOrBool
{
    I { int },
    B { bool }
} 

enum class IntOrString
{
    I { int },
    S { string }
} 
```

## Unions can be generic ##
For a union that can be either `T1` or `T2`:
```C#
enum struct Either<T1, T2>
{
    Left { T1 },
    Right { T2 }
}
```
This then highlights the benefit of the shortcutting approach to pattern matching:
```C#
var either = Either<int, bool>.Left(2);

if (either is Left { T1 value }) ...

if (either is T1 value) ...
```
"Left" and "Right" are just handy labels, but they carry no useful information and could just as easily be called "Sally" and "Harry". Removing them from the pattern match significantly increases the readability of the code.

## Constructing a union type ##
As seen in previous examples, one way of constructing a union is to fully express the type and label:
```c#
var foo = new IntOrBool.I(2);
```

If `I` is unambiguous then the type isn't needed:
```c#
var foo = new I(2); // foo is an instance of IntAndBool
```

If the type involves generics though, this doesn't work:
```C#
var either = Left(2); // Error. We could infer that T1 is int, but what's T2?
```

So, as long as the value is unambiguous with regards to the types in the union, the label isn't needed:
```C#
var either = Either<int, bool>(2); // It's a Left.
```

Finally, unions could support implicit casting:
```C#
Either<int, bool> either = 2;
```

## Empty cases ##

In the previous examples, the cases all have values of some type or other. But there are situations where a case doesn't have a meaningful value. The classic `Maybe`/`Option` type being one such example:
```C#
enum struct Option<T>
{
    None,
    Some { T }
}
```
In this case, pattern matching uses the label as normal:
```C#
var maybe = Some(2);

var result = maybe switch {
    None => "no value",
    int i => i.ToString();
}
```
And constructing a union instance with an empty case is just like using a parameterless constructor:
```c#
Option<int> maybe = None;
```

## Closed enums are just a union of empty cases ##

With regard to [Proposal: "Closed" enum types](https://github.com/dotnet/csharplang/issues/3179), a closed enum (ie one that has a fixed set of cases that cannot be extended at runtime) can be expressed via a union:
```c#
enum struct Bool { False, True }

int M(Bool b) => b switch {
    False => 0,
    True => 1
};
```
Unlike classic, "open" enums, the cases of such a closed enum do not have any values so cannot be cast to/from eg `int`.

## Single cases ##

So far, all the examples have been of unions with at least two cases. However, single case unions can be used to address [the primitive obsession problem](https://refactoring.guru/smells/primitive-obsession) without the need for lots of boilerplate code.

```c#
enum class PostCode { PostCode { string } }

enum class TelephoneNumber { Number { string } }

void HandlePostCode(PostCode) => ...

PostCode postCode = "AA1 1AA"; // string can be cast to PostCode
TelephoneNumber phone = "001 555 ...";

HandllePostCode(postCode); // valid
HandllePostCode("AA1 1AA"); // Also valid as string can be cast to PostCode
HandlePostCode(phone); // invalid
```

And the value from such a single case can be "deconstructed" with pattern matching as required:
```c#
if (postCode is string s)
{
    ...
}
```

## Cases can have values of the same type ##
```c#
enum struct Telephone
{
    Landline { string },
    Mobile { string }
}
```
In such cases, the label must be explicitly specified during construction:
```c#
Telephone phone = new Telephone("12345"); // error as this could be a LandLine or Mobile

var mobile = new Mobile("077..."); // All good
```

And the label is also needed in pattern matching:
```c#
if (mobile is Mobile { var s }) ...
```

## Cases can have more than one value and the values can be named ##
Up until now, all the examples have just used one value, which has not had a name and so a variation on recursive pattern matching has been used to access the value:
```c#
if (mobile is Mobile { var s }) ...
```

But sometimes we'd want to give it a name. Also sometimes we'd want that label to take more than one value, in which case they definitely want names. An example might be:

```c#
enum struct Shapes 
{
    Point,  
    Rectangle { double width, double length },
    Circle { double radius }
}
```
`Circle` doesn't need the name, `radius`. But it helps clarify what the value is. A `Rectangle { double, double }` is pretty meaningless by itself though, so it makes sense to name them. 

With names, ordinary recursive pattern matching can be used:
```c#
var area = shape switch {
    Point => 0,
    Rectangle { width: var w, length: var l } => w * l,
    Circle { radius: var r } => Math.PI * r * r
};
```
though the `radius:` part is optional.

## Union equality ##
For both class-based and struct-based unions, equality would be value-based. Copying the equality rules for records likely makes sense. As those rules (especially around `==`) have the potential to change, I'll not detail equality further, therefore.

## Recursive cases ##
As C# types already support self-referencing to create recursive types, this can be applied to unions too. For example, a generic  tree structure could be expressed as follows:
```c#
enum class Tree<TLeafData, TNodeData>
{
    LeafNode { TLeafData },
    InternalNode { IEnumerable<(TNodeData, Tree<TLeafData,TNodeData>)> }
}
```

## Serialization, deconstruction and `ToString()` ##
Unions will need to support serialization/deserialization somehow. The challenge is that many serialization frameworks rely on property-based serialization. This doesn't fit nicely with unions as far as I can see. I therefore don't have a proposed solution to this at this time.

Deconstructors for unions do not make much sense to me as C# does not support multiple deconstructors with the same arity and difference parameter types. Therefore my feeling is that a union shouldn't auto-implement a `Deconstruct` method.

The default `ToString` for a union likely can just be of the form:
```
<Label> [[<Name>:]<Value>(,[<Name>:]<Value>)*]
```
So in the `Shapes` example above, a rectangle of `10.0 x 20.0` would result in:  
`Rectangle width:10.0,length:20.0`.

## User-defined code within unions ##

In the case of single case unions, as well as preventing muddling primitives and supplying metadata around the purpose of the value, it's common to want to support value validation too. So allowing user-defined code, such as supplying a validating constructor, should be considered for unions. 

## Inheritance ##

As unions are a closed set of types, class-based unions should be sealed and thus cannot be inherited from.

There are likely use cases where it makes sense for class-based unions to inherit from a base class though.

**Comment by 333fred** [comment]
This is a very good writeup. You've hit a lot of points that I think are important to me as well, and I'll certainly keep this issue in mind as we move forward with design.

One small comment, I think you forgot an `is` in the shortcutting section? Fwiw that's one of the sections I'm more iffy on: it could be considered unambiguous, but that feels like too much magic to me, particularly as introducing a new case could be a source breaking change. It seems like too much spooky action at a distance.

**Comment by HaloFour** [comment]
Debating syntax as always is bike-shedding but I envision DUs to be more built on top of record syntax.  So given you can define records with the following syntax:

```cs
public record Rectangle(int Length, int Width);
public record Circle(int Radius);
```

You could define a DU as (something like) the following:

```cs
public enum Shape {
    Rectangle(int Length, int Width),
    Circle(int Radius)
}
```

What that actually generates if certainly up for a lot of debate.

**Comment by HaloFour** [comment]
I have a feeling that DUs will likely end up meaning more than one thing depending on how they're intended to be used.

You could have closed type hierarchies where each of the cases is a separate type that inherits/implements from a base type, such as how Java and Scala 2.x approach ADTs:

```java
package com.example.expression;

public sealed interface Expr
    permits ConstantExpr, PlusExpr, TimesExpr, NegExpr {...}

public record ConstantExpr(int i)       implements Expr {...}
public record PlusExpr(Expr a, Expr b)  implements Expr {...}
public record TimesExpr(Expr a, Expr b) implements Expr {...}
public record NegExpr(Expr e)           implements Expr {...}
```

And Scala 3.x introduces a nice shorthand for that:

```scala
enum Option[+T] {
  case Some(x: T)
  case None
}
```

You could also have tagged unions where a type hierarchy wouldn't work, such as with structs where you'd want a zero- or low-cost abstraction.  This is how F# implements them:

```fsharp
[<Struct>]
type Option<'a> =
    | Some of 'a
    | None
```

Maybe a single implementation can offer the flexibility of a type hierarchy with the performance characteristics of a tagged union?

**Comment by jnm2** [comment]
> "Left" and "Right" are just handy labels, but they carry no useful information and could just as easily be called "Sally" and "Harry". Removing them from the pattern match significantly increases the readability of the code.

I'm okay with this as syntax sugar for using `Left` and `Right` if T1 and T2 are different, but there is a big problem for me if matching is actually type-based and not actually nominal. One of my most commonly-used DUs, in pseudocode:

```cs
enum Result<T>
{
    Success(T value),
    Error(string message),
}
```

What should happen here?

```cs
var result = Result<string>.Error("message");
if (result is string value)
{
    // Is this Success or Error?
```

**Comment by HaloFour** [comment]
@jnm2 

I agree, I personally think that the case names are more important than the types of their elements, especially since they could be a singleton (e.g. `None`) or have any number of elements.  I don't think allowing them to be elided makes sense in the match anymore would it would to elide the property names in a recursive property pattern.

**Comment by Unknown6656** [comment]
@HaloFour 
> Debating syntax as always is bike-shedding but I envision DUs to be more built on top of record syntax. So given you can define records with the following syntax:

~We have to be careful with that syntax. It could be easily confused with a method declaration. What about using the already existing `case`-keyword for union case declarations?~

------------
@DavidArno One important point: "anonymous" unions (syntax is debatable):
```csharp
(union Option<int>{ Some { int }; None }) TryParseInt32(string s) => .....;
```
I'd hate to declare a `OptionalInt`-union for this case. The solution should be analogous to current tuple usage.

**Comment by TheUnlocked** [comment]
For single-type cases, rather than allowing you to match on the type like
```
if (opt is T1 value) { ... }
```
I'd prefer allowing
```cs
if (opt is Some value) { ... }
```
It's more descriptive, just as concise, and probably less prone to errors.

**Comment by 333fred** [comment]
```cs
if (opt is Some value) { ... }
```
This already means something today.

**Comment by TheUnlocked** [comment]
Ah...-- if you actually want `value` to stay as an `Option` my proposed alternative would be an issue. Alright, I concede there.

**Comment by FiniteReality** [comment]
I personally believe eliding case names for discriminated unions would be far too dangerous, leading to code that actually ends up being far more brittle. (Especially in the `Result<string>` case demonstrated with an Error case which contains a string for the error message.)

Other than that, I don't really see any issues with the features on your wishlist.

**Comment by AartBluestoke** [comment]
even in the non-generic case the type can be ambiguous - i deal with Microsoft Dynamics and Entities can be owned by any Identity Principal, and at the moment i have to manually track or ask what type of guid i'm dealing with:

enum mscrm.principal{
systemuser {Guid},
team {Guid},
businessUnit {Guid}
}

**Comment by orthoxerox** [comment]
> In the following example, IntOrBool is a struct and IntOrString a class. 

Is there a reason why one has a bool and the other a string? If there's none, then this can lead the reader astray.

> If the type involves generics though, this doesn't work:

It should still work if we're not using local type inference, `return Left(2);` should pick up the generic types from the method signature.

**Comment by mdro-bk** [comment]
> ## Single cases
> ...
> 
> And the value from such a single case can be "deconstructed" with pattern matching as required:
> 
> ```cs
> if (postCode is string s)
> {
>     ...
> }
> ```
> 
Having to use if or switch for the infallible extraction of the underlying value of a "type-wrapper" union would be inconvenient:
```cs
if (!(contact.Name is string name) || !(contact.EMail is string mail) || !(contact.PhoneNumber is string phone))
{
    throw new UnreachableException();
}
string contactBlock = $"{name}\nM: {mail}\nP: {phone}";
```
We could add shorter syntax for these infallible cases, for example cast-style:
```cs
string contactBlock = $"{(string)contact.Name}\nM: {(string)contact.EMail}\nP: {(string)contact.PhoneNumber}";
```
But if we would create syntax for that use-case anyway, I'd say it would make more sense to not abuse unions for that and implement a specialized syntax like #1695.

**Comment by DavidArno** [comment]
@333fred, typo fixed. Thanks.

With regard to the comments from yourself and others regarding the "shortcutting section", I've expanded that section to explain my thinking further. The key point for me is that I'd like to see syntax parity in matching eg `int?` and `Option<int>`:
```c#
int? x = 1;
Option<int> y = 1;

if (x is int i1) ... // we don't express this as: if (x is int? { int i1 }) ...
if (y is int i2) ... // therefore if (y is Some { int i2 })... seems burdensome in comparison to nullables
```

With regards to @jnm2's example, I'd see this only applying though if there were no ambiguity over which case was being made:
```c#
enum Result<T>
{
    Success(T value),
    Error(string message),
}

var result = Result<string>.Error("message");
if (result is string value) ... // this would be an error as both Success and Error could match here
```

But I agree that there is a degree of "magic" to this and maybe that's too high a price to pay to simplify just one edge-case union (`Option`/`Maybe`).

**Comment by HaloFour** [comment]
@DavidArno 

> The key point for me is that I'd like to see syntax parity in matching eg `int?` and `Option<int>`.

I can see wanting that equivalence but I don't know that it makes sense to affect all other DUs for that special case.  And without additional runtime support it would not behave like `Nullable<T>` when boxed and that pattern would never match.  IMO, it'd be sufficient to use a pattern like `Some(var x)` to match and extract the value from `Option`/`Maybe`.

When it comes to DUs like `Option` what concerns me more is the cost of the abstraction and the ergonomics of matching if each "case" isn't a separate type.

**Comment by orthoxerox** [comment]
One more thing: struct-based DUs will benefit from non-defaultable value types ([latest discussion](https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-07-01.md)) a lot. While some DUs can be arranged so that their default value matches the zero-bit pattern, some (like Either) don't have a default value to speak of.

**Comment by tomvanwoow** [comment]
I'm not a huge fan of the implicit conversions, even in the cases where its unambiguous. I think you should always have to specify the name of the alternative of the union you are calling, since otherwise adding new alternatives could break existing code.

**Comment by stephen-hawley** [comment]
Multiple things - why not make the syntax a little more clear that this is a union:
```
enum struct IntOrBool {
    int I | bool B
}
```
This makes it more clear that it's choice `I` *or* `B` It also tightens things up a bit.
What does `typeof` return? I assume `IntOrBool`. Will there be a `caseof` pseudo function? It would be handy to also generate an enum maybe under the same name such that `IntOrBool.I` is the value of the descriminator and `IntOrBool.I(n)` is the factory.

If this is a true DU, then the payloads in the actual implementation should overlap so as to not waste memory. This is an issue from a garbage collection standpoint, however. How will that be handled?
I assume also that I can have methods on these as well.

**Comment by jnm2** [comment]
@stephen-hawley What about `I(int x, int y)`?

**Comment by FiniteReality** [comment]
> Multiple things - why not make the syntax a little more clear that this is a union:
> 
> ```
> enum struct IntOrBool {
>     int I | bool B
> }
> ```

I personally disagree with this syntax... It doesn't really do much to clarify that it's a union or clarify that there's a choice IMHO. Since we're clearly into bikeshedding category, I'd like to see something akin to the Rust syntax, which I feel really did get discriminated unions more or less right:

```rust
enum Animal {
    Dog(String, f64),
    Cat { name: String, weight: f64 },
}

let mut a: Animal = Animal::Dog("Cocoa".to_string(), 37.2);
a = Animal::Cat { name: "Spotty".to_string(), weight: 2.7 };
```
(This example is from their reference on [enums](https://doc.rust-lang.org/reference/items/enumerations.html))

This is much like the syntax examples given by the OP, which I feel fit very much in line with C# as a language.

**Comment by Unknown6656** [comment]
> This is much like the syntax examples given by the OP, which I feel fits very much in line with C# as a language.

Agreed, however, @stephen-hawley's view point probably comes from the "traditional" syntax of describing union types (e.g. in ~Haskell,~ OCaml, F#, etc.):
```fsharp
type IntOrBool = 
    | I of int
    | B of bool
```
I do love the usage of `|` to represent a choice, as it has some symmetry with the traditional "Or"-operator.
This, however, is not a smart syntax for languages such as C# which are not indentation-sensitive.
