### ISSUE TITLE
[Proposal] pluralof expression

### ISSUE THREAD

**Issue by krzysklein** [dotnet/csharplang#3764]
# pluralof expression

* [x] Proposed
* [ ] Prototype: [None]
* [ ] Implementation: [None]
* [ ] Specification: [Not Started]

## Summary
[summary]: The `nameof` expression produces the name of a variable, type, or member as the string constant. An enhancement to this would be a 'pluralof' expression, which would produce a pluralized version of the name, for example `pluralof(User)` would generate `"Users"`.

## Motivation
[motivation]: This would be useful for example in the EF's ToTable configuration mapping method, where we need to pass a pluralized name (by convention in some projects); using string leterals in that case does not allow automatic change during refactor.

## Detailed design
[design]: The syntax would be similar to `nameof` expression, but it would produce a pluralized name (just like Visual Studio member name suggestion does for collections). It would be also brilliant if Visual Studio could tell what the pluralized literal will be (in a tooltip when hovering a mouse cursor over it).

## Drawbacks
[drawbacks]: None.

## Alternatives
[alternatives]: Still using string literals and maintaining the code during refactor.

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by PathogenDavid** [comment]
This is a recipe for a localization nightmare, and once implemented the feature could never evolve without breaking people.

Other than shorter syntax and having the pluralization happen at compile time, it isn't clear why this is better than using [a library like Humanizr](https://humanizr.net/#pluralize): `nameof(User).Pluralize()`

**Comment by HaloFour** [comment]
Irregular pluralization is common and complicated enough in English, let alone every other language.  There languages with different plural forms between "few", "some" and "many".  A concern like this is best suited for a library or analyzer where behavior can be configured or overridden.

**Comment by svick** [comment]
What does `pluralof(Uživatel)` return? Or `pluralof(Пользователь)`? (Both are valid C# identifiers.)

**Comment by 333fred** [comment]
Thanks for the idea. However, we generally try and stay away from this type of thing in the compiler, as there are many questions around changing strings: Should the name be localized in the programmer's environment, or in the runners? What if multiple team members are in different locales? This is why constant values in strings can only be composed of other strings, and you can't add a `1.0` to `"a"`: would that be `"1.0a"`, or `"1,0a"`? As @PathogenDavid has pointed out, there are good libraries available for this such as Humanizr, which we use in the IDE for pluralizing variable name suggestions. If this is something you need, I suggest you take a look at that.

**Comment by krzysklein** [comment]
Thanks for the comments!
I think this Humanizr library would be a better option than enhancing a compiler.
