### ISSUE TITLE
It should be possible to get the owner Type for any object property.

### ISSUE THREAD

**Issue by arung2207** [dotnet/csharplang#3767]
Every Object should have a method GetOwnerType() to return the Type of the class owning that object. Please see the attached file: [Program.cs.txt](https://github.com/dotnet/csharplang/files/5010050/Program.cs.txt). 

Currently, this information can't be retrieved via reflection also.

**Comment by theunrepentantgeek** [comment]
What problem does this solve? Why should *every* .NET type be burdened with this overhead?

The vast majority of types I've written in C# don't have any concept of ownership at all. If the few that did have such a concept, most had multiple types of owners, not a single one.

**Comment by yaakov-h** [comment]
This assumes very narrow ownership semantics, and doesn't seem like something feasible or even useful without significant further explanation and study.

**Comment by MillKaDe** [comment]
As far as I understand the sample program in the attached file 'Program.cs.txt' :

```c#
using System;
using System.Diagnostics;

namespace GetObjectOwner {
    class Program {
        static void Main(string[] args) {
            Debug.WriteLine($"(new A()).objA.GetOwner() = {(new A()).objA.GetOwnerType().FullName} --> should print: GetObjectOwner.A");
            Debug.WriteLine($"(new B()).objB.GetOwner() = {(new B()).objB.GetOwnerType().FullName} --> should print: GetObjectOwner.B");
        }
    }

    public class Debugger {
        public string state;
    }
    public class A {
        public Debugger objA =new Debugger();
    }
    public class B {
        public Debugger objB = new Debugger();
    }

    public static class Extensions {
        public static Type GetOwnerType(this Object target) {            
            //replace with logic to retrieve the owner type possibly via reflection
            return target.GetType();
        }
    }
}

```
the original poster ( @arung2207 ) wants the **containing** type, not the owner type.

This can be solved with expression trees : 
[SharpLab link](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHqAQwFsBTAZwAdCBjUgAgFVgBLAG3oG88977UADPQDKAGQCi9ALz9MAOlEsoARzniAHpTAVyLAPZRyAbl78hwgErTZci6QBmbUjVYGTuPoNkA2egGEDcj0nd1NUAGYffnR6AEkoez0uU09MXwBBMABzCDIoYA06SlcoelIwMD0waQA+eihSAHd6TJy8gvUikvoACgASACIegEpa+qb6AFkATwAVacoGEbkZydJiACNygeH3PlTfVAAWegAFMCVgeMSAMRZSNjheyzk7h7hrpPsWYZT9qTqAHULsBSIoGr1Bt93vQAOScb5yAByJFIAF9YfQ9PZ6MAFgx4Yi3o95otkaiMTs9vtUGl+CdzpdPuc9IswHjnhY5Cy2XjPvRKD8/nwAfRgSxQeCloMtKzyhz4YLyWQMVicXjFnDOEqefK5vjlejYVS/hEosczhd8p8ADyzOo9MTiNSabTkXQGG2oACsdpqdTYJA2cEIo24Hn2fBYOJ6gc2IfoLHI9QgbDYo2AAAtKs0Gs1WrlSPkkam2IVSMV9KUekQyNjenHg6HdsKRBIXVodFX6Bs9HBptZGyG5AAhPvTIz0AD0U9xmYJeam+s1y1W6y2YEx1HZrejvQAhD1e/3E8mnSt1+UNJ33d2yJsr67hhns3pmuVKmBqZHz9e3R7SjzUkGBke8Nz/Dt/yrScZznBcJhmYDemGLdCB3CMfy5NYHzAfkwPKax8LACDsI3GDZyzAkVmmUjylQ9DIyjGNDyA/FTzbZ0kSaP8uwMcZGj/Z85xzMoKiqb99iQmgDGAQglCULIkJkPMIOA8jrA1Uh6x6RD8V+DD9nFUFIQGJD4Wk/I5KgBTgMNVULNkpRk0IegTQMvhyEaCUaEzXoiIvHDgLDVs+BoQhyAYF5aLAYDyFee5HhAS0mQSPRiSeHoiPocKRC5dLPl2fgAHYJMjMKItygKN1i7lKl5aYksZa1Ut1dkB0yy9qhyl5Wr5VLCtQEqQvoOAHEIVNQGEt9RM/Ur6DRP4FojNFp1nT4eAjM1yGASAXBELh+EiS56GMeawkiDB/AOs1jpoScls8C6YnSPxA3dZIDLNYR6HS4QJLNPwfoSuA/H+yJvp5b7OHoLJSGAe7TUiQGeUB6HYfhs7lvOk6dogPb0mEXG9vDSMvqB94/sRq70tBqmIbqqGYbhhHPqRy1WVRpmMYezHI2xy7aSKj7SYuukLUmKzkOFxjPlqlLEl6EYxkXF63uTZZfpbdy4lSuXmoVnoldFFXXvC9Xhni94/C1xidcSPWrlSxXRmNiZVbN5DatZYQbZl3Wmsdg2jbqE21c9lHfcjWWA/5Q2XZDt3Cd24BPc1ubo6tQOkjj5XE6JlONeB630/9zPY+D/iWiTvGC4tyHI/2DP5eziuVervblgjiSeaWvAVtg2sKGoOgmFYNg8CAA==)

```c#
using System;

namespace Util {

  using SLE = System.Linq.Expressions;
  using SR = System.Reflection;
  using static Console;

  public static class Info {
    static ArgumentException error => new ArgumentException ($"() => new MyType ().MyMember");
    static void PrintInfoField (SR.FieldInfo fi)
      => WriteLine ($"field '{fi.Name}' of type '{fi.FieldType.Name}'");
    static void PrintInfoProperty (SR.PropertyInfo pi)
      => WriteLine ($"property '{pi.Name}' of type '{pi.PropertyType.Name}'");
    public static void PrintInfo<T> (SLE.Expression<Func<T>> lambda) {
      if (lambda is null) throw new ArgumentNullException (nameof (lambda));
      SLE.Expression body = lambda.Body; // the 'new MyType ().MyMember' part
      if (!(body is SLE.MemberExpression memberExpr)) throw error;
      SLE.Expression newType = memberExpr.Expression; // the 'new MyType ()' part
      SR.MemberInfo member = memberExpr.Member; // the '.MyMember' part
      if (!(newType is SLE.NewExpression newExpr)) throw error;
      Type containingType = newExpr.Type; // = typeof (MyType)
      Write ($"Type '{containingType.Name}' contains a ");
      switch (member.MemberType) {
        case SR.MemberTypes.Field: PrintInfoField (member as SR.FieldInfo); return;
        case SR.MemberTypes.Property: PrintInfoProperty (member as SR.PropertyInfo); return;
        default: throw error;
      }
    }
  } // Info

  public struct S { public int s; }
  public class C { public int c; }
  public class AClass {
    public S FieldS;
    public C FieldC;
    public S PropS { get; }
    public C PropC { get; }
  }
  public struct AStruct {
    public S FieldS;
    public C FieldC;
    public S PropS { get; }
    public C PropC { get; }
  }
    
  public class Program {
    public static void Main () {
      Info.PrintInfo (() => new AClass ().FieldS);
      Info.PrintInfo (() => new AClass ().FieldC);
      Info.PrintInfo (() => new AClass ().PropS);
      Info.PrintInfo (() => new AClass ().PropC);
      Info.PrintInfo (() => new AStruct ().FieldS);
      Info.PrintInfo (() => new AStruct ().FieldC);
      Info.PrintInfo (() => new AStruct ().PropS);
      Info.PrintInfo (() => new AStruct ().PropC);
    }
  }

} // namespace Util
```
which gives the following output :

```
Type 'AClass' contains a field 'FieldS' of type 'S'  
Type 'AClass' contains a field 'FieldC' of type 'C'  
Type 'AClass' contains a property 'PropS' of type 'S'  
Type 'AClass' contains a property 'PropC' of type 'C'  
Type 'AStruct' contains a field 'FieldS' of type 'S'  
Type 'AStruct' contains a field 'FieldC' of type 'C'  
Type 'AStruct' contains a property 'PropS' of type 'S'  
Type 'AStruct' contains a property 'PropC' of type 'C'  
```

**Comment by IllidanS4** [comment]
.NET is not an environment where objects are implicitly owned by other objects. Existing objects contain only references to other objects, and only the runtime/GC owns all those objects. Any other ownership model must be maintained by your own application. I suggest you look in `System.ComponentModel` instead.

**Comment by silver-bytes** [comment]
I have updated the program to explain the use case where I felt it would be a useful add-on if the determination is possible via reflection. [Program.cs.txt](https://github.com/dotnet/csharplang/files/5014440/Program.cs.txt)

@MillKaDe, thanks for your program. It gets the container via the lambda expression, I was pointing to getting the information via the object instance itself.

**Comment by arung2207** [comment]
I have updated the program to explain the use case where I felt it would be a useful add-on if the determination is possible via reflection. [Program.cs.txt](https://github.com/dotnet/csharplang/files/5014460/Program.cs.txt)


@MillKaDe, thanks for your program. It gets the container via the lambda expression, I was pointing to getting the information via the object instance itself.

**Comment by MillKaDe** [comment]
> .. I was pointing to getting the information via the object instance itself.

**Owner** and **containting object** are two different things !

A member (field, property, ...) does not know if it is part of another object.  There is no pointer / reference back to the containing object.

If a (containing) type contains members (fields, properties, ...), that information is stored in the containing types metadata.

To find the containing object of a member **just from the member**, you have to scan the whole heap (similar to the garbage collector) and check each and every object by scanning all their members and compare them to the member you searching for.

**Comment by arung2207** [comment]
I appreciate the responsiveness. The explanation seems reasonable, I am closing the issue.
