### ISSUE TITLE
Use T~ for an unconstrained defaultable T instead of T?

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#3771]
C# 9.0 preview uses `T?` in an unconstrained context to mean `defaultable T`.

This suffers from two disadvantages:
1. When `T` is constrained to a struct, `T?` means `Nullable<T>`. Removing the constraint now changes the type of `T?` which is confusing.
2. If in the future we gain runtime support for assigning null to an unconstrained `T`, allowing for methods like `FirstOrNull<T>`, the `T?` syntax will be taken.

I would suggest using the `T~` syntax instead. This has a number of nice features:

1. It's already an operator and appears on most keyboards.
2. The current operator is prefix unary so there should be no parsing ambiguities.
3. To me `T~` suggests "approximately T", i.e. this could be an instance of `T`, or it could be `default`, which isn't quite `T`. Not the best justification maybe, but it evokes the right feelings to my mind much more right to me than e.g. `T#`.

**Comment by AntiPasha** [comment]
According to this [LDM](https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-17.md#t), thing s were changed, the proposed syntax is `where T: default`

**Comment by YairHalberstadt** [comment]
@antipasha

That's the syntax for the constraint. This is talking about the syntax for the type.

**Comment by CyrusNajmabadi** [comment]
I would personally not like this.  I think `?` is natural and what people will want to use when taking an existing generic api and trying to NRT-ify it.  Having that syntax just work is compelling and desirable here.  There would have be extremely substantial benefits in order to need to use a different syntax here.

**Comment by huoyaoyuan** [comment]
I think it must use something other than `T?`. `T??` gave a good impression to me.

**Comment by hez2010** [comment]
@huoyaoyuan Based on this [LDM](https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-17.md#t) `T??` will result in ambiguity. 

I would prefer `T?` or `T~?` than `T?`, which can be considered as "approximately nullable".

**Comment by jnm2** [comment]
`Task<[MaybeNull] T>` would work just fine too. It would emit the same IL that is emitted for `Task<T?>` in the current preview and no other attribute would be allowed there.

**Comment by stefanloerwald** [comment]
I very much like the attribute syntax. It is incredibly trivial to understand and reason about. It also fits in well with the existing attributes around nullability.

If attributes were valid on type parameters in general, this would e.g. enable writing a set of attributes for mutable/immutable (sort of like const in C++) and an accompanying analyzer.

**Comment by YairHalberstadt** [comment]
Closing as the ship has already sailed on this one
