### ISSUE TITLE
[Proposal] Allow IEnumerator to be passed into a foreach directly

### ISSUE THREAD

**Issue by runny-yolk** [dotnet/csharplang#3778]
This feels like something that may have been proposed before, but I had a look through the open/closed issues with search terms "IEnumerator" and "foreach" and didn't find anybody proposing this, but all the same, apologies in advance if this is a duplicate, or if there's an obvious reason that this isn't already a feature that I just completely missed; I'm fairly new to C#, but I like to think I do my homework on every lang I use.

The foreach statement is pretty much just syntactic sugar for stepping through an IEnumerator - at least, that's what I understood from [the spec of the foreach statment](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-foreach-statement):
```csharp
// x must implement IEnumerable
foreach (V v in x) embedded_statement

// goes to..
{
    // e is an IEnumerator
    E e = ((C)(x)).GetEnumerator();
    try {
        while (e.MoveNext()) {
            V v = (V)(T)e.Current;
            embedded_statement
        }
    }
    finally {
        ... // Dispose e
    }
}
```

My proposal is this:
```csharp
// x can be IEnumerable or IEnumerator
foreach (V v in x) embedded_statement

// goes to..
{
    // in the case that x is an IEnumerable
    E e = ((C)(x)).GetEnumerator();
    // in the case that x is an IEnumerator
    E e = x;
    // both of the above can be compile-time checks, so no additonal runtime overhead
    // e is an IEnumerator, everything else proceeds the same way
    try {
        while (e.MoveNext()) {
            V v = (V)(T)e.Current;
            embedded_statement
        }
    }
    finally {
        ... // Dispose e
    }
}
```

The advantage of this would be the ability to _seriously_ cut down on boilerplate needed to make simple use cases of foreach and IEnumerator work (sorry, I use tab indentation, and Github renders tabs as **many** spaces):
```csharp
using System.Collections.Generic;

class Example {
	class NumerableFor: IEnumerable<int> {
		int l;
		public NumerableFor(int _l){
			l = _l;
		}
		IEnumerator<int> IEnumerable<int>.GetEnumerator(){
			// the rest of this class is boilerplate, which needs repeating in a slightly different way for every different foreach use case
			// the below is the only line of functionality
			for(int i = 0; i < l; i++) yield return i;
		}
		IEnumerator IEnumerable.GetEnumerator(){
			// ...and the line needs to be repeated as well
			for(int i = 0; i < l; i++) yield return i;
		}
	}

	// all that should be needed
	IEnumerator<int> For(int l){
		for(int i = 0; i < l; i++) yield return i;
	}

	void Main(){
		// works, but requires the verbose implementation above
		foreach(int i in new NumerableFor(5)) Debug.Log(i);

		// doesn't compile, but would if my proposal was implemented
		foreach(int i in For(5)) Debug.Log(i);

		// based on what foreach expands out to
		// works, but is fairly verbose to use every time
		// more or less what the above would expand to if my proposal was implemented
		{
			IEnumerator<int> e = For(5);
			try {
				while (e.MoveNext()) {
					int i = e.Current;
					Debug.Log(i);
				}
			}
			finally {
				e.Dispose();
			}
		}
	}
}
```
Obviously this is a ridiculous real use case (you can just use a for loop), but I wanted to keep it as simple as possible to demonstrate just how much boilerplate is needed, and what it would look like if it wasn't. My actual use case is iterating over portions of 3D arrays, so being able to go `foreach(var (x,y,z) in For3D(1,2,3)) statement;` would be really useful, and much more succint than a bunch of `for` statements. Currently I've just stomached the boilerplate, which clutters up my `Utils` class.

As well as enabling my specific use case though, implementing this proposal would add flexibility to a useful feature of the language - something that I'd say is a good thing for its own sake. `foreach` is an abstraction designed to make the life of a developer easier, so making it easier to use would make sense, right?

An alternative implementation to this proposal that would achieve the same goal - and probably have other unintended side effects - would be implementing IEnumberable for IEnumerator and having it return itself when GetEnumerator is called. Can't implement this as an extension method, unfortunately.

**Comment by YairHalberstadt** [comment]
There's very few cases in which you would enumerate an IEnumerator directly, and in most of those cases it's because you don't want to consume it completely, just partially and then store the enumerator for later use.

I just can't see the demand for this, especially seeing as there's a perfectly valid way to do it already available.

Given that most enumerators don't require disposal iterating over them is usually as simple as:

```csharp
while (e.MoveNext()) {
    int i = e.Current;
    Debug.Log(i);
}
```

That's only 1 line more than:

```csharp
foreach (var i in e) {
    Debug.Log(i);
}
```

**Comment by YairHalberstadt** [comment]
> An alternative implementation to this proposal that would achieve the same goal - and probably have other unintended side effects - would be implementing IEnumberable for IEnumerator and having it return itself when GetEnumerator is called. Can't implement this as an extension method, unfortunately.

With C# 9.0 you should be able to use an extension GetEnumerator() in foreach.

Try [this on sharplab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQQB4wgO2QSwHsdUxCkoBjACwB8ABAJgEYBYAKHoAYACe5gCwBuDh3oBmPox4BhHgG8OPZX0n0BPALIAKAJIBRHHAC2EBLHIAefDhgA+HrhNmLCAJQKlK72Qo0e2gBuUAg8+GE4jkam5jDkbl7eSXzMAJza+G4i7MnKiTwAvhxF7GJqzABsUjz6WLgExMgcijkqEilVBtEucQiWACoOAOIQMIbOsVaD2jDU+Mg8XROuAw5OMa4eALxr3ZMI2QVAA=) on the "extension GetEnumerator" branch.

**Comment by runny-yolk** [comment]
> > An alternative implementation to this proposal that would achieve the same goal - and probably have other unintended side effects - would be implementing IEnumberable for IEnumerator and having it return itself when GetEnumerator is called. Can't implement this as an extension method, unfortunately.
> 
> With C# 9.0 you should be able to use an extension GetEnumerator() in foreach.
> 
> Try [this on sharplab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQQB4wgO2QSwHsdUxCkoBjACwB8ABAJgEYBYAKHoAYACe5gCwBuDh3oBmPox4BhHgG8OPZX0n0BPALIAKAJIBRHHAC2EBLHIAefDhgA+HrhNmLCAJQKlK72Qo0e2gBuUAg8+GE4jkam5jDkbl7eSXzMAJza+G4i7MnKiTwAvhxF7GJqzABsUjz6WLgExMgcijkqEilVBtEucQiWACoOAOIQMIbOsVaD2jDU+Mg8XROuAw5OMa4eALxr3ZMI2QVAA=) on the "extension GetEnumerator" branch.

Oh nice! Looks exactly like what I'd need. Unfortunately, I'm working with Unity, so I'm limited to 7.6 😅 Seems like the lang already has the feature I want though, so I'll close the issue.

> 
> For your specific case (iterating through 3 dimensional arrays) you could even do:
> 
> ```cs
> using System;
> using System.Collections.Generic;
> 
> public class C {
>     public void M(int[,,] arr) {
>         foreach (var (a, b, c) in (0..arr.GetLength(0), 0..arr.GetLength(1), 0..arr.GetLength(2)))
>             Console.WriteLine(arr[a,b,c]);
>     }
> }
> 
> public static class Extensions
> {
>     public static IEnumerator<(int, int, int)> GetEnumerator(this Range a, Range b, Range c)
>     {
>         foreach (var aVal in a)
>         {
>             foreach (var bVal in b)
>             {
>                 foreach(var cVal in c)
>                 {
>                     yield return (aVal, bVal, cVal);
>                 }
>             }
>         }
>     }
>     
>     public struct RangeEnumerator
>     {
>         public RangeEnumerator(int start, int end) => (Current, _end) = (start - 1, end);
>         public int Current { get; private set; }
>         private int _end;
>         public bool MoveNext() => ++Current < _end;
>     }
> 
>     public static RangeEnumerator GetEnumerator(this Range range)
>     {
>         if (range.Start.IsFromEnd || range.End.IsFromEnd)
>             ThrowIsFromEnd();
> 
>         if (range.Start.Value > range.End.Value)
>             ThrowStartIsGreaterThanEnd();
> 
>         return new RangeEnumerator(range.Start.Value, range.End.Value);
> 
>         static void ThrowIsFromEnd() => throw new ArgumentException("range start and end must not be from end");
>         static void ThrowStartIsGreaterThanEnd() => throw new ArgumentException("start is greater than end");
>     }
> }
> ```

Thanks! Currently I'm just using integers as the arguments, and for loops for the iteration, I hadn't thought about ranges. This'll come in handy.

**Comment by HaloFour** [comment]
For previous versions of C# you can always write an extension method for the `IEnumerator<T>` that wraps it back in an `IEnumerable<T>`:

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQuADAAS6EAsA3GZTYQHQAyAlpgI5OlmAZlYA2GvioBRTOjCIIMAPYIpAD3iYoXJVqoBvMlWM0RtcTLkLlq2fIQRgAGzgAeACoA+Ku6WX7ji4engAUMAAWXFBUAJL+1irBVHB2CQgAlAZGJjm4AOxUmHAA7tKpDjbxDs5uXiEpVhUq6QI5AL5k2ca4IrAYAMYwZY2KKlWBtd6GpDk5AA4IXABuinBUCHAQACa6TgCeseM2SQ0BNgJdsz3DZ2PlEyFx98deyc/NWTOz3xFRbKdpKgAXjeI3Ol3anS+32uTzBiVeAHE4DAjioQpkgd4AU0EK0TB1SITmIRxARWAVprlSTQ6FQALIQHgYz7fYwrBCg26ckHjGpsABKEEwAHM4CEKEgqABWdJsZGo94IDH47440YINj0pRLOAAOTgGhVEJM6psWp1+sNMGN0NmJuMADMVJt+uEqCEOVQVk50GseFy0mxfHyXBjMlS2dSAJyeiC+uAtB1UQlRy6EtpAA=)
