### ISSUE TITLE
[Bug] Assigning to (discard) _

### ISSUE THREAD

**Issue by willem640** [dotnet/csharplang#3782]
You're somehow able to assign to the discard, as if you would use _ as a variable name.

Steps to reproduce:

Have a try catch block, and catch Exeption _
```cs
try
{
    throw new Exception();
}
catch (Exception _)
{
    _ = 5;
}
```

Compiling the prededing code results in an error: `Error CS0029: Cannot implicitly convert type 'int' to 'System.Exception' (CS0029)`

From that error, I get that somehow the discard operator got a value, but correct me if I'm wrong.

Using the discard operator there is, of course, not the way to do it, but as I understand it you should not be able to assign anything to the discard operator, weird code or not.

I use C# 9, and if it's of any significance, my project's target framework is netstandard2.1, though the error isn't any different if I switch to netcoreapp3.1.

`dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Hope this is of any help.

**Comment by HaloFour** [comment]
When the compiler introduced `_` as a discard it retained compatibility with `_` as an identifier in any scenario where that was already legal, such as `catch (Exception _)`.  That introduces a local in scope with the identifier `_` of type `Exception` which can be referenced by that name for the rest of the block.  As you now have an identifier with the name `_` in scope the compiler no longer treats it as a discard so it considers your assignment as attempting to assign to the existing variable.

The `catch` clause has a different mechanism for discarding the exception variable, exclude the identifier:

```cs
try
{
    throw new Exception();
}
catch (Exception)
{
    _ = 5;
}
```

**Comment by willem640** [comment]
So it's not a bug? Seems so strange to me that you can use something that seems reserved to me as a normal identifier without using @ .

**Comment by HaloFour** [comment]
`_` isn't a reserved identifier in C#.  You could (and still can) use it as an identifier.  In C# 7.0 it was changed to also be a discard, but to preserve backward compatibility with existing code it is only considered a discard if no identifier by that name is already in scope, or for syntax that wasn't legal before.

**Comment by willem640** [comment]
Alright, thanks for enlightening me

**Comment by jnm2** [comment]
The same is true of many keywords. `var` or `nameof` or `from`, for instance. They are called contextual keywords because they are only keywords in certain contexts.

**Comment by willem640** [comment]
Interesting! I'm only a beginner, hence my confusion.

**Comment by 333fred** [comment]
If you have other C# questions, you might find it easier to join one of the C# communities like https://discord.gg/csharp or https://gitter.im/dotnet/csharplang, which are chat communities that will likely give you a quicker response time :).

**Comment by willem640** [comment]
I will! Thanks for the recommendation!
