### ISSUE TITLE
Enhance Auto Property Pattern

### ISSUE THREAD

**Issue by Flutterish** [dotnet/csharplang#3784]
Auto properties should support extended syntax other than just `<mod> <name> { get; <mod> set; }`. That is when I want to invoke a method or modify the value before setting it, I have to make a private field. I propse we get rid of that need.
```cs
public double Time {
    get;
    set {
        new += 1;
        CacheInfo();
        new = value; // new + [op] keyword means its not a breaking change
    }
}

public double Angle {
    get;
    set => AnimateRotationTo( new = value );
}

public float Alpha {
    get => value + 0.1f; // value can now be used in get as the current field value
    //set => value - 0.1f; // this is NOT ALLOWED
    set => new = value - 0.1f;
}
```
This is equivalent to:
```cs
private double time;
public double Time {
    get => time;
    set {
        time += 1;
        CacheInfo();
        time = value;
    }
}

private double angle;
public double Angle {
    get => angle;
    set => AnimateRotationTo( angle = value );
}

private float alpha;
public float Alpha {
    get => alpha + 0.1f;
    set => alpha = value - 0.1f;
}
```
This would mean cleaner internals for types as there are no leftover private fields. One thing you might consider bad is that now there is no way to get the private value and you must rely on the getter, in which case you must use the current style.

How would the compiler know what is an auto property and what is not? One empty `set` or `get` would indicate it, or the use of the `new + [op]` in `set` or `value` in `get`.

**Comment by khm1600** [comment]
#140
