### ISSUE TITLE
[sugestion] Simplify syntax for typeof expression

### ISSUE THREAD

**Issue by leandromoh** [dotnet/csharplang#3789]
C# 7.1 improved [default expression](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/target-typed-default.md), allowing us to omit the parameter type when it was redundant , 
what let us write `SomeType obj = default` instead of `SomeType obj = default(SomeType)`, and it was amazing.

In a similar way, I feel a certain redundancy when working with `typeof` expression, like 
1) `typeof(T) == typeof(SomeType)`
2) `Type objectType = typeof(SomeType)`
3) `var objectType = typeof(SomeType)`
4) `objectType == typeof(SomeType)`

So my sugestion is basically allow the  `typeof` to be omitted. Aside from that, it behaves like `typeof(T)`.
The main motivation are to avoid typing redundant information.
So the previous examples would become the follow correspondents:

1) `T == SomeType`
2) `Type objectType = SomeType`
3) `var objectType = SomeType`
4) `objectType == SomeType`

At least for me, looks quite more natural. Specially to write `T == string` than `typeof(T) == typeof(string)`.

**Comment by theunrepentantgeek** [comment]
Changing the keyword **default** worked precisely because it is a reserved keyword, so there were no breaking changes involved.

Unfortunately, allowing the use of a type name to be used in place of **typeof** would be a breaking change.

For example, in the following code the statement `Foo(Demo)` is currently unambiguous; if `Demo` was a synonym for `typeof(Demo)` it would be ambiguous. Introducing a compiler error like this would undoubtedly break existing code.

``` csharp
public class Demo { }

public class C {
    
    private void Foo(Demo d) {}
    private void Foo(Type t) {}
    
    public Demo Demo { get; set; }
    
    public void M() {
        Foo(Demo);
    }
}
```

**Comment by Flutterish** [comment]
I believe what you are proposing is making a static type name eqivalent to its dynamic type description. While this does make sense to me, as @theunrepentantgeek pointed out, its a breaking change.

I think this could be resolved by making a variable name take precedence over a type name in ambigious context, like a variable name already does `Demo Demo; // Demo is the variable`. This would be equivalent to having a `static readonly Type` variable assigned to every namespace containing that type ( which namespaces can't do ).

**Comment by leandromoh** [comment]
@theunrepentantgeek woow, I did not think that. It would really be a breaking chance, unless we define a precedence as @Flutterish pointed out. 

Anyway, as the suggestion apparently had not a good reception, I will close the issue. 
Thanks for feedback!
