### ISSUE TITLE
Proposal: support deconstructing directly to a parameter list

### ISSUE THREAD

**Issue by DavidArno** [dotnet/csharplang#379]
(I'm fairly sure this has already been asked for, but I can't - as usual - find it. So I'm taking the lazy route of requesting it and relying on @alrz's search-fu to point out the dup if it does exists, already 😁)

**Problem**
I have a method:
```cs
int F(int p1, int p2) => ...
```
Pre-C#7, one simply provided the parameters and all was well. As of C# 7, I now might have a tuple of `(int,int)`, or a type `SomeThing` with a `void Deconstruct(out int, out int)` declared.

In both cases, having to explicitly deconstruct the value and still specify the two parameters seems cumbersome. Instead, it feels like it should be possible to do the following:
```cs
var tuple = (1, 1);
var someThing = new SomeThing();

var r1 = F(tuple);
var r2 = F(someThing);
```

**Possible solution**
For the generalised expression:
```cs
F(a)
```
* If `a` is a tuple of `n` values and `F` doesn't have an overload that takes a tuple of `n` values as a single parameter, but does have an overload of `n` parameters of matching types, then the compiler will replace `F(a)` with `F(a,Item1, ..., ItemN)`.  
* If the type of `a` has a `Deconstruct` that returns `n` values  and `F` doesn't have an overload that takes a single parameter of `a`'s type, but does have an overload of `n` parameters of matching types, then the compiler will replace `F(a)` with:
```cs
(item1, ..., itemN) = a;
F(item1, ..., itemN);
```

**Lambdas**
For the case of `F2(Func<int, int, int> func)`, the tuple case could further be extended to auto-deconstruct the tuple to the parameter list of a lambda:
```cs
var tuple = (1, 1);
var result = F2(tuple => ...);
```
could be converted to:
```cs
var tuple = (1, 1);
var result = F2((tuple.Item1, tuple.Item2) => ...);
```

**Comment by alrz** [comment]
#153, #258

**Comment by DavidArno** [comment]
Closing this as, as @alrz has pointed out, it's a dup of #258.
