### ISSUE TITLE
Allow Tuple Syntax for 1-Tuples (Tuple<T1>)

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/csharplang#3793]
*Okay, first time submitting & semi-professional developer; please be gentle!*

Even though .NET provides the struct [ValueTuple<T1>](https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple-1?view=netcore-3.1 ) for 1-tuples (i.e. singleton tuples), tuple syntax isn't supported:

`(string foo) Hello; // Syntax errors!`
`(int bar, bool baz) World; // Okay!!` 

From looking at the above's syntax tree, it looks like 1-tuples are being evaluated as expression statements, while higher-order tulpes are evaluated as variable declarations.

I think tuple syntax for 1-tuples should be allowed for parity at least.  For my use case, I'm putting together a scripting framework that wraps the .NET scripting library with some extra functionality. One way I was considering having scripts declare expected input is with a tuple declaration (e.g. `(string foo, char bar) input;`). This option becomes less attractive if tuple syntax isn't allowed for 1-tuples.

**Comment by YairHalberstadt** [comment]
This is championed by @gafter at https://github.com/dotnet/csharplang/issues/883

**Comment by zacharylayne** [comment]
> This is championed by @gafter at #883

What's the etiquette here? Do I champion #883 ? Do I close this one?

**Comment by YairHalberstadt** [comment]
You'll struggle to champion it unless you join the language design team 😉 but you definitely should upvote that issue!
Closing this issue is best to avoid duplicates.

And welcome to the CSharplang repo - we look forward to hearing many more of your suggestions!

**Comment by zacharylayne** [comment]
Awesome! I appreciate it. :)
