### ISSUE TITLE
Property: using on properties

### ISSUE THREAD

**Issue by jimsnab** [dotnet/csharplang#3797]
It would be nice to extend `using` to properties, when the backing store is `field`. My example:

```
public using Font DisplayFont
{
    get
    {
        return field;
    }
    set
    {
        if (value == null)
        {
            throw new ArgumentNullException();
        }
        field = value;
    }
}
```

The concept here is to dispose `field` before it is overwritten, or when the property container is disposed.

It should also work with implicit `field`:

```
public using Font DisplayFont { get; set; }
```

**Comment by jnm2** [comment]
It would be surprising and unpleasant for me to discover that I had transferred ownership of a disposable object simply by setting a property to it. What if I want to switch back and forth between two fonts that I've already created?

**Comment by jimsnab** [comment]
You are right. My example is an ugly ownership transfer.

I guess I am ultimately trying to simplify disposal when I want the class to be the owner of `field`.

`field = using new Font(value);`

In the setter, but that implies the wrong scope.

Possibly not worth pursuing.

**Comment by theunrepentantgeek** [comment]
In the rare cases where ownership is transferred, a property assignment is the wrong model because no one will expect that behaviour. 

In similar situations, I've used a readonly property and a mutating method because that provides better clarity. 

For example, perhaps 

``` csharp
public Font Font { get; }

public void AdoptFont(Font font)
{ ... }
```

**Comment by jimsnab** [comment]
There's something here for a class or property level using, but the proposal needs much improvement. Abandoning.
