### ISSUE TITLE
allow nameof for private or protected member with special access modifier

### ISSUE THREAD

**Issue by tanekim77** [dotnet/csharplang#3808]
I have read a issue about similar topic in the closed issues, but I think there was not sufficient discussion about other alternative like the one below.

I think it will be very useful to have a special access modifier such that it will act like private/protected member when trying to access it's value but will act like public member when trying to access the member through nameof.
I.e.

```
public class A {
   allownameof private int _a;
   allownameof protected int _b;
}
```

```
var temp = new A();
temp._a => throws an error.
temp._b => throws an error.
nameof(A._a) => returns "_a"
nameof(A._b) => returns "_b"
```

This will be very useful when implementing domain driven design, where I want to have private/protected fields in POCO aggregate class that need to be mapped to columns through fluent api of Entity Framework. Currently, the only way to map private/protected fields to colums is to use magic string "_a" or "_b". This will be a huge burden to maintain if there are tons of private/protected fields to take care of.

**Comment by ZacharyPatten** [comment]
> Currently, the only way to map private/protected fields to colums is to use magic string "_a" or "_b".

There are multiple ways to accomplish this task currently.

You could add static string properties:
```cs
using System;

class Program
{
	static void Main()
	{
		Console.WriteLine(A.FieldOne);
		Console.WriteLine(A.FieldTwo);
		Console.WriteLine(A.FieldThree);
	}
}

class A
{
	private object _a;
	protected object _b;
	internal object _c;

	public const string FieldOne = nameof(_a);
	public const string FieldTwo = nameof(_b);
	public const string FieldThree = nameof(_c);
}
```

Or you could just use reflection to get the members:
```cs
using System;
using System.Reflection;

class Program
{
	static void Main()
	{
		foreach (FieldInfo fieldInfo in typeof(A).GetFields(
			BindingFlags.Public |
			BindingFlags.NonPublic |
			BindingFlags.Instance))
		{
			Console.WriteLine(fieldInfo.Name);
		}
	}
}

class A
{
	private object _a;
	protected object _b;
	internal object _c;
}
```

Or you could use code generation to make sure names always match up.

Personally I don't think a language change is necessary here (although I understand the reasoning). Types should not be dependent on the private members of other types as much as possible.

**Comment by tanekim77** [comment]
@ZacharyPatten Thanks for the input. The part I was talking about is the following scenario:

       ```
     _context.Entity<A>
                .Property("_a")
                .UsePropertyAccessMode(PropertyAccessMode.Field)
                .HasColumnName("_a")
                .IsRequired(false); // Here this line applies to "_a" only.

            _context.Entity<A>
                .Property("_b")
                .UsePropertyAccessMode(PropertyAccessMode.Field)
                .HasColumnName("_b")
                .IsRequired(true); // This line applies to "_b" only.
```
The solution you wrote about static strings work, but suppose there are many classes with many private fields, then having to write static strings will not only bloat the codes but also having to sync names of hundrends of private fields with that of the helper fields would also be cumbersome.

Another way you mentioned is to use reflection, but it still doesn't give me option to pick a specific field for specific configuration, as in the example.

**Comment by theunrepentantgeek** [comment]
This very much sounds like a perfect use case for writing a custom [Source Generator](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/). 

You can generate all the boilerplate that you want to avoid writing by hand, adhering to your very specific domain rules - and you can do it _**today**_, no need to wait for years for a language change.

**Comment by tanekim77** [comment]
@theunrepentantgeek  Thanks, I will look into it.

**Comment by john-h-k** [comment]
If other code relies on their exact name like that, surely they shouldn't be private? `internal` and get-only would be more suitable. Alternatively, allowing properties with private getters and setters would have a similar affect (can't read or write, but can `nameof`), but they are currently not legal
