### ISSUE TITLE
Inferencing of nullability for delegates

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/csharplang#3811]
The inferred nullability of types for parameters are not always applied to occurrences of those types in Func delegates. Consider the following: 

    public class xTestNullabilityInference
    {
        public void Create<TSource, T0, T1>(
            Action<T0, T1> action,
            Func<TSource, T0> expression0,
            Func<TSource, T1> expression1,
            T0 fallback0 = default(T0),
            T1 fallback1 = default(T1)
        ) where TSource : class, new()
        {
            action.Invoke(
                expression0.Invoke(new TSource()),
                expression1.Invoke(new TSource())
            );
        }

        public void Test()
        {
            this.Create(
                (Subject subject, int x) => { Debug.WriteLine($"subject.X is {subject.X}, and x is {x}"); },  // *** (a)
                (Subject subject) => subject,
                (Subject subject) => subject.X
            );
        }

        public void Test2()
        {
            this.Create(
                (subject, x) => { Debug.WriteLine($"subject.X is {subject.X}, and x is {x}"); },  // *** (b)
                (Subject subject) => subject,
                (Subject subject) => subject.X
            );
        }
    }

Expected: no nullability warnings. The Subject parameter in the lambda expression should not be nullable, because TSource should be inferred as non-nullable in the second and third arguments to Create. 

Actual: 'subject' in the 2nd and 3rd arguments to Create is inferred to be non-nullable in both the argument and the body of the lambda expression. However, 'subject' in the 1st argument to create is inferred to be nullable. On line (a), a warning CS8662 is generated on the entire delegate saying "Nullability of reference types in type of parameter 'subject' of 'lambda expression' doesn't match the target delegate 'Action<Subject?, int>'.  On line (b), a warning CS8602 is generated on 'subject.X' saying that 'subject' may be null here and indicating that the type of 'subject' is Subject?. 

Noting that I am working with NETStandard.Library 2.0.3 and Microsoft.NETCore.Platforms 3.1.2 due to the fact that I am targeting UWP. Would the attributes in NETCore 5.0 prevent the problem described above?

**Comment by canton7** [comment]
If you remove `T0 fallback0 = default(T0)` and `T1 fallback1 = default(T1)`, the warning [goes away](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobABgAJt8A6AEQEsIBzAOwHtYGBjKAbhIBiVgFcANmIjAxcCnFZSZJbAGYquCgA8AKnFgA5cZOAMxDGAE8AkqwBmiedzgkA3iQoeqa7ABYKAYQQ4CHgAHm0AZXYRBCckCm0yeO18AD4ACndPbOpccKSEtIoIbhgGdlYkLOyPbABWcKiYuISyVLlNAAcgqChy1iTqmvrG6Ni4ZKK4Lp6+iqJibIBKCgB3AAsHBKbxihB1eNY4VfSlobdFmo8SsoqaGwA3dgBrOEzLq+zp7r05gfvWE9XukjqttmMnKcllUPp8PN9Zv1aI8Xm9QeDmm8lmdYcsBLCAL4kIaqKh+XSwU7nIbZGDrBhQGiBYLwd5w7LpCIiYAAKzgpQoUG5fNK8QYrBgWhWAF52i4KHQ4MARMwaAB1BDmOAAGXFbwAJAAiIW8/kwGgADQoDIoLhNIvNFoJ8QgrBQWmtUFtmgJhqWfAozo8AHpgxQAFSRijpCA49meTnCs2CpOlGXte1mmHxjyJ00CzNpiiylP5x00zz+oZE4gk7zkvQwXBU2EXOF0hlMoIhN4Vq7pQsweKadO2hVKlXqzXwXVHdJGweWz22xdOl1uj02lw+v0BoMUUMRqPpYBxnN5h2lh2jwfZ89cstXs031Pl3GV/HZGs15TeDQPh1XBpUlxUlK15WYOAYADKAoL3TwSAJIA).

The issue is of course that `T0 fallback0 = default(T0)` tells the compiler that if `T0` is a reference type then it can be null, which is why (presumably) it's inferring `T0` as a `Subject?` rather than a `Subject`. Yes it's inferring `TSource` as a non-nullable `Subject` but that's not the source of the warnings.

**Comment by sjb-sjb** [comment]
Interesting. Seems like quite a pain in the neck, too. I have a variant of this with 8 parameters instead of just 2. I do want the fallback parameters to be optional. How can I do it? With 8 type parameters, writing out all the variations of class vs struct constraints for all of them would mean 256 signatures, which seems like about 255 too many. Any suggestions?

**Comment by canton7** [comment]
If you make `fallback0` a `T0?`, then that shuts it up. [Link](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobABgAJt8A6AEQEsIBzAOwHtYGBjKAbhLkqtRiw5deNAMLsUcAIKsIAGwCeUBvxIBiVgFdlyiMGVwKcJSbiCAzFVwUAHgBU4sAHIGjwBsoYxVAElWADNEC25rYgBvEgp4qjtsABYKKQQ4CHgAHmcAZXY9BEikCmcyUud8AD4ACjiExupcXIqymooIbhgGdlYkBsb47ABWXIKikrKyavNHAAcMqA0+isGh0fHC4rhKjrgFpZXWfAHiIYTygH4KEJVlYC6Aa0oAXgo5O4MYWvKASjOF3iVVu90e3Ce+Ao70+EG+v3wf3WfwoAHcABbhMoTHYUED2UqsOCo2pI84JWLki5dHp9GjBABu7CecHqVKB8QOizcxzI9NYTJZtSJqOx20ipIB6w5XKOvRO/MFrJFYsmrL+ZI5fwE7IAviR1tgkqlXLBSetKRyYOjNNIMllWdKgbU8npgAArODdChQN2e7qlBisGBOFGvWbRCh0ODAPTMGgAdQQ/jgABkg6yACQAIl9Hq9MBoAA0KJoKNE8/7C0XdaUIKwUE5S1By45ddntRRa/EAPQ9igAKiHFFqEE1HISLr9BZ90+6YdmlYLgIn8Sn+e9S/n0MXc+rTvi2vW+uIhuNZTcMFw5vZlqB1tt6Uy8DZq7XW5gpUcC/LUZjccTZN4HTIlahzD9i2bcsIJrOsGybMtojbDs+C7UoKD7Qdh1qYBx1Xdcq1nDcYB/D8V3w11iKIqtSL3YsDwoI89RIE9bHsChKKrEg7wSI1S2DCgS0jZg4BgVCoFE1DdQSFigA==).

This functionality is being introduced in C# 9. If you're using 8, then you can add `where T0 : class` if possible.

**Comment by sjb-sjb** [comment]
What I conclude is that nullability is not really working in 8, it does not have the tools to enforce non-nullability (if desired) or to defeat all the problems caused by the fact that nullable types are not actually types and the fact that nullability cannot be applied to unconstrained types. When I search on the topic I see so many posts that all seem to boil down to these issues. 

How about having a real type system for nullable types, defining the type that "T?" represents when T is an unconstrained type, and just using attributes to tell the compiler the intended type mapping for code that was written in the old language? I feel that we have gone down the wrong path on this one ...

**Comment by sjb-sjb** [comment]
Going back to the original question, how can I work around this in C#8 ?

**Comment by HaloFour** [comment]
@sjb-sjb 

This was all debated at length.  NRTs have to fit into an ecosystem nearly 2 decades old, where 95%+ of the existing APIs already enforce that parameters are not null.  Creating a new type system will break that _entire_ ecosystem and require rewriting everything.  Having a perfect type system that nobody can or will use is pointless.  NRTs aren't perfect, but they don't have to be.  They need to be good enough guardrails to keep most developers from accidentally tripping over common cases.  This is the same approach that a lot of other languages take, like Kotlin, Swift and Typescript.  This is the approach Jetbrains has used for R# and IntelliJ for C# and Java respectively.

**Comment by sjb-sjb** [comment]
I guess what I don't understand is why creating a new type system would break the existing ecosystem. For a given method, class, struct, or interface in the existing ecosystem there would be a corresponding method, class, struct, or interface in the new language. The correspondence would be to simply add ? to all the reference types except where indicated by a [NotNull] attribute. It seems like a straightforward injection of the old language into the new one. In cases like bool TryGetX( out X x) in the old language, the mapped signature would be bool TryGetX( out X? x), which admittedly is not an improvement over the old signature but it also is no worse than the old signature either. Over time new signatures could be added such as X? TryGetX() and the old signatures could be deprecated.  In terms of finding latent bugs in the old ecosystem, I think a lot would be uncovered by just null-checking at runtime to match the signatures on inputs and outputs when calling into the old language. Other than such latent bugs, adoption would be pretty much automatic since people wouldn't have to work through all the problems that we are discussing and add a lot of complex attributes just to get the compiler to infer what people want it to infer.

**Comment by sjb-sjb** [comment]
True you would have to add a lot of [NotNull] attributes in the existing ecosystem, but I think that you are doing that (or something more difficult, actually) anyway under the current approach.

**Comment by sjb-sjb** [comment]
Closing this as the answer seems to be that C#9 will solve the problem in this example.

**Comment by sjb-sjb** [comment]
@CyrusNajmabadi commented that the purpose of NRT is to enable improvement of past code, and that we don't want to break existing code. And @theunrepentantgeek pointed out the pain that was caused in Python by making a breaking change. 

At the same time, where do we want to be in 5 or 10 years? Do we want to still be in a place where we do not really definitely know that a non-nullable variable actually is not null? Do we still to still be testing for null and throwing runtime exceptions? I believe the answer is we want to eventually get to a place where non-nullable values are definitely always not null, so that runtime tests and exceptions are eliminated. That means eventually we want to get to a typed approach to nullability. 

So ... what about eventually introducing "#nullable typed" which would compile as a typed-based system. It seems eminently do-able to figure out the interaction between code compiled this way and code compiled with, say, #nullable enable.
