### ISSUE TITLE
Records: Equality operator override in record types? (==)

### ISSUE THREAD

**Issue by dale-palmer** [dotnet/csharplang#3815]
Are there plans to override the equality operator in a record type? This behaviour may be intentional but it is certainly unexpected at first.

Here is a code sample:

```
class Program
{
    static void Main(string[] args)
    {
        var john = new Person("John Doe", 42);
        var john2 = new Person("John Doe", 42);

        Console.WriteLine(john.Equals(john2));  // true
        Console.WriteLine(john == john2);       // false
    }
}

record Person(string Name, int Age);
```

**Comment by 333fred** [comment]
Yes: https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-07-27.md#Equality-operators-in-records. Hope that helps.

**Comment by PathogenDavid** [comment]
As Fred noted, `==` support for records is coming, but the change isn't yet available in the compiler in the current .NET previews.

However the change has been implemented and is available in daily builds of the compiler. If you want to try them, the easiest way is to use [`Microsoft.Net.Compilers.Toolset`](https://github.com/dotnet/roslyn/blob/master/docs/compilers/Compiler%20Toolset%20NuPkgs.md) from [Azure DevOps](https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet-tools). (Don't use the MyGet feed referenced on that page, it's out-of-date and should be fixed soon.)

**Comment by dale-palmer** [comment]
That's great. Thanks guys!
