### ISSUE TITLE
Adding ThrowsWhenNullAttribute

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#3816]
Look at the following code segment:

```
using System;

#nullable enable

public class Program
{
    public void Foo(string? s)
    {
        if (s is null) throw new ArgumentNullException(nameof(s));
    }

    public void Bar(string? s)
    {
        Foo(s);
        Console.WriteLine(s.Length);
    }
}
```

Note the warning: `CS8602: Dereference of a possibly null reference.`

My suggestion is to add ThrowsWhenNullAttribute in .NET runtime, which the compiler should special treat it to know what a specific method throws an exception if an argument is null.

So, the following code shouldn't have any warnings:

```
using System;

#nullable enable

public class Program
{
    public void Foo([ThrowsIfNull] string? s)
    {
        if (s is null) throw new ArgumentNullException(nameof(s));
    }

    public void Bar(string? s)
    {
        Foo(s);
        Console.WriteLine(s.Length);
    }
}

**Comment by canton7** [comment]
Use `[NotNull]`: that does what you want.

From [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute?view=netcore-3.1) (which aren't particularly clear here, granted):

> Specifies that an input argument was not null when the call returns.

**Comment by Youssef1313** [comment]
@canton7 Thanks. That makes sense. Closing this.
