### ISSUE TITLE
Type inference from the body of a method

### ISSUE THREAD

**Issue by Daynvheur** [dotnet/csharplang#3817]
Hi everyone.

I have a request about type inference, in the case where the type could be infered from a lambda's input parameter:
```
using System;
public class C
{
    public void M<T>(T useless, Action<T> action) => M(useless, s => M1(s)); // Ok
    public void M<T>(string useless, Action<T> action) => M(useless, s => M1(s)); // Ok, T *is* string because of the M's overload resolution
    /* // Only one at a time ->
    public void M<T>(Action<T> action) => M<T>(s => M1(s)); // Ok
    public void M<T>(Action<T> action) => M((Action<T>)(s => M1(s))); // Ok
    */
    public void M<T>(Action<T> action) => M(s => M1(s)); // CS0411

    void M1<T>(T s){}
}
```
The `s => M1(s)` input parameter is not automatically infered as compatible with `T`, unless expressing it as such.
@YairHalberstadt on Gitter found the related documentation [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#type-inference), it seems to be a language change request.

What would the requirements to infer `T` from `M1`'s input be? (When dropping the `useless` param.)
The samples provided here are overly simplified, but the use case is based on a real one.

**Comment by ZacharyPatten** [comment]
You appear to be trying to get the body of `public void M<T>(Action<T> action)` to be able to implicitly call another `M` method, but your other `M` overloads take two parameters, not one.

If you change this line...
```cs
public void M<T>(Action<T> action) => M(s => M1(s)); // CS0411
```
To this...
```cs
public void M<T>(Action<T> action) => M(default(T), s => M1(s));
```
Then it might be doing what you want it to, but I find it a little unclear from your description.

---

Did you instead mean for `public void M<T>(Action<T> action)` to call `M1` rather than `M`? In that case that would not work because C# requires a delegate type when using lambdas. You cannot do this for example:
```cs
var action = s => Console.WriteLine(s);
```
The compiler needs to know the type of the lambda:
```cs
Action<string> action = s => Console.WriteLine(s);
```

**Comment by ZacharyPatten** [comment]
I wrote a better example... Hopefully this helps:
```cs
using System;

public class Example
{
	// Example 1 (works)
	public void A<T>() => B(s => Console.WriteLine(s));
	public void B(Action<string> action) => action(default);

	// Example 2 (works)
	public void C<T>(Action<T> action) => D(action);
	public void D<T>(Action<T> action) => action(default);

	// Example 3 (works)
	public void E<T>() => F((T t) => { });
	public void F<T>(Action<T> action) => action(default);

	// Example 4 (does not work)
	public void G<T>() => H(s => Console.WriteLine(s));
	public void H<T>(Action<T> action) => action(default);
}
```

You appear to be running into `Example 4`.  `Examples 1-3` all works because they retain the type of the generic. In `Example 4`, you take in an `Action<T>` but you never use it, and thus the compiler has no way to infer the type because you are making a lambda that doesn't have `T` on it.

**Comment by Daynvheur** [comment]
Thanks for the sample preciness/modifications, the 2-params `M` method is only there to show something worky, not the usecase (which you guessed is calling `M1` instead of `M`).

May you accept to propose the same for an extract of a [more near-real](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQBgAIUMA6AYQHsAbauAYxgEtKA7KCt+gVwQTlYwA3LgLEMAFhF4iJUgBkmrAI7SxJAKzTcS+AlYRq4gGzE0hAMoQwABzq4A3rgCQAYn4BzFq0IA5SjCEAO6UCADWSh7BTDAAFpTcgXAAHnZM9DGRhHFwhACq2QCeNrnQhABCuC4oAMwmhMCUNJZwMABKEDAwEPSxcGACMFAAFIqwADwAggB8hNRMsJNQAJQuALyzhJOMAOICiEzK3HBTADTl08OEAPTXhACiqfxQUHAAJoTjF0UlLs7O1BIaBAcwWMCWpz+zjekzebwAKpRyhAPCDhlBKANJqcGijVjh/s4NriPKRYQikSjhlDnEwAGb+cGsQogjEDcqEYkwBDHSEEwkQOFo5ac2YAWQgNnRmLgk2Wyz5hLeQJBwBRAEl4GAOcSACKUYZqjya/rlfH/fGEK3Wq1IJC4G027YwPasA5HODU/kAlWgxZQRX/ah5EFuoKEMYwL6XBU3O6PGzPV4faM/OBQmFwxHI1GEaVYnFG83/YlGslZykeL2E2kMgKTZmsmU62bc3k0wVvYWiwgSqVs2XywPQ31Gk3anv6w0arVmv6Wx22+04RdW52u93HatB33zf3DzMUnNooFnQhUVg8PiDHPR6bLYb52WFvFxh5POAvd6fb4wYrp71SxRcsjypGl6UZBsWUIAcW2yHk4GHZxO27Yk+yfOUhwzUcZ1NScDTHWdiwXRc7QdVd132BBDi3KFAQwYE/XBAMM3JbMUTRAdsRJYsiVmMs2Mrbd/gg+tGxg5sezbRCOyFPMRTQyUMKw71lQYk8GOjB9CLwvUCNw7V5TfBMk2/VM/1+fkSMdMiVwo3YqJouBbjPb433ICx8AkDAMBxeF/3yQh6AgVhWACBpciUOlEG/OkEExQhD3Y1FT3hHELyvfhBFvPJpmmHEwoQQg4oStTgVPXK/mE+jGL3Zjh1uYNQzgcNI2jYZY1ufJL0xAZBDmApgDgahKHDGBKEIKLEHyViK2PG4ACphlPbiMt4LKYFvC57wW64MJfDwRS61L0q4dabxRcZctmMAmA8WJAiGybWGi/gPjKFbTsvc7ssu7bCAAfihIDSUEnNhNrSDxNgqSEKQlD5J7dCuKHN9ySsehxnhG67oeiLnte78ynRnpUwBwgAHVYkKSaoAkrEAHI6Ys3IwsCMIwqCHwgdU31riW08LmWXadInPTp2NIj520AlXAEN5PG8PxwpCcIsiCGJ4kSQgUjSDJmFYKIckClnCDKSocBcdw4C8NhzzYeBkhgKoCUTJgADdOlyEhTEaZpKLdaiPSxnFctGMEsdmGqcRO+3vuvX6PCuvLErBlEY803LEqBc0nH5NaE82y6s6NTlCDDOPMoupOw+WaR/gABQgBBDDoahSAAMVCe4eliYZo+yHskqEmADvlevnBQAB2LYHMDpyJZxMq65cABfcirRcN3Pfgeo/aMAPNxONL8kuNrsbmIEcTarPg0WvJXjoF40w+Gxm+sXaM7QEPK5+oua5TsPHMX9k7ZwYrnP4BcNo5X4iiMuFcoHV2Th1CeTcW60GGp3buvd+5X0HsSIBVJR48RXvyaes8XSOQ9IvMBaBSHOHXpbV21Ed7ewwL7JoB855H0jstDANRI4khARfZeLg86N3fhg9uXcEA916DQ0WQ8gQS3HOPP45DpL10YbgVwiYUSQGCM3VgWQ3gLAgMAOghB1S6nuPgfAxgiBdTQdYVoiAmaEG4K8cu4V+B0E9v1Po/AXbOG3l7eoKAJCECnByGI/QRQOEINogktR6gcnQpMSaWoFKzArhyBJq8Za6Jbh4AxQQjFZGeONfgVibF2IccErqiDE6EAABLDRKEVAYcRKBvGqHUH2xBIlpyTtjYYcQFi/0LreC+RoY4aB/vvWYokmSFDmYIzsED+T0jzGWKg3BBDDGWVBBSaxCD4F4gJOEwxOwdXoUk5wXUrC2EsSzOmbw4B0iUJkNgUA+lmC2IQfJfz0AVEBYk4F5hyBgvuXLVgCsbZKwvI7Z2OBV5AA==) sample?
The goal is to get rid of type re-expressiveness, the only acceptable type being `B` ; which might be accurately determined by the `() => Map(A item)` lambda of the `Func<T> add` delegate.

**Comment by Daynvheur** [comment]
I figured out how simplify the use case:
```cs
public void M1(string input) => M((input) => input);
public void M<T, U>(System.Func<T, U> reaction) {}
```
`M1` has `in T, out U`, but simply transfers input as output -> `U` is of type `T`, but the type is not infered.

Could that be possible to keep the `T` type alive when trying to resolve the `System.Func<T, U>`'s output?

**Comment by ZacharyPatten** [comment]
_Your example:_
> ```cs
> public void M1(List<string> input) => M(input, (second, name) => name.Add(second));
> public void M<T, U>(List<T> items, Action<T, List<U>> action)
> {
>     List<U> list = new List<U>();
>     Parallel.ForEach(items, item => action(item, list));
> }
> ```

In your new example, what you appear to be requesting is for the **compiler to be able to infer parameter types based on the usage of the parameters inside the body of a method** (in this case a lambda expression). By this I mean that in the lambda expression you are making, `(second, name) => name.Add(second)`, we know that `second` is a `string` because it is of type `T` on the definition of `M` and `T` can be inferred from the passing of `input` (which is of type `string`) as the `items` parameter to `M`. At this point we know `name` is of type `Action<string, List<U>>` but inside the body of the lambda you are calling the `.Add(...)` method and passing in a `string` value into that method, and you appear to be requesting that the compiler be able to infer `U` to be `string` based on calling the `List<string>.Add(...)` method.

However, even in your new example **the type of `U` still cannot be inferred to be `string`.** It could still be a lot of values such as anything that is implicitly cast-able from a string:
```cs
using System;
using System.Collections.Generic;

public class Example
{
    // this is "M" from your example
    public void A<T1, T2>(List<T1> list, Action<T1, List<T2>> action) { }

    // Note: This is "M1" from your example.
    public void B(List<string> input) => A(input, (second, name) => name.Add(second));

    #region New Examples (All work)

    public void C(List<string> input) => A(input, (string second, List<string> name) => name.Add(second));

    public void D(List<string> input) => A(input, (string second, List<MyClass> name) => name.Add(second));

    public void E(List<string> input) => A(input, (string second, List<MyStruct> name) => name.Add(second));

	#endregion
}

public class MyClass
{
    public static implicit operator MyClass(string a) => new MyClass();
}

public struct MyStruct
{
    public static implicit operator MyStruct(string a) => new MyStruct();
}
```

But more to the point... that is not how the type system works in C#. The compiler doesn't infer types from usage of normal methods (or anything other than methods) based on usage. Why should that be a feature for lambda expressions? C# is a type-safe language, and your request would inevitably break the type-safeness of the type system.

**Comment by Daynvheur** [comment]
I don't expect that to become a feature for lambda expression, but a general thought about type infered from method bodies.

You are totally right about your `New Examples` region, I'm trying to call `List<U>.Add(...)` with `...` mapped to a specific (unique) deterministic type, in a may that should not result in multiple compatible types...

```cs
using System;
using System.Collections.Generic;

public class Example
{
	// this is "M" from your example
	public void A<T1, T2>(List<T1> list, Action<T1, List<T2>> action) { }

	// Ok
	public void C1(List<string> input) => A(input, (string second, List<int> name) => name.Add(Map(second)));
	public void D1(List<MyClass> input) => A(input, (MyClass second, List<double?> name) => name.Add(Map(second)));
	public void E1(List<MyStruct> input) => A(input, (MyStruct second, List<decimal?> name) => name.Add(Map(second)));

	// Ko
	public void F(List<int> input) => A(input, (/*int*/ second, /*List<ouput type of Map(int)>*/ name) => name.Add(Map(second)));
	
	private int Map(string item) => 10;
	private double? Map(MyClass item) => 0;
	private decimal? Map(MyStruct item) => null;
}

public class MyClass
{
	public static implicit operator MyClass(string a) => new MyClass();
}

public struct MyStruct
{
	public static implicit operator MyStruct(string a) => new MyStruct();
}
```

Isn't there any way to ask for an implicit type inference from method bodies if (and only if) only one candidate is valid?

**Comment by ZacharyPatten** [comment]
> if (and only if) only one candidate is valid

You appear to be under the impression that there is a situation in which there could only be one possible type that could be valid to populate a specific generic parameter. This is likely not the case. If you have examples please prove me wrong, but **I don't think this situation is possible at the moment.**

Your new example doesn't appear to add anything to the scenario. Were you trying to use the `Map` overloads to reduce the number of possible values that `<T2>` could be? If that was your intent, it did not do what you intended. It doesn't matter that you are calling a non-generic method inside the lambda, there are still multiple types that `<T2>` could be:
```cs
using System;
using System.Collections.Generic;

public class Example
{
	public void A<T1, T2>(List<T1> list, Action<T1, List<T2>> action) { }

	// removed other examples because they are irrelevant

	// this does not work by design
	public void F(List<int> input) => A(input, (second, name) => name.Add(Map(second)));

	#region Working Examples

	public void G(List<int> input) => A(input, (int second, List<int> name) => name.Add(Map(second)));
	public void H(List<int> input) => A(input, (int second, List<MyClass2> name) => name.Add(Map(second)));
	public void I(List<int> input) => A(input, (int second, List<MyStruct2> name) => name.Add(Map(second)));

	#endregion

	// removed other "Map" methods because they are irrelevant

	private int Map(int item) => 10;
}

public class MyClass2
{
	public static implicit operator MyClass2(int a) => new MyClass2();
}

public struct MyStruct2
{
	public static implicit operator MyStruct2(int a) => new MyStruct2();
}
```

Hopefully I did not missunderstand your comment.

**Comment by Daynvheur** [comment]
You're again right in that the `Map()` doesn't change anything, you did not missunderstood my comment.
I thought that would be a simple thing to request, that the `<T2>` type could be infered straightforwardly from the (apparently not) only compatible type when one was available.

Closing the issue now, as I can't provide anything more constructive.
