### ISSUE TITLE
[Proposal] Add Permutate LINQ function in C#

### ISSUE THREAD

**Issue by sps014** [dotnet/csharplang#3824]
Permutation function is not that hard to implement, so many people might be asking why not create a Extension Method yourself.

#### That's a fair question , actually until now we have been using Permutate function like this, I really don't have good points to counter that.

1. I come from competitive programming background, i solve all the problems in C# i really encounter many problems involving permutation , In Languages Like C++ and Python  already providing built-in  implementations. Everytime i have to either reinvent the wheel or copy from one of my previous solved question if am using C#.
```cpp
//C++ STL builtin
 auto v=std::next_permutation(myints,myints+3);
```
```py
from itertools import permutations 
# python permutations iter tools
p = permutations(s) 
```

2. We have several other LINQ functions that are also easy to implement ourself like Where, Select etc. but at the end of the day we are having them in C#.

3. It won't be a breaking change in C# ecosystem, people won't be troubled with that .

4. With DotNetCore 5 and C# 9 I am expecting more and more people migrating towards C# , this function can come in handy for beginners just like Top Level Programs will benefit them.

##### Proposal 
The Idea is to have a Permutate LINQ Function like,
```cs
var list=new List<int>();
var allPer=list.Permutate().ToList();
allPer=list.Permutate(startIndex:3).ToList();
allPer=list.Permutate(startIndex:3,endIndex:5).ToList();

```

**Comment by spydacarnage** [comment]
That would be a proposal for the runtime, not the language team.
Also, you should probably expand your proposal to include what you would want this Permutate method to do.

**Comment by HaloFour** [comment]
This repository is for requests to the language syntax itself.  For requesting the addition of new functions I'd suggest opening a proposal in the [runtime repo](https://github.com/dotnet/runtime) instead.

**Comment by sps014** [comment]
Oh , so sorry to put it in wrong repo , i thought this might be general C# Repo, migrating and closing this issue from here...

**Comment by ZacharyPatten** [comment]
@sps014 Please link this issue if when you create a new issue. I am interested in this topic. :)

I have made my own versions of this topic if you would be interested in seeing my implementations.

**Comment by sps014** [comment]
Currently I have migrated this issue [here ](https://github.com/dotnet/runtime/issues/41399) .
feel free to share your implementation, if possible please switch to new  [runtime issue repo](https://github.com/dotnet/runtime/issues/41399).
