### ISSUE TITLE
Add a simpler way to type conversion

### ISSUE THREAD

**Issue by musli** [dotnet/csharplang#3834]
old:
```
var grid = ((sender as FrameworkElement).Parent as FrameworkElement).Parent as Grid;
or
var grid = (Grid)((FrameworkElement)((FrameworkElement)sender).Parent).Parent;
```
new:
`var grid = sender => FrameworkElement.Parent=>FrameworkElement.Parent=>Grid;`

**Comment by TJtangjun** [comment]
sender<FrameworkElement>.Parent<FrameworkElement>.Parent<FrameworkElement>

**Comment by Richiban** [comment]
If you do this a lot in certain projects, you can introduce an extension method like so:

```csharp
var grid = sender.As<FrameworkElement>().Parent.As<FrameworkElement>().Parent.As<FrameworkElement>();
```

Or even another one called `Parent`:

```csharp
var grid = sender.As<FrameworkElement>().Parent<FrameworkElement>().Parent<FrameworkElement>();
```

**Comment by dstarkowski** [comment]
> Or even another one called `Parent`:
> 
> ```cs
> var grid = sender.As<FrameworkElement>().Parent<FrameworkElement>().Parent<FrameworkElement>();
> ```

IMO not only doesn't require new ways to do the same thing in the language, but is also easiest to read of all the proposals. Yet it cures symptom not the cause.

Been years since I did any wpf, but I think your code shouldn't really know about exact structure of your control tree. Otherwise small changes in layout may break the app.

@musli 
If you really need reference to that Grid and are sure it is somewhere there, consider implementing method that traverses the tree and finds nearest ancestor of given type.

**Comment by PathogenDavid** [comment]
Similar issue with different motivations and similar response: #2009

As an aside, if you aren't going to check for null when using `as`, you're generally better off casting because it gives a [much more useful exception when your assumption was wrong](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQZA9sAFZwDGMABBYwLyOZwDujAQgBQBKANxkyuQgE5+AIgC0CxUrmMAwtCZcAljAAWjaI2XGZIsjAQBPMgG8yjB434tDAQUEA6ACIUAKrq1MAHMhUVIAXzI6CBg6fX4AUQAPOjgABxgtCkxGOCTBW3tHCWk8swixUhLQ8SlZY2VGADkKBEgAG0Zo2CMGxVMwi2tSO1JHJ353Ck8ff0CQ8sjSaNj45NSMrJyywrHiurKwpfEAZkYCRldd8dwz3AAWRlmA4KFGGyXjqrv8PnfwoA=).

**Comment by HaloFour** [comment]
@musli 

`=>` is already the lambda operator in C#.

**Comment by HaloFour** [comment]
Sounds like a perfect case for recursive pattern matching as well.

```cs
var grid = sender switch {
    FrameworkElement { Parent: FrameworkElement { Parent: Grid value } } => value,
    _ => null // or throw expression
};
```

**Comment by musli** [comment]
> 听起来也是递归模式匹配的完美案例。
> 
> ```cs
> var grid = sender switch {
>     FrameworkElement { Parent: FrameworkElement { Parent: Grid value } } => value,
>     _ => null // or throw expression
> };
> ```

Thank you, I think this way of writing is not concise enough. I hope to build a new way of writing, using keywords "to" or "=>" or other, in order to achieve the purpose of directly accessing the converted class

**Comment by musli** [comment]
> 如果在某些项目中经常这样做，可以引入一种扩展方法，如：
> 
> ```cs
> var grid = sender.As<FrameworkElement>().Parent.As<FrameworkElement>().Parent.As<FrameworkElement>();
> ```
> 
> 甚至另一个叫做 ：`Parent`
> 
> ```cs
> var grid = sender.As<FrameworkElement>().Parent<FrameworkElement>().Parent<FrameworkElement>();
> ```

Thank you for your answer, my usage here is just for example, not limited to wpf controls

**Comment by musli** [comment]
> > Or even another one called `Parent`:
> > ```cs
> > var grid = sender.As<FrameworkElement>().Parent<FrameworkElement>().Parent<FrameworkElement>();
> > ```
> 
> IMO not only doesn't require new ways to do the same thing in the language, but is also easiest to read of all the proposals. Yet it cures symptom not the cause.
> 
> Been years since I did any wpf, but I think your code shouldn't really know about exact structure of your control tree. Otherwise small changes in layout may break the app.
> 
> @musli
> If you really need reference to that Grid and are sure it is somewhere there, consider implementing method that traverses the tree and finds nearest ancestor of given type.

**Comment by musli** [comment]
> > 甚至另一个叫做 ：`Parent`
> > ```cs
> > var grid = sender.As<FrameworkElement>().Parent<FrameworkElement>().Parent<FrameworkElement>();
> > ```
> 
> IMO 不仅不需要用新方法来在语言中做同样的事情， 而且最容易阅读所有的建议。然而，它治愈的症状，而不是原因。
> 
> 自从我做任何 wpf 以来已经很多年了， 但我认为你的代码不应该真正知道你的控制树的确切结构。否则，布局的小更改可能会破坏应用。
> 
> @musli
> 如果确实需要对该网格的引用，并且确定它位于该网格的某处，请考虑实现遍历树并查找给定类型的最近祖先的方法。

Thank you for your answer, my usage here is just for example, not limited to wpf controls

**Comment by musli** [comment]
> > 甚至另一个叫做 ：`Parent`
> > ```cs
> > var grid = sender.As<FrameworkElement>().Parent<FrameworkElement>().Parent<FrameworkElement>();
> > ```
> 
> IMO 不仅不需要用新方法来在语言中做同样的事情， 而且最容易阅读所有的建议。然而，它治愈的症状，而不是原因。
> 
> 自从我做任何 wpf 以来已经很多年了， 但我认为你的代码不应该真正知道你的控制树的确切结构。否则，布局的小更改可能会破坏应用。
> 
> @musli
> 如果确实需要对该网格的引用，并且确定它位于该网格的某处，请考虑实现遍历树并查找给定类型的最近祖先的方法。

Thank you for your answer, my usage here is just for example, not limited to wpf controls

**Comment by musli** [comment]
> > Or even another one called `Parent`:
> > ```cs
> > var grid = sender.As<FrameworkElement>().Parent<FrameworkElement>().Parent<FrameworkElement>();
> > ```
> 
> IMO not only doesn't require new ways to do the same thing in the language, but is also easiest to read of all the proposals. Yet it cures symptom not the cause.
> 
> Been years since I did any wpf, but I think your code shouldn't really know about exact structure of your control tree. Otherwise small changes in layout may break the app.
> 
> @musli
> If you really need reference to that Grid and are sure it is somewhere there, consider implementing method that traverses the tree and finds nearest ancestor of given type.

Thank you for your answer, my usage here is just for example, not limited to wpf controls
