### ISSUE TITLE
C# 9 Preview 8 - Record with public setters violates immutability.

### ISSUE THREAD

**Issue by majorimi** [dotnet/csharplang#3836]
I'm just trying out C# 9 which is getting some cool features. Thanks for that.
Mostly interested in **Records**. As I understood **Records are _immutable_ by nature and got compiled to a class**.

So what I done is wrote one class with one public Get/Set prop and, as a lazy developer, Copy->Pasted and changed it to a Record. Immediately got surprised when did not get build error... Got more surprised when I was **able to SET a value of a record after instantiation**... In my opinion **It violates the record type itself**. Hence the whole feature is meaningless basically record can be "cheated" back to a simple class (except the value type comparison).

```
using System;

var c1 = new ClassObj();
c1.Id = 5;
var r1 = new RecordObj();
r1.Id = 5; //Huge violation of Record type
Console.WriteLine(c1.Id);
Console.WriteLine(r1.Id);
Console.WriteLine(r1.Equals(new RecordObj() { Id = 5 }));
Console.WriteLine(c1.Equals(new ClassObj() { Id = 5 }));

public class ClassObj
{
	public int Id { get; set; }
}

public record RecordObj
{
	public int Id { get; set; } //set; should not be allowed!
}
```

Output:
```
5
5
True
False
```

**Comment by HaloFour** [comment]
@majorimi 

> As I understood Records are **immutable by nature**

This is not true.  Records provide value identity/equality, not immutability.  Positional records will provide init-only properties by default, but may be overridden.

**Comment by majorimi** [comment]
Thanks for your answer. 
Yes I get the value based identity/equality and works perfectly. However I think most of the posts are a bit misleading about the new Record feature. All examples showing code with Records having { get; init; } properties and talking about immutability. But same **{ get; init; } can be applied on a Class** properties as well. Hence **making that class immutable**.

I think even the official announcement misleading. It can be interpreted: if you want immutability declare it as a record. However it has nothing to do with record as you said.. So the code examples show a new feature by using another new feature... Yes I understand immutability and records go hand in hand, that's why I **was thinking Records should be immutable by default. Hope the team can add a default read-only shorthand soon.**

https://devblogs.microsoft.com/dotnet/welcome-to-c-9-0/#records 
"If you want the whole object to be **immutable** and **behave like a value**, then you should consider declaring it as a record:"

**Comment by HaloFour** [comment]
@majorimi 

I agree, the old posts can make it confusing.  I do believe it's intended that the default behavior of records will be readonly (as is the case with positional records) but there was a lot of confusion around the design for nominal records.  The suggested syntax in that blog post was to declare the members like fields and they would automagickally become readonly/init-only properties, and I believe that was shot down during design review.  As mentioned the team is still considering syntax that would make it easier (and thus encourage) init-only members within a nominal record:

```cs
public record Foo
{
    data string Name; // becomes an init-only property
}
```

**Comment by majorimi** [comment]
Sorry to hear that the original design failed to get into the product. There was probably some reason... I like the shorthand but may **I suggest to use the "init" or "readonly" keywords**. So do not introduce one more keyword....

```
public record Foo
{
    init string Name; // or
    readonly string Name;
}
```
