### ISSUE TITLE
[Proposal] ConcurrentList<T>

### ISSUE THREAD

**Issue by luizfernandonb** [dotnet/csharplang#3837]
As far as I know, there is no thread-safe collection that works exactly with ```List<T>```, there is```ConcurrentBag<T>```, but let's face it, it is not the same thing, nor can we remove an exact object that we want when using it, and this is definitely not a good thing.

My proposal is in the title, create a ```ConcurrentList<T>```, or improve the ```ConcurrentBag<T>```.

**Comment by HaloFour** [comment]
Thanks for the submission!

Proposals for new types or APIs are better handled by the [runtime](https://github.com/dotnet/runtime/) repo which works on the base class library.  This repository is specifically for changes to the syntax of the C# language.

**Comment by luizfernandonb** [comment]
Okay, sorry, I'll do the issue there.
