### ISSUE TITLE
Challenge: succinct null testing / throw for member invocation with nullability enabled. 

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/csharplang#3838]
As people start to enable nullability checks in their code, there are often situations such as this: 

    this.ToggleCommand.EngageWhileLoaded(this); // warning, ToggleCommand may be null

Obviously the warning is easily eliminated by inserting "?" after "ToggleCommand". However, this produces code that is not a strong as we might like, because if there is a bug that results in ToggleCommand being null then no exception will be raised and the programmer will not be alerted to the fact that there is a problem. Pre-nullability an exception would have been thrown. 

Now, for expressions rather than member invocation we can use ?? to throw an exception instead, without a lot of fuss: 

    ICommand command = this.ToggleCommand ?? throw new NullabilityLogicException();

The challenge is, how can we have a similarly succinct syntax to throw an exception in the member invocation case? For example can we create syntax such as this?

    this.ToggleCommand?.EngageWhileLoaded(this) ?? throw new NullabilityLogicException();

sjb

**Comment by HaloFour** [comment]
The following will silence the warning while continuing to throw the exception:

```cs
this.ToggleCommand!.EngageWhileLoaded(this)
```

**Comment by sjb-sjb** [comment]
Hmmm. True. No control over the type of exception though. And I might argue somewhat unaesthetic inasmuch as it means putting null into a non-nullable reference (that you then dereference). It is equivalent to 

    ICommand command = this.ToggleCommand!;
    command.EngageWhileLoaded(this);

This is contrary to the world-view that you should avoid using "!" in right-hand-side expressions (I know, not everyone shares that view). What I want instead is something equivalent to:

    ICommand command = this.ToggleCommand ?? throw new NullabilityLogicException();
    command.EngageWhileLoaded(this);

sjb

**Comment by 333fred** [comment]
It seems to me that `NullabilityLogicException` is just another name for `NullReferenceException`.

**Comment by DavidArno** [comment]
> ... What I want instead is something equivalent to ...

What about:

```cs
if (!(ToggleCommand is {} command)) throw new NullabilityLogicException();
command.EngageWhileLoaded(this);
```

Ideally, with C# 9 I'd write it as:
```cs
if (ToggleCommand is not {} command) throw new NullabilityLogicException();
command.EngageWhileLoaded(this);
```
But that currently gives an error: `error CS8780: A variable may not be declared within a 'not' or 'or' pattern`.

**Comment by PathogenDavid** [comment]
If you really want succinct syntax for this: ([SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFAACATAIxVXUDMhdhAKnLFQN5VCQ9mwDCAezCQ0AEwD8XcQHMlBCVIiyA3IOG6hrdgBZCAEXHdYACgCU+wgMrDnhKzAAWASygA6TstU4dWkZITkFDwRxAHdCNDhYgDlsXGBPLE8YAE8AGWVPAGMAUQAPArgABxhPcTRbGx8itCUIJTgAdS8CPIgZOBk3LygbHSdhAF8qScpmNg5gzRl+e0NqEyaWts70uB6+gfFgACs4AphCcTsxl0IAXgA+QkiYuITCRPEYAEkwCoIwEjwGSlcpVGp1EZTJg0Oa0d4pPDpTK5fLFMqVaq1QggQggjHghyEaZAA=))

```csharp
(this.ToggleCommand  ?? throw new NullabilityLogicException()).EngageWhileLoaded(this);
```

-----------

However I agree with Fred here. If `ToggleCommand` can be null, then your method should have some sensible behavior when it is null. If it's a private method that should only be called when `ToggleCommand` is already known to be non-null, then this isn't an unreasonable use of `!`, IMO.

**Comment by sjb-sjb** [comment]
@PathogenDavid thanks I think that does it. Would prefer the ?? at the end but such is life.
I'm not saying ! is unreasonable but I would like to live in a world without it, at least to the extent possible :-)

**Comment by sjb-sjb** [comment]
P.S. @333fred  I would point out the difference between NullReferenceException and something like NullabilityLogicException is that NullabilityLogicException is intended to occur as soon as any attempt is made to access a non-nullable variable that contains null, while NullReferenceException is not intended to occur until that variable is actually de-referenced. This after all is the key difference between nullable references and lazily-initialized non-nullable references -- early occurrence of exceptions prevents null from being copied around and propagated to a distant part of your code.

**Comment by 333fred** [comment]
While I see your point, I do believe that, for at least the 60% case, those points are the same point. There are certainly some points where you return a value and then dereference it later. But I would assert that the combination of NRT (where you will get a warning if you do something bad, at the location you do it) and regular NullReferenceExceptions are enough to handle this. If I could go back in time to C# 1.0 we'd have first-class `Option<T>` in the language, but we don't have that option :)
