### ISSUE TITLE
How to test for non-nullable property using reflection? 

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/csharplang#3841]
I have a PropertyInfo and would like to test whether or not the property is non-nullable (i.e. has either a non-nullable value type or a non-nullable reference type). 

Jon Skeet's blog on NullabilityAttribute (https://codeblog.jonskeet.uk/2019/02/10/nullableattribute-and-c-8/) is suggestive but doesn't actually say how to do it, and the structure of it does not look very easy at all. I can't even resolve a reference to NullabilityAttribute, although Pierre Arnaud suggested a way around this (http://code.fitness/post/2019/02/nullableattribute.html). Then again, there is a Roslyn doc that starts by saying that NullabilityAttribute is for the compiler only and should not appear in source (https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md).

Is there anything existing or in someone's head that will do this? 

sjb

**Comment by 333fred** [comment]
https://github.com/dotnet/runtime/issues/29723 was going to be shipped in 5.0, but it looks like it was slipped to a future milestone. Until that ships, you're either going to have to interpret the annotations yourself or use some library that was created to do this (I don't know of any, to be clear).

**Comment by sjb-sjb** [comment]
I see there is a StackOverflow question on this with an answer by Canton7: https://stackoverflow.com/questions/58453972/how-to-use-net-reflection-to-check-for-nullable-reference-type
