### ISSUE TITLE
No CS4014 when passing an async lambda to a function that expects a synchronous function

### ISSUE THREAD

**Issue by G3Kappa** [dotnet/csharplang#3842]
Say you have a `void Foo(Action<string> callback)` method - it expects a synchronous callback and fires it at some point during execution. From the POV of the library maintainer, there's no reason to believe that `callback` wouldn't block.

As it turns out, I can call it like this: `Foo(async x => { Console.WriteLine(x); })`. It seems to me that, in this case, the callback is not awaited, and it just runs in a separate thread. In fact, I discovered this due to the DbContext concurrency issues that arose while debugging an ASP.NET application. 

It's not unexpected behaviour, because regular non-awaited calls behave much in the same way.

The problem is that, when passing async lambdas to methods that don't expect them, the compiler generates no warnings. This doesn't match the current behaviour for non-awaited async method calls, which correctly generate a CS4014 warning.

Is there a compelling reason for this or was it just an oversight?

(Yes, I'm aware that `Foo` can be refactored to accept a `Func<string, Task>` but this isn't always possible!)

**EDIT:** The example I provided is wrong, as my problematic Foo implementation actually returns a Task\<bool>.

**Comment by HaloFour** [comment]
The `async` keyword doesn't make a method execute on a different thread.  It only enables the `await` keyword and the state machine machinery within the method.  If that method never uses `await` then the method will execute synchronously.

**Comment by PathogenDavid** [comment]
I believe this is by design. It's essentially generating an `async void` method, IE:

```
async void Lambda(int x)
    => Console.WriteLine(x);
```

Also in your specific example [you should be getting a warning](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKF+gZlwG9cACCs9Ncy0nSxsgMQHtWAKFADjIA8yAXgB8VDAE4OfAJTSA3LQoBfRWVUoCYgGxUALC3ZcMaADwoMABlEBjCABs7wCNYDW01fUYqc3oA):

> warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

**Comment by HaloFour** [comment]
Agreed, there should be a warning that the `async` lambda isn't actually "asynchronous" (since it doesn't `await` anything).

As for why this is possible (or `async void` exists at all) was to enable using `async` method with existing event handlers and calling back interfaces.

**Comment by G3Kappa** [comment]
> 
> 
> I believe this is by design. It's essentially generating an `async void` method, IE:
> 
> ```
> async void Lambda(int x)
>     => Console.WriteLine(x);
> ```
> 
> Also in your specific example [you should be getting a warning](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKF+gZlwG9cACCs9Ncy0nSxsgMQHtWAKFADjIA8yAXgB8VDAE4OfAJTSA3LQoBfRWVUoCYgGxUALC3ZcMaADwoMABlEBjCABs7wCNYDW01fUYqc3oA):
> 
> > warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

That makes sense, but I'm getting no warning. The project is on C# 8.0, and this is how my method looked before refactoring:

`protected virtual async Task<bool> Foo(int id, Action<MyEntity> beforeCommit)`

`beforeCommit` was being called like a normal action in-between two other asynchronous functions. Come to think of it, the example I provided is wrong, so maybe there's something I'm missing here related to Foo being asyncrhonous.

This is how I call it:

```csharp
public virtual async Task<bool> OnBar(int id)
        {
            return await Foo(id, async e =>
            {
                e.MyFlag = true;
                await SomethingElse(e);
            });
        }
```

Now I've refactored `Foo` to:

`protected virtual async Task<bool> Foo(int id, Func<MyEntity, Task> beforeCommit)`, and I've made sure to await `beforeCommit`, but either way, no warnings whatsoever.

**Comment by PathogenDavid** [comment]
> As for why this is possible (or `async void` exists at all) was to enable using `async` method with existing event handlers and calling back interfaces.

Yup, [the example given in the C# language reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions#async-lambdas) is even using it for exactly that.

---------

@G3Kappa The warning associated with your original example had to do with the fact that you had an `async` method with no `await` -- method referring to the lambda rather than `Foo`. Since your actual code has an `await` in the lambda, there's warning.

If your codebase is heavily async and you have no legitimate or limited legitimate uses for `async void`, your best bet is to add an analyzer to your project.

**Comment by PathogenDavid** [comment]
> **EDIT:** The example I provided is wrong, as my problematic Foo implementation actually returns a Task<bool>.

What `Foo` returns (or whether it is `async` for that matter) has no affect here. The only thing that matters is the type of the `callback` parameter.

**Comment by G3Kappa** [comment]
Oh, I see... And now I understand the reasoning behind it. Thank you! It seems counter-intuitive at first, but given that there are valid motivations behind it, and given that I was able to fix my issue, I'll rest my case.

I'll read up on the spec!

**Comment by PathogenDavid** [comment]
No problem! Yeah, sometimes stuff in the language can seem a bit strange, but there's usually a reason for it (that reason usually being legacy nonsense or it isn't strange when you consider other contexts.)

If you're gonna go all-in on reading the spec, I should point out that [the newer language features are in separate documents](https://github.com/dotnet/csharplang/tree/31289a8255732df5c0379a6d197142109b7afced/proposals).

Also if you like reading on dead trees, there's a [woefully out-of-date annotated version of the C# 4 spec](https://www.amazon.com/gp/product/0321741765/) you might be able to find used. (Obviously it's too old to use on its own, but the annotations are still interesting and largely relevant today.)

**Comment by jnm2** [comment]
Also, there are community analyzers that flag this exact scenario along with other usages of `async void` as warnings.
