### ISSUE TITLE
Implicitly scoped fixed statement

### ISSUE THREAD

**Issue by RUSshy** [dotnet/csharplang#3849]
We have ``using var disposable = new Disposable()``

Can we please have the same for fixed? ``fixed byte* ptr = buffer``

**Comment by 333fred** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/2186.

**Comment by RUSshy** [comment]
Oops my bad, i made sure to search before posting, i couldn't find anything about it

Thanks!
