### ISSUE TITLE
[question] error CS8506: No best type was found for the switch expression.

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/csharplang#3852]
why tip this error? how to fix it?
```csharp
int n = 10;
// ...
await (n switch {
    1 => Task.Yield (),
    2 => Task.Yield (),
    3 => ((Func<Task>)(async () => {
        await Task.Yield ();
    })).Invoke (),
    _ => Task.Yield (),
});
```

version:
vs2019 community 16.7.2
.net core 3.1

**Comment by pinkfloydx33** [comment]
I'm guessing it's because `Task.Yield` returns a `YieldAwaitable` while the lambda returns a `Task`. They are both are "awaitables" but they don't share a common type.

**Comment by 333fred** [comment]
That's correct, there _is_ no common type possible here.

It seems like this question has been answered, so I'm going to close this out.
