### ISSUE TITLE
Cannot enfore generic method to accept record

### ISSUE THREAD

**Issue by Rainmaker52** [dotnet/csharplang#3859]
### Description
When creating a generic method on .NET 5, it is not possible to enforce the generic to be a "record" type. Instead "where T: class" needs to be used.

In my opinion, this should be possible. It will also hint to the compiler the input is read-only.

### Example
// Compiles. And, oddly enough, allows /records/ to be passed in:
public async ValueTask SendMessage<T>(T message) where T: class
// Does not work:
public async ValueTask SendMessage<T>(T message) where T: record

For the bot: Label area-TypeSystem-coreclr possibly?

**Comment by svick** [comment]
See the recent discussion following https://github.com/dotnet/csharplang/issues/39#issuecomment-675463741, where the conclusion was that this would not be useful, for example:

> The intent with records is that, hopefully in C# 10, there won't be a meaningful semantic difference between a record and a class. You'll be able to get all the benefits of records (such as `with`ability) in either the full form of a class or in the smaller record declaration. I'm just not sure what you actually want to to constrain to with that.

Keep in mind that records don't have to be read-only. For example, [the following is a perfectly valid record](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMABAMICwAUAN4WG2G4CMAbPQCyECyEAlpgBQBKGnWrk64wgDcICQrIC8hTHADuhAEqCA3MIlyAdAElCi1vh1i6AXwo3yFBHADGAewQATDRVHjcAZkJeGEJjSkIAczgYLUIoKJi7KyA):

```c#
record R
{
    public int I { get; set; }
}
```

**Comment by CyrusNajmabadi** [comment]
> It will also hint to the compiler the input is read-only.

Records are not read only :-)

**Comment by 333fred** [comment]
As stated in the conversation svick linked, this is very much by design. We'll let this issue stay open as a separate place to discuss this further, but please do read the conversation at that link as it contains a lot of info as to the motivations of the design team here.
