### ISSUE TITLE
Proposal: more improvements to nullable reference types

### ISSUE THREAD

**Issue by jcouv** [dotnet/csharplang#3868]
Follow-up on [C# 9 work](https://github.com/dotnet/csharplang/issues/3297).

Considered for C# 10:
- `Task<T>` (LDM tentatively approved, needs design proposal for task-like types)
- LINQ (LDM expressed interested to handle `Where`, needs design proposal)
- uninitialized fields and constructors (no plan, aside from MemberNotNull)

**Comment by alrz** [comment]
>uninitialized fields and constructors

I understand this isn't about records but could that replace https://github.com/dotnet/csharplang/issues/3630 somehow? 

I think the important distinction is to warn on object construction (new) rather than inside the constructor.

**Comment by jcouv** [comment]
Closing in favor of https://github.com/dotnet/csharplang/issues/3950 (Task<T>) and https://github.com/dotnet/csharplang/issues/3951 (LINQ).
The discussion of initialization debt is covered by required properties feature.
