### ISSUE TITLE
Checked expressions

### ISSUE THREAD

**Issue by Logerfo** [dotnet/csharplang#387]
Today, `checked` statements always requires curly braces. I understand that some statements like try/catch should require braces because of ambiguity issues, but that does not seem to be the case. I'd like to propose the following code to be possible:

```C#
checked i++;
```

Being equivalent to:

```C#
checked
{
   i++;
}
```

Being a little more audacious, it would be very nice if the following code were possible, but that's a plus:

```C#
int a = checked i + 1;
```

Being equivalent to:

```C#
int a;
checked
{
   a = i + 1;
}
```

I couldn't find any issue mentioning anything like that in the Roslyn repository. Am I missing something?
I guess the exactly same thing applies to `unsafe` statement, but I couldn't find anything either.

**Comment by alrz** [comment]
try `int a = checked(i + 1);`

**Comment by Logerfo** [comment]
@alrz I totally didn't see this coming lol guess we're done here
