### ISSUE TITLE
[Proposal]: [is-inference scope]

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/csharplang#3881]
The `Play` method defined in `Child` should be available from `Parent` variable `p` pointing to a `Child` object in a scope where `p` has passed the condition `if(p is Child)` below.

```
class Parent{}
class Child : Parent
{
    void Play() { }
}

class Program
{
    static void Main()
    {   
        Parent p = new Child();
        if(p is Child)
        {
            p.Play();
        }
    }
}
```

I am  inspired by the Dart language! Any comments are always welcome.

**Comment by pstricks-fans** [comment]
I just knew this feature, so I cancel this proposal. Thank you!

```
        if(p is Child dummy)
        {
            dummy.Play();
        }
```

**Comment by pstricks-fans** [comment]
Someone asked me to reopen this.

**Comment by leandromoh** [comment]
I think is more readable with a new variable...

```c#
if(p is Child c)
{
    c.Play();
}
```

**Comment by HaloFour** [comment]
The language can't reinterpret `p` to be a `Child` without introducing breaking changes as `Parent` can already have a non-virtual method called `Play`.

**Comment by 333fred** [comment]
As this is not a full syntactic and semantic proposal, I'm converting it to a discussion.
