### ISSUE TITLE
[Proposal]: Allow init-only auto-properties in readonly structs

### ISSUE THREAD

**Issue by HaloFour** [dotnet/csharplang#3884]
# Allow init-only auto-properties in readonly structs

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

I propose that C# relax the restriction around the types of auto-properties supported on readonly structs to allow init-only auto-properties.  Said properties are effectively immutable, only permitting mutation during initialization.  They are also backed by a readonly-field.

## Motivation
[motivation]: #motivation

Supporting init-only auto-properties in readonly structs would make it easier to create said types via initializer.  This would also enable "with" support for readonly structs in C# 10.0.

## Detailed design
[design]: #detailed-design

The compiler will relax the imposed restrictions on what types of auto-properties are allowed to be declared in a readonly struct to support auto-properties with an `init` accessor:

```cs
public readonly struct Point
{
    public int X { get; init; }
    public int Y { get; init; }
}

var point = new Point { X = 25, Y = 30 };
var anotherPoint = point with { Y = 35 };
```

## Drawbacks
[drawbacks]: #drawbacks

TBD

## Alternatives
[alternatives]: #alternatives

TBD

## Unresolved questions
[unresolved]: #unresolved-questions

TBD

## Design meetings

N/A

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/47652 :wink:

**Comment by 333fred** [comment]
Note: I didn't open the issue on csharplang directly because I don't believe it actually requires changing the init spec.

**Comment by HaloFour** [comment]
Is it worth leaving this proposal open to ensure that the spec includes verbiage that `init` is allowed here?

**Comment by 333fred** [comment]
Probably

**Comment by pkulikov** [comment]
@HaloFour @333fred 
Now, C# compiler allows to use `init` with **not** auto-properties as well. The following compiles:

```csharp
public readonly struct A
{
    private readonly int x;
    public A(int n) => x = n;
    public int X { get => x; init => x = value; }
}
```

However, note the preceding example assigns to the **field** in the constructor. Assignment to the property doesn't compile:
```csharp
public readonly struct A
{
    private readonly int x;
    public A(int n) => X = n;
    public int X { get => x; init => x = value; }
}
```

The error: `error CS0188: The 'this' object cannot be used before all of its fields have been assigned`

The variant with auto-property compiles:
```csharp
public readonly struct A
{
    public A(int n) => X = n;
    public int X { get; init; }
}
```

That seems inconsistent. Especially, the difference between the first two examples. In the second one, I can define an `init` accessor but cannot use it in the constructor. Is that by design?

**Comment by YairHalberstadt** [comment]
@pkulikov 

This is not related to init, but all structs.

The compiler requires you to set all fields of a struct before calling any of it's members.

With an auto-property, the compiler can "see through" the auto property and tell that it's actually just setting a field.

With a non auto-property the compiler can't do this. See it sees you calling X.init before setting the "x" field, and so gives you an error.

**Comment by YairHalberstadt** [comment]
For an example of why this is disallowed, consider the following:

```csharp
[SkipLocalsInit]
M()
{
    var a = new A();
    a.X[0] = 0; // will write into random memory
}

public readonly struct A
{
    private readonly int[] x;
    public A(int n) => X = n;
    public int X { get => x; init {} }
}
```

**Comment by pkulikov** [comment]
@YairHalberstadt ah, thanks! So, if I add the default constructor call in the second example like `: this()`, code compiles. Why doesn't the compiler do that for me?

**Comment by YairHalberstadt** [comment]
@pkulikov 

Because then you end up intializing all fields twice which is a performance issue.

**Comment by pkulikov** [comment]
@YairHalberstadt clear, thank you for explanations. (In particular, that means that using object initializers with stucts is not performance-friendly?)

**Comment by YairHalberstadt** [comment]
In practice no. I would expect the JIT to remove the double initialization, and the overhead is absolutely tiny anyway.
