### ISSUE TITLE
[Proposal]: Improve method overload resolution for implicit value type arrays

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/csharplang#3933]
# Improve method overload resolution for arrays

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
The current implementation of method overload resolution seems to treat implicit arrays of value types differently that reference types. I propose that implicit arrays of value types should be treated the same as explicit arrays and implicit arrays of reference types.

#### Why are we doing this?
To prevent the following runtime bug from happening:
```csharp
void Main() {
    FindAsync(new[] { 1, 2 }, new[] { 3, 4 });                 // 1
    FindAsync(new[] { 1, 2 }, CancellationToken.None);         // 1
    FindAsync(new object[] { 1, 2 }, CancellationToken.None);  // 2
    FindAsync(new[] { "1", "2" }, CancellationToken.None);     // 2
}

public void FindAsync(params object[] keyValues) {
    Console.WriteLine("1");
}

public void FindAsync(object[] keyValues, CancellationToken token = default) {
    Console.WriteLine("2");
}
```

#### What use case does it support?
Implicit value type arrays being passed to a method with multiple overloads. This is an issue that currently happens with `FindAsync` in EF Core:
https://github.com/dotnet/efcore/issues/22667

#### What is the expected outcome?
The method resolution logic should match that of explicit arrays and implicit reference type arrays.

## Detailed design
If a method has multiple overloads, one with params of object[] and one with object[] and a second parameter, the second overload should be used when passing an implicit array and a second parameter that matches the type of the second parameter.

For example, this should be the outcome:
```csharp
void Main() {
    FindAsync(new[] { 1, 2 }, new[] { 3, 4 });                 // 1
    FindAsync(new[] { 1, 2 }, CancellationToken.None);         // 2
    FindAsync(new object[] { 1, 2 }, CancellationToken.None);  // 2
    FindAsync(new[] { "1", "2" }, CancellationToken.None);     // 2
}

public void FindAsync(params object[] keyValues) {
    Console.WriteLine("1");
}

public void FindAsync(object[] keyValues, CancellationToken token = default) {
    Console.WriteLine("2");
}
```

## Drawbacks
It could break existing code with the very specific scenario of a method having two overloads, one with params of object[] and one with object[] and a second parameter.

## Alternatives
This could possibly be an analyzer that warns users that they need to be more specific with their use of an API.

## Unresolved questions
None

**Comment by CyrusNajmabadi** [comment]
i don't think we could change behavior here as there will be code that depends on existing semantics.  You could certainly create your own analyzer that warns if you use this pattern if you think it's problematic for your domain.
