### ISSUE TITLE
[Proposal]: allow the keyword interface as generic constraint

### ISSUE THREAD

**Issue by BrayanKhosravian** [dotnet/csharplang#3964]
# allow the keyword interface as generic constraint

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

This feature would allow restricting generic parameters for any interface.

## Motivation
[motivation]: #motivation

The motivation is to make generic constraints more flexible and restrictive.

With the given proposal the caller could specify any interface instead of a specific one.
And the caller is restricted not to specify a class or a struct.

## Detailed design
[design]: #detailed-design

the following code does not compile:
```cs
public void RegisterService<TService, TInterface>()
	where TService : class
	where TInterface : interface // <- CS1031 "type expected"
{
	_containerBuilder.RegisterType<TService>().As<TInterface>();
}
```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

1.) A possible workaround would be to create a "markup interface" which is empty and use it for the constraint.
But this means that all interfaces have to implement that "markup interface".

2.) Not to restrict for only interfaces and use `class` as a constraint

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by svick** [comment]
> The motivation is to make generic constraints more flexible and restrictive.

That's not really a motivation. **Why** do you think such constraint would be useful?

**Comment by BrayanKhosravian** [comment]
With the given proposal the caller could specify any interface instead of a specific one.
And the caller is restricted not to specify a class or a struct.

Will update the proposal.

**Comment by svick** [comment]
@BrayanKhosravian That still only describes what the proposal is, but not why should it be added to the language.

**Comment by 333fred** [comment]
I'm going to move this to be a discussion. I'm also not convinced _why_ this needs to be a constraint, and I think some discussion around the topic would be better before making this a full proposal. What issue are you trying to solve? What code does this enable that wasn't possible before? Motivating examples are very helpful for trying to understand why you want to see this feature in C#.
