### ISSUE TITLE
[Proposal]: Multiple usings from same namespaces

### ISSUE THREAD

**Issue by lucasteles** [dotnet/csharplang#3966]
#  Block dependency using

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary

A way to use multiples usings inside a namespaces

## Motivation

Usually, there's a lot o namespace using repetition in C# 

## Detailed design

Instead of write in this way:

```cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
/* 
  Some code ....
*/
```
Would be nice to write in this way

```cs
using Microsoft.AspNetCore { Builder, Hosting, Http }
using Microsoft.Extensions { DependencyInjection, Hosting, Logging } 
```

## Drawbacks
I don't know any

## Alternatives
Just use the normal usings

**Comment by HaloFour** [comment]
See: https://github.com/dotnet/csharplang/issues/1696

**Comment by RUSshy** [comment]
```C#
using Microsoft.AspNetCore:  Builder, Hosting, Http;
```

**Comment by 333fred** [comment]
Closing as a duplicate.
