### ISSUE TITLE
[Proposal]: Auto-implemented properties with expression bodies

### ISSUE THREAD

**Issue by mstaros** [dotnet/csharplang#3988]
# Auto-implemented properties with expression bodies

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
Allow block bodies and expression bodies together in properties to get one-liner lazy initialization. 

## Motivation
Today  when using expression bodies in properties with  backing fields one has to implement the fields manually. Usage  of auto-implemented properties  in this case would make things easier.
Instead of rule that  forbids  usage of  block bodies and expression bodies together lets  add clear  and useful semantic sense  to  it.

## Example
```
    class A
    {
        int X() {...}
        
        /// lazy default  value; can be reset
        int PropWR { get; set; } => X();

        ///  lazy   value
        int PropR { get;  } => X();
    }
```

Which is shortcut for

```
    int PropR {
           get { 
                if (_is_propRSet)
                {
                    return _propR
                }
                else
                {
                    _propR =  X();
                    _is_propRSet = true;
                    return _propR;
                }
             } 
          }
         int _propR;
         bool _is_propRSet;

        int PropRW
        {
            get
            {
                if (_is_propRWSet)
                {
                    return _propRW
                }
                else
                {
                    _propRW =  X();
                    _is_propRWSet = true;
                    return _propRW;
                }
            }
            set
            {
                _is_propRWSet = true;
                _propRW = value;
            }
        }
        int _propRW;
        bool _is_propRWSet; 
```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by YairHalberstadt** [comment]
Can you please show the code that would be generated in both of these cases?

As far as I can see this is actually about having a way to easily lazy initialize a property?

If so I don't thing an expression bodied initializer indicates that, especially as they can already be used in a similar way in properties and have a very different meaning in such cases.

**Comment by YairHalberstadt** [comment]
For a recent discussion on lazy initialization see https://github.com/dotnet/csharplang/discussions/3982

**Comment by theunrepentantgeek** [comment]
I think much of the problem you're trying to address here is better addressed by #140

**Comment by mstaros** [comment]
> I think much of the problem you're trying to address here is better addressed by #140

No, it is quite a different proposal  . This one is about lazy initialization with minimum new syntax added to the language.

**Comment by Joe4evr** [comment]
> No, it is quite a different proposal . This one is about lazy initialization with minimum new syntax added to the language.

![](https://cdn.discordapp.com/attachments/384292949116321793/638957149288136734/jks6Qqr.png)

**Comment by mstaros** [comment]
> > No, it is quite a different proposal . This one is about lazy initialization with minimum new syntax added to the language.
> 
> Yes and..?  this is just one liner for  lazy initialization, no more, no less. One cannot achieve it just using field value from  https://github.com/dotnet/csharplang/issues/140

**Comment by YairHalberstadt** [comment]
@mstaros 

You can do lazy initialization as follows:

```csharp
    class A
    {
        int X() {...}
        
        int PropWR { get => field ?? = X(); set => field = value; }

        int PropR { get => field ?? = X(); }
    }
```

**Comment by mstaros** [comment]
> @mstaros
> 
> You can do lazy initialization as follows:
> 
> ```cs
>     class A
>     {
>         int X() {...}
>         
>         int PropWR { get => field ??= X(); set => field = value; }
> 
>         int PropR { get => field ??= X(); }
>     Only for reference types. And even that  it is much more verbose. I am just using something that already exists in language  and instead of forbidding it suggest another semantics

**Comment by YairHalberstadt** [comment]
@mstaros So what alternativecode would you suggest this generate?

**Comment by mstaros** [comment]
> @mstaros So what alternativecode would you suggest this generate?

I have added the code inside the proposal itself

**Comment by theunrepentantgeek** [comment]
> Today when using expression bodies in properties with backing fields one has to implement the fields manually.

With #140 (or any of several other suggested similar issues) the backing field would not need to be implemented manually.


There are a lot of options - _policy_ - around lazy instantiation which would make it nigh on impossible to implement as a language feature. There are good reasons why `Lazy<T>` has so many options.

To illustrate with your simplest example:

```
 ///  lazy   value
int PropR { get;  } => X();
```

* Do we guarantee that `X()` will be called exactly once?
* If so, how do we ensure that?
* If not, which value is used? The result of the first call? The result of the second? Whichever returns first?
* If `X()` throws an exception, does the exception escapes the property getter?
* If it does, what happens the next time the property is read? Is the same exception thrown again (ie it's cached), or do we call `X()` again? What if we want the above guarantee that `X()` will be called exactly once?
* What happens if two threads read the property at the same time?
* How do we accommodate an **async** `X()` method?

Should the feature be implemented in the most straightforward way, making it useless for concurrent and multi-threaded purposes - and subject to some nasty silent failure modes.

Or should the feature be implemented in a way that's compatible with concurrent and multi-threaded execution, at the cost of significant performance for the common case?

One last thought, all that code you've shown can very easily be simplified. For readonly properties, use `Lazy<T>`, for readwrite properties define your own `LazyRW<T>` struct, and the properties fall out like this:

``` csharp
int PropR {
   get => _propR.Value;
}
    
Lazy<int> _propR = new(() => X());
    
int PropRW
{
    get => _propRW.Value;
    set => _propRW.Value = value;
}
    
LazyRW<int> _propRW = new LazyRW<int>(() => X());
```

You get _**all**_ the policy control over all the questions I asked above, and you can do it now, **_today_**.

**Comment by mstaros** [comment]
> > Today when using expression bodies in properties with backing fields one has to implement the fields manually.
> 
> With #140 (or any of several other suggested similar issues) the backing field would not need to be implemented manually.
> 
> There are a lot of options - _policy_ - around lazy instantiation which would make it nigh on impossible to implement as a language feature. There are good reasons why `Lazy<T>` has so many options.
> 
> To illustrate with your simplest example:
> 
> ```
>  ///  lazy   value
> int PropR { get;  } => X();
> ```
> 
> * Do we guarantee that `X()` will be called exactly once?
> * If so, how do we ensure that?
> * If not, which value is used? The result of the first call? The result of the second? Whichever returns first?
> * If `X()` throws an exception, does the exception escapes the property getter?
> * If it does, what happens the next time the property is read? Is the same exception thrown again (ie it's cached), or do we call `X()` again? What if we want the above guarantee that `X()` will be called exactly once?
> * What happens if two threads read the property at the same time?
> * How do we accommodate an **async** `X()` method?
> 
> Should the feature be implemented in the most straightforward way, making it useless for concurrent and multi-threaded purposes - and subject to some nasty silent failure modes.
> 
> Or should the feature be implemented in a way that's compatible with concurrent and multi-threaded execution, at the cost of significant performance for the common case?
> 
> One last thought, all that code you've shown can very easily be simplified. For readonly properties, use `Lazy<T>`, for readwrite properties define your own `LazyRW<T>` struct, and the properties fall out like this:
> 
> ```cs
> int PropR {
>    get => _propR.Value;
> }
>     
> Lazy<int> _propR = new(() => X());
>     
> int PropRW
> {
>     get => _propRW.Value;
>     set => _propRW.Value = value;
> }
>     
> LazyRW<int> _propRW = new(() => X());
> ```
> 
> You get _**all**_ the policy control over all the questions I asked above, and you can do it now, **_today_**.

Yes, today I can do it with explicitly implemented backing fields, no doubt.   The point  is to avoid  manual implementation of them. And  not always we need thread-safety. It is just ordinary backing field. An this is existing construction, forbidden now. And just new semantic for existing construction.

**Comment by Joe4evr** [comment]
> Why should one remember not to use something while it can be used as an easy way to add lazy init(not thread-safe) instead

Because what about the people who require it to be thread-safe? Or any of the other pieces of policy @theunrepentantgeek outlined above? Elevating one very specific scenario over all the others will lead the developers that need more control into a Pit of Failure.

As Gafter once said:
> Just because you can't think of all the bad things that would happen doesn't mean there aren't any.

**Comment by mstaros** [comment]
> > Why should one remember not to use something while it can be used as an easy way to add lazy init(not thread-safe) instead
> 
> Because what about the people who require it to be thread-safe? Or any of the other pieces of policy @theunrepentantgeek outlined above? Elevating one very specific scenario over all the others will lead the developers that need more control into a Pit of Failure.
> 
> As Gafter once said:
> 
> > Just because you can't think of all the bad things that would happen doesn't mean there aren't any.

When you are dealing with ordinary auto-implemented properties   you don't want to make them to be heavier if they don't require to be thread-safe . You want for them to be lightweight. This case is no  exception. Just lightweight property. When you need thread-safety then use  special tools.

**Comment by HaloFour** [comment]
https://github.com/dotnet/csharplang/discussions/3982#discussioncomment-92536

**Comment by mstaros** [comment]
> This is cached properties with a different name:
> 
> [#3982 (comment)](https://github.com/dotnet/csharplang/discussions/3982#discussioncomment-92536)

No, it is not cache at all.  It is indeed about auto-generated  felds. Resettable. It does not  introduce any new symbols and new attributes-it is the very important point.  Just using existing constructs. It is not thread-safe.

**Comment by HaloFour** [comment]
@mstaros 

Lazy computation is the same as memoization or caching.  The end result is that you don't repeat the computation.  Beyond that it is splitting hairs and implementation details.  This can be implemented by source generators, as mentioned by the other discussion.  Such a solution would use different syntax but would be more capable and more widely applicable, and require zero changes to the language.

**Comment by mstaros** [comment]
> @mstaros
> 
> Lazy computation is the same as memoization or caching. The end result is that you don't repeat the computation. Beyond that it is splitting hairs and implementation details. This can be implemented by source generators, as mentioned by the other discussion. Such a solution would use different syntax but would be more capable and more widely applicable, and require zero changes to the language.
Not all lazy initialzers are equal.  For one the cache you mentioned is not resettable.  And what is much more important -It requires litter language with an additional entity-new attribute .  It will be quite a heavy price- to add a new entity  for every small feature.    This proposal does not add any new entities-just adds new interpretation to existing one. In a niche left by usage ban. This is very important point. It is cheap and light.  About source generators and their endless capabilities - you can say the same about any auto-implemented properties-can't you?

**Comment by mstaros** [comment]
> @mstaros
> 
> Lazy computation is the same as memoization or caching. The end result is that you don't repeat the computation. Beyond that it is splitting hairs and implementation details. This can be implemented by source generators, as mentioned by the other discussion. Such a solution would use different syntax but would be more capable and more widely applicable, and require zero changes to the language.

**Comment by mstaros** [comment]
Sorry, clicked by mistake

**Comment by HaloFour** [comment]
> For one the cache you mentioned is not resettable

It is whatever the source generator makes it.

> This proposal does not add any new entities-just adds new interpretation to existing one. In a niche left by usage ban. This is very important point. It is cheap and light.

Source generators are cheap and light.  Changing the language is the most expensive possible option.

**Comment by mstaros** [comment]
> > For one the cache you mentioned is not resettable
> 
> It is whatever the source generator makes it.
> 
> > This proposal does not add any new entities-just adds new interpretation to existing one. In a niche left by usage ban. This is very important point. It is cheap and light.
> 
> Source generators are cheap and light. Changing the language is the most expensive possible option.

We go by circles. If you think that language should contain expression-bodied members for readonly property , but forbid it  for property with auto-generated field -let it be.

**Comment by mstaros** [comment]
And additional answer to your post:
1. Not all properties  should be thread-safe. Moreover, auto-implemented properties are not thread-safe by definition. 
2. Lazy initialization is not about thread-safety. It is about lazy initialization. 

This proposal  add additional functionality to auto-implemented properties. In simple and light way. That's it. But when auto-implemented properties  has no relations to thread-safety.
Why do you mention thread-safety at all?  

Now  back to other your statements:

> With #140 (or any of several other suggested similar issues) the backing field would not need to be implemented manually.

Not true. You cannot create lazy initializer using just  field  notion from  there.  Try to do it for value types and see.
Moreover it adds additional entity to  the language and not  that much functionality.

 >There are a lot of options - _policy_ - around lazy instantiation which would make it nigh on impossible to implement as a language feature. There are good reasons why `Lazy<T>` has so many options.

Not true.   Lazy class serves absolutely different purpose:  thread -safe lazy initializion.   You don't want  to use it   when you dont care about threads. Guess when it happens? Yes, when  you are ok with auto-implemented properties.

>Do we guarantee that `X()` will be called exactly once? 
All these question again about thread-safety. Not related.

>One last thought, all that code you've shown can very easily be simplified. For readonly properties, use `Lazy<T>`, for readwrite properties define your own `LazyRW<T>` struct, and the properties fall out like this:

No simplification here. You created backing fields manually. You added heavy-weight and not related Lazy object.


 >Or should the feature be implemented in a way that's compatible with concurrent and multi-threaded execution, at the cost of significant performance for the common case?

No. This feature is an extension for auto-implemented properties. When  you use them -you don't case about multi-threading. Otherwise  you would use something else.

**Comment by CyrusNajmabadi** [comment]
Lazy has overlapping concerns with multi-threading.  i.e. when i normally have a type i can't (easily) share it among multiple threads prior to it being initialized.  As such, i can safely initialize up front and then share.  That desire to share can still exist in many domains even when doing things lazily.  As such, the desire to be lazy, while still being multi-threading-sharing safe is present.

**Comment by HaloFour** [comment]
There are tons of similar "tiny" requests to add functionality around auto-properties.  There isn't enough syntax available to add them all.  It'd be far preferable to have a mechanism that would enable layering in those concerns in a relatively concise manner.  Delegated properties is one such approach, which would solve for "lazy" (which retaining the ability to specify policy around multithreading) and many of those other concerns.  I'd rather try to solve for a simple syntax for enabling all of those scenarios rather than implementing a very limited form of exactly one scenario.

**Comment by mstaros** [comment]
> Lazy has overlapping concerns with multi-threading. i.e. when i normally have a type i can't (easily) share it among multiple threads prior to it being initialized. As such, i can safely initialize up front and then share. That desire to share can still exist in many domains even when doing things lazily. As such, the desire to be lazy, while still being multi-threading-sharing safe is present.

It is  because people usually  use word `Lazy` for thread-safe cases.  But you might need the laziness even if you are working with single-thread or thread-safe environment. Lazy means that if you initialize something only when you need. If at all. No more. No inherent multithreading concern here. If you use auto-implemented properties- it means you don't care about threads.  You cannot lock backing fields there, can you?( ok, we are not talking about reflection).  So it  will be ok in this  case to use lazy extension for them also. Just to save you some coding. That's simple.

**Comment by mstaros** [comment]
> There are tons of similar "tiny" requests to add functionality around auto-properties. There isn't enough syntax available to add them all. It'd be far preferable to have a mechanism that would enable layering in those concerns in a relatively concise manner. Delegated properties is one such approach, which would solve for "lazy" (which retaining the ability to specify policy around multithreading) and many of those other concerns. I'd rather try to solve for a simple syntax for enabling all of those scenarios instead of implementing a very limited form of exactly one scenario.

Not true. We already discussed here you suggestion about cache using attributes. It adds another entity without adding much functionality.  Which is very expensive indeed. That's why I think that your proposal is for source generator only.
For this case - we don't add any new entity. We just permit forbidden case. Can you see the difference?

**Comment by CyrusNajmabadi** [comment]
> No more.

I'm not willing to make that statement.  Indeed, this is why Lazy<T> itself has options to control it's threading behavior.

**Comment by CyrusNajmabadi** [comment]
> If you use auto-implemented properties- it means you don't care about threads. 

That is not true.  I use auto-implemented properties a *lot* where i also care about threads.

**Comment by mstaros** [comment]
> > If you use auto-implemented properties- it means you don't care about threads.
> 
> That is not true. I use auto-implemented properties a _lot_ where i also care about threads.

How do you put the  lock  on the backing fields then? I am talking about thread -safety of the fields of course. Not about all your program.

**Comment by CyrusNajmabadi** [comment]
> How do you put the lock on the backing fields then? 

I don't need to.  My auto-props are threadsafe.  I just want to preserve that if i move to lazy-init for them.

**Comment by mstaros** [comment]
> > How do you put the lock on the backing fields then?
> 
> I don't need to. My auto-props are threadsafe. I just want to preserve that if i move to lazy-init for them.

If they are thread-safe already, it means nothing bad can happen with them in multi-thread environment. But if you care about lazy init of them - they are not thread safe.

**Comment by mstaros** [comment]
Let's image you want to use Lazy class for thread safety. So use it.
How on the earth this contradicts to:

`  int PropR { get;  } => X();`
  
 If i have  an object with million properties or million objects with one property that I don't want to initialize beforehand and I don't care about threads and just don't want to implement million backing fields manually.   What is wrong in wish to use this well-known syntax?  Do you see any new class? new attribute? Lot of typing?  
 
Why you are ok with 
`  int PropR { get; set; } = X();
 then?

**Comment by CyrusNajmabadi** [comment]
> If they are thread-safe already, it means nothing bad can happen with them in multi-thread environment. But if you care about lazy init of them - they are not thread safe.

By being lazy, they now may be shared in multi-threaded code *prior* to be initialzied.  Which means now you may have race conditions.  When they were not lazy it was possible to share in multi-threadded code because (commonly) tehy would be entirely initialized before that happens.  this is why the two topics are interrelated.

**Comment by mstaros** [comment]
> > If they are thread-safe already, it means nothing bad can happen with them in multi-thread environment. But if you care about lazy init of them - they are not thread safe.
> 
> By being lazy, they now may be shared in multi-threaded code _prior_ to be initialzied. Which means now you may have race conditions. When they were not lazy it was possible to share in multi-threadded code because (commonly) tehy would be entirely initialized before that happens. this is why the two topics are interrelated.

Disagree completely. When property is initialized it can fall victim of threads at any moment. There is no rule  that initialized property is thread-safe.

**Comment by CyrusNajmabadi** [comment]
> When property is initialized it can fall victim of threads at any moment

It really can't.  Because, in general, my instance isn't exposed to other threads while it is being constructed.  I would have to write some very strange code to allow for that.  As such, post construction i know it's safe and easy to share.  Note that roslyn itself is massively built on top of this concept.  Post construction the type is entirely safe to use and share.  There are many cases where we use normal auto-props and lazy auto-props.  THe normal ones are easy with this approach.  The lazy ones are not as multi-threading has to be taken into account.

**Comment by mstaros** [comment]
Only immutable types are safe post-construction. Nothing strange in mutable classes. Thats's why people invented all this constructs-locks , mutexes and lot of others- to defend mutable fields in mutable classes. It  has nothing to do with initialization.

**Comment by CyrusNajmabadi** [comment]
None of what you've said addresses the core point i'm making that being lazy can create concerns with multi-threading.  I didn't say it is always a concern.  I'm stating there are scenarios where it can be a concern.  These happen to be scenarios taht i'm very interested and passionate about though as these types of designs happen to be exactly the sort that Roslyn itself uses.  So i would very much want any language design we created here to consdier those so that we would be able to use this language feature ourselves.  I would be very disappointed if we just ignored it and then added a feature that we couldn't use in our own project for this very common case/need.

**Comment by mstaros** [comment]
if you want to  invent one-liner for lazy thread-safe initialization-go for it. My goal is absolutely different. I just want to use forbidden constructs as one-liner to avoid manual typing.  And for  cases (there are lot of them) when programmer works in thread-safe environment and when she is  well aware about it.  No more, no less.

**Comment by CyrusNajmabadi** [comment]
> My goal is absolutely different.

Right.  But being on the language design group, i look at features not only for what they do for the person who filed it, but for how they can be beneficial to the entire ecosystem.  That means not scoping them overly narrowly when a broader approach would make them far more useful and applicable to a wide variety of important scenarios.

**Comment by CyrusNajmabadi** [comment]
Or, put another way:  if the feature isn't valuable enough, i wouldn't invest in getting it into the language.  If it is valuable, i will :)

**Comment by mstaros** [comment]
Still not clear how  you make these decisions.
I suggested this feature only because it does not add any new syntax to the language.  I didn't invent new wheel.  It is not a burden for developer at all  to learn it. They know the syntax already. But  instead of remembering not use the construct she will remember it's semantics instead.   So this feature is extremely light for both sides -for language team and for  developers. And I assure you that most of programmers need it  to save typing.  
And one more thing. You don't want every lazy initialization to be thread-safe before hand. You don't want to use heavy Lazy class when you don't need it.  If you care about performance and memory  footprint.  The idea always always use  thread-safe lazy init is harmful for performance. Use it when you need it.

**Comment by CyrusNajmabadi** [comment]
> Still not clear how you make these decisions.

I look at teh feature and the complexity cost it adds, and i look at the scenarios it enables and how valuable i think those are.  I weigh the pros/cons personally and make a decision :)

> You don't want every lazy initialization to be thread-safe before hand. 

Agreed.

>  You don't want to use heavy Lazy class when you don't need it. 

Agreed.

>  Use it when you need it.

Agreed.  That's my point.  I'd want such a feature to have a way that woudl allow me to use this when i needed it.  :)

**Comment by mstaros** [comment]
>Agreed. That's my point. I'd want such a feature to have a way that woudl allow me to use this when i needed it. :)

So go for it and invent:). Why do you want to leave the construct forbidden and poor guys continue typing million lines when it is has almost zero cost to implement and use? How does it relate to your dream  about perfect tunable one-liner? and even if someone invent it(not sure when)  -where is the contradiction?

**Comment by 333fred** [comment]
> I suggested this feature only because it does not add any new syntax to the language. I didn't invent new wheel. It is not a burden for developer at all to learn it.

Personally, I don't find this syntax to be particularly intuitive. It doesn't match any other usage of the `=>` sigil in the language: the fat arrow normally refers to things that produce a value. Switch expression cases, expression-bodied members, lambdas... none of these imply any form of caching. That you are using `=>` here to mean caching is confusing to me.

> So this feature is extremely light for both sides -for language team and for developers.

Just to be clear, no language change is light, for anyone. Even the smallest language changes require many hours of development work. Multiple LDM sessions are usually required to hash out the semantics of a proposal. We also have to consider any related proposals: are we boxing ourselves out of other future work? Then someone from the compiler team has to actually implement this, and multiple other members must review it. We then have a larger compiler-team review of the feature. The IDE team has to update their code to understand the new features. The docs team has to create documentation on the new feature. Downstream teams that depend on understanding C# code have to update their tools. This is hundreds of hours of work, at a minimum, for _any_ language change, just on the language design side. That's to say nothing of the actual user education required.

**Comment by mstaros** [comment]
> > I suggested this feature only because it does not add any new syntax to the language. I didn't invent new wheel. It is not a burden for developer at all to learn it.
> 
> Personally, I don't find this syntax to be particularly intuitive. It doesn't match any other usage of the `=>` sigil in the language: the fat arrow normally refers to things that produce a value. Switch expression cases, expression-bodied members, lambdas... none of these imply any form of caching. That you are using `=>` here to mean caching is confusing to me.
> 
> > So this feature is extremely light for both sides -for language team and for developers.
> 
> Just to be clear, no language change is light, for anyone. Even the smallest language changes require many hours of development work. Multiple LDM sessions are usually required to hash out the semantics of a proposal. We also have to consider any related proposals: are we boxing ourselves out of other future work? Then someone from the compiler team has to actually implement this, and multiple other members must review it. We then have a larger compiler-team review of the feature. The IDE team has to update their code to understand the new features. The docs team has to create documentation on the new feature. Downstream teams that depend on understanding C# code have to update their tools. This is hundreds of hours of work, at a minimum, for _any_ language change, just on the language design side. That's to say nothing of the actual user education required.

Ok, this is finally something that I can agree with. If syntax seems to be  not intuitive- it is not.  I  just want to notice it is not about caching- it is about auto-properties.  Thats why I  hoped the syntax  would be obvious  for developers.

**Comment by 333fred** [comment]
> I just want to notice it is not about caching- it is about auto-properties. Thats why I hoped the syntax would be obvious for developers.

It is though: you propose that using the `=>` generates an extra bool flag to track whether the property has been initialized, and initializing it on `get` if it hasn't yet been initialized. That's just a description of a simple cache. And I also agree with the other commenters here that threading _is_ a concern, simply because someone is inevitably going to end up using this in a threading context. We know from many years of experience that the shortest way to express a thing will be the preferred way of doing so. Handing developers this tool and then saying "oh, but don't use it in this super-common case" isn't a great experience because it draws developers towards a pit of failure, where the natural and easiest thing to do is actually the wrong thing.

**Comment by mstaros** [comment]
> > I just want to notice it is not about caching- it is about auto-properties. Thats why I hoped the syntax would be obvious for developers.
> 
> It is though: you propose that using the `=>` generates an extra bool flag to track whether the property has been initialized, and initializing it on `get` if it hasn't yet been initialized. That's just a description of a simple cache. And I also agree with the other commenters here that threading _is_ a concern, simply because someone is inevitably going to end up using this in a threading context. We know from many years of experience that the shortest way to express a thing will be the preferred way of doing so. Handing developers this tool and then saying "oh, but don't use it in this super-common case" isn't a great experience because it draws developers towards a pit of failure, where the natural and easiest thing to do is actually the wrong thing.

Here I disagree again) . When you  give to developer Dictionary she knows not to use it for concurrent threads. She  uses ConcurrentDictionary instead.  And  vice versa-she does not use ConcurrentDictionary for thread-safe environment, because Dictionary is way faster in the case.  Nothing wrong with it.

**Comment by mstaros** [comment]
> @mstaros
> 
> That's why Dictionary is not a part of the language.

But auto-properties are and there is no way to make access to backing fields thread-safe. Inside the property itself.

**Comment by HaloFour** [comment]
@mstaros 

> But auto-properties are and there is no way to make access to backing fields thread-safe. Inside the property itself.

A mutable property is inherently not thread safe.  No amount of locking will fix that.  A readonly or init-only auto-property is inherently thread safe.

**Comment by mstaros** [comment]
> @mstaros
> 
> > But auto-properties are and there is no way to make access to backing fields thread-safe. Inside the property itself.
> 
> A mutable property is inherently not thread safe. No amount of locking will fix that. A readonly or init-only auto-property is inherently thread safe.

Sure. But  while you can make explicitly implemented backing field thread-safe, using lock, you cannot do the same with  auto-property and it's backing field. You need one more additional field. That's the point.  

You want the new construct to be thread-safe per se, without any usage of additional fields. And you are ok with using additional fields for auto-property.

**Comment by HaloFour** [comment]
@mstaros 

> But while you can make explicitly implemented backing field thread-safe, using lock, you cannot do the same with auto-property and it's backing field.

Not with a mutable property, auto-property or not.  As soon as you have read/write operations not controlled by the same critical section you are no longer thread safe.  You cannot make the property thread-safe by locking the individual accessor methods.  At most you can make the code that runs within a single accessor method thread-safe, but given such a property would involve more logic than reading/writing a backing field it would no longer be a candidate for an auto-property.

**Comment by mstaros** [comment]
> @mstaros
> 
> > But while you can make explicitly implemented backing field thread-safe, using lock, you cannot do the same with auto-property and it's backing field.
> 
> Not with a mutable property, auto-property or not. As soon as you have read/write operations not controlled by the same critical section you are no longer thread safe. You cannot make the property thread-safe by locking the individual accessor methods. At most you can make the code that runs within a single accessor method thread-safe, but given such a property would involve more logic than reading/writing a backing field it would no longer be a candidate for an auto-property.

If you have very complex logic reading million properties from million classes inside getter access- nothing will save  you, even Lazy class and EnsureInitialized.  But how does it relate to the topic?

**Comment by HaloFour** [comment]
@mstaros 

> If you have very complex logic reading million properties from million classes inside getter accessor- nothing will save you, even Lazy class and EnsureInitialized. But how does it relate to the topic?

I have no idea how that relates to this topic.

It's quite easy to make the code within the getter accessor thread-safe via critical section or ensuring that it runs on initialization prior to the instance being shared.  If you want that getter to also be lazily-evaluated it's still pretty easy by employing `Lazy<T>`, where you can choose from one of three thread-safety policies.  It's very unlikely that such a property would be mutable.

**Comment by mstaros** [comment]
Thank you for the short course of what a  critical section is  and how many items are in LazyThreadSafetyMode  enum.    The last sentence is about probabilistic programming I suppose;)
But we are so far away of any topic that I really  don't know what to answer)

**Comment by mstaros** [comment]
This proposal is not enough generic for  the language, now I agree.
