### ISSUE TITLE
[Proposal]: Auto-generated fields  in expression-bodied members

### ISSUE THREAD

**Issue by mstaros** [dotnet/csharplang#4005]
# Auto-generated fields  in expression-bodied members

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

 New syntax is suggested for expression-bodied members where expression is a method call. If  this method has 
 ref parameter and in runtime it's value is substituted with discard  `_` -  it means that for this parameter compiler will generate 
 anonymous field of the same type.
 For static member it is  a static field, for instance member- an instance field.
 The identity  of the field  =   `containing type name  + memberName(without  -get  and  -set suffixes) +parameter name`;
 If  getter and setters  both have generated  fields  with the same names but with different types  - compiler will throw error.

## Motivation
 To avoid tedious code repetition with manually created fields.

## Example

```csharp
 public class A
    {
       //generates fields  for parameters target, initialized, synclock
        int X => LazyInitializer.EnsureInitialized<int>(ref _, ref _, ref _, () => 1);

    
        static T Z<T>(int a) => B.Cache(a, ref _, ref _);  //generates static fields for parameters: cache, lck


        string Y
        {
            get => B.GetterSetter(default, ref _,  true);  // generate backing field  
            set => B.GetterSetter(value, ref _ ,  false);  // generate backing field  
        }
    }

    class B
    {
        public static T Cache<T>(int x, ref Dictionary<int, T> cache, ref object lck)
        {
            T calculate(int z) { ...}
            lock (lck)
            {
                if (cache.TryGetValue(x, out var v))
                {
                    return v;
                }
                else
                {

                    var retval = calculate(x);
                    cache.Add(x, retval);
                    return retval;
                }
            }

        }
        public static string GetterSetter(string value, ref string backing,  bool isGetter)
        {
            static void OnPropertyChanged(string v)
            {
                    ...
            }


            if (!isGetter)
            {
                if (value != backing)
                {
                    backing = value;
                    OnPropertyChanged(value);
                }
            }
            return backing;
        }
    }

```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by HaloFour** [comment]
@mstaros 

> Not just one predefined field. Which is not enough.

I see, so you're proposing that each `_` refers to a different auto-generated field?  How would you refer to the same field twice then?

Coming from languages like Scala that has functionality like this with lambda arguments I can state that the behavior of a discard acting like an incrementing series of values is incredibly confusing and a source of bugs.

**Comment by mstaros** [comment]
> @mstaros
> 
> > Not just one predefined field. Which is not enough.
> 
> I see, so you're proposing that each `_` refers to a different auto-generated field? How would you refer to the same field twice then?
> 
> Coming from languages like Scala that has functionality like this with lambda arguments I can state that the behavior of a discard acting like an incrementing series of values is incredibly confusing and a source of bugs.
 
The fields are autogenerated and are used only inside the generating  methods. No external references to them.

**Comment by mstaros** [comment]
Just loo

> > The fields are autogenerated and are used only inside the generating methods. No external references to them.
> 
> Which is what makes it incredibly difficult to see what is going on.

Just look inside the method code)

**Comment by HaloFour** [comment]
That method could be anywhere, including other assemblies.

**Comment by HaloFour** [comment]
I have to disagree, and if having `ref _` anywhere within a method automatically turn into an implicitly typed and anonymously named field in the current class would be a very surprising behavior with unexpected side effects.  That would mean that `ref _` and `out _` have _very_ different semantics.

**Comment by mstaros** [comment]
> I have to disagree, and if having `ref _` anywhere within a method automatically turn into an implicitly typed and anonymously named field in the current class would be a very surprising behavior with unexpected side effects. That would mean that `ref _` and `out _` have _very_ different semantics.

Can you give any example please? how anonymous field not reachable from outside the method call can give a side effect that user is not aware of?

**Comment by 333fred** [comment]
> Can you give any example please? how anonymous field not reachable from outside the method call can give a side effect that user is not aware of?

Because the result from the previous call is stored in the class. This is not how discards generally work: the results are _completely_ unobservable. Even in the current method. This would be highly confusing.

**Comment by mstaros** [comment]
> > Can you give any example please? how anonymous field not reachable from outside the method call can give a side effect that user is not aware of?
> 
> Because the result from the previous call is stored in the class. This is not how discards generally work: the results are _completely_ unobservable. Even in the current method. This would be highly confusing.

ok, the syntax could be tweaked , it can be another symbol at your wish . It is the least  important point for now.

**Comment by HaloFour** [comment]
The use case still feels much better solved by either #133 or #140.

```cs
public int SomeValue {
    var cache = new Cache<int>(SomeExpensiveCalculation);
    get => cache.Value;
}

public string Name {
    get;
    set => NotifyOnChanged(ref field, value);
}
```

**Comment by mstaros** [comment]
> The use case still feels much better solved by either #133 or #140.
> 
> ```cs
> public int SomeValue {
>     var cache = new Cache<int>(SomeExpensiveCalculation);
>     get => cache.Value;
> }
> 
> public string Name {
>     get;
>     set => NotifyOnChanged(ref field, value);
> }
No, it is a subcase. It can repeat  only  1 from 3 aforementioned examples.

**Comment by 333fred** [comment]
You can have more than one property-scoped field in the proposal.

**Comment by HaloFour** [comment]
```cs
public int SomeValue {
    var field1 = ...;
    var field2 = ...;
    get => field1 + field2;
}
```

**Comment by 333fred** [comment]
> > You can have more than one property-scoped field in the proposal.
> 
> Exactly. This is the gist of the proposal.

As in #133 will allow you to have more than 1 property-scoped field.

**Comment by mstaros** [comment]
> ```cs
> public int SomeValue {
>     var field1 = ...;
>     var field2 = ...;
>     get => field1 + field2;
> }
> ```

it solves only part  of problem.  user has to repeat the code again and again. This proposal solves both.

**Comment by mstaros** [comment]
> > > You can have more than one property-scoped field in the proposal.
> > 
> > 
> > Exactly. This is the gist of the proposal.
> 
> As in #133 will allow you to have more than 1 property-scoped field.

yes, but  what should user do with  about manual typing again and again? copypaste?

**Comment by HaloFour** [comment]
I don't see repetition.  I see declaration, I see initialization, and I see usage.  Those are three different things.

**Comment by mstaros** [comment]
> I don't see repetition. I see declaration, I see initialization, and I see usage. Those are three different things.

Repetition is not inside. It is outside and  is quite obvious here. When you have a lot of similar properties that you want to initialize in similar way - say, using EnsureInitialized.-you have to write define the fields again and again.

**Comment by HaloFour** [comment]
> When you have a lot of similar properties that you want to initialize in similar way - say, using EnsureInitialized.-you have to define the fields again and again.

Or you can write a helper wrapper and encapsulate that all within a single type, like `Lazy<T>` already does.  I don't think my example of a lazy/cached property involves an onerous amount of code:

```cs
public int SomeValue {
    var cache = new Lazy<int>(SomeExpensiveCalculation);
    get => cache.Value;
}
```

**Comment by mstaros** [comment]
> > When you have a lot of similar properties that you want to initialize in similar way - say, using EnsureInitialized.-you have to define the fields again and again.
> 
> Or you can write a helper wrapper and encapsulate that all within a single type, like `Lazy<T>` already does. I don't think my example of a lazy/cached property involves an onerous amount of code:
> 
> ```cs
> public int SomeValue {
>     var cache = new Lazy<int>(SomeExpensiveCalculation);
>     get => cache.Value;
> }
> ```

But I don't want to use Lazy class. It is heavy. And even more to that-you still need copy the code. It is bad thing in any case . If  tomorrow I want to refactor  the code- I have to go  through million places and remove first line you wrote  or change it

**Comment by YairHalberstadt** [comment]
I cannot remember the last time I've had a property which required access to 2 fields which weren't used anywhere else. I imagine the percentage of cases where this occurs are far less than 0.1% of all properties.

**Comment by mstaros** [comment]
> I cannot remember the last time I've had a property which required access to 2 fields which weren't used anywhere else. I imagine the percentage of cases where this occurs are far less than 0.1% of all properties.

It means you don't use Ensureinitialized that much for example) . We have  a lot properties like that.

**Comment by HaloFour** [comment]
@mstaros 

> But I don't want to use Lazy class. It is heavy.

So write a struct version that does the initialization you want it to do.

> It is bad thing in any case . If tomorrow I want to refactor the code- I have to go through million places and remove first line you wrote or change it.

You're going to have to do that anyway.

> It is about repetition itself.

And DRY isn't about making it so that you never have to type the same thing more than once.

**Comment by mstaros** [comment]
> @mstaros
> 
> > But I don't want to use Lazy class. It is heavy.
> 
> So write a struct version that does the initialization you want it to do.
Sorry, I don't want to invent a wheel when I have  tested tools already.
> 
> > It is bad thing in any case . If tomorrow I want to refactor the code- I have to go through million places and remove first line you wrote or change it.
> 
> You're going to have to do that anyway.

This contradicts the very goal of language design - to insist on code repetition. That's why we have inheritance for example.


> 
> > It is about repetition itself.
> 
> And DRY isn't about making it so that you never have to type the same thing more than once.

**Comment by HaloFour** [comment]
```cs
public struct LazyStruct<T> {
    private readonly object sync;
    private readonly Func<T> factory;
    private bool initialized;
    private T value;

    public LazyStruct(Func<T> factory) {
        this.sync = new object();
        this.factory = factory;
    }

    public int Value => Lazy.EnsureInitialized(ref value, ref initialized, sync, factory);
}

public LazyStruct<T> lazy(Func<T> factory) => new LazyStruct<T>(factory);

// to use
public int SomeValue {
    var cache = lazy(SomeExpensiveCalculation);
    get => cache.Value;
}

```

**Comment by HaloFour** [comment]
> But I don't want to copy structure every time.

There's only one copy here and that's during initialization.  That wouldn't be slower than the individual field initialization that you're proposing.  The rest of the mutations are in-place and doesn't involve copies.

> I still want to use three fields.  You added struct and one more ref field.

The struct is reusable across your project (and all projects).  If you want three fields write your implementation to be different.

**Comment by mstaros** [comment]
> > But I don't want to copy structure every time.
> 
> There's only one copy here and that's during initialization. That wouldn't be slower than the individual field initialization that you're proposing. The rest of the mutations are in-place and doesn't involve copies.
> 
> > I still want to use three fields.  You added struct and one more ref field.
> 
> The struct is reusable across your project (and all projects). It's not more verbose than all of the code that you're putting into your Cache implementation. If you want three fields write your implementation to be different.

If I have performance oriented code I count every copy and every reference.   You didn't give any reason why the proposal is nor correct, and insist on code that make things worse.

**Comment by HaloFour** [comment]
@mstaros 

> If I have performance oriented code I count every copy and every reference.

If you have performance-oriented code then you'd know that mutating a struct in place is no more expensive than updating a single field.  There aren't additional copies going on here.

> You didn't give any single reason why the proposal is notcorrect, and insist on code that make things worse.

I gave you my opinion.  You're free to not like that opinion.  But the onus is on you to convince the members of the team why they should consider your approval, not why not.

**Comment by HaloFour** [comment]
@mstaros 

I've stated several reasons for my opinion.  My experience with implicit lambda arguments in Scala, the implicit creation of any number of fields, the fact that the state of a discard is observable between invocations, the confusing association with `out _`, and my general disagreement with trying to make things as terse as possible.

**Comment by mstaros** [comment]
> > You pass struct as parameter. You copy it.
> 
> I don't see any place where this is happening. Can you point to the lines where you think the struct is being passed as a parameter or is being copied? When i look at [#4005 (comment)](https://github.com/dotnet/csharplang/issues/4005#issuecomment-707848514) i don't see it.

I suppose the struct is sent to the getter as a closure. Is it correct? Otherwise it wouldn't be a cache. Also it has additional refetence to factory.

**Comment by mstaros** [comment]
> @mstaros
> 
> I've stated several reasons for my opinion. My experience with implicit lambda arguments in Scala, the implicit creation of any number of fields, the fact that the state of a discard is observable between invocations, the confusing association with `out _`, and my general disagreement with trying to make things as terse as possible.

There is no discards at all. Just symbol. This is not relevant at all

**Comment by CyrusNajmabadi** [comment]
> I suppose the struct is sent to the getter as a closure. 

No.  The getter would direct access this as a field.  There would be no copying.

> Also it has additional reference to factory.

Sure.  But that's not a struct.  it's copied.  it just contains the code that produces the value on-demand.  With LazyInitializer it will also be dropped once the value is initialized.

**Comment by mstaros** [comment]
> > I suppose the struct is sent to the getter as a closure.
> 
> No. The getter would direct access this as a field. There would be no copying.
> 
> > Also it has additional reference to factory.
> 
> Sure. But that's not a struct. it's copied. it just contains the code that produces the value on-demand. With LazyInitializer it will also be dropped once the value is initialized.

I didnt say  that the factory  reference is copy  of struct.
Just as additional point. If it is not a closure-how does this getter know about the struct and stuct is still a cache? Can you show a generated  code please? As a pseudo of course.

**Comment by HaloFour** [comment]
@mstaros 

> Just as additional point. If it is not a closure-how does this getter know about the struct and stuct is still a cache? Can you show a generated code please? As a pseudo of course.

Property-scoped fields are normal class fields, they're just not accessible outside of the property.  The getter accessor method can reference the struct just like it can any class field.

**Comment by CyrusNajmabadi** [comment]
> Can you show a generated code please? As a pseudo of course.

Sure.  

```c#
public int SomeValue {
    var cache = lazy(SomeExpensiveCalculation);
    get => cache.Value;
}
```

would translate to:

```
private <>SomeValue_cache = lazy(SomeExpensiveCalculation);
public int SomeValue {
    get => <>SomeValue_cache.Value;
}
```

**Comment by mstaros** [comment]
It  sounds strange because you criticized particularily  discard  functionalty and  not  the symbol itself.

**Comment by mstaros** [comment]
> > Can you show a generated code please? As a pseudo of course.
> 
> Sure.
> 
> ```cs
> public int SomeValue {
>     var cache = lazy(SomeExpensiveCalculation);
>     get => cache.Value;
> }
> ```
> 
> would translate to:
> 
> ```
> private <>SomeValue_cache = lazy(SomeExpensiveCalculation);
> public int SomeValue => <>SomeValue_cache.Value;
> ```
> 
> As you can see, there are no copies here. And there is nothing like "the struct is sent to the getter as a closure"

So every va iin the code inside the property  generates new field?

**Comment by CyrusNajmabadi** [comment]
> So every var in the code inside the property generates new field?

Every property local that needs to be referenced in the getter/setter likely would.  It's really just a scoping feature.

**Comment by mstaros** [comment]
> > So every var in the code inside the property generates new field?
> 
> Every property-local that needs to be referenced in the getter/setter likely would. It's really just a scoping feature

It means things will get wild and uncontrollable.user can create lot of fields without noticing it. And they eont be discarded even. It is much worse  than i thought.

**Comment by CyrusNajmabadi** [comment]
> And they wont be discarded even. It is much worse than i thought.

Why would they be discarded?  It's literally the data you want the property to return.  if it's not stored in a field somewhere, how would you expect this to work?  Looking at your proposal, you seem to recognize this and you are also storing data in fields so that it can stored/accessed as necessary.  How do you see any of these proposals working if they have no place to store the data?

**Comment by HaloFour** [comment]
@mstaros 

> It means things will get wild and uncontrollable.user can create lot of fields without noticing it. And they wont be discarded even. It is much worse than i thought.

Property-scoped fields is not a block of arbitrary code, it is very specifically a set of fields with optional initializers.  You're not going to be putting arbitrary statements there, because you can't.

**Comment by mstaros** [comment]
Thank you for asking) finally someone got interested) it will generate fields only for ref  parameters with discard symbols.  No way to add more fields by mistake.
In your case i can write any code with any number of variables. Including intermidiary ones.and if they are referenced in  getter the fields will be generated. Lots of them potentially.

**Comment by mstaros** [comment]
What will happen if the var is mentioned both in getter and setter then?

**Comment by HaloFour** [comment]
Same thing that happens when you reference a field in both the getter and setter.

**Comment by mstaros** [comment]
What are the code restrictions then?

**Comment by HaloFour** [comment]
@mstaros 

> What are the code restrictions then?

It's not "code", it's field declarations.

**Comment by CyrusNajmabadi** [comment]
> Thank you for asking) finally someone got interested) it will generate fields only for ref parameters with discard symbols. No way to add more fields by mistake.

With the proposal we've been linking to, it would be extremely hard to add a field by mistake.  i.e. it's *very very very* clear that you're intending to add state since you're doing `var thingy = ...` in your property :)   You have to put htat in explicitly, and the entire purpose is to be able to have state computed that you can now use in your getter/setter :)

**Comment by HaloFour** [comment]
Also note that the design for that proposal has not really been discussed, so while I do advocate for allowing `var` to be used to infer the type of the field (as the limited scope I believe eliminates most of the concerns around inferred variables) that's not a decision that has been made by the team.  It's possible that they would look like normal field declarations only without accessibility modifiers.

**Comment by CyrusNajmabadi** [comment]
@mstaros i tried to clarify this in https://github.com/dotnet/csharplang/issues/4005#issuecomment-707894738

All that proposal is is a way to take your fields that are only referenced by one property, and *scope* them exactly to that property. i.e if i have this today:

```c#
Lazy<int> _lazyAge = ...
int Age => _lazyAge.Value;
```

then it's really easy for some *other* code to use `_lazyAge` inappropriately.  Guarding against that is hard.  What property-scoped-fields let you do is just rewrite that as:

```c#
int Age 
{
    // fields:
    Lazy<int> _lazyAge = ...

    // accessors:
    get => _lazyAge.Value;
}
```

It's effectively the same, except now `_lazyAge` can't accidentally be used by someone else.  I hope that helps clear htings up! :)

**Comment by mstaros** [comment]
Ok got it. So it is just fields you dont want toauto- generate by some reason. Making user to write them every time for every single property..making impossible to create a template for code..and not taking into account methods memoization..

**Comment by YairHalberstadt** [comment]
@mstaros 

On a different track, what would happen if there were a different number of `_` in the getter and the setter?
Also what if you need to access them in a different order in getter and setter?

**Comment by mstaros** [comment]
It is ok to have different number of field in getter and setter. . If  fields eith the same name has a same type. You can see sample above how it can be handled with one function even.

**Comment by HaloFour** [comment]
@mstaros 

> So it is just fields you dont want toauto- generate by some reason.

Why is autogeneration necessary?  Or even desired?  Where else does the C# language automatically generate a member where state can be observable between invocations?

> and not taking into account methods memoization..

The code I demonstrated is very specifically method memoization, but the feature very intentionally is intended to solve many more use cases as well.

**Comment by HaloFour** [comment]
More importantly, why would I expect that these autogenerated fields between the getter and setter have any relationship to one another?  Why doesn't the following generate two entirely unrelated fields?  Why shouldn't it?

```cs
public int Foo {
    get => Getter(ref _);
    set => Setter(ref _);
}
```

**Comment by mstaros** [comment]
I explained why. To avoid endless code repetition.This is  main source of bugs and time spent in vain.

**Comment by HaloFour** [comment]
You have to repeat `Getter` and `Setter` everywhere, how about replacing that with another sigil?  And `public`?  And `int`?

**Comment by mstaros** [comment]
Fields wiill be the same because  parameter names  and types will be the same. It is mentioned in proposal.  But agree that it will be better handled by single method as in the example above.

**Comment by CyrusNajmabadi** [comment]
@mstaros would you be interested in potentially taking this discussion to either gitter.im/csharplang?

**Comment by YairHalberstadt** [comment]
@mstaros 

I think I'm slowly coming to understand the motivation behind your proposal here:

1. You're looking for how you can create a reusable bit of code, that will simplify adding all sorts of effects to properties.
2. You've realized that methods are almost enough to get you there (at least for the use cases you care about), but what is missing is how to create fields.
3. So you're suggesting the least obtrusive possible syntax to just create the fields you need, because as far as you're concerned the class shouldn't care about the fields, it's the methods job to create them?

**Comment by mstaros** [comment]
> @mstaros
> 
> I think I'm slowly coming to understand the motivation behind your proposal here:
> 
> 1. You're looking for how you can create a reusable bit of code, that will simplify adding all sorts of effects to properties.
> 2. You've realized that methods are almost enough to get you there (at least for the use cases you care about), but what is missing is how to create fields.
> 3. So you're suggesting the least obtrusive possible syntax to just create the fields you need, because as far as you're concerned the class shouldn't care about the fields, it's the methods job to create them?
> 
> Is that a fair description of your thought process?

Yes) and it is both about propertiesand methods bte

**Comment by theunrepentantgeek** [comment]
> This contradicts the very goal of language design - to insist on code repetition. That's why we have inheritance for example.

I don't think this is correct at all - using inheritance for code reuse almost invariably leads to a brittle class hierarchy that's difficult to understand.

I think this should have been opened as a discussion, not an issue.

**Comment by mstaros** [comment]
> > This contradicts the very goal of language design - to insist on code repetition. That's why we have inheritance for example.
> 
> I don't think this is correct at all - using inheritance for code reuse almost invariably leads to a brittle class hierarchy that's difficult to understand.
> 
> I think this should have been opened as a discussion, not an issue.

Sorry, we are not talking about inheritance here.it was a point in  general discussion.

**Comment by YairHalberstadt** [comment]
Ok @mstaros I think I understand now.

I think the motivation is a good one, but I think the syntax and semantics is a little at odds with everything else in C#.

I would suggest we move this to a discussion if that's ok, and try to work on this to get it somewhere where it's more likely to be accepted?

**Comment by mstaros** [comment]
Sorry for typos ) i am typing on the go)

**Comment by CyrusNajmabadi** [comment]
> I explained why. To avoid endless code repetition.This is main source of bugs and time spent in vain.

This is a noble goal.  However, we have to look at the proposal in its entirety to know if it does that.  For example, your proposal allows:

```c#
public int Foo {
    get => Getter(ref _);
    set => Setter(ref _);
}
```

Very importantly: I have no idea what this means.  

First, a major issue (as you yourself mentioned), is that this should generate a field.  That's not evident at all, and would require close examination to realize this.

Second, there are two potential interpretations for this and, and both comes with major issues.  Let's take the interpretation that the `_` refers to the same field in both accessors.  If that's the case, how does one know this?  What if you have:

```c#
public int Foo {
    get => Getter(ref _, ref _);
    set => Setter(ref _, ref _);
}
```

Is there some sort of correspondance here betwene all these dicards?  Are they all the same field?  Are there two fields for the getter, and two *distinct* fields for the setter? Are there two fields for the getter and the language somehow shares those fields with the setter?  If so, what's the sharing strategy.  How does the compiler know which getter fields correspond to which setter fields?  etc. etc.

**Comment by HaloFour** [comment]
Even if the compiler can determine unambiguously which fields are generated and shared it's inexplicable to someone reading that source what it all means.  You could have anywhere between two or four separate fields being generated and it's possible (even likely) that two separate "templates" will accidentally share state by virtual of their parameter names.

**Comment by mstaros** [comment]
> Even if the compiler can determine unambiguously which fields are generated and shared it's inexplicable to someone reading that source what it all means. You could have anywhere between two or four separate fields being generated and it's possible (even likely) that two separate "templates" will accidentally share state by virtual of their parameter names.

Here I agree. And see my answer above please

**Comment by CyrusNajmabadi** [comment]
> I already answered about fields.Its parameters names that define field identity. 

In itself this seems highly problematic as that's also not obvious from looking at the code.  It also means that changing a parameter name in your code can silently change the meaning of this.  i.e. say i have:

```get => Foo(out _) + Bar(out _)```.  Changing either of Foo or Bar's first parameter name can dramatically impact what this cod means (i.e. if a field is shared between them, or if it is a fresh field for each.

This is sometimes a problem you get when you want to elide saying as much as possible.  Sometimes it's necessary to state these things because otherwise the code simply lacks clarity and is took brittle to normal editing.

**Comment by mstaros** [comment]
No.the proposal about one method call.it was stated from the start

**Comment by CyrusNajmabadi** [comment]
>  It is open for discussion

Of course :)   this is part of a healthy discussion on the topic.  Effectively, as i weigh a language proposal i end up having to weigh out this stuff.  I strongly understand your desire to write less, and to have a brief syntax to solve this issue for yourself.  Where things break down for me is that i see this coming with severe issues that worry me.

**Comment by mstaros** [comment]
No ..your examples about any expression while the proposal is about single call. It is about flexible one liner

**Comment by CyrusNajmabadi** [comment]
> No.the proposal about one method call.it was stated from the start

It may feel discouraging, but part of the lang design process is wondering if a proposal is *too* specialized.  i.e. if you're so narrowly producing a solution for just one case that it's just not worth it.  We'll often reject a proposal that has that sort of issue in favor of one that isn't necessarily as terse/simple but which more broadly covers a wider swath of cases. 

If the narrow-feature can be a slam dunk (great syntax, easy to understand, solves the 95% case), I would be more amenable to taking it.  But if it's much more lke 'so-so syntax, somewhat confusing, and only hits a narrow slice of expressions' then it's far less likely to be picked up.

In hte case here, you're vastly restricting the space where this approach could be used.  put another way, with expr-bodied properties we allow *any* expression today.  So i would strongly prefer solutions that do not get in the way of that.  I get that for you, the sweet-spot might be one method.  But that feels like too strong a limitation to put in place in the language (i.e. we don't do that anywhere else).

**Comment by mstaros** [comment]
Because it is so easy to wrap code in a method to avoid any code repetition.

**Comment by mstaros** [comment]
I cannot see any big  restriction  here frankly. One time method wrapper creation versus field definition repetition.

**Comment by CyrusNajmabadi** [comment]
You would need to create a wrapper mehtod for all places where you had multiple calls (or any sort of more complex expression).  i get that you don't think that's a big deal.  But now can you see why other s don't think it's a big deal to just have the `var ...` in the property?  In each case, there's a new declaration being made.  The benefit of the property-local case is that it's scoped just to the property.  With your 'method wrapper' case, now i'm not only making the method, but i'm also cluttering up my type with it.

**Comment by HaloFour** [comment]
Feels like this is half-way attempting to be delegated properties, but trying to keep the state external which is why it's requiring these automagick ref fields.  I'd much rather more exploration with delegated properties (and how they relate to property-scoped fields, if they do).  The property could be a struct and define its own internal state that is completely hidden from the consuming property.  Building on my example above:

```cs
public struct LazyStruct<T> {
    private readonly object sync;
    private readonly Func<T> factory;
    private bool initialized;
    private T value;

    public LazyStruct(Func<T> factory) {
        this.sync = new object();
        this.factory = factory;
    }

    public T Getter() => Lazy.EnsureInitialized(ref value, ref initialized, sync, factory);
    public void Setter(T value) {
        this.value = value;
        this.initialized = true;
    } 
}

// use
public int SomeValue using new LazyStuct<int>(SomeExpensiveCalculation);

// lowered to
private LazyStruct<int> <>SomeValue_delegate = new LazyStruct<int>(SomeExpensiveCalculation);
public int SomeValue {
    get => <>SomeValue_delegate.Getter();
    set => <>SomeValue_delegate.Setter(value);
}
```

**Comment by mstaros** [comment]
No..you have 100 simular  properties. What is better-to create method once or to copy paste the fields and tje logics? What is better when you want to refactor them all tomorrow? Then say after tomortow?

**Comment by CyrusNajmabadi** [comment]
> What is better-to create method once

I could say the same for your approach :)   You could have to make 100 helper methods to do the wrapping as you specified.  

> What is better when you want to refactor them all tomorrow? 

IMO, the property-field approach is the better way.
