### ISSUE TITLE
[Proposal]: Weak keyword better memory managment

### ISSUE THREAD

**Issue by redradist** [dotnet/csharplang#4039]
# Weak keyword better memory management

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary
Lets discuss if it possible and would be useful to add weak keyword for such scenarious:
```csharp
class Customer
{
    weak event Action evt; // All Targets are stored by WeakReferece-s
    void Run()
    {
        var list = new List<object>();
        Action<bool> action = weak () => if (list.TryGetTarget(out List<object> lst)) lst.Count > 0; // list is captured by WeakReference-s in lambda object
    }
}
```

## Motivation
[motivation]: #motivation
This feature could improve the situation with leak memory

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by HaloFour** [comment]
You can already use `WeakReference<T>` in these cases.
