### ISSUE TITLE
[Proposal]: Discard in 'using' declaration

### ISSUE THREAD

**Issue by FstTesla** [dotnet/csharplang#4085]
# Discard in using declaration

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Allow the usage of discards in `using` declarations, therefore combining `using` statements without variable and discards in standard variable declarations.

## Motivation
[motivation]: #motivation

Throughout this proposal, let's assume that we are talking about `using` statements that comply with all the conditions to be replaced by a `using` declaration.

While `using` statements with a variable can be transformed in `using` declarations, `using` statements without variable cannot be transformed in `using` declarations in a straightforward way.

At the moment, the simplest option to transform a suitable `using` statement without variable into a `using` declarations is as follows:
```
// BEFORE
using (MakeSomeDisposable())
{
  DoStuff();
}

// AFTER
using IDisposable _ = MakeSomeDisposable(); // or 'var'
DoStuff();
```

Of course, the underscore in this context acts as a regular identifier, so it can cause potential conflicts. Alternatives are usage of talking identifiers (e.g. `ignored`), one-letters (such as `d`) or identifiers that look like discards (such as `_0`, `_1`, `_d`).

## Detailed design
[design]: #detailed-design

The proposed change is to allow `using` declarations in the following form:
```
using _ = MakeSomeDisposable();
```
Its semantics are the same of the example given in the previous section, except that the variable is discarded.

Of course this whole proposal can be extended to `await using`.

## Drawbacks
[drawbacks]: #drawbacks

None.

## Alternatives
[alternatives]: #alternatives

Since this proposal is just syntactic sugar, the alternatives are keeping the `using` statement without variable as is, or transforming it according to the example above.

## Unresolved questions
[unresolved]: #unresolved-questions

None.

## Design meetings

N/A

**Comment by YairHalberstadt** [comment]
This is already championed at #2235, so whilst I think this is a cleaner writeup, I can't see the point of having two issues open
