### ISSUE TITLE
[Proposal]: Syntactic sugar for breaking out of or continuing nested loops

### ISSUE THREAD

**Issue by Ramobo** [dotnet/csharplang#4109]
# Syntactic sugar for breaking out of or continuing nested loops

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

- Extend the `break` statement to support `break {n};`, which breaks out of the `{n}` innermost loops;
- Extend the `continue` statement to support `continue {n}`, which starts a new iteration of each of the `{n}` innermost loops.

## Motivation
[motivation]: #motivation

Using nested loops is a common way to deal with multi-dimensional arrays:
```csharp
for (int z = 0; z < array.GetLength(2); z++)
{
    for (int y = 0; y < array.GetLength(1); y++)
    {
        for (int x = 0; x < array.GetLength(0); x++)
        {
            // [...]
        }
    }
}
```

If you always break out of at most the innermost loop, this is perfectly fine. If you want to break out of nested loops, however, you have two options:
1. `goto`:
```csharp
for (int z = 0; z < array.GetLength(2); z++)
{
    for (int y = 0; y < array.GetLength(1); y++)
    {
        for (int x = 0; x < array.GetLength(0); x++)
        {
            goto @break;
        }
    }
}
@break:
```
2. Break variable:
```csharp
bool shouldBreak = false;
for (int z = 0; z < array.GetLength(2); z++)
{
    if (shouldBreak) break;

    for (int y = 0; y < array.GetLength(1); y++)
    {
        if (shouldBreak) break;
        
        for (int x = 0; x < array.GetLength(0); x++)
        {
            shouldBreak = true;
            break;
        }
    }
}
```

Neither of these are ideal, and you know that the situation is bad because `goto` is the best option.

Here's the `continue` version:
```csharp
////////// GOTO //////////

for (int z = 0; z < array.GetLength(2); z++)
{
@continue:

    for (int y = 0; y < array.GetLength(1); y++)
    {
        for (int x = 0; x < array.GetLength(0); x++)
        {
            x++; y++; z++;
            goto @continue;
        }
    }
}

////////// CONTINUE VARIABLE //////////

bool shouldContinue = true;
for (int z = 0; z < array.GetLength(2); z++)
{
    for (int y = 0; y < array.GetLength(1); y++)
    {
        for (int x = 0; x < array.GetLength(0); x++)
        {
            shouldContinue = true;
            x++;
            break;
        }

        if (shouldContinue)
        {
            y++;
            break;
        }
    }

    if (shouldContinue)
    {
        shouldContinue = false;
        continue;
    }
}
```

## Detailed design
[design]: #detailed-design

The proposal is to support the following constructs:
```csharp
////////// BREAK //////////

for (int z = 0; z < array.GetLength(2); z++)
{
    for (int y = 0; y < array.GetLength(1); y++)
    {
        for (int x = 0; x < array.GetLength(0); x++)
        {
            break 3; // Breaks out of all 3 loops.
        }
    }
}
// Execution is here after `break 3;`.

////////// CONTINUE //////////

for (int z = 0; z < array.GetLength(2); z++)
{
    // After `continue 3`, execution is here and { z = 1, y = 1, x = 1 }.

    for (int y = 0; y < array.GetLength(1); y++)
    {
        for (int x = 0; x < array.GetLength(0); x++)
        {
            continue 3; // Goes to the next iteration of all 3 loops.
        }
    }
}
```

### Syntax

The following changes are made to the syntactic grammar:
```diff
break_statement
-    : 'break' ';'
+    : 'break' integer_literal? ';'
    ;

continue_statement
-    : 'continue' ';'
+    : 'continue' integer_literal? ';'
    ;
```

### Semantics

This proposal is so simple that I think that [Summary](#summary) and the examples at the beginning of [this section](#detailed-design) (these damn links aren't working) explain this well enough.

### Specification

The following sections will have to be changed:
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-break-statement
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-continue-statement

### Implementation

No runtime or library changes are necessary, as both of these can definitely be implemented as syntactic sugar around the `goto` statement, with `continue {n}` being harder. They would compile to something like the `goto` examples in [Motivation](#motivation).

## Drawbacks; Alternatives; Unresolved questions
[drawbacks]: #drawbacks
[alternatives]: #alternatives
[unresolved-questions]: #unresolved-questions

I see none.

## Design meetings

[None yet.]

**Comment by HaloFour** [comment]
https://github.com/dotnet/csharplang/issues/869

**Comment by MgSam** [comment]
`continue 3;` is way less clear and way more brittle than `goto @continue;`

**Comment by CyrusNajmabadi** [comment]
The way java does it seems utterly clear and simple.  You just label the loop, and you can `break/continue` that label.  If someone made a proposal for that, i would champion it.

**Comment by Joe4evr** [comment]
Also a duplicate of dotnet/roslyn#5883

**Comment by CyrusNajmabadi** [comment]
Proposal started here: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-15.0/labeled-break-continue.md
Championed Issue here: https://github.com/dotnet/csharplang/issues/9875
Discussion here: https://github.com/dotnet/csharplang/discussions/9876

Closing this out to move discussion there.
