### ISSUE TITLE
Planning: Working Set Themes

### ISSUE THREAD

**Issue by MadsTorgersen** [dotnet/csharplang#4144]
# Working Set themes

For planning purposes, here's a list of the language features in the [Working Set](https://github.com/dotnet/csharplang/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Working+Set%22) milestone sorted loosely by themes. It's important to note that there are way more features here than can fit in any one release! Also, while all are intended to get further language design scrutiny, that doesn't mean they'll make it all the way into a shipping version of C#.

## Initialization and immutability

- #4024 Direct constructor parameters
- #3885 Support readonly modifier for classes and records
- #3630 Required Properties 
- #3530 Extend with-expression to anonymous type 
- #2691 Primary Constructors 
- #162 Pattern-based `with` expressions
- #4334 Record structs
- Inherit between records and other classes

## Pattern matching

- #4018 Permit variable declarations under disjunctive patterns
- #3435 list pattern 

## Scope

- #3980 Call local static functions in base constructor
- #373 Support for method parameter names in nameof() 

## Nullable

- #3951 Nullable analysis of LINQ queries 
- #3950 `Task<T>` nullability covariance 
- #2145 Simplified parameter null validation code 

## Boilerplate reduction

- #3428 Global usings for namespaces, types and aliases with command line switch 
- #137 File scoped namespaces 

## Closed and grouped types

- #3179 "Closed" enum types 
- #2926 Name lookup for simple name when target type known 
- #113 Discriminated Unions

## Statements in expressions

- #377 Sequence Expressions 
- #3086 Expression blocks 

## Switch enhancements

- #3038 Enhanced switch statements 
- #3037 Block-bodied switch expression arms 
- #2632 Switch expression as a statement expression 

## Span and ref

- #2302 Efficient Params and String Formatting 
- #1881 Switching ReadOnlySpan<char> with constant strings 
- #1148 where T : ref struct 
- #1147 allow references to structs to be stored in fields of ref structs 

## Fixed

- #1793 Permit a fixed field to be declared inside a readonly struct
- #1502 Five ideas for improving working with fixed buffers 

## Type classes

- #1711 Roles, extension interfaces and static interface members 
- #110 Type Classes (aka Concepts, Structural Generic Constraints)

## Deconstruction

- #4082 Nominal and Collection Deconstruction 
- #1358 Allow value tuple deconstruction with default keyword 
- #125 Mix Declarations and Variables in Deconstruction

## Auto-properties

- #140 Semi-Auto-Properties; `field` keyword 
- #133 Property-Scoped Fields 

## Misc

- #3658 Repeated Attributes in Partial Members 
- #2180 Allow omitting unused parameters 
- #1407 Allow `[AsyncMethodBuilder(...)]` on methods 
- #287 CallerArgumentExpression
- #124 Allow Generic Attributes

**Comment by 333fred** [comment]
We're not using this issue for planning anymore, closing out.
