### ISSUE TITLE
[Proposal]: Allow for 'when' patterns on function parameters.

### ISSUE THREAD

**Issue by thargol1** [dotnet/csharplang#4182]
# Allow for 'when' patterns on function parameters.

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
Having patterns on function parameters would allow for functions to be split in several independent blocks of code.

## Example
A contrived example for clarity:
```csharp
public string Report(int number) when number < 0
{
	return "I'm sorry you're in debt.";
}

public string Report(int number)
{
	return "All clear.";
}
```
The compiler could generate the following code with a dispatcher for this
```csharp
// dispatcher
public string Report(int number)
{
	if (number < 0) return Report_@1(number);
	return Report_@2(number);
}

internal string Report_@1(int number)
{
	return "I'm sorry you're in debt.";
}

internal string Report_@2(int number)
{
	return "All clear.";
}
```

## Motivation
 This would allow for the following scenarios:
 * If the compiler can prove the parameters always meet the condition it can generate code that bypasses the dispatcher, making for faster code.
 * If the compiler can prove a specific version is never called and it's 'private' or 'internal' it can omit it from the generated dispatcher-code and remove the version entirely.

For developers it could mean:
* Clearer code with less indentation.
* More expressive function definitions.
* Separation of concerns on the micro level, e.g. separation parameter validation from actual implementation.
* Better documentation, if the documentation generator is updated as well.

For the .Net runtime it could mean faster code, for example `string.Equals(a, b, StringComparison.Ordinal)` could jump directly to the ordinal compare code bypassing some checks if it's defined with something like this `when a is not null and b is not null and comparison == StringComparison.Ordinal`.

## Drawbacks
One could consider this feature as 'helping the compiler'. In general developers should not help the compiler, it's smarter than most of them.

## Alternatives
Don't implement this and just use existing code patterns.

## Unresolved questions
Would this be limited to patterns or would expression also be allowed? The compiler would have an easier job proving patterns than expressions. On the other hand constant expressions calling constant functions can also be proven during compile time.

Use the `when` or the `where` keyword? In my opinion it should be the `when` keyword as this feature is similar to switch statements/expressions.

Would this be allowed for `virtual` functions? Object inheritance can complicate this a lot.

## Compatibility
As the generated dispatcher function is backward compatible with existing C# this feature would not break existing code bases.

## More examples
```csharp
class X : IEquatable<X>
{
	public string Y {get; private set;}

	public bool Equals(X? other) when other is null => false;
	public bool Equals(X other) => Y.Equals(other.Y); // Can we leave out the question mark after X, or would that change the signature?

	public void UpdateY(string? value) when value is null
	{
		throw new ArgumentNullException(nameof(value));
	} 

	public void UpdateY(string value) when value is { Length < 3}
	{
		throw new ArgumentException("Too short", nameof(value));
	} 

	public void UpdateY(string value) => y = value;

	void Demo(object param) when param is SqlConnection
	{
		//...
	}

	void Demo(object param) when param is SqlTransaction
	{
		//...
	}
}
```

**Comment by HaloFour** [comment]
See:

https://github.com/dotnet/csharplang/discussions/1548
https://github.com/dotnet/csharplang/issues/1468
https://github.com/dotnet/roslyn/issues/955
