### ISSUE TITLE
[Proposal]: constant type inference

### ISSUE THREAD

**Issue by pikadun** [dotnet/csharplang#4242]
# Constant type inference
constant type inference
* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Use `const <name> = <variable>;` instead of `const <type> <name> = <variable>;`.
Such as:
```csharp
const int a = 1; // old
const a = 1;      // new

const string s = "str"; // old
const s = "str";           // new
```

## Motivation
[motivation]: #motivation

### Why are we doing this?
It can make c# more concise;

### What use cases does it support?
All constant declarations, such as:
```csharp
const a = 1;
const s = "str";
```

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/issues/106

**Comment by YairHalberstadt** [comment]
Closing as championed at #106
