### ISSUE TITLE
[Proposal]: Support generic types in nameof()

### ISSUE THREAD

**Issue by cobalthex** [dotnet/csharplang#4251]
# Support generic types in nameof()

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: Add the ability for nameof to accept generic types without filled in type arguments, e.g. `nameof(List<>.Count)`.

## Motivation
[motivation]: Currently one needs to fill in a value for the type arg (any should do) for nameof to work. While the type doesn't matter, having one entered might imply that it does.

**Comment by yaakov-h** [comment]
Duplicate of #702.

**Comment by svick** [comment]
Closing as duplicate.
