### ISSUE TITLE
how to easily exclude properties from record equality?

### ISSUE THREAD

**Issue by juepiezhongren** [dotnet/csharplang#4257]
i have a record
```
    public record Order(string UserId, DateTime Time) {
        public User User { get; set; }
    }
```
where User is not a init property and i dont want it to be within equality consideration.

any easy way to make it happen?

**Comment by theunrepentantgeek** [comment]
I believe, by design, the answer here is to implement `Equals()` yourself since you don't want the auto-implemented behaviour.

**Comment by juepiezhongren** [comment]
@theunrepentantgeek ，i'm also trying to do a source generator for my senarios, where simply a equal override seems not enough

**Comment by orthoxerox** [comment]
I agree that it's one of the logical growth points for this feature. Reimplementing the whole equality is usually a big pain in the neck if all you need is to add a sequence-equal collection member or exclude a volatile member.

An attribute that supplies a different equality comparer for a member would work well, but I would settle for a helper like `System.HashCode` (`System.RecordEquals`?)
