### ISSUE TITLE
[please implement this feature in mobile development specially in android and ios along with other .net platform..If possible use interpreter support to implement them]: [Microsoft.CSharp]

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/csharplang#4261]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [x] Implementation: Not Started
* [x] Specification: Not Started

## Summary
[summary]: #summary

## Motivation
[motivation]: #motivation

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by Barshan-Mandal** [comment]
please implement this feature in mobile development specially in android and ios along with other .net platform..If possible use interpreter support to implement them]: [Microsoft.CSharp]

**Comment by YairHalberstadt** [comment]
Closing as this is a request for dotnet/runtime
