### ISSUE TITLE
[please introduce shared code for tizen ios android windows linux mac cloud and almost all supported platform in a single project as soon as you can..I like it very much]: [All in one Project]

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/csharplang#4262]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

## Motivation
[motivation]: #motivation

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by Barshan-Mandal** [comment]
please introduce shared code for tizen ios android windows linux mac cloud and almost all supported platform in a single project as soon as you can..I like it very much

**Comment by YairHalberstadt** [comment]
Closing as request for dotnet/runtime
