### ISSUE TITLE
[Please unify all nugets  for .net 5 and unity]: [Unification]

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/csharplang#4263]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

## Motivation
[motivation]: #motivation

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by Barshan-Mandal** [comment]
please specify nuget in another tab for .net 5 and unity..It wiill be an ide trembling feature I think

**Comment by YairHalberstadt** [comment]
Closing as not applicable to this repository. I would discuss with unity how this can be done.
