### ISSUE TITLE
[making hidden services for android and ios]: [Service for android , ios,linux,tizen and mac]

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/csharplang#4264]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

## Motivation
[motivation]: #motivation

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by Barshan-Mandal** [comment]
[making hidden services for android and ios]: [Service for android , ios,linux,tizen and mac]....Hackers will like it alike hackers used to love microsoft technologies like vs19 than xcode which is never used by hackers😂😂😂.Xcpde is the baddest ide ever

**Comment by YairHalberstadt** [comment]
I'm not sure what this is requesting but it's definitely not applicable to this repository. Maybe discuss with xamarin?
