### ISSUE TITLE
[please enable drag and drop feature in shared code alike xcode]: [drag and drop feature]

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/csharplang#4265]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

## Motivation
[motivation]: #motivation

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by Barshan-Mandal** [comment]
[please enable drag and drop feature in shared code alike xcode]: [drag and drop feature] it will make vs19 more popular with increasing popularity rate than xcode

**Comment by theunrepentantgeek** [comment]
This doesn't seem to be a request for a change to the C# langugage.

**Comment by yaakov-h** [comment]
This doesn't seem to be a request with _any_ level of specificity.

**Comment by sharwell** [comment]
This is either a feature request for dotnet/roslyn, or a suggestion for Visual Studio. I would suggest starting by providing feedback through the Report a Suggestion feature of Visual Studio.

**Comment by YairHalberstadt** [comment]
@Barshan-Mandal 

Before opening any new issues/discussions, could you please discuss with us on gitter which repository they're appropriate for?
