### ISSUE TITLE
[please introduce classes for cross platform Low level memory manupulation and low level works alike c programming with great ease of working]: [cross platform Low level memory manupulation]

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/csharplang#4266]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

## Motivation
[motivation]: #motivation

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by Barshan-Mandal** [comment]
[please introduce classes for cross platform Low level memory manupulation and low level works alike c programming with great ease of working]: [cross platform Low level memory manupulation]    hackers and os ddeveloper and virtualization developers  will like it

**Comment by sharwell** [comment]
This is a feature request for dotnet/runtime.
