### ISSUE TITLE
[Proposal]: Allow variable designation for property patterns

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#4294]
# Allow variable designation for property patterns

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Allows the following syntax: `if (myObj is string s { Length: 5 })`

## Motivation
[motivation]: #motivation

Currently, Both `if (myObj is string { Length: 5 })` and `if (myObj is string s)` are allowed. But the combination of both isn't allowed.

The combination of both will be useful in some situations to shorten long checks. e.g.:

```csharp
if (myObj is string s { Length: 5 } && SomeFunction(s)) { }
```

## Detailed design
[design]: #detailed-design

I'm unfamiliar with antlr, so I'll leave this part for someone else to write.

## Drawbacks
[drawbacks]: #drawbacks

I can't think of any drawbacks. This doesn't complicate or add any cluster to the language syntax as both syntaxes are allowed today.

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by Youssef1313** [comment]
[A real example](https://github.com/dotnet/roslyn/pull/50219/commits/f937e8d8a2f10747077bbcd8584c35e3ea4d8441) of where this could be useful.

**Comment by HaloFour** [comment]
The variable designation goes after the property patterns:

```cs
if (myObj is string { Length: 5 } s)
```

**Comment by Youssef1313** [comment]
@HaloFour, whops. My mistake. I think the diagnostic should be more clear when the order is swapped. Let me close this and open an issue in roslyn for diagnostic clarity.

**Comment by Youssef1313** [comment]
Opened https://github.com/dotnet/roslyn/issues/50220. Thanks @HaloFour.
