### ISSUE TITLE
[Proposal]: Diamond operator (generic types inference)

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#4295]
# Diamond operator (generic types inference)

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Similar to Java's diamond operator, this proposal is to allow the usage of diamond operator `<>` to infer generic types when possible.

## Motivation
[motivation]: #motivation

Consider a real example from Roslyn's repo like [this](https://github.com/dotnet/roslyn/blob/a351a149558878a79b514278ef0236bb4eeab7ca/src/EditorFeatures/TestUtilities/Workspaces/TestHostDocument.cs#L83).

It's much more nicer to write:

```csharp
        // Short version with diamond operator.
        public IDictionary<string, ImmutableArray<TextSpan>> AnnotatedSpans { get; } = new Dictionary<>();

        // Unnecessarily long and repetitive.
        public IDictionary<string, ImmutableArray<TextSpan>> AnnotatedSpans { get; } = new Dictionary<string, ImmutableArray<TextSpan>>();

```

## Detailed design
[design]: #detailed-design

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by YairHalberstadt** [comment]
Discussed previously at https://github.com/dotnet/csharplang/discussions/2935

It's not immediately obvious how the type parameters will be inferred. I'm moving this to a discussion to help drive forward a spec for that.

**Comment by YairHalberstadt** [comment]
It doesn't look like it's possible to convert issues to discussions anymore. I'm going to close this, and feel free to open a discussion about how this could be specced. Alternatively if you add more detail to this issue let me know and I'll reopen :-)
