### ISSUE TITLE
[Proposal]: Construction Methods

### ISSUE THREAD

**Issue by msedi** [dotnet/csharplang#4296]
# Construction Methods

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
Currently only constructors can access readonly properties. However, sometimes there is a need to move parts of the constrcutor into helper methods, but these helper methods cannot modify readonly properties. I therefore suggest a possibility to enable methods to modify/set readonly properties at object construction (which I here call construction methods).

## Motivation
Due to different reasons it is sometimes necessary to move constructor code into helper methods 

- Reason 1
You cannot change the order of how constructors are executed. Sometimes you need to insert code in front of the original constructor which is currently not possible. A solution is to introduce a protected virtual method that enables to modify the object creation before or after the original constructor.

- Reason 2
Sometimes constructor code can be massive and it makes sense to shift this code into lokal helper methods.

One way out would be to make these properties `protected set` so that these methods can modify the potential readonly property. Or you make the property `private set` and let these methods return the value and assign it in the constructor.

## Detailed design
In the end the proposal is pretty simple. If accepted here, there needs to be some sort of relaxation to methods that take part in the construction process. But with special restrictions:

- They can only be called in the constructor  and should therefore not show up in IntelliSense 
- They need to marked e.g. as `constructor` (just a proposal, I personally also do not prefer it)

## Drawbacks
I can currently see no runtime disadvantages, but I see the problem that a method with a "weird" behavior is introduced, compared to other methods. 

Honestly, I would prefer a better way, but since from my knowledge virtual method calls in constructors are not the preferred way, I see currently not other alternative.

## Alternatives
Leave it as it is and stay with virtual methods that return the value which is then assigned in the constructor.

## Unresolved questions
At least for me it is still a question how much benefit readonly properties have compared to private set properties if the runtime is able to optimize and inline properties at all. If this is somehow clarified there would be maybe no need for this proposal. But then the question is how much benefit readonly properties really have.

**Comment by YairHalberstadt** [comment]
Thanks for the suggestion!

As explained [here](https://github.com/dotnet/csharplang/discussions/3578#discussioncomment-143634) it seems likely this will happen in a future release.

I don't think this issue is substantially different from that existing discussion, so absent a formal spec for this proposed feature I'm going to close this to keep discussion over there.
