### ISSUE TITLE
[Proposal]: Covariant override parameters

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dotnet/csharplang#4300]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

In C# 9 we have covariant return types. It would be nice to have the same for method parameter.

## Motivation
[motivation]: #motivation

## Detailed design
[design]: #detailed-design
public class A1{}
public class A2:A1{}

public class A{
virtual void A(A1 a);
}
Public class AI:A{
override void A(A2 a){}
}

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/discussions/3562

**Comment by YairHalberstadt** [comment]
Parameters can't be covariant, they have to be contravariant. That's discussed at #3562
