### ISSUE TITLE
C# Better Define Directive

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/csharplang#4311]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-Better-Define-Directive/1273115)._

---
<p>Personally I think it's already time to the C# implement more complex #define syntaxes</p><p>I really want can o things like:</p><pre>#define ver 499
#if ver &lt; 500
Console.WriteLine(ver);
//not very important, but should be good as well that create a anonymous constant value<br>#endif<br></pre><p></p>

---
#### Feedback Bot on 11/30/2020, 09:56 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by HaloFour** [comment]
https://github.com/dotnet/csharplang/discussions/3254

**Comment by 333fred** [comment]
Closing as a duplicate.
