### ISSUE TITLE
Interpolated String Parse-Error

### ISSUE THREAD

**Issue by bernd5** [dotnet/csharplang#4318]
**Version Used**: 
3.9.0-2.final

**Steps to Reproduce**:
The following code is parsed invalid:
```CSharp
using System;

namespace Tests
{
	class App
	{
		static void Main()
		{
			string s = $"InterpolatedString {{{27,7:X}}}";

			Console.WriteLine(s);
		}
	}
}
```

Easy visible with syntax highlighting:
![grafik](https://user-images.githubusercontent.com/26689688/102718120-c16d2900-42e6-11eb-8fcd-cae26ab1e864.png)

**Expected Behavior**:
The curly braces do not belong to InterpolationFormatClauseSyntax. The content should be simply: "X".

**Actual Behavior**:
we get an InterpolationFormatClauseSyntax with the content "X}"

**Comment by bernd5** [comment]
I had a look at the [spec](https://github.com/dotnet/csharplang/blob/a3d67d141501101af9dbb9e8192ca8b4c717e316/spec/lexical-structure.md#interpolated-string-literals) and found:

```
interpolation_format_character
    : '<Any character except \" (U+0022), : (U+003A), { (U+007B) and } (U+007D)>'
    ;
```

Therefore the roslyn implementation seems to be invalid. The issue can move back to roslyn.

**Comment by jaredpar** [comment]
@bernd5 the issue though is should we adjust to match the new interpretation of the BCL.

**Comment by alrz** [comment]
while you're at it, maybe permit ternaries without parentheses in case this is actually a parsing issue.

I think Cyrus had a proposal to parse it just like TS does.

**Comment by bernd5** [comment]
As I understand the spec, the language forces the new interpretation of BCL for interpolation-format-strings.
And I understand that this was not a big issue because the current roslyn implementation allows both interpretations by simply not interpreting it at compile-time. It is handled at runtime via String.Format.

We get just an issue if we write for example syntax-rewriters to optimize such strings. And of course things like syntax-highlighting.

**Comment by bernd5** [comment]
In addition to the "brace-issue" I would like to add these issues, too:

https://github.com/dotnet/roslyn/issues/50742

https://github.com/dotnet/roslyn/issues/50741

**Comment by bernd5** [comment]
In addition the spec does not dissallow preprocessor directives / the hash-sign inside of interpolated strings which are explicitly dissallowed in the roslyn implementation (who is right?).

Shouldn't preprocessing handled before lexing?

This code does not compile with roslyn:
```
using System;

Console.WriteLine(@$"Test
{
#if XXX
  "A" 
#else
  "B"
#endif 
}");
```
