### ISSUE TITLE
Introduce attribute for warning / error if a method's return value is not used

### ISSUE THREAD

**Issue by Richiban** [dotnet/csharplang#432]
In modern programming it is considered good programming practice to separate functions / methods into one of two categories: _commands_ and _queries_. _Commands_ are methods that modify some global state (such as persisting to a database or just mutating an object) and should not return data; _queries_ are methods that calculate and return some state in the program and must not modify any state in the process.

In order to aid this approach (as well as bringing other benefits that I'll bring up later), I propose that C# introduce something similar to Swift 2's `@warn_unused_result` attribute. It decorates a non-void method and indicates that the compiler should give a warning if the return result of the method is not used ("used" in this case means: assigned to a variable, passed into a method etc).

This enables us to clearly indicate that a method is only useful for its return value (all _queries_ will be this way). Example usage:

```csharp
[WarnUnusedResult]
public int GetTotalPrice()
{
	return (from item in _items
	        where item.IsLive
	        select item.Price).Sum();
}
```

The compiler would then give a warning in the following case:

```csharp
public void Main()
{
	DoSomething();

	card.GetTotalPrice(); // Warning: return result is ignored

	DoSomethingElse();
}
```

To get the warning to go away, add the following assignment:

```csharp
public void Main()
{
	DoSomething();

	var total = card.GetTotalPrice();

	DoSomethingElse();
}
```

Please note: Despite some similarities this is _not_ the same as `[Pure]`. Not modifying state is only half the definition of a _pure_ function; the other half being that the function must always return the same answer for a given set of inputs. An example:

```csharp
public DateTime GetNow()
{
	return DateTime.Now;
}
```

The above method is clearly not pure: it takes no arguments yet will return a different result (nearly) every time it is called. It would benefit from the addition of a `WarnUnusedResult` attribute.

As for other benefits: it's also very important for methods that return Tasks. Given the method 

```csharp
public async Task MyMethod()
{
	await Task.Delay(500);

	DoSomeStuff();
}
```

if I call `MyMethod()` and don't await the result C# will give me a compiler warning: 

> Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.

This is very desirable, **but** it only seems to occur if the method is marked as `async`, not if it simply returns a `Task`, as in this example:

```csharp
public Task MyOtherMethod()
{
	return Task.Delay(1000);
}
```

In the above case no error / warning will be shown but serious and hard-to-find bugs may well occur as a result. With an attribute warning that the result of the method should not be ignored, these issues will be easy to find within your codebase.

For what it's worth I would rather this attribute was the other way around (i.e. the compiler assumed that all return values shouldn't be ignored and an attribute can be used to indicate an ignorable result), but that would be too close to a breaking change and is therefore unlikely to be implemented.

**Comment by zippec** [comment]
> Commands are methods that modify some global state (such as persisting to a database or just mutating an object) and should not return data; queries are methods that calculate and return some state in the program and must not modify any state in the process.

I disagree. What you call commands usually return values in modern APIs in order to accommodate fluent syntax. Ignoring their return value should not yield warnings.

**Comment by Richiban** [comment]
@zippec 
>> Commands are methods that modify some global state (such as persisting to a database or just mutating an object) and should not return data; queries are methods that calculate and return some state in the program and must not modify any state in the process.

> I disagree. What you call commands usually return values in modern APIs in order to accommodate fluent syntax. Ignoring their return value should not yield warnings.

Fluent APIs are a very specific case (I would argue that it's a bit of a hack anyway because of the language's lack of method cascading). Since it's fairly prevalent in OO programming that's why I'm not actually advocating that the warning be the default.

I wrote a Roslyn analyzer that gives warnings for unused return values; it works well but I need Attributes in the BCL to turn it on (or off). In addition this is a feature that needs to be very commonplace in order to be useful; everyone has to have it or hardly anyone will annotate their methods.

**Comment by DavidArno** [comment]
> In modern programming it is considered good programming practice to separate functions / methods into one of two categories: commands and queries.

I dispute the claim that this is considered good practice in "modern programming". This thinking is ten years old and belongs to the ideas of the rotten domain model.

I think the idea is back to front too. It shouldn't be for the author of `GetTotalPrice` to decide if I should handle the result or not. It would be better, in my view, to have a Roslyn analyzer warn on *all* ignored return results (either on an opt-in or opt-out basis using attributes).

**Comment by Richiban** [comment]
@DavidArno Come on man, I'm not arguing for DDD here. I'm just saying (along with people like Bertrand Meyer and Mark Seemann) that:

> Asking a question should not change the answer

You're right that this is not a new idea, but it's still new to most devs that I meet.

**Comment by CyrusNajmabadi** [comment]
Something like "warn_unused_result" would absolutely be useful.  Especially for API's like System.Collections.Immutable where you can do things like "collection.Add(...)" but it's a mistake if you don't observe the result of the operation.

However, this does not need to be anything in the language.  You could accomplish this today with a set of attributes and an analyzer.  For APIs that didn't use the attribute, you could also just provide purity files (similar to how Typescript has .d.ts files) that specify API signatures known to have this behavior.

**Comment by CyrusNajmabadi** [comment]
> "Introduce attribute"

Any time a feature is basically "add an attribute, and check it", i recommend that the proposal be moved over to:

https://github.com/dotnet/roslyn-analyzers

**Comment by Richiban** [comment]
@CyrusNajmabadi 
> You could accomplish this today with a set of attributes and an analyzer

That was my initial reaction as well, and in fact I've written a Roslyn Analyzer to do exactly this. However, it's not particularly useful if the BCL doesn't offer some method of opting in / out as the feature needs to be widespread to work.

Currently Roslyn doesn't offer any functionality for decorating the methods of external APIs with an attribute; can you imagine the fragmentation if it did?

If this is not at its most appropriate as a language feature, perhaps an attribute in https://github.com/dotnet/corefx combined with an analyzer in https://github.com/dotnet/roslyn-analyzers?

**Comment by CyrusNajmabadi** [comment]
I feel like this is very amenable to the TypeScript solution.  Instead of mandating that every API know about and opt-into this attribute, APIs can be annotated *after the fact* with whatever information you want.  That way you can quickly rev this stuff *and even work with previous versions of APIs*, without having to get the entire world to adopt and proffer this attribute.

**Comment by CyrusNajmabadi** [comment]
Note: this is how Roslyn handles things like Public-APIs btw.  We have a file that contains the signatures of hte APIs we've made public.  And we have an analyzer that checks our compilations to make sure we haven't gotten rid of any of them.  No need for attributes when you can just get the full name of a symbol and use that to indicate the presence of this behavior.

**Comment by CyrusNajmabadi** [comment]
> can you imagine the fragmentation if it did?

This is literally how TypeScript works, and there seems to be little (any?) fragmentation in their ecosystem.  People just publish d.ts files documenting the APIs and those d.ts files are used by everyone.  Sites like DefinitelyTyped aggregate those files as well.  

I'd much rather that sort of approach rather than having to define a new attribute, bake it into the compiler, and then wait 5-10 *years* for this attribute to get any traction across things like teh BCL and other major libraries.

**Comment by Richiban** [comment]
> This is literally how TypeScript works, and there seems to be little (any?) fragmentation in their ecosystem

Isn't this because everyone is working towards a single goal: adding type information to an API?

This is certainly an interesting idea. How would you see it working? If I have a particular attribute defined in a NuGet package somewhere, how would decorate, say, a method in the immutable collections package? And, more importantly, do I add my attribute to the same definition file that everyone else is adding their attributes to as well?

**Comment by CyrusNajmabadi** [comment]
I'm would go a dual approach:  

1. define an attribute.  If a member has that attribute, respect it.
2. just allow for a text file listing members that have been 'virtually annotated' (like how Roslyn does our public-API analysis) or how TS uses .d.ts files.

Use both to determine if this is a member whose result should be observed.  If it should, and it isn't, then error.

**Comment by gafter** [comment]
This sounds more like a compiler (or analyzer) feature than a language feature.

**Comment by leotsarev** [comment]
If you will do it, please use name [MustUseReturnValue] for R# compatibility

**Comment by Joe4evr** [comment]
> Especially for API's like System.Collections.Immutable

Or `System.String`. I occasionally see newbies trip over the fact that `string.Replace()` and the like "didn't change the string at all".

**Comment by CyrusNajmabadi** [comment]
Closing as this is not a language feature.

**Comment by CyrusNajmabadi** [comment]
Feel free to reopen on roslyn-analyzers

**Comment by perlun** [comment]
(For reference, did anything come out of this discussion? I found this issue while googling for something similar to the C++ `[[nodiscard]]` attribute which is [available now since C++17](https://en.cppreference.com/w/cpp/language/attributes/nodiscard). It would be surprising for C++ to be more innovative than C# for a change. :slightly_smiling_face:)

**Comment by CyrusNajmabadi** [comment]
@perlun c# already hadt an analyzers system to add restrictions to the language. We don't need new language features for that :-)

**Comment by perlun** [comment]
Fair enough @CyrusNajmabadi. I think this is perhaps an important enough feature to make it into Roslyn/csc itself though, but... I'll quite honestly say that I have zero insight into the design philosophy around it. Of course you can always add it as an "external" analyzer so to speak, but it'll always be more of a 2nd class citizen that way, won't it?

**Comment by CyrusNajmabadi** [comment]
>  but it'll always be more of a 2nd class citizen that way, won't it?

No.  We don't treat any analyzers as more or less special.  My view is that the community driven analyzers are more important as they reflect what teh community comes up with for all these particular domains :)

**Comment by bernd5** [comment]
I think it is more a runtime issue - they should introduce an attribute like "NoDiscard" which could be analyzed. Otherwise we may end up in a bunch of different attributes with the same meaning...
Not sure who would write the analyzer - but analyzers like that should become part of the standard toolkit / SDK.

**Comment by CyrusNajmabadi** [comment]
> Otherwise we may end up in a bunch of different attributes with the same meaning...

That doesn't seem like a problem.  Presumably the community will settle on the ones they think are best.

**Comment by colejohnson66** [comment]
If you're using JetBrains' Rider, the `JetBrains.Annotations` package has `[MustUseReturnValue]`.
