### ISSUE TITLE
[Proposal]: throwing exceptions should accept expression for throwing different exceptions

### ISSUE THREAD

**Issue by SetTrend** [dotnet/csharplang#4356]
# `throw` should support conditional expressions

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
I propose to have the `throw` keyword support conditional operators in order to throw different exceptions depending on a condition, like this:

```c#
if (x is List<string>) ...
else throw x is null
  ? ArgumentNullException("Null argument provided.")
  : new ArgumentException("Invalid object provided.");
```

## Motivation
My proposal will save some amount of traditional typing when checking for correct method arguments.

## Detailed design

The `throw` keyword should accept an _**expression**_ yielding an object derived from `System.Exception`.

## Drawbacks
None that I could think of at the moment.

## Alternatives

Not implementing my proposal would retain the constantly recurring typing effort to write code like this:

```c#
if (x is List<string>) ...
else
  if (x is null) throw new ArgumentNullException("Null argument provided.");
  else throw new ArgumentException("Invalid object provided.");
```

## Unresolved questions
None so far.

**Comment by HaloFour** [comment]
Did you close this accidentally or because you realized that it's already legal?  The `throw` statement has always allowed any `Exception`-returning expression.

**Comment by SetTrend** [comment]
Hi Halo,

yes, unfortunately I was too impatient when I created this issue :cry:.

I accidentally believed this was the cause for a cryptic Analyzer message about [`ArgumentNullException` string content](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2208) (which was even more crypting in its German translation, to give as an excuse). I then accidentally misinterpreted my conditional expression as being the cause for this message because after I rephrased this part of my code the analyzer first cleared the error window and then took quite a while to complain again 😯  ...

So I quickly went to close this false issue 😰
