### ISSUE TITLE
[Proposal]: Nullable reference type checks should not be performed on members of abstract class

### ISSUE THREAD

**Issue by SetTrend** [dotnet/csharplang#4358]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary / Motivation
Currently, nullable reference checks are performed on non-private properties/fields of abstract classes.

![grafik](https://user-images.githubusercontent.com/9283914/105789538-ed816700-5f82-11eb-8017-5e15a562a4c3.png)

Abstract classes, however, cannot be instantiated. Instead, a derived class _must_ be implemented to get the abstract class to life.

So, I propose to omit corresponding nullable reference checks from the constructor of abstract classes and, instead, raise them to occur on constructors of derived, non-abstract, implementing classes:

![Nullable reference checks on abstract class](https://user-images.githubusercontent.com/9283914/105792152-6be00800-5f87-11eb-8ac5-c7f8eec0de5f.gif)

Currently, it is required to assign redundant dummy values to such kind of properties/fields, which is cumbersome depending on the type of object to create. It doesn't add meaning to the code and bloats the result.

**Comment by Phantonia** [comment]
I kind of see your point, but I disagree. In my opinion, each field should be `private`. Every class should ensure itself that instances are in a valid state. It's also quite telling that you can't even assign `readonly` field of the base class in a sub class's constructor. 
The better way would be assigning the field in the base class's constructor and making it a parameter.
