### ISSUE TITLE
Proposal: Generic type constraint for all nullable types

### ISSUE THREAD

**Issue by lachbaer** [dotnet/csharplang#441]
There are sometimes scenarios where a generic class or function is always valid for nullable value types as well as (nullable) reference types.

Currently there is no other way as to duplicate the code
```cs
static IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T> list) where T : class
{
   return list.Where(x => x != null);
}
static IEnumerable<T?> GetNonNullitemList<T>(IEnumerable<T?> list) where T : struct
{
    return list.Where(x => x != null);
}
```

I propose a type constraint `?` (or `??`, or `???`) that allows for all nullable types
```cs
static IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T> list) where T : ?
{
    return list.Where(x => x != null);
}
```
The "Questionmark" `?` would fit in nicely with the current meanings.

This could be extended to allow only *non-nullable* types and non-nullable reference types
```cs
static IEnumerable<Type> GetTypeList<T>(IEnumerable<T> list) where T : !
{
    // we can safely call a method on x, because x cannot be null
    return list.Select(x => x.GetType());
}
```

**Comment by yaakov-h** [comment]
This seems like it should be considered as a part of #36, not it's own feature.

**Comment by svick** [comment]
```c#
static IEnumerable<T> GetNonNullItemList<T>(IEnumerable<T> list) where T : ?
{
    return list.Where(x => x != null);
}
```

So, if I pass `IEnumerable<int?>` in, I get `IEnumerable<int?>` back, even though it won't contain any `null`s? I don't think that's good enough.

In my opinion, what you want is to be able to write `T?` without having to constrain it to `struct`. E.g.:

```c#
static IEnumerable<T> GetNonNullItemList<T>(IEnumerable<T?> list)
{
    return list.Where(x => x != null).Select(x => (T)x);
}
```

The problem with this is that there is no good way to express it at the IL level. But maybe it could work with some kind of CLR modification.

**Comment by lachbaer** [comment]
@svick 
> So, if I pass IEnumerable<int?> in, I get IEnumerable<int?> back, even though it won't contain any nulls? I don't think that's good enough.

In this special case, yes. But if you enter reference types, then it fits.
As probably non-nullable reference types will come, with an `!` token that shall somehow ensure non-nullness, the following modification could work.
```cs
static IEnumerable<T!> GetNonNullitemList<T>(IEnumerable<T> list) where T : ?
{
    return list.Where(x => x != null).Select(x => (T!)x);
}
```

**Comment by CyrusNajmabadi** [comment]
Why not just have:

```
static IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T?> list) where T : struct
    => list.Where(x => x != null).Select(x => x.value);

static IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T> list) where T : class
    => list.Where(x => x != null);
```

This will work on lists of nullables, and lists of reference types.  It will *appropriately* not work on lists of value types.

**Comment by jnm2** [comment]
@CyrusNajmabadi If overload resolution let us have that, it would be amazing.

**Comment by CyrusNajmabadi** [comment]
Overload resolution should give you that today.  I just tested and it worked exactly as expected:

```c#
    static IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T?> list) where T : struct
        => list.Where(x => x != null).Select(x => x.Value);

    static IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T> list) where T : class
        => list.Where(x => x != null);

    void Test(IEnumerable<int> structs, IEnumerable<int?> nullables, IEnumerable<string> classes)
    {
        // GetNonNullitemList(structs); <-- get compiler errror.
        GetNonNullitemList(nullables);
        GetNonNullitemList(classes);
    }
```

**Comment by orthoxerox** [comment]
@CyrusNajmabadi it will break when it's the return type that is nullable:

```c#
static T? SafeGet(IReadOnlyList<T> source, int index)
    => (index >= 0 && index < source.Count) ? source[index] : null;
```

**Comment by lachbaer** [comment]
@CyrusNajmabadi 
And it is code duplication, because if `T?` would also respect **all** nullable types, i.e. including reference types, the same could be expressed as
```cs
    static IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T?> list)
        => list.Where(x => x != null).Select(x => (T)x);
```
A possible `where T : ?` could tell the compiler to generate the two variants, but with the same contents
```cs
    IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T?> list) where T : struct
    IEnumerable<T> GetNonNullitemList<T>(IEnumerable<T> list) where T : class
```

Same goes for `where T : !` and `T!`. That must say, that the supplied type must be non-nullable
```cs
// we can safely call a method on x, because x cannot be null
static IEnumerable<Type> GetTypeList<T>(IEnumerable<T!> list) where T : !
    => list.Select(x => x.GetType());
```
The `: !` would tell the compiler to create two versions, one for `struct`, one for `class`.

In case of a CLR change, the `where T : ? / ! ` can be ommited if just `T?` and `T!` respect all (non)-nullable types and do not rely on the `System.Nullable<T>` type.

**Comment by mikernet** [comment]
I don't think the nullable value type / nullable reference type behavioral split can possibly be bridged without a new runtime and new C#2 language. The current split between how nullable reference types and nullable value types behave means we are just piling on more and more of these syntactical complexities to work around what should really be a simplification instead. 

Generic constraints kinda suck because they force the consumers to also have the same constraints all the way up. That was mildly tolerable when it was just struct/class but with nullable issues on top of all that it's getting a bit silly. 

The only way around all this mess is to redo everything and have some way for generic arguments to indicate whether they accept only a nullable type, only a non-nullable type or either type. NRTs need to be similar to NVTs in the sense that they are considered a different type by the runtime and  behave the same way. Generic parameters can then be explicitly nullable or non-nullable even for reference types and then everything works together symbiotically.

A man can dream :)
