### ISSUE TITLE
Discussion: extend the scope of parameter names to attributes

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#443]
```cs
[SomeAttribute(nameof(param))]
void M(object param, [CallerArgumentExpression(nameof(param))] string arg = null) {}
```
PS: This is different from https://github.com/dotnet/csharplang/issues/373 as it proposes to allow parameters in `nameof` from any method.

**Comment by gafter** [comment]
This would be an incompatible change. Instead of binding to a constant from the enclosing scope, an attribute argument would now bind to a (non-constant) parameter, which would make a currently compiling program an error.

**Comment by jamesqo** [comment]
@gafter Do you mean something like

```cs
private const string foo = "";

void M(string foo, [AttributeAcceptingString(foo)] string blah) {}
```

would break, because it would bind to the parameter `foo` instead of the constant `foo`? In that case, why not check to see if there is a constant named `foo` before checking for parameters?

**Comment by alrz** [comment]
@jamesqo this change would not affect your example, because `foo` as a parameter has no value in an attribute. However, it affects a `nameof(constant)` if there is also a parameter named `constant`, *with no observable difference* (it's the string "constant" either way). Anywho, as you said, with a specific lookup order this issue will be resolved.

**Comment by taori** [comment]
Accessing the name of argument names with this version is very inconvenient in comparison to a modification of the nameof expression as described in #373 i would say.

**Comment by alrz** [comment]
Closing in favor of championed issue https://github.com/dotnet/csharplang/issues/373
