### ISSUE TITLE
Comparing Against a Generic Type

### ISSUE THREAD

**Issue by Hosch250** [dotnet/csharplang#447]
I recently had this code:
```
interface IFoo
{
    void DoSomething();
}

interface IValueFoo<T> : IFoo
{
    IEnumerable<T> Foos { get; }
    void LoadFoos(SomeType val);
}
```
Then, at one point, I had a collection of `IFoo`s, some of which were `IValueFoo`s. I needed to run an operation on all `IValueFoo`s, so I wanted to do something like:
```
SomeType val = new SomeType(); // just for example
foreach (var foo in fooCollection.OfType<IValueFoo<>>()) { foo.LoadFoos(val); }
```
This resulted in error CS7003.

---

My proposal is to extend type matching (is this the right term?) where generic arguments are involved for the following cases:
```
.OfType<T>()
[identifier] as [type]
[identifier] is [type] [newIdentifier]?
```
Rather than requiring an argument for the generic type, it will allow:
```
foo is IValueFoo<>
foo is IValueFoo<,>
```

**Comment by CyrusNajmabadi** [comment]
What is the type of 'foo' in this code:

```foreach (var foo in fooCollection.OfType<IValueFoo<>>())```

? 

It looks like it will be an ```IValueFoo<>```, but i have no idea what that is...

What could you do with that type?  You would not be able to call "Foos" on it because you'd have no idea what the return type of that variable would be.  So what would you expect this to do?

**Comment by Hosch250** [comment]
Ah, I missed part of the interface, but I totally get your point. The background of this issue was I wanted to walk an ANTLR parse tree with a set of listeners defined in some "inspections" (like Roslyn analyzers). Each inspection has its own listener and list of interesting nodes found by the listener, but I don't care about `T` in this circumstance. I think what I really need is a third interface that `IValueFoo<T>` implements that exposes just these listeners.

Thank you for showing me this flaw; I have absolutely no idea what this would be useful for myself, now.

**Comment by CyrusNajmabadi** [comment]
:)

>  I think what I really need is a third interface that IValueFoo<T> implements that exposes just these listeners.

Yes.  That's waht i've done myself in the past.  Works well for the parts that you clearly don't/can't use the the strong-typed parts of.
