### ISSUE TITLE
[Proposal]: Shorthand property setter

### ISSUE THREAD

**Issue by c0nd3v** [dotnet/csharplang#4480]
# Shorthand property setter

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
Easier way to quickly define a setter only property (Similar to the shorthand getter property feature) **This feature assumes we want to have a default get method**

## Motivation
I think it makes sense because we already have the shorthand getter.

## Detailed design
Its already there for the getter so why not have it for the setter.

```cs
public int hello <= 100 * value;
```

## Drawbacks
None that I can think of.

## Alternatives
Using the normal set:
```cs
private int _hello;
public int hello
{
    get => _hello;
    set => _hello = 100 * value;
}
```

## Unresolved questions
None that I can think of

## Design meetings
Sorry but I'm not sure about this one either.

**Comment by theunrepentantgeek** [comment]
What is the value of this? What problem does it solve?

```
public int hello <= 100 * value;
```

This world declare a write-only property with an inaccessible field for storage, so the only code that can read the value will be using reflection. Doesn't seem to be widely useful. 

Note that this can't be equivalent to your alternative as the backing fields for autoproperties have inexpressible names to avoid name collisions.
