### ISSUE TITLE
[Proposal]: Jump Filters / Conditional Jump Statements

### ISSUE THREAD

**Issue by crazycrank** [dotnet/csharplang#4482]
# Jump Filters / Conditional Jump Statements

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Add the ability to define jump filters on jump statements to reduce dead lines and improve readability for jump statements that only execute under certain conditions.

## Motivation
[motivation]: #motivation

An often seen pattern is to have a method return or throw, or a loop continuing/breaking under certain conditions. This can be to guard a method entry, provide an early success condition, or for many other reasons. E.g. `Equal` methods suffer heavily from this. This is typically done using the always identical patterns
```csharp
// probably the default version, but it has lot a dead lines, and with a empty line after the block,
// uses 5 lines of code.
if (condition)
{
    return; // could also be throw, continue, break or even goto
}

// this shorthand variant reduces the lines used to (still) 3. This variant often conflicts with styleguides as well.
if (condition)
    return;

// The shortest variant, but it still often breaks with styleguides, as readability of single line statements 
// isn't that great. It also hides the most important information (watch out, the method can end here!) 
// at the end of the line, which is especially bad if the condition is a somewhat long statement. 
// It als increases mental complexity to grasp the flow of the logic.
if (condition) return;

if (havingAnObject.WithALongMethodName(andAnotherLongParameterName)) return SomeClass.AndInnerClass.ConstantValue;
```

Reducing this boilerplate with a concise statement that brings the intended flow information into the foreground could increase developer productivity, especially when reading code. It also goes nicely with other syntactic sugar improvements of C# in the past few years, like exception filters and all the null conditional shorthands.

## Detailed design
[design]: #detailed-design

I propose introduce conditional jump statements or jump filters (along the lines of exception filters). These provide a syntactic sugar for this often seen pattern. A jump statement could look like something of the following

```csharp
// a conditional return
return value when (condition);

// or throwing an exception
throw new ArgumentOutOfRangeException(nameof(arg)) when (arg < 0);

// continuing the loop
continue when (i % 7 == 0);

// or with pattern matching 
return failure when ({ IsFailure: true } failure);

// with a line break in case of long statements, which shows the readability benefit of bringing the 
// jump statement to the front of the line.
return SomeClass.AndInnerClass.ConstantValue
    when (havingAnObject.WithALongMethodName(andAnotherLongParameterName);

// same thing for break and goto
```

This allows developers to better focus on the core business logic of a method, reducing dead lines for guarding checks of parameters or when early jumps out of the current flow are possible. The also bring the intent of a statement into the foreground, reducing mental overhead when parsing a method.

The proposed syntax is straight forward and should feel natural to the language. I think using `when` instead of `if` gives it a nice symmetry to exception filters, which also puts the condition to the back of the statement. That's also why I'm talking about jump filters in this proposal and not about conditional jump statements or similiar.

The compiler would translate all this statements to the currently valid form, so the compiled IL should look the same no mattter which form is used. So
```csharp
return value when (condition);
```
translates to
```csharp
if (condition)
{
    return value;
}
```
using all the same rules as the original form, especially considering pattern matching and variable assignments.

The jump filter could be attached as a conditional element to all of the existing jump_statements currently present in the language
```antlr
return_statement
    : 'return' expression? jump_filter? ';'
    ;
throw_statement
    : 'throw' expression? jump_filter? ';'
    ;
break_statement
    : 'break' jump_filter? ';'
    ;
continue_statement
    : 'continue' jump_filter? ';'
    ;
goto_statement
    : 'goto' identifier jump_filter? ';'
    | 'goto' 'case' constant_expression jump_filter? ';'
    | 'goto' 'default' jump_filter? ';'
    ;

jump_filter
    : 'when' '('  boolean_expression ')'
    ;
```

## Drawbacks
[drawbacks]: #drawbacks
It introduces  a new language feature for something that we can already do, even though it's more concise. IMHO the improvements outweigh the benefit in this case.

## Alternatives
[alternatives]: #alternatives

An alternative to jump filters is the already somewhat discussed guard statement as discussed in #11562. The guard statement would solve the issues mentioned above only in certain cases though (checks on method entry). 

Some existing (and declined) proposals also focused on the return statement only, whereas I think a general solution for all jump statements would benefit the language more and keeps them aligned to each other.

Last alternative is do nothing at all, since it's only syntactic sugar for existing features.

## Related issues
[related]: #related
Guard Statements and conditional if statements #138 #325 #1368 #2966 #3242 #11562

Similar issues have been discussed before. As mentioned above, I think guard statements have a much more precise scope, making them not applicable in many of the situations where jump statements appear behind a condition. Similarly, allowing jump filters only on return statements would make them behave differently then other jump statements and introduce a weird asymmetry. Even though these were mostly closed, I strongly believe that a general jump filter could improve the language, allowing developers to write code which is more focused on the actual business logic instead of boilerplatey checks that clutter their code.

Not an Issue as it happened too lang ago, but the exception filters as the spiritual parent of this proposal.

**Comment by HaloFour** [comment]
https://github.com/dotnet/csharplang/issues/2966

**Comment by 333fred** [comment]
Closing as a duplicate.
