### ISSUE TITLE
Pattern matching selector

### ISSUE THREAD

**Issue by Logerfo** [dotnet/csharplang#449]
Currently, C# permits simplifying LINQ-ish selectors by only writing the method name, and the rest can be inferred, as shown below. I'd like to propose some sort of simplification to the new pattern matching stuff:

```C#
someCollection.Where(x => SomeMethod(x)); //ugly
someCollection.Where(SomeMethod); //awesome
someCollection.Where(x => x is SomeClass _); //ugly
someCollection.Where(is SomeClass _); //my proposal
```

**Alternatives:**
```C#
bool IsSomeClass(object x) => x is SomeClass _;
someCollection.Where(IsSomeClass);
``` 
```C#
Func<object, bool> IsSomeClass = x => x is SomeClass _;
someCollection.Where(IsSomeClass);
```

Would that be achievable? Thanks.

**Comment by jnm2** [comment]
What's wrong with `someCollection.OfType<SomeClass>()`?

**Comment by HaloFour** [comment]
See #91.  It's similar although I propose the use of some sigil to clarify that the expression represents a delegate.  Otherwise you're looking for the compiler to recognize expressions that are missing an initial operand?

**Comment by svick** [comment]
@jnm2 I think `.OfType<SomeClass>` is actually significantly better, because it returns `IEnumerable<SomeClass>`, not `IEnumerable<object>`, like `.Where(is SomeClass _)` would.

**Comment by Logerfo** [comment]
@svick it's not better if you're working with method hiding or explicit interface implementation.

@HaloFour nice one, it solves a bunch of similar cases, but I don't see why the case I'm presenting would need a sigil, although the `is` operator would need to have some _non-beaking_ changes.

**Comment by HaloFour** [comment]
@Logerfo 

The use of something like a sigil opens it up to all sorts of other expressions, not just `is`.  My preference would be to seek an expression form that can satisfy as many simplified cases as possible.

I do believe that pattern matching in the context of LINQ will be quite important, although the method syntax is likely to remain permanently limited due to the scoping of any introduced identifiers.

**Comment by Logerfo** [comment]
@jnm2 besides what I pointed to @svick, your suggestion does not solve other cases like `TakeWhile`, for instance.

**Comment by Logerfo** [comment]
@HaloFour I understand. What i meant is that if your proposal gets done, mine would be a simplification of yours for this specific case.

**Comment by CyrusNajmabadi** [comment]
I'm also with those who think ```.OfType<SomeClass>``` is more appropriate here.

**Comment by Logerfo** [comment]
I think you didn't get the intention of my proposal, I'm sticking with #91 because it covers many more scenarios anyway.

**Comment by jnm2** [comment]
@Logerfo 

Your proposal didn't lead to `TakeWhile` in any obvious way that I saw. Putting the "real" use cases in the proposal would help us grasp the intention of the proposal.
