### ISSUE TITLE
[Proposal]: Inlined enumeration as function argument expression

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/csharplang#4530]
# Inlined enumeration as function argument expression

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

This syntax should provide a faster way to call a function for each element in an enumerable object.

## Motivation
[motivation]: #motivation

The main motive behind this syntax is simplifying the code that is required to properly enumerate through a collection of objects and only call one function within. In other words, this aims to simplify the process of performing a single operation on a collection of objects.

## Detailed design
[design]: #detailed-design

Assuming that an operation is performed like so:
```csharp
foreach (var x in items)
    Function(x);
```
the new syntax simplifies this code into:
```
Function(foreach in items);
```

This skips the need for introducing a temporary variable into the mix, as its only purpose is to be used once.

---

For functions with multiple arguments, the `foreach in` statement should be placed before the collection whose iterated elements are intended to be used as an argument at the desired position. For instance:
```csharp
foreach (var x in items)
    Function(1, x);
```
becomes:
```
Function(1, foreach in items);
```

---

Multiple `foreach in` can be allowed per single function call, but it becomes the equivalent of nesting each `foreach` loop in each other. Example:
```csharp
foreach (var x in itemsX)
    foreach (var y in itemsY)
        Function(x, y);
```
becomes:
```
Function(foreach in itemsX, foreach in itemsY);
```

---

Multiple `foreach in` can also be present in `params` args. Example:
```csharp
// assume the function:
void Register(params Item[] items);

// usage code:
foreach (var x in itemsX)
foreach (var y in itemsY)
foreach (var z in itemsZ)
foreach (var w in itemsW)
    Register(x, y, z, w);
```
becomes:
```
Register(foreach in itemsX, foreach in itemsY, foreach in itemsZ, foreach in itemsW);
```

---

Nested and chained function call expressions are also supported.
An example of a chained function call expression:
```csharp
foreach (var c in chars)
    stringBuilder.Append(c).Append(' ');
```
becomes:
```csharp
stringBuilder.Append(foreach in chars).Append(' ');
```

And an example of a nested function call expression:
```csharp
foreach (var loc in locations)
    Register(Invert(loc));
```
becomes:
```csharp
Register(Invert(foreach in locations));
```

---

There is also the ability to apply this for `IAsyncEnumerable` objects, by using the `await foreach in` variant. Example:
```csharp
await foreach (var x in items)
    Function(x);
```
becomes:
```csharp
Function(await foreach in items);
```

## Drawbacks
[drawbacks]: #drawbacks

This syntax does not break compatibility with other rules. It is however a relatively niche feature, and despite it not requiring changes outside Roslyn itself, it could not prove worthy of existing.

One issue is from supporting multiple `foreach in` in a single call, which may increase line size for cases when more than 2 are used, sacficing code readability.

## Alternatives
[alternatives]: #alternatives

Another proposed design is only offering a shorthand for:
```csharp
foreach (var x in items)
    Function(x);
```
into:
```
Function foreach in items;
```
Same conditionals apply, but this syntax only works for functions that take exactly one argument. It is not clear if nested or chained function call expressions can be supported, or what new features and syntax would have to be introduced for that to work.

## Unresolved questions
[unresolved]: #unresolved-questions

None yet.

## Design meetings

None.

**Comment by HaloFour** [comment]
IMO, this makes it painfully easy to miss the fact that an enumeration is happening and that the method is invoked multiple times.  It's also very unclear what happens in the case of a fluent API, does the method get called on the return value or on the original target?  If the latter it wouldn't work at all with immutable types.

This feels like an awful lot of voodoo and for minimal savings.  There's little appreciably different between:

```cs
Register(Invert(foreach in locations));
```

and

```cs
foreach (var loc in locations) Register(Invert(loc));
```

And it's much clearer how the latter will behave, which is much more important than saving a couple of keystrokes.

**Comment by AlFasGD** [comment]
> IMO, this makes it painfully easy to miss the fact that an enumeration is happening and that the method is invoked multiple times.

The presence of `foreach` alone should be sufficient to denote that something's being enumerated.

> It's also very unclear what happens in the case of a fluent API, does the method get called on the return value or on the original target? If the latter it wouldn't work at all with immutable type builders.

It was specifically declared that the order of the nesting and chaining is taken into account. All examples provide the relation of the current vs the proposed syntax, **without altering the result of the execution**.

> This feels like an awful lot of voodoo and for minimal savings.

It might indeed appear cluttery, but personally, putting two lines of code in one is a bigger sin. I always ensure that I break the statement in the way they should normally appear like in the provided examples.

**Comment by HaloFour** [comment]
> The presence of `foreach` alone should be sufficient to denote that something's being enumerated.

Which can easily be lost in the middle of a relatively long list of parameters.

> It might indeed appear cluttery, but personally, putting two lines of code in one is a bigger sin. I always ensure that I break the statement in the way they should normally appear like in the provided examples.

That's a style preference.  The language doesn't care if you put them on a single line or eight.  But if your intent on breaking those two statements onto multiple lines is to make it more clear that the iteration is happening then you're very unlikely to want to use a `foreach` argument modifier which makes that iteration substantially less apparently.

**Comment by AlFasGD** [comment]
> Which can easily be lost in the middle of a relatively long list of parameters.

That's true, and it is not encouraged to be used in such cases. The motivation section explains the reason well enough, discarding the need to repeat it.

> But if your intent on breaking those two statements onto multiple lines is to make it more clear that the iteration is happening then you're very unlikely to want to use a foreach argument modifier which makes that iteration substantially less apparent.

My intent is to oblige with the syntax and not convolute the line with all that information. In a standard simple `foreach` you've got the statement, which consists of a variable declaration, including its name, the enumerated collection, and the usage of the enumerated elements, usually through a function, which also declares that the temporary variable is included.

This new syntax gets rid of the declaration and naming of a temporary variable that holds the enumerated element. The produced result only consists of the action, the indication of an enumeration process and the enumerated collection. It's also flexible enough to allow other arguments to exist in the call, without invalidating the syntax in the case of a function that has more than 1 arguments.

**Comment by Youssef1313** [comment]
> This new syntax gets rid of the declaration and naming of a temporary variable that holds the enumerated element.

What about `Array.ForEach(items, Function)`?

**Comment by AlFasGD** [comment]
> What about `Array.ForEach(items.ToArray(), Function)`?

`ToArray` should be avoided for simply enumerating due to performance concerns.

LINQ does provide a `ForEach` function for `IEnumerable`, but it's still a LINQ function. Furthermore, it's also not as optimal due to the requirement of passing a delegate.
