### ISSUE TITLE
[Proposal]: make EventHandler as a IList

### ISSUE THREAD

**Issue by Banyc** [dotnet/csharplang#4535]
# Make `EventHandler` as a `IList`

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Please make `EventHandler` as a `IList` that could be `Clear()`, `Add()`, ...

## Motivation
[motivation]: #motivation

I want to clean up all the delegates that are previously assigned to a timer's `Elapsed` event. I don't want it to fire the old delegates that have had the old parameters. I want the timer to fire the newest delegate with the newest parameters.

## Detailed design
[design]: #detailed-design

Just make something like:

```csharp
public class EventHandler : IList<Delegate>
```

or

```csharp
public class EventHandler : List<Delegate>
```

## Drawbacks
[drawbacks]: #drawbacks

Might take some time to implement and test, I guess?

## Alternatives
[alternatives]: #alternatives

There are a lot of complaints around this issue. One of the examples:

- <https://stackoverflow.com/questions/91778/how-to-remove-all-event-handlers-from-an-event>

It is not easy to remember/keep track of the old delegates that have been assigned to an event handler. Make `Clear()` method could make life tons' better.

## Unresolved questions
[unresolved]: #unresolved-questions

Currently no.

## Design meetings

Currently no.

**Comment by YairHalberstadt** [comment]
This is an issue for dotnet/runtime

**Comment by Banyc** [comment]
> This is an issue for dotnet/runtime

Thanks for the extremely fast reply!

**Comment by Banyc** [comment]
@YairHalberstadt I have issued in dotnet/runtime:

<https://github.com/dotnet/runtime/issues/49595>

In the conversation, it seems to be there is a pitfall in the delegate type system. This might be an issue of C# language design. I hope both contributors can discuss the design!

Again, thanks for fast reply! I really appreciate it!

**Comment by YairHalberstadt** [comment]
@Banyc 

I would suggest opening a new discussion (not issue - those are for fully speced proposals, and should be opened by invitation from language team) suggesting a `clear` event accessor.

Thanks!

**Comment by Banyc** [comment]
@YairHalberstadt Could you convert this issue to the discussion? I cannot find the button...

Thanks!!!

**Comment by YairHalberstadt** [comment]
@Banyc I think it would be easier to open a new discussion, as the suggested solution is very different (`clear` accessor instead of making EventHandler `IList`)

**Comment by HaloFour** [comment]
Delegates are immutable so they can't really implement `IList` or implement a `Clear` method.  To "clear" a delegate field for an event you can set it to `null`:

```cs
protected void ClearMyEvent() {
    this.MyEvent = null;
}
```

**Comment by Banyc** [comment]
@HaloFour Best example to me! It seems that we need to make this mechanism apply to all event handlers. To user code, it is a decent solution, but to packages, it might be hard to implement...

Thank you for all the kind supports and advice!

**Comment by HaloFour** [comment]
@Banyc 

> It seems that we need to make this mechanism apply to all event handlers.

I don't agree that this should be exposed to all events.  That would enable outside callers to effectively clear all events for all classes, which shouldn't be their concern.  Those callers should be concerned only with managing their own subscriptions.  If a given class wants to expose the ability to clear all subscribers then they should expose a method to do so.
