### ISSUE TITLE
Allow a lambda expression with a statement body to be converted to an expression tree

### ISSUE THREAD

**Issue by maurosampietro** [dotnet/csharplang#4568]
Error CS0834 says: A lambda expression with a statement body cannot be converted to an expression tree.

So this is possible:

```c#
Expression<Func<string, bool>> example1 = str => str == "ok";`
```

But this is not possible:

```c#
    Expression<Func<string, bool>> example2 = str => 
    { 
         if( str == "ok" ) 
             return true; 

         return false
    };
```

However creating a new method and passing in the params does the trick:

```c#
    Expression<Func<string, bool>> example3 = str => RelayMethod( str );

    private bool RelayMethod( string str )
    {
        if( str == "ok" )
            return true;

        return false;
    }

```
The trick always works in any scenario so why don't we automatically generate the 'method trick' (when a lambda expression with a statement body is detected) and remove this limit?

**Comment by HaloFour** [comment]
See: https://github.com/dotnet/csharplang/issues/2545
