### ISSUE TITLE
[Proposal]: [Dedicated case for invalid value in the switch statement and expression]

### ISSUE THREAD

**Issue by tymtam2** [dotnet/csharplang#4576]
# Dedicated case for invalid value in the switch statement and expression

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Introduce special cases for the swtich statement and switch expression (`unmapped` and `?` respectively) for enums
to
handle unmapped values (as opposed to all "other mapped values") 
in order to
keep compile time ability to detect unhandled known values
because 
the current `default`/`_` solution removes compile time detection of known unhandled valus in order to handle the fact that c# enums can have invalid values. 

For example:
```
public enum Directions { Up, Down, Right, Left }
    
(...)    
var o = direction switch
{
     Directions.Up    => "vertical",
     Directions.Down => "vertical",
     _ => "horizontal",
     ? => throw new Exception($"Invalid value for direction: {direction}");
};
```

## Motivation
[motivation]: #motivation

Enums in C# are special. A variable of an enum type can hold a value that are no mapped in the enum declaration. The switch expression's and switch statement's abiltiy to detect errors at compile time is compromised because developers end up adding `_` or `default` to handle umapped values and loose the compile time warning about unhandled mapped values. Providing a dedicated case for unhandled values will create a safer, more correct code. 

## Detailed design
[design]: #detailed-design

Introduce `unmapped` for the switch statement and `?` for the switch expression applicable when switching on an enum. The `unmapped`/`_` case is invoked when the examined value is not mapped. 

Let's consider the following setup.
```
public enum Directions { Up, Down, Right, Left }
    
(...)    
var o = direction switch
{
     Directions.Up    => "vertical",
     Directions.Down => "vertical",
     Directions.Right    => "horizonal",
     Directions.Left => "horizontal",
     ? => throw new Exception($"Invalid value for direction: {direction}");
};
```

If `direction` is (Directions)5 then `?` is invoked. If the value is `Directions.Left` then `_` is invoked. 

If `?` is not provided the `_` is invoked. 

The primary use case is keeping the ability to detect unhandled cases when adding new values to enum.
```
public enum Directions { Up, Down, Right, Left, Forward, Back  } 
    
(...)    
var o = direction switch
{
     Directions.Up    => "vertical",
     Directions.Down => "vertical",
     Directions.Right    => "horizonal",
     Directions.Left => "horizontal",
     ? => throw new Exception($"Invalid value for direction: {direction}");
     // Compile time warning: Forward, Back are not handled 
};
```

Currently the default handler the error of missing handlers would not be detected until runtime:
```
public enum Directions { Up, Down, Right, Left, Forward, Back  }
    
(...)    
var o = direction switch
{
     Directions.Up    => "vertical",
     Directions.Down => "vertical",
     Directions.Right    => "horizonal",
     Directions.Left => "horizontal",
     _ => throw new Exception($"Invalid value for direction: {direction}"); // Only at runtime. So late!
};
```

## Drawbacks
[drawbacks]: #drawbacks

Code is not backward compatible. The code may slow down. 

## Alternatives
[alternatives]: #alternatives

Allow first calls, in code, acknowledment of 
`Warning CS8509 The switch expression does not handle all possible values of its input type (it is not exhaustive). For example, the pattern '...' is not covered.`

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by YairHalberstadt** [comment]
I think this is definitely an interesting idea. There are some things which will need clarification:

1. Currently everything acceptable in a switch expression is also a valid pattern. So I think this should be a pattern rather than specifically for a switch expression.
2. What should the codegen be for this?
3. How should this handle flags enums?
4. Are we looking at unmapped values at compile time or runtime? I presume compile time, but that should ideally be called out explicitly in the proposal.

Finally DUs present a better solution to this whole problem. Is this worth doing, or should we just wait till they get implemented.

Also if this could be written in 'specese' that would be useful. Id be happy to help with that if you're not sure how to go about that.
