### ISSUE TITLE
[Proposal]: [FEATURE_NAME]

### ISSUE THREAD

**Issue by dhughes55** [dotnet/csharplang#4578]
# Backtick as Alternative Double Quote Syntax

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Currently in the C# programming language, the only way to specify a string literal is to use double quotes.  I think there should be a second option for declaring a string literal: the backtick.  JavaScript supports the backtick as part of its template literal implementation.  I think C# should allow something similar, but simpler.  Simply allow the backtick to be treated as an alternative to the double quote character when declaring a string literal.

Example:
var string1 = "This is the only way to write a string right now."
var string2 = \`With this feature, this would now be an acceptable alternative.\`

## Motivation
[motivation]: #motivation

Who has ever needed to write HTML inside a string?  Do any of these three examples look familiar to anyone?
var html = "<span class=\\\"icon phone\\\">Content\</span>\";
var html = "<span class=\'icon phone\'>Content\</span>\";
var html = @"<span class=""icon phone"">Content\</span>\";

All three are theoretically usable but each has its own flaws.  Wouldn't it be nice (and much more elegant) to be able to write this instead?
var html = \`<span class=\"icon phone\">Content\</span>\`;

## Detailed design
[design]: #detailed-design

The main use case is providing a way to not have to constantly escape string literals.  There's not much to explain in terms of the usage. The back tick would simply be treated as an alternative syntax to the double quote in pretty much any place where double quotes are allowed in the creation of string literals (with the exception of now allowing @\`string\` syntax.  This means you could do things like below:

var foo = $\`My name is {firstName}\`;

But you couldn't do the following since the compiler wouldn't know whether to treat back-to-back double quotes as one or two quotes:

var bar = @\`This however, wouldn't be allowed since it points to two different syntax techniques.\`

## Drawbacks
[drawbacks]: #drawbacks

I can't think of any good reason.  I'm not a C# expert by any means, but to my knowledge the backtick isn't reserved for any other special purpose.  That said, it's hard to imagine that this is the first time anyone has suggested this feature since there's something similar in JavaScript.  So some drawbacks may already be out there and I just don't know about them.

## Alternatives
[alternatives]: #alternatives

There's no real negative impact of not doing this other than code continuing to sometimes be less legible than it could be.

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by yaakov-h** [comment]
#4304 is already addressing the string literal escaping use-case.

**Comment by 333fred** [comment]
Closing as a duplicate. Backticks have already been suggested in the issue yaakov linked, so I'd prefer to keep discussion there.
