### ISSUE TITLE
Discussion: Highlight branching keywords in IDEs

### ISSUE THREAD

**Issue by lachbaer** [dotnet/csharplang#458]
## Summary
All branching keywords like `break`, `continue`, `goto` and most of all `return` should be highlighted in a different color as the standard keyword color.

In Visual Studio and VS Code my suggestion is violet instead of blue.

## Motiviation
Branch points should be visible in a method without any further ado for the reader. No marking of one keyword and get all equivalent keywords highlighted should be required.

## Variations
`break`s in `switch` statements are expected and belong to the constructs normal appearance. They could be kept in the standard highlight color.

![branchhighlight](https://cloud.githubusercontent.com/assets/17041498/25178869/e144d2ba-2507-11e7-94bc-02f106b79de6.png)

**Comment by orthoxerox** [comment]
@lachbaer Shouldn't this be in the roslyn repo? It's not really a language design issue, is it?

**Comment by lachbaer** [comment]
@orthoxerox I wasn't sure. Do you think I should post it there are well?

**Comment by HaloFour** [comment]
This repo concerns changes to the language itself.  Implementation of those changes in the compiler and any tooling belong in Roslyn.

I'm going to assume that Roslyn already classifies said statements in a way that would enable the IDE to differentiate between them.  It's just a matter of adding their classification to the Fonts and Colors preferences.  The only other Roslyn issue on the subject is https://github.com/dotnet/roslyn/issues/3976 which references a greater body of work called "symbol specification" (for which I could not find an issue).

**Comment by bigown** [comment]
`if` is branching, `foreach` is branching, many keywords branching.

**Comment by lachbaer** [comment]
@bigown I - obviously - mean the mentioned statements 😶 😶 😶

**Comment by lachbaer** [comment]
Moved to dotnet/roslyn#18810
