### ISSUE TITLE
[ExcludeFromCodeCoverage] attribute not available on method generated from excluded method

### ISSUE THREAD

**Issue by jakubch1** [dotnet/csharplang#4826]
Scenario is:
Method
```
        [ExcludeFromCodeCoverage]
        public async Task TestExcludedAsyncFunction()
        {
            await Task.Delay(1).ConfigureAwait(false);
        }
```

will generate class: `.class nested private auto ansi sealed beforefieldinit '<TestExcludedAsyncFunction>d__2'` which doesn't have any ExcludeFromCodeCoverage attribute so coverage tools will instrument and show coverage for it. We were trying to find ordinal number `2` on initial method but we fail using Microsoft.Reflection.Metadata, so we can't match those 2 methods.

Very similar issue we see for local methods, methods with yield, lambda. Could you please preserve `ExcludeFromCodeCoverage` attribute in such cases?

Related issue:
https://github.com/microsoft/vstest/issues/2658

**Comment by jaredpar** [comment]
Moving to csharplang. How the attributes apply to generated code is generally driven by C# LDM (it's a gray area but considered part of the language design). Would need to get a language change here to change the compiler behavior. 

@MadsTorgersen FYI
