### ISSUE TITLE
Issue compiling C# project: Unrecognized option: /deterministic

### ISSUE THREAD

**Issue by rich0726** [dotnet/csharplang#4856]
Hello!
Recently I've started having trouble compiling a C# based web application in VS2019.  The same issue is happening in multiple versions of VS2019, as far back as 16.4, and as far forward as 16.11 Preview 2.  I'm thinking my project file got corrupted somehow, because this is happening on multiple machines.

The error is CS2007, reported by CSC, and reads "Unrecognized option: /deterministic+"

This occurs whether or not I explicitly declare deterministic in the PropertyGroup in my .csproj file, and whether or not I set it to true or false.

Note that prior to this, I was getting an error saying that Debugging information setting couldn't be set to "portable", and that I'd have to use full or pdbonly.  I change to Full, and now I get this error.

Any help is greatly appreciated!

**Comment by alexrp** [comment]
This probably belongs on [dotnet/sdk](https://github.com/dotnet/sdk).

Please share your project file and the output of `dotnet --info`.

**Comment by rich0726** [comment]
We can close this.  After much experimentation, I realized that the error message was a red herring, caused by an unresolved assembly reference.  Not sure why pre-compile didn't pick that up, but alas, I'm good to go.
