### ISSUE TITLE
[Proposal]: allow using `namespaces` without curly braces

### ISSUE THREAD

**Issue by ikourfaln** [dotnet/csharplang#4874]
# allow using `namespaces` without curly braces

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary

We are heavily using Namespaces to organize and control the scope of classes and method names in larger programming projects.

## Motivation

Minimize the code you have to write

## Detailed design
Examples:

Currently:

```cs
namespace SampleNamespace
{
    class SampleClass
    {
        public void SampleMethod()
        {
            System.Console.WriteLine("SampleMethod inside SampleNamespace");
        }
    }
}
```

Proposed:

```cs
namespace SampleNamespace

class SampleClass
{
    public void SampleMethod()
    {
        System.Console.WriteLine("SampleMethod inside SampleNamespace");
    }
}
```

**Comment by bernd5** [comment]
already proposed and implemented, see: https://github.com/dotnet/csharplang/blob/3c8559f186d4c5df5d1299b0eaa4e139ae130ab6/proposals/csharp-10.0/file-scoped-namespaces.md

**Comment by ZacharyPatten** [comment]
https://github.com/dotnet/csharplang/issues/137 is already a proposed feature and is included in the https://github.com/dotnet/roslyn/blob/main/docs/Language%20Feature%20Status.md feature tracker as "File-scoped namespace".

**Comment by CyrusNajmabadi** [comment]
Closing out as already proposed and being implemented for C# 10.
