### ISSUE TITLE
[Proposal]: Multiple top-level statement compilation units

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#4899]
# Multiple top-level statement compilation units

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Today, the language allows only one top-level compilation units because only one entry-point should be generated. This proposal allows multiple top-level compilation units with a restriction described below.

## Motivation
[motivation]: #motivation

Writing top-level statement programs is a very neat feature. However, things get a bit messy when the file becomes large, usually due to multiple local functions being declared.

## Detailed design
[design]: #detailed-design

This simply lift the restriction and allows multiple top-level files if and only if exactly one of these files contain non-`LocalFunctionStatement` global statement. So, for example, allow the following:

```csharp
// File1.cs
Console.WriteLine("Hello, world");

// File2.cs
void M() { }
```

but, disallow the following:

```
// File1.cs
Console.WriteLine("Hello, world");

// File2.cs
Console.WriteLine("Hello, world 2");
```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by 333fred** [comment]
We intentionally did not do this to keep the design space for generalized top-level functions open.

**Comment by Youssef1313** [comment]
> We intentionally did not do this to keep the design space for generalized top-level functions open.

Can you provide more details on that please? Thanks.

**Comment by 333fred** [comment]
https://github.com/dotnet/csharplang/blob/main/meetings/2020/LDM-2020-03-09.md#simple-programs

**Comment by Youssef1313** [comment]
I'm closing as this is unlikely to move forward per the previous LDM conclusion.
