### ISSUE TITLE
Global or Default Namespace Statements

### ISSUE THREAD

**Issue by Turpy** [dotnet/csharplang#4907]
Similar to the new global using statements, it would be nice if there was an option for a global namespace that could be set for a project so that if a namespace was not declared in a file then it would default to this global namespace. 

If a namespace was provided then it would override the globally set namespace.

Also, it would be nice if there was a directory structure for source files underneath the top level directory for the project then the name of the directory can be appended automatically to the project level global namespace - again if none are provided in that file.

**Comment by CyrusNajmabadi** [comment]
> then the name of the directory can be appended automatically to the project level global namespace - again if none are provided in that file.

Just an FYI, but we are very unlikely to do either of these as we are generally loathe to have the project file have impact on the meaning of code, or how the metadata for symbols is generated.

**Comment by jnm2** [comment]
Moving to a discussion as requested in the issue selector and the issue template.
