### ISSUE TITLE
Improve resolution of 'new expressions' for params

### ISSUE THREAD

**Issue by kofifus** [dotnet/csharplang#4940]
### Discussed in https://github.com/dotnet/csharplang/discussions/4939

<div type='discussions-op-text'>

<sup>Originally posted by **kofifus** July 18, 2021</sup>
Consider:

```
class MyList<T> {
  public MyList(params T[] ts) { /* add all items to internal list */ }
}

record Employee(string Name, int Age);

var l1 = new MyList<Employee>(new Employee("John", 30));   // ok

var l2 = new MyList<Employee>(new("John", 30));  // error CS8752: The type 'Program.Employee[]' may not be used as the target type of new()

var l3 = new MyList<Employee>(new("John", 30), new("Eric", 30)) // ok;
```

If my understanding is correct, the reason for the error in l2 is that according to the standard: 
>A target_typed_new expression does not have a type. However, there is a new object creation conversion that is an implicit conversion from expression, that exists from a target_typed_new to every type.

However in this case I believe the compiler can be improved to detect that the new expression needs to be a new `Employee` and not `Employee[]`

Thanks

</div>

**Comment by svick** [comment]
[Per the readme](https://github.com/dotnet/csharplang/blob/f05a7cd/README.md#proposals), an issue should be opened only for a "fully fleshed out proposal". Since this is not that and since a discussion already exists, I'm going to close this issue.

**Comment by kofifus** [comment]
@svick apologies I didn't realise that thanks
