### ISSUE TITLE
Proposal: Allow conditional operator `? :` under 'void' conditions

### ISSUE THREAD

**Issue by lachbaer** [dotnet/csharplang#495]
This proposal is **syntactic sugar**.

Instead of writing
```cs
public void Construct() {
    if (!_is_initialized)
        (_denominator, _scale, _struct_initialized) = (1d, 1d, true);
    else
        throw new InvalidOperationException();
}
```
it would be nicer to compress this to
```cs
public void Construct() =>
     (!_struct_initialized) ?  (_denominator, _scale, _struct_initialized) = (1d, 1d, true) 
                            :  throw new InvalidOperationException();
```
This would also allow using it in void lambdas. Instead of writing
```cs
List<Fraction> list = new List<Fraction>() { ... };
list.ForEach((item) => {
    if (!item._struct_initialized) item.Construct();
});  // company style: we shall not write {} blocks in one line.
```
it will look more "lambda typical"
```cs
List<Fraction> list = new List<Fraction>()  { ... };
list.ForEach( (item) => (! item.IsInitialized) ? item.Construct() : void );
```
*(Sample makes use of of #135 and uses a `void` as return value)*

**Comment by jnm2** [comment]
If it was possible, I'd use  
`list.ForEach(item => if (!item.IsInitialized) item.Construct());` rather than  
`list.ForEach(item => !item.IsInitialized ? item.Construct() : void);` because I find it more readable.

**Comment by lachbaer** [comment]
> If it was possible,

But it isn't. ;-) Don't lambdas without blocks have *expressions* instead of *statements*? That's why I had this form in mind. For this proposal I assumed that an expression form is mandatory in case of `=>`. Also, the foreach just came into my mind as an example of llambdas, while arbitrarily searching for one (to just show the "look" of it).

I'm currently on the side experimenting with that `Fraction` struct (#99) in several ways to valuate guard code, copy-constructors, syntax changes, etc. And while writing guard code I somehow typed zombie like that `(!_struct_initialized) ?  ...`. Obviously that didn't work, but sometimes good ideas just pop up subconsciously :wink:

**Comment by HaloFour** [comment]
@lachbaer 

> Don't lambdas without blocks have expressions instead of *statements*?

They can be void expressions:

```cs
list.ForEach(i => Console.WriteLine(i));
```

But `if` and most other control statements cannot be used in such expressions.

That said, I don't see a lot of benefit to the alternative form you proposed above.  I find the actual `if` statement to be much cleaner and easier to read.  The expectation of the ternary conditional operator is that it would produce a value, not strictly cause side effects.

**Comment by lachbaer** [comment]
> They can be void expressions:

Yes, that's the idea behind `() => (! item.IsInitialized) ? item.Construct() : void `, it makes use of existing features.

> The expectation of the ternary conditional operator is that it would produce a value, not strictly cause side effects

I think that it is also absolutely legitimate to see `cond ? x : y` as an expression form of
`if (conditon)` x else y` with x and y itself being further expressions that have the same return type. Then adding a `void` return type as implied on #135 will lead to this proposal.

**Comment by mburbea** [comment]
This is already legal and completely hideous.
```csharp
public class Foo{
    public string X{get;}
    public Foo(string x){
          X = x != null ? x : throw new ArgumentNullException(nameof(x));
    }
}
```

As for the returning void thing, I don't think it adds much value besides a reduction in syntax and could lead to confusion. One-liner lambda conditionals, where half isn't used doesn't add much value.

**Comment by lachbaer** [comment]
The return type of
```cs
x=> x > 5 ? x.ToString() : void
```
is "`void`", i.e. that it is illegal for `Select`. This proposal is really strongly related to #135.

**Comment by jnm2** [comment]
@lachbaer 

> > If it was possible,
> 
> But it isn't. ;-) 

It's exactly as possible as your proposed syntax. I'm just saying, if we're changing the language, I find this one more readable.

@mburbea Matter of opinion for sure. I kinda like this too which does the same thing: `X = x ?? throw new ArgumentNullException(nameof(x));`

**Comment by DavidArno** [comment]
@mburbea,
> This is already legal and completely hideous...

I agree. Here, I've fixed it for you:
```cs
public class Foo
{
    public string X {get;}
    public Foo(string x) => X = x ?? throw new ArgumentNullException(nameof(x));
}
```

I have to confess that I'm confused how this related to the thread topic though.

**Comment by mburbea** [comment]
The example in the op shows this. Matter of opinion, I think using `X = x ?? throw new ...` is very ugly and easy to miss.

**Comment by DavidArno** [comment]
@lachbaer,

It's worth bearing in mind that both of your examples can be expressed without if statements already.

Example 1:
```cs
public void Construct() =>
    (_denominator, _scale, _struct_initialized) = !_struct_initialized 
        ?  (_denominator, _scale, _struct_initialized) = (1d, 1d, true) 
        :  throw new InvalidOperationException();
```

Example 2 (using `ToUnitFunc` from [Succinc&lt;T&gt;](https://github.com/DavidArno/SuccincT/blob/master/src/SuccincT/Functional/ActionExtensions.cs)):
```cs
var list = new List<Fraction>() { ... };
list.Where(item => !item._struct_initialized)
    .Select(item => ToUnitFunc(item.Construct)());

**Comment by bondsbw** [comment]
@HaloFour 
> But `if` and most other control statements cannot be used in such expressions.

That sounds like the real issue, maybe it should be addressed instead of creating new syntax just to provide a workaround.

**Comment by lachbaer** [comment]
@mburbea 
> Matter of opinion, I think using X = x ?? throw new ... is very ugly and easy to miss.

Yes, I definitely like it and use it in verifying setter values: `set => backingField = value ?? throw ...`

**Comment by lachbaer** [comment]
> instead of creating new syntax just to provide a workaround.

I disagree that it is a "workaround". My personal experience with the `? :` construct - in the meaning of practical using - is that it is *kind of * a shortcut for `if-else`.

Don't you actually read it literally as "if condition then return else return"? At least all programming tutorials and books basicaly explain it this way.

That's why I think it would *also* perfectly deal as an expression syntax `if-else` construct.

**Comment by lachbaer** [comment]
@DavidArno 
> It's worth bearing in mind that both of your examples can be expressed without if statements already

Yes, it could. As could so many million other cases where nevertheless syntacic eases were introduced. I came up with this proposal, because I *really* typed that construct thoughtlessly. That only shows how differently human brains think => **human factors** (might have seen that expression from me somewhere else already 😉 )

The whole discussions about *sugar*, and the plain existence of further languages other to C(#) is substanciated by the need to satisfy different ways of thinking, different ways of approaching a solution.

Unfortunately mainly only a few well known members engage in these discussions here. Therefore the pool of opinions in contrary to the opions in the wilderness out there is quite limited and not representative.

That said, I think that my proposal is *absolutely* justifiable considering my flow of thoughts when programming.

**Comment by bondsbw** [comment]
@lachbaer 
> Don't you actually read it literally as "if condition then return else return"?

Right, so:

`if (!item.IsInitialized) item.Construct()` says "If item is not initialized, then call Construct()."

`!item.IsInitialized ? item.Construct() : void` says "If item is not Initialized, then return the nothing result of calling Construct(), else return nothing."

I stand by my statement that it is a workaround for the original intent.

**Comment by aluanhaddad** [comment]
@bondsbw 
> @HaloFour
> 
> But if and most other control statements cannot be used in such expressions.
> 
> That sounds like the real issue.  Maybe that should be addressed instead of creating new syntax just to provide a workaround.

I believe @alrz already presented a fairly detailed proposal for this some time ago.

@lachbaer Would you be willing to offer some other use case? That code looks really ugly. I mean why is the caller checking to see if an object is initialized and then conditionally calling a `Construct` member? The whole thing looks like it could be encapsulated inside of the object and even wrapping it in an extension method would improve readability regardless of the proposal.

I can sort of relate to wanting a shorthand form of a conditional with only one branch but the example does not sell me on it.

**Comment by lachbaer** [comment]
@aluanhaddad 
The sample arose from a fraction `struct`. As you know, a `struct` can have a non-initialized state. I tried to create some guard-statements on the members to ensure initialisation somehow. I mostly use basic constructs and I like compact blocks or "one-liners". That is just my current style of coding.

**Comment by Thaina** [comment]
If `Fraction` is struct then foreaching `List<Fraction>` and construct cannot change really construct inside the list. that foreaching function is not pass by ref

If it is a class we could

```C#
list.ForEach((item) => !(item.IsInitialized ? null : item).Construct());
```

If it struct and pass by ref then, well, I was propose #494 and it could be used in this case the same as class

**Comment by Thaina** [comment]
But actually what I think about this case is. We should just use `where`

```C#
list.WhereRef((ref item) => !item.IsInitialized).ForEach((ref item) => item.Construct());
```

**Comment by yaakov-h** [comment]
Why would you construct a fraction inside a list? Why not add constructed fractions to the list?

**Comment by lachbaer** [comment]
@Thaina 
> If Fraction is struct then foreaching List<Fraction> and construct cannot really construct inside the list. 

You are abolutely right. And unfortunately there currently is no `ForEach(RefAction<T> action)` as far as I could see. This makes the sample obliterate somehow.

The for the further discussion let's assume *a construct like* - i.e. **not** the concrete problem 
```cs
// hypothetical Connection class
list.ForEach( (connection) => (!connection.State != State.Open) ? connection.Open() : void )
```

@yaakov-h 
> Why would you construct a fraction inside a list? Why not add constructed fractions to the list?

Because `Fraction` is shall be a value type and assume the initialization of the list as being given 
```cs
var fracList = new Fraction[100].ToList();
foreach (ref var item in fracList) item.Construct();
```
because that reads nicely, in my opionon - i.e. for peoples whos mind flow is as mine (*human factors*) - it is more expressive than
```cs
var fracList = new List<Fraction>(100);
for (int i=100; i>0; --i) {
    var temp = new Fraction();
    temp.Construct()
    fracList.Add(temp);
}
```
besides there currently is no `foreach(ref` (worth another proposal!).

I want to **emphasize** that this proposal and discussion is solely to extend `? :` to `void` environmental conditions as an alternative syntacic expression way of `if (condition) then [return] x else [return] y`. A prerequirement being the possibility of returning `void`, as proposed elsewhere.

This is **not** about a concrete problem on how to realize a `foreach`.

Imagine returning `void` would be possible. *Then* it would only be logical to have `? :` this way, wouldn't it?

I nevertheless like the idea of allowing basic flow statements (`if`, `switch`, `for`, `do`, `while`, etc.) in lambda expressions *very much*! ❤️ Though not in expression-bodied members. That's what blocks are for ;-)

**Comment by lachbaer** [comment]
This is rather part of the matter of #135.
The basic idea here has no support.

Allowing basic flow statements (`if`, `switch`, `for`, `do`, `while`, any more?) in lambda expressions is already possible by wrapping them in braces. Eliminating the braces would be nice, but I doubt that the team is willing to do that just two save to characters and space.
