### ISSUE TITLE
nameof should support Byte[]

### ISSUE THREAD

**Issue by kelicto** [dotnet/csharplang#5007]
``` C#
/// <summary>
///     Convert the object to a SqlDbType.
/// </summary>
/// <param name="obj"></param>
/// <returns></returns>
public static SqlDbType ToSqlDbType(object obj)
{
    if (obj is null)
        throw new ArgumentNullException(nameof(obj));

    var result = SqlDbType.NChar;
    var type = obj.GetType();

    result = type.Name switch
    {
        nameof(Boolean) => SqlDbType.Bit,
        nameof(Byte) => SqlDbType.TinyInt,
        nameof(Int16) => SqlDbType.SmallInt,
        nameof(Int32) => SqlDbType.SmallInt,
        nameof(Single) => SqlDbType.Real,
        nameof(Double) => SqlDbType.Float,
        nameof(String) => SqlDbType.NChar,
        nameof(Guid) => SqlDbType.UniqueIdentifier,
        nameof(XmlReader) => SqlDbType.Xml,
        nameof(Decimal) => SqlDbType.Money,
        nameof(DateTime) => SqlDbType.DateTime2,
        "Byte[]" => SqlDbType.Binary,
        nameof(Object) => SqlDbType.Variant,
        _ => result
    };

    return result;
}
```

**Comment by CyrusNajmabadi** [comment]
This isn't really how you'd want to write code.  For example, if i had a `Foo.Boolean` it would match your first case, despite not actually being that type.  This was also a problem with your original code where you tried to do `nameof(List<int>)` wchih really is just going to not be waht you want.

**Comment by theunrepentantgeek** [comment]
Why don't you write this using pattern matching? 

I think something like this would work - and would have greater typesafety than making everything stringly typed:

``` csharp
public static SqlDbType ToSqlDbType(object obj)
{
    if (obj is null)
        throw new ArgumentNullException(nameof(obj));

    var result = SqlDbType.NChar;
    var type = obj.GetType();

    result = obj switch {
        bool => SqlDbType.Bit,
        byte => SqlDbType.TinyInt,
        short => SqlDbType.SmallInt,
        float => SqlDbType.Real,
        double => SqlDbType.Float,
        string => SqlDbType.NChar,
        Guid => SqlDbType.UniqueIdentifier,
        XmlReader => SqlDbType.Xml,
        Decimal => SqlDbType.Money,
        DateTime => SqlDbType.DateTime2,
        byte[] => SqlDbType.Binary,
        _ => SqlDbType.Variant,
    };
    
    return result;
}
```

**Comment by kelicto** [comment]
> This isn't really how you'd want to write code. For example, if i had a `Foo.Boolean` it would match your first case, despite not actually being that type. This was also a problem with your original code where you tried to do `nameof(List<int>)` wchih really is just going to not be waht you want.

Yeah. I only want to test, accidentally submitted.

**Comment by kelicto** [comment]
> 你为什么不使用模式匹配来写这个？
> 
> 我认为这样的事情会起作用 - 并且比将所有内容都输入字符串具有更大的类型安全性：
> 
> ```cs
> public  static  SqlDbType  ToSqlDbType ( object  obj ) 
> { if ( obj is null )
>          throw new ArgumentNullException ( nameof ( obj )); var结果= SqlDbType。字符；
>     无功类型= obj。获取类型(); 结果= obj switch { 
>         bool => SqlDbType。位，
>         
> 
>           
> 
>         
>         字节=>  SqlDbType。TinyInt，
>         短=>  SqlDbType。SmallInt，
>         float =>  SqlDbType。Real , 
>         double =>  SqlDbType。浮点数，
>         字符串=>  SqlDbType。NChar , 
>         Guid =>  SqlDbType。UniqueIdentifier , 
>         XmlReader =>  SqlDbType。Xml，
>         十进制=> 数据库类型。Money , 
>         DateTime =>  SqlDbType。DateTime2 , 
>         byte[] =>  SqlDbType。二进制，
>         _ =>  SqlDbType。变体, 
>     }; 返回结果；
> }
>     
>      
> ```

Yeah. But, I cannot use it. It's a project on .net Framwork. I don't know why you can work.

**Comment by kelicto** [comment]
I know I can use the way to solve the problem. I still want C# can support `array` type. Because, It's very useful to me!

**Comment by yaakov-h** [comment]
if you’re still on .NET Framework then you probably won’t be making any use of new language improvements until you can modernise. The earliest any new features not already in development could possibly be available is .NET 7.

**Comment by kelicto** [comment]
> if you’re still on .NET Framework then you probably won’t be making any use of new language improvements until you can modernise. The earliest any new features not already in development could possibly be available is .NET 7.

Because, My project's SDK only provider .NET Framework version.

**Comment by 333fred** [comment]
Closing in favor of the discussion https://github.com/dotnet/csharplang/discussions/5006.
