### ISSUE TITLE
Null-propagating operator ?. in Expression Trees

### ISSUE THREAD

**Issue by NetMage** [dotnet/csharplang#503]
Expression Trees should be extended to support the C# 6.0 null propagating operator so that it can be used with Linq, with a translation to allow providers such as Linq to SQL to work.

The discussion on CodePlex doesn't seemed to have moved over to here, and has been sitting around for 3 years - I think it is worth revisiting, and ideally implementing. An ideal use case is an Outer Join in Linq to Objects.

[https://roslyn.codeplex.com/discussions/571077](url)

**Comment by jnm2** [comment]
Yes. It has been far, far too long.

**Comment by jnm2** [comment]
This may be covered by https://github.com/dotnet/csharplang/issues/158.

**Comment by NetMage** [comment]
Good point.

**Comment by NetMage** [comment]
I copied to other issue and will close this issue.

**Comment by leandromoh** [comment]
While expression trees does not support the C# 6.0 null propagating, what we can do is create a visitor that modify expression tree for safe null propagation (just like the operator does)!
  
Check this gist [NullPropagationVisitor.cs](https://gist.github.com/leandromoh/92bec4eddbacb1b20f4a67cd5ac6a081)
