### ISSUE TITLE
Improve generic to support IHttpActionResult<T>

### ISSUE THREAD

**Issue by rxdeveloper** [dotnet/csharplang#509]
Web API 2 does recommends to returns IHttpActionResult for all action methods, but it does not support IHttpActionResult<T>. This make the action method's signature is less readable. After researching the internet I found out the reason is said that IHttpActionResult<T> is not supported because it's not type-safe, but that reason is not reasonable to me.

I wonder if it's a limitation of C#'s generic implementation?

**Comment by HaloFour** [comment]
What does this have to do with C# the language?  If you have an issue with Web API 2 the framework perhaps you should take it up on their repo?  Unless they come back with a specific reason around how generics work in .NET (which would still not be a C# issue) this doesn't belong here.
