### ISSUE TITLE
Open issues for lambda expression and method group type inference

### ISSUE THREAD

**Issue by cston** [dotnet/csharplang#5095]
## Open issues for lambda expression and method group type inference

---
### Best common type should use conversions from expressions
Best common type currently considers the conversions from _types_ of the expressions, ignoring untyped expressions, rather than using conversions from the _expressions_.

_Proposal: Consider conversions from expressions if one or more of the expressions is a lambda expression or method group._

```csharp
delegate int StringIntDelegate(string s);
static int StrLength(string s) => s.Length;

var a1 = new[] { (StringIntDelegate)StrLength, (string s) => int.Parse(s) };
var a2 = new[] { (string s) => s.Length, (string s) => int.Parse(s) }; // error CS0826: No best type
```

---
### Better function member should prefer overloads where arguments use existing conversions
_Proposal: Prefer overload candidates where arguments with C#9 conversions over arguments with function type conversions._

```csharp
static void F(object obj, Action callback) { }
static void F(int i, Delegate callback) { }

// C#9: F(object, Action)
// C#10: ambiguous
F(0, () => { });
```

---
### Conversion to `object` for method group may be a source of errors
Allowing implicit conversion of method group to `object` means mistakes where a method is referenced but not invoked are no reported as errors at compile-time.

_Proposal: Change conversion of method group or lambda expression to `object` to an explicit conversion only._

```csharp
static object GetValue() => 0;
// C#9: error CS0428: Cannot convert method group to 'object'. Did you intend to invoke the method?
// C#10: ok
object obj = GetValue;
```

**Comment by 333fred** [comment]
Discussed in LDM on 8/23/21: https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-08-23.md#lambda-expression-and-method-group-type-inference-issues.
