### ISSUE TITLE
Discussion: Init Method for constructor call only.

### ISSUE THREAD

**Issue by steve-goulding** [dotnet/csharplang#5103]
Sometimes I find myself writing code in a constructor that initialises a class level variable and would rather it was contained in its own descriptive method.   
However this then means that the variable can't be made readonly and the method could be called elsewhere in the class.
It would be nice if there was an _init_ keyword for a method which 
a) enforced calls only from a constructor
b) you could set readonly properties and init property setters from within it.

**Comment by quinmars** [comment]
See #4704.
