### ISSUE TITLE
Simplifying multiple strings in the parameter. 

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/csharplang#5116]
### Background and motivation

I have often seen in source codes that many people repeat methods in an if statement very often, it would be much easier if you had the `||` operator in the parameter of the function. 

### API Proposal

**Current Situation**

```C#
namespace Test
{
     public class Main(string[] args)
     {
           string myText = "I m a Star";
           
           if(myText.Contains("Star") || myText.Contains("a") || myText.Contains("I")) {
                Console.WriteLine("It contains");
            }
     }
}
```     
**Simplify**

```C#
namespace Test
{
     public class Main(string[] args)
     {
           string myText = "I m a Star";
           
           if(myText.Contains("Star" || "a" || "I")) {
                Console.WriteLine("It contains");
            }
     }
}
```     

### API Usage

```cs
// Simplifying the repeat of methods in a If statement.
string.Contains("first string" || "second string" || "another string");
````

**Comment by HaloFour** [comment]
I understand the behavior that you're looking for but to me it doesn't make sense to try to achieve that by operators.

The order of operations within an expression `Contains("foo" || "bar")` is that the expression `"foo" || "bar"` is evaluated first into a single value, and then that value is passed once as an argument to the method `Contains`.  That is how that form of expression is always evaluated today and it already compiles for any two operands that support the operator.

**Comment by 333fred** [comment]
This is extremely similar to https://github.com/dotnet/csharplang/discussions/5082, so I'm going to close this and redirect further conversations there.
