### ISSUE TITLE
Should lambda expression or method group be considered convertible to `MulticastDelegate` if the delegate type cannot be inferred?

### ISSUE THREAD

**Issue by cston** [dotnet/csharplang#5124]
Is a lambda expression or method group with no natural type considered convertible to `System.MulticastDelegate` (or base types or interfaces) or to `System.Linq.Expressions.Expression`?

Currently a lambda (or method group) is only convertible to `MulticastDelegate` etc. if the compiler can infer a delegate type. However, that means overload resolution can be affected simply by making a lambda signature explicit.

### Example 1: Ambiguous overloads

Consider the example below from https://github.com/dotnet/roslyn/issues/55691.

There are two calls to `app.Map()`. The second call - with explicit lambda parameter type – is ambiguous because the conversion to `string` is preferred over `PathString` for one parameter while the conversion to `Action<IAppBuilder>` is preferred over `Delegate` for another parameter.

Should the first call to `app.Map()` be ambiguous even though the delegate type of `builder => { }` cannot be inferred?

```csharp 
using System;
#nullable enable
 
var app = new WebApp();
app.Map("/sub1", builder => { });               // ambiguous?
app.Map("/sub2", (IAppBuilder builder) => { }); // ambiguous
 
class WebApp : IAppBuilder, IRouteBuilder { }
interface IAppBuilder { }
interface IRouteBuilder { }
 
static class AppBuilderExtensions
{
    public static IAppBuilder Map(this IAppBuilder app, PathSring path, Action<IAppBuilder> callback) => app;
}
 
static class RouteBuilderExtensions
{
    public static IRouteBuilder Map(this IRouteBuilder routes, string path, Delegate callback) => routes;
}
 
struct PathSring
{
    public PathSring(string? path) { Path = path; }
    public string? Path { get; }
    public static implicit operator PathSring(string? s) => new PathSring(s);
    public static implicit operator string?(PathSring path) => path.Path;
}
```

### Example 2: Instance and extension methods

If the `Delegate` overload is an instance method and the strongly-typed overload is an extension method, and if all lambda expressions are considered convertible to `Delegate`, the compiler will effectively ignore the extension method and simply fail binding to the `Delegate` overload if the delegate type for a lambda expression cannot be inferred.

```csharp
using System;
using static System.Console;

var w = new Widget();
w.Invoke((int arg) => { }, 1); // Widget
w.Invoke(arg => { }, 2);       // Extensions or error?

class Widget
{
    public void Invoke(Delegate d, params object[] args) { WriteLine("Widget"); }
}

static class Extensions
{
    public static void Invoke<T>(this Widget w, Action<T> action, T arg) { WriteLine("Extensions"); }
}
```

**Comment by 333fred** [comment]
This was discussed in LDM on September 1st. We will not be changing the current rules. https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-09-01.md#lambda-expression-conversions-to-delegate
