### ISSUE TITLE
[Proposal]: Add explicit self-referencing type constraint

### ISSUE THREAD

**Issue by huoshan12345** [dotnet/csharplang#5125]
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
Currently, if we want to define a generic class with self-referencing type constraint, we can do this:
```
public interface ISingleton<TSelf> where TSelf : ISingleton<TSelf>
{
    static abstract TSelf Instance { get; }
}
public class SingletonA : ISingleton<SingletonA>
{
    public static SingletonA Instance { get; } = new SingletonA();
}
```
It works well, but there is one unexpected usage:  
```
public class SingletonB : ISingleton<SingletonA>
{
    public static SingletonA Instance { get; } = new SingletonA();
}
```
The class `SingletonB` is defined legally but not reasonable cause `SingletonB` should implement `ISingleton<SingletonB>` instead of `ISingleton<SingletonA>`. It is a misuse of `ISingleton<TSelf>` and cannot be prevented.

## Motivation
To prevente the misuse of self-referencing type constraint.

## Detailed design
[design]: #detailed-design

Add a new keyword `self` to generic constraint, which restricts that the generic type must be the implement type itself.
So we can rewrite the above code as:
```
public interface ISingleton<TSelf> where TSelf : self
{
    static abstract TSelf Instance { get; }
}
public class SingletonA : ISingleton<SingletonA>
{
    public static SingletonA Instance { get; } = new SingletonA();
}
```
And the following is illegal now:
```
public class SingletonB : ISingleton<SingletonA> // compile error: type mismatch, should be ISingleton<SingletonB>
{
    ...
}
```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by 333fred** [comment]
I'm converting this to a discussion, as outlined in the README. https://github.com/dotnet/csharplang#discussions
