### ISSUE TITLE
Complaining about documentation: async method builder types

### ISSUE THREAD

**Issue by matthew-a-thomas** [dotnet/csharplang#5238]
After banging my head for hours against my broken custom async method builder, I have concluded two things are incorrect in the documentation [for builder types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/task-types#builder-type):

1. It [says](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/task-types#:~:text=AwaitUnsafeOnCompleted()%20should%20call%20awaiter.OnCompleted(action)) "AwaitUnsafeOnCompleted() should call awaiter.OnCompleted(action)", when instead it should call awaiter.UnsafeOnCompleted like Microsoft's own async method builder [does](https://github.com/dotnet/runtime/blob/v5.0.10/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs#L101)
1. It [says](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/task-types#:~:text=If%20the%20state%20machine%20is%20implemented%20as%20a%20struct%2C%20then%20builder.SetStateMachine(stateMachine)%20is%20called%20with%20a%20boxed%20instance%20of%20the%20state%20machine) "If the state machine is implemented as a struct, then builder.SetStateMachine(stateMachine) is called with a boxed instance of the state machine", when in reality that method is _not_ invoked when the state machine is a struct (or else there's some reason why none of my breakpoints and calls to `Debugger.Break()` are being hit)

And if I may complain a little bit, the documentation was not helpful at all for me figuring out why my custom async method builder worked in Debug builds or as a `class`, but didn't work in Release mode as a `struct`. In my opinion it feels like the documentation was an afterthought and isn't meant to be used by the public outside of Microsoft. So let me add:

3. It [says](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/task-types#:~:text=The%20builder%20type%20is%20a%20class%20or%20struct) "The builder type is a class or struct", but there are no warnings about the nuance of making it a `struct`

If you want to learn more about my journey through a failed attempt, and why I think "nuanced" and "hard" are good words for it, then start reading [here](https://stackoverflow.com/q/69396896/3063273).

**Comment by 333fred** [comment]
@jcouv or @BillWagner

**Comment by cston** [comment]
@matthew-a-thomas, thanks for reporting these issues. I've made corrections to the existing documentation in https://github.com/dotnet/csharplang/pull/5253.

**Comment by BillWagner** [comment]
@cston @333fred I think we can close this based on #5253 None of the other async docs discuss writing an async method builder.
