### ISSUE TITLE
Do not show error CS0075 on non-ambiguous declarations

### ISSUE THREAD

**Issue by ChrisBertrandIndus** [dotnet/csharplang#5247]
Can we get rid of this error on non-ambiguous declarations ?
So to prevent developers to add parenthesis that make code less readable.

Example 1 :

	int i = (System.Int32) -4;

Example 2 :

	Distance d = (Distance) -25.0;	

	public struct Distance
	{
		double Value;

		public static explicit operator Distance(double a) => new() { Value = a };
		public static explicit operator double(Distance a) => a.Value;
	}

I have read the [information page](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0075?f1url=%3FappId%3Droslyn%26k%3Dk(CS0075)), but still don't find it convincing on such simple and non-ambiguous cases.

**Comment by CyrusNajmabadi** [comment]
@Youssef1313  is correct.  And the code truly is ambiguous.  imagine you have something like:

```c#
    E E { get; }
    void M()
    {
        _ = (E) -4;
    }
```

is this retrieval of the E property, which 4 is then subtracted from it?  Or is it a cast to the E type of the value `-4`?  Both are potential interpretations.  Ambiguity is bad.  So we resolve this by complaining and forcing you to make it clear to us what you meant.

**Comment by CyrusNajmabadi** [comment]
> I understand that's more work and that may even imply a restructuring of the rules or of the compiler itself.

Yes. But let's explore that idea. This would now mean that parsing could not happen independently of semantic analysis. And it means that Roslyn could not be immutable. If binding could change the interpretation of syntax this would have enormous implications for both performance and immutability-safety of the entire compiler (and everything above it).

**Comment by ChrisBertrandIndus** [comment]
@CyrusNajmabadi 

Yes, I suspected that would imply a restructuring.
Maybe for a next compiler. ;-)
Thank you anyway.
