### ISSUE TITLE
Proposal: Static Indexers

### ISSUE THREAD

**Issue by MovGP0** [dotnet/csharplang#526]
I was thinking about having static indexers, ie. for well known tensors like `LeviCivita[i,j,k]`. The current solution is to [use a singleton pattern instead](http://stackoverflow.com/questions/401232/static-indexers).  

```csharp
public static class LeviCivita
{
    public static int [int i, int j] /* static indexer */
        requires i >= 0 && i < 2 /* contracts */
        requires j >= 0 && j < 2
    {
        return (i == j) ? 0 : (i,j) == (0,1) ? +1 : -1;
    }

    public static int [int i, int j, int k] /* static indexer */
        requires i >= 0 && i < 3 /* contracts */
        requires j >= 0 && j < 3
        requires k >= 0 && k < 3
    {
        return (i == j || j == k || i == k) ? 0 : IsEvenPermutation(i,j,k) ? +1 : -1;
    }

    private static bool IsEvenPermutation(int i, int j, int k)
    {
        switch((i, j, k)) // pattern matching
        {
            case (0,1,2): 
            case (2,0,1):
            case (1,2,0):
               return true;
            case (0,2,1):
            case (1,0,2):
            case (2,1,0):
               return false;
            default: 
               throw new ArgumentException();
        }
    }
}
```

**Comment by dstarkowski** [comment]
Personally never needed static indexers and can't really imagine how they could be useful.

Possibly there is a valid use case for them, but in my opinion your example is not one of them. And I don't only mean the static part, it shouldn't be indexer at all. It doesn't return value by index, it calculates result based on parameters. That's what static methods are for.

**Comment by MovGP0** [comment]
@dstarkowski  not exactly. technically a tensor is an abstraction of matrices and thus a value object. Querying from such an object is a lookup and doesn't calculate anything. I should have written this with a Key-Value-Table to make it more clear. 

I agree that there is no need to do it this way. In practice, you can use a dependency-injection framework do return an singleton instance of objects like this.

**Comment by yaakov-h** [comment]
Is the concern performance overhead of having an extra object around, or call-site code style? If it's call-site code style, you could combine `using static` with the singleton.

**Comment by MovGP0** [comment]
it's about code style, not performance.

**Comment by dstarkowski** [comment]
> it's about code style, not performance.

Just my opinion, but this is bad code style. That's not what indexers are for and in consequence would make code less obvious. For me that's forcing programming language to reflect math and C# syntax was not designed for that. Can you give an example of use case that's not math-related?

**Comment by yaakov-h** [comment]
Your code example uses about 4 or 5 different language feature proposals that do not exist so I've removed them, but you can achieve the call-site code style you want with something like the following:

```
namespace Example
{
    using System;
    using static MathHelpers;

    class Program
    {
        static int Main(string[] args)
        {
            return LeviCivita[1, 2];
        }
    }

    public static class MathHelpers
    {
        public static LeviCivitaImpl LeviCivita { get; } = new LeviCivitaImpl();

        public class LeviCivitaImpl
        {
            public int this[int i, int j]
            {
                get => throw new NotImplementedException();
            }

            public int this[int i, int j, int k]
            {
                get => throw new NotImplementedException();
            }
        }
    }
}
```
