### ISSUE TITLE
Proposal : runtime attributes

### ISSUE THREAD

**Issue by Pzixel** [dotnet/csharplang#529]
**Summary**

Making easier to extend existing classes with attributes

**Motivation**

Sometimes we find us in situation when we want to attribute being dynamically added to a class that didn't have it before. It may be `Serializable`, `DataContract` or tons of `Validation`. Very viable example is that we want to display some model in UI and validate user inputs. In Microsoft stack you have to do it using `unobtrusive attributes` and MVC takes all care about it. But you cannot reference `Microsoft.Mvc.Razor` from model just because you want some validation for obvious reasons. And here you have to write some ViewModels that is just like a model, but has attributes. You have to write a ViewModel not because you want to add some indirection, but because language itself makes you to do it. 

**Design**

I propose use the same mechanism that is using for inheritance and interfaces. Object can inherit one and only one parent (and overrides address in methodtable) and it has a list of interfaces and implementations of interface methods. I propose something similar: we can just add something like `DynamicAttributesList`, which can be freely populated and cleared by reflection methods. When you call `GetAttributes` it concat results of current implementation of `GetAttributes` and attributes from this list. We already have `System.ComponentModel.TypeDescriptor`, but we may want closer integration with methods such as mentioned `GetAttributes`, because otherwise it's a bit useless.

I don't see this change breaks anything in any way, it's quietly easy to implement it and it simplify some cases a lot. The only drawback I see here it cannot be language-only feature and require some CLR support.

**Comment by svick** [comment]
> The only drawback I see here it cannot be language-only feature and require some CLR support.

How does this feature have any language component at all? Isn't it just a request to modify the API and behavior of reflection? If that's the case, it belongs to [the corefx repo](https://github.com/dotnet/corefx).

**Comment by Pzixel** [comment]
@svick it seems that you are right. Sorry, I mischose the repository for my proposition.
