### ISSUE TITLE
[Proposal]: ReadOnlySpan initialization from static data

### ISSUE THREAD

**Issue by stephentoub** [dotnet/csharplang#5295]
# ReadOnlySpan initialization from static data

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Provide a syntax for initializing a `ReadOnlySpan<T>` from constant data and with guaranteed zero allocation.

## Motivation
[motivation]: #motivation

https://github.com/dotnet/roslyn/pull/24621 added compiler support that translates:
```C#
ReadOnlySpan<byte> data = new byte[] { const, values };
```
into non-allocating code that blits the binary data into the assembly data section and creates a span that points directly to that data.  The same optimization is done for:
```C#
static readonly ReadOnlySpan<byte> Data => new byte[] { const, values };
```

We now rely on this all over the place in dotnet/runtime and elsewhere, as it provides a very efficient means for accessing a collection of constant values with minimal overhead and in a way the JIT is able to optimize consumption of very well.

However, there are multiple problems with this:
1. The optimization only applies to byte-sized primitive T values, namely byte, sbyte, and bool.  Specify any other type, and you fall off a massive cliff, as code you were hoping to be allocation-free now allocates a new array on every access.
2. It's easy to accidentally fall off a similar cliff if at least one of the values turns out to be non-const (or becomes non-const), e.g. if a const value referred to in the initialization is changed elsewhere from a const to a static readonly.
3. The syntax is confusing, as it looks like it's allocating, and PRs that optimize code from:
```C#
private static readonly byte[] s_bytes = new byte[] { ... };
```
to
```C#
private static ReadOnlySpan<byte> Bytes => new byte[] { ... };
```
are often met with confusion and misinformation.
## Detailed design
[design]: #detailed-design

Add dedicated syntax for creating spans without allocating that:
1. Doesn't visually look like it's allocating (i.e. avoid use of 'new').
2. Provides validation with errors if the data isn't provably constant.

As the following syntax fails to compile today:
```C#
ReadOnlySpan<byte> data = { 1, 2, 3 };
```
and
```C#
static ReadOnlySpan<byte> Data => { 1, 2, 3 };
```
they could be co-opted for this purpose.

Opening up this syntax via the removal of `new T[]` doesn't prevent the optimization from being applied by the compiler when `new T[]` is used, but it would guarantee a non-allocating implementation when the `new T[]` isn't used.

This could also tie in with `params Span<T>`: the syntax for the local variant could blit the data into the assembly if possible, or else fall back to the same implementation it would use for a `params Span<T>` method argument (assuming that `params` syntax itself doesn't itself fall back to heap allocation).

Implementation-wise, the compiler would use RVA statics whenever possible and fall back to static readonly arrays otherwise.

## Drawbacks
[drawbacks]: #drawbacks

TBD

## Alternatives
[alternatives]: #alternatives

TBD

## Unresolved questions
[unresolved]: #unresolved-questions

Related to this, we have prototyped in both the runtime and the C# compiler support for extending this optimization to more than just byte-sized primitives.  The difficulty with other primitives is endianness, and it can be addressed in a manner similar to array initialization: the runtime exposes a helper that either returns the original pointer, or sets up a cache of a copy of the data reversed based on the current endianness.  There are also multiple fallback code generation options available for if that API isn't available.  Such improvements to the compiler are related but separate from the improvements to the language syntax for this existing optimization.

## Design meetings

* https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-09-21.md#readonlyspan-initialization-from-static-data
* https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-10-09.md#readonlyspan-initialization-from-static-data

cc: @jaredpar

**Comment by bernd5** [comment]
As specified in https://github.com/dotnet/csharplang/blob/3c8559f186d4c5df5d1299b0eaa4e139ae130ab6/spec/arrays.md#array-creation the syntax `localOrField = { 1, 2, 3 };` is just a "shortcut" for `localOrField = new int[]{ 1, 2, 3 };`

So I think the optimization should be done regardless how the array initialization is written syntactically if possible. Currently we have these forms AFAIK:
- `new Type[]{ value1, value2}`
- `new[]{ value1, value2}`
- `{ value1, value2 }`

To force this behaviour we could maybe introduce a new intrinsic Function like `System.Array.CreateConstArray(1, 2, 3)`.

BTW: it would be nice if we could write: 
```csharp
static ReadOnlySpan<byte> Data => { 1, 2, 3 };
```
or 
```csharp
static ReadOnlySpan<byte> Data { return { 1, 2, 3 }; }
```

**Comment by stephentoub** [comment]
> So I think the optimization should be done regardless how the array initialization is written syntactically.

As I noted,  the compiler would be free to do so... it already does so.  But one of the key aspects here is the compiler preventing you from shooting yourself in the foot, guaranteeing that the syntax is non-allocating (at least beyond any initialization required, e.g. in the case of a big endian machine reading the assembly little endian data),  and it would be a breaking change if the existing usage that allocates stopped compiling.

**Comment by jaredpar** [comment]
> Provides validation with warnings or errors if the expression would allocate

This feels like the best approach to me. Essentially we could standardize on `= { ... }` as being the non-allocating form. Then we could warn in any situation where it would cause an allocation:

- The contents of the `{ ... }` were non-const
- The target of the expression was `Span<byte>` 
- The target of the expression was `ReadOnlySpan<T>` where `T` is not `byte`, `bool` or `sbyte`. This of course would change if we implemented the optimization for non-byte sized types.

The one part that still bothers me is arrays. That syntax works for arrays today but has none of the safe guards. I've thought a bit about adding a disabled warning here that could be enabled by developers who hit this a lot but I'm having trouble convincing myself that meets the bar. Given that this only works on fields and locals today, maybe just knowing it doesn't work on arrays is enough for developers.

> BTW: it would be nice if we could write:
> static ReadOnlySpan<byte> Data => { 1, 2, 3 };

That is asking for `{ ... }` to be a more general expression where today it's limited to field and local declarations. It's not un-doable but a bit of a bigger ask. 

If we took this then I'd feel a bit more strongly about finding a way to extend this warning to cases where it crossed into arrays. Take for example the code `M({1, 2, 3})` which would be legal if we generalized this to expressions. Whether or not it allocates depends on overload resolution.

**Comment by Naine** [comment]
> It would be really weird if it didn't though. For example it would be weird if I could say const i = const 42 but not [My(const 1)]. I can't introducing this without introducing the complete picture.

It doesn't need to be supported for all constant expressions, only array initializer expressions:

```csharp
ReadOnlySpan<byte> span = new byte[] { 1, 2, 3 };        // creates span from System.Array (unless optimizable)
ReadOnlySpan<byte> span = stackalloc byte[] { 1, 2, 3 }; // creates span from stack array
ReadOnlySpan<byte> span = const byte[] { 1, 2, 3 };      // creates span from assembly data section
```

**Comment by CyrusNajmabadi** [comment]
Championing this.  I too fell into:

> The syntax is confusing, as it looks like it's allocating, and PRs that optimize code from ... are often met with confusion and misinformation.

It would be nice to have a form that was less magical about how it was working with the compiler to get this result.

**Comment by CyrusNajmabadi** [comment]
> As the following syntax fails to compile today:

Yup.  And, afaict, within roslyn, there woudl be no complexity to parse this at all.  This would already fix directly into our syntax model.  So this would just be something on the semantic side to enable.  I don't know the compiler impl here well, but i have a feeling it could be done with minimal effort.  Specifically:

`byte[] b = { ... }` is already supported, and so the compiler already effectively has to bind and translate that form to `byte[] b = new byte[the_length] { ... }` internally.  So this would just be:

1. do teh same for if you have `{ ... }` on the RHS of a `ReadOnlySpan<X> X = { ... }` or as the expr in a `ReadOnlySpan<X> X => expr` property body.  The rest of binding/emit should then take over and give teh same optimization as today.
2. Relax the rule on ref-structs as fields to allow them as static-readonly fields.  Though need runtime/gc people to state if that will be a problem or not.  Conceptually for C# i don't see any problems there.
3. Ensure that binding can understand that if you have `ReadOnlySpan<X> x = { ... }` what the right type of the array initializer is.  For example, if you have `ReadOnlySpan<byte> X = { 1, 2, 3 }` we want this to be viewed as `ReadOnlySpan<byte> X = new byte[] { 1, 2, 3 }` *not* `ReadOnlySpan<byte> X = new int[] { 1, 2, 3 }`.  Not sure if that's trivial, or if that may require some hackery to understand these special types.  Given the optimization around arrays/ROS already in the compiler today, my guess is that there are already these special type hacks, so this would be nbd to encode into the language and support here.

**Comment by CyrusNajmabadi** [comment]
@jaredpar I'm interested in taking a stab at this once we have space in the schedule.  Let's chat about when/if you think this is possible to slot in.  Definitely low pri, but also seems nice to have, hopefully cheap, and well received by the community here.

**Comment by jkotas** [comment]
> Relax the rule on ref-structs as fields to allow them as static-readonly fields. Though need runtime/gc people to state if that will be a problem or not. 

Yes, that's a problem for the runtime. One of the primary reason for ref-structs to exist is that they cannot appear on the GC heap.

**Comment by CyrusNajmabadi** [comment]
@jkotas Can we relax this in some fashion?  *Conceptually* in this case there should be no problem that i can see (def correct me if i'm wrong).  However, i'm not sure if this would be just something about ROS, or something that could extend to ref-structs in general.  And, to be clear, i solely mean the use of them in static-readonly locations, nowhere else.  Thanks!

**Comment by jkotas** [comment]
> Can we relax this in some fashion? 

`static` fields are stored on the GC heap just like anything else. 

This is hard trade-off for the runtime to make. If we relax this, we will end up with increased GC latencies that translate to worse P99s that is something that top tier services care about a lot.

**Comment by CyrusNajmabadi** [comment]
Can you clarify where hte increased GC latency comes from?  Conceptually, a user can (and already did) write: 

```
private static readonly T[] static_array = { ... }
```

Wrapping that with ROS to make the array non-mutable doesn't seem like it should have a GC impact.

**Comment by jkotas** [comment]
The `byref` in `Span`/`ReadOnlySpan` are expensive for the GC to walk. The GC has to find the containing object for them that is an expensive operation.

**Comment by CyrusNajmabadi** [comment]
> The GC has to find the containing object for them

Why does the GC have to find the containing object for them?

**Comment by jkotas** [comment]
So that it can mark the object as reachable.

**Comment by CyrusNajmabadi** [comment]
Why does it need to mark the containing object as reachable?  (aside, this back and forth seems to be really inefficient).  Would it be possible for you to break down the entirety of what's going on here so each message doesn't need a further 'why' to get a sense of the very next step in the algorithm?  Thanks.

**Comment by jkotas** [comment]
I feel that I am trying to explain the basic internal working of the GC. There are books and talk series dedicated to explaining the full chain of why things are done in certain way and the trade-offs involved in the GC design. I agree that it is not useful to replay those here.

It would be certainly technically possible (though a ton of work) to allow byrefs on heap. The problem are the performance trade-off that would come from that decision. We are not convinced that these trade-offs would be an overall win.

The short story is that marking byrefs is expensive. Marking byrefs has to find a containing object. It is ~100x more expensive than a simple pointer dereference that is used for object references. Limiting byrefs to active stack only makes this cost manageable (the typical code has only so many byrefs on live stacks) and keeps the core marking algorithm simple.

There are many possible trade-offs in this area. For example, the classic Java VMs do not have byrefs like .NET. Instead, they explicitly store and pass around the containing object of the byref. It means that the code has slower throughput, but the GC is simpler and can do less work it does not need to support lookup of containing object from arbitrary pointer.

**Comment by CyrusNajmabadi** [comment]
> I feel that I am trying to explain the basic internal working of the GC.

This doesn't feel basic to me.  It's unclear to me why the containing type is relevant at all for a static ROS field.  Perhaps you can go the other direction and show an example of why it would matter?

**Comment by CyrusNajmabadi** [comment]
> Consider static ReadOnlySpan<byte> s_field = new byte[] { 1, 2, 3 };. Something needs to keep the byte[] alive.

Sure.  I expect the field would keep that alive.  I don't see what that has to do with the containing type of 's_field' as per:

> The GC has to find the containing object for them that is an expensive operation.

**Comment by stephentoub** [comment]
It's the containing object for the ref inside of the span, not the containing type for the static field.  Forget spans for a moment, allowing spans there is akin to allowing static ref fields, and so if you hypothetically had:
```C#
static readonly ref byte s_byte = ref CreateSomeObject().SomeByteField;
```
that ref field needs to keep alive the object containing that SomeByteField that's being referenced.

**Comment by CyrusNajmabadi** [comment]
I guess i'm saying: what about jsut ROS around arrays, so they're morally treated the exact same way as arrays are today.  Just that they cannot be mutated.

**Comment by stephentoub** [comment]
> so they're morally treated the exact same way as arrays are today

A `byte[] s_field` references the object, not something inside the object.  A `ref byte s_field` can reference inside the object.  They can't be treated the same.

Are you instead suggesting the C# language would only allow you to store a `ReadOnlySpan<byte>` into a `ReadOnlySpan<byte>` field if it were constructed with a ref to the head of the object rather than to an interior pointer?

**Comment by CyrusNajmabadi** [comment]
>Are you instead suggesting the C# language would only allow you to store a ReadOnlySpan<byte> into a ReadOnlySpan<byte> field if it were constructed with a ref to the head of the object rather than to an interior pointer?

Yes, exactly.  It would be allowing `static readonly ROS<byte> = { ... }`

**Comment by stephentoub** [comment]
The GC would need to special-case static readonly fields of spans to say that, unlike every other span, the ref is guaranteed to be the head of the object.  That feels like a very expensive special-case for something that doesn't buy you a whole lot, and is actually likely to be more expensive for consumers of the field than if it were just a property unless the JIT is also augmented with a lot more intelligence around such things.

**Comment by CyrusNajmabadi** [comment]
>  That feels like a very expensive special-case for something

Could you clarify "expensive" in this context?  Does that mean expensive to do the analysis?  Expensive for the GC?  etc.?

> I don't think it's worth a lot of effort to also be able to write:

Fair. :)

**Comment by Neme12** [comment]
> > It doesn't need to be supported for all constant expressions, only array initializer expressions:
> 
> That seems very counterintuitive. If `const` is meant to explicitly identify expressions that are `const` why should it be limited to a subset of `const` expressions?
> 
> Yes I agree that `const 42` (or any other literal) is a bit silly but what about `const A.B`? Lacking `const` that could be a side effecting property but with `const` prefix I've guaranteed I'm accessing a constant here. Or even `const A + B` as another example.
> 
> I can't see introducing `const` as a way to identify `const` array expressions but exclude it from all the other expression that are constant.

I think the idea is that `const` would be a new type of "alloc", in addition to `new` and `stackalloc`, not a general expression. But to make that clear, something like `constalloc` could be better:

```c#
ReadOnlySpan<byte> span = new byte[] { 1, 2, 3 };        // creates span from System.Array (unless optimizable)
ReadOnlySpan<byte> span = stackalloc byte[] { 1, 2, 3 }; // creates span from stack array
ReadOnlySpan<byte> span = constalloc byte[] { 1, 2, 3 }; // creates span from assembly data section
```
If you then use `constalloc` where the compiller cannot do the "optimization" and return a span from the assembly, that would be an error. So it's clear what the intent is and if someone relies on the optimization, they wouldn't accidentally get an array allocation.

**Comment by Neme12** [comment]
Also, this:
```c#
ReadOnlySpan<byte> span = { 1, 2, 3 };
```
could be a shorthand for `constalloc`, just like array initialization. But this shorthand wouldn't work after `=>` or as a general expression, only in initializers, to match how this works with arrays and make the language consistent.

**Comment by MichalPetryka** [comment]
Would the language provide a guarantee with this that the memory is always fixed (not in a GC moveable heap) and that it always lives at least as long or longer as the type it is defined in? Those two guarantees could be really useful when dealing with high performance code.

**Comment by stephentoub** [comment]
I think it would depend on how constrained we want it to be. For example, without RuntimeHelpers.CreateSpan, it could still support the relevant types by caching the array into a readonly static; it could do the same even for types CreateSpan doesn't support. I personally think that's more helpful than a guarantee about immovability.

**Comment by Sergio0694** [comment]
Would we at least have the immovability guaranteed when using types that don't need endianness fixups, like today? As in, when declaring a constant buffer of type `byte` (but also `sbyte`, `bool`), it would be great to be able to rely on this as an actual specification, just like we can today when using the `new byte[]` trick. That should be doable, right?

**Comment by stephentoub** [comment]
> Would we at least have the immovability guaranteed when using types that don't need endianness fixups, like today? 
>  it would be great to be able to rely on this as an actual specification, just like we can today when using the new byte[] trick

This is not guaranteed by any specification.

**Comment by Sergio0694** [comment]
Uh... Can you clarify on what you mean by that? As in, yes the `new byte[]` trick for spans is not formally in any specification, but (as long as you're using Roslyn to compile), that _is_ guaranteed to result in a pinned memory region as far as I know, since it's just point to embedded PE data. I'm relying on this myself and know several other folks who do as well, and while talking with other .NET folks in the past (eg. Tanner, Egor, Aaron, Jeremy, etc.) nobody ever mentioned one couldn't rely on this being the case. I thought this was a well established "Roslyn implementation detail but you can rely on this" feature at this point? 😅

**Comment by stephentoub** [comment]
I mean it's an implementation detail of the compiler today.  No C#, CLR, ECMA, etc. specification would be violated if that were changed.  No formal process beyond normal PR review was used to vet the IL the compiler emits for this as part of the PR that implemented the optimization.  Etc.

**Comment by Sergio0694** [comment]
So, we've been chatting about several issues regarding constant data these past few days with @tannergooding, @AaronRobinsonMSFT, @jkoritzinsky and other folks. There were two main aspects that have been brought up:
1) Relying on the data being in the PE section, and therefore pinned (or, relying on the data being pinned at all).
2) Returning data in a `ReadOnlyMemory<T>`, and concerns related to assembly unloading.

Point 2 was brought up in https://github.com/dotnet/runtime/issues/71268 and I'd consider that as being pretty much resolved, as you can safely do this by implementing a custom `MemoryManager<T>` wrapping some delegate accessing the span (or equivalent logic). That'd implicitly root the containing assembly, wouldn't rely on the span data pinned, and it would still let you avoid using `ToArray()` on the span, so let's ignore that one here (just mentioned it for additional context, as it was related).

Point 1 is still an open issue, and we've been brainstorming ideas on how to potentially resolve this. For context, the spans being lowered by Roslyn into the PE section and therefore being pinned is something that is used in production. For instance, Tanner has thousands of uses of this (I mean `Unsafe.AsPointer` on an RVA span) throughout TerraFX, I'm using the same in my ComputeSharp library which is also used in production by several folks, etc. Since this is, as you said, not really detailed anywhere, it's essentially undefined behavior, and I think it would be nice to come up with a proper way to address this.

Note: of course folks are currently testing this (eg. Tanner has plenty of unit tests for all supported TFMs in his CI, I'm doing the same for my projects, etc), but this is still not ideal at all, plus it would not help catch scenarios where a customer might bump their TFM without updating the dependency at the same time, and that could just break completely.

There's two different ways I could see us tackling this:
- **Language:** we could make constant data using the new syntax be specced to always be lowered to a span in the PE data section by Roslyn, making this well defined behavior. Caveat: this of course would not work for spans that require endianness fixups, as in that case the runtime might have to allocate an array and copy the adjusted data to it.
- **Runtime:** Tanner proposed the idea of using some attribute (eg. `[FixedAddressValueType]`, or a new one) to annotate a property returning a constant span, that would instruct the runtime to ensure the span data is pinned (ie. either doing nothing if the data is already in the PE data section, or otherwise allocating the array in the POH).

To me it seems we could do both: making the new `{ ... }` const syntax be always lowered to the PE data section if `T` allows it (ie. for `byte`, `sbyte`), and then separately from that, propose some new attribute to allow developers to opt-in into getting the data being guaranteed to be pinned by the runtime in all cases, regardless of the type of `T`.

Wanted to get some additional thoughts before opening a proposal, especially because the one about making `{ ... }` be guaranteed to be in the PE data section for `byte` and `sbyte` would be an update to this spec, so I guess it should just belong to this proposal. As the proposal says, there's plenty of code in the runtime too that relies on this be the case, so it would seem fine to me to decide to make this a properly specced behavior and no longer an implementation detail? 🙂

**Comment by jkotas** [comment]
> Runtime: Tanner proposed the idea of using some attribute (eg. [FixedAddressValueType], or a new one) to annotate a property returning a constant span, that would instruct the runtime to ensure the span data is pinned (ie. either doing nothing if the data is already in the PE data section, or otherwise allocating the array in the POH)

This sounds like overengineering to me. It should be fine to say in 
https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md that embedded data (II.16.3 Embedding data in a PE file) have fixed address at runtime. BTW: I am not able to find anything the ECMA spec that says locals have fixed address at runtime... .

**Comment by MichalPetryka** [comment]
Well locals do not always have a fixed address in runtime, for example in async methods.

**Comment by Sergio0694** [comment]
> "It should be fine to say in
https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md that embedded data (II.16.3 Embedding data in a PE file) have fixed address at runtime"

That seems perfect to me, absolutely. No new attributes needed, and for existing code it'd mostly just be making what is currently just an implementation detail, well defined behavior. All I care about here really is just making this something that is technically correct to rely on in production scenarios, so if it was possible to just add this to the spec, then that'd be just great 😄

**Comment by stephentoub** [comment]
>  I, personally, don't see a lot of benefit to caching in a static readonly T[] as that's strictly "more expensive" and going to result in the same or worse "bloat" to the image size. 

I'm not sure what you mean as it being "strictly more expensive".  If a developer writes:
```C#
public ReadOnlySpan<int> Data => { 1, 2, 3, 4, 5 };
```
having the compiler lower that to caching it in a field is in no way strictly more expensive than allocating a new array on each invocation.  It is more expensive than using CreateSpan, but CreateSpan may not always exist.  A developer should be able to write the above code and get reasonable performance regardless of what platform is being targeted, e.g. we want to be able to write the above in a file that's built in to an assembly targeting .NET 8 and netstandard2.1.  Also enabling such lowering removes complexity... regardless of the type in question, a developer could then always write the above, whether the data has no endianness issues, whether CreateSpan is available, and whether CreateSpan even works with the type in question... the average developer no longer needs to know or think as much about the costs involved, whether they're going to fall off a cliff, etc... the syntax "just works" and does the best possible thing.

**Comment by tannergooding** [comment]
> having the compiler lower that to caching it in a field is in no way strictly more expensive than allocating a new array on each invocation.

Caching `{ 1, 2, 3, 4, 5 }` as some `private static readonly int[] _PrivateData = new int[] { 1, 2, 3, 4, 5 }; `public ReadOnlySpan<int> Data => _PrivateData;` is more "expensive" than simply emitting it as the `CreateSpan` call directly to the embedded data. It requires more overall metadata to support, but also an allocation and requires a static constructor to run at some point leading to worse codegen and handling in NAOT scenarios where the initialization logic can't be removed.

> It is more expensive than using CreateSpan, but CreateSpan may not always exist. A developer should be able to write the above code and get reasonable performance regardless of what platform is being targeted, e.g. we want to be able to write the above in a file that's built in to an assembly targeting .NET 8 and netstandard2.1.

Such a new feature is, strictly speaking .NET 8/C# 12+ exclusive at this point and using such features on .NET Standard 2.1 will be officially unsupported. There are plenty of features that do not work downstream and I don't think its worth making such a feature be "worse" just to support such a scenario. Devs who need to target the other have alternatives, such as continuing to use the `public static readonly int[] Data = new int[] { 1, 2, 3, 4, 5 };` syntax -or- caching the data themselves and returning it through the `public ReadOnlySpan<int> Data { get; }` property.

> the average developer no longer needs to know or think as much about the costs involved

The average developer won't be impacted by such a guarantee because it will only be available if  they target .NET 8/C# 12+ and in such a scenario they get the feature with any guarantees we want to put in place.

**Comment by stephentoub** [comment]
> is more "expensive" than simply emitting it as the CreateSpan call directly to the embedded data

No one is arguing against that.

> I don't think its worth making such a feature be "worse" just to support such a scenario.

It wouldn't be worse. If CreateSpan is available, it would use it. If it's not, it would use a caching field. I don't understand why that's contentious. It enables this language syntax for every type, regardless of whether it's able to be optimized even further on the target platform.

**Comment by stephentoub** [comment]
> The average developer won't be impacted by such a guarantee because the entire feature will only be available if they target .NET 8/C# 12+ and in such a scenario they get the feature with any guarantees we want to put in place.

Yes, they will, as CreateSpan only works with a su subset of types.

**Comment by jaredpar** [comment]
>  If CreateSpan is available and usable for a given type, it would use it. If it's not, it would use a caching field. I don't understand why that's contentious.

This pattern of "use X if available otherwise fall back to Y" is pretty common in the C# compiler. It allows to generate better code when possible but keep features working, albeit in a less efficient way, when they're not. The decisions here are very much inline with how the compiler tends to approach these problems (for pretty much all the usability reasons @stephentoub outlined above). 

The use of the data as a fixed item feels pretty domain specific. It's not a general purpose usage. As such my recommendation would be such domains should have an analyzer to guarantee they're only using the `ROS<T>` as `fixed` when indeed it truly is lowered down to static data in the PE file.

**Comment by tannergooding** [comment]
> That would be completely non viable in eg. TerraFX.Interop.Windows unfortunatley (not to mention it'd be much slower).

Just noting I'm not personally concerned with my own libraries here. I'm only targeting .NET LTS + STS and can update it all to be validated.

I'm just trying to raise some of the concerns and asks for codification that exist more broadly as I do think that having some way to more broadly guarantee the data is "definitively pinned" (even if runtime specific) would be net goodness. This doesn't have to come in the form of unique syntax, it could come in the form of a spec guarantee, an attribute, or something else.

**Comment by stephentoub** [comment]
> Yes, but such projects won't have access to ReadOnlySpan<T> Name => { cns, cns, cns } syntax on the downlevel TFMs

Yes, they will. That's not how C# works. If you believe it's truly unsupported then please submit the PRs to runtime, Azure SDK, Roslyn, aspnetcore, and so on to stop using newer LangVers when targeting netstandard and the like. I'm sorry, I find this line of argument very frustrating. Very, very, very few devs have the same scenarios being microoptimized for here; many more would benefit from simplified syntax that avoids allocation. You get 95+% of the perf benefits by avoiding the allocation via caching it; we should enable the simple syntax that "just works" and fits the best possible thing everywhere, rather than failing to compile or falling off a cliff, in either case increasing learning curve and complexity. If we also want to make additional spec guarantees for some types/uses, that's fine.

**Comment by jkoritzinsky** [comment]
> > Yes, but such projects won't have access to ReadOnlySpan Name => { cns, cns, cns } syntax on the downlevel TFMs
> 
> Yes, they will. That's not how C# works. If you believe it's truly unsupported then please submit the PRs to runtime, Azure SDK, Roslyn, aspnetcore, and so on to stop using newer LangVers when targeting netstandard and the like.

The docs explicitly state that new language versions are not supported on older target frameworks. We don't block them as we use them ourselves on downlevel TFMs (barring features that rely on runtime support), but we explicitly tell customers that they are not supported.

Having downlevel TFM support with the new LangVersion is reasonable, but we should consider the cost of implementation with the fact that it's an explicitly not supported scenario.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

> [C# 11](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11) is supported only on .NET 7 and newer versions. [C# 10](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10) is supported only on .NET 6 and newer versions. [C# 9](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9) is supported only on .NET 5 and newer versions. [C# 8.0](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8) is supported only on .NET Core 3.x and newer versions.

**Comment by stephentoub** [comment]
> We don't block them as we use them ourselves on downlevel TFMs

Yes, "everyone" does. We go out of our way to keep them working unless there's a strong reason we can't. Adding a caching strategy that we'd want to be available even on the latest platform in order to support types that don't work with CreateSpan is not a significant burden.

**Comment by tannergooding** [comment]
I agree and an analyzer is often a good choice. But, there is also only so much that an analyzer can check and or guarantee.

Would it be possible for Roslyn (not C#) to documented something like `ReadOnlySpan<T> x => { cns, cns, cns };` (for C# vX+) will always emit a "data declaration" for `byte/sbyte` and that it will do the same for other primitive types when `CreateSpan` is available.

That would allow devs to then independently rely on the implementation detail and base their analyzers on something "sound".

It would also still leave the implementation fairly flexible for non-constant data and for user-defined types.

**Comment by 333fred** [comment]
Discussed in https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-10-09.md#readonlyspan-initialization-from-static-data. As this has mostly been subsumed by C# 12 features, we are closing this out.

**Comment by PavelCibulka** [comment]
This already works inside functions. for exaple:

```
static float x1(int a){
            a = a & 3;
            ReadOnlySpan<float> numbers = [1f, 0.7f, 0.3f, 0.5f];
            return numbers[a];
        } 
static float x2(int a){
            a = a & 3;
            ReadOnlySpan<float> numbers = [1f, 0.7f, 0.3f, 0.5f];
            return numbers[a];
}
```

Get compiled into:
```
Program:x1(int):float (FullOpts):
       and      edi, 3
       mov      eax, edi
       mov      rcx, 0x71F73122CC20      ; static handle
       vmovss   xmm0, dword ptr [rcx+4*rax]
       ret      

Program:x2(int):float (FullOpts):
       and      edi, 3
       mov      eax, edi
       mov      rcx, 0x71F73122CC20      ; static handle
       vmovss   xmm0, dword ptr [rcx+4*rax]
       ret  
```

ReadOnlySpan is practically const. Both functions use same memory address. But it is not very nice for programer. It would be better if we could do obvious thing. 

const ReadOnlySpan<float> numbers = [1f, 0.7f, 0.3f, 0.5f];
