### ISSUE TITLE
Proposal discussions

### ISSUE THREAD

**Issue by scottdorman** [dotnet/csharplang#53]
Are discussions about proposals supposed to only happen in the mailing list or can they also be entered as issues in the repo?

The only concerns about them happening only in the mailing list is that they're not readily visible/accessible and aren't part of the repo (so no history, searching, etc. that we'd get with having them as issues).

Also, how long should it typically take to receive the confirmation email after subscribing to the mailing lists?

**Comment by HaloFour** [comment]
@scottdorman 

https://github.com/dotnet/roslyn/issues/17054

**Comment by scottdorman** [comment]
@HaloFour Thanks for the link. Reading through it now.
