### ISSUE TITLE
[Proposal] Const Refs for Parameters and Methods

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#536]
## const ref parameters and methods
- [x] Proposed
- [ ] Prototype
- [ ] Implementation
- [ ] Specification
## Summary
Allow a way to pass a parameter as a reference whose value, not it state, cannot be modified (and extend it also to ref returns). Additionally, allow a way to let the compiler enforce that methods do NOT change the state of the containing member.

Note: this proposal is different from state immutability so it is NOT a duplicate of [readonly refs](https://github.com/dotnet/csharplang/blob/e8a42bafa8d7ca7b77160bdc0bdeff91b58e389c/proposals/readonly-ref.md).
## Motivation
Sometimes you need to pass a parameter by reference for performance reasons and at the same time, enforce that it cannot be reassigned (specially for fields that cannot be declared as read-only). Thus, its state can be modified. Think of it as a constant pointer. Following this rationale, such rule could be also applied to ref returns.

For methods, there may be use cases where you want enforce that specific methods do not change the state of the containing element (for example, a getter).
## Syntax for Parameters
In order to maintain familiarity with native languages like C++, the syntax would use the reserved words “const ref”.

**Case 1:** const ref parameter 
```c#
i) declaration: void DoSomeStuff ( const ref Class1 parameter1, … ) { }

ii) use: DoSomeStuff ( const ref myClass1, ...);

```

**Case 2:** const ref return

```c#
i) declaration: const ref Class1 DoSomeStuff ( … ) { }

i) use: const ref Class1 myClass1 = const ref DoSomeStuff ( ... );
```

**Case 3:** both, const ref parameters and const ref return

```c#
i) declaration: const ref Class1 DoSomeStuff ( const ref Class1 parameter1, const ref Class2 parameter2, … ) { }

i) use: const ref Class1 myClass1 = const ref DoSomeStuff (const ref myParameter1, ... );
```
## Syntax for Methods

Again, syntax should be similar to the one used in C++:

**Case 1:** const operations

```c#
void DoSomeStuff ( … ) const { }
```

**Case 2:** const getter

```c#
// The use of const for setters must not be allowed by the compiler
MyClass Property1 { const get { … } }
```

## Alternatives
For parameters, use a read-only backing field, which would imply to redesign logic so that such field gets assigned when declared or the containing element gets constructed.

For methods, the alternative is “stay as is”.
## Unresolved Questions
1. In the case of simple primitives, like an int, will the C# compiler enforce immutability for a const ref parameter and or const ref return?

2. Given a signature like ...: 

```c#
void DoSomeStuff ( const ref Class1 parameter1 ) { }
```

... will the compiler consider it different from any of the following ...?

```c#
void DoSomeStuff ( ref Class1 parameter1 ) { }

void DoSomeStuff ( Class1 parameter1 ) { }
```
... so you can declare them within the same element with no conflicts?

3. Could it be possible to use 'var' instead of `const ref <Type>`? Like ...:

```c#
var myClass1 = const ref DoSomeStuff (const ref myParameter1, ... );
```

... or ...

```c#
const ref var myClass1 = const ref DoSomeStuff (const ref myParameter1, ... );
```

## Design Meetings
n/a

**Comment by DavidArno** [comment]
> Note: this proposal is different from state immutability so it is NOT a duplicate of readonly refs.

Could you provide an example of in what way this is different, as it sounds identical to me 😕

**Comment by Ultrahead** [comment]
The key difference:

static Vector3 Add (const ref Vector3 v1, readonly ref Vector3 v2)
{
     v1 = default(Vector3); // Error at compilation time.
     
     v1.X = 0; // This compliles ok.
}

**Comment by jnm2** [comment]
It's weird for `const` to have a weaker sense than `readonly`.

**Comment by DavidArno** [comment]
I'm with @jnm2 here: you seem to want to use the keyword `const` to mean "can be modified". `const` implies even stricter immutability than `readonly`.

Semantics aside, you are describing a type that you pass by reference, without modifying what that reference points to, but that can have its innards modified. Classes fit that bill precisely.

**Comment by Ultrahead** [comment]
As stated on the proposal, the use of `const ref` is to keep familiarity with C++. And 'const' applies to the reference it-self, not the referenced element.

Performance-wise, you are not creating a copy of the reference (or valuetype) passed as a parameter and yet, you enforce that the reference cannot be reassigned.

**Comment by mikedn** [comment]
> As stated on the proposal, the use of const ref is to keep familiarity with C++. 

Well, it certainly doesn't look familiar to me. The example
```C++
v1.X = 0; // This compiles ok.
```
would not compile in C++ unless `X` is `mutable`. And you don't seem to describe such a feature so the example is plain weird.

On top of it C# already uses `const` and it's more similar to C++'s `constexpr` than `const`. Having both `ref readonly` and your suggested kind of `const` will probably be an amazing source of confusion.

**Comment by Ultrahead** [comment]
The example is based on the one used for the read-only ref proposal where x is mutable on the Vector3 struct (usually a public field).

`const ref` is not confusing to me, but provided the feature gets implemented, I'm open to an alternative syntax.

**Comment by mikedn** [comment]
> The example is based on the one used for the read-only ref proposal where x is mutable on the Vector3 struct (usually a public field).

The example fails to illustrate the need for `const ref`. It allows one to change a field of `Vector3` but disallows changing the entire `Vector3` value. That's just weird.

**Comment by Ultrahead** [comment]
It was used to illustrate the key differences with read-only ref.

As for the need of const ref, I'd use it with IoC, Dependency Injection, and any case where a read-only backing field cannot be used. For example, when you cannot initialize and assign an instance to a field when declared or inside a constructor.

**Comment by Ultrahead** [comment]
With the new reference semantics for value types introduced in 7.2, this proposal has been partially met.

**Comment by ufcpp** [comment]
This concept looks like more similar to [copyability](https://github.com/dotnet/csharplang/issues/859) rather than readonly/const-ness. It is not the same but kind of "dual".

```cs
var x = new X();

var other = x; // copyability

x = other; // this concept? overwritability?
```

**Comment by alrz** [comment]
>Allow a way to pass a parameter as a reference whose value, not it state, cannot be modified

You mean something like this?
```cpp
const char* pstring = ...;
char* const pstring = ...;
const char* const pstring = ...;
```
or in C#,
```cs
readonly ref var x = ...;
ref readonly var x = ...;
readonly ref readonly var x = ...;
```
