### ISSUE TITLE
[Open Question]: `required` parsing

### ISSUE THREAD

**Issue by 333fred** [dotnet/csharplang#5439]
In https://github.com/dotnet/csharplang/blob/main/proposals/required-members.md, we add a new modifier `required`. However, we need to decide how we do the parsing for this feature: are we going to attempt to continue to make code like the following work?

```cs
public class required {}

class C
{
    public required R { get; set; }
}
```

**Comment by alrz** [comment]
https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-10-25.md

>We will start working on an implementation of the simplified version of this proposal that uses attributes for contract modifications, not specific syntax

Is that no longer true?

**Comment by 333fred** [comment]
> Is that no longer true?

Contract modifications refers to exemptions, not to actually creating a contract. It never meant removing the required keyword.

**Comment by Youssef1313** [comment]
I'd personally prefer taking a small breaking change for the given example (I even believe this will affect near zero customers) over introducing "human parsing" issues. There was a breaking change for records already:

```csharp
public class @record {}

public abstract class C
{
    public abstract record F(); // Is this a record or a function? IT's currently considered a record. Potentially breaking old code.
}
```

So why not another breaking change :smile:

**Comment by timcassell** [comment]
If the `required` keyword must always come before the type name, I see no reason not to allow it. Your example would parse `required` as the type.

```cs
public class required {}

class C
{
    public required required R { get; set; }
}
```

This example would have the type `required` and the property `R` is required.

`required` then is a context-sensitive keyword.

**Comment by 333fred** [comment]
> Didn't you guys already decide to start warning on all lowercase type names?

Yes, but that doesn't mean we can't make this particular parse work, so I still want LDM to make an explicit decision here. It can impact refactorings for moving to a new language version if we do it in a particular way.

**Comment by Korporal** [comment]
Rather than:

```cs
public class Person
{
    // The default constructor requires that FirstName and LastName be set at construction time
    public required string FirstName { get; init; }
    public string MiddleName { get; init; } = "";
    public required string LastName { get; init; }
}
```

would this not also achieve the same result with less complexity?

```cs
public class Person
{
    // The default constructor requires that FirstName and LastName be set at construction time
    public string FirstName { get; required; }
    public string MiddleName { get; required; } = "";
    public string LastName { get; reqd; }  // possible abbreviation
}
```

?

**Comment by HaloFour** [comment]
@Korporal 

How would you differentiate between `required`+`init` and `required`+`set`?

**Comment by Korporal** [comment]
@HaloFour 

Well I'd envisage `required` to be even more restrictive than `init` not only can one only set the value at certain points in the execution but they actually _must_ set the value, so it would complement `init` and `set` becoming a third option.

**Comment by 333fred** [comment]
This issue is not for discussing changes to the mission statement. It's only for addressing a specific parsing question in the approved specification for required _members_ (note that I didn't say properties, as fields can also be required). If you would like to discuss more general things, please use https://github.com/dotnet/csharplang/issues/3630.

**Comment by IDjinn** [comment]
I think when you're by own breaking convenction (like type aways pastel case) youre assuming the code may not work... `@required` must solve that if you really want use lower case.


> If the `required` keyword must always come before the type name, I see no reason not to allow it. Your example would parse `required` as the type.
> 
> ```cs
> public class required {}
> 
> class C
> {
>     public required required R { get; set; }
> }
> ```
> 
> This example would have the type `required` and the property `R` is required.
> 
> `required` then is a context-sensitive keyword.

This also make total sense if required is a context-sensitve keyword e must solve this "problem"

**Comment by 333fred** [comment]
LDM met today: https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-12-15.md#required-parsing. Conclusion: we will not allow types named `required` in C# 11 without using an `@` to escape, and we will not try to make the above scenario work.
