### ISSUE TITLE
Index of char is wrong while getting from the string using the String.IndexOf()

### ISSUE THREAD

**Issue by sampath-narayanan** [dotnet/csharplang#5442]
* .NET Core Version:   NetCore 5.0
* Windows version: windows 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No, only occurs in the NetCore 

 **Problem description:**
 
Index of char is wrong while getting from the string using the String.IndexOf(). This issue occurs only when we set the the region and regional format as the Thailand and thai language. 

![image](https://user-images.githubusercontent.com/88649640/140939392-f8bfe436-0f2f-4bdc-b593-854ffb92e776.png)

Mean while issue not occurs while setting region and regional format english language and unitedstates.

 **Actual behavior:** 
**Case 1:**
```
string v = "{Total items Count}:{10}";
n1 = v.IndexOf("}");
```
 Here, we will get the n1 as 0 which is wrong.

**Case 2:**
```
string v = "{Total items Count}:{10}";
n2 = v.IndexOf("}", 20);
```
Here, we will get n2 as 20, which is wrong.

 **Expected behavior:**
 
For the case one the expected output is 18

For the case two the expected output is 23

 **Minimal repro:**
Please refer the attached sample

Case 1:
1. Run the sample
2. Click the "Click the button get the initial index of  }"  to get the initial index of "}".

Case 2:
1. Run the sample
2. Click the "Click the button get the index of } where the start index will be 20" to get the index of  "}" after the index 20.

Please set the Region and regional format as thailand and thai before run the sample

[Sample.zip](https://github.com/dotnet/wpf/files/7505416/Sample.zip)

**Comment by ufcpp** [comment]
It is also not the C# issue.

@sampath-narayanan Use `StringComparison.Ordinal`.

```cs
string v = "{Total items Count}:{10}";
var n2 = v.IndexOf("}", 20, StringComparison.Ordinal);
```

See https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu

**Comment by koszeggy** [comment]
See also [this](https://stackoverflow.com/q/64833645/5114784) SO question.

**Comment by 333fred** [comment]
Closing this out, as previous commenters have answered the issue. In the future, this type of issue should be opened on dotnet/runtime.
