### ISSUE TITLE
Proposal: inheritance from array

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#548]
The current C# array is sealed, I want to remove this limitation and create classes inherited from array.
Somebody may ask, "Why not put array in your class?" 
My answer is that I want to reduce total object number and GC pressure. If I put an array in my class, then I have to create two objects when I instantiate my class: the class instance itself and the array. But if I can define a class inherited from an array, then I would be able to create only one object when instantiating it.
For example:
```C#
class A<T>:T[]
{
    int offset;
    ......
}
int main(string[] args)
{
   var a=new[args.Length] A<string>(); 
   /*I use the syntax "new[n]"  to express the inherited array's length in the new instance is n*/
   a[0]=args[0]; //I can use "a" as an array
   a.offset=1; //I can use "a" as a normal object
   ......
   var b=new[3] A<int>();
   ......
   b=new[4] A<int>();
   ......
}
```
This proposal seems like a C/C++ feature: zero-size array at the end of struct.
```C
struct A
{
    int offset;
    int array[0];
};

int main()
{
     struct A *a=(struct A*)malloc(sizeof(struct A)+100*sizeof(int));
     a->offset=1;
     a->array[0]=23;
     a->array[1]=32;
     ......
}
```

**Comment by svick** [comment]
I think that the idea of avoiding array allocations by combining them with another object might have some merit, but:

1. It should not be done through inheritance. The embedded array should be an implementation detail, not something so pervasive it even affects how you create instances of that class.
2. As far as I know, GC pressure is mostly about the number of allocated *bytes*, so this wouldn't help much.
3. The way C#/.Net has been heading to improve GC pressure when it comes to arrays is to use unmanaged memory and `Span<T>`. Does this have a use case that `Span<T>` would not satisfy?
