### ISSUE TITLE
Should we have Fraction object and literal supported in language?

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#553]
Lately I found that whenever we talk about struct feature. Fraction often came up as an example

Somehow I felt that Fraction actually useful. Normally approximate number with float. `3 * (1 / 3f)` is not became what we would expect. Floating point error need to be handled everywhere since we program in C

Most of the time we care about precision than the range of number. If we could naturally use `Fraction` in code it could make a lot of sense in many calculation logic

And instead of always making fraction on our own then overriding all operators just about conversion between each number type. I think it could be useful enough to have it built in into literal

```C#
struct Fraction64 { public int Number,Divider; }
struct Fraction128 { public long Number,Divider; }

Fraction64 f = 1 / 3r;
var three = 9 * f; // num:9 / div:3. Should it always find LCM or just did it when overflow?

Fraction128 = 1 / 7R; // Can we have literal r for small fraction and R for large one?

var one = 1r // 1 / 1. With literal it became easy to deal with when normally new it just became 0/0
```

ps. Should we also add `Algebraic` object too?

```C#
class Algebraic128
{
    public Fraction128 Value = 0 / 1R;
    public Algebraic Power = null;

    public static implicit operator double(Algebraic128 value) => Math.Pow((double)Value,Power ?? 1);
}

var a = 1A; // xxxA literal for algebraic
```

ps2. Should we name this feature `Fraction` or `Rational` ?
Actually I use `R` literal for Rational instinctively. So I think back that I should name this feature as `Ration`

**Comment by Thaina** [comment]
A little more idea

We actually could handle fraction like this

```C#
struct Fraction64
{
    uint divider;
    public int Number;
    public uint Divider { get => divider + 1; set => divider = value - 1 }

    public double Value { get => Number / (double)Divider; }
}
```

With this we will always handle negative only in number. And zeromemory will be 0 / 1

**Comment by lachbaer** [comment]
An individual NuGet package would be sufficient in my eyes, if anyone wants to create one.

Fraction is just a quite good example for a small value type that is invalid when standard constructed or defaulted. In this context many concepts can be shown nicely.

**Comment by Thaina** [comment]
@lachbaer Package library cannot add support to literal. It not natural and not be standard. This feature, if used, would be too deep reliance dependency. Being nuget make it risky to become like javascript leftpadding in npm

**Comment by alrz** [comment]
Related: http://0.30000000000000004.com/

**Comment by HaloFour** [comment]
Literal supports seems unnecessary here.  In fact, it seems downright confusing because you're basing a literal syntax off of an expression syntax.  Either operand of a binary expression can itself be an expression.

If you want fractions you are fully capable of expressing them today with simple structs.  Baking something into the BCL and the language would enshrine only one mechanism through which these structs would work.  Under the hood they'd still calculate to floating point values, which means that the result of using them in calculations would remain as imprecise as it always would.

**Comment by DavidArno** [comment]
@HaloFour 

The literal syntax is confusing. But it could avoid suffering from problems of representing simple base 10 numbers as base 2 floats, eg:
```cs
var x = 0.1r; 
var y = 0.2r; 
var z = x + y; 

var s = z.ToString(); //  0.3
```

**Comment by Thaina** [comment]
@HaloFour The actual literal syntax is only a number with literal. Not expression

I just make an assumption that this struct should support any number conversion, any operator that operate between `Rational` and normal number will be converted into `Rational` automaticcally like float

Actually it is

```C#
var f = 1 / 3f; // float 0.333333333333
var r = 1 / 3r; // rational 1/3
```

is the same as

```C#
var f = 1f / 3f; // float 0.333333333333
var r = 1r / 3r; // rational 1/3
```

Step by step is, compiler just know that `r` is literal for `Rational`. So 3r is rational. And so 1 / 3r would be converted into 1r / 3r;

I was normally write float for 1/3 like that so I just take it for grant. It should also work on `1r / 3` or `0.1r / 30` and so on

**Comment by Thaina** [comment]
@HaloFour Also I wish this feature would not use any floating point under the hood. I actually try to avoid it until we throw irrational number (`root`,`pi`,etc) to it. I think almost all number we deal with in financial and 

And as I was thinking about `class Algebraic` maybe we could do irrational thing with that

Maybe easier than that if we assume most of number we deal with would be only polynomial we could have `struct Irrational { Fraction Value,Power; }`

**Comment by tannergooding** [comment]
I think this is the type of proposal that needs to be provided as a NuGet package initially. Then, if it becomes widely used/popular, CoreFX would look at making it an official API. Finally, once it is an official API, C# could look at providing literal support.

I do agree that the type itself shouldn't be represented as a binary based float and instead would likely get represented by two integers (representing a Numerator and Denominator). However, there is some overlap with decimal based float (which IEEE 754:2008 does define, but proper support isn't provided in CoreFX currently). Decimal based float does not have the same rounding issues as binary-based floats, they just suffer from numbers which are not "exactly" representable (such as 1/3), which this proposal would correctly handle.

**Comment by HaloFour** [comment]
@Thaina @tannergooding 

Agreed, internally you'd be dealing with the representation of the fraction.  But at some point that representation must collapse to a value that can be used mathematically.  In my opinion neither the BCL nor the language should make the decision as to how that should happen and what intermediate values should be used.  Financial use cases would likely benefit from slower but more precise fixed point operations whereas scientific or gaming use cases would likely benefit from faster floating point operations.  And that can be narrowed down further between single/double/quadruple/native precision floating point or `decimal`-like fixed or `BigDecimal`-like infinite precision.  And both irrational and infinitely-repeating rational values would always be a sticking point.  In my opinion it's not the place of the language to decide on any of that via endorsement of a particular type and its implementation details.

**Comment by Thaina** [comment]
@HaloFour I expect this feature tobe literal so it would not be collapsed mathematically. It should be used and passed along as far as it can go mathematically

I wish that irrational struct could be used in graphics and physics simulation too. It based on rational. It could be collapsed only when we pass it to gpu. But on cpu it should stay as int

Also I'm not sure how fast 2*1 and 1*3 compare to 2/3f. I think flop is slower on cpu

**Comment by Joe4evr** [comment]
Doesn't `decimal` already do this? If I understand correctly, the reason that `decimal` is more accurate than `double` is because `decimal` actually stores a numerator and a denominator (which is probably the same reason that it's not `const`-assignable).

**Comment by jnm2** [comment]
Not exactly- `decimal` stores an integer with a decimal exponent instead of a binary exponent. So when it comes to `1/3`, decimal and binary are fundamentally in the same boat.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  If there is a proposal for an API it shoudl go to the libraries.  If that can happen, we could consider some sort of literal support for it in the future.

**Comment by Thaina** [comment]
@CyrusNajmabadi 
> If there is a proposal for an API it should go to the libraries

Sorry but I got confused here. You mean corefx?

**Comment by CyrusNajmabadi** [comment]
Sure. :)
