### ISSUE TITLE
Open questions for diagnostics for parameterless struct constructors

### ISSUE THREAD

**Issue by cston** [dotnet/csharplang#5546]
Questions around diagnostics for use of `new()` with parameterless struct constructors - see [LDM-2021-03-10](https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-03-10.md#parameterless-struct-constructors).

### Report diagnostic for `new()` when the struct type has constructors but no parameterless constructor?

Report a (warning wave) warning for use of `new()` when the type has constructors but no parameterless constructor?
(We’ve previously decided no warnings should be reported when substituting a struct type for a type parameter with `new()` or `struct` constraint however.)

```csharp
struct S
{
    public S(int b) { B = b; }
    public int A = 42;
    public int B;
}

record struct R(int X, int Y);

var s = new S(); // warning: not calling constructor?
var r = new R(); // warning: not calling constructor?
```

### Report diagnostic when `new()` does not invoke the parameterless constructor?

Report a warning or an error for parameter default value `new()` with a struct type with an explicit parameterless constructor since the constructor will not be invoked?

```csharp
struct S
{
    public S() { ... }
}

static void F(S s = new()) // warning or error: ignoring constructor?
{
}
```

**Comment by 333fred** [comment]
LDM Notes from this discussion: https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-12-15.md#warnings-for-parameterless-struct-constructor.

> #### Conclusion
> We'll look at doing an analyzer implementing a warning on structs with field initializers that do not generate a parameterless constructor, with some amount of heuristic suppression for scenarios where it is unavoidable.
