### ISSUE TITLE
Proposal/Discussion:  "Damnit" Postfix Operator (!)

### ISSUE THREAD

**Issue by HaloFour** [dotnet/csharplang#556]
This proposal/discussion is an addendum to #36 to make official the proposal of a "damnit" operator which can be used to forcibly unwrap a nullable value into a non-nullable value.

In the current non-nullable reference proposal it would cause a warning to be emitted if a nullable reference is passed/assigned to a non-nullable reference value where flow analysis cannot guarantee that the reference is not null.  In those cases the developer could use the postfix `!` operator to explicitly instruct the compiler that the value would not be `null` in that circumstance which would suppress the warning:

```cs
string? GetName() => ...;
void PrintName(string name) => Console.WriteLine(name);

string? name = GetName();
PrintName(name);   // emits warning
PrintName(name!);  // suppresses warning
```

For the sake of symmetry I also propose that this operator be available on nullable value types.  It would be equivalent to calling the `Value` property:

```cs
int? length = name?.Length;

int x = length!;  //  equivalent to length.Value or (int)length
```

### Open Questions:

1. Should the `!` operator cause an immediate exception if the value in question is `null`?

**Comment by jnm2** [comment]
> Should the ! operator cause an immediate exception if the value in question is null?

How would it make sense to not throw immediately?

**Comment by HaloFour** [comment]
@jnm2 

That's specifically in the case of a nullable reference type.  The compiler could simply accept that the developer knew what they were doing and pass the reference, even if it happens to be `null`.  It saves the cost of the comparison, but not really much else.

For nullable value types there really isn't an option; it will throw.

**Comment by jnm2** [comment]
If I declare a non-nullable reference parameter, I'd rather have the invariant enforced *outside* the method.

**Comment by whoisj** [comment]
While I still prefer to ban the whole concept of not nullable (sorry, I'm an old fashioned C guy and believe `null` is very useful), this is going to be the next best thing.

**Comment by whoisj** [comment]
> I'd rather have the invariant enforced outside the method.

How? From the time the value is validated, and the time everything is pushed to the stack, copied, and executed, another thread could have swept through and null'd the value.

**Comment by YaakovDavis** [comment]
Just having fun:
```
bool? a, b;
...
var x = !a! != b! ? a! : !b!;
```

**Comment by jnm2** [comment]
@whoisj 

> From the time the value is validated, and the time everything is pushed to the stack, copied, and executed, another thread could have swept through and null'd the value.

Nulled the stack of another thread?

**Comment by lachbaer** [comment]
> `var x = !a! != b! ? a! : !b!;`

Mh, despite how ridiculous it looks I must say that I understood it instantaneously. 😏

**Comment by lachbaer** [comment]
> Should the ! operator cause an immediate exception if the value in question is null

Yes, `!` states that programmer is knowing what she is doing - therefore the '!' character. In case of a Nullable `GetValueOrDefault()` *could* be called, but what method *should* be called on a reference type that is 'null' instead? `null` throws. Period! 😃

**Comment by janjoostvanzon** [comment]
> var x = !a! != b! ? a! : !b!;

I can read that. By the way: the last two dammit operators are redundant.

**Comment by lachbaer** [comment]
@janjoostvanzon 
> the last two dammit operators are redundant

No, they aren't. The condition `!a! != b!` is independent of the assignment to `var x`. To be sure that x is of type `bool` and not `bool?` both expressions must be surely of type `bool`, therefore the 'damnit' cast. Otherwise either the true or false part is of type `bool?` and thus the resulting type should be of type `bool?`.

If either of `a` or `b` is `null`, the condition will throw. Only in that regard they are redundant.

**Comment by janjoostvanzon** [comment]
@lachbaer:
I get it, it turns var from bool? into bool.
I guess I am not fluent yet in C# 7.?

**Comment by lachbaer** [comment]
> I guess I am not fluent yet in C# 7.

Neither am I 😃

**Comment by whoisj** [comment]
> Nulled the stack of another thread?

Depends on what they point to, so yeah. Also, there's no reason the expectation cannot be `value.nonNullValue != null`, then you're really hosed.

**Comment by jnm2** [comment]
@whois So same as the general problem with `(new string![1])[0]`.

**Comment by DavidArno** [comment]
Downvoting this in favour of my own proposal of the [*as pattern*](https://github.com/dotnet/csharplang/issues/402), which covers this use-case without having to overload the meaning of `!`:
```cs
string? GetName() => ...;
void PrintName(string name) => Console.WriteLine(name);

string? name = GetName();
PrintName(name);   // emits warning
PrintName(name as string);  // suppresses warning
```

**Comment by DavidArno** [comment]
Why would we want to overload `!`, creating hard to read code, when `as` (with minor tweeking) already serves this purpose:
```cs
string? GetName() => ...;
void PrintName(string name) => Console.WriteLine(name);

string? name = GetName();
PrintName(name);   // emits warning
PrintName(name as string);  // suppresses warning
```

**Comment by DavidArno** [comment]
> > the last two dammit operators are redundant

> No, they aren't. 

I disagree. Since the expression, `!a! != b!` will have already determined that `a` and `b` are not `null` (since an exception would have been thrown if they were), then there'd be no need to "re-damnit" them in the rest of the ternary expression. They can safely be converted from `T?` to `T`.

**Comment by YaakovDavis** [comment]
> will have already determined that `a` and `b` are not `null`

The compiler is generally not smart enough to infer types based on flow. Consider the following:
```
int? a = 5;
if(a != null)
{
   int b = a!;
}
```

The `!` is still needed in inside the `if`, even though one can tell from the flow that `a` can't possibly be null.

**Comment by DavidArno** [comment]
@YaakovDavis,

That's a fair point. Though just because the compiler can't infer types across statements, it probably could be made to do so within a ternary expression much more simply.

As an aside, your code example still doesn't need the "dammit operator", as `is` can be used:
```cs
int? a = 5;
if(a is int b)
{
    // safely use b here
}
```
(I appreciate your code was to illustrate a different point, but it highlights how a new operator probably isn't needed, too).

**Comment by YaakovDavis** [comment]
> a new operator probably isn't needed, too

Well, there's a good substitute for it when null testing is involved (as in the example above), but in some scenarios you might just want to coerce a non-null value, based on arbitrary logic. 

Just as we have the `Value` property for nullable value-types, I agree with the OP that there should be a corresponding mechanism for nullable reference-types.

**Comment by alrz** [comment]
as an alternative to `var x = length!;` I've suggested `var! x = legnth;` which can be also used in patterns to null-guard a var pattern (#306).

**Comment by HaloFour** [comment]
@YaakovDavis 

Said flow has been suggested for nullable reference types.  If the compiler can determine definitively that a variable of a nullable reference type is not null then it can be used as a non-nullable reference without causing the warning.

I do not know if such logic could also apply to nullable value types.  That would be a little more involved as they are different types.  It could also impact existing code.  At most maybe the compiler would allow an implicit cast from the nullable value type to the normal value type without an explicit cast.

**Comment by YaakovDavis** [comment]
@HaloFour 

The usefulness of such "definite determinations" is dependent upon the percentage of cases the compiler can cover.
If the percentage is not high enough, you end up with a confusing codebase, where the reader has to do the hard work, reasoning about every piece of code to understand the actual type.
This is worse than no "automatic inference".

Personally, I'd prefer predictability over "smartness".

**Comment by HaloFour** [comment]
@YaakovDavis 

That is the behavior as described by the LDM regarding nullable reference types.  It's been stated that the type of a nullable reference isn't any different, only it's potential state of nullability.  But if flow analysis can eliminate the possibility of `null` then the compiler can treat the variable as non-`null` and suppress any warnings.

All I'm proposing in my comment above is that it might be possible to extend that behavior to nullable value types.  But I admit that it's a little further of a stretch given that the type is actually different and that impacts such things as overload resolution.  At most the compiler could treat it as `Nullable<T>` but also implicitly cast-able to `T`.

Of course if nullable reference types don't follow that model then it doesn't make any sense for nullable value types to.

**Comment by YaakovDavis** [comment]
> It's been stated that the type of a nullable reference isn't any different

I wasn't aware of this, I should get myself more familiar with the original proposal.

**Comment by HaloFour** [comment]
@YaakovDavis 

Here's the relevant blurb:

> A flow analysis tracks nullable reference variables. Where the analysis deems that they would not be null (e.g. after a check or an assignment), their value will be considered a non-null reference.

And I also see that they did mention the "damnit" operator.  I missed that on previous inspection, possibly due to the difference in spelling:

> A nullable reference can also explicitly be treated as non-null with the postfix x! operator (the "dammit" operator), for when flow analysis cannot establish a non-null situation that the developer knows is there.

So that makes the above proposal moot.  Although I think I'll reopen it to explore how the same concepts could apply to nullable value types.
