### ISSUE TITLE
Question: discard result of void-returning method

### ISSUE THREAD

**Issue by stepanbenes** [dotnet/csharplang#567]
I recently discovered that the following is valid C# 7 code:
```C#
void Method()
{
...
}
void OtherMethod()
{
    _ = Method();
}
```
I use new language feature discards quite often to explicitly state that I don't care about the result of a method. What confused me is that it is also applicable to void-returning methods. I find it misleading as the first look on code suggests that the Method returns something.

I would like to ask what reasons has led to this design.

**Comment by DavidArno** [comment]
[It's a bug and will be fixed with the next release of the compiler](https://github.com/dotnet/roslyn/issues/17674).

**Comment by stepanbenes** [comment]
Ok, thanks.
Fixing it would be a breaking change though, but I think it is justified.
