### ISSUE TITLE
Open question for shadowing field keyword in semi auto property

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#5703]
I do think we should ask the LDM what this code means though:

```cs
int Prop
{
    set
    {
        field = value;
        {
            int field = 0; // Does this shadow the backing field? Or is there an error reported somewhere?
        }
    }
}
```

_Originally posted by @333fred in https://github.com/dotnet/roslyn/pull/59109#discussion_r793916686_

**Comment by 333fred** [comment]
Added to the agenda for next Wednesday.

**Comment by 333fred** [comment]
LDM conclusion: `field` can be shadowed by parameters or locals in a nested scope.

https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-02-16.md#open-questions-in-field
