### ISSUE TITLE
Compiler breaks when constant name is the same as type name

### ISSUE THREAD

**Issue by deimastep** [dotnet/csharplang#571]
**Version Used**: VS 2017 version 15.2 release 26430.4

**Steps to Reproduce**:

1. Start build this code in .Net Core console project "Test"
```csharp
using System.Text.RegularExpressions;
// ...
const RegexOptions RegexOptions = RegexOptions.CultureInvariant | RegexOptions.IgnoreCase;
var regex = new Regex(@"\s*", RegexOptions);
```

**Expected Behavior**:
Should be compiled.
If I remove `const` everything is fine:
```csharp
RegexOptions RegexOptions = RegexOptions.CultureInvariant | RegexOptions.IgnoreCase;
var regex = new Regex(@"\s*", RegexOptions);
```

**Actual Behavior**:
Compiler just emits message:
`CSC : error CS7038: Failed to emit module 'Test'.`

**Comment by lachbaer** [comment]
You can put this in the [dotnet/roslyn](https://github.com/dotnet/roslyn) repo as an issue.

**Comment by deimastep** [comment]
Ok, did that. Thanks.
