### ISSUE TITLE
Proposal One element tuple syntax

### ISSUE THREAD

**Issue by phillyai** [dotnet/csharplang#575]
We should use ValueTuple<T> constructor to create one element tuple like this.
```csharp
var a = new ValueTuple<int>(1);
```
How about add syntax like python?
```csharp
var a = (1,)
```

**Comment by orthoxerox** [comment]
Should womples differ from scalar values at all? Is there a case where they *shouldn't* be equivalent?

**Comment by svick** [comment]
One-element tuples were previously discussed at LDMs [in 2016](https://github.com/dotnet/csharplang/blob/master/meetings/2016/LDM-2016-04-06.md#syntax-for-0-tuples-and-1-tuples) and [in 2017](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-03-15.md#0-and-1-element-tuples), though those notes don't say much. They don't even mention the `(1,)` syntax.

**Comment by phillyai** [comment]
I think this issue should be closed until when tuple can be descontructed into element and tuple. Like, `var (a, *b, c) = (1, 2, 3, 4, 5)`

**Comment by phillyai** [comment]
I was thinking wrong. I was thinking tuple as list.

**Comment by kofifus** [comment]
+1 I think that's a good idea

**Comment by palenshus** [comment]
Can this be reopened?

**Comment by jnm2** [comment]
This might be able to serve as that open discussion: https://github.com/dotnet/csharplang/discussions/4668

Otherwise, this issue would need to get converted into a discussion, since issues are now for specs only.
