### ISSUE TITLE
Proposal: Associate enum with string

### ISSUE THREAD

**Issue by andrew-vdb** [dotnet/csharplang#576]
Let's make this working
```
enum Operator
{
    Equal = "=",
    MoreThan= ">=",
    ...
}
```

At this moment, this is not possible, some people do workaround with reflection or making a new class
or use attribute or make some converter method to string

**Comment by svick** [comment]
Are you saying you want an `enum` whose underlying type is `string`? If you wanted that to work the same as other `enum` types, then that would require modifications to the CLR and I think also metadata format (i.e. ECMA-335).

> some people do workaround with reflection or making a new class or use attribute or make some converter method to string

Could you explain what's wrong with those workarounds?

**Comment by mattnischan** [comment]
How would this be different than a static class with consts?

```csharp
public static class Operator
{
    public const string Equal = "=";
    public const string MoreThan = ">=";
}
```

**Comment by khellang** [comment]
@mattnischan That would mean your APIs has to take a `string` argument, which means you could pass any string into it. It's also not very good for IntelliSense and discovery. C#'s enum still allows you to pass any value of the underlying type, casted to the enum type, though.

This can easily be "worked around" by using a Java-style [Enumeration class](https://github.com/HeadspringLabs/Enumeration/blob/master/Enumeration.cs).

**Comment by mattnischan** [comment]
@khellang I see what you're getting at, and I hadn't considered that angle specifically. However, I'm still trying to understand the use case a bit. Is it just to be able to cast to a string later? In any case, I suppose it could compile to something like:

```csharp
public struct Operator
{
    private const string _equal = "=";
    private const string _greaterThan = ">";

    public static readonly Operator Equal = new Operator(_equal);
    public static readonly Operator GreaterThan = new Operator(_greaterThan);

    private string _value;

    public Operator(string value)
    {
        _value = value;
    }

    public static implicit operator string(Operator obj)
    {
        return obj._value;
    }

    public static implicit operator Operator(string obj)
    {
        switch (obj)
        {
            case _equal:
                return Equal;
            case _greaterThan:
                return GreaterThan;
            default:
                throw new InvalidCastException($"Provided string {obj} cannot be converted to {nameof(Operator)}");
        }
    }

    //GetHashCode, ==, etc. here
}
```

**Comment by Thaina** [comment]
@mattnischan Sure we could do that. But that was reinventing the enum

**Comment by Thaina** [comment]
But on the other hand I would find it easier to add extension method to enum map with string

enum Operator
{
    Equal,MoreThan,...
}

public static class OperatorExt
{
    public string AsString(this Operator op) => switch() return;
    public bool TryParse(string text,out Operator op) => switch() return;
}

**Comment by mattnischan** [comment]
@Thaina Not reinventing. I was just saying that Roslyn could lower `enum Operator : string` into that struct form. That would be an easier addition than the runtime changes needed to actually support something like (in IL):

```csharp
.class public Operator extends [mscorlib]System.Enum
{
    .field public specialname rtspecialname string _val
    .field public static literal valuetype Operator Equal = "Equal"
    .field public static literal valuetype Operator GreaterThan = "GreaterThan"
}
```

In fact, that's not even valid standard CIL. Per the ECMA spec:

>  The symbols of an enum are represented by an underlying integer type: one of { bool, char, int8, unsigned int8, int16, unsigned int16, int32, unsigned int32, int64, unsigned int64, native int, unsigned native int }

So, now you have spec and runtime changes. Much easier to lower it into a compile time generated struct.

**Comment by Joe4evr** [comment]
> This can easily be "worked around" by using a Java-style Enumeration class.

The problem with that, though, is that [Java has a patent on their implementation](https://www.google.com/patents/US7263687) (which gafter knows all about 🙃).

**Comment by khellang** [comment]
I'm not saying that this should necessarily be included in the language, but that you can work around it in your own code, with relative ease :smile:

**Comment by mattnischan** [comment]
> with relative ease
Depends on your situation. If you want to make your string "enum" a struct (which real enums are), you're going to have to repeat the code every single time, which is pretty annoying.

**Comment by Unknown6656** [comment]
I think it is possible with the current CLR version. The CLR allows string constants (they are stored byte-wise in CLI code). One would "just" have to loosen the restriction on `enum`s to accept any (internal) binary constant.

> The problem with that, though, is that Java has a patent on their implementation (which gafter knows all about 🙃).

Microsoft should patent any form of efficient and intelligent programming features -- that would be the end for Java's future. :trollface:

**Comment by Jehoel** [comment]
With apologies for thread-necromancy - I was googling this problem after getting frustrated with some `const String`s in my current project.

I feel C#/.NET's current `enum` is a bad design because it provides no hard guarantees about the value contained within (i.e. how we can cast any arbitrary integer to any `enum` type with a matching underlying type). My fingers are getting tired of always having to add a `default: throw new ArgumentOutOfRangeException` every time I `switch` on an enum.

A better long-term solution would be TypeScript-style algebraic types where values participate in the type definition - but also allowing named members - this would also work for integer enums - and as a first-class implementation of discriminated unions (see https://github.com/mcintyre321/OneOf ).

This could also be used to implement strongly-typed type-aliases too.

So instead of the proposed:

    enum CarMake : String
    {
        Ford = "Ford",
        GM   = "General Motors",
        Toyota = "Toyota",
        Skoda = "Skoda"
    }

or an unlabelled TypeScript typedef:

    type CarMake = "Ford" | "General Motors" | "Toyota" | "Skoda"

We'd have:

    type CarMake
    {
        String Ford = "Ford",
        String GM = "General Motors",
        String Toyota = "Toyota",
        String Skoda = "Skoda"
    }

(Of course the `String` type declarations wouldn't have to be uniform)

A type like this wouldn't require any CLR changes if it's implemented as its own class type (like how `ValueTuple` works) and the `switch` operator would be overloaded for types like these such that the compiler enforces exhaustive branching (if applicable, e.g. in a `Match` role) and no-longer requires a `default` case.

**Comment by KalleOlaviNiemitalo** [comment]
See also #2849.

**Comment by YairHalberstadt** [comment]
I'm going to close this as a 'duplicate' of #2849. Although this is earlier, that issue is more detailed, so I think it's best to continue conversation there.
