### ISSUE TITLE
Method Chaining

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#577]
I would like to request that C# allow additional invocations on methods that return void.  Related, I would like to be able to call Setter members as if they were functions.  

If the Method is an instance method, the instance method should be "returned" by void.
If the Method is a static method, the static class should be "returned" by void.

  For example:
````
Console.WriteLine("Hello World");
Console.BackgroundColor = ConsoleColor.Green;
Console.WriteLine("Hello Green World");
````

should be able to be written as:
````
Console
    .WriteLine("Hello World")
    .BackgroundColor(ConsoleColor.Green)
    .WriteLine("Hello Green World")
    ;
````            
This would bring Fluent APIs to the existing C# codebases.
This would not break existing code because in existing code, you cannot "dot" off of void returns.

**Comment by svick** [comment]
> I would like to be able to call Setter members as if they were functions

What happens when the type of the property is a delegate?

```c#
static class C
{
    public static Action<object> P { get; set; }
}

…

Action<object> a = o => {};
C.P(a);
```

This is already valid syntax, which gets the property and then invokes the delegate, passing `a` as parameter (implicitly converting from `Action<object>` to `object`). But you would want to use the same syntax to set the property?

**Comment by YaakovDavis** [comment]
Proposed [here](https://github.com/dotnet/roslyn/issues/8947) with a slightly different syntax.

**Comment by YaakovDavis** [comment]
And [here](https://github.com/dotnet/roslyn/issues/16961).

**Comment by DavidArno** [comment]
If really don't see how:
```cs
Console
    .WriteLine("Hello World")
    .BackgroundColor(ConsoleColor.Green)
    .WriteLine("Hello Green World")
    ;
```
is more readable, or in any way offers any other benefits over:
```cs
using static System.Console;
...
WriteLine("Hello World");
BackgroundColor = ConsoleColor.Green;
WriteLine("Hello Green World");
```
