### ISSUE TITLE
Discussion: 'switch' on multiple parameters

### ISSUE THREAD

**Issue by niklaskarl** [dotnet/csharplang#579]
Lets suppose you have two enums _Foo_ and _Bar_ and want to implement a conditional operation based on a combination of those enums. Today you would do something like a nested switch:

``` cs
Foo foo;
Bar bar;

switch (foo)
{
    case Foo.Value1:
        switch (bar)
        {
            case Bar.Value1:
                // do something
                break;
            case Bar.Value2:
                // do something else
                break;
            default:
                throw new NotSupportedException();
        }

        break;
    case Foo.Value2:
        switch (bar)
        {
            case Bar.Value1:
                // do something
                break;
            case Bar.Value2:
                // do something else
                break;
            default:
                throw new NotSupportedException();
        }

        break;
    default:
        throw new NotSupportedException();
}
```

Pretty ugly and not very intuitive to read. I would suggest allowing multiple parameters in the switch like this:

``` cs
Foo foo;
Bar bar;

switch (foo | bar)
{
    case Foo.Value1 | Bar.Value1:
        // do something
        break;
    case Foo.Value1 | Bar.Value2:
        // do something else
        break;
    case Foo.Value2 | Bar.Value1:
        // do something
        break;
    case Foo.Value2 | Bar.Value2:
        // do something else
        break;
    default:
        throw new NotSupportedException();
}
```

I understand that the vertical bar character (|) already has a different meaning in C# and cannot be used as a separator. I'm expecting your suggestions on this :)

Additionaly you could allow wildcards that match all values:

``` cs
Foo foo;
Bar bar;

switch (foo | bar)
{
    case Foo.Value1 | Bar.Value1:
        // do something
        break;
    case Foo.Value1 | Bar.Value2:
        // do something else
        break;
    case Foo.Value2 | *:
        // do something
        break;
    default:
        throw new NotSupportedException();
}
```

Mixed with pattern matching this would be a pretty powerful construct. What do you think? I'm looking forward for your comments and ideas.

**Comment by HaloFour** [comment]
With recursive patterns you could just `switch` on a tuple.

**Comment by jnm2** [comment]
I was going to say, switching on a tuple seems ideal both from a conceptual perspective as well as allowing a performance boost in cases where the compiler can internally left shift one of the values and or them together to create a jump table.

**Comment by jnm2** [comment]
This would be not only a readability boost but also a performance enhancement if some or all cases can be converted to a single jump table.

I would also request that a single jump table could be created for any combination of enums, ints and especially booleans. When you have one enum and two or three booleans and you need a case for every permutation, you really want this feature.

**Comment by DavidArno** [comment]
In addition to the fact that this will be possible with tuples when recursive patterns are added to C#, it's already possible to use a dictionary with a tuple key instead of a switch:
```cs
private static readonly Dictionary<(Foo, Bar), Action> Actions =
    new Dictionary<(Foo, Bar), Action>
    {
        [(Foo.Value1, Bar.Value1)] = DoThingOne,
        [(Foo.Value2, Bar.Value1)] = DoThingTwo,
        [(Foo.Value1, Bar.Value2)] = DoThingThree,
        [(Foo.Value2, Bar.Value2)] = DoThingFour
    };

if (!Actions.ContainsKey((foo, bar))) throw new NotSupportedException();
Actions[(foo, bar)]();
```

**Comment by bondsbw** [comment]
Good idea.  FWIW this isn't so terrible today (though I still like this proposal better):

```c#
switch (foo)
{
    case Foo.Value1 when bar == Bar.Value1:
        // do something
        break;
    case Foo.Value1 when bar == Bar.Value2:
        // do something else
        break;
    case Foo.Value2 when bar == Bar.Value1:
        // do something
        break;
    case Foo.Value2 when bar == Bar.Value2:
        // do something else
        break;
    default:
        throw new NotSupportedException();
}
```

**Comment by lachbaer** [comment]
@DavidArno yours doesn't look as nice as a classical `switch` 😛 😉

**Comment by DavidArno** [comment]
@Lachbaer,

That's what makes measuring readability so hard. In my world, `switch` is a clunky procedural construct that has no place in my code. I've been using dictionaries of actions & funcs instead for years as they are so much nicer on the eye in my view. 😎

However now `switch` has basic pattern support and `when` clauses, I've started using them again. If only those hideous `breaks` could be got rid of.

**Comment by neofuji** [comment]
> I understand that the vertical bar character (|) already has a different meaning in C# and cannot be used as a separator. I'm expecting your suggestions on this :)

Can `,` be used instead of `|`?

```cs
Foo foo;
Bar bar;

switch (foo, bar)
{
    case Foo.Value1, Bar.Value1:
        // do something
        break;
    case Foo.Value1, Bar.Value2:
        // do something else
        break;
    case Foo.Value2, _:
        // do something
        break;
    default:
        throw new NotSupportedException();
}
```
However I also agree on just using tuples.

**Comment by gafter** [comment]
The pattern-matching  extensions for C# 8 support switching on tuples in both the switch statement and the new switch expression. They are prototyped in the Roslyn branch `features/recursive-patterns`.
