### ISSUE TITLE
[Request] Merge the LDM meeting notes via pull requests

### ISSUE THREAD

**Issue by alexpolozov** [dotnet/csharplang#584]
On CodePlex and [dotnet/roslyn](https://github.com/dotnet/roslyn), the team used to create dedicated threads for LDM discussion notes. The community could then discuss these notes specifically in the thread, providing feedback toward specific decisions made by the team in that meeting.

Here, @MadsTorgersen started pushing LDM discussion notes directly to master. Thus, they mostly remain unnoticed, barring the cases when the champion for a particular feature updates its spec or creates new issue threads after an LDM (shoutout and kudos to @gafter here 🙂).

I humbly suggest that the LDM notes should be merged to master via pull requests, just like the rest of spec/proposal modifications. Also, it would be nice if every PR thread would stay _open_ for a week or so _after it's merged_, so that it could serve as a hub for any LDM-related feedback from the community.

Thanks a lot for your consideration!

**Comment by yaakov-h** [comment]
How do you keep a PR open after merging? Or do you mean that after a week or so it would be locked?

**Comment by apskim** [comment]
Ah, sorry. I thought the PR state (merged/unmerged) and the corresponding discussion state (open/closed) were different, but looks like they are not. You can still comment on a merged PR, but it's not as discoverable.
Maybe the team can create dedicated discussion threads in the Issues for each LDM, and close/lock them after a week?

**Comment by jnm2** [comment]
I really liked the discussion threads they used to create.

**Comment by DavidArno** [comment]
Good point re merging a PR closes it. So discussion threads would be the way forward.

It would be good if the team created them, but there is nothing to stop the rest of us doing so if they don't.

**Comment by alexpolozov** [comment]
The discussion threads are now appearing regularly; thanks, @MadsTorgersen!
