### ISSUE TITLE
Proposal: dynamic array with lazy reallocation feature

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#586]
The current C# array can "resize", but it acturally allocates new memory and copies data, and the old memory can neither be freed nor be used until next GC. 
I hope to have a kind of dynamic array which can change its length without memory reallocation until next GC. When this kind of array extend its length, only allocate memory of "extended" size, and use an internal list to manage the old and new memory. Users needn't know how many internal fragments the dynamic array has, they should be able to use it as a normal array. When GC occurs, the CLR should put all fragments of a dynamic array together and update internal link pointers. If the dynamic array reduces its length, the CLR should be able to "free" some memory after next GC.
All these CLR actions should be transparent to users. 
The dynamic array should be a new class, and do not affect the behavior of the current array.
For example:
```C#
DynamicArray<int> da=new DynamicArray<int>(100); //length is initialized to be 100
......
da.Resize(200); 
/*new size is 200, but only allocate new memory of size 100. Old memory is still in use and links to new memory. Now 'da' has internal fragments, but it will have contiguous memory of size 200 after next GC. */
......
da.Resize(10);
/* No allocation. Free memory of size 190 after next GC. */
```

**Comment by HaloFour** [comment]
This belongs on the [CoreCLR](https://github.com/dotnet/coreclr) repo as this doesn't suggest any changes to the C# language but it does propose some radical changes to CLR arrays.

That said, I don't see how this will be possible.  CLR arrays are expected to be a contiguous block of memory.  It's expected that you can perform unsafe operations via pointers directly over the contents of the array.  I don't see how this proposal is compatible with that behavior.

**Comment by benaadams** [comment]
@HaloFour maybe [CoreFx](https://github.com/dotnet/corefx) as an api request?

Could be a List\<T> type linked array collection with fixed array allocations 

`[N array] -> [N array] -> [N array] -> null`

**Comment by HaloFour** [comment]
@benaadams

Also fine, although I don't think making a new collection that is like `LinkedList<List<T>>` is exactly in the same spirit as the proposal above.

**Comment by ygc369** [comment]
@benaadams 
Before GC, the dynamic array is what you said. But when GC happens, the CLR should put all the blocks together to be a contiguous array.

**Comment by ygc369** [comment]
@HaloFour 
I ask for a new class DynamicArray which encapsulates the CLR behavior I described above

**Comment by benaadams** [comment]
K, that's more fancy :) 

@ygc369 should be raise issue in [corefx](https://github.com/dotnet/corefx) as api request rather than csharplang as is a api+runtime rather than language feature (i.e. would be a data type that would work same in all languages and need no language syntax that's specific to C#).
