### ISSUE TITLE
Is C# 7.1 available in preview?

### ISSUE THREAD

**Issue by DavidArno** [dotnet/csharplang#590]
Not sure if this is a good use of an issue here, but here goes 😁 

At a conference yesterday, I was listening to Kathleen Dollard. She was of the impression that a preview release of VS with C# 7.1 was available. I'd not heard of this though and thought that 7.1 was coming with VS 20017 update 4 and that there wouldn't be a preview. To further confuse things update 3 is out, yet [@gafter has a tentative list of feature for 7.1 coming with that already shipped update](https://github.com/dotnet/csharplang/blob/master/Language-Version-History.md).

Anyone have any idea which is the correct version of events here?

**Comment by alrz** [comment]
That list is already merged in. https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md

**Comment by svick** [comment]
As far as I can tell:

* The current version of VS 2017 Preview (a.k.a. VS 15.3 Preview) contains a very limited preview version of C# 7.1, which, just like [the language features table in its branch](https://github.com/dotnet/roslyn/blob/Visual-Studio-2017-Preview-Version-15.3/docs/Language%20Feature%20Status.md) suggests, only contains default expressions.
* The version of Roslyn available from the [Roslyn MyGet](https://dotnet.myget.org/gallery/roslyn) contains the features in the [language features table in the master branch](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md).
   * You can fairly easily try it yourself on .Net Core by adding the Roslyn MyGet to a NuGet.config and then referencing a recent prerelease version of the `Microsoft.Net.Compilers` package (currently version `3.0.0-dev-61716-08`).
   * This means the following code compiles:

      ```c#
      class Program
      {
          static async Task Main() // async Main
          {
              int a = default, b = 42; // default expressions
              var t = (a, b);
              Console.WriteLine(t.a); // infer tuple names
          }

          bool M<T>(T t) => t is string s; // pattern matching with generics
      }
      ```
* In both cases, you have to switch the language version from `default` to `latest` either in the UI or by adding `<LangVersion>Latest</LangVersion>` to the csproj.

**Comment by DavidArno** [comment]
Thanks @svick, that clarifies things.

**Comment by jcouv** [comment]
@svick is correct. Only default literal made it into preview 1.

Preview 2 will have all the [C# 7.1 features](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md#c-71) (async Main, inferred tuple names, and pattern matching on a generic type).

You don't have to edit your project file or project settings, there is now a codefixer which offers you to change the LangVersion in your project(s) when you use a new feature.

I assume it's ok to close the issue now. Feel free to re-open if needed.

**Comment by shanselman** [comment]
Nice. I prefer `<LangVersion>7.1</LangVersion>` though.

**Comment by DavidArno** [comment]
@shanselman,

I prefer to use `<LangVersion>latest</LangVersion>`. That way, when C# 7.2/8.0 is released, I don't need to update my project again to take advantage of that version's features.

@jcouv,

The current "fix" produces a lot of "fluff" in the project file: 
```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
  <LangVersion>latest</LangVersion>
</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  <LangVersion>latest</LangVersion>
</PropertyGroup>
```
Is this likely to be improved in a future release to just add `<LangVersion>latest</LangVersion>` to the standard, non-conditional, `<PropertyGroup/>`?

**Comment by jnm2** [comment]
@jcouv This isn't the only thing that inserts conditional sections. Almost anything I do in the properties page does this and I have to manually clean up the mess, so it's never even worth the time opening the properties page. Is this going to be fixed?

For example, it's extremely unusual and weird for AllowUnsafeCode to be conditional on build configuration. That's \*always\* an error when I see it happen.

**Comment by CyrusNajmabadi** [comment]
Project file issues should be filed over at https://github.com/dotnet/project-system.  Thanks!

**Comment by jcouv** [comment]
Filed https://github.com/dotnet/project-system/issues/2732 for the fluff issue in csproj

**Comment by jnm2** [comment]
You're awesome @jcouv. 🎉
