### ISSUE TITLE
Open question for semi auto properties (static local functions or lambdas containing `field`)

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#5923]
For example:

```csharp
using System;
public class C
{
    public static int P
    {
        get
        {
            Func<int> f = static () => field;
            Console.WriteLine(f());
            return 0;
        }
    }
}
```

Should static lambdas or local functions be able to access `field`? And if so, should they be able to force `field` to be created if it wouldn't otherwise exist?

Raised in review: https://github.com/dotnet/roslyn/pull/59767#discussion_r827161006

cc @333fred

**Comment by 333fred** [comment]
Address in LDM March 21st, 2022: https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-03-21.md#open-question-in-semi-auto-properties
