### ISSUE TITLE
In case a T :  D then nameof(C<T>.P.X) cannot be replaced with nameof(C<>.P.X) as T is unspecified.  The compiler should assume T is D and only when D has a X nameof(C<>.P.X) is equivalent to nameof(C<D>.P.X) otherwise you need to specify the generic type parameter to access X.

### ISSUE THREAD

**Issue by Chrobob-777** [dotnet/csharplang#5944]
In case a T :  D then nameof(C<T>.P.X) cannot be replaced with nameof(C<T>.P.X) as T is unspecified.  The compiler should assume T is D and only when D has a X nameof(C<T>.P.X) is equivalent to nameof(C<T>.P.X) otherwise you need to specify the generic type parameter to access 

_Originally posted by @qsdfplkj in https://github.com/dotnet/csharplang/discussions/702#discussioncomment-2418104_

**Comment by jnm2** [comment]
Discussion should stay at https://github.com/dotnet/csharplang/discussions/702#discussioncomment-2418104, please.
