### ISSUE TITLE
void switch expression

### ISSUE THREAD

**Issue by natilivni** [dotnet/csharplang#5951]
The switch expression syntax introduced in c# 8 is fantastic for writing readable and compact switch statements which are not unnecessarily verbose. 

However, one limitation of this syntax is the assumption that the statement must return a value.

I propose that we allow the switch expression to call void methods as follows:

```
i switch {
  1 => method1(), 
  2 => method2(), 
  _ => method3()
};
 ```

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/discussions/2181
