### ISSUE TITLE
Pattern matching with UTF-8 String Literals

### ISSUE THREAD

**Issue by tmds** [dotnet/csharplang#6037]
[C# 11 preview blog post](https://devblogs.microsoft.com/dotnet/csharp-11-preview-updates/) includes _UTF-8 String Literals_, and _Pattern matching with spans_ (specifically: `[ReadOnly]Span<char>`).

It would be interesting if both can be combined, allowing pattern matching against `[ReadOnly]Span<byte>`.

For example:

```cs
static HttpMethod ParseHttpMethod(ReadOnlySpan<byte> method)
{
    return method switch { 
        "GET"  => HttpMethod.Get, 
        "POST" => HttpMethod.Post, 
...
        _ => HttpVerb.Unknown };
}
```

This is interesting for use-cases that involve parsing UTF-8.

cc @KathleenDollard

_Originally posted by @tmds in https://github.com/dotnet/csharplang/discussions/6036_

**Comment by tmds** [comment]
cc @davidfowl

**Comment by RikkiGibson** [comment]
Moving discussion back to the discussion thread for now. Thanks!
