### ISSUE TITLE
Property Observers in C# like Swift

### ISSUE THREAD

**Issue by HamedFathi** [dotnet/csharplang#604]
In Swift to observe and respond to property values Property Observers are used. Each and every time when property values are set property observers are called. Except lazy stored properties we can add property observers to 'inherited' property by method 'overriding'.

Property Observers can be defined by either.

- Before Storing the value - willset.
- After Storing the new value - didset.

When a property is set in an initializer willset and didset observers cannot be called.

```
public class Sample {

 public int Value {
  get;
  set;
  beforeSet(value) {
   Console.WriteLine($ "Total Counter is: ${value}");
  }
  afterSet {
   if (counter > value) {
    Console.WriteLine($ "Newly Added Counter {counter - oldValue}");
   }
  }

 }
}
```

This can be more useful than IPropertychanged and I think can be a very very small way to gathering AOP programming based on C# syntax.

**Comment by HaloFour** [comment]
Why is this an improvement on writing that logic in the setter/getter methods?  It's not like you can observe the changes of other instances, so it doesn't cover the same use cases as `INotifyPropertyChanged`.  It seems like some weird middle ground between auto-implemented properties and normal properties but the verbosity isn't much of an improvement over normal properties.

**Comment by jnm2** [comment]
I'd much rather have the `field` keyword and write:

```c#
public int Value
{
    get;
    set
    {
        Console.WriteLine($"Total Counter is: {value}");

        var oldValue = field;
        field = value;

        if (counter > value)
            Console.WriteLine($"Newly Added Counter {counter - oldValue}");
    }
}
```

Or even in this case:


```c#
public int Value
{
    get;
    set
    {
        Console.WriteLine($"Total Counter is: {value}");
        if (counter > value)
            Console.WriteLine($"Newly Added Counter {counter - field}");
        field = value;
    }
}
```

**Comment by Thaina** [comment]
@jnm2 Is that #318 ?

I don't like `field` keyword. #318 should just be enough

**Comment by quinmars** [comment]
@jnm2

I like the idea of the of the `field` keyword. Implementing the `INotifyPropertyChanged` interface still involves some (imho too much) boiler plate code, although it already was improved in the last years.
Making a property observable needs today something like the following code:

```csharp
private IEnumerable<EmployeeViewModel> _Employees;
public IEnumerable<EmployeeViewModel> Employees
{
	get => _Employees;
	set => SetField(ref _Employees, value);
}
```

With the field keyword this could become:

```csharp
public IEnumerable<EmployeeViewModel> Employees
{
	get;
	set => SetField(ref field, value);
}
```

@Thaina

With proposal #318 it would look like that:

```csharp
public IEnumerable<EmployeeViewModel> Employees
{
	IEnumerable<EmployeeViewModel> field;
	get => field;
	set => SetField(ref field, value);
}
```
	
You still have to repeat the type for the backing field and you have to declare the backing field. I definitely prefer @jnm2 proposal. The only problem I see, is that the `field` keyword can already be used as a variable name, which makes it hard to introduce it now as a contextual keyword.

**Comment by Thaina** [comment]
> The only problem I see, is that the field keyword can already be used as a variable name, which makes it hard to introduce it now as a contextual keyword

That's what I said 318 is enough. Stop introducing new keyword just for lazy purpose. And also there are many possibility to work with property by more than one field. Or even using many property on one field. field keyword has just only one usage

**Comment by ggaabe** [comment]
I think this would be a good change. willSet and didSet are useful. There will always be a lot of people who drag their feet on language features or syntax improvements so they don't have to learn anything else their whole lives. Don't let others get you down about it.
