### ISSUE TITLE
[semi-auto-props] Question: DefiniteAssignment warning for properties with a setter

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#6080]
```csharp
public struct C
{
    public C()
    {
        // Is this warning expected?
        // CS9020: The 'this' object is read before all of its fields have been assigned, causing preceding implicit assignments of 'default' to non-explicitly assigned fields.
        P = 5;
    }

    public int P { get => field; set => field = value; }
}
```

There is no way to ensure the field is definitely assigned without using an initializer.

**Comment by RikkiGibson** [comment]
Yeah, this is exactly the diagnostic I expected to see, although I did expect that the compilation options would need to include `.WithSpecificDiagnosticOptions(ReportStructInitializationWarnings)`. That is, this warning would only be reported for users who made some special effort to surface the warning. See dotnet/roslyn#60176.

**Comment by Youssef1313** [comment]
@RikkiGibson Yup I had `ReportStructInitializationWarnings` in my test. But @AlekseyTs asked to bring this to LDM.

Quoting his comment:

> Perhaps zero initialization of fields created for properties like the one we are testing shouldn't cause the warning. There is no way for a user to initialize the field directly, other than a property initializer. Something to discuss at LDM. A PROTOTYPE comment is good for now.

**Comment by 333fred** [comment]
Discussed in LDM on May 2nd, 2022: https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-05-02.md#definite-assignment-of-manually-implemented-setters. This warning will be reported for all manually implemented setters, regardless of whether the property has a backing field.
