### ISSUE TITLE
[semi-auto-props]: Revise spec regarding `set;`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#6089]
The spec for semi-auto properties allows `public int P { set; }` where it used to produce `error CS8051: Auto-implemented properties must have get accessors.`

I don't see a real benefit from allowing `set;` only property. Should it be disallowed?

@333fred @AlekseyTs @CyrusNajmabadi

**Comment by OJacot-Descombes** [comment]
We should allow virtual ones
``` c#
public virtual int P { set; }
```

**Comment by alrz** [comment]
This is like a parameterless Deconstruct() which has no real advantage but the language allows it just because it fits into the spec and there's no obvious reason to add an exception for it.

An analyzer could definitely flag it.

**Comment by Youssef1313** [comment]
> there's no obvious reason to add an exception for it.

Why? It was already disallowed. Why we remove the existing exception with semi-auto-props?

**Comment by Youssef1313** [comment]
> We should allow virtual ones
> 
> ```cs
> public virtual int P { set; }
> ```

What's the use case for that?

**Comment by alrz** [comment]
> > there's no obvious reason to add an exception for it.
> 
> Why? It was already disallowed. Why we remove the existing exception with semi-auto-props?

My impression was that this case falls out of the spec for semi autoprops. If not, then this doesn't apply.

**Comment by OJacot-Descombes** [comment]
@Youssef1313, an overridden setter-only property can do something useful with the assigned value. Imagine that the class is a write-only wrapper for another (read/write) class, then it can assign the value to the wrapped read/write property. This wrapper class could implement a contra-variant interface with an `in` generic type parameter. A setter-only property is rarely used but makes sense if it is not an auto-property. A virtual auto-property can be overridden as explicitly implemented property.

**Comment by Youssef1313** [comment]
I actually mis-read the [spec](https://github.com/dotnet/csharplang/blob/main/proposals/semi-auto-properties.md). It *very clearly* states this is not allowed but somehow I dropped it while reading.

> + An auto-property is not allowed to only have a single semicolon-only `set` accessor without a `get` accessor.

I was probably confused by this part of the diff:

![image](https://user-images.githubusercontent.com/31348972/184866694-22f364c9-2306-4a4e-b07b-023b2339cca9.png)

@333fred I'm going to close this and remove it from LDM schedule.
