### ISSUE TITLE
catch-all '*' or discard '_' for patterns?

### ISSUE THREAD

**Issue by lachbaer** [dotnet/csharplang#609]
In https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md the discard pattern is defined as a single underscore `_`, but in the examples a star `*` is used as the *catch-all* pattern. However, the `*` is not defined in that preliminary specification. What's the current status?

**Comment by yaakov-h** [comment]
I thought it was initially `*`, but then changed to `_`?

**Comment by lachbaer** [comment]
Filed a [PR](https://github.com/dotnet/csharplang/pull/610). Let's see if it becomes accepted.

**Comment by aluanhaddad** [comment]
Yes this was changed. See https://github.com/dotnet/roslyn/issues/16674
