### ISSUE TITLE
Define a syntax to conditionally set (init) properties in object initializers

### ISSUE THREAD

**Issue by AArnott** [dotnet/csharplang#6117]
### Discussed in https://github.com/dotnet/csharplang/discussions/5588

<div type='discussions-op-text'>

<sup>Originally posted by **AArnott** December 29, 2021</sup>
In https://github.com/neuecc/MessagePack-CSharp/pull/1369#issuecomment-1002726721 we discuss how it seems to be impossible to initialize an object's `init` properties conditionally. For a deserializer that needs to set these properties *iff* values for those properties appear in the serialized data stream, this presents a real problem for AOT generated deserializer code. I expect the System.Text.Json deserializer's new AOT code gen feature in 6.0.0 may suffer from the same problem.

For example consider initializing this object:

```cs
public class A {
  public int B { get; init; } = 3;
  public int C { get; init; }
}
```

Properties B and C can only be set with syntax like this:

```cs
A a = new A {
  B = 5,
  C = 2,
};
```

This is fine for hand-written code. But for an AOT code generated deserializer when values for B or C are optional, we would need something like this:

```cs
A a = new A {
  B = reader.ReadInt32("B"),
  C = reader.ReadInt32("C"),
};
```

But how would we make the assignments to B (and C) optional such that a missing value for B would allow the `3` default value to remain? There is no syntax supported in C# today to do this. An alternative might be to invoke it with its existing value, but as there is no way to reference the object within its own object initializer, we can't do something like this:

```cs
A a = new A {
  B = reader.TryReadInt32("B", out int v) ? v : _.B,
  C = reader.ReadInt32("C"),
};
```

Above I hypothesize that `_` is a reference to the initializing object, but this isn't valid C# 10 code.

Do we need a new feature for this?</div>

@CyrusNajmabadi suggested this syntax, which is quite nice:

```cs
var readB = reader.TryReadInt32("B", out int b);
var c = reader.ReadInt32("C");;
A a = new A
{
    B = b when readB,
    C = c
};
```

**Comment by Dreamescaper** [comment]
Would it be possible to allow discards here?

```csharp
A a = new A {
  B = reader.TryReadInt32("B", out int v) ? v : _, // '_' means do nothing
  C = reader.ReadInt32("C"),
};
```

**Comment by 333fred** [comment]
We only convert discussions to issues when there is a member of the LDT that has championed. At this time, there does not appear to be interest, so I'm closing this out.
