### ISSUE TITLE
Generic type operator overloading

### ISSUE THREAD

**Issue by gdefraiteur** [dotnet/csharplang#612]
could be cool to have operator overloading for generic types.

**Comment by svick** [comment]
Could you clarify what exactly do you mean? Generic types already can overload operators, e.g.:

```c#
class C<T>
{
    public static C<T> operator +(C<T> left, C<T> right) => null;
}

…

var c = new C<int>();
var sum = c + c;
```

**Comment by orthoxerox** [comment]
I am not sure if that's what OP wanted, but operator methods cannot have generic parameters of their own.

```c#
class C<T>
{
    public static C<T> operator +<U>(C<T> left, C<U> right) => null;
}
```

**Comment by AdamSpeight2008** [comment]
Generic Extension Operators would be nice to have.
```csharp
static bool operator = <T> (this T Le, T() Ri) 
  where T has bool operator = (T, T)
{
  for(var j = 0; j < Ri.Length; j++)
  {
    if( Li == Ri[j] ) return true;
  }
  return false;
}

```

**Comment by gdefraiteur** [comment]
well, then we need something maybe to ensure that the T type has operator overloading. (without using exceptions).

just the "where T has bool operator" is cool.

but yea as well i agree with the need of generic extension operators ^^.

**Comment by DavidArno** [comment]
I had a genuine use case for this today. I wanted to overload the `+` operator to provide "cons" support and figured I'd just define:
```cs
public static IConsEnumerable<T> operator +<T>(T head, IEnumerable<T> tail) => ...
```
but that of course doesn't compile as generic operators aren't supported. So I'd really like them to be.
