### ISSUE TITLE
Extension Methods as Interface Implementation.

### ISSUE THREAD

**Issue by gdefraiteur** [dotnet/csharplang#613]
Could be cool to have extension methods as Interface Implementation.

**Comment by HaloFour** [comment]
[Shapes](https://github.com/dotnet/csharplang/issues/164) should cover this functionality.  They differ in a number of ways from interfaces but they would allow for duck-typing based on extensions.

**Comment by gdefraiteur** [comment]
Is it somehow auto implemented? like 

i don't explicitly say that some class is of that shape, but when i use it as this shape, it works?

if that's the case those shapes could be very cool.
