### ISSUE TITLE
Extension Fields

### ISSUE THREAD

**Issue by gdefraiteur** [dotnet/csharplang#614]
Could be cool to have extension fields.

**Comment by yaakov-h** [comment]
#192?

**Comment by HaloFour** [comment]
The problem with extension fields is where are they stored?  Currently the common pattern is to use a `WeakDictionary` to associate the data with an instance, but that is quite inefficient and puts a lot of additional load on the garbage collector.  Unless a much better mechanism is discovered I don't imagine that the language would enshrine the functionality in syntax.

**Comment by yaakov-h** [comment]
How about `ConditionalWeakTable<,>`?

**Comment by HaloFour** [comment]
@yaakov-h 

That's probably the preferred mechanism today, yes, but it still relies on weak handles which, to my understanding, are what creates the additional load on the garbage collector.

**Comment by Thaina** [comment]
No

And if it would just use `ConditionalWeakTable` it could be just syntactic sugar for property
