### ISSUE TITLE
Open issues for `ref` fields

### ISSUE THREAD

**Issue by cston** [dotnet/csharplang#6149]
### 1. Parse `scoped` as a modifier with `-langversion:11`?
What is the effect of parsing `scoped` as a modifier on existing code that uses `scoped` as a type name or identifier?
```csharp
// C#10: 'scoped' type
class scoped { }
scoped s;
static void F(scoped x, ref scoped y) { }
```
```csharp
// C#10: 'scoped' identifier
bool scoped;
scoped = true;
```

### 2. Allow `ref` auto properties?
Support `ref` auto property declarations? If so, allow `set` or `init`?
```csharp
ref T P0 { get; }
ref T P1 { get; set; }
ref T P2 { get; init; }
```

### 3. Allow `ref` assignment in object initializers?
```csharp
ref struct R<T>
{
    public ref T F;
}

int i = 0;
var r = new R<int> { F = ref i };
```

### 4. Report diagnostic for constructor that does not set `ref` field?
Report a diagnostic for an explicit constructor that does not assign to a `ref` field, or that assigns a value?
```csharp
ref struct R<T>
{
    private ref T _t;

    public R() { } // warning: ref is not assigned

    public R(ref T t)
    {
        _t = t; // warning: assigning value not ref
    }
}
```

### 5. `scoped` differences in overrides and interface implementations
Report a diagnostic for mismatches of `scoped` across overrides or implicit or explicit interface implementations? Allow "safe" variance differences?
```csharp
ref struct R<T> { }

abstract class A<T>
{
    public abstract R<T> F1(scoped R<T> r);
    public abstract R<T> F2(R<T> r);
}

class B : A<int>
{
    public override R<int> F1(R<int> r) => r;              // error?
    public override R<int> F2(scoped R<int> r) => default; // ok?
}
```
_Proposed: Report errors for any differences in `scoped`, even "safe" differences._

### 6. `scoped` differences in delegate conversions
Report a diagnostic for mismatches of `scoped` in conversions from lambda expressions or method groups to delegate types? Allow "safe" variance differences?
```csharp
ref struct R { }

delegate R D1(scoped R r);
delegate R D2(R r);

D1 i1 = (R r) => r;              // error?
D2 i2 = (scoped R r) => default; // ok?

D1 e1 = (D1)((R r) => r);              // error?
D2 e2 = (D2)((scoped R r) => default); // ok?
```
_Proposed: Report errors for any differences in `scoped`, even "safe" differences._

**Comment by FaustVX** [comment]
> Allow `ref` assignment in object initializers?
> ```csharp
> ref struct R<T>
> {
>     public ref T F;
> }
> 
> int i = 0;
> var r = new R<int> { ref F = ref i };
> ```

the field `F` should be initialized with `ref F = …` to be consistent with other `ref` variables assignment ?

**Comment by BreyerW** [comment]
> ### Allow `ref` auto properties?
> Support `ref` auto property declarations? If so, allow `set` or `init`?
> 
> ```cs
> ref T P0 { get; }
> ref T P1 { get; set; }
> ref T P2 { get; init; }
> ```

Ref setters would be useful on its own for event patterns where you would still want to avoid copying large struct and fire some kind of event. Like detect if new matrix4x4 (which is decently big struct 16x float fields) changed position or rotation or scale and fire appropiate events. Yes its niche but are so many other perf oriented features.

As for object initializer allowing it would remove yet another suprise that u cant object initialize everything so i hope it lands somewhere in future

**Comment by hez2010** [comment]
> ### Report diagnostic for constructor that does not set `ref` field?
> Report a diagnostic for an explicit constructor that does not assign to a `ref` field, or that assigns a value?
> 
> ```cs
> ref struct R<T>
> {
>     private ref T _t;
> 
>     public R() { } // warning: ref is not assigned
> 
>     public R(ref T t)
>     {
>         _t = t; // warning: assigning value not ref
>     }
> }
> ```


I think at least the `assigning value not ref` should be reported. I used to prototype something using ref fields but immediately came into a problem that caused a NRE in the runtime because I missed a `ref` in the right operand of assignment.

**Comment by 333fred** [comment]
Questions 1-3 were discussed in LDM on May 23rd, 2022. We still need to confirm question 3, which we will do after discussing question 4.

https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-05-23.md#open-issues-for-ref-fields

**Comment by hypeartist** [comment]
Could someone explain why `A ref field cannot have a type that is ref struct` (https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#:~:text=A%20ref%20field%20cannot%20have%20a%20type%20that%20is%20ref%20struct)? 
This is such a huge limitation that it makes the whole idea with `ref fields` to look quite meaningless to me.

**Comment by Joe4evr** [comment]
@hypeartist Because a `ref` is not allowed to live longer than the object it's referring to. If the `ref struct` restriction did not exist, you could end up with `ref`s referring into stack-space above whatever holds it, which is *incredibly* dangerous.

**Comment by hypeartist** [comment]
@Joe4evr 

> you could end up with `ref`s referring into stack-space above whatever holds it,

You perfectly can end up with it via non-ref type field too:
`
	ref struct S
	{
		public ref int F;

		public static void M(ref S s)
		{
			ReadOnlySpan<int> f = stackalloc int[1];
			s.F = MemoryMarshal.GetReference(f);
		}
	}
`

**Comment by hez2010** [comment]
> Could someone explain why `A ref field cannot have a type that is ref struct`

See https://github.com/dotnet/roslyn/pull/62186#issuecomment-1170244475. It just doesn't catch up in C# 11, while it will be enabled in the future.

**Comment by hypeartist** [comment]
> It just doesn't catch up in C# 11 (because it involves complicated lifetime analysis which needs more time to implement), while it will be enabled in the future.

That's exactly the answer I was hoping to hear! Thank you.

**Comment by GianvitoDifilippo** [comment]
> `MemoryMarshal.GetReference` is an unsafe API so definitely you can bypass the check.

Speaking of unsafe APIs, can the ref field check be bypassed too? Maybe with `Unsafe.As<TFrom, TTo>`? Suppose I need to store a reference to an `Utf8JsonReader` in another `ref struct`:

```cs
ref struct MyRefStruct(ref Utf8JsonReader reader)
{
  private ref ReinterpretMe _reader = ref Unsafe.As<Utf8JsonReader, ReinterpretMe>(ref reader);

  public void UseTheReader()
  {
    ref Utf8JsonReader reader = ref Unsafe.As<ReinterpretMe, Utf8JsonReader>(ref _reader);
    // Use the reader
  }
}

struct ReinterpretMe;
```

For context, the reason I need this is passing a ref struct that implements an interface to a generic method, leveraging the upcoming `allows ref struct` feature:

```cs
MyService service = GetTheService();
Utf8JsonReader reader = GetTheReader();

MyCallback callback = new MyCallback(ref reader);
service.MyMethod(ref callback);

class MyService
{
  public void MyMethod<TCallback>(ref TCallback callback)
    where TCallback : IMyCallback, allows ref struct
  {
    // do some stuff
    callback.Execute();
  }
}

interface IMyCallback
{
  void Execute();
}

ref struct MyCallback(ref Utf8JsonReader reader) : IMyCallback
{
  private ref ReinterpretMe _reader = ref Unsafe.As<Utf8JsonReader, ReinterpretMe>(ref reader);

  public void Execute()
  {
    ref Utf8JsonReader reader = ref Unsafe.As<ReinterpretMe, Utf8JsonReader>(ref _reader);
    // Use the reader
  }
}

struct ReinterpretMe;
```

I tested this and it seems to be working but I'm not 100% sure that this solution is safe under this use case or it can lead to catastrophic memory issues I'm not aware of.

**Comment by colejohnson66** [comment]
That is horribly unsafe and will likely confuse the GC at some point

**Comment by GianvitoDifilippo** [comment]
@colejohnson66 thank you for your answer!

> That is horribly unsafe and will likely confuse the GC at some point. You should _never_ use `Unsafe.As` between types with different memory layouts.

I know that looks horrible 😄 but since in principle the only thing that prevents storing a reference to a ref struct is the incompleteness of the compiler's lifetime analysis, I was wondering if there was a workaround that involved using some unsafe APIs in a "safe" way.
I genuinely don't understand how the GC is involved here, as everything is happening on the stack. I've seen plenty of examples in the runtime source where instances of any type, even generic type parameters, are reinterpreted as `byte`, which to me looks like getting a pointer to that variable without using the `unsafe` keyword; I could have similarly used `byte` in my example instead of `ReinterpretMe`.

> Why can’t you just store the Utf8JsonReader directly?

I could copy `reader` into a field of `MyCallback` and then copy that field back into `reader` after calling `MyMethod`, but I'd rather avoid that since `Utf8JsonReader` is a quite large struct and I have multiple invocation to `MyMethod` and multiple instantiation of `MyCallback` (because in my case, `MyCallback` is a generic type and I need to reinstantiate it each time).

**Comment by colejohnson66** [comment]
I meant this:

```csharp
ref struct MyCallback(ref Utf8JsonReader reader) : IMyCallback
{
  private ref Utf8JsonReader _reader = ref reader;

  public void Execute()
  {
    // Use the reader
  }
}
```

**Comment by 333fred** [comment]
Folks, please take any discussion to a separate discussion thread or forum. This was an issue specifically for open questions that LDM needed to look at, and is now long resolved.
