### ISSUE TITLE
using static class

### ISSUE THREAD

**Issue by Logerfo** [dotnet/csharplang#618]
Considering the new `using static` feature introduced in C# 7.0, I propose the following code to be valid:
```c#
namespace A.B
{
   //only possible in static classes?
   public using static class C 
   {
      public static void M() { }
   }

   public static class D
   {
      public static void N() => M(); 
      //Should a "Unnecessary using directive" warning be thrown if M() is not called?
   }
}
```
Which translates to:
```c#
//In case the answer for the comment above is YES,
//if there is both using static A.B.C; and using static class C in the file,
//which one should be considered redundant?
using static A.B.C;

namespace A.B
{
   public static class C
   {
      public static void M() { }
   }

   public static class D
   {
      public static void N() => M();
   }
}
```

Unresolved questions are already pointed out in the code pieces above.

**Comment by lachbaer** [comment]
I like your translation better than the short cut. Also the shortcut isn't actually that short, it only reduces the `using` line at the top.
> Should a "Unnecessary using directive" warning be thrown if M() is not called?

In the IDE unused `using` declarations are light grey, this way it can be seen that it isn't used.

**Comment by svick** [comment]
Is this supposed to work only in the same namespace? Or would it work from another namespace/assembly too?

In other words, if I have `using A.B;`, does that mean I can write just `M()` to call `C.M()`? If that's what you meant, then that sounds very similar to [the `AutoOpen` attribute from F#](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.autoopenattribute-class-%5Bfsharp%5D).

**Comment by Logerfo** [comment]
@svick this is supposed to work only in the same file, exactly as `using static` works today. The proposal is just a syntactic sugar, not a scope change.

**Comment by svick** [comment]
@Logerfo How often do you have multiple classes in the same file? I think that does not happen very often, so this would have fairly limited use.

**Comment by Logerfo** [comment]
@svick I had the idea of the proposal when I stumbled on the case where I had to use the very same enum in two classes in the same file and namespace, which made me declare a third one.

**Comment by GeirGrusom** [comment]
```csharp
namespace Foobar
{
  using static A;
  static class A
  {
    public void Foo() { }
  }

  class B
  {
    void Bar()
    {
       Foo();
    }
  }
}
```

**Comment by Logerfo** [comment]
@GeirGrusom I didn't know that using directives could be used in the namespace context. Probably the translation would be the following, then:
```c#
namespace A.B
{
   using static C;
   public static class C
   {
      public static void M() { }
   }

   public static class D
   {
      public static void N() => M();
   }
}
```
Now I can answer two of three unresolved questions:
>Should a "Unnecessary using directive" warning be thrown if M() is not called?

Yes
>Which one should be considered redundant?

The latter if in the same scope, the outermost if not, as today.

**Comment by lmcarreiro** [comment]
It's a good practice to put different classes in different files, so it could not be used to make the code better...

The using directives at the top of the file just change how the compiler will look and interpret the code that you write, they are used only by the compiler and make no difference in the generated assembly.
The keywords that prefix the class declaration (modifiers) change the behavior of the class, what the class is, so a "using" modifier makes no sense. It would be confusing.

**Comment by gordanr** [comment]
> It's a good practice to put different classes in different files

[Not directly related with this topic.] Record types could change this practice in some modeling approaches. For example, when we modeling every DB column with record types, all these types we can put in a single file.

**Comment by Logerfo** [comment]
@lmcarreiro as I [said](https://github.com/dotnet/csharplang/issues/618#issuecomment-303479551), I needed it for an enum. Do I really need a new file just for an enum?

**Comment by lmcarreiro** [comment]
It's up to you to decide, when my enum doesn't have too much items and will be used by properties in just one class, I put it together in the same file as the class too. But with enum I don't like to use as static.

**Comment by aluanhaddad** [comment]
> I didn't know that using directives could be used in the namespace context.

That doesn't impact this proposal as the translations are essentially equivalent.

If this is just for file scoping, then I do not think this adds value.

If it were like F#'s `AutoOpen` that @svick mentioned, or the similar [`package object`](http://www.scala-lang.org/docu/files/packageobjects/packageobjects.html) feature in Scala, then I think it would be valuable.

**Comment by Logerfo** [comment]
Closing due to death and rejection
