### ISSUE TITLE
Discussion/Suggestion: Type matching with generic constraints

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/csharplang#619]
Hi,

I came across a funny issue today, where I have an object of unknown type, and it's composed of several interfaces without having a concrete type or connection between them, to be passed as a single type. Let the code do the talking:

    foreach(PropertyInfo property in GetProperties()
    { 
      var value = property.GetValue(obj);
        if(value is Blah)
        {
        }
        else if (value is INotifyCollectionChanged incc
          && value is IEnumerable<ITrackableObject> trackableCollection)
        /*****************************************************/

     //1
     void ProcessTrackableCollection<TCollection>(TCollection collection)
        where TCollection : INotifyCollectionChanged, IEnumerable<ITrackableObject> 
     {
       //perfect now how r u gonna call it without having a concrete type
     }
     //2
     void ProcessTrackableCollection(object collection)
     {
       //meh
       var incc = (INotifyCollectionChanged)collection;
       var tCol = (IEnumerable<ITrackableCollection>)collection;
     }
     //3
     void ProcessTrackableCollection(INotifyCollectionChanged collection)
     {
        // IEnumerable<ITrackableCollection> will really cry
        var tCol = (IEnumerable<ITrackableCollection>)collection;
     }
     //4
     void ProcessTrackableCollection(INotifyCollectionChanged incc, IEnumerable<T> collection) 
     { /* :P */ }
        
___

I hope the situation is clear by the code itself, so my suggestion is to be able to define aliases of composed type constraints and use them wherever:

    using TCollection : INotifyCollectionChanged, IEnumerable<ITrackableObject>;
    namesapace Hello
    {

      public class Program
      {
        
        static void Main()
        {
           PropertyInfo property = GetPropertyInfo();
           object obj = (TCollection)property.GetValue(GetItem());
           Foo(obj);
        }
 
        public static Foo(TCollection obj) 
        {
           obj.CollectionChanged += OnCollectionChanged;
           _Items = obj.ToArray(); //no cast
        }       
      }
    }

I hope I'm clear enough, should I hear rants and I'll expand.

**Comment by HaloFour** [comment]
I believe that this falls under union/intersection types, which is not something that C# or the CLR supports (outside of generic type constraints).  See #228, #344 and #399.

In short, you'd probably want something like:

```cs
if (value is (INotifyCollectionChanged & IEnumerable<ITrackableObject>) collection) {
    // collection treated as both interfaces here
}
```

This is assuming that I am interpreting your "discussion" correctly.

**Comment by weitzhandler** [comment]
@HaloFour lol I know it was gross, hope to make it more readable tomorrow, looks like you understood me well, tho I was more about the aliasing part than the union part.
