### ISSUE TITLE
New assignment operator: =.

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/csharplang#623]
I've thought of a new assignment operator, the `=.` one.

What this operator does is assign the result of an extension function affecting that object. Here is an example:

```csharp
string eg = "This is an example string.";
eg=.Substring(5, 2);
// Equal to eg = eg.Substring(5, 2);
```

I hope you like this idea.

**Comment by jnm2** [comment]
Pretty much a dupe of https://github.com/dotnet/csharplang/issues/500?

**Comment by janjoostvanzon** [comment]
You beat me jnm2. I couldn't find it fast enough.

**Comment by AlFasGD** [comment]
Sorry, didn't check if it exists... Gonna remove that post.

**Comment by jcouv** [comment]
Closing as this is indeed a duplicate of #500.
