### ISSUE TITLE
Move Proposals to Respective Language Version Directory

### ISSUE THREAD

**Issue by shaggygi** [dotnet/csharplang#628]
Based on [Language Feature Status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md#language-feature-status) in Roslyn repo, should the following proposal files be moved?

### [csharp-7.1](https://github.com/dotnet/csharplang/tree/master/proposals/csharp-7.1)
- [Async Main](https://github.com/dotnet/csharplang/blob/master/proposals/async-main.md)
- [Default Expressions](https://github.com/dotnet/csharplang/blob/master/proposals/target-typed-default.md)
- [Ref Assemblies](https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md)
- [Pattern-matching with generics](https://github.com/dotnet/csharplang/blob/master/proposals/generics-pattern-match.md)

If so, related [Roslyn page](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md#language-feature-status) would need to be updated to new paths, as well.

**Comment by shaggygi** [comment]
cc @jcouv 
Looks like you recently added links to proposals.

**Comment by jcouv** [comment]
Here's a PR to do that: https://github.com/dotnet/csharplang/pull/870
