### ISSUE TITLE
specification of the `foreach` statement (12.9.5) doesn't apply for `System.Span`

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/csharplang#6289]
### Discussed in https://github.com/dotnet/csharplang/discussions/6288

<div type='discussions-op-text'>

<sup>Originally posted by **ltcmelo** July 18, 2022</sup>
The [`foreach` statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#1295-the-foreach-statement) is specified by means of an expansion into a `while` *.  
But the specification doesn't apply for a type such as `System.Span` or `System.ReadOnlySpan` as the expansion will produce invalid code.  
Specifically: the `V` in `foreach (V v in x) «embedded_statement»` will expand into the `V` in `V v = (V)(T)e.Current;`; however, if the `foreach` is inside an `async` method, then the declaration `V v` will lead to a diagnose such as:

`error CS4012: Parameters or locals of type 'ReadOnlySpan<char>' cannot be declared in async methods or async lambda expressions.` 

Here's an example in which specified expansion breaks.

```
public class C
{
    public async Task M()
    {
        IReadOnlyList<string> o = null;
        foreach (ReadOnlySpan<char> c in o) {}        
        return;
    }
}
```

\* I have (most of) this expansion as a [syntax rewriter](https://github.com/ShiftLeftSecurity/SharpSyntaxRewriter/blob/master/src/SharpSyntaxRewriter/Rewriters/ExpandForeach.cs).</div>

**Comment by 333fred** [comment]
The specification is valid here. The expansion is not valid code for other reasons, which has nothing to do with the foreach itself.

**Comment by ltcmelo** [comment]
I'm confused @333fred … this is the specified expansion of `foreach` (from the link above).

```
foreach (V v in x) «embedded_statement»
```

Becomes

```
{
    E e = ((C)(x)).GetEnumerator();
    try
    {
        while (e.MoveNext())
        {
            V v = (V)(T)e.Current;
            «embedded_statement»
        }
    }
    finally
    {
        ... // Dispose e
    }
}
```

If you apply this expansion to the source I posted above, then it will produce an invalid source.

**Comment by 333fred** [comment]
It produces invalid source because it is not legal to use a ReadOnlySpan in an async method. That has nothing to do with foreach.

As a side note, as ref structs cannot be boxed nor be type arguments, this will never work, regardless of whether the context is an async method.

**Comment by ltcmelo** [comment]
> it is not legal to use a ReadOnlySpan in an async method. That has nothing to do with foreach.

@333fred I understand this, but that is irrelevant: if I a follow an expansion from the language specification, it must work for any legal program of the language, regardless of the context; it doesn't matter the reason why the program becomes illegal, what matters is that a legal program remains legal after whatever expansion is the language specification.

**Comment by 333fred** [comment]
The fact that this program compiles is a bug. It is not a spec problem, it is a compiler problem. We should not be letting you use an ref struct in an async method like this.

**Comment by CyrusNajmabadi** [comment]
@ltcmelo Yes.  That's what we were discussing in gitter :)
