### ISSUE TITLE
Unary operators and default literal

### ISSUE THREAD

**Issue by akarpov89** [dotnet/csharplang#632]
**Version Used**: 
Master branch on May 19
**Steps to Reproduce**:

Compile the following code:

```csharp
class C
{
  void M()
  {
    var a = +default;
    var b = -default;
    var c = ~default;
    var d = !default;
  }
}
```
**Expected Behavior**:
Compiler emits errors CS0023: Operator '+' / '-' / '~' / '!' cannot be applied to operand of type 'default'
**Actual Behavior**:
Code compiles without errors. The local variables have the following types and values:

```ml
a: int = 0
b: int = 0
c: int = -1
d: bool = true
```

I understand that this is an implication of unary operator overload resolution using predefined operator implementations. But I see absolutely no benefit in allowing such a weird code.
The [default literal proposal](https://github.com/dotnet/csharplang/blob/master/proposals/target-typed-default.md) mentions couple of usages that are considered illegal (`throw default` and `default == default`). Could you please consider extending this list?

/cc @jcouv

**Comment by jcouv** [comment]
@akarpov89 Thanks for catching this. I'll look at it this week.
I agree this seems fishy.

**Comment by jcouv** [comment]
Issue moved to [dotnet/roslyn #19848](https://github.com/dotnet/roslyn/issues/19848) via [**ZenHub**](https://www.zenhub.com/)
