### ISSUE TITLE
[Question]: How to null check c# 7 tuple in LINQ query?

### ISSUE THREAD

**Issue by Kritner** [dotnet/csharplang#646]
Given:

```
class Program
{
    private static readonly List<(int a, int b, int c)> Map = new List<(int a, int b, int c)>()
    {
        (1, 1, 2),
        (1, 2, 3),
        (2, 2, 4)
    };

    static void Main(string[] args)
    {
        var result = Map.FirstOrDefault(w => w.a == 4 && w.b == 4);

        if (result == null)
            Console.WriteLine("Not found");
        else
            Console.WriteLine("Found");
    }
}
```

In the above example, a compiler error is encountered at line if (result == null). How would I go about checking that the tuple is found prior to proceeding in my "found" logic?

Prior to using the new c# 7 tuples, I would have this:

```
class Program
{
    private static readonly List<Tuple<int, int, int>> Map = new List<Tuple<int, int, int>>()
    {
        new Tuple<int, int, int> (1, 1, 2),
        new Tuple<int, int, int> (1, 2, 3),
        new Tuple<int, int, int> (2, 2, 4)
    };

    static void Main(string[] args)
    {
        var result = Map.FirstOrDefault(w => w.Item1 == 4 && w.Item2 == 4);

        if (result == null)
            Console.WriteLine("Not found");
        else
            Console.WriteLine("Found");
    }
}
```

Which worked fine. I like the more easily interpreted intention of the new syntax, but am unsure on how to null check it prior to acting on what was found (or not).

**Comment by HaloFour** [comment]
C# tuples use `System.ValueTuple` which is a struct.  Structs don't have `null` values, their default value is zeroed out, so the result of `FirstOrDefault` when the predicate finds no match is actually `(0, 0, 0)`.

Here's an example extension method that would provide the logic that you'd want in this case:

```cs
public static class EnumerableExtensions {
    public static T? FirstOrNull<T>(this IEnumerable<T> items, Func<T, bool> predicate) where T : struct {
        if (items == null) throw new ArgumentNullException(nameof(item));
        if (predicate == null) throw new ArgumentNullException(nameof(predicate));
        foreach (var item in items) {
            if (predicate(item)) return item;
        }
        return null;
    }
}
```

**Comment by ViIvanov** [comment]
You can try to use helper method, that converts a sequence of value types to sequence of nullable value types before calling `FirstOrDefault(…)`:
```cs
private static IEnumerable<T?> AsEnumerableOfNullable<T>(this IEnumerable<T> source) where T : struct => source.Cast<T?>();
```
and use it like this:
```cs
var result = Map.AsEnumerableOfNullable().FirstOrDefault(w => w.Item1 == 4 && w.Item2 == 4);
if (result == null)
    Console.WriteLine("Not found");
else
    Console.WriteLine($"Found: {result.Value}");
```

**Comment by jnm2** [comment]
I call mine `AsNullable()` and `FirstOrNull` too, but I implement `FirstOrNull` via `.AsNullable().FirstOrDefault()` in case the BCL `FirstOrDefault` has optimizations I can't access. @HaloFour what are your thoughts on that?

@Kritner If you know that `(0, 0, 0)` will absolutely never appear in `Map` then another option is:

```c#

var result = Map.FirstOrDefault(w => w.a == 4 && w.b == 4);

if (result == default((int, int, int)))
    Console.WriteLine("Not found");
else
    Console.WriteLine("Found");
```

But you have to be careful to remember that [connascence](http://connascence.io/meaning.html) later on if `(0, 0, 0)` ever does gain an opportunity to appear in `Map`, so @HaloFour's suggestion is likely the safest.

**Comment by alrz** [comment]
A tuple can't be null, but in C# 7.1 `if (result == default)` works fine.

**Comment by Kritner** [comment]
@HaloFour that works beautifully!  Thanks!
