### ISSUE TITLE
[Proposal]: [Adding reference from NuGet]

### ISSUE THREAD

**Issue by mustafas18** [dotnet/csharplang#6523]
# Adding references from NuGet

## Summary
[summary]: #summary

Adding a method which can add references from NuGet. (e.g. `MetadataReference.CreateFromNuget("Microsoft.EntityFrameworkCore"`);

## Motivation
[motivation]: #motivation

Users can easily add their desire references to their code.

**Comment by jnm2** [comment]
This looks like an API request for Roslyn. Please file this in the Roslyn repository and use the [Roslyn API request template](https://github.com/dotnet/roslyn/issues/new?assignees=&labels=Feature+Request%252CConcept-API&template=api-suggestion.md).
