### ISSUE TITLE
Support classes private to namespaces

### ISSUE THREAD

**Issue by jochenz** [dotnet/csharplang#6531]
I think there is benefit in making this code legal:

``` cs
namespace MyNamespace.SubNamespace;

private class MyClassScopedPrivatelyToMySubNamespace 
{
}
```

The idea is that the class would be visible to the namespace (and child namespaces), but not to other namespaces.

This avoids having to create a separate assembly to make a class internal. It allows for better implementation hiding within an assembly. This allows better code structure and can avoid undesired coupling within an assembly.

Happy to read your thoughts on this.

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/discussions/1138

And from [readme](https://github.com/dotnet/csharplang):

> For new feature proposals, however, please raise them for [discussion](https://github.com/dotnet/csharplang/labels/Discussion), and only submit a proposal as a pull request if invited to do so by a member of the Language Design Team (a "champion").

**Comment by jochenz** [comment]
Oops, will correct this immediately.
