### ISSUE TITLE
Feature suggestion: pure switch statements

### ISSUE THREAD

**Issue by johnknoop** [dotnet/csharplang#655]
I really like the new pattern matching of c# 7. But what would be even better, is pure functional pattern matching:

```

void Hello()
{
    int? ParseAndAdd(object x) {
        match (x)
        {
            case int i when i > 0:
                return i + 1;
            default:
            case string s:
                return (int?) null;
        }
    }

    var result = ParseAndAdd("hello");
}

```
Since it's a `match` rather than a `switch`, it would guard against any side effects such as state mutation. Or actually, it would be fine even if it didn't. Just the ability to return the result of this expression would be good enough.

The above code could be written in shorter form:

```
var result = match (x) {
    with int i when i > 0 => i + 1;
    with string s => (int?) null;
}
```

If I know that the entire body is pure, then I don't have to look for mutations of field variables and stuff, that saves me time when debugging. And such code always make me feel more comfortable. There's a nuget package called Simplicity, which I'll probably continue using over the new pattern matching language features, just because it allows for writing safer code. But I would love if the language itself actually supported this.

(note, I initially posted this in the roslyn repo, but was told that this is the right place to do it).

**Comment by HaloFour** [comment]
An expression form of `switch` has been proposed as a part of the wider pattern matching proposal:

[Patterns - Match Expression](https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md#match-expression)

The proposed grammar is like this:

```cs
var result = x match (
    case int i when i > 0: i + 1,
    case string s: (int?)null
);
```

But of course that could all change.

**Comment by Opiumtm** [comment]
>An expression form of  switch  has been proposed as a part of the wider pattern matching proposal

Absolutely needed language feature. `switch` expression would be **very** useful for LINQ queries too!

**Comment by elnemerahmed** [comment]
I guess you guys need to read this page.
https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching

**Comment by 333fred** [comment]
@elnemerahmed this issue is 3 years old. Switch expressions were not a thing when this issue was created.

That being said, I think I can safely close it out now that we have this.
