### ISSUE TITLE
Implementation of AOP (Aspect Oriencted Programming) in C#

### ISSUE THREAD

**Issue by niconico49** [dotnet/csharplang#6558]
I don't know if is the right place for this suggestion/idea but is possible add in c# language code (and runtime too) something similar to aspectJ (aspect oriencted programming) in java? I know that is possible to do something similar thanks to the attributes but i think that is too expensive during runtime execution, because every code interrogation and analysis will be executed only during the execution thanks the reflections. Is better to do the same thing during the code compilation because the eventually AOP library (or possible c# future feature support) takes the pieces of code (kernel code and aspect code), join them and compile.
I know there are some libraries that emulate that too, but, from my point of view are too complicated if compared with the same feature realized for java programming. The question is: is possible to do the same (or more simple) natively for c#?
Thanks a lot and good programming.

**Comment by HaloFour** [comment]
See: #107

And: https://www.postsharp.net/aop.net

Notably Java doesn't have any AOP features.  AspectJ is entirely external and relies on rewriting the bytecode of the program either after compilation or at runtime via a Java agent.

**Comment by 333fred** [comment]
Closing as a duplicate. In he future, please open new requests as discussions, not issues, as documented in our readme.
