### ISSUE TITLE
Should we copy/move proposal from Roslyn?

### ISSUE THREAD

**Issue by eyalsk** [dotnet/csharplang#66]
The title says it all. :)

**Comment by scottdorman** [comment]
Isn't this what @gafter has been doing? I think he's only pulling in the active proposals though. Are you asking if *all* of them should be moved over?

**Comment by eyalsk** [comment]
@scottdorman Well, I'm asking whether the people that wrote proposals can start post them here?

**Comment by scottdorman** [comment]
> Well, I'm asking whether the people that wrote proposals can start post them here?

If you had previously written one that's in the Roslyn repo, I would think so but @gafter or @MadsTorgersen should give the definitive answer on that.

**Comment by gafter** [comment]
You are welcome to copy proposals that you still want into this repo. They will turn into discussion issues, but they will at least be read by the language design team (unlike issues in Roslyn, which were often missed by the team). Doing so is no guarantee that a member of the language design team will champion it, but it is a good first step.

**Comment by eyalsk** [comment]
@gafter Okay, thank you.

**Comment by alrz** [comment]
>You are welcome to copy proposals that you still want into this repo.

I'm afraid doing so in bulk would cause the opposite effect i.e. not be read by LDT.

**Comment by gafter** [comment]
@alrz We'll keep that in mind as we discuss whether or not to do so in bulk.

**Comment by eyalsk** [comment]
@gafter I'm sure whether this is a good idea but maybe you can create an index for proposals that you discussed during LDM, this way the community can track whether their proposal got discussed.

**Comment by scottdorman** [comment]
@eyalsk Are you looking for something like this:

| Proposal | Status |
|-----------|--------|
| [Async Streams](https://github.com/dotnet/csharplang/blob/master/proposals/async-streams.md) |  |
| [Covariant return types](https://github.com/dotnet/csharplang/blob/master/proposals/covariant-returns.md) | Proposed |
| [default interface methods](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md) | Proposed |
| [expression variables in initializers](https://github.com/dotnet/csharplang/blob/master/proposals/expression-variables-in-initializers.md) | Proposed |
| [Private Protected](https://github.com/dotnet/csharplang/blob/master/proposals/private-protected.md) | Complete |

Or are you more interested in knowing in which LDM the proposal was discussed? So, something like (note that the links to the actual LDMs aren't accurate, I just grabbed two at random to use as an example):

| Proposal | Meetings |
|-----------|--------|
| [Async Streams](https://github.com/dotnet/csharplang/blob/master/proposals/async-streams.md) |  |
| [Covariant return types](https://github.com/dotnet/csharplang/blob/master/proposals/covariant-returns.md) | |
| [default interface methods](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md) | |
| [expression variables in initializers](https://github.com/dotnet/csharplang/blob/master/proposals/expression-variables-in-initializers.md) | |
| [Private Protected](https://github.com/dotnet/csharplang/blob/master/proposals/private-protected.md) | [LDM Jan 15, 2017](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-01-17.md),  [LDM Feb 14, 2017](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-02-14.md) |

**Comment by orthoxerox** [comment]
@scottdorman Both columns are useful, can we have both?

**Comment by scottdorman** [comment]
@orthoxerox It's just a matter of how much work someone has to do/is willing to do. :)

**Comment by eyalsk** [comment]
@scottdorman Like @orthoxerox I think we should have both if it's not a hassle but otherwise I'd be happy with something like the first table.

In addition I'd want to have a link that leads to the discussion and I think we can help them with that. :)

**Comment by scottdorman** [comment]
@eyalsk It will be a bit of a pain to get setup initially, but once that's done I don't *think* it would be too hard to keep up to date.

> In addition I'd want to have a link that leads to the discussion 

So you're wanting a link back to the relevant issue where the discussion is taking place? If there is more than one issue, I'd assume you'd want that linked as well?

To be honest, this is really starting to sound like proposals should be tracked as projects. I think that gives us all what we're looking for - a single place to go to see everything that's going on about a particular proposal.

If it started life as an issue, that's fine too as that issue could simply reference the relevant project and then be closed.

**Comment by eyalsk** [comment]
@scottdorman 

> So you're wanting a link back to the relevant issue where the discussion is taking place? If there is more than one issue, I'd assume you'd want that linked as well?

There's always a single discussion going on, we helped them track dups and reference issues before so this shouldn't be a problem and we can also help them keep this document up-to-date too, at least when it comes to discussions.

I don't know if we really need to list all the LDMs, posting the most recent one might be sufficient.

So what I'm suggesting is a table that looks like this:

| Proposal | Status | Recent Meeting | Active Discussion |
|----------|--------|--------------|-------------------|
|          |        |              |                   |

This way people won't have to search for proposals and all the information would be a matter of a click away from them.
