### ISSUE TITLE
Error in specification?

### ISSUE THREAD

**Issue by jacovc86** [dotnet/csharplang#660]
https://github.com/dotnet/csharplang/blob/master/spec/basic-concepts.md#declarations

...define classes (Classes), structs (Iterators), interfaces (Interfaces)...

structs is linked to Iterators

**Comment by lachbaer** [comment]
Seems so. I guess that documents links are auto-generated, so the source must be corrected first before pushing an updated version in the repo.

**Comment by svick** [comment]
@lachbaer I believe these documents were auto-generated once, but modifying the Markdown now directly is okay, so I have created a PR to fix this: https://github.com/dotnet/csharplang/pull/720.
