### ISSUE TITLE
Proposal: Allow null-conditional operators and null-coalescing operators to be overloaded

### ISSUE THREAD

**Issue by Lorenzo501** [dotnet/csharplang#6619]
### Discussed in https://github.com/dotnet/csharplang/discussions/2020

<div type='discussions-op-text'>

<sup>Originally posted by **Alexees** November 21, 2018</sup>
I'm asking this in favour of the Game Engine Unity. Since the core engine is written in C++ and scripts are written in C#, == and != are overriden. This means even though serialized fields (public or SerializeFieldAttribute) which are reference types, get an instance of the corresponding C# class created during construction. In these cases those operators still return null because there has not been any C++ equivalent constructed.
Now since ?. and ?? have made their introduction, they cause a lot of confusion as you have to know when they can be applied and when they cannot. Here, they cannot. Visual Studio shows the variabled as being null, but they're still chosen despite this fact and cause NullReferenceExceptions afterwards.
If they were overridable they could just implement the same logic and we all could use this syntax without hesitation.</div>

### Official poll in https://github.com/dotnet/csharplang/discussions/6618

<div type='discussions-op-text'>

<sup>Originally posted by **Lorenzo501** October 28, 2022</sup>
These four operators have to be overloaded in the **Unity game engine** _(very popular)_ but cannot, and is therefore making all four operators incompatible with Unity objects. The workarounds to use those operators on non-Unity objects and at the same time taking action on the code style suggestions for these operators with Unity objects, requires clumsy extensions and in my case even an _(Unity)_ editor utility to initialize a singleton with early access for editor scripts if it's null.<br>
This all just to get rid of the code style suggestions and keep things as nice and consistent with those new operators as it can be. These workarounds aren't standarized either! So most Unity game developers do not even use the new operators at all and are simply turning off the code style suggestions for it. Please make these operators available to everyone by making the exception to have them become overloadable.</div>

**Comment by Lorenzo501** [comment]
**You can check the Unity forum for more information.**

**Comment by jaredpar** [comment]
Closing as this issue is already under discussion in [2020](https://github.com/dotnet/csharplang/discussions/2020) as you noted. The discussion should continue there. Fragmenting to an issue does not help the conversation.

**Comment by Lorenzo501** [comment]
> Closing as this issue is already under discussion in [2020](https://github.com/dotnet/csharplang/discussions/2020) as you noted. The discussion should continue there. Fragmenting to an issue does not help the conversation.

The other discussion doesn't even mention all null-conditional operators and null-coalescing operators in the title, and contains a confusing mistake in the title: "()??" and the poll could've been useful. Why didn't you just change the poll options to a simple yes and no, if that was your only reason to close it..? I seriously doubt that people will care about the extra text between parentheses. It was the first thing that came to my mind. Could've been improved by you or me, when deemed necessary..
