### ISSUE TITLE
Exception Coalescence

### ISSUE THREAD

**Issue by Ekl1p5e** [dotnet/csharplang#6663]
### Discussed in https://github.com/dotnet/csharplang/discussions/6662

<div type='discussions-op-text'>

<sup>Originally posted by **Ekl1p5e** November  7, 2022</sup>
I think it would be useful to add an exception coalescence operator in order to avoid using the ternary operator for a check first. Roughly, it would look something like this:

enum Color { Red, Blue, Orange, };

Color GetColorFromString(string color)
{
  switch(color)
  {
    case "Blue":
      return Color.Blue;
    default:
      throw new Exception();
  }
}

object GetObj(string color)
{
  return new
 {
    COLOR = GetColorFromString(color) *? default,
  }
}

the operator isnt important, but i think this would be useful for making concise expressions.</div>

**Comment by bernd5** [comment]
Exceptions are quite expensive and should not be used in non execptional use cases.
I would recommend:

```csharp
System.Console.WriteLine(GetObj("Red"));
System.Console.WriteLine(GetObj("Blue"));
System.Console.WriteLine(GetObj("Orange"));
System.Console.WriteLine(GetObj("Purple"));

Color? GetColorFromString(string color)
{
	switch(color)
	{
		case "Blue":
			return Color.Blue;
		case "Red":
			return Color.Red;
		case "Orange":
			return Color.Orange;
		default:
			return null;
	}
}

object GetObj(string color)
{
	return GetColorFromString(color) ?? default;
}

enum Color { None, Red, Blue, Orange, };
```

**Comment by 333fred** [comment]
Discussions should not be migrated to issues without express invitation from a member of the LDT.

**Comment by 333fred** [comment]
Please continue any discussion in the original discussion thread, #6662.
