### ISSUE TITLE
Might be a good idea to add a template to ideas that are posted here?

### ISSUE THREAD

**Issue by eyalsk** [dotnet/csharplang#67]
Some folks got great ideas but _formatting_ or/and _structuring_ isn't their strongest side so I think that adding a template for ideas can be useful both for these people and for others that want to have a _framework_ to write their ideas and post them here.

I know that there is one for [proposals](https://github.com/dotnet/csharplang/blob/master/proposals/proposal-template.md) but I think that they are different in nature.

**Comment by scottdorman** [comment]
What would the template look like? Maybe for some types of issues but I wouldn't think a template would work for every type of issue that somebody might submit.

**Comment by eyalsk** [comment]
@scottdorman Well, it's a template for a reason, sections can be modified as necessary to fit the person's need but I feel like having something is better than looking at a blank page, it might also encourage people to think more about their ideas.

So what I'm thinking is something like this:

Background
------------

A brief or in-depth overview about the idea.

Problem
---------

Describe what are the problems today and/or why a new approach is necessary.

Solution
---------

Propose a new solution that solves the noted problems above.

Advantages
------------

Describe the advantages the solution has in comparison to existing solutions.

Disadvantages
---------------

Describe the disadvantages the solution has in comparison to existing solutions.

Conclusion
-----------

Emphasize the benefits of the idea and the value it adds to the language.

Resources
----------

A placeholder for 3rd-party links and additional information about the subject.

**Comment by HaloFour** [comment]
@eyalsk 

There is already a proposal template:  https://github.com/dotnet/csharplang/blob/master/proposals/proposal-template.md

That's the format you'd have to follow for any proposal submitted as a PR to the repo, so you might as well start there.

**Comment by eyalsk** [comment]
@HaloFour Yes I saw that but I feel like it's more oriented towards the details than the concept and I think that there should be something that precedes this.

It's like the difference between a _wireframe_ and a _mockup_ or the difference between _architecture_ and _design_.

One is more abstract than the other.

**Comment by Thaina** [comment]
@HaloFour Could we have that format as default text when we press new issue button?

**Comment by eyalsk** [comment]
@Thaina We can but @HaloFour isn't responsible for that, you can create a new issue about it if you think that we need it.
