### ISSUE TITLE
Numerical Operations on Arrays

### ISSUE THREAD

**Issue by maxwenger** [dotnet/csharplang#671]
Traditionally in C#, you are required to implement all mathematical operations on arrays, such as matrix multiplication.

It would be really helpful if we could perform operations like this on arrays.
```cs
int[,] a = new int[4, 2] { { 1, 2 }, 
                           { 3, 4 }, 
                           { 5, 6 },
                           { 7, 8 } };

int[,] b = new int[2, 4] { { 8, 7, 6, 5 }, 
                           { 4, 3, 2, 1 } };

int[,] product = a * b;

// product = { { 16, 13, 10, 7 },
//             { 40, 33, 26, 19 },
//             { 64, 53, 42, 31 },
//             { 88, 73, 58, 43 } };
```

This would also extend to the other mathematical functions (+, -, *, /).

**Comment by Unknown6656** [comment]
Which functions would you propose to be implemented?

- Matrix/Matrix multiplication, addition and subtraction
- Matrix/Matrix division is **not** possible, as a matrix is a non-commutative algebraic ring and does therefore not define its multiplicative inverse (a division requires the multiplicative inverse member of a given element)
- Matrix/Scalar multiplication and subtraction (including the prefix operators `+` and `-`, which would translate into `result = ±1 * array` respectively)

<hr/>

Although I really _love_ this proposal, I am not sure, whether the effort is worth it concerning matrices.
I would rather see numerical operations implemented in the following sense:

```csharp
int[] a = { 3, 1, 5, 8, 8 };
int[] b = { 4, 2, 0, 7, -1 };

int[] c = a + b; // 7, 3, 5, 15, 7
int[] d = a - (b * 4); // 19, 9, 5, 36, 4
float[] e = -c / 2f; // -3,5, -1.5, -2.5, -7.5, -3.5
// etc...
```

**Comment by Vlad-Stryapko** [comment]
@maxwenger 
I think it would be the best to combine your suggestion with https://github.com/dotnet/roslyn/issues/11159. 

That way, when 'extension everything' is implemented, a separate NuGet package with matrix operators can be created without including those operators in the language itself. What do you think?

**Comment by yaakov-h** [comment]
This sounds to me like something that belongs in `System.Numerics`, not specific algorithms as the default operators for general-purpose arrays.

**Comment by alrz** [comment]
This will be possible once we have "extension everything". extension conversion operators are unlikely to happen but other operators can be actually useful as extensions.

**Comment by svick** [comment]
I'm not sure this belongs into the C# language itself. Instead, if you want to work with matrices, consider using a specialized library.

Though I tried to convert your example to use [`MathNet.Numerics.LinearAlgebra`](https://numerics.mathdotnet.com/Matrix.html) and got this exception:

> Matrices and vectors of type 'Int32' are not supported. Only Double, Single, Complex or Complex32 are supported at this point.

**Comment by maxwenger** [comment]
Thanks!
I'll see if I can collaborate with the teams mentioned above!
