### ISSUE TITLE
[Proposal Question]: Required member support for `MemberNotNull`

### ISSUE THREAD

**Issue by 333fred** [dotnet/csharplang#6754]
https://github.com/dotnet/roslyn/issues/65406
https://github.com/dotnet/csharplang/discussions/6752

We have a few issues around people using `required` properties with explicit backing fields. While much of the scenario is out of scope for C# 11, we could potentially use `MemberNotNull` to enhance our understanding (as it requires no analysis of method bodies) and silence nullability warnings as appropriate. As an example:

```cs
class Base
{
    protected string f;

    public required string P
    {
        get => f;
        [MemberNotNull(nameof(f))]
        set => f = value;
    }

    public Base()
    {
    } // No warning that `f` might be null

    public Base(int _) : this()
    {
        f.ToString(); // Warning: we infer that `this()` didn't set f because required member `P.set` has it in its `MemberNotNull`
    }
}

class Derived : Base
{
    public Derived : base()
    {
         base.f.ToSring(); // Warning: we infer that `base()` didn't set f because required member `base.P.set` has it in its MemberNotNull
    }
}
```

Formally:

If a constructor does not chain to a construct with `SetsRequiredMembers`, we assume that all members mentioned in a `MemberNotNull` on a required member `M` or required member setter (if `M` is a property) have an initial nullable state of maybe default after the chained initializer has run. At the end of the constructor, we do not warn about nullable state mismatches in any member that is mentioned in a `MemberNotNull` on any `M`.

**Comment by JoasE** [comment]
When will the analysis of `init` bodies be planned so we don't have to use the `MemberNotNullAttribute`?

**Comment by 333fred** [comment]
> When will the analysis of `init` bodies be planned so we don't have to use the `MemberNotNullAttribute`?

This is unlikely to ever happen.

**Comment by 333fred** [comment]
Discussed in LDM: https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-11-30.md#revise-membernotnull-for-required.

Conclusion: change is accepted.
