### ISSUE TITLE
ref Switch Expression

### ISSUE THREAD

**Issue by ilyfairy** [dotnet/csharplang#6758]
### Discussed in https://github.com/dotnet/csharplang/discussions/6757

<div type='discussions-op-text'>

<sup>Originally posted by **ilyfairy** November 29, 2022</sup>
Make Switch expression support ref
Now it prompts an error "Invalid expression term \'ref\'"

```CSharp
string str = "a1";
int x = 1;
int y = 2;

ref int r = ref str switch
{
    "a1" => ref x,
    "a2" => ref y,
    _ => ref Unsafe.NullRef<int>()
};
```

**Comment by eyalalonn** [comment]
@ilyfairy It's enough to post it once and you shouldn't post this here as per the guidance on the front page of the repo so you can close it.
