### ISSUE TITLE
Improve hard code string experience

### ISSUE THREAD

**Issue by John0King** [dotnet/csharplang#677]
We already have something  for this : 
```c#
string v = @"<html>
<body>
    <p></p>
</body>
</html>";
```
but  if the html has some attributes or it is a json string ,  then you can not just copy and past in C# .
I hope there some feature like this:
```C#
string v = @` // must end the line
{
  "state":"success",
   "errorMessage":""
}
`; // must take a whole line
string mysqlStr = `
SELECT `id`,`title`,`publishTime` from `news` order by `publishTime` desc
`;

```
Any characters inside  the ` `` `  is string ,   and we can use  `string.Formate()` or `string.Replace()`  to deal with `{0}`

if it is possible, it's better  replace ` $"xxx{code}xxx" ` to  ``` `xxx{code}xxx` ```

Sorry for my bad english , hope you understand my meaning .

**Comment by ViIvanov** [comment]
> …you can not just copy and past in C#

Yes, but I think this problem can be solved by IDE (or extension for it), not by language specification.

Also, I think
```cs
string v = @"
{
  ""state"": ""success"",
  ""errorMessage"": """"
}
";
```
is not a bad for reading or writing.

**Comment by HaloFour** [comment]
See #89

**Comment by John0King** [comment]
@ViIvanov reading is not the problem ,  the problem is copy and past   a  pice of  "huge" json or html such like a complex tagHelper in asp.net core, you can just test in html and past it into C#.

> this problem can be solved by IDE (or extension for it)

now there is script version of C# , such like .csx or .cake , and have a few  editors ( vs , vscode ,vs for mac  ) ,  I don't think it will be a good idea only do it on IDE . on the other hand , PHP already have this 
```php
$a = <<<EOF
<html>
<body stlyel="background:red"></body>
</html>
EOF;
```

**Comment by jnm2** [comment]
ReSharper offsets a quick fix to escape ecerything when you first paste. I feel like this should stay an IDE solution rather than a language solution.

**Comment by MgSam** [comment]
@jnm2 If it does, I've never encountered the feature in almost a decade of using R#. And what happens when you want to copy the text back out into something else? Finally, the impedance mismatch of what you're reading on the screen being different from what the program sees at runtime (due to escapes), can be extremely annoying and time-wasting.

**Comment by alrz** [comment]
>If it does, I've never encountered the feature in almost a decade of using R#. And what happens when you want to copy the text back out into something else?

What if we make it totally transparent, like de-escape when we copy *from* string literals to an external target, escape when we copy from an external source to an string literal, and copy as-is when it's being copied around.

**Comment by TessenR** [comment]
>  If it does, I've never encountered the feature in almost a decade of using R#
It's a relatively new feature. It's been around for about a year by now and it only pops up if there is something to escape.

> And what happens when you want to copy the text back out into something else?
If that "something else" is somewhere in your project (e.g. another C# string, js string, xml-doc comment etc) there will be a suggestion to re-escape it with respect to both original and target escaping rules.

>  like de-escape when we copy from string literals to an external target
Does de-escape always make sense? I might be about to paste it in a string in some script file with similar or even exactly same escaping rules. Unless paste location is known it might be a disruptive experience. That's an interesting idea for a separate shortcut, though.

**Comment by orthoxerox** [comment]
What if the code I'm pasting in has a line with a single backtick? I'd rather ask for a heredoc syntax of sorts:

```c#
var x = @@SomeIdentifier
Everything inside is a string, 
I can use everything(", ', @, {}) except
a line that starts with
SomeIdentifier.ToUpperInvariant();
```

**Comment by iamcarbon** [comment]
Have we considered using the [Multi-Line String Literal](https://github.com/apple/swift-evolution/blob/master/proposals/0168-multi-line-string-literals.md) syntax that Swift has adopted? 

This would also help simplify inline SQL scripts in addition to XML and JSON. 

var jsonText  = """
{
   ""key"": "a",
   ""value": 1
}
""";

**Comment by HaloFour** [comment]
I'm still a bigger fan to the approach taken by C++.  Their raw strings incorporate custom identifiers which mean that there is no single sentinel which terminates the string, as is the case with any other heredoc or multiline literal format.  A take on that syntax is what I proposed with #89.

**Comment by John0King** [comment]
if it can void  json's  `{ }`,`""`  , I'm ok with that!

I will close this issue,  and discuss on #89
