### ISSUE TITLE
Introducing a suffix for 'byte' literals

### ISSUE THREAD

**Issue by light-traveller** [dotnet/csharplang#6775]
### Discussed in https://github.com/dotnet/csharplang/discussions/6774

<div type='discussions-op-text'>

<sup>Originally posted by **light-traveller** December  2, 2022</sup>
### Proposal
Adding a suffix to C# language to explicitly denote the type of a `byte` literal.

Proposed letter for the suffix: **y** and **Y**

The character `'y'` as the second letter in the `byte` keyword is a good choice and does not interfere with the hexadecimal `b` literal.

**Example**
```
var myByte = 0xF5y;
var yourByte = 0b_1010_1100Y;
var anotherByte = 100Y;
```

### Motivation
This will be much of a big help when declaring implicitly typed variables in *bit/byte manipulating scenarios*—in which hard-coded literals are frequently used—by reducing explicit casting and saving key strokes.

**Example**
```c#
var highByte = 0xF0y;
var lowByte = 0x03y;

var bytes = new[] { highByte, lowByte };
var result = Process(bytes);

byte[] Process(byte[] input)
{
    //...
}
```
In the above example, without the proposed suffix, `masks` array will be an `int[]` and the code cannot be compiled.</div>

**Comment by CyrusNajmabadi** [comment]
> In the above example,

This will work with collection literals.

```c#
var result = Process([0xF0, 0x03]);

byte[] Process(byte[] input)
{
    //...
}
```

**Comment by 333fred** [comment]
As discussed in our readme, discussions should stay discussions until a member of the LDT invites creating a championed issue.
