### ISSUE TITLE
Implement interface with generic method

### ISSUE THREAD

**Issue by GeraudFabien** [dotnet/csharplang#680]
Hello,
Problems
When you want to implement many interface having the same method with one method you must map all your method to one. I encounter this problem with interface with genric Inside like this
```
interface Filter<T> : T:IOtherInterface { 
  IQueryable <T> Filter<T>(T source){ ... }
}
```
The main problem is you musn't do casting on IQueriable for Entity Framework. So you must implement the interface to all Entity you want to filter. This mean having a lot of noise.

Solutions
```
    interface IMyInterface
    {
        int HelloWorld();
    }

    class MyClass : IMyInterface
    {
        public T HelloWorld<T>()
        {
            return default(T);
        }
    }
```
I have search for an équivalent issue i didn't found one. Sorry if i'm wrong.

**Comment by miloush** [comment]
I might not understand the problem properly, but can't you forward it?
```C#
class MyClass : IMyInterface
{
    public T HelloWorld<T>()
    {
        return default(T);
    }

    int IMyInterface.HelloWorld() => HelloWorld<int>();
}
```

**Comment by zippec** [comment]
Not sure I understand correctly, but it looks like something that you should be able to solve with [explicit interface implementation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)

**Comment by GeraudFabien** [comment]
@miloush Yes you're right i didn't thinks of it. My issue was to avoid aall the forwarding for each interface you implement since with it add 4 line of code + 3 line of comment +1 blank line for each interface. But with this form it's cleaner.

@zippec I have see that but for me this feature shouldn't be use except to port code from other langage who have it. It totaly break the concept of interface..

Thanks you both.
