### ISSUE TITLE
Constant patterns in 'is' expression question: why different from 'switch'?

### ISSUE THREAD

**Issue by controlflow** [dotnet/csharplang#69]
Can somebody explain why this `is` constant pattern:
```c#
bool Is42(byte b) => b is 42;
```
Works not the same way as similar `switch` statement:
```c#
bool Is42(byte b) {
    switch (b) {
        case 42: return true;
        default: return false;
    }
}
```

`switch` statement performs implicit conversion of literal expressions under `case` labels to *"govering-type"* (`byte` in the example above), while `is` expression just uses "nominal"/"default" type of literal expression and in fact first method never returns `true`.

Is there a deep reason why `is` constant pattern do not performs such implicit conversion of literal based on LHS type?

**Comment by gafter** [comment]
The short answer is that a switch's constant expression is, by specification, converted to the type of the switch expression. There is no such accommodation for the `is` expression. When put as you do, I agree there should have been. This would have been glaringly obvious if we had done recursive patterns at the same time.

Unfortunately, this would be a breaking change. It may be one worth taking.

@dotnet/roslyn-compat-council I propose that the constant of a constant pattern should be converted to the type of the matched expression not only for `switch`, but for all contexts in which a pattern can occur. This would technically be a breaking change for code that uses `is` with a constant pattern in C# 7 where the constant is the wrong type. In that case the compiler produces matching code that always returns `false` in C# 7 It is proposed that we change that such that the constant expression is converted to the type of the matched expression before the comparison, using rules similar to the rules used for the switch statement.

**Comment by alrz** [comment]
>It may be one worth taking.

Definitely. These seemingly subtle differences between `is` and `case` are just too confusing. Other than binding which has to be done to retain backward compat, honestly there is no reason to introduce further divergence. Specifically, when recursive patterns are implemented, this becomes more and more observable.

**Comment by gafter** [comment]
See also https://github.com/dotnet/roslyn/issues/17103 for the compiler bug that we don't implement the spec's special accommodation for integral types.

**Comment by controlflow** [comment]
@gafter Great thanks for looking into this 👍
I hope the best way to fix spec's incompatibility would be to introduce implicit conversion :)


One more example of confusing lack of implicit conversion:
```c#
// Error CS0664: Literal of type double cannot be implicitly converted to type 'float';
//               use an 'F' suffix to create a literal of this type
bool IsPI(float x) => x is 3.14;
```

**Comment by alrz** [comment]
@controlflow That one is actually consistent with `switch`. Perhaps it should be relaxed to accept `float`?

**Comment by HaloFour** [comment]
> Unfortunately, this would be a breaking change. It may be one worth taking.

I know that I saw the release date of VS2017 announced.  Does this mean that the door for closing bugs or considering issues like this is effectively closed?

**Comment by MadsTorgersen** [comment]
@gafter: We should definitely make this change as soon as possible:

- We don't want arbitrary differences from `switch`
- We don't want anymore useless `is` expressions

**Comment by gafter** [comment]
@jaredpar Presuming we want this fix in the earliest possible update, where should a fix be targeted?

**Comment by gafter** [comment]
I want to change the spec so that instead of saying that there is a special case for integral types, the constant expression is converted using an implicit conversion to the type of the expression being matched. If no such conversion exists, it is an error. The value of the expression is then the result of `convertedConstant.Equals(expr)`.
