### ISSUE TITLE
[Proposal]: [I got true in `ReferenceEquals`, but a different result in  using as for type conversion]

### ISSUE THREAD

**Issue by MoYuan00** [dotnet/csharplang#6955]
Here is the program fragment in question:
```c#
public  void Dispatch(T sender, NetMessageRequest message)
{
    foreach(var item in _reqFields)
    {
        IExtensible val = item.GetGetMethod(true).Invoke(message, null) as IExtensible;
        if (val != null)
        {
            Log.InfoFormat("message:{0} val:{1} eq:{2} ==:{3} ReferenceEquals:{4}, typeof(T):{5}",
                message.firstTestRequest, val, val.Equals(message.firstTestRequest),
                message.firstTestRequest == val, ReferenceEquals(message.firstTestRequest, val), typeof(T));

            MessageDistributer<T>.Instance.RaiseEvent(sender, val); // false
            MessageDistributer<T>.Instance.RaiseEvent(sender, message.firstTestRequest); // true
        }
    }
}
```
The type of `item` is  `PropertyInfo`

`RaiseEvent` is equivalent to the following：
```c#

    var type = val.GetType();
    MessageHandler<Tm> handler = val as MessageHandler<Tm>;
    if (handler != null){  // true or false

    }

```

The output from `Log.InfoFormat` is as follows：
```
message:SkillBridge.Message.FirstTestRequest 
val:SkillBridge.Message.FirstTestRequest 
eq:True 
==:True 
ReferenceEquals:True, 
typeof(T):Network.NetConnection`1[Network.NetSession]
```

C# environment version：.NET Framework 4.8

---
That explains most of the information about the program and the variable types, function logic. (No extranous logic is explained).

Here's my **problem** statement:

**I got true in `ReferenceEquals`, but a different result in `RaiseEvent` using as for type conversion**

**Comment by MoYuan00** [comment]
`RaiseEvent`函数内部` if (handler != null) `会出现 `true` 和 `false`两种结果。关于结果我已经使用注释标注在调用处。

**Comment by MoYuan00** [comment]
如果有人能告诉我忽略了什么，或者解决这个问题，我真的很感谢！在我看来语言内部不应该出现这种问题，当我看到`ReferenceEquals:True`时我们已经找不到原因。

**Comment by MoYuan00** [comment]
`MessageDistributer<T>.Instance`是一个范围单例的字段，并没有什么特别的。

**Comment by MoYuan00** [comment]
MessageDistributer<T>.Instance是一个单例的字段，并没有什么特别的。

**Comment by MoYuan00** [comment]
如果有人能告诉我忽略了什么，或者解决这个问题，我真的很感谢！
在我看来语言内部不应该出现这种问题，看到`ReferenceEquals:True`我们认为没有能力找到原因，并将问题认定为语言内部问题。（或许有啥特殊语法规定？）

**Comment by CyrusNajmabadi** [comment]
@MoYuan00 Can you please translate the above to english?  This is currently not actionable by us.

**Comment by eyalalonn** [comment]
@CyrusNajmabadi Based on the translation of ChatGPT 😄 this is an issue with the code and has nothing to do with the language.

**Comment by MoYuan00** [comment]
The problem I want to describe is similar to what you understand. I used reflection to get PropertyInfo and directly used Val to get a different type conversion result, but their reference values are the same. If this is a procedural problem, that's great, but I can't understand where I went wrong. Maybe you need a simpler case?

**Comment by MoYuan00** [comment]
> @CyrusNajmabadi基于 ChatGPT 的翻译😄这是代码的问题，与语言无关。
> 
> p.s. 我想 OP 想了解为什么在下面的代码中输出是不同的，因为在比较相等时，它们的值是相同的，所以它更多的是 SO 问题或获得 Discord/Gitter 或其他方面的帮助。
> 
> ```
> MessageDistributer<T>.Instance.RaiseEvent(sender, val); // false
> MessageDistributer<T>.Instance.RaiseEvent(sender, message.firstTestRequest); // true
> ```

The problem I want to describe is similar to what you understand. I used reflection to get PropertyInfo and directly used Val to get a different type conversion result, but their reference values are the same. 
If this is a procedural problem, that's great, but I can't understand where I went wrong. 
Maybe you need a simpler case?

**Comment by MoYuan00** [comment]
> @MoYuan00 Can you please translate the above to english? This is currently not actionable by us.

Ok, I'm sorry. I have now translated the problem description into English to the best of my ability. Thank you for your reply.

**Comment by MoYuan00** [comment]
`MessageDistributer.Instance`: It's a singleton field, nothing special, right

**Comment by MoYuan00** [comment]
I've provided as little executable code as possible to reproduce this problem.

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Test
{
    public class Program
    {
        static void Main(string[] args)
        {
            new ClassA<Object>().run();
        }
    }

    public class ClassA<T> {
        public int _int = 10;
        public ClassA<T> val { get; set; }

        public void run()
        {
            this.val = this;
            Class<T>.Instance.setDga<T>(this.func);

            var type = typeof(ClassA<T>);
            var proInfo = type.GetProperty("val");
            var getVal = proInfo.GetGetMethod().Invoke(this, new object[] {});

            Console.WriteLine("call with getVal");
            Class<T>.Instance.Trans(getVal);
            Class<T>.Instance.Trans(getVal);

            Console.WriteLine("");

            Console.WriteLine("call with val");
            Class<T>.Instance.Trans(val);
            Class<T>.Instance.Trans(val);

            Console.WriteLine("");

            Console.WriteLine("compare val and getVal:  \r\n " +
                "==:{0} \r\n " +
                "equals:{1} \r\n " +
                "refEquals:{2} \r\n  " +
                "getVal{3} \r\n " +
                "val:{4} \r\n" +
                "type==:{5}", 
                getVal == val, val?.Equals(getVal), ReferenceEquals(getVal, val),
                ((ClassA<T>)getVal)._int, val._int,
                getVal.GetType() == val.GetType());
            
            Console.ReadKey();
        }

        public void func(T handler) { 
            Console.WriteLine("success call func! handler:{0}", handler);
        }
    }

    public class Class<T>
    {
        private static Class<T> _instance;
        public static Class<T> Instance { 
            get {
                if(_instance == null)
                    _instance = new Class<T>();
                return _instance; 
            } 
        }
        public delegate void Handler<Tm>(Tm message);
        private Delegate dga;

        public void setDga<Tm>(Handler<Tm> handler)
        {
            dga = handler;
        }

        public void Trans<Tm>(Tm obj)
        {
            var t1 = dga as Handler<Tm>;
            if (t1 != null) t1(obj);
            Console.WriteLine("result:{0}", t1);
        }
    }
}


```
This program will work when I run it in. Net Framework 4.8 results are as follows:
```
call with getVal
success call func! handler:Test.ClassA`1[System.Object]
result:Test.Class`1+Handler`1[System.Object,System.Object]
success call func! handler:Test.ClassA`1[System.Object]
result:Test.Class`1+Handler`1[System.Object,System.Object]

call with val
result:
result:

compare val and getVal:
 ==:True
 equals:True
 refEquals:True
  getVal10
 val:10
type==:True

```


I'm sorry if this problem is due to my unfamiliarity with C#. I tried to find the cause and analysis of the problem, but there was no result.

I can't find an explanation for this part on google or in official documentation.

I don't understand why the call results would be different when these values are all the same.

**Comment by amis92** [comment]
The problem is the static types don't match - the confusion probably stems from all the implicit types and casting, especially from creating a `Handler<object>` delegate wrapper around `this.func` method group.

0. Given `new ClassA<Object>().run();`;
1. Calling `Class<T>.Instance.setDga<T>(this.func);` means that the `handler` parameter in `setDga` is typed as `Handler<object>` - and that's the type the `dga` delegate actually has.
2. `val` is `ClassA<T> val`, but `getVal` has static type `object` (as returned from `Invoke`).
3. Calling `Trans(getVal)` is specifically resolved as `Trans<object>(getVal)`, which means that inside we're performing a cast of `dga as Handler<object>`, which succeeds - that's exactly the type `handler` was passed with (see 1.).
4. Calling `Trans(val)` is on the other hand resolved as `Trans<ClassA<object>>(val)`, which means that inside we're performing a cast of `dga as Handler<ClassA<object>>(val)`, which doesn't succeed because the types don't match (`Handler<object>` is not convertible to `Handler<ClassA<object>>`).

**Comment by amis92** [comment]
Oh, you've edited the code and now it's the other way around - you've switched `Handler<object>` to `Handler<ClassA<object>>` and now you can't cast `dga` from `Handler<ClassA<object>>` to `Handler<object>` when calling `Trans<object>(val)`.

You can add a cast of `val` to `ClassA<T>` when initializing or calling Trans: either `var val = (ClassA<T>)...Invoke(...);` or `Trans((ClassA<T>)val);`.

**Comment by MoYuan00** [comment]
> Oh, you've edited the code and now it's the other way around - you've switched `Handler<object>` to `Handler<ClassA<object>>` and now you can't cast `dga` from `Handler<ClassA<object>>` to `Handler<object>` when calling `Trans<object>(val)`.
> 
> You can add a cast of `val` to `ClassA<T>` when initializing or calling Trans: either `var val = (ClassA<T>)...Invoke(...);` or `Trans((ClassA<T>)val);`.
> 
> Alternatively (with the initial/older code), you could've used [handler parameter contravariance](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates) using `in` - `delegate void Handler<in Tm>(Tm message);`; this would've allowed conversion of an instance of `Handler<object>` to a variable of type `Handler<ClassA<object>>`.

---

Thank you for your answer. I think you are right. I knew something about generic inverting, but I didn't expect it to be the cause of implicit type conversions. And I use `Trans((ClassA&lt; T&gt;) val)` got the right result.


I will look carefully at your reference to [handler parameter contravariance](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates) to avoid other problems next time.


Thank you very much indeed!
