### ISSUE TITLE
Tuple null-zero issue

### ISSUE THREAD

**Issue by Crispried** [dotnet/csharplang#698]
Good day!
I've came accross on interesting issue with Tuples in System.ValueTuple (it's important, because with usual Tuple there is no problem). So, I have function, for example:
```
        public (AnyClass class, bool found) AnyFunction()
        {
                return SomeStaticClass.ExecuteSomeFunc<(AnyClass , bool)>(() => {
                return (null, false);
            });
        }
```

And it seems that this code should be ok, but compiler says "Cannot convert lambda expression to delegate type  because some of the return types in the block are not implicitly convertible to the delegate return type."

But if I will change this function on
```
        public (AnyClass class, bool found) AnyFunction()
        {
                return SomeStaticClass.ExecuteSomeFunc<(AnyClass , bool)>(() => {
                return Tuple.Create<AnyClass , bool>(null, false);
            });
        }
```

Everything complies well.

**Comment by HaloFour** [comment]
Not sure if I'm missing something but the following compiles fine for me:

```cs
using System;

public class AnyClass { }

public static class SomeStaticClass {
    public static T ExecuteSomeFunc<T>(Func<T> func) => func();
}

public class C {
    public (AnyClass @class, bool found) AnyFunction() {
        return SomeStaticClass.ExecuteSomeFunc<(AnyClass, bool)>(() => {
            return (null, false);
        });
    }
}
```

**Comment by Crispried** [comment]
Yep, your example works, but if you will change parameter in your ExecuteSomeFunc to Func<object) func, so it will be look like
```
        public static T ExecuteFunc<T>(Func<object> func)
        {
            return (T)func();
        }
```
It won't work. What is interesting - there won't be an error if you will return Tuple via Tuple.Create.
```
        public (AnyClass @class, bool found) AnyFunction()
        {
            return SomeStaticClass.ExecuteFunc<(AnyClass, bool)>(() => {
                return (null, false); // compiler error
                //return Tuple.Create<AnyClass, bool>(null, false); // no compiler error
            });
        }
```
Also compiler won't say about error if you will change (null, false) on (0, false), but you will get error in runtime if you will execute this code.

**Comment by HaloFour** [comment]
The compiler can't infer the type of the first element of the tuple as `null` has no type.  It's the same reason why `var x = null;` and `var tuple = (null, false);` aren't legal.  You'd need to supply that type information.  It's also why you can't use generic argument inference with `Tuple.Create`.

**Comment by Crispried** [comment]
It's ok, but it compiles with (0, false) and we get error in runtime. I don't think that it is correct.

**Comment by HaloFour** [comment]
That would be the result of your code.  You're boxing the `(int, bool)` tuple in an `object` and later trying to cast that to a tuple of type `(AnyClass, bool)`.  That will result in a runtime error.  If you want compile time type checking then don't short circuit it by boxing.

**Comment by skyne98** [comment]
@HaloFour , so, as I can understand, every value type object that is used in generic ones is being automatically boxed?

For example, does int end up boxed in this snippet?
```csharp
int foo = 10;
var bar = Tuple.Create<int>(foo); // <- here
```
If it is true then it is kind of frustrating because code like this
```csharp
object car = new Car();
Car anotherCar = (Car)car; // <- runtime error, if car is not Car
```
can be found much less often than usage of parentheses as syntatic sugar. Is think compiler should somehow see that boxing takes place in tuples and should warn programmers about situations like this, despite boxing.

**Comment by HaloFour** [comment]
@skyne98

In the example above @Crispried is returning the tuple from a `Func<object>`,  so he's explicitly assigning the struct to an `object`.  He's then explicitly attempting to cast/unbox to a different and incompatible type which is what is causing the runtime exception.  This behavior is completely unrelated to tuples or generics.  Generics only comes into play as in the CLR the generic arguments are reified and a `ValueTuple<int, bool>` is not the same type as `ValueTuple<AnyClass, bool>`.

**Comment by Joe4evr** [comment]
In .NET, generics never box value types because there's explicit support for it in the CLR. Java made the (mistaken) decision to make generics cast everything to `object`, which could be the source of your confusion.

**Comment by HaloFour** [comment]
@skyne98

No, you can't cast or convert a `System.Tuple<,>` to a `System.ValueTuple<,>` or vice versa.  They are completely different types.  As you mentioned, `System.Tuple<,>` is a `class` whereas `System.ValueTuple<,>` is a `struct`.  C# tuple literal syntax always uses `System.ValueTuple`, not `System.Tuple`.

**Comment by skyne98** [comment]
@HaloFour, thanks for your answers, you helped a lot. This new syntactic sugar and all the stuff, that takes place under the hood can sometimes be very confusing.

**Comment by Crispried** [comment]
@HaloFour 
Thanks for your answers, now it is clear!

**Comment by gafter** [comment]
If I understand this conversation, we've concluded that the behavior is by design and correct. That suggests we should close this issue. Is that right?

**Comment by Crispried** [comment]
I think yes, the issue could be closed.
