### ISSUE TITLE
Proposal: fullnameof operator

### ISSUE THREAD

**Issue by dsaf** [dotnet/csharplang#701]
Migrated from: https://github.com/dotnet/roslyn/issues/14474 and https://github.com/dotnet/roslyn/issues/7973

A well-know one, not much to add.

Doing this currently which is not amazing:

```csharp
public static class Extensions
{
    public static string fullnameof<T>() => typeof(T).FullName;
}

using static Extensions;

Console.WriteLine(fullnameof<SampleClass>());
```

**Comment by jnm2** [comment]
If we do this, `fullnameof` should return the **C# language** name, not the CLR type name (to the extent that they differ). That is the current philosophy behind `nameof` and I see the value. For example, `Foo` not ``Foo`1`` or ``Foo`1[System.Int32]``.

In other words, it should return what you type in C# to refer to the object, not the CLR representation.
This matters with nested classes because in C# you don't write `Namespace.ContainingType+NestedType`; you write `Namespace.ContainingType.NestedType`.

**Comment by janjoostvanzon** [comment]
I feel uneasy promoting my own framework here, but I made something for this a long time ago. It isn't perfect, but it will handle many common cases. You can call:

    ExpressionHelper.GetText(() => myVariable.MyList[i].MyProperty);

And get "myVariable.MyList[i].MyProperty" out.

A lot of my framework depends on this.
It won't cover full type names, though. I had something for that too, but I never got to port it to my current code base.

https://github.com/janjoostvanzon/JJ.Framework/blob/master/Framework/Reflection/ExpressionHelper.cs
https://github.com/janjoostvanzon/JJ.Framework/blob/master/Framework/Reflection/ExpressionToTextTranslator.cs

**Comment by jnm2** [comment]
@janjoostvanzon That's really cool! Now if only it was a compile-time constant and could be used in an attribute...

**Comment by janjoostvanzon** [comment]
@jnm2 That's what I thought when I made it. I vaguely remember it being 400x as slow as a literal string.

**Comment by janjoostvanzon** [comment]
Could have been 40x as slow. Not sure anymore.

**Comment by janjoostvanzon** [comment]
@jnm2 That's what I thought when I made it. That would give better performance, even though I did try to squeeze as much performance out of my code as I could. Still it cannot be faster than a literal string.

**Comment by alrz** [comment]
@dsaf 

There is a proposal  to make `typeof(T).FullName` a compile-time constant (https://github.com/dotnet/roslyn/issues/10972). Does that cover your use cases?

Also https://github.com/dotnet/csharplang/issues/522 suggests to add a shorthand for `nameof(Class.Method)`, e.g. `$Class.Method`, I'd added to that that we can use `$@Class.Method` to produce a string as it appeared in the source (https://github.com/dotnet/csharplang/issues/522#issuecomment-298505216).

**Comment by alrz** [comment]
> it would be nice to be able to refer to sub-namespaces and members

`$@Namespace.Class.Method` would allow that too, yes it does require to spell out all required parts but I don't think we can make it any shorter without losing flexibility.

**Comment by Meai1** [comment]
This stuff is ridiculous, an extra keyword just for something small like this? just add a method like Class.fullnameof

**Comment by HaloFour** [comment]
@Meai1 

The point of it being a keyword is that it could be used as a constant.  Invoking a method on the `Type` class doesn't result in a constant string and thus can't be used in something like an attribute.

I believe there is a separate proposal for having the compiler consider certain expressions on `typeof(T)` as constants, e.g. `typeof(Foo).FullName`.

**Comment by Meai1** [comment]
ok but this really sounds more like a problem about c# attributes. Why else require all these new keywords

**Comment by HaloFour** [comment]
@Meai1

The arguments used in attributes are required to be constants and embeddable directly in the assembly metadata.  That is a limitation of the CLR and not specifically of the C# language.  When the CLR actually instantiates the attribute it expects that the embedded constant matches the type of the constructor parameter or property so the C# compiler can't embed any alternatives, let alone something that represents an expression to be evaluated at runtime.  The best the C# compiler could do is to introduce a form of constant expressions (`constexpr`) which could be evaluated at compile time and their result directly embedded.

**Comment by wrummler** [comment]
This would be mighty convenient in some cases, especially when defining an [`EventSource`][event-source] subtype.

[event-source]: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netframework-4.7.1

I'm currently doing this:

```csharp
        // I'm repeating the full namespace in each case, even though I don't strictly need to, for better safety if/when refactoring moves things around.
        [EventSource(Name =
            nameof(Company) + "." +
            nameof(Company.ProductUmbrella) + "." +
            nameof(Company.ProductUmbrella.Product) + "." +
            nameof(Company.ProductUmbrella.Product.Feature) + "." +
            nameof(Company.ProductUmbrella.Product.Feature.Module) + "." +
            nameof(Company.ProductUmbrella.Product.Feature.Module.ETWEventSource))]
        public class ETWEventSource : EventSource
        {
```

I'd be delighted to be able to do this:

```csharp
        [EventSource(Name = fullnameof(ETWEventSource))]
        public class ETWEventSource : EventSource
        {
```

**Comment by IanKemp** [comment]
This should work for namespaces too!

I.e. `fullnameof(Full.Namespace.Name)` = `Full.Namespace.Name`

**Comment by CyrusNajmabadi** [comment]
> If we do this, fullnameof should return the C# language name, not the CLR type name (to the extent that they differ). That is the current philosophy behind nameof and I see the value. For example, Foo not Foo`1 or Foo`1[System.Int32].

How does this work with generics?

**Comment by npodbielski** [comment]
This would be most usable in Obsolete attribute. 
`[Obsolete("use "+fullnameof(NewClass.NewMethod)+" instead.")]'
For now this is necessary to use
`[Obsolete("use "+nameof(NewClass) +"." + nameof(NewClass.NewMethod)+" instead.")]'
Which is a really tiresome for few dozens of members.

**Comment by alrz** [comment]
I think the ability to use interpolated strings in attributes would make that less tiresome.  But it seems that no one on the team has championed it yet.

**Comment by npodbielski** [comment]
Probably because $ operator is just really string.Format in disguise and attributes needs const strings.
Which would be better? I think new operator that is translated to just plain string would be better since $ could be confusing (it would be behave differently depending on the place of use).

**Comment by alrz** [comment]
@npodbielski `string.Format` is already optimized away in certain cases, e.g. where all inserted expressions are strings. ([example](https://sharplab.io/#v2:D4AQDABCCMDcCwAoEBmKAmCBhCBvJEhUaMkAsgBQCUeBR9IA7BACQBEAtgKYAuAFgHsAJgC48AOwCG3AQDMKZKgF82CRPSVIlQA=))

**Comment by npodbielski** [comment]
Cool. I didn't know. Anyway still, if we are talking about refactoring tools, IMHO it would complicate things (i.e. refactor by conversion $ to string.Format) because tool would have to inspect if $ is not used in attribute. 
And `[Obsolete($"use {nameof(NewClass)}}.{nameof(NewClass.NewMethod)} instead.")]` is still more complicated then `[Obsolete("use "+fullnameof(NewClass.NewMethod)+" instead.")]` or some other syntax that would do the same thing.

**Comment by gistofj** [comment]
honestly I'd be happy if the `nameof` operator didn't reduce names. For example, the following code
```C#
System.Console.WriteLine(nameof(System.String));
System.Console.WriteLine(nameof(String));
```
writes 
```
String
String
```
I'd much rather see it output
```
System.String
String
```
but that could open a whole can of worms... so I can very much live with `nameof` as is.

**Comment by HaloFour** [comment]
I'd be happy if `typeof(String).Name` and `typeof(String).FullName` could be considered constant values evaluated by the compiler.

**Comment by mwpowellhtx** [comment]
Perhaps a corollary to this one, I have a case where `namespaceof` would also be interesting. i.e.

```C#
namespace Foo
{
    class Bar { }
}

// ...

const string barNameSpace = namespaceof(Bar); // "Foo" const string
```

I mean, if we can discover `nameof` as a `const string`, I imagine it would not be that difficult to do a similar thing for its `namespace`.
