### ISSUE TITLE
Nullable Reference warning despite `.Where()` filter

### ISSUE THREAD

**Issue by JoeyHerrington** [dotnet/csharplang#7058]
I have a list of objects with a nullable property.  When I filter out the nulls using a `.Where()` statement, I still get a **CS8602: Dereference of a possibly null reference.** warning.  Since I filtered out possible null values, this warning should not appear.

TargetFramework = net7.0

```c#
var fooList = new List<Foo> {
    new Foo { Bar = "Bar1" },
    new Foo { Bar = "Bar2" },
    new Foo { Bar = string.Empty },
    new Foo { Bar = null }
};

var filteredFoos = fooList
    .Where(f => !string.IsNullOrEmpty(f.Bar))
    .Select(f => f.Bar.ToLower()) // CS8602: Dereference of a possibly null reference.
    .ToList();

public class Foo
{
    public string? Bar { get; set; }
}
```

**Comment by 333fred** [comment]
(Not planned is used for duplicate items).
