### ISSUE TITLE
[Proposal] Allow a Brotli compression level between Fastest and Optimal

### ISSUE THREAD

**Issue by SvenViking** [dotnet/csharplang#7135]
# Summary

Allow the System.IO.Compression.Brotli compression level to be set to a level or levels in-between the "Fastest" and "Optimal" settings, whether by allowing an explicit compression level to be passed to a BrotliStream or BrotliEncoder via an enum or integer value (outside of .NET, Brotli supports compression levels between 0 and 11), or by adding a new member to the CompressionLevel enum. 

# Motivation

The [.NET Blog article introducing support for Brotli compression](https://devblogs.microsoft.com/dotnet/introducing-support-for-brotli-compression/) explains that:

- At the Fastest setting, Brotli compression ratios and times are not much better than GZip at its Fastest setting.
- At the Optimal setting, Brotli compression ratios are good, but it is exceedingly slow, with compression times *orders of magnitude higher* than GZip at its Optimal setting.
- At medium compression levels such as Level 5, Brotli compression ratios are greatly improved for minimal time penalties, essentially providing the best of both worlds with both higher ratios and faster speeds than GZip's Optimal setting.

However, as far as I have been able to find, there is no way to use the suggested Compression Level 5 or any other level between the Fastest and Optimal settings via .NET's Brotli implementation. This would seem to be far from optimal for many use cases.

**Comment by theunrepentantgeek** [comment]
I think this is a library request, not a language one. 

This repo is for discussion of future language features.

**Comment by SvenViking** [comment]
Ah, apologies for the mistake. Would you happen to be able to tell me where such a request should be made?

**Comment by SvenViking** [comment]
(Closing the request.)
