### ISSUE TITLE
proposal: add async foreach/ienumarator

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/csharplang#714]
async foreach
async ienumerator

while(await enumerator.Move())
{
     process((await?) enumerator.Current)
}
.....
async foreach(var a in list)
{
     process(a);
}

Thanks.

**Comment by svick** [comment]
I think this is a duplicate of https://github.com/dotnet/csharplang/issues/43 and https://github.com/dotnet/csharplang/issues/390.

**Comment by lobster2012-user** [comment]
Thanks. Closed.
