### ISSUE TITLE
[Proposal]: Native C# compiler support

### ISSUE THREAD

**Issue by taozuhong** [dotnet/csharplang#7149]
# Native compiler support

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
Make C# compiler like C/C++ without Manage runtime support

## Motivation
[motivation]: #motivation
I do like C# language, but manage runtime, I do hope C# language have a native compiler support.

Now I'm using C# native version: [Vala](https://gitlab.gnome.org/GNOME/vala)

**Comment by huoyaoyuan** [comment]
Does [NativeAOT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/) meet your requirement? There are even someone using it to write UEFI firmware (of course not using the BCL).
