### ISSUE TITLE
Issue with static abstract in interfaces

### ISSUE THREAD

**Issue by Mathew-Kochekkan** [dotnet/csharplang#7264]
```
namespace StaticAbstractTest
{

    public interface ITest1<TSelf> where TSelf : ITest1<TSelf>
    {
        static abstract bool SomeFlag { get; }
    }

    public interface ITest2<TSelf> : ITest1<TSelf> where TSelf : ITest2<TSelf>
    {
        static bool ITest1<TSelf>.SomeFlag => true;
    }

    public struct Test2 : ITest2<Test2>
    {
    }

    public class Class2 : ITest2<Class2>
    {
    }

    internal class Program
    {
        static void Main(string[] args)
        {
            var test = new Test2();

            Console.WriteLine("Hello, World!");
        }
    }
}
```

The above code fails with fatal error when trying to run it. However if I replace var test = new Test2(); with var test = new Class2(); , it succeds and runs just fine. Am I missing something.

Attaching the project below
[StaticAbstractTest.zip](https://github.com/dotnet/csharplang/files/11683441/StaticAbstractTest.zip)

**Comment by CyrusNajmabadi** [comment]
What 'Fatal Error' do you get?

**Comment by Mathew-Kochekkan** [comment]
The console window I get when running the project is attached

![Fatal Error](https://github.com/dotnet/csharplang/assets/66130764/31726111-7b54-4f6c-9531-32496a0dbcdc)

**Comment by CyrusNajmabadi** [comment]
Failure in the runtime shuold go to dotnet/runtime.  I'll move you there.

**Comment by CyrusNajmabadi** [comment]
Hrm.. github won't let me move you.  You might want to just close this out and reopen there yourself.  Sorry! :(

**Comment by Mathew-Kochekkan** [comment]
Ok. Will post it there thank you

**Comment by Mathew-Kochekkan** [comment]
Will post it there. Thank you

**Comment by Mathew-Kochekkan** [comment]
Posted in dotnet/runtime as 

 Issue with static abstract in interfaces #87248
