### ISSUE TITLE
Track proposals, status, meetings and discussions in a single wiki document

### ISSUE THREAD

**Issue by eyalsk** [dotnet/csharplang#73]
I'm proposing to create a wiki page that is basically a table that tracks all the relevant information related to proposals.

**Something like this:**

C# 7.1

| Proposal | Status | Recent LDM | Active Discussion |
|:----------:|:--------:|:--------------:|:-------------------:|
| [Records](https://github.com/dotnet/csharplang/blob/master/proposals/records.md) | Proposed | [Jan 28, 2015](https://github.com/dotnet/csharplang/blob/master/meetings/2015/LDM-2015-01-28.md) |  [#39](https://github.com/dotnet/csharplang/issues/39)|

C# 7.0

| Proposal | Status | Recent LDM | Active Discussion |
|:----------:|:--------:|:--------------:|:-------------------:|
| Local functions | Completed| [Oct 18, 2016](https://github.com/dotnet/csharplang/blob/master/meetings/2016/LDM-2016-10-18.md) |  [#56](https://github.com/dotnet/csharplang/issues/56)|

* _The community can help and keep this document up-to-date._

* _The links are only for demonstration._

The TypeScript team has a similar [document](https://github.com/Microsoft/TypeScript/wiki/Roadmap) even though it's vastly different.

Such document would be valuable for few reasons:

1. It can help navigating between the various documents and issues.

2. It can help people stay up-to-date with the language and have everything they need to know in single place.

3. It can reduce duplications because sometimes people search for features but they never find them (due to wrong keywords) and end up creating their own issue.

**Comment by HaloFour** [comment]
I think that any such Wiki page should be as auto-generated as possible from the list of the proposals in the repo as well as the tagged issues.  That way as long as the script runs periodically and updates the Wiki that page can be kept current just by the normal processes adopted for proposals.

**Comment by scottdorman** [comment]
As reference, this is the split issue from part of the discussion on https://github.com/dotnet/csharplang/issues/66.

**Comment by scottdorman** [comment]
@HaloFour So you're proposing some sort of offline script that updates a document in the repo?

In general, I like the idea of a wiki-like document. (I still think projects might be a better approach though.) Is Status the current status of the proposal (Proposed, Not Implemented, etc. - basically the set of checkboxes at the top of the proposal template)?

I like having the most recent LDM here, but there is already a section in the proposal which is supposed to list links to the relevant LDMs (with a summary of the changes) so it seems like having the most recent one listed here would be both redundant and additional work (unless it were able to be automated in some fashion).

**Comment by eyalsk** [comment]
@scottdorman 

> Is Status the current status of the proposal (Proposed, Not Implemented, etc. - basically the set of checkboxes at the top of the proposal template)?

Yes.

> I like having the most recent LDM here, but there is already a section in the proposal which is supposed to list links to the relevant LDMs (with a summary of the changes) so it seems like having the most recent one listed here would be both redundant and additional work 

I don't think that it's redundant at all.

In both of these cases you have to click on the proposal to check for status or LDM notes, it's much better to see these details up-front in the table.

About the additional work, the community can help, it's not such a big deal, however, if they can automate it, this would be superb but I wouldn't count on this and doing it manually isn't such a daunting task.

You can look at other teams like VSCode, TypeScript and ASP.NET where these documents is just part of their process.

**Comment by eyalsk** [comment]
@MadsTorgersen Can you please take a look at this and tell us your thoughts about it?

Thanks.

**Comment by eyalsk** [comment]
@gafter Any plans for this sort of things? I don't mind helping with this or even maintain it, I really feel like it would help. :)

**Comment by gafter** [comment]
@eyalsk When things settle down a bit we plan to write a document summarizing the status of the various proposals. It may be a few weeks before we can do that. We're thinking of using the Milestone labels to suggest when we think the proposals could happen. With few exceptions (private protected` comes to mind) proposals (like "records") that affect the shape of APIs that can be expressed are unlikely to occur in point releases.

**Comment by eyalsk** [comment]
@gafter Okay, thank you.
