### ISSUE TITLE
Proposal: Interesting way built Factory Pattern on Language level

### ISSUE THREAD

**Issue by kogoia** [dotnet/csharplang#731]
What if we will introduce `constructor` constraint in `interface`s, something like this:
```cs
public interface IFoo 
{
	constructor(int number, string text); 
        new(int number, string text); // maybe this better
	int Sum(int number);
}
```

And after this new keyword `type` or more suitable word:
```cs
public Bar 
{
	private type IFoo _type;
	private int _number;
	public Bar(type IFoo type, int number) 
	{
		_type = type;
		_number = number;
	}	
	public IFoo Create(string message) 
	{
		return new _type(_number, message)
	}
}
```

After this we can use it as follow

```cs
var foo = new Bar(Foo, 10).Create("Hello"); // Foo is class inherited from IFoo interface
var res = foo.Sum(5);
```

I do not know how hard it will be to implement this on the .NET platform, but it will be very nice.

**Edited:**

```cs
    public class Bar
    {
        private readonly type IFoo _tp;
        public Bar(type IFoo tp)
        {
            _tp = tp
        }

        public IFoo Create(string message)
        {
            return new _tp(message);
        }
    }

    new Bar(curried Foo(a)).Create("Hello"); // or lazy Foo(a)
    new Bar(new::Foo(a)).Create("Hello");
```

Behind `new::` compiler generate some decorator class with `curried` constructors.

If class haven't constructor then:
```cs
type instance = new::Foo(); // or new::Foo
Foo foo = new Foo();
```
And instead of `new Bar(Foo, 10)` use `new Bar(new::Foo)` this more meaningful then `new Bar(Foo)`

**Edited 2**

```cs
    public class Bar
    {
        private readonly type IFoo _tp;
        public Bar(type IFoo tp) 
            where type IFoo : new(int, string)
        {
            _tp = tp
        }

        public IFoo Create(string message)
        {
            return new _tp(message);
        }
    }
```

Instead of `type` keyword we can use `<>` as in generics

```cs
    public class Bar
    {
        private readonly <IFoo> _tp;
        public Bar(<IFoo> tp) 
            where <IFoo> : new(string)
        {
            _tp = tp
        }

        public IFoo Create(string message)
        {
            return new _tp(message);
        }
    }
     new Bar(new::Foo(a)).Create("Hello");
```
`new::Foo(a)` must generate on the fly, new class with constructor which takes one parametre (something like anonymous objects)

**Comment by DavidArno** [comment]
By adding a constructor contraint to `IFoo`, you are forcing all implementation to provide that constructor, whether it makes sense for them to do so, or not. I might have a `ZeroFoo`, which doesn't need a `number` passed to it, as it'll always be zero. But I'd be forced to provide that two parameter constructor, and ignore `number`, thus breaking the Liskov substitution principle and Principle of least astonishment.

And such a construct isn't needed. In your example, a `Func<string, IFoo>` delegate could be used instead:
```cs
public Bar 
{
    private Func<string, IFoo> _fooCreator;

    public Bar(Func<string, IFoo> fooCreator) => _fooCreator = fooCreator; 

    public IFoo Create(string message) => _fooCreator(message);
}

var foo = new Bar(message => new Foo(10, message)).Create("Hello");
var res = foo.Sum(5);
```

It achieves the same result, without introducing "new is glue" coupling between `Bar` and how an `IFoo` gets created.

**Comment by kogoia** [comment]
In this case I will be create another `constructor`

```cs
public interface IFoo
{
    constructor();
    constructor(int number, string text);
    int Sum(int number);
}

public class Foo
{
    public Foo()
         : this(0, String.Empty) {}
    public Foo(int number, string text) { ... }
} 
```

About this `new Bar(message => new Foo(10, message))`, I also do on same way, but I would like hide creating logic inside class, not pass as function in constructor.

**Comment by kogoia** [comment]
This result may achieve with this way

```cs
    public class FooCreator
    {
        private readonly int _number;

        public FooCreator(int number)
        {
            _number = number;
        }
        public IFoo Create(string message)
        {
            return new Foo(_number, message);
        }
    }

    new Baar(new FooCreator(10)).Create("Hello");
```

**Comment by DavidArno** [comment]
So you prefer to create a 12 line class, rather than `message => new Foo(10, message)`? Each to their own, I guess 😀

**Comment by kogoia** [comment]
Yes :) 
Therefore I would want to have this way of do same thing: `new Bar(Foo, 10)`

**Comment by kogoia** [comment]
IMO such things are important in large projects, where important maintebility. I mean hide all things within classes and have only declarative description of code on top level, like this:
```cs
    new TrimmedText(
        new UpperCaseText(
            new UTF8Text(
                 new Text(...)
            )
        )
    )
```
This code snipped not related with this case, its only example, what I mean by declarative description.

**Comment by sharwell** [comment]
> But I'd be forced to provide that two parameter constructor, and ignore number, thus breaking the Liskov substitution principle and the principle of least astonishment.

@DavidArno LSP wouldn't apply here. In your scenario, you assumed that `number` was not needed by some specific type implementing the interface, which implies that the value passed to the constructor for `number` is not observable through other members of the interface. A violation of LSP would require a type to claim to implement the interface, yet fail to perform the operations described by the interface (e.g. `ImmutableArray<T>`'s "implementation" of `IList<T>.Add`).

Demonstrating a violation of least astonishment in this case would ideally involve showing that it is not clear to the caller what would be considered a valid value for `number`, or showing that the side effects caused by a particular value do not align with expectations. If `number` is ignored by a particular implementation and the value is not exposed through the interface (previous paragraph), then the side effects part wouldn't apply. I would argue that a claim of least astonishment can't be applied generally to this feature, though like any other feature it would be possible for it to arise in specific situations.

**Comment by alrz** [comment]
Construction seems irrelevant to what interfaces provide as a contract between types that are *already constructed*.

**Comment by alrz** [comment]
I'll note that shapes (https://github.com/dotnet/csharplang/issues/164) could probably cover this case because they are more or less just a constraint.

**Comment by sharwell** [comment]
@alrz I was looking for the shapes proposal, and yes I agree that it is a much more comprehensive solution to the underlying problem, provided it actually gets implemented.

**Comment by HaloFour** [comment]
I'm with @DavidArno that passing a delegate already solves this problem very neatly.  Simply pass a factory delegate.  It neatly abstracts how the type is created and allows you to use a factory class as an intermediary.  The only thing that I think could improve on that is the language offering a simpler syntax for taking a delegate to a constructor.

**Comment by svick** [comment]
@HaloFour 

> The only thing that I think could improve on that is the language offering a simpler syntax for taking a delegate to a constructor.

For the record, the proposal for that is https://github.com/dotnet/csharplang/issues/674.

**Comment by kogoia** [comment]
Maybe somthing like this:

```cs
    public class Foo
    {
        private readonly type IBarp _tp;
        public Foo(type IBar tp)
        {
            _tp = tp
        }

        public IFoo Create(string message)
        {
            return new _tp(message);
        }
    }

    new Foo(curried Bar(a)).Create("Hello"); // or lazy Bar(a)
```

**Comment by DavidArno** [comment]
@svick, @HaloFour,

I saw that proposal recently and thought "what possible use could anyone have for treating a constructor as a delegate?" Mere days later, along comes this proposal showing a really good use-case. I live and learn...

**Comment by svick** [comment]
@kogoia I have two questions for you:

1. What is the problem that you're trying to solve? You keep proposing various things that could be done, but as far as I can tell, never explain *why* should they be done.
2. What makes your proposal significantly better than existing alternatives, especially lambdas/delegates? If an alternative that's almost as good as what you're proposing already exists, that makes introducing a new feature much less likely.

**Comment by kogoia** [comment]
Good questions

The @DavidArno answer solves my problem very well, but I prefer [this](https://github.com/dotnet/csharplang/issues/731#issuecomment-314082265) way, because I think [so](https://github.com/dotnet/csharplang/issues/731#issuecomment-314085394)

I would like that C# give us more simpler way do things such this.

```cs
new Bar(new::Foo(10)).Create("Hello");
new Bar(new::Foo, 10).Create("Hello");
```

It's goon when such things builtin in Language. As I know C# is more for OOP then FP, and I against pass naked functions ( lambdas/delegates) as parameters. And I think the language should have a pronounced character, which in this case is OOP.

I'm not against FP, it's powerful paradigm and LINQ is elegant implementation of FP things, but it would be good to have another way to do some things more object-oriented.

Maybe I wrong about this specific way integrate decorator pattern on language level, but I believe that exist more elegant way to do this. So why not find it?!:)

**Comment by HaloFour** [comment]
The OOP method already exists: pass a factory instance implementing some interface.  This notion of having constructor inheritance or implementation is not OOP.  Constructors are not a part of the contract of a type and they are not inherited in any OOP language of which I am aware.

The character of C# has always been OOP with elements of functional programming.  Delegates were there in 1.0 and are a critical part of the design of the framework.  Arguing that you think that C# should ignore part of it's core heritage and adopt your preferred paradigm is not likely going to win any arguments towards proposals like this any more than it does for people who demand that C# be more functional.

**Comment by kogoia** [comment]
Good argument, I agree, that constructor inheritance of implementation is not OO.

What about his way, instead of add constraints in interface we do vice versa and expect instance of object with constructor, like this:

```cs
    public class Bar
    {
        private readonly type IFoo _tp;
        public Bar(type IFoo tp) 
            where type IFoo : new(int, string)
        {
            _tp = tp
        }

        public IFoo Create(string message)
        {
            return new _tp(message);
        }
    }
```

Instead of `type` keyword we can use `<>` as in generics

```cs
    public class Bar
    {
        private readonly <IFoo> _tp;
        public Bar(<IFoo> tp) 
            where <IFoo> : new(string)
        {
            _tp = tp
        }

        public IFoo Create(string message)
        {
            return new _tp(message);
        }
    }
     new Bar(new::Foo(a)).Create("Hello");
```
`new::Foo(a)` must generate on the fly, new class with constructor which takes one parametre (something like anonymous objects)

What do you think about this? My goal is that language must promote write code in OO style, as this do another FP languages for FP paradigm. I mean we lacks tools to express OO in elegant way, as in F# we can elegant write FP code.

And I don't say that we must ignore delegates/lambdas:)

**Comment by HaloFour** [comment]
@kogoia 

There are proposals for extending generic constraints to support things like constructor parameters.  In my opinion that's the wrong way to go since you limit how the object is created.

The shapes proposal also fits since it would allow for an expanded constraints which are enforced at compile time.  It could also potentially support extension constructors allowing for abstraction in the creation of a specific type even when its own constructor doesn't match that constraint.

I think that given those options that the likelihood of the team picking up yet another way to solve this problem isn't going to be that likely, especially if your argument boils down to wanting to make C# more OOP regardless of the existing (and very succinct) solutions.

**Comment by kogoia** [comment]
It's clear, I close the issue.
