### ISSUE TITLE
Proposal: provide a way to forbid struct assignment

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#733]
I hope that C# can provide syntax to forbid some structs to assign each other.
Assignment-forbidden struct must follow these rules:
1. When it is used as a function parameter, it must be passed by ref.
2. It can be initialized, but can't assign each other by value. (Can't copy value, but can copy ref).
3. It can be embedded in class or another assignment-forbidden struct, but can't be embedded in normal struct.

For example:
```C#
struct StringEditor
{
    private string str;
    public StringEditor(char c, int n) { this.str = new string(c, n); }
    public char this[int index]
    {
        get { return str[index]; }
        unsafe set 
        {
             if (index<0 || index>=str.Length) throw IndexOutOfRangeException();
             fixed(char *p=str) { p[index]=value; } 
        }
    }
    public string Finish() { string s=this.str; this.str=null; return s; }
    public void ReInit(char c, int n) { this.str = new string(c, n); }
}

static string[] GetRandomStrings(int count, int length)
{
    string[] result = new string[count];
    Random r = new Random();
    int i;
    for(i=0;i<count;i++)
    {
        StringEditor se=new StringEditor(' ', length);
        int j;
        for(j=0;j<length;j++) se[j]=(char)r.Next(32, 126);
        result[i]=se.Finish();
    }
    return result;
}

static void main()
{
    ......
    string[] ss = GetRandomStrings(1000, 1000);
    ......
}
```
I think the code above is efficient for no extra allocation or copying. Even `StringBuilder` can't do this, because `StringBuilder.ToString` means copying.
If I use `StringEditor` myself, no problem; but if I provide it to other people, I'm concerned that they can't use it correctly. They might use it like this:
```C#
static void sample()
{
    var se1=new StringEditor(' ', 100);
    var se2=se1; //se1 and se2 share the same internal string, this might cause bugs! I want to forbid this.
    ......
}
```
So I hope to have a mechanism to forbid specific structs to assign each other.

**Comment by ygc369** [comment]
Maybe some people want to advise me to make `StringEditor` a class. That's OK, but might cause extra heap allocations, especially when people use it incorrectly.

**Comment by ufcpp** [comment]
Similar to Destructible types?
https://github.com/dotnet/csharplang/blob/master/meetings/2015/LDM-2015-02-11.md

**Comment by ygc369** [comment]
@ufcpp 
Oh yes, quite similar. I think this proposal is part of that.
