### ISSUE TITLE
Discussion : Local Properties

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/csharplang#734]
Since C# 7 added Local Functions how does the community feel about local get only properties? It provides a kind of feature symmetry with local functions. I don't know if it is a good idea, but i didn't see any discussion over it.

As with normal properties they are useful to:

- Delay execution of an expression
- Reduce repetition
- Give a 'name' to a live expression
- Ensure a calculated value is always up-to-date

Some design considerations.

- They should be restricted to getter-only. So they are just calculated values.
- They should only allow the `=>` syntax. The `{get { }}` syntax is too verbose, it implies that `set` is allowed and it encourages non-trivial expressions in local property bodies.

A simple example:

### Before
```C#
public IEnumerable<int> Smoothed(int[] data, int windowSize)
{
    int windowStart = 0;
    ArraySegment<int> nextSegment() => new ArraySegment<int>(data, windowStart++, windowSize);
    
    while((windowSize + windowStart) < data.Length)    
        yield return smooooth(nextSegment());
    
}

private int smooooth(ArraySegment<int> segment)
{
    int value = 0;
    for(int i = segment.Offset; i < segment.Count; i++)
        value += segment.Array[i];
    return value / segment.Count;
}
```

### After

```C#
public IEnumerable<int> Smoothed(int[] data, int windowSize)
{
    int windowStart = 0;
    bool windowValid => data.Length < (windowSize + windowStart);//local property
    ArraySegment<int> nextSegment() => new ArraySegment<int>(data, windowStart++, windowSize);

    while(windowValid)
        yield return smooooth(nextSegment());    
}

private int smooooth(ArraySegment<int> segment)
{
    int value = 0;
    for(int i = segment.Offset; i < segment.Count; i++)
        value += segment.Array[i];
    return value / segment.Count;
}
```

This example doesn't necessarily demonstrate a killer usage but similar to local functions, i would find uses for them.

The downsides are pretty obvious:

- potential loss of performance in hot functions 
- Increases syntax density
- Potentially low benefit
- more 'tricks' for ill-tempered devs to unleash on unsuspecting codebases

**Comment by Logerfo** [comment]
> They should only allow the => syntax.

This implies that the return value must always be a single expression, which reduces the feature benefit.

**Comment by HaloFour** [comment]
While the idea of a local identifier that refers to a live calculation is intriguing I don't really see that much novelty here to justify it.  Local functions seem more than sufficient and make it clear that what you're invoking does perform some calculation.  The only difference is the inclusion of parenthesis:

```cs
public IEnumerable<int> Smoothed(int[] data, int windowSize)
{
    int windowStart = 0;
    bool windowValid() => data.Length < (windowSize + windowStart);//local function
    ArraySegment<int> nextSegment() => new ArraySegment<int>(data, windowStart++, windowSize);

    while(windowValid())
        yield return smooooth(nextSegment());    
}
```

**Comment by alrz** [comment]
You define "accessors" aka properties to hide implementation logic for a specific "value", on the other hand, local functions enable code sharing in a specific scope, for example. You can see how the former doesn't really make sense in such context.

**Comment by Logerfo** [comment]
I guess a proposal "Make parenthesis optional in both call and declaration for parameterless local functions" would make more sense, but I'm not sure if that's possible.

**Comment by alrz** [comment]
An invocation without parens is called a method group. So that would change the semantics of an existing syntax.

**Comment by AlgorithmsAreCool** [comment]
@Logerfo yes it reduces the benefit, but i think that allowing complex expressions in the feature is inviting messy code. 

@alrz I'm not sure the only purpose of property accessors is to hide implementation.  Additionally you can use them to delay calculation, and avoid caching values in locals. 

@HaloFour I am intrigued by the concept of captured live expressions as well. I need to try to write a more compelling use case for them.

**Comment by alrz** [comment]
>I'm not sure the only purpose of property accessors is to hide implementation. Additionally you can use them to delay calculation, and avoid caching values in locals.

That *is* hiding implemention logic. It helps you decide later whether it should be cached or not without breaking binary backward compat.

**Comment by BraedonWooding** [comment]
You can have constant local variables like;
```CSharp
public void Foo() {
    const int x = 0;
}
```
Though obviously that doesn't include non compile time constant values, but honestly you also have to include the fact that is the scope independent of the function?  Like how C/C++ handle static local variables where they stay and don't get re-written upon function call, in that case one should handle those first before the discussion of read only get anywhere and honestly why have that property syntax it isn't a property it's a field, a better syntax would be `readonly Foo bar = new Foo();` to represent that.

**Comment by AlgorithmsAreCool** [comment]
I thought i closed this ages ago?!

**Comment by PathogenDavid** [comment]
Why close it? Even though it's inactive, the request is still valid as far as I can tell.

**Comment by AlgorithmsAreCool** [comment]
@PathogenDavid 
I think the consensus is that it isn't a good idea, the semantics are kinda odd and probably waaaay too subtle.

I think local functions are a better way to go.
