### ISSUE TITLE
"nonabstract" generic parameter contraint

### ISSUE THREAD

**Issue by melanchall** [dotnet/csharplang#742]
There is a real problem with constraining generic parameters with interface or abstract type. Let's say we have a method:

```csharp
public static T ConvertTo<T>(...) where T : ISomeInterface
{
    // return an instance of T
}
```

Obviously this method can be called like this:

```csharp
ConvertTo<ISomeInterface>(...);
```

But it doesn't make sense for this method since only instances can be returned. The same problem with constraining by abstract classes.

At now I just throw `NotSupportedException` if `typeof(T)` is invalid for particular method. But this check occurs in run-time. It would be much better to have ability to filter out non-instantiable types at compile-time.

I suggest to allow constraining generic parameters by instantiable types. For example, with `nonabstract` keyword:

```csharp
public static T ConvertTo<T>(...) where T : ISomeInterface, nonabstract
{
    // return an instance of T
}
```

**Comment by HaloFour** [comment]
Are you expecting `ConvertTo` to actually instantiate `T`?  If so, that's what the `new()` constraint is for.  Yes, it is limited to parameterless and there are proposals that seek to expand that.

**Comment by melanchall** [comment]
@HaloFour Yes. `ConvertTo` instantiate `T`. `new()` force to have a parameterless constructor. I need a way to constraint generic parameter with instantiable types only. This constraint shouldn't care about presence of specific constructors or any other members of a type. Only this method knows how to instantiate `T`.

I've searched list of feature requests before posting my issue and didn't find any proposal for what I want. But of course I could overlook the same issues. Sorry if it is so.

**Comment by DavidArno** [comment]
Whilst certain folk are going to roll their eyes in dispair here (I'm looking at you, @eyalsk 😉), I'm going to say it anyway...

This sort of thing can already be handled with a semantic analyzer, which you could write yourself (and bundle it with your library in a nuget package, for example). For example, with the annotation,
```cs
[NonAbstractOnly]
public static T ConvertTo<T>(...) where T : ISomeInterface
{
    // return an instance of T
}
```
The the analyzer can check every call to `ConvertTo()` at compile time to ensure the supplied parameter is an instantiable type and can generate a compiler error if not.

**Comment by HaloFour** [comment]
If a new generic type parameter constraint is under consideration I would prefer one that could describe the required parameter types accepted by the constructor.  That way you can write the method in a proper and type-safe manner using the `new` operator rather than breaking out reflection.  A `nonabstract` constraint doesn't buy you any of that and it would effectively be the only generic constraint that doesn't affect the shape of instances of that generic type.

```cs
public static T ConvertTo<T>(Foo foo) where T : ISomeInterface, new(Foo) {
    return new T(foo);
}
```

Speaking of shapes, I wonder if [that proposal](https://github.com/dotnet/csharplang/issues/164) would be able to handle this case.

**Comment by melanchall** [comment]
@DavidArno Hmm... so I need to write another tool (semantic analyzer) by myself for this task? It's not worth it. If this the only way and implementing of suggested constraint is not expected then I will stick with throwing the `NotSupportedException` :(

**Comment by Joe4evr** [comment]
@DavidArno The following can actually be done (why, who knows? 🙃 )
```cs
public static T ConvertTo<[NonAbstractOnly] T>(...) where T : ISomeInterface
{
    // return an instance of T
}
```

**Comment by melanchall** [comment]
@HaloFour What if different types should be instantiated via different constructors?

**Comment by HaloFour** [comment]
@melanchall 

In my opinion that doesn't sound like it's a good fit for generic type constraints.

**Comment by Joe4evr** [comment]
> `new()` force to have a parameterless constructor. I need a way to constraint generic parameter with instantiable types only.

Not quite, `new()` also enforces the type to be non-abstract already. Otherwise you get (emphasis mine):
> error CS0310: 'C' must be a **non-abstract** type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'X.Do<T>()'

**Comment by melanchall** [comment]
@Joe4evr Yes, but unfortunately non-abstractness goes along with required parameterless constructor. I just mentioned part of the constraint's description that is important for my case.

Well.. I'll be waiting for great C# improvements that will solve all my programming problems :)

**Comment by Joe4evr** [comment]
That is true, and it would be nice to catch abstract types being passed as a type-parameter regardless of their constructor at compile time, rather than at runtime (would help *a lot* in DI-related scenarios).

**Comment by eyalsk** [comment]
@DavidArno We already have "Extensions everything", we just need to have a new issue and name it "Analyzers everywhere", haha.. 😆 

But really my opinion about analyzers is that they are good when it comes to provide guidance and to enforce all sorts of practices but when you find yourself writing an analyzer for something that the type system is the better tool for the job but is limited in the language then maybe something needs to be done there.

My rule of thumb is the moment you write an analyzer and is mandatory then analyzers is the wrong tool for the job.

**Comment by CyrusNajmabadi** [comment]
What is the use case for this proposal?  I've seen abstract (har har) ideas thrown around, but i don't know the actual concrete cases where this is desirable.

**Comment by melanchall** [comment]
@CyrusNajmabadi Use case described in first post. It is real use case, not an imaginary one.

**Comment by CyrusNajmabadi** [comment]
I don't understand the first use case.  You say you need an instance.  But you'll always get an instance.

**Comment by jnm2** [comment]
@CyrusNajmabadi He's saying the method needs a guarantee that it can construct an instance of the given type.

@melanchall Why not take a `Func<T>` factory?

**Comment by jnm2** [comment]
@melanchall Or `Func<int, int, T>` or whatever you need?

**Comment by CyrusNajmabadi** [comment]
> He's saying the method needs a guarantee that it can construct an instance of the given type.

I'm not sure how saying "this type is not abstract" gives a guarantee that it can construct an instance of the type.  How would it actually do that?

**Comment by eyalsk** [comment]
One thing I don't understand though, how come you have a function that takes any T and require you to have specific constructor? wouldn't you expect T to be an abstract class?

**Comment by melanchall** [comment]
@eyalsk If your question is for me - I didn't said anything about constructor. I suggested concrete idea: ability to constraint type parameter with non-abstract types. It doesn't matter what constrcutors have implementations of `T`.

Now I see the long discussion that goes away from my first post with each comment. So it is time to close this issue...

**Comment by jnm2** [comment]
@melanchall I notice discussions will tend to wander if you don't provide concrete examples up front of what it looks like when it is used and why there are no good alternatives.

**Comment by jnm2** [comment]
> But it doesn't make sense for this method since only instances can be returned. The same problem with constraining by abstract classes.

But *everywhere* interfaces and abstract classes are used, they always do represent instances. I can have an instance of `IEnumerable`. I can have an instance of `Stream`. Of course it's always more derived than I can see through static typing at compile time, but the whole point of object-oriented programming is that the exact most derived type doesn't matter. You only work with the type that has the minimum you need.

**Comment by jnm2** [comment]
If you ever do need to know an instance's most derived type, that means the type is in violation of the https://en.wikipedia.org/wiki/Liskov_substitution_principle.

> If S is a subtype of T, then objects of type T may be replaced with objects of type S (i.e. an object of type T may be substituted with any object of a subtype S) without altering any of the desirable properties of T (correctness, task performed, etc.)
