### ISSUE TITLE
CultureNotFoundException: Culture is not supported. (Parameter 'culture') 4096 (0x1000) is an invalid culture identifier.

### ISSUE THREAD

**Issue by UdhayaKumarDuraisamy** [dotnet/csharplang#7483]
`CultureInfo cultureInfo = new CultureInfo(CultureInfo.CurrentCulture.LCID);`

When using the above code with the "en-AT" culture, the below exception occurred. I'm using a Blazor project and I rendered the project default in the en-AT culture.

Exception : CultureNotFoundException: Culture is not supported. (Parameter 'culture')
4096 (0x1000) is an invalid culture identifier.

**Comment by Rekkonnect** [comment]
Better report this in dotnet/runtime I believe
