### ISSUE TITLE
Semicolons after types and namespaces

### ISSUE THREAD

**Issue by miloush** [dotnet/csharplang#751]
Why are semicolons allowed after types and namespaces (resp. one semicolon after each)?

I.e. you can write
```C#
namespace N {
{
    class C
    {
        class M { };
    };
}
;
```
I tried to look into the C# specification for supporting this but was unable to spot it.

**Comment by jnm2** [comment]
Because you can have using directives which are like statements in the sense that they must be semicolon-separated.

**Comment by jnm2** [comment]
Once you have semicolon-separation going on, I'd expect it to be just like the semicolon-separation we're used to inside classes.

Really no different than class member declarations.

**Comment by jnm2** [comment]
Ah, but why *exactly* zero or one? That doesn't make sense to me. it's inconsistent with the rest of C#.

**Comment by HaloFour** [comment]
`namespace-declaration`, `class-declaration`, `struct declaration`, `interface-declaration` and `enum-declaration` all explicitly specify that the trailing semicolon is optional per the C# spec.  They are the only parts of the language to do so.

IIRC it's completely unrelated to `using` directives which are required to be the first statements within a given namespace.  It's also not related to having multiple declarations within the same file as the C# compiler handles that just fine.  It's also unrelated to `empty-statement` which can only appear where an `embedded-statement` is permitted.

If I had to guess as to why the semicolon is optional it would be that the C# team initially didn't want them to be there but felt that allowing them would make C++ programmers feel more comfortable.  They're unnecessary for parsing the language in this context.

**Comment by RobBlob** [comment]
HaloFour seems to be correct here. It's a shame really, as C# wasn't really backward compatible with any language, and it fails to follow the principle of least surprise. Elsewhere in the language, typically a single "statement" is terminated by a semicolon, while a block of statements isn't. Think of method definitions:

void A(int a, int b) => a + b;
void A(int a, int b) { return a + b; }

Illustrates the point. Having namespaces and types behave differently increases the cognitive load while learning the language, at no real benefit to the developer.

**Comment by jnm2** [comment]
> Having namespaces and types behave differently increases the cognitive load while learning the language, at no real benefit to the developer.

Why does it increase the cognitive load? I've been using C# for 5+ years and have never had a reason to think about semicolons outside classes.

**Comment by miloush** [comment]
Thanks HaloFour, I can now see it in the spec too, I was looking one level higher.

**Comment by eyalsk** [comment]
Question is why it's an error to put semicolons after a function? it isn't in C++ and iirc in Java too.

**Comment by CyrusNajmabadi** [comment]
> Question is why it's an error to put semicolons after a function?

It shouldn't be an error to put semicolons after a function.  this parses fine locally:

```c#
class C
{
    void M()
    {
        void function() { } ;
    }
}

**Comment by jnm2** [comment]
@CyrusNajmabadi He's not talking about local functions.

**Comment by CyrusNajmabadi** [comment]
What is he talking about?

**Comment by jnm2** [comment]
Why is this an error
```c#
class C
{
    void M()
    {
    };
}
```

since this is not

```c#
class C
{
    void M()
    {
    }
};
```

**Comment by CyrusNajmabadi** [comment]
Ah, i see.  You mean 'methods'.

Reason: because no one has asked for us to support that.  Feel free to file suggestion.  I'm not sure if anyone would champion it.  But i don't see why it wouldn't be supported.

**Comment by jnm2** [comment]
The world being what it is, a lot of people mean 'methods' by it around here. 😄

**Comment by eyalsk** [comment]
@CyrusNajmabadi I don't like semicolons and prefer to have none so it would probably be silly of me to propose it but just wondered why the original team decided to make this an error, not a big deal. 😄 

@jnm2 Thanks for clarifying my question. 😉
