### ISSUE TITLE
Discussion: mandatory partial methods

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#753]
This was discussed under source generators, but it is still useful with current code generation mechanisms,

We can relax `partial` method restrictions and make that a mandatory partial method.
```cs
partial class C
{
  public partial void M();
}

partial class C 
{
  public void M() { } // produce error if absent
}
```
**Open question:** How could we define a private mandatory partial method? Currently `private partial` is not permitted but since the default modifier is `private` that could lead to confusion.

(edited to use `partial` instead of `extern` to reflect the discussion below)

**Comment by HaloFour** [comment]
@alrz 

Using the `extern` modifier on a method is already legal.  It's used to mark methods without implementations.  The compiler allows it but produces a warning if there is no attributes decorating the method such as `DllImportAttribute`.

**Comment by alrz** [comment]
Calling such methods would fail at runtime. So you should either provide an implementation (as proposed here) or add the attribute. Not sure if it already has any legitimate use cases outside DllImport.

Regarding backward compat I think this is similar to https://github.com/dotnet/roslyn/issues/8456,  so I perhaps these could be resolved similarly. (note: that issue doesn't even produce a warning).

**Comment by alrz** [comment]
Furthermore, with an implementation, the warning will go away. you could opt-in to make that an error.

**Comment by HaloFour** [comment]
@alrz 

> Not sure if it already has any legitimate use cases outside DllImport.

Remoting.  I've used this feature myself to declare client versions of server objects where the implementations are furnished at runtime, either by remoting or through my own code.  For fun I've even abused `extern` methods with `ContextBoundObject` to produce a form of P/Invoke that calls stored procedures.  The application of *any* attribute eliminates the warning, including your own.

IIRC, mscorlib also declares various methods as `extern` and then has their implementation provided by the CLR.

**Comment by Happypig375** [comment]
Also `MethodImplAttribute` which allows calls to the CLR.

**Comment by alrz** [comment]
So I think we're left with a couple of options,

1. Use `/warnaserror:626`, though the error message should be adjusted to mention partial declarations. 
1. Use `partial` but require an implementation when it does not satisfy current restrictions on optional partial methods. Downside to this approuch is that partial methods are already private, but since currently we require the access modifier to be absent, `private partial` could mean that it's mandatory.
1. Use a different keyword outright.

**Comment by HaloFour** [comment]
🍝  I might propose the following alternatives:

1. `private` + `partial`
    There's nothing implied by the combination of those keywords that the method requires an implementation.
1. `abstract` + `partial`
    Could cause confusion as `abstract` implies `virtual` but `partial` implies `private` and the two are incompatible.
1. `private` + `abstract`
    Similar to above.
1. No syntax changes, expand allowed use of `partial` methods
     Currently `partial` methods cannot return a value nor have `ref`/`out` parameters.  The C# compiler could relax that restriction while imposing the restriction that a method that does any of those things *must* have an implementation.  However, methods that don't return values or have `ref`/`out` parameters couldn't be made mandatory.

**Comment by alrz** [comment]
You could abuse this to have the same effect of `replace` for properties. (using `partial`for representation)
```cs
partial class Person
{
  public partial string Name { get; set; }
}

//  generated
partial class Person
{
  public string Name { ... }
}
```
But it moves the modifier to the "source" declaration rather than the generated declaration.
```cs
partial class Person
{
  public string Name { get; set; }
}

// generated
partial class Person
{
  replace public string Name { ... }
}
```
While this allows you to do things that are not already possible, I think this is just a complementary feature to `replace`, not a replacement thereof. So I think this should NOT be permitted for properties but it is absolutely useful for methods (or constructors for that matter).

I've intented this to be a standalone feature that can be used with existing code generators, but in the presence of a long discussion on whether or not `replace` could be added independantly (https://github.com/dotnet/csharplang/issues/107), I think this also belongs to that bucket.
