### ISSUE TITLE
Duplicate "case" when doing if->switch conversion

### ISSUE THREAD

**Issue by joeloff** [dotnet/csharplang#754]
When you have an OR expression and one of the subexpression repeat in an else-if, you get a duplicate case generated when converting from an if to a switch in Visual Studio using the quick refactoring option, e.g.

if ((x==2) || (x==3)) 
else if (x==3)

The generated switch you get will be something like

switch (x)
{
  case 2:
  case 3:
    break;
  case 3:
    break;
}

the "else" is effectively dead code

@Pilchie

**Comment by jnm2** [comment]
It transforms a snippet with a dead branch to another snippet with a dead branch. I think that's cool that it preserved the model, if anything.

**Comment by jnm2** [comment]
What did you want it to do, not transform the code? Drop a branch? Typically people perform transformation like this in order to edit the result to make it valid.

**Comment by joeloff** [comment]
Yes, I suspect get the bulk of the code converted and then editing afterwards. But perhaps suggesting to first remove the dead code would be an option. I saw something similar when I tried out a dangling else.

For example, if I have this

 `
 if (x==2)
                if (x==3)
                { }
                else if (x==4)
                { }
`

It actually doesn't offer me the "if to switch" option for the outer if statement, but instead suggests adding braces first which I thought was really great.

Another option for the original issue might be to offer two options, "convert if" and "remove dead code".

**Comment by CyrusNajmabadi** [comment]
Yeah, this seems like a good feature to me.

**Comment by alrz** [comment]
The "feature" that could find dead code here could potentially find a lot of other cases as well, because this requires a full data flow analysis, even more complex than what the compiler already does.
```cs
if (obj is IEnumerable<char>) return;
if (obj is string) { /* dead code */ }
```
If you convert the above to a switch, you get a subsumption error.

**Comment by HaloFour** [comment]
As this issue is related to refactoring tools or analyzers in Visual Studio doesn't it belong in the [Roslyn repository](https://github.com/dotnet/roslyn/)?

**Comment by Pilchie** [comment]
Moved to https://github.com/dotnet/roslyn/issues/20981.
