### ISSUE TITLE
Radzen inline editing not working

### ISSUE THREAD

**Issue by gurjeet2019** [dotnet/csharplang#7554]
I am facing this exception while adding/updating records in radzen inline grid.
Error: System.Collections.Generic.KeyNotFoundException: The given key 'my object name' was not present in the dictionary.

I am using 
access modifier **public** and **class** type as class
**public** **record** modal name

**Comment by CyrusNajmabadi** [comment]
No clue what radzen is. You'd need to take this up with them.

**Comment by iam3yal** [comment]
Radzen is a Blazor component library and it has absolutely nothing to do with this repo so post your issue [here](https://github.com/radzenhq/radzen-blazor/issues).

**Comment by CyrusNajmabadi** [comment]
Closing out.
