### ISSUE TITLE
Proposal: allow array to shrink

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#756]
C# should provide a method to shrink array without reallocation. After shrinking, some memory should be freed at once.
For example:
```C#
int[] a= new int[100];
......
a.shrink(10); // the new length of "a" is 10, no allocation. The memory after 10 elements should be freed at once, need not wait for GC. The freed memory could be used by next allocation.
string s = new string('c', 50); // the memory of string "s" could be allocated from the freed memory above.
......
```

**Comment by sharwell** [comment]
There is a great deal of code (in the framework and applications) which currently relies on this not being able to occur. However, the ongoing work on `Span<T>` should allow a library to implement an array-like type which does provide this functionality, at least for cases where `T` is blittable.

**Comment by mattwar** [comment]
This seems like more of a runtime feature request, unrelated to the C# language.
