### ISSUE TITLE
Proposal: Methods like string.Format() should support ValueTuple as parameter to avoid boxing

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#767]
If we could use ValueTuple as `string.Format()`'s parameter, many boxing could be avoided.
For example:
```C#
int n=10;
string s="aaa";
bool c=true;
var t=string.Format("{0},{1},{2}", (n, s, c)); //no boxing! 
/* string.Format() has this overload: string Format(string format, ValueTuple); */

Console.WriteLine("{0},{1},{2}", (c, s, n)); //Other methods like string.Format() have this kind of overload too
```

**Comment by HaloFour** [comment]
That would be a proposal for [CoreFX](https://github.com/dotnet/corefx) since it doesn't affect the C# language at all.

**Comment by ygc369** [comment]
@HaloFour 
This kind of overload seems to need compiler support. The current C# compiler does not support ValueTuple as parameter. So how could CoreFx team add this overload?

**Comment by mikedn** [comment]
> This kind of overload seems to need compiler support. 

Do you have any idea what all this means and what needs to happen for it to work?

**Comment by jnm2** [comment]
There is literally no benefit to using a tuple vs using the same number of normal arguments because the string.Format method would need to have the same generic arity either way to avoid boxing.

**Comment by HaloFour** [comment]
@ygc369 

> This kind of overload seems to need compiler support.

No it doesn't.

> The current C# compiler does not support ValueTuple as parameter.

Yes it does.  Your mistake is thinking that `ValueTuple` is one type.  It's a slew of different types, each based on the number of elements in the tuple.  For 2 elements you need `ValueTuple<T1, T2>`.  For 7 elements you need `ValueTuple<T1, T2, T3, T4, T5, T6, T7>`.  Those are different types in the CLR and in C#.  What you need is an overload per arity of the tuple that the method will accept:

```cs
public class String {
    public static string Format<T1, T2>(string format, ValueTuple<T1, T2> args) { ... }
    public static string Format<T1, T2, T3>(string format, ValueTuple<T1, T2, T3> args) { ... }
    public static string Format<T1, T2, T3, T4>(string format, ValueTuple<T1, T2, T3, T4> args) { ... }
}
```

**Comment by jnm2** [comment]
@ygc369 None of the other ValueTuple types inherit from ValueTuple. They are each a struct with a specific generic arity. ValueTuple is not meant to be abstracted like that.

**Comment by yaakov-h** [comment]
And if you create `string.Format` overloads for `ValueTuple<>` and `ValueTuple<,>` etc, you may as well cut `ValueTuple` out of the equation and just do `string.Format(string, object)`, `string.Format(string, object, object)` etc.

**Comment by mikedn** [comment]
> What you need is an overload per arity of the tuple that the method will accept:

And then using ValueTuple doesn't serve much purpose since you can have:
```C#
public class String {
    public static string Format<T1, T2>(string format, T1 t1, T2 t2) { ... }
    public static string Format<T1, T2, T3>(string format, T1 t1, T2 t2, T3 t3) { ... }
    public static string Format<T1, T2, T3, T4>(string format, T1 t1, T2 t2, T3 t3, T4 t4) { ... }
}
```

**Comment by ygc369** [comment]
@yaakov-h 
@mikedn
Do you mean that this kind of overload can't avoid boxing?

**Comment by yaakov-h** [comment]
@ygc369 No, you just seem to fundamentally misunderstand how `ValueTuple` works. It's not a single class/struct, but a series of structs.

**Comment by ygc369** [comment]
@yaakov-h 
Thank you. I understand it now. I'll post this issue to CoreFx repo.

**Comment by mikedn** [comment]
> Do you mean that this kind of overload can't avoid boxing?

It can. The question that you should ask is "at what cost?"

**Comment by ygc369** [comment]
@mikedn
at what cost? you know?

**Comment by Logerfo** [comment]
@jnm2 
>ValueTuple is not meant to be abstracted like that.

Why not? If `ValueTuple` inherited `IEnumerable`, for example, you could either read and return generic arity tuples. Boxing would be necessary, but I think that's better than no support for it at all.

**Comment by jnm2** [comment]
@Logerfo I was referring to the specific arity `ValueTuple`.

**Comment by jnm2** [comment]
All `Tuple` and `ValueTuple` arities implement an internal `ITuple` abstraction which I do think they should expose.

**Comment by yaakov-h** [comment]
That still wouldn't help this "avoid boxing" proposal.

**Comment by Logerfo** [comment]
```c#
(decimal totalValue, decimal totalQuantity) totals = collection.Sum(item => (item.Value, item.Quantity));
```
My point is that AFAIK I can't achieve the above without writing an overload for each arity, which is pretty annoying.

**Comment by jnm2** [comment]
Exactly.

**Comment by HaloFour** [comment]
I don't believe `ITuple` was added at this point or that the `ValueTuple<...>` types share a common interface for that purpose.  Having to negotiate such an interface would certainly incur boxing and allocations, though.

Ultimately I'd agree that it's probably better to explore generic overloads of `string.Format` that accept a known number of arguments, e.g. `string.Format<T1, T2>(string format, T1 arg1, T2 arg2)`.  I don't know if that would cause issues with the existing non-generic overloads.  All existing code would immediately start using the generic overloads due to generic inference and that could introduce subtle changes, although it really shouldn't.

That said, given that string formatting is a relatively inefficient process to begin with involving a number of internal allocations would a change like this actually have any real impact on performance?  IIRC internally the values are still going to end up being boxed so that they can be passed to the current culture format provider.

**Comment by jnm2** [comment]
Actually I think it's IValueTuple. It's there, I was working in that file.

**Comment by mikedn** [comment]
There's ITuple and IValueTupleInternal. Neither are relevant, the first offers access to tuple items via and indexer that returns `object`. The second is obviously internal.

In general, using ValueTuple to solve this "problem" in a meaningful way would require something similar to C++'s templates. Generics can't be used for this.

**Comment by jnm2** [comment]
Like I said, it's internal but could be exposed. Separate topic, though.
