### ISSUE TITLE
Proposal: Smart casts

### ISSUE THREAD

**Issue by srollinet** [dotnet/csharplang#768]
[Kotlin](https://kotlinlang.org/docs/reference/typecasts.html#smart-casts) has an even shorter version of `if (input is MyClass xxx){...}` 

that looks like:

```
if (obj is MyClass)
{
    //obj is automatically cast to MyClass
    obj.MethodThatExistsOnMyClass();
}
```

### Proposal
Add this small syntactic sugar in C#

**Comment by HaloFour** [comment]
This would change the semantics of existing code in breaking ways.

**Comment by HaloFour** [comment]
For reference:  https://github.com/dotnet/roslyn/issues/4670

**Comment by srollinet** [comment]
Thanks for the reference, I dit not find it.
I'll close the issue as it was already proposed but not accepted
