### ISSUE TITLE
Open issue: evaluation of implicit indexers in object initializers

### ISSUE THREAD

**Issue by jcouv** [dotnet/csharplang#7684]
As part of implementing support for implicit indexers in object initializers (`new C() { [rangeExpr] = { … } }`) some details of order of evaluation need to be spec'ed.

The [spec](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/expressions.md#128163-object-initializers) for object initializers says that:
>  When an initializer target refers to an indexer, the arguments to the indexer shall always be evaluated exactly once. Thus, even if the arguments end up never getting used (e.g., because of an empty nested initializer), they are evaluated for their side effects.

When we have an implicit Index or Range indexer, does "argument" refer to the argument given to the virtual indexer or the argument(s) given to the actual indexer (or Slice method)?

Taking an example: `new C() { [^1] = { [2] = 42, [3] = 43 } }`
We have two main options that stay in line with current spec:
1.	Cache the argument to the virtual indexer, namely `^1`, which means that `c.Length` will be called once for `c[cachedIndexArgument][2] = 42` and again for `c[cachedIndexArgument][3] = 43`.
2.	Cache the argument given to the `this[int i]` indexer, which means that `c.Length` is called once and then we evaluate `c[cachedIntegerArgument][2] = 42` and `c[cachedIntegerArgument][3] = 43`.
In the case of a virtual Range indexer, we would cache the arguments to the `Slice(int start, int length)` method.

Since this scenario is not bound by compatibility with the native compiler we could even 

 3.	adopt more aggressive caching: `var temp = c[^1]; temp[2] = 42; temp[3] = 43;` (caching not only the argument but also the receiver).

**Comment by jcouv** [comment]
Discussed on 11/15. We're going ahead with a variant of option 2 (try to no call Length when nested initializer)

**Comment by 333fred** [comment]
Discussed in LDM on https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-11-15.md#evaluation-of-implicit-indexers-in-object-initializers.
