### ISSUE TITLE
Proposal: Extend generic type new() constraint with parameter types

### ISSUE THREAD

**Issue by devedse** [dotnet/csharplang#769]
_From @devedse on October 12, 2016 20:20_

## Background

Currently C# allows its users to apply the "new()" constraint on methods accepting a generic type to let the compiler know it has a parameter-less constructor.

The following example shows 2 'random generators' that implement the IRandom interface that are being created and then used to return data:

```
class Program
{
    static void Main(string[] args)
    {
        var randomData1 = CreateRandomData<FastRandom>(10);
        var randomData2 = CreateRandomData<CryptoRandom>(10);
    }

    public static IEnumerable<int> CreateRandomData<R>(int length) where R : IRandom, new()
    {
        var randomGenerator = new R();
        for (int i = 0; i < length; i++)
        {
            yield return randomGenerator.Next();
        }
    }
}

public interface IRandom
{
    int Next();
}

public class FastRandom : IRandom
{
    public FastRandom()
    {

    }

    public int Next()
    {
        return 0;
    }
}

public class CryptoRandom : IRandom
{
    public CryptoRandom()
    {

    }

    public int Next()
    {
        return 1;
    }
}
```
## Problem

Currently it's not possible to provide a parameter (e.g. a seed) to the constructor of the 'to-be created' random generators. The current solutions would be:
1. Use reflection to call the constructor and passing the argument to it. (Disadvantage: Not compile time safe)
2. Use a factory and do a switch case on the different types of implementations of the IRandom interface. Then return a new instance of the found match. (Disadvantage: Need to extend Factory every time a new class implements IRandom)
3. Implement an additional method on the interface (and thus implementing classes) Initialize(int seed); which will initialize the class and set it up. (Disadvantage: Having to do 2 method calls for something that's normally done in the constructor.)
## Solution: parameterized new()

My proposed solution would be to also accept parameter types in the new() constraint. E.g. the **new(int)** in the following line of code:

```
public static IEnumerable<int> CreateRandomData<R>(int length) where R : IRandom, new(int)
```

This would make the complete solution look something similar to this:

```
class Program
{
    static void Main(string[] args)
    {
        var randomData1 = CreateRandomData<FastRandom>(10);
        var randomData2 = CreateRandomData<CryptoRandom>(10);
    }

    public static IEnumerable<int> CreateRandomData<R>(int length) where R : IRandom, new(int)
    {
        var randomGenerator = new R(50);
        for (int i = 0; i < length; i++)
        {
            yield return randomGenerator.Next();
        }
    }
}

public interface IRandom
{
    int Next();
}

public class FastRandom : IRandom
{
    private int seed;
    public FastRandom(int seed)
    {
        this.seed = seed;
    }

    public int Next()
    {
        return 0 + seed;
    }
}

public class CryptoRandom : IRandom
{
    private int seed;
    public CryptoRandom(int seed)
    {
        this.seed = seed;
    }

    public int Next()
    {
        return 1 + seed;
    }
}
```

_Copied from original issue: dotnet/roslyn#14461_

**Comment by devedse** [comment]
_From @dsaf on October 12, 2016 21:24_

This seems to be a duplicate of #2206 which is a shame because your version is also well-written. On the upside it's already in `1-Planning` state :).

**Comment by devedse** [comment]
Ah :), well, my goal to get this implemented would still be resolved then.
Any idea how long it usually takes for an item to go from 1-Planning to Implemented / Released?

**Comment by devedse** [comment]
_From @dsaf on October 13, 2016 16:47_

No idea. Let's say I wouldn't expect it next year.

**Comment by devedse** [comment]
_From @timopomer on November 28, 2016 0:55_

@devedse i know this issue is old, but just in case you wanted to make this you can use (R)Activator.CreateInstance(typeof(R), length)

**Comment by devedse** [comment]
Yeah, that's indeed one of the workaround you can use for now. However I would like to do this type safe at compile time :).

**Comment by orthoxerox** [comment]
Some other potential solutions for this:

1. Abstract factory:

```c#
public interface IRandomFactory
{
    IRandom Create(int length);
}

public struct FastRandomFactory : IRandomFactory //being a struct is important
{
    public IRandom Create(int length) => new FastRandom(length);
}

public static IEnumerable<int> CreateRandomData<F>(int length) 
    where F : IRandomFactory, struct
{
    var randomGenerator = default(F).Create(length);
    for (int i = 0; i < length; i++)
    {
        yield return randomGenerator.Next();
    }
}
```

2. Waiting for shapes (they will solve a generalized problem of requiring specific methods)

3. Extending interface definitions to support constructors:

```c#
public interface IRandom
{
    public IRandom(int length);
    ...
}
```

**Comment by jnm2** [comment]
The thinh I'm worried about is that `new(int, string)` has no semantic meaning. Types that aren't meant to match will match. Also suppose you need to refactor to start taking three parameters? All your method constraints are coupled to the very specific signature and all will break, whereas a factory interface or delegate type are named and separate that coupling away from each usage quite nicely.

**Comment by Pzixel** [comment]
Allowing interfaces to have static methods, or add new interfaces on types themselves could solve this. Create an instance of class just to call a method which returns new instance of this class. That's sounds weird. This is why we cannot have interface `IParseable<T>` where we could have a method `T Parse(string input);`, because we don't want to create an instance just to create an instance and simultaneosly we can't invoke `T.Parse` because we don't constraint the type itself, but only its instance methods...

**Comment by jnm2** [comment]
@Pzixel Already gave my thoughts on that in https://github.com/dotnet/csharplang/issues/837.

**Comment by Pzixel** [comment]
@jnm2 shapes probably might solve this? I mean:

```csharp
public shape CreatableWithSeed
{
    new(int seed);
}

public static IEnumerable<int> CreateRandomData<R>(int length) where R : IRandom, CreatableWithSeed
{
	var randomGenerator = new R(50);
	for (int i = 0; i < length; i++)
	{
		yield return randomGenerator.Next();
	}
}
```

**Comment by gafter** [comment]
This is part of a proposal being tracked at #110 which is under active development at MSR (Microsoft Research).

**Comment by ActivistInvestor** [comment]
> @jnm2: The thing I'm worried about is that new(int, string) has no semantic meaning

I don't recall ever having used new() without an additional type constraint. 

How does using new() without a type constraint have any more semantic meaning than using the theoretical or proposed parameterized new(...) without also using a type constraint?

**Comment by jnm2** [comment]
> I don't recall ever having used new() without an additional type constraint.

It's common as part of a generic factory method (in the same spirit as `new Lazy<Foo>().Value`).

> How does using new() without a type constraint have any more semantic meaning than using the theoretical or proposed parameterized new(...) without also using a type constraint?

This is an excellent point. I would answer that it's obvious with `new()` that you get the default construction of whatever `T` is, whether constrained or not. With `new(string, int)`, it's not obvious what the first and second arguments mean, whether `T` is constrained or not. What choices are you making with that string and int? What are you causing to happen?

You don't really have that question with `new T()`. You know you're getting the default construction of `T`.

**Comment by ActivistInvestor** [comment]
> This is an excellent point. I would answer that it's obvious with new() that you get the default construction of whatever T is, whether constrained or not. With new(string, int), it's not obvious what the first and second arguments mean, whether T is constrained or not. What choices are you making with that string and int? What are you causing to happen? You don't really have that question with new T(). You know you're getting the default construction of T.

I don't see how that is any less-obvious than deriving a type from any base type with a constructor that takes arguments, and which must be supermessaged from the constructor of the derived type.

Sorry, I still don't see your point.

**Comment by jnm2** [comment]
> I don't see how that differs from what one must do today (use reflection to construct instances via calls to a parameterized constructor).
> 
> This is widely done now

Is it widely done now? Other than serializers whose entire job is reflection-based, I don't see this much at all, and I have been in a variety of codebases. Activator.CreateInstance is very rarely used with constructor parameters- certainly no more than `MethodInfo.Invoke` and for the same reasons.

What people usually do is a factory interface where you can call `IPersonFactory(string name, int age)` and that is much more common.

**Comment by ActivistInvestor** [comment]
> Is it widely done now? Other than serializers whose entire job is reflection-based, I don't see this much at all, and I have been in a variety of codebases. Activator.CreateInstance is very rarely used with constructor parameters- certainly no more than MethodInfo.Invoke and for the same reasons.

It is done via ConstructorInfo, not Activator. The patterns it is used in typically involve a class that has the responsibility for managing multiple instances of a consumer-provided class (the generic argument), and the class that manages the instances must create instances of the consumer-provided class, and pass arguments to their constructors. In many cases, the consumer-provided class is derived from another class that must have the constructor arguments passed into their constructors, etc.

The practice has been discussed in this issue, nonetheless.

> What people usually do is a factory delegate or interface where you can call IPersonFactory.Get(string name, int age) and that is much more common. Even a Func<string, int, Person> getPersonByNameAndAge parameter has all the semantic meaning you need. No Activator.CreateInstance nonsense.

In many of the cases where I've dealt with this pattern, there is no need for the consumer to provide a factory function, make any API calls, or do anything at all in code. 

Everything is done via an Attribute which is read when the containing assembly is loaded. The consumer only needs to apply the attribute to the class for which instances are created and managed, and ensure that the class has the required constructor. When the assembly containing the attributed class is loaded, the system that manages instances of the class will register the class and create instances as needed, without the consumer that provides the class having to do anything at all.

**Comment by ActivistInvestor** [comment]
> Is it widely done now? Other than serializers whose entire job is reflection-based, I don't see this much at all, and I have been in a variety of codebases. Activator.CreateInstance is very rarely used with constructor parameters- certainly no more than MethodInfo.Invoke and for the same reasons.

Actually, most robust factory patterns do not have a dependence on generics in the first place, because if they did, that would restrict them to only being usable with statically-defined types, rather than types that are defined or determined dynamically at runtime. They may support support generics at some level, but when you get down to the bare metal, the generic arguments usually get converted to a runtime type via `typeof()`, and that's what's ultimately used to construct instances, which can only be done via reflection.

For example, if there was only `Activator.CreateInstance<T>` (which simply delegates to a non-generic overload)?  What good would that be if you don't know the type at compile-time?

**Comment by devedse** [comment]
The reason I'm not sure if I would like Activator.CreateInstance<T> is because it would make this functionality rely on the System.Reflection library. I suppose it's better then nothing, but for a feature like this I'm not sure if that is the way to go. Furthermore, would there be any difference performance wise? (When extending Activator.CreateInstance I would assume reflection would be used in combination with casting, wheras the new(... , ...) could be as fast as simply creating an instance of a class.

**Comment by Joe4evr** [comment]
> The reason I'm not sure if I would like Activator.CreateInstance is because it would make this functionality rely on the System.Reflection library.

Well, using the `T : new()` constraint and doing `new T()` is *already* using `Activator.CreateInstance()` since forever, so you're out of luck on that front. 🙃 

> When extending Activator.CreateInstance I would assume reflection would be used in combination with casting, wheras the new(... , ...) could be as fast as simply creating an instance of a class.

There is no way to invoke the constructor of a type known only at runtime (which is exactly what you're doing) without using reflection.

**Comment by devedse** [comment]
@Joe4evr, I don't think your second point is fully correct. Since you can use Expression trees to in fact reach the speed of Compile time invoked constructors.

**Comment by devedse** [comment]
HI all,

Can we maybe revisit this and get some new insights if we would want or not want this to be implemented, as there's quite some people that have upvoted this.

**Comment by jnm2** [comment]
I really like the way https://github.com/dotnet/csharplang/issues/2528 would allow this.

**Comment by Shadowblitz16** [comment]
I actually just tried doing `where T : new(...)` just to see if it was a thing.
then I looked up this when I realized C# didn't support it.
it kinda makes sense syntax wise to allow the user to control generic constructors by passing parameters to the new constraint.

its basically saying constrain the constructors to this signature.

**Comment by Pzixel** [comment]
with shapes it should be possible to demand static method Create which should actually create a value.

**Comment by adamstyl** [comment]
> HI all,
> 
> Can we maybe revisit this and get some new insights if we would want or not want this to be implemented, as there's quite some people that have upvoted this.

@devedse considering how popular is this [10 year old question at stackoverflow](https://stackoverflow.com/q/840261/1303323), I would say it's not just "some people" ;)

I personally consider it useful as I found myself more than once in need of a parameterized new() solution. My 2 cents.

**Comment by devedse** [comment]
Hi all, It's been a while, but I just saw a notification drop in my mailbox so I thought I'd chip in again too. I still think this idea would be great to add.

As @Shadowblitz16 also mentioned, having this, simply makes sense. Having `new()` accept a parameter specification feels intuitive to me, especially since there's already ( ) in there.

I saw your approach regarding shapes as well but I think this could still be a strong addition since shapes seem to resolve a more difficult challenge we're running into.

In regards to @jnm2 's comment about it not having semantic meaning, can't we build it the same way that named tuple's solve this?:

```
private static (int Count, double Sum, double SumOfSquares) ComputeSumAndSumOfSquares(IEnumerable<double> sequence)
{
    var computation = (count: 0, sum: 0.0, sumOfSquares: 0.0);

    foreach (var item in sequence)
    {
        computation.count++;
        computation.sum += item;
        computation.sumOfSquares += item * item;
    }

    return computation;
}
```

That way you could have either one of these options:

Option 1:
```
    public static IEnumerable<int> CreateRandomData<R>(int length) where R : IRandom, new(int)
    {
      ...
    }
```

Option 2:
```
    public static IEnumerable<int> CreateRandomData<R>(int length) where R : IRandom, new(int seed)
    {
      ...
    }
```

Another way I wouldn't mind this issue to be solved is by having the option to define a constructor definition inside an interface. I mean, why do we have the ability to define methods but not constructors? To me it would make sense to have both. This might also have some more benefits when doing serialization / deserialization.

**Comment by Pzixel** [comment]
It could be naturally solved if typeclasses come into the game so you can just write `where T : New<int>`, and there is no need for special syntax in the language. Waiting for #164

**Comment by devedse** [comment]
@Pzixel then you'd still have the problem that it doesn't have any semantic meaning though.

**Comment by Pzixel** [comment]
I don't get your idea. Could you elaborate? It looks like it's a complete replacement:

```cs
shape New<T> {
  static Create(T arg) -> this;
}

...

void Foo<TVal, TNew>(Tval arg) where TNew : New<TVal>, IBar {
  var newVal = TNew.Create(arg);
  newVal.Bar();
}
```

**Comment by devedse** [comment]
Ah that's what you mean, I haven't really checked out shapes enough. So with that solution you wouldn't be using the constructor, but rather a static method that creates an instance of the class with some parameters?

Could you maybe show an example how this would work for the example above with the Random instances?

**Comment by Pzixel** [comment]
No problem:

```cs
public extension NewRandom of Random : New<int>
{
    public static this Create(int arg) => new Random(arg);
}
```

**Comment by devedse** [comment]
@Pzixel, but in your example, why do you still include the : New<int>. You already specify in the Create method that there's an int argument right?

**Comment by Pzixel** [comment]
Because type inference in C# works this way.

**Comment by adamstyl** [comment]
@devedse as I'm the one who "stirred the pot" I think that it might be better off if we keep the constructor in interface separate from the parametarized `new()` feature request. Otherwise it won't have a chance to make it to the language I'm afraid.

Now the question (IMHO always) is how can we draw some attention to this one so that it will have some chance to reach a future version of C#. C# 20 let's say -hope I wont be in pension by then.😅 As I see it, the popularity of the question in SO (where I actually landed this page from) can be an indicator of the usability of the feature.
