### ISSUE TITLE
Allow usage of nameof on parameters of methods from outside

### ISSUE THREAD

**Issue by Mafii** [dotnet/csharplang#771]
Consider the following method:

``` C#
public void TestMethod(int someValue, double someOtherValue)
{
  // this works
  string name = nameof(someValue);
}
```

Now I would love to use nameof onto a parameter from outside the method.

I propose the following syntax.

``` C#
public void AntherTestMethod()
{
  // I want THIS to work
  // if my methods are in the same class
  string nameOfParam1InTestMethod = nameof(TestMethod.someValue);
  // if they are in other classes, add the class name infront of it
  string nameOfAParamInAnotherClass = nameof(TheClass.TestMethod.someOtherValue);
}
```

If this is not clear enough, another idea would be `ClassName.MethodName.params.paramName`

So the `params` keyword to access the params of a method.

---

Where is this useful?

This would be especially useful in Web/using ASP.NET when you have to specify the name of a parameter of a method as a string. With this change I would be able to adress them in a compile time and refoctoring safe way. If the param name changes, I'll notice.

**Comment by tannergooding** [comment]
I've found a few places where this would also be useful in doc comments.

**Comment by taori** [comment]
some discussion already happened here https://github.com/dotnet/csharplang/issues/373

**Comment by perholje** [comment]
This would be great for unit testing methods throwing ArgumentExceptions.

**Comment by taori** [comment]
@Mafii would you mind closing this issue, since some discussion already happened at #373 ? Also some effort has gone into discussing overloads there. There's no point in duplicating issues i think.

**Comment by Mafii** [comment]
@taori Totally agree, thanks for linking me the dupe.
