### ISSUE TITLE
New idea for pattern to assist with tuple usage

### ISSUE THREAD

**Issue by taori** [dotnet/csharplang#774]
I'm a big fan of using the new pattern syntax to do things like

```
if(Some.Field.Property is Shape s)
{
    // do things with s
}
```

Would it be possible to add another functionality like that in a fashion like this?

`AppleDevice.GetDeviceVersion().major where GetVersion return is (int major, int minor)`

I would love to be able to write my code like this:

```
if (AppleDevice.GetDeviceVersion() aka d  d.major>= 5 && d.minor >= 3)
      this.uiText.TextAlignment = UITextAlignment.Center;
```

instead of this

```
var version = AppleDevice.GetDeviceVersion();
if (version.major>= 5 && version.minor >= 3)
      this.uiText.TextAlignment = UITextAlignment.Center;
```

**Comment by svick** [comment]
What's the advantage of this syntax? If it's that the variable `d` doesn't leak outside the scope of the `if`, then that would be inconsistent with the `is` operator.

There's also already a similar proposal: Declaration expressions (https://github.com/dotnet/csharplang/issues/595). With that, your code would be:

```c#
if ((var version = AppleDevice.GetDeviceVersion()).major >= 5 && version.minor >= 3)
      this.uiText.TextAlignment = UITextAlignment.Center;
```

(Also, I got confused by the `AppleDevice.GetDeviceVersion().major where GetVersion return is (int major, int minor)` line. At first I thought this was proposing some new syntax and not just explaining what `GetDeviceVersion()` returns.)

**Comment by YotaXP** [comment]
Seems like a lot of work for something that could be done with a very simple extension method.
```
public static R Aka<T, R>(this T value, Func<T, R> function) => function(value);

...

if (AppleDevice.GetDeviceVersion().Aka(d => d.major >= 5 && d.minor >= 3))
      this.uiText.TextAlignment = UITextAlignment.Center;
```

**Comment by HaloFour** [comment]
```cs
if (AppleDevice.GetDeviceVersion() is var d && d.major >= 5 && d.minor >= 3) { ... }
```

**Comment by jnm2** [comment]
Yes, we already have `is var` for declaration expressions.

**Comment by taori** [comment]
That is awesome. I don't think i've seen it used like that in samples. For some reason i thought this only works in scenarios where the type is known while int.Parse(out var i) etc would be special cases. I am glad i was wrong. Thanks for pointing it out.
