### ISSUE TITLE
Support shorthand tuple syntax for switch statements.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/csharplang#777]
Currently you have to use the fully qualified tuple name (`System.ValueTuple<>`) when attempting to switch on a tuple:
```C#
var someTuple = (5, "some value");

switch (someTuple)
{
    case ValueTuple<int, string> temp:
        Console.WriteLine("true");
        break;

    case (int, string):     // CS1525: Invalid expression term 'int'; CS1525: Invalid expression term 'string'; CS0150: A constant value is expected
        break;

    case (int, string) t:   // CS1525: Invalid expression term 'int'; CS1525: Invalid expression term 'string'; CS0150: A constant value is expected; CS1003: Syntax error, ':' expected
        break;

    default:
        Console.WriteLine("false");
        break;
}
```

In the above code, only the first case is allowed (a name must be provided and just doing `case ValueTuple<int, string>:` gives an error).

I would expect that the third case (`case (int, string) t:`) would be supported.

**Comment by tannergooding** [comment]
FYI. @CyrusNajmabadi, @jcouv

**Comment by jcouv** [comment]
I'll let @gafter comment. In particular, I don't know his latest thinking on disambiguation of different cases, such as `case (int, string):` and `case (x, y):`.

Relates of https://github.com/dotnet/roslyn/issues/15899
Relates to https://stackoverflow.com/questions/40832381/if-object-is-string-color-c-sharp-7-0-tuple-usage-doesnt-work/40832782

**Comment by gafter** [comment]
Tuple types are not permitted in patterns, as they conflict syntactically with tuple patterns. However, you can write

`case (int _, string _):`

that is working in the current prototype of recursive patterns for C# 8 in Roslyn's branch `features/recursive-patterns`.
