### ISSUE TITLE
Provide better switch support for tuples.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/csharplang#778]
Currently, the support for switching on tuples is very verbose:

You must currently do something like the following:
```C#
var someTuple = (5, "some value");

switch (someTuple)
{
    case ValueTuple<int, string> temp when (temp.Item1 == 5) && (temp.Item2 == "some value"):
        Console.WriteLine("true");
        break;

    default:
        Console.WriteLine("false");
        break;
}
```

https://github.com/dotnet/csharplang/issues/777 tracks supporting `case (int, string) temp:`, but it would additionally be ideal if one did not need to explicitly code the when clauses.

This could be provided via syntax such as the following: `case (5, "some value"):`.

**Comment by tannergooding** [comment]
FYI. @jcouv, @CyrusNajmabadi

**Comment by HaloFour** [comment]
That would fall under recursive patterns which are a part of the pattern matching proposal already.

**Comment by CyrusNajmabadi** [comment]
Note: there are recursive patterns, but there are also non-recursive patterns that also are not supported.  For example, i can't say:

```c#
var someTuple = (5, "some value");

switch (someTuple)
{
    case (int, string) t when t == (6, "other value"):
        break;
    case (int, string) t when t == (5, "some value"):
        break;
}
```

In this case, this is just the tuple equivalent to what you can do today with non tuple types.

**Comment by HaloFour** [comment]
@CyrusNajmabadi 

> Note: there are recursive patterns, but there are also non-recursive patterns that also are not supported.

I figured that was due to outstanding questions around recursive patterns.  If the team decided on supporting that syntax now for matching tuples that they couldn't then also use that same syntax to support matching on the deconstruction of a type, either conditionally or unconditionally, without the potential of breaking existing code.

**Comment by gafter** [comment]
This is part of the recursive patterns feature planned for C# 8, and is already implemented in Roslyn's `features/recursive-patterns` branch.
