### ISSUE TITLE
[Proposal]: request support for the ISO 8601 standard 24:00:00 time format in C#

### ISSUE THREAD

**Issue by choby** [dotnet/csharplang#7816]
I am writing to request support for the[ ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard 24:00:00 time format in C#. Currently, this format is not supported, and I believe that adding support for it would be beneficial for developers who need to represent midnight in their applications.

I understand that the current standard for representing midnight is 00:00:00, but the ISO 8601 standard allows for 24:00:00 as an alternative representation. This format is used in some industries, such as aviation, and it would be helpful to have support for it in C#.

**Comment by hwoodiwiss** [comment]
I think this might be better suited to a discussion in the runtime repo [here](https://github.com/dotnet/runtime/discussions), as this would need runtime/BCL implementation, rather than implementing in the language.

**Comment by choby** [comment]
ok
