### ISSUE TITLE
Proposal: sealed enums (completeness checking in switch statements)

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/csharplang#782]
Since full-blown discriminated unions are a long way away (they'll come after records and records will come in C#8.0 or later), I propose to implement a much smaller feature that will allow us to avoid incorrect defaults or skipped clauses.

1. A new enum-targeted attribute should be introduced, `System.SealedEnumerationAttribute`. It is a compile-time error when a single type has both `System.SealedEnumerationAttribute` and `System.FlagsAttribute`.
2. Enumeration declarations should accept `sealed` modifier. This is equivalent to decorating the type with `System.SealedEnumerationAttribute`.
3. Switch statement binder should check the type of its expression. If it's a sealed enumeration, then the list of switch labels must not include pattern labels or default lables and must include every single enumerated value.
4. To prevent enumeration values added in another assembly after compilation from silently skipping the switch statement, a default case must be added by the binder to all such switch statements. The default case should throw.

**Comment by svick** [comment]
> If it's a sealed enumeration, then the list of switch labels must not include `default`, must not include pattern labels and must include every single enumerated value.

This sounds too restrictive to me. I think you want to prevent mistakes in the common case, where every enum value has a separate case. But I don't see why you should also prohibit more advanced cases, like `default` or patterns, especially considering that it's the `enum` author who chooses whether it's `sealed` or not, not the user.

---

How much protection will there be from creating a "wrong" value? I assume the compiler would not allow `MySealedEnum e = (MySealedEnum)42;`. But would the CLR prohibit `MySealedEnum e = (MySealedEnum)Enum.ToObject(typeof(MySealedEnum), 42);` or `MySealedEnum e = (MySealedEnum)(object)42;`?

**Comment by alrz** [comment]
>If it's a sealed enumeration, then the list of switch labels must not include default, must not include pattern labels and must include every single enumerated value.



(1) I think this only should affect completeness of a switch statement, e.g.
```cs
[Complete]
enum E { A, B }
int M(E e) {
    switch (e) {
      case E.A: return 0;
      case E.B: return 1;
    }
} // no error (CS0161)
```
(2) The `default` case never contribute to subsumption checking, for example, you can have a `default` case after `case var`. This is because `default` is evaluated regardless of where it appears. However a discard i.e. `case _` should be flagged as unreachable if the enum is marked as complete.

(3) I agree that this should emit the default case anyways but perhaps we should add this functionally to struct ADTs so that we don't have to worry about CLR enums accepting any possible value of the underlying type.

**Comment by Pzixel** [comment]
How it will work with serialization? For example:

```
static void Main()
{
	var colors = new List<E> { E.A };
	var result = Serialize(colors);
	Console.WriteLine(result);
}

public static string Serialize<T>(T obj)
{
	var serializer = new NetDataContractSerializer();
	var sb = new StringBuilder();
	using (var writer = XmlWriter.Create(sb))
	{
		serializer.WriteObject(writer, obj);
		writer.Flush();
		return sb.ToString();
	}
}

[Complete]
enum E { A = 1, B }
```

Now it fails at runtime because of internals of `NetDataContractSerializer`. But it's just because it checks if enum is actually is in valid range. However, your enum have to check it at compile time. And here you see what happens: we just can encounter a situation where abstractions leak and we can't even add this enum in the list.

**Comment by YotaXP** [comment]
I would prefer something more along the lines of D's [`final switch`](http://dlang.org/spec/statement.html#final-switch-statement) statement.  An alternative version of `switch` that fails to compile if any of the enumeration values are not used.

Makes more sense to me for this sort of restriction to be requested by the consumer, rather than specified on the type itself.

**Comment by Pzixel** [comment]
@YotaXP and what if this `final switch` encounter the situation when value doesn't have a corresponding branch?
```
using System;
using System.Runtime.InteropServices;
 
public class Test
{
	public static void Main()
	{
		bool x = LolBool.Value;
 
		switch (x)
		{
			case true:
			case false:
				break;
			default:
				Console.WriteLine("lol");
				break;
		}
	}
 
	public static class LolBool
	{
		public static readonly bool Value = new LolBoolUnion(0x80).BoolValue;
 
		[StructLayout(LayoutKind.Explicit)]
		private struct LolBoolUnion
		{
			[FieldOffset(0)]
			private readonly byte byteValue;
			[FieldOffset(0)]
			public readonly bool BoolValue;
 
			public LolBoolUnion(byte byteValue) : this()
			{
				this.byteValue = byteValue;
			}
		}
	}
}
```

**Comment by orthoxerox** [comment]
@Pzixel was your comment addressed to svick or to me? Because I don't see any switches in your example code. I do not propose to prevent instantiation of invalid enum values in this issue.

**Comment by jnm2** [comment]
@Pzixel Copying my code is absolutely fine, but converting it to use tabs... tsk tsk. 🤔

**Comment by Pzixel** [comment]
@orthoxerox I'm just going your way and show that even today we have some problems with invalid enum values and cannot just remove them from the language or add a new feature that works this different. And I was talking with @alrz .

**Comment by sirgru** [comment]
I also believe the control whether the whole enum should be used is the consumer's responsibility. In my view, such hypothetical `final switch` would not allow `default`, but would have a 'hidden' default clause that throws an exception if ever reached. This way it could combine reasonable compile-time safety with runtime 'safety' (doing what is expected by the user).

**Comment by alrz** [comment]
Ha, this is the reversed proposal for https://github.com/rust-lang/rfcs/pull/2008 😄

**Comment by abjennings** [comment]
I would still love to see algebraic data types and real enums in C#, but in the meantime, I created a compiler extension that helps me make sure I'm getting all the cases when I want to:

https://github.com/abjennings/EnumAnalyzer

It looks for places where I throw an "EnumNotExhaustedException", then checks the surrounding code block to make sure all the _defined_ enum values are mentioned at least once.  If not, it gives me a diagnostic error.

There are definitely corner cases it won't handle, but for me, it seems a good 90/10 solution (90% of the benefit for 10% of the cost).  Also, it's my first compiler extension, so any feedback is appreciated...
