### ISSUE TITLE
Proposal:  Exception preview operator

### ISSUE THREAD

**Issue by bondsbw** [dotnet/csharplang#787]
Inspired by #786, this alternative proposal seeks to simplify a common use case in logging exceptions and rethrowing them.

Unlike similar proposals, this one does not aim to create a "catch-all" mechanism or encourage control flow using exceptions.

An exception preview operator, `!!`, is introduced with behavior as described in the following example.

#### Simple example

Given some error helpers:
```c#
void MayThrowException() => ...
void LogError(Exception ex) => ...
```
A typical use case is to log any exception which is caught, and immediately rethrow it:
```c#
try
{
    MayThrowException();
}
catch (Exception ex)
{
    LogError(ex);
    throw;
}
```
Under this proposal, the `try`/`catch` block may be replaced with a single statement:
```c#
MayThrowException() !! LogError;
```

#### Always rethrows exception
The exception preview operator always rethrows the exception upon completion of right-hand method, as indicated in the example.  It never swallows the exception.

#### Infix operator
The exception preview operator is an infix operator.  Its left operand is a statement or expression which may throw an exception, and its right operand is a method group (shown above) or lambda.

This is an example of usage in expression form with a method group:
```c#
int i = int.Parse("ABC") !! LogError;

// Equivalent to:
int i;
try
{
    i = int.Parse("ABC");
}
catch (Exception ex)
{
    LogError(ex);
    throw;
}
```
And as a statement with a lambda:
```c#
MayThrowException() !! (Exception ex => logger.Error(ex.Message));

// Roughly the same as:
try
{
    MayThrowException();
}
catch (Exception ex)
{
    logger.Error(ex.Message);
    throw;
}
```

#### Method group or lambda parameter
The method group or lambda must have exactly one non-default parameter.  This parameter is the exception type, corresponding to the catch argument:
```c#
void LogBadException(BadException bex) => logger.Error(bex);

MayThrowException() !! LogBadException;

// Equivalent to:
try
{
    MayThrowException();
}
catch (BadException bex)
{
    LogBadException(bex);
    throw;
}
```
Any exception which does not match the parameter type does not get caught.

#### Chaining
```c#
MayThrowException() !! LogBadException !! LogException;

// Equivalent to:
try
{
    MayThrowException();
}
catch (BadException bex)
{
    LogBadException(bex);
    throw;
}
catch (Exception ex)
{
    LogError(ex);
    throw;
}
```

#### `When` clause
```c#
string s = Console.ReadLine();
MayThrowException() !! LogError when (string.IsNullOrEmpty(s));

// Equivalent to:
try
{
    MayThrowException();
}
catch (Exception ex) when (string.IsNullOrEmpty(s))
{
    LogError(ex);
    throw;
}
```

**Comment by bondsbw** [comment]
As usual, I encourage input and alternative syntax discussion.

**Comment by HaloFour** [comment]
I don't like trying to pack a very limited (and opinionated) form of exception handling like this directly into the language.  It eliminates the locality of the exception handling and promotes this form of removed catch-all.  "Log and rethrow" is commonly considered to be an anti-pattern and that's all this syntax seems to encourage.

**Comment by MgSam** [comment]
My personal feeling is that a library method is probably sufficient here, as this isn't something that you're typically doing a ton of in code. That way you can use a method with a much more descriptive name.

It also seems a little weird to me that control flow is guaranteed to be interrupted whenever the right hand is executed, but I'm not sure the syntax necessarily conveys that.

**Comment by bondsbw** [comment]
@HaloFour I agree, logging and rethrowing can be an antipattern.  I feel there are legitimate uses too.

Another use case is to wrap an exception.  It could be done by throwing a new exception from within the right operand.  

But throwing the exception from that method may not result in the stack trace you want.  We can fix this by letting the right operand return an exception that should be thrown:

```c#
WrappedException WrapException(Exception ex)
    => new WrappedException("Wrapping the original exception with another and adding some relevant data from this level", ex);

MayThrowException !! WrapException;

// Equivalent to:
try
{
    MayThrowException();
}
catch (Exception ex)
{
    throw WrapException(ex);
}
```

In this case the stack trace ends where the `!!` is used, instead of the helper method or lambda.

**Comment by HaloFour** [comment]
@bondsbw 

How would you wrap exceptions with anything useful if you have to effectively pipe through this separate method which would not have access to the arguments or locals of the method in which the exception is thrown?  The only way that makes sense is to declare the method as a local function instead, that way it can access that information, but you've lost the ability to share it amongst any other methods.  Seems like the worst of all worlds.

**Comment by bondsbw** [comment]
If you need more than object state, use a lambda.

**Comment by jnm2** [comment]
Seems like `try { } catch (SomeException ex) { throw new MyException(ex); } is just as expressive as anything. I'm in favor of an expression form (with braces) as well as a statement form, but that's about as far as I see value to a wider audience.

**Comment by HaloFour** [comment]
@bondsbw 

> If you need more than object state, use a lambda.

Same problem with local functions.  Now you have bizarre/hoisted locality and no ability to share.

```cs
Func<Exception, WrappedException> handler = (exception) => new WrappedException($"Failed because of value {arg}.", exception);

MayThrowException() !! handler;
```

vs.

```cs
try {
    MayThrowException();
}
catch (Exception exception) {
    throw new WrappedException($"Failed because of value {arg}." exception);
}
```

This is even more verbose and provides no benefits, but has plenty of limitations.  I don't see any point to it.

**Comment by jnm2** [comment]
Any shortening of `try { } catch (SomeException ex) { throw new MyException(ex); }` necessarily implies a specialization better suited as an internal library method than as a language feature. Same as any block of repetitive code.

**Comment by bondsbw** [comment]
@HaloFour The helper method can still exist.  I would declare the lambda at the site of the operand.

With type inference, we can make this much shorter and more reusable than either of your examples:

```c#
MayThrowException() !! ex => WrapException(ex, arg);
```

**Comment by HaloFour** [comment]
@bondsbw 

Lambda syntax requires a known delegate type in order to function at all, let alone offer any type inference.  You're proposing something that would behave very differently to how that syntax currently behaves in the language.  It still has the locality problem and it doesn't read remotely like exception handling.

**Comment by eyalsk** [comment]
@jnm2 

> Any shortening of try { } catch (SomeException ex) { throw new MyException(ex); } necessarily implies a specialization better suited as an internal library method than as a language feature. Same as any block of repetitive code.

I'm not sure about that, I mean sure, you can solve that easily by creating a specialized method but you increase the call stack at times by gaining nothing, sometimes abstractions gets in the way and the language can definitely make this better, however, based on my experience, I don't tend to do exception handling often and people use the word often without any context to convey that it's needed but never say how often to warrant this.

What I'm getting at is if this was common then the language could probably help but honestly how often people are handling exceptions and even more wrapping a single method? "seems like people do exception handling more than they should."

**Comment by jnm2** [comment]
> What I'm getting at is if this was common then the language could probably help but honestly how often people are handling exceptions and even more wrapping a single method? "seems like people do exception handling more than they should."

Exactly. If it's an overwhelmingly common need, then it makes sense for the language to address it. If it's not, it makes sense to work *within* the language and yes, increase the call stack or else inline your logic.

**Comment by GSPP** [comment]
This immediate logging is actually an anti-pattern. It leads to each step in the call chain redundantly logging the exception. It's often better to do nothing, let it bubble up and log it at the point where it is handled/suppressed.

**Comment by bondsbw** [comment]
Closing due to lack of interest.
