### ISSUE TITLE
Proposal: change 'is var x' to check require non-null x

### ISSUE THREAD

**Issue by sharwell** [dotnet/csharplang#792]
In most cases where `var` is allowed for inferring a type, the resulting inferred type is syntactically interchangeable. One exception is the following:

```csharp
public void Method(object input)
{
  if (input is object value)
  {
    // value has the static type 'object'
    // this block executes only if input is non-null
  }

  if (input is var value)
  {
    // value has the static type 'object'
    // this block executes even if input is null
  }
}
```

This behavior has several problems:

1. Aside from the obvious `is null`, `is var` is the only cases where an `is` operator can produce a true result when the left hand side is null. This is confusing.
2. The pattern-matching `is` operator has the potential to support null checks on exposed values in concurrent code (https://github.com/dotnet/csharplang/issues/788#issuecomment-320472658), but usage in this case would require the type name always be explicitly specified.
3. If this is not changed, then after the language supports nullable reference types we will have a case where `var` cannot be replaced with the inferred type without a syntax error:

    ```csharp
    string? local = ...;
    if (local is string a) { }
    if (local is var b) { } // b has the type 'string?'
    if (local is string? b) { } // syntax error, presumably equivalent to CS8116
    ```

**Comment by DavidArno** [comment]
I'm puzzled, why would:
```cs
if (local is string? b) { }
```
be a syntax error? If `local` is null, the expression is false and the if block won't execute. If not null, then the value is assigned to the nullable variable `b` and the block is executed.

Whether it was the correct decision to always have the `is var` pattern match, regardless of whether the value is null or not is surely moot: the decision was made and changing it now would be a breaking change (which seems to have no benefit.

**Comment by sharwell** [comment]
@DavidArno Currently both of the following are not allowed:

```csharp
if (local is DateTime? b) { } // fails to parse
if (local is Nullable<DateTime> b) { } // CS8116: it is not legal to use nullable type 'DateTime?' in a pattern

**Comment by sharwell** [comment]
:memo: The most likely situation where this will cause changes is code that uses the following form:

```csharp
case var _ when someExpression:
```

**Comment by HaloFour** [comment]
I'd have to dig but I'm pretty sure the entire debate over `is var` matching `null` already happened.  Considering that's the behavior per spec and per legal C# 7.0 code I can't imagine that the team would reverse it.

Without getting into recursive patterns under what circumstances would `if (input is var x)` be preferred to `if (input != null)`?  Flow analysis with non-nullable references would determine that `input` is not `null` at that point and allow direct referencing.  Having to declare and use a new variable in scope that literally has the same meaning as the existing variable seems extraneous.

**Comment by sharwell** [comment]
@HaloFour this pattern would benefit

```csharp
public string? Property { get; }
```

```csharp
if (this.Property != null)
  MethodWithNotNullArg(this.Property); // I expect a warning here

if (this.Property is var value)
  MethodWithNotNullArg(value); // I would not expect a warning here

// But we're being left with this as the only actually-safe form:
if (this.Property is string value)
  MethodWithNotNullArg(value);
```

**Comment by DavidArno** [comment]
@sharwell,

Again I'm not arguing whether `is var` always matching was the right decision or not, but that's the way it is, and two (more verbose) ways would exist to avoid warnings in your example:
```cs
if (this.Property is PropertyType value)
  MethodWithNotNullArg(value);

if (this.Property is var value && value != null)
  MethodWithNotNullArg(value);
```

**Comment by sharwell** [comment]
> And with read-only locals, what you want could be achieved with an `is let` pattern:

In the absence of this proposal (`is var` checking for null) getting accepted, `is let` would be a suitable alternative.

**Comment by HaloFour** [comment]
I'd pay money to have `is let` also limit scope to when definitely assigned, avoiding the whole leaky pattern variable thing.

**Comment by Thaina** [comment]
I think it look good but what happen when we write

```C#
if(!(obj is let x))
{
    // x is nothing?
}

// x is nowhere to be used ?
```

**Comment by DavidArno** [comment]
@Thaina,

`!(obj is let x)` would be semantically identical to `!(obj is ObjType x)`. So the same rules would apply:
```cs
if (!(s is string ss))
{
    var x = ss; // Error: ss is unassigned here and is unusable
}
else
{
    var y = ss; // ss is assigned and not null
}
var z = ss; // Error: ss may not be assigned and is unusable

if (!(s is let ss))
{
    var x = ss; // Error: ss is unassigned here and is unusable
}
else
{
    var y = ss; // ss is assigned and not null
}
var z = ss; // Error: ss may not be assigned and is unusable
```

**Comment by Thaina** [comment]
@DavidArno I was guessing like that but I'm not sure because there are mention about scope leakage. The `z` in your case would know nothing about `ss` because it outside of `if` scope

Is the `else` count as the same scope as `if` ?

**Comment by DavidArno** [comment]
@Thaina,

`ss` not being visible to `z` is an option. I like it in principle, but it would be inconsistent with other `is` patterns. I guess it depends on how much cash @HaloFour is prepared to stump up 😀 

It would make sense for `else` to be considered part of the `if` scope if such a scope restriction were introduced.

**Comment by alrz** [comment]
as it was mentioned before, var pattern deliberately doesn't check for null for two reasons,

- It's considered as "catch all" for switch, i.e. `case var x` would subsume all the subsequent patterns.
- When used in a recursive pattern to bind a value, being null is kinda irrelevant, unless, of course, you want to add nullable reference types into the mix.

Anyways, I do think different scope/nullability for `let` besides being readonly is attractive but it feels like a JavaScript feature.

**Comment by HaloFour** [comment]
I wonder if a behavioral change would be palatable when considered specifically alongside nullable reference types.  Since that syntax/behavior does not exist today it theoretically wouldn't be a breaking change.  Although using an older compiler would produce a different result.

```cs
public class Foo {
    public string Bar { get; set; }
    public string? Baz { get; set; }
}

///
var foo = MethodReturnsFoo();

if (foo.Bar is var bar) {
    // always true, bar could be null but shouldn't be
}

if (foo.Baz is var baz) {
    // only true if Baz returns non-null value
}
```

**Comment by alrz** [comment]
@HaloFour 

What if null was a valid value? It shouldn't cause the whole pattern to fail if it's not explicitly specified to do so (using a new syntax).

**Comment by aluanhaddad** [comment]
Another argument for not using `let` as the keyword to introduce readonly local variables
```swift
if (nullable is let nonNullable)
```
vs
```kotlin
if (nullable is val nonNullable)
```
😝

**Comment by DavidArno** [comment]
@aluanhaddad,

I agree that `is let` scans horribly compared with `is val`. But `val` and `var` look too similar in my view. And I prefer `let x = ...` to `val x = ...`. There's never a perfect solution.

**Comment by HaloFour** [comment]
🍝 

How about:

```cs
if (foo?.Bar?.Baz isnot null x) { ... }
```

**Comment by alrz** [comment]
>`if (foo?.Bar?.Baz is null x) { ... }`

or combine `not` and `as` patterns:

```cs
if( e is not null as x )
```
(insert any token instead of `as` since it is ambigious -- this includes "none" which is basically what @HaloFour  suggests)

**Comment by gafter** [comment]
In the next update to pattern-matching in C#, we will be adding support for a property pattern. For example, if you have a `object o`, you would be able to test if it is a `Point` whose `X` value is `3`, and save its `Y` value into a variable `y` by writing

``` c#
if (o is Point {X is 3, Y is var y}) ...
```

(syntax not necessarily final; we might use `:` instead of `is`)

If the input is already of the type you're testing, you can omit it and that type is implied. For example, if you have a variable `p` of type `Point`, you would write

``` c#
if (p is {X is 3, Y is var y}) ...
```

You can also provide an identifier if you want to refer to the matched entity later:

``` c#
if (GetPoint() is {X is 3, Y is var y} p) ...
```

The semantics of a property pattern is that it first tests if the input is non-null, and then if it is non-null it also matches the named properties against the provided patterns. You can have any number of nested property/pattern pairs. In this example, if `GetPoint()` returns type `Point?`, then `p` will be of type `Point` (stripping nullable). 

As a side-effect, you get a null pattern "for free", because "zero" satisfies "any number":

``` c#
if (GetPoint() is {} p) // if the returned point is not null...
```

Given that there is pattern `{}` that acts exactly like `var` but doesn't match null (and conveniently strips `Nullable<>` from the type when it is present), we are unlikely to add any further way to do the same thing.

**Comment by gafter** [comment]
As for the actual proposal here: we cannot make that change, as it would change the behavior of existing code.

**Comment by jnm2** [comment]
> ```cs
> if (GetPoint() is {} p) // if the returned point is not null...
> ```
> 
> Given that there is pattern `{}` that acts exactly like `var` but doesn't match null (and conveniently strips `Nullable<>` from the type when it is present), we are unlikely to add any further way to do the same thing.

I can live with this quite happily.

**Comment by sharwell** [comment]
Yep, me too.

**Comment by DavidArno** [comment]
> if (GetPoint() is {} p) // if the returned point is not null...

Love it! 👍

**Comment by alrz** [comment]
Copying https://github.com/dotnet/csharplang/issues/306#issuecomment-336021072

>That would make it impossible to use `{}` for array patterns. `{}` could match an empty array, on the other hand, property patterns always need to match at least one property e.g. `{name is var p}`

**Comment by Makeloft** [comment]
Solution for your problem
```c#
public static bool Is<T>(this T o, out T x) => (x = o) != null; /* or same (x = o) is T */
```
```c#
if ({expression}.Is(out var x) && M(x.A, x.B))
    Console.WriteLine("true")
else Console.WriteLine("false");
```
```c#
public class Point
{ 
    public int X { get; set; }
    public int Y { get; set; }
}

public Point GetPoint() => new Point { X = 123, Y = 321 };
public bool IsHitTestPassed(int x, int y) => x >= 0 && x <= y;

var o = GetPoint();
if (o.Is(out var p) && IsHitTestPassed(p.X, p.Y))
    Console.WriteLine("true");
else Console.WriteLine("false");

if (GetPoint().Is(out var p) && IsHitTestPassed(p.X, p.Y))
    Console.WriteLine("true");
else Console.WriteLine("false");
```
More details and samples here:
https://github.com/dotnet/csharplang/issues/1196#issuecomment-352406099
https://github.com/dotnet/csharplang/issues/1196#issuecomment-352418662

**Comment by sharwell** [comment]
@Makeloft that does not resolve the original goal of having a syntax work well with nullable reference types. In your sample, the out parameter `x` would need to have the type `T?`, which defeats the purpose.

**Comment by Makeloft** [comment]
@sharwell at the current sample we may safely work with 'null' values too. The implementation of 'Is' method equals to the expression 'o is {} t'. You may rename method if needed.

P.S. https://github.com/dotnet/csharplang/issues/1196#issuecomment-353974382

**Comment by sharwell** [comment]
> The implementation of 'Is' method equals to the expression 'o is {} t'.

This would be correct if #727 were available, but under the current rules of the language we cannot replace `is {} t` with an extension method (at least not for the specific purpose of working with Nullable Reference Types).

**Comment by Makeloft** [comment]
@sharwell 
IMHO, constantly true expression 'is var t' and compensation 'is {} t' are mistakes of design.
Actually, I prefer using of extension methods instead new no intuitive syntax.

**Comment by HaloFour** [comment]
@Makeloft 

> Actually, I prefer using of extension methods instead new no intuitive syntax.

You're free to use your own extension methods instead.  However, those extension methods won't help you with recursive patterns when they are adopted in the language.  Perhaps active patterns will fill that role and you can either roll your own null-checking patterns, or use ones built-in.  I'm personally hoping that `Option<T>` patterns `Some(T)` and `None` will work on arbitrary reference types and nullable value types.

**Comment by Makeloft** [comment]
@HaloFour why extension methods are not helpful with recursive patterns?
Similar constructions works fine
```c#
if (GetModel().Is(out var p) && p.PropA.Is() && p.PropB(out var b) && b.PropX.Is(123) ...
```
Or are you mean something else?
