### ISSUE TITLE
[Proposal] Allow method groups to behave the same as lambdas under type inference.

### ISSUE THREAD

**Issue by bradphelan** [dotnet/csharplang#798]
The following is not possible. ( Everything defined as local functions )

    public static void MyAction(int i, int j, int k){}
    public static void DoSomething<T0,T1,T2>(Action<T0,T1,T2> action){}
    DoSomething(MyAction)

however the following is possible

    public static void MyAction(int i, int j, int k){}
    public static void DoSomething<T0,T1,T2>(Action<T0,T1,T2> action){}
    DoSomething((int i, int j, int k)=>MyAction(i,j,k));

It just feels wrong that the first is not possible and the second is.

**Comment by DavidArno** [comment]
This is a duplicate of [Type argument inference with unambiguous method group](https://github.com/dotnet/csharplang/issues/129).
