### ISSUE TITLE
Open questions for `field` and `value` as contextual keywords

### ISSUE THREAD

**Issue by cston** [dotnet/csharplang#8130]
## Open questions for `field` and `value` as contextual keywords

Open questions for `field` and `value` as contextual keywords. Some of these issues were raised at the previous LDM discussion.

- Proposal: https://github.com/dotnet/csharplang/issues/7964
- Previous discusson: [LDM-2024-03-04](https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-03-04.md#breaking-changes-making-field-and-value-contextual-keywords)

### 1. Allow `nameof(field)` and `nameof(value)`?

`nameof(value)` is useful for error reporting, and has an obvious value of *`"value"`*.

Should `nameof(field)` also be supported? If so, what is the expected value of `nameof(field)`?

```csharp
if (value is null)
    throw new ArgumentNullException(nameof(value));

Console.WriteLine(nameof(field)); // ok?
```

### 2. Should `value` be a keyword in a property or indexer `get`? Should `field` be a keyword in an indexer?

`value` is the implicit parameter for `set` and `init` accessors. Should that keyword be allowed in `get` accessors where there is no implicit parameter?

`field` is the backing field for *non-indexer* properties. Should that keyword be allowed in indexers where there is no obvious backing field?

In both cases, the only use of the keywords may be `nameof()`.

```csharp
object P { get => nameof(value); }

object this[int i]
{
    get { return _list[i]; }
    set { _list[i] = value ?? nameof(field); }
}
```

### 3. Should `field` and `value` be considered keywords in lambdas and local functions within property accessors?

It seems obvious that `field` and `value` should be allowed in nested functions, to allow closures over those values, but confirming that `field` and `value` are keywords in nested functions.

### 4. Should `field` and `value` be keywords in property or accessor *signatures*?

`field` and `value` will be considered keywords *within* accessor bodies. Should they also be considered keywords *outside* the accessor bodies in the property and accessor *signatures*?

```csharp
class await { }
async Task<await> F() => return default; // ok

class field { }
field P { get; set; } // ok?
```

### 5. Should `nameof(field)` and `nameof(value)` be allowed in property and accessor *signatures*?

Related to the previous question, but specifically as values using `nameof()`.

```csharp
[MyAttribute(nameof(field))] object P { get; set; }

object this[string x, string y = nameof(value)] { get; set; }
```

**Comment by TahirAhmadov** [comment]
My opinion: 1, yes, 2, no and no, 3, yes, 4, no, 5, no.

**Comment by 333fred** [comment]
Discussed in LDM: https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-05-15.md#field-and-value-as-contextual-keywords
