### ISSUE TITLE
[] matches string and byte[] in overload resolution, but it can't be a string

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/csharplang#8326]
### Type of issue

Other (describe below)

### Description

[Using 8.0.300 SDK]

This code:

```csharp
public class C
{
    public void M()
    {
        M([]);
    }
    
    void M(string s) {}
    void M(byte[] bytes) {}
}
```

Yields, for M([]);``:

```
error CS0121: The call is ambiguous between the following methods or properties: 'C.M(string)' and 'C.M(byte[])'
```

However, this code:

```csharp
public class C
{
    public void N()
    {
        string s = [];
        byte[] bytes = [];
    }
}
```

Yields, for `string s = [];`:

```
error CS1729: 'string' does not contain a constructor that takes 0 arguments
```

What's going on here?

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/collection-expressions

### Content source URL

https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md

**Comment by 333fred** [comment]
What's going on is that you need to upgrade your SDK to a current version. See the changes discussed during https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-01-10.md#conclusions, and the breaking change implementing the fix.

**Comment by paulomorgado** [comment]
> What's going on is that you need to upgrade your SDK to a current version. See the changes discussed during https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-01-10.md#conclusions, and the breaking change implementing the fix.

Is the design meeting the only place where this is noted?

**Comment by 333fred** [comment]
Sorry, I thought I linked the breaking change notification: https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%208.md#collection-expression-target-type-must-have-constructor-and-add-method.
