### ISSUE TITLE
Null check syntactic sugar; Make `foo?` equivalent to `foo != null`

### ISSUE THREAD

**Issue by kingces95** [dotnet/csharplang#833]
So here's my weekend idea...

Null checks are common so why not sprinkle on some (more) syntactic sugar? 

Instead of
```` C#
if (myArg == null) throw new ArgumentNullException()
````
how about
```` C#
if (!myArg?) throw new ArgumentNullException()
````
We've already become accustom to an expression that starts with `myArg?` being declarative syntax for a null check followed by property access (as in `myArg?.Prop`) or a null check followed by an alternate expression (as in `myArg ?? myOtherArg`). So if `myArg?` is followed by nothing, then... well... it's just a null check resulting in a bool (which could possibly be followed by some procedural action like throwing an exception).

**Comment by HaloFour** [comment]
If `obj?` produced a `bool` it would be expected that `obj?.ToString()` would return either `"True"` or `"False"`, but that is already legal syntax that has a completely different behavior.  This proposal would either break this behavior or introduce ambiguities.

**Comment by MillKaDe** [comment]
.. has already been suggested a few times .. See:
- [**#196 - Discussion: `null` evaluation operator to boolean**](https://github.com/dotnet/csharplang/issues/196)
- [**#545 - Proposal: `?obj` operator for real '!null' check on all nullable types**](https://github.com/dotnet/csharplang/issues/545)
- plus several others linked in those two threads ..

Possible syntax (unary prefix operator with highest precedence):

C# (now)|C# (proposed)|C/C++|remarks
---|---|---|---
`if (p != null) ..`|`if (?p) ..`|`if (p) ..`|`= !ReferenceEquals (null, p)`
`if (p == null) ..`|`if (!?p) ..`|`if (!p) ..`|`= ReferenceEquals (null, p)`

The `!` operator for bool already exists, and the `?` operator for non-null checks would be implemented something like this ..
```c#
static public bool operator ? (T t) where T : class => !ReferenceEquals (null, t);
```
For details about this particular syntax see the two linked threads.

Both threads mentioned above are closed right now, but I still think a null check operator would be really nice.

**Comment by MillKaDe** [comment]
@HaloFour : I think a **prefix** instead of **postfix** operator would avoid the problems you mention.

**Comment by HaloFour** [comment]
My opinion is that an equality comparison is succinct enough and significantly more readable than either operator-based proposal.

**Comment by kingces95** [comment]
@HaloFour, ah, yeah. `Foo?.ToString()` is ambiguous. Duh. Well, that's why language design should be left to the professionals! 

@MillKaDe thanks for the links. The prefix ops may work but I gotta say I'm more accustom to seeing the question mark as a postfix operator..
