### ISSUE TITLE
What the community thinks about a csharplang channel?

### ISSUE THREAD

**Issue by eyalsk** [dotnet/csharplang#834]
Hey guys,

There are some channels both on IRC/Gitter for other languages and I wonder what the community thinks about having our own channel on Gitter?

The goal of the channel would be as follow:

1. General discussions about C#.

2. Discussing language design and theory.

3. Helping people out and provide assistance.

4. Anything related to C# that can't be discussed here.

I'm not sure who should own the channel, the design team or the community but it's definitely up for discussion.

Just for reference TypeScript has a channel on Gitter and there is a small C# channel on QuakeNet but I'm not sure how many people there know about this repo and how many of them actually engage in discussions, not to mention that a Gitter channel is by far better than IRC for this due to GitHub integration.

Thoughts?

**Comment by yaakov-h** [comment]
There's a decent C# channel on Freenode already (`##csharp`) too.

**Comment by eyalsk** [comment]
@yaakov-h oh, didn't know about it, I'll join even though I think that Gitter is much better because you can watch the activity of the repo, linking stuff is easier and it's much more accessible than IRC. :)

**Comment by eyalsk** [comment]
@yaakov-h Are you sure? because it seems like there no such a channel on freenode, the only two channels I see are #csharp.de and #learncsharp both only with a single person in them. :)

**Comment by eyalsk** [comment]
Closing this due lack of interest.

**Comment by HaloFour** [comment]
I've been trying to drum up more interest and participation for the CodePlex/GitHub repos on the EfNet #C# channel for years with little success.  Even those that read these issues rarely comment.  Same at my current company.  Most of my coworkers find the subject interesting but not enough to really get involved.  It's a real shame and I don't know how to better encourage community involvement.

**Comment by eyalsk** [comment]
@HaloFour Yup, it really frustrates me because people I work with and also friends don't like the subject as much as I do and as much as I try to encourage them they don't see what's so interesting about it besides the fact that the language is a tool to them to write software. :)

I don't know whether I should keep the issue open and let it linger or keep it close? what do you think? I really want us to have a Gitter channel. ^^

**Comment by amis92** [comment]
I think you can just go ahead and create it, we're an open source community and there are no restrictions (I think?) for creating channels for public repos.

I know I'll be there :)

And then just like, open a PR with Gitter badge :shipit:

**Comment by eyalsk** [comment]
@amis92 Thanks, I'll do it. ;)
