### ISSUE TITLE
The unofficial C# channel is open on Gitter, feel free to join.

### ISSUE THREAD

**Issue by eyalsk** [dotnet/csharplang#836]
Hey guys,

Previously, I've created [a post about it](https://github.com/dotnet/csharplang/issues/834) and asked what the community thinks about having our own channel but there was no interest so I decided to create it and let time do its thing! 

**The goal of the channel is as follow:**

1. General discussions about C#.

2. Discussing language design and theory.

3. Helping people out and provide assistance.

4. Anything related to C# that can't be discussed here.

So please [join](https://gitter.im/CSharpLang)! be respectful and spread the love! <3.

**Bear in mind this would probably be a slow channel at the start so if no one answer please be patient.** 

The only downside is because this is "unofficial" I can't have integration so I'm not too sure how to go about it, it would be nice if the owners here would allow it.

**I really want this to be an open and friendly channel.**

@MadsTorgersen would it be fine to enable Gitter integration? all you guys have to do is add the Gitter service to the repo and use the key I provide so the folks on the channel would have the ability to see the activity for this repo, alternatively, you can create a new channel, whatever you guys decide.

**Update1:** I couldn't add @MadsTorgersen as an admin so I've added @gafter and @CyrusNajmabadi, they can add the service and use the key instead of me providing it.

I also made the following community members an admin of the channel: @HaloFour, @jnm2, @Joe4evr, @alrz, @svick, @DavidArno, @yaakov-h.

<s>I tried to add @MgSam and @orthoxerox to the list but for some reason I couldn't, maybe it has something to do with privacy.</s>

**Update2:** Added @orthoxerox and @MgSam to the admin list.

**Comment by eyalsk** [comment]
@CyrusNajmabadi, @MadsTorgersen, @gafter I really don't want to sound like a broken record but can any of you tell me whether it's possible to add the Gitter service to the channel? or at least discuss the possibility? 

Adding the Gitter service to the channel will allow us to easily link issues and watch the repo for updates.

I know we're a small community here but still a community nonetheless and having this channel allows us to share ideas and and experiences about C# and development in general that wouldn't be possible without it.

I really hope I'm not asking much.

**Comment by jcouv** [comment]
@eyalsk Would you have any links describing the Gitter service integration, how it works and how to enable it? Thanks

**Comment by eyalsk** [comment]
@jcouv Sure,

1. GitHub [WebHooks](https://github.com/gitlabhq/gitlabhq/blob/master/doc/user/project/integrations/webhooks.md).

2. [Gitter: Integrations](https://gitter.zendesk.com/hc/en-us/articles/200176722-Integrations) 

I made you an admin so you can have full control, if you need any help with it I'd be more than happy to help.

Thank you!

**Comment by tannergooding** [comment]
https://github.com/dotnet/csharplang/pull/999

Looking at seeing about integrations now.

**Comment by eyalsk** [comment]
@tannergooding Thank you guys. :)
