### ISSUE TITLE
Interface constructors

### ISSUE THREAD

**Issue by UnoSD** [dotnet/csharplang#837]
I was looking at this proposal from @devedse : https://github.com/dotnet/csharplang/issues/769

And it would be a nice language feature although, I agree with @jnm2 on his comment: https://github.com/dotnet/csharplang/issues/769#issuecomment-323382615 about the lack of semantical meaning

How about defining the constructor on the interfaces? That would solve both problems; it will allow parameters in constructors and the interface can specify the meaning with named parameters and a constructor that is bound to the interface meaning itself.

```csharp
class Program
{
    static void Main(string[] args)
    {
        var randomData1 = CreateRandomData<FastRandom>(10);
        var randomData2 = CreateRandomData<CryptoRandom>(10);
    }

    public static IEnumerable<int> CreateRandomData<R>(int length) where R : IRandom
    {
        var randomGenerator = new R(50);

        for (int i = 0; i < length; i++)
            yield return randomGenerator.Next();
    }
}

public interface IRandom
{
    IRandom(int seed);
    int Next();
}

public class FastRandom : IRandom
{
    private int seed;

    public FastRandom(int seed) => this.seed = seed;

    public int Next() => 0 + seed;
}

public class CryptoRandom : IRandom
{
    private int seed;

    public CryptoRandom(int seed) => this.seed = seed;

    public int Next() => 1 + seed;
}
```

Haven't thought this through yet so please apologise if it has some evident pitfall.

For instance, I, for one, struggle with the idea of forcing a parameter on an interface that has potentially no effect on the public API output but it is just an internal implementation detail.

**Comment by Pzixel** [comment]
IMHO it has nothing to do with interface. For example, how compiler have to choose between different constructors? Meanwhile, `public static IEnumerable<int> CreateRandomData<R>(int length) where R : IRandom, new(int)` seems to be far more reasonable.

**Comment by vladd** [comment]
In the normal cases, classes implementing the same interface nevertheless need different parameters in their constructors.

```
public class NoRandom : IRandom
{
    public int Next() => 0;
}

public class FastRandom : IRandom
{
    int seed, multiplier;
    public FastRandom(int seed, int multiplier)
    {
        this.seed = seed;
        this.multiplier = multiplier;
    }
    public int Next() => { seed *= multiplier; return seed; }
}

public class CombiningRandom : IRandom
{
    IRandom source, index;
    int[] reservoir = new int[256];
    public CombiningRandom(IRandom source, IRandom index)
    {
        this.source = source;
        this.index = index;
        for (int i = 0; i < reservoir.Length; i++) reservoir[i] = source.Next();
    }
    public int Next()
    {
        uint nextIdx = (uint)index.Next() >> 24;
        int result = reservoir[nextIdx];
        reservoir[nextIdx] = source.Next();
        return result;
    }
}
```

Having a predefined constructor signature would require squeezing the parameters into the signature types, which isn't going to produce a good code. Let's not endorse bad coding patterns.

**Comment by Opiumtm** [comment]
Most obvious and direct solution is to use "factory pattern".

Just define "factory interface"
```C#
public interface ISomething
{
    // ...
}

public interface ISomethingFactory<T> where T : ISomething
{
    T Create(int arg1, string arg2);
}
```

**Comment by jnm2** [comment]
What does this gain you over simply declaring a separate factory interface or custom delegate?
The separate factory interface makes more sense than including all the methods in one interface because the concerns are separate. You might want to use a caching factory in some places and a transient factory in other places while both factories return the same implementation.

Plus, like @vladd says there's the problem of different implementations needing extra constructor parameters which is almost a given.

**Comment by Pzixel** [comment]
@jnm2 C# is a turing-complete language so you already can express anything, but it's better to have a language support than write factory of factory of adapter of facade. You already have a factory which just invoking a constructor. It's a completly mechanical process and this is what compilers are good at.

**Comment by orthoxerox** [comment]
@jnm2 it's the same kind of request as the one about async constructors (#419). In both cases you can use a factory method, but bare factory methods are an antipattern in my opinion. You should construct objects using constructors, and it's an unnecessary limitation of the language that a constructor is a special method that always automatically allocates a new object. I would gladly welcome constructors that return cached instances, construct objects asynchronously etc.

Why can't the rules of object instantiation be a part of the interface? They are no different from the rules of interaction.

**Comment by HaloFour** [comment]
Constructors aren't virtual and aren't inherited behavior.  It generally doesn't make any sense for them to be given each type has very different dependencies.

That said, I would imagine that shapes would satisfy this proposal.

**Comment by Pzixel** [comment]
@HaloFour constructors has defenitly inherited behaviour. It has been discussed already: https://github.com/dotnet/csharplang/issues/419#issuecomment-294190226 and https://github.com/dotnet/roslyn/issues/6788#issuecomment-272162052 . I didn't invent any worthwhile solution but I defenitly think that we need more asyncish support in language.

**Comment by HaloFour** [comment]
@Pzixel 

What you are describing is not inheritance.  Constructors are not inherited, which is why a derived class must invoke a parent constructor from its own constructor.

**Comment by Pzixel** [comment]
@HaloFour In this regard you're right, because I meant logical `inheritance`.

**Comment by DavidArno** [comment]
I subscribe to the view that the need for a design pattern in code is an indication of a deficit in that language. Factory patterns are one such example. As @orthoxerox says,  `new` really is very limited in C#: it returns a new instance of some type. In situations where a value singleton is needed, a cached value, or some other control over what type is provided to the caller, then factories are needed. I do not subscribe to the view that factory methods are anti-patterns though. They are genuine patterns: they provide a work-around to the language's limitations.

However, I do not see this proposal as addressing any of this. What parameters a class needs for its constructors is implementation specific. Binding all implementations to a specific constructor defined by an interface feels like a step in the wrong direction to me.

**Comment by UnoSD** [comment]
Another downside is that it may encourage people to use it for logic classes forcing either to "service-locate" dependencies or to avoid DI all together.

Perhaps we could solve this in a different fashion, as having to write a factory to achieve this is of course good practice, but a lot of boilerplate in simple cases. User could rely on high order functions passing the factory method in, but that would make it even closer to the implementation in some cases.

**Comment by jnm2** [comment]
I don't understand why you'd ever expect to be able to return arbitrary objects from a constructor. We need the concept of construction. It's unique; it *means* "build a brand new instance." You can't replace it with a higher-level factory abstraction. Any factory abstraction would have to delegate back to construction at some point so the factory abstraction itself wouldn't be called "construction."

**Comment by DavidArno** [comment]
@jnm2,
> I don't understand why you'd ever expect to be able to return arbitrary objects from a constructor.

I'm not sure we would expect to. `new` is just a built-in factory. But other factories are needed too, thus the various factory patterns. Language syntax for replacing those patterns would be nice. But it really isn't a priority in my view.

**Comment by eyalsk** [comment]
#164 should solve this problem.
