### ISSUE TITLE
Discussion: \$ character escape for names

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#838]
Currently, when you want to build up a string from multiple identifier names you'd end up with this:
```cs
var str = $"logged: {nameof(Class)}.{nameof(Class.Member)}";
```
Which is a lot less readable compared to the equivalent raw string `"logged: Class.Member".

I want to suggest to use `\$` and `\$@` character escapes (currently an error) for that,
```cs
string a = "logged: \$Class.Member";                 // "logged: Member"
string b = "logged: \$@Class.Member";                // "logged: Class.Member"
string c = "logged: \$@Namespace.Class.Member";      // "logged: Namespace.Class.Member"
```
This should work for non-verbatim string interpolated strings as well.

Note: If you want to use a raw string after `.` you would have to escape it i.e. `\.`.

Rel: https://github.com/dotnet/csharplang/issues/522

**Comment by eyalsk** [comment]
@alrz Will it have the added benefit to produce a constant as opposed to `string.Format`? or it's just going to be equivalent to the former?

**Comment by yaakov-h** [comment]
How do you finish this type of interpolation? Where's the end boundary?

e.g.:

```
string a = $"Log {nameof(Foo)}Thing"; // "Log FooThing"
string b = "Log \$FooThing" // ??
```

Also related: #701, dotnet/roslyn#10972

**Comment by eyalsk** [comment]
@yaakov-h Well, it's only a problem if you have a `FooThing`, so how about something like this `\$Foo$`?

**Comment by alrz** [comment]
@eyalsk A string literal is a constant already and this addition would not change that. Note: there are other proposals to make string interolated strings a constant if all of interpolations are constant and there is no format specifier which is unrelated here.

**Comment by orthoxerox** [comment]
This will make Visual Studio's refactoring job much harder. The benefit of `nameof` is that it is a separate syntax node.

**Comment by alrz** [comment]
@orthoxerox how about another syntax node just like interpolations?

**Comment by eyalsk** [comment]
@alrz I know that a string literal is a constant, not sure whether I was clear but I'm asking whether this version of interpolated string would end up being a constant as opposed to a string.Format call.

```
var str = $"logged: {nameof(Class)}.{nameof(Class.Member)}";
```

Same as the following:

```
var str = string.Format("logged: {0}.{1}", nameof(Class), nameof(Class.Member));
```

Now, I'm asking whether your version would have the added benefit to be the following:

```
var str = "logged: Class.Member";
```

Or is it just the same and the only thing it adds is "readability"?

**Comment by alrz** [comment]
@eyalsk The point is to keep identifiers in sync in case of renaming etc. But the final string is the same.

**Comment by eyalsk** [comment]
@alrz Ah okay, thanks. :)

**Comment by Thaina** [comment]
More like you need `fullnameof(Class.Member)`

**Comment by alrz** [comment]
@Thaina It does not address verbosity caused by nameof+string interpolation mentioned in the OP.
