### ISSUE TITLE
nullable tracking doesn't work well with linq

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#8383]
**Version Used**: master

**Steps to Reproduce**:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;

#nullable enable
public class C {
    public IEnumerable<string> WhereNotNull(IEnumerable<string?> strings)
    {
        return strings.Where(x => x != null);
    }
}
```

**Expected Behavior**:

No warning

**Actual Behavior**:

warning CS8619: Nullability of reference types in value of type 'IEnumerable<string?>' doesn't match target type 'IEnumerable<string>'.

**Comment by julealgon** [comment]
@mungojam @Mrxx99 @Spongman @BenMakesGames 
> To cover the main case, maybe the BCL could add a function `.WhereNotNull()`.

This has been rejected.
- https://github.com/dotnet/runtime/issues/30381

**Comment by 333fred** [comment]
Closing as a duplicate of https://github.com/dotnet/csharplang/issues/3951.
