### ISSUE TITLE
Auto checking for null before calling a method

### ISSUE THREAD

**Issue by melanchall** [dotnet/csharplang#842]
Sometimes it is needed to write the code like:

```csharp
var something = x == null ? null : Func(x);
```

It looks like a boilerplate code to check for `null` before passing an argument to the method. Especially if expressions like this occurs several times in one instruction:

```csharp
return new Something(x == null ? null : Foo(x),
                     y == null ? null : Bar(y));
```

One possible way to cope with this cases is to return `null` inside those methods if an input argument is `null`. But it is not always good and desirable behavior. For example, it is a common practice to throw `ArgumentNullException` in this case for public API methods. So we need to prevent calling of them with `null`.

I suggest an idea to provide kind of syntax sugar for described scenario. Something like this:

```csharp
return new Something(Foo(x?), Bar(y?));
```

which will compile into the instructions above checking a value for `null`. Maybe `?` after an indentifier is not a good choice since it can be treated as uncompleted ternary operator especially if a variable it is attached to is a bool. But it is just an idea, which in my opinion can make code shorter and clearer.

Also if a method's return type is `void` it just will not be called. With this "feature" code like this:

```csharp
public object Func(object arg)
{
    if (arg == null)
        return null;

    var x = Foo(arg);
    if (x == null)
        return null;

    var y = Bar(x);
    if (y != null)
        Do(y);

    return y;
}
```

will be simplified to:

```csharp
public object Func(object arg)
{
    var y = Bar(Foo(arg?)?);
    Do(y?);

    return y;
}
```

**Comment by jnm2** [comment]
Duplicate of #433?

**Comment by melanchall** [comment]
Yes, indeed... I had feeling that this idea already proposed, but didn't find it. Thanks for pointing this out.
