### ISSUE TITLE
Think of a way to define return type and return value at same time?

### ISSUE THREAD

**Issue by wysisoft** [dotnet/csharplang#851]
i'm always doing this
```
List<string> someFunc(){
var returnValue = new List<string>();
...some code...
return returnValue;
}
```

I wish there was maybe some keyword like 'this', but instead of 'this' its 'returnValue', and its just shorthand for '`var returnValue = new List<string>();`', and it changed type as the return type of the function changed - would be pretty cool. Also maybe it would know to return at the end of the method?

```
List<string> someFunc(){
returnValue.add("test");
}
```

**Comment by franzalex** [comment]
Why would you want to do this at all?

**Comment by MillKaDe** [comment]
I am not sure, if I understand what you want ?!?
Do you mean so called **fluent** syntax ?
For example:
```c#
class XList<T> { // a 'fluent' wrapper for List
  List<T> list;
  XList () { list = new List<T> (); }
  XList<T> add (T t) { list.Add (t); return list; } // add item and return modified self
}
// ...
XList<string> someFunc () => new XList<string> ().add ("test"); // create list and add item
```

**Comment by DavidArno** [comment]
The big problem I have with this proposal is that it positively encourages the use of concrete types in the return type of the method signature. For example, I'd write your example method as:
```cs
IList<string> SomeFunc()
{
    var returnValue = new List<string>();
    ...some code...
    return returnValue;
}
```
That way, if in future I wanted to change the actual type returned, to eg an array or `MyOwnList`, I can do so without having to change the method's signature. Changing that signature is a violation of the Open/Closed principle.

**Comment by HaloFour** [comment]
How would this work if the function returned an interface, or an abstract class, or a class without a default constructor?  What if you wanted to instead invoke a non-default constructor on the type?  Would the function still invoke that default constructor and waste an allocation?

I used to program in VB5/6 where the only way to return values from functions was to assign an implicit variable.  Relying on the control of the function to then properly exit the function was a constant source of logic bugs.  I think it would be a bad idea to introduce said concept to C#.  Doubly-so if that implicit variable was to somehow get preinitialized to some value incurring allocation.

**Comment by jnm2** [comment]
To say nothing of how easily it would be to accidentally break code depending on the API. It's good that it's explicit because it requires attention to change.
