### ISSUE TITLE
Proposal: shorthand syntax for IEnumerable<T>

### ISSUE THREAD

**Issue by DavidArno** [dotnet/csharplang#852]
I find that a lot of methods I write handle `IEnumerable<T>`. I maybe be unusual in this regard, but assuming I'm typical, then this type seems an obvious candidate for some sort of shorthand syntax, as it is a long name to have to type & read. So for example, the following method:
```cs
public IEnumerable<int> AddOneToEachElement(IEnumerable<int> collection)
{
    foreach (var element in collection)
    {
        yield return element + 1;
    }
}
```
could be expressed something like:
```cs
public <[int]> AddOneToEachElement(<[int]> collection)
{
    foreach (var element in collection)
    {
        yield return element + 1;
    }
}
```

Also, with the likely new type of something like `IAsyncEnumerable<T>` for async collections, this new type is even more cumbersome to read/write. So again, it could likewise be abbreviated. maybe to something like `<[async T]>`, but others might have a better idea for abbreviated syntax.

(Update: a slightly flippant reason for wanting this is because I often struggle to type `IEnumerable` properly, as evidenced by me mistyping it in this issue's title! 😀 )

**Comment by DavidArno** [comment]
@banjouuid,

Any chance you could explain your down-vote? Thanks.

**Comment by banjouuid** [comment]
I don't think really necessary to add it as it looks more confusing to me when I see 
`<[int]>` I don't know if I'm looking at an array a badly formed generic or else.

I agree that IEnumerable<T> is quite a big name to write but it doesn't make me think for 5 seconds what I'm looking at.

**Comment by DavidArno** [comment]
@banjouuid,

OK, makes sense. Thanks.

**Comment by MillKaDe** [comment]
**Option 1: type alias**
```c#
using ISeq<T> = IEnumerable<T>;
```
Unfortunately, Generics are not (yet) supported in type alias definitions - but maybe that could be changed ?

**Option 2: special syntactic sugar**
If C# gets some special syntax for IEnumerable<T>, it should look somewhat similar to arrays `T[]`.
For example:
```c#
T<[ ]> // instead of <[T]>
```
.. but it looks wierd. I would prefer Option 1.

**Comment by banjouuid** [comment]
I would use also Option 1

**Comment by eyalsk** [comment]
@DavidArno Nothing that a snippet can't solve. 😉

**Comment by Pzixel** [comment]
If you are writing readable code your priority is clearness of written rather than type a bit less. And I find `IEnumerable<T>` much more readable. Another reason, I see also tons of `IQueryable<T>`, why not a special syntax for this one? :)

**Comment by DavidArno** [comment]
Thanks for your feedback all. There's some good food for thought there.

I shall close this issue. If anyone feels it worth keeping open for further discussion, please let me know.

**Comment by HaloFour** [comment]
I'm not a big fan of the F#-like syntax where you define different container types via wrapping other type names in punctuation.

**Comment by jnm2** [comment]
I type `IEnuemrable` all the time... but I like @eyalsk's idea. Seems like something better solved via IDE than via language feature. Autocorrect, for instance. 😄
