### ISSUE TITLE
Discussion: Static Constructor Injection?

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/csharplang#858]
Static/Type Constructors allow us to configure or create types at runtime, but can't be called and therefore can't accept parameters. They are often used to establish or initialize things like loggers, configurations, or other cross-cutting concerns. These are some of the things that we might want to inject into the classes using Dependency Injection. These can be either injected into the class or initialized in a static constructor, but not both. Allowing a static/type constructor to accept injected parameters can give us both. Injecting static classes also isn't possible right now, but might be with this, and can have some benefits.

This is limited since this is at the type level and shared by all instances.

```
using DependencyInjection

public class Foo{
   private static ILogger _logger;
   private static Utility _utility;
   static Foo(ILogger logger, Utility staticUtilityClass){
      _logger = logger;
      _utiltity = staticUtiltiyClass;
   }

   private readonly IBehaviorial _behavior
   public  Foo(IBehaviorial behavior){
      // Logger injected in static constructor is available in regular constructor
      _logger.LogInformation("logger statically injected");
      _behavior = behavior;
   }

   public void Method( int value ){
      // Static classes can be swapped out and use "regular" DI syntax.
      // If converted to instance classes, little changes.
       var utilityResult = _utility.StaticFunction(value);
   }
}
```
A static constructor would only accept parameters that can be resolved by the DI system. Things like loggers are good candidates for this, but any static or possibly singleton-type object might work. It may even be possible to inject static classes. For example, you may have some static utility classes that implement common functions. Since the static constructor is assigning to static variables, you could configure which of these you wanted to use in the static constructor. This would even be better if static classes could implement interfaces.

I've been using a Service Locator approach to do things like this in static/type constructors to create multiple composition roots and DI in "newed" classes. Being able to use the constructor would be more flexible.

**Comment by HaloFour** [comment]
So you're suggesting that the CLR needs to bake in some dependency injection framework?  Currently DI and IoC are completely library concerns.

Why do you need to inject these dependencies in a static context?  Why not inject them at the instance constructor?  You're making some big assumptions regarding the scope, lifecycle and context of said dependencies when you inject them this way.  What if the logger is proxied per request?  Leave that control in the hands of the container where it belongs.

**Comment by RandyBuchholz** [comment]
@HaloFour It wouldn't see it being much different from how things work right now, just having two places to inject - first in the static constructor and then in the regular constructor. The use cases wouldn't really be that different either. Anything you would normally do in a static constructor now you would still do, only if you are using DI you can now provide variables/parameters via injection. If any CLR changes were needed it would not be to add DI, but to have it delegate to a container like it does with a regular constructor. So if you currently configure a logger in the static constructor you still would, but you now have the option of letting a container help you. Or if you are configuring your logger using DI in the regular constructor, you can move forward in the pipeline (if it makes sense) and use DI in the static constructor.

**Comment by HaloFour** [comment]
> If any CLR changes were needed it would not be to add DI, but to have it delegate to a container like it does with a regular constructor. 

What container?  Type initializers are private details and handled non-deterministically by the CLR.  There is no mechanism through which these methods can be resolved or invoked by an external actor.  You're suggesting making these methods public, directly invocable and somehow deterministic.  How are these methods called and when?  What happens if the type must be initialized prior to the container invoking it?

**Comment by eyalsk** [comment]
@RandyBuchholz How do I control what gets injected? seems too much magic to me and I don't understand what's the benefit of this over existing solutions.

> Being able to use the constructor would be more flexible.

Why? to me it seems like the exact opposite.

**Comment by RandyBuchholz** [comment]
What sent me down this path was exploring building libraries that used DI and had multiple composition roots and nested containers. Long story short, I found that I could create ServiceProviders inside static constructors and then use them in my regular constructors to let me combine using `new` and having DI available inside the class. It was DI abuse, I guess, but it allowed modelbinder, activator, and anything else that wants a parameterless constructor to create an instance with DI enabled. Conceptually I was doing something like
```
var a = new Foo( IFooService serviceF ) {
   Name = "Me",   
   Bar = new Bar( IBarService serviceB ) {
      Height = 20
   }
}
```
But IFooService and IBarService were resolved inside the static constructor not on the regular constructor. It was just ` new Foo{...}` and then inside Foo I could use `_serviceF.WhatEver()`. I was also working on having the library pick up stuff from the outer container. Users of the library only needed to register a IConfig defined in the library in the outer container and the library would be able to use it. I knew some of that wouldn't work completely, but I wanted to see how far I could get. I actually got farther than I expected. I was making a call out of the static constructor to get an `IServiceCollection` to make everything work. If I was able to reverse that and the external container could resolve `IServiceCollection`  on the static constructor of the library config class I would be pretty close. Most of what I do is experimental, not so much practical.

So I put this up as a discussion and not a proposal because I didn't know if it made sense and used logger because in my research logger seemed to be something that people didn't like putting in every constructor (if they DI'ed it). And it was a good example of where it might be practical - if you do it there you can log in your regular constructors, it's a little out of the way, and if you do Logger<Class> it sort of fits as a type feature.

**Comment by eyalsk** [comment]
@RandyBuchholz fair enough I dunno seems to me too much "voodoo" to make this work, it seems to bring a lot of complexity in and people wouldn't get a lot of benefit out of this.

**Comment by RandyBuchholz** [comment]
@eyalsk Yeah, I didn't realize how far down in the CLR static constructors were. Building the providers by hand isn't a big deal. Closing this and posting a code frag. This is a simple way to get DI in classes created with new.

```
        internal class Program {
            [STAThread]
            public static void Main(string[] args) {

                var services = new ServiceCollection()
                    .AddTransient<Application>()
                    .BuildServiceProvider();

                services.GetRequiredService<Application>().Run();
            }
        }

        /******* Application Base Class *******/
        public class Application {
            public void Run() {
                var entityInstance = new EntityClass();

                Console.WriteLine(entityInstance.TwoTimes(4));
                Console.WriteLine(entityInstance.ThreeTimes(8));

            }
        }

        // Newable with DI
        public class EntityClass {
            private static readonly IServiceProvider Provider;
            private static readonly EntityClass _;

            static EntityClass() {
                Provider = new ServiceCollection()
                    .AddTransient<EntityClass>()
                    .AddTransient<IEntityUtilityOne, EntityUtilityOne>()
                    .AddTransient<IEntityUtilityTwo, EntityUtilityTwo>()
                    .AddTransient<IUtilityClass, UtilityClass>()
                    .BuildServiceProvider();
            }

            private EntityClass(EntityClass _) {
                _entityUtilityOne = Provider.GetService<IEntityUtilityOne>();
                _entityUtilityTwo = Provider.GetService<IEntityUtilityTwo>();
            }

            /**************************************************/

            private readonly IEntityUtilityOne _entityUtilityOne;
            private readonly IEntityUtilityTwo _entityUtilityTwo;

            public EntityClass() : this(_) {
            }
            public int ThreeTimes(int i) => _entityUtilityTwo.TimesThree(i);
            public int TwoTimes(int i) => _entityUtilityOne.TimesTwo(i);

        }

        // Level 1 DI

        public interface IEntityUtilityOne {
            int TimesTwo(int i);
        }

        public class EntityUtilityOne : IEntityUtilityOne {
            private readonly IUtilityClass _utilityClass;
            public EntityUtilityOne(IUtilityClass uc) { _utilityClass = uc; }

            public int TimesTwo(int i) => _utilityClass.Multiply(2, i);
        }


        public interface IEntityUtilityTwo {
            int TimesThree(int i);
        }

        public class EntityUtilityTwo : IEntityUtilityTwo {
            private readonly IUtilityClass _utilityClass;
            public EntityUtilityTwo(IUtilityClass uc) { _utilityClass = uc; }

            public int TimesThree(int i) => _utilityClass.Multiply(3, i);
        }

        // Level 2 DI

        public interface IUtilityClass {
            int Multiply(int x, int y);
        }

        public class UtilityClass : IUtilityClass {
            public int Multiply(int x, int y) { return x * y; }
        }

    }
```
