### ISSUE TITLE
Non-copyable structs

### ISSUE THREAD

**Issue by jbayardo** [dotnet/csharplang#859]
There are cases where one is interested in having objects with few data members and a small amount of code to deal with them, but want to avoid copying.

A real use-case we had is a lock-free flag: we had a lot of places in the code base that used Interlock functions to basically set a bool to 0 or 1, or used Volatile in completely wrong ways. We created a struct that looks something like this:

    public struct SingleUseFlag
    {
        private int _state;

        public SingleUseFlag()
        {
            _state = 0;
        }

        public void RaiseOrDie()
        {
            if (Raise() == false)
                throw new InvalidOperationException($"Repeated Raise for a {nameof(SingleUseFlag)} instance");
        }

        public bool Raise()
        {
            return Interlocked.CompareExchange(ref _state, 1, 0) == 0;
        }

        public bool IsRaised()
        {
            return _state != 0;
        }
    }

With a few inlined methods and some other things, in an attempt to make logic this less error-prone.

If you passed this struct as an argument to a function, a copy of the internal `_state` would ensue, and hence you would be keeping two separate flags. On the other hand, declaring this as a class adds the _unwanted_ semantic of a shared flag, as well as unnecessary overhead for something that should be inlined and completely removed (although as a class it would be easy to prevent copying from happening).

In C++, this would be easily fixed by explicitly deleting the copy constructor, copy assignment, move constructor, and move assignment operators. It would be great to be able to specify a "this should never be copied" constraint for the struct in C#.

**Comment by HaloFour** [comment]
Considering that the copy behavior is the one major defining trait of `struct`s in the CLR I don't really understand why (or how) you could eliminate that.  Such a beast would be quite difficult to actually use since literally every assignment of a struct is a copy.  How would you propose to actually use this data type?  I don't see how it's possible to have both the lack of copying as well as non-shared state.

**Comment by Joe4evr** [comment]
So why is that a struct when it should logically be a class?

And you can forget using "muh allocations" as your answer. [In Eric Lippert's words:](https://blogs.msdn.microsoft.com/ericlippert/2009/05/04/the-stack-is-an-implementation-detail-part-two/)
> The relevant feature of value types is **that they have the semantics of being copied by value**, not that **sometimes their deallocation can be optimized by the runtime**.

**Comment by Happypig375** [comment]
What about Swift behaviour that a struct is only copied when it is written to:
(Citing Swift on Wikipedia)
>Similarly to C# and in contrast to most other OO languages, Swift offers built-in support for objects using either pass-by-reference or pass-by-value semantics, the former using the class declaration and the latter using struct...... To ensure that even the largest structs do not cause a performance penalty when they are handed off, Swift uses copy on write so that the objects are copied only if and when the program attempts to change a value in them.

**Comment by HaloFour** [comment]
@Happypig375

That's not automatic in Swift.  That language has the same semantics as C#.  To make a struct use CoW semantics you have to wrap it in a reference type.  It's similar to String in the BCL.  It is a reference type but also effectively immutable and modifications are performed through methods which copy and mutate the value.

https://marcosantadev.com/copy-write-swift-value-types/

**Comment by Happypig375** [comment]
@HaloFour So that code is strongly tied to Automatic Reference Counting, but C# uses Garbage Collection. If it were to be automatic, it would be very beneficial, and I don't think it would break existing code.

**Comment by HaloFour** [comment]
@Happypig375 

Doesn't matter what mechanism of clean up that it's tied to, it still involves an allocation on the heap and passing that reference around.  Doing such would have a drastic impact on the performance of existing code.  Doing such automatically doesn't make sense in any language, including Swift.  You either have reference semantics with shared state or you have value semantics with copying.

**Comment by tannergooding** [comment]
> If you passed this struct as an argument to a function, a copy of the internal _state would ensue, and hence you would be keeping two separate flags

Why is `ref` or the upcoming `ref readonly` insufficient?

**Comment by tannergooding** [comment]
You may have a struct:
```csharp
struct Size
{
    int x;
    int y;
}
```

You can then declare a method that takes this type as a parameter in several different ways:
```csharp
void SetSize(Size size);                // C/C++: void SetSize(Size size)
void SetSize(ref Size size);            // C/C++: void SetSize(Size* size);
void SetSize(ref readonly Size size);   // C/C++: void SetSize(const Size* size);
```

The exact semantics of each depends on the underlying calling convention.
At least on Windows:
* The first shadow copies the struct to the stack and passes a reference to it (either in a register or on the 
stack, depending on which convention).
* The second and third do not shadow copy and just pass a reference to the struct (no shadow-copying).
  * The second allows the user to easily modify the original struct
  * The third prevents the user from modifying the original struct, unless they remove the readonly modifier (`System.Runtime.CompilerServices.Unsafe`) or if they remove the const modifier (C/C++, `const_cast`).

**Comment by Thaina** [comment]
I know the usage and think it's good, I like it, but I don't think this will really be used much to worth being feature

Still if this feature would develop I think we need to bring back C style constructor

Such as
```C#
fixed struct Vector3
{
    public float X,Y,Z;
}


Vector3 position(0,0,0);
```

**Comment by Happypig375** [comment]
@Thaina How is that any better than this?
```cs
struct Vector3
{
    public float X, Y, Z;
}

var position = new Vector3 { X = 0, Y = 0, Z = 0 };
```
With Records (#39) and target-typed new expressions this will become even better:
```cs
struct Vector3(float X, float Y, float Z);

Vector3 position = new(0, 0, 0);
```

**Comment by jnm2** [comment]
I've worked with C style constructors a number of times and I hate them. There's no way (besides non-compiler-checked comments) to notate which field each value goes to. `Vector3` is a specially understood structure where that isn't an issue but in the majority of cases the clarity would be beneficial.

**Comment by Thaina** [comment]
@Happypig375 I mean if this 859 "Non-copyable structs" feature will be implemented. You cannot write 

```C#
var position = new Vector3 { X = 0, Y = 0, Z = 0 };
```

Because that was copying `new Vector3` into `var position`. So only C style constructor can make this kind of struct call its constructor

I just point out the fact that "Non-copyable structs" cannot call constructor

**Comment by ufcpp** [comment]
In some case, mutable structs are very useful for obtaining high performance. For example:

- [ResizableArray](https://github.com/dotnet/corefxlab/blob/master/src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs) in corefxlab
- [JsonWriter](https://github.com/neuecc/Utf8Json/blob/master/src/Utf8Json/JsonWriter.cs) in [Utf8Json](https://github.com/neuecc/Utf8Json), 441-stared very popular library

However, [mutable structs are evil](https://stackoverflow.com/questions/441309/why-are-mutable-structs-evil) for now. Non-copyability of mutable structs are the most feasible solution for this evil issue.

**Comment by ufcpp** [comment]
@Thaina 

[Rust's memory ownership model](https://doc.rust-lang.org/book/first-edition/ownership.html) solves such a problem.

```cs
static void Main()
{
    var p1 = new Vector3 { X = 0, Y = 0, Z = 0 }; // ownership is transferred from LHS to p1

    Write(p1); // OK. pass by reference

    var p2 = p1; // transfer ownership again

    Write(p2); // OK. pass by reference

    Write(p1); // NG. p1 no longer has ownership
}

static void Write(in Vector3 p)
{
    Console.WriteLine($"({p.X}, {p.Y}, {p.Z})");
}
```

**Comment by ufcpp** [comment]
see also:

- [Destructible Types](https://github.com/dotnet/csharplang/issues/121)
- https://www.microsoft.com/en-us/research/wp-content/uploads/2017/07/snowflake-extended.pdf

**Comment by ufcpp** [comment]
I've created an analyzer for non-copyable structs: https://github.com/ufcpp/NonCopyableAnalyzer

**Comment by drewnoakes** [comment]
> Why is ref or the upcoming ref readonly insufficient?

@tannergooding mutable `ref struct`s are still subject to copying. Sometimes you want to enforce a single copy of some state, where it just happens to live on the stack.

An example would be a version of `Lazy<T>` that lives on the stack. Currently you can write:

```c#
public ref struct StackLazy<T>
{
    private readonly Func<T> _func;

    public T ValueOrDefault { get; private set; }

    public bool IsCreated { get; private set; }

    public StackLazy(Func<T> func) : this() => _func = func;

    public T Value
    {
        get
        {
            if (!IsCreated)
            {
                ValueOrDefault = _func();
                IsCreated = true;
            }

            return ValueOrDefault;
        }
    }
}
```

This will work within the current frame, or if you pass by `ref`, but as soon as you pass without `ref` the recipient has a copy and you can double-initialise the value. Having the compiler enforce non-copyability would provide correctness here.

Other examples might be scope-based utilities for nestable operations such as logging entry/exit, timing, etc.

The C++ equivalent would be a deleted copy ctor and assignment operator.

**Comment by tmds** [comment]
I like C++ [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization). I think a C# version would be a non-copyable struct that has a destructor(/Dispose method).

Maybe because non-copyable structs require passing by ref, that should be the default behavior: the ref keyword is implicit (because the struct is 'refonly').

**Comment by ceztko** [comment]
Are "non-copyable structs" actually coming anytime soon? I don't see a champion for them. The poster use case has some uses but the fact you can really turn the `struct` into a `class` at the cost of making it _shared_ seems like a good balance between what you can achieve with encapsulation and the need to keep the number of features into the language to not grow indefinitely (similarly to the balance achieved introducing the `internal` access modifier: sometimes you can't create coupled classes that are fully safe to use within the same assembly boundary, but it's usually considered not a big deal). Instead I don't think the C++ RAII motivation to add such feature to C# super strong: sure, C++ can disable copy, but it also has [guarenteed copy elision ](https://en.cppreference.com/w/cpp/language/copy_elision) and move semantics, which make it very comfortable to create _guards_, _transactions_ or resource cleaners in general and pass them trough different boundaries, which would not be easily available in C# (not part of the language, at least). For RAII purpose I suggest to extend warning for `Dispose` method not being called in structs, as I discuss better in [#1110](https://github.com/dotnet/csharplang/issues/1110#issuecomment-556083632).

**Comment by Joe4evr** [comment]
> Are "non-copyable structs" actually coming anytime soon? I don't see a champion for them.

As long as there's no Champion on the language team, the answer is pretty much guaranteed to be "No".

**Comment by tmds** [comment]
> move semantics

This should be considered also for non-copyable C# structs.
