### ISSUE TITLE
Alternative commented out code delimeters.

### ISSUE THREAD

**Issue by djaus2** [dotnet/csharplang#861]
Can I suggest that some alternative delimiters be adopted for commenting out code as opposed to standard in-code comment delimeters. (**//** and **/* */**).
A code editor could then optionally hide such code, and also have a command to remove commented out code. 
I often comment out slabs of code when trying a different or better implementation but want to retain original in situa until the new version is tested. Yes you could do this via repository but I'd like it this way. 

Cost would be that some characters would have to be assigned for this capability that if actually required then escape sequences would be required.

**Comment by FredyFerrari** [comment]
why not #IF?

**Comment by jnm2** [comment]
> A code editor could then optionally hide such code

If you don't like seeing the code “in situ”, better practice would be to encapsulate it. IDEs also currently support collapsing multiline comments. I would never be in favor of an IDE altogether hiding lines of a file from me.

> and also have a command to remove commented out code.

Seems dangerous. Either you already know the commented out code is worthless, in which case you delete it and rely on source control if you ever need to refer to it again, or you keep it uncommented and compiling so that you don't break it.

**Comment by HaloFour** [comment]
You've got comments and you've got conditional compilation via preprocessor directives.  I don't think that the language needs to add more, especially to encourage what is widely considered bad practice.

**Comment by AtsushiKan** [comment]
Personally, the one incremental improvement I'd like to see is for "#if 0" and "#if 1" to be allowed. (No other numerical values or expressions, just "0" and "1").

Really, it feels silly every time I want to disable a piece of code, I have to type

#if SOME_MADE_UP_SYMBOL_THAT_I_HOPE_REALLY_ISNT_USED_IN_THIS_MASSIVE_BUILD_SYSTEM
#endif

...
and then, have to edit two non-contiguous lines (or find a symbol that is used) to switch back and forth.

Note that my usual scenario for this is in experimenting in private branches - not for code intended to be PR'd. Hence, I'm less concerned than usual about the "bad practice" angle.

**Comment by HaloFour** [comment]
@AtsushiKan 

`#if false` and `#if true`

**Comment by AtsushiKan** [comment]
Ah, ok - didn't know about that one.

**Comment by jnm2** [comment]
I discovered this nonsense you can use sometimes, it's quite fun:
```c#
/*
var a = 1;
/*/
var a = 2;
//*/
```
Add an extra slash at the beginning:
```c#
//*
var a = 1;
/*/
var a = 2;
//*/
```

Works if you have multiple pairs:
```c#
//*
var a = 1;
/*/
var a = 2;
/*/
var b = 1;
/*/
var b = 2;
//*/
```

**Comment by eyalsk** [comment]
@djaus2 

> I often comment out slabs of code when trying a different or better implementation but want to retain original in situa until the new version is tested. Yes you could do this via repository but I'd like it this way.

I don't get the point of "liking" something when it's clearly not a matter of taste, it's more of using the right tool for the job and by using a version control you save yourself a lot of hassle.

I think that you can change between branches a lot faster than you can comment code back and forth, especially when you do that across multiple files.

**Comment by jnm2** [comment]
> I think that you can change between branches a lot faster than you can comment code back and forth, especially when you do that across multiple files.

This is so true.

**Comment by djaus2** [comment]
OK, thanks for everyone's feedback, The suggestion has been well and truly rejected.
So the suggestions are
(a) Use repository branches
(b) Use #if 

jnm2 You comment is interesting. Could lead to some classic spaghetti code. 
You are also correct, the "hidden" code should be collapsed rather than hidden

Alternatively one could always just use // for comments and /* .. */ for code, or viz

Ok so its a collective thumbs down, so I'll close this.
Thanks to all for comments. I'll be back.

**Comment by jnm2** [comment]
(Just so everyone is clear, I don't recommend committing code with that commenting out pattern. 😁 That would totally contradict my initial comment.)
