### ISSUE TITLE
Interface proxy implementation

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#865]
Sometimes we make a class that can do things like dictionary with internal dictionary, so we attach interface `IDictionary` to it

I think it too redundant to implement whole interface

So we should have some syntax that would transpiled to automatically implementation

```C#
class SafeAddDictionary<K,V> : Dictionary<K,V>
{
    readonly Dictionary<K,V> dict = new Dictionary<K,V>();

    public void Add(K key,V value) // implement only Add
    {
         if(!dict.Contain(key))
              dict.Add(key,value);
    }

    Dictionary<K,V>.this => dict; // syntax to be transpiled
    // Transpiler implement everything except `Add`
}
```

**Comment by Joe4evr** [comment]
Dupe of #234.

Also, not a great example due to the existence of `TryAdd()`.

**Comment by Thaina** [comment]
Thank you very much @Joe4evr
