### ISSUE TITLE
Proposal: Expand supported Caller Info Attributes

### ISSUE THREAD

**Issue by HaloFour** [dotnet/csharplang#87]
Copied from https://github.com/dotnet/roslyn/issues/351

# Problem:

The currently supported caller info attributes can only provide the name of the method, the name of the source file and the line number of the call in the source file.  This is fine for scenarios such as simplifying implementations of `INotifyPropertyChanged`.  However, if using these attributes for logging the amount of information available is quite limited.
# Solution:

Expand the number of supported caller info attributes to allow embedding additional diagnostic information.  The following list is quite expansive to discuss/argue over the potential possibilities.

**CallerColumnNumberAttribute**:  The column number of where the method is invoked. 
**CallerTypeNameAttribute**:  The simple name of the declaring type of the calling method.
**CallerNamespaceAttribute**:  The namespace of the declaring type of the calling method.
**CallerFullTypeNameAttribute**:  The full name of the declaring type of the calling method.
**CallerTypeAttribute**:  The declaring type of the calling method.  This is replaced by the compiler by `ldtoken` of the type followed by a call to `Type.GetTypeFromHandle`.
**CallerMethodAttribute**:  The MethodBase of the calling method.  This is replaced by the compiler by `ldtoken` of the method reference followed by a call to `MethodBase.GetMethodFromHandle`.

Example usage:

``` cs
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Project1 {
    public static class Program {
        private static void Foo([CallerMemberName] string memberName = null,
                                [CallerTypeName] string typeName = null,
                                [CallerNamespaceName] string namespaceName = null,
                                [CallerFullTypeName] string fullTypeName = null,
                                [CallerFilePath] string filePath = null,
                                [CallerLineNumber] int lineNumber = 0,
                                [CallerColumnNumber] int columnNumber = 0,
                                [CallerType] Type type,
                                [CallerMethod] MethodBase method)
        {
            Debug.Assert(memberName == "Main");
            Debug.Assert(typeName == "Program");
            Debug.Assert(namespaceName == "Project1");
            Debug.Assert(fullTypeName == "Project1.Program");
            Debug.Assert(filePath == "c:\\foo\\bar\\Program.cs");
            Debug.Assert(lineNumber == 29);
            Debug.Assert(columnNumber == 12);
            Debug.Assert(type == typeof(Program));
            Debug.Assert(method == typeof(Program).GetMethod("Main"));
        }

        public static void Main() {
            Foo();
        }
    }
}
```

----

It was also suggested by @AdamSpeight2008 that a caller-info struct be supported for situations where you want several of these values but don't want to have to declare/annotate multiple parameters.

```vb
Class CallerInfo
  Public ReadOnly MemberName   As String
  Public ReadOnly TypeName     As String
  Public ReadOnly Namespace    As String
  Public ReadOnly FullTypeName As String
  Public ReadOnly FilePath     As String
  Public ReadOnly LineNumber   As Integer
  Public ReadOnly ColumnNumber As Integer
  Public ReadOnly Type         As Type
  Public ReadOnly Method       As MethodBase
End Class
```

```vb
Public Sub Foo(<CallerInfo> ByVal info As CallerInfo = Nothing)
End Sub
```

LDM history:
- https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-01-03.md#other-caller-attributes

**Comment by scottdorman** [comment]
I'm not sure I see a need for `CallerColumnNumberAttribute`. What's the use case you see for that one?

By supporting just `CallerTypeAttribute`, wouldn't we gain access to the same information as what would be in `CallerTypeNameAttribute`, `CallerNamespaceAttribute`, and `CallerFullTypeNameAttribute`? 

`CallerTypeNameAttribute` is available from [`Type.Name`](https://msdn.microsoft.com/en-us/library/system.reflection.memberinfo.name(v=vs.110).aspx), `CallerNamespaceAttribute` is available from [`Type.Namespace`](https://msdn.microsoft.com/en-us/library/system.type.namespace(v=vs.110).aspx) and `CallerFullTypeNameAttribute` is available through [`Type.FullName`](https://msdn.microsoft.com/en-us/library/system.type.fullname(v=vs.110).aspx).

I do like the idea of having a `CallerInfo` struct that can be used in place of having to specify each individual attribute. This would be an "all or nothing" scenario in the sense that if I use the struct, I get all of the values filled in. If I don't want/need all of them, I can still specify them individually.

**Comment by AdamSpeight2008** [comment]
Would it be possible to make the value lazy, so they are produced when need / used.

**Comment by scottdorman** [comment]
@AdamSpeight2008 I'm not sure that would work. From [MSDN](https://msdn.microsoft.com/en-us/library/hh534540(v=vs.110).aspx), "Caller Info values are emitted as literals into the Intermediate Language (IL) at compile time." That would prevent them from being lazily evaluated since they aren't evaluated at run time.

**Comment by HaloFour** [comment]
> I'm not sure I see a need for `CallerColumnNumberAttribute`. What's the use case you see for that one?

Completes the set, mostly.  I could see some use for capturing the position of multiple calls to the same method nested in some other expression, but that might be pretty esoteric.

> By supporting just `CallerTypeAttribute`, wouldn't we gain access to the same information as what would be in `CallerTypeNameAttribute`, `CallerNamespaceAttribute`, and `CallerFullTypeNameAttribute`?

Yes.  C# already supports `CallerTypeNameAttribute`, so I built this proposal from there.

My use cases would be covered if the only caller-info attributes were `CallerMethod`, `CallerFilePath` and `CallerLineNumber`.  Everything else of value to me can be derived from that.

> I'm not sure that would work. From MSDN, "Caller Info values are emitted as literals into the Intermediate Language (IL) at compile time." That would prevent them from being lazily evaluated since they aren't evaluated at run time.

Technically true, but it's possible that some of the work could be deferred until runtime.  Specifically with `CallerInfo` where you accept a `struct` of the values.  That `struct` could have a constructor that only accepts the `RuntimeMethodHandle` for the calling method pushed by `ldtoken`, the file name and the file line number.  Then the actual method and type properties could be lazily evaluated by taking that `RuntimeMethodHandle` and loading the actual `MethodBase` and from that deriving the declaring `Type`.

**Comment by scottdorman** [comment]
> C# already supports CallerTypeNameAttribute

Do you mean `CallerMemberNameAttribute`?

So, right now we already have `CallerFilePathAttribute`, `CallerMemberNameAttribute`, and `CallerLineNumberAttribute`.

I think if we just added `CallerTypeAttribute` and `CallerMemberAttribute` (which return a `Type` and a `MemberInfo`, respectively), would that work? I changed to returning `MemberInfo` as it's the base class for `MethodBase` and I think would allow `CallerMember` to be more generally useful and work for properties as well.

> Technically true, but it's possible that some of the work could be deferred until runtime.

I would think this wouldn't be desirable due to performance considerations. It also introduces different compile-time behavior between using the attributes directly and using the struct. Then again, it might not be possible to implement `CallerTypeAttribute` and `CallerMemberAttribute` at compile time, not sure about that.

**Comment by HaloFour** [comment]
@scottdorman 

> Do you mean `CallerMemberNameAttribute`?

Oops, you're right.  None of the attributes cover the type at the moment.

> Then again, it might not be possible to implement `CallerTypeAttribute` and `CallerMemberAttribute` at compile time, not sure about that.

I don't see why not.  They're not as simple as expressions as pushing a string literal or an integer literal, but they're still relatively easy.  It's two IL opcodes to derive the `Type` or the `MethodBase` and push it onto the stack, `ldtoken` with the type or method token followed by either `call Type.GetTypeFromHandle` or `call MethodBase.GetMethodFromHandle`.  The former is literally how `typeof(T)` works.  The tokens themselves are deterministic at compile-time.

**Comment by scottdorman** [comment]
@HaloFour `typeof(T)` is a runtime call though, not a compile time literal. Are you saying that the compiler would simply emit the required IL opcodes instead of emitting the literal? I guess the difference is that by emitting the literal value, there is no runtime cost to getting the information (other than just normal parameter access overhead) but there would be slight runtime cost associated with accessing `CallerTypeAttribute` and `CallerMemberAttribute`. Granted, I doubt it's significant enough of an overhead to make much difference, especially since these probably wouldn't have a high amount of access and something could probably be done to cache the call site information, similar to what's done with `dynamic`.

**Comment by HaloFour** [comment]
@scottdorman 

Yes, it would be a runtime call.  The only way to avoid that would be to have those caller-info attributes applied to parameters of type `RuntimeTypeHandle` or `RuntimeMethodHandle` and have the compiler only emit `ldtoken` which is still evaluated at runtime but should be faster.  But all you're doing there is offloading the inevitable to the callee which is going to have to invoke those methods to get something useful anyway.

Either way, this is a *lot* less overhead than what people are doing now to support getting this kind of information which is accepting a `MethodBase` and requiring the caller to call `MethodBase.GetCurrentMethod` manually, or by getting a stack trace in the callee and trying to find the calling method, assuming that the JIT isn't inlining it.

**Comment by scottdorman** [comment]
> Either way, this is a lot less overhead than what people are doing now to support getting this kind of information

Absolutely agree on that! :) Yes, this introduces a small amount of overhead, but significantly less than what's incurred now to get the same information.

**Comment by AdamSpeight2008** [comment]
Another possibility is to do something similar to what we do with strings literals. Have a embedded dictionary lookup table.

**Comment by dotnetchris** [comment]
Building general purpose computing with CallerMemberName is extremely frustrating with the lack of CallerTypeName, leads to all kinds of voodoo required to coerce types from somewhere that you can locate who someone is.

**Comment by dotnetchris** [comment]
@scottdorman `[CallerType]` and `[CallerMember]` would be exactly what I want.

**Comment by sextondjc** [comment]
@dotnetchris same here. Even just the fully qualified caller type name as a parameter attribute would solve a multitude of problems.

**Comment by dotnetchris** [comment]
`[CallerMember]` would be my most preferred but I would completely be able to live with only `[CallerTypeName]`

**Comment by dotnetchris** [comment]
Basically I want more and more tools to be able to write programming to write my programming.

**Comment by Pzixel** [comment]
Can't it be accomplished by #107 ? It can be 3-party nuget package that do this stuff. I'm not sure that we need built-in feature, when we just can write some extensions for Roslyn. Best issue resolution - do nothing.

**Comment by HaloFour** [comment]
@Pzixel 

Not easily.  Source generators are about decorating entire methods and leaving their contents generally unchanged.  To implement caller attributes via source generators would require the generator to rewrite the method body so that it could replace the optional parameters.  It's certainly possible but it requires a bit more effort.  Since caller attributes are already a part of C# and work by piggy-backing off of optional parameters I think that it's worth expanding them to cover more common use cases.

**Comment by 304NotModified** [comment]
Would be great if the "new version" would be backwards and forward compatible. Adding the caller member attributes is now a binary breaking change.

**Comment by yaakov-h** [comment]
@304NotModified How so?

**Comment by Happypig375** [comment]
What is the situation of this proposal? What is left to discuss? I look forward to this proposal.

**Comment by HaloFour** [comment]
@jcouv 

With `CallerArgumentExpressionAttribute` moving forward has there been any form of discussion around further expansion of the caller member attributes as outlined in this proposal?

**Comment by jcouv** [comment]
@HaloFour Good question. It may be worth consider batching some of these, if LDM is supportive.
My sense is that prioritization will be a challenge. But I'll try to get this on LDM agenda.

**Comment by jcouv** [comment]
One more thing, LDM is largely offline until January and I expect the first couple of meetings to focus on blocking  C# 7.3 issues. So it may be mid-Jan until we can discuss this. I'll update here as I hear more.

**Comment by HaloFour** [comment]
@jcouv 

Thanks.  Note that I threw the kitchen sink in there, but this is certainly not an all-or-none proposition.

My primary use case has been within logging/tracing libraries where I'd like a cheap and easy way to figure out the context of the caller.  Currently I'm using `StackTrace` to accomplish this, which ain't cheap and is subject to being inaccurate due to JIT inlining.  And what I currently output is pretty verbose and includes the type name, generic type arguments and parameter types, formatted to be nicely readable, e.g. `Dictionary<int,string>::TryGetValue(int, out string)`

**Comment by dotnetchris** [comment]
`[CallerTypeName]` is critical, everything else is a nice to have.

**Comment by jcouv** [comment]
This was discussed in LDM today (Jan 3rd 2018). See upcoming notes.

**Comment by Pzixel** [comment]
@jcouv do you guys even sleep? It's a NY, just eat some cakes, don't meet until next monday 😋

**Comment by yaakov-h** [comment]
> See upcoming notes.

That's a bit hard at the moment. 😄

**Comment by HaloFour** [comment]
@jcouv 

https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-01-03.md#other-caller-attributes

> We are not comfortable with those just yet. We'd need to work on the details. For now we are suspicious of having a record of a lot of different information, and of the number of proposed ones in #87.

> QOTD: "What about CallerPoliticalAffiliation?".

Understood.  To note, I threw a lot of spaghetti at the wall in this proposal.  I don't intend for all of it to stick.

If you wanted to effectively capture all of the use cases that could be covered here, `CallerMethodAttribute` I believe would give you access to all of the other pieces of information via reflection, e.g. method name, simple type name, full type name, namespace, assembly, etc.

**Comment by TheXenocide** [comment]
At least having access to the full type name would definitely have helped with several diagnostic utilities I've made. I can see the merit of using Type/MemberInfo and would have used them were they available, though given the discussion about runtime evaluation versus compile-time literals, there may be some merit to having string attributes. Do we know why some values were provided with the original feature release where others weren't? I strongly suspect this was included due to increasing reliance on INotifyPropertyChanged with no fully-baked native AOP mechanism (which is something I'd find extremely appealing and could similarly solve this and many other problems abstractly--with a more generally useful range of functionality--though it's likely much easier to implement an analog to compile-time functionality that already exists).

**Comment by dotnetchris** [comment]
@TheXenocide https://github.com/dotnet/csharplang/issues/164 upon completion will give us absolute AOP at every single point in dotnet since you'll be able to proxy any object transparently to the existing receivers.

**Comment by TheXenocide** [comment]
@dotnetchris, I'll have to give that a more thorough read when I have more time, but at first glance while I can see how it solves many types of problems that AOP frameworks tend to target (INotifyPropertyChange, multiple-inheritance stand-ins, type-specific wrappers, etc.), it does not appear to universally solve compile-time instruction enhancement in all the ways and with all the optimizations that existing aspect weavers do (and, especially notably, does not provide compile-time evaluation of programmatic logic to apply aspects; e.g. PostSharp's IAspectProvider). I'm not sure how those shapes/extensions would be used to, say, allow a developer to convert an annotation (like an Attribute applied to any parameter on any method) into a set of conditional logic based on information provided by the caller at compile-time the way these Caller Info Attributes work (I could implement this with PostSharp or Fody today, with some caveats that would be better solved using ASTs/syntax analysis à la Roslyn). I look forward to additional language improvements to help solve cross-cutting concerns, but there are still fundamental AOP concepts not addressed from what I can tell.

**Comment by dotnetchris** [comment]
@TheXenocide right, it's not compile time interception it would be run time interception. 

>  allow a developer to convert an annotation (like an Attribute applied to any parameter on any method)

you would do something like setup a static constructor or use one of the App_Start files etc etc to bootstrap that would do assembly scanning, find all the methods with that attribute. You'd construct some type of dictionary or map of that data. Then at run time you flow your code over the shape and you would do things if the flow hit your map.

Then you would likely combine this with Dependency Injection that you're invisibly injecting your Shape proxies to wherever you want them and they appear to be the traditional type to the receiving sites.

**Comment by TheXenocide** [comment]
Alas, I'm much more interested in compile time aspects than runtime proxies, though I understand how these might be useful.

**Comment by dotnetchris** [comment]
Any news on this?

**Comment by KyleKolpek** [comment]
I would also love an update on this. Particularly `CallerTypeName`.

Also, for my use case it would be important to have the type an Attribute is attributed to, rather than the true caller. This is consistent with [`CallerMemberName`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callermembernameattribute?view=netframework-4.7.2#remarks) behavior (see quote below). I expect this would be the case, but also wanted to make sure it was noted.

> Attribute constructor


> The name of the member to which the attribute is applied. If the attribute is any element within a member (such as a parameter, a return value, or a generic type parameter), this result is the name of the member that's associated with that element.

**Comment by alexsorokoletov** [comment]
+1 for this proposal. CallerTypeName is the thing (as many other pointed), other are less important. Current workaround (getting filename and then deduct type name from the file) is a bit messy.

**Comment by maxfridbe** [comment]
Any news?

**Comment by jcouv** [comment]
> Any news?

Our hands are full with current C# 8 feature set (in particular, nullable reference types and default interface members).

**Comment by abezverkov** [comment]
+1 for CallerType or CallerTypeName.   Just came searching again for the ump-teenth time in case something had changed.

**Comment by georgiuk** [comment]
What about CallerInstanceObject so as to pass the instance of the object that called the Method/Property. In case of static this will be always null.

**Comment by yaakov-h** [comment]
That sounds like a fun can of worms.

**Comment by TheXenocide** [comment]
@georgiuk  Not sure how I feel about CallerInstanceObject; that seems like logic that would generally be more explicit (and not sure how useful it would be as it would probably have to be of type "Object"). The other attributes are strictly metadata, whereas this crosses into the actual data territory. Feels like extension methods are analogous and more appropriate representation.

**Comment by georgiuk** [comment]
Yes, CallerInstanceObject probably is off the limits for this API.   
Another thing I was thinking is if there will be possible to make it more strict. I mean right now a caller can bypass it and pass anything else as parameter. Wouldn't be useful if the compiler disallow passing those parameters explicitly?
Having CallerMethod to discriminate Getter and Setter would also be useful.

**Comment by mikernet** [comment]
This proposal excites me, aside from one issue that I don't think it addresses but I really wish it would, which is shortening chained "fluent" extension methods such as:

```c#
public void DoSomething(string[] values)
{
    values.ThrowIfNull(nameof(values))
        .ThrowIfCountLessThan(1, nameof(values))
        .ThrowIfAnyNullOrWhitespace(nameof(values));

    // do stuff with values
}
```

to this:

```c#
public void DoSomething(string[] values)
{
    values.ThrowIfNull()
        .ThrowIfCountLessThan(1)
        .ThrowIfAnyNullOrWhitespace();

    // do stuff with values
}
```

If I understand this correctly, each of those calls would get the full part of the expression that came before. If I didn't care about performance I could just `Substring()` it on the first dot it finds, but that would be prohibitively expensive for some use cases such as this.

Anyone have a clever solution or amendment to this proposal to b able to achieve this?

**Comment by CodeAngry** [comment]
By 2025 maybe we get this. Because when you design this CallerInfo you add:
- CallerFilePath
- CallerLineNumber
- CallerMemberName
but somehow manage to not even think about the CallerTypeName that has the CallerMemberName, because... who needs that?!

**Another one of those Microsoft moments in API design.** That will be eventually fixed _(to be read: made to work as it should have had since start)_ in a decade.

Who knows, maybe someone comes up with the idea of changing CallerMemberName from `Method` to `ParentNS[.ChildNS].Type.Method`. Insane creativity right here. And then every logging code will actually work properly.

**Comment by TheXenocide** [comment]
@CodeAngry - username checks out...

**Comment by TonyValenti** [comment]
I wanted to post my note for this, especially "CallerMemberType" as a Type (and not a string).
