### ISSUE TITLE
Simplify the initializing of fields and properties

### ISSUE THREAD

**Issue by qaqz111** [dotnet/csharplang#872]
Since you can't use `var` to defined class members, you have to write this:
```C#
class A
{
    private Dictionary<string, Dictionary<string, List<(int count, string desc)>> infos =
        new Dictionary<string, Dictionary<string, List<(int count, string desc)>>(16);

    private List<int> list = new List<int>(16);
}
```
Yes VS can help completing the initialize statements after you input '=', but what if you want to change the type of the member? You have to modify it twice.

It will be simpler if there is a shorthanded way:
```C#
class A
{
    private Dictionary<string, Dictionary<string, List<(int count, string desc)>> infos = new(16);

    private List<int> list = new(16);
}
```

**Comment by svick** [comment]
This looks like duplicate of https://github.com/dotnet/csharplang/issues/100.

**Comment by qaqz111** [comment]
Yes I have not notice that.
Closed.
