### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by qaqz111** [dotnet/csharplang#873]
```C#
private int x;
[Test]
public void Foo()
{
    x = 16;
    x -= Bar(4);
    Console.WriteLine(x); //-> 12
}
private int Bar(int y)
{
    x -= y;
    return y;
}
```
The IL of release compile:
```IL
IL_0000: ldarg.0
IL_0001: ldc.i4.s 16
IL_0003: stfld int32 NUnitTest.Test1::x
IL_0008: ldarg.0
IL_0009: ldarg.0
IL_000a: ldfld int32 NUnitTest.Test1::x //<- old value pushed onto stack
IL_000f: ldarg.0
IL_0010: ldc.i4.4
IL_0011: call instance int32 NUnitTest.Test1::Bar(int32)
IL_0016: sub
IL_0017: stfld int32 NUnitTest.Test1::x
IL_001c: ldarg.0
IL_001d: ldfld int32 NUnitTest.Test1::x
IL_0022: call void [mscorlib]System.Console::WriteLine(int32)
IL_0027: ret
```
The point is `IL_000a`, **current** value of `x` is pushed onto stack, but next call changed the value of `x`, the previous current value becomes **old** value.

**Comment by HaloFour** [comment]
No.

The expression `x -= Bar(4)` actually translates to `x = x - Bar(4)` and the value of `x` is read before `Bar` is invoked.  The value of `x` at that time is 16.  It doesn't matter that `Bar` then proceeds to modify `x` because the value has already been read and will not be read again.  So, when `Bar` returns 4, that is subtracted from the value of `x` before calling `Bar`, which was 16.  Thus, 12.

**Comment by qaqz111** [comment]
Yes it is, you're right.

**Comment by jnm2** [comment]
However in C++ if you change `x -= bar(4);` to `x = x - bar(4);`, it prints 12 rather than 8.

**Comment by jnm2** [comment]
Since IL is stack-based, a new local would have to be introduced in order to evaluate `Bar(4)` before reading `x` to calculate `x - Bar(4)`. This results in less efficient code. I wouldn't be surprised if it breaks some people in super subtle ways.

**Comment by qaqz111** [comment]
But I still got 8 after change `x -= bar(4);` to `x = x - bar(4);` in VS2017.

I tried java and js, they also give the result of `12`.

Looks like it is a designed difference between C/C++ and these languages. I'm going to remember this. It was often got confused with these differences since previously worked with C++ a lot.

**Comment by jnm2** [comment]
C: https://ideone.com/yhyJr5
C++: https://ideone.com/SLj6J5

**Comment by jnm2** [comment]
You're right, VS2017's C++ compiler does return 8, unlike ideone which probably uses gcc.

In general, I try not to write code that is dependent on arcane details like this. :D

**Comment by qaqz111** [comment]
Looks like msvc is different from clang/gcc at this detail.

I tried Release/Debug, set project compile code as C/C++, all of them give result of 8.
