### ISSUE TITLE
Discussion：Solution-based macros needed

### ISSUE THREAD

**Issue by MaleDong** [dotnet/csharplang#876]
Until now in VS, we only have project-based macros, and you can imagine it won't be an easy thing to define macros or remove some of them and do changes for different kinds of publish versions. Imagine if you have many libraries with one executable main program, and some methods of libraries are published ONLY WHEN YOU HAVE THE MACRO OF "PRODUCT", while some published for "FREE"……. (depending on different kinds of conditions globally). Now I have to define these macros step-by-step one by one in "Project"=>"Build"=>"Conditional Compiler Symbol" ,and do removing one by one for different kinds of versions....

In fact there should be a nicer way (something like C++ maybe). I mean we can create some rules or ways to define a globally-based (Solution-based) macros. And all of the solution's files (*.cs) can share the macro and treat them as "pre-defined". This means you don't need to re-define duplicated macros.

A typical example is that suppose I have several C# libraries with one executable Console app, and I have to define duplicated macros in as many as projects I have now. And for different kinds of version publishments, I need to carefully remove some macros or do something else and recompile, which is complicated and easy to make mistakes. Because these macros are managed unitedly belonging to the same solution. Why don't we have a globally-based macro mechanism (of course rules will be defined later after discussion).

**Comment by HaloFour** [comment]
I think that this belongs in the [Roslyn](https://github.com/dotnet/roslyn/issues) repo rather than here since it involves tooling and not modifications to the C# syntax.

**Comment by jnm2** [comment]
@MaleDong Easy solution I'd suggest is a `Common.props` file next to the solution file:

```xml
<Project>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);FOO</DefineConstants>
  </PropertyGroup>

</Project>
```
Then in each .csproj:

```xml
  <Import Project="..\SharedAssemblyInfo.props" />
```

**Comment by MaleDong** [comment]
@HaloFour : Thanks! 

In fact I tend to have a new creator of a file (something called "Global Macros"), where I can define solution-based macros. (The idea is very similar to @jnm2 ).

And I'm not sure whether we have special things in C# or VB.net for macros, so I temporarily put it here. And if you think it's a wrong place. Well……Can I move my thread to Roslyn or would you lend me hand to cope with that?

**Comment by eyalsk** [comment]
@MaleDong You can't really move it there but you can just close the issue here and create a new one over there. :)

**Comment by MaleDong** [comment]
Thanks! I'll close that:)
