### ISSUE TITLE
Discussion: consider target-type when the compiler can't determine the type of a ternary

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#877]
Currently, C# requires either of operands in a ternary to be convertible to one another, e.g.
```cs
void M(C2 a, C3 b, bool c)
{
  C1 x = c ? a : b; // ERROR
  C1 y = c ? b : a; // ERROR
}
class C1 {}
class C2 : C1 {}
class C3 : C1 {}
```
But in the above example the compiler could consider the target-type `C1` for the conditional expression instead of requiring a cast on either of operands.

Note that the proposal https://github.com/dotnet/csharplang/issues/33 has been limited to nullables so that's not an alternative here. 

Other constructs that can be target-typed: 

- `??` operator: `SyntaxNode x = expression ?? statement;`.
- `switch` expressions: `Size size = e switch { p1 => new(1, 2), p2 => new(3, 4) };`

**Comment by vladd** [comment]
This way, the behaviour will be inconsistent, as the target type is available for assignment LHS but not for arbitrary expressions.

    C1 x = c ? a : b;
    string s = x.ToString();

would work whereas

    string s = (c ? a : b).ToString();

would not.

**Comment by DavidArno** [comment]
@vladd,
Whereas:
```cs
string s = ((c ? a : b) as C1).ToString();
```
would work. That would overcome any inconsistency.

**Comment by alrz** [comment]
Note: `as` doesn't do target typing, it tries to "convert" the expression to that type. e.g `(null, null) as (C, C)?` is an error whereas a direct cast works. null/default is a special case though.

**Comment by alrz** [comment]
@vladd The ternary in `(c ? a : b).ToString();` does not have a type or target-type, so you should either cast it to `C1` or have it to produce a "most specific type" which is what intersection types are about and they are relatively costly in implementation as they require clr changes.

**Comment by DavidArno** [comment]
@alrz, nor does `=` do target typing. So maybe I should have said that by using `as`, it *could* do the same type inference as you propose in the OP.

**Comment by vladd** [comment]
@alrz If I understand correctly, in C# pretty much every expression (with exception of method groups/lambdas and `null` literal) has its intrinsic type. This allows for the logic "for any expression, we can get the types of its constituent parts, and deduce the type of the expression itself".

The way you are proposing breaks this logic, as the conditional expression would need to know the _outer_ type in order to infer the inner types. This raises the question: where should be the border between top-to-bottom and bottom-to-top type inference?

**Comment by alrz** [comment]
Target-typing is a well-defined concept in the language. ternary itself does apply it to either of operands that does not have a type, e.g. `c ? obj : default`. I'm just suggesting we apply it to both operands if they are not implicitly convertible to each other.

**Comment by vladd** [comment]
@alrz I see your point. Till now typeless (or top-to-bottom-typed) expressions were either _simple_ expressions like `null` or `default`, or lambdas. Now, either of the alternatives in the conditional expression can be another conditional expression, so this means that type inference must be propagated down the tree, right? So this is more like lambda case, not like `null` case.

**Comment by alrz** [comment]
Another use case from: https://github.com/dotnet/corefxlab/pull/1742#discussion_r137580133

> 
> ```cs
> Span<byte> buffer = size < 128 ? stackalloc byte[size] : new byte[size];
> ```

**Comment by HaloFour** [comment]
@alrz 

Does that imply that the language team is also relaxing the restrictions on the use of `stackalloc`?  Currently it can't be used in expressions at all.

**Comment by alrz** [comment]
@HaloFour Relevant PR: https://github.com/dotnet/roslyn/pull/22162, being used over here: https://github.com/dotnet/corefxlab/pull/1742

**Comment by alrz** [comment]
Well, that example just works with dotnet/roslyn#22162 in place. so not related here.

**Comment by alrz** [comment]
As of 7.2 natural type of `stackalloc` depends on it being directly in a local declaration initialization, that means a pair of parentheses could change the type of the expression,
```cs
var x = stackalloc int[int]; // x is int*
var x = (stackalloc int[int]); // x is Span<int>
```
As mentioned in https://github.com/dotnet/roslyn/pull/22162 the main motivation was to make casts unnecessary, for example, in a ternary like this:
```cs
Span<byte> buffer = size < 128 ? stackalloc byte[size] : new byte[size];
```
That's the only place that casts would have to be present without this rule, otherwise we have an implicit conversion from stackalloc to Span, so no cast is necessary in all other places.

This proposal could have the same effect without changing natural type of `stackalloc`, at the cost of the target type being mandatory.

Note: there is already a request to make that an analyzer https://github.com/dotnet/roslyn/issues/22411

I wonder how badly this could be confusing right now that warrants to take a breaking change and fix it.

**Comment by alrz** [comment]
Closing in favor of championed issue #2460
