### ISSUE TITLE
Using alias directive and ValueTuples

### ISSUE THREAD

**Issue by cameron-elliott** [dotnet/csharplang#879]
This may well be by design, but as a user of C# 7, it seems odd
that it is possible to use the 'naming' value tuple syntax as subtypes of using aliases,
but it is not possible to directly use 'naming' value tuples.

example:
using AA = System.ValueTuple<int, int>;
using BB = System.Nullable<(int, int)>;
using CC = System.Func<int, (bool tag1, int tag2)>;
using DD = (int,int);

The first three are all valid per Roslyn, but the fourth is not.

**Comment by jnm2** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/423.

**Comment by cameron-elliott** [comment]
Sorry for duplicate
