### ISSUE TITLE
Seeming contradiction

### ISSUE THREAD

**Issue by myieye** [dotnet/csharplang#8883]
### Type of issue

Typo

### Description

These two statements appear to contradict each other. Does an object of type `System.Threading.Lock` get "special-cased" or is it "tested as any other object"?

A.
> The presence of the lock keyword in C# might lead developers to think they can use it with this new type. Doing so wouldn't lock according to the semantics of this type but would instead **treat it as any other object**

B.
> Semantics of the lock statement **are changed to special-case** the System.Threading.Lock

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-13.0/lock-object

### Content source URL

https://github.com/dotnet/csharplang/blob/main/proposals/csharp-13.0/lock-object.md

**Comment by 333fred** [comment]
These are two separate sections. The first is the motivation for the feature, in that we want lock to work. The second describes how we accomplish that.

**Comment by jnm2** [comment]
In other words, "A" is describing what would be the case if the proposal was not done, and "B" is describing the proposed change, so there is no contradiction.
