### ISSUE TITLE
Proposal: Support "raw" string literals

### ISSUE THREAD

**Issue by HaloFour** [dotnet/csharplang#89]
Copied from https://github.com/dotnet/roslyn/issues/2239

## Problem:

Verbatim string literals are often used to copy in chunks of text such as SQL or XML.  It's not uncommon for this text to contain embedded double-quotes, which then must be doubled-up in C# in order to be escaped.  This makes it obnoxious if you have to copy and paste the text back and forth since it would have to be fixed each time.

``` cs
string xml = @"<?xml version=""1.0""?>
<root>
    <item attr=""foo"" />
</root>";
```
## Solution:

By supporting a custom notation for starting and ending a string literal it enables evaluating the double quotes as part of the string that do not have to be escaped.  The programmer would use a pattern at the beginning of the string which then must be matched to denote the end of the string.

Proposed syntax would be based on verbatim string syntax:

_raw-string-literal_:
    @("   _raw-string-literal-characters_ <sup>opt</sup>   " )
    @( _identifier_ "   _raw-string-literal-characters_ <sup>opt</sup>   " _identifier_ )

_raw-string-literal-characters_:
    Any characters except " _identifer_ <sup>opt</sup> )

The `@` would be immediately followed by an open-parenthesis (`(`).  Following that is an optional delimiter which is any legal C# identifier and then a double-quote.  Next would be the raw string contents which would be interpreted exactly as they appear in the file.  The terminator of the string literal would be a double quote immediately followed by the optional delimiter and a close-parenthesis (`)`).

The following example is a raw string without a custom delimiter.  It is terminated simply by the sequence `")`.  Double quotes that appear within the string are interpreted as a part of the string as long as they are not followed by a close-parenthesis character (`)`).

``` cs
string xml = @("<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>");
```

The following example is a raw string with a custom delimiter.  As the custom delimiter is specified as "foo" that sets the terminating sequence to be `"foo)`.  Any other characters are interpreted as a part of the string literal, including any portion of the terminating sequence.  Note that the term "foo" appears within the string after a double-quote, but since it is not also followed by a close-parenthesis (`)`) it is not considered the terminating sequence of the literal.

In this example the custom delimiter is "foo".  Note that the attribute value is not considered as the end of the string.  However, if it was followed by a parenthesis it would be and a different custom delimiter might have to be chosen.

``` cs
string xml = @(foo"<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>"foo);
```

Here are examples of raw strings containing the syntax for other raw strings:

``` cs
string raw1 = @(foo"string s = @("Hello!");"foo);
string raw2 = @(bar"string raw1 = @("string s = @("Hello!");"foo);"bar);
string raw3 = @(baz"string raw2 = @(bar"string raw1 = @("string s = @("Hello!");"foo);"bar);"baz);
```

This syntax is loosely based on C++11 raw string literals, although I personally don't care for the parenthesis or delimiter appearing within the body of the string.  I'm definitely not married to this syntax and variations are welcome.

Existing UserVoice suggestion, using C++11-like syntax:  [Allow to have custom delimiters in raw string literal](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/5678481-allow-to-have-custom-delimiters-in-raw-string-lite)

**Comment by scottdorman** [comment]
I like this, although I'm not sure about the syntax. It seems similar in nature to VB.NET's XML literals.

**Comment by HaloFour** [comment]
@scottdorman 

The syntax is largely borrowed from C++ with some tweaks.  C++ raw strings look like this:

```cpp
const char* xml = R"foo(<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>)foo";
```

My personal opinion is that it's bizarre that the raw string termination identifier appears within the string.

While containing unescaped XML would certainly be a goal I wouldn't want to limit these strings to any specific form of content, such as HTML, SQL or JSON each of which has similar issues.

**Comment by scottdorman** [comment]
@HaloFour 

> While containing unescaped XML would certainly be a goal I wouldn't want to limit these strings to any specific form of content, such as HTML, SQL or JSON each of which has similar issues.

Absolutely. I was really just mentioning that this is similar in nature to VB's XML literals, but those literals don't require any special delimiters or structuring.

What about something like this:

```c#
string xml = @("foo(<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>")@;
```

So it's the pair of `@(` and `)@` symbols that denote the start and end of the string literal? It's not quite as simple as the C++ syntax but I think using a pair of symbols keeps it from being ambiguous and keeps the delimiters consistent (which would better enable/allow code analysis).

**Comment by HaloFour** [comment]
@scottdorman 

My proposal covers that syntax.  But that would mean that the sequence `")@` becomes a special sequence that would require some form of escaping otherwise it would terminate the string.  That's the purpose of the optional identifier, it establishes the termination sequence.

Note that the following two examples would produce the exact same string, the same string produced by the C++ example:

```cs
string xml1 = @("<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>");

string xml2 = @(foo"<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>"foo);
```

That `foo` within the parenthesis doesn't exist within the string.

**Comment by DavidArno** [comment]
With the example:
````cs
string xml = @(foo"<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>"foo);
````
You appear to be making the job of the compiler harder than it need be as, upon arriving at `<item attr="foo`, it has to check if the next token is `)` to see if the end of the string has been reached or not. I'd therefore think it easier if the above were viewed as a compilation error (as there is a `"` following `"foo` ) and to make it necessary to use a custom delimiter that doesn't appear in the string:
````cs
string xml = @(bar"<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>"bar);
````

**Comment by orthoxerox** [comment]
Why not use [here documents](https://en.wikipedia.org/wiki/Here_document) for that? Instead of a new delimiter you could use any custom delimiter that doesn't appear in the string. Something like:

```c#
string xml = @@bar
<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>
bar;
```

**Comment by HaloFour** [comment]
@DavidArno

I think having to ensure that the string can never contain the delimiter would make it harder on the developer than it should need to be.  If you're copying/pasting a relatively large blob of formatted text you wouldn't want to have to scan the entire text to find out what would be a legal delimiter.  That parsing requirement is exactly what has been imposed on C++ and it doesn't seem to have any issues with it.  Also seems to be the common theme with heredocs.

@orthoxerox

Can't say I'm a fan of a string format that doesn't use double-quotes or is whitespace sensitive.  I see that D has a syntax that is somewhat between other heredocs and C++ raw strings by using a `q` prefix, double-quotes and an identifier immediately followed by a newline:

```d
string xml = q"foo
<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>
foo";
```

Of the heredoc syntax I'd probably prefer something along those lines the best:

```cs
string xml = @@"foo
<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>
foo";
```

**Comment by HaloFour** [comment]
@CyrusNajmabadi has [suggested a different string literal syntax](https://github.com/dotnet/csharplang/issues/371#issuecomment-354710829).  It's not quite "raw" strings since there is still an escape sequence involved but the goal is to solve similar issues in avoiding having to use escape sequences:

> ```cs
> @ <any-punc> contents <original-punc>
> ```
> 
> Within these strings, the only thing you'd have to escape would be the starting punc char

That would allow the following to be string literals:

```cs
var s1 = @`This is a string that contains a double quote:  "  `;

// with an escape sequence
var s2 = @`This is a string that contains a double quote: " and a backtick: `` `;

// change char to no longer need escape sequence
var s3 = @-This is a string that contains a double quote: "  and a backtick: ` -;
```

One advantage to this syntax is that it would allow interpolation:

```cs
var name = "Cyrus";
var json = $@`{{ "name": "{name}" }}`;
```

Which could potentially also be supported in my proposed syntax:

```cs
var name = "Halo";
var json = $@("{{ "name": "{name}" }}");
```

Although in both cases it is a tad awkward since you have to escape the curly brackets.

So between the two the major differences are:

1. Use of identifiers v. punctuation as terminators.
    1. What are the limits as to what punctation is supported?
1. Ability to use sequences of multiple characters as terminators.

**Comment by vladd** [comment]
I'd like to additionally propose Swift-like handling of the initial white space: if we have multiline raw literal, we want to allow ignored spaces at the beginning of each line. Swift [resolves this](https://github.com/apple/swift-evolution/blob/master/proposals/0168-multi-line-string-literals.md) in the following way:

> To allow free formatting of the literal an indentation stripping operation is applied whereby any whitespace characters in front of the closing delimiter are removed from each of the lines in the literal.

**Comment by alrz** [comment]
>var json = $@`{{ "name": "{name}" }}`;

If you need to escape all  braces, this is no longer a "raw string". probably it's better to escape interpolations instead.

**Comment by HaloFour** [comment]
@alrz 

Agreed.  I honestly don't care for trying to make interpolation and "raw" strings work.  You still end up having to escape something.

The same is true in Swift.  You still have to escape `"` if it appears in a triplet, and you still have to escape `\(` because the language supports interpolation.

**Comment by orthoxerox** [comment]
I think strings with custom delimiters would need custom interpolators, too. Something like: ```var json = $~@`{"name": "~name~"}`;```. This way you would be able to use them for almost any raw data.

**Comment by alrz** [comment]
doesn't have to be a different character,
```
var json = $`{ name: `{name}` }`;
```
so the interpolation is started via `<punc>{`

also I don't think `@` is needed, this is a raw string so `@` is implied.

**Comment by michael-hawker** [comment]
I feel like Python has solved this pretty eloquently with their [triple quoted strings](https://docs.python.org/3/library/stdtypes.html?highlight=string%20literal#text-sequence-type-str) and support for both `'` and `"` to define strings, as JavaScript provides too.

     var mystring = """Some text
     with a newline and "quotes" is here""";

I can't think of a time where I ran into a problem trying to store something with this approach.

**Comment by cryxia** [comment]
I'd like to weigh in with what I've seen in perl for their regular expressions:
```perl
var a =~ m/match/;
var a =~ m#match#;
```
A similar thing exists in sed:
```
s/a/b/
s#a#b#
```

As you can see, the char after the command denotes the delimiter in the regex. If we look at the c# literal syntax:

```c#
var foo = @"some string";
```

Then perhaps we can just consider the first char after the @ symbol to denote the final delimiter
```c#
var foo = @|some string with "quotes"|;
```
This pattern works because the parser treats everything between the identifer verbatimly, even whitespace and newlines:
```c#
var foo = @"some string
with new lines
that ends in a quote";
```
so for the new way:
```c#
var foo = @%some string
with new lines and "quotes"
that ends here%;
```

Granted, this syntax might look weird to anyone not used to it. I'm also not sure how well this would go with interpolated strings:
```c#
var foo = @$#some string {a.Bar}#;
```

**Comment by gafter** [comment]
> Is there any progress on this?

No, there is no progress on this.

**Comment by Gnbrkm41** [comment]
It'd be useful for cases like regex patterns, where double quotes has to be escaped regardless of regular literals (`\"`) or verbatim literals (`""`).

I was thinking of something like `@@"some strings here"`, where only the outermost pair of double quotes are considered and the contents are always escaped; can't tell if it's possible, nor a good idea though.

**Comment by canton7** [comment]
> where only the outermost pair of double quotes are considered

How would you do this, in practice? How do you know which double quote is the "outermost"?

**Comment by Gnbrkm41** [comment]
@canton7, hence 'can't tell if it's possible'. :^)

**Comment by canton7** [comment]
(I'm pretty sure it's impossible - that's why I asked)

**Comment by Thaina** [comment]
+1

Today I am frustrate with writing json. The wellformed json object required us to write `"` everywhere. Ability to make a block that could write raw string with `"` character is really precious convenient

Also one option I would like to add is, allow context sensitive for `''`. I mean just let compiler determined `'Any text with length 2 or more. may contain " character'` as `string` instead of `char` should be possible. It will be `char` if inside `''` is a single character

**Comment by ajdust** [comment]
Has there been any progress on this idea?

C# is lagging behind in this regard. Nearly every mainstream programming language except C# has this feature in some form or another. I know there's more to it, but just being able to use a different string delimiter so I don't have to `@""""` `"\""` escape quotes would be nice.

Here is a reference for the way those other programming languages handle this:

| Language | Summary |
| --- | --- |
| Java | [Triple quotes](https://openjdk.java.net/jeps/355) |
| Python | [Triple quotes](https://docs.python.org/3/tutorial/introduction.html#strings) |
| JavaScript | [Backtick](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) |
| Go | [Backtick](https://golang.org/ref/spec#String_literals) |
| C++ | [Customizable delimiter](https://docs.microsoft.com/en-us/cpp/cpp/string-and-character-literals-cpp?view=vs-2019) |
| PHP | [Here doc](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) |
| Ruby | [Here doc or Q%](https://docs.ruby-lang.org/en/2.0.0/syntax/literals_rdoc.html#label-Strings) |
| PowerShell | [Here-string @' delimiter](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-6#here-strings) |
| Rust | [r# delimiter](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals) |
| Scala | [Triple quotes](https://docs.scala-lang.org/overviews/quasiquotes/intro.html) |
| Kotlin | [Triple quotes](https://kotlinlang.org/docs/reference/basic-types.html#strings) |
| Swift | [Triple quotes](https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html) |
| F# | [Triple quotes](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/strings) |

Java has a fairly considered implementation coming in JDK 13 which seems very reasonable. [Here is a recent talk by Brian Goetz talking about it.](https://youtu.be/GAa54jXKbn4?t=1426).

**Comment by Tragen** [comment]
I wish this would come soon.
I like the flexibility in PHP and the new Java implementation is also good.
I love the flexibility with intenting strings depending on the end string.
This makes copy paste much easier. SQL, C# Code, JSON, HTML aso.
Also having the flexibility to enter your own text in PHP is great.

**Comment by robertsundstrom** [comment]
JavaScript uses ``` ` ```  for raw strings and template strings.

Java has adopted the same syntax.

```csharp
string xml = `<?xml version="1.0"?>
<root>
    <item attr="foo" />
</root>`;
```

Of course, placeholders should be supported.

**Comment by michael-hawker** [comment]
@robertsundstrom backtick is being used quite a bit in Markdown these days, so I'd still vote for **triple-quote**. 

Especially seeing from @ajdust's table [here](https://github.com/dotnet/csharplang/issues/89#issuecomment-558347061) that a majority of main-stream languages (including **F#**, **Swift**, and **Kotlin**) have also picked that as their syntax.

**Comment by HaloFour** [comment]
@michael-hawker 

The majority of the features referenced in that table are not raw strings, they are multiline string literals.  Almost all of them support some flavor of escape sequence or templating and thus require additional escaping, which is what I'm trying to avoid.  I don't want to have to duplicate `\` anymore than I have to duplicate `"`.

That's why I like about the C++ approach, everything between the delimiters is considered completely raw and included verbatim in the resulting literal, including newlines and all punctuation.  And the ability to include a custom delimiter means being able to avoid any special sequence that may already exist within the string.  The C++-based proposal allows you to paste the code for a raw string verbatim within a raw string.  That's not possible with most of the other referenced implementations.

**Comment by michael-hawker** [comment]
@HaloFour I agree, It's not worth adding this syntax if we still have to escape everything. Most of my experience with triple-quotes (Python) still don't need to be escaped. I see this working just like the [F# docs state](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/strings#triple-quoted-strings):

> In this case, all escape sequences are ignored, including double quotation mark characters.

**Comment by HaloFour** [comment]
@michael-hawker 

Except for `\` before a newline.  A lot of languages with `"""`-style multiline literals treats that as a continuation character and omit the newline, including F#, Python and Swift.

**Comment by Tragen** [comment]
I think that \ before newline should be ignored. The string should be as is.
For me, the intenting is also important so you can move the whole block to align with the rest of the code and you have the spaces before truncated like in Java.

**Comment by ajdust** [comment]
Recently announced, C# is getting a (in preview) [compiler feature called "Source Generators"](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/). Using this, one of the things you might find yourself doing is writing C# in C# strings. Proper (flexible) raw strings would make this easier.

### C#

Say I wanted to code-generate a string with the value `The foo says "C:\bar"`, so I have
```csharp
var inside = @"The foo says ""C:\bar""";
```

With current syntax that would be this. Not ideal. So much frustrating `""`.
```csharp
var outside = @"
	var inside = @""The foo says """"C:\bar"""""";
";
```

### Rust

Consider Rust's `r#"..."#` raw string syntax. Note the inside is now readable verbatim C#.
```
var outside = r#"
    var inside = @"The foo says ""C:\bar""";
"#;
```

Of course, instead of `@"The foo says ""C:\bar"""`, the inside could use the raw syntax too `r#"The foo says "C:\bar""#`. Just use two `#` for the outside delimiter. Easy.
```
var outside = r##"
    var inside = r#"The foo says "C:\bar""#;
"##;
```

### R

Consider R's raw string syntax (as of 4.0, note this syntax is very similar to that of C++). In R I can declare a string `inside` without escaping quotes. Here the delimiters are `r"(` and `)"`.
```R
inside = r"(The foo says "C:\bar")"
```

Then I can wrap that code in another string, just add `-` as needed. Three here, why not. So the delimiters are `r"---(` and `)---"`. Again I can copy paste code, including a raw string itself, inside another raw string with ease.
```R
outside = r"---( inside = r"(The foo says "C:\bar")" )---"
```

### Heredoc

Heredoc also works, as in PHP, Ruby, Perl, shell. Here's valid PHP, with an OUTSIDE heredoc string containing an INSIDE heredoc string. However, note the need to escape `$v` -> `\$v` and recognized escapes like `\n` -> `\\n`.

```php
$outside = <<<OUTSIDE
\$inside = <<<INSIDE
    The foo says "C:\bar"
INSIDE;
OUTSIDE;

print("Outside:\n$outside\n\n");
eval($outside);
print("Inside:\n$inside");
```
Prints:
```
Outside:
$inside = <<<INSIDE
    The foo says "C:\bar"
INSIDE;

Inside:
    The foo says "C:\bar"
```

**Comment by surfsky** [comment]
I prefer to triple-backtick(```) for these reasons:

- It is barely used  in program codes.
- It has no chaos with ' and '' and ', and need barely escape char.
- It is simple, and has good visualization and well-recognized.
- It is adopted by dart and markdown.

For example:

``` csharp
var txt = ```
            string with ' and '' and `
            string with expression: ${a + b} ;
            string with multiline text
          ```;
```

Triple-quote is a sub-choice which has little chaos with ".

``` csharp
var txt = """
            string with ' and '' and `
            string with expression: ${a + b} ;
            string with multiline text
          """;
```


Wish any progress on this issue. It's a old issue for so long time.

**Comment by simonpbond** [comment]
Any updates on this? 

Being able to use double quotes in a string is such a required feature, especially when having to work with other database platforms (out of our control) such as Postgres as a .NET Developer. (Postgres requires double quotes otherwise `TableName` or `ColumnName` will be transformed to `tablename` or `columnname` and therefore not exist.) 

Plus as everyone else has mentioned, copying Json etc.

**Comment by ZacharyPatten** [comment]
This might be a terrible idea...

But what if instead of trying all these tricks to force the string into a C# file, we just included a new keyword that would pull in a file as a raw string?

`string myString = fileToString("my file.xml");`

Then IDE's could add previews of that file on-line similar to how you can preview the "Go To Definition" in VS.

Also, because the file would have an extension on it, it could be syntax colored relatively.

Rather than shoving strings into C# syntax, why not pull them in via keyword at compile time?

**Comment by HaloFour** [comment]
@ZacharyPatten 

> But what if instead of trying all these tricks to force the string into a C# file, we just included a new keyword that would pull in a file as a raw string?

You can already use resources to accomplish something similar.  But that moves the content into another file that you have to navigate to in order to view the string.

At this point most languages aside from C# seem to have added this feature, including C++ and Java.  Its inclusion would be far from controversial.

**Comment by ZacharyPatten** [comment]
Why does the string need to be in the same file so bad if you can get the exact same functionality (or likely better considering you will have the extension of the file to color) from a file-to-string keyword?

> You can already use resources to accomplish something similar. But that moves the content into another file that you have to navigate to in order to view the string.

As mentioned, IDEs could be made to treat this as if it were in-line while you are developing by simply having the file of the string open right below it. Example:

![image001](https://user-images.githubusercontent.com/3385986/91572929-c6136900-e914-11ea-8892-1bf83f00f9e7.png)

> At this point most languages aside from C# seem to have added this feature, including C++ and Java. Its inclusion would be far from controversial.

Just because they do doesn't mean it is proper for C#. If a file-to-string keyword existed I would personally never use the feature of this issue. There is no reason both couldn't exist though if people wanted choices though.

**Comment by HaloFour** [comment]
@ZacharyPatten 

There's plenty of content in the 5-10 LOC range where splitting it into a separate file makes little sense and only makes it more difficult to track what is going on.  Think SQL statements and the like.  People do this already using C#'s verbatim strings, but you have to manually deal with escaping any quotes that might exist within the string.  That's why this feature has been added to so many languages.  C++ and Java have identical concerns to C# in this area.

Yes, tooling could improve that experience within the IDE, but it doesn't improve the situation in source control where a reviewer now has to manually bounce between completely separate parts of the PR to determine what is going on.

**Comment by ZacharyPatten** [comment]
I fail to see how having SQL in seperate files would make it harder to track. In my opinion it would make it easier. If you see a `.sql` file you know it is SQL; if you see `.cs` you don't immediately know if that has nested SQL inside it. Having seperate files for seperate languages is actually better organization in my opinion.

**Comment by HaloFour** [comment]
@ZacharyPatten 

Well we'll have to agree to disagree.  Having tons of little `.sql` or `.json` files strewn around the project to contain little bits of other languages to be used in C# is a nightmare to track and follow.  Especially in integration tests where you might have to mock and compare multiple JSON chunks for a single test.  In my current Java project we used to have dozens of separate JSON files for a single integration test suite and it was an awful experience.  We've since moved them all to text blocks and it's an infinitely better experience.  We've always followed this approach with our python tests.  There's a reason so many languages have adopted this functionality, the alternative is objectively terrible.

**Comment by simonpbond** [comment]
@ZacharyPatten Personally I would prefer my SQL to remain inside my function (and typically the only function it relates to), otherwise it feels similar to breaking up functions into their own files. The SQL execution and the SQL query go hand in hand in my view. As far as feeling the actual frustration, try using Postgres as a database with .NET (or as a custom store for Identity Framework) you will feel the pain! : [Here is an example from a Microsoft MVP on the issue](https://andrewlock.net/customising-asp-net-core-identity-ef-core-naming-conventions-for-postgresql/). Not to say this should be the only reason for such a change, but I don't see the downside to it.

**Comment by simonpbond** [comment]
@ZacharyPatten Just to add, I see nothing wrong with your idea also, we are probably just seeing it from a different use case.

**Comment by HaloFour** [comment]
@ZacharyPatten 

I'd also suggest that if you wanted to organize those files separately but not have to deal with loading them as files or as resources at runtime that a source generator would probably be a decent solution.  You'd define a partial class annotated with an attribute with the directory and file pattern and the generator could embed the contents of each file as a string member or constant.   That'd probably work better than the approach with project resource files today (where the tooling is not well suited to multiline content).  But it still leaves the content as separate files.

To each their own.  I know from my experience that people are already using verbatim strings to embed this content into their source.  It works alright but requires escaping double quotes and doesn't round-trip particularly well.
