### ISSUE TITLE
Suggestion: Allow ; After this/base on Constructors

### ISSUE THREAD

**Issue by jeme** [dotnet/csharplang#906]
I know this is a super small thing, and as such, I would only suggest this if the effort to support this is equally small.

When dealing with overloaded constructors or calls to base constructors I am getting a bit tired of the needed `{ }` so I would like to get rid of those and just allow ending such a call with `;` or something else.

Generally:
```CSharp
public MyClass() 
  : this(new DefaultFoo(), new DefaultFox())
{
}

public MyClass(IFox fox) 
  : this(new DefaultFoo(), fox)
{
}

public MyClass(IFoo foo) 
  : this(foo, new DefaultFox())
{
}

public MyClass(IFoo foo, IFox fox) 
{
  this.foo = foo;
  this.fox = fox;
}
```

Would become:
```CSharp
public MyClass() 
  : this(new DefaultFoo(), new DefaultFox());

public MyClass(IFox fox) 
  : this(new DefaultFoo(), fox);

public MyClass(IFoo foo) 
  : this(foo, new DefaultFox());

public MyClass(IFoo foo, IFox fox) 
{
  this.foo = foo;
  this.fox = fox;
}
```

I know it's just a single character we save. But if it is an easy fix then why not?

**Comment by DavidArno** [comment]
Duplicate of #860.

**Comment by jeme** [comment]
Indeed, I tried to see if it was already suggested but clearly I should have searched for ctor and not constructor, lets close this one then.

**Comment by DavidArno** [comment]
😆 Searching can be hard here. I have the unfair advantage over you of having been involved in that previous discussion and found it via a link from one of my own earlier suggestions. Such dupes though help show the team that this little feature is something many of us want, so it's still good you posted.
