### ISSUE TITLE
'Extract method' refactoring breaks compilation

### ISSUE THREAD

**Issue by TessenR** [dotnet/csharplang#910]
**Steps to reproduce:**

```cs
class C
{
  public static void Main()
  {
    void Local() { }
    Local(); // invoke 'extract method' over this statement
  }
}
```

**Expected result:**
The refactoring is not available

**Actual result:**
Roslyn executes the refactoring and breaks compilation:
```cs
class C
{
  public static void Main()
  {
    void Local() { }
    NewMethod();
  }

  private static void NewMethod()
  {
    Local();
  }
}
```

**Comment by jnm2** [comment]
Curious, what did you expect it to do?
If the only other option is to fail to do anything at all, it's actually better to go ahead and produce noncompiling code. People often use code fixes to get a head start on the manual changes they know they'll have to make to finish refactoring it.

**Comment by TessenR** [comment]
@jnm2 

Refactorings aren't supposed to break code.  I expect that refactorings either don't break code or warn me before breaking it. I think that a warning would be better but currently Roslyn just doesn't offer refactorings which breaks code.

Consider the following example:
```cs
class C
{
  public void Test()
  {
    var x = new {A = 1};
    Console.WriteLine(1); // 'extract method' is available here
    Console.WriteLine(x.A); // but not here
  }
}
```

The same refactoring isn't available in the second case exactly because there is no typesafe way to pass an anonymous type into the extracted method. Note that it's unavailable and doesn't produce broken code.

**Comment by TessenR** [comment]
Also, it looks like just having either a local function declaration or a local function usage in the extracted code breaks extract method in various ways
```cs
  public void Test()
  {
    int x = 0;
    // extract the two lines below
    void Local() { }
    Console.WriteLine(x);
  }
```

Actual result:
```cs
  private static void NewMethod()
  {
    void Local() { }
    Console.WriteLine(x);
  }
```

Expected result:
```cs
  private static void NewMethod(int x)
  {
    void Local() { }
    Console.WriteLine(x);
  }
```

If I extract just the last line it works, but if I also extract the local function declaration the parameter is lost.

**Comment by jnm2** [comment]
Ah- also this belongs over at dotnet/roslyn.

**Comment by jnm2** [comment]
> >  it's actually better to go ahead and produce noncompiling code
> 
> Refactorings aren't supposed to break code.

@CyrusNajmabadi I believe you were the one that changed my mind on this. Am I remembering correctly?

**Comment by jnm2** [comment]
In any case, this seems to be a consistent theme:

> In any case, our general design is NOT to block refactorings like this. Once users know about them, they often want to do the refactoring even if it temporarily introduces a problem, because it's still a shortcut on the way to their final destination.

https://github.com/dotnet/roslyn/issues/18504#issuecomment-292323119
https://github.com/dotnet/roslyn/issues/20298#issuecomment-309338086
https://github.com/dotnet/roslyn/issues/16230#issuecomment-270525728
https://github.com/dotnet/roslyn/issues/13285#issuecomment-243001927

**Comment by TessenR** [comment]
> Ah- also this belongs over at dotnet/roslyn.
Yeah, sorry. I've accidentally created it in the wrong repository.

**Comment by TessenR** [comment]
@jnm2 
There are no reasons to break code in the second example where the refactoring loses a parameter.

Also regarding the 'offer breaking refactorings' theme. As I mentioned above I do think that a warning would be a great solution in cases like this. It looks like detecting the problem is also a consistent theme.

> This is working as intended. **As the preview shows, there is an error here**. (that's why we say 'conflicts detected').

> In general, our philosophy is to make refactorings available, and assume that the user knows what they are doing, and instead just try to **inform about the consequences using the preview.**

> Our general philosophy is to allow you to do things even if they aren't perfect because it might be one step in a process you are doing and still helpful. **We do try to include conflict information though, so that you can make an informed choice about whether or not to proceed.**

However, there are no conflicts in this case neither in the context menu nor in the preview.

**Comment by sharwell** [comment]
@TessenR These would be good to post over in dotnet/roslyn. :smile:

**Comment by jnm2** [comment]
I'm happy with warnings. Just so long as I can go ahead with what I want to do and I'm not slowed down by the code fix being too ginger.

**Comment by jnm2** [comment]
![xkcd](https://imgs.xkcd.com/comics/sandwich.png)

**Comment by TessenR** [comment]
@sharwell  Sure. I'll create it in a few minutes. I'm regularly checking both repositories and accidentally created the issue from a wrong browser tab :(
