### ISSUE TITLE
"lead" contextual keyword.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#915]
**Summary**

Often when writing code for instance members in static contexts, you encounter this familiar error.

> can not do this in static context.

Usually this happens when you are writing code when a type is not fully initialized.

**Few Scenarios**
Scenario 1 : can not use instance field by passing it to base class or overloaded constructors
```
private object _field = new object();
public Constructor() : base(_field) // error using "base" or "this"
{
}
```
Scenario 2: can not use instance field by using it inside default member initializers.
```
private List<int> _values = new List<int>();
public ReadOnlyCollection<int> Values { get; } = new ReadOnlyCollection(_values); // error
```
Scenario 3: can not call instance methods inside static contexts.
```
public Constructor(int x, int y, int z) : base(Reform(x, y, z)) // error
{
}
```
Scenario 4: can not use instance members inside delegates initialized in static context.

(if you come up with more specific scenarios please share for sake of completeness.)

common solution is to defer your code inside constructor or an instance method that is called later. or do some thing completely independent and static. 

**Proposal and explanation**

it would be nice if we could specialize some member initializations by using a denoting a "lead" keyword. "lead" is the best name I could recall. but this is open to any suggestion that is more contextually meaning full and short.

The **lead** keyword will cause to **precipitate initialization of applied member**, allowing to be used by other instance members in static contexts.

lead keyword can facilitate member initialization in static context which is fairly a common problem.

using lead members can also allow us to write additional logics between calling a constructor and before going down to base class.

When using lead member inside static contexts of instance member, it is **guaranteed** that lead member is fully initialized. therefore it is not dangerous to use since that part of class is guaranteed to be stable.

* lead members can access other lead members, but can not access other instance members.
* lead members can not be virtual. though it can be implemented from an interface.
* lead member can not be static, but can access static members.
* lead member can be field, property, method or indexer.
* lead method can not be marked as async.
* lead member can not contain lock statements.
* lead member can not be marked as unsafe. (just for safety!)

using lead keyword must not violate any of these clauses other wise compiler error must be issued. 
(if there are other concerns please share for sake of completeness)

**Few examples**
Example 1:
```
private lead Point PreInitialize(int x, int y, int z)
{
    // only able to access other lead members.
    return new Point(x, y, z); // I know, its just an example!
}
public Constructor(int x, int y, int z) : base(PreInitialize(x, y, z)) // do something to x,y,z before calling base constructor.
{
}
```
Example 2:
```
private lead List<int> _values = new List<int>(); 
public ReadOnlyCollection<int> Values { get; } = new ReadOnlyCollection(_values); // be happy.
```

if you come up with better examples please share, I know there are lots of good examples out there. in your mind! go ahead.

**Discussing Compilation**

Thanks for comments.
I believe This is still possible to achieve without requiring any change in CLR.

Look at following code
```
class B {}
class D : B
{
    int i = 42;
    public int x { get; set; } = C.reference.method();
    
    public D()
    {
    	method();
    }
    
    private int method()
    {
        return 3;
    }
}

static class C
{
    public static D reference = new D();
}
```
Produces
```
        IL_0000: ldarg.0
        IL_0001: ldc.i4.s 42
        IL_0003: stfld int32 D::i
        IL_0008: ldarg.0
        IL_0009: ldsfld class D C::reference
        IL_000e: callvirt instance int32 D::'method'() // instance call before constructor call.
        IL_0013: stfld int32 D::'<x>k__BackingField'
        IL_0018: ldarg.0
        IL_0019: call instance void B::.ctor()
        IL_001e: ldarg.0
        IL_001f: call instance int32 D::'method'()
        IL_0024: pop
        IL_0025: ret
```

The problem is that we are using an already instantiated object. but the purpose of this code is to show that we CAN have instance calls before constructor call. 

Compiler can allow calling instance members of current instance (?), the reason it doesn't because its not safe to do so. but with closures I made earlier it will be safe to call instance method before constructor call.

I know its not quite right to have so much prejudice, I did not study CLR. I would love you people to discuss upon this more.

**Comment by HaloFour** [comment]
I believe that it's the CLR which enforces the rule that the first thing that an instance constructor does is call a base constructor.  Not doing that produces unverifiable assemblies which is not something that should be encouraged via a language feature.

**Comment by MkazemAkhgary** [comment]
@HaloFour  for that matter, it could be done via a trick. a lead member is defined in base class but its only usable via a derived class.

**Comment by MkazemAkhgary** [comment]
another idea, this may not be optimal but a lead member causes a creation of super class which has all those lead members defined, therefore even by CLR it will be handled safely, though using one more base introduces some overhead under the hood. @HaloFour

**Comment by HaloFour** [comment]
@MkazemAkhgary 

> a lead member (when compiled) is defined in base class but its only usable via a derived class.

What base class?  You're only defining one class.  To have the compiler silently emit another means that the compiler also has to emit a second publicly named type that could be referenced directly.

Even then, what's the point? None of those "hacks" would allow for your instance code to execute prior to the constructor of the base type being invoked.

**Comment by MkazemAkhgary** [comment]
The point is clear in post, to add syntactic sugar. but with statement you made this seems to be impossible, at least as an syntactic sugar. this will change normal compilation procedure. I did not know the fact you just noted. hence the post I made. but thanks for comments. so it might not be worthy to implement. @HaloFour

**Comment by svick** [comment]
@HaloFour 

> I believe that it's the CLR which enforces the rule that the first thing that an instance constructor does is call a base constructor.

I don't think that's true. Instance member initializers are actually executed before the base constructor. For example, this code:

```c#
class B {}

class D : B
{
    int i = 42;
}
```

produces this IL for `D`'s constructor:

```il
D..ctor:
IL_0000:  ldarg.0     
IL_0001:  ldc.i4.s    2A 
IL_0003:  stfld       D.i
IL_0008:  ldarg.0     
IL_0009:  call        B..ctor
IL_000E:  ret  
```

**Comment by jnm2** [comment]
[sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmAAgCECBvAXwFgAoG(/AgEQJGJtJoM4LQDsZuCAXgIAWPAG4a5IA))

**Comment by MkazemAkhgary** [comment]
@HaloFour @svick @jnm2 @srivatsn @migueldeicaza Thanks for suggestions. please take a look at updated post.
