### ISSUE TITLE
Expand Throw Expressions to more use-cases

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/csharplang#918]
Given that Throw Expressions work in this case:

    string myStr;

    public MyObj( string myStr ) =>
        this.myStr = myStr ?? throw new ArgumentNullException( "myStr" );

I would find it perfectly natural, even expected, that they also work in this case:

    bool isRunning;

    public void Run() =>
        isRunning = !isRunning || throw new InvalidOperationException( "Already running" );

**Comment by MkazemAkhgary** [comment]
why not 

```
isRunning = !isRunning ? isRunning :  throw new InvalidOperationException( "Already running" );
```

**Comment by HappyNomad** [comment]
@MkazemAkhgary  Yes, that's how I've written my code given the current situation.  But a fully spec'd out/implemented Throw Expression feature would be better in the long run.  The cognitive load would be less.  Instead of thinking about what specific, arbitrary use-cases happen to be covered by the spec, we could just understand the basic concept, write our code, and move on.

**Comment by jnm2** [comment]
Anecdotally, I've run into wanting to use throw expressions with `||` and `&&` four times or so since I started using them.

**Comment by HappyNomad** [comment]
@jnm2  What would it look like with an `&&`?

**Comment by jnm2** [comment]
`(expressionThatShouldBeFalse) && throw ...`

**Comment by jnm2** [comment]
I admit it's less readable than `!(expressionThatShouldBeFalse) || throw ...`, but you can't really treat the two operators asymmetrically when you implement this feature.

**Comment by bondsbw** [comment]
Discussed as an open question in proposal #176
Never/bottom type (#538) could provide a more generalized version of this feature
Also discussed at #580

**Comment by MkazemAkhgary** [comment]
Obviously you cant have `throw` as first operand of either && or ||. other wise it would be meaningless.

Also how would you react to something like this?

```
if((!A || throw) && B && throw)
```

This is nightmare. allowing throw statement here is not meaningful, you expect to see conditions when working with `||`, `&&` not throwing exceptions. 

IMO use of ternary operator or if statement is much more readable.

**Comment by jnm2** [comment]
@MkazemAkhgary You're right, in that `(!A || throw)` is guaranteed to evaluate to false or else execution leaves before getting to the rest of the expression.

**Comment by HappyNomad** [comment]
This discussion has been an interesting, but now I see why this language feature shouldn't involve Boolean expressions.

**Comment by jnm2** [comment]
I wonder how this would interact with nullable tools? `?? throw` throws for the null case, `&& throw` and `|| throw` could throw for the other two cases.

**Comment by MkazemAkhgary** [comment]
`??` is actually nice, its common to throw exception when parameters are expected to have value and not be null. but `||` and `&&` are used for working with Boolean values and only the result is used for branching by if statement or ternary operator.

I also discourage `condition && someMethod()` when some method has side effects. it becomes harder to understand flow control of application. so does throw.

**Comment by jnm2** [comment]
Certainly. I'm putting ideas out there that I obviously don't see myself using.
