### ISSUE TITLE
Proposal: Infer generic type based on target

### ISSUE THREAD

**Issue by HaloFour** [dotnet/csharplang#92]
Copied from https://github.com/dotnet/roslyn/issues/5429

### Problem

When calling generic methods where the generic type parameter is only used as the return value of the method there is currently no inference which leads to repetition.

``` cs
DataTable table = ...;
var people = table.Rows
    .Select(row => new Person {
        Id = row.Field<int>("id"),
        Name = row.Field<string>("name"),
        Birthdate = row.Field<DateTime>("dob")
    })
    .ToList();
```
### Proposal

It would be convenient if in the specific case of the generic type parameter being the return type if the compiler could infer the generic type argument based on the destination of the result.  This would only be permitted if the method is called in an unambiguous fashion.  The return value must be assigned to a destination with an explicit type and there can be no other non-generic methods with the same name and parameters.

``` cs
int id = row.Field("id"); // legal, generic type argument inferred to be int
var id = row.Field("id"); // not legal, circular inference
row.Field("id"); // not legal, no assignment to a type
```

**Comment by alrz** [comment]
I think this also should work:
```cs
IQuerable<int> M() => Array.Empty().AsQueryable();

public static T[] Empty<T>();
public static IQueriable<T> AsQueryable<T>(this IEnumerable<T>);
```

**Comment by alrz** [comment]
Should the target type flow into parameters as well?
```cs
T M(out T t) {...}

int i = M(out var i); // should this compile?
```
@HaloFour I think Java relies only on the overload resolution result to be viable and doesn't care if type parameters are used in input positions, right?

**Comment by Foxtrek64** [comment]
What are your thoughts on providing a (sane) default via an overload?

I could see it being useful in some cases, such as where an API developer would like to provide a default return type that can act as a catch-all (`object` or some kind of common interface or type) but still provide the ability to cast to the specified type as needed.

However, I could also see it causing some undesirable or perhaps unexpected behavior depending on implementation, especially if the user assumes no type parameter was needed because it was implied rather than because it fell back to a type-parameterless overload.

```cs
private readonly Dictionary<string, object> _dict;

public string Find(string key)
    => DoFoo<string>(key);

public TResult Find<TResult>(string key)
{
    // Some sort of dummy lookup code
    return _dict[key] as TResult;
}
```
```cs
int id = item.Find("Id"); // Legal, as discussed by op.
var name = item.Find("name"); // Falls back to type-parameterless overload. Type becomes 'string'.
```

**Comment by AartBluestoke** [comment]
@Foxtrek64 that would mean that replacing a type with var is a breaking change. I suspect that makes this feature a non-starter.

**Comment by HaloFour** [comment]
@AartBluestoke 

It's not a "breaking change" if you have to modify source to exhibit the different behavior.  But I agree that this could be confusing behavior.

**Comment by alrz** [comment]
`int a = default;`

*You can't have both fish and bear's paw.*
