### ISSUE TITLE
Proposal: out base x

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#920]
I saw that `out var x` is valid instead of explicitly specifying type, and I actually liked it because it shorten my code.

why not also allowing use of base class too (implied cast from child to base). for example.

```
public void Foo(out Base b)
{
    Bar(out Base x);
    b = x;
    // or even
    Bar(out b);
}

public void Bar(out Child c)
{
    c = new Child();
}
```

This is just for fun, now I haven't recently see need for this but I remember I did few times. 😆 (which then I had to make it two line)

**Comment by HaloFour** [comment]
@MkazemAkhgary 

`out` parameters in C# are really `ref` parameters which are implemented using reference types in the CLR which are really just managed pointers.  They're not permitted to be variant as they have to be both readable and writable by both the caller and callee, and `Bar` cannot accept a `Base` argument.

The C# compiler could fake this by emitting a local of the appropriate type and copying the value over, e.g.:

```cs
public void Foo(out Base b)
{
    Child $temp;
    Bar(out $temp);
    b = $temp;
}
```

But this would behave semantically different from how normal `ref` parameters work.  As they are pointers when the method updates the value the update is immediately reflected at the original location.  That might be kind of academic with locals, but it's quite important with fields where invoking another instance method could read the updated field value before the callee returns:

**Comment by MkazemAkhgary** [comment]
I see, so changes to Child would not be immediate and visible to Base, until callee eventually returns and `b` is set. @HaloFour
