### ISSUE TITLE
Proposal: Add an `LARGE_ADDRESS_AWARE` switch to the .NET compiler

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/csharplang#929]
## _This is a copy/pasta from dotnet/roslyn#9209_

----

I sometimes write applications and/or libraries which need the `LARGE_ADDRESS_AWARE`-flag set. I usually solve this by calling `editbin.exe` as postbuild-event.

Would it be an good idea to add a corresponding switch directly to the C#/F#/.... compiler?
It would have the following pros:
- one could save a few miliseconds/seconds of compilation time and postbuild-event calls
- it is easier to use for regular users (when properly integrated into VisualStudio)
- would not influence the compiler speed a lot - as it is only one argument which must be parsed and one bit which must be written
- reduce the amount of possible error sources during execution and project build (e.g. when some uses editbin incorrectly)

_Or am I the sole one appending the `editbin`-postbuild to every second project of mine?_

---
An alternative could be the introduction of an pseudo-attribute like
```csharp
[assembly: LargeAddressAwareApplication]
```

**Comment by eyalsk** [comment]
@Unknown6656 I think it's more of a tooling issue than a language issue. :)

**Comment by sharwell** [comment]
@Unknown6656 The C# compiler already does this.

| Architecture | LAA | Settings |
| --- | --- | --- |
| X86 | No | Platform: X86 |
| X86 | Yes | Platform: Any CPU, Prefer32Bit: True |
| X64 when available | N/A | Platform: Any CPU, Prefer32Bit: False |
| X64 only | N/A | Platform: X64 |

**Comment by sharwell** [comment]
@Unknown6656 I updated the linked Roslyn issue to show the code which implements the feature.

**Comment by Unknown6656** [comment]
@eyalsk : I know, I just wanted to raise more people to the issue and I thought the `roslyn`-repo was more busy with bug fixes and people here have more 'free time' for language or compiler features.

@sharwell : Thank you very much for your help and information! I was not aware of the implementation.

**Comment by eyalsk** [comment]
@Unknown6656 Ahh okay, fair enough. :)

**Comment by gafter** [comment]
Closing, as there is no language change proposed herein.

**Comment by AraHaan** [comment]
Actually LAA is possible on 64 bit processes themselves too, or so I see the option on CFF Explorer on 64 bit applications / dlls that I load into it.
