### ISSUE TITLE
covariant return type, i.e type of implementer

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#930]
Allow `?` as return type of interfaces. here is simple example.

```
public interface IFoo
{
    ? DeepCopy();
}

public class Foo : IFoo
{
    Foo DeepCopy()
    {
        return new Foo();
    }
}

public class Bar : IFoo
{
    Bar DeepCopy()
    {
        return new Bar();
    }
}
```

Now if you were to call from interface instance, you would get interface itself. i.e

```
var bar = new Bar();
var copiedBar = bar.DeepCopy();
var copiedIFoo = ((IFoo)bar).DeepCopy(); // returns IFoo.
```

Note that "?" can only be used as return type. it can not be used as input. that means `?` is covariant.

The example is feasible with following equivalent:

```
public interface IFoo
{
    IFoo DeepCopy();
}

public class Foo : IFoo
{
    IFoo IFoo.DeepCopy() => DeepCopy();
    Foo DeepCopy()
    {
        return new Foo();
    }
}
```

but advantage of "?" is that you save few lines and you have better contract.

"?" is also possible as return type of abstract members.

```
public interface IFoo
{
    ? DeepCopy();
}

public abstract class Foo : IFoo
{
    abstract ? DeepCopy();
}

public class Bar : Foo
{
    Bar DeepCopy()
    {
        return new Bar();
    }
}
```

**Comment by orthoxerox** [comment]
Dupe of #169, #252,

**Comment by Joe4evr** [comment]
Also of #49.

**Comment by MkazemAkhgary** [comment]
Those proposals are more refined than this, especially #169 , so I close this proposal.

**Comment by jnm2** [comment]
> Those proposals are more refined than this, especially #252 , so I close this proposal.

Not to mention they they are dupes. 😄
