### ISSUE TITLE
support for implicit enum cast 

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#932]
Allow implicit operator cast simply by noting this.

I know why implicit cast of enums were prevented and it makes absolute sense.  [Why enums require an explicit cast to int type?]( https://stackoverflow.com/questions/4728295/why-enums-require-an-explicit-cast-to-int-type)

But you as a developer know better than c# compiler. why not allowing it by maybe adding implicit keyword when defining enum?

I really needed implicit cast from enum to int (mapping note names into integer) so I had to workaround this issue using class and static properties.

```
public implicit enum Note // notice keywords
{
    C = 0,
    D = 2,
    E = 4,
    F = 5,
    G = 7,
    A = 9,
    B = 11,
}
```

by denoting implicit keyword you tell compiler to shut up and let me do my own work! 😄 so you use it implicitly.

```
int x = Note.G; // nice and simple
```

Type of enum would also apply on how cast works. for example enum of long can be implicitly cast to long but cant be implicitly cast to int. this rule may not necessarily apply since enum values are constant.

Allowing "explicit" keyword would not make much sense, but allowing it makes it symmetric.

(I have omitted most of enum members (total of 128 members). it contains note names with their octave mapped to note numbers from 0 to 127)

**Comment by svick** [comment]
> I had to workaround this issue using class and static properties

To me, that doesn't sound like a workaround, it sounds like the right way to do it. What makes the proposed `implicit enum` better? Or do you want to be able to treat it both as the `enum` and `int`?

**Comment by eyalsk** [comment]
@MkazemAkhgary So why are you using enums? the point of using them is to abstract the underlying value and them being a different type makes sense for making an explicit cast, in my opinion, what you're proposing goes against the very thing enums try to solve so instead you can just do the following:

```
public static class Note
{
	public const int C = 0;
	
	public const int D = 2;
	
	public const int E = 4;
	
	public const int F = 5;
	
	public const int G = 7;
	
	public const int A = 9;
	
	public const int B = 11;
}
```

**Comment by MkazemAkhgary** [comment]
@eyalsk thanks, I will use this syntax. I'm using text template to generate code so It shouldn't be problem.

**Comment by gafter** [comment]
@MkazemAkhgary It sounds like you may be withdrawing this request for a language feature. If so, please close.

**Comment by MkazemAkhgary** [comment]
Sorry, I had to do it after I commented. I forgot though @gafter
