### ISSUE TITLE
Allow modifiers on types in any order (partial, ref, readonly)

### ISSUE THREAD

**Issue by jcouv** [dotnet/csharplang#949]
Currently `partial` on a type is required to precede the type keyword (for instance, `partial struct`).
This was discussed in LDM earlier this week, but probably warrants confirmation.
Also, there is the question of lookahead strategy.

Tagging @gafter @agocke

**Comment by alrz** [comment]
Dup of 946?

**Comment by eyalsk** [comment]
Sorry for my ignorant but is there a reason or use-case for that? or it's just esthetics?

**Comment by jcouv** [comment]
@eyalsk The motivation is just to remove an irregularity.
With the introduction of ref structs, we ran into some parsing questions. Which one is OK: ref partial struct, or partial ref struct? How about combinations with other modifiers? 
With C#7.2, we'll require partial before struct, and ref before that. But those seem arbitrary limitations, which could stumble users.

**Comment by jcouv** [comment]
Closing this one. Indeed duplicate. Thanks @alrz

**Comment by eyalsk** [comment]
@jcouv Ah okay, thanks.
