### ISSUE TITLE
Optimize Generic new() Constraint

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/csharplang#953]
[Jon Skeet](https://codeblog.jonskeet.uk/2011/08/22/optimization-and-generics-part-1-the-new-constraint/) has a whole blog post describing how the generic `new()` constraint calls `Activator.CreateInstance` which uses reflection, so it ends up being slow.

Workarounds for this at the moment are to use `default(T)` for structs or creating a `Func<T>` lambda using expression trees like so:

```
Expression.Lambda<Func<T>>(Expression.New(typeof(T))).Compile();
```

Ideally `new()` can be optimized so that these workarounds are not necessary.

**Comment by orthoxerox** [comment]
Shouldn't this be in https://github.com/dotnet/roslyn? The spec doesn't say how this constraint must be implemented.

**Comment by RehanSaeed** [comment]
Moved to https://github.com/dotnet/roslyn/issues/22464
