### ISSUE TITLE
Proposal: File and class scoped visibility modifier

### ISSUE THREAD

**Issue by Denis535** [dotnet/csharplang#954]
Kotlin has one good feature: private modifier for classes.

> If you mark a declaration private, it will only be visible inside the file containing the declaration;

https://kotlinlang.org/docs/reference/visibility-modifiers.html

I think it would be very useful for decomposition of classes.
For example: split class into main class and thair helper or into View, Model, Controller.
Now I must to name/rename every class with full name: MyBlaBlaBlaClass, MyBlaBlaBlaClassHelper or MyBlaBlaBlaView, MyBlaBlaBlaModel, MyBlaBlaBlaController. 
With file scoped modifier I could name just: Helper, Model (I'm writting Model and Controller in the same file). 
It will encourage to write more decomposed code and smaller classes.
Only one problem: how those classes can be available for tests.

Also I have one more similar proposal: class scoped modifier (neested classes without real nesting).
For example: MyBlaBlaBlaClass.Helper or MyBlaBlaBlaController.Model.
I don't need to access private members of outer class. I want to avoid hell of long class names and big neested classes.

**Comment by svick** [comment]
> With file scoped modifier I could name just: Helper, Model (I'm writting Model and Controller in the same file).

Why aren't nested classes sufficient for this?

Personally, I like that in C#, files don't really matter, because it makes refactoring easier. This proposal would break that: for example, I can't easily move a file-scoped class to a different file, if it becomes too large.

> Also I have one more similar proposal: class scoped modifier (nested classes without real nesting).

I don't understand what are you proposing here, could could clarify, maybe by showing example code that uses this?

**Comment by deni35** [comment]
> Why aren't nested classes sufficient for this?
Big neested class or big scope hierarchy makes class terrible.

> I don't understand what are you proposing here, could could clarify, maybe by showing example code that uses this?
```
class MyClass {}
class MyClass.Helper {}
```
1) It's very clear that Helper refers to MyClass.
2) When I rename MyClass then MyClass.Helper will be renamed automatically.

**Comment by HaloFour** [comment]
@deni35 

I don't see how that avoids either problem of "long nested class names" or "big nested classes".  You're still embedding the parent class name right in the nested class name.  And as for the size of your nested class, where do you expect that code to go?

If the complaint is that the nested class code is embedded in the same file as the parent class, well, nobody is forcing you to do that.  Define the parent class as a `partial` class and you can have a separate file for the nested class, without trading any of the benefits of it being nested.  At worst you have an extra level of indentation if you go with the default auto-format.

I'm not personally opposed to the notion of class names being compound like that but I think it immediately runs into an ambiguity problem as to whether the nesting is parent classes vs. namespaces.

**Comment by yaakov-h** [comment]
I'm confused. Your long example above makes no use of `private class` whatsoever.

Swift has `private` and `fileprivate`, and that's been somewhat of a disaster.
