### ISSUE TITLE
lock and finally

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#957]
lock is used critical section of program, if it fails it may leave program to undefined state. to fix this issue you can currently do this

```
lock(obj)
{
    try
    {
    }
    finally
    {
    }
}
```

it would be nice if finally could be used in conjunction with lock.

```
lock(obj)
{
}
finally
{
}
```

finally lock is also executed inside lock. so lock is released after finally.

This is not essential but is something I found pretty cool.

**Comment by sharwell** [comment]
I am a huge :-1: on this issue *specifically* on the point that in the example, the `finally` clause appear outside the `lock` block yet executes within the locked section.

**Comment by HaloFour** [comment]
Agreed, it would not be intuitive or consistent if the lock remains acquired within the `finally` block.  That could lead to a pit of failure situation where developers believe that they can perform lengthy operations within the `finally` block not realizing the contention that they are putting on the synchronizing resource.

**Comment by alrz** [comment]
This is already possible,
```cs
lock(obj) try
{
}
finally
{
}
```

**Comment by MkazemAkhgary** [comment]
Ow i missed that

**Comment by jnm2** [comment]
@alrz What I was gonna say! :D People rely too much on following the IDE's automatic formatting.
