### ISSUE TITLE
sync root lock on methods

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#958]
sometimes you use locks on body of methods to synchronize root of calls.

```
private object obj = new object();
public void Foo()
{
    lock(obj)
    {
    }
}
public void Bar()
{
    lock(obj)
    {
    }
}
```

it would be nice if lock body could be merged with method body. lock is not part of method signature.

whether body lock expression be static context or not has room for discussion but I think it would be nice if it wont be in static context.

```
private object obj = new object();
public lock(obj) void Foo()
{
}
public lock(obj) void Bar(object obj) // would lock on obj parameter.
{
}
```

**Comment by yaakov-h** [comment]
Looks like #892’s `guardedby`

**Comment by HaloFour** [comment]
Why is it necessary, or an improvement, to move the position of the `lock` statement in these cases?  As you said, "lock is not a part of the method signature," not in practice or implementation, but this proposal is trying to make it a part of the method signature.

**Comment by jnm2** [comment]
This makes the signature ugly and hard to read.

**Comment by benaadams** [comment]
@MkazemAkhgary you can already do this by applying an attribute to the method

```[MethodImplAttribute(MethodImplOptions.Synchronized)]```

static methods are type locked on other static methods that have the attribute

instance methods are instance locked on other instance methods that have the attribute

**Comment by MkazemAkhgary** [comment]
@benaadams I cant see Synchronized option in UWP. is this something new in net standard 2?

**Comment by benaadams** [comment]
Ah, I think its something that's gone. Also was the `[Synchronization]` attribute for the class, but I think they were come to be seen as bad practice

**Comment by sharwell** [comment]
> I cant see Synchronized option in UWP. is this something new in net standard 2?

This was added to .NET Standard 2.0. It will be available in UWP after it is updated to support the new standard.

**Comment by MkazemAkhgary** [comment]
good to know, yes locking on `this` can be dangerous since it may not be obvious to consumers that you are locking on specific instance, my class is internal by the way so it will be safe to use.
