### ISSUE TITLE
weak locks.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#959]
This is something that can be achieved with semaphores but having this feature will make it much easier.

This allows you to for example do this. 

 - be able to perform many thread-safe read operations
 - if write operation is in progress, all other reads will suspended until write lock is released.

```
public void Read()
{
    weak lock(obj) // many threads are allowed to enter weak lock section until a lock (strong lock) has entered critical section.
    {
    }
}
public void Write()
{
    lock(obj) // just a normal lock but weak locks can not enter until this lock exits critical section. 
              // if weak lock is entered, this lock can not enter until weak locks are released
    {
    }
}
```

**Comment by alexrp** [comment]
Sounds like you want a [ReaderWriterLockSlim](https://msdn.microsoft.com/en-us/library/system.threading.readerwriterlockslim(v=vs.110).aspx).

You could make some extension methods for it that would allow you to say something like:

```csharp
var myLock = new ReaderWriterLockSlim (...);

using (myLock.ReadGuard ())
{
    // ...
}

using (myLock.WriteGuard ())
{
    // ...
}
```

(Those extension methods would return an `IDisposable` struct that acquires the relevant portion of the lock in the constructor and releases it in the `Dispose` method.)

**Comment by MkazemAkhgary** [comment]
sounds great, I did not know such thing exist @alexrp
