### ISSUE TITLE
Enhance "'default' expression can be simplified"

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/csharplang#961]
Consider this C# 7.1 snippet:

![image](https://user-images.githubusercontent.com/2716316/31126369-43449d54-a854-11e7-9688-b33d3609ecaa.png)

The compiler offers to "simplify" `default(DateTime)` with `default`, but that's not just a mere simplification, because the return type of the function is `object`, so `default` will return `null` whereas the default `DateTime`, which is a value type, is an unset tho initialized instance of `DateTime`.
The offer the compiler notifies sounds like it has no impact on the actual code but a syntactic sugar, which is wrong.

My request is that the compiler should only offer `default(T)` simplification if the types pre and post simplification will be the same.

**Comment by HaloFour** [comment]
I believe that this would belong on the [Roslyn](https://github.com/dotnet/roslyn/issues) repo since it's a bug in the tooling and not specifically in the language spec itself.

**Comment by weitzhandler** [comment]
@HaloFour I already started writing this post on Roslyn then thought I'll post it here since it's C# specific, but as per your comment, it's posted [here](https://github.com/dotnet/roslyn/issues/22484). Will close this issue now.
