### ISSUE TITLE
rethrow exception outside try catch block

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#971]
the statement for exception re-throw inside try catch block is simply `throw;`. that will keep the original stack trace.

but what if we are not using a try catch, I don't see way to re-throw exception. consider this case.

```
return DoSomething().ContinueWith(t =>
{
    var ex = t.Exception?.GetBaseException();
    if (ex != null) throw ex;
    // some operations
    return data;
}, TaskContinuationOptions.ExecuteSynchronously);
```

there is no way (or at least I'm not aware of) to re-throw `ex`. it would be nice if rethrow out side try catch was possible too.

```
if (ex != null) rethrow ex; // will not overwrite stack trace.
```

**Comment by HaloFour** [comment]
You can use [`ExceptionDispatchInfo`](https://msdn.microsoft.com/en-us/library/system.runtime.exceptionservices.exceptiondispatchinfo.aspx) which was added in .NET 4.5.

```cs
return DoSomething().ContinueWith(t =>
{
    var ex = t.Exception?.GetBaseException();
    if (ex != null) ExceptionDispatchInfo.Capture(ex).Throw();
    // some operations
    return data;
}, TaskContinuationOptions.ExecuteSynchronously);
```

**Comment by MkazemAkhgary** [comment]
@HaloFour thank you!

**Comment by svick** [comment]
And if you're on .Net Core 2.0, instead of `ExceptionDispatchInfo.Capture(ex).Throw()`, you can write just `ExceptionDispatchInfo.Throw(ex)` (see https://github.com/dotnet/corefx/issues/16896).

**Comment by MkazemAkhgary** [comment]
good, ill be using .Net core 2.0 soon, so ill keep that in mind. @svick

**Comment by alrz** [comment]
why not OnlyOnRanToCompletion?
