### ISSUE TITLE
ref array, a selected range from T[]

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#972]
return by ref from array is very cool feature.

```
private byte[] array;
public ref byte ItemByRef(int index) => ref array[index];
//...
ref var x = ref ItemByRef(index);
x = 3;
```

why not extending this feature to ref[]?

```
private byte[] array = new byte[100];
public ref[] byte RangeByRef(int index, int length) => ref[length] array[index];
//...
ref[] var x = ref[] RangeByRef(index, 10);
x[0] = 3;
x[1] = 4;
x[10] = 0; // index out of range exception
var length = x.Length;
```

Note that whole purpose of this proposal is to avoid creating temporary arrays. therefor `ref[]` should not allocate any array. it will be reference to selected item from array plus length of selected range.

if selected range is bigger than size of array, it should throw index out of range exception.

size of range is only specified when selecting range from array. so assigning ref[] to another variable does not need to have any number associated. although length of selected array can be retrieved by `Length` property.

selected range could become shrink by specifying new size that must be equal or smaller than current range, other wise exception should be thrown.

```
ref[] int shrink = ref[] SelectRange(10); // no shrink.
ref[] int shrink = ref[5] SelectRange(10); // shrinks 10 to 5
ref[] int shrink = ref[15] SelectRange(10); // throws runtime exception, even if original array is larger than 15 length.
```

**Comment by bbarry** [comment]
Conceptually this is what `Span<T>` is. 

See the proposal currently targeted for 7.2 about spans:

https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md

In short there are/will be these Span types that reference an array segment:


    long[] a = { 90, 91, 92, 93, 94, 95, 96, 97, 98 };
    Span<long> span = new Span<long>(a, 4, 3);
    // span contains the memory segment pointing at the array segment { 94, 95, 96 }
    ref long b = ref span[1]; // 95
    b = 100;
    // a == { 90, 91, 92, 93, 94, 100, 96, 97, 98 }

documentation for netcore-2.0: https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-2.0

source in corefx: https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Span.cs

**Comment by yaakov-h** [comment]
There's also `ArraySegment<T>` today, if that suits your needs (for now).

**Comment by MkazemAkhgary** [comment]
closing this issue since its already being implemented via span, syntaxes are different tho
