### ISSUE TITLE
ValueEnumerator (fast to code and run)

### ISSUE THREAD

**Issue by benaadams** [dotnet/csharplang#982]
# tl;dr
To completely implement fast struct class-level iterator, fast struct method iterator, and the `IEnumerable<T>` `IEnumerable` set:
```csharp
partial class List<T>
    : IValueEnumerable<T, List<T>.SkipEnumerator>
    : IEnumerable<T>
{
    int _size;
    T[] _items;

    // Method iterator
    public enumerator<T> SkipEnumerator Skip(int index) // typeof(SkipEnumerator)
    {
        while (index < _size)
        {
            index++;
            yield return _items[index - 1];
        }
    }

    // Class-level IValueEnumerable
    public SkipEnumerator GetValueEnumerator() => Skip(toSkip: 0);

    // Class-level IEnumerable
    public EnumeratorAdapter<T, SkipEnumerator> GetEnumerator() => GetValueEnumerator();
}
```
# Motivation

Its fairly convoluted to add an non-allocating struct enumerator to a class; and yield iterators which have a simpler syntax are allocating and also don't work as a class-level struct enumerable.

Related: `System.Linq` is a wonderful feature, however it also allocates for all the IEnumerables; so it would be desirable to find a solution that supports a non-allocating struct-based `Linq` or Value Linq

### Background

Given a [common or garden List<T> class](https://github.com/dotnet/coreclr/blob/076a61ef2eb3baf69182139f36b948f104e3b740/src/mscorlib/shared/System/Collections/Generic/List.cs)
```csharp
public partial class List<T>
{
    private T[] _items;
    private int _size;
    private int _version;
}
```
Adding an indexer is fairly straight forward using the `this[]` property, and it would be good to have a similar ease of use for an enumerator; that is also non-allocating for yield enumerators.

Follow up to https://github.com/dotnet/csharplang/issues/974

# Proposal

### Contract
```csharp
public interface IValueEnumerator<T> : IDisposable
{
    T TryGetNext(out bool success);
}
```

### Contextual keyword

New *method_modifier* to specify the method is a ValueEnumerator which is genericly typed `enumerator<>`
```diff
method_modifier
    : 'new'
    | 'public'
    | 'protected'
    | 'internal'
    | 'private'
    | 'static'
    | 'virtual'
    | 'sealed'
    | 'override'
    | 'abstract'
    | 'extern'
    | 'async'
    | method_modifier_unsafe
+   | method_modifier_enumerator
    ;

+method_modifier_enumerator
+   : 'enumerator'<' type_argument'>'
+   ;
```

It is a struct-based **iterator** and works with `yield` and is of type *return_type*

### Implementation Usage

`public enumerable<T> StructTypeName MethodName()`

Convention: `public enumerable<T> MethodNameEnumerator MethodName()`

`List<T>` example for method iterator (from opening definition)
```csharp
partial class List<T>
{
    // Developer types for enumerator iterator
    public enumerator<T> SkipEnumerator Skip(int toSkip) // typeof(SkipEnumerator)
    {
        int version = _version;
        int index = toSkip;

        while ((uint)index < (uint)_size)
        {
            if (version == _version) throw new InvalidOperationException("List changed");

            index++;
            yield return _items[index - 1];
        }
    }
}
```

`Stack<T>` example for method iterator (from C# spec [iterator Stack sample](https://github.com/dotnet/csharplang/blob/0bffa700dba61735c79fdee7f189d1eda3246835/spec/classes.md#implementation-example))
```csharp
partial class Stack<T>
{
    // Developer types for enumerator iterator
    public enumerator<T> SkipEnumerator Skip(int toSkip) // typeof(SkipEnumerator)
    {
        int start = count - toSkip - 1;
        for (int i = start; i >= 0; --i) yield return items[i];
    }
}
```
The *type* name of the Enumerator is part of the *method_header* declaration so user is at liberty to define it as 
```csharp
public enumerator<T> NamingIsHard Skip(int toSkip) // typeof(NamingIsHard)
```

### Consumption Usage
`foreach` will bind to a `IValueEnumerator<T>` and usage as now:
```csharp
// Developer types 
foreach (T item in list.Skip(toSkip: 5)) 
{
    // Loop body
}
```

#### Implementation Generation

Example code for `List<T>.Skip(int toSkip)` that the compiler could generate
```csharp
public SkipEnumerator Skip(int toSkip) => new SkipEnumerator(this, toSkip);

public struct SkipEnumerator : IValueEnumerator<T>
{
    private int __state;
    private List<T> __thisCapture;

    private int version;
    private int index;

    internal SkipEnumerator(List<T> thisCapture, int toSkip)
    {
        __state = 1;
        __thisCapture = thisCapture;
        version = thisCapture._version;
        index = toSkip;
    }

    public T TryGetNext(out bool success)
    {
        switch (__state)
        {
            case 0: throw new InvalidOperationException("Uninitialized enumerator");
            case 1:
                if ((uint)index < (uint)__thisCapture._size)
                {
                    if (version == __thisCapture._version)
                    {
                        throw new InvalidOperationException("List changed");
                    }
                    index++;
                    success = true;
                    return __thisCapture._items[index - 1];
                }
                __state = 2;
                goto case 2;
            case 2:
            default:
                success = false;
                return default(T);
        }
    }

    public void Dispose() { }

    // Implicit conversion detailed below in Interop
    public static implicit operator EnumeratorAdapter<T, SkipEnumerator>(SkipEnumerator enumerator)
    {
        return new EnumeratorAdapter<T, SkipEnumerator>(enumerator);
    }
}
```
#### Consumption Generation
Example code for `foreach` that the compiler could generate
```csharp
var current = enumerator.TryGetNext(out bool success);
while (success)
{
    // Loop body

    current = enumerator.TryGetNext(out success);
}
```

### Contract
```csharp
public interface IValueEnumerable<T, TEnumerator>
    where TEnumerator : struct, IValueEnumerator<T>
{
    TEnumerator GetValueEnumerator();
}
```

### Implementation Usage
```csharp
partial class List<T> : IValueEnumerable<T, List<T>.SkipEnumerator>
{
    public SkipEnumerator GetValueEnumerator() => Skip(toSkip: 0);
}
```

### Consumption Usage
`foreach` will bind to `GetValueEnumerator` in preference to `GetEnumerator` if available and usage as now:
```csharp
// Developer types 
foreach (T item in list) 
{
    // Loop body
}
```

### Implementation Generation
*No special code generation*
 
### Consumption Generation
Example code for `foreach` that the compiler could generate
```csharp
using (var enumerator = list.GetValueEnumerator())
{
    // As above for method iterator
    var current = enumerator.TryGetNext(out bool success);
    while (success)
    {
        // Loop body

        current = enumerator.TryGetNext(out success);
    }
}
```

### Implementation Usage
```csharp
public SkipEnumerator SkipTen() => Skip(toSkip: 10);
```
### Code Generation
*No special code generation*

## IEnumerable Interop
A common `EnumeratorAdapter` type can be shared for all `IValueEnumerator`s with an implicit conversion
```csharp
public struct EnumeratorAdapter<T, TValueEnumerator> : IEnumerator<T>
    where TValueEnumerator : IValueEnumerator<T>
{
    private TValueEnumerator _enumerator; // mutable struct, do not make readonly
    private T _current;

    internal EnumeratorAdapter(TValueEnumerator enumerator)
    {
        _enumerator = enumerator;
        _current = default(T);
    }

    public T Current => _current;

    public bool MoveNext()
    {
        _current = _enumerator.TryGetNext(out bool success);
        return success;
    }

    public void Dispose() => _enumerator.Dispose();
    object IEnumerator.Current => Current;
    void IEnumerator.Reset() => throw new NotSupportedException();
}
```
This means to implement the IEnumerable pattern is as follows:
```csharp
partial class List<T> : IEnumerable<T>
{
    public EnumeratorAdapter<T, SkipEnumerator> GetEnumerator() => GetValueEnumerator();
    IEnumerator<T> IEnumerable<T>.GetEnumerator() => GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```
## foreach precedence

`ValueEnumerator<T>` > `ValueEnumerable<T>` > `IEnumerable<T>` > `IEnumerable`

# Issues

### Return vs out
Return `T` or return `bool`?

@jaredpar [mentions on twitter](https://twitter.com/jaredpar/status/834884511930331136)
>strangest part is the signature of TryGetNext:
`T TryGetNext(out bool b)` It's demonstrably faster than `bool TryGetNext(out T elem)`

e.g.
```csharp
public interface IValueEnumerator<T> : IDisposable
{
    T TryGetNext(out bool success);
}
```
vs
```csharp
public interface IValueEnumerator<T> : IDisposable
{
    bool TryGetNext(out T value);
}
```

### Disposal on iterator
Some questions

### Covariance

I said fast right 😉 Though open question...

### Type inference

Type inference isn't complete for Value Linq style extension methods
```csharp
public static class Iterator
{
    // Can be inferred
    public static void ForEach<TValueEnumerator, TSource>(this TValueEnumerator enumerator, Action<TSource> action)
        where TValueEnumerator : struct, IValueEnumerator<TSource>
    {
        var current = enumerator.TryGetNext(out bool success);
        while (success)
        {
            action(current);

            current = enumerator.TryGetNext(out success);
        }
    }

    // Can't be inferred
    public static int Count<TValueEnumerator, TSource>(this TValueEnumerator enumerator)
        where TValueEnumerator : struct, IValueEnumerator<TSource>
    {
        int count = 0;
        enumerator.TryGetNext(out bool success);
        while (success)
        {
            count++;

            enumerator.TryGetNext(out success);
        }

        return count;
    }

    // Can be inferred, but unneeded extra param
    public static int Count<TValueEnumerator, TSource>(this TValueEnumerator enumerator, TSource _)
        where TValueEnumerator : struct, IValueEnumerator<TSource>
    {
        int count = 0;
        enumerator.TryGetNext(out bool success);
        while (success)
        {
            count++;

            enumerator.TryGetNext(out success);
        }

        return count;
    }
}

class Program
{
    void Main()
    {
        var list = new List<int>();

        // Works
        list.GetValueEnumerator().ForEach((int i) => Console.WriteLine(i));

        // The type arguments for method
        // 'Iterator.Count<TValueEnumerator, TSource>(TValueEnumerator)' 
        // cannot be inferred from the usage.
        // Try specifying the type arguments explicitly
        list.GetValueEnumerator().Count();

        // Works
        int _ = 0;
        list.GetValueEnumerator().Count(_);
    }
}
```
### Value Linq
`IValueEnumerable` would be a preferred pattern
```csharp
public static int Count<TEnumerable, TEnumerator, TSource>(this TEnumerable source)
    where TEnumerable : struct, IValueEnumerable<TSource, TEnumerator>
    where TEnumerator : struct, IValueEnumerator<TSource>
```
As it can then be type short-cut e.g.
```csharp
if (source is ICollection)
{
    return ((ICollection)source).Count;
}
else
{
    // iterate
}
```
But then type inference for the generics is an extra step away

/cc @jaredpar @nguerrera @CyrusNajmabadi @davkean @HaloFour @sharwell @svick @HaloFour  @karelz

**Comment by HaloFour** [comment]
@benaadams 

Given that external code could obtain their own `ValueEnumerable` via `new` or `default` perhaps it would be better to use 1 as the initial `__state` value and reserve 0 for detecting an uninitialized enumerator?

```cs
public SkipEnumerator Skip(int toSkip) => new SkipEnumerator(this, toSkip);

public struct SkipEnumerator : IValueEnumerator<T>
{
    private int __state;
    private List<T> __thisCapture;

    private int version;
    private int index;

    internal SkipEnumerator(List<T> thisCapture, int toSkip)
    {
        __state = 1;
        __thisCapture = thisCapture;
        version = thisCapture._version;
        index = toSkip;
    }

    public T TryGetNext(out bool success)
    {
        switch (__state)
        {
            case 0: throw new InvalidOperationException("Uninitialized enumerator");
            case 1:
                if ((uint)index < (uint)__thisCapture._size)
                {
                    if (version == __thisCapture._version)
                    {
                        throw new InvalidOperationException("List changed");
                    }
                    index++;
                    success = true;
                    return __thisCapture._items[index - 1];
                }
                __state = 2;
                goto case 2;
            case 1:
            default:
                success = false;
                return default(T);
        }
    }

    public void Dispose() { }

    // Implicit conversion detailed below in Interop
    public static implicit operator EnumeratorAdapter<T, SkipEnumerator>(SkipEnumerator enumerator)
    {
        return new EnumeratorAdapter<T, SkipEnumerator>(enumerator);
    }
}
```

**Comment by benaadams** [comment]
@HaloFour updated

**Comment by nguerrera** [comment]
This is pretty close to what I was suggesting in https://github.com/dotnet/csharplang/issues/974#issuecomment-334775026, so obviously that makes me happy. :)

The difference is that I was proposing having both `enumerator<T>` and `enumerable<T>` with exactly the same use cases as `IEnumerator<T>` and `IEnumerable<T>` iterators today. The former is useful for implementing `Get(Value)Enumerable()` while the latter is useful for returning sequences from arbitrary methods.

I would caution against trying to make enumerators the exchange currency for "value LINQ". In today's world, enumerator usage is always: get a fresh one at sequence start, enumerate, throw away. That's why their mutability doesn't matter.  However, if we start having lots of things that return and accept enumerators directly, it will start to matter and get messy.

**Comment by nguerrera** [comment]
I wonder if `IValueEnumerable<T, E>` -> `IEnumerable<T>` adapter could be default interface implementation (if that feature lands) with `IValueEnumerable<T, E> : IEnumerable<T>`. Ditto for `IEnumerable<T> : IEnumerable` that exists today. That could save a lot of boilerplate.

**Comment by benaadams** [comment]
> I would caution against trying to make enumerators an exchange currency. In today's world, enumerator usage is always: get a fresh one at sequence start, enumerate, throw away. 

Agreed; an issue that did come up was `Dispose`; for `enumerable` started it is clear to call `Dispose` for `enumerator` it is not clear. Also casting for fast-path (to `ICollection`/`IList` for `.Count` vs enumerating the entire collection). Listed them in Issues.

> default interface implementation 

This is nice :)

>  having both `enumerator<T>` and `enumerable<T>`

Will try again... 3rd time's the charm ;-)

**Comment by benaadams** [comment]
> default interface implementation

Would be something like:
```csharp
public interface IEnumerable<out T>
{
    IEnumerator<T> GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

public interface IValueEnumerable<T, TEnumerator> : IEnumerable<T>
    where TEnumerator : struct, IValueEnumerator<T>
{
    TEnumerator GetValueEnumerator();
    IEnumerator<T> IEnumerable<T>.GetEnumerator() => new EnumeratorAdapter<T, TEnumerator>(GetValueEnumerator());
}
```

**Comment by benaadams** [comment]
Not sure implementing `GetEnumerator()` in the default interface would achieve anything? (like implementing strongly typed enumerator for downlevel C#)
```csharp
public partial interface IValueEnumerable<T, TEnumerator> : IEnumerable<T>
    where TEnumerator : struct, IValueEnumerator<T>
{
    TEnumerator GetValueEnumerator();
    IEnumerator<T> IEnumerable<T>.GetEnumerator() => new EnumeratorAdapter<T, TEnumerator>(GetValueEnumerator());
    // Achieve anything ?
    EnumeratorAdapter<T, TEnumerator> GetEnumerator() => new EnumeratorAdapter<T, TEnumerator>(GetValueEnumerator());
}
```

**Comment by benaadams** [comment]
@nguerrera 3rd approach showing all the variants would be
```csharp
partial class List<T> : IValueEnumerable<T, List<T>.ValueEnumerator>
{
    int _size;
    T[] _items;

    // Class-level ValueEnumerable (iterator)
    public enumerator<T> ValueEnumerator GetValueEnumerator() // typeof(ValueEnumerator)
    {
        int index = 0;
        while (index < _size)
        {
            index++;
            yield return _items[index - 1];
        }
    }
    
    // Method iteratable (iteratable)
    public enumerable<T> SkipEnumerable Skip(int index) // typeof(SkipEnumerable)
    {
        while (index < _size)
        {
            index++;
            yield return _items[index - 1];
        }
    }
  
    // Method iterator (iterator)
    public SkipEnumerable.Enumerator TenSkipped() // typeof(SkipEnumerable.Enumerator)
        => Skip(10).GetValueEnumerator();

    // Class-level Enumerable - downlevel C# struct enumerable support
    public EnumeratorAdapter<T, ValueEnumerator> GetEnumerator() => GetValueEnumerator();
    
    // IEnumerable.GetEnumerator() // implemented via default interface
    // IEnumerable<T>.GetEnumerator() // implemented via default interface
}
```

**Comment by benaadams** [comment]
I think Linq Any is over reporting the allocations by x10 https://github.com/dotnet/BenchmarkDotNet/issues/797

**Comment by bbarry** [comment]
small nit: 

`foreach(V c in x)` lowerings should be:

if x is IValueEnumerable:

```csharp
using (E e = ((C)x).GetValueEnumerator();) 
{
    while (true)
    {
        V c = (V)(T)e.TryGetNext(out bool success);
        if (!success) break;

        // Loop body
    }
}
```

and just the loop if x is IValueEnumerator.
Conversions skipped where unnecessary.

because this (and other conversions) should work (as they do in current foreach statements):

```csharp
long Sum(List<int> list)
{
    long a = 0;
    foreach(long l in list)  { a += l; }
    return a;
}
```


And that it should be structurally done instead of depending on types.

**Comment by benaadams** [comment]
> And that it should be structurally done instead of depending on types.

Works for foreach, but has issues with a ValueLinq or `ValueEnumerator` (rather than `IEnumerable<T>`) based methods?

**Comment by bbarry** [comment]
Yes that is what I meant. For `foreach` it would be a structural pattern (and thus would work with ref struct types). APIs that required the implementations here would require the interfaces at least until [shapes](https://github.com/dotnet/csharplang/issues/110) comes along.

**Comment by sebas77** [comment]
I have some interesting application for this and would help my team writing allocation 0 code in a more comfortable way.

**Comment by arekbal** [comment]
[But...](https://gist.github.com/arekbal/0435367c34988d3736c0d9f4b04a2324)
```
                  Method |       Mean |     Error |    StdDev | Scaled | ScaledSD |
------------------------ |-----------:|----------:|----------:|-------:|---------:|
          array_by_index |   883.7 ns | 13.486 ns | 11.262 ns |   1.27 |     0.05 |
     array_by_enumerator |   698.9 ns | 14.310 ns | 28.578 ns |   1.00 |     0.00 |
           list_by_index | 2,383.7 ns | 12.979 ns | 12.140 ns |   3.42 |     0.13 |
      list_by_enumerator | 2,941.2 ns | 22.656 ns | 21.192 ns |   4.22 |     0.17 |
     list_by_array_index |   711.3 ns | 13.976 ns | 29.785 ns |   1.02 |     0.06 |
      list_by_span_index |   777.0 ns | 15.518 ns | 25.058 ns |   1.11 |     0.06 |
 list_by_span_enumerator |   490.2 ns |  3.595 ns |  3.362 ns |   0.70 |     0.03 |
```
List<T> is that unfortunate example...
List<T> of structs, is holding items in continous memory space. It basically acts as resizable Array<T>. 
Index accessor and/or list enumerator should run as fast as Array without any new non-inlineable temporaries in between.
What List<T> enumeration needs, first of all, is to expose some sort of ReadOnly/AsSpan() and/or T[] RawArray/RawData and/or index access by ref...

I understand you guys hope for some linq over values. But please re-design for performance.
Biggest Linq failure was exactly performance considerations...

Side Note: Interleaving is also important issue here.
for instance, summing all X's over Array<Point> would be noticably faster in some sort of InterleavedArray<Point>[] (where X's are first then Y's come second).
Why is that important... for bigger structs like 64 bytes(Rectangle) or fixed buffers, these things if not cared about are slowing things to a crawl.

**Comment by sebas77** [comment]
Still hope this is going to happen. I need iterator blocks generating structs instead of classes to avoid allocations. I don't use enumerator blocks to enumerate data structures, but instead to create asynchronous coroutines that can be used in very interesting patterns to reduce the complexity of long running routines. 

this following example is meaningless, but I use for testing purposes. It's zero allocation code:

`public IEnumerator TestCrazyMultiThread()
        {
            ValueObject result = new ValueObject();

            using (var runner = new MultiThreadRunner<TestEnumerator>("TestSimpleTaskRoutineStopStartWithProvider"))
            {
                int i = 0;
                while (i++ < 20)
                {
                    var continuationWrapper = crazyEnumerator(result, runner).ToTaskRoutine(new SyncRunner<ContinuationWrapper<TestEnumerator>>()).Start();
                    
                    while (continuationWrapper.MoveNext() == true)
                        yield return null;
                }
            }

            Assert.That(result.counter, Is.EqualTo(100));
        }

        ContinuationWrapper<TestEnumerator> crazyEnumerator(ValueObject result, IRunner<TestEnumerator> runner)
        {
            return new TestEnumerator(result).ToTaskRoutine(runner).Start();
        }
        
        struct TestEnumerator : IEnumerator
        {
            readonly ValueObject _result;

            public TestEnumerator(ValueObject result):this()
            {
                _result = result;
            }

            public bool MoveNext()
            {
                Interlocked.Add(ref _result.counter, 1);
            }

            public void Reset()
            {
                throw new NotImplementedException();
            }

            public object Current { get; private set; }
        }`

in this code I run the crazy enumerator code 20 times in side a thread and I expect the counter in the valueobject (The only class) to be increased N times.

However I am forced to write test as an implementation of an IEnumerator while it would be WAY nicer to use an iterator block returning a value type to avoid allocation.

P.S.: while this look similar to what I could achieve with async tasks, my use case is different and I actually prefer my way at the moment.
