### ISSUE TITLE
Async thread lock ("await lock")

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/csharplang#983]
**Background**
The disabling of await within lock makes sense because of the high likelihood of deadlock. At the same time, people do need to preserve integrity of data structures within async methods. An obvious way to do this is to use SemaphoreSlim (perhaps with a wrapper). However this is not very convenient because it does not allow thread re-entrancy, which means that (a) the programmer has to take extra care to avoid calling one locking method from within another one, and (b) it is difficult to provide re-entrancy on the same thread should you want to do so. In addition, generally such a design is not consistent with the existing language design (i.e. lock is thread-re-entrant while semaphores are not; and lock / semaphore features do not interact with each other). 

Obviously one can build thread re-entrancy into the SemaphoreSlim wrapper. The point of this proposal however is to integrate this into the language and provide a natural extension of lock for use in the async programming environment. 

**Proposal**

We should be able to do this within an async method: 

    await lock (lockObject) { 
        ... set parameter based on class-level data ...
        result = await methodAsync( parameter ); 
        .... update class state using result ... 
    }

The semantics of "await lock" would be: await a SemaphoreSlim(1,1) to enter the lock, unless the thread has already entered the lock previously (i.e. allow re-entrancy on the same thread); and exit the lock at the end of the block. Presumably some kind of reference counting is needed to keep track of how many times the lock has been re-entered by the thread (e.g. using ThreadLocal<int> for the reference count). 

Note the continuation of the await lock should be on the same thread since, obviously, the point is to obtain a lock on that thread. Consequently there is no need to create extra syntax for specifying any other continuation.

In addition, the async lock and the existing (synchronous) lock mechanisms should work together, so that await lock will not enter if another thread has done a lock, and vice versa. This will provide a nice and intuitive extension of the existing lock keyword. 

**Discussion**
I don't think that this approach is unduly likely to cause deadlock. You _could_ cause a deadlock with this, in more or less the same ways that you can cause a deadlock using the existing (synchronous) lock mechanism. You would have to lock an object and stay in the lock while kicking off another thread that also tried to lock the same object. What would then happen most likely would be two Tasks that are awaiting each other but not blocking the thread -- a situation that I would say is incrementally better than a synchronous deadlock. 

Regardless of how easily you can create a deadlocked thread (or two deadlocked Tasks), the fact is that practically every application does need to be able to protect the integrity of data that is being accessed both before and after awaiting an async method. Specifically, class data members accessed before the await will often be needed to specify the awaited task parameters, and the task result will then often be used to update other class data members.  Rather than have everyone home-brew their own solution, we should be providing the best practice in a language feature. 

-- sjb

**Comment by jnm2** [comment]
I find it very uncomfortable to treat a given thread specially because every `await` bounces the work to a random threadpool thread.

**Comment by jnm2** [comment]
Also, existing library options also provide other benefits like cancellation or waiting for all current tasks to finish.

**Comment by yaakov-h** [comment]
Your proposal states that we should be able to `await lock(lockObject)`, but then states that this syntax would be compiled down to a `SemaphoreSlim`. If so, what happens to `lockObject` and what is it’s role in the lock?

**Comment by sjb-sjb** [comment]
@jnm2 in general my suggestion is to establish best practice for async locking and then incorporate it into the language using syntax more or less like what I proposed. So if you can outline what you feel is the best practice (i.e. the "existing library options" that you refer to) in a simplified way then we can discuss the pros and cons of each approach. A few comments: 

(1) As relates to cancellation, I don't feel it is necessary to be able to cancel the await lock, because instead of doing that we can cancel the other task which is currently holding the lock. Also we should not have to cancel lock requests because the other task currently holding the lock should exit promptly. This is similar to the situation with the existing lock keyword, where there is no cancellation or timeout mechanism provided -- one is supposed to avoid deadlocks, not break them using cancellation or timeouts. 

(2) I'm not sure how "waiting for all current tasks to finish" applies to the design of async lock. You can still do this within the lock body. Would be interested to know any lock-specific aspect of this that you may have in mind. 

(3) I don't feel that we are treating one thread specially. Await will only send the continuation to a different thread if you configure await to do so. I am just suggesting that awaiting a thread lock is not a situation where you then want to continue on a different thread. Consequently we do not need a syntax to enable a configure await for the locking step. 

(4) We should figure out what to do if the await inside of the lock body continues onto another thread. Based on the two or three different AsyncLock's that I've seen, configuring the continuation onto another thread (within the lock body) does not change the lock at all. In that case, the continuation would access the data from a different thread than the thread that obtained the lock. If we have re-entered the lock then potentially we could have two continuations on different threads both accessing the data -- obviously a problem.  What would probably make more sense would be for the continuation to obtain a lock on it's thread for the continuation, and drop the lock on the old thread. Obviously this would have to be done atomically in order to preserve consistency. The net effect would be that the lock would migrate threads along with the continuation. Hopefully the compiler can deal with moving the lock onto a new thread at the same time that it deals with moves the continuation onto a new thread.  

This kind of complexity (4) might be the reason why some AsyncLock's are semaphore-based only, i.e. are not thread-specific and do not allow thread re-entrancy. However I feel the purely semaphore-based approach does create more coding challenges because of the need to avoid calling locking methods from other locking methods -- in my experience this means that public methods cannot call other public methods. Another way to describe this drawback of semaphore-based locking is that when you have a mix of sync and async methods in your class, the sync methods have to synchronously obtain the lock and this instantly leads to deadlock if one locking function calls another. In addition there is also the language design issue: it makes more sense for the sync and async locking mechanisms to be similar with respect to thread re-entrancy.

**Comment by yaakov-h** [comment]
@sjb-sjb 

> Await will only send the continuation to a different thread if you configure await to do so.

This is false. It all depends on the current `SynchronizationContext`. In many applications such as console apps, all continuations are thrown on the Thread Pool by default.

> I am just suggesting that awaiting a thread lock is not a situation where you then want to continue on a different thread.

You might want to continue on the same thread that just released the lock, to avoid further rescheduling of the work.

> Hopefully the compiler can deal with moving the lock onto a new thread

This would have to be up to the runtime / BCL, not the compiler.

I don't think there's anywhere for this proposal to go without a clear design and BCL implementation of your desired locking mechanism.

**Comment by sjb-sjb** [comment]
@yaakov-h Thanks for your excellent comment, that await continues on the same SynchronizationContext rather than the same thread. 

As relates to an await occurring within the lock body, what this means is that the lock may migrate to a new thread even if ConfigureAwait(false) is not specified. However I think my comments about migrating the lock to the continuation thread still apply. 

As relates to the continuation of the await lock itself, presumably this also will execute on a thread taken from the captured SynchronizationContext (or default context). So, when we have obtained the lock using an await, then we should immediately migrate the lock to the thread on which the await is continuing.  Again, though, I don't think that we need a syntax for continuing onto a different thread than that one. 

On your comment about the need for a clear design, my purpose in opening the discussion was to design the language feature in collaboration with the community.

**Comment by sjb-sjb** [comment]
P.S. The purpose of lockObject from a semantic point of view is just to identify the lock. What the compiler and runtime use it for is a different matter, I am happy to defer to the Roslyn contributors as to the best way to implement.

**Comment by HaloFour** [comment]
There is only one locking mechanism that the C# compiler is aware of and that is the one built into the CLI via `System.Threading.Monitor`.  That is what the `lock` keyword relies on to function.  Even if the various other synchronization classes exist in various versions of the framework there's no guarantee to the compiler that they will be there.

For something like asynchronous locking to work you'd need a couple of enhancements to `Monitor`.  First you'd need a method to "park" a lock where it remains acquired but not owned by any thread.  Second you'd need a method to re-acquire that lock, potentially from another thread.  To do this "securely" you'd need some "cookie" value that you can obtain when "parking" the lock which would be required in order to re-acquire that lock.  Then the C# compiler could "park" the lock when it wires up a continuation and re-acquire the lock within that continuation.  One giant glaring problem with all of that is that the C# compiler has no idea what locks the current thread has acquired so this method would require that literally every wired continuation check for locks, "park" them and reacquire them.

I do have a big philosophical problem with a proposal such as this.  It's expected that an asynchronous operation will be fairly long-lived and holding a lock for a long duration somewhere where you expect contention is probably not a very good idea.  There are special cases where this is expected, such as with initialization of a common resource which must be done asynchronously, but I think that it's perfectly sufficient to manage that with such helper classes as `Lazy<Task<T>>` today.

**Comment by yaakov-h** [comment]
@HaloFour There are really two parts to this:

1. Ability to `await` the acquisition of a lock
2. Ability to `await` while holding a lock

I agree with the philosophical problem of the second, but I don't see anything wrong with the first.

**Comment by HaloFour** [comment]
How you describe `async lock` doesn't seem possible.  It not feasible for the current thread to be the continuation thread of the block.  That thread has already returned control to the calling method and is doing something else.  The only way to force the current thread to be the continuation thread would be to block it for the duration of time that you're waiting for the lock to be acquired.  You can't have both "asynchrony" and "affinity", they are mutually exclusive propositions.

 @jnm2 

> because every `await` bounces the work to a random threadpool thread.

Technically the C# compiler is completely (and blissfully) ignorant as to where that continuation thread came from, just as long as it happens to call the `Action` delegate passed to `OnCompleted`/`OnUnsafeCompleted`.

@yaakov-h 

> but I don't see anything wrong with the first.

It's an interesting concept, but it's not one that works with any of the locking mechanisms that exist today.  They all rely on thread ownership and that is incompatible with how `async`/`await` works (and was designed to work).

**Comment by benaadams** [comment]
It would be very easy to create race conditions as both `t1` and `t2` could simultaneously run with the lock for below
```csharp
await lock (lockObject) { 
    var t1 = DoThing(); 
    var t2 = DoThing();
    await Task.WhenAll(t1, t2);
}

Task async DoThing()
{
    await Task.Delay(rnd.NextDouble() * 300);
    _amount = _amount + 1;
}
```

**Comment by yaakov-h** [comment]
@benaadams You can already do that today with `Task.WaitAll` or threads or just about anything, really.

**Comment by sjb-sjb** [comment]
@benaadams  I agree that is a race condition, but I am not sure that it is a case where we need the await within the lock. One could just use a synchronous lock: 

     Task DoTwiceAsync() {
        t1 = DoOnceAsync();
        t2 = DoOnceAsync();
        await Task.WhenAll( t1, t2);
     }

     private Task DoOnceAsync() {
        await Task.Delay( rnd.NextDouble() * 300);
        lock (this._lockObject) { this._amount += 1; }
     }

Concerning the philosophical problem, if some aspects of the original suggestion don't make sense then the challenge is to define what kind of locking does make sense in the async context. Clearly the answer isn't "none" since there are so many postings out there about various ways to do it. We need to take the best practice and wrap some syntax around it. 

I will try to put together a good use case and post it.

**Comment by benaadams** [comment]
Its the concurrency issue with `async` I'm highlighting. With sync its always one straight execution path - however async can split to multiple concurrent execution paths; so how does the lock "owner" propagate correctly? As the multiple paths would all think they had the lock

**Comment by yaakov-h** [comment]
Lock ownership already fails in a similar manner if you spawn parallel asynchronous work while holding the lock.

```
void DoTwiceSync()
{
    lock (lockObject)
    {
        var t1 = DoOnceAsync();
        var t2 = DoOnceAsync();
        Task.WaitAll(t1, t2);
    }
 }

async Task DoOnceAsync()
{
    await Task.Delay(rnd.NextDouble() * 300);
    _amount = _amount + 1;
}
```

This proposal doesn't solve it, but doesn't exactly break/cause it either.

**Comment by benaadams** [comment]
@yaakov-h yes; but `.Wait` `.Result` `.WaitAll` etc have lots of other associated problems; threadpool starvation, UI locking, deadlock if on a custom scheduler or message pump etc 

So should be exceptional use rather than common use; and `lock` prevents `await`ing in it as it won't behave in an expected manner.

The issue I have with the proposal is the re-entrancy; which I think is the core proposition and what it would mean to have the lock.

I suppose the example would express it better written as:
```csharp
await lock (lockObject) { 
    var t1 = DoThing(); 
    var t2 = DoThing();
    await Task.WhenAll(t1, t2);
}

Task async DoThing()
{
    await Task.Delay(rnd.NextDouble() * 300);
    // can this possibly be re-entrant?
    await lock (lockObject) { 
        _amount = _amount + 1;
    }
}

**Comment by benaadams** [comment]
@yaakov-h yes; but `.Wait` `.Result` `.WaitAll` etc have lots of other associated problems; threadpool starvation, UI locking, deadlock if on a custom scheduler or message pump etc 

So should be exceptional use rather than common use with `await`, `WhenAll` etc being the preferred approach; and `lock` prevents `await`ing in it as it won't behave in an expected manner.

The issue I have with the proposal is the re-entrancy; which I think is the core proposition and what it would mean to have the lock.

I suppose the example would express it better written as:
```csharp
await lock (lockObject) { 
    var t1 = DoThing(); 
    var t2 = DoThing();
    await Task.WhenAll(t1, t2);
}

Task async DoThing()
{
    await Task.Delay(rnd.NextDouble() * 300);
    // can this possibly be re-entrant?
    await lock (lockObject) { 
        _amount = _amount + 1;
    }
}
```
It suggests guarantees I'm not sure it could have; for the general case?

It would be nice to have; however I'm not sure I entirely grasp the semantics for safe re-entrancy

**Comment by sjb-sjb** [comment]
Here is the first of two use case examples. Please bear with me as this is obviously very simplistic compared to real-world code.  

In this example one could easily use a semaphore; in other words the "await lock" doesn't involve any re-entrancy. All we are trying to do is maintain consistency so that the state that is input to the awaited operation (in this case await SaveChangesAsync) is not messed up during the operation and therefore can be updated appropriately after the awaited operation. 

There are both sync and async uses of the lock because the public surface has both sync and async methods. If you have a lot of methods in the class and you use semaphores then you have to spend time making sure that no locking method is invoked from any other locking method, and this can result in having to create additional private methods just to omit the locking step. If you had a re-entrant lock mechanism then it would make your life a bit easier. 

    public class Entities<TDbContext,TEntity> where TDbContext: DbContext where TEntity: class
    {
        private List<TEntity> ExistingPage = null;
        private List<TEntity> AddedEntities = new List<TEntity>();
        private TDbContext Context = null;
        private object LockObject = new object();

        public async Task LoadExistingPageAsync(...)
        {
            await lock (this.LockObject) {
                using (var context = new TDbContext()) {
                    this.ExistingPage = await context.Set<TEntity>().ToListAsync(); // load entities from disk
                }
            }
        }

        public void SetPropertyValue( TEntity entity, string propertyName, object value)
        {
            lock (this.LockObject) {
                entity.GetType().GetProperty(propertyName).SetValue(entity, value);
                if (entity.IsDirty) {
                    this.Context = this.Context ?? new TDbContext();
                    this.Context.Add(entity);
                }
                bool isInPage = this.ExistingPage?.Contains(entity) ?? false;
                if (!isInPage) { 
                    this.AddedEntities.Add(entity);
                }
            }
        }

        public async Task SaveAsync()
        {
            await lock (this.LockObject) {
                if (this.Context == null) { return; }
                await this.Context.SaveChangesAsync();
                if (this.ExistingPage != null) {
                    foreach (var savedEntity in this.AddedEntities) {
                        this.ExistingPage.Add(savedEntity); 
                    }
                }
                this.Context.Dispose();
                this.Context = null;
                this.AddedEntities.Clear();
            }
        }
    }

**Comment by sjb-sjb** [comment]
I have given up on the second example, which was meant to show the need for re-entrancy, in other words something that could not be really done without thread re-entrancy. But the thing is, if your design is going to allow re-entrancy on the same thread during an asynchronous operation, then from a design point of view you probably would allow the re-entrancy from any thread ... in other words, you could just release the lock during the awaited operation. 

So at this point I would say re-entrancy for async locks would be primarily a convenience in a class containing mixed sync/async code. With re-entrancy, you can call a synchronous method from within another method, without having to figure out whether there is a lock buried somewhere in the synchronous method. What I would point out, however, is that this is pretty much all the value there is to re-entrancy for synchronous locks. Whether done synchronously or asynchronously, you will probably have a bug if you think you have obtained a lock but then you call into user/application code that then calls back into your class. 

The following code illustrates how similar the design issues are between the sync and async cases.

Here is the sync version.

    public class SyncCallbacks
    {
        private List<Action> _callbacks = new List<Action>();
        private object _lockObject = new object();

        public void Add( Action action)
        {
            lock (this._lockObject) {
                this._callbacks.Add(action);
            }
        }
        public void Cleanup()
        {
            lock (this._lockObject) {
                ... 
                this._callbacks.Clear();
                ... 
            }
        }
        public void Invoke()
        {
            lock (this._lockObject) {
                foreach (var callback in this._callbacks) {
                    callback(); // bug! user code can call back into Add.
                }
                this.Cleanup(); // convenient!
            }
        }
    }

The exact same issues / conveniences show up in the async version: 

    public class AsyncCallbacks
    {
        private List<Func<Task>> _callbacks = new List<Func<Task>>();
        private object _lockObject = new object();

        public void Add(Func<Task> actionAsync)
        {
            lock (this._lockObject) {
                this._callbacks.Add(actionAsync);
            }
        }
        public void Cleanup()
        {
            lock (this._lockObject) {
                ... 
                this._callbacks.Clear();
                ... 
            }
        }
        public async Task InvokeAsync()
        {
            await lock (this._lockObject) {
                foreach (var callbackAsync in this._callbacks) {
                    await callbackAsync(); // bug! user code can call back into Add.
                }
                this.Cleanup(); // convenient!
            }
        }
    }

**Comment by sjb-sjb** [comment]
So where does this leave us? If we ditch the re-entrancy then the "await lock" is far simpler and probably just as useful; on the other hand it then would be inconsistent with the existing synchronous "lock" semantics.

**Comment by sjb-sjb** [comment]
I think the conclusion is that, although it might be cool to have better language support for exclusive access / non-re-entrant locks / semaphores, the "lock" keyword is not an appropriate for this purpose because "lock" is already associated with re-entrancy. Consequently, if we were to introduce language support for exclusive access / semaphores then it would require either a new keyword or some really creative use of existing keywords. 

I'd say give up on this, at least for the time being.

**Comment by jnm2** [comment]
@HaloFour 

> Technically the C# compiler is completely (and blissfully) ignorant as to where that continuation thread came from, just as long as it happens to call the Action delegate passed to OnCompleted/OnUnsafeCompleted.

Yes. I was only making a point. =)

**Comment by benaadams** [comment]
@sjb-sjb you may want to check out https://blogs.msdn.microsoft.com/pfxteam/2012/02/12/building-async-coordination-primitives-part-6-asynclock/

**Comment by sjb-sjb** [comment]
Yes, I've been using something like that. My idea was we should have done language support. But I am not sure how to resolve the fact that "lock" in c# allows re-entrancy while allowing re-entrancy in the async case causes all kinds of problems. Arguably "lock" should not allow re-entrancy but it is hard to change that at this point.

**Comment by CyrusNajmabadi** [comment]
it's not clear to me why we need any special language support here.  Take a look at https://github.com/dotnet/roslyn/blob/878ffad23b8b06cb229c9ab31eada7634a473508/src/Workspaces/Core/Portable/Utilities/ValuesSources/CachedWeakValueSource.cs#L58 as an example of how roslyn achieves async critical section acquisition (without reentrancy) in a simple and clean manner.

**Comment by sjb-sjb** [comment]
@CyrusNajmabadi From a technical point of view, I like the solution you pointed out. However I don't think the syntax ("using (await Gate.DisposableWaitAsync(cancellationToken).ConfigureAwait(false))") is easy enough. 

We do have a simple syntax with the "lock" keyword, it's just that it is pretty much useless now that so much of everyone's code is async.

**Comment by sjb-sjb** [comment]
Concerning the re-entrancy dilemma discussed earlier, I tend to think that re-entrancy under the existing "lock" keyword is not doing anyone much good. When re-entrancy occurs it usually means either (a) convenience for the programmer who is calling one of their locking functions from another locking function; or (b) a programming bug. 

So if we are not too concerned about (a) then maybe the solution is to keep the "lock" keyword but revise the semantics to be really locking (i.e. semaphore-like semantics). Obviously we would want to do this in a way that would avoid breaking existing code. For example, if the lock object is declared with "lock myLock;" then the use of "lock (myLock) {...}" would mean semaphore-based locking. Then "await lock (myLock) {...}" would be the async version. 

What do people think of that idea?

**Comment by HaloFour** [comment]
@sjb-sjb

I think it still suffers from the problems around lock ownership and concurrency which you've not addressed.  Thread-based locking is simply incompatible with `async` methods.

Also, why should the `lock` keyword be extended for this case when it's not used for any other synchronization mechanism, synchronous or otherwise?  C# 1.0 didn't suffer for it.  I think to change the meaning of `lock` now would just be confusing, especially if it was reentrant in one situation but not in others.

**Comment by sjb-sjb** [comment]
Well, "await lock (myLock) {...}" would basically mean "using (await myLock.WaitAsync()) {...}" with myLock being a SemaphoreSlim(1,1). I don't see any problem with that. One could have variants for continuation although personally I don't think the continuation options are needed.

**Comment by jnm2** [comment]
> However I don't think the syntax ("using (await Gate.DisposableWaitAsync(cancellationToken).ConfigureAwait(false))") is easy enough.

I don't see that at all.

> We do have a simple syntax with the "lock" keyword, it's just that it is pretty much useless now that so much of everyone's code is async.

I use it just as much as ever. At this point I'm pretty sure you're conflating two kinds of task.

**Comment by sjb-sjb** [comment]
What two kinds? I'm not confusing Tasks and threads if that's what you mean.

**Comment by jnm2** [comment]
The kind of task where you need thread synchronization, and just as importantly memory barriers, and the kind of task where you just need to queue async operations.

**Comment by scalablecory** [comment]
`lock` is guaranteed to unlock if a thread is aborted. Something based on `using` has no such guarantee.

I know abort is a dirty word and we like to pretend it doesn't happen most of the time, but figured it deserves a mention as we'd be changing a standard safety feature of `lock`. There is precedence here, as I believe async has already broken abort guarantees for `finally`.

**Comment by sjb-sjb** [comment]
@jnm2 No, I agree those are distinct problems. I'm not suggesting to get rid of the current "lock" semantics, which is needed for thread synchronization and memory integrity. I'm suggesting to add to the language with an additional kind of lock. The difference between the two kinds would be indicated by different declarations ("object myLock = ..." for the current kind of lock and "lock myLock = ..." for the new kind). 

@scalablecory  Just before your comment, I edited my comment to sneak in the word "wrapper". The wrapper is an IDisposable struct that releases the lock when the wrapper is disposed. So if you blow out of the "using" then the wrapper is disposed and the lock is released. (BTW, the fact that it is a struct does not lead to boxing when used with "using").

**Comment by CyrusNajmabadi** [comment]
> However I don't think the syntax ("using (await Gate.DisposableWaitAsync(cancellationToken).ConfigureAwait(false))") is easy enough.

What is your proposal then? :)

**Comment by CyrusNajmabadi** [comment]
> Well, "await lock (myLock) {...}" would basically mean "using (await myLock.WaitAsync())

How do i indicate cancellation?  Or that i want ConfigureAwait(false)?

**Comment by scalablecory** [comment]
@sjb-sjb It's an inherent flaw in the way `using` is transformed, not something you can work around. Imagine:

```
using(var foo = bar())
{
}
```

translates to:

```
var foo = bar();
try
{
}
finally
{
	foo.Dispose();
}
```

Now, `ThreadAbortException` throws right before `try` is entered.

The "safe" way to do abort-safe `using` would require a translation into something like:

```
bool init = false;
TDisposable disp;

try
{
	try {}
	finally
	{
		disp = CreateDisposable();
		init = true;
	}
	
	///
}
finally
{
	if(init) disp.Dispose();
}
```

**Comment by CyrusNajmabadi** [comment]
> On the synchronous side, "lock (myLock) {...}" would mean "using (await myLock.Wait())) {...}".

Something about htat doesn't make sense :)

**Comment by CyrusNajmabadi** [comment]
> However I don't think the syntax ... is easy enough.

I disagree.  It's fairly simple, and addresses the primary concerns around async (cancellation, configureawait).  You can also extend it through normal extension methods.  For example, i could have other extensions allowing me to do:

```using (await gate.WaitAsync(false))``` or
```using (await gate.WaitAsync(cancellationToken, false))```

Your proposal is to have:

```await lock (gate)```

That's just not enough of an improvement over:

```using (await gate.WaitAsync())```

Why do we need such specialized syntax?

**Comment by sjb-sjb** [comment]
@CyrusNajmabadi Ooops... I've edited out the extra "await". As for why have this feature, it's a reasonable question, but as it is today everyone has to write or acquire a bunch of wrapper code. Also see the somewhat subtle problem identified by @scalablecory. 

@scalablecory Well, I see the point, and it does look like a potential bug in the current wrapper approach. I am not sure what all of the conditions are that could cause an exception (of any type) after the SemaphoreSlim lock acquisition but before the using block is entered. I'd be interested in hearing any thoughts that @StephenCleary might have on this. Presumably the compiler would have to deal with this somehow. I'm not clear on how to do it -- can another ThreadAbortException occur during the cleanup code in the finally block, for example?

**Comment by CyrusNajmabadi** [comment]
> but as it is today everyone has to write or acquire a bunch of wrapper code.   

Adding a language feature to avoid having to write a small extension once in your codebase isn't really valuable.  If there was a large tax you incurred all over your code for this, that would be different.

**Comment by CyrusNajmabadi** [comment]
> Presumably the compiler would have to deal with this somehow

The jit would have to do it.  Right now is special cases the code that hte compiler emits for Monitor.Enter.

**Comment by CyrusNajmabadi** [comment]
>  Also see the somewhat subtle problem identified by @scalablecory.

The subtle problem *always* has to be handled by the jit.  It can't be handled by the c# language or compiler.  There is no code we can generate that will be safe against the abort.  For example, say you have:

```
object o;
try {
    o = foo();
}
finally {
    // what can i do here?
}
```

It may be the case that the abort happens right after 'foo' executes, but before the assignment even happens to 'o'.  

Writing thread-abort-safe code is enormously difficult (to the point that i personally don't think it's even worth it).

**Comment by sjb-sjb** [comment]
Concerning the earlier comments from @benaadams and @HaloFour on the problems of thread ownership of an async lock, what I now suggest is that the lock not be owned by a specific thread (or task for that matter). It would just be a plain old semaphore, basically.

**Comment by scalablecory** [comment]
> The subtle problem always has to be handled by the jit. It can't be handled by the c# language or compiler. There is no code we can generate that will be safe against the abort.

@CyrusNajmabadi that is untrue. The code I wrote is safe against abort and however convoluted is the "standard" way to handle it. It's possible, just not practical outside of very specific controlled situations.

Does anyone know if the TPL even has any defined behavior around a thread abort? It might all be a moot point.

**Comment by jnm2** [comment]
@sjb-sjb 

> No, I agree those are distinct problems. I'm not suggesting to get rid of the current "lock" semantics, which is needed for thread synchronization and memory integrity. I'm suggesting to add to the language with an additional kind of lock. 

And my point is, because they are distinct problems, we shouldn't reuse the `lock` statement and make it act with two different sets of semantics based on whether `await` appears inside. or the lock object is a special type. Existing library options provide more clarity than changing the language IMO.

**Comment by sjb-sjb** [comment]
@jnm2 that's a valid point of view. Personally I happen to feel that locking is needed often when we have async code -- since we are in an async environment where presumably multiple overlapping requests can arrive. My gut feeling is maybe 30% of the time we need locking that prevents re-entrancy. To me that's enough to warrant a language feature ... certainly when you compare it to some things that we have special syntax for, like --i vs i--. 

About reusing the "lock" keyword, it's not totally unintuitive ... "lock myLock;" does seem a bit more forceful than "object mylock;", which is more or less aligned to the stronger type of locking involved. I'm sure some people will get mixed up, but those people probably don't have a great understanding of threads and the difference between thread locks vs semaphores in the first place. 

Anyway I am open to other syntax suggestions.

**Comment by HaloFour** [comment]
@sjb-sjb 

From what it sounds like no language features are necessary to accomplish these goals.  The use of existing language constructs produces a fairly concise result.  What's more important is that issues of policy control are left to library authors and developers to decide, not the language.  Issues like reentrancy, timeouts, cancellation, continuation and synchronization can be managed individually through a plethora of existing syntax options.  That wouldn't be possible with a language feature as you describe.

At the *very* least any such language feature would have to support cancellation and configuration of synchronization context.  How do you propose wrapping that up in `lock` without it becoming a mess?

**Comment by scalablecory** [comment]
Most people don't have complex lock schemes... it's just one lock guarding one thing.

I feel like for this situation, work queues are often more appropriate for an async workload than locks. They just fit so cleanly into async. A simple interface I've used is something like `asyncLock.Perform(Func<Task>)`.

More complex situations are too rare to need a keyword.

**Comment by sjb-sjb** [comment]
@scalablecory's example is equally appealing as locking. I find it convincing, it wouldn't make sense to commit the language to async locks when async work queues are just as good.

**Comment by StephenCleary** [comment]
I'm late to the party here, but since I was pinged for comment, my comment is:

[I'm philosophically opposed to recursive/reentrant locks in general](https://blog.stephencleary.com/2013/04/recursive-re-entrant-locks.html). I assume `lock` is only recursive because "it's always been done that way" or "the Win32 mutex is" or "Java's `synchronized` did it that way", as opposed to an actually *good* reason. If an `await lock` were to be added, I would recommend it *not* be recursive.

**Comment by sjb-sjb** [comment]
Well, I agree with @StephenCleary about the value of non-re-entrant locks. In addition I feel that async locking is important enough to deserve its own language feature. I recently posted about the need to adapt other language flow-of-control features to make them more functional under the async / await paradigm. See issue #114 on Oct 22, 2017. The issue relates to how to adapt the 'using' / IDispose flow-of-control statement to the async / await paradigm.

**Comment by BrunoZell** [comment]
As alternative you can currently do

```csharp
using (await _enumerationSemaphore) {
    // do multithread-critical stuff here
}

```

With these extension methods:

```csharp
public static class SemaphoreSlimExtensions
{
    public static TaskAwaiter<DisposableReleaser> GetAwaiter(this SemaphoreSlim semaphoreSlim) =>
        semaphoreSlim.LockAsync().GetAwaiter();

    public static async Task<DisposableReleaser> LockAsync(this SemaphoreSlim semaphoreSlim, CancellationToken cancellationToken = default)
    {
        await semaphoreSlim.WaitAsync(cancellationToken);
        return new DisposableReleaser(semaphoreSlim);
    }

    public readonly struct DisposableReleaser : IDisposable
    {
        private readonly SemaphoreSlim _semaphore;

        public DisposableReleaser(SemaphoreSlim semaphore) =>
            _semaphore = semaphore;

        public void Dispose() =>
            _semaphore.Release();
    }
}
```
