### ISSUE TITLE
?() operator for delegates and events

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/csharplang#984]
Delegates invoking and event raising with null checking have become `?.Invoke()`.
`?()` would looks better.

**Comment by ufcpp** [comment]
dup of https://github.com/dotnet/csharplang/issues/261

**Comment by huoyaoyuan** [comment]
Thanks for reminding.
The ambiguity seems resolvable, but maybe adding much overhead I think.
Closing because it already considered.
