### ISSUE TITLE
one to many assignment (batch assignment)

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#987]
allow to set single variable to many variables like this.

 - return type of expression must have implicit cast for all variables. 
 - statement can declare new variables or can use existing variables
 - ref assignment will cause all variables to reference same thing.

examples for value and reference assignments.
```
// distinct type declaration and single assignment.
(int x, int y, int z, double w) = 0; 

// both will reference same Foo.
(Foo x, Bar y) = new Foo(); // only works if Foo inherits Bar or has implicit cast defined.

// implicit type declaration.
var (x, y) = 0; 
var (x, y) = new Foo();

// one to many assignment.
(x, y) = 0;

// assume param and item[5] have implicit cast (but are not same type)
(item[5], param) = new Foo(); // useful when indexer access time is not O(1)
```

**side effects:**

this assignment should not have side effects. for example the following statement will call Foo only once.

    (x, y) = GetFoo();

side proposal: 
many to one assignment is also possible. but that requires construct methods stated in #941

**Comment by orthoxerox** [comment]
#973 should cover that via `double w = int x = int y = int z = 0;`

**Comment by sharwell** [comment]
:memo: This syntax overlaps with deconstructing assignments. Technically all of the above are already possible as long as the user is willing to write a variety of extension methods.

For an example in Roslyn, see this: https://github.com/dotnet/roslyn/blob/4011656d468e44c4b0dbb50d7991c2bd42ae66f6/src/Compilers/Core/Portable/InternalUtilities/KeyValuePair.cs#L14-L18

**Comment by jnm2** [comment]
`= default` already works in two of the `= 0` examples today. `= 1` is a better illustration.

**Comment by DavidArno** [comment]
Deconstructors can be used to support all use cases in the OP's examples. Just add the follow code to your project in some way:
```cs
static class MultipleAssignmentDeconstructs
{
    public static void Deconstruct<T>(this T value, out T a, out T b) =>
        (a, b) = (value, value);
    public static void Deconstruct<T>(this T value, out T a, out T b, out T c) =>
        (a, b, c) = (value, value, value);
    public static void Deconstruct<T>(this T value, out T a, out T b, out T c, out T d) =>
        (a, b, c, d) = (value, value, value, value);

}
```

**Comment by MkazemAkhgary** [comment]
@DavidArno good to know, I missed that.
@orthoxerox that sounds interesting it will covert this indeed.
