### ISSUE TITLE
Improve generic type parameters inference.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#997]
When a generic type parameter is constrained with other generic parameters, it is possible to infer both types from constrained generic type. (currently not supported by compiler)

```
public static Foo<TBar, T> AsFoo(this TBar bar) where TBar : IBar<T>
{
     return new Foo<TBar, T>(bar);
}
```

when calling this.

```
var foo = bar.AsFoo(); // type parameters can not be inferred.
```

but It should be inferred, because information about `T` already exist in constraint for TBar here ` where TBar : IBar<T>`

**Comment by khellang** [comment]
Related/duplicates: https://github.com/dotnet/csharplang/issues/110, https://github.com/dotnet/csharplang/issues/478, https://github.com/dotnet/csharplang/issues/741, https://github.com/dotnet/roslyn/issues/5023 and https://github.com/dotnet/roslyn/issues/15166.

There's even PRs where this work was already done: https://github.com/dotnet/roslyn/pull/6644 and https://github.com/dotnet/roslyn/pull/7850.

**Comment by bbarry** [comment]
[This unfortunate observation](https://github.com/dotnet/roslyn/pull/7850#issuecomment-170154270) describes the problem with doing this:

Suppose you have these methods:

```csharp
public static Foo<string, char> AsFoo(this object bar) =>
    new Foo<string, char>(bar);
public static Foo<TBar, T> AsFoo(this TBar bar) where TBar : IEnumerable<T> =>
    new Foo<TBar, T>(bar);
```

this call would change:

    var foo = bar.AsFoo();

**Comment by benaadams** [comment]
And if it didn't I'm not sure you could implement ValueLinq without creating all new `List<T>` etc classes

As
```csharp
public static int Count<TSource>(this IEnumerable<TSource> source)
```
Would take precedence over
```csharp
public static int Count<TEnumerable, TEnumerator, TSource>(this TEnumerable source)
    where TEnumerable : struct, IValueEnumerable<TSource, TEnumerator>
    where TEnumerator : struct, IValueEnumerator<TSource>
```
(Ideally I'd like the `struct` constraint to give a boost in matching)

**Comment by gafter** [comment]
@agocke is investigating extending type inference to take constraints into account.

**Comment by benaadams** [comment]
From: https://github.com/dotnet/csharplang/issues/982#issuecomment-397198667

The main issue is lack of inference of generic arguments based on constraints so you need to do:
```csharp
list.Any<List<int>, List<int>.ValueEnumerator>();
list.Count<List<int>, List<int>.ValueEnumerator>();
```
Rather than
```csharp
list.Any();
list.Count();
```
To resolve
```csharp
public static int Count<TSource, TValueEnumerator>(this TSource source)
    where TSource : IValueEnumerable<TValueEnumerator>
    where TValueEnumerator : struct, IValueEnumerator
```

However, running a perf test for a "ValueLinq" https://gist.github.com/benaadams/294cbd41ec1179638cb4b5495a15accf

```
    Method | Categories |      Mean |     Error |    StdDev | Scaled | Allocated |
---------- |----------- |----------:|----------:|----------:|-------:|----------:|
      Linq |        Any | 16.718 ns | 0.0615 ns | 0.0480 ns |   1.00 |     320 B |
 ValueLinq |        Any |  8.241 ns | 0.0286 ns | 0.0253 ns |   0.49 |       0 B |
           |            |           |           |           |        |           |
      Linq |      Count | 69.538 ns | 0.3562 ns | 0.2781 ns |   1.00 |      32 B |
 ValueLinq |      Count | 35.665 ns | 0.1095 ns | 0.0970 ns |   0.51 |       0 B |
```
Its twice as fast and cuts allocations to zero

**Comment by agocke** [comment]
My summary here: the break is real, but much of the annoyance is around inference *failure* -- when there are no other suitable overloads, but the compiler still fails to properly infer your generic arguments.

I think the only way to deal with that is re-do overload resolution after an inference failure, this time taking constraints into account. This could be expensive, so we would have to decide whether that's something we want to do, or whether we can accept some overload resolution breaking changes.

**Comment by Joe4evr** [comment]
Code depending on compiler options creates a dialect, and the Language Design Team has been hard at work for the past 15+ years to keep dialects as far away from the language as possible.

**Comment by bahusoid** [comment]
I'm also suffering from this issue:

```C#
public interface IQuery<TResult> {}
public static class Extensions
{
	public static TQuery AdjustQuery<TQuery, TResult>(this TQuery query) where TQuery : IQuery<TResult>
	{
		//...
		return query;
	}
}

IQuery<int> q = GetQuery();
q.AdjustQuery(); // <- Doesn't compile. Need to call explicitly:
q.AdjustQuery<IQuery<int>,int>(); // Works but very ugly
```

And as a workaround I'm currently using the following constructs:

```C#
public static TQuery AdjustQuery<TQuery, TResult>(this TQuery queryThis, IQuery<TResult> query) where TQuery : IQuery<TResult>
{
	//... call query methods
	return queryThis;
}
//OR
public static TQuery AdjustQuery<TQuery, TResult>(this TQuery queryThis, Func<TQuery, IQuery<TResult>> getQuery ) where TQuery : IQuery<TResult>
{
	var query = getQuery(queryThis);
	//... call query methods
	return queryThis;
}

var q = GetQuery();
q.AdjustQuery(q);// <-- parameter duplication to avoid explicit type declaration
//OR
GetQuery().AdjustQuery(x => x);
```

It works but that parameter duplication looks a bit hacky and unnecessary.

So if such type inference can't be implemented in the near future (which seems to be the case as suggested pr https://github.com/dotnet/roslyn/pull/7850 is closed long time ago)  I'm asking to implement some syntactic sugar that will simplify writing and using such methods. Maybe support the following declaration:
 ```C#
public static TQuery AdjustQuery<TQuery, TResult>(this TQuery queryThis, IQuery<TResult> query = queryThis) where TQuery : IQuery<TResult>
```
So caller can avoid providing `query` parameter explicitly.

**Comment by Ultrahead** [comment]
https://github.com/dotnet/roslyn/pull/7850#issuecomment-477815307

**Comment by QXD-me** [comment]
@agocke I know it’s been a while on this issue. But does expensive in this case mean in terms of compilation time or expense of dev time to implement?
If it is compilation time that’s at stake isn’t code usually “mostly working” I.e. only the bit you’re working on is broken, so there shouldn’t be that many methods that need rechecking? I guess maybe if someone renames a method without using the refactor tool there might be more?
(I’m not familiar with the compiler internals, so please forgive my ignorance if what I’m saying is dumb)
