### ISSUE TITLE
Type of implementing class used in interface

### ISSUE THREAD

**Issue by drozdekl** [dotnet/csharplang#998]
There is not currently any possibility to express type of implementing class in interface. I am newbie in C# so there is maybe trivial reason why there is not anything like `that` keyword in the language so it would be great if you could make it clearer for me.

I have made an example of what it could look like. Firstly the code which is currently working:
```csharp
interface IPlus<T> {
	T Plus(T other);
}

struct MyInt : IPlus<MyInt> {
	public MyInt(int value) {
		Value = value;
	}

	public MyInt Plus(MyInt other) =>
		new MyInt(Value + other.Value);

	public int Value { get; }
}

struct Complex<T> : IPlus<Complex<T>> where T : IPlus<T> {
	public Complex(T re, T im) {
		Re = re;
		Im = im;
	}

	public Complex<T> Plus(Complex<T> other) =>
		new Complex<T>(Re.Plus(other.Re), Im.Plus(other.Im));

	public T Re { get; }
	public T Im { get; }
}
```
It is not possible to express that every class implementing `IPlus<T>` should be exactly of type `T`. More specifically `T : IPlus<T>` was meant to be OK but for example `T : IPlus<int>` should be error.

The `that` keyword would take away type parameter. I think that the code with `that` would be much clearer.

```csharp
interface IPlus {
	that Plus(that other);
}

// that ~ MyInt
struct MyInt : IPlus {
	public MyInt(int value) {
		Value = value;
	}

	public MyInt Plus(MyInt other) =>
		new MyInt(Value + other.Value);

	public int Value { get; }
}

// that ~ Complex<T>
struct Complex<T> : IPlus where T : IPlus {
	public Complex(T re, T im) {
		Re = re;
		Im = im;
	}

	public Complex<T> Plus(Complex<T> other) =>
		new Complex<T>(Re.Plus(other.Re), Im.Plus(other.Im));

	public T Re { get; }
	public T Im { get; }
}
```

**Comment by jnm2** [comment]
Sounds like you want https://github.com/dotnet/csharplang/issues/169?
